dico("A", 5, "ABACA").
dico("A", 5, "ABATS").
dico("A", 5, "ABBES").
dico("A", 5, "ABCES").
dico("A", 5, "ABDOS").
dico("A", 5, "ABEES").
dico("A", 5, "ABERS").
dico("A", 5, "ABETI").
dico("A", 5, "ABIES").
dico("A", 5, "ABIMA").
dico("A", 5, "ABIME").
dico("A", 5, "ABLES").
dico("A", 5, "ABOIE").
dico("A", 5, "ABOIS").
dico("A", 5, "ABOLI").
dico("A", 5, "ABORD").
dico("A", 5, "ABOTS").
dico("A", 5, "ABOUT").
dico("A", 5, "ABOYA").
dico("A", 5, "ABOYE").
dico("A", 5, "ABRAS").
dico("A", 5, "ABRIA").
dico("A", 5, "ABRIE").
dico("A", 5, "ABRIS").
dico("A", 5, "ABUSA").
dico("A", 5, "ABUSE").
dico("A", 5, "ABUTA").
dico("A", 5, "ABUTE").
dico("A", 5, "ABYME").
dico("A", 5, "ACCES").
dico("A", 5, "ACCON").
dico("A", 5, "ACCOT").
dico("A", 5, "ACCRO").
dico("A", 5, "ACCRU").
dico("A", 5, "ACCUL").
dico("A", 5, "ACCUS").
dico("A", 5, "ACERA").
dico("A", 5, "ACERE").
dico("A", 5, "ACHAT").
dico("A", 5, "ACHEB").
dico("A", 5, "ACHES").
dico("A", 5, "ACIDE").
dico("A", 5, "ACIER").
dico("A", 5, "ACINI").
dico("A", 5, "ACMES").
dico("A", 5, "ACNES").
dico("A", 5, "ACONS").
dico("A", 5, "ACORE").
dico("A", 5, "ACRAS").
dico("A", 5, "ACRES").
dico("A", 5, "ACTAI").
dico("A", 5, "ACTAS").
dico("A", 5, "ACTAT").
dico("A", 5, "ACTEE").
dico("A", 5, "ACTER").
dico("A", 5, "ACTES").
dico("A", 5, "ACTEZ").
dico("A", 5, "ACTIF").
dico("A", 5, "ACULS").
dico("A", 5, "ACYLE").
dico("A", 5, "ADACS").
dico("A", 5, "ADAGE").
dico("A", 5, "ADAVS").
dico("A", 5, "ADDAX").
dico("A", 5, "ADENT").
dico("A", 5, "ADIEU").
dico("A", 5, "ADIRE").
dico("A", 5, "ADMET").
dico("A", 5, "ADMIS").
dico("A", 5, "ADMIT").
dico("A", 5, "ADNEE").
dico("A", 5, "ADNES").
dico("A", 5, "ADOBE").
dico("A", 5, "ADONC").
dico("A", 5, "ADONS").
dico("A", 5, "ADORA").
dico("A", 5, "ADORE").
dico("A", 5, "ADRAR").
dico("A", 5, "ADRET").
dico("A", 5, "ADULA").
dico("A", 5, "ADULE").
dico("A", 5, "AEDES").
dico("A", 5, "AERAI").
dico("A", 5, "AERAS").
dico("A", 5, "AERAT").
dico("A", 5, "AEREE").
dico("A", 5, "AERER").
dico("A", 5, "AERES").
dico("A", 5, "AEREZ").
dico("A", 5, "AFATS").
dico("A", 5, "AFFIN").
dico("A", 5, "AFFUT").
dico("A", 5, "AGACA").
dico("A", 5, "AGACE").
dico("A", 5, "AGAME").
dico("A", 5, "AGAMI").
dico("A", 5, "AGAPE").
dico("A", 5, "AGATE").
dico("A", 5, "AGAVE").
dico("A", 5, "AGEES").
dico("A", 5, "AGENT").
dico("A", 5, "AGGLO").
dico("A", 5, "AGHAS").
dico("A", 5, "AGIES").
dico("A", 5, "AGILE").
dico("A", 5, "AGIOS").
dico("A", 5, "AGIRA").
dico("A", 5, "AGITA").
dico("A", 5, "AGITE").
dico("A", 5, "AGNAT").
dico("A", 5, "AGNEL").
dico("A", 5, "AGONI").
dico("A", 5, "AGORA").
dico("A", 5, "AGREA").
dico("A", 5, "AGREE").
dico("A", 5, "AGREG").
dico("A", 5, "AGRES").
dico("A", 5, "AGUIS").
dico("A", 5, "AHANA").
dico("A", 5, "AHANE").
dico("A", 5, "AHANS").
dico("A", 5, "AHURI").
dico("A", 5, "AICHA").
dico("A", 5, "AICHE").
dico("A", 5, "AIDAI").
dico("A", 5, "AIDAS").
dico("A", 5, "AIDAT").
dico("A", 5, "AIDEE").
dico("A", 5, "AIDER").
dico("A", 5, "AIDES").
dico("A", 5, "AIDEZ").
dico("A", 5, "AIENT").
dico("A", 5, "AIEUL").
dico("A", 5, "AIEUX").
dico("A", 5, "AIGLE").
dico("A", 5, "AIGRE").
dico("A", 5, "AIGRI").
dico("A", 5, "AIGUE").
dico("A", 5, "AIGUS").
dico("A", 5, "AILEE").
dico("A", 5, "AILES").
dico("A", 5, "AILLA").
dico("A", 5, "AILLE").
dico("A", 5, "AIMAI").
dico("A", 5, "AIMAS").
dico("A", 5, "AIMAT").
dico("A", 5, "AIMEE").
dico("A", 5, "AIMER").
dico("A", 5, "AIMES").
dico("A", 5, "AIMEZ").
dico("A", 5, "AINEE").
dico("A", 5, "AINES").
dico("A", 5, "AINOU").
dico("A", 5, "AINSI").
dico("A", 5, "AIOLI").
dico("A", 5, "AIRAI").
dico("A", 5, "AIRAS").
dico("A", 5, "AIRAT").
dico("A", 5, "AIREE").
dico("A", 5, "AIRER").
dico("A", 5, "AIRES").
dico("A", 5, "AIREZ").
dico("A", 5, "AISEE").
dico("A", 5, "AISES").
dico("A", 5, "AISYS").
dico("A", 5, "AJONC").
dico("A", 5, "AJOUR").
dico("A", 5, "AJOUT").
dico("A", 5, "AJUTS").
dico("A", 5, "AKANS").
dico("A", 5, "AKENE").
dico("A", 5, "ALBUM").
dico("A", 5, "ALDIN").
dico("A", 5, "ALDOL").
dico("A", 5, "ALEAS").
dico("A", 5, "ALEMS").
dico("A", 5, "ALENE").
dico("A", 5, "ALEPH").
dico("A", 5, "ALESA").
dico("A", 5, "ALESE").
dico("A", 5, "ALEZE").
dico("A", 5, "ALFAS").
dico("A", 5, "ALGIE").
dico("A", 5, "ALGOL").
dico("A", 5, "ALGUE").
dico("A", 5, "ALIAS").
dico("A", 5, "ALIBI").
dico("A", 5, "ALIOS").
dico("A", 5, "ALISE").
dico("A", 5, "ALITA").
dico("A", 5, "ALITE").
dico("A", 5, "ALIZE").
dico("A", 5, "ALLAI").
dico("A", 5, "ALLAS").
dico("A", 5, "ALLAT").
dico("A", 5, "ALLEE").
dico("A", 5, "ALLER").
dico("A", 5, "ALLES").
dico("A", 5, "ALLEU").
dico("A", 5, "ALLEZ").
dico("A", 5, "ALLIA").
dico("A", 5, "ALLIE").
dico("A", 5, "ALLOC").
dico("A", 5, "ALMEE").
dico("A", 5, "ALOES").
dico("A", 5, "ALOIS").
dico("A", 5, "ALORS").
dico("A", 5, "ALOSE").
dico("A", 5, "ALPAX").
dico("A", 5, "ALPES").
dico("A", 5, "ALPHA").
dico("A", 5, "ALPIN").
dico("A", 5, "ALTOS").
dico("A", 5, "ALULE").
dico("A", 5, "ALUNA").
dico("A", 5, "ALUNE").
dico("A", 5, "ALUNI").
dico("A", 5, "ALUNS").
dico("A", 5, "ALVIN").
dico("A", 5, "ALYTE").
dico("A", 5, "AMANS").
dico("A", 5, "AMANT").
dico("A", 5, "AMATI").
dico("A", 5, "AMBLA").
dico("A", 5, "AMBLE").
dico("A", 5, "AMBON").
dico("A", 5, "AMBRA").
dico("A", 5, "AMBRE").
dico("A", 5, "AMENA").
dico("A", 5, "AMENE").
dico("A", 5, "AMERE").
dico("A", 5, "AMERS").
dico("A", 5, "AMIBE").
dico("A", 5, "AMICT").
dico("A", 5, "AMIDE").
dico("A", 5, "AMIES").
dico("A", 5, "AMIGO").
dico("A", 5, "AMINE").
dico("A", 5, "AMISH").
dico("A", 5, "AMMAN").
dico("A", 5, "AMMIS").
dico("A", 5, "AMOKS").
dico("A", 5, "AMOME").
dico("A", 5, "AMONT").
dico("A", 5, "AMOUR").
dico("A", 5, "AMPHI").
dico("A", 5, "AMPLE").
dico("A", 5, "AMPLI").
dico("A", 5, "AMUIE").
dico("A", 5, "AMUIR").
dico("A", 5, "AMUIS").
dico("A", 5, "AMUIT").
dico("A", 5, "AMURA").
dico("A", 5, "AMURE").
dico("A", 5, "AMUSA").
dico("A", 5, "AMUSE").
dico("A", 5, "AMYLE").
dico("A", 5, "ANALE").
dico("A", 5, "ANARS").
dico("A", 5, "ANAUX").
dico("A", 5, "ANCHE").
dico("A", 5, "ANCRA").
dico("A", 5, "ANCRE").
dico("A", 5, "ANDIN").
dico("A", 5, "ANEES").
dico("A", 5, "ANELS").
dico("A", 5, "ANETH").
dico("A", 5, "ANGES").
dico("A", 5, "ANGLE").
dico("A", 5, "ANGON").
dico("A", 5, "ANGOR").
dico("A", 5, "ANIER").
dico("A", 5, "ANILS").
dico("A", 5, "ANIMA").
dico("A", 5, "ANIME").
dico("A", 5, "ANION").
dico("A", 5, "ANISA").
dico("A", 5, "ANISE").
dico("A", 5, "ANJOU").
dico("A", 5, "ANNAL").
dico("A", 5, "ANNEE").
dico("A", 5, "ANODE").
dico("A", 5, "ANONA").
dico("A", 5, "ANONE").
dico("A", 5, "ANONS").
dico("A", 5, "ANSEE").
dico("A", 5, "ANSES").
dico("A", 5, "ANTAN").
dico("A", 5, "ANTES").
dico("A", 5, "ANTRE").
dico("A", 5, "AORTE").
dico("A", 5, "AOUTA").
dico("A", 5, "AOUTE").
dico("A", 5, "AOUTS").
dico("A", 5, "APERO").
dico("A", 5, "APHTE").
dico("A", 5, "APIDE").
dico("A", 5, "APIOL").
dico("A", 5, "APION").
dico("A", 5, "APLAT").
dico("A", 5, "APNEE").
dico("A", 5, "APODE").
dico("A", 5, "APPAS").
dico("A", 5, "APPAT").
dico("A", 5, "APPEL").
dico("A", 5, "APPUI").
dico("A", 5, "APRES").
dico("A", 5, "APTES").
dico("A", 5, "APURA").
dico("A", 5, "APURE").
dico("A", 5, "APYRE").
dico("A", 5, "ARABE").
dico("A", 5, "ARACK").
dico("A", 5, "ARACS").
dico("A", 5, "ARAKS").
dico("A", 5, "ARASA").
dico("A", 5, "ARASE").
dico("A", 5, "ARBRE").
dico("A", 5, "ARCHE").
dico("A", 5, "ARCHI").
dico("A", 5, "ARCON").
dico("A", 5, "ARDUE").
dico("A", 5, "ARDUS").
dico("A", 5, "ARECS").
dico("A", 5, "ARENA").
dico("A", 5, "ARENE").
dico("A", 5, "ARETE").
dico("A", 5, "ARGAN").
dico("A", 5, "ARGAS").
dico("A", 5, "ARGOL").
dico("A", 5, "ARGON").
dico("A", 5, "ARGOT").
dico("A", 5, "ARGUA").
dico("A", 5, "ARGUE").
dico("A", 5, "ARGUS").
dico("A", 5, "ARIAS").
dico("A", 5, "ARIDE").
dico("A", 5, "ARIEN").
dico("A", 5, "ARISA").
dico("A", 5, "ARISE").
dico("A", 5, "ARMAI").
dico("A", 5, "ARMAS").
dico("A", 5, "ARMAT").
dico("A", 5, "ARMEE").
dico("A", 5, "ARMER").
dico("A", 5, "ARMES").
dico("A", 5, "ARMET").
dico("A", 5, "ARMEZ").
dico("A", 5, "ARMON").
dico("A", 5, "AROBE").
dico("A", 5, "AROLE").
dico("A", 5, "AROLS").
dico("A", 5, "AROME").
dico("A", 5, "ARQUA").
dico("A", 5, "ARQUE").
dico("A", 5, "ARRET").
dico("A", 5, "ARROI").
dico("A", 5, "ARSIN").
dico("A", 5, "ARSIS").
dico("A", 5, "ARTEL").
dico("A", 5, "ARUMS").
dico("A", 5, "ARYEN").
dico("A", 5, "ARYLE").
dico("A", 5, "ARZEL").
dico("A", 5, "ASANA").
dico("A", 5, "ASDIC").
dico("A", 5, "ASILE").
dico("A", 5, "ASINE").
dico("A", 5, "ASPES").
dico("A", 5, "ASPIC").
dico("A", 5, "ASPIS").
dico("A", 5, "ASPLE").
dico("A", 5, "ASPRE").
dico("A", 5, "ASQUE").
dico("A", 5, "ASRAM").
dico("A", 5, "ASSAI").
dico("A", 5, "ASSEC").
dico("A", 5, "ASSES").
dico("A", 5, "ASSEZ").
dico("A", 5, "ASSIS").
dico("A", 5, "ASSIT").
dico("A", 5, "ASTER").
dico("A", 5, "ASTIC").
dico("A", 5, "ASTIS").
dico("A", 5, "ASTRE").
dico("A", 5, "ATACA").
dico("A", 5, "ATELE").
dico("A", 5, "ATEMI").
dico("A", 5, "ATHEE").
dico("A", 5, "ATLAS").
dico("A", 5, "ATMAN").
dico("A", 5, "ATOCA").
dico("A", 5, "ATOLL").
dico("A", 5, "ATOME").
dico("A", 5, "ATONE").
dico("A", 5, "ATOUR").
dico("A", 5, "ATOUT").
dico("A", 5, "ATRES").
dico("A", 5, "AUBES").
dico("A", 5, "AUBIN").
dico("A", 5, "AUCUN").
dico("A", 5, "AUDIO").
dico("A", 5, "AUDIT").
dico("A", 5, "AUGEE").
dico("A", 5, "AUGES").
dico("A", 5, "AUGET").
dico("A", 5, "AULAS").
dico("A", 5, "AULNE").
dico("A", 5, "AUNAI").
dico("A", 5, "AUNAS").
dico("A", 5, "AUNAT").
dico("A", 5, "AUNEE").
dico("A", 5, "AUNER").
dico("A", 5, "AUNES").
dico("A", 5, "AUNEZ").
dico("A", 5, "AURAI").
dico("A", 5, "AURAS").
dico("A", 5, "AUREZ").
dico("A", 5, "AUSSI").
dico("A", 5, "AUTAN").
dico("A", 5, "AUTEL").
dico("A", 5, "AUTOS").
dico("A", 5, "AUTRE").
dico("A", 5, "AVAIS").
dico("A", 5, "AVAIT").
dico("A", 5, "AVALA").
dico("A", 5, "AVALE").
dico("A", 5, "AVALS").
dico("A", 5, "AVANT").
dico("A", 5, "AVARE").
dico("A", 5, "AVENS").
dico("A", 5, "AVENT").
dico("A", 5, "AVENU").
dico("A", 5, "AVERA").
dico("A", 5, "AVERE").
dico("A", 5, "AVERS").
dico("A", 5, "AVEUX").
dico("A", 5, "AVIDE").
dico("A", 5, "AVIEZ").
dico("A", 5, "AVILI").
dico("A", 5, "AVINA").
dico("A", 5, "AVINE").
dico("A", 5, "AVION").
dico("A", 5, "AVISA").
dico("A", 5, "AVISE").
dico("A", 5, "AVISO").
dico("A", 5, "AVIVA").
dico("A", 5, "AVIVE").
dico("A", 5, "AVOIE").
dico("A", 5, "AVOIR").
dico("A", 5, "AVONS").
dico("A", 5, "AVOUA").
dico("A", 5, "AVOUE").
dico("A", 5, "AVOYA").
dico("A", 5, "AVOYE").
dico("A", 5, "AVRIL").
dico("A", 5, "AWACS").
dico("A", 5, "AWALE").
dico("A", 5, "AWELE").
dico("A", 5, "AXAIS").
dico("A", 5, "AXAIT").
dico("A", 5, "AXANT").
dico("A", 5, "AXEES").
dico("A", 5, "AXELS").
dico("A", 5, "AXENE").
dico("A", 5, "AXENT").
dico("A", 5, "AXERA").
dico("A", 5, "AXIAL").
dico("A", 5, "AXIEZ").
dico("A", 5, "AXILE").
dico("A", 5, "AXONE").
dico("A", 5, "AXONS").
dico("A", 5, "AYANT").
dico("A", 5, "AYONS").
dico("A", 5, "AZERI").
dico("A", 5, "AZOBE").
dico("A", 5, "AZORA").
dico("A", 5, "AZORE").
dico("A", 5, "AZOTA").
dico("A", 5, "AZOTE").
dico("A", 5, "AZURA").
dico("A", 5, "AZURE").
dico("A", 5, "AZURS").
dico("A", 5, "AZYME").
