dico("B", 7, "BABALLE").
dico("B", 7, "BABILLA").
dico("B", 7, "BABILLE").
dico("B", 7, "BABINES").
dico("B", 7, "BABIOLE").
dico("B", 7, "BABISME").
dico("B", 7, "BABOLAI").
dico("B", 7, "BABOLAS").
dico("B", 7, "BABOLAT").
dico("B", 7, "BABOLER").
dico("B", 7, "BABOLES").
dico("B", 7, "BABOLEZ").
dico("B", 7, "BABORDS").
dico("B", 7, "BABOUIN").
dico("B", 7, "BABOUNE").
dico("B", 7, "BACANTE").
dico("B", 7, "BACCARA").
dico("B", 7, "BACHAGE").
dico("B", 7, "BACHAIS").
dico("B", 7, "BACHAIT").
dico("B", 7, "BACHANT").
dico("B", 7, "BACHEES").
dico("B", 7, "BACHENT").
dico("B", 7, "BACHERA").
dico("B", 7, "BACHIEZ").
dico("B", 7, "BACHONS").
dico("B", 7, "BACHOTA").
dico("B", 7, "BACHOTE").
dico("B", 7, "BACHOTS").
dico("B", 7, "BACILLE").
dico("B", 7, "BACLAGE").
dico("B", 7, "BACLAIS").
dico("B", 7, "BACLAIT").
dico("B", 7, "BACLANT").
dico("B", 7, "BACLEES").
dico("B", 7, "BACLENT").
dico("B", 7, "BACLERA").
dico("B", 7, "BACLEUR").
dico("B", 7, "BACLIEZ").
dico("B", 7, "BACLONS").
dico("B", 7, "BADAMES").
dico("B", 7, "BADASSE").
dico("B", 7, "BADATES").
dico("B", 7, "BADAUDA").
dico("B", 7, "BADAUDE").
dico("B", 7, "BADAUDS").
dico("B", 7, "BADECHE").
dico("B", 7, "BADERAI").
dico("B", 7, "BADERAS").
dico("B", 7, "BADEREZ").
dico("B", 7, "BADERNE").
dico("B", 7, "BADGEAI").
dico("B", 7, "BADGEAS").
dico("B", 7, "BADGEAT").
dico("B", 7, "BADGEES").
dico("B", 7, "BADGENT").
dico("B", 7, "BADGERA").
dico("B", 7, "BADGIEZ").
dico("B", 7, "BADIANE").
dico("B", 7, "BADINAI").
dico("B", 7, "BADINAS").
dico("B", 7, "BADINAT").
dico("B", 7, "BADINER").
dico("B", 7, "BADINES").
dico("B", 7, "BADINEZ").
dico("B", 7, "BADIONS").
dico("B", 7, "BADOISE").
dico("B", 7, "BAESINE").
dico("B", 7, "BAFFAIS").
dico("B", 7, "BAFFAIT").
dico("B", 7, "BAFFANT").
dico("B", 7, "BAFFEES").
dico("B", 7, "BAFFENT").
dico("B", 7, "BAFFERA").
dico("B", 7, "BAFFIEZ").
dico("B", 7, "BAFFLES").
dico("B", 7, "BAFFONS").
dico("B", 7, "BAFOUAI").
dico("B", 7, "BAFOUAS").
dico("B", 7, "BAFOUAT").
dico("B", 7, "BAFOUEE").
dico("B", 7, "BAFOUER").
dico("B", 7, "BAFOUES").
dico("B", 7, "BAFOUEZ").
dico("B", 7, "BAFRAIS").
dico("B", 7, "BAFRAIT").
dico("B", 7, "BAFRANT").
dico("B", 7, "BAFREES").
dico("B", 7, "BAFRENT").
dico("B", 7, "BAFRERA").
dico("B", 7, "BAFREUR").
dico("B", 7, "BAFRIEZ").
dico("B", 7, "BAFRONS").
dico("B", 7, "BAGADOU").
dico("B", 7, "BAGAGES").
dico("B", 7, "BAGARRA").
dico("B", 7, "BAGARRE").
dico("B", 7, "BAGASSE").
dico("B", 7, "BAGAUDE").
dico("B", 7, "BAGAYOU").
dico("B", 7, "BAGNARD").
dico("B", 7, "BAGNOLE").
dico("B", 7, "BAGOUTS").
dico("B", 7, "BAGUAGE").
dico("B", 7, "BAGUAIS").
dico("B", 7, "BAGUAIT").
dico("B", 7, "BAGUANT").
dico("B", 7, "BAGUEES").
dico("B", 7, "BAGUELS").
dico("B", 7, "BAGUENT").
dico("B", 7, "BAGUERA").
dico("B", 7, "BAGUIER").
dico("B", 7, "BAGUIEZ").
dico("B", 7, "BAGUIOS").
dico("B", 7, "BAGUONS").
dico("B", 7, "BAIERAI").
dico("B", 7, "BAIERAS").
dico("B", 7, "BAIEREZ").
dico("B", 7, "BAIGNAI").
dico("B", 7, "BAIGNAS").
dico("B", 7, "BAIGNAT").
dico("B", 7, "BAIGNEE").
dico("B", 7, "BAIGNER").
dico("B", 7, "BAIGNES").
dico("B", 7, "BAIGNEZ").
dico("B", 7, "BAILLAI").
dico("B", 7, "BAILLAS").
dico("B", 7, "BAILLAT").
dico("B", 7, "BAILLEE").
dico("B", 7, "BAILLER").
dico("B", 7, "BAILLES").
dico("B", 7, "BAILLEZ").
dico("B", 7, "BAILLIE").
dico("B", 7, "BAILLIS").
dico("B", 7, "BAILLON").
dico("B", 7, "BAIOQUE").
dico("B", 7, "BAIRAMS").
dico("B", 7, "BAISAIS").
dico("B", 7, "BAISAIT").
dico("B", 7, "BAISANT").
dico("B", 7, "BAISEES").
dico("B", 7, "BAISENT").
dico("B", 7, "BAISERA").
dico("B", 7, "BAISERS").
dico("B", 7, "BAISEUR").
dico("B", 7, "BAISIEZ").
dico("B", 7, "BAISONS").
dico("B", 7, "BAISOTA").
dico("B", 7, "BAISOTE").
dico("B", 7, "BAISSAI").
dico("B", 7, "BAISSAS").
dico("B", 7, "BAISSAT").
dico("B", 7, "BAISSEE").
dico("B", 7, "BAISSER").
dico("B", 7, "BAISSES").
dico("B", 7, "BAISSEZ").
dico("B", 7, "BAISURE").
dico("B", 7, "BAJOUES").
dico("B", 7, "BAJOYER").
dico("B", 7, "BAKEOFE").
dico("B", 7, "BAKLAVA").
dico("B", 7, "BAKUFUS").
dico("B", 7, "BALADAI").
dico("B", 7, "BALADAS").
dico("B", 7, "BALADAT").
dico("B", 7, "BALADEE").
dico("B", 7, "BALADER").
dico("B", 7, "BALADES").
dico("B", 7, "BALADEZ").
dico("B", 7, "BALADIN").
dico("B", 7, "BALAFON").
dico("B", 7, "BALAFRA").
dico("B", 7, "BALAFRE").
dico("B", 7, "BALAIES").
dico("B", 7, "BALAISE").
dico("B", 7, "BALANCA").
dico("B", 7, "BALANCE").
dico("B", 7, "BALANES").
dico("B", 7, "BALATAS").
dico("B", 7, "BALATUM").
dico("B", 7, "BALAYAI").
dico("B", 7, "BALAYAS").
dico("B", 7, "BALAYAT").
dico("B", 7, "BALAYEE").
dico("B", 7, "BALAYER").
dico("B", 7, "BALAYES").
dico("B", 7, "BALAYEZ").
dico("B", 7, "BALBOAS").
dico("B", 7, "BALCONS").
dico("B", 7, "BALEARE").
dico("B", 7, "BALEINE").
dico("B", 7, "BALESES").
dico("B", 7, "BALEVRE").
dico("B", 7, "BALEZES").
dico("B", 7, "BALISAI").
dico("B", 7, "BALISAS").
dico("B", 7, "BALISAT").
dico("B", 7, "BALISEE").
dico("B", 7, "BALISER").
dico("B", 7, "BALISES").
dico("B", 7, "BALISEZ").
dico("B", 7, "BALISTE").
dico("B", 7, "BALIVAI").
dico("B", 7, "BALIVAS").
dico("B", 7, "BALIVAT").
dico("B", 7, "BALIVEE").
dico("B", 7, "BALIVER").
dico("B", 7, "BALIVES").
dico("B", 7, "BALIVEZ").
dico("B", 7, "BALLADE").
dico("B", 7, "BALLAIS").
dico("B", 7, "BALLAIT").
dico("B", 7, "BALLANT").
dico("B", 7, "BALLAST").
dico("B", 7, "BALLENT").
dico("B", 7, "BALLERA").
dico("B", 7, "BALLETS").
dico("B", 7, "BALLIEZ").
dico("B", 7, "BALLONS").
dico("B", 7, "BALLOTE").
dico("B", 7, "BALLOTS").
dico("B", 7, "BALOISE").
dico("B", 7, "BALOURD").
dico("B", 7, "BALZANE").
dico("B", 7, "BALZANS").
dico("B", 7, "BAMBARA").
dico("B", 7, "BAMBINE").
dico("B", 7, "BAMBINS").
dico("B", 7, "BAMBOUS").
dico("B", 7, "BANALES").
dico("B", 7, "BANANAI").
dico("B", 7, "BANANAS").
dico("B", 7, "BANANAT").
dico("B", 7, "BANANEE").
dico("B", 7, "BANANER").
dico("B", 7, "BANANES").
dico("B", 7, "BANANEZ").
dico("B", 7, "BANBANS").
dico("B", 7, "BANCALE").
dico("B", 7, "BANCALS").
dico("B", 7, "BANCHAI").
dico("B", 7, "BANCHAS").
dico("B", 7, "BANCHAT").
dico("B", 7, "BANCHEE").
dico("B", 7, "BANCHER").
dico("B", 7, "BANCHES").
dico("B", 7, "BANCHEZ").
dico("B", 7, "BANCOUL").
dico("B", 7, "BANDAGE").
dico("B", 7, "BANDAIS").
dico("B", 7, "BANDAIT").
dico("B", 7, "BANDANA").
dico("B", 7, "BANDANT").
dico("B", 7, "BANDEAU").
dico("B", 7, "BANDEES").
dico("B", 7, "BANDENT").
dico("B", 7, "BANDERA").
dico("B", 7, "BANDIEZ").
dico("B", 7, "BANDITS").
dico("B", 7, "BANDOLS").
dico("B", 7, "BANDONS").
dico("B", 7, "BANGIEE").
dico("B", 7, "BANIANS").
dico("B", 7, "BANLONS").
dico("B", 7, "BANNIES").
dico("B", 7, "BANNIRA").
dico("B", 7, "BANQUAI").
dico("B", 7, "BANQUAS").
dico("B", 7, "BANQUAT").
dico("B", 7, "BANQUEE").
dico("B", 7, "BANQUER").
dico("B", 7, "BANQUES").
dico("B", 7, "BANQUET").
dico("B", 7, "BANQUEZ").
dico("B", 7, "BANTOUE").
dico("B", 7, "BANTOUS").
dico("B", 7, "BANVINS").
dico("B", 7, "BANYULS").
dico("B", 7, "BAOBABS").
dico("B", 7, "BAPTEME").
dico("B", 7, "BAPTISA").
dico("B", 7, "BAPTISE").
dico("B", 7, "BAQUAIS").
dico("B", 7, "BAQUAIT").
dico("B", 7, "BAQUANT").
dico("B", 7, "BAQUEES").
dico("B", 7, "BAQUENT").
dico("B", 7, "BAQUERA").
dico("B", 7, "BAQUETA").
dico("B", 7, "BAQUETE").
dico("B", 7, "BAQUETS").
dico("B", 7, "BAQUIEZ").
dico("B", 7, "BAQUONS").
dico("B", 7, "BARAKAS").
dico("B", 7, "BARAQUA").
dico("B", 7, "BARAQUE").
dico("B", 7, "BARATIN").
dico("B", 7, "BARATTA").
dico("B", 7, "BARATTE").
dico("B", 7, "BARBAIS").
dico("B", 7, "BARBAIT").
dico("B", 7, "BARBANT").
dico("B", 7, "BARBARE").
dico("B", 7, "BARBEAU").
dico("B", 7, "BARBEES").
dico("B", 7, "BARBELE").
dico("B", 7, "BARBENT").
dico("B", 7, "BARBERA").
dico("B", 7, "BARBETS").
dico("B", 7, "BARBIER").
dico("B", 7, "BARBIEZ").
dico("B", 7, "BARBONS").
dico("B", 7, "BARBOTA").
dico("B", 7, "BARBOTE").
dico("B", 7, "BARBOTS").
dico("B", 7, "BARBUES").
dico("B", 7, "BARBULE").
dico("B", 7, "BARDAGE").
dico("B", 7, "BARDAIS").
dico("B", 7, "BARDAIT").
dico("B", 7, "BARDANE").
dico("B", 7, "BARDANT").
dico("B", 7, "BARDEAU").
dico("B", 7, "BARDEES").
dico("B", 7, "BARDENT").
dico("B", 7, "BARDERA").
dico("B", 7, "BARDIEZ").
dico("B", 7, "BARDITS").
dico("B", 7, "BARDONS").
dico("B", 7, "BARDOTS").
dico("B", 7, "BAREGES").
dico("B", 7, "BAREMES").
dico("B", 7, "BARETAI").
dico("B", 7, "BARETAS").
dico("B", 7, "BARETAT").
dico("B", 7, "BARETER").
dico("B", 7, "BARETES").
dico("B", 7, "BARETEZ").
dico("B", 7, "BARIBAL").
dico("B", 7, "BARINES").
dico("B", 7, "BARIOLA").
dico("B", 7, "BARIOLE").
dico("B", 7, "BARJOTS").
dico("B", 7, "BARLONG").
dico("B", 7, "BARMAID").
dico("B", 7, "BARMANS").
dico("B", 7, "BARNUMS").
dico("B", 7, "BAROLOS").
dico("B", 7, "BARONET").
dico("B", 7, "BARONNE").
dico("B", 7, "BAROQUE").
dico("B", 7, "BAROUDA").
dico("B", 7, "BAROUDE").
dico("B", 7, "BAROUDS").
dico("B", 7, "BAROUFE").
dico("B", 7, "BAROUFS").
dico("B", 7, "BARQUES").
dico("B", 7, "BARRAGE").
dico("B", 7, "BARRAIS").
dico("B", 7, "BARRAIT").
dico("B", 7, "BARRANT").
dico("B", 7, "BARREAU").
dico("B", 7, "BARREES").
dico("B", 7, "BARRELS").
dico("B", 7, "BARRENS").
dico("B", 7, "BARRENT").
dico("B", 7, "BARRERA").
dico("B", 7, "BARREUR").
dico("B", 7, "BARRIEZ").
dico("B", 7, "BARRIRA").
dico("B", 7, "BARRITS").
dico("B", 7, "BARRONS").
dico("B", 7, "BARROTS").
dico("B", 7, "BARRURE").
dico("B", 7, "BARYONS").
dico("B", 7, "BARYTEE").
dico("B", 7, "BARYTES").
dico("B", 7, "BARYTON").
dico("B", 7, "BARYUMS").
dico("B", 7, "BARZOIS").
dico("B", 7, "BASALES").
dico("B", 7, "BASALTE").
dico("B", 7, "BASAMES").
dico("B", 7, "BASANAI").
dico("B", 7, "BASANAS").
dico("B", 7, "BASANAT").
dico("B", 7, "BASANEE").
dico("B", 7, "BASANER").
dico("B", 7, "BASANES").
dico("B", 7, "BASANEZ").
dico("B", 7, "BASASSE").
dico("B", 7, "BASATES").
dico("B", 7, "BASCULA").
dico("B", 7, "BASCULE").
dico("B", 7, "BASELLE").
dico("B", 7, "BASERAI").
dico("B", 7, "BASERAS").
dico("B", 7, "BASEREZ").
dico("B", 7, "BASIDES").
dico("B", 7, "BASILIC").
dico("B", 7, "BASIONS").
dico("B", 7, "BASIQUE").
dico("B", 7, "BASISTE").
dico("B", 7, "BASKETS").
dico("B", 7, "BASMATI").
dico("B", 7, "BASOCHE").
dico("B", 7, "BASQUES").
dico("B", 7, "BASQUET").
dico("B", 7, "BASSETS").
dico("B", 7, "BASSINA").
dico("B", 7, "BASSINE").
dico("B", 7, "BASSINS").
dico("B", 7, "BASSONS").
dico("B", 7, "BASTAIS").
dico("B", 7, "BASTAIT").
dico("B", 7, "BASTANT").
dico("B", 7, "BASTENT").
dico("B", 7, "BASTERA").
dico("B", 7, "BASTIDE").
dico("B", 7, "BASTIEZ").
dico("B", 7, "BASTING").
dico("B", 7, "BASTINS").
dico("B", 7, "BASTION").
dico("B", 7, "BASTONS").
dico("B", 7, "BATAMES").
dico("B", 7, "BATARDE").
dico("B", 7, "BATARDS").
dico("B", 7, "BATASSE").
dico("B", 7, "BATATES").
dico("B", 7, "BATAVES").
dico("B", 7, "BATAVIA").
dico("B", 7, "BATCHES").
dico("B", 7, "BATEAUX").
dico("B", 7, "BATELAI").
dico("B", 7, "BATELAS").
dico("B", 7, "BATELAT").
dico("B", 7, "BATELEE").
dico("B", 7, "BATELER").
dico("B", 7, "BATELES").
dico("B", 7, "BATELET").
dico("B", 7, "BATELEZ").
dico("B", 7, "BATELLE").
dico("B", 7, "BATERAI").
dico("B", 7, "BATERAS").
dico("B", 7, "BATEREZ").
dico("B", 7, "BATHYAL").
dico("B", 7, "BATIDAS").
dico("B", 7, "BATIERE").
dico("B", 7, "BATIMES").
dico("B", 7, "BATIONS").
dico("B", 7, "BATIRAI").
dico("B", 7, "BATIRAS").
dico("B", 7, "BATIREZ").
dico("B", 7, "BATISSE").
dico("B", 7, "BATISTE").
dico("B", 7, "BATITES").
dico("B", 7, "BATONNA").
dico("B", 7, "BATONNE").
dico("B", 7, "BATOUDE").
dico("B", 7, "BATTAGE").
dico("B", 7, "BATTAIS").
dico("B", 7, "BATTAIT").
dico("B", 7, "BATTANT").
dico("B", 7, "BATTEES").
dico("B", 7, "BATTENT").
dico("B", 7, "BATTEUR").
dico("B", 7, "BATTIEZ").
dico("B", 7, "BATTOIR").
dico("B", 7, "BATTONS").
dico("B", 7, "BATTRAI").
dico("B", 7, "BATTRAS").
dico("B", 7, "BATTREZ").
dico("B", 7, "BATTUES").
dico("B", 7, "BATTURE").
dico("B", 7, "BAUDETS").
dico("B", 7, "BAUGEAI").
dico("B", 7, "BAUGEAS").
dico("B", 7, "BAUGEAT").
dico("B", 7, "BAUGEES").
dico("B", 7, "BAUGENT").
dico("B", 7, "BAUGERA").
dico("B", 7, "BAUGIEZ").
dico("B", 7, "BAUMIER").
dico("B", 7, "BAUXITE").
dico("B", 7, "BAVAMES").
dico("B", 7, "BAVARDA").
dico("B", 7, "BAVARDE").
dico("B", 7, "BAVARDS").
dico("B", 7, "BAVASSA").
dico("B", 7, "BAVASSE").
dico("B", 7, "BAVATES").
dico("B", 7, "BAVERAI").
dico("B", 7, "BAVERAS").
dico("B", 7, "BAVEREZ").
dico("B", 7, "BAVETTE").
dico("B", 7, "BAVEURS").
dico("B", 7, "BAVEUSE").
dico("B", 7, "BAVIONS").
dico("B", 7, "BAVOCHA").
dico("B", 7, "BAVOCHE").
dico("B", 7, "BAVOIRS").
dico("B", 7, "BAVOLET").
dico("B", 7, "BAVURES").
dico("B", 7, "BAYAMES").
dico("B", 7, "BAYASSE").
dico("B", 7, "BAYATES").
dico("B", 7, "BAYERAI").
dico("B", 7, "BAYERAS").
dico("B", 7, "BAYEREZ").
dico("B", 7, "BAYIONS").
dico("B", 7, "BAYRAMS").
dico("B", 7, "BAZARDA").
dico("B", 7, "BAZARDE").
dico("B", 7, "BAZOOKA").
dico("B", 7, "BEAGLES").
dico("B", 7, "BEAIENT").
dico("B", 7, "BEANCES").
dico("B", 7, "BEANTES").
dico("B", 7, "BEASSES").
dico("B", 7, "BEATNIK").
dico("B", 7, "BEAUPRE").
dico("B", 7, "BEAUTES").
dico("B", 7, "BEBETES").
dico("B", 7, "BEBITES").
dico("B", 7, "BECANES").
dico("B", 7, "BECARDS").
dico("B", 7, "BECARRE").
dico("B", 7, "BECASSE").
dico("B", 7, "BECAUSE").
dico("B", 7, "BECCARD").
dico("B", 7, "BECHAGE").
dico("B", 7, "BECHAIS").
dico("B", 7, "BECHAIT").
dico("B", 7, "BECHANT").
dico("B", 7, "BECHEES").
dico("B", 7, "BECHENT").
dico("B", 7, "BECHERA").
dico("B", 7, "BECHERS").
dico("B", 7, "BECHEUR").
dico("B", 7, "BECHIEZ").
dico("B", 7, "BECHOIR").
dico("B", 7, "BECHONS").
dico("B", 7, "BECOTAI").
dico("B", 7, "BECOTAS").
dico("B", 7, "BECOTAT").
dico("B", 7, "BECOTEE").
dico("B", 7, "BECOTER").
dico("B", 7, "BECOTES").
dico("B", 7, "BECOTEZ").
dico("B", 7, "BECQUEE").
dico("B", 7, "BECQUET").
dico("B", 7, "BECTAIS").
dico("B", 7, "BECTAIT").
dico("B", 7, "BECTANT").
dico("B", 7, "BECTEES").
dico("B", 7, "BECTENT").
dico("B", 7, "BECTERA").
dico("B", 7, "BECTIEZ").
dico("B", 7, "BECTONS").
dico("B", 7, "BEDAINE").
dico("B", 7, "BEDANES").
dico("B", 7, "BEDEAUX").
dico("B", 7, "BEDEGAR").
dico("B", 7, "BEDONNA").
dico("B", 7, "BEDONNE").
dico("B", 7, "BEDOUIN").
dico("B", 7, "BEERAIS").
dico("B", 7, "BEERAIT").
dico("B", 7, "BEERENT").
dico("B", 7, "BEERIEZ").
dico("B", 7, "BEERONS").
dico("B", 7, "BEERONT").
dico("B", 7, "BEFFROI").
dico("B", 7, "BEGAIES").
dico("B", 7, "BEGARDS").
dico("B", 7, "BEGAYAI").
dico("B", 7, "BEGAYAS").
dico("B", 7, "BEGAYAT").
dico("B", 7, "BEGAYEE").
dico("B", 7, "BEGAYER").
dico("B", 7, "BEGAYES").
dico("B", 7, "BEGAYEZ").
dico("B", 7, "BEGGARD").
dico("B", 7, "BEGONIA").
dico("B", 7, "BEGUARD").
dico("B", 7, "BEGUETA").
dico("B", 7, "BEGUETE").
dico("B", 7, "BEGUINE").
dico("B", 7, "BEGUINS").
dico("B", 7, "BEIGNES").
dico("B", 7, "BEIGNET").
dico("B", 7, "BEIRAMS").
dico("B", 7, "BEJAUNE").
dico("B", 7, "BELAMES").
dico("B", 7, "BELANTE").
dico("B", 7, "BELANTS").
dico("B", 7, "BELASSE").
dico("B", 7, "BELATES").
dico("B", 7, "BELERAI").
dico("B", 7, "BELERAS").
dico("B", 7, "BELEREZ").
dico("B", 7, "BELETTE").
dico("B", 7, "BELIERE").
dico("B", 7, "BELIERS").
dico("B", 7, "BELINOS").
dico("B", 7, "BELIONS").
dico("B", 7, "BELITRE").
dico("B", 7, "BELLOTS").
dico("B", 7, "BELOTEE").
dico("B", 7, "BELOTES").
dico("B", 7, "BELOUGA").
dico("B", 7, "BELUGAS").
dico("B", 7, "BENARDE").
dico("B", 7, "BENARDS").
dico("B", 7, "BENDIRS").
dico("B", 7, "BENGALE").
dico("B", 7, "BENGALI").
dico("B", 7, "BENIGNE").
dico("B", 7, "BENIMES").
dico("B", 7, "BENIRAI").
dico("B", 7, "BENIRAS").
dico("B", 7, "BENIREZ").
dico("B", 7, "BENISSE").
dico("B", 7, "BENITES").
dico("B", 7, "BENJOIN").
dico("B", 7, "BENOITE").
dico("B", 7, "BENOITS").
dico("B", 7, "BENTHOS").
dico("B", 7, "BENZENE").
dico("B", 7, "BENZINE").
dico("B", 7, "BENZOLE").
dico("B", 7, "BENZOLS").
dico("B", 7, "BENZYLE").
dico("B", 7, "BEOTHUK").
dico("B", 7, "BEOTIEN").
dico("B", 7, "BEQUEES").
dico("B", 7, "BEQUETA").
dico("B", 7, "BEQUETE").
dico("B", 7, "BEQUETS").
dico("B", 7, "BERBERE").
dico("B", 7, "BERCAIL").
dico("B", 7, "BERCAIS").
dico("B", 7, "BERCAIT").
dico("B", 7, "BERCANT").
dico("B", 7, "BERCEAU").
dico("B", 7, "BERCEES").
dico("B", 7, "BERCENT").
dico("B", 7, "BERCERA").
dico("B", 7, "BERCEUR").
dico("B", 7, "BERCIEZ").
dico("B", 7, "BERCONS").
dico("B", 7, "BERGERE").
dico("B", 7, "BERGERS").
dico("B", 7, "BERLINE").
dico("B", 7, "BERLUES").
dico("B", 7, "BERMUDA").
dico("B", 7, "BERNAIS").
dico("B", 7, "BERNAIT").
dico("B", 7, "BERNANT").
dico("B", 7, "BERNEES").
dico("B", 7, "BERNENT").
dico("B", 7, "BERNERA").
dico("B", 7, "BERNEUR").
dico("B", 7, "BERNIEZ").
dico("B", 7, "BERNOIS").
dico("B", 7, "BERNONS").
dico("B", 7, "BERTHES").
dico("B", 7, "BERTHON").
dico("B", 7, "BESACES").
dico("B", 7, "BESANTS").
dico("B", 7, "BESIGUE").
dico("B", 7, "BESOGNA").
dico("B", 7, "BESOGNE").
dico("B", 7, "BESOINS").
dico("B", 7, "BESSONS").
dico("B", 7, "BESTIAL").
dico("B", 7, "BESTIAU").
dico("B", 7, "BETASSE").
dico("B", 7, "BETIFIA").
dico("B", 7, "BETIFIE").
dico("B", 7, "BETISAI").
dico("B", 7, "BETISAS").
dico("B", 7, "BETISAT").
dico("B", 7, "BETISER").
dico("B", 7, "BETISES").
dico("B", 7, "BETISEZ").
dico("B", 7, "BETOINE").
dico("B", 7, "BETOIRE").
dico("B", 7, "BETONNA").
dico("B", 7, "BETONNE").
dico("B", 7, "BETTING").
dico("B", 7, "BETYLES").
dico("B", 7, "BEUGLAI").
dico("B", 7, "BEUGLAS").
dico("B", 7, "BEUGLAT").
dico("B", 7, "BEUGLEE").
dico("B", 7, "BEUGLER").
dico("B", 7, "BEUGLES").
dico("B", 7, "BEUGLEZ").
dico("B", 7, "BEURRAI").
dico("B", 7, "BEURRAS").
dico("B", 7, "BEURRAT").
dico("B", 7, "BEURREE").
dico("B", 7, "BEURRER").
dico("B", 7, "BEURRES").
dico("B", 7, "BEURREZ").
dico("B", 7, "BEZOARD").
dico("B", 7, "BIACIDE").
dico("B", 7, "BIAISAI").
dico("B", 7, "BIAISAS").
dico("B", 7, "BIAISAT").
dico("B", 7, "BIAISEE").
dico("B", 7, "BIAISER").
dico("B", 7, "BIAISES").
dico("B", 7, "BIAISEZ").
dico("B", 7, "BIARROT").
dico("B", 7, "BIAURAL").
dico("B", 7, "BIBANDE").
dico("B", 7, "BIBELOT").
dico("B", 7, "BIBERON").
dico("B", 7, "BIBINES").
dico("B", 7, "BIBIONS").
dico("B", 7, "BIBITES").
dico("B", 7, "BICARRE").
dico("B", 7, "BICHAIS").
dico("B", 7, "BICHAIT").
dico("B", 7, "BICHANT").
dico("B", 7, "BICHENT").
dico("B", 7, "BICHERA").
dico("B", 7, "BICHIEZ").
dico("B", 7, "BICHOFS").
dico("B", 7, "BICHONS").
dico("B", 7, "BICLOUS").
dico("B", 7, "BICOQUE").
dico("B", 7, "BICORNE").
dico("B", 7, "BICROSS").
dico("B", 7, "BICYCLE").
dico("B", 7, "BIDASSE").
dico("B", 7, "BIDENTS").
dico("B", 7, "BIDOCHE").
dico("B", 7, "BIDONNA").
dico("B", 7, "BIDONNE").
dico("B", 7, "BIDULES").
dico("B", 7, "BIELLES").
dico("B", 7, "BIENNAL").
dico("B", 7, "BIENTOT").
dico("B", 7, "BIERGOL").
dico("B", 7, "BIEVRES").
dico("B", 7, "BIFACES").
dico("B", 7, "BIFFAGE").
dico("B", 7, "BIFFAIS").
dico("B", 7, "BIFFAIT").
dico("B", 7, "BIFFANT").
dico("B", 7, "BIFFEES").
dico("B", 7, "BIFFENT").
dico("B", 7, "BIFFERA").
dico("B", 7, "BIFFIEZ").
dico("B", 7, "BIFFINS").
dico("B", 7, "BIFFONS").
dico("B", 7, "BIFFURE").
dico("B", 7, "BIFIDES").
dico("B", 7, "BIFIDUS").
dico("B", 7, "BIFOCAL").
dico("B", 7, "BIFOLIE").
dico("B", 7, "BIFTECK").
dico("B", 7, "BIGAMES").
dico("B", 7, "BIGAMIE").
dico("B", 7, "BIGARRA").
dico("B", 7, "BIGARRE").
dico("B", 7, "BIGHORN").
dico("B", 7, "BIGLAIS").
dico("B", 7, "BIGLAIT").
dico("B", 7, "BIGLANT").
dico("B", 7, "BIGLEES").
dico("B", 7, "BIGLENT").
dico("B", 7, "BIGLERA").
dico("B", 7, "BIGLEUX").
dico("B", 7, "BIGLIEZ").
dico("B", 7, "BIGLONS").
dico("B", 7, "BIGNOLE").
dico("B", 7, "BIGNONE").
dico("B", 7, "BIGORNA").
dico("B", 7, "BIGORNE").
dico("B", 7, "BIGOTES").
dico("B", 7, "BIGOUDI").
dico("B", 7, "BIGUINE").
dico("B", 7, "BIHARIS").
dico("B", 7, "BIKINIS").
dico("B", 7, "BILABIE").
dico("B", 7, "BILAMES").
dico("B", 7, "BILASSE").
dico("B", 7, "BILATES").
dico("B", 7, "BILERAI").
dico("B", 7, "BILERAS").
dico("B", 7, "BILEREZ").
dico("B", 7, "BILEUSE").
dico("B", 7, "BILIEES").
dico("B", 7, "BILIEUX").
dico("B", 7, "BILIONS").
dico("B", 7, "BILLAGE").
dico("B", 7, "BILLAIS").
dico("B", 7, "BILLAIT").
dico("B", 7, "BILLANT").
dico("B", 7, "BILLARD").
dico("B", 7, "BILLEES").
dico("B", 7, "BILLENT").
dico("B", 7, "BILLERA").
dico("B", 7, "BILLETE").
dico("B", 7, "BILLETS").
dico("B", 7, "BILLIEZ").
dico("B", 7, "BILLION").
dico("B", 7, "BILLONS").
dico("B", 7, "BILLOTS").
dico("B", 7, "BILOBEE").
dico("B", 7, "BILOBES").
dico("B", 7, "BILOCAL").
dico("B", 7, "BILOQUA").
dico("B", 7, "BILOQUE").
dico("B", 7, "BIMANES").
dico("B", 7, "BIMETAL").
dico("B", 7, "BIMODAL").
dico("B", 7, "BINAGES").
dico("B", 7, "BINAIRE").
dico("B", 7, "BINAMES").
dico("B", 7, "BINARDS").
dico("B", 7, "BINARTS").
dico("B", 7, "BINASSE").
dico("B", 7, "BINATES").
dico("B", 7, "BINERAI").
dico("B", 7, "BINERAS").
dico("B", 7, "BINEREZ").
dico("B", 7, "BINERIE").
dico("B", 7, "BINETTE").
dico("B", 7, "BINEURS").
dico("B", 7, "BINEUSE").
dico("B", 7, "BINIONS").
dico("B", 7, "BINIOUS").
dico("B", 7, "BINOCLE").
dico("B", 7, "BINOMES").
dico("B", 7, "BINTJES").
dico("B", 7, "BIOCIDE").
dico("B", 7, "BIOGENE").
dico("B", 7, "BIOPSIE").
dico("B", 7, "BIOPUCE").
dico("B", 7, "BIOTINE").
dico("B", 7, "BIOTITE").
dico("B", 7, "BIOTOPE").
dico("B", 7, "BIOTYPE").
dico("B", 7, "BIOXYDE").
dico("B", 7, "BIPALES").
dico("B", 7, "BIPAMES").
dico("B", 7, "BIPARES").
dico("B", 7, "BIPARTI").
dico("B", 7, "BIPASSA").
dico("B", 7, "BIPASSE").
dico("B", 7, "BIPATES").
dico("B", 7, "BIPEDES").
dico("B", 7, "BIPEDIE").
dico("B", 7, "BIPENNE").
dico("B", 7, "BIPERAI").
dico("B", 7, "BIPERAS").
dico("B", 7, "BIPEREZ").
dico("B", 7, "BIPEURS").
dico("B", 7, "BIPHASE").
dico("B", 7, "BIPIEDS").
dico("B", 7, "BIPIONS").
dico("B", 7, "BIPLACE").
dico("B", 7, "BIPLANS").
dico("B", 7, "BIPOINT").
dico("B", 7, "BIPOLES").
dico("B", 7, "BIQUETS").
dico("B", 7, "BIRDIES").
dico("B", 7, "BIREMES").
dico("B", 7, "BIRIBIS").
dico("B", 7, "BIRMANE").
dico("B", 7, "BIRMANS").
dico("B", 7, "BIROTOR").
dico("B", 7, "BIROUTE").
dico("B", 7, "BISAMES").
dico("B", 7, "BISASSE").
dico("B", 7, "BISATES").
dico("B", 7, "BISCHOF").
dico("B", 7, "BISCOME").
dico("B", 7, "BISCOTO").
dico("B", 7, "BISCUIT").
dico("B", 7, "BISEAUX").
dico("B", 7, "BISERAI").
dico("B", 7, "BISERAS").
dico("B", 7, "BISEREZ").
dico("B", 7, "BISETTE").
dico("B", 7, "BISEXUE").
dico("B", 7, "BISHOPS").
dico("B", 7, "BISIONS").
dico("B", 7, "BISMUTH").
dico("B", 7, "BISONNE").
dico("B", 7, "BISQUAI").
dico("B", 7, "BISQUAS").
dico("B", 7, "BISQUAT").
dico("B", 7, "BISQUER").
dico("B", 7, "BISQUES").
dico("B", 7, "BISQUEZ").
dico("B", 7, "BISSACS").
dico("B", 7, "BISSAIS").
dico("B", 7, "BISSAIT").
dico("B", 7, "BISSANT").
dico("B", 7, "BISSEES").
dico("B", 7, "BISSELS").
dico("B", 7, "BISSENT").
dico("B", 7, "BISSERA").
dico("B", 7, "BISSEUR").
dico("B", 7, "BISSIEZ").
dico("B", 7, "BISSONS").
dico("B", 7, "BISTRAI").
dico("B", 7, "BISTRAS").
dico("B", 7, "BISTRAT").
dico("B", 7, "BISTREE").
dico("B", 7, "BISTRER").
dico("B", 7, "BISTRES").
dico("B", 7, "BISTREZ").
dico("B", 7, "BISTROS").
dico("B", 7, "BISTROT").
dico("B", 7, "BITAMES").
dico("B", 7, "BITASSE").
dico("B", 7, "BITATES").
dico("B", 7, "BITERAI").
dico("B", 7, "BITERAS").
dico("B", 7, "BITEREZ").
dico("B", 7, "BITIONS").
dico("B", 7, "BITONAL").
dico("B", 7, "BITORDS").
dico("B", 7, "BITTAIS").
dico("B", 7, "BITTAIT").
dico("B", 7, "BITTANT").
dico("B", 7, "BITTEES").
dico("B", 7, "BITTENT").
dico("B", 7, "BITTERA").
dico("B", 7, "BITTERS").
dico("B", 7, "BITTIEZ").
dico("B", 7, "BITTONS").
dico("B", 7, "BITTUES").
dico("B", 7, "BITTURA").
dico("B", 7, "BITTURE").
dico("B", 7, "BITUBES").
dico("B", 7, "BITUMAI").
dico("B", 7, "BITUMAS").
dico("B", 7, "BITUMAT").
dico("B", 7, "BITUMEE").
dico("B", 7, "BITUMER").
dico("B", 7, "BITUMES").
dico("B", 7, "BITUMEZ").
dico("B", 7, "BITURAI").
dico("B", 7, "BITURAS").
dico("B", 7, "BITURAT").
dico("B", 7, "BITUREE").
dico("B", 7, "BITURER").
dico("B", 7, "BITURES").
dico("B", 7, "BITUREZ").
dico("B", 7, "BIVALVE").
dico("B", 7, "BIVEAUX").
dico("B", 7, "BIVOUAC").
dico("B", 7, "BIZARRE").
dico("B", 7, "BIZNESS").
dico("B", 7, "BIZUTAI").
dico("B", 7, "BIZUTAS").
dico("B", 7, "BIZUTAT").
dico("B", 7, "BIZUTEE").
dico("B", 7, "BIZUTER").
dico("B", 7, "BIZUTES").
dico("B", 7, "BIZUTEZ").
dico("B", 7, "BIZUTHS").
dico("B", 7, "BLABLAS").
dico("B", 7, "BLAFARD").
dico("B", 7, "BLAGUAI").
dico("B", 7, "BLAGUAS").
dico("B", 7, "BLAGUAT").
dico("B", 7, "BLAGUEE").
dico("B", 7, "BLAGUER").
dico("B", 7, "BLAGUES").
dico("B", 7, "BLAGUEZ").
dico("B", 7, "BLAIRAI").
dico("B", 7, "BLAIRAS").
dico("B", 7, "BLAIRAT").
dico("B", 7, "BLAIREE").
dico("B", 7, "BLAIRER").
dico("B", 7, "BLAIRES").
dico("B", 7, "BLAIREZ").
dico("B", 7, "BLAMAGE").
dico("B", 7, "BLAMAIS").
dico("B", 7, "BLAMAIT").
dico("B", 7, "BLAMANT").
dico("B", 7, "BLAMEES").
dico("B", 7, "BLAMENT").
dico("B", 7, "BLAMERA").
dico("B", 7, "BLAMIEZ").
dico("B", 7, "BLAMONS").
dico("B", 7, "BLANCHE").
dico("B", 7, "BLANCHI").
dico("B", 7, "BLASAIS").
dico("B", 7, "BLASAIT").
dico("B", 7, "BLASANT").
dico("B", 7, "BLASEES").
dico("B", 7, "BLASENT").
dico("B", 7, "BLASERA").
dico("B", 7, "BLASIEZ").
dico("B", 7, "BLASONS").
dico("B", 7, "BLASTES").
dico("B", 7, "BLATERA").
dico("B", 7, "BLATERE").
dico("B", 7, "BLATTES").
dico("B", 7, "BLAZERS").
dico("B", 7, "BLECHES").
dico("B", 7, "BLEDARD").
dico("B", 7, "BLEMIES").
dico("B", 7, "BLEMIRA").
dico("B", 7, "BLENDES").
dico("B", 7, "BLENNIE").
dico("B", 7, "BLESAIS").
dico("B", 7, "BLESAIT").
dico("B", 7, "BLESANT").
dico("B", 7, "BLESENT").
dico("B", 7, "BLESERA").
dico("B", 7, "BLESIEZ").
dico("B", 7, "BLESITE").
dico("B", 7, "BLESOIS").
dico("B", 7, "BLESONS").
dico("B", 7, "BLESSAI").
dico("B", 7, "BLESSAS").
dico("B", 7, "BLESSAT").
dico("B", 7, "BLESSEE").
dico("B", 7, "BLESSER").
dico("B", 7, "BLESSES").
dico("B", 7, "BLESSEZ").
dico("B", 7, "BLETSAI").
dico("B", 7, "BLETSAS").
dico("B", 7, "BLETSAT").
dico("B", 7, "BLETSEE").
dico("B", 7, "BLETSER").
dico("B", 7, "BLETSES").
dico("B", 7, "BLETSEZ").
dico("B", 7, "BLETTES").
dico("B", 7, "BLETTIE").
dico("B", 7, "BLETTIR").
dico("B", 7, "BLETTIS").
dico("B", 7, "BLETTIT").
dico("B", 7, "BLEUETS").
dico("B", 7, "BLEUIES").
dico("B", 7, "BLEUIRA").
dico("B", 7, "BLEUTAI").
dico("B", 7, "BLEUTAS").
dico("B", 7, "BLEUTAT").
dico("B", 7, "BLEUTEE").
dico("B", 7, "BLEUTER").
dico("B", 7, "BLEUTES").
dico("B", 7, "BLEUTEZ").
dico("B", 7, "BLIAUDS").
dico("B", 7, "BLIAUTS").
dico("B", 7, "BLIBLIS").
dico("B", 7, "BLINDAI").
dico("B", 7, "BLINDAS").
dico("B", 7, "BLINDAT").
dico("B", 7, "BLINDEE").
dico("B", 7, "BLINDER").
dico("B", 7, "BLINDES").
dico("B", 7, "BLINDEZ").
dico("B", 7, "BLINQUA").
dico("B", 7, "BLINQUE").
dico("B", 7, "BLISTER").
dico("B", 7, "BLOCAGE").
dico("B", 7, "BLOCAUX").
dico("B", 7, "BLOCHET").
dico("B", 7, "BLONDEL").
dico("B", 7, "BLONDES").
dico("B", 7, "BLONDIE").
dico("B", 7, "BLONDIN").
dico("B", 7, "BLONDIR").
dico("B", 7, "BLONDIS").
dico("B", 7, "BLONDIT").
dico("B", 7, "BLOOMER").
dico("B", 7, "BLOQUAI").
dico("B", 7, "BLOQUAS").
dico("B", 7, "BLOQUAT").
dico("B", 7, "BLOQUEE").
dico("B", 7, "BLOQUER").
dico("B", 7, "BLOQUES").
dico("B", 7, "BLOQUEZ").
dico("B", 7, "BLOTTIE").
dico("B", 7, "BLOTTIR").
dico("B", 7, "BLOTTIS").
dico("B", 7, "BLOTTIT").
dico("B", 7, "BLOUSAI").
dico("B", 7, "BLOUSAS").
dico("B", 7, "BLOUSAT").
dico("B", 7, "BLOUSEE").
dico("B", 7, "BLOUSER").
dico("B", 7, "BLOUSES").
dico("B", 7, "BLOUSEZ").
dico("B", 7, "BLOUSON").
dico("B", 7, "BLOUSSE").
dico("B", 7, "BLUETTE").
dico("B", 7, "BLUFFAI").
dico("B", 7, "BLUFFAS").
dico("B", 7, "BLUFFAT").
dico("B", 7, "BLUFFEE").
dico("B", 7, "BLUFFER").
dico("B", 7, "BLUFFES").
dico("B", 7, "BLUFFEZ").
dico("B", 7, "BLUSHES").
dico("B", 7, "BLUTAGE").
dico("B", 7, "BLUTAIS").
dico("B", 7, "BLUTAIT").
dico("B", 7, "BLUTANT").
dico("B", 7, "BLUTEES").
dico("B", 7, "BLUTENT").
dico("B", 7, "BLUTERA").
dico("B", 7, "BLUTIEZ").
dico("B", 7, "BLUTOIR").
dico("B", 7, "BLUTONS").
dico("B", 7, "BOBARDS").
dico("B", 7, "BOBBIES").
dico("B", 7, "BOBECHE").
dico("B", 7, "BOBETTE").
dico("B", 7, "BOBEURS").
dico("B", 7, "BOBEUSE").
dico("B", 7, "BOBINAI").
dico("B", 7, "BOBINAS").
dico("B", 7, "BOBINAT").
dico("B", 7, "BOBINEE").
dico("B", 7, "BOBINER").
dico("B", 7, "BOBINES").
dico("B", 7, "BOBINEZ").
dico("B", 7, "BOBINOT").
dico("B", 7, "BOBONNE").
dico("B", 7, "BOBTAIL").
dico("B", 7, "BOCAGER").
dico("B", 7, "BOCAGES").
dico("B", 7, "BOCARDA").
dico("B", 7, "BOCARDE").
dico("B", 7, "BOCARDS").
dico("B", 7, "BODEGAS").
dico("B", 7, "BOEINGS").
dico("B", 7, "BOESSES").
dico("B", 7, "BOETTES").
dico("B", 7, "BOGGIES").
dico("B", 7, "BOGHEAD").
dico("B", 7, "BOGHEIS").
dico("B", 7, "BOGHEYS").
dico("B", 7, "BOGUEES").
dico("B", 7, "BOGUETS").
dico("B", 7, "BOHEMES").
dico("B", 7, "BOHRIUM").
dico("B", 7, "BOILERS").
dico("B", 7, "BOILLES").
dico("B", 7, "BOIRAIS").
dico("B", 7, "BOIRAIT").
dico("B", 7, "BOIRIEZ").
dico("B", 7, "BOIRONS").
dico("B", 7, "BOIRONT").
dico("B", 7, "BOISAGE").
dico("B", 7, "BOISAIS").
dico("B", 7, "BOISAIT").
dico("B", 7, "BOISANT").
dico("B", 7, "BOISEES").
dico("B", 7, "BOISENT").
dico("B", 7, "BOISERA").
dico("B", 7, "BOISEUR").
dico("B", 7, "BOISIEZ").
dico("B", 7, "BOISONS").
dico("B", 7, "BOISSON").
dico("B", 7, "BOITAIS").
dico("B", 7, "BOITAIT").
dico("B", 7, "BOITANT").
dico("B", 7, "BOITENT").
dico("B", 7, "BOITERA").
dico("B", 7, "BOITEUX").
dico("B", 7, "BOITIER").
dico("B", 7, "BOITIEZ").
dico("B", 7, "BOITONS").
dico("B", 7, "BOITTES").
dico("B", 7, "BOIVENT").
dico("B", 7, "BOLCHOS").
dico("B", 7, "BOLDUCS").
dico("B", 7, "BOLEROS").
dico("B", 7, "BOLIDES").
dico("B", 7, "BOLIERS").
dico("B", 7, "BOLIVAR").
dico("B", 7, "BOLLARD").
dico("B", 7, "BOMBAGE").
dico("B", 7, "BOMBAIS").
dico("B", 7, "BOMBAIT").
dico("B", 7, "BOMBANT").
dico("B", 7, "BOMBEES").
dico("B", 7, "BOMBENT").
dico("B", 7, "BOMBERA").
dico("B", 7, "BOMBEUR").
dico("B", 7, "BOMBIEZ").
dico("B", 7, "BOMBONS").
dico("B", 7, "BONACES").
dico("B", 7, "BONAMIA").
dico("B", 7, "BONARDE").
dico("B", 7, "BONARDS").
dico("B", 7, "BONASSE").
dico("B", 7, "BONBONS").
dico("B", 7, "BONDAGE").
dico("B", 7, "BONDAIS").
dico("B", 7, "BONDAIT").
dico("B", 7, "BONDANT").
dico("B", 7, "BONDEES").
dico("B", 7, "BONDENT").
dico("B", 7, "BONDERA").
dico("B", 7, "BONDIEZ").
dico("B", 7, "BONDIRA").
dico("B", 7, "BONDONS").
dico("B", 7, "BONDREE").
dico("B", 7, "BONGARE").
dico("B", 7, "BONHEUR").
dico("B", 7, "BONICHE").
dico("B", 7, "BONIFIA").
dico("B", 7, "BONIFIE").
dico("B", 7, "BONITES").
dico("B", 7, "BONJOUR").
dico("B", 7, "BONNARD").
dico("B", 7, "BONNETS").
dico("B", 7, "BONNOIS").
dico("B", 7, "BONOBOS").
dico("B", 7, "BONSAIS").
dico("B", 7, "BONSOIR").
dico("B", 7, "BOOGIES").
dico("B", 7, "BOOLEEN").
dico("B", 7, "BOOLIEN").
dico("B", 7, "BOOMERS").
dico("B", 7, "BOOSTAI").
dico("B", 7, "BOOSTAS").
dico("B", 7, "BOOSTAT").
dico("B", 7, "BOOSTEE").
dico("B", 7, "BOOSTER").
dico("B", 7, "BOOSTES").
dico("B", 7, "BOOSTEZ").
dico("B", 7, "BORAINE").
dico("B", 7, "BORAINS").
dico("B", 7, "BORANES").
dico("B", 7, "BORASSE").
dico("B", 7, "BORATEE").
dico("B", 7, "BORATES").
dico("B", 7, "BORDAGE").
dico("B", 7, "BORDAIS").
dico("B", 7, "BORDAIT").
dico("B", 7, "BORDANT").
dico("B", 7, "BORDEES").
dico("B", 7, "BORDELS").
dico("B", 7, "BORDENT").
dico("B", 7, "BORDERA").
dico("B", 7, "BORDIER").
dico("B", 7, "BORDIEZ").
dico("B", 7, "BORDONS").
dico("B", 7, "BORDURE").
dico("B", 7, "BOREALE").
dico("B", 7, "BOREALS").
dico("B", 7, "BOREAUX").
dico("B", 7, "BORGNES").
dico("B", 7, "BORINES").
dico("B", 7, "BORIQUE").
dico("B", 7, "BORNAGE").
dico("B", 7, "BORNAIS").
dico("B", 7, "BORNAIT").
dico("B", 7, "BORNANT").
dico("B", 7, "BORNEES").
dico("B", 7, "BORNENT").
dico("B", 7, "BORNERA").
dico("B", 7, "BORNIEZ").
dico("B", 7, "BORNOIE").
dico("B", 7, "BORNONS").
dico("B", 7, "BORNOYA").
dico("B", 7, "BORNOYE").
dico("B", 7, "BOROROS").
dico("B", 7, "BOROUGH").
dico("B", 7, "BORTSCH").
dico("B", 7, "BORURES").
dico("B", 7, "BOSCOTS").
dico("B", 7, "BOSCOYO").
dico("B", 7, "BOSKOOP").
dico("B", 7, "BOSNIEN").
dico("B", 7, "BOSQUET").
dico("B", 7, "BOSSAGE").
dico("B", 7, "BOSSAIS").
dico("B", 7, "BOSSAIT").
dico("B", 7, "BOSSANT").
dico("B", 7, "BOSSEES").
dico("B", 7, "BOSSELA").
dico("B", 7, "BOSSELE").
dico("B", 7, "BOSSENT").
dico("B", 7, "BOSSERA").
dico("B", 7, "BOSSEUR").
dico("B", 7, "BOSSIEZ").
dico("B", 7, "BOSSOIR").
dico("B", 7, "BOSSONS").
dico("B", 7, "BOSSUAI").
dico("B", 7, "BOSSUAS").
dico("B", 7, "BOSSUAT").
dico("B", 7, "BOSSUEE").
dico("B", 7, "BOSSUER").
dico("B", 7, "BOSSUES").
dico("B", 7, "BOSSUEZ").
dico("B", 7, "BOSTONS").
dico("B", 7, "BOTTAIS").
dico("B", 7, "BOTTAIT").
dico("B", 7, "BOTTANT").
dico("B", 7, "BOTTEES").
dico("B", 7, "BOTTELA").
dico("B", 7, "BOTTELE").
dico("B", 7, "BOTTENT").
dico("B", 7, "BOTTERA").
dico("B", 7, "BOTTEUR").
dico("B", 7, "BOTTIER").
dico("B", 7, "BOTTIEZ").
dico("B", 7, "BOTTINE").
dico("B", 7, "BOTTINS").
dico("B", 7, "BOTTONS").
dico("B", 7, "BOUBOUS").
dico("B", 7, "BOUCANA").
dico("B", 7, "BOUCANE").
dico("B", 7, "BOUCANS").
dico("B", 7, "BOUCAUD").
dico("B", 7, "BOUCAUT").
dico("B", 7, "BOUCAUX").
dico("B", 7, "BOUCHAI").
dico("B", 7, "BOUCHAS").
dico("B", 7, "BOUCHAT").
dico("B", 7, "BOUCHEE").
dico("B", 7, "BOUCHER").
dico("B", 7, "BOUCHES").
dico("B", 7, "BOUCHEZ").
dico("B", 7, "BOUCHON").
dico("B", 7, "BOUCHOT").
dico("B", 7, "BOUCLAI").
dico("B", 7, "BOUCLAS").
dico("B", 7, "BOUCLAT").
dico("B", 7, "BOUCLEE").
dico("B", 7, "BOUCLER").
dico("B", 7, "BOUCLES").
dico("B", 7, "BOUCLEZ").
dico("B", 7, "BOUCOTS").
dico("B", 7, "BOUDAIS").
dico("B", 7, "BOUDAIT").
dico("B", 7, "BOUDANT").
dico("B", 7, "BOUDDHA").
dico("B", 7, "BOUDEES").
dico("B", 7, "BOUDENT").
dico("B", 7, "BOUDERA").
dico("B", 7, "BOUDEUR").
dico("B", 7, "BOUDIEZ").
dico("B", 7, "BOUDINA").
dico("B", 7, "BOUDINE").
dico("B", 7, "BOUDINS").
dico("B", 7, "BOUDOIR").
dico("B", 7, "BOUDONS").
dico("B", 7, "BOUELAI").
dico("B", 7, "BOUELAS").
dico("B", 7, "BOUELAT").
dico("B", 7, "BOUELER").
dico("B", 7, "BOUELES").
dico("B", 7, "BOUELEZ").
dico("B", 7, "BOUETTE").
dico("B", 7, "BOUEURS").
dico("B", 7, "BOUEUSE").
dico("B", 7, "BOUFFAI").
dico("B", 7, "BOUFFAS").
dico("B", 7, "BOUFFAT").
dico("B", 7, "BOUFFEE").
dico("B", 7, "BOUFFER").
dico("B", 7, "BOUFFES").
dico("B", 7, "BOUFFEZ").
dico("B", 7, "BOUFFIE").
dico("B", 7, "BOUFFIR").
dico("B", 7, "BOUFFIS").
dico("B", 7, "BOUFFIT").
dico("B", 7, "BOUFFON").
dico("B", 7, "BOUGEAI").
dico("B", 7, "BOUGEAS").
dico("B", 7, "BOUGEAT").
dico("B", 7, "BOUGEES").
dico("B", 7, "BOUGENT").
dico("B", 7, "BOUGERA").
dico("B", 7, "BOUGIES").
dico("B", 7, "BOUGIEZ").
dico("B", 7, "BOUGNAT").
dico("B", 7, "BOUGONS").
dico("B", 7, "BOUGRAN").
dico("B", 7, "BOUGRES").
dico("B", 7, "BOUILLE").
dico("B", 7, "BOUILLI").
dico("B", 7, "BOUINAI").
dico("B", 7, "BOUINAS").
dico("B", 7, "BOUINAT").
dico("B", 7, "BOUINEE").
dico("B", 7, "BOUINER").
dico("B", 7, "BOUINES").
dico("B", 7, "BOUINEZ").
dico("B", 7, "BOUKHAS").
dico("B", 7, "BOULAIE").
dico("B", 7, "BOULAIS").
dico("B", 7, "BOULAIT").
dico("B", 7, "BOULANT").
dico("B", 7, "BOULDER").
dico("B", 7, "BOULEAU").
dico("B", 7, "BOULEES").
dico("B", 7, "BOULENT").
dico("B", 7, "BOULERA").
dico("B", 7, "BOULETE").
dico("B", 7, "BOULETS").
dico("B", 7, "BOULEUX").
dico("B", 7, "BOULIER").
dico("B", 7, "BOULIEZ").
dico("B", 7, "BOULINE").
dico("B", 7, "BOULINS").
dico("B", 7, "BOULOIR").
dico("B", 7, "BOULONS").
dico("B", 7, "BOULOTS").
dico("B", 7, "BOUMAIT").
dico("B", 7, "BOUMERA").
dico("B", 7, "BOUMEUR").
dico("B", 7, "BOUQUET").
dico("B", 7, "BOUQUIN").
dico("B", 7, "BOURBES").
dico("B", 7, "BOURBON").
dico("B", 7, "BOURDES").
dico("B", 7, "BOURDON").
dico("B", 7, "BOURGES").
dico("B", 7, "BOURRAI").
dico("B", 7, "BOURRAS").
dico("B", 7, "BOURRAT").
dico("B", 7, "BOURREE").
dico("B", 7, "BOURRER").
dico("B", 7, "BOURRES").
dico("B", 7, "BOURREZ").
dico("B", 7, "BOURRIN").
dico("B", 7, "BOURRUE").
dico("B", 7, "BOURRUS").
dico("B", 7, "BOURSES").
dico("B", 7, "BOUSAIS").
dico("B", 7, "BOUSAIT").
dico("B", 7, "BOUSANT").
dico("B", 7, "BOUSEES").
dico("B", 7, "BOUSENT").
dico("B", 7, "BOUSERA").
dico("B", 7, "BOUSEUX").
dico("B", 7, "BOUSIER").
dico("B", 7, "BOUSIEZ").
dico("B", 7, "BOUSINS").
dico("B", 7, "BOUSONS").
dico("B", 7, "BOUTADE").
dico("B", 7, "BOUTAIS").
dico("B", 7, "BOUTAIT").
dico("B", 7, "BOUTANT").
dico("B", 7, "BOUTEES").
dico("B", 7, "BOUTENT").
dico("B", 7, "BOUTERA").
dico("B", 7, "BOUTEUR").
dico("B", 7, "BOUTIEZ").
dico("B", 7, "BOUTOIR").
dico("B", 7, "BOUTONS").
dico("B", 7, "BOUTRES").
dico("B", 7, "BOUTURA").
dico("B", 7, "BOUTURE").
dico("B", 7, "BOUVETA").
dico("B", 7, "BOUVETE").
dico("B", 7, "BOUVETS").
dico("B", 7, "BOUVIER").
dico("B", 7, "BOUVRIL").
dico("B", 7, "BOVIDES").
dico("B", 7, "BOVINES").
dico("B", 7, "BOWETTE").
dico("B", 7, "BOWLING").
dico("B", 7, "BOXAMES").
dico("B", 7, "BOXASSE").
dico("B", 7, "BOXATES").
dico("B", 7, "BOXERAI").
dico("B", 7, "BOXERAS").
dico("B", 7, "BOXEREZ").
dico("B", 7, "BOXEURS").
dico("B", 7, "BOXEUSE").
dico("B", 7, "BOXIONS").
dico("B", 7, "BOYARDS").
dico("B", 7, "BOYAUTA").
dico("B", 7, "BOYAUTE").
dico("B", 7, "BOYCOTT").
dico("B", 7, "BRABANT").
dico("B", 7, "BRACTEE").
dico("B", 7, "BRADAGE").
dico("B", 7, "BRADAIS").
dico("B", 7, "BRADAIT").
dico("B", 7, "BRADANT").
dico("B", 7, "BRADEES").
dico("B", 7, "BRADELS").
dico("B", 7, "BRADENT").
dico("B", 7, "BRADERA").
dico("B", 7, "BRADEUR").
dico("B", 7, "BRADIEZ").
dico("B", 7, "BRADONS").
dico("B", 7, "BRADYPE").
dico("B", 7, "BRAGARD").
dico("B", 7, "BRAGUES").
dico("B", 7, "BRAHMAN").
dico("B", 7, "BRAHMIS").
dico("B", 7, "BRAIENT").
dico("B", 7, "BRAIERA").
dico("B", 7, "BRAILLA").
dico("B", 7, "BRAILLE").
dico("B", 7, "BRAIRAI").
dico("B", 7, "BRAIRAS").
dico("B", 7, "BRAIREZ").
dico("B", 7, "BRAISAI").
dico("B", 7, "BRAISAS").
dico("B", 7, "BRAISAT").
dico("B", 7, "BRAISEE").
dico("B", 7, "BRAISER").
dico("B", 7, "BRAISES").
dico("B", 7, "BRAISEZ").
dico("B", 7, "BRAMAIS").
dico("B", 7, "BRAMAIT").
dico("B", 7, "BRAMANT").
dico("B", 7, "BRAMEES").
dico("B", 7, "BRAMENT").
dico("B", 7, "BRAMERA").
dico("B", 7, "BRAMIEZ").
dico("B", 7, "BRAMONS").
dico("B", 7, "BRANCHA").
dico("B", 7, "BRANCHE").
dico("B", 7, "BRANCHU").
dico("B", 7, "BRANDES").
dico("B", 7, "BRANDIE").
dico("B", 7, "BRANDIR").
dico("B", 7, "BRANDIS").
dico("B", 7, "BRANDIT").
dico("B", 7, "BRANDON").
dico("B", 7, "BRANDYS").
dico("B", 7, "BRANLAI").
dico("B", 7, "BRANLAS").
dico("B", 7, "BRANLAT").
dico("B", 7, "BRANLEE").
dico("B", 7, "BRANLER").
dico("B", 7, "BRANLES").
dico("B", 7, "BRANLEZ").
dico("B", 7, "BRANQUE").
dico("B", 7, "BRANTES").
dico("B", 7, "BRAQUAI").
dico("B", 7, "BRAQUAS").
dico("B", 7, "BRAQUAT").
dico("B", 7, "BRAQUEE").
dico("B", 7, "BRAQUER").
dico("B", 7, "BRAQUES").
dico("B", 7, "BRAQUET").
dico("B", 7, "BRAQUEZ").
dico("B", 7, "BRASAGE").
dico("B", 7, "BRASAIS").
dico("B", 7, "BRASAIT").
dico("B", 7, "BRASANT").
dico("B", 7, "BRASEES").
dico("B", 7, "BRASENT").
dico("B", 7, "BRASERA").
dico("B", 7, "BRASERO").
dico("B", 7, "BRASIER").
dico("B", 7, "BRASIEZ").
dico("B", 7, "BRASONS").
dico("B", 7, "BRASQUA").
dico("B", 7, "BRASQUE").
dico("B", 7, "BRASSAI").
dico("B", 7, "BRASSAS").
dico("B", 7, "BRASSAT").
dico("B", 7, "BRASSEE").
dico("B", 7, "BRASSER").
dico("B", 7, "BRASSES").
dico("B", 7, "BRASSEZ").
dico("B", 7, "BRASSIN").
dico("B", 7, "BRASURE").
dico("B", 7, "BRAVADE").
dico("B", 7, "BRAVAIS").
dico("B", 7, "BRAVAIT").
dico("B", 7, "BRAVANT").
dico("B", 7, "BRAVEES").
dico("B", 7, "BRAVENT").
dico("B", 7, "BRAVERA").
dico("B", 7, "BRAVIEZ").
dico("B", 7, "BRAVONS").
dico("B", 7, "BRAYAIS").
dico("B", 7, "BRAYAIT").
dico("B", 7, "BRAYANT").
dico("B", 7, "BRAYEES").
dico("B", 7, "BRAYENT").
dico("B", 7, "BRAYERA").
dico("B", 7, "BRAYERS").
dico("B", 7, "BRAYIEZ").
dico("B", 7, "BRAYONS").
dico("B", 7, "BREAKAI").
dico("B", 7, "BREAKAS").
dico("B", 7, "BREAKAT").
dico("B", 7, "BREAKEE").
dico("B", 7, "BREAKER").
dico("B", 7, "BREAKES").
dico("B", 7, "BREAKEZ").
dico("B", 7, "BREANTS").
dico("B", 7, "BRECHES").
dico("B", 7, "BRECHET").
dico("B", 7, "BREEDER").
dico("B", 7, "BREGMAS").
dico("B", 7, "BRELAGE").
dico("B", 7, "BRELAIS").
dico("B", 7, "BRELAIT").
dico("B", 7, "BRELANS").
dico("B", 7, "BRELANT").
dico("B", 7, "BRELEES").
dico("B", 7, "BRELENT").
dico("B", 7, "BRELERA").
dico("B", 7, "BRELIEZ").
dico("B", 7, "BRELONS").
dico("B", 7, "BRESILS").
dico("B", 7, "BRESSAN").
dico("B", 7, "BRETONS").
dico("B", 7, "BRETTAI").
dico("B", 7, "BRETTAS").
dico("B", 7, "BRETTAT").
dico("B", 7, "BRETTEE").
dico("B", 7, "BRETTER").
dico("B", 7, "BRETTES").
dico("B", 7, "BRETTEZ").
dico("B", 7, "BRETZEL").
dico("B", 7, "BREUILS").
dico("B", 7, "BREVETA").
dico("B", 7, "BREVETE").
dico("B", 7, "BREVETS").
dico("B", 7, "BREVITE").
dico("B", 7, "BRIARDE").
dico("B", 7, "BRIARDS").
dico("B", 7, "BRICOLA").
dico("B", 7, "BRICOLE").
dico("B", 7, "BRIDAGE").
dico("B", 7, "BRIDAIS").
dico("B", 7, "BRIDAIT").
dico("B", 7, "BRIDANT").
dico("B", 7, "BRIDEES").
dico("B", 7, "BRIDENT").
dico("B", 7, "BRIDERA").
dico("B", 7, "BRIDGEA").
dico("B", 7, "BRIDGEE").
dico("B", 7, "BRIDGER").
dico("B", 7, "BRIDGES").
dico("B", 7, "BRIDGEZ").
dico("B", 7, "BRIDIEZ").
dico("B", 7, "BRIDONS").
dico("B", 7, "BRIEFAI").
dico("B", 7, "BRIEFAS").
dico("B", 7, "BRIEFAT").
dico("B", 7, "BRIEFEE").
dico("B", 7, "BRIEFER").
dico("B", 7, "BRIEFES").
dico("B", 7, "BRIEFEZ").
dico("B", 7, "BRIFFAI").
dico("B", 7, "BRIFFAS").
dico("B", 7, "BRIFFAT").
dico("B", 7, "BRIFFEE").
dico("B", 7, "BRIFFER").
dico("B", 7, "BRIFFES").
dico("B", 7, "BRIFFEZ").
dico("B", 7, "BRIGADE").
dico("B", 7, "BRIGAND").
dico("B", 7, "BRIGUAI").
dico("B", 7, "BRIGUAS").
dico("B", 7, "BRIGUAT").
dico("B", 7, "BRIGUEE").
dico("B", 7, "BRIGUER").
dico("B", 7, "BRIGUES").
dico("B", 7, "BRIGUEZ").
dico("B", 7, "BRILLAI").
dico("B", 7, "BRILLAS").
dico("B", 7, "BRILLAT").
dico("B", 7, "BRILLER").
dico("B", 7, "BRILLES").
dico("B", 7, "BRILLEZ").
dico("B", 7, "BRIMADE").
dico("B", 7, "BRIMAIS").
dico("B", 7, "BRIMAIT").
dico("B", 7, "BRIMANT").
dico("B", 7, "BRIMEES").
dico("B", 7, "BRIMENT").
dico("B", 7, "BRIMERA").
dico("B", 7, "BRIMIEZ").
dico("B", 7, "BRIMONS").
dico("B", 7, "BRINDES").
dico("B", 7, "BRINELL").
dico("B", 7, "BRINGEE").
dico("B", 7, "BRINGES").
dico("B", 7, "BRINGUA").
dico("B", 7, "BRINGUE").
dico("B", 7, "BRIOCHE").
dico("B", 7, "BRIQUAI").
dico("B", 7, "BRIQUAS").
dico("B", 7, "BRIQUAT").
dico("B", 7, "BRIQUEE").
dico("B", 7, "BRIQUER").
dico("B", 7, "BRIQUES").
dico("B", 7, "BRIQUET").
dico("B", 7, "BRIQUEZ").
dico("B", 7, "BRISAIS").
dico("B", 7, "BRISAIT").
dico("B", 7, "BRISANT").
dico("B", 7, "BRISEES").
dico("B", 7, "BRISENT").
dico("B", 7, "BRISERA").
dico("B", 7, "BRISEUR").
dico("B", 7, "BRISIEZ").
dico("B", 7, "BRISKAS").
dico("B", 7, "BRISONS").
dico("B", 7, "BRISQUE").
dico("B", 7, "BRISTOL").
dico("B", 7, "BRISURE").
dico("B", 7, "BRITISH").
dico("B", 7, "BROCARD").
dico("B", 7, "BROCART").
dico("B", 7, "BROCCIO").
dico("B", 7, "BROCCIU").
dico("B", 7, "BROCHAI").
dico("B", 7, "BROCHAS").
dico("B", 7, "BROCHAT").
dico("B", 7, "BROCHEE").
dico("B", 7, "BROCHER").
dico("B", 7, "BROCHES").
dico("B", 7, "BROCHET").
dico("B", 7, "BROCHEZ").
dico("B", 7, "BROCOLI").
dico("B", 7, "BRODAIS").
dico("B", 7, "BRODAIT").
dico("B", 7, "BRODANT").
dico("B", 7, "BRODEES").
dico("B", 7, "BRODENT").
dico("B", 7, "BRODERA").
dico("B", 7, "BRODEUR").
dico("B", 7, "BRODIEZ").
dico("B", 7, "BRODONS").
dico("B", 7, "BROIENT").
dico("B", 7, "BROIERA").
dico("B", 7, "BROIGNE").
dico("B", 7, "BROKERS").
dico("B", 7, "BROMATE").
dico("B", 7, "BROMEES").
dico("B", 7, "BROMURE").
dico("B", 7, "BRONCAS").
dico("B", 7, "BRONCHA").
dico("B", 7, "BRONCHE").
dico("B", 7, "BRONZAI").
dico("B", 7, "BRONZAS").
dico("B", 7, "BRONZAT").
dico("B", 7, "BRONZEE").
dico("B", 7, "BRONZER").
dico("B", 7, "BRONZES").
dico("B", 7, "BRONZEZ").
dico("B", 7, "BROSSAI").
dico("B", 7, "BROSSAS").
dico("B", 7, "BROSSAT").
dico("B", 7, "BROSSEE").
dico("B", 7, "BROSSER").
dico("B", 7, "BROSSES").
dico("B", 7, "BROSSEZ").
dico("B", 7, "BROUETS").
dico("B", 7, "BROUSSE").
dico("B", 7, "BROUTAI").
dico("B", 7, "BROUTAS").
dico("B", 7, "BROUTAT").
dico("B", 7, "BROUTEE").
dico("B", 7, "BROUTER").
dico("B", 7, "BROUTES").
dico("B", 7, "BROUTEZ").
dico("B", 7, "BROWNIE").
dico("B", 7, "BROYAGE").
dico("B", 7, "BROYAIS").
dico("B", 7, "BROYAIT").
dico("B", 7, "BROYANT").
dico("B", 7, "BROYATS").
dico("B", 7, "BROYEES").
dico("B", 7, "BROYEUR").
dico("B", 7, "BROYIEZ").
dico("B", 7, "BROYONS").
dico("B", 7, "BRUANTS").
dico("B", 7, "BRUCCIO").
dico("B", 7, "BRUCHES").
dico("B", 7, "BRUCINE").
dico("B", 7, "BRUGNON").
dico("B", 7, "BRUIMES").
dico("B", 7, "BRUINAT").
dico("B", 7, "BRUINER").
dico("B", 7, "BRUINES").
dico("B", 7, "BRUIRAI").
dico("B", 7, "BRUIRAS").
dico("B", 7, "BRUIREZ").
dico("B", 7, "BRUISSA").
dico("B", 7, "BRUISSE").
dico("B", 7, "BRUITAI").
dico("B", 7, "BRUITAS").
dico("B", 7, "BRUITAT").
dico("B", 7, "BRUITEE").
dico("B", 7, "BRUITER").
dico("B", 7, "BRUITES").
dico("B", 7, "BRUITEZ").
dico("B", 7, "BRULAGE").
dico("B", 7, "BRULAIS").
dico("B", 7, "BRULAIT").
dico("B", 7, "BRULANT").
dico("B", 7, "BRULEES").
dico("B", 7, "BRULENT").
dico("B", 7, "BRULERA").
dico("B", 7, "BRULEUR").
dico("B", 7, "BRULIEZ").
dico("B", 7, "BRULOIR").
dico("B", 7, "BRULONS").
dico("B", 7, "BRULOTS").
dico("B", 7, "BRULURE").
dico("B", 7, "BRUMAIT").
dico("B", 7, "BRUMERA").
dico("B", 7, "BRUMEUX").
dico("B", 7, "BRUNCHA").
dico("B", 7, "BRUNCHE").
dico("B", 7, "BRUNCHS").
dico("B", 7, "BRUNETS").
dico("B", 7, "BRUNIES").
dico("B", 7, "BRUNIRA").
dico("B", 7, "BRUSQUA").
dico("B", 7, "BRUSQUE").
dico("B", 7, "BRUTALE").
dico("B", 7, "BRUTAUX").
dico("B", 7, "BRUTION").
dico("B", 7, "BRUYANT").
dico("B", 7, "BRUYERE").
dico("B", 7, "BRYONES").
dico("B", 7, "BUBALES").
dico("B", 7, "BUCCALE").
dico("B", 7, "BUCCAUX").
dico("B", 7, "BUCCINS").
dico("B", 7, "BUCHAIS").
dico("B", 7, "BUCHAIT").
dico("B", 7, "BUCHANT").
dico("B", 7, "BUCHEES").
dico("B", 7, "BUCHENT").
dico("B", 7, "BUCHERA").
dico("B", 7, "BUCHERS").
dico("B", 7, "BUCHEUR").
dico("B", 7, "BUCHIEZ").
dico("B", 7, "BUCHONS").
dico("B", 7, "BUCRANE").
dico("B", 7, "BUDGETA").
dico("B", 7, "BUDGETE").
dico("B", 7, "BUDGETS").
dico("B", 7, "BUFFERS").
dico("B", 7, "BUFFETS").
dico("B", 7, "BUFFLAI").
dico("B", 7, "BUFFLAS").
dico("B", 7, "BUFFLAT").
dico("B", 7, "BUFFLEE").
dico("B", 7, "BUFFLER").
dico("B", 7, "BUFFLES").
dico("B", 7, "BUFFLEZ").
dico("B", 7, "BUFFLON").
dico("B", 7, "BUGAKUS").
dico("B", 7, "BUGGEES").
dico("B", 7, "BUGGIES").
dico("B", 7, "BUGRANE").
dico("B", 7, "BUISSON").
dico("B", 7, "BULBEUX").
dico("B", 7, "BULGARE").
dico("B", 7, "BULLAIS").
dico("B", 7, "BULLAIT").
dico("B", 7, "BULLANT").
dico("B", 7, "BULLDOG").
dico("B", 7, "BULLEES").
dico("B", 7, "BULLENT").
dico("B", 7, "BULLERA").
dico("B", 7, "BULLEUX").
dico("B", 7, "BULLIEZ").
dico("B", 7, "BULLONS").
dico("B", 7, "BUNKERS").
dico("B", 7, "BUNRAKU").
dico("B", 7, "BUQUAIS").
dico("B", 7, "BUQUAIT").
dico("B", 7, "BUQUANT").
dico("B", 7, "BUQUEES").
dico("B", 7, "BUQUENT").
dico("B", 7, "BUQUERA").
dico("B", 7, "BUQUIEZ").
dico("B", 7, "BUQUONS").
dico("B", 7, "BURATIN").
dico("B", 7, "BUREAUX").
dico("B", 7, "BURELEE").
dico("B", 7, "BURELES").
dico("B", 7, "BURELLE").
dico("B", 7, "BURETTE").
dico("B", 7, "BURGAUX").
dico("B", 7, "BURGERS").
dico("B", 7, "BURGIEN").
dico("B", 7, "BURINAI").
dico("B", 7, "BURINAS").
dico("B", 7, "BURINAT").
dico("B", 7, "BURINEE").
dico("B", 7, "BURINER").
dico("B", 7, "BURINES").
dico("B", 7, "BURINEZ").
dico("B", 7, "BURLATS").
dico("B", 7, "BURMESE").
dico("B", 7, "BURNOUS").
dico("B", 7, "BURSITE").
dico("B", 7, "BUSAMES").
dico("B", 7, "BUSARDS").
dico("B", 7, "BUSASSE").
dico("B", 7, "BUSATES").
dico("B", 7, "BUSERAI").
dico("B", 7, "BUSERAS").
dico("B", 7, "BUSEREZ").
dico("B", 7, "BUSETTE").
dico("B", 7, "BUSHIDO").
dico("B", 7, "BUSHMAN").
dico("B", 7, "BUSHMEN").
dico("B", 7, "BUSIONS").
dico("B", 7, "BUSQUAI").
dico("B", 7, "BUSQUAS").
dico("B", 7, "BUSQUAT").
dico("B", 7, "BUSQUEE").
dico("B", 7, "BUSQUER").
dico("B", 7, "BUSQUES").
dico("B", 7, "BUSQUEZ").
dico("B", 7, "BUSSENT").
dico("B", 7, "BUSSIEZ").
dico("B", 7, "BUSTIER").
dico("B", 7, "BUTAMES").
dico("B", 7, "BUTANES").
dico("B", 7, "BUTANOL").
dico("B", 7, "BUTASSE").
dico("B", 7, "BUTATES").
dico("B", 7, "BUTENES").
dico("B", 7, "BUTERAI").
dico("B", 7, "BUTERAS").
dico("B", 7, "BUTEREZ").
dico("B", 7, "BUTEURS").
dico("B", 7, "BUTEUSE").
dico("B", 7, "BUTINAI").
dico("B", 7, "BUTINAS").
dico("B", 7, "BUTINAT").
dico("B", 7, "BUTINEE").
dico("B", 7, "BUTINER").
dico("B", 7, "BUTINES").
dico("B", 7, "BUTINEZ").
dico("B", 7, "BUTIONS").
dico("B", 7, "BUTOIRS").
dico("B", 7, "BUTOMES").
dico("B", 7, "BUTORDE").
dico("B", 7, "BUTTAGE").
dico("B", 7, "BUTTAIS").
dico("B", 7, "BUTTAIT").
dico("B", 7, "BUTTANT").
dico("B", 7, "BUTTEES").
dico("B", 7, "BUTTENT").
dico("B", 7, "BUTTERA").
dico("B", 7, "BUTTEUR").
dico("B", 7, "BUTTIEZ").
dico("B", 7, "BUTTOIR").
dico("B", 7, "BUTTONS").
dico("B", 7, "BUTYLES").
dico("B", 7, "BUVABLE").
dico("B", 7, "BUVANTS").
dico("B", 7, "BUVARDS").
dico("B", 7, "BUVETTE").
dico("B", 7, "BUVEURS").
dico("B", 7, "BUVEUSE").
dico("B", 7, "BUVIONS").
dico("B", 7, "BUXACEE").
dico("B", 7, "BUZUKIS").
dico("B", 7, "BUZZERS").
dico("B", 7, "BYLINES").
