dico("B", 8, "BAASISME").
dico("B", 8, "BAASISTE").
dico("B", 8, "BABALLES").
dico("B", 8, "BABEURRE").
dico("B", 8, "BABILLAI").
dico("B", 8, "BABILLAS").
dico("B", 8, "BABILLAT").
dico("B", 8, "BABILLER").
dico("B", 8, "BABILLES").
dico("B", 8, "BABILLEZ").
dico("B", 8, "BABIOLES").
dico("B", 8, "BABISMES").
dico("B", 8, "BABOLAIS").
dico("B", 8, "BABOLAIT").
dico("B", 8, "BABOLANT").
dico("B", 8, "BABOLENT").
dico("B", 8, "BABOLERA").
dico("B", 8, "BABOLIEZ").
dico("B", 8, "BABOLONS").
dico("B", 8, "BABOUCHE").
dico("B", 8, "BABOUINE").
dico("B", 8, "BABOUINS").
dico("B", 8, "BABOUNES").
dico("B", 8, "BACANTES").
dico("B", 8, "BACCARAS").
dico("B", 8, "BACCARAT").
dico("B", 8, "BACHAGES").
dico("B", 8, "BACHAMES").
dico("B", 8, "BACHASSE").
dico("B", 8, "BACHATES").
dico("B", 8, "BACHERAI").
dico("B", 8, "BACHERAS").
dico("B", 8, "BACHEREZ").
dico("B", 8, "BACHIONS").
dico("B", 8, "BACHIQUE").
dico("B", 8, "BACHOLLE").
dico("B", 8, "BACHOTAI").
dico("B", 8, "BACHOTAS").
dico("B", 8, "BACHOTAT").
dico("B", 8, "BACHOTEE").
dico("B", 8, "BACHOTER").
dico("B", 8, "BACHOTES").
dico("B", 8, "BACHOTEZ").
dico("B", 8, "BACHOTTE").
dico("B", 8, "BACILLES").
dico("B", 8, "BACLAGES").
dico("B", 8, "BACLAMES").
dico("B", 8, "BACLASSE").
dico("B", 8, "BACLATES").
dico("B", 8, "BACLERAI").
dico("B", 8, "BACLERAS").
dico("B", 8, "BACLEREZ").
dico("B", 8, "BACLEURS").
dico("B", 8, "BACLEUSE").
dico("B", 8, "BACLIONS").
dico("B", 8, "BACONIEN").
dico("B", 8, "BACTERIE").
dico("B", 8, "BADABOUM").
dico("B", 8, "BADAIENT").
dico("B", 8, "BADAMIER").
dico("B", 8, "BADASSES").
dico("B", 8, "BADAUDAI").
dico("B", 8, "BADAUDAS").
dico("B", 8, "BADAUDAT").
dico("B", 8, "BADAUDER").
dico("B", 8, "BADAUDES").
dico("B", 8, "BADAUDEZ").
dico("B", 8, "BADECHES").
dico("B", 8, "BADERAIS").
dico("B", 8, "BADERAIT").
dico("B", 8, "BADERENT").
dico("B", 8, "BADERIEZ").
dico("B", 8, "BADERNES").
dico("B", 8, "BADERONS").
dico("B", 8, "BADERONT").
dico("B", 8, "BADGEAIS").
dico("B", 8, "BADGEAIT").
dico("B", 8, "BADGEANT").
dico("B", 8, "BADGEONS").
dico("B", 8, "BADGERAI").
dico("B", 8, "BADGERAS").
dico("B", 8, "BADGEREZ").
dico("B", 8, "BADGEUSE").
dico("B", 8, "BADGIONS").
dico("B", 8, "BADIANES").
dico("B", 8, "BADIGEON").
dico("B", 8, "BADINAGE").
dico("B", 8, "BADINAIS").
dico("B", 8, "BADINAIT").
dico("B", 8, "BADINANT").
dico("B", 8, "BADINENT").
dico("B", 8, "BADINERA").
dico("B", 8, "BADINIEZ").
dico("B", 8, "BADINONS").
dico("B", 8, "BADLANDS").
dico("B", 8, "BADOISES").
dico("B", 8, "BAESINES").
dico("B", 8, "BAFFAMES").
dico("B", 8, "BAFFASSE").
dico("B", 8, "BAFFATES").
dico("B", 8, "BAFFERAI").
dico("B", 8, "BAFFERAS").
dico("B", 8, "BAFFEREZ").
dico("B", 8, "BAFFIONS").
dico("B", 8, "BAFOUAIS").
dico("B", 8, "BAFOUAIT").
dico("B", 8, "BAFOUANT").
dico("B", 8, "BAFOUEES").
dico("B", 8, "BAFOUENT").
dico("B", 8, "BAFOUERA").
dico("B", 8, "BAFOUIEZ").
dico("B", 8, "BAFOUONS").
dico("B", 8, "BAFRAMES").
dico("B", 8, "BAFRASSE").
dico("B", 8, "BAFRATES").
dico("B", 8, "BAFRERAI").
dico("B", 8, "BAFRERAS").
dico("B", 8, "BAFREREZ").
dico("B", 8, "BAFREURS").
dico("B", 8, "BAFREUSE").
dico("B", 8, "BAFRIONS").
dico("B", 8, "BAGARRAI").
dico("B", 8, "BAGARRAS").
dico("B", 8, "BAGARRAT").
dico("B", 8, "BAGARREE").
dico("B", 8, "BAGARRER").
dico("B", 8, "BAGARRES").
dico("B", 8, "BAGARREZ").
dico("B", 8, "BAGASSES").
dico("B", 8, "BAGAUDES").
dico("B", 8, "BAGAYOUS").
dico("B", 8, "BAGNARDE").
dico("B", 8, "BAGNARDS").
dico("B", 8, "BAGNOLES").
dico("B", 8, "BAGUAGES").
dico("B", 8, "BAGUAMES").
dico("B", 8, "BAGUASSE").
dico("B", 8, "BAGUATES").
dico("B", 8, "BAGUERAI").
dico("B", 8, "BAGUERAS").
dico("B", 8, "BAGUEREZ").
dico("B", 8, "BAGUETTE").
dico("B", 8, "BAGUIERS").
dico("B", 8, "BAGUIONS").
dico("B", 8, "BAHAISME").
dico("B", 8, "BAHAMEEN").
dico("B", 8, "BAHAMIEN").
dico("B", 8, "BAHREINI").
dico("B", 8, "BAHUTAGE").
dico("B", 8, "BAIERAIS").
dico("B", 8, "BAIERAIT").
dico("B", 8, "BAIERIEZ").
dico("B", 8, "BAIERONS").
dico("B", 8, "BAIERONT").
dico("B", 8, "BAIGNADE").
dico("B", 8, "BAIGNAIS").
dico("B", 8, "BAIGNAIT").
dico("B", 8, "BAIGNANT").
dico("B", 8, "BAIGNEES").
dico("B", 8, "BAIGNENT").
dico("B", 8, "BAIGNERA").
dico("B", 8, "BAIGNEUR").
dico("B", 8, "BAIGNIEZ").
dico("B", 8, "BAIGNONS").
dico("B", 8, "BAILLAIS").
dico("B", 8, "BAILLAIT").
dico("B", 8, "BAILLANT").
dico("B", 8, "BAILLEES").
dico("B", 8, "BAILLENT").
dico("B", 8, "BAILLERA").
dico("B", 8, "BAILLEUR").
dico("B", 8, "BAILLIES").
dico("B", 8, "BAILLIEZ").
dico("B", 8, "BAILLIVE").
dico("B", 8, "BAILLONS").
dico("B", 8, "BAIOQUES").
dico("B", 8, "BAISABLE").
dico("B", 8, "BAISAMES").
dico("B", 8, "BAISASSE").
dico("B", 8, "BAISATES").
dico("B", 8, "BAISERAI").
dico("B", 8, "BAISERAS").
dico("B", 8, "BAISEREZ").
dico("B", 8, "BAISEURS").
dico("B", 8, "BAISEUSE").
dico("B", 8, "BAISIONS").
dico("B", 8, "BAISOTAI").
dico("B", 8, "BAISOTAS").
dico("B", 8, "BAISOTAT").
dico("B", 8, "BAISOTEE").
dico("B", 8, "BAISOTER").
dico("B", 8, "BAISOTES").
dico("B", 8, "BAISOTEZ").
dico("B", 8, "BAISSAIS").
dico("B", 8, "BAISSAIT").
dico("B", 8, "BAISSANT").
dico("B", 8, "BAISSEES").
dico("B", 8, "BAISSENT").
dico("B", 8, "BAISSERA").
dico("B", 8, "BAISSIER").
dico("B", 8, "BAISSIEZ").
dico("B", 8, "BAISSONS").
dico("B", 8, "BAISURES").
dico("B", 8, "BAJOCIEN").
dico("B", 8, "BAJOYERS").
dico("B", 8, "BAKCHICH").
dico("B", 8, "BAKELITE").
dico("B", 8, "BAKEOFES").
dico("B", 8, "BAKLAVAS").
dico("B", 8, "BALADAIS").
dico("B", 8, "BALADAIT").
dico("B", 8, "BALADANT").
dico("B", 8, "BALADEES").
dico("B", 8, "BALADENT").
dico("B", 8, "BALADERA").
dico("B", 8, "BALADEUR").
dico("B", 8, "BALADIEZ").
dico("B", 8, "BALADINE").
dico("B", 8, "BALADINS").
dico("B", 8, "BALADONS").
dico("B", 8, "BALAFONS").
dico("B", 8, "BALAFRAI").
dico("B", 8, "BALAFRAS").
dico("B", 8, "BALAFRAT").
dico("B", 8, "BALAFREE").
dico("B", 8, "BALAFRER").
dico("B", 8, "BALAFRES").
dico("B", 8, "BALAFREZ").
dico("B", 8, "BALAIENT").
dico("B", 8, "BALAIERA").
dico("B", 8, "BALAISES").
dico("B", 8, "BALANCAI").
dico("B", 8, "BALANCAS").
dico("B", 8, "BALANCAT").
dico("B", 8, "BALANCEE").
dico("B", 8, "BALANCER").
dico("B", 8, "BALANCES").
dico("B", 8, "BALANCEZ").
dico("B", 8, "BALANDRE").
dico("B", 8, "BALANITE").
dico("B", 8, "BALATUMS").
dico("B", 8, "BALAYAGE").
dico("B", 8, "BALAYAIS").
dico("B", 8, "BALAYAIT").
dico("B", 8, "BALAYANT").
dico("B", 8, "BALAYEES").
dico("B", 8, "BALAYENT").
dico("B", 8, "BALAYERA").
dico("B", 8, "BALAYEUR").
dico("B", 8, "BALAYIEZ").
dico("B", 8, "BALAYONS").
dico("B", 8, "BALBUTIA").
dico("B", 8, "BALBUTIE").
dico("B", 8, "BALEARES").
dico("B", 8, "BALEINEE").
dico("B", 8, "BALEINES").
dico("B", 8, "BALENIDE").
dico("B", 8, "BALEVRES").
dico("B", 8, "BALINAIS").
dico("B", 8, "BALISAGE").
dico("B", 8, "BALISAIS").
dico("B", 8, "BALISAIT").
dico("B", 8, "BALISANT").
dico("B", 8, "BALISEES").
dico("B", 8, "BALISENT").
dico("B", 8, "BALISERA").
dico("B", 8, "BALISEUR").
dico("B", 8, "BALISIER").
dico("B", 8, "BALISIEZ").
dico("B", 8, "BALISONS").
dico("B", 8, "BALISTES").
dico("B", 8, "BALIVAGE").
dico("B", 8, "BALIVAIS").
dico("B", 8, "BALIVAIT").
dico("B", 8, "BALIVANT").
dico("B", 8, "BALIVEAU").
dico("B", 8, "BALIVEES").
dico("B", 8, "BALIVENT").
dico("B", 8, "BALIVERA").
dico("B", 8, "BALIVIEZ").
dico("B", 8, "BALIVONS").
dico("B", 8, "BALLADES").
dico("B", 8, "BALLAMES").
dico("B", 8, "BALLANTE").
dico("B", 8, "BALLANTS").
dico("B", 8, "BALLASSE").
dico("B", 8, "BALLASTA").
dico("B", 8, "BALLASTE").
dico("B", 8, "BALLASTS").
dico("B", 8, "BALLATES").
dico("B", 8, "BALLERAI").
dico("B", 8, "BALLERAS").
dico("B", 8, "BALLEREZ").
dico("B", 8, "BALLIONS").
dico("B", 8, "BALLONNA").
dico("B", 8, "BALLONNE").
dico("B", 8, "BALLOTES").
dico("B", 8, "BALLOTIN").
dico("B", 8, "BALLOTTA").
dico("B", 8, "BALLOTTE").
dico("B", 8, "BALOISES").
dico("B", 8, "BALOURDE").
dico("B", 8, "BALOURDS").
dico("B", 8, "BALTIQUE").
dico("B", 8, "BALUCHON").
dico("B", 8, "BALUSTRE").
dico("B", 8, "BALZANES").
dico("B", 8, "BAMAKOIS").
dico("B", 8, "BAMBARAS").
dico("B", 8, "BAMBINES").
dico("B", 8, "BAMBOCHA").
dico("B", 8, "BAMBOCHE").
dico("B", 8, "BAMBOULA").
dico("B", 8, "BANALISA").
dico("B", 8, "BANALISE").
dico("B", 8, "BANALITE").
dico("B", 8, "BANANAIS").
dico("B", 8, "BANANAIT").
dico("B", 8, "BANANANT").
dico("B", 8, "BANANEES").
dico("B", 8, "BANANENT").
dico("B", 8, "BANANERA").
dico("B", 8, "BANANIER").
dico("B", 8, "BANANIEZ").
dico("B", 8, "BANANONS").
dico("B", 8, "BANCABLE").
dico("B", 8, "BANCAIRE").
dico("B", 8, "BANCALES").
dico("B", 8, "BANCHAGE").
dico("B", 8, "BANCHAIS").
dico("B", 8, "BANCHAIT").
dico("B", 8, "BANCHANT").
dico("B", 8, "BANCHEES").
dico("B", 8, "BANCHENT").
dico("B", 8, "BANCHERA").
dico("B", 8, "BANCHIEZ").
dico("B", 8, "BANCHONS").
dico("B", 8, "BANCOULS").
dico("B", 8, "BANDAGES").
dico("B", 8, "BANDAMES").
dico("B", 8, "BANDANAS").
dico("B", 8, "BANDANTE").
dico("B", 8, "BANDANTS").
dico("B", 8, "BANDASSE").
dico("B", 8, "BANDATES").
dico("B", 8, "BANDEAUX").
dico("B", 8, "BANDERAI").
dico("B", 8, "BANDERAS").
dico("B", 8, "BANDEREZ").
dico("B", 8, "BANDIERE").
dico("B", 8, "BANDIONS").
dico("B", 8, "BANGIEES").
dico("B", 8, "BANLIEUE").
dico("B", 8, "BANNERET").
dico("B", 8, "BANNETON").
dico("B", 8, "BANNETTE").
dico("B", 8, "BANNIERE").
dico("B", 8, "BANNIMES").
dico("B", 8, "BANNIRAI").
dico("B", 8, "BANNIRAS").
dico("B", 8, "BANNIREZ").
dico("B", 8, "BANNISSE").
dico("B", 8, "BANNITES").
dico("B", 8, "BANQUAIS").
dico("B", 8, "BANQUAIT").
dico("B", 8, "BANQUANT").
dico("B", 8, "BANQUEES").
dico("B", 8, "BANQUENT").
dico("B", 8, "BANQUERA").
dico("B", 8, "BANQUETA").
dico("B", 8, "BANQUETE").
dico("B", 8, "BANQUETS").
dico("B", 8, "BANQUIER").
dico("B", 8, "BANQUIEZ").
dico("B", 8, "BANQUISE").
dico("B", 8, "BANQUONS").
dico("B", 8, "BANTOUES").
dico("B", 8, "BAPTEMES").
dico("B", 8, "BAPTISAI").
dico("B", 8, "BAPTISAS").
dico("B", 8, "BAPTISAT").
dico("B", 8, "BAPTISEE").
dico("B", 8, "BAPTISER").
dico("B", 8, "BAPTISES").
dico("B", 8, "BAPTISEZ").
dico("B", 8, "BAPTISME").
dico("B", 8, "BAPTISTE").
dico("B", 8, "BAQUAMES").
dico("B", 8, "BAQUASSE").
dico("B", 8, "BAQUATES").
dico("B", 8, "BAQUERAI").
dico("B", 8, "BAQUERAS").
dico("B", 8, "BAQUEREZ").
dico("B", 8, "BAQUETAI").
dico("B", 8, "BAQUETAS").
dico("B", 8, "BAQUETAT").
dico("B", 8, "BAQUETEE").
dico("B", 8, "BAQUETER").
dico("B", 8, "BAQUETES").
dico("B", 8, "BAQUETEZ").
dico("B", 8, "BAQUETTE").
dico("B", 8, "BAQUIONS").
dico("B", 8, "BARAQUAI").
dico("B", 8, "BARAQUAS").
dico("B", 8, "BARAQUAT").
dico("B", 8, "BARAQUEE").
dico("B", 8, "BARAQUER").
dico("B", 8, "BARAQUES").
dico("B", 8, "BARAQUEZ").
dico("B", 8, "BARATINA").
dico("B", 8, "BARATINE").
dico("B", 8, "BARATINS").
dico("B", 8, "BARATTAI").
dico("B", 8, "BARATTAS").
dico("B", 8, "BARATTAT").
dico("B", 8, "BARATTEE").
dico("B", 8, "BARATTER").
dico("B", 8, "BARATTES").
dico("B", 8, "BARATTEZ").
dico("B", 8, "BARBAMES").
dico("B", 8, "BARBANTE").
dico("B", 8, "BARBANTS").
dico("B", 8, "BARBAQUE").
dico("B", 8, "BARBARES").
dico("B", 8, "BARBARIE").
dico("B", 8, "BARBASSE").
dico("B", 8, "BARBATES").
dico("B", 8, "BARBEAUX").
dico("B", 8, "BARBECUE").
dico("B", 8, "BARBELEE").
dico("B", 8, "BARBELES").
dico("B", 8, "BARBERAI").
dico("B", 8, "BARBERAS").
dico("B", 8, "BARBEREZ").
dico("B", 8, "BARBETTE").
dico("B", 8, "BARBICHE").
dico("B", 8, "BARBICHU").
dico("B", 8, "BARBIERE").
dico("B", 8, "BARBIERS").
dico("B", 8, "BARBIFIA").
dico("B", 8, "BARBIFIE").
dico("B", 8, "BARBILLE").
dico("B", 8, "BARBIONS").
dico("B", 8, "BARBITAL").
dico("B", 8, "BARBOTAI").
dico("B", 8, "BARBOTAS").
dico("B", 8, "BARBOTAT").
dico("B", 8, "BARBOTEE").
dico("B", 8, "BARBOTER").
dico("B", 8, "BARBOTES").
dico("B", 8, "BARBOTEZ").
dico("B", 8, "BARBOTIN").
dico("B", 8, "BARBOTTE").
dico("B", 8, "BARBOUZE").
dico("B", 8, "BARBULES").
dico("B", 8, "BARCASSE").
dico("B", 8, "BARDAGES").
dico("B", 8, "BARDAMES").
dico("B", 8, "BARDANES").
dico("B", 8, "BARDASSA").
dico("B", 8, "BARDASSE").
dico("B", 8, "BARDATES").
dico("B", 8, "BARDEAUX").
dico("B", 8, "BARDELLE").
dico("B", 8, "BARDERAI").
dico("B", 8, "BARDERAS").
dico("B", 8, "BARDEREZ").
dico("B", 8, "BARDIONS").
dico("B", 8, "BAREFOOT").
dico("B", 8, "BARETAIS").
dico("B", 8, "BARETAIT").
dico("B", 8, "BARETANT").
dico("B", 8, "BARETENT").
dico("B", 8, "BARETERA").
dico("B", 8, "BARETIEZ").
dico("B", 8, "BARETONS").
dico("B", 8, "BARIBALS").
dico("B", 8, "BARILLET").
dico("B", 8, "BARIOLAI").
dico("B", 8, "BARIOLAS").
dico("B", 8, "BARIOLAT").
dico("B", 8, "BARIOLEE").
dico("B", 8, "BARIOLER").
dico("B", 8, "BARIOLES").
dico("B", 8, "BARIOLEZ").
dico("B", 8, "BARISIEN").
dico("B", 8, "BARJAQUA").
dico("B", 8, "BARJAQUE").
dico("B", 8, "BARKHANE").
dico("B", 8, "BARLONGS").
dico("B", 8, "BARMAIDS").
dico("B", 8, "BARNACHE").
dico("B", 8, "BARNACLE").
dico("B", 8, "BARONETS").
dico("B", 8, "BARONNES").
dico("B", 8, "BARONNET").
dico("B", 8, "BARONNIE").
dico("B", 8, "BAROQUES").
dico("B", 8, "BAROUDAI").
dico("B", 8, "BAROUDAS").
dico("B", 8, "BAROUDAT").
dico("B", 8, "BAROUDER").
dico("B", 8, "BAROUDES").
dico("B", 8, "BAROUDEZ").
dico("B", 8, "BAROUFES").
dico("B", 8, "BAROUFLE").
dico("B", 8, "BARRAGES").
dico("B", 8, "BARRAMES").
dico("B", 8, "BARRANCO").
dico("B", 8, "BARRASSE").
dico("B", 8, "BARRATES").
dico("B", 8, "BARREAUX").
dico("B", 8, "BARRERAI").
dico("B", 8, "BARRERAS").
dico("B", 8, "BARREREZ").
dico("B", 8, "BARRETTE").
dico("B", 8, "BARREURS").
dico("B", 8, "BARREUSE").
dico("B", 8, "BARRIERE").
dico("B", 8, "BARRIMES").
dico("B", 8, "BARRIONS").
dico("B", 8, "BARRIQUE").
dico("B", 8, "BARRIRAI").
dico("B", 8, "BARRIRAS").
dico("B", 8, "BARRIREZ").
dico("B", 8, "BARRISSE").
dico("B", 8, "BARRITES").
dico("B", 8, "BARRURES").
dico("B", 8, "BARYTEES").
dico("B", 8, "BARYTINE").
dico("B", 8, "BARYTITE").
dico("B", 8, "BARYTONS").
dico("B", 8, "BASAIENT").
dico("B", 8, "BASALTES").
dico("B", 8, "BASANAIS").
dico("B", 8, "BASANAIT").
dico("B", 8, "BASANANT").
dico("B", 8, "BASANEES").
dico("B", 8, "BASANENT").
dico("B", 8, "BASANERA").
dico("B", 8, "BASANIEZ").
dico("B", 8, "BASANONS").
dico("B", 8, "BASASSES").
dico("B", 8, "BASCULAI").
dico("B", 8, "BASCULAS").
dico("B", 8, "BASCULAT").
dico("B", 8, "BASCULEE").
dico("B", 8, "BASCULER").
dico("B", 8, "BASCULES").
dico("B", 8, "BASCULEZ").
dico("B", 8, "BASEBALL").
dico("B", 8, "BASELLES").
dico("B", 8, "BASERAIS").
dico("B", 8, "BASERAIT").
dico("B", 8, "BASERENT").
dico("B", 8, "BASERIEZ").
dico("B", 8, "BASERONS").
dico("B", 8, "BASERONT").
dico("B", 8, "BASICITE").
dico("B", 8, "BASILEUS").
dico("B", 8, "BASILICS").
dico("B", 8, "BASIQUES").
dico("B", 8, "BASISTES").
dico("B", 8, "BASMATIS").
dico("B", 8, "BASOCHES").
dico("B", 8, "BASQUAIS").
dico("B", 8, "BASQUETS").
dico("B", 8, "BASQUINE").
dico("B", 8, "BASSESSE").
dico("B", 8, "BASSETTE").
dico("B", 8, "BASSINAI").
dico("B", 8, "BASSINAS").
dico("B", 8, "BASSINAT").
dico("B", 8, "BASSINEE").
dico("B", 8, "BASSINER").
dico("B", 8, "BASSINES").
dico("B", 8, "BASSINET").
dico("B", 8, "BASSINEZ").
dico("B", 8, "BASSISTE").
dico("B", 8, "BASTAGUE").
dico("B", 8, "BASTAING").
dico("B", 8, "BASTAMES").
dico("B", 8, "BASTAQUE").
dico("B", 8, "BASTASSE").
dico("B", 8, "BASTATES").
dico("B", 8, "BASTERAI").
dico("B", 8, "BASTERAS").
dico("B", 8, "BASTEREZ").
dico("B", 8, "BASTERNE").
dico("B", 8, "BASTIAIS").
dico("B", 8, "BASTIDES").
dico("B", 8, "BASTIDON").
dico("B", 8, "BASTILLE").
dico("B", 8, "BASTINGS").
dico("B", 8, "BASTIONS").
dico("B", 8, "BASTONNA").
dico("B", 8, "BASTONNE").
dico("B", 8, "BATACLAN").
dico("B", 8, "BATAIENT").
dico("B", 8, "BATAILLA").
dico("B", 8, "BATAILLE").
dico("B", 8, "BATARDES").
dico("B", 8, "BATASSES").
dico("B", 8, "BATAVIAS").
dico("B", 8, "BATAYOLE").
dico("B", 8, "BATELAGE").
dico("B", 8, "BATELAIS").
dico("B", 8, "BATELAIT").
dico("B", 8, "BATELANT").
dico("B", 8, "BATELEES").
dico("B", 8, "BATELETS").
dico("B", 8, "BATELEUR").
dico("B", 8, "BATELIER").
dico("B", 8, "BATELIEZ").
dico("B", 8, "BATELLES").
dico("B", 8, "BATELONS").
dico("B", 8, "BATERAIS").
dico("B", 8, "BATERAIT").
dico("B", 8, "BATERENT").
dico("B", 8, "BATERIEZ").
dico("B", 8, "BATERONS").
dico("B", 8, "BATERONT").
dico("B", 8, "BATHYALE").
dico("B", 8, "BATHYAUX").
dico("B", 8, "BATIERES").
dico("B", 8, "BATIFOLA").
dico("B", 8, "BATIFOLE").
dico("B", 8, "BATIMENT").
dico("B", 8, "BATIRAIS").
dico("B", 8, "BATIRAIT").
dico("B", 8, "BATIRENT").
dico("B", 8, "BATIRIEZ").
dico("B", 8, "BATIRONS").
dico("B", 8, "BATIRONT").
dico("B", 8, "BATISSES").
dico("B", 8, "BATISSEZ").
dico("B", 8, "BATISTES").
dico("B", 8, "BATOILLA").
dico("B", 8, "BATOILLE").
dico("B", 8, "BATONNAI").
dico("B", 8, "BATONNAS").
dico("B", 8, "BATONNAT").
dico("B", 8, "BATONNEE").
dico("B", 8, "BATONNER").
dico("B", 8, "BATONNES").
dico("B", 8, "BATONNET").
dico("B", 8, "BATONNEZ").
dico("B", 8, "BATOUDES").
dico("B", 8, "BATTABLE").
dico("B", 8, "BATTAGES").
dico("B", 8, "BATTANTE").
dico("B", 8, "BATTANTS").
dico("B", 8, "BATTERIE").
dico("B", 8, "BATTEURS").
dico("B", 8, "BATTEUSE").
dico("B", 8, "BATTIMES").
dico("B", 8, "BATTIONS").
dico("B", 8, "BATTISSE").
dico("B", 8, "BATTITES").
dico("B", 8, "BATTOIRS").
dico("B", 8, "BATTRAIS").
dico("B", 8, "BATTRAIT").
dico("B", 8, "BATTRIEZ").
dico("B", 8, "BATTRONS").
dico("B", 8, "BATTRONT").
dico("B", 8, "BATTURES").
dico("B", 8, "BAUDRIER").
dico("B", 8, "BAUDROIE").
dico("B", 8, "BAUGEAIS").
dico("B", 8, "BAUGEAIT").
dico("B", 8, "BAUGEANT").
dico("B", 8, "BAUGEONS").
dico("B", 8, "BAUGERAI").
dico("B", 8, "BAUGERAS").
dico("B", 8, "BAUGEREZ").
dico("B", 8, "BAUGIONS").
dico("B", 8, "BAUHINIA").
dico("B", 8, "BAUHINIE").
dico("B", 8, "BAUMIERS").
dico("B", 8, "BAUXITES").
dico("B", 8, "BAVAIENT").
dico("B", 8, "BAVARDAI").
dico("B", 8, "BAVARDAS").
dico("B", 8, "BAVARDAT").
dico("B", 8, "BAVARDER").
dico("B", 8, "BAVARDES").
dico("B", 8, "BAVARDEZ").
dico("B", 8, "BAVAROIS").
dico("B", 8, "BAVASSAI").
dico("B", 8, "BAVASSAS").
dico("B", 8, "BAVASSAT").
dico("B", 8, "BAVASSER").
dico("B", 8, "BAVASSES").
dico("B", 8, "BAVASSEZ").
dico("B", 8, "BAVERAIS").
dico("B", 8, "BAVERAIT").
dico("B", 8, "BAVERENT").
dico("B", 8, "BAVERIEZ").
dico("B", 8, "BAVERONS").
dico("B", 8, "BAVERONT").
dico("B", 8, "BAVETTES").
dico("B", 8, "BAVEUSES").
dico("B", 8, "BAVOCHAI").
dico("B", 8, "BAVOCHAS").
dico("B", 8, "BAVOCHAT").
dico("B", 8, "BAVOCHEE").
dico("B", 8, "BAVOCHER").
dico("B", 8, "BAVOCHES").
dico("B", 8, "BAVOCHEZ").
dico("B", 8, "BAVOLETS").
dico("B", 8, "BAYADERE").
dico("B", 8, "BAYAIENT").
dico("B", 8, "BAYASSES").
dico("B", 8, "BAYERAIS").
dico("B", 8, "BAYERAIT").
dico("B", 8, "BAYERENT").
dico("B", 8, "BAYERIEZ").
dico("B", 8, "BAYERONS").
dico("B", 8, "BAYERONT").
dico("B", 8, "BAZARDAI").
dico("B", 8, "BAZARDAS").
dico("B", 8, "BAZARDAT").
dico("B", 8, "BAZARDEE").
dico("B", 8, "BAZARDER").
dico("B", 8, "BAZARDES").
dico("B", 8, "BAZARDEZ").
dico("B", 8, "BAZOOKAS").
dico("B", 8, "BEARNAIS").
dico("B", 8, "BEASSENT").
dico("B", 8, "BEASSIEZ").
dico("B", 8, "BEATIFIA").
dico("B", 8, "BEATIFIE").
dico("B", 8, "BEATNIKS").
dico("B", 8, "BEAUCOUP").
dico("B", 8, "BEAUFORT").
dico("B", 8, "BEAUPRES").
dico("B", 8, "BECARRES").
dico("B", 8, "BECASSES").
dico("B", 8, "BECCARDS").
dico("B", 8, "BECFIGUE").
dico("B", 8, "BECHAGES").
dico("B", 8, "BECHAMEL").
dico("B", 8, "BECHAMES").
dico("B", 8, "BECHASSE").
dico("B", 8, "BECHATES").
dico("B", 8, "BECHERAI").
dico("B", 8, "BECHERAS").
dico("B", 8, "BECHEREZ").
dico("B", 8, "BECHEURS").
dico("B", 8, "BECHEUSE").
dico("B", 8, "BECHIONS").
dico("B", 8, "BECHIQUE").
dico("B", 8, "BECHOIRS").
dico("B", 8, "BECOSSES").
dico("B", 8, "BECOTAIS").
dico("B", 8, "BECOTAIT").
dico("B", 8, "BECOTANT").
dico("B", 8, "BECOTEES").
dico("B", 8, "BECOTENT").
dico("B", 8, "BECOTERA").
dico("B", 8, "BECOTIEZ").
dico("B", 8, "BECOTONS").
dico("B", 8, "BECQUEES").
dico("B", 8, "BECQUETA").
dico("B", 8, "BECQUETE").
dico("B", 8, "BECQUETS").
dico("B", 8, "BECTAMES").
dico("B", 8, "BECTANCE").
dico("B", 8, "BECTASSE").
dico("B", 8, "BECTATES").
dico("B", 8, "BECTERAI").
dico("B", 8, "BECTERAS").
dico("B", 8, "BECTEREZ").
dico("B", 8, "BECTIONS").
dico("B", 8, "BEDAINES").
dico("B", 8, "BEDEGARS").
dico("B", 8, "BEDEISTE").
dico("B", 8, "BEDONNAI").
dico("B", 8, "BEDONNAS").
dico("B", 8, "BEDONNAT").
dico("B", 8, "BEDONNER").
dico("B", 8, "BEDONNES").
dico("B", 8, "BEDONNEZ").
dico("B", 8, "BEDOUINE").
dico("B", 8, "BEDOUINS").
dico("B", 8, "BEERIONS").
dico("B", 8, "BEFFROIS").
dico("B", 8, "BEGAIENT").
dico("B", 8, "BEGAIERA").
dico("B", 8, "BEGAYAIS").
dico("B", 8, "BEGAYAIT").
dico("B", 8, "BEGAYANT").
dico("B", 8, "BEGAYEES").
dico("B", 8, "BEGAYENT").
dico("B", 8, "BEGAYERA").
dico("B", 8, "BEGAYEUR").
dico("B", 8, "BEGAYIEZ").
dico("B", 8, "BEGAYONS").
dico("B", 8, "BEGGARDS").
dico("B", 8, "BEGONIAS").
dico("B", 8, "BEGUARDS").
dico("B", 8, "BEGUETAI").
dico("B", 8, "BEGUETAS").
dico("B", 8, "BEGUETAT").
dico("B", 8, "BEGUETER").
dico("B", 8, "BEGUETES").
dico("B", 8, "BEGUETEZ").
dico("B", 8, "BEGUEULE").
dico("B", 8, "BEGUINES").
dico("B", 8, "BEHAISME").
dico("B", 8, "BEIGNETS").
dico("B", 8, "BEJAUNES").
dico("B", 8, "BELAIENT").
dico("B", 8, "BELANDRE").
dico("B", 8, "BELANTES").
dico("B", 8, "BELASSES").
dico("B", 8, "BELEMENT").
dico("B", 8, "BELERAIS").
dico("B", 8, "BELERAIT").
dico("B", 8, "BELERENT").
dico("B", 8, "BELERIEZ").
dico("B", 8, "BELERONS").
dico("B", 8, "BELERONT").
dico("B", 8, "BELETTES").
dico("B", 8, "BELIERES").
dico("B", 8, "BELITRES").
dico("B", 8, "BELIZIEN").
dico("B", 8, "BELLATRE").
dico("B", 8, "BELLOTTE").
dico("B", 8, "BELOTEES").
dico("B", 8, "BELOTEUR").
dico("B", 8, "BELOUGAS").
dico("B", 8, "BEMOLISA").
dico("B", 8, "BEMOLISE").
dico("B", 8, "BENARDES").
dico("B", 8, "BENEFICE").
dico("B", 8, "BENEVOLE").
dico("B", 8, "BENGALIE").
dico("B", 8, "BENGALIS").
dico("B", 8, "BENICHON").
dico("B", 8, "BENIGNES").
dico("B", 8, "BENINOIS").
dico("B", 8, "BENIRAIS").
dico("B", 8, "BENIRAIT").
dico("B", 8, "BENIRENT").
dico("B", 8, "BENIRIEZ").
dico("B", 8, "BENIRONS").
dico("B", 8, "BENIRONT").
dico("B", 8, "BENISSES").
dico("B", 8, "BENISSEZ").
dico("B", 8, "BENITIER").
dico("B", 8, "BENJAMIN").
dico("B", 8, "BENJOINS").
dico("B", 8, "BENOITES").
dico("B", 8, "BENZENES").
dico("B", 8, "BENZINES").
dico("B", 8, "BENZOATE").
dico("B", 8, "BENZOLEE").
dico("B", 8, "BENZOLES").
dico("B", 8, "BENZOYLE").
dico("B", 8, "BENZYLES").
dico("B", 8, "BEOTHUKS").
dico("B", 8, "BEOTIENS").
dico("B", 8, "BEOTISME").
dico("B", 8, "BEQUETAI").
dico("B", 8, "BEQUETAS").
dico("B", 8, "BEQUETAT").
dico("B", 8, "BEQUETEE").
dico("B", 8, "BEQUETER").
dico("B", 8, "BEQUETES").
dico("B", 8, "BEQUETEZ").
dico("B", 8, "BEQUETTE").
dico("B", 8, "BEQUILLA").
dico("B", 8, "BEQUILLE").
dico("B", 8, "BERBERES").
dico("B", 8, "BERBERIS").
dico("B", 8, "BERCAMES").
dico("B", 8, "BERCANTE").
dico("B", 8, "BERCANTS").
dico("B", 8, "BERCASSE").
dico("B", 8, "BERCATES").
dico("B", 8, "BERCEAUX").
dico("B", 8, "BERCERAI").
dico("B", 8, "BERCERAS").
dico("B", 8, "BERCEREZ").
dico("B", 8, "BERCEURS").
dico("B", 8, "BERCEUSE").
dico("B", 8, "BERCIONS").
dico("B", 8, "BEREZINA").
dico("B", 8, "BERGERAC").
dico("B", 8, "BERGERES").
dico("B", 8, "BERGERIE").
dico("B", 8, "BERIBERI").
dico("B", 8, "BERIMBAU").
dico("B", 8, "BERLINES").
dico("B", 8, "BERMUDAS").
dico("B", 8, "BERNACHE").
dico("B", 8, "BERNACLE").
dico("B", 8, "BERNAMES").
dico("B", 8, "BERNASSE").
dico("B", 8, "BERNATES").
dico("B", 8, "BERNERAI").
dico("B", 8, "BERNERAS").
dico("B", 8, "BERNEREZ").
dico("B", 8, "BERNEURS").
dico("B", 8, "BERNEUSE").
dico("B", 8, "BERNICLE").
dico("B", 8, "BERNIONS").
dico("B", 8, "BERNIQUE").
dico("B", 8, "BERNOISE").
dico("B", 8, "BERRUYER").
dico("B", 8, "BERTHONS").
dico("B", 8, "BESACIER").
dico("B", 8, "BESAIGUE").
dico("B", 8, "BESICLES").
dico("B", 8, "BESIGUES").
dico("B", 8, "BESOGNAI").
dico("B", 8, "BESOGNAS").
dico("B", 8, "BESOGNAT").
dico("B", 8, "BESOGNEE").
dico("B", 8, "BESOGNER").
dico("B", 8, "BESOGNES").
dico("B", 8, "BESOGNEZ").
dico("B", 8, "BESSEMER").
dico("B", 8, "BESSONNE").
dico("B", 8, "BESTIALE").
dico("B", 8, "BESTIAUX").
dico("B", 8, "BESTIOLE").
dico("B", 8, "BETASSES").
dico("B", 8, "BETATRON").
dico("B", 8, "BETEMENT").
dico("B", 8, "BETIFIAI").
dico("B", 8, "BETIFIAS").
dico("B", 8, "BETIFIAT").
dico("B", 8, "BETIFIEE").
dico("B", 8, "BETIFIER").
dico("B", 8, "BETIFIES").
dico("B", 8, "BETIFIEZ").
dico("B", 8, "BETISAIS").
dico("B", 8, "BETISAIT").
dico("B", 8, "BETISANT").
dico("B", 8, "BETISENT").
dico("B", 8, "BETISERA").
dico("B", 8, "BETISIER").
dico("B", 8, "BETISIEZ").
dico("B", 8, "BETISONS").
dico("B", 8, "BETOINES").
dico("B", 8, "BETOIRES").
dico("B", 8, "BETONNAI").
dico("B", 8, "BETONNAS").
dico("B", 8, "BETONNAT").
dico("B", 8, "BETONNEE").
dico("B", 8, "BETONNER").
dico("B", 8, "BETONNES").
dico("B", 8, "BETONNEZ").
dico("B", 8, "BETTINGS").
dico("B", 8, "BEUGLAIS").
dico("B", 8, "BEUGLAIT").
dico("B", 8, "BEUGLANT").
dico("B", 8, "BEUGLEES").
dico("B", 8, "BEUGLENT").
dico("B", 8, "BEUGLERA").
dico("B", 8, "BEUGLIEZ").
dico("B", 8, "BEUGLONS").
dico("B", 8, "BEURETTE").
dico("B", 8, "BEURRAGE").
dico("B", 8, "BEURRAIS").
dico("B", 8, "BEURRAIT").
dico("B", 8, "BEURRANT").
dico("B", 8, "BEURREES").
dico("B", 8, "BEURRENT").
dico("B", 8, "BEURRERA").
dico("B", 8, "BEURRIER").
dico("B", 8, "BEURRIEZ").
dico("B", 8, "BEURRONS").
dico("B", 8, "BEUVERIE").
dico("B", 8, "BEVATRON").
dico("B", 8, "BEYLICAL").
dico("B", 8, "BEYLICAT").
dico("B", 8, "BEYLISME").
dico("B", 8, "BEZOARDS").
dico("B", 8, "BIACIDES").
dico("B", 8, "BIAFRAIS").
dico("B", 8, "BIAISAIS").
dico("B", 8, "BIAISAIT").
dico("B", 8, "BIAISANT").
dico("B", 8, "BIAISEES").
dico("B", 8, "BIAISENT").
dico("B", 8, "BIAISERA").
dico("B", 8, "BIAISIEZ").
dico("B", 8, "BIAISONS").
dico("B", 8, "BIARROTE").
dico("B", 8, "BIARROTS").
dico("B", 8, "BIATHLON").
dico("B", 8, "BIAURALE").
dico("B", 8, "BIAURAUX").
dico("B", 8, "BIBACIER").
dico("B", 8, "BIBANDES").
dico("B", 8, "BIBELOTA").
dico("B", 8, "BIBELOTE").
dico("B", 8, "BIBELOTS").
dico("B", 8, "BIBENDUM").
dico("B", 8, "BIBERONS").
dico("B", 8, "BIBLIQUE").
dico("B", 8, "BIBLISTE").
dico("B", 8, "BICARREE").
dico("B", 8, "BICARRES").
dico("B", 8, "BICHAMES").
dico("B", 8, "BICHASSE").
dico("B", 8, "BICHATES").
dico("B", 8, "BICHERAI").
dico("B", 8, "BICHERAS").
dico("B", 8, "BICHEREZ").
dico("B", 8, "BICHETTE").
dico("B", 8, "BICHIONS").
dico("B", 8, "BICHONNA").
dico("B", 8, "BICHONNE").
dico("B", 8, "BICKFORD").
dico("B", 8, "BICOLORE").
dico("B", 8, "BICOQUES").
dico("B", 8, "BICORNES").
dico("B", 8, "BICOUCHE").
dico("B", 8, "BICYCLES").
dico("B", 8, "BIDASSES").
dico("B", 8, "BIDOCHES").
dico("B", 8, "BIDONNAI").
dico("B", 8, "BIDONNAS").
dico("B", 8, "BIDONNAT").
dico("B", 8, "BIDONNEE").
dico("B", 8, "BIDONNER").
dico("B", 8, "BIDONNES").
dico("B", 8, "BIDONNEZ").
dico("B", 8, "BIENFAIT").
dico("B", 8, "BIENNALE").
dico("B", 8, "BIENNAUX").
dico("B", 8, "BIENNOIS").
dico("B", 8, "BIENVENU").
dico("B", 8, "BIERGOLS").
dico("B", 8, "BIFFAGES").
dico("B", 8, "BIFFAMES").
dico("B", 8, "BIFFASSE").
dico("B", 8, "BIFFATES").
dico("B", 8, "BIFFERAI").
dico("B", 8, "BIFFERAS").
dico("B", 8, "BIFFEREZ").
dico("B", 8, "BIFFETON").
dico("B", 8, "BIFFIONS").
dico("B", 8, "BIFFURES").
dico("B", 8, "BIFLECHE").
dico("B", 8, "BIFOCALE").
dico("B", 8, "BIFOCAUX").
dico("B", 8, "BIFOLIEE").
dico("B", 8, "BIFOLIES").
dico("B", 8, "BIFTECKS").
dico("B", 8, "BIFURQUA").
dico("B", 8, "BIFURQUE").
dico("B", 8, "BIGAMIES").
dico("B", 8, "BIGARADE").
dico("B", 8, "BIGARRAI").
dico("B", 8, "BIGARRAS").
dico("B", 8, "BIGARRAT").
dico("B", 8, "BIGARREE").
dico("B", 8, "BIGARRER").
dico("B", 8, "BIGARRES").
dico("B", 8, "BIGARREZ").
dico("B", 8, "BIGEMINE").
dico("B", 8, "BIGHORNS").
dico("B", 8, "BIGLAMES").
dico("B", 8, "BIGLASSE").
dico("B", 8, "BIGLATES").
dico("B", 8, "BIGLERAI").
dico("B", 8, "BIGLERAS").
dico("B", 8, "BIGLEREZ").
dico("B", 8, "BIGLEUSE").
dico("B", 8, "BIGLIONS").
dico("B", 8, "BIGNOLES").
dico("B", 8, "BIGNOLLE").
dico("B", 8, "BIGNONES").
dico("B", 8, "BIGNONIA").
dico("B", 8, "BIGORNAI").
dico("B", 8, "BIGORNAS").
dico("B", 8, "BIGORNAT").
dico("B", 8, "BIGORNEE").
dico("B", 8, "BIGORNER").
dico("B", 8, "BIGORNES").
dico("B", 8, "BIGORNEZ").
dico("B", 8, "BIGOUDEN").
dico("B", 8, "BIGOUDIS").
dico("B", 8, "BIGRILLE").
dico("B", 8, "BIGUINES").
dico("B", 8, "BIHOREAU").
dico("B", 8, "BIJECTIF").
dico("B", 8, "BIJUMEAU").
dico("B", 8, "BILABIAL").
dico("B", 8, "BILABIEE").
dico("B", 8, "BILABIES").
dico("B", 8, "BILAIENT").
dico("B", 8, "BILASSES").
dico("B", 8, "BILERAIS").
dico("B", 8, "BILERAIT").
dico("B", 8, "BILERENT").
dico("B", 8, "BILERIEZ").
dico("B", 8, "BILERONS").
dico("B", 8, "BILERONT").
dico("B", 8, "BILEUSES").
dico("B", 8, "BILIAIRE").
dico("B", 8, "BILIEUSE").
dico("B", 8, "BILINGUE").
dico("B", 8, "BILLAGES").
dico("B", 8, "BILLAMES").
dico("B", 8, "BILLARDS").
dico("B", 8, "BILLASSE").
dico("B", 8, "BILLATES").
dico("B", 8, "BILLERAI").
dico("B", 8, "BILLERAS").
dico("B", 8, "BILLEREZ").
dico("B", 8, "BILLETEE").
dico("B", 8, "BILLETES").
dico("B", 8, "BILLETTE").
dico("B", 8, "BILLIONS").
dico("B", 8, "BILLONNA").
dico("B", 8, "BILLONNE").
dico("B", 8, "BILOBEES").
dico("B", 8, "BILOCALE").
dico("B", 8, "BILOCAUX").
dico("B", 8, "BILOQUAI").
dico("B", 8, "BILOQUAS").
dico("B", 8, "BILOQUAT").
dico("B", 8, "BILOQUEE").
dico("B", 8, "BILOQUER").
dico("B", 8, "BILOQUES").
dico("B", 8, "BILOQUEZ").
dico("B", 8, "BIMBELOT").
dico("B", 8, "BIMESTRE").
dico("B", 8, "BIMETAUX").
dico("B", 8, "BIMODALE").
dico("B", 8, "BIMODAUX").
dico("B", 8, "BIMOTEUR").
dico("B", 8, "BINAIENT").
dico("B", 8, "BINAIRES").
dico("B", 8, "BINASSES").
dico("B", 8, "BINAURAL").
dico("B", 8, "BINCHOIS").
dico("B", 8, "BINERAIS").
dico("B", 8, "BINERAIT").
dico("B", 8, "BINERENT").
dico("B", 8, "BINERIES").
dico("B", 8, "BINERIEZ").
dico("B", 8, "BINERONS").
dico("B", 8, "BINERONT").
dico("B", 8, "BINETTES").
dico("B", 8, "BINEUSES").
dico("B", 8, "BINOCLES").
dico("B", 8, "BINOMIAL").
dico("B", 8, "BIOAMINE").
dico("B", 8, "BIOCIDES").
dico("B", 8, "BIOGENES").
dico("B", 8, "BIOGENIE").
dico("B", 8, "BIOLOGIE").
dico("B", 8, "BIOMASSE").
dico("B", 8, "BIONGULE").
dico("B", 8, "BIONIQUE").
dico("B", 8, "BIOPSIES").
dico("B", 8, "BIOPUCES").
dico("B", 8, "BIOTINES").
dico("B", 8, "BIOTIQUE").
dico("B", 8, "BIOTITES").
dico("B", 8, "BIOTOPES").
dico("B", 8, "BIOTYPES").
dico("B", 8, "BIOXYDES").
dico("B", 8, "BIPAIENT").
dico("B", 8, "BIPARTIE").
dico("B", 8, "BIPARTIS").
dico("B", 8, "BIPASSAI").
dico("B", 8, "BIPASSAS").
dico("B", 8, "BIPASSAT").
dico("B", 8, "BIPASSEE").
dico("B", 8, "BIPASSER").
dico("B", 8, "BIPASSES").
dico("B", 8, "BIPASSEZ").
dico("B", 8, "BIPEDIES").
dico("B", 8, "BIPENNEE").
dico("B", 8, "BIPENNES").
dico("B", 8, "BIPERAIS").
dico("B", 8, "BIPERAIT").
dico("B", 8, "BIPERENT").
dico("B", 8, "BIPERIEZ").
dico("B", 8, "BIPERONS").
dico("B", 8, "BIPERONT").
dico("B", 8, "BIPHASEE").
dico("B", 8, "BIPHASES").
dico("B", 8, "BIPLACES").
dico("B", 8, "BIPOINTS").
dico("B", 8, "BIPOUTRE").
dico("B", 8, "BIQUETTE").
dico("B", 8, "BIRMANES").
dico("B", 8, "BIROTORS").
dico("B", 8, "BIROUTES").
dico("B", 8, "BISAIENT").
dico("B", 8, "BISAIEUL").
dico("B", 8, "BISAIGUE").
dico("B", 8, "BISASSES").
dico("B", 8, "BISBILLE").
dico("B", 8, "BISCAIEN").
dico("B", 8, "BISCAYEN").
dico("B", 8, "BISCHOFS").
dico("B", 8, "BISCOMES").
dico("B", 8, "BISCORNU").
dico("B", 8, "BISCOTIN").
dico("B", 8, "BISCOTOS").
dico("B", 8, "BISCOTTE").
dico("B", 8, "BISCUITA").
dico("B", 8, "BISCUITE").
dico("B", 8, "BISCUITS").
dico("B", 8, "BISEAUTA").
dico("B", 8, "BISEAUTE").
dico("B", 8, "BISERAIS").
dico("B", 8, "BISERAIT").
dico("B", 8, "BISERENT").
dico("B", 8, "BISERIEZ").
dico("B", 8, "BISERONS").
dico("B", 8, "BISERONT").
dico("B", 8, "BISETTES").
dico("B", 8, "BISEXUEE").
dico("B", 8, "BISEXUEL").
dico("B", 8, "BISEXUES").
dico("B", 8, "BISINGUE").
dico("B", 8, "BISMUTHE").
dico("B", 8, "BISMUTHS").
dico("B", 8, "BISONNES").
dico("B", 8, "BISONTIN").
dico("B", 8, "BISQUAIS").
dico("B", 8, "BISQUAIT").
dico("B", 8, "BISQUANT").
dico("B", 8, "BISQUENT").
dico("B", 8, "BISQUERA").
dico("B", 8, "BISQUIEZ").
dico("B", 8, "BISQUINE").
dico("B", 8, "BISQUONS").
dico("B", 8, "BISSAMES").
dico("B", 8, "BISSASSE").
dico("B", 8, "BISSATES").
dico("B", 8, "BISSERAI").
dico("B", 8, "BISSERAS").
dico("B", 8, "BISSEREZ").
dico("B", 8, "BISSEURS").
dico("B", 8, "BISSEUSE").
dico("B", 8, "BISSEXTE").
dico("B", 8, "BISSEXUE").
dico("B", 8, "BISSIONS").
dico("B", 8, "BISTABLE").
dico("B", 8, "BISTORTE").
dico("B", 8, "BISTOURI").
dico("B", 8, "BISTRAIS").
dico("B", 8, "BISTRAIT").
dico("B", 8, "BISTRANT").
dico("B", 8, "BISTREES").
dico("B", 8, "BISTRENT").
dico("B", 8, "BISTRERA").
dico("B", 8, "BISTRIEZ").
dico("B", 8, "BISTRONS").
dico("B", 8, "BISTROTE").
dico("B", 8, "BISTROTS").
dico("B", 8, "BITAIENT").
dico("B", 8, "BITASSES").
dico("B", 8, "BITERAIS").
dico("B", 8, "BITERAIT").
dico("B", 8, "BITERENT").
dico("B", 8, "BITERIEZ").
dico("B", 8, "BITERONS").
dico("B", 8, "BITERONT").
dico("B", 8, "BITONALE").
dico("B", 8, "BITONALS").
dico("B", 8, "BITONAUX").
dico("B", 8, "BITONIAU").
dico("B", 8, "BITTAMES").
dico("B", 8, "BITTASSE").
dico("B", 8, "BITTATES").
dico("B", 8, "BITTERAI").
dico("B", 8, "BITTERAS").
dico("B", 8, "BITTEREZ").
dico("B", 8, "BITTIONS").
dico("B", 8, "BITTURAI").
dico("B", 8, "BITTURAS").
dico("B", 8, "BITTURAT").
dico("B", 8, "BITTUREE").
dico("B", 8, "BITTURER").
dico("B", 8, "BITTURES").
dico("B", 8, "BITTUREZ").
dico("B", 8, "BITUMAGE").
dico("B", 8, "BITUMAIS").
dico("B", 8, "BITUMAIT").
dico("B", 8, "BITUMANT").
dico("B", 8, "BITUMEES").
dico("B", 8, "BITUMENT").
dico("B", 8, "BITUMERA").
dico("B", 8, "BITUMEUX").
dico("B", 8, "BITUMIEZ").
dico("B", 8, "BITUMINA").
dico("B", 8, "BITUMINE").
dico("B", 8, "BITUMONS").
dico("B", 8, "BITURAIS").
dico("B", 8, "BITURAIT").
dico("B", 8, "BITURANT").
dico("B", 8, "BITUREES").
dico("B", 8, "BITURENT").
dico("B", 8, "BITURERA").
dico("B", 8, "BITURIEZ").
dico("B", 8, "BITURONS").
dico("B", 8, "BIVALENT").
dico("B", 8, "BIVALVES").
dico("B", 8, "BIVOUACS").
dico("B", 8, "BIZARRES").
dico("B", 8, "BIZERTIN").
dico("B", 8, "BIZINGUE").
dico("B", 8, "BIZUTAGE").
dico("B", 8, "BIZUTAIS").
dico("B", 8, "BIZUTAIT").
dico("B", 8, "BIZUTANT").
dico("B", 8, "BIZUTEES").
dico("B", 8, "BIZUTENT").
dico("B", 8, "BIZUTERA").
dico("B", 8, "BIZUTIEZ").
dico("B", 8, "BIZUTONS").
dico("B", 8, "BLABLATA").
dico("B", 8, "BLABLATE").
dico("B", 8, "BLAFARDE").
dico("B", 8, "BLAFARDS").
dico("B", 8, "BLAGUAIS").
dico("B", 8, "BLAGUAIT").
dico("B", 8, "BLAGUANT").
dico("B", 8, "BLAGUEES").
dico("B", 8, "BLAGUENT").
dico("B", 8, "BLAGUERA").
dico("B", 8, "BLAGUEUR").
dico("B", 8, "BLAGUIEZ").
dico("B", 8, "BLAGUONS").
dico("B", 8, "BLAIRAIS").
dico("B", 8, "BLAIRAIT").
dico("B", 8, "BLAIRANT").
dico("B", 8, "BLAIREAU").
dico("B", 8, "BLAIREES").
dico("B", 8, "BLAIRENT").
dico("B", 8, "BLAIRERA").
dico("B", 8, "BLAIRIEZ").
dico("B", 8, "BLAIRONS").
dico("B", 8, "BLAISOIS").
dico("B", 8, "BLAMABLE").
dico("B", 8, "BLAMAGES").
dico("B", 8, "BLAMAMES").
dico("B", 8, "BLAMASSE").
dico("B", 8, "BLAMATES").
dico("B", 8, "BLAMERAI").
dico("B", 8, "BLAMERAS").
dico("B", 8, "BLAMEREZ").
dico("B", 8, "BLAMIONS").
dico("B", 8, "BLANCHES").
dico("B", 8, "BLANCHET").
dico("B", 8, "BLANCHIE").
dico("B", 8, "BLANCHIR").
dico("B", 8, "BLANCHIS").
dico("B", 8, "BLANCHIT").
dico("B", 8, "BLANCHON").
dico("B", 8, "BLANDICE").
dico("B", 8, "BLASAMES").
dico("B", 8, "BLASASSE").
dico("B", 8, "BLASATES").
dico("B", 8, "BLASERAI").
dico("B", 8, "BLASERAS").
dico("B", 8, "BLASEREZ").
dico("B", 8, "BLASIONS").
dico("B", 8, "BLASONNA").
dico("B", 8, "BLASONNE").
dico("B", 8, "BLASTULA").
dico("B", 8, "BLATERAI").
dico("B", 8, "BLATERAS").
dico("B", 8, "BLATERAT").
dico("B", 8, "BLATERER").
dico("B", 8, "BLATERES").
dico("B", 8, "BLATEREZ").
dico("B", 8, "BLEDARDS").
dico("B", 8, "BLEMIMES").
dico("B", 8, "BLEMIRAI").
dico("B", 8, "BLEMIRAS").
dico("B", 8, "BLEMIREZ").
dico("B", 8, "BLEMISSE").
dico("B", 8, "BLEMITES").
dico("B", 8, "BLENNIES").
dico("B", 8, "BLESAMES").
dico("B", 8, "BLESASSE").
dico("B", 8, "BLESATES").
dico("B", 8, "BLESERAI").
dico("B", 8, "BLESERAS").
dico("B", 8, "BLESEREZ").
dico("B", 8, "BLESIONS").
dico("B", 8, "BLESITES").
dico("B", 8, "BLESOISE").
dico("B", 8, "BLESSAIS").
dico("B", 8, "BLESSAIT").
dico("B", 8, "BLESSANT").
dico("B", 8, "BLESSEES").
dico("B", 8, "BLESSENT").
dico("B", 8, "BLESSERA").
dico("B", 8, "BLESSIEZ").
dico("B", 8, "BLESSONS").
dico("B", 8, "BLESSURE").
dico("B", 8, "BLETSAIS").
dico("B", 8, "BLETSAIT").
dico("B", 8, "BLETSANT").
dico("B", 8, "BLETSEES").
dico("B", 8, "BLETSENT").
dico("B", 8, "BLETSERA").
dico("B", 8, "BLETSIEZ").
dico("B", 8, "BLETSONS").
dico("B", 8, "BLETTIES").
dico("B", 8, "BLETTIRA").
dico("B", 8, "BLEUATRE").
dico("B", 8, "BLEUIMES").
dico("B", 8, "BLEUIRAI").
dico("B", 8, "BLEUIRAS").
dico("B", 8, "BLEUIREZ").
dico("B", 8, "BLEUISSE").
dico("B", 8, "BLEUITES").
dico("B", 8, "BLEUTAIS").
dico("B", 8, "BLEUTAIT").
dico("B", 8, "BLEUTANT").
dico("B", 8, "BLEUTEES").
dico("B", 8, "BLEUTENT").
dico("B", 8, "BLEUTERA").
dico("B", 8, "BLEUTIEZ").
dico("B", 8, "BLEUTONS").
dico("B", 8, "BLINDAGE").
dico("B", 8, "BLINDAIS").
dico("B", 8, "BLINDAIT").
dico("B", 8, "BLINDANT").
dico("B", 8, "BLINDEES").
dico("B", 8, "BLINDENT").
dico("B", 8, "BLINDERA").
dico("B", 8, "BLINDIEZ").
dico("B", 8, "BLINDONS").
dico("B", 8, "BLINQUAI").
dico("B", 8, "BLINQUAS").
dico("B", 8, "BLINQUAT").
dico("B", 8, "BLINQUEE").
dico("B", 8, "BLINQUER").
dico("B", 8, "BLINQUES").
dico("B", 8, "BLINQUEZ").
dico("B", 8, "BLISTERS").
dico("B", 8, "BLIZZARD").
dico("B", 8, "BLOCAGES").
dico("B", 8, "BLOCHETS").
dico("B", 8, "BLONDELS").
dico("B", 8, "BLONDEUR").
dico("B", 8, "BLONDIES").
dico("B", 8, "BLONDINE").
dico("B", 8, "BLONDINS").
dico("B", 8, "BLONDIRA").
dico("B", 8, "BLONDOIE").
dico("B", 8, "BLONDOYA").
dico("B", 8, "BLONDOYE").
dico("B", 8, "BLOOMERS").
dico("B", 8, "BLOQUAIS").
dico("B", 8, "BLOQUAIT").
dico("B", 8, "BLOQUANT").
dico("B", 8, "BLOQUEES").
dico("B", 8, "BLOQUENT").
dico("B", 8, "BLOQUERA").
dico("B", 8, "BLOQUEUR").
dico("B", 8, "BLOQUIEZ").
dico("B", 8, "BLOQUONS").
dico("B", 8, "BLOTTIES").
dico("B", 8, "BLOTTIRA").
dico("B", 8, "BLOUSAIS").
dico("B", 8, "BLOUSAIT").
dico("B", 8, "BLOUSANT").
dico("B", 8, "BLOUSEES").
dico("B", 8, "BLOUSENT").
dico("B", 8, "BLOUSERA").
dico("B", 8, "BLOUSIEZ").
dico("B", 8, "BLOUSONS").
dico("B", 8, "BLOUSSES").
dico("B", 8, "BLUETTES").
dico("B", 8, "BLUFFAIS").
dico("B", 8, "BLUFFAIT").
dico("B", 8, "BLUFFANT").
dico("B", 8, "BLUFFEES").
dico("B", 8, "BLUFFENT").
dico("B", 8, "BLUFFERA").
dico("B", 8, "BLUFFEUR").
dico("B", 8, "BLUFFIEZ").
dico("B", 8, "BLUFFONS").
dico("B", 8, "BLUTAGES").
dico("B", 8, "BLUTAMES").
dico("B", 8, "BLUTASSE").
dico("B", 8, "BLUTATES").
dico("B", 8, "BLUTERAI").
dico("B", 8, "BLUTERAS").
dico("B", 8, "BLUTEREZ").
dico("B", 8, "BLUTERIE").
dico("B", 8, "BLUTIONS").
dico("B", 8, "BLUTOIRS").
dico("B", 8, "BOBECHES").
dico("B", 8, "BOBETTES").
dico("B", 8, "BOBEUSES").
dico("B", 8, "BOBINAGE").
dico("B", 8, "BOBINAIS").
dico("B", 8, "BOBINAIT").
dico("B", 8, "BOBINANT").
dico("B", 8, "BOBINARD").
dico("B", 8, "BOBINEAU").
dico("B", 8, "BOBINEES").
dico("B", 8, "BOBINENT").
dico("B", 8, "BOBINERA").
dico("B", 8, "BOBINEUR").
dico("B", 8, "BOBINIER").
dico("B", 8, "BOBINIEZ").
dico("B", 8, "BOBINOIR").
dico("B", 8, "BOBINONS").
dico("B", 8, "BOBINOTS").
dico("B", 8, "BOBONNES").
dico("B", 8, "BOBTAILS").
dico("B", 8, "BOCAGERE").
dico("B", 8, "BOCAGERS").
dico("B", 8, "BOCARDAI").
dico("B", 8, "BOCARDAS").
dico("B", 8, "BOCARDAT").
dico("B", 8, "BOCARDEE").
dico("B", 8, "BOCARDER").
dico("B", 8, "BOCARDES").
dico("B", 8, "BOCARDEZ").
dico("B", 8, "BOCHIMAN").
dico("B", 8, "BOGHEADS").
dico("B", 8, "BOGOMILE").
dico("B", 8, "BOHEMIEN").
dico("B", 8, "BOHRIUMS").
dico("B", 8, "BOIRIONS").
dico("B", 8, "BOISAGES").
dico("B", 8, "BOISAMES").
dico("B", 8, "BOISASSE").
dico("B", 8, "BOISATES").
dico("B", 8, "BOISERAI").
dico("B", 8, "BOISERAS").
dico("B", 8, "BOISEREZ").
dico("B", 8, "BOISERIE").
dico("B", 8, "BOISEURS").
dico("B", 8, "BOISIONS").
dico("B", 8, "BOISSEAU").
dico("B", 8, "BOISSONS").
dico("B", 8, "BOITAMES").
dico("B", 8, "BOITASSE").
dico("B", 8, "BOITATES").
dico("B", 8, "BOITERAI").
dico("B", 8, "BOITERAS").
dico("B", 8, "BOITEREZ").
dico("B", 8, "BOITERIE").
dico("B", 8, "BOITEUSE").
dico("B", 8, "BOITIERS").
dico("B", 8, "BOITILLA").
dico("B", 8, "BOITILLE").
dico("B", 8, "BOITIONS").
dico("B", 8, "BOLETALE").
dico("B", 8, "BOLIVARS").
dico("B", 8, "BOLIVIEN").
dico("B", 8, "BOLLARDS").
dico("B", 8, "BOLONAIS").
dico("B", 8, "BOMBAGES").
dico("B", 8, "BOMBAMES").
dico("B", 8, "BOMBANCE").
dico("B", 8, "BOMBARDA").
dico("B", 8, "BOMBARDE").
dico("B", 8, "BOMBASIN").
dico("B", 8, "BOMBASSE").
dico("B", 8, "BOMBATES").
dico("B", 8, "BOMBERAI").
dico("B", 8, "BOMBERAS").
dico("B", 8, "BOMBEREZ").
dico("B", 8, "BOMBEURS").
dico("B", 8, "BOMBEUSE").
dico("B", 8, "BOMBIONS").
dico("B", 8, "BOMBONNE").
dico("B", 8, "BONAMIAS").
dico("B", 8, "BONARDES").
dico("B", 8, "BONASSES").
dico("B", 8, "BONBONNE").
dico("B", 8, "BONDAGES").
dico("B", 8, "BONDAMES").
dico("B", 8, "BONDASSE").
dico("B", 8, "BONDATES").
dico("B", 8, "BONDELLE").
dico("B", 8, "BONDERAI").
dico("B", 8, "BONDERAS").
dico("B", 8, "BONDEREZ").
dico("B", 8, "BONDIMES").
dico("B", 8, "BONDIONS").
dico("B", 8, "BONDIRAI").
dico("B", 8, "BONDIRAS").
dico("B", 8, "BONDIREZ").
dico("B", 8, "BONDISSE").
dico("B", 8, "BONDITES").
dico("B", 8, "BONDONNA").
dico("B", 8, "BONDONNE").
dico("B", 8, "BONDREES").
dico("B", 8, "BONGARES").
dico("B", 8, "BONHEURS").
dico("B", 8, "BONHOMIE").
dico("B", 8, "BONHOMME").
dico("B", 8, "BONICHES").
dico("B", 8, "BONICHON").
dico("B", 8, "BONIFACE").
dico("B", 8, "BONIFIAI").
dico("B", 8, "BONIFIAS").
dico("B", 8, "BONIFIAT").
dico("B", 8, "BONIFIEE").
dico("B", 8, "BONIFIER").
dico("B", 8, "BONIFIES").
dico("B", 8, "BONIFIEZ").
dico("B", 8, "BONIMENT").
dico("B", 8, "BONJOURS").
dico("B", 8, "BONNARDE").
dico("B", 8, "BONNARDS").
dico("B", 8, "BONNETTE").
dico("B", 8, "BONNICHE").
dico("B", 8, "BONNOISE").
dico("B", 8, "BONSOIRS").
dico("B", 8, "BONZERIE").
dico("B", 8, "BONZESSE").
dico("B", 8, "BOOLEENS").
dico("B", 8, "BOOLIENS").
dico("B", 8, "BOOSTAIS").
dico("B", 8, "BOOSTAIT").
dico("B", 8, "BOOSTANT").
dico("B", 8, "BOOSTEES").
dico("B", 8, "BOOSTENT").
dico("B", 8, "BOOSTERA").
dico("B", 8, "BOOSTERS").
dico("B", 8, "BOOSTIEZ").
dico("B", 8, "BOOSTONS").
dico("B", 8, "BORACITE").
dico("B", 8, "BORAINES").
dico("B", 8, "BORASSES").
dico("B", 8, "BORASSUS").
dico("B", 8, "BORATEES").
dico("B", 8, "BORCHTCH").
dico("B", 8, "BORDAGES").
dico("B", 8, "BORDAMES").
dico("B", 8, "BORDASSE").
dico("B", 8, "BORDATES").
dico("B", 8, "BORDEAUX").
dico("B", 8, "BORDELLE").
dico("B", 8, "BORDERAI").
dico("B", 8, "BORDERAS").
dico("B", 8, "BORDEREZ").
dico("B", 8, "BORDERIE").
dico("B", 8, "BORDIERE").
dico("B", 8, "BORDIERS").
dico("B", 8, "BORDIGUE").
dico("B", 8, "BORDIONS").
dico("B", 8, "BORDURES").
dico("B", 8, "BOREALES").
dico("B", 8, "BORIQUEE").
dico("B", 8, "BORIQUES").
dico("B", 8, "BORNAGES").
dico("B", 8, "BORNAMES").
dico("B", 8, "BORNASSE").
dico("B", 8, "BORNATES").
dico("B", 8, "BORNERAI").
dico("B", 8, "BORNERAS").
dico("B", 8, "BORNEREZ").
dico("B", 8, "BORNIONS").
dico("B", 8, "BORNOIES").
dico("B", 8, "BORNOYAI").
dico("B", 8, "BORNOYAS").
dico("B", 8, "BORNOYAT").
dico("B", 8, "BORNOYEE").
dico("B", 8, "BORNOYER").
dico("B", 8, "BORNOYES").
dico("B", 8, "BORNOYEZ").
dico("B", 8, "BOROUGHS").
dico("B", 8, "BORRELIA").
dico("B", 8, "BORTSCHS").
dico("B", 8, "BOSCOTTE").
dico("B", 8, "BOSCOYOS").
dico("B", 8, "BOSKOOPS").
dico("B", 8, "BOSNIENS").
dico("B", 8, "BOSQUETS").
dico("B", 8, "BOSSAGES").
dico("B", 8, "BOSSAMES").
dico("B", 8, "BOSSASSE").
dico("B", 8, "BOSSATES").
dico("B", 8, "BOSSELAI").
dico("B", 8, "BOSSELAS").
dico("B", 8, "BOSSELAT").
dico("B", 8, "BOSSELEE").
dico("B", 8, "BOSSELER").
dico("B", 8, "BOSSELES").
dico("B", 8, "BOSSELEZ").
dico("B", 8, "BOSSELLE").
dico("B", 8, "BOSSERAI").
dico("B", 8, "BOSSERAS").
dico("B", 8, "BOSSEREZ").
dico("B", 8, "BOSSETTE").
dico("B", 8, "BOSSEURS").
dico("B", 8, "BOSSEUSE").
dico("B", 8, "BOSSIONS").
dico("B", 8, "BOSSOIRS").
dico("B", 8, "BOSSUAIS").
dico("B", 8, "BOSSUAIT").
dico("B", 8, "BOSSUANT").
dico("B", 8, "BOSSUEES").
dico("B", 8, "BOSSUENT").
dico("B", 8, "BOSSUERA").
dico("B", 8, "BOSSUIEZ").
dico("B", 8, "BOSSUONS").
dico("B", 8, "BOSTONNA").
dico("B", 8, "BOSTONNE").
dico("B", 8, "BOTANISA").
dico("B", 8, "BOTANISE").
dico("B", 8, "BOTRYTIS").
dico("B", 8, "BOTTAMES").
dico("B", 8, "BOTTASSE").
dico("B", 8, "BOTTATES").
dico("B", 8, "BOTTELAI").
dico("B", 8, "BOTTELAS").
dico("B", 8, "BOTTELAT").
dico("B", 8, "BOTTELEE").
dico("B", 8, "BOTTELER").
dico("B", 8, "BOTTELES").
dico("B", 8, "BOTTELEZ").
dico("B", 8, "BOTTELLE").
dico("B", 8, "BOTTERAI").
dico("B", 8, "BOTTERAS").
dico("B", 8, "BOTTEREZ").
dico("B", 8, "BOTTERIE").
dico("B", 8, "BOTTEURS").
dico("B", 8, "BOTTIERE").
dico("B", 8, "BOTTIERS").
dico("B", 8, "BOTTINES").
dico("B", 8, "BOTTIONS").
dico("B", 8, "BOUBOULA").
dico("B", 8, "BOUBOULE").
dico("B", 8, "BOUCANAI").
dico("B", 8, "BOUCANAS").
dico("B", 8, "BOUCANAT").
dico("B", 8, "BOUCANEE").
dico("B", 8, "BOUCANER").
dico("B", 8, "BOUCANES").
dico("B", 8, "BOUCANEZ").
dico("B", 8, "BOUCAUDS").
dico("B", 8, "BOUCAUTS").
dico("B", 8, "BOUCHAGE").
dico("B", 8, "BOUCHAIN").
dico("B", 8, "BOUCHAIS").
dico("B", 8, "BOUCHAIT").
dico("B", 8, "BOUCHANT").
dico("B", 8, "BOUCHEES").
dico("B", 8, "BOUCHENT").
dico("B", 8, "BOUCHERA").
dico("B", 8, "BOUCHERE").
dico("B", 8, "BOUCHERS").
dico("B", 8, "BOUCHEUR").
dico("B", 8, "BOUCHIEZ").
dico("B", 8, "BOUCHOIE").
dico("B", 8, "BOUCHONS").
dico("B", 8, "BOUCHOTS").
dico("B", 8, "BOUCHOYA").
dico("B", 8, "BOUCHOYE").
dico("B", 8, "BOUCLAGE").
dico("B", 8, "BOUCLAIS").
dico("B", 8, "BOUCLAIT").
dico("B", 8, "BOUCLANT").
dico("B", 8, "BOUCLEES").
dico("B", 8, "BOUCLENT").
dico("B", 8, "BOUCLERA").
dico("B", 8, "BOUCLIER").
dico("B", 8, "BOUCLIEZ").
dico("B", 8, "BOUCLONS").
dico("B", 8, "BOUDAMES").
dico("B", 8, "BOUDASSE").
dico("B", 8, "BOUDATES").
dico("B", 8, "BOUDDHAS").
dico("B", 8, "BOUDERAI").
dico("B", 8, "BOUDERAS").
dico("B", 8, "BOUDEREZ").
dico("B", 8, "BOUDERIE").
dico("B", 8, "BOUDEURS").
dico("B", 8, "BOUDEUSE").
dico("B", 8, "BOUDINAI").
dico("B", 8, "BOUDINAS").
dico("B", 8, "BOUDINAT").
dico("B", 8, "BOUDINEE").
dico("B", 8, "BOUDINER").
dico("B", 8, "BOUDINES").
dico("B", 8, "BOUDINEZ").
dico("B", 8, "BOUDIONS").
dico("B", 8, "BOUDOIRS").
dico("B", 8, "BOUELAIS").
dico("B", 8, "BOUELAIT").
dico("B", 8, "BOUELANT").
dico("B", 8, "BOUELENT").
dico("B", 8, "BOUELERA").
dico("B", 8, "BOUELIEZ").
dico("B", 8, "BOUELONS").
dico("B", 8, "BOUETTES").
dico("B", 8, "BOUEUSES").
dico("B", 8, "BOUFFAIS").
dico("B", 8, "BOUFFAIT").
dico("B", 8, "BOUFFANT").
dico("B", 8, "BOUFFEES").
dico("B", 8, "BOUFFENT").
dico("B", 8, "BOUFFERA").
dico("B", 8, "BOUFFEUR").
dico("B", 8, "BOUFFIES").
dico("B", 8, "BOUFFIEZ").
dico("B", 8, "BOUFFIRA").
dico("B", 8, "BOUFFONS").
dico("B", 8, "BOUGEAIS").
dico("B", 8, "BOUGEAIT").
dico("B", 8, "BOUGEANT").
dico("B", 8, "BOUGEOIR").
dico("B", 8, "BOUGEONS").
dico("B", 8, "BOUGERAI").
dico("B", 8, "BOUGERAS").
dico("B", 8, "BOUGEREZ").
dico("B", 8, "BOUGIONS").
dico("B", 8, "BOUGNATS").
dico("B", 8, "BOUGONNA").
dico("B", 8, "BOUGONNE").
dico("B", 8, "BOUGRANS").
dico("B", 8, "BOUGRINE").
dico("B", 8, "BOUIBOUI").
dico("B", 8, "BOUILLES").
dico("B", 8, "BOUILLEZ").
dico("B", 8, "BOUILLIE").
dico("B", 8, "BOUILLIR").
dico("B", 8, "BOUILLIS").
dico("B", 8, "BOUILLIT").
dico("B", 8, "BOUILLON").
dico("B", 8, "BOUINAIS").
dico("B", 8, "BOUINAIT").
dico("B", 8, "BOUINANT").
dico("B", 8, "BOUINEES").
dico("B", 8, "BOUINENT").
dico("B", 8, "BOUINERA").
dico("B", 8, "BOUINIEZ").
dico("B", 8, "BOUINONS").
dico("B", 8, "BOUJARON").
dico("B", 8, "BOULAIES").
dico("B", 8, "BOULAMES").
dico("B", 8, "BOULANGE").
dico("B", 8, "BOULASSE").
dico("B", 8, "BOULATES").
dico("B", 8, "BOULBENE").
dico("B", 8, "BOULDERS").
dico("B", 8, "BOULEAUX").
dico("B", 8, "BOULERAI").
dico("B", 8, "BOULERAS").
dico("B", 8, "BOULEREZ").
dico("B", 8, "BOULETEE").
dico("B", 8, "BOULETES").
dico("B", 8, "BOULETTE").
dico("B", 8, "BOULEUSE").
dico("B", 8, "BOULGOUR").
dico("B", 8, "BOULIERS").
dico("B", 8, "BOULIMIE").
dico("B", 8, "BOULINES").
dico("B", 8, "BOULIONS").
dico("B", 8, "BOULISME").
dico("B", 8, "BOULISTE").
dico("B", 8, "BOULOCHA").
dico("B", 8, "BOULOCHE").
dico("B", 8, "BOULOIRS").
dico("B", 8, "BOULONNA").
dico("B", 8, "BOULONNE").
dico("B", 8, "BOULOTTA").
dico("B", 8, "BOULOTTE").
dico("B", 8, "BOUMEURS").
dico("B", 8, "BOUQUETE").
dico("B", 8, "BOUQUETS").
dico("B", 8, "BOUQUINA").
dico("B", 8, "BOUQUINE").
dico("B", 8, "BOUQUINS").
dico("B", 8, "BOURACAN").
dico("B", 8, "BOURBEUX").
dico("B", 8, "BOURBIER").
dico("B", 8, "BOURBONS").
dico("B", 8, "BOURDONS").
dico("B", 8, "BOURGADE").
dico("B", 8, "BOURGEON").
dico("B", 8, "BOURONNA").
dico("B", 8, "BOURONNE").
dico("B", 8, "BOURRADE").
dico("B", 8, "BOURRAGE").
dico("B", 8, "BOURRAIS").
dico("B", 8, "BOURRAIT").
dico("B", 8, "BOURRANT").
dico("B", 8, "BOURREAU").
dico("B", 8, "BOURREES").
dico("B", 8, "BOURRELA").
dico("B", 8, "BOURRELE").
dico("B", 8, "BOURRENT").
dico("B", 8, "BOURRERA").
dico("B", 8, "BOURREUR").
dico("B", 8, "BOURRIDE").
dico("B", 8, "BOURRIER").
dico("B", 8, "BOURRIEZ").
dico("B", 8, "BOURRINE").
dico("B", 8, "BOURRINS").
dico("B", 8, "BOURROIR").
dico("B", 8, "BOURRONS").
dico("B", 8, "BOURRUES").
dico("B", 8, "BOURSIER").
dico("B", 8, "BOUSAMES").
dico("B", 8, "BOUSASSE").
dico("B", 8, "BOUSATES").
dico("B", 8, "BOUSCULA").
dico("B", 8, "BOUSCULE").
dico("B", 8, "BOUSERAI").
dico("B", 8, "BOUSERAS").
dico("B", 8, "BOUSEREZ").
dico("B", 8, "BOUSEUSE").
dico("B", 8, "BOUSIERS").
dico("B", 8, "BOUSILLA").
dico("B", 8, "BOUSILLE").
dico("B", 8, "BOUSIONS").
dico("B", 8, "BOUSSOLE").
dico("B", 8, "BOUTADES").
dico("B", 8, "BOUTAMES").
dico("B", 8, "BOUTASSE").
dico("B", 8, "BOUTATES").
dico("B", 8, "BOUTEFAS").
dico("B", 8, "BOUTEFEU").
dico("B", 8, "BOUTERAI").
dico("B", 8, "BOUTERAS").
dico("B", 8, "BOUTEREZ").
dico("B", 8, "BOUTEURS").
dico("B", 8, "BOUTIONS").
dico("B", 8, "BOUTIQUE").
dico("B", 8, "BOUTISSE").
dico("B", 8, "BOUTOIRS").
dico("B", 8, "BOUTONNA").
dico("B", 8, "BOUTONNE").
dico("B", 8, "BOUTURAI").
dico("B", 8, "BOUTURAS").
dico("B", 8, "BOUTURAT").
dico("B", 8, "BOUTUREE").
dico("B", 8, "BOUTURER").
dico("B", 8, "BOUTURES").
dico("B", 8, "BOUTUREZ").
dico("B", 8, "BOUVERIE").
dico("B", 8, "BOUVETAI").
dico("B", 8, "BOUVETAS").
dico("B", 8, "BOUVETAT").
dico("B", 8, "BOUVETEE").
dico("B", 8, "BOUVETER").
dico("B", 8, "BOUVETES").
dico("B", 8, "BOUVETEZ").
dico("B", 8, "BOUVETTE").
dico("B", 8, "BOUVIERE").
dico("B", 8, "BOUVIERS").
dico("B", 8, "BOUVRILS").
dico("B", 8, "BOUZOUKI").
dico("B", 8, "BOWETTES").
dico("B", 8, "BOWLINGS").
dico("B", 8, "BOXAIENT").
dico("B", 8, "BOXASSES").
dico("B", 8, "BOXERAIS").
dico("B", 8, "BOXERAIT").
dico("B", 8, "BOXERENT").
dico("B", 8, "BOXERIEZ").
dico("B", 8, "BOXERONS").
dico("B", 8, "BOXERONT").
dico("B", 8, "BOXEUSES").
dico("B", 8, "BOYAUTAI").
dico("B", 8, "BOYAUTAS").
dico("B", 8, "BOYAUTAT").
dico("B", 8, "BOYAUTEE").
dico("B", 8, "BOYAUTER").
dico("B", 8, "BOYAUTES").
dico("B", 8, "BOYAUTEZ").
dico("B", 8, "BOYCOTTA").
dico("B", 8, "BOYCOTTE").
dico("B", 8, "BOYCOTTS").
dico("B", 8, "BOYOMAIS").
dico("B", 8, "BRABANTS").
dico("B", 8, "BRACELET").
dico("B", 8, "BRACHIAL").
dico("B", 8, "BRACONNA").
dico("B", 8, "BRACONNE").
dico("B", 8, "BRACTEAL").
dico("B", 8, "BRACTEES").
dico("B", 8, "BRADAGES").
dico("B", 8, "BRADAMES").
dico("B", 8, "BRADASSE").
dico("B", 8, "BRADATES").
dico("B", 8, "BRADERAI").
dico("B", 8, "BRADERAS").
dico("B", 8, "BRADEREZ").
dico("B", 8, "BRADERIE").
dico("B", 8, "BRADEURS").
dico("B", 8, "BRADEUSE").
dico("B", 8, "BRADIONS").
dico("B", 8, "BRADYPES").
dico("B", 8, "BRAGARDE").
dico("B", 8, "BRAGARDS").
dico("B", 8, "BRAHMANE").
dico("B", 8, "BRAHMANS").
dico("B", 8, "BRAHMINE").
dico("B", 8, "BRAIERAI").
dico("B", 8, "BRAIERAS").
dico("B", 8, "BRAIEREZ").
dico("B", 8, "BRAILLAI").
dico("B", 8, "BRAILLAS").
dico("B", 8, "BRAILLAT").
dico("B", 8, "BRAILLEE").
dico("B", 8, "BRAILLER").
dico("B", 8, "BRAILLES").
dico("B", 8, "BRAILLEZ").
dico("B", 8, "BRAIMENT").
dico("B", 8, "BRAIRAIS").
dico("B", 8, "BRAIRAIT").
dico("B", 8, "BRAIRIEZ").
dico("B", 8, "BRAIRONS").
dico("B", 8, "BRAIRONT").
dico("B", 8, "BRAISAGE").
dico("B", 8, "BRAISAIS").
dico("B", 8, "BRAISAIT").
dico("B", 8, "BRAISANT").
dico("B", 8, "BRAISEES").
dico("B", 8, "BRAISENT").
dico("B", 8, "BRAISERA").
dico("B", 8, "BRAISIEZ").
dico("B", 8, "BRAISONS").
dico("B", 8, "BRAMAMES").
dico("B", 8, "BRAMASSE").
dico("B", 8, "BRAMATES").
dico("B", 8, "BRAMERAI").
dico("B", 8, "BRAMERAS").
dico("B", 8, "BRAMEREZ").
dico("B", 8, "BRAMIONS").
dico("B", 8, "BRANCARD").
dico("B", 8, "BRANCHAI").
dico("B", 8, "BRANCHAS").
dico("B", 8, "BRANCHAT").
dico("B", 8, "BRANCHEE").
dico("B", 8, "BRANCHER").
dico("B", 8, "BRANCHES").
dico("B", 8, "BRANCHEZ").
dico("B", 8, "BRANCHIE").
dico("B", 8, "BRANCHUE").
dico("B", 8, "BRANCHUS").
dico("B", 8, "BRANDADE").
dico("B", 8, "BRANDIES").
dico("B", 8, "BRANDIRA").
dico("B", 8, "BRANDONS").
dico("B", 8, "BRANLAIS").
dico("B", 8, "BRANLAIT").
dico("B", 8, "BRANLANT").
dico("B", 8, "BRANLEES").
dico("B", 8, "BRANLENT").
dico("B", 8, "BRANLERA").
dico("B", 8, "BRANLEUR").
dico("B", 8, "BRANLEUX").
dico("B", 8, "BRANLIEZ").
dico("B", 8, "BRANLONS").
dico("B", 8, "BRANQUES").
dico("B", 8, "BRAQUAGE").
dico("B", 8, "BRAQUAIS").
dico("B", 8, "BRAQUAIT").
dico("B", 8, "BRAQUANT").
dico("B", 8, "BRAQUEES").
dico("B", 8, "BRAQUENT").
dico("B", 8, "BRAQUERA").
dico("B", 8, "BRAQUETS").
dico("B", 8, "BRAQUEUR").
dico("B", 8, "BRAQUIEZ").
dico("B", 8, "BRAQUONS").
dico("B", 8, "BRASAGES").
dico("B", 8, "BRASAMES").
dico("B", 8, "BRASASSE").
dico("B", 8, "BRASATES").
dico("B", 8, "BRASERAI").
dico("B", 8, "BRASERAS").
dico("B", 8, "BRASEREZ").
dico("B", 8, "BRASEROS").
dico("B", 8, "BRASIERS").
dico("B", 8, "BRASILLA").
dico("B", 8, "BRASILLE").
dico("B", 8, "BRASIONS").
dico("B", 8, "BRASQUAI").
dico("B", 8, "BRASQUAS").
dico("B", 8, "BRASQUAT").
dico("B", 8, "BRASQUEE").
dico("B", 8, "BRASQUER").
dico("B", 8, "BRASQUES").
dico("B", 8, "BRASQUEZ").
dico("B", 8, "BRASSAGE").
dico("B", 8, "BRASSAIS").
dico("B", 8, "BRASSAIT").
dico("B", 8, "BRASSANT").
dico("B", 8, "BRASSARD").
dico("B", 8, "BRASSEES").
dico("B", 8, "BRASSENT").
dico("B", 8, "BRASSERA").
dico("B", 8, "BRASSEUR").
dico("B", 8, "BRASSEYA").
dico("B", 8, "BRASSEYE").
dico("B", 8, "BRASSIEZ").
dico("B", 8, "BRASSINS").
dico("B", 8, "BRASSONS").
dico("B", 8, "BRASURES").
dico("B", 8, "BRAVACHE").
dico("B", 8, "BRAVADES").
dico("B", 8, "BRAVAMES").
dico("B", 8, "BRAVASSE").
dico("B", 8, "BRAVATES").
dico("B", 8, "BRAVERAI").
dico("B", 8, "BRAVERAS").
dico("B", 8, "BRAVEREZ").
dico("B", 8, "BRAVERIE").
dico("B", 8, "BRAVIONS").
dico("B", 8, "BRAVOURE").
dico("B", 8, "BRAYAMES").
dico("B", 8, "BRAYASSE").
dico("B", 8, "BRAYATES").
dico("B", 8, "BRAYERAI").
dico("B", 8, "BRAYERAS").
dico("B", 8, "BRAYEREZ").
dico("B", 8, "BRAYIONS").
dico("B", 8, "BREAKAIS").
dico("B", 8, "BREAKAIT").
dico("B", 8, "BREAKANT").
dico("B", 8, "BREAKEES").
dico("B", 8, "BREAKENT").
dico("B", 8, "BREAKERA").
dico("B", 8, "BREAKIEZ").
dico("B", 8, "BREAKONS").
dico("B", 8, "BRECHETS").
dico("B", 8, "BREEDERS").
dico("B", 8, "BRELAGES").
dico("B", 8, "BRELAMES").
dico("B", 8, "BRELASSE").
dico("B", 8, "BRELATES").
dico("B", 8, "BRELERAI").
dico("B", 8, "BRELERAS").
dico("B", 8, "BRELEREZ").
dico("B", 8, "BRELIONS").
dico("B", 8, "BRELOQUE").
dico("B", 8, "BRESILLA").
dico("B", 8, "BRESILLE").
dico("B", 8, "BRESSANE").
dico("B", 8, "BRESSANS").
dico("B", 8, "BRESTOIS").
dico("B", 8, "BRETAUDA").
dico("B", 8, "BRETAUDE").
dico("B", 8, "BRETECHE").
dico("B", 8, "BRETELLE").
dico("B", 8, "BRETESSE").
dico("B", 8, "BRETONNE").
dico("B", 8, "BRETTAIS").
dico("B", 8, "BRETTAIT").
dico("B", 8, "BRETTANT").
dico("B", 8, "BRETTEES").
dico("B", 8, "BRETTELA").
dico("B", 8, "BRETTELE").
dico("B", 8, "BRETTENT").
dico("B", 8, "BRETTERA").
dico("B", 8, "BRETTEUR").
dico("B", 8, "BRETTIEZ").
dico("B", 8, "BRETTONS").
dico("B", 8, "BRETZELS").
dico("B", 8, "BREUVAGE").
dico("B", 8, "BREVETAI").
dico("B", 8, "BREVETAS").
dico("B", 8, "BREVETAT").
dico("B", 8, "BREVETEE").
dico("B", 8, "BREVETER").
dico("B", 8, "BREVETES").
dico("B", 8, "BREVETEZ").
dico("B", 8, "BREVETTE").
dico("B", 8, "BREVITES").
dico("B", 8, "BRIARDES").
dico("B", 8, "BRICELET").
dico("B", 8, "BRICOLAI").
dico("B", 8, "BRICOLAS").
dico("B", 8, "BRICOLAT").
dico("B", 8, "BRICOLEE").
dico("B", 8, "BRICOLER").
dico("B", 8, "BRICOLES").
dico("B", 8, "BRICOLEZ").
dico("B", 8, "BRIDAGES").
dico("B", 8, "BRIDAMES").
dico("B", 8, "BRIDASSE").
dico("B", 8, "BRIDATES").
dico("B", 8, "BRIDERAI").
dico("B", 8, "BRIDERAS").
dico("B", 8, "BRIDEREZ").
dico("B", 8, "BRIDGEAI").
dico("B", 8, "BRIDGEAS").
dico("B", 8, "BRIDGEAT").
dico("B", 8, "BRIDGEES").
dico("B", 8, "BRIDGENT").
dico("B", 8, "BRIDGERA").
dico("B", 8, "BRIDGEUR").
dico("B", 8, "BRIDGIEZ").
dico("B", 8, "BRIDIONS").
dico("B", 8, "BRIEFAIS").
dico("B", 8, "BRIEFAIT").
dico("B", 8, "BRIEFANT").
dico("B", 8, "BRIEFEES").
dico("B", 8, "BRIEFENT").
dico("B", 8, "BRIEFERA").
dico("B", 8, "BRIEFIEZ").
dico("B", 8, "BRIEFING").
dico("B", 8, "BRIEFONS").
dico("B", 8, "BRIEVETE").
dico("B", 8, "BRIFFAIS").
dico("B", 8, "BRIFFAIT").
dico("B", 8, "BRIFFANT").
dico("B", 8, "BRIFFEES").
dico("B", 8, "BRIFFENT").
dico("B", 8, "BRIFFERA").
dico("B", 8, "BRIFFIEZ").
dico("B", 8, "BRIFFONS").
dico("B", 8, "BRIGADES").
dico("B", 8, "BRIGANDA").
dico("B", 8, "BRIGANDE").
dico("B", 8, "BRIGANDS").
dico("B", 8, "BRIGUAIS").
dico("B", 8, "BRIGUAIT").
dico("B", 8, "BRIGUANT").
dico("B", 8, "BRIGUEES").
dico("B", 8, "BRIGUENT").
dico("B", 8, "BRIGUERA").
dico("B", 8, "BRIGUIEZ").
dico("B", 8, "BRIGUONS").
dico("B", 8, "BRILLAIS").
dico("B", 8, "BRILLAIT").
dico("B", 8, "BRILLANT").
dico("B", 8, "BRILLENT").
dico("B", 8, "BRILLERA").
dico("B", 8, "BRILLIEZ").
dico("B", 8, "BRILLONS").
dico("B", 8, "BRIMADES").
dico("B", 8, "BRIMAMES").
dico("B", 8, "BRIMASSE").
dico("B", 8, "BRIMATES").
dico("B", 8, "BRIMBALA").
dico("B", 8, "BRIMBALE").
dico("B", 8, "BRIMERAI").
dico("B", 8, "BRIMERAS").
dico("B", 8, "BRIMEREZ").
dico("B", 8, "BRIMIONS").
dico("B", 8, "BRINELLS").
dico("B", 8, "BRINGEES").
dico("B", 8, "BRINGUAI").
dico("B", 8, "BRINGUAS").
dico("B", 8, "BRINGUAT").
dico("B", 8, "BRINGUEE").
dico("B", 8, "BRINGUER").
dico("B", 8, "BRINGUES").
dico("B", 8, "BRINGUEZ").
dico("B", 8, "BRIOCHEE").
dico("B", 8, "BRIOCHES").
dico("B", 8, "BRIOCHIN").
dico("B", 8, "BRIQUAIS").
dico("B", 8, "BRIQUAIT").
dico("B", 8, "BRIQUANT").
dico("B", 8, "BRIQUEES").
dico("B", 8, "BRIQUENT").
dico("B", 8, "BRIQUERA").
dico("B", 8, "BRIQUETA").
dico("B", 8, "BRIQUETE").
dico("B", 8, "BRIQUETS").
dico("B", 8, "BRIQUIEZ").
dico("B", 8, "BRIQUONS").
dico("B", 8, "BRISAMES").
dico("B", 8, "BRISANCE").
dico("B", 8, "BRISANTE").
dico("B", 8, "BRISANTS").
dico("B", 8, "BRISASSE").
dico("B", 8, "BRISATES").
dico("B", 8, "BRISCARD").
dico("B", 8, "BRISERAI").
dico("B", 8, "BRISERAS").
dico("B", 8, "BRISEREZ").
dico("B", 8, "BRISEURS").
dico("B", 8, "BRISEUSE").
dico("B", 8, "BRISIONS").
dico("B", 8, "BRISOLEE").
dico("B", 8, "BRISQUES").
dico("B", 8, "BRISTOLS").
dico("B", 8, "BRISURES").
dico("B", 8, "BRIVISTE").
dico("B", 8, "BROCANTA").
dico("B", 8, "BROCANTE").
dico("B", 8, "BROCARDA").
dico("B", 8, "BROCARDE").
dico("B", 8, "BROCARDS").
dico("B", 8, "BROCARTS").
dico("B", 8, "BROCCIOS").
dico("B", 8, "BROCCIUS").
dico("B", 8, "BROCHAGE").
dico("B", 8, "BROCHAIS").
dico("B", 8, "BROCHAIT").
dico("B", 8, "BROCHANT").
dico("B", 8, "BROCHEES").
dico("B", 8, "BROCHENT").
dico("B", 8, "BROCHERA").
dico("B", 8, "BROCHETS").
dico("B", 8, "BROCHEUR").
dico("B", 8, "BROCHIEZ").
dico("B", 8, "BROCHOIR").
dico("B", 8, "BROCHONS").
dico("B", 8, "BROCHURE").
dico("B", 8, "BROCOLIS").
dico("B", 8, "BRODAMES").
dico("B", 8, "BRODASSE").
dico("B", 8, "BRODATES").
dico("B", 8, "BRODERAI").
dico("B", 8, "BRODERAS").
dico("B", 8, "BRODEREZ").
dico("B", 8, "BRODERIE").
dico("B", 8, "BRODEURS").
dico("B", 8, "BRODEUSE").
dico("B", 8, "BRODIONS").
dico("B", 8, "BROIERAI").
dico("B", 8, "BROIERAS").
dico("B", 8, "BROIEREZ").
dico("B", 8, "BROIGNES").
dico("B", 8, "BROMATES").
dico("B", 8, "BROMELIA").
dico("B", 8, "BROMIQUE").
dico("B", 8, "BROMISME").
dico("B", 8, "BROMUREE").
dico("B", 8, "BROMURES").
dico("B", 8, "BRONCHAI").
dico("B", 8, "BRONCHAS").
dico("B", 8, "BRONCHAT").
dico("B", 8, "BRONCHER").
dico("B", 8, "BRONCHES").
dico("B", 8, "BRONCHEZ").
dico("B", 8, "BRONZAGE").
dico("B", 8, "BRONZAIS").
dico("B", 8, "BRONZAIT").
dico("B", 8, "BRONZANT").
dico("B", 8, "BRONZEES").
dico("B", 8, "BRONZENT").
dico("B", 8, "BRONZERA").
dico("B", 8, "BRONZEUR").
dico("B", 8, "BRONZIER").
dico("B", 8, "BRONZIEZ").
dico("B", 8, "BRONZONS").
dico("B", 8, "BROQUARD").
dico("B", 8, "BROQUART").
dico("B", 8, "BROSSAGE").
dico("B", 8, "BROSSAIS").
dico("B", 8, "BROSSAIT").
dico("B", 8, "BROSSANT").
dico("B", 8, "BROSSEES").
dico("B", 8, "BROSSENT").
dico("B", 8, "BROSSERA").
dico("B", 8, "BROSSIER").
dico("B", 8, "BROSSIEZ").
dico("B", 8, "BROSSONS").
dico("B", 8, "BROUETTA").
dico("B", 8, "BROUETTE").
dico("B", 8, "BROUHAHA").
dico("B", 8, "BROUILLA").
dico("B", 8, "BROUILLE").
dico("B", 8, "BROUILLY").
dico("B", 8, "BROUSSES").
dico("B", 8, "BROUSSIN").
dico("B", 8, "BROUTAGE").
dico("B", 8, "BROUTAIS").
dico("B", 8, "BROUTAIT").
dico("B", 8, "BROUTANT").
dico("B", 8, "BROUTARD").
dico("B", 8, "BROUTART").
dico("B", 8, "BROUTEES").
dico("B", 8, "BROUTENT").
dico("B", 8, "BROUTERA").
dico("B", 8, "BROUTIEZ").
dico("B", 8, "BROUTONS").
dico("B", 8, "BROWNIEN").
dico("B", 8, "BROWNIES").
dico("B", 8, "BROWNING").
dico("B", 8, "BROYAGES").
dico("B", 8, "BROYAMES").
dico("B", 8, "BROYASSE").
dico("B", 8, "BROYATES").
dico("B", 8, "BROYEURS").
dico("B", 8, "BROYEUSE").
dico("B", 8, "BROYIONS").
dico("B", 8, "BRUCCIOS").
dico("B", 8, "BRUCELLA").
dico("B", 8, "BRUCINES").
dico("B", 8, "BRUGEOIS").
dico("B", 8, "BRUGNONS").
dico("B", 8, "BRUINAIT").
dico("B", 8, "BRUINERA").
dico("B", 8, "BRUINEUX").
dico("B", 8, "BRUIRAIS").
dico("B", 8, "BRUIRAIT").
dico("B", 8, "BRUIRENT").
dico("B", 8, "BRUIRIEZ").
dico("B", 8, "BRUIRONS").
dico("B", 8, "BRUIRONT").
dico("B", 8, "BRUISSAI").
dico("B", 8, "BRUISSAS").
dico("B", 8, "BRUISSAT").
dico("B", 8, "BRUISSER").
dico("B", 8, "BRUISSES").
dico("B", 8, "BRUISSEZ").
dico("B", 8, "BRUITAGE").
dico("B", 8, "BRUITAIS").
dico("B", 8, "BRUITAIT").
dico("B", 8, "BRUITANT").
dico("B", 8, "BRUITEES").
dico("B", 8, "BRUITENT").
dico("B", 8, "BRUITERA").
dico("B", 8, "BRUITEUR").
dico("B", 8, "BRUITIEZ").
dico("B", 8, "BRUITONS").
dico("B", 8, "BRULAGES").
dico("B", 8, "BRULAMES").
dico("B", 8, "BRULANTE").
dico("B", 8, "BRULANTS").
dico("B", 8, "BRULASSE").
dico("B", 8, "BRULATES").
dico("B", 8, "BRULERAI").
dico("B", 8, "BRULERAS").
dico("B", 8, "BRULEREZ").
dico("B", 8, "BRULERIE").
dico("B", 8, "BRULEURS").
dico("B", 8, "BRULEUSE").
dico("B", 8, "BRULIONS").
dico("B", 8, "BRULOIRS").
dico("B", 8, "BRULURES").
dico("B", 8, "BRUMAIRE").
dico("B", 8, "BRUMASSA").
dico("B", 8, "BRUMASSE").
dico("B", 8, "BRUMEUSE").
dico("B", 8, "BRUNANTE").
dico("B", 8, "BRUNATRE").
dico("B", 8, "BRUNCHAI").
dico("B", 8, "BRUNCHAS").
dico("B", 8, "BRUNCHAT").
dico("B", 8, "BRUNCHER").
dico("B", 8, "BRUNCHES").
dico("B", 8, "BRUNCHEZ").
dico("B", 8, "BRUNEIEN").
dico("B", 8, "BRUNETTE").
dico("B", 8, "BRUNIMES").
dico("B", 8, "BRUNIRAI").
dico("B", 8, "BRUNIRAS").
dico("B", 8, "BRUNIREZ").
dico("B", 8, "BRUNISSE").
dico("B", 8, "BRUNITES").
dico("B", 8, "BRUNOISE").
dico("B", 8, "BRUSHING").
dico("B", 8, "BRUSQUAI").
dico("B", 8, "BRUSQUAS").
dico("B", 8, "BRUSQUAT").
dico("B", 8, "BRUSQUEE").
dico("B", 8, "BRUSQUER").
dico("B", 8, "BRUSQUES").
dico("B", 8, "BRUSQUEZ").
dico("B", 8, "BRUTALES").
dico("B", 8, "BRUTIONS").
dico("B", 8, "BRUXISME").
dico("B", 8, "BRUYANTE").
dico("B", 8, "BRUYANTS").
dico("B", 8, "BRUYERES").
dico("B", 8, "BUANDIER").
dico("B", 8, "BUCAILLE").
dico("B", 8, "BUCCALES").
dico("B", 8, "BUCHAMES").
dico("B", 8, "BUCHASSE").
dico("B", 8, "BUCHATES").
dico("B", 8, "BUCHERAI").
dico("B", 8, "BUCHERAS").
dico("B", 8, "BUCHEREZ").
dico("B", 8, "BUCHERON").
dico("B", 8, "BUCHETTE").
dico("B", 8, "BUCHEURS").
dico("B", 8, "BUCHEUSE").
dico("B", 8, "BUCHIONS").
dico("B", 8, "BUCRANES").
dico("B", 8, "BUDDLEIA").
dico("B", 8, "BUDGETAI").
dico("B", 8, "BUDGETAS").
dico("B", 8, "BUDGETAT").
dico("B", 8, "BUDGETEE").
dico("B", 8, "BUDGETER").
dico("B", 8, "BUDGETES").
dico("B", 8, "BUDGETEZ").
dico("B", 8, "BUFFLAGE").
dico("B", 8, "BUFFLAIS").
dico("B", 8, "BUFFLAIT").
dico("B", 8, "BUFFLANT").
dico("B", 8, "BUFFLEES").
dico("B", 8, "BUFFLENT").
dico("B", 8, "BUFFLERA").
dico("B", 8, "BUFFLIEZ").
dico("B", 8, "BUFFLONS").
dico("B", 8, "BUGLOSSE").
dico("B", 8, "BUGRANES").
dico("B", 8, "BUILDING").
dico("B", 8, "BUISSAIE").
dico("B", 8, "BUISSONS").
dico("B", 8, "BUKAVIEN").
dico("B", 8, "BULBAIRE").
dico("B", 8, "BULBEUSE").
dico("B", 8, "BULBILLE").
dico("B", 8, "BULGARES").
dico("B", 8, "BULGOMME").
dico("B", 8, "BULLAIRE").
dico("B", 8, "BULLAMES").
dico("B", 8, "BULLASSE").
dico("B", 8, "BULLATES").
dico("B", 8, "BULLDOGS").
dico("B", 8, "BULLERAI").
dico("B", 8, "BULLERAS").
dico("B", 8, "BULLEREZ").
dico("B", 8, "BULLETIN").
dico("B", 8, "BULLEUSE").
dico("B", 8, "BULLIONS").
dico("B", 8, "BUNGALOW").
dico("B", 8, "BUNRAKUS").
dico("B", 8, "BUPRESTE").
dico("B", 8, "BUQUAMES").
dico("B", 8, "BUQUASSE").
dico("B", 8, "BUQUATES").
dico("B", 8, "BUQUERAI").
dico("B", 8, "BUQUERAS").
dico("B", 8, "BUQUEREZ").
dico("B", 8, "BUQUIONS").
dico("B", 8, "BURATINE").
dico("B", 8, "BURATINS").
dico("B", 8, "BURELEES").
dico("B", 8, "BURELLES").
dico("B", 8, "BURETTES").
dico("B", 8, "BURGIENS").
dico("B", 8, "BURGONDE").
dico("B", 8, "BURGRAVE").
dico("B", 8, "BURINAGE").
dico("B", 8, "BURINAIS").
dico("B", 8, "BURINAIT").
dico("B", 8, "BURINANT").
dico("B", 8, "BURINEES").
dico("B", 8, "BURINENT").
dico("B", 8, "BURINERA").
dico("B", 8, "BURINEUR").
dico("B", 8, "BURINIEZ").
dico("B", 8, "BURINONS").
dico("B", 8, "BURMESES").
dico("B", 8, "BURSITES").
dico("B", 8, "BUSAIENT").
dico("B", 8, "BUSAIGLE").
dico("B", 8, "BUSASSES").
dico("B", 8, "BUSERAIS").
dico("B", 8, "BUSERAIT").
dico("B", 8, "BUSERENT").
dico("B", 8, "BUSERIEZ").
dico("B", 8, "BUSERONS").
dico("B", 8, "BUSERONT").
dico("B", 8, "BUSETTES").
dico("B", 8, "BUSHIDOS").
dico("B", 8, "BUSHMANS").
dico("B", 8, "BUSINESS").
dico("B", 8, "BUSQUAIS").
dico("B", 8, "BUSQUAIT").
dico("B", 8, "BUSQUANT").
dico("B", 8, "BUSQUEES").
dico("B", 8, "BUSQUENT").
dico("B", 8, "BUSQUERA").
dico("B", 8, "BUSQUIEZ").
dico("B", 8, "BUSQUONS").
dico("B", 8, "BUSSIONS").
dico("B", 8, "BUSTIERE").
dico("B", 8, "BUSTIERS").
dico("B", 8, "BUTAIENT").
dico("B", 8, "BUTANIER").
dico("B", 8, "BUTANOLS").
dico("B", 8, "BUTASSES").
dico("B", 8, "BUTERAIS").
dico("B", 8, "BUTERAIT").
dico("B", 8, "BUTERENT").
dico("B", 8, "BUTERIEZ").
dico("B", 8, "BUTERONS").
dico("B", 8, "BUTERONT").
dico("B", 8, "BUTEUSES").
dico("B", 8, "BUTINAGE").
dico("B", 8, "BUTINAIS").
dico("B", 8, "BUTINAIT").
dico("B", 8, "BUTINANT").
dico("B", 8, "BUTINEES").
dico("B", 8, "BUTINENT").
dico("B", 8, "BUTINERA").
dico("B", 8, "BUTINEUR").
dico("B", 8, "BUTINIEZ").
dico("B", 8, "BUTINONS").
dico("B", 8, "BUTORDES").
dico("B", 8, "BUTTAGES").
dico("B", 8, "BUTTAMES").
dico("B", 8, "BUTTASSE").
dico("B", 8, "BUTTATES").
dico("B", 8, "BUTTERAI").
dico("B", 8, "BUTTERAS").
dico("B", 8, "BUTTEREZ").
dico("B", 8, "BUTTEURS").
dico("B", 8, "BUTTIONS").
dico("B", 8, "BUTTOIRS").
dico("B", 8, "BUTYLENE").
dico("B", 8, "BUTYRATE").
dico("B", 8, "BUTYREUX").
dico("B", 8, "BUTYRINE").
dico("B", 8, "BUVABLES").
dico("B", 8, "BUVAIENT").
dico("B", 8, "BUVETIER").
dico("B", 8, "BUVETTES").
dico("B", 8, "BUVEUSES").
dico("B", 8, "BUXACEES").
dico("B", 8, "BYRONIEN").
dico("B", 8, "BYZANTIN").
