dico("B", 9, "BAASISMES").
dico("B", 9, "BAASISTES").
dico("B", 9, "BABELIQUE").
dico("B", 9, "BABELISME").
dico("B", 9, "BABELUTTE").
dico("B", 9, "BABEURRES").
dico("B", 9, "BABILLAGE").
dico("B", 9, "BABILLAIS").
dico("B", 9, "BABILLAIT").
dico("B", 9, "BABILLANT").
dico("B", 9, "BABILLARD").
dico("B", 9, "BABILLENT").
dico("B", 9, "BABILLERA").
dico("B", 9, "BABILLIEZ").
dico("B", 9, "BABILLONS").
dico("B", 9, "BABOLAMES").
dico("B", 9, "BABOLASSE").
dico("B", 9, "BABOLATES").
dico("B", 9, "BABOLERAI").
dico("B", 9, "BABOLERAS").
dico("B", 9, "BABOLEREZ").
dico("B", 9, "BABOLIONS").
dico("B", 9, "BABORDAIS").
dico("B", 9, "BABOUCHES").
dico("B", 9, "BABOUCHKA").
dico("B", 9, "BABOUINES").
dico("B", 9, "BACCARATS").
dico("B", 9, "BACCHANAL").
dico("B", 9, "BACCHANTE").
dico("B", 9, "BACCIFERE").
dico("B", 9, "BACCIVORE").
dico("B", 9, "BACHAIENT").
dico("B", 9, "BACHASSES").
dico("B", 9, "BACHELIER").
dico("B", 9, "BACHERAIS").
dico("B", 9, "BACHERAIT").
dico("B", 9, "BACHERENT").
dico("B", 9, "BACHERIEZ").
dico("B", 9, "BACHERONS").
dico("B", 9, "BACHERONT").
dico("B", 9, "BACHIQUES").
dico("B", 9, "BACHOLLES").
dico("B", 9, "BACHOTAGE").
dico("B", 9, "BACHOTAIS").
dico("B", 9, "BACHOTAIT").
dico("B", 9, "BACHOTANT").
dico("B", 9, "BACHOTEES").
dico("B", 9, "BACHOTENT").
dico("B", 9, "BACHOTERA").
dico("B", 9, "BACHOTEUR").
dico("B", 9, "BACHOTIEZ").
dico("B", 9, "BACHOTONS").
dico("B", 9, "BACHOTTES").
dico("B", 9, "BACILLOSE").
dico("B", 9, "BACLAIENT").
dico("B", 9, "BACLASSES").
dico("B", 9, "BACLERAIS").
dico("B", 9, "BACLERAIT").
dico("B", 9, "BACLERENT").
dico("B", 9, "BACLERIEZ").
dico("B", 9, "BACLERONS").
dico("B", 9, "BACLERONT").
dico("B", 9, "BACLEUSES").
dico("B", 9, "BACONIENS").
dico("B", 9, "BACTERIEN").
dico("B", 9, "BACTERIES").
dico("B", 9, "BADAMIERS").
dico("B", 9, "BADASSENT").
dico("B", 9, "BADASSIEZ").
dico("B", 9, "BADAUDAIS").
dico("B", 9, "BADAUDAIT").
dico("B", 9, "BADAUDANT").
dico("B", 9, "BADAUDENT").
dico("B", 9, "BADAUDERA").
dico("B", 9, "BADAUDIEZ").
dico("B", 9, "BADAUDONS").
dico("B", 9, "BADELAIRE").
dico("B", 9, "BADERIONS").
dico("B", 9, "BADGEAMES").
dico("B", 9, "BADGEASSE").
dico("B", 9, "BADGEATES").
dico("B", 9, "BADGERAIS").
dico("B", 9, "BADGERAIT").
dico("B", 9, "BADGERENT").
dico("B", 9, "BADGERIEZ").
dico("B", 9, "BADGERONS").
dico("B", 9, "BADGERONT").
dico("B", 9, "BADGEUSES").
dico("B", 9, "BADIGEONS").
dico("B", 9, "BADINAGES").
dico("B", 9, "BADINAMES").
dico("B", 9, "BADINASSE").
dico("B", 9, "BADINATES").
dico("B", 9, "BADINERAI").
dico("B", 9, "BADINERAS").
dico("B", 9, "BADINEREZ").
dico("B", 9, "BADINERIE").
dico("B", 9, "BADINIONS").
dico("B", 9, "BADMINTON").
dico("B", 9, "BAECKEOFE").
dico("B", 9, "BAFFAIENT").
dico("B", 9, "BAFFASSES").
dico("B", 9, "BAFFERAIS").
dico("B", 9, "BAFFERAIT").
dico("B", 9, "BAFFERENT").
dico("B", 9, "BAFFERIEZ").
dico("B", 9, "BAFFERONS").
dico("B", 9, "BAFFERONT").
dico("B", 9, "BAFOUAMES").
dico("B", 9, "BAFOUASSE").
dico("B", 9, "BAFOUATES").
dico("B", 9, "BAFOUERAI").
dico("B", 9, "BAFOUERAS").
dico("B", 9, "BAFOUEREZ").
dico("B", 9, "BAFOUILLA").
dico("B", 9, "BAFOUILLE").
dico("B", 9, "BAFOUIONS").
dico("B", 9, "BAFRAIENT").
dico("B", 9, "BAFRASSES").
dico("B", 9, "BAFRERAIS").
dico("B", 9, "BAFRERAIT").
dico("B", 9, "BAFRERENT").
dico("B", 9, "BAFRERIEZ").
dico("B", 9, "BAFRERONS").
dico("B", 9, "BAFRERONT").
dico("B", 9, "BAFREUSES").
dico("B", 9, "BAGAGISTE").
dico("B", 9, "BAGARRAIS").
dico("B", 9, "BAGARRAIT").
dico("B", 9, "BAGARRANT").
dico("B", 9, "BAGARREES").
dico("B", 9, "BAGARRENT").
dico("B", 9, "BAGARRERA").
dico("B", 9, "BAGARREUR").
dico("B", 9, "BAGARRIEZ").
dico("B", 9, "BAGARRONS").
dico("B", 9, "BAGATELLE").
dico("B", 9, "BAGDADIEN").
dico("B", 9, "BAGNARDES").
dico("B", 9, "BAGUAIENT").
dico("B", 9, "BAGUASSES").
dico("B", 9, "BAGUERAIS").
dico("B", 9, "BAGUERAIT").
dico("B", 9, "BAGUERENT").
dico("B", 9, "BAGUERIEZ").
dico("B", 9, "BAGUERONS").
dico("B", 9, "BAGUERONT").
dico("B", 9, "BAGUETTES").
dico("B", 9, "BAHAISMES").
dico("B", 9, "BAHAMEENS").
dico("B", 9, "BAHAMIENS").
dico("B", 9, "BAHREINIE").
dico("B", 9, "BAHREINIS").
dico("B", 9, "BAHUTAGES").
dico("B", 9, "BAIERIONS").
dico("B", 9, "BAIGNADES").
dico("B", 9, "BAIGNAMES").
dico("B", 9, "BAIGNASSE").
dico("B", 9, "BAIGNATES").
dico("B", 9, "BAIGNERAI").
dico("B", 9, "BAIGNERAS").
dico("B", 9, "BAIGNEREZ").
dico("B", 9, "BAIGNEURS").
dico("B", 9, "BAIGNEUSE").
dico("B", 9, "BAIGNIONS").
dico("B", 9, "BAIGNOIRE").
dico("B", 9, "BAILLAMES").
dico("B", 9, "BAILLASSE").
dico("B", 9, "BAILLATES").
dico("B", 9, "BAILLERAI").
dico("B", 9, "BAILLERAS").
dico("B", 9, "BAILLEREZ").
dico("B", 9, "BAILLEURS").
dico("B", 9, "BAILLEUSE").
dico("B", 9, "BAILLIAGE").
dico("B", 9, "BAILLIONS").
dico("B", 9, "BAILLIVES").
dico("B", 9, "BAILLONNA").
dico("B", 9, "BAILLONNE").
dico("B", 9, "BAISABLES").
dico("B", 9, "BAISAIENT").
dico("B", 9, "BAISASSES").
dico("B", 9, "BAISEMAIN").
dico("B", 9, "BAISEMENT").
dico("B", 9, "BAISERAIS").
dico("B", 9, "BAISERAIT").
dico("B", 9, "BAISERENT").
dico("B", 9, "BAISERIEZ").
dico("B", 9, "BAISERONS").
dico("B", 9, "BAISERONT").
dico("B", 9, "BAISEUSES").
dico("B", 9, "BAISOTAIS").
dico("B", 9, "BAISOTAIT").
dico("B", 9, "BAISOTANT").
dico("B", 9, "BAISOTEES").
dico("B", 9, "BAISOTENT").
dico("B", 9, "BAISOTERA").
dico("B", 9, "BAISOTIEZ").
dico("B", 9, "BAISOTONS").
dico("B", 9, "BAISSAMES").
dico("B", 9, "BAISSASSE").
dico("B", 9, "BAISSATES").
dico("B", 9, "BAISSERAI").
dico("B", 9, "BAISSERAS").
dico("B", 9, "BAISSEREZ").
dico("B", 9, "BAISSIERE").
dico("B", 9, "BAISSIERS").
dico("B", 9, "BAISSIONS").
dico("B", 9, "BAJOCIENS").
dico("B", 9, "BAKCHICHS").
dico("B", 9, "BAKELITES").
dico("B", 9, "BALADAMES").
dico("B", 9, "BALADASSE").
dico("B", 9, "BALADATES").
dico("B", 9, "BALADERAI").
dico("B", 9, "BALADERAS").
dico("B", 9, "BALADEREZ").
dico("B", 9, "BALADEURS").
dico("B", 9, "BALADEUSE").
dico("B", 9, "BALADINES").
dico("B", 9, "BALADIONS").
dico("B", 9, "BALAFRAIS").
dico("B", 9, "BALAFRAIT").
dico("B", 9, "BALAFRANT").
dico("B", 9, "BALAFREES").
dico("B", 9, "BALAFRENT").
dico("B", 9, "BALAFRERA").
dico("B", 9, "BALAFRIEZ").
dico("B", 9, "BALAFRONS").
dico("B", 9, "BALAIERAI").
dico("B", 9, "BALAIERAS").
dico("B", 9, "BALAIEREZ").
dico("B", 9, "BALALAIKA").
dico("B", 9, "BALANCAIS").
dico("B", 9, "BALANCAIT").
dico("B", 9, "BALANCANT").
dico("B", 9, "BALANCEES").
dico("B", 9, "BALANCENT").
dico("B", 9, "BALANCERA").
dico("B", 9, "BALANCIER").
dico("B", 9, "BALANCIEZ").
dico("B", 9, "BALANCINE").
dico("B", 9, "BALANCONS").
dico("B", 9, "BALANDRES").
dico("B", 9, "BALANITES").
dico("B", 9, "BALAYAGES").
dico("B", 9, "BALAYAMES").
dico("B", 9, "BALAYASSE").
dico("B", 9, "BALAYATES").
dico("B", 9, "BALAYERAI").
dico("B", 9, "BALAYERAS").
dico("B", 9, "BALAYEREZ").
dico("B", 9, "BALAYETTE").
dico("B", 9, "BALAYEURS").
dico("B", 9, "BALAYEUSE").
dico("B", 9, "BALAYIONS").
dico("B", 9, "BALAYURES").
dico("B", 9, "BALBUTIAI").
dico("B", 9, "BALBUTIAS").
dico("B", 9, "BALBUTIAT").
dico("B", 9, "BALBUTIEE").
dico("B", 9, "BALBUTIER").
dico("B", 9, "BALBUTIES").
dico("B", 9, "BALBUTIEZ").
dico("B", 9, "BALBUZARD").
dico("B", 9, "BALBYNIEN").
dico("B", 9, "BALCONNET").
dico("B", 9, "BALDAQUIN").
dico("B", 9, "BALEINAGE").
dico("B", 9, "BALEINEAU").
dico("B", 9, "BALEINEES").
dico("B", 9, "BALEINIER").
dico("B", 9, "BALENIDES").
dico("B", 9, "BALESTRON").
dico("B", 9, "BALINAISE").
dico("B", 9, "BALISAGES").
dico("B", 9, "BALISAMES").
dico("B", 9, "BALISASSE").
dico("B", 9, "BALISATES").
dico("B", 9, "BALISERAI").
dico("B", 9, "BALISERAS").
dico("B", 9, "BALISEREZ").
dico("B", 9, "BALISEURS").
dico("B", 9, "BALISEUSE").
dico("B", 9, "BALISIERS").
dico("B", 9, "BALISIONS").
dico("B", 9, "BALISTITE").
dico("B", 9, "BALIVAGES").
dico("B", 9, "BALIVAMES").
dico("B", 9, "BALIVASSE").
dico("B", 9, "BALIVATES").
dico("B", 9, "BALIVEAUX").
dico("B", 9, "BALIVERAI").
dico("B", 9, "BALIVERAS").
dico("B", 9, "BALIVEREZ").
dico("B", 9, "BALIVERNE").
dico("B", 9, "BALIVIONS").
dico("B", 9, "BALKANISA").
dico("B", 9, "BALKANISE").
dico("B", 9, "BALLAIENT").
dico("B", 9, "BALLANTES").
dico("B", 9, "BALLASSES").
dico("B", 9, "BALLASTAI").
dico("B", 9, "BALLASTAS").
dico("B", 9, "BALLASTAT").
dico("B", 9, "BALLASTEE").
dico("B", 9, "BALLASTER").
dico("B", 9, "BALLASTES").
dico("B", 9, "BALLASTEZ").
dico("B", 9, "BALLERAIS").
dico("B", 9, "BALLERAIT").
dico("B", 9, "BALLERENT").
dico("B", 9, "BALLERIEZ").
dico("B", 9, "BALLERINE").
dico("B", 9, "BALLERONS").
dico("B", 9, "BALLERONT").
dico("B", 9, "BALLONNAI").
dico("B", 9, "BALLONNAS").
dico("B", 9, "BALLONNAT").
dico("B", 9, "BALLONNEE").
dico("B", 9, "BALLONNER").
dico("B", 9, "BALLONNES").
dico("B", 9, "BALLONNET").
dico("B", 9, "BALLONNEZ").
dico("B", 9, "BALLOTINS").
dico("B", 9, "BALLOTTAI").
dico("B", 9, "BALLOTTAS").
dico("B", 9, "BALLOTTAT").
dico("B", 9, "BALLOTTEE").
dico("B", 9, "BALLOTTER").
dico("B", 9, "BALLOTTES").
dico("B", 9, "BALLOTTEZ").
dico("B", 9, "BALLUCHON").
dico("B", 9, "BALNEAIRE").
dico("B", 9, "BALOURDES").
dico("B", 9, "BALOUTCHI").
dico("B", 9, "BALSAMIER").
dico("B", 9, "BALSAMINE").
dico("B", 9, "BALTHASAR").
dico("B", 9, "BALTHAZAR").
dico("B", 9, "BALTIQUES").
dico("B", 9, "BALUCHONS").
dico("B", 9, "BALUSTRES").
dico("B", 9, "BALZACIEN").
dico("B", 9, "BAMAKOISE").
dico("B", 9, "BAMBOCHAI").
dico("B", 9, "BAMBOCHAS").
dico("B", 9, "BAMBOCHAT").
dico("B", 9, "BAMBOCHER").
dico("B", 9, "BAMBOCHES").
dico("B", 9, "BAMBOCHEZ").
dico("B", 9, "BAMBOULAS").
dico("B", 9, "BANALISAI").
dico("B", 9, "BANALISAS").
dico("B", 9, "BANALISAT").
dico("B", 9, "BANALISEE").
dico("B", 9, "BANALISER").
dico("B", 9, "BANALISES").
dico("B", 9, "BANALISEZ").
dico("B", 9, "BANALITES").
dico("B", 9, "BANANAMES").
dico("B", 9, "BANANASSE").
dico("B", 9, "BANANATES").
dico("B", 9, "BANANERAI").
dico("B", 9, "BANANERAS").
dico("B", 9, "BANANEREZ").
dico("B", 9, "BANANIERE").
dico("B", 9, "BANANIERS").
dico("B", 9, "BANANIONS").
dico("B", 9, "BANCABLES").
dico("B", 9, "BANCAIRES").
dico("B", 9, "BANCARISA").
dico("B", 9, "BANCARISE").
dico("B", 9, "BANCHAGES").
dico("B", 9, "BANCHAMES").
dico("B", 9, "BANCHASSE").
dico("B", 9, "BANCHATES").
dico("B", 9, "BANCHERAI").
dico("B", 9, "BANCHERAS").
dico("B", 9, "BANCHEREZ").
dico("B", 9, "BANCHIONS").
dico("B", 9, "BANCROCHE").
dico("B", 9, "BANDAIENT").
dico("B", 9, "BANDANTES").
dico("B", 9, "BANDASSES").
dico("B", 9, "BANDERAIS").
dico("B", 9, "BANDERAIT").
dico("B", 9, "BANDERENT").
dico("B", 9, "BANDERIEZ").
dico("B", 9, "BANDEROLE").
dico("B", 9, "BANDERONS").
dico("B", 9, "BANDERONT").
dico("B", 9, "BANDIERES").
dico("B", 9, "BANDONEON").
dico("B", 9, "BANJOISTE").
dico("B", 9, "BANJULAIS").
dico("B", 9, "BANLIEUES").
dico("B", 9, "BANNERETS").
dico("B", 9, "BANNETONS").
dico("B", 9, "BANNETTES").
dico("B", 9, "BANNIERES").
dico("B", 9, "BANNIRAIS").
dico("B", 9, "BANNIRAIT").
dico("B", 9, "BANNIRENT").
dico("B", 9, "BANNIRIEZ").
dico("B", 9, "BANNIRONS").
dico("B", 9, "BANNIRONT").
dico("B", 9, "BANNISSES").
dico("B", 9, "BANNISSEZ").
dico("B", 9, "BANQUABLE").
dico("B", 9, "BANQUAMES").
dico("B", 9, "BANQUASSE").
dico("B", 9, "BANQUATES").
dico("B", 9, "BANQUERAI").
dico("B", 9, "BANQUERAS").
dico("B", 9, "BANQUEREZ").
dico("B", 9, "BANQUETAI").
dico("B", 9, "BANQUETAS").
dico("B", 9, "BANQUETAT").
dico("B", 9, "BANQUETER").
dico("B", 9, "BANQUETEZ").
dico("B", 9, "BANQUETTE").
dico("B", 9, "BANQUIERE").
dico("B", 9, "BANQUIERS").
dico("B", 9, "BANQUIONS").
dico("B", 9, "BANQUISES").
dico("B", 9, "BANQUISTE").
dico("B", 9, "BAPTISAIS").
dico("B", 9, "BAPTISAIT").
dico("B", 9, "BAPTISANT").
dico("B", 9, "BAPTISEES").
dico("B", 9, "BAPTISENT").
dico("B", 9, "BAPTISERA").
dico("B", 9, "BAPTISIEZ").
dico("B", 9, "BAPTISMAL").
dico("B", 9, "BAPTISMES").
dico("B", 9, "BAPTISONS").
dico("B", 9, "BAPTISTES").
dico("B", 9, "BAQUAIENT").
dico("B", 9, "BAQUASSES").
dico("B", 9, "BAQUERAIS").
dico("B", 9, "BAQUERAIT").
dico("B", 9, "BAQUERENT").
dico("B", 9, "BAQUERIEZ").
dico("B", 9, "BAQUERONS").
dico("B", 9, "BAQUERONT").
dico("B", 9, "BAQUETAIS").
dico("B", 9, "BAQUETAIT").
dico("B", 9, "BAQUETANT").
dico("B", 9, "BAQUETEES").
dico("B", 9, "BAQUETIEZ").
dico("B", 9, "BAQUETONS").
dico("B", 9, "BAQUETTES").
dico("B", 9, "BARACHOIS").
dico("B", 9, "BARAGOUIN").
dico("B", 9, "BARAQUAIS").
dico("B", 9, "BARAQUAIT").
dico("B", 9, "BARAQUANT").
dico("B", 9, "BARAQUEES").
dico("B", 9, "BARAQUENT").
dico("B", 9, "BARAQUERA").
dico("B", 9, "BARAQUIEZ").
dico("B", 9, "BARAQUONS").
dico("B", 9, "BARATERIE").
dico("B", 9, "BARATINAI").
dico("B", 9, "BARATINAS").
dico("B", 9, "BARATINAT").
dico("B", 9, "BARATINEE").
dico("B", 9, "BARATINER").
dico("B", 9, "BARATINES").
dico("B", 9, "BARATINEZ").
dico("B", 9, "BARATTAGE").
dico("B", 9, "BARATTAIS").
dico("B", 9, "BARATTAIT").
dico("B", 9, "BARATTANT").
dico("B", 9, "BARATTEES").
dico("B", 9, "BARATTENT").
dico("B", 9, "BARATTERA").
dico("B", 9, "BARATTIEZ").
dico("B", 9, "BARATTONS").
dico("B", 9, "BARBACANE").
dico("B", 9, "BARBADIEN").
dico("B", 9, "BARBAIENT").
dico("B", 9, "BARBANTES").
dico("B", 9, "BARBAQUES").
dico("B", 9, "BARBARIES").
dico("B", 9, "BARBARISA").
dico("B", 9, "BARBARISE").
dico("B", 9, "BARBASSES").
dico("B", 9, "BARBECUES").
dico("B", 9, "BARBELEES").
dico("B", 9, "BARBELURE").
dico("B", 9, "BARBERAIS").
dico("B", 9, "BARBERAIT").
dico("B", 9, "BARBERENT").
dico("B", 9, "BARBERIEZ").
dico("B", 9, "BARBERONS").
dico("B", 9, "BARBERONT").
dico("B", 9, "BARBETTES").
dico("B", 9, "BARBICHES").
dico("B", 9, "BARBICHUE").
dico("B", 9, "BARBICHUS").
dico("B", 9, "BARBIERES").
dico("B", 9, "BARBIFIAI").
dico("B", 9, "BARBIFIAS").
dico("B", 9, "BARBIFIAT").
dico("B", 9, "BARBIFIEE").
dico("B", 9, "BARBIFIER").
dico("B", 9, "BARBIFIES").
dico("B", 9, "BARBIFIEZ").
dico("B", 9, "BARBILLES").
dico("B", 9, "BARBILLON").
dico("B", 9, "BARBITALS").
dico("B", 9, "BARBOTAGE").
dico("B", 9, "BARBOTAIS").
dico("B", 9, "BARBOTAIT").
dico("B", 9, "BARBOTANT").
dico("B", 9, "BARBOTEES").
dico("B", 9, "BARBOTENT").
dico("B", 9, "BARBOTERA").
dico("B", 9, "BARBOTEUR").
dico("B", 9, "BARBOTIEZ").
dico("B", 9, "BARBOTINE").
dico("B", 9, "BARBOTINS").
dico("B", 9, "BARBOTONS").
dico("B", 9, "BARBOTTES").
dico("B", 9, "BARBOUZES").
dico("B", 9, "BARBUDIEN").
dico("B", 9, "BARCASSES").
dico("B", 9, "BARDAIENT").
dico("B", 9, "BARDASSAI").
dico("B", 9, "BARDASSAS").
dico("B", 9, "BARDASSAT").
dico("B", 9, "BARDASSEE").
dico("B", 9, "BARDASSER").
dico("B", 9, "BARDASSES").
dico("B", 9, "BARDASSEZ").
dico("B", 9, "BARDELLES").
dico("B", 9, "BARDERAIS").
dico("B", 9, "BARDERAIT").
dico("B", 9, "BARDERENT").
dico("B", 9, "BARDERIEZ").
dico("B", 9, "BARDERONS").
dico("B", 9, "BARDERONT").
dico("B", 9, "BARDOLINO").
dico("B", 9, "BAREFOOTS").
dico("B", 9, "BAREMIQUE").
dico("B", 9, "BARETAMES").
dico("B", 9, "BARETASSE").
dico("B", 9, "BARETATES").
dico("B", 9, "BARETERAI").
dico("B", 9, "BARETERAS").
dico("B", 9, "BARETEREZ").
dico("B", 9, "BARETIONS").
dico("B", 9, "BARGUIGNA").
dico("B", 9, "BARGUIGNE").
dico("B", 9, "BARIGOULE").
dico("B", 9, "BARILLETS").
dico("B", 9, "BARIOLAGE").
dico("B", 9, "BARIOLAIS").
dico("B", 9, "BARIOLAIT").
dico("B", 9, "BARIOLANT").
dico("B", 9, "BARIOLEES").
dico("B", 9, "BARIOLENT").
dico("B", 9, "BARIOLERA").
dico("B", 9, "BARIOLIEZ").
dico("B", 9, "BARIOLONS").
dico("B", 9, "BARIOLURE").
dico("B", 9, "BARISIENS").
dico("B", 9, "BARJAQUAI").
dico("B", 9, "BARJAQUAS").
dico("B", 9, "BARJAQUAT").
dico("B", 9, "BARJAQUER").
dico("B", 9, "BARJAQUES").
dico("B", 9, "BARJAQUEZ").
dico("B", 9, "BARKHANES").
dico("B", 9, "BARLONGUE").
dico("B", 9, "BARNABITE").
dico("B", 9, "BARNACHES").
dico("B", 9, "BARNACLES").
dico("B", 9, "BAROMETRE").
dico("B", 9, "BARONNAGE").
dico("B", 9, "BARONNETS").
dico("B", 9, "BARONNIAL").
dico("B", 9, "BARONNIES").
dico("B", 9, "BAROQUEUX").
dico("B", 9, "BAROSCOPE").
dico("B", 9, "BAROUDAIS").
dico("B", 9, "BAROUDAIT").
dico("B", 9, "BAROUDANT").
dico("B", 9, "BAROUDENT").
dico("B", 9, "BAROUDERA").
dico("B", 9, "BAROUDEUR").
dico("B", 9, "BAROUDIEZ").
dico("B", 9, "BAROUDONS").
dico("B", 9, "BAROUFLES").
dico("B", 9, "BARQUETTE").
dico("B", 9, "BARRACUDA").
dico("B", 9, "BARRAIENT").
dico("B", 9, "BARRANCOS").
dico("B", 9, "BARRASSES").
dico("B", 9, "BARREMENT").
dico("B", 9, "BARRERAIS").
dico("B", 9, "BARRERAIT").
dico("B", 9, "BARRERENT").
dico("B", 9, "BARRERIEZ").
dico("B", 9, "BARRERONS").
dico("B", 9, "BARRERONT").
dico("B", 9, "BARRETTES").
dico("B", 9, "BARREUSES").
dico("B", 9, "BARRICADA").
dico("B", 9, "BARRICADE").
dico("B", 9, "BARRIERES").
dico("B", 9, "BARRIQUES").
dico("B", 9, "BARRIRAIS").
dico("B", 9, "BARRIRAIT").
dico("B", 9, "BARRIRENT").
dico("B", 9, "BARRIRIEZ").
dico("B", 9, "BARRIRONS").
dico("B", 9, "BARRIRONT").
dico("B", 9, "BARRISSES").
dico("B", 9, "BARRISSEZ").
dico("B", 9, "BARYTINES").
dico("B", 9, "BARYTITES").
dico("B", 9, "BASANAMES").
dico("B", 9, "BASANASSE").
dico("B", 9, "BASANATES").
dico("B", 9, "BASANERAI").
dico("B", 9, "BASANERAS").
dico("B", 9, "BASANEREZ").
dico("B", 9, "BASANIONS").
dico("B", 9, "BASASSENT").
dico("B", 9, "BASASSIEZ").
dico("B", 9, "BASCULAIS").
dico("B", 9, "BASCULAIT").
dico("B", 9, "BASCULANT").
dico("B", 9, "BASCULEES").
dico("B", 9, "BASCULENT").
dico("B", 9, "BASCULERA").
dico("B", 9, "BASCULEUR").
dico("B", 9, "BASCULIEZ").
dico("B", 9, "BASCULONS").
dico("B", 9, "BASEBALLS").
dico("B", 9, "BASERIONS").
dico("B", 9, "BASICITES").
dico("B", 9, "BASILAIRE").
dico("B", 9, "BASILICAL").
dico("B", 9, "BASILIQUE").
dico("B", 9, "BASIPHILE").
dico("B", 9, "BASOCHIEN").
dico("B", 9, "BASOPHILE").
dico("B", 9, "BASQUAISE").
dico("B", 9, "BASQUINES").
dico("B", 9, "BASSECOUR").
dico("B", 9, "BASSEMENT").
dico("B", 9, "BASSESSES").
dico("B", 9, "BASSETTES").
dico("B", 9, "BASSINAGE").
dico("B", 9, "BASSINAIS").
dico("B", 9, "BASSINAIT").
dico("B", 9, "BASSINANT").
dico("B", 9, "BASSINEES").
dico("B", 9, "BASSINENT").
dico("B", 9, "BASSINERA").
dico("B", 9, "BASSINETS").
dico("B", 9, "BASSINIEZ").
dico("B", 9, "BASSINONS").
dico("B", 9, "BASSISTES").
dico("B", 9, "BASTAGUES").
dico("B", 9, "BASTAIENT").
dico("B", 9, "BASTAINGS").
dico("B", 9, "BASTAQUES").
dico("B", 9, "BASTASSES").
dico("B", 9, "BASTERAIS").
dico("B", 9, "BASTERAIT").
dico("B", 9, "BASTERENT").
dico("B", 9, "BASTERIEZ").
dico("B", 9, "BASTERNES").
dico("B", 9, "BASTERONS").
dico("B", 9, "BASTERONT").
dico("B", 9, "BASTIAISE").
dico("B", 9, "BASTIDONS").
dico("B", 9, "BASTILLEE").
dico("B", 9, "BASTILLES").
dico("B", 9, "BASTILLON").
dico("B", 9, "BASTIONNA").
dico("B", 9, "BASTIONNE").
dico("B", 9, "BASTONNAI").
dico("B", 9, "BASTONNAS").
dico("B", 9, "BASTONNAT").
dico("B", 9, "BASTONNEE").
dico("B", 9, "BASTONNER").
dico("B", 9, "BASTONNES").
dico("B", 9, "BASTONNEZ").
dico("B", 9, "BATACLANS").
dico("B", 9, "BATAILLAI").
dico("B", 9, "BATAILLAS").
dico("B", 9, "BATAILLAT").
dico("B", 9, "BATAILLER").
dico("B", 9, "BATAILLES").
dico("B", 9, "BATAILLEZ").
dico("B", 9, "BATAILLON").
dico("B", 9, "BATARDEAU").
dico("B", 9, "BATARDISE").
dico("B", 9, "BATASSENT").
dico("B", 9, "BATASSIEZ").
dico("B", 9, "BATAVIQUE").
dico("B", 9, "BATAYOLES").
dico("B", 9, "BATELAGES").
dico("B", 9, "BATELAMES").
dico("B", 9, "BATELASSE").
dico("B", 9, "BATELATES").
dico("B", 9, "BATELEURS").
dico("B", 9, "BATELEUSE").
dico("B", 9, "BATELIERE").
dico("B", 9, "BATELIERS").
dico("B", 9, "BATELIONS").
dico("B", 9, "BATELLENT").
dico("B", 9, "BATELLERA").
dico("B", 9, "BATERIONS").
dico("B", 9, "BATHOLITE").
dico("B", 9, "BATHYALES").
dico("B", 9, "BATIFOLAI").
dico("B", 9, "BATIFOLAS").
dico("B", 9, "BATIFOLAT").
dico("B", 9, "BATIFOLER").
dico("B", 9, "BATIFOLES").
dico("B", 9, "BATIFOLEZ").
dico("B", 9, "BATILLAGE").
dico("B", 9, "BATIMENTS").
dico("B", 9, "BATIRIONS").
dico("B", 9, "BATISSAIS").
dico("B", 9, "BATISSAIT").
dico("B", 9, "BATISSANT").
dico("B", 9, "BATISSENT").
dico("B", 9, "BATISSEUR").
dico("B", 9, "BATISSIEZ").
dico("B", 9, "BATISSONS").
dico("B", 9, "BATOILLAI").
dico("B", 9, "BATOILLAS").
dico("B", 9, "BATOILLAT").
dico("B", 9, "BATOILLER").
dico("B", 9, "BATOILLES").
dico("B", 9, "BATOILLEZ").
dico("B", 9, "BATONNAIS").
dico("B", 9, "BATONNAIT").
dico("B", 9, "BATONNANT").
dico("B", 9, "BATONNATS").
dico("B", 9, "BATONNEES").
dico("B", 9, "BATONNENT").
dico("B", 9, "BATONNERA").
dico("B", 9, "BATONNETS").
dico("B", 9, "BATONNIER").
dico("B", 9, "BATONNIEZ").
dico("B", 9, "BATONNONS").
dico("B", 9, "BATRACIEN").
dico("B", 9, "BATTABLES").
dico("B", 9, "BATTAIENT").
dico("B", 9, "BATTANTES").
dico("B", 9, "BATTEMENT").
dico("B", 9, "BATTERIES").
dico("B", 9, "BATTEUSES").
dico("B", 9, "BATTIRENT").
dico("B", 9, "BATTISSES").
dico("B", 9, "BATTITURE").
dico("B", 9, "BATTRIONS").
dico("B", 9, "BAUDRIERS").
dico("B", 9, "BAUDROIES").
dico("B", 9, "BAUDRUCHE").
dico("B", 9, "BAUGEAMES").
dico("B", 9, "BAUGEASSE").
dico("B", 9, "BAUGEATES").
dico("B", 9, "BAUGERAIS").
dico("B", 9, "BAUGERAIT").
dico("B", 9, "BAUGERENT").
dico("B", 9, "BAUGERIEZ").
dico("B", 9, "BAUGERONS").
dico("B", 9, "BAUGERONT").
dico("B", 9, "BAUHINIAS").
dico("B", 9, "BAUHINIES").
dico("B", 9, "BAUQUIERE").
dico("B", 9, "BAVARDAGE").
dico("B", 9, "BAVARDAIS").
dico("B", 9, "BAVARDAIT").
dico("B", 9, "BAVARDANT").
dico("B", 9, "BAVARDENT").
dico("B", 9, "BAVARDERA").
dico("B", 9, "BAVARDIEZ").
dico("B", 9, "BAVARDONS").
dico("B", 9, "BAVAROISE").
dico("B", 9, "BAVASSAIS").
dico("B", 9, "BAVASSAIT").
dico("B", 9, "BAVASSANT").
dico("B", 9, "BAVASSENT").
dico("B", 9, "BAVASSERA").
dico("B", 9, "BAVASSIEZ").
dico("B", 9, "BAVASSONS").
dico("B", 9, "BAVERIONS").
dico("B", 9, "BAVOCHAIS").
dico("B", 9, "BAVOCHAIT").
dico("B", 9, "BAVOCHANT").
dico("B", 9, "BAVOCHEES").
dico("B", 9, "BAVOCHENT").
dico("B", 9, "BAVOCHERA").
dico("B", 9, "BAVOCHIEZ").
dico("B", 9, "BAVOCHONS").
dico("B", 9, "BAVOCHURE").
dico("B", 9, "BAYADERES").
dico("B", 9, "BAYASSENT").
dico("B", 9, "BAYASSIEZ").
dico("B", 9, "BAYERIONS").
dico("B", 9, "BAYONNAIS").
dico("B", 9, "BAZARDAIS").
dico("B", 9, "BAZARDAIT").
dico("B", 9, "BAZARDANT").
dico("B", 9, "BAZARDEES").
dico("B", 9, "BAZARDENT").
dico("B", 9, "BAZARDERA").
dico("B", 9, "BAZARDIEZ").
dico("B", 9, "BAZARDONS").
dico("B", 9, "BEARNAISE").
dico("B", 9, "BEASSIONS").
dico("B", 9, "BEATEMENT").
dico("B", 9, "BEATIFIAI").
dico("B", 9, "BEATIFIAS").
dico("B", 9, "BEATIFIAT").
dico("B", 9, "BEATIFIEE").
dico("B", 9, "BEATIFIER").
dico("B", 9, "BEATIFIES").
dico("B", 9, "BEATIFIEZ").
dico("B", 9, "BEATITUDE").
dico("B", 9, "BEAUCERON").
dico("B", 9, "BEAUFORTS").
dico("B", 9, "BECASSEAU").
dico("B", 9, "BECASSINE").
dico("B", 9, "BECFIGUES").
dico("B", 9, "BECHAIENT").
dico("B", 9, "BECHAMELS").
dico("B", 9, "BECHASSES").
dico("B", 9, "BECHERAIS").
dico("B", 9, "BECHERAIT").
dico("B", 9, "BECHERENT").
dico("B", 9, "BECHERIEZ").
dico("B", 9, "BECHERONS").
dico("B", 9, "BECHERONT").
dico("B", 9, "BECHEUSES").
dico("B", 9, "BECHEVETA").
dico("B", 9, "BECHEVETE").
dico("B", 9, "BECHIQUES").
dico("B", 9, "BECOTAMES").
dico("B", 9, "BECOTASSE").
dico("B", 9, "BECOTATES").
dico("B", 9, "BECOTERAI").
dico("B", 9, "BECOTERAS").
dico("B", 9, "BECOTEREZ").
dico("B", 9, "BECOTIONS").
dico("B", 9, "BECQUEREL").
dico("B", 9, "BECQUETAI").
dico("B", 9, "BECQUETAS").
dico("B", 9, "BECQUETAT").
dico("B", 9, "BECQUETEE").
dico("B", 9, "BECQUETER").
dico("B", 9, "BECQUETES").
dico("B", 9, "BECQUETEZ").
dico("B", 9, "BECQUETTE").
dico("B", 9, "BECTAIENT").
dico("B", 9, "BECTANCES").
dico("B", 9, "BECTASSES").
dico("B", 9, "BECTERAIS").
dico("B", 9, "BECTERAIT").
dico("B", 9, "BECTERENT").
dico("B", 9, "BECTERIEZ").
dico("B", 9, "BECTERONS").
dico("B", 9, "BECTERONT").
dico("B", 9, "BEDEISTES").
dico("B", 9, "BEDEPHILE").
dico("B", 9, "BEDONNAIS").
dico("B", 9, "BEDONNAIT").
dico("B", 9, "BEDONNANT").
dico("B", 9, "BEDONNENT").
dico("B", 9, "BEDONNERA").
dico("B", 9, "BEDONNIEZ").
dico("B", 9, "BEDONNONS").
dico("B", 9, "BEDOUINES").
dico("B", 9, "BEEFSTEAK").
dico("B", 9, "BEERAIENT").
dico("B", 9, "BEGAIERAI").
dico("B", 9, "BEGAIERAS").
dico("B", 9, "BEGAIEREZ").
dico("B", 9, "BEGAYAMES").
dico("B", 9, "BEGAYANTE").
dico("B", 9, "BEGAYANTS").
dico("B", 9, "BEGAYASSE").
dico("B", 9, "BEGAYATES").
dico("B", 9, "BEGAYERAI").
dico("B", 9, "BEGAYERAS").
dico("B", 9, "BEGAYEREZ").
dico("B", 9, "BEGAYEURS").
dico("B", 9, "BEGAYEUSE").
dico("B", 9, "BEGAYIONS").
dico("B", 9, "BEGUETAIS").
dico("B", 9, "BEGUETAIT").
dico("B", 9, "BEGUETANT").
dico("B", 9, "BEGUETENT").
dico("B", 9, "BEGUETERA").
dico("B", 9, "BEGUETIEZ").
dico("B", 9, "BEGUETONS").
dico("B", 9, "BEGUEULES").
dico("B", 9, "BEGUINAGE").
dico("B", 9, "BEHAISMES").
dico("B", 9, "BEIGEASSE").
dico("B", 9, "BEIGEATRE").
dico("B", 9, "BEIGNERIE").
dico("B", 9, "BELANDRES").
dico("B", 9, "BELASSENT").
dico("B", 9, "BELASSIEZ").
dico("B", 9, "BELEMENTS").
dico("B", 9, "BELEMNITE").
dico("B", 9, "BELERIONS").
dico("B", 9, "BELIZIENS").
dico("B", 9, "BELLADONE").
dico("B", 9, "BELLATRES").
dico("B", 9, "BELLEMENT").
dico("B", 9, "BELLIGENE").
dico("B", 9, "BELLOTTES").
dico("B", 9, "BELLUAIRE").
dico("B", 9, "BELOTEURS").
dico("B", 9, "BELOTEUSE").
dico("B", 9, "BELVEDERE").
dico("B", 9, "BEMOLISAI").
dico("B", 9, "BEMOLISAS").
dico("B", 9, "BEMOLISAT").
dico("B", 9, "BEMOLISEE").
dico("B", 9, "BEMOLISER").
dico("B", 9, "BEMOLISES").
dico("B", 9, "BEMOLISEZ").
dico("B", 9, "BENEFICES").
dico("B", 9, "BENEFICIA").
dico("B", 9, "BENEFICIE").
dico("B", 9, "BENEFIQUE").
dico("B", 9, "BENEVOLAT").
dico("B", 9, "BENEVOLES").
dico("B", 9, "BENGALIES").
dico("B", 9, "BENICHONS").
dico("B", 9, "BENIGNITE").
dico("B", 9, "BENINCASE").
dico("B", 9, "BENINOISE").
dico("B", 9, "BENIRIONS").
dico("B", 9, "BENISSAIS").
dico("B", 9, "BENISSAIT").
dico("B", 9, "BENISSANT").
dico("B", 9, "BENISSENT").
dico("B", 9, "BENISSEUR").
dico("B", 9, "BENISSIEZ").
dico("B", 9, "BENISSONS").
dico("B", 9, "BENITIERS").
dico("B", 9, "BENJAMINE").
dico("B", 9, "BENJAMINS").
dico("B", 9, "BENTHIQUE").
dico("B", 9, "BENTONITE").
dico("B", 9, "BENZIDINE").
dico("B", 9, "BENZOATES").
dico("B", 9, "BENZOIQUE").
dico("B", 9, "BENZOLEES").
dico("B", 9, "BENZOYLES").
dico("B", 9, "BEOTHUQUE").
dico("B", 9, "BEOTIENNE").
dico("B", 9, "BEOTISMES").
dico("B", 9, "BEQUETAIS").
dico("B", 9, "BEQUETAIT").
dico("B", 9, "BEQUETANT").
dico("B", 9, "BEQUETEES").
dico("B", 9, "BEQUETENT").
dico("B", 9, "BEQUETERA").
dico("B", 9, "BEQUETIEZ").
dico("B", 9, "BEQUETONS").
dico("B", 9, "BEQUETTES").
dico("B", 9, "BEQUILLAI").
dico("B", 9, "BEQUILLAS").
dico("B", 9, "BEQUILLAT").
dico("B", 9, "BEQUILLEE").
dico("B", 9, "BEQUILLER").
dico("B", 9, "BEQUILLES").
dico("B", 9, "BEQUILLEZ").
dico("B", 9, "BEQUILLON").
dico("B", 9, "BERCAIENT").
dico("B", 9, "BERCANTES").
dico("B", 9, "BERCASSES").
dico("B", 9, "BERCEMENT").
dico("B", 9, "BERCERAIS").
dico("B", 9, "BERCERAIT").
dico("B", 9, "BERCERENT").
dico("B", 9, "BERCERIEZ").
dico("B", 9, "BERCERONS").
dico("B", 9, "BERCERONT").
dico("B", 9, "BERCEUSES").
dico("B", 9, "BEREZINAS").
dico("B", 9, "BERGAMOTE").
dico("B", 9, "BERGERACS").
dico("B", 9, "BERGERIES").
dico("B", 9, "BERIBERIS").
dico("B", 9, "BERIMBAUS").
dico("B", 9, "BERKELIUM").
dico("B", 9, "BERLINGOT").
dico("B", 9, "BERLINOIS").
dico("B", 9, "BERMUDIEN").
dico("B", 9, "BERNACHES").
dico("B", 9, "BERNACLES").
dico("B", 9, "BERNAIENT").
dico("B", 9, "BERNARDIN").
dico("B", 9, "BERNASSES").
dico("B", 9, "BERNEMENT").
dico("B", 9, "BERNERAIS").
dico("B", 9, "BERNERAIT").
dico("B", 9, "BERNERENT").
dico("B", 9, "BERNERIEZ").
dico("B", 9, "BERNERONS").
dico("B", 9, "BERNERONT").
dico("B", 9, "BERNEUSES").
dico("B", 9, "BERNICLES").
dico("B", 9, "BERNIQUES").
dico("B", 9, "BERNOISES").
dico("B", 9, "BERRICHON").
dico("B", 9, "BERRUYERE").
dico("B", 9, "BERRUYERS").
dico("B", 9, "BERYLLIUM").
dico("B", 9, "BERZINGUE").
dico("B", 9, "BESACIERE").
dico("B", 9, "BESACIERS").
dico("B", 9, "BESAIGUES").
dico("B", 9, "BESOGNAIS").
dico("B", 9, "BESOGNAIT").
dico("B", 9, "BESOGNANT").
dico("B", 9, "BESOGNEES").
dico("B", 9, "BESOGNENT").
dico("B", 9, "BESOGNERA").
dico("B", 9, "BESOGNEUX").
dico("B", 9, "BESOGNIEZ").
dico("B", 9, "BESOGNONS").
dico("B", 9, "BESSEMERS").
dico("B", 9, "BESSONNES").
dico("B", 9, "BESTIAIRE").
dico("B", 9, "BESTIALES").
dico("B", 9, "BESTIOLES").
dico("B", 9, "BETATRONS").
dico("B", 9, "BETIFIAIS").
dico("B", 9, "BETIFIAIT").
dico("B", 9, "BETIFIANT").
dico("B", 9, "BETIFIEES").
dico("B", 9, "BETIFIENT").
dico("B", 9, "BETIFIERA").
dico("B", 9, "BETIFIIEZ").
dico("B", 9, "BETIFIONS").
dico("B", 9, "BETISAMES").
dico("B", 9, "BETISASSE").
dico("B", 9, "BETISATES").
dico("B", 9, "BETISERAI").
dico("B", 9, "BETISERAS").
dico("B", 9, "BETISEREZ").
dico("B", 9, "BETISIERS").
dico("B", 9, "BETISIONS").
dico("B", 9, "BETONNAGE").
dico("B", 9, "BETONNAIS").
dico("B", 9, "BETONNAIT").
dico("B", 9, "BETONNANT").
dico("B", 9, "BETONNEES").
dico("B", 9, "BETONNENT").
dico("B", 9, "BETONNERA").
dico("B", 9, "BETONNIEZ").
dico("B", 9, "BETONNONS").
dico("B", 9, "BETTERAVE").
dico("B", 9, "BETULACEE").
dico("B", 9, "BETULINEE").
dico("B", 9, "BEUGLAMES").
dico("B", 9, "BEUGLANTE").
dico("B", 9, "BEUGLANTS").
dico("B", 9, "BEUGLASSE").
dico("B", 9, "BEUGLATES").
dico("B", 9, "BEUGLERAI").
dico("B", 9, "BEUGLERAS").
dico("B", 9, "BEUGLEREZ").
dico("B", 9, "BEUGLIONS").
dico("B", 9, "BEURETTES").
dico("B", 9, "BEURRAGES").
dico("B", 9, "BEURRAMES").
dico("B", 9, "BEURRASSE").
dico("B", 9, "BEURRATES").
dico("B", 9, "BEURRERAI").
dico("B", 9, "BEURRERAS").
dico("B", 9, "BEURREREZ").
dico("B", 9, "BEURRERIE").
dico("B", 9, "BEURRIERE").
dico("B", 9, "BEURRIERS").
dico("B", 9, "BEURRIONS").
dico("B", 9, "BEUVERIES").
dico("B", 9, "BEVATRONS").
dico("B", 9, "BEYLICALE").
dico("B", 9, "BEYLICATS").
dico("B", 9, "BEYLICAUX").
dico("B", 9, "BEYLISMES").
dico("B", 9, "BIACUMINE").
dico("B", 9, "BIAFRAISE").
dico("B", 9, "BIAISAMES").
dico("B", 9, "BIAISASSE").
dico("B", 9, "BIAISATES").
dico("B", 9, "BIAISERAI").
dico("B", 9, "BIAISERAS").
dico("B", 9, "BIAISEREZ").
dico("B", 9, "BIAISIONS").
dico("B", 9, "BIARROTES").
dico("B", 9, "BIATHLETE").
dico("B", 9, "BIATHLONS").
dico("B", 9, "BIAURALES").
dico("B", 9, "BIBACIERS").
dico("B", 9, "BIBASIQUE").
dico("B", 9, "BIBASSIER").
dico("B", 9, "BIBELOTAI").
dico("B", 9, "BIBELOTAS").
dico("B", 9, "BIBELOTAT").
dico("B", 9, "BIBELOTER").
dico("B", 9, "BIBELOTES").
dico("B", 9, "BIBELOTEZ").
dico("B", 9, "BIBENDUMS").
dico("B", 9, "BIBERONNA").
dico("B", 9, "BIBERONNE").
dico("B", 9, "BIBLIOBUS").
dico("B", 9, "BIBLIQUES").
dico("B", 9, "BIBLISTES").
dico("B", 9, "BICAMERAL").
dico("B", 9, "BICARREES").
dico("B", 9, "BICEPHALE").
dico("B", 9, "BICHAIENT").
dico("B", 9, "BICHASSES").
dico("B", 9, "BICHERAIS").
dico("B", 9, "BICHERAIT").
dico("B", 9, "BICHERENT").
dico("B", 9, "BICHERIEZ").
dico("B", 9, "BICHERONS").
dico("B", 9, "BICHERONT").
dico("B", 9, "BICHETTES").
dico("B", 9, "BICHLAMAR").
dico("B", 9, "BICHONNAI").
dico("B", 9, "BICHONNAS").
dico("B", 9, "BICHONNAT").
dico("B", 9, "BICHONNEE").
dico("B", 9, "BICHONNER").
dico("B", 9, "BICHONNES").
dico("B", 9, "BICHONNEZ").
dico("B", 9, "BICHROMIE").
dico("B", 9, "BICIPITAL").
dico("B", 9, "BICKFORDS").
dico("B", 9, "BICOLORES").
dico("B", 9, "BICONCAVE").
dico("B", 9, "BICONVEXE").
dico("B", 9, "BICOUCHES").
dico("B", 9, "BICOURANT").
dico("B", 9, "BICUSPIDE").
dico("B", 9, "BIDONNAGE").
dico("B", 9, "BIDONNAIS").
dico("B", 9, "BIDONNAIT").
dico("B", 9, "BIDONNANT").
dico("B", 9, "BIDONNEES").
dico("B", 9, "BIDONNENT").
dico("B", 9, "BIDONNERA").
dico("B", 9, "BIDONNIEZ").
dico("B", 9, "BIDONNONS").
dico("B", 9, "BIDOUILLA").
dico("B", 9, "BIDOUILLE").
dico("B", 9, "BIELLETTE").
dico("B", 9, "BIENERGIE").
dico("B", 9, "BIENFAITS").
dico("B", 9, "BIENNALES").
dico("B", 9, "BIENNOISE").
dico("B", 9, "BIENSEANT").
dico("B", 9, "BIENVENIR").
dico("B", 9, "BIENVENUE").
dico("B", 9, "BIENVENUS").
dico("B", 9, "BIFFAIENT").
dico("B", 9, "BIFFASSES").
dico("B", 9, "BIFFEMENT").
dico("B", 9, "BIFFERAIS").
dico("B", 9, "BIFFERAIT").
dico("B", 9, "BIFFERENT").
dico("B", 9, "BIFFERIEZ").
dico("B", 9, "BIFFERONS").
dico("B", 9, "BIFFERONT").
dico("B", 9, "BIFFETONS").
dico("B", 9, "BIFILAIRE").
dico("B", 9, "BIFLECHES").
dico("B", 9, "BIFOCALES").
dico("B", 9, "BIFOLIEES").
dico("B", 9, "BIFOLIOLE").
dico("B", 9, "BIFURQUAI").
dico("B", 9, "BIFURQUAS").
dico("B", 9, "BIFURQUAT").
dico("B", 9, "BIFURQUER").
dico("B", 9, "BIFURQUES").
dico("B", 9, "BIFURQUEZ").
dico("B", 9, "BIGARADES").
dico("B", 9, "BIGARRAIS").
dico("B", 9, "BIGARRAIT").
dico("B", 9, "BIGARRANT").
dico("B", 9, "BIGARREAU").
dico("B", 9, "BIGARREES").
dico("B", 9, "BIGARRENT").
dico("B", 9, "BIGARRERA").
dico("B", 9, "BIGARRIEZ").
dico("B", 9, "BIGARRONS").
dico("B", 9, "BIGARRURE").
dico("B", 9, "BIGEMINEE").
dico("B", 9, "BIGEMINES").
dico("B", 9, "BIGLAIENT").
dico("B", 9, "BIGLASSES").
dico("B", 9, "BIGLERAIS").
dico("B", 9, "BIGLERAIT").
dico("B", 9, "BIGLERENT").
dico("B", 9, "BIGLERIEZ").
dico("B", 9, "BIGLERONS").
dico("B", 9, "BIGLERONT").
dico("B", 9, "BIGLEUSES").
dico("B", 9, "BIGNOLLES").
dico("B", 9, "BIGNONIAS").
dico("B", 9, "BIGOPHONA").
dico("B", 9, "BIGOPHONE").
dico("B", 9, "BIGORNAGE").
dico("B", 9, "BIGORNAIS").
dico("B", 9, "BIGORNAIT").
dico("B", 9, "BIGORNANT").
dico("B", 9, "BIGORNEAU").
dico("B", 9, "BIGORNEES").
dico("B", 9, "BIGORNENT").
dico("B", 9, "BIGORNERA").
dico("B", 9, "BIGORNIEZ").
dico("B", 9, "BIGORNONS").
dico("B", 9, "BIGOTERIE").
dico("B", 9, "BIGOTISME").
dico("B", 9, "BIGOUDENE").
dico("B", 9, "BIGOUDENS").
dico("B", 9, "BIGOURDAN").
dico("B", 9, "BIGREMENT").
dico("B", 9, "BIGRILLES").
dico("B", 9, "BIGUANIDE").
dico("B", 9, "BIHOREAUX").
dico("B", 9, "BIJECTIFS").
dico("B", 9, "BIJECTION").
dico("B", 9, "BIJECTIVE").
dico("B", 9, "BIJOUTIER").
dico("B", 9, "BIJUMEAUX").
dico("B", 9, "BILABIALE").
dico("B", 9, "BILABIAUX").
dico("B", 9, "BILABIEES").
dico("B", 9, "BILASSENT").
dico("B", 9, "BILASSIEZ").
dico("B", 9, "BILATERAL").
dico("B", 9, "BILBOQUET").
dico("B", 9, "BILERIONS").
dico("B", 9, "BILHARZIA").
dico("B", 9, "BILHARZIE").
dico("B", 9, "BILIAIRES").
dico("B", 9, "BILIEUSES").
dico("B", 9, "BILINGUES").
dico("B", 9, "BILLAIENT").
dico("B", 9, "BILLASSES").
dico("B", 9, "BILLERAIS").
dico("B", 9, "BILLERAIT").
dico("B", 9, "BILLERENT").
dico("B", 9, "BILLERIEZ").
dico("B", 9, "BILLERONS").
dico("B", 9, "BILLERONT").
dico("B", 9, "BILLETEES").
dico("B", 9, "BILLETTES").
dico("B", 9, "BILLONNAI").
dico("B", 9, "BILLONNAS").
dico("B", 9, "BILLONNAT").
dico("B", 9, "BILLONNEE").
dico("B", 9, "BILLONNER").
dico("B", 9, "BILLONNES").
dico("B", 9, "BILLONNEZ").
dico("B", 9, "BILOCALES").
dico("B", 9, "BILOQUAIS").
dico("B", 9, "BILOQUAIT").
dico("B", 9, "BILOQUANT").
dico("B", 9, "BILOQUEES").
dico("B", 9, "BILOQUENT").
dico("B", 9, "BILOQUERA").
dico("B", 9, "BILOQUIEZ").
dico("B", 9, "BILOQUONS").
dico("B", 9, "BIMBELOTS").
dico("B", 9, "BIMENSUEL").
dico("B", 9, "BIMESTRES").
dico("B", 9, "BIMODALES").
dico("B", 9, "BIMOTEURS").
dico("B", 9, "BINASSENT").
dico("B", 9, "BINASSIEZ").
dico("B", 9, "BINAURALE").
dico("B", 9, "BINAURAUX").
dico("B", 9, "BINCHOISE").
dico("B", 9, "BINERIONS").
dico("B", 9, "BINOCLARD").
dico("B", 9, "BINOMIALE").
dico("B", 9, "BINOMIAUX").
dico("B", 9, "BINOMINAL").
dico("B", 9, "BIOAMINES").
dico("B", 9, "BIOCENOSE").
dico("B", 9, "BIOCHIMIE").
dico("B", 9, "BIOCLIMAT").
dico("B", 9, "BIODESIGN").
dico("B", 9, "BIOGENESE").
dico("B", 9, "BIOGENIES").
dico("B", 9, "BIOGRAPHE").
dico("B", 9, "BIOLOGIES").
dico("B", 9, "BIOLOGISA").
dico("B", 9, "BIOLOGISE").
dico("B", 9, "BIOMASSES").
dico("B", 9, "BIOMETRIE").
dico("B", 9, "BIONGULEE").
dico("B", 9, "BIONGULES").
dico("B", 9, "BIONIQUES").
dico("B", 9, "BIOPSIQUE").
dico("B", 9, "BIORYTHME").
dico("B", 9, "BIOSPHERE").
dico("B", 9, "BIOSTASIE").
dico("B", 9, "BIOTIQUES").
dico("B", 9, "BIPARTIES").
dico("B", 9, "BIPARTITE").
dico("B", 9, "BIPASSAIS").
dico("B", 9, "BIPASSAIT").
dico("B", 9, "BIPASSANT").
dico("B", 9, "BIPASSEES").
dico("B", 9, "BIPASSENT").
dico("B", 9, "BIPASSERA").
dico("B", 9, "BIPASSIEZ").
dico("B", 9, "BIPASSONS").
dico("B", 9, "BIPENNEES").
dico("B", 9, "BIPERIONS").
dico("B", 9, "BIPHASEES").
dico("B", 9, "BIPHENYLE").
dico("B", 9, "BIPOLAIRE").
dico("B", 9, "BIPOUTRES").
dico("B", 9, "BIQUETTES").
dico("B", 9, "BIRAPPORT").
dico("B", 9, "BISAIEULE").
dico("B", 9, "BISAIEULS").
dico("B", 9, "BISAIGUES").
dico("B", 9, "BISANNUEL").
dico("B", 9, "BISASSENT").
dico("B", 9, "BISASSIEZ").
dico("B", 9, "BISBILLES").
dico("B", 9, "BISCAIENS").
dico("B", 9, "BISCAYENS").
dico("B", 9, "BISCORNUE").
dico("B", 9, "BISCORNUS").
dico("B", 9, "BISCOTEAU").
dico("B", 9, "BISCOTINS").
dico("B", 9, "BISCOTTES").
dico("B", 9, "BISCUITAI").
dico("B", 9, "BISCUITAS").
dico("B", 9, "BISCUITAT").
dico("B", 9, "BISCUITEE").
dico("B", 9, "BISCUITER").
dico("B", 9, "BISCUITES").
dico("B", 9, "BISCUITEZ").
dico("B", 9, "BISEAUTAI").
dico("B", 9, "BISEAUTAS").
dico("B", 9, "BISEAUTAT").
dico("B", 9, "BISEAUTEE").
dico("B", 9, "BISEAUTER").
dico("B", 9, "BISEAUTES").
dico("B", 9, "BISEAUTEZ").
dico("B", 9, "BISERIONS").
dico("B", 9, "BISEXUEES").
dico("B", 9, "BISEXUELS").
dico("B", 9, "BISMUTHEE").
dico("B", 9, "BISMUTHES").
dico("B", 9, "BISONTINE").
dico("B", 9, "BISONTINS").
dico("B", 9, "BISQUAMES").
dico("B", 9, "BISQUASSE").
dico("B", 9, "BISQUATES").
dico("B", 9, "BISQUERAI").
dico("B", 9, "BISQUERAS").
dico("B", 9, "BISQUEREZ").
dico("B", 9, "BISQUINES").
dico("B", 9, "BISQUIONS").
dico("B", 9, "BISSAIENT").
dico("B", 9, "BISSALIEN").
dico("B", 9, "BISSASSES").
dico("B", 9, "BISSERAIS").
dico("B", 9, "BISSERAIT").
dico("B", 9, "BISSERENT").
dico("B", 9, "BISSERIEZ").
dico("B", 9, "BISSERONS").
dico("B", 9, "BISSERONT").
dico("B", 9, "BISSEUSES").
dico("B", 9, "BISSEXTES").
dico("B", 9, "BISSEXUEE").
dico("B", 9, "BISSEXUEL").
dico("B", 9, "BISSEXUES").
dico("B", 9, "BISTABLES").
dico("B", 9, "BISTORTES").
dico("B", 9, "BISTOURIS").
dico("B", 9, "BISTOURNA").
dico("B", 9, "BISTOURNE").
dico("B", 9, "BISTRAMES").
dico("B", 9, "BISTRASSE").
dico("B", 9, "BISTRATES").
dico("B", 9, "BISTRERAI").
dico("B", 9, "BISTRERAS").
dico("B", 9, "BISTREREZ").
dico("B", 9, "BISTRIONS").
dico("B", 9, "BISTROTES").
dico("B", 9, "BISULFATE").
dico("B", 9, "BISULFITE").
dico("B", 9, "BISULFURE").
dico("B", 9, "BITANGENT").
dico("B", 9, "BITASSENT").
dico("B", 9, "BITASSIEZ").
dico("B", 9, "BITENSION").
dico("B", 9, "BITERIONS").
dico("B", 9, "BITERROIS").
dico("B", 9, "BITONALES").
dico("B", 9, "BITONIAUX").
dico("B", 9, "BITTAIENT").
dico("B", 9, "BITTASSES").
dico("B", 9, "BITTERAIS").
dico("B", 9, "BITTERAIT").
dico("B", 9, "BITTERENT").
dico("B", 9, "BITTERIEZ").
dico("B", 9, "BITTERONS").
dico("B", 9, "BITTERONT").
dico("B", 9, "BITTURAIS").
dico("B", 9, "BITTURAIT").
dico("B", 9, "BITTURANT").
dico("B", 9, "BITTUREES").
dico("B", 9, "BITTURENT").
dico("B", 9, "BITTURERA").
dico("B", 9, "BITTURIEZ").
dico("B", 9, "BITTURONS").
dico("B", 9, "BITUMAGES").
dico("B", 9, "BITUMAMES").
dico("B", 9, "BITUMASSE").
dico("B", 9, "BITUMATES").
dico("B", 9, "BITUMERAI").
dico("B", 9, "BITUMERAS").
dico("B", 9, "BITUMEREZ").
dico("B", 9, "BITUMEUSE").
dico("B", 9, "BITUMINAI").
dico("B", 9, "BITUMINAS").
dico("B", 9, "BITUMINAT").
dico("B", 9, "BITUMINEE").
dico("B", 9, "BITUMINER").
dico("B", 9, "BITUMINES").
dico("B", 9, "BITUMINEZ").
dico("B", 9, "BITUMIONS").
dico("B", 9, "BITURAMES").
dico("B", 9, "BITURASSE").
dico("B", 9, "BITURATES").
dico("B", 9, "BITURBINE").
dico("B", 9, "BITURERAI").
dico("B", 9, "BITURERAS").
dico("B", 9, "BITUREREZ").
dico("B", 9, "BITURIONS").
dico("B", 9, "BIVALENCE").
dico("B", 9, "BIVALENTE").
dico("B", 9, "BIVALENTS").
dico("B", 9, "BIVOLTAGE").
dico("B", 9, "BIVOUAQUA").
dico("B", 9, "BIVOUAQUE").
dico("B", 9, "BIZERTINE").
dico("B", 9, "BIZERTINS").
dico("B", 9, "BIZUTAGES").
dico("B", 9, "BIZUTAMES").
dico("B", 9, "BIZUTASSE").
dico("B", 9, "BIZUTATES").
dico("B", 9, "BIZUTERAI").
dico("B", 9, "BIZUTERAS").
dico("B", 9, "BIZUTEREZ").
dico("B", 9, "BIZUTIONS").
dico("B", 9, "BLABLABLA").
dico("B", 9, "BLABLATAI").
dico("B", 9, "BLABLATAS").
dico("B", 9, "BLABLATAT").
dico("B", 9, "BLABLATER").
dico("B", 9, "BLABLATES").
dico("B", 9, "BLABLATEZ").
dico("B", 9, "BLAFARDES").
dico("B", 9, "BLAGUAMES").
dico("B", 9, "BLAGUASSE").
dico("B", 9, "BLAGUATES").
dico("B", 9, "BLAGUERAI").
dico("B", 9, "BLAGUERAS").
dico("B", 9, "BLAGUEREZ").
dico("B", 9, "BLAGUEURS").
dico("B", 9, "BLAGUEUSE").
dico("B", 9, "BLAGUIONS").
dico("B", 9, "BLAIRAMES").
dico("B", 9, "BLAIRASSE").
dico("B", 9, "BLAIRATES").
dico("B", 9, "BLAIREAUX").
dico("B", 9, "BLAIRERAI").
dico("B", 9, "BLAIRERAS").
dico("B", 9, "BLAIREREZ").
dico("B", 9, "BLAIRIONS").
dico("B", 9, "BLAISOISE").
dico("B", 9, "BLAMABLES").
dico("B", 9, "BLAMAIENT").
dico("B", 9, "BLAMASSES").
dico("B", 9, "BLAMERAIS").
dico("B", 9, "BLAMERAIT").
dico("B", 9, "BLAMERENT").
dico("B", 9, "BLAMERIEZ").
dico("B", 9, "BLAMERONS").
dico("B", 9, "BLAMERONT").
dico("B", 9, "BLANCHETS").
dico("B", 9, "BLANCHEUR").
dico("B", 9, "BLANCHIES").
dico("B", 9, "BLANCHIRA").
dico("B", 9, "BLANCHONS").
dico("B", 9, "BLANDICES").
dico("B", 9, "BLASAIENT").
dico("B", 9, "BLASASSES").
dico("B", 9, "BLASEMENT").
dico("B", 9, "BLASERAIS").
dico("B", 9, "BLASERAIT").
dico("B", 9, "BLASERENT").
dico("B", 9, "BLASERIEZ").
dico("B", 9, "BLASERONS").
dico("B", 9, "BLASERONT").
dico("B", 9, "BLASONNAI").
dico("B", 9, "BLASONNAS").
dico("B", 9, "BLASONNAT").
dico("B", 9, "BLASONNEE").
dico("B", 9, "BLASONNER").
dico("B", 9, "BLASONNES").
dico("B", 9, "BLASONNEZ").
dico("B", 9, "BLASPHEMA").
dico("B", 9, "BLASPHEME").
dico("B", 9, "BLASTULAS").
dico("B", 9, "BLATERAIS").
dico("B", 9, "BLATERAIT").
dico("B", 9, "BLATERANT").
dico("B", 9, "BLATERENT").
dico("B", 9, "BLATERERA").
dico("B", 9, "BLATERIEZ").
dico("B", 9, "BLATERONS").
dico("B", 9, "BLEMIRAIS").
dico("B", 9, "BLEMIRAIT").
dico("B", 9, "BLEMIRENT").
dico("B", 9, "BLEMIRIEZ").
dico("B", 9, "BLEMIRONS").
dico("B", 9, "BLEMIRONT").
dico("B", 9, "BLEMISSES").
dico("B", 9, "BLEMISSEZ").
dico("B", 9, "BLESAIENT").
dico("B", 9, "BLESASSES").
dico("B", 9, "BLESEMENT").
dico("B", 9, "BLESERAIS").
dico("B", 9, "BLESERAIT").
dico("B", 9, "BLESERENT").
dico("B", 9, "BLESERIEZ").
dico("B", 9, "BLESERONS").
dico("B", 9, "BLESERONT").
dico("B", 9, "BLESOISES").
dico("B", 9, "BLESSAMES").
dico("B", 9, "BLESSANTE").
dico("B", 9, "BLESSANTS").
dico("B", 9, "BLESSASSE").
dico("B", 9, "BLESSATES").
dico("B", 9, "BLESSERAI").
dico("B", 9, "BLESSERAS").
dico("B", 9, "BLESSEREZ").
dico("B", 9, "BLESSIONS").
dico("B", 9, "BLESSURES").
dico("B", 9, "BLETSAMES").
dico("B", 9, "BLETSASSE").
dico("B", 9, "BLETSATES").
dico("B", 9, "BLETSERAI").
dico("B", 9, "BLETSERAS").
dico("B", 9, "BLETSEREZ").
dico("B", 9, "BLETSIONS").
dico("B", 9, "BLETTIMES").
dico("B", 9, "BLETTIRAI").
dico("B", 9, "BLETTIRAS").
dico("B", 9, "BLETTIREZ").
dico("B", 9, "BLETTISSE").
dico("B", 9, "BLETTITES").
dico("B", 9, "BLEUATRES").
dico("B", 9, "BLEUETIER").
dico("B", 9, "BLEUIRAIS").
dico("B", 9, "BLEUIRAIT").
dico("B", 9, "BLEUIRENT").
dico("B", 9, "BLEUIRIEZ").
dico("B", 9, "BLEUIRONS").
dico("B", 9, "BLEUIRONT").
dico("B", 9, "BLEUISSES").
dico("B", 9, "BLEUISSEZ").
dico("B", 9, "BLEUTAMES").
dico("B", 9, "BLEUTASSE").
dico("B", 9, "BLEUTATES").
dico("B", 9, "BLEUTERAI").
dico("B", 9, "BLEUTERAS").
dico("B", 9, "BLEUTEREZ").
dico("B", 9, "BLEUTIONS").
dico("B", 9, "BLINDAGES").
dico("B", 9, "BLINDAMES").
dico("B", 9, "BLINDASSE").
dico("B", 9, "BLINDATES").
dico("B", 9, "BLINDERAI").
dico("B", 9, "BLINDERAS").
dico("B", 9, "BLINDEREZ").
dico("B", 9, "BLINDIONS").
dico("B", 9, "BLINQUAIS").
dico("B", 9, "BLINQUAIT").
dico("B", 9, "BLINQUANT").
dico("B", 9, "BLINQUEES").
dico("B", 9, "BLINQUENT").
dico("B", 9, "BLINQUERA").
dico("B", 9, "BLINQUIEZ").
dico("B", 9, "BLINQUONS").
dico("B", 9, "BLIZZARDS").
dico("B", 9, "BLOCAILLE").
dico("B", 9, "BLOCKHAUS").
dico("B", 9, "BLONDASSE").
dico("B", 9, "BLONDEURS").
dico("B", 9, "BLONDIMES").
dico("B", 9, "BLONDINES").
dico("B", 9, "BLONDINET").
dico("B", 9, "BLONDIRAI").
dico("B", 9, "BLONDIRAS").
dico("B", 9, "BLONDIREZ").
dico("B", 9, "BLONDISSE").
dico("B", 9, "BLONDITES").
dico("B", 9, "BLONDOIES").
dico("B", 9, "BLONDOYAI").
dico("B", 9, "BLONDOYAS").
dico("B", 9, "BLONDOYAT").
dico("B", 9, "BLONDOYER").
dico("B", 9, "BLONDOYEZ").
dico("B", 9, "BLOQUAMES").
dico("B", 9, "BLOQUANTE").
dico("B", 9, "BLOQUANTS").
dico("B", 9, "BLOQUASSE").
dico("B", 9, "BLOQUATES").
dico("B", 9, "BLOQUERAI").
dico("B", 9, "BLOQUERAS").
dico("B", 9, "BLOQUEREZ").
dico("B", 9, "BLOQUEURS").
dico("B", 9, "BLOQUEUSE").
dico("B", 9, "BLOQUIONS").
dico("B", 9, "BLOTTIMES").
dico("B", 9, "BLOTTIRAI").
dico("B", 9, "BLOTTIRAS").
dico("B", 9, "BLOTTIREZ").
dico("B", 9, "BLOTTISSE").
dico("B", 9, "BLOTTITES").
dico("B", 9, "BLOUSAMES").
dico("B", 9, "BLOUSANTE").
dico("B", 9, "BLOUSANTS").
dico("B", 9, "BLOUSASSE").
dico("B", 9, "BLOUSATES").
dico("B", 9, "BLOUSERAI").
dico("B", 9, "BLOUSERAS").
dico("B", 9, "BLOUSEREZ").
dico("B", 9, "BLOUSIONS").
dico("B", 9, "BLUFFAMES").
dico("B", 9, "BLUFFASSE").
dico("B", 9, "BLUFFATES").
dico("B", 9, "BLUFFERAI").
dico("B", 9, "BLUFFERAS").
dico("B", 9, "BLUFFEREZ").
dico("B", 9, "BLUFFEURS").
dico("B", 9, "BLUFFEUSE").
dico("B", 9, "BLUFFIONS").
dico("B", 9, "BLUTAIENT").
dico("B", 9, "BLUTASSES").
dico("B", 9, "BLUTERAIS").
dico("B", 9, "BLUTERAIT").
dico("B", 9, "BLUTERENT").
dico("B", 9, "BLUTERIES").
dico("B", 9, "BLUTERIEZ").
dico("B", 9, "BLUTERONS").
dico("B", 9, "BLUTERONT").
dico("B", 9, "BOBINAGES").
dico("B", 9, "BOBINAMES").
dico("B", 9, "BOBINARDS").
dico("B", 9, "BOBINASSE").
dico("B", 9, "BOBINATES").
dico("B", 9, "BOBINEAUX").
dico("B", 9, "BOBINERAI").
dico("B", 9, "BOBINERAS").
dico("B", 9, "BOBINEREZ").
dico("B", 9, "BOBINETTE").
dico("B", 9, "BOBINEURS").
dico("B", 9, "BOBINEUSE").
dico("B", 9, "BOBINIERE").
dico("B", 9, "BOBINIERS").
dico("B", 9, "BOBINIONS").
dico("B", 9, "BOBINOIRS").
dico("B", 9, "BOBSLEIGH").
dico("B", 9, "BOCAGERES").
dico("B", 9, "BOCARDAGE").
dico("B", 9, "BOCARDAIS").
dico("B", 9, "BOCARDAIT").
dico("B", 9, "BOCARDANT").
dico("B", 9, "BOCARDEES").
dico("B", 9, "BOCARDENT").
dico("B", 9, "BOCARDERA").
dico("B", 9, "BOCARDIEZ").
dico("B", 9, "BOCARDONS").
dico("B", 9, "BOCHIMANS").
dico("B", 9, "BODYBOARD").
dico("B", 9, "BOGOMILES").
dico("B", 9, "BOHEMIENS").
dico("B", 9, "BOIRAIENT").
dico("B", 9, "BOISAIENT").
dico("B", 9, "BOISASSES").
dico("B", 9, "BOISEMENT").
dico("B", 9, "BOISERAIS").
dico("B", 9, "BOISERAIT").
dico("B", 9, "BOISERENT").
dico("B", 9, "BOISERIES").
dico("B", 9, "BOISERIEZ").
dico("B", 9, "BOISERONS").
dico("B", 9, "BOISERONT").
dico("B", 9, "BOISSEAUX").
dico("B", 9, "BOISSELEE").
dico("B", 9, "BOITAIENT").
dico("B", 9, "BOITASSES").
dico("B", 9, "BOITEMENT").
dico("B", 9, "BOITERAIS").
dico("B", 9, "BOITERAIT").
dico("B", 9, "BOITERENT").
dico("B", 9, "BOITERIES").
dico("B", 9, "BOITERIEZ").
dico("B", 9, "BOITERONS").
dico("B", 9, "BOITERONT").
dico("B", 9, "BOITEUSES").
dico("B", 9, "BOITILLAI").
dico("B", 9, "BOITILLAS").
dico("B", 9, "BOITILLAT").
dico("B", 9, "BOITILLER").
dico("B", 9, "BOITILLES").
dico("B", 9, "BOITILLEZ").
dico("B", 9, "BOLCHEVIK").
dico("B", 9, "BOLETALES").
dico("B", 9, "BOLIVARES").
dico("B", 9, "BOLIVIANO").
dico("B", 9, "BOLIVIENS").
dico("B", 9, "BOLOGNAIS").
dico("B", 9, "BOLOMETRE").
dico("B", 9, "BOLONAISE").
dico("B", 9, "BOMBAIENT").
dico("B", 9, "BOMBANCES").
dico("B", 9, "BOMBARDAI").
dico("B", 9, "BOMBARDAS").
dico("B", 9, "BOMBARDAT").
dico("B", 9, "BOMBARDEE").
dico("B", 9, "BOMBARDER").
dico("B", 9, "BOMBARDES").
dico("B", 9, "BOMBARDEZ").
dico("B", 9, "BOMBARDON").
dico("B", 9, "BOMBASINS").
dico("B", 9, "BOMBASSES").
dico("B", 9, "BOMBEMENT").
dico("B", 9, "BOMBERAIS").
dico("B", 9, "BOMBERAIT").
dico("B", 9, "BOMBERENT").
dico("B", 9, "BOMBERIEZ").
dico("B", 9, "BOMBERONS").
dico("B", 9, "BOMBERONT").
dico("B", 9, "BOMBEUSES").
dico("B", 9, "BOMBONNES").
dico("B", 9, "BONBONNES").
dico("B", 9, "BONDAIENT").
dico("B", 9, "BONDASSES").
dico("B", 9, "BONDELLES").
dico("B", 9, "BONDERAIS").
dico("B", 9, "BONDERAIT").
dico("B", 9, "BONDERENT").
dico("B", 9, "BONDERIEZ").
dico("B", 9, "BONDERISA").
dico("B", 9, "BONDERISE").
dico("B", 9, "BONDERONS").
dico("B", 9, "BONDERONT").
dico("B", 9, "BONDIRAIS").
dico("B", 9, "BONDIRAIT").
dico("B", 9, "BONDIRENT").
dico("B", 9, "BONDIRIEZ").
dico("B", 9, "BONDIRONS").
dico("B", 9, "BONDIRONT").
dico("B", 9, "BONDISSES").
dico("B", 9, "BONDISSEZ").
dico("B", 9, "BONDONNAI").
dico("B", 9, "BONDONNAS").
dico("B", 9, "BONDONNAT").
dico("B", 9, "BONDONNEE").
dico("B", 9, "BONDONNER").
dico("B", 9, "BONDONNES").
dico("B", 9, "BONDONNEZ").
dico("B", 9, "BONHOMIES").
dico("B", 9, "BONHOMMES").
dico("B", 9, "BONICHONS").
dico("B", 9, "BONIFACES").
dico("B", 9, "BONIFIAIS").
dico("B", 9, "BONIFIAIT").
dico("B", 9, "BONIFIANT").
dico("B", 9, "BONIFIEES").
dico("B", 9, "BONIFIENT").
dico("B", 9, "BONIFIERA").
dico("B", 9, "BONIFIIEZ").
dico("B", 9, "BONIFIONS").
dico("B", 9, "BONIMENTA").
dico("B", 9, "BONIMENTE").
dico("B", 9, "BONIMENTS").
dico("B", 9, "BONISSEUR").
dico("B", 9, "BONNARDES").
dico("B", 9, "BONNEMENT").
dico("B", 9, "BONNETEAU").
dico("B", 9, "BONNETEUR").
dico("B", 9, "BONNETIER").
dico("B", 9, "BONNETTES").
dico("B", 9, "BONNICHES").
dico("B", 9, "BONNOISES").
dico("B", 9, "BONZERIES").
dico("B", 9, "BONZESSES").
dico("B", 9, "BOOKMAKER").
dico("B", 9, "BOOLEENNE").
dico("B", 9, "BOOLIENNE").
dico("B", 9, "BOOMERANG").
dico("B", 9, "BOOSTAMES").
dico("B", 9, "BOOSTASSE").
dico("B", 9, "BOOSTATES").
dico("B", 9, "BOOSTERAI").
dico("B", 9, "BOOSTERAS").
dico("B", 9, "BOOSTEREZ").
dico("B", 9, "BOOSTIONS").
dico("B", 9, "BOQUETEAU").
dico("B", 9, "BORACITES").
dico("B", 9, "BORCHTCHS").
dico("B", 9, "BORDAIENT").
dico("B", 9, "BORDASSES").
dico("B", 9, "BORDELAIS").
dico("B", 9, "BORDELLES").
dico("B", 9, "BORDERAIS").
dico("B", 9, "BORDERAIT").
dico("B", 9, "BORDEREAU").
dico("B", 9, "BORDERENT").
dico("B", 9, "BORDERIES").
dico("B", 9, "BORDERIEZ").
dico("B", 9, "BORDERONS").
dico("B", 9, "BORDERONT").
dico("B", 9, "BORDIERES").
dico("B", 9, "BORDIGUES").
dico("B", 9, "BORIQUEES").
dico("B", 9, "BORNAIENT").
dico("B", 9, "BORNASSES").
dico("B", 9, "BORNERAIS").
dico("B", 9, "BORNERAIT").
dico("B", 9, "BORNERENT").
dico("B", 9, "BORNERIEZ").
dico("B", 9, "BORNERONS").
dico("B", 9, "BORNERONT").
dico("B", 9, "BORNOIENT").
dico("B", 9, "BORNOIERA").
dico("B", 9, "BORNOYAIS").
dico("B", 9, "BORNOYAIT").
dico("B", 9, "BORNOYANT").
dico("B", 9, "BORNOYEES").
dico("B", 9, "BORNOYIEZ").
dico("B", 9, "BORNOYONS").
dico("B", 9, "BORRELIAS").
dico("B", 9, "BORSALINO").
dico("B", 9, "BOSCOTTES").
dico("B", 9, "BOSNIAQUE").
dico("B", 9, "BOSNIENNE").
dico("B", 9, "BOSSAIENT").
dico("B", 9, "BOSSASSES").
dico("B", 9, "BOSSELAGE").
dico("B", 9, "BOSSELAIS").
dico("B", 9, "BOSSELAIT").
dico("B", 9, "BOSSELANT").
dico("B", 9, "BOSSELEES").
dico("B", 9, "BOSSELIEZ").
dico("B", 9, "BOSSELLES").
dico("B", 9, "BOSSELONS").
dico("B", 9, "BOSSELURE").
dico("B", 9, "BOSSERAIS").
dico("B", 9, "BOSSERAIT").
dico("B", 9, "BOSSERENT").
dico("B", 9, "BOSSERIEZ").
dico("B", 9, "BOSSERONS").
dico("B", 9, "BOSSERONT").
dico("B", 9, "BOSSETTES").
dico("B", 9, "BOSSEUSES").
dico("B", 9, "BOSSUAMES").
dico("B", 9, "BOSSUASSE").
dico("B", 9, "BOSSUATES").
dico("B", 9, "BOSSUERAI").
dico("B", 9, "BOSSUERAS").
dico("B", 9, "BOSSUEREZ").
dico("B", 9, "BOSSUIONS").
dico("B", 9, "BOSTONIEN").
dico("B", 9, "BOSTONNAI").
dico("B", 9, "BOSTONNAS").
dico("B", 9, "BOSTONNAT").
dico("B", 9, "BOSTONNER").
dico("B", 9, "BOSTONNES").
dico("B", 9, "BOSTONNEZ").
dico("B", 9, "BOSTRYCHE").
dico("B", 9, "BOTANIQUE").
dico("B", 9, "BOTANISAI").
dico("B", 9, "BOTANISAS").
dico("B", 9, "BOTANISAT").
dico("B", 9, "BOTANISER").
dico("B", 9, "BOTANISES").
dico("B", 9, "BOTANISEZ").
dico("B", 9, "BOTANISTE").
dico("B", 9, "BOTTAIENT").
dico("B", 9, "BOTTASSES").
dico("B", 9, "BOTTELAGE").
dico("B", 9, "BOTTELAIS").
dico("B", 9, "BOTTELAIT").
dico("B", 9, "BOTTELANT").
dico("B", 9, "BOTTELEES").
dico("B", 9, "BOTTELEUR").
dico("B", 9, "BOTTELIEZ").
dico("B", 9, "BOTTELLES").
dico("B", 9, "BOTTELONS").
dico("B", 9, "BOTTERAIS").
dico("B", 9, "BOTTERAIT").
dico("B", 9, "BOTTERENT").
dico("B", 9, "BOTTERIES").
dico("B", 9, "BOTTERIEZ").
dico("B", 9, "BOTTERONS").
dico("B", 9, "BOTTERONT").
dico("B", 9, "BOTTIERES").
dico("B", 9, "BOTTILLON").
dico("B", 9, "BOTULIQUE").
dico("B", 9, "BOTULISME").
dico("B", 9, "BOUBOULAI").
dico("B", 9, "BOUBOULAS").
dico("B", 9, "BOUBOULAT").
dico("B", 9, "BOUBOULER").
dico("B", 9, "BOUBOULES").
dico("B", 9, "BOUBOULEZ").
dico("B", 9, "BOUCANAGE").
dico("B", 9, "BOUCANAIS").
dico("B", 9, "BOUCANAIT").
dico("B", 9, "BOUCANANT").
dico("B", 9, "BOUCANEES").
dico("B", 9, "BOUCANENT").
dico("B", 9, "BOUCANERA").
dico("B", 9, "BOUCANIER").
dico("B", 9, "BOUCANIEZ").
dico("B", 9, "BOUCANONS").
dico("B", 9, "BOUCHAGES").
dico("B", 9, "BOUCHAINS").
dico("B", 9, "BOUCHAMES").
dico("B", 9, "BOUCHARDA").
dico("B", 9, "BOUCHARDE").
dico("B", 9, "BOUCHASSE").
dico("B", 9, "BOUCHATES").
dico("B", 9, "BOUCHERAI").
dico("B", 9, "BOUCHERAS").
dico("B", 9, "BOUCHERES").
dico("B", 9, "BOUCHEREZ").
dico("B", 9, "BOUCHERIE").
dico("B", 9, "BOUCHETON").
dico("B", 9, "BOUCHEURS").
dico("B", 9, "BOUCHEUSE").
dico("B", 9, "BOUCHIONS").
dico("B", 9, "BOUCHOIES").
dico("B", 9, "BOUCHONNA").
dico("B", 9, "BOUCHONNE").
dico("B", 9, "BOUCHOYAI").
dico("B", 9, "BOUCHOYAS").
dico("B", 9, "BOUCHOYAT").
dico("B", 9, "BOUCHOYEE").
dico("B", 9, "BOUCHOYER").
dico("B", 9, "BOUCHOYES").
dico("B", 9, "BOUCHOYEZ").
dico("B", 9, "BOUCLAGES").
dico("B", 9, "BOUCLAMES").
dico("B", 9, "BOUCLASSE").
dico("B", 9, "BOUCLATES").
dico("B", 9, "BOUCLERAI").
dico("B", 9, "BOUCLERAS").
dico("B", 9, "BOUCLEREZ").
dico("B", 9, "BOUCLETTE").
dico("B", 9, "BOUCLIERS").
dico("B", 9, "BOUCLIONS").
dico("B", 9, "BOUDAIENT").
dico("B", 9, "BOUDASSES").
dico("B", 9, "BOUDERAIS").
dico("B", 9, "BOUDERAIT").
dico("B", 9, "BOUDERENT").
dico("B", 9, "BOUDERIES").
dico("B", 9, "BOUDERIEZ").
dico("B", 9, "BOUDERONS").
dico("B", 9, "BOUDERONT").
dico("B", 9, "BOUDEUSES").
dico("B", 9, "BOUDINAGE").
dico("B", 9, "BOUDINAIS").
dico("B", 9, "BOUDINAIT").
dico("B", 9, "BOUDINANT").
dico("B", 9, "BOUDINEES").
dico("B", 9, "BOUDINENT").
dico("B", 9, "BOUDINERA").
dico("B", 9, "BOUDINIEZ").
dico("B", 9, "BOUDINONS").
dico("B", 9, "BOUELAMES").
dico("B", 9, "BOUELASSE").
dico("B", 9, "BOUELATES").
dico("B", 9, "BOUELERAI").
dico("B", 9, "BOUELERAS").
dico("B", 9, "BOUELEREZ").
dico("B", 9, "BOUELIONS").
dico("B", 9, "BOUFFAMES").
dico("B", 9, "BOUFFANTE").
dico("B", 9, "BOUFFANTS").
dico("B", 9, "BOUFFARDE").
dico("B", 9, "BOUFFASSE").
dico("B", 9, "BOUFFATES").
dico("B", 9, "BOUFFERAI").
dico("B", 9, "BOUFFERAS").
dico("B", 9, "BOUFFEREZ").
dico("B", 9, "BOUFFETTE").
dico("B", 9, "BOUFFEURS").
dico("B", 9, "BOUFFEUSE").
dico("B", 9, "BOUFFIMES").
dico("B", 9, "BOUFFIONS").
dico("B", 9, "BOUFFIRAI").
dico("B", 9, "BOUFFIRAS").
dico("B", 9, "BOUFFIREZ").
dico("B", 9, "BOUFFISSE").
dico("B", 9, "BOUFFITES").
dico("B", 9, "BOUFFONNA").
dico("B", 9, "BOUFFONNE").
dico("B", 9, "BOUGEAMES").
dico("B", 9, "BOUGEASSE").
dico("B", 9, "BOUGEATES").
dico("B", 9, "BOUGEOIRS").
dico("B", 9, "BOUGEOTTE").
dico("B", 9, "BOUGERAIS").
dico("B", 9, "BOUGERAIT").
dico("B", 9, "BOUGERENT").
dico("B", 9, "BOUGERIEZ").
dico("B", 9, "BOUGERONS").
dico("B", 9, "BOUGERONT").
dico("B", 9, "BOUGILLON").
dico("B", 9, "BOUGONNAI").
dico("B", 9, "BOUGONNAS").
dico("B", 9, "BOUGONNAT").
dico("B", 9, "BOUGONNEE").
dico("B", 9, "BOUGONNER").
dico("B", 9, "BOUGONNES").
dico("B", 9, "BOUGONNEZ").
dico("B", 9, "BOUGRESSE").
dico("B", 9, "BOUGRINES").
dico("B", 9, "BOUIBOUIS").
dico("B", 9, "BOUILLAIS").
dico("B", 9, "BOUILLAIT").
dico("B", 9, "BOUILLANT").
dico("B", 9, "BOUILLARD").
dico("B", 9, "BOUILLENT").
dico("B", 9, "BOUILLEUR").
dico("B", 9, "BOUILLIES").
dico("B", 9, "BOUILLIEZ").
dico("B", 9, "BOUILLIRA").
dico("B", 9, "BOUILLONS").
dico("B", 9, "BOUINAMES").
dico("B", 9, "BOUINASSE").
dico("B", 9, "BOUINATES").
dico("B", 9, "BOUINERAI").
dico("B", 9, "BOUINERAS").
dico("B", 9, "BOUINEREZ").
dico("B", 9, "BOUINIONS").
dico("B", 9, "BOUJARONS").
dico("B", 9, "BOULAIENT").
dico("B", 9, "BOULANGEA").
dico("B", 9, "BOULANGEE").
dico("B", 9, "BOULANGER").
dico("B", 9, "BOULANGES").
dico("B", 9, "BOULANGEZ").
dico("B", 9, "BOULASSES").
dico("B", 9, "BOULBENES").
dico("B", 9, "BOULERAIS").
dico("B", 9, "BOULERAIT").
dico("B", 9, "BOULERENT").
dico("B", 9, "BOULERIEZ").
dico("B", 9, "BOULERONS").
dico("B", 9, "BOULERONT").
dico("B", 9, "BOULETAGE").
dico("B", 9, "BOULETEES").
dico("B", 9, "BOULETTES").
dico("B", 9, "BOULEUSES").
dico("B", 9, "BOULEVARD").
dico("B", 9, "BOULGOURS").
dico("B", 9, "BOULIMIES").
dico("B", 9, "BOULINIER").
dico("B", 9, "BOULISMES").
dico("B", 9, "BOULISTES").
dico("B", 9, "BOULOCHAI").
dico("B", 9, "BOULOCHAS").
dico("B", 9, "BOULOCHAT").
dico("B", 9, "BOULOCHER").
dico("B", 9, "BOULOCHES").
dico("B", 9, "BOULOCHEZ").
dico("B", 9, "BOULOMANE").
dico("B", 9, "BOULONNAI").
dico("B", 9, "BOULONNAS").
dico("B", 9, "BOULONNAT").
dico("B", 9, "BOULONNEE").
dico("B", 9, "BOULONNER").
dico("B", 9, "BOULONNES").
dico("B", 9, "BOULONNEZ").
dico("B", 9, "BOULOTTAI").
dico("B", 9, "BOULOTTAS").
dico("B", 9, "BOULOTTAT").
dico("B", 9, "BOULOTTEE").
dico("B", 9, "BOULOTTER").
dico("B", 9, "BOULOTTES").
dico("B", 9, "BOULOTTEZ").
dico("B", 9, "BOUMERAIT").
dico("B", 9, "BOUMERANG").
dico("B", 9, "BOUQUETEE").
dico("B", 9, "BOUQUETES").
dico("B", 9, "BOUQUETIN").
dico("B", 9, "BOUQUINAI").
dico("B", 9, "BOUQUINAS").
dico("B", 9, "BOUQUINAT").
dico("B", 9, "BOUQUINEE").
dico("B", 9, "BOUQUINER").
dico("B", 9, "BOUQUINES").
dico("B", 9, "BOUQUINEZ").
dico("B", 9, "BOURACANS").
dico("B", 9, "BOURBEUSE").
dico("B", 9, "BOURBIERS").
dico("B", 9, "BOURDAINE").
dico("B", 9, "BOURDALOU").
dico("B", 9, "BOURDIGUE").
dico("B", 9, "BOURDONNA").
dico("B", 9, "BOURDONNE").
dico("B", 9, "BOURGADES").
dico("B", 9, "BOURGEOIS").
dico("B", 9, "BOURGEONS").
dico("B", 9, "BOURGERON").
dico("B", 9, "BOURGOGNE").
dico("B", 9, "BOURGUEIL").
dico("B", 9, "BOURONNAI").
dico("B", 9, "BOURONNAS").
dico("B", 9, "BOURONNAT").
dico("B", 9, "BOURONNER").
dico("B", 9, "BOURONNES").
dico("B", 9, "BOURONNEZ").
dico("B", 9, "BOURRACHE").
dico("B", 9, "BOURRADES").
dico("B", 9, "BOURRAGES").
dico("B", 9, "BOURRAMES").
dico("B", 9, "BOURRASSA").
dico("B", 9, "BOURRASSE").
dico("B", 9, "BOURRATES").
dico("B", 9, "BOURRATIF").
dico("B", 9, "BOURREAUX").
dico("B", 9, "BOURRELAI").
dico("B", 9, "BOURRELAS").
dico("B", 9, "BOURRELAT").
dico("B", 9, "BOURRELEE").
dico("B", 9, "BOURRELER").
dico("B", 9, "BOURRELES").
dico("B", 9, "BOURRELET").
dico("B", 9, "BOURRELEZ").
dico("B", 9, "BOURRELLE").
dico("B", 9, "BOURRERAI").
dico("B", 9, "BOURRERAS").
dico("B", 9, "BOURREREZ").
dico("B", 9, "BOURRETTE").
dico("B", 9, "BOURREURS").
dico("B", 9, "BOURREUSE").
dico("B", 9, "BOURRICHE").
dico("B", 9, "BOURRICOT").
dico("B", 9, "BOURRIDES").
dico("B", 9, "BOURRIERS").
dico("B", 9, "BOURRINES").
dico("B", 9, "BOURRIONS").
dico("B", 9, "BOURRIQUE").
dico("B", 9, "BOURROIRS").
dico("B", 9, "BOURSETTE").
dico("B", 9, "BOURSIERE").
dico("B", 9, "BOURSIERS").
dico("B", 9, "BOUSAIENT").
dico("B", 9, "BOUSASSES").
dico("B", 9, "BOUSCUEIL").
dico("B", 9, "BOUSCULAI").
dico("B", 9, "BOUSCULAS").
dico("B", 9, "BOUSCULAT").
dico("B", 9, "BOUSCULEE").
dico("B", 9, "BOUSCULER").
dico("B", 9, "BOUSCULES").
dico("B", 9, "BOUSCULEZ").
dico("B", 9, "BOUSERAIS").
dico("B", 9, "BOUSERAIT").
dico("B", 9, "BOUSERENT").
dico("B", 9, "BOUSERIEZ").
dico("B", 9, "BOUSERONS").
dico("B", 9, "BOUSERONT").
dico("B", 9, "BOUSEUSES").
dico("B", 9, "BOUSILLAI").
dico("B", 9, "BOUSILLAS").
dico("B", 9, "BOUSILLAT").
dico("B", 9, "BOUSILLEE").
dico("B", 9, "BOUSILLER").
dico("B", 9, "BOUSILLES").
dico("B", 9, "BOUSILLEZ").
dico("B", 9, "BOUSINGOT").
dico("B", 9, "BOUSSOLES").
dico("B", 9, "BOUTAIENT").
dico("B", 9, "BOUTARGUE").
dico("B", 9, "BOUTASSES").
dico("B", 9, "BOUTEFEUX").
dico("B", 9, "BOUTEILLE").
dico("B", 9, "BOUTERAIS").
dico("B", 9, "BOUTERAIT").
dico("B", 9, "BOUTERENT").
dico("B", 9, "BOUTERIEZ").
dico("B", 9, "BOUTERONS").
dico("B", 9, "BOUTERONT").
dico("B", 9, "BOUTEROUE").
dico("B", 9, "BOUTIQUES").
dico("B", 9, "BOUTISSES").
dico("B", 9, "BOUTONNAI").
dico("B", 9, "BOUTONNAS").
dico("B", 9, "BOUTONNAT").
dico("B", 9, "BOUTONNEE").
dico("B", 9, "BOUTONNER").
dico("B", 9, "BOUTONNES").
dico("B", 9, "BOUTONNEZ").
dico("B", 9, "BOUTURAGE").
dico("B", 9, "BOUTURAIS").
dico("B", 9, "BOUTURAIT").
dico("B", 9, "BOUTURANT").
dico("B", 9, "BOUTUREES").
dico("B", 9, "BOUTURENT").
dico("B", 9, "BOUTURERA").
dico("B", 9, "BOUTURIEZ").
dico("B", 9, "BOUTURONS").
dico("B", 9, "BOUVERIES").
dico("B", 9, "BOUVETAGE").
dico("B", 9, "BOUVETAIS").
dico("B", 9, "BOUVETAIT").
dico("B", 9, "BOUVETANT").
dico("B", 9, "BOUVETEES").
dico("B", 9, "BOUVETIEZ").
dico("B", 9, "BOUVETONS").
dico("B", 9, "BOUVETTES").
dico("B", 9, "BOUVIERES").
dico("B", 9, "BOUVILLON").
dico("B", 9, "BOUVREUIL").
dico("B", 9, "BOUZOUKIS").
dico("B", 9, "BOVARYSME").
dico("B", 9, "BOXASSENT").
dico("B", 9, "BOXASSIEZ").
dico("B", 9, "BOXERIONS").
dico("B", 9, "BOYAUDIER").
dico("B", 9, "BOYAUTAIS").
dico("B", 9, "BOYAUTAIT").
dico("B", 9, "BOYAUTANT").
dico("B", 9, "BOYAUTEES").
dico("B", 9, "BOYAUTENT").
dico("B", 9, "BOYAUTERA").
dico("B", 9, "BOYAUTIEZ").
dico("B", 9, "BOYAUTONS").
dico("B", 9, "BOYCOTTAI").
dico("B", 9, "BOYCOTTAS").
dico("B", 9, "BOYCOTTAT").
dico("B", 9, "BOYCOTTEE").
dico("B", 9, "BOYCOTTER").
dico("B", 9, "BOYCOTTES").
dico("B", 9, "BOYCOTTEZ").
dico("B", 9, "BOYOMAISE").
dico("B", 9, "BRABANCON").
dico("B", 9, "BRACELETS").
dico("B", 9, "BRACHIALE").
dico("B", 9, "BRACHIAUX").
dico("B", 9, "BRACONNAI").
dico("B", 9, "BRACONNAS").
dico("B", 9, "BRACONNAT").
dico("B", 9, "BRACONNEE").
dico("B", 9, "BRACONNER").
dico("B", 9, "BRACONNES").
dico("B", 9, "BRACONNEZ").
dico("B", 9, "BRACTEALE").
dico("B", 9, "BRACTEAUX").
dico("B", 9, "BRACTEOLE").
dico("B", 9, "BRADAIENT").
dico("B", 9, "BRADASSES").
dico("B", 9, "BRADERAIS").
dico("B", 9, "BRADERAIT").
dico("B", 9, "BRADERENT").
dico("B", 9, "BRADERIES").
dico("B", 9, "BRADERIEZ").
dico("B", 9, "BRADERONS").
dico("B", 9, "BRADERONT").
dico("B", 9, "BRADEUSES").
dico("B", 9, "BRAGARDES").
dico("B", 9, "BRAGUETTE").
dico("B", 9, "BRAHMANES").
dico("B", 9, "BRAHMINES").
dico("B", 9, "BRAIERAIS").
dico("B", 9, "BRAIERAIT").
dico("B", 9, "BRAIERIEZ").
dico("B", 9, "BRAIERONS").
dico("B", 9, "BRAIERONT").
dico("B", 9, "BRAILLAIS").
dico("B", 9, "BRAILLAIT").
dico("B", 9, "BRAILLANT").
dico("B", 9, "BRAILLARD").
dico("B", 9, "BRAILLEES").
dico("B", 9, "BRAILLENT").
dico("B", 9, "BRAILLERA").
dico("B", 9, "BRAILLEUR").
dico("B", 9, "BRAILLIEZ").
dico("B", 9, "BRAILLONS").
dico("B", 9, "BRAIMENTS").
dico("B", 9, "BRAIRIONS").
dico("B", 9, "BRAISAGES").
dico("B", 9, "BRAISAMES").
dico("B", 9, "BRAISASSE").
dico("B", 9, "BRAISATES").
dico("B", 9, "BRAISERAI").
dico("B", 9, "BRAISERAS").
dico("B", 9, "BRAISEREZ").
dico("B", 9, "BRAISETTE").
dico("B", 9, "BRAISIERE").
dico("B", 9, "BRAISIONS").
dico("B", 9, "BRAMAIENT").
dico("B", 9, "BRAMASSES").
dico("B", 9, "BRAMEMENT").
dico("B", 9, "BRAMERAIS").
dico("B", 9, "BRAMERAIT").
dico("B", 9, "BRAMERENT").
dico("B", 9, "BRAMERIEZ").
dico("B", 9, "BRAMERONS").
dico("B", 9, "BRAMERONT").
dico("B", 9, "BRANCARDA").
dico("B", 9, "BRANCARDE").
dico("B", 9, "BRANCARDS").
dico("B", 9, "BRANCHAGE").
dico("B", 9, "BRANCHAIS").
dico("B", 9, "BRANCHAIT").
dico("B", 9, "BRANCHANT").
dico("B", 9, "BRANCHEES").
dico("B", 9, "BRANCHENT").
dico("B", 9, "BRANCHERA").
dico("B", 9, "BRANCHIAL").
dico("B", 9, "BRANCHIES").
dico("B", 9, "BRANCHIEZ").
dico("B", 9, "BRANCHONS").
dico("B", 9, "BRANCHUES").
dico("B", 9, "BRANDADES").
dico("B", 9, "BRANDEVIN").
dico("B", 9, "BRANDILLA").
dico("B", 9, "BRANDILLE").
dico("B", 9, "BRANDIMES").
dico("B", 9, "BRANDIRAI").
dico("B", 9, "BRANDIRAS").
dico("B", 9, "BRANDIREZ").
dico("B", 9, "BRANDISSE").
dico("B", 9, "BRANDITES").
dico("B", 9, "BRANLAMES").
dico("B", 9, "BRANLANTE").
dico("B", 9, "BRANLANTS").
dico("B", 9, "BRANLASSE").
dico("B", 9, "BRANLATES").
dico("B", 9, "BRANLERAI").
dico("B", 9, "BRANLERAS").
dico("B", 9, "BRANLEREZ").
dico("B", 9, "BRANLETTE").
dico("B", 9, "BRANLEURS").
dico("B", 9, "BRANLEUSE").
dico("B", 9, "BRANLIONS").
dico("B", 9, "BRAQUAGES").
dico("B", 9, "BRAQUAMES").
dico("B", 9, "BRAQUASSE").
dico("B", 9, "BRAQUATES").
dico("B", 9, "BRAQUERAI").
dico("B", 9, "BRAQUERAS").
dico("B", 9, "BRAQUEREZ").
dico("B", 9, "BRAQUEURS").
dico("B", 9, "BRAQUEUSE").
dico("B", 9, "BRAQUIONS").
dico("B", 9, "BRASAIENT").
dico("B", 9, "BRASASSES").
dico("B", 9, "BRASERAIS").
dico("B", 9, "BRASERAIT").
dico("B", 9, "BRASERENT").
dico("B", 9, "BRASERIEZ").
dico("B", 9, "BRASERONS").
dico("B", 9, "BRASERONT").
dico("B", 9, "BRASILIEN").
dico("B", 9, "BRASILLAI").
dico("B", 9, "BRASILLAS").
dico("B", 9, "BRASILLAT").
dico("B", 9, "BRASILLER").
dico("B", 9, "BRASILLES").
dico("B", 9, "BRASILLEZ").
dico("B", 9, "BRASQUAIS").
dico("B", 9, "BRASQUAIT").
dico("B", 9, "BRASQUANT").
dico("B", 9, "BRASQUEES").
dico("B", 9, "BRASQUENT").
dico("B", 9, "BRASQUERA").
dico("B", 9, "BRASQUIEZ").
dico("B", 9, "BRASQUONS").
dico("B", 9, "BRASSAGES").
dico("B", 9, "BRASSAMES").
dico("B", 9, "BRASSARDS").
dico("B", 9, "BRASSASSE").
dico("B", 9, "BRASSATES").
dico("B", 9, "BRASSERAI").
dico("B", 9, "BRASSERAS").
dico("B", 9, "BRASSEREZ").
dico("B", 9, "BRASSERIE").
dico("B", 9, "BRASSEURS").
dico("B", 9, "BRASSEUSE").
dico("B", 9, "BRASSEYAI").
dico("B", 9, "BRASSEYAS").
dico("B", 9, "BRASSEYAT").
dico("B", 9, "BRASSEYEE").
dico("B", 9, "BRASSEYER").
dico("B", 9, "BRASSEYES").
dico("B", 9, "BRASSEYEZ").
dico("B", 9, "BRASSIERE").
dico("B", 9, "BRASSIONS").
dico("B", 9, "BRAVACHES").
dico("B", 9, "BRAVAIENT").
dico("B", 9, "BRAVASSES").
dico("B", 9, "BRAVEMENT").
dico("B", 9, "BRAVERAIS").
dico("B", 9, "BRAVERAIT").
dico("B", 9, "BRAVERENT").
dico("B", 9, "BRAVERIES").
dico("B", 9, "BRAVERIEZ").
dico("B", 9, "BRAVERONS").
dico("B", 9, "BRAVERONT").
dico("B", 9, "BRAVOURES").
dico("B", 9, "BRAYAIENT").
dico("B", 9, "BRAYASSES").
dico("B", 9, "BRAYERAIS").
dico("B", 9, "BRAYERAIT").
dico("B", 9, "BRAYERENT").
dico("B", 9, "BRAYERIEZ").
dico("B", 9, "BRAYERONS").
dico("B", 9, "BRAYERONT").
dico("B", 9, "BREAKAMES").
dico("B", 9, "BREAKASSE").
dico("B", 9, "BREAKATES").
dico("B", 9, "BREAKERAI").
dico("B", 9, "BREAKERAS").
dico("B", 9, "BREAKEREZ").
dico("B", 9, "BREAKFAST").
dico("B", 9, "BREAKIONS").
dico("B", 9, "BREHAIGNE").
dico("B", 9, "BRELAIENT").
dico("B", 9, "BRELASSES").
dico("B", 9, "BRELERAIS").
dico("B", 9, "BRELERAIT").
dico("B", 9, "BRELERENT").
dico("B", 9, "BRELERIEZ").
dico("B", 9, "BRELERONS").
dico("B", 9, "BRELERONT").
dico("B", 9, "BRELOQUES").
dico("B", 9, "BRESILIEN").
dico("B", 9, "BRESILINE").
dico("B", 9, "BRESILLAI").
dico("B", 9, "BRESILLAS").
dico("B", 9, "BRESILLAT").
dico("B", 9, "BRESILLEE").
dico("B", 9, "BRESILLER").
dico("B", 9, "BRESILLES").
dico("B", 9, "BRESILLET").
dico("B", 9, "BRESILLEZ").
dico("B", 9, "BRESSANES").
dico("B", 9, "BRESTOISE").
dico("B", 9, "BRETAILLA").
dico("B", 9, "BRETAILLE").
dico("B", 9, "BRETAUDAI").
dico("B", 9, "BRETAUDAS").
dico("B", 9, "BRETAUDAT").
dico("B", 9, "BRETAUDEE").
dico("B", 9, "BRETAUDER").
dico("B", 9, "BRETAUDES").
dico("B", 9, "BRETAUDEZ").
dico("B", 9, "BRETECHES").
dico("B", 9, "BRETELLES").
dico("B", 9, "BRETESSEE").
dico("B", 9, "BRETESSES").
dico("B", 9, "BRETONNES").
dico("B", 9, "BRETTAMES").
dico("B", 9, "BRETTASSE").
dico("B", 9, "BRETTATES").
dico("B", 9, "BRETTELAI").
dico("B", 9, "BRETTELAS").
dico("B", 9, "BRETTELAT").
dico("B", 9, "BRETTELEE").
dico("B", 9, "BRETTELER").
dico("B", 9, "BRETTELES").
dico("B", 9, "BRETTELEZ").
dico("B", 9, "BRETTELLE").
dico("B", 9, "BRETTERAI").
dico("B", 9, "BRETTERAS").
dico("B", 9, "BRETTEREZ").
dico("B", 9, "BRETTEURS").
dico("B", 9, "BRETTEUSE").
dico("B", 9, "BRETTIONS").
dico("B", 9, "BREUVAGES").
dico("B", 9, "BREVETAIS").
dico("B", 9, "BREVETAIT").
dico("B", 9, "BREVETANT").
dico("B", 9, "BREVETEES").
dico("B", 9, "BREVETENT").
dico("B", 9, "BREVETERA").
dico("B", 9, "BREVETIEZ").
dico("B", 9, "BREVETONS").
dico("B", 9, "BREVETTES").
dico("B", 9, "BREVIAIRE").
dico("B", 9, "BRICELETS").
dico("B", 9, "BRICHETON").
dico("B", 9, "BRICOLAGE").
dico("B", 9, "BRICOLAIS").
dico("B", 9, "BRICOLAIT").
dico("B", 9, "BRICOLANT").
dico("B", 9, "BRICOLEES").
dico("B", 9, "BRICOLENT").
dico("B", 9, "BRICOLERA").
dico("B", 9, "BRICOLEUR").
dico("B", 9, "BRICOLIER").
dico("B", 9, "BRICOLIEZ").
dico("B", 9, "BRICOLONS").
dico("B", 9, "BRIDAIENT").
dico("B", 9, "BRIDASSES").
dico("B", 9, "BRIDERAIS").
dico("B", 9, "BRIDERAIT").
dico("B", 9, "BRIDERENT").
dico("B", 9, "BRIDERIEZ").
dico("B", 9, "BRIDERONS").
dico("B", 9, "BRIDERONT").
dico("B", 9, "BRIDGEAIS").
dico("B", 9, "BRIDGEAIT").
dico("B", 9, "BRIDGEANT").
dico("B", 9, "BRIDGEONS").
dico("B", 9, "BRIDGERAI").
dico("B", 9, "BRIDGERAS").
dico("B", 9, "BRIDGEREZ").
dico("B", 9, "BRIDGEURS").
dico("B", 9, "BRIDGEUSE").
dico("B", 9, "BRIDGIONS").
dico("B", 9, "BRIEFAMES").
dico("B", 9, "BRIEFASSE").
dico("B", 9, "BRIEFATES").
dico("B", 9, "BRIEFERAI").
dico("B", 9, "BRIEFERAS").
dico("B", 9, "BRIEFEREZ").
dico("B", 9, "BRIEFINGS").
dico("B", 9, "BRIEFIONS").
dico("B", 9, "BRIEVETES").
dico("B", 9, "BRIFFAMES").
dico("B", 9, "BRIFFASSE").
dico("B", 9, "BRIFFATES").
dico("B", 9, "BRIFFERAI").
dico("B", 9, "BRIFFERAS").
dico("B", 9, "BRIFFEREZ").
dico("B", 9, "BRIFFIONS").
dico("B", 9, "BRIGADIER").
dico("B", 9, "BRIGANDAI").
dico("B", 9, "BRIGANDAS").
dico("B", 9, "BRIGANDAT").
dico("B", 9, "BRIGANDEE").
dico("B", 9, "BRIGANDER").
dico("B", 9, "BRIGANDES").
dico("B", 9, "BRIGANDEZ").
dico("B", 9, "BRIGANTIN").
dico("B", 9, "BRIGNOLET").
dico("B", 9, "BRIGUAMES").
dico("B", 9, "BRIGUASSE").
dico("B", 9, "BRIGUATES").
dico("B", 9, "BRIGUERAI").
dico("B", 9, "BRIGUERAS").
dico("B", 9, "BRIGUEREZ").
dico("B", 9, "BRIGUIONS").
dico("B", 9, "BRILLAMES").
dico("B", 9, "BRILLANCE").
dico("B", 9, "BRILLANTA").
dico("B", 9, "BRILLANTE").
dico("B", 9, "BRILLANTS").
dico("B", 9, "BRILLASSE").
dico("B", 9, "BRILLATES").
dico("B", 9, "BRILLERAI").
dico("B", 9, "BRILLERAS").
dico("B", 9, "BRILLEREZ").
dico("B", 9, "BRILLIONS").
dico("B", 9, "BRIMAIENT").
dico("B", 9, "BRIMASSES").
dico("B", 9, "BRIMBALAI").
dico("B", 9, "BRIMBALAS").
dico("B", 9, "BRIMBALAT").
dico("B", 9, "BRIMBALEE").
dico("B", 9, "BRIMBALER").
dico("B", 9, "BRIMBALES").
dico("B", 9, "BRIMBALEZ").
dico("B", 9, "BRIMBELLE").
dico("B", 9, "BRIMERAIS").
dico("B", 9, "BRIMERAIT").
dico("B", 9, "BRIMERENT").
dico("B", 9, "BRIMERIEZ").
dico("B", 9, "BRIMERONS").
dico("B", 9, "BRIMERONT").
dico("B", 9, "BRINDILLE").
dico("B", 9, "BRINGEURE").
dico("B", 9, "BRINGUAIS").
dico("B", 9, "BRINGUAIT").
dico("B", 9, "BRINGUANT").
dico("B", 9, "BRINGUEES").
dico("B", 9, "BRINGUENT").
dico("B", 9, "BRINGUERA").
dico("B", 9, "BRINGUIEZ").
dico("B", 9, "BRINGUONS").
dico("B", 9, "BRIOCHEES").
dico("B", 9, "BRIOCHINE").
dico("B", 9, "BRIOCHINS").
dico("B", 9, "BRIQUAMES").
dico("B", 9, "BRIQUASSE").
dico("B", 9, "BRIQUATES").
dico("B", 9, "BRIQUERAI").
dico("B", 9, "BRIQUERAS").
dico("B", 9, "BRIQUEREZ").
dico("B", 9, "BRIQUETAI").
dico("B", 9, "BRIQUETAS").
dico("B", 9, "BRIQUETAT").
dico("B", 9, "BRIQUETEE").
dico("B", 9, "BRIQUETER").
dico("B", 9, "BRIQUETES").
dico("B", 9, "BRIQUETEZ").
dico("B", 9, "BRIQUETTE").
dico("B", 9, "BRIQUIONS").
dico("B", 9, "BRISAIENT").
dico("B", 9, "BRISANCES").
dico("B", 9, "BRISANTES").
dico("B", 9, "BRISASSES").
dico("B", 9, "BRISCARDS").
dico("B", 9, "BRISEMENT").
dico("B", 9, "BRISERAIS").
dico("B", 9, "BRISERAIT").
dico("B", 9, "BRISERENT").
dico("B", 9, "BRISERIEZ").
dico("B", 9, "BRISERONS").
dico("B", 9, "BRISERONT").
dico("B", 9, "BRISEUSES").
dico("B", 9, "BRISOLEES").
dico("B", 9, "BRISQUARD").
dico("B", 9, "BRISSOTIN").
dico("B", 9, "BRIVISTES").
dico("B", 9, "BROCANTAI").
dico("B", 9, "BROCANTAS").
dico("B", 9, "BROCANTAT").
dico("B", 9, "BROCANTEE").
dico("B", 9, "BROCANTER").
dico("B", 9, "BROCANTES").
dico("B", 9, "BROCANTEZ").
dico("B", 9, "BROCARDAI").
dico("B", 9, "BROCARDAS").
dico("B", 9, "BROCARDAT").
dico("B", 9, "BROCARDEE").
dico("B", 9, "BROCARDER").
dico("B", 9, "BROCARDES").
dico("B", 9, "BROCARDEZ").
dico("B", 9, "BROCHAGES").
dico("B", 9, "BROCHAMES").
dico("B", 9, "BROCHANTE").
dico("B", 9, "BROCHANTS").
dico("B", 9, "BROCHASSE").
dico("B", 9, "BROCHATES").
dico("B", 9, "BROCHERAI").
dico("B", 9, "BROCHERAS").
dico("B", 9, "BROCHEREZ").
dico("B", 9, "BROCHETON").
dico("B", 9, "BROCHETTE").
dico("B", 9, "BROCHEURS").
dico("B", 9, "BROCHEUSE").
dico("B", 9, "BROCHIONS").
dico("B", 9, "BROCHOIRS").
dico("B", 9, "BROCHURES").
dico("B", 9, "BRODAIENT").
dico("B", 9, "BRODASSES").
dico("B", 9, "BRODEQUIN").
dico("B", 9, "BRODERAIS").
dico("B", 9, "BRODERAIT").
dico("B", 9, "BRODERENT").
dico("B", 9, "BRODERIES").
dico("B", 9, "BRODERIEZ").
dico("B", 9, "BRODERONS").
dico("B", 9, "BRODERONT").
dico("B", 9, "BRODEUSES").
dico("B", 9, "BROIEMENT").
dico("B", 9, "BROIERAIS").
dico("B", 9, "BROIERAIT").
dico("B", 9, "BROIERIEZ").
dico("B", 9, "BROIERONS").
dico("B", 9, "BROIERONT").
dico("B", 9, "BROMELIAS").
dico("B", 9, "BROMIQUES").
dico("B", 9, "BROMISMES").
dico("B", 9, "BROMUREES").
dico("B", 9, "BRONCHAIS").
dico("B", 9, "BRONCHAIT").
dico("B", 9, "BRONCHANT").
dico("B", 9, "BRONCHENT").
dico("B", 9, "BRONCHERA").
dico("B", 9, "BRONCHIEZ").
dico("B", 9, "BRONCHITE").
dico("B", 9, "BRONCHONS").
dico("B", 9, "BRONZAGES").
dico("B", 9, "BRONZAMES").
dico("B", 9, "BRONZANTE").
dico("B", 9, "BRONZANTS").
dico("B", 9, "BRONZASSE").
dico("B", 9, "BRONZATES").
dico("B", 9, "BRONZERAI").
dico("B", 9, "BRONZERAS").
dico("B", 9, "BRONZEREZ").
dico("B", 9, "BRONZETTE").
dico("B", 9, "BRONZEURS").
dico("B", 9, "BRONZEUSE").
dico("B", 9, "BRONZIERE").
dico("B", 9, "BRONZIERS").
dico("B", 9, "BRONZIONS").
dico("B", 9, "BROQUARDS").
dico("B", 9, "BROQUARTS").
dico("B", 9, "BROQUELIN").
dico("B", 9, "BROQUETTE").
dico("B", 9, "BROSSAGES").
dico("B", 9, "BROSSAMES").
dico("B", 9, "BROSSASSE").
dico("B", 9, "BROSSATES").
dico("B", 9, "BROSSERAI").
dico("B", 9, "BROSSERAS").
dico("B", 9, "BROSSEREZ").
dico("B", 9, "BROSSERIE").
dico("B", 9, "BROSSIERE").
dico("B", 9, "BROSSIERS").
dico("B", 9, "BROSSIONS").
dico("B", 9, "BROUETTAI").
dico("B", 9, "BROUETTAS").
dico("B", 9, "BROUETTAT").
dico("B", 9, "BROUETTEE").
dico("B", 9, "BROUETTER").
dico("B", 9, "BROUETTES").
dico("B", 9, "BROUETTEZ").
dico("B", 9, "BROUHAHAS").
dico("B", 9, "BROUILLAI").
dico("B", 9, "BROUILLAS").
dico("B", 9, "BROUILLAT").
dico("B", 9, "BROUILLEE").
dico("B", 9, "BROUILLER").
dico("B", 9, "BROUILLES").
dico("B", 9, "BROUILLEZ").
dico("B", 9, "BROUILLON").
dico("B", 9, "BROUILLYS").
dico("B", 9, "BROUSSARD").
dico("B", 9, "BROUSSINS").
dico("B", 9, "BROUTAGES").
dico("B", 9, "BROUTAMES").
dico("B", 9, "BROUTARDS").
dico("B", 9, "BROUTARTS").
dico("B", 9, "BROUTASSE").
dico("B", 9, "BROUTATES").
dico("B", 9, "BROUTERAI").
dico("B", 9, "BROUTERAS").
dico("B", 9, "BROUTEREZ").
dico("B", 9, "BROUTILLE").
dico("B", 9, "BROUTIONS").
dico("B", 9, "BROWNIENS").
dico("B", 9, "BROWNINGS").
dico("B", 9, "BROYAIENT").
dico("B", 9, "BROYASSES").
dico("B", 9, "BROYERENT").
dico("B", 9, "BROYEUSES").
dico("B", 9, "BRUCELLAS").
dico("B", 9, "BRUCELLES").
dico("B", 9, "BRUGEOISE").
dico("B", 9, "BRUINEUSE").
dico("B", 9, "BRUIRIONS").
dico("B", 9, "BRUISSAGE").
dico("B", 9, "BRUISSAIS").
dico("B", 9, "BRUISSAIT").
dico("B", 9, "BRUISSANT").
dico("B", 9, "BRUISSENT").
dico("B", 9, "BRUISSERA").
dico("B", 9, "BRUISSIEZ").
dico("B", 9, "BRUISSONS").
dico("B", 9, "BRUITAGES").
dico("B", 9, "BRUITAMES").
dico("B", 9, "BRUITASSE").
dico("B", 9, "BRUITATES").
dico("B", 9, "BRUITERAI").
dico("B", 9, "BRUITERAS").
dico("B", 9, "BRUITEREZ").
dico("B", 9, "BRUITEURS").
dico("B", 9, "BRUITEUSE").
dico("B", 9, "BRUITIONS").
dico("B", 9, "BRULAIENT").
dico("B", 9, "BRULANTES").
dico("B", 9, "BRULASSES").
dico("B", 9, "BRULEMENT").
dico("B", 9, "BRULERAIS").
dico("B", 9, "BRULERAIT").
dico("B", 9, "BRULERENT").
dico("B", 9, "BRULERIES").
dico("B", 9, "BRULERIEZ").
dico("B", 9, "BRULERONS").
dico("B", 9, "BRULERONT").
dico("B", 9, "BRULEUSES").
dico("B", 9, "BRUMAIRES").
dico("B", 9, "BRUMASSAT").
dico("B", 9, "BRUMASSER").
dico("B", 9, "BRUMASSES").
dico("B", 9, "BRUMERAIT").
dico("B", 9, "BRUMEUSES").
dico("B", 9, "BRUNANTES").
dico("B", 9, "BRUNATRES").
dico("B", 9, "BRUNCHAIS").
dico("B", 9, "BRUNCHAIT").
dico("B", 9, "BRUNCHANT").
dico("B", 9, "BRUNCHENT").
dico("B", 9, "BRUNCHERA").
dico("B", 9, "BRUNCHIEZ").
dico("B", 9, "BRUNCHONS").
dico("B", 9, "BRUNEIENS").
dico("B", 9, "BRUNETTES").
dico("B", 9, "BRUNIRAIS").
dico("B", 9, "BRUNIRAIT").
dico("B", 9, "BRUNIRENT").
dico("B", 9, "BRUNIRIEZ").
dico("B", 9, "BRUNIRONS").
dico("B", 9, "BRUNIRONT").
dico("B", 9, "BRUNISSES").
dico("B", 9, "BRUNISSEZ").
dico("B", 9, "BRUNOISES").
dico("B", 9, "BRUSHINGS").
dico("B", 9, "BRUSQUAIS").
dico("B", 9, "BRUSQUAIT").
dico("B", 9, "BRUSQUANT").
dico("B", 9, "BRUSQUEES").
dico("B", 9, "BRUSQUENT").
dico("B", 9, "BRUSQUERA").
dico("B", 9, "BRUSQUIEZ").
dico("B", 9, "BRUSQUONS").
dico("B", 9, "BRUTALISA").
dico("B", 9, "BRUTALISE").
dico("B", 9, "BRUTALITE").
dico("B", 9, "BRUXISMES").
dico("B", 9, "BRUYANTES").
dico("B", 9, "BRYOLOGIE").
dico("B", 9, "BRYOPHYTE").
dico("B", 9, "BUANDERIE").
dico("B", 9, "BUANDIERE").
dico("B", 9, "BUANDIERS").
dico("B", 9, "BUBONIQUE").
dico("B", 9, "BUCAILLES").
dico("B", 9, "BUCEPHALE").
dico("B", 9, "BUCHAIENT").
dico("B", 9, "BUCHASSES").
dico("B", 9, "BUCHERAIS").
dico("B", 9, "BUCHERAIT").
dico("B", 9, "BUCHERENT").
dico("B", 9, "BUCHERIEZ").
dico("B", 9, "BUCHERONS").
dico("B", 9, "BUCHERONT").
dico("B", 9, "BUCHETTES").
dico("B", 9, "BUCHEUSES").
dico("B", 9, "BUCOLIQUE").
dico("B", 9, "BUDDLEIAS").
dico("B", 9, "BUDGETAIS").
dico("B", 9, "BUDGETAIT").
dico("B", 9, "BUDGETANT").
dico("B", 9, "BUDGETEES").
dico("B", 9, "BUDGETENT").
dico("B", 9, "BUDGETERA").
dico("B", 9, "BUDGETIEZ").
dico("B", 9, "BUDGETISA").
dico("B", 9, "BUDGETISE").
dico("B", 9, "BUDGETONS").
dico("B", 9, "BUFFETIER").
dico("B", 9, "BUFFLAGES").
dico("B", 9, "BUFFLAMES").
dico("B", 9, "BUFFLASSE").
dico("B", 9, "BUFFLATES").
dico("B", 9, "BUFFLERAI").
dico("B", 9, "BUFFLERAS").
dico("B", 9, "BUFFLEREZ").
dico("B", 9, "BUFFLESSE").
dico("B", 9, "BUFFLETIN").
dico("B", 9, "BUFFLIONS").
dico("B", 9, "BUFFLONNE").
dico("B", 9, "BUGLOSSES").
dico("B", 9, "BUILDINGS").
dico("B", 9, "BUISSAIES").
dico("B", 9, "BUISSIERE").
dico("B", 9, "BUISSONNA").
dico("B", 9, "BUISSONNE").
dico("B", 9, "BUKAVIENS").
dico("B", 9, "BULBAIRES").
dico("B", 9, "BULBEUSES").
dico("B", 9, "BULBILLES").
dico("B", 9, "BULGOMMES").
dico("B", 9, "BULLAIENT").
dico("B", 9, "BULLAIRES").
dico("B", 9, "BULLASSES").
dico("B", 9, "BULLDOZER").
dico("B", 9, "BULLERAIS").
dico("B", 9, "BULLERAIT").
dico("B", 9, "BULLERENT").
dico("B", 9, "BULLERIEZ").
dico("B", 9, "BULLERONS").
dico("B", 9, "BULLERONT").
dico("B", 9, "BULLETINS").
dico("B", 9, "BULLEUSES").
dico("B", 9, "BUNGALOWS").
dico("B", 9, "BUPRESTES").
dico("B", 9, "BUQUAIENT").
dico("B", 9, "BUQUASSES").
dico("B", 9, "BUQUERAIS").
dico("B", 9, "BUQUERAIT").
dico("B", 9, "BUQUERENT").
dico("B", 9, "BUQUERIEZ").
dico("B", 9, "BUQUERONS").
dico("B", 9, "BUQUERONT").
dico("B", 9, "BURALISTE").
dico("B", 9, "BURATINES").
dico("B", 9, "BURGIENNE").
dico("B", 9, "BURGONDES").
dico("B", 9, "BURGRAVES").
dico("B", 9, "BURINAGES").
dico("B", 9, "BURINAMES").
dico("B", 9, "BURINASSE").
dico("B", 9, "BURINATES").
dico("B", 9, "BURINERAI").
dico("B", 9, "BURINERAS").
dico("B", 9, "BURINEREZ").
dico("B", 9, "BURINEURS").
dico("B", 9, "BURINIONS").
dico("B", 9, "BURINISTE").
dico("B", 9, "BURKINABE").
dico("B", 9, "BURKINAIS").
dico("B", 9, "BURLESQUE").
dico("B", 9, "BURLINGUE").
dico("B", 9, "BURUNDAIS").
dico("B", 9, "BUSAIGLES").
dico("B", 9, "BUSASSENT").
dico("B", 9, "BUSASSIEZ").
dico("B", 9, "BUSERIONS").
dico("B", 9, "BUSQUAMES").
dico("B", 9, "BUSQUASSE").
dico("B", 9, "BUSQUATES").
dico("B", 9, "BUSQUERAI").
dico("B", 9, "BUSQUERAS").
dico("B", 9, "BUSQUEREZ").
dico("B", 9, "BUSQUIONS").
dico("B", 9, "BUSSEROLE").
dico("B", 9, "BUSTIERES").
dico("B", 9, "BUTADIENE").
dico("B", 9, "BUTANIERS").
dico("B", 9, "BUTASSENT").
dico("B", 9, "BUTASSIEZ").
dico("B", 9, "BUTERIONS").
dico("B", 9, "BUTINAGES").
dico("B", 9, "BUTINAMES").
dico("B", 9, "BUTINASSE").
dico("B", 9, "BUTINATES").
dico("B", 9, "BUTINERAI").
dico("B", 9, "BUTINERAS").
dico("B", 9, "BUTINEREZ").
dico("B", 9, "BUTINEURS").
dico("B", 9, "BUTINEUSE").
dico("B", 9, "BUTINIONS").
dico("B", 9, "BUTTAIENT").
dico("B", 9, "BUTTASSES").
dico("B", 9, "BUTTERAIS").
dico("B", 9, "BUTTERAIT").
dico("B", 9, "BUTTERENT").
dico("B", 9, "BUTTERIEZ").
dico("B", 9, "BUTTERONS").
dico("B", 9, "BUTTERONT").
dico("B", 9, "BUTYLENES").
dico("B", 9, "BUTYLIQUE").
dico("B", 9, "BUTYRATES").
dico("B", 9, "BUTYREUSE").
dico("B", 9, "BUTYRINES").
dico("B", 9, "BUTYRIQUE").
dico("B", 9, "BUVETIERE").
dico("B", 9, "BUVETIERS").
dico("B", 9, "BYRONIENS").
dico("B", 9, "BYSSINOSE").
dico("B", 9, "BYZANTINE").
dico("B", 9, "BYZANTINS").
