dico("C", 5, "CABAN").
dico("C", 5, "CABAS").
dico("C", 5, "CABLA").
dico("C", 5, "CABLE").
dico("C", 5, "CABOT").
dico("C", 5, "CABRA").
dico("C", 5, "CABRE").
dico("C", 5, "CABRI").
dico("C", 5, "CABUS").
dico("C", 5, "CACAO").
dico("C", 5, "CACAS").
dico("C", 5, "CACHA").
dico("C", 5, "CACHE").
dico("C", 5, "CADDY").
dico("C", 5, "CADES").
dico("C", 5, "CADET").
dico("C", 5, "CADIS").
dico("C", 5, "CADOR").
dico("C", 5, "CADRA").
dico("C", 5, "CADRE").
dico("C", 5, "CADUC").
dico("C", 5, "CAFES").
dico("C", 5, "CAFRE").
dico("C", 5, "CAFTA").
dico("C", 5, "CAFTE").
dico("C", 5, "CAGEE").
dico("C", 5, "CAGES").
dico("C", 5, "CAGET").
dico("C", 5, "CAGNA").
dico("C", 5, "CAGNE").
dico("C", 5, "CAGOT").
dico("C", 5, "CAGOU").
dico("C", 5, "CAHOT").
dico("C", 5, "CAIDS").
dico("C", 5, "CAIEU").
dico("C", 5, "CAIRN").
dico("C", 5, "CAJET").
dico("C", 5, "CAJOU").
dico("C", 5, "CAJUN").
dico("C", 5, "CAKES").
dico("C", 5, "CAKTA").
dico("C", 5, "CAKTI").
dico("C", 5, "CALAI").
dico("C", 5, "CALAO").
dico("C", 5, "CALAS").
dico("C", 5, "CALAT").
dico("C", 5, "CALEE").
dico("C", 5, "CALER").
dico("C", 5, "CALES").
dico("C", 5, "CALEZ").
dico("C", 5, "CALFS").
dico("C", 5, "CALIN").
dico("C", 5, "CALLA").
dico("C", 5, "CALLE").
dico("C", 5, "CALLS").
dico("C", 5, "CALMA").
dico("C", 5, "CALME").
dico("C", 5, "CALMI").
dico("C", 5, "CALOS").
dico("C", 5, "CALOT").
dico("C", 5, "CALTA").
dico("C", 5, "CALTE").
dico("C", 5, "CALUS").
dico("C", 5, "CALVA").
dico("C", 5, "CAMAI").
dico("C", 5, "CAMAS").
dico("C", 5, "CAMAT").
dico("C", 5, "CAMBA").
dico("C", 5, "CAMBE").
dico("C", 5, "CAMEE").
dico("C", 5, "CAMER").
dico("C", 5, "CAMES").
dico("C", 5, "CAMEZ").
dico("C", 5, "CAMPA").
dico("C", 5, "CAMPE").
dico("C", 5, "CAMPO").
dico("C", 5, "CAMPS").
dico("C", 5, "CAMUS").
dico("C", 5, "CANAI").
dico("C", 5, "CANAL").
dico("C", 5, "CANAR").
dico("C", 5, "CANAS").
dico("C", 5, "CANAT").
dico("C", 5, "CANDI").
dico("C", 5, "CANEE").
dico("C", 5, "CANER").
dico("C", 5, "CANES").
dico("C", 5, "CANEZ").
dico("C", 5, "CANGE").
dico("C", 5, "CANIF").
dico("C", 5, "CANIN").
dico("C", 5, "CANNA").
dico("C", 5, "CANNE").
dico("C", 5, "CANOE").
dico("C", 5, "CANON").
dico("C", 5, "CANOT").
dico("C", 5, "CANTS").
dico("C", 5, "CANUS").
dico("C", 5, "CANUT").
dico("C", 5, "CAOUA").
dico("C", 5, "CAPAI").
dico("C", 5, "CAPAS").
dico("C", 5, "CAPAT").
dico("C", 5, "CAPEA").
dico("C", 5, "CAPEE").
dico("C", 5, "CAPER").
dico("C", 5, "CAPES").
dico("C", 5, "CAPET").
dico("C", 5, "CAPEZ").
dico("C", 5, "CAPON").
dico("C", 5, "CAPOS").
dico("C", 5, "CAPOT").
dico("C", 5, "CAPPA").
dico("C", 5, "CAPRE").
dico("C", 5, "CAPTA").
dico("C", 5, "CAPTE").
dico("C", 5, "CAQUA").
dico("C", 5, "CAQUE").
dico("C", 5, "CARAT").
dico("C", 5, "CARDA").
dico("C", 5, "CARDE").
dico("C", 5, "CARET").
dico("C", 5, "CAREX").
dico("C", 5, "CARGO").
dico("C", 5, "CARIA").
dico("C", 5, "CARIE").
dico("C", 5, "CARIS").
dico("C", 5, "CARME").
dico("C", 5, "CARNE").
dico("C", 5, "CARPE").
dico("C", 5, "CARRA").
dico("C", 5, "CARRE").
dico("C", 5, "CARRY").
dico("C", 5, "CARTA").
dico("C", 5, "CARTE").
dico("C", 5, "CARVA").
dico("C", 5, "CARVI").
dico("C", 5, "CARYS").
dico("C", 5, "CASAI").
dico("C", 5, "CASAS").
dico("C", 5, "CASAT").
dico("C", 5, "CASCO").
dico("C", 5, "CASEE").
dico("C", 5, "CASER").
dico("C", 5, "CASES").
dico("C", 5, "CASEZ").
dico("C", 5, "CASHS").
dico("C", 5, "CASSA").
dico("C", 5, "CASSE").
dico("C", 5, "CASTE").
dico("C", 5, "CATAS").
dico("C", 5, "CATCH").
dico("C", 5, "CATHO").
dico("C", 5, "CATIE").
dico("C", 5, "CATIN").
dico("C", 5, "CATIR").
dico("C", 5, "CATIS").
dico("C", 5, "CATIT").
dico("C", 5, "CAUDE").
dico("C", 5, "CAURI").
dico("C", 5, "CAUSA").
dico("C", 5, "CAUSE").
dico("C", 5, "CAVAI").
dico("C", 5, "CAVAS").
dico("C", 5, "CAVAT").
dico("C", 5, "CAVEE").
dico("C", 5, "CAVER").
dico("C", 5, "CAVES").
dico("C", 5, "CAVET").
dico("C", 5, "CAVEZ").
dico("C", 5, "CAYEU").
dico("C", 5, "CEANS").
dico("C", 5, "CEDAI").
dico("C", 5, "CEDAS").
dico("C", 5, "CEDAT").
dico("C", 5, "CEDEE").
dico("C", 5, "CEDER").
dico("C", 5, "CEDES").
dico("C", 5, "CEDEX").
dico("C", 5, "CEDEZ").
dico("C", 5, "CEDIS").
dico("C", 5, "CEDRE").
dico("C", 5, "CEGEP").
dico("C", 5, "CEINS").
dico("C", 5, "CEINT").
dico("C", 5, "CELAI").
dico("C", 5, "CELAS").
dico("C", 5, "CELAT").
dico("C", 5, "CELEE").
dico("C", 5, "CELER").
dico("C", 5, "CELES").
dico("C", 5, "CELEZ").
dico("C", 5, "CELLA").
dico("C", 5, "CELLE").
dico("C", 5, "CELTE").
dico("C", 5, "CELUI").
dico("C", 5, "CENES").
dico("C", 5, "CENNE").
dico("C", 5, "CENSE").
dico("C", 5, "CENTS").
dico("C", 5, "CEPEE").
dico("C", 5, "CEPES").
dico("C", 5, "CERAT").
dico("C", 5, "CERCE").
dico("C", 5, "CERFS").
dico("C", 5, "CERNA").
dico("C", 5, "CERNE").
dico("C", 5, "CESAR").
dico("C", 5, "CESSA").
dico("C", 5, "CESSE").
dico("C", 5, "CESTE").
dico("C", 5, "CETTE").
dico("C", 5, "CEZIG").
dico("C", 5, "CHAHS").
dico("C", 5, "CHAIR").
dico("C", 5, "CHAIS").
dico("C", 5, "CHALE").
dico("C", 5, "CHAMP").
dico("C", 5, "CHANS").
dico("C", 5, "CHANT").
dico("C", 5, "CHAOS").
dico("C", 5, "CHAPE").
dico("C", 5, "CHARS").
dico("C", 5, "CHATS").
dico("C", 5, "CHAUD").
dico("C", 5, "CHAUT").
dico("C", 5, "CHAUX").
dico("C", 5, "CHEAP").
dico("C", 5, "CHEFS").
dico("C", 5, "CHEIK").
dico("C", 5, "CHENE").
dico("C", 5, "CHENI").
dico("C", 5, "CHENU").
dico("C", 5, "CHERA").
dico("C", 5, "CHERE").
dico("C", 5, "CHERI").
dico("C", 5, "CHERS").
dico("C", 5, "CHEVA").
dico("C", 5, "CHEVE").
dico("C", 5, "CHIAC").
dico("C", 5, "CHIAI").
dico("C", 5, "CHIAS").
dico("C", 5, "CHIAT").
dico("C", 5, "CHICS").
dico("C", 5, "CHIEE").
dico("C", 5, "CHIEN").
dico("C", 5, "CHIER").
dico("C", 5, "CHIES").
dico("C", 5, "CHIEZ").
dico("C", 5, "CHILE").
dico("C", 5, "CHILI").
dico("C", 5, "CHINA").
dico("C", 5, "CHINE").
dico("C", 5, "CHIOT").
dico("C", 5, "CHIPA").
dico("C", 5, "CHIPE").
dico("C", 5, "CHIPS").
dico("C", 5, "CHIRO").
dico("C", 5, "CHOCO").
dico("C", 5, "CHOCS").
dico("C", 5, "CHOIE").
dico("C", 5, "CHOIR").
dico("C", 5, "CHOIS").
dico("C", 5, "CHOIT").
dico("C", 5, "CHOIX").
dico("C", 5, "CHOKE").
dico("C", 5, "CHOMA").
dico("C", 5, "CHOME").
dico("C", 5, "CHOPA").
dico("C", 5, "CHOPE").
dico("C", 5, "CHOPS").
dico("C", 5, "CHOSE").
dico("C", 5, "CHOTT").
dico("C", 5, "CHOUX").
dico("C", 5, "CHOYA").
dico("C", 5, "CHOYE").
dico("C", 5, "CHTIS").
dico("C", 5, "CHUES").
dico("C", 5, "CHUMS").
dico("C", 5, "CHUTA").
dico("C", 5, "CHUTE").
dico("C", 5, "CHVAS").
dico("C", 5, "CHYLE").
dico("C", 5, "CHYME").
dico("C", 5, "CIBLA").
dico("C", 5, "CIBLE").
dico("C", 5, "CICLA").
dico("C", 5, "CICLE").
dico("C", 5, "CIDRE").
dico("C", 5, "CIELS").
dico("C", 5, "CIEUX").
dico("C", 5, "CIGUE").
dico("C", 5, "CILIE").
dico("C", 5, "CILLA").
dico("C", 5, "CILLE").
dico("C", 5, "CIMES").
dico("C", 5, "CINES").
dico("C", 5, "CIPAL").
dico("C", 5, "CIPPE").
dico("C", 5, "CIPRE").
dico("C", 5, "CIRAI").
dico("C", 5, "CIRAS").
dico("C", 5, "CIRAT").
dico("C", 5, "CIREE").
dico("C", 5, "CIRER").
dico("C", 5, "CIRES").
dico("C", 5, "CIREZ").
dico("C", 5, "CIRON").
dico("C", 5, "CIRRE").
dico("C", 5, "CIRSE").
dico("C", 5, "CISTE").
dico("C", 5, "CITAI").
dico("C", 5, "CITAS").
dico("C", 5, "CITAT").
dico("C", 5, "CITEE").
dico("C", 5, "CITER").
dico("C", 5, "CITES").
dico("C", 5, "CITEZ").
dico("C", 5, "CIVES").
dico("C", 5, "CIVET").
dico("C", 5, "CIVIL").
dico("C", 5, "CLADE").
dico("C", 5, "CLAIE").
dico("C", 5, "CLAIM").
dico("C", 5, "CLAIR").
dico("C", 5, "CLAMA").
dico("C", 5, "CLAME").
dico("C", 5, "CLAMP").
dico("C", 5, "CLAMS").
dico("C", 5, "CLANS").
dico("C", 5, "CLAPI").
dico("C", 5, "CLAPS").
dico("C", 5, "CLARK").
dico("C", 5, "CLASH").
dico("C", 5, "CLAVA").
dico("C", 5, "CLAVE").
dico("C", 5, "CLAYS").
dico("C", 5, "CLEAN").
dico("C", 5, "CLEBS").
dico("C", 5, "CLEFS").
dico("C", 5, "CLERC").
dico("C", 5, "CLICK").
dico("C", 5, "CLICS").
dico("C", 5, "CLIMS").
dico("C", 5, "CLINS").
dico("C", 5, "CLIPS").
dico("C", 5, "CLIVA").
dico("C", 5, "CLIVE").
dico("C", 5, "CLODO").
dico("C", 5, "CLONA").
dico("C", 5, "CLONE").
dico("C", 5, "CLOPA").
dico("C", 5, "CLOPE").
dico("C", 5, "CLORA").
dico("C", 5, "CLORE").
dico("C", 5, "CLOSE").
dico("C", 5, "CLOUA").
dico("C", 5, "CLOUE").
dico("C", 5, "CLOUP").
dico("C", 5, "CLOUS").
dico("C", 5, "CLOWN").
dico("C", 5, "CLUBS").
dico("C", 5, "CLUSE").
dico("C", 5, "COACH").
dico("C", 5, "COATI").
dico("C", 5, "COBEA").
dico("C", 5, "COBEE").
dico("C", 5, "COBOL").
dico("C", 5, "COBRA").
dico("C", 5, "COCAS").
dico("C", 5, "COCCI").
dico("C", 5, "COCHA").
dico("C", 5, "COCHE").
dico("C", 5, "COCON").
dico("C", 5, "COCOS").
dico("C", 5, "COCUE").
dico("C", 5, "COCUS").
dico("C", 5, "CODAI").
dico("C", 5, "CODAS").
dico("C", 5, "CODAT").
dico("C", 5, "CODEE").
dico("C", 5, "CODER").
dico("C", 5, "CODES").
dico("C", 5, "CODEX").
dico("C", 5, "CODEZ").
dico("C", 5, "CODON").
dico("C", 5, "COEFS").
dico("C", 5, "COEUR").
dico("C", 5, "COGNA").
dico("C", 5, "COGNE").
dico("C", 5, "COHUE").
dico("C", 5, "COING").
dico("C", 5, "COINS").
dico("C", 5, "COIRS").
dico("C", 5, "COITA").
dico("C", 5, "COITE").
dico("C", 5, "COITS").
dico("C", 5, "COKES").
dico("C", 5, "COLAS").
dico("C", 5, "COLEE").
dico("C", 5, "COLIN").
dico("C", 5, "COLIS").
dico("C", 5, "COLLA").
dico("C", 5, "COLLE").
dico("C", 5, "COLON").
dico("C", 5, "COLOS").
dico("C", 5, "COLTS").
dico("C", 5, "COLZA").
dico("C", 5, "COMAS").
dico("C", 5, "COMBE").
dico("C", 5, "COMBI").
dico("C", 5, "COMBO").
dico("C", 5, "COMMA").
dico("C", 5, "COMME").
dico("C", 5, "COMPO").
dico("C", 5, "COMTE").
dico("C", 5, "CONCU").
dico("C", 5, "CONDE").
dico("C", 5, "CONDO").
dico("C", 5, "CONES").
dico("C", 5, "CONGA").
dico("C", 5, "CONGE").
dico("C", 5, "CONNE").
dico("C", 5, "CONNU").
dico("C", 5, "CONTA").
dico("C", 5, "CONTE").
dico("C", 5, "COPAL").
dico("C", 5, "COPIA").
dico("C", 5, "COPIE").
dico("C", 5, "COPLA").
dico("C", 5, "COPPA").
dico("C", 5, "COPRA").
dico("C", 5, "COPTE").
dico("C", 5, "COQUE").
dico("C", 5, "CORAN").
dico("C", 5, "CORDA").
dico("C", 5, "CORDE").
dico("C", 5, "CORES").
dico("C", 5, "CORME").
dico("C", 5, "CORNA").
dico("C", 5, "CORNE").
dico("C", 5, "CORNU").
dico("C", 5, "CORON").
dico("C", 5, "CORPS").
dico("C", 5, "CORSA").
dico("C", 5, "CORSE").
dico("C", 5, "CORSO").
dico("C", 5, "COSSA").
dico("C", 5, "COSSE").
dico("C", 5, "COSSU").
dico("C", 5, "COSYS").
dico("C", 5, "COTAI").
dico("C", 5, "COTAS").
dico("C", 5, "COTAT").
dico("C", 5, "COTEE").
dico("C", 5, "COTER").
dico("C", 5, "COTES").
dico("C", 5, "COTEZ").
dico("C", 5, "COTIE").
dico("C", 5, "COTIR").
dico("C", 5, "COTIS").
dico("C", 5, "COTIT").
dico("C", 5, "COTON").
dico("C", 5, "COTRE").
dico("C", 5, "COTTA").
dico("C", 5, "COTTE").
dico("C", 5, "COUAC").
dico("C", 5, "COUDA").
dico("C", 5, "COUDE").
dico("C", 5, "COUDS").
dico("C", 5, "COUIC").
dico("C", 5, "COULA").
dico("C", 5, "COULE").
dico("C", 5, "COUPA").
dico("C", 5, "COUPE").
dico("C", 5, "COUPS").
dico("C", 5, "COURE").
dico("C", 5, "COURS").
dico("C", 5, "COURT").
dico("C", 5, "COURU").
dico("C", 5, "COUSE").
dico("C", 5, "COUSU").
dico("C", 5, "COUTA").
dico("C", 5, "COUTE").
dico("C", 5, "COUTS").
dico("C", 5, "COUVA").
dico("C", 5, "COUVE").
dico("C", 5, "COUVI").
dico("C", 5, "COXAL").
dico("C", 5, "COYAU").
dico("C", 5, "COYER").
dico("C", 5, "CRABE").
dico("C", 5, "CRACK").
dico("C", 5, "CRACS").
dico("C", 5, "CRADE").
dico("C", 5, "CRADO").
dico("C", 5, "CRAIE").
dico("C", 5, "CRAMA").
dico("C", 5, "CRAME").
dico("C", 5, "CRANA").
dico("C", 5, "CRANE").
dico("C", 5, "CRANS").
dico("C", 5, "CRAPS").
dico("C", 5, "CRASE").
dico("C", 5, "CRASH").
dico("C", 5, "CRAUS").
dico("C", 5, "CRAUX").
dico("C", 5, "CRAVE").
dico("C", 5, "CRAWL").
dico("C", 5, "CREAI").
dico("C", 5, "CREAS").
dico("C", 5, "CREAT").
dico("C", 5, "CREDO").
dico("C", 5, "CREEE").
dico("C", 5, "CREEK").
dico("C", 5, "CREER").
dico("C", 5, "CREES").
dico("C", 5, "CREEZ").
dico("C", 5, "CREMA").
dico("C", 5, "CREME").
dico("C", 5, "CRENA").
dico("C", 5, "CRENE").
dico("C", 5, "CREPA").
dico("C", 5, "CREPE").
dico("C", 5, "CREPI").
dico("C", 5, "CREPU").
dico("C", 5, "CRETA").
dico("C", 5, "CRETE").
dico("C", 5, "CRETS").
dico("C", 5, "CREUX").
dico("C", 5, "CREVA").
dico("C", 5, "CREVE").
dico("C", 5, "CRIAI").
dico("C", 5, "CRIAS").
dico("C", 5, "CRIAT").
dico("C", 5, "CRIBS").
dico("C", 5, "CRICS").
dico("C", 5, "CRIEE").
dico("C", 5, "CRIER").
dico("C", 5, "CRIES").
dico("C", 5, "CRIEZ").
dico("C", 5, "CRIME").
dico("C", 5, "CRINS").
dico("C", 5, "CRISA").
dico("C", 5, "CRISE").
dico("C", 5, "CRISS").
dico("C", 5, "CROCO").
dico("C", 5, "CROCS").
dico("C", 5, "CROIE").
dico("C", 5, "CROIS").
dico("C", 5, "CROIT").
dico("C", 5, "CROIX").
dico("C", 5, "CROSS").
dico("C", 5, "CROUP").
dico("C", 5, "CROWN").
dico("C", 5, "CRUEL").
dico("C", 5, "CRUES").
dico("C", 5, "CRUOR").
dico("C", 5, "CUBAI").
dico("C", 5, "CUBAS").
dico("C", 5, "CUBAT").
dico("C", 5, "CUBEE").
dico("C", 5, "CUBER").
dico("C", 5, "CUBES").
dico("C", 5, "CUBEZ").
dico("C", 5, "CUCUL").
dico("C", 5, "CUCUS").
dico("C", 5, "CUEVA").
dico("C", 5, "CUFAT").
dico("C", 5, "CUIRA").
dico("C", 5, "CUIRE").
dico("C", 5, "CUIRS").
dico("C", 5, "CUISE").
dico("C", 5, "CUITA").
dico("C", 5, "CUITE").
dico("C", 5, "CUITS").
dico("C", 5, "CULAI").
dico("C", 5, "CULAS").
dico("C", 5, "CULAT").
dico("C", 5, "CULEE").
dico("C", 5, "CULER").
dico("C", 5, "CULES").
dico("C", 5, "CULEX").
dico("C", 5, "CULEZ").
dico("C", 5, "CULOT").
dico("C", 5, "CULTE").
dico("C", 5, "CUMIN").
dico("C", 5, "CUMUL").
dico("C", 5, "CURAI").
dico("C", 5, "CURAS").
dico("C", 5, "CURAT").
dico("C", 5, "CUREE").
dico("C", 5, "CURER").
dico("C", 5, "CURES").
dico("C", 5, "CUREZ").
dico("C", 5, "CURIE").
dico("C", 5, "CURRY").
dico("C", 5, "CUTIS").
dico("C", 5, "CUVAI").
dico("C", 5, "CUVAS").
dico("C", 5, "CUVAT").
dico("C", 5, "CUVEE").
dico("C", 5, "CUVER").
dico("C", 5, "CUVES").
dico("C", 5, "CUVEZ").
dico("C", 5, "CYANS").
dico("C", 5, "CYCAS").
dico("C", 5, "CYCLE").
dico("C", 5, "CYCLO").
dico("C", 5, "CYGNE").
dico("C", 5, "CYMES").
dico("C", 5, "CYONS").
dico("C", 5, "CZARS").
