dico("C", 7, "CABALAI").
dico("C", 7, "CABALAS").
dico("C", 7, "CABALAT").
dico("C", 7, "CABALEE").
dico("C", 7, "CABALER").
dico("C", 7, "CABALES").
dico("C", 7, "CABALEZ").
dico("C", 7, "CABANAI").
dico("C", 7, "CABANAS").
dico("C", 7, "CABANAT").
dico("C", 7, "CABANEE").
dico("C", 7, "CABANER").
dico("C", 7, "CABANES").
dico("C", 7, "CABANEZ").
dico("C", 7, "CABANON").
dico("C", 7, "CABARET").
dico("C", 7, "CABECHE").
dico("C", 7, "CABECOU").
dico("C", 7, "CABIAIS").
dico("C", 7, "CABINES").
dico("C", 7, "CABINET").
dico("C", 7, "CABLAGE").
dico("C", 7, "CABLAIS").
dico("C", 7, "CABLAIT").
dico("C", 7, "CABLANT").
dico("C", 7, "CABLEAU").
dico("C", 7, "CABLEES").
dico("C", 7, "CABLENT").
dico("C", 7, "CABLERA").
dico("C", 7, "CABLEUR").
dico("C", 7, "CABLIER").
dico("C", 7, "CABLIEZ").
dico("C", 7, "CABLONS").
dico("C", 7, "CABLOTS").
dico("C", 7, "CABOCHE").
dico("C", 7, "CABOSSA").
dico("C", 7, "CABOSSE").
dico("C", 7, "CABOTAI").
dico("C", 7, "CABOTAS").
dico("C", 7, "CABOTAT").
dico("C", 7, "CABOTER").
dico("C", 7, "CABOTES").
dico("C", 7, "CABOTEZ").
dico("C", 7, "CABOTIN").
dico("C", 7, "CABRAGE").
dico("C", 7, "CABRAIS").
dico("C", 7, "CABRAIT").
dico("C", 7, "CABRANT").
dico("C", 7, "CABREES").
dico("C", 7, "CABRENT").
dico("C", 7, "CABRERA").
dico("C", 7, "CABRIEZ").
dico("C", 7, "CABRONS").
dico("C", 7, "CACABAI").
dico("C", 7, "CACABAS").
dico("C", 7, "CACABAT").
dico("C", 7, "CACABER").
dico("C", 7, "CACABES").
dico("C", 7, "CACABEZ").
dico("C", 7, "CACAOTE").
dico("C", 7, "CACAOUI").
dico("C", 7, "CACARDA").
dico("C", 7, "CACARDE").
dico("C", 7, "CACHAIS").
dico("C", 7, "CACHAIT").
dico("C", 7, "CACHANT").
dico("C", 7, "CACHEES").
dico("C", 7, "CACHENT").
dico("C", 7, "CACHERA").
dico("C", 7, "CACHERE").
dico("C", 7, "CACHETA").
dico("C", 7, "CACHETE").
dico("C", 7, "CACHETS").
dico("C", 7, "CACHIEZ").
dico("C", 7, "CACHONS").
dico("C", 7, "CACHOTS").
dico("C", 7, "CACHOUS").
dico("C", 7, "CACIQUE").
dico("C", 7, "CACOLET").
dico("C", 7, "CACTEES").
dico("C", 7, "CACTIER").
dico("C", 7, "CADAVRE").
dico("C", 7, "CADDIES").
dico("C", 7, "CADEAUX").
dico("C", 7, "CADENAS").
dico("C", 7, "CADENCA").
dico("C", 7, "CADENCE").
dico("C", 7, "CADENES").
dico("C", 7, "CADETTE").
dico("C", 7, "CADMEEN").
dico("C", 7, "CADMIAI").
dico("C", 7, "CADMIAS").
dico("C", 7, "CADMIAT").
dico("C", 7, "CADMIEE").
dico("C", 7, "CADMIER").
dico("C", 7, "CADMIES").
dico("C", 7, "CADMIEZ").
dico("C", 7, "CADMIUM").
dico("C", 7, "CADOGAN").
dico("C", 7, "CADRAGE").
dico("C", 7, "CADRAIS").
dico("C", 7, "CADRAIT").
dico("C", 7, "CADRANS").
dico("C", 7, "CADRANT").
dico("C", 7, "CADRATS").
dico("C", 7, "CADREES").
dico("C", 7, "CADRENT").
dico("C", 7, "CADRERA").
dico("C", 7, "CADREUR").
dico("C", 7, "CADRIEZ").
dico("C", 7, "CADRONS").
dico("C", 7, "CADUCEE").
dico("C", 7, "CADUQUE").
dico("C", 7, "CAECALE").
dico("C", 7, "CAECAUX").
dico("C", 7, "CAECUMS").
dico("C", 7, "CAESIUM").
dico("C", 7, "CAFARDA").
dico("C", 7, "CAFARDE").
dico("C", 7, "CAFARDS").
dico("C", 7, "CAFEIER").
dico("C", 7, "CAFEINE").
dico("C", 7, "CAFETAI").
dico("C", 7, "CAFETAN").
dico("C", 7, "CAFETAS").
dico("C", 7, "CAFETAT").
dico("C", 7, "CAFETEE").
dico("C", 7, "CAFETER").
dico("C", 7, "CAFETES").
dico("C", 7, "CAFETEZ").
dico("C", 7, "CAFTAIS").
dico("C", 7, "CAFTAIT").
dico("C", 7, "CAFTANS").
dico("C", 7, "CAFTANT").
dico("C", 7, "CAFTEES").
dico("C", 7, "CAFTENT").
dico("C", 7, "CAFTERA").
dico("C", 7, "CAFTEUR").
dico("C", 7, "CAFTIEZ").
dico("C", 7, "CAFTONS").
dico("C", 7, "CAGEOTS").
dico("C", 7, "CAGETTE").
dico("C", 7, "CAGIBIS").
dico("C", 7, "CAGNARD").
dico("C", 7, "CAGNEUX").
dico("C", 7, "CAGOTES").
dico("C", 7, "CAGOULE").
dico("C", 7, "CAHIERS").
dico("C", 7, "CAHOTAI").
dico("C", 7, "CAHOTAS").
dico("C", 7, "CAHOTAT").
dico("C", 7, "CAHOTEE").
dico("C", 7, "CAHOTER").
dico("C", 7, "CAHOTES").
dico("C", 7, "CAHOTEZ").
dico("C", 7, "CAHUTES").
dico("C", 7, "CAIDATS").
dico("C", 7, "CAILLAI").
dico("C", 7, "CAILLAS").
dico("C", 7, "CAILLAT").
dico("C", 7, "CAILLEE").
dico("C", 7, "CAILLER").
dico("C", 7, "CAILLES").
dico("C", 7, "CAILLEZ").
dico("C", 7, "CAILLOT").
dico("C", 7, "CAILLOU").
dico("C", 7, "CAIMANS").
dico("C", 7, "CAIQUES").
dico("C", 7, "CAIROTE").
dico("C", 7, "CAISSES").
dico("C", 7, "CAISSON").
dico("C", 7, "CAITYAS").
dico("C", 7, "CAJEPUT").
dico("C", 7, "CAJOLAI").
dico("C", 7, "CAJOLAS").
dico("C", 7, "CAJOLAT").
dico("C", 7, "CAJOLEE").
dico("C", 7, "CAJOLER").
dico("C", 7, "CAJOLES").
dico("C", 7, "CAJOLEZ").
dico("C", 7, "CALAGES").
dico("C", 7, "CALAMAR").
dico("C", 7, "CALAMES").
dico("C", 7, "CALAMUS").
dico("C", 7, "CALASSE").
dico("C", 7, "CALATES").
dico("C", 7, "CALCIFS").
dico("C", 7, "CALCINA").
dico("C", 7, "CALCINE").
dico("C", 7, "CALCINS").
dico("C", 7, "CALCIOS").
dico("C", 7, "CALCITE").
dico("C", 7, "CALCIUM").
dico("C", 7, "CALCULA").
dico("C", 7, "CALCULE").
dico("C", 7, "CALCULS").
dico("C", 7, "CALECHE").
dico("C", 7, "CALECIF").
dico("C", 7, "CALECON").
dico("C", 7, "CALENDO").
dico("C", 7, "CALEPIN").
dico("C", 7, "CALERAI").
dico("C", 7, "CALERAS").
dico("C", 7, "CALEREZ").
dico("C", 7, "CALETAI").
dico("C", 7, "CALETAS").
dico("C", 7, "CALETAT").
dico("C", 7, "CALETEE").
dico("C", 7, "CALETER").
dico("C", 7, "CALETES").
dico("C", 7, "CALETEZ").
dico("C", 7, "CALFATA").
dico("C", 7, "CALFATE").
dico("C", 7, "CALFATS").
dico("C", 7, "CALIBRA").
dico("C", 7, "CALIBRE").
dico("C", 7, "CALICES").
dico("C", 7, "CALICHE").
dico("C", 7, "CALICOT").
dico("C", 7, "CALIERS").
dico("C", 7, "CALIFAT").
dico("C", 7, "CALIFES").
dico("C", 7, "CALINAI").
dico("C", 7, "CALINAS").
dico("C", 7, "CALINAT").
dico("C", 7, "CALINEE").
dico("C", 7, "CALINER").
dico("C", 7, "CALINES").
dico("C", 7, "CALINEZ").
dico("C", 7, "CALIONS").
dico("C", 7, "CALLAIS").
dico("C", 7, "CALLAIT").
dico("C", 7, "CALLANT").
dico("C", 7, "CALLEES").
dico("C", 7, "CALLENT").
dico("C", 7, "CALLERA").
dico("C", 7, "CALLEUR").
dico("C", 7, "CALLEUX").
dico("C", 7, "CALLIEZ").
dico("C", 7, "CALLONS").
dico("C", 7, "CALLUNE").
dico("C", 7, "CALMAGE").
dico("C", 7, "CALMAIS").
dico("C", 7, "CALMAIT").
dico("C", 7, "CALMANT").
dico("C", 7, "CALMARS").
dico("C", 7, "CALMEES").
dico("C", 7, "CALMENT").
dico("C", 7, "CALMERA").
dico("C", 7, "CALMIEZ").
dico("C", 7, "CALMIRA").
dico("C", 7, "CALMONS").
dico("C", 7, "CALOMEL").
dico("C", 7, "CALORIE").
dico("C", 7, "CALOTIN").
dico("C", 7, "CALOTTA").
dico("C", 7, "CALOTTE").
dico("C", 7, "CALOYER").
dico("C", 7, "CALQUAI").
dico("C", 7, "CALQUAS").
dico("C", 7, "CALQUAT").
dico("C", 7, "CALQUEE").
dico("C", 7, "CALQUER").
dico("C", 7, "CALQUES").
dico("C", 7, "CALQUEZ").
dico("C", 7, "CALTAIS").
dico("C", 7, "CALTAIT").
dico("C", 7, "CALTANT").
dico("C", 7, "CALTEES").
dico("C", 7, "CALTENT").
dico("C", 7, "CALTERA").
dico("C", 7, "CALTIEZ").
dico("C", 7, "CALTONS").
dico("C", 7, "CALUGEA").
dico("C", 7, "CALUGER").
dico("C", 7, "CALUGES").
dico("C", 7, "CALUGEZ").
dico("C", 7, "CALUMET").
dico("C", 7, "CALURES").
dico("C", 7, "CALYPSO").
dico("C", 7, "CAMAIEU").
dico("C", 7, "CAMAILS").
dico("C", 7, "CAMAMES").
dico("C", 7, "CAMARDE").
dico("C", 7, "CAMARDS").
dico("C", 7, "CAMASSE").
dico("C", 7, "CAMATES").
dico("C", 7, "CAMBAIS").
dico("C", 7, "CAMBAIT").
dico("C", 7, "CAMBANT").
dico("C", 7, "CAMBEES").
dico("C", 7, "CAMBENT").
dico("C", 7, "CAMBERA").
dico("C", 7, "CAMBIAL").
dico("C", 7, "CAMBIEZ").
dico("C", 7, "CAMBIUM").
dico("C", 7, "CAMBONS").
dico("C", 7, "CAMBRAI").
dico("C", 7, "CAMBRAS").
dico("C", 7, "CAMBRAT").
dico("C", 7, "CAMBREE").
dico("C", 7, "CAMBRER").
dico("C", 7, "CAMBRES").
dico("C", 7, "CAMBREZ").
dico("C", 7, "CAMBUSE").
dico("C", 7, "CAMELIA").
dico("C", 7, "CAMELLE").
dico("C", 7, "CAMELOT").
dico("C", 7, "CAMERAI").
dico("C", 7, "CAMERAL").
dico("C", 7, "CAMERAS").
dico("C", 7, "CAMEREZ").
dico("C", 7, "CAMIONS").
dico("C", 7, "CAMORRA").
dico("C", 7, "CAMPAIS").
dico("C", 7, "CAMPAIT").
dico("C", 7, "CAMPANE").
dico("C", 7, "CAMPANT").
dico("C", 7, "CAMPEES").
dico("C", 7, "CAMPENT").
dico("C", 7, "CAMPERA").
dico("C", 7, "CAMPEUR").
dico("C", 7, "CAMPHRA").
dico("C", 7, "CAMPHRE").
dico("C", 7, "CAMPIEZ").
dico("C", 7, "CAMPING").
dico("C", 7, "CAMPONS").
dico("C", 7, "CAMUSES").
dico("C", 7, "CANADAS").
dico("C", 7, "CANAMES").
dico("C", 7, "CANAPES").
dico("C", 7, "CANAQUE").
dico("C", 7, "CANARAS").
dico("C", 7, "CANARDA").
dico("C", 7, "CANARDE").
dico("C", 7, "CANARDS").
dico("C", 7, "CANARIS").
dico("C", 7, "CANASSE").
dico("C", 7, "CANASTA").
dico("C", 7, "CANATES").
dico("C", 7, "CANCALE").
dico("C", 7, "CANCANA").
dico("C", 7, "CANCANE").
dico("C", 7, "CANCANS").
dico("C", 7, "CANCELS").
dico("C", 7, "CANCERS").
dico("C", 7, "CANCHES").
dico("C", 7, "CANCRES").
dico("C", 7, "CANDACE").
dico("C", 7, "CANDELA").
dico("C", 7, "CANDEUR").
dico("C", 7, "CANDIDA").
dico("C", 7, "CANDIDE").
dico("C", 7, "CANDIES").
dico("C", 7, "CANDIRA").
dico("C", 7, "CANEPIN").
dico("C", 7, "CANERAI").
dico("C", 7, "CANERAS").
dico("C", 7, "CANEREZ").
dico("C", 7, "CANETON").
dico("C", 7, "CANETTE").
dico("C", 7, "CANEVAS").
dico("C", 7, "CANEZOU").
dico("C", 7, "CANGUES").
dico("C", 7, "CANICHE").
dico("C", 7, "CANIDES").
dico("C", 7, "CANIERS").
dico("C", 7, "CANINES").
dico("C", 7, "CANIONS").
dico("C", 7, "CANISSE").
dico("C", 7, "CANITIE").
dico("C", 7, "CANNAGE").
dico("C", 7, "CANNAIE").
dico("C", 7, "CANNAIS").
dico("C", 7, "CANNAIT").
dico("C", 7, "CANNANT").
dico("C", 7, "CANNEES").
dico("C", 7, "CANNELA").
dico("C", 7, "CANNELE").
dico("C", 7, "CANNENT").
dico("C", 7, "CANNERA").
dico("C", 7, "CANNEUR").
dico("C", 7, "CANNIER").
dico("C", 7, "CANNIEZ").
dico("C", 7, "CANNOIS").
dico("C", 7, "CANNONS").
dico("C", 7, "CANONNA").
dico("C", 7, "CANONNE").
dico("C", 7, "CANOPEE").
dico("C", 7, "CANOPES").
dico("C", 7, "CANOTAI").
dico("C", 7, "CANOTAS").
dico("C", 7, "CANOTAT").
dico("C", 7, "CANOTER").
dico("C", 7, "CANOTES").
dico("C", 7, "CANOTEZ").
dico("C", 7, "CANTALS").
dico("C", 7, "CANTATE").
dico("C", 7, "CANTERS").
dico("C", 7, "CANTINA").
dico("C", 7, "CANTINE").
dico("C", 7, "CANTONS").
dico("C", 7, "CANTORS").
dico("C", 7, "CANTRES").
dico("C", 7, "CANULAI").
dico("C", 7, "CANULAR").
dico("C", 7, "CANULAS").
dico("C", 7, "CANULAT").
dico("C", 7, "CANULEE").
dico("C", 7, "CANULER").
dico("C", 7, "CANULES").
dico("C", 7, "CANULEZ").
dico("C", 7, "CANUSES").
dico("C", 7, "CANYONS").
dico("C", 7, "CANZONE").
dico("C", 7, "CANZONI").
dico("C", 7, "CAOUANE").
dico("C", 7, "CAPABLE").
dico("C", 7, "CAPAMES").
dico("C", 7, "CAPASSE").
dico("C", 7, "CAPATES").
dico("C", 7, "CAPEAIS").
dico("C", 7, "CAPEAIT").
dico("C", 7, "CAPEANT").
dico("C", 7, "CAPEENT").
dico("C", 7, "CAPEERA").
dico("C", 7, "CAPEIEZ").
dico("C", 7, "CAPELAI").
dico("C", 7, "CAPELAN").
dico("C", 7, "CAPELAS").
dico("C", 7, "CAPELAT").
dico("C", 7, "CAPELEE").
dico("C", 7, "CAPELER").
dico("C", 7, "CAPELES").
dico("C", 7, "CAPELET").
dico("C", 7, "CAPELEZ").
dico("C", 7, "CAPELLA").
dico("C", 7, "CAPELLE").
dico("C", 7, "CAPEONS").
dico("C", 7, "CAPERAI").
dico("C", 7, "CAPERAS").
dico("C", 7, "CAPEREZ").
dico("C", 7, "CAPEYAI").
dico("C", 7, "CAPEYAS").
dico("C", 7, "CAPEYAT").
dico("C", 7, "CAPEYER").
dico("C", 7, "CAPEYES").
dico("C", 7, "CAPEYEZ").
dico("C", 7, "CAPIONS").
dico("C", 7, "CAPITAL").
dico("C", 7, "CAPITAN").
dico("C", 7, "CAPITEE").
dico("C", 7, "CAPITES").
dico("C", 7, "CAPITON").
dico("C", 7, "CAPONNA").
dico("C", 7, "CAPONNE").
dico("C", 7, "CAPORAL").
dico("C", 7, "CAPOTAI").
dico("C", 7, "CAPOTAS").
dico("C", 7, "CAPOTAT").
dico("C", 7, "CAPOTEE").
dico("C", 7, "CAPOTER").
dico("C", 7, "CAPOTES").
dico("C", 7, "CAPOTEZ").
dico("C", 7, "CAPOUAN").
dico("C", 7, "CAPRICE").
dico("C", 7, "CAPRIER").
dico("C", 7, "CAPRINE").
dico("C", 7, "CAPRINS").
dico("C", 7, "CAPRONS").
dico("C", 7, "CAPSAGE").
dico("C", 7, "CAPSIDE").
dico("C", 7, "CAPSIEN").
dico("C", 7, "CAPSULA").
dico("C", 7, "CAPSULE").
dico("C", 7, "CAPTAGE").
dico("C", 7, "CAPTAIS").
dico("C", 7, "CAPTAIT").
dico("C", 7, "CAPTALS").
dico("C", 7, "CAPTANT").
dico("C", 7, "CAPTEES").
dico("C", 7, "CAPTENT").
dico("C", 7, "CAPTERA").
dico("C", 7, "CAPTEUR").
dico("C", 7, "CAPTIEZ").
dico("C", 7, "CAPTIFS").
dico("C", 7, "CAPTIVA").
dico("C", 7, "CAPTIVE").
dico("C", 7, "CAPTONS").
dico("C", 7, "CAPTURA").
dico("C", 7, "CAPTURE").
dico("C", 7, "CAPUCES").
dico("C", 7, "CAPUCHE").
dico("C", 7, "CAPUCIN").
dico("C", 7, "CAPULET").
dico("C", 7, "CAQUAGE").
dico("C", 7, "CAQUAIS").
dico("C", 7, "CAQUAIT").
dico("C", 7, "CAQUANT").
dico("C", 7, "CAQUEES").
dico("C", 7, "CAQUENT").
dico("C", 7, "CAQUERA").
dico("C", 7, "CAQUETA").
dico("C", 7, "CAQUETE").
dico("C", 7, "CAQUETS").
dico("C", 7, "CAQUEUR").
dico("C", 7, "CAQUIEZ").
dico("C", 7, "CAQUONS").
dico("C", 7, "CARABES").
dico("C", 7, "CARABIN").
dico("C", 7, "CARACAL").
dico("C", 7, "CARACOS").
dico("C", 7, "CARACUL").
dico("C", 7, "CARAFAI").
dico("C", 7, "CARAFAS").
dico("C", 7, "CARAFAT").
dico("C", 7, "CARAFEE").
dico("C", 7, "CARAFER").
dico("C", 7, "CARAFES").
dico("C", 7, "CARAFEZ").
dico("C", 7, "CARAFON").
dico("C", 7, "CARAIBE").
dico("C", 7, "CARAITE").
dico("C", 7, "CARAMBA").
dico("C", 7, "CARAMEL").
dico("C", 7, "CARAQUE").
dico("C", 7, "CARASSE").
dico("C", 7, "CARATES").
dico("C", 7, "CARBETS").
dico("C", 7, "CARBONE").
dico("C", 7, "CARBURA").
dico("C", 7, "CARBURE").
dico("C", 7, "CARCANS").
dico("C", 7, "CARCELS").
dico("C", 7, "CARDAGE").
dico("C", 7, "CARDAIS").
dico("C", 7, "CARDAIT").
dico("C", 7, "CARDANS").
dico("C", 7, "CARDANT").
dico("C", 7, "CARDEES").
dico("C", 7, "CARDENT").
dico("C", 7, "CARDERA").
dico("C", 7, "CARDERE").
dico("C", 7, "CARDEUR").
dico("C", 7, "CARDIAL").
dico("C", 7, "CARDIAS").
dico("C", 7, "CARDIEZ").
dico("C", 7, "CARDIOS").
dico("C", 7, "CARDITE").
dico("C", 7, "CARDIUM").
dico("C", 7, "CARDONS").
dico("C", 7, "CAREMES").
dico("C", 7, "CARENAI").
dico("C", 7, "CARENAS").
dico("C", 7, "CARENAT").
dico("C", 7, "CARENCA").
dico("C", 7, "CARENCE").
dico("C", 7, "CARENEE").
dico("C", 7, "CARENER").
dico("C", 7, "CARENES").
dico("C", 7, "CARENEZ").
dico("C", 7, "CARESSA").
dico("C", 7, "CARESSE").
dico("C", 7, "CARGUAI").
dico("C", 7, "CARGUAS").
dico("C", 7, "CARGUAT").
dico("C", 7, "CARGUEE").
dico("C", 7, "CARGUER").
dico("C", 7, "CARGUES").
dico("C", 7, "CARGUEZ").
dico("C", 7, "CARIAIS").
dico("C", 7, "CARIAIT").
dico("C", 7, "CARIANT").
dico("C", 7, "CARIBES").
dico("C", 7, "CARIBOU").
dico("C", 7, "CARIEES").
dico("C", 7, "CARIENT").
dico("C", 7, "CARIERA").
dico("C", 7, "CARIEUX").
dico("C", 7, "CARIIEZ").
dico("C", 7, "CARIOCA").
dico("C", 7, "CARIONS").
dico("C", 7, "CARISTE").
dico("C", 7, "CARLINE").
dico("C", 7, "CARLINS").
dico("C", 7, "CARMELS").
dico("C", 7, "CARMINA").
dico("C", 7, "CARMINE").
dico("C", 7, "CARMINS").
dico("C", 7, "CARNAGE").
dico("C", 7, "CARNAUX").
dico("C", 7, "CARNEAU").
dico("C", 7, "CARNEES").
dico("C", 7, "CARNELE").
dico("C", 7, "CARNETS").
dico("C", 7, "CARNIER").
dico("C", 7, "CAROGNE").
dico("C", 7, "CAROLIN").
dico("C", 7, "CAROLOS").
dico("C", 7, "CAROLUS").
dico("C", 7, "CAROTTA").
dico("C", 7, "CAROTTE").
dico("C", 7, "CAROUBE").
dico("C", 7, "CAROUGE").
dico("C", 7, "CARPEAU").
dico("C", 7, "CARPEES").
dico("C", 7, "CARPIEN").
dico("C", 7, "CARRAIS").
dico("C", 7, "CARRAIT").
dico("C", 7, "CARRANT").
dico("C", 7, "CARRARE").
dico("C", 7, "CARREAU").
dico("C", 7, "CARREES").
dico("C", 7, "CARRELA").
dico("C", 7, "CARRELE").
dico("C", 7, "CARRENT").
dico("C", 7, "CARRERA").
dico("C", 7, "CARRICK").
dico("C", 7, "CARRIER").
dico("C", 7, "CARRIEZ").
dico("C", 7, "CARROIE").
dico("C", 7, "CARRONS").
dico("C", 7, "CARROYA").
dico("C", 7, "CARROYE").
dico("C", 7, "CARRURE").
dico("C", 7, "CARTAIE").
dico("C", 7, "CARTAIS").
dico("C", 7, "CARTAIT").
dico("C", 7, "CARTANT").
dico("C", 7, "CARTAYA").
dico("C", 7, "CARTAYE").
dico("C", 7, "CARTEES").
dico("C", 7, "CARTELS").
dico("C", 7, "CARTENT").
dico("C", 7, "CARTERA").
dico("C", 7, "CARTERS").
dico("C", 7, "CARTIER").
dico("C", 7, "CARTIEZ").
dico("C", 7, "CARTONS").
dico("C", 7, "CARTOON").
dico("C", 7, "CARYERS").
dico("C", 7, "CASAMES").
dico("C", 7, "CASAQUE").
dico("C", 7, "CASASSE").
dico("C", 7, "CASATES").
dico("C", 7, "CASBAHS").
dico("C", 7, "CASCADA").
dico("C", 7, "CASCADE").
dico("C", 7, "CASCARA").
dico("C", 7, "CASCHER").
dico("C", 7, "CASEEUX").
dico("C", 7, "CASEINE").
dico("C", 7, "CASERAI").
dico("C", 7, "CASERAS").
dico("C", 7, "CASERET").
dico("C", 7, "CASEREZ").
dico("C", 7, "CASERNA").
dico("C", 7, "CASERNE").
dico("C", 7, "CASETTE").
dico("C", 7, "CASIERS").
dico("C", 7, "CASIMIR").
dico("C", 7, "CASINGS").
dico("C", 7, "CASINOS").
dico("C", 7, "CASIONS").
dico("C", 7, "CASOARS").
dico("C", 7, "CASQUAI").
dico("C", 7, "CASQUAS").
dico("C", 7, "CASQUAT").
dico("C", 7, "CASQUEE").
dico("C", 7, "CASQUER").
dico("C", 7, "CASQUES").
dico("C", 7, "CASQUEZ").
dico("C", 7, "CASSAGE").
dico("C", 7, "CASSAIS").
dico("C", 7, "CASSAIT").
dico("C", 7, "CASSANT").
dico("C", 7, "CASSATE").
dico("C", 7, "CASSAVE").
dico("C", 7, "CASSEAU").
dico("C", 7, "CASSEES").
dico("C", 7, "CASSENT").
dico("C", 7, "CASSERA").
dico("C", 7, "CASSEUR").
dico("C", 7, "CASSIER").
dico("C", 7, "CASSIES").
dico("C", 7, "CASSIEZ").
dico("C", 7, "CASSINE").
dico("C", 7, "CASSONS").
dico("C", 7, "CASSOTS").
dico("C", 7, "CASSURE").
dico("C", 7, "CASTARD").
dico("C", 7, "CASTARS").
dico("C", 7, "CASTELS").
dico("C", 7, "CASTINE").
dico("C", 7, "CASTING").
dico("C", 7, "CASTORS").
dico("C", 7, "CASTRAI").
dico("C", 7, "CASTRAS").
dico("C", 7, "CASTRAT").
dico("C", 7, "CASTREE").
dico("C", 7, "CASTRER").
dico("C", 7, "CASTRES").
dico("C", 7, "CASTREZ").
dico("C", 7, "CASTRUM").
dico("C", 7, "CASUELS").
dico("C", 7, "CATAIRE").
dico("C", 7, "CATALAN").
dico("C", 7, "CATALPA").
dico("C", 7, "CATCHAI").
dico("C", 7, "CATCHAS").
dico("C", 7, "CATCHAT").
dico("C", 7, "CATCHER").
dico("C", 7, "CATCHES").
dico("C", 7, "CATCHEZ").
dico("C", 7, "CATELLE").
dico("C", 7, "CATGUTS").
dico("C", 7, "CATHARE").
dico("C", 7, "CATHODE").
dico("C", 7, "CATIMES").
dico("C", 7, "CATINAI").
dico("C", 7, "CATINAS").
dico("C", 7, "CATINAT").
dico("C", 7, "CATINEE").
dico("C", 7, "CATINER").
dico("C", 7, "CATINES").
dico("C", 7, "CATINEZ").
dico("C", 7, "CATIONS").
dico("C", 7, "CATIRAI").
dico("C", 7, "CATIRAS").
dico("C", 7, "CATIREZ").
dico("C", 7, "CATISSE").
dico("C", 7, "CATITES").
dico("C", 7, "CATLEYA").
dico("C", 7, "CATOGAN").
dico("C", 7, "CAUDALE").
dico("C", 7, "CAUDAUX").
dico("C", 7, "CAUDEES").
dico("C", 7, "CAUSAIS").
dico("C", 7, "CAUSAIT").
dico("C", 7, "CAUSALE").
dico("C", 7, "CAUSALS").
dico("C", 7, "CAUSANT").
dico("C", 7, "CAUSAUX").
dico("C", 7, "CAUSEES").
dico("C", 7, "CAUSENT").
dico("C", 7, "CAUSERA").
dico("C", 7, "CAUSEUR").
dico("C", 7, "CAUSIEZ").
dico("C", 7, "CAUSONS").
dico("C", 7, "CAUSSES").
dico("C", 7, "CAUTELE").
dico("C", 7, "CAUTERE").
dico("C", 7, "CAUTION").
dico("C", 7, "CAVAGES").
dico("C", 7, "CAVALAI").
dico("C", 7, "CAVALAS").
dico("C", 7, "CAVALAT").
dico("C", 7, "CAVALEE").
dico("C", 7, "CAVALER").
dico("C", 7, "CAVALES").
dico("C", 7, "CAVALEZ").
dico("C", 7, "CAVAMES").
dico("C", 7, "CAVASSE").
dico("C", 7, "CAVATES").
dico("C", 7, "CAVEAUX").
dico("C", 7, "CAVECON").
dico("C", 7, "CAVERAI").
dico("C", 7, "CAVERAS").
dico("C", 7, "CAVEREZ").
dico("C", 7, "CAVERNE").
dico("C", 7, "CAVIARS").
dico("C", 7, "CAVIONS").
dico("C", 7, "CAVISTE").
dico("C", 7, "CAVITES").
dico("C", 7, "CAWCHER").
dico("C", 7, "CAYENNE").
dico("C", 7, "CAZETTE").
dico("C", 7, "CEBIDES").
dico("C", 7, "CEBISTE").
dico("C", 7, "CEBUANO").
dico("C", 7, "CECIDIE").
dico("C", 7, "CECILIE").
dico("C", 7, "CECITES").
dico("C", 7, "CEDAMES").
dico("C", 7, "CEDANTE").
dico("C", 7, "CEDANTS").
dico("C", 7, "CEDASSE").
dico("C", 7, "CEDATES").
dico("C", 7, "CEDERAI").
dico("C", 7, "CEDERAS").
dico("C", 7, "CEDEREZ").
dico("C", 7, "CEDEROM").
dico("C", 7, "CEDILLE").
dico("C", 7, "CEDIONS").
dico("C", 7, "CEDRAIE").
dico("C", 7, "CEDRATS").
dico("C", 7, "CEDULES").
dico("C", 7, "CEIGNES").
dico("C", 7, "CEIGNEZ").
dico("C", 7, "CEIGNIS").
dico("C", 7, "CEIGNIT").
dico("C", 7, "CEINDRA").
dico("C", 7, "CEINDRE").
dico("C", 7, "CEINTES").
dico("C", 7, "CELADON").
dico("C", 7, "CELAMES").
dico("C", 7, "CELASSE").
dico("C", 7, "CELATES").
dico("C", 7, "CELEBRA").
dico("C", 7, "CELEBRE").
dico("C", 7, "CELERAI").
dico("C", 7, "CELERAS").
dico("C", 7, "CELEREZ").
dico("C", 7, "CELERIS").
dico("C", 7, "CELESTA").
dico("C", 7, "CELESTE").
dico("C", 7, "CELIBAT").
dico("C", 7, "CELIONS").
dico("C", 7, "CELLIER").
dico("C", 7, "CELLULE").
dico("C", 7, "CELSIUS").
dico("C", 7, "CELTIUM").
dico("C", 7, "CEMBROS").
dico("C", 7, "CEMENTA").
dico("C", 7, "CEMENTE").
dico("C", 7, "CEMENTS").
dico("C", 7, "CENACLE").
dico("C", 7, "CENDRAI").
dico("C", 7, "CENDRAS").
dico("C", 7, "CENDRAT").
dico("C", 7, "CENDREE").
dico("C", 7, "CENDRER").
dico("C", 7, "CENDRES").
dico("C", 7, "CENDREZ").
dico("C", 7, "CENELLE").
dico("C", 7, "CENSEES").
dico("C", 7, "CENSEUR").
dico("C", 7, "CENSIER").
dico("C", 7, "CENSIVE").
dico("C", 7, "CENSUEL").
dico("C", 7, "CENSURA").
dico("C", 7, "CENSURE").
dico("C", 7, "CENTAVO").
dico("C", 7, "CENTILE").
dico("C", 7, "CENTIME").
dico("C", 7, "CENTONS").
dico("C", 7, "CENTRAI").
dico("C", 7, "CENTRAL").
dico("C", 7, "CENTRAS").
dico("C", 7, "CENTRAT").
dico("C", 7, "CENTREE").
dico("C", 7, "CENTRER").
dico("C", 7, "CENTRES").
dico("C", 7, "CENTREZ").
dico("C", 7, "CENURES").
dico("C", 7, "CEPAGES").
dico("C", 7, "CERAMES").
dico("C", 7, "CERASTE").
dico("C", 7, "CERBERE").
dico("C", 7, "CERCEAU").
dico("C", 7, "CERCHES").
dico("C", 7, "CERCLAI").
dico("C", 7, "CERCLAS").
dico("C", 7, "CERCLAT").
dico("C", 7, "CERCLEE").
dico("C", 7, "CERCLER").
dico("C", 7, "CERCLES").
dico("C", 7, "CERCLEZ").
dico("C", 7, "CERDANE").
dico("C", 7, "CERDANS").
dico("C", 7, "CEREALE").
dico("C", 7, "CERISES").
dico("C", 7, "CERITES").
dico("C", 7, "CERITHE").
dico("C", 7, "CERIUMS").
dico("C", 7, "CERMETS").
dico("C", 7, "CERNAIS").
dico("C", 7, "CERNAIT").
dico("C", 7, "CERNANT").
dico("C", 7, "CERNEAU").
dico("C", 7, "CERNEES").
dico("C", 7, "CERNENT").
dico("C", 7, "CERNERA").
dico("C", 7, "CERNIEZ").
dico("C", 7, "CERNONS").
dico("C", 7, "CERNURE").
dico("C", 7, "CERQUES").
dico("C", 7, "CERTAIN").
dico("C", 7, "CERTIFS").
dico("C", 7, "CERULEE").
dico("C", 7, "CERULES").
dico("C", 7, "CERUMEN").
dico("C", 7, "CERUSEE").
dico("C", 7, "CERUSES").
dico("C", 7, "CERVEAU").
dico("C", 7, "CERVIDE").
dico("C", 7, "CERVIER").
dico("C", 7, "CESIUMS").
dico("C", 7, "CESSAIS").
dico("C", 7, "CESSAIT").
dico("C", 7, "CESSANT").
dico("C", 7, "CESSEES").
dico("C", 7, "CESSENT").
dico("C", 7, "CESSERA").
dico("C", 7, "CESSIEZ").
dico("C", 7, "CESSION").
dico("C", 7, "CESSONS").
dico("C", 7, "CESTODE").
dico("C", 7, "CESURES").
dico("C", 7, "CETACEE").
dico("C", 7, "CETACES").
dico("C", 7, "CETANES").
dico("C", 7, "CETEAUX").
dico("C", 7, "CETENES").
dico("C", 7, "CETERAC").
dico("C", 7, "CETOINE").
dico("C", 7, "CETONES").
dico("C", 7, "CETOSES").
dico("C", 7, "CEVENOL").
dico("C", 7, "CEVICHE").
dico("C", 7, "CEZIGUE").
dico("C", 7, "CHABINE").
dico("C", 7, "CHABINS").
dico("C", 7, "CHABLAI").
dico("C", 7, "CHABLAS").
dico("C", 7, "CHABLAT").
dico("C", 7, "CHABLEE").
dico("C", 7, "CHABLER").
dico("C", 7, "CHABLES").
dico("C", 7, "CHABLEZ").
dico("C", 7, "CHABLIS").
dico("C", 7, "CHABLON").
dico("C", 7, "CHABOTS").
dico("C", 7, "CHABROL").
dico("C", 7, "CHABROT").
dico("C", 7, "CHACALS").
dico("C", 7, "CHACONE").
dico("C", 7, "CHACUNE").
dico("C", 7, "CHADOUF").
dico("C", 7, "CHAFIIS").
dico("C", 7, "CHAGRIN").
dico("C", 7, "CHAHUTA").
dico("C", 7, "CHAHUTE").
dico("C", 7, "CHAHUTS").
dico("C", 7, "CHAILLE").
dico("C", 7, "CHAINAI").
dico("C", 7, "CHAINAS").
dico("C", 7, "CHAINAT").
dico("C", 7, "CHAINEE").
dico("C", 7, "CHAINER").
dico("C", 7, "CHAINES").
dico("C", 7, "CHAINEZ").
dico("C", 7, "CHAINON").
dico("C", 7, "CHAIOTE").
dico("C", 7, "CHAIRES").
dico("C", 7, "CHAISES").
dico("C", 7, "CHAKRAS").
dico("C", 7, "CHALAND").
dico("C", 7, "CHALAZE").
dico("C", 7, "CHALETS").
dico("C", 7, "CHALEUR").
dico("C", 7, "CHALINS").
dico("C", 7, "CHALITS").
dico("C", 7, "CHALOIR").
dico("C", 7, "CHALONE").
dico("C", 7, "CHALUTA").
dico("C", 7, "CHALUTE").
dico("C", 7, "CHALUTS").
dico("C", 7, "CHAMADE").
dico("C", 7, "CHAMANE").
dico("C", 7, "CHAMANS").
dico("C", 7, "CHAMBRA").
dico("C", 7, "CHAMBRE").
dico("C", 7, "CHAMEAU").
dico("C", 7, "CHAMOIS").
dico("C", 7, "CHAMPIS").
dico("C", 7, "CHAMSIN").
dico("C", 7, "CHANCEL").
dico("C", 7, "CHANCES").
dico("C", 7, "CHANCIE").
dico("C", 7, "CHANCIR").
dico("C", 7, "CHANCIS").
dico("C", 7, "CHANCIT").
dico("C", 7, "CHANCRE").
dico("C", 7, "CHANGEA").
dico("C", 7, "CHANGEE").
dico("C", 7, "CHANGER").
dico("C", 7, "CHANGES").
dico("C", 7, "CHANGEZ").
dico("C", 7, "CHANNES").
dico("C", 7, "CHANSON").
dico("C", 7, "CHANTAI").
dico("C", 7, "CHANTAS").
dico("C", 7, "CHANTAT").
dico("C", 7, "CHANTEE").
dico("C", 7, "CHANTER").
dico("C", 7, "CHANTES").
dico("C", 7, "CHANTEZ").
dico("C", 7, "CHANTRE").
dico("C", 7, "CHANVRE").
dico("C", 7, "CHAOUCH").
dico("C", 7, "CHAPEAU").
dico("C", 7, "CHAPEES").
dico("C", 7, "CHAPELA").
dico("C", 7, "CHAPELE").
dico("C", 7, "CHAPKAS").
dico("C", 7, "CHAPONS").
dico("C", 7, "CHAPSKA").
dico("C", 7, "CHARADE").
dico("C", 7, "CHARALE").
dico("C", 7, "CHARBON").
dico("C", 7, "CHARDON").
dico("C", 7, "CHARGEA").
dico("C", 7, "CHARGEE").
dico("C", 7, "CHARGER").
dico("C", 7, "CHARGES").
dico("C", 7, "CHARGEZ").
dico("C", 7, "CHARIAS").
dico("C", 7, "CHARIOT").
dico("C", 7, "CHARITE").
dico("C", 7, "CHARLOT").
dico("C", 7, "CHARMAI").
dico("C", 7, "CHARMAS").
dico("C", 7, "CHARMAT").
dico("C", 7, "CHARMEE").
dico("C", 7, "CHARMER").
dico("C", 7, "CHARMES").
dico("C", 7, "CHARMEZ").
dico("C", 7, "CHARNEL").
dico("C", 7, "CHARNUE").
dico("C", 7, "CHARNUS").
dico("C", 7, "CHARPIE").
dico("C", 7, "CHARREE").
dico("C", 7, "CHARRES").
dico("C", 7, "CHARRET").
dico("C", 7, "CHARRIA").
dico("C", 7, "CHARRIE").
dico("C", 7, "CHARROI").
dico("C", 7, "CHARRON").
dico("C", 7, "CHARRUA").
dico("C", 7, "CHARRUE").
dico("C", 7, "CHARTER").
dico("C", 7, "CHARTES").
dico("C", 7, "CHARTIL").
dico("C", 7, "CHARTRE").
dico("C", 7, "CHASSAI").
dico("C", 7, "CHASSAS").
dico("C", 7, "CHASSAT").
dico("C", 7, "CHASSEE").
dico("C", 7, "CHASSER").
dico("C", 7, "CHASSES").
dico("C", 7, "CHASSEZ").
dico("C", 7, "CHASSIE").
dico("C", 7, "CHASSIS").
dico("C", 7, "CHASTES").
dico("C", 7, "CHATAIN").
dico("C", 7, "CHATEAU").
dico("C", 7, "CHATIAI").
dico("C", 7, "CHATIAS").
dico("C", 7, "CHATIAT").
dico("C", 7, "CHATIEE").
dico("C", 7, "CHATIER").
dico("C", 7, "CHATIES").
dico("C", 7, "CHATIEZ").
dico("C", 7, "CHATOIE").
dico("C", 7, "CHATONS").
dico("C", 7, "CHATOYA").
dico("C", 7, "CHATOYE").
dico("C", 7, "CHATRAI").
dico("C", 7, "CHATRAS").
dico("C", 7, "CHATRAT").
dico("C", 7, "CHATREE").
dico("C", 7, "CHATRER").
dico("C", 7, "CHATRES").
dico("C", 7, "CHATREZ").
dico("C", 7, "CHATTAI").
dico("C", 7, "CHATTAS").
dico("C", 7, "CHATTAT").
dico("C", 7, "CHATTER").
dico("C", 7, "CHATTES").
dico("C", 7, "CHATTEZ").
dico("C", 7, "CHAUDES").
dico("C", 7, "CHAUFFA").
dico("C", 7, "CHAUFFE").
dico("C", 7, "CHAULAI").
dico("C", 7, "CHAULAS").
dico("C", 7, "CHAULAT").
dico("C", 7, "CHAULEE").
dico("C", 7, "CHAULER").
dico("C", 7, "CHAULES").
dico("C", 7, "CHAULEZ").
dico("C", 7, "CHAUMAI").
dico("C", 7, "CHAUMAS").
dico("C", 7, "CHAUMAT").
dico("C", 7, "CHAUMEE").
dico("C", 7, "CHAUMER").
dico("C", 7, "CHAUMES").
dico("C", 7, "CHAUMEZ").
dico("C", 7, "CHAUSSA").
dico("C", 7, "CHAUSSE").
dico("C", 7, "CHAUVES").
dico("C", 7, "CHAUVEZ").
dico("C", 7, "CHAUVIN").
dico("C", 7, "CHAUVIR").
dico("C", 7, "CHAUVIS").
dico("C", 7, "CHAUVIT").
dico("C", 7, "CHAVIRA").
dico("C", 7, "CHAVIRE").
dico("C", 7, "CHAYOTE").
dico("C", 7, "CHEBECS").
dico("C", 7, "CHEBEKS").
dico("C", 7, "CHECHES").
dico("C", 7, "CHECHIA").
dico("C", 7, "CHEDAIL").
dico("C", 7, "CHEDDAR").
dico("C", 7, "CHEIKHS").
dico("C", 7, "CHEIRES").
dico("C", 7, "CHELATE").
dico("C", 7, "CHELEMS").
dico("C", 7, "CHEMINA").
dico("C", 7, "CHEMINE").
dico("C", 7, "CHEMINS").
dico("C", 7, "CHEMISA").
dico("C", 7, "CHEMISE").
dico("C", 7, "CHENAIE").
dico("C", 7, "CHENALA").
dico("C", 7, "CHENALE").
dico("C", 7, "CHENAUX").
dico("C", 7, "CHENEAU").
dico("C", 7, "CHENETS").
dico("C", 7, "CHENILS").
dico("C", 7, "CHENITS").
dico("C", 7, "CHENUES").
dico("C", 7, "CHEPTEL").
dico("C", 7, "CHEQUES").
dico("C", 7, "CHERAIS").
dico("C", 7, "CHERAIT").
dico("C", 7, "CHERANT").
dico("C", 7, "CHERCHA").
dico("C", 7, "CHERCHE").
dico("C", 7, "CHERENT").
dico("C", 7, "CHERERA").
dico("C", 7, "CHERGUI").
dico("C", 7, "CHERIES").
dico("C", 7, "CHERIEZ").
dico("C", 7, "CHERIFS").
dico("C", 7, "CHERIRA").
dico("C", 7, "CHERMES").
dico("C", 7, "CHERONS").
dico("C", 7, "CHEROTS").
dico("C", 7, "CHERRAI").
dico("C", 7, "CHERRAS").
dico("C", 7, "CHERRAT").
dico("C", 7, "CHERRER").
dico("C", 7, "CHERRES").
dico("C", 7, "CHERREZ").
dico("C", 7, "CHERRYS").
dico("C", 7, "CHERTES").
dico("C", 7, "CHERVIS").
dico("C", 7, "CHESTER").
dico("C", 7, "CHETIFS").
dico("C", 7, "CHETIVE").
dico("C", 7, "CHEVAGE").
dico("C", 7, "CHEVAIS").
dico("C", 7, "CHEVAIT").
dico("C", 7, "CHEVALA").
dico("C", 7, "CHEVALE").
dico("C", 7, "CHEVANT").
dico("C", 7, "CHEVAUX").
dico("C", 7, "CHEVEES").
dico("C", 7, "CHEVELU").
dico("C", 7, "CHEVENT").
dico("C", 7, "CHEVERA").
dico("C", 7, "CHEVETS").
dico("C", 7, "CHEVEUX").
dico("C", 7, "CHEVIEZ").
dico("C", 7, "CHEVONS").
dico("C", 7, "CHEVRER").
dico("C", 7, "CHEVRES").
dico("C", 7, "CHEVRON").
dico("C", 7, "CHIADAI").
dico("C", 7, "CHIADAS").
dico("C", 7, "CHIADAT").
dico("C", 7, "CHIADEE").
dico("C", 7, "CHIADER").
dico("C", 7, "CHIADES").
dico("C", 7, "CHIADEZ").
dico("C", 7, "CHIALAI").
dico("C", 7, "CHIALAS").
dico("C", 7, "CHIALAT").
dico("C", 7, "CHIALER").
dico("C", 7, "CHIALES").
dico("C", 7, "CHIALEZ").
dico("C", 7, "CHIAMES").
dico("C", 7, "CHIANTE").
dico("C", 7, "CHIANTI").
dico("C", 7, "CHIANTS").
dico("C", 7, "CHIARDS").
dico("C", 7, "CHIASMA").
dico("C", 7, "CHIASME").
dico("C", 7, "CHIASSE").
dico("C", 7, "CHIATES").
dico("C", 7, "CHIBOUK").
dico("C", 7, "CHIBRES").
dico("C", 7, "CHICANA").
dico("C", 7, "CHICANE").
dico("C", 7, "CHICANO").
dico("C", 7, "CHICHES").
dico("C", 7, "CHICHIS").
dico("C", 7, "CHICLES").
dico("C", 7, "CHICONS").
dico("C", 7, "CHICOTA").
dico("C", 7, "CHICOTE").
dico("C", 7, "CHICOTS").
dico("C", 7, "CHIENNE").
dico("C", 7, "CHIERAI").
dico("C", 7, "CHIERAS").
dico("C", 7, "CHIEREZ").
dico("C", 7, "CHIERIE").
dico("C", 7, "CHIEURS").
dico("C", 7, "CHIEUSE").
dico("C", 7, "CHIFFES").
dico("C", 7, "CHIFFON").
dico("C", 7, "CHIFFRA").
dico("C", 7, "CHIFFRE").
dico("C", 7, "CHIGNAI").
dico("C", 7, "CHIGNAS").
dico("C", 7, "CHIGNAT").
dico("C", 7, "CHIGNER").
dico("C", 7, "CHIGNES").
dico("C", 7, "CHIGNEZ").
dico("C", 7, "CHIGNON").
dico("C", 7, "CHIIONS").
dico("C", 7, "CHIISME").
dico("C", 7, "CHIITES").
dico("C", 7, "CHILIEN").
dico("C", 7, "CHILOMS").
dico("C", 7, "CHIMERE").
dico("C", 7, "CHIMIES").
dico("C", 7, "CHIMIOS").
dico("C", 7, "CHINAGE").
dico("C", 7, "CHINAIS").
dico("C", 7, "CHINAIT").
dico("C", 7, "CHINANT").
dico("C", 7, "CHINDAI").
dico("C", 7, "CHINDAS").
dico("C", 7, "CHINDAT").
dico("C", 7, "CHINDER").
dico("C", 7, "CHINDES").
dico("C", 7, "CHINDEZ").
dico("C", 7, "CHINEES").
dico("C", 7, "CHINENT").
dico("C", 7, "CHINERA").
dico("C", 7, "CHINEUR").
dico("C", 7, "CHINIEZ").
dico("C", 7, "CHINOIS").
dico("C", 7, "CHINONS").
dico("C", 7, "CHINOOK").
dico("C", 7, "CHINURE").
dico("C", 7, "CHIONIS").
dico("C", 7, "CHIOTTE").
dico("C", 7, "CHIPAGE").
dico("C", 7, "CHIPAIS").
dico("C", 7, "CHIPAIT").
dico("C", 7, "CHIPANT").
dico("C", 7, "CHIPEES").
dico("C", 7, "CHIPENT").
dico("C", 7, "CHIPERA").
dico("C", 7, "CHIPEUR").
dico("C", 7, "CHIPIES").
dico("C", 7, "CHIPIEZ").
dico("C", 7, "CHIPONS").
dico("C", 7, "CHIPOTA").
dico("C", 7, "CHIPOTE").
dico("C", 7, "CHIQUAI").
dico("C", 7, "CHIQUAS").
dico("C", 7, "CHIQUAT").
dico("C", 7, "CHIQUEE").
dico("C", 7, "CHIQUER").
dico("C", 7, "CHIQUES").
dico("C", 7, "CHIQUEZ").
dico("C", 7, "CHIRALE").
dico("C", 7, "CHIRAUX").
dico("C", 7, "CHISELS").
dico("C", 7, "CHITINE").
dico("C", 7, "CHITONS").
dico("C", 7, "CHIURES").
dico("C", 7, "CHLEUHE").
dico("C", 7, "CHLEUHS").
dico("C", 7, "CHLORAI").
dico("C", 7, "CHLORAL").
dico("C", 7, "CHLORAS").
dico("C", 7, "CHLORAT").
dico("C", 7, "CHLOREE").
dico("C", 7, "CHLORER").
dico("C", 7, "CHLORES").
dico("C", 7, "CHLOREZ").
dico("C", 7, "CHNOQUE").
dico("C", 7, "CHNOUFS").
dico("C", 7, "CHOANES").
dico("C", 7, "CHOCARD").
dico("C", 7, "CHOEURS").
dico("C", 7, "CHOIENT").
dico("C", 7, "CHOIERA").
dico("C", 7, "CHOIRAI").
dico("C", 7, "CHOIRAS").
dico("C", 7, "CHOIREZ").
dico("C", 7, "CHOISIE").
dico("C", 7, "CHOISIR").
dico("C", 7, "CHOISIS").
dico("C", 7, "CHOISIT").
dico("C", 7, "CHOLERA").
dico("C", 7, "CHOLINE").
dico("C", 7, "CHOMAGE").
dico("C", 7, "CHOMAIS").
dico("C", 7, "CHOMAIT").
dico("C", 7, "CHOMANT").
dico("C", 7, "CHOMEES").
dico("C", 7, "CHOMENT").
dico("C", 7, "CHOMERA").
dico("C", 7, "CHOMEUR").
dico("C", 7, "CHOMIEZ").
dico("C", 7, "CHOMONS").
dico("C", 7, "CHONDRE").
dico("C", 7, "CHOPAIS").
dico("C", 7, "CHOPAIT").
dico("C", 7, "CHOPANT").
dico("C", 7, "CHOPEES").
dico("C", 7, "CHOPENT").
dico("C", 7, "CHOPERA").
dico("C", 7, "CHOPIEZ").
dico("C", 7, "CHOPINA").
dico("C", 7, "CHOPINE").
dico("C", 7, "CHOPINS").
dico("C", 7, "CHOPONS").
dico("C", 7, "CHOPPAI").
dico("C", 7, "CHOPPAS").
dico("C", 7, "CHOPPAT").
dico("C", 7, "CHOPPER").
dico("C", 7, "CHOPPES").
dico("C", 7, "CHOPPEZ").
dico("C", 7, "CHOQUAI").
dico("C", 7, "CHOQUAS").
dico("C", 7, "CHOQUAT").
dico("C", 7, "CHOQUEE").
dico("C", 7, "CHOQUER").
dico("C", 7, "CHOQUES").
dico("C", 7, "CHOQUEZ").
dico("C", 7, "CHORALE").
dico("C", 7, "CHORALS").
dico("C", 7, "CHORAUX").
dico("C", 7, "CHORBAS").
dico("C", 7, "CHORDES").
dico("C", 7, "CHOREES").
dico("C", 7, "CHOREGE").
dico("C", 7, "CHORION").
dico("C", 7, "CHORIZO").
dico("C", 7, "CHORONS").
dico("C", 7, "CHORTEN").
dico("C", 7, "CHOTTES").
dico("C", 7, "CHOUANS").
dico("C", 7, "CHOUCAS").
dico("C", 7, "CHOUGNA").
dico("C", 7, "CHOUGNE").
dico("C", 7, "CHOUIAS").
dico("C", 7, "CHOUINA").
dico("C", 7, "CHOUINE").
dico("C", 7, "CHOUQUE").
dico("C", 7, "CHOURAI").
dico("C", 7, "CHOURAS").
dico("C", 7, "CHOURAT").
dico("C", 7, "CHOUREE").
dico("C", 7, "CHOURER").
dico("C", 7, "CHOURES").
dico("C", 7, "CHOUREZ").
dico("C", 7, "CHOURIN").
dico("C", 7, "CHOUTES").
dico("C", 7, "CHOYAIS").
dico("C", 7, "CHOYAIT").
dico("C", 7, "CHOYANT").
dico("C", 7, "CHOYEES").
dico("C", 7, "CHOYIEZ").
dico("C", 7, "CHOYONS").
dico("C", 7, "CHREMES").
dico("C", 7, "CHRISME").
dico("C", 7, "CHRISTS").
dico("C", 7, "CHROMAI").
dico("C", 7, "CHROMAS").
dico("C", 7, "CHROMAT").
dico("C", 7, "CHROMEE").
dico("C", 7, "CHROMER").
dico("C", 7, "CHROMES").
dico("C", 7, "CHROMEZ").
dico("C", 7, "CHROMOS").
dico("C", 7, "CHRONOS").
dico("C", 7, "CHRYSIS").
dico("C", 7, "CHTIMIS").
dico("C", 7, "CHUINTA").
dico("C", 7, "CHUINTE").
dico("C", 7, "CHURENT").
dico("C", 7, "CHUTAIS").
dico("C", 7, "CHUTAIT").
dico("C", 7, "CHUTANT").
dico("C", 7, "CHUTEES").
dico("C", 7, "CHUTENT").
dico("C", 7, "CHUTERA").
dico("C", 7, "CHUTEUR").
dico("C", 7, "CHUTIEZ").
dico("C", 7, "CHUTNEY").
dico("C", 7, "CHUTONS").
dico("C", 7, "CHYLEUX").
dico("C", 7, "CHYPREE").
dico("C", 7, "CHYPRES").
dico("C", 7, "CIBARES").
dico("C", 7, "CIBICHE").
dico("C", 7, "CIBISTE").
dico("C", 7, "CIBLAGE").
dico("C", 7, "CIBLAIS").
dico("C", 7, "CIBLAIT").
dico("C", 7, "CIBLANT").
dico("C", 7, "CIBLEES").
dico("C", 7, "CIBLENT").
dico("C", 7, "CIBLERA").
dico("C", 7, "CIBLIEZ").
dico("C", 7, "CIBLONS").
dico("C", 7, "CIBOIRE").
dico("C", 7, "CIBOULE").
dico("C", 7, "CICEROS").
dico("C", 7, "CICLAIS").
dico("C", 7, "CICLAIT").
dico("C", 7, "CICLANT").
dico("C", 7, "CICLEES").
dico("C", 7, "CICLENT").
dico("C", 7, "CICLERA").
dico("C", 7, "CICLIEZ").
dico("C", 7, "CICLONS").
dico("C", 7, "CIERGES").
dico("C", 7, "CIGALES").
dico("C", 7, "CIGARES").
dico("C", 7, "CIGOGNE").
dico("C", 7, "CILICES").
dico("C", 7, "CILIEES").
dico("C", 7, "CILLAIS").
dico("C", 7, "CILLAIT").
dico("C", 7, "CILLANT").
dico("C", 7, "CILLEES").
dico("C", 7, "CILLENT").
dico("C", 7, "CILLERA").
dico("C", 7, "CILLIEZ").
dico("C", 7, "CILLONS").
dico("C", 7, "CIMAISE").
dico("C", 7, "CIMENTA").
dico("C", 7, "CIMENTE").
dico("C", 7, "CIMENTS").
dico("C", 7, "CIMIERS").
dico("C", 7, "CINABRE").
dico("C", 7, "CINCLES").
dico("C", 7, "CINEMAS").
dico("C", 7, "CINESES").
dico("C", 7, "CINETIR").
dico("C", 7, "CINGLAI").
dico("C", 7, "CINGLAS").
dico("C", 7, "CINGLAT").
dico("C", 7, "CINGLEE").
dico("C", 7, "CINGLER").
dico("C", 7, "CINGLES").
dico("C", 7, "CINGLEZ").
dico("C", 7, "CINOCHE").
dico("C", 7, "CINOQUE").
dico("C", 7, "CINTRAI").
dico("C", 7, "CINTRAS").
dico("C", 7, "CINTRAT").
dico("C", 7, "CINTREE").
dico("C", 7, "CINTRER").
dico("C", 7, "CINTRES").
dico("C", 7, "CINTREZ").
dico("C", 7, "CIPALES").
dico("C", 7, "CIPAYES").
dico("C", 7, "CIPOLIN").
dico("C", 7, "CIRAGES").
dico("C", 7, "CIRAMES").
dico("C", 7, "CIRASSE").
dico("C", 7, "CIRATES").
dico("C", 7, "CIRCINE").
dico("C", 7, "CIRCUIT").
dico("C", 7, "CIRCULA").
dico("C", 7, "CIRCULE").
dico("C", 7, "CIRERAI").
dico("C", 7, "CIRERAS").
dico("C", 7, "CIREREZ").
dico("C", 7, "CIREURS").
dico("C", 7, "CIREUSE").
dico("C", 7, "CIRIERE").
dico("C", 7, "CIRIERS").
dico("C", 7, "CIRIONS").
dico("C", 7, "CIRONNE").
dico("C", 7, "CIRQUES").
dico("C", 7, "CIRRHES").
dico("C", 7, "CISEAUX").
dico("C", 7, "CISELAI").
dico("C", 7, "CISELAS").
dico("C", 7, "CISELAT").
dico("C", 7, "CISELEE").
dico("C", 7, "CISELER").
dico("C", 7, "CISELES").
dico("C", 7, "CISELET").
dico("C", 7, "CISELEZ").
dico("C", 7, "CISTRES").
dico("C", 7, "CISTRON").
dico("C", 7, "CISTUDE").
dico("C", 7, "CITADIN").
dico("C", 7, "CITAMES").
dico("C", 7, "CITASSE").
dico("C", 7, "CITATES").
dico("C", 7, "CITERAI").
dico("C", 7, "CITERAS").
dico("C", 7, "CITEREZ").
dico("C", 7, "CITERNE").
dico("C", 7, "CITHARE").
dico("C", 7, "CITIONS").
dico("C", 7, "CITOYEN").
dico("C", 7, "CITRATE").
dico("C", 7, "CITRINE").
dico("C", 7, "CITRINS").
dico("C", 7, "CITRONS").
dico("C", 7, "CIVAITE").
dico("C", 7, "CIVELLE").
dico("C", 7, "CIVETTE").
dico("C", 7, "CIVIERE").
dico("C", 7, "CIVILES").
dico("C", 7, "CIVIQUE").
dico("C", 7, "CIVISME").
dico("C", 7, "CLABAUD").
dico("C", 7, "CLABOTA").
dico("C", 7, "CLABOTE").
dico("C", 7, "CLABOTS").
dico("C", 7, "CLAIRES").
dico("C", 7, "CLAIRET").
dico("C", 7, "CLAIRON").
dico("C", 7, "CLAMAIS").
dico("C", 7, "CLAMAIT").
dico("C", 7, "CLAMANT").
dico("C", 7, "CLAMEAU").
dico("C", 7, "CLAMECA").
dico("C", 7, "CLAMECE").
dico("C", 7, "CLAMEES").
dico("C", 7, "CLAMENT").
dico("C", 7, "CLAMERA").
dico("C", 7, "CLAMEUR").
dico("C", 7, "CLAMIEZ").
dico("C", 7, "CLAMONS").
dico("C", 7, "CLAMPAI").
dico("C", 7, "CLAMPAS").
dico("C", 7, "CLAMPAT").
dico("C", 7, "CLAMPEE").
dico("C", 7, "CLAMPER").
dico("C", 7, "CLAMPES").
dico("C", 7, "CLAMPEZ").
dico("C", 7, "CLAMPIN").
dico("C", 7, "CLAMPSA").
dico("C", 7, "CLAMPSE").
dico("C", 7, "CLAMSAI").
dico("C", 7, "CLAMSAS").
dico("C", 7, "CLAMSAT").
dico("C", 7, "CLAMSER").
dico("C", 7, "CLAMSES").
dico("C", 7, "CLAMSEZ").
dico("C", 7, "CLANDES").
dico("C", 7, "CLANGOR").
dico("C", 7, "CLAPETS").
dico("C", 7, "CLAPIER").
dico("C", 7, "CLAPIES").
dico("C", 7, "CLAPIRA").
dico("C", 7, "CLAPMAN").
dico("C", 7, "CLAPOTA").
dico("C", 7, "CLAPOTE").
dico("C", 7, "CLAPOTS").
dico("C", 7, "CLAPPAI").
dico("C", 7, "CLAPPAS").
dico("C", 7, "CLAPPAT").
dico("C", 7, "CLAPPER").
dico("C", 7, "CLAPPES").
dico("C", 7, "CLAPPEZ").
dico("C", 7, "CLAQUAI").
dico("C", 7, "CLAQUAS").
dico("C", 7, "CLAQUAT").
dico("C", 7, "CLAQUEE").
dico("C", 7, "CLAQUER").
dico("C", 7, "CLAQUES").
dico("C", 7, "CLAQUET").
dico("C", 7, "CLAQUEZ").
dico("C", 7, "CLARAIN").
dico("C", 7, "CLARIAS").
dico("C", 7, "CLARINE").
dico("C", 7, "CLARTES").
dico("C", 7, "CLASHES").
dico("C", 7, "CLASSAI").
dico("C", 7, "CLASSAS").
dico("C", 7, "CLASSAT").
dico("C", 7, "CLASSEE").
dico("C", 7, "CLASSER").
dico("C", 7, "CLASSES").
dico("C", 7, "CLASSEZ").
dico("C", 7, "CLAUSES").
dico("C", 7, "CLAVAGE").
dico("C", 7, "CLAVAIS").
dico("C", 7, "CLAVAIT").
dico("C", 7, "CLAVANT").
dico("C", 7, "CLAVEAU").
dico("C", 7, "CLAVEES").
dico("C", 7, "CLAVELE").
dico("C", 7, "CLAVENT").
dico("C", 7, "CLAVERA").
dico("C", 7, "CLAVETA").
dico("C", 7, "CLAVETE").
dico("C", 7, "CLAVIER").
dico("C", 7, "CLAVIEZ").
dico("C", 7, "CLAVONS").
dico("C", 7, "CLAYERE").
dico("C", 7, "CLAYONS").
dico("C", 7, "CLEBARD").
dico("C", 7, "CLEDARS").
dico("C", 7, "CLEMENT").
dico("C", 7, "CLENCHE").
dico("C", 7, "CLEPHTE").
dico("C", 7, "CLERGES").
dico("C", 7, "CLERGIE").
dico("C", 7, "CLICHAI").
dico("C", 7, "CLICHAS").
dico("C", 7, "CLICHAT").
dico("C", 7, "CLICHEE").
dico("C", 7, "CLICHER").
dico("C", 7, "CLICHES").
dico("C", 7, "CLICHEZ").
dico("C", 7, "CLIENTE").
dico("C", 7, "CLIENTS").
dico("C", 7, "CLIGNAI").
dico("C", 7, "CLIGNAS").
dico("C", 7, "CLIGNAT").
dico("C", 7, "CLIGNEE").
dico("C", 7, "CLIGNER").
dico("C", 7, "CLIGNES").
dico("C", 7, "CLIGNEZ").
dico("C", 7, "CLIMATS").
dico("C", 7, "CLINFOC").
dico("C", 7, "CLINKER").
dico("C", 7, "CLIPART").
dico("C", 7, "CLIPPAI").
dico("C", 7, "CLIPPAS").
dico("C", 7, "CLIPPAT").
dico("C", 7, "CLIPPEE").
dico("C", 7, "CLIPPER").
dico("C", 7, "CLIPPES").
dico("C", 7, "CLIPPEZ").
dico("C", 7, "CLIPSAI").
dico("C", 7, "CLIPSAS").
dico("C", 7, "CLIPSAT").
dico("C", 7, "CLIPSEE").
dico("C", 7, "CLIPSER").
dico("C", 7, "CLIPSES").
dico("C", 7, "CLIPSEZ").
dico("C", 7, "CLIQUAI").
dico("C", 7, "CLIQUAS").
dico("C", 7, "CLIQUAT").
dico("C", 7, "CLIQUEE").
dico("C", 7, "CLIQUER").
dico("C", 7, "CLIQUES").
dico("C", 7, "CLIQUET").
dico("C", 7, "CLIQUEZ").
dico("C", 7, "CLISSAI").
dico("C", 7, "CLISSAS").
dico("C", 7, "CLISSAT").
dico("C", 7, "CLISSEE").
dico("C", 7, "CLISSER").
dico("C", 7, "CLISSES").
dico("C", 7, "CLISSEZ").
dico("C", 7, "CLIVAGE").
dico("C", 7, "CLIVAIS").
dico("C", 7, "CLIVAIT").
dico("C", 7, "CLIVANT").
dico("C", 7, "CLIVEES").
dico("C", 7, "CLIVENT").
dico("C", 7, "CLIVERA").
dico("C", 7, "CLIVIEZ").
dico("C", 7, "CLIVONS").
dico("C", 7, "CLOACAL").
dico("C", 7, "CLOAQUE").
dico("C", 7, "CLOCHAI").
dico("C", 7, "CLOCHAS").
dico("C", 7, "CLOCHAT").
dico("C", 7, "CLOCHEE").
dico("C", 7, "CLOCHER").
dico("C", 7, "CLOCHES").
dico("C", 7, "CLOCHEZ").
dico("C", 7, "CLOISON").
dico("C", 7, "CLOITRA").
dico("C", 7, "CLOITRE").
dico("C", 7, "CLONAGE").
dico("C", 7, "CLONAIS").
dico("C", 7, "CLONAIT").
dico("C", 7, "CLONANT").
dico("C", 7, "CLONEES").
dico("C", 7, "CLONENT").
dico("C", 7, "CLONERA").
dico("C", 7, "CLONIES").
dico("C", 7, "CLONIEZ").
dico("C", 7, "CLONONS").
dico("C", 7, "CLOPAIS").
dico("C", 7, "CLOPAIT").
dico("C", 7, "CLOPANT").
dico("C", 7, "CLOPEES").
dico("C", 7, "CLOPENT").
dico("C", 7, "CLOPERA").
dico("C", 7, "CLOPETS").
dico("C", 7, "CLOPIEZ").
dico("C", 7, "CLOPINA").
dico("C", 7, "CLOPINE").
dico("C", 7, "CLOPONS").
dico("C", 7, "CLOPPAI").
dico("C", 7, "CLOPPAS").
dico("C", 7, "CLOPPAT").
dico("C", 7, "CLOPPER").
dico("C", 7, "CLOPPES").
dico("C", 7, "CLOPPEZ").
dico("C", 7, "CLOQUAI").
dico("C", 7, "CLOQUAS").
dico("C", 7, "CLOQUAT").
dico("C", 7, "CLOQUEE").
dico("C", 7, "CLOQUER").
dico("C", 7, "CLOQUES").
dico("C", 7, "CLOQUEZ").
dico("C", 7, "CLORAIS").
dico("C", 7, "CLORAIT").
dico("C", 7, "CLORIEZ").
dico("C", 7, "CLORONS").
dico("C", 7, "CLORONT").
dico("C", 7, "CLOSANT").
dico("C", 7, "CLOSEAU").
dico("C", 7, "CLOSENT").
dico("C", 7, "CLOSIEZ").
dico("C", 7, "CLOSONS").
dico("C", 7, "CLOTURA").
dico("C", 7, "CLOTURE").
dico("C", 7, "CLOUAGE").
dico("C", 7, "CLOUAIS").
dico("C", 7, "CLOUAIT").
dico("C", 7, "CLOUANT").
dico("C", 7, "CLOUEES").
dico("C", 7, "CLOUENT").
dico("C", 7, "CLOUERA").
dico("C", 7, "CLOUIEZ").
dico("C", 7, "CLOUONS").
dico("C", 7, "CLOUTAI").
dico("C", 7, "CLOUTAS").
dico("C", 7, "CLOUTAT").
dico("C", 7, "CLOUTEE").
dico("C", 7, "CLOUTER").
dico("C", 7, "CLOUTES").
dico("C", 7, "CLOUTEZ").
dico("C", 7, "CLOYERE").
dico("C", 7, "CLUSTER").
dico("C", 7, "CNEMIDE").
dico("C", 7, "COACHAI").
dico("C", 7, "COACHAS").
dico("C", 7, "COACHAT").
dico("C", 7, "COACHEE").
dico("C", 7, "COACHER").
dico("C", 7, "COACHES").
dico("C", 7, "COACHEZ").
dico("C", 7, "COACTIF").
dico("C", 7, "COAGULA").
dico("C", 7, "COAGULE").
dico("C", 7, "COALISA").
dico("C", 7, "COALISE").
dico("C", 7, "COALTAR").
dico("C", 7, "COASSAI").
dico("C", 7, "COASSAS").
dico("C", 7, "COASSAT").
dico("C", 7, "COASSER").
dico("C", 7, "COASSES").
dico("C", 7, "COASSEZ").
dico("C", 7, "COAXIAL").
dico("C", 7, "COBAEAS").
dico("C", 7, "COBALTS").
dico("C", 7, "COBAYES").
dico("C", 7, "COBIERS").
dico("C", 7, "COCAGNE").
dico("C", 7, "COCAIER").
dico("C", 7, "COCAINE").
dico("C", 7, "COCARDE").
dico("C", 7, "COCASSE").
dico("C", 7, "COCHAIS").
dico("C", 7, "COCHAIT").
dico("C", 7, "COCHANT").
dico("C", 7, "COCHEES").
dico("C", 7, "COCHENT").
dico("C", 7, "COCHERA").
dico("C", 7, "COCHERE").
dico("C", 7, "COCHERS").
dico("C", 7, "COCHETS").
dico("C", 7, "COCHIEZ").
dico("C", 7, "COCHLEE").
dico("C", 7, "COCHONS").
dico("C", 7, "COCKERS").
dico("C", 7, "COCKNEY").
dico("C", 7, "COCKPIT").
dico("C", 7, "COCOLAI").
dico("C", 7, "COCOLAS").
dico("C", 7, "COCOLAT").
dico("C", 7, "COCOLEE").
dico("C", 7, "COCOLER").
dico("C", 7, "COCOLES").
dico("C", 7, "COCOLEZ").
dico("C", 7, "COCONNA").
dico("C", 7, "COCONNE").
dico("C", 7, "COCOONA").
dico("C", 7, "COCOONE").
dico("C", 7, "COCOONS").
dico("C", 7, "COCOTAI").
dico("C", 7, "COCOTAS").
dico("C", 7, "COCOTAT").
dico("C", 7, "COCOTER").
dico("C", 7, "COCOTES").
dico("C", 7, "COCOTEZ").
dico("C", 7, "COCOTTA").
dico("C", 7, "COCOTTE").
dico("C", 7, "COCTION").
dico("C", 7, "COCUAGE").
dico("C", 7, "COCUFIA").
dico("C", 7, "COCUFIE").
dico("C", 7, "CODAGES").
dico("C", 7, "CODAMES").
dico("C", 7, "CODANTE").
dico("C", 7, "CODANTS").
dico("C", 7, "CODASSE").
dico("C", 7, "CODATES").
dico("C", 7, "CODEINE").
dico("C", 7, "CODERAI").
dico("C", 7, "CODERAS").
dico("C", 7, "CODEREZ").
dico("C", 7, "CODEURS").
dico("C", 7, "CODEUSE").
dico("C", 7, "CODIFIA").
dico("C", 7, "CODIFIE").
dico("C", 7, "CODIONS").
dico("C", 7, "COEDITA").
dico("C", 7, "COEDITE").
dico("C", 7, "COELOME").
dico("C", 7, "COENURE").
dico("C", 7, "COFFINS").
dico("C", 7, "COFFRAI").
dico("C", 7, "COFFRAS").
dico("C", 7, "COFFRAT").
dico("C", 7, "COFFREE").
dico("C", 7, "COFFRER").
dico("C", 7, "COFFRES").
dico("C", 7, "COFFRET").
dico("C", 7, "COFFREZ").
dico("C", 7, "COGERAI").
dico("C", 7, "COGERAS").
dico("C", 7, "COGERAT").
dico("C", 7, "COGEREE").
dico("C", 7, "COGERER").
dico("C", 7, "COGERES").
dico("C", 7, "COGEREZ").
dico("C", 7, "COGITAI").
dico("C", 7, "COGITAS").
dico("C", 7, "COGITAT").
dico("C", 7, "COGITEE").
dico("C", 7, "COGITER").
dico("C", 7, "COGITES").
dico("C", 7, "COGITEZ").
dico("C", 7, "COGNACS").
dico("C", 7, "COGNAIS").
dico("C", 7, "COGNAIT").
dico("C", 7, "COGNANT").
dico("C", 7, "COGNATS").
dico("C", 7, "COGNEES").
dico("C", 7, "COGNENT").
dico("C", 7, "COGNERA").
dico("C", 7, "COGNEUR").
dico("C", 7, "COGNIEZ").
dico("C", 7, "COGNONS").
dico("C", 7, "COHESIF").
dico("C", 7, "COHOBAI").
dico("C", 7, "COHOBAS").
dico("C", 7, "COHOBAT").
dico("C", 7, "COHOBEE").
dico("C", 7, "COHOBER").
dico("C", 7, "COHOBES").
dico("C", 7, "COHOBEZ").
dico("C", 7, "COHORTE").
dico("C", 7, "COIFFAI").
dico("C", 7, "COIFFAS").
dico("C", 7, "COIFFAT").
dico("C", 7, "COIFFEE").
dico("C", 7, "COIFFER").
dico("C", 7, "COIFFES").
dico("C", 7, "COIFFEZ").
dico("C", 7, "COINCAI").
dico("C", 7, "COINCAS").
dico("C", 7, "COINCAT").
dico("C", 7, "COINCEE").
dico("C", 7, "COINCER").
dico("C", 7, "COINCES").
dico("C", 7, "COINCEZ").
dico("C", 7, "COINCHA").
dico("C", 7, "COINCHE").
dico("C", 7, "COITAIS").
dico("C", 7, "COITAIT").
dico("C", 7, "COITANT").
dico("C", 7, "COITENT").
dico("C", 7, "COITERA").
dico("C", 7, "COITIEZ").
dico("C", 7, "COITONS").
dico("C", 7, "COITRON").
dico("C", 7, "COITTES").
dico("C", 7, "COKAGES").
dico("C", 7, "COKEFIA").
dico("C", 7, "COKEFIE").
dico("C", 7, "COKERIE").
dico("C", 7, "COKEURS").
dico("C", 7, "COKINGS").
dico("C", 7, "COLBACK").
dico("C", 7, "COLERES").
dico("C", 7, "COLIBRI").
dico("C", 7, "COLINOT").
dico("C", 7, "COLIQUE").
dico("C", 7, "COLITES").
dico("C", 7, "COLLABO").
dico("C", 7, "COLLAGE").
dico("C", 7, "COLLAIS").
dico("C", 7, "COLLAIT").
dico("C", 7, "COLLANT").
dico("C", 7, "COLLEES").
dico("C", 7, "COLLEGE").
dico("C", 7, "COLLENT").
dico("C", 7, "COLLERA").
dico("C", 7, "COLLETA").
dico("C", 7, "COLLETE").
dico("C", 7, "COLLETS").
dico("C", 7, "COLLEUR").
dico("C", 7, "COLLEYS").
dico("C", 7, "COLLIER").
dico("C", 7, "COLLIEZ").
dico("C", 7, "COLLIGE").
dico("C", 7, "COLLINE").
dico("C", 7, "COLLONS").
dico("C", 7, "COLLURE").
dico("C", 7, "COLLYRE").
dico("C", 7, "COLMATA").
dico("C", 7, "COLMATE").
dico("C", 7, "COLOBES").
dico("C", 7, "COLOMBE").
dico("C", 7, "COLOMBO").
dico("C", 7, "COLONAT").
dico("C", 7, "COLONEL").
dico("C", 7, "COLONES").
dico("C", 7, "COLONIE").
dico("C", 7, "COLONNE").
dico("C", 7, "COLORAI").
dico("C", 7, "COLORAS").
dico("C", 7, "COLORAT").
dico("C", 7, "COLOREE").
dico("C", 7, "COLORER").
dico("C", 7, "COLORES").
dico("C", 7, "COLOREZ").
dico("C", 7, "COLORIA").
dico("C", 7, "COLORIE").
dico("C", 7, "COLORIS").
dico("C", 7, "COLOSSE").
dico("C", 7, "COLTINA").
dico("C", 7, "COLTINE").
dico("C", 7, "COLTINS").
dico("C", 7, "COLURES").
dico("C", 7, "COLVERT").
dico("C", 7, "COMBATS").
dico("C", 7, "COMBAVA").
dico("C", 7, "COMBIEN").
dico("C", 7, "COMBINA").
dico("C", 7, "COMBINE").
dico("C", 7, "COMBLAI").
dico("C", 7, "COMBLAS").
dico("C", 7, "COMBLAT").
dico("C", 7, "COMBLEE").
dico("C", 7, "COMBLER").
dico("C", 7, "COMBLES").
dico("C", 7, "COMBLEZ").
dico("C", 7, "COMEDIE").
dico("C", 7, "COMEDON").
dico("C", 7, "COMETES").
dico("C", 7, "COMICES").
dico("C", 7, "COMIQUE").
dico("C", 7, "COMITAT").
dico("C", 7, "COMITES").
dico("C", 7, "COMMAND").
dico("C", 7, "COMMENT").
dico("C", 7, "COMMERA").
dico("C", 7, "COMMERE").
dico("C", 7, "COMMETS").
dico("C", 7, "COMMISE").
dico("C", 7, "COMMODE").
dico("C", 7, "COMMUAI").
dico("C", 7, "COMMUAS").
dico("C", 7, "COMMUAT").
dico("C", 7, "COMMUEE").
dico("C", 7, "COMMUER").
dico("C", 7, "COMMUES").
dico("C", 7, "COMMUEZ").
dico("C", 7, "COMMUNE").
dico("C", 7, "COMMUNS").
dico("C", 7, "COMMUTA").
dico("C", 7, "COMMUTE").
dico("C", 7, "COMPACT").
dico("C", 7, "COMPARA").
dico("C", 7, "COMPARE").
dico("C", 7, "COMPARU").
dico("C", 7, "COMPATI").
dico("C", 7, "COMPERE").
dico("C", 7, "COMPETA").
dico("C", 7, "COMPETE").
dico("C", 7, "COMPILA").
dico("C", 7, "COMPILE").
dico("C", 7, "COMPILS").
dico("C", 7, "COMPLET").
dico("C", 7, "COMPLOT").
dico("C", 7, "COMPLUS").
dico("C", 7, "COMPLUT").
dico("C", 7, "COMPONE").
dico("C", 7, "COMPONS").
dico("C", 7, "COMPOSA").
dico("C", 7, "COMPOSE").
dico("C", 7, "COMPOST").
dico("C", 7, "COMPOTE").
dico("C", 7, "COMPRIS").
dico("C", 7, "COMPRIT").
dico("C", 7, "COMPTAI").
dico("C", 7, "COMPTAS").
dico("C", 7, "COMPTAT").
dico("C", 7, "COMPTEE").
dico("C", 7, "COMPTER").
dico("C", 7, "COMPTES").
dico("C", 7, "COMPTEZ").
dico("C", 7, "COMPUTS").
dico("C", 7, "COMTALE").
dico("C", 7, "COMTATS").
dico("C", 7, "COMTAUX").
dico("C", 7, "COMTOIS").
dico("C", 7, "CONARDE").
dico("C", 7, "CONARDS").
dico("C", 7, "CONASSE").
dico("C", 7, "CONATIF").
dico("C", 7, "CONATUS").
dico("C", 7, "CONCAVE").
dico("C", 7, "CONCEDA").
dico("C", 7, "CONCEDE").
dico("C", 7, "CONCEPT").
dico("C", 7, "CONCERT").
dico("C", 7, "CONCHIA").
dico("C", 7, "CONCHIE").
dico("C", 7, "CONCILE").
dico("C", 7, "CONCISE").
dico("C", 7, "CONCLUE").
dico("C", 7, "CONCLUS").
dico("C", 7, "CONCLUT").
dico("C", 7, "CONCOIS").
dico("C", 7, "CONCOIT").
dico("C", 7, "CONCRET").
dico("C", 7, "CONCUES").
dico("C", 7, "CONDOMS").
dico("C", 7, "CONDORS").
dico("C", 7, "CONDUIS").
dico("C", 7, "CONDUIT").
dico("C", 7, "CONDYLE").
dico("C", 7, "CONFERA").
dico("C", 7, "CONFERE").
dico("C", 7, "CONFIAI").
dico("C", 7, "CONFIAS").
dico("C", 7, "CONFIAT").
dico("C", 7, "CONFIEE").
dico("C", 7, "CONFIER").
dico("C", 7, "CONFIES").
dico("C", 7, "CONFIEZ").
dico("C", 7, "CONFINA").
dico("C", 7, "CONFINE").
dico("C", 7, "CONFINS").
dico("C", 7, "CONFIRA").
dico("C", 7, "CONFIRE").
dico("C", 7, "CONFISE").
dico("C", 7, "CONFITE").
dico("C", 7, "CONFITS").
dico("C", 7, "CONFLIT").
dico("C", 7, "CONFLUA").
dico("C", 7, "CONFLUE").
dico("C", 7, "CONFOND").
dico("C", 7, "CONFORT").
dico("C", 7, "CONFUSE").
dico("C", 7, "CONGAIS").
dico("C", 7, "CONGAYE").
dico("C", 7, "CONGELA").
dico("C", 7, "CONGELE").
dico("C", 7, "CONGERE").
dico("C", 7, "CONGREA").
dico("C", 7, "CONGREE").
dico("C", 7, "CONGRES").
dico("C", 7, "CONGRUE").
dico("C", 7, "CONGRUS").
dico("C", 7, "CONIDIE").
dico("C", 7, "CONIQUE").
dico("C", 7, "CONJURA").
dico("C", 7, "CONJURE").
dico("C", 7, "CONNAIS").
dico("C", 7, "CONNAIT").
dico("C", 7, "CONNARD").
dico("C", 7, "CONNEAU").
dico("C", 7, "CONNEXE").
dico("C", 7, "CONNOTA").
dico("C", 7, "CONNOTE").
dico("C", 7, "CONNUES").
dico("C", 7, "CONOIDE").
dico("C", 7, "CONOPEE").
dico("C", 7, "CONQUES").
dico("C", 7, "CONQUET").
dico("C", 7, "CONQUIS").
dico("C", 7, "CONQUIT").
dico("C", 7, "CONSEIL").
dico("C", 7, "CONSENS").
dico("C", 7, "CONSENT").
dico("C", 7, "CONSOLA").
dico("C", 7, "CONSOLE").
dico("C", 7, "CONSOLS").
dico("C", 7, "CONSONA").
dico("C", 7, "CONSONE").
dico("C", 7, "CONSORT").
dico("C", 7, "CONSPUA").
dico("C", 7, "CONSPUE").
dico("C", 7, "CONSTAT").
dico("C", 7, "CONSULS").
dico("C", 7, "CONSUMA").
dico("C", 7, "CONSUME").
dico("C", 7, "CONTACT").
dico("C", 7, "CONTAGE").
dico("C", 7, "CONTAIS").
dico("C", 7, "CONTAIT").
dico("C", 7, "CONTANT").
dico("C", 7, "CONTEES").
dico("C", 7, "CONTENT").
dico("C", 7, "CONTENU").
dico("C", 7, "CONTERA").
dico("C", 7, "CONTEUR").
dico("C", 7, "CONTIEZ").
dico("C", 7, "CONTIGU").
dico("C", 7, "CONTINS").
dico("C", 7, "CONTINT").
dico("C", 7, "CONTINU").
dico("C", 7, "CONTONS").
dico("C", 7, "CONTOUR").
dico("C", 7, "CONTRAI").
dico("C", 7, "CONTRAS").
dico("C", 7, "CONTRAT").
dico("C", 7, "CONTREE").
dico("C", 7, "CONTRER").
dico("C", 7, "CONTRES").
dico("C", 7, "CONTREZ").
dico("C", 7, "CONTRIT").
dico("C", 7, "CONTUSE").
dico("C", 7, "CONVENT").
dico("C", 7, "CONVENU").
dico("C", 7, "CONVERS").
dico("C", 7, "CONVEXE").
dico("C", 7, "CONVIAI").
dico("C", 7, "CONVIAS").
dico("C", 7, "CONVIAT").
dico("C", 7, "CONVICT").
dico("C", 7, "CONVIEE").
dico("C", 7, "CONVIER").
dico("C", 7, "CONVIES").
dico("C", 7, "CONVIEZ").
dico("C", 7, "CONVINS").
dico("C", 7, "CONVINT").
dico("C", 7, "CONVIVE").
dico("C", 7, "CONVOIE").
dico("C", 7, "CONVOIS").
dico("C", 7, "CONVOLA").
dico("C", 7, "CONVOLE").
dico("C", 7, "CONVOYA").
dico("C", 7, "CONVOYE").
dico("C", 7, "COOKIES").
dico("C", 7, "COOLIES").
dico("C", 7, "COOPERA").
dico("C", 7, "COOPERE").
dico("C", 7, "COOPTAI").
dico("C", 7, "COOPTAS").
dico("C", 7, "COOPTAT").
dico("C", 7, "COOPTEE").
dico("C", 7, "COOPTER").
dico("C", 7, "COOPTES").
dico("C", 7, "COOPTEZ").
dico("C", 7, "COPAHUS").
dico("C", 7, "COPAIER").
dico("C", 7, "COPAINS").
dico("C", 7, "COPAYER").
dico("C", 7, "COPEAUX").
dico("C", 7, "COPIAGE").
dico("C", 7, "COPIAIS").
dico("C", 7, "COPIAIT").
dico("C", 7, "COPIANT").
dico("C", 7, "COPIEES").
dico("C", 7, "COPIENT").
dico("C", 7, "COPIERA").
dico("C", 7, "COPIEUR").
dico("C", 7, "COPIEUX").
dico("C", 7, "COPIIEZ").
dico("C", 7, "COPINAI").
dico("C", 7, "COPINAS").
dico("C", 7, "COPINAT").
dico("C", 7, "COPINER").
dico("C", 7, "COPINES").
dico("C", 7, "COPINEZ").
dico("C", 7, "COPINGS").
dico("C", 7, "COPIONS").
dico("C", 7, "COPISTE").
dico("C", 7, "COPRAHS").
dico("C", 7, "COPRINS").
dico("C", 7, "COPSAGE").
dico("C", 7, "COPULAI").
dico("C", 7, "COPULAS").
dico("C", 7, "COPULAT").
dico("C", 7, "COPULER").
dico("C", 7, "COPULES").
dico("C", 7, "COPULEZ").
dico("C", 7, "COQUARD").
dico("C", 7, "COQUART").
dico("C", 7, "COQUETA").
dico("C", 7, "COQUETE").
dico("C", 7, "COQUETS").
dico("C", 7, "COQUINE").
dico("C", 7, "COQUINS").
dico("C", 7, "CORBEAU").
dico("C", 7, "CORBINS").
dico("C", 7, "CORBLEU").
dico("C", 7, "CORDAGE").
dico("C", 7, "CORDAIS").
dico("C", 7, "CORDAIT").
dico("C", 7, "CORDANT").
dico("C", 7, "CORDATS").
dico("C", 7, "CORDEAU").
dico("C", 7, "CORDEES").
dico("C", 7, "CORDELA").
dico("C", 7, "CORDELE").
dico("C", 7, "CORDENT").
dico("C", 7, "CORDERA").
dico("C", 7, "CORDEUR").
dico("C", 7, "CORDIAL").
dico("C", 7, "CORDIER").
dico("C", 7, "CORDIEZ").
dico("C", 7, "CORDITE").
dico("C", 7, "CORDOBA").
dico("C", 7, "CORDONS").
dico("C", 7, "COREENS").
dico("C", 7, "CORIACE").
dico("C", 7, "CORMIER").
dico("C", 7, "CORNACS").
dico("C", 7, "CORNAGE").
dico("C", 7, "CORNAIS").
dico("C", 7, "CORNAIT").
dico("C", 7, "CORNANT").
dico("C", 7, "CORNARD").
dico("C", 7, "CORNEEN").
dico("C", 7, "CORNEES").
dico("C", 7, "CORNENT").
dico("C", 7, "CORNERA").
dico("C", 7, "CORNERS").
dico("C", 7, "CORNETS").
dico("C", 7, "CORNEUR").
dico("C", 7, "CORNIER").
dico("C", 7, "CORNIEZ").
dico("C", 7, "CORNIOT").
dico("C", 7, "CORNONS").
dico("C", 7, "CORNUES").
dico("C", 7, "COROLLE").
dico("C", 7, "CORONAL").
dico("C", 7, "CORONER").
dico("C", 7, "COROZOS").
dico("C", 7, "CORRALS").
dico("C", 7, "CORRECT").
dico("C", 7, "CORRELA").
dico("C", 7, "CORRELE").
dico("C", 7, "CORRIDA").
dico("C", 7, "CORRIGE").
dico("C", 7, "CORRODA").
dico("C", 7, "CORRODE").
dico("C", 7, "CORROIE").
dico("C", 7, "CORROIS").
dico("C", 7, "CORROYA").
dico("C", 7, "CORROYE").
dico("C", 7, "CORSAGE").
dico("C", 7, "CORSAIS").
dico("C", 7, "CORSAIT").
dico("C", 7, "CORSANT").
dico("C", 7, "CORSEES").
dico("C", 7, "CORSENT").
dico("C", 7, "CORSERA").
dico("C", 7, "CORSETA").
dico("C", 7, "CORSETE").
dico("C", 7, "CORSETS").
dico("C", 7, "CORSIEZ").
dico("C", 7, "CORSONS").
dico("C", 7, "CORTEGE").
dico("C", 7, "CORTINE").
dico("C", 7, "CORTONS").
dico("C", 7, "CORVEES").
dico("C", 7, "CORVIDE").
dico("C", 7, "CORYMBE").
dico("C", 7, "CORYZAS").
dico("C", 7, "COSAQUE").
dico("C", 7, "COSIGNA").
dico("C", 7, "COSIGNE").
dico("C", 7, "COSINUS").
dico("C", 7, "COSSAIS").
dico("C", 7, "COSSAIT").
dico("C", 7, "COSSANT").
dico("C", 7, "COSSARD").
dico("C", 7, "COSSENT").
dico("C", 7, "COSSERA").
dico("C", 7, "COSSIEZ").
dico("C", 7, "COSSONS").
dico("C", 7, "COSSUES").
dico("C", 7, "COSTALE").
dico("C", 7, "COSTARD").
dico("C", 7, "COSTARS").
dico("C", 7, "COSTAUD").
dico("C", 7, "COSTAUX").
dico("C", 7, "COSTEAU").
dico("C", 7, "COSTUMA").
dico("C", 7, "COSTUME").
dico("C", 7, "COTABLE").
dico("C", 7, "COTAMES").
dico("C", 7, "COTASSE").
dico("C", 7, "COTATES").
dico("C", 7, "COTEAUX").
dico("C", 7, "COTELEE").
dico("C", 7, "COTELES").
dico("C", 7, "COTERAI").
dico("C", 7, "COTERAS").
dico("C", 7, "COTEREZ").
dico("C", 7, "COTERIE").
dico("C", 7, "COTEURS").
dico("C", 7, "COTICES").
dico("C", 7, "COTIDAL").
dico("C", 7, "COTIERE").
dico("C", 7, "COTIERS").
dico("C", 7, "COTIMES").
dico("C", 7, "COTINGA").
dico("C", 7, "COTIONS").
dico("C", 7, "COTIRAI").
dico("C", 7, "COTIRAS").
dico("C", 7, "COTIREZ").
dico("C", 7, "COTISAI").
dico("C", 7, "COTISAS").
dico("C", 7, "COTISAT").
dico("C", 7, "COTISEE").
dico("C", 7, "COTISER").
dico("C", 7, "COTISES").
dico("C", 7, "COTISEZ").
dico("C", 7, "COTISSE").
dico("C", 7, "COTITES").
dico("C", 7, "COTOIES").
dico("C", 7, "COTONNA").
dico("C", 7, "COTONNE").
dico("C", 7, "COTOYAI").
dico("C", 7, "COTOYAS").
dico("C", 7, "COTOYAT").
dico("C", 7, "COTOYEE").
dico("C", 7, "COTOYER").
dico("C", 7, "COTOYES").
dico("C", 7, "COTOYEZ").
dico("C", 7, "COTRETS").
dico("C", 7, "COTTAGE").
dico("C", 7, "COTTAIS").
dico("C", 7, "COTTAIT").
dico("C", 7, "COTTANT").
dico("C", 7, "COTTEES").
dico("C", 7, "COTTENT").
dico("C", 7, "COTTERA").
dico("C", 7, "COTTIDE").
dico("C", 7, "COTTIEZ").
dico("C", 7, "COTTONS").
dico("C", 7, "COTYLES").
dico("C", 7, "COUARDE").
dico("C", 7, "COUARDS").
dico("C", 7, "COUCHAI").
dico("C", 7, "COUCHAS").
dico("C", 7, "COUCHAT").
dico("C", 7, "COUCHEE").
dico("C", 7, "COUCHER").
dico("C", 7, "COUCHES").
dico("C", 7, "COUCHEZ").
dico("C", 7, "COUCHIS").
dico("C", 7, "COUCOUS").
dico("C", 7, "COUDAGE").
dico("C", 7, "COUDAIS").
dico("C", 7, "COUDAIT").
dico("C", 7, "COUDANT").
dico("C", 7, "COUDEES").
dico("C", 7, "COUDENT").
dico("C", 7, "COUDERA").
dico("C", 7, "COUDIEZ").
dico("C", 7, "COUDOIE").
dico("C", 7, "COUDONS").
dico("C", 7, "COUDOYA").
dico("C", 7, "COUDOYE").
dico("C", 7, "COUDRAI").
dico("C", 7, "COUDRAS").
dico("C", 7, "COUDRES").
dico("C", 7, "COUDREZ").
dico("C", 7, "COUENNE").
dico("C", 7, "COUETTE").
dico("C", 7, "COUFFAS").
dico("C", 7, "COUFFES").
dico("C", 7, "COUFFIN").
dico("C", 7, "COUGNOU").
dico("C", 7, "COUGUAR").
dico("C", 7, "COUILLE").
dico("C", 7, "COUILLU").
dico("C", 7, "COUINAI").
dico("C", 7, "COUINAS").
dico("C", 7, "COUINAT").
dico("C", 7, "COUINER").
dico("C", 7, "COUINES").
dico("C", 7, "COUINEZ").
dico("C", 7, "COULAGE").
dico("C", 7, "COULAIS").
dico("C", 7, "COULAIT").
dico("C", 7, "COULANT").
dico("C", 7, "COULEES").
dico("C", 7, "COULENT").
dico("C", 7, "COULERA").
dico("C", 7, "COULEUR").
dico("C", 7, "COULIEZ").
dico("C", 7, "COULOIR").
dico("C", 7, "COULOMB").
dico("C", 7, "COULONS").
dico("C", 7, "COULPES").
dico("C", 7, "COULURE").
dico("C", 7, "COUNTRY").
dico("C", 7, "COUPAGE").
dico("C", 7, "COUPAIS").
dico("C", 7, "COUPAIT").
dico("C", 7, "COUPANT").
dico("C", 7, "COUPEES").
dico("C", 7, "COUPENT").
dico("C", 7, "COUPERA").
dico("C", 7, "COUPEUR").
dico("C", 7, "COUPIEZ").
dico("C", 7, "COUPLAI").
dico("C", 7, "COUPLAS").
dico("C", 7, "COUPLAT").
dico("C", 7, "COUPLEE").
dico("C", 7, "COUPLER").
dico("C", 7, "COUPLES").
dico("C", 7, "COUPLET").
dico("C", 7, "COUPLEZ").
dico("C", 7, "COUPOIR").
dico("C", 7, "COUPOLE").
dico("C", 7, "COUPONS").
dico("C", 7, "COUPURE").
dico("C", 7, "COUQUES").
dico("C", 7, "COURAGE").
dico("C", 7, "COURAIS").
dico("C", 7, "COURAIT").
dico("C", 7, "COURANT").
dico("C", 7, "COURATA").
dico("C", 7, "COURATE").
dico("C", 7, "COURBAI").
dico("C", 7, "COURBAS").
dico("C", 7, "COURBAT").
dico("C", 7, "COURBEE").
dico("C", 7, "COURBER").
dico("C", 7, "COURBES").
dico("C", 7, "COURBEZ").
dico("C", 7, "COURCON").
dico("C", 7, "COUREES").
dico("C", 7, "COURENT").
dico("C", 7, "COUREUR").
dico("C", 7, "COURGES").
dico("C", 7, "COURIEZ").
dico("C", 7, "COURLAN").
dico("C", 7, "COURLIS").
dico("C", 7, "COURONS").
dico("C", 7, "COURRAI").
dico("C", 7, "COURRAS").
dico("C", 7, "COURREZ").
dico("C", 7, "COURSAI").
dico("C", 7, "COURSAS").
dico("C", 7, "COURSAT").
dico("C", 7, "COURSEE").
dico("C", 7, "COURSER").
dico("C", 7, "COURSES").
dico("C", 7, "COURSEZ").
dico("C", 7, "COURSIE").
dico("C", 7, "COURSON").
dico("C", 7, "COURTES").
dico("C", 7, "COURTIL").
dico("C", 7, "COURUES").
dico("C", 7, "COUSAIS").
dico("C", 7, "COUSAIT").
dico("C", 7, "COUSANT").
dico("C", 7, "COUSENT").
dico("C", 7, "COUSEUR").
dico("C", 7, "COUSIEZ").
dico("C", 7, "COUSINA").
dico("C", 7, "COUSINE").
dico("C", 7, "COUSINS").
dico("C", 7, "COUSOIR").
dico("C", 7, "COUSONS").
dico("C", 7, "COUSSIN").
dico("C", 7, "COUSUES").
dico("C", 7, "COUTAIS").
dico("C", 7, "COUTAIT").
dico("C", 7, "COUTANT").
dico("C", 7, "COUTEAU").
dico("C", 7, "COUTEES").
dico("C", 7, "COUTENT").
dico("C", 7, "COUTERA").
dico("C", 7, "COUTEUX").
dico("C", 7, "COUTIEZ").
dico("C", 7, "COUTILS").
dico("C", 7, "COUTONS").
dico("C", 7, "COUTRES").
dico("C", 7, "COUTUME").
dico("C", 7, "COUTURA").
dico("C", 7, "COUTURE").
dico("C", 7, "COUVADE").
dico("C", 7, "COUVAIN").
dico("C", 7, "COUVAIS").
dico("C", 7, "COUVAIT").
dico("C", 7, "COUVANT").
dico("C", 7, "COUVEES").
dico("C", 7, "COUVENT").
dico("C", 7, "COUVERA").
dico("C", 7, "COUVERT").
dico("C", 7, "COUVIEZ").
dico("C", 7, "COUVOIR").
dico("C", 7, "COUVONS").
dico("C", 7, "COUVRES").
dico("C", 7, "COUVREZ").
dico("C", 7, "COUVRIR").
dico("C", 7, "COUVRIS").
dico("C", 7, "COUVRIT").
dico("C", 7, "COUYONS").
dico("C", 7, "COWPERS").
dico("C", 7, "COXALES").
dico("C", 7, "COYOTES").
dico("C", 7, "CRABIER").
dico("C", 7, "CRABOTA").
dico("C", 7, "CRABOTE").
dico("C", 7, "CRABOTS").
dico("C", 7, "CRACHAI").
dico("C", 7, "CRACHAS").
dico("C", 7, "CRACHAT").
dico("C", 7, "CRACHEE").
dico("C", 7, "CRACHER").
dico("C", 7, "CRACHES").
dico("C", 7, "CRACHEZ").
dico("C", 7, "CRACHIN").
dico("C", 7, "CRACKER").
dico("C", 7, "CRADOTS").
dico("C", 7, "CRAIGNE").
dico("C", 7, "CRAILLA").
dico("C", 7, "CRAILLE").
dico("C", 7, "CRAINTE").
dico("C", 7, "CRAINTS").
dico("C", 7, "CRAMAIS").
dico("C", 7, "CRAMAIT").
dico("C", 7, "CRAMANT").
dico("C", 7, "CRAMBES").
dico("C", 7, "CRAMEES").
dico("C", 7, "CRAMENT").
dico("C", 7, "CRAMERA").
dico("C", 7, "CRAMIEZ").
dico("C", 7, "CRAMINE").
dico("C", 7, "CRAMONS").
dico("C", 7, "CRAMPAI").
dico("C", 7, "CRAMPAS").
dico("C", 7, "CRAMPAT").
dico("C", 7, "CRAMPEE").
dico("C", 7, "CRAMPER").
dico("C", 7, "CRAMPES").
dico("C", 7, "CRAMPEZ").
dico("C", 7, "CRAMPON").
dico("C", 7, "CRANAIS").
dico("C", 7, "CRANAIT").
dico("C", 7, "CRANANT").
dico("C", 7, "CRANEES").
dico("C", 7, "CRANENT").
dico("C", 7, "CRANERA").
dico("C", 7, "CRANEUR").
dico("C", 7, "CRANIEN").
dico("C", 7, "CRANIEZ").
dico("C", 7, "CRANONS").
dico("C", 7, "CRANSON").
dico("C", 7, "CRANTAI").
dico("C", 7, "CRANTAS").
dico("C", 7, "CRANTAT").
dico("C", 7, "CRANTEE").
dico("C", 7, "CRANTER").
dico("C", 7, "CRANTES").
dico("C", 7, "CRANTEZ").
dico("C", 7, "CRAPAUD").
dico("C", 7, "CRAPETS").
dico("C", 7, "CRAPOTA").
dico("C", 7, "CRAPOTE").
dico("C", 7, "CRAPULE").
dico("C", 7, "CRAQUAI").
dico("C", 7, "CRAQUAS").
dico("C", 7, "CRAQUAT").
dico("C", 7, "CRAQUEE").
dico("C", 7, "CRAQUER").
dico("C", 7, "CRAQUES").
dico("C", 7, "CRAQUEZ").
dico("C", 7, "CRASHAI").
dico("C", 7, "CRASHAS").
dico("C", 7, "CRASHAT").
dico("C", 7, "CRASHEE").
dico("C", 7, "CRASHER").
dico("C", 7, "CRASHES").
dico("C", 7, "CRASHEZ").
dico("C", 7, "CRASPEC").
dico("C", 7, "CRASSAI").
dico("C", 7, "CRASSAS").
dico("C", 7, "CRASSAT").
dico("C", 7, "CRASSEE").
dico("C", 7, "CRASSER").
dico("C", 7, "CRASSES").
dico("C", 7, "CRASSEZ").
dico("C", 7, "CRATERE").
dico("C", 7, "CRATONS").
dico("C", 7, "CRAVATA").
dico("C", 7, "CRAVATE").
dico("C", 7, "CRAWLAI").
dico("C", 7, "CRAWLAS").
dico("C", 7, "CRAWLAT").
dico("C", 7, "CRAWLEE").
dico("C", 7, "CRAWLER").
dico("C", 7, "CRAWLES").
dico("C", 7, "CRAWLEZ").
dico("C", 7, "CRAYERE").
dico("C", 7, "CRAYEUX").
dico("C", 7, "CRAYONS").
dico("C", 7, "CREAMES").
dico("C", 7, "CREANCE").
dico("C", 7, "CREASSE").
dico("C", 7, "CREATES").
dico("C", 7, "CREATIF").
dico("C", 7, "CRECHAI").
dico("C", 7, "CRECHAS").
dico("C", 7, "CRECHAT").
dico("C", 7, "CRECHER").
dico("C", 7, "CRECHES").
dico("C", 7, "CRECHEZ").
dico("C", 7, "CREDITA").
dico("C", 7, "CREDITE").
dico("C", 7, "CREDITS").
dico("C", 7, "CREDULE").
dico("C", 7, "CREERAI").
dico("C", 7, "CREERAS").
dico("C", 7, "CREEREZ").
dico("C", 7, "CREIONS").
dico("C", 7, "CREMAGE").
dico("C", 7, "CREMAIS").
dico("C", 7, "CREMAIT").
dico("C", 7, "CREMANT").
dico("C", 7, "CREMEES").
dico("C", 7, "CREMENT").
dico("C", 7, "CREMERA").
dico("C", 7, "CREMEUX").
dico("C", 7, "CREMIER").
dico("C", 7, "CREMIEZ").
dico("C", 7, "CREMONE").
dico("C", 7, "CREMONS").
dico("C", 7, "CRENAGE").
dico("C", 7, "CRENAIS").
dico("C", 7, "CRENAIT").
dico("C", 7, "CRENANT").
dico("C", 7, "CRENEAU").
dico("C", 7, "CRENEES").
dico("C", 7, "CRENELA").
dico("C", 7, "CRENELE").
dico("C", 7, "CRENENT").
dico("C", 7, "CRENERA").
dico("C", 7, "CRENIEZ").
dico("C", 7, "CRENONS").
dico("C", 7, "CREOLES").
dico("C", 7, "CREOSOL").
dico("C", 7, "CREPAGE").
dico("C", 7, "CREPAIS").
dico("C", 7, "CREPAIT").
dico("C", 7, "CREPANT").
dico("C", 7, "CREPEES").
dico("C", 7, "CREPELE").
dico("C", 7, "CREPELU").
dico("C", 7, "CREPENT").
dico("C", 7, "CREPERA").
dico("C", 7, "CREPIER").
dico("C", 7, "CREPIES").
dico("C", 7, "CREPIEZ").
dico("C", 7, "CREPINE").
dico("C", 7, "CREPINS").
dico("C", 7, "CREPIRA").
dico("C", 7, "CREPITA").
dico("C", 7, "CREPITE").
dico("C", 7, "CREPONS").
dico("C", 7, "CREPUES").
dico("C", 7, "CREPURE").
dico("C", 7, "CRESOLS").
dico("C", 7, "CRESSON").
dico("C", 7, "CRESYLS").
dico("C", 7, "CRETACE").
dico("C", 7, "CRETAIS").
dico("C", 7, "CRETAIT").
dico("C", 7, "CRETANT").
dico("C", 7, "CRETEES").
dico("C", 7, "CRETENT").
dico("C", 7, "CRETERA").
dico("C", 7, "CRETIEZ").
dico("C", 7, "CRETINE").
dico("C", 7, "CRETINS").
dico("C", 7, "CRETOIS").
dico("C", 7, "CRETONS").
dico("C", 7, "CREUSAI").
dico("C", 7, "CREUSAS").
dico("C", 7, "CREUSAT").
dico("C", 7, "CREUSEE").
dico("C", 7, "CREUSER").
dico("C", 7, "CREUSES").
dico("C", 7, "CREUSET").
dico("C", 7, "CREUSEZ").
dico("C", 7, "CREVAIS").
dico("C", 7, "CREVAIT").
dico("C", 7, "CREVANT").
dico("C", 7, "CREVARD").
dico("C", 7, "CREVEES").
dico("C", 7, "CREVENT").
dico("C", 7, "CREVERA").
dico("C", 7, "CREVIEZ").
dico("C", 7, "CREVONS").
dico("C", 7, "CREVOTA").
dico("C", 7, "CREVOTE").
dico("C", 7, "CREVURE").
dico("C", 7, "CRIAMES").
dico("C", 7, "CRIANTE").
dico("C", 7, "CRIANTS").
dico("C", 7, "CRIARDE").
dico("C", 7, "CRIARDS").
dico("C", 7, "CRIASSE").
dico("C", 7, "CRIATES").
dico("C", 7, "CRIBLAI").
dico("C", 7, "CRIBLAS").
dico("C", 7, "CRIBLAT").
dico("C", 7, "CRIBLEE").
dico("C", 7, "CRIBLER").
dico("C", 7, "CRIBLES").
dico("C", 7, "CRIBLEZ").
dico("C", 7, "CRICKET").
dico("C", 7, "CRICRIS").
dico("C", 7, "CRIERAI").
dico("C", 7, "CRIERAS").
dico("C", 7, "CRIEREZ").
dico("C", 7, "CRIEURS").
dico("C", 7, "CRIEUSE").
dico("C", 7, "CRIIONS").
dico("C", 7, "CRINIER").
dico("C", 7, "CRIQUAI").
dico("C", 7, "CRIQUAS").
dico("C", 7, "CRIQUAT").
dico("C", 7, "CRIQUER").
dico("C", 7, "CRIQUES").
dico("C", 7, "CRIQUET").
dico("C", 7, "CRIQUEZ").
dico("C", 7, "CRISAIS").
dico("C", 7, "CRISAIT").
dico("C", 7, "CRISANT").
dico("C", 7, "CRISENT").
dico("C", 7, "CRISERA").
dico("C", 7, "CRISIEZ").
dico("C", 7, "CRISONS").
dico("C", 7, "CRISPAI").
dico("C", 7, "CRISPAS").
dico("C", 7, "CRISPAT").
dico("C", 7, "CRISPEE").
dico("C", 7, "CRISPER").
dico("C", 7, "CRISPES").
dico("C", 7, "CRISPEZ").
dico("C", 7, "CRISPIN").
dico("C", 7, "CRISSAI").
dico("C", 7, "CRISSAS").
dico("C", 7, "CRISSAT").
dico("C", 7, "CRISSER").
dico("C", 7, "CRISSES").
dico("C", 7, "CRISSEZ").
dico("C", 7, "CRISTAL").
dico("C", 7, "CRITERE").
dico("C", 7, "CRITHME").
dico("C", 7, "CROASSA").
dico("C", 7, "CROASSE").
dico("C", 7, "CROATES").
dico("C", 7, "CROBARD").
dico("C", 7, "CROBARS").
dico("C", 7, "CROCHAI").
dico("C", 7, "CROCHAS").
dico("C", 7, "CROCHAT").
dico("C", 7, "CROCHEE").
dico("C", 7, "CROCHER").
dico("C", 7, "CROCHES").
dico("C", 7, "CROCHET").
dico("C", 7, "CROCHEZ").
dico("C", 7, "CROCHIE").
dico("C", 7, "CROCHIR").
dico("C", 7, "CROCHIS").
dico("C", 7, "CROCHIT").
dico("C", 7, "CROCHON").
dico("C", 7, "CROCHUE").
dico("C", 7, "CROCHUS").
dico("C", 7, "CROIENT").
dico("C", 7, "CROIRAI").
dico("C", 7, "CROIRAS").
dico("C", 7, "CROIREZ").
dico("C", 7, "CROISAI").
dico("C", 7, "CROISAS").
dico("C", 7, "CROISAT").
dico("C", 7, "CROISEE").
dico("C", 7, "CROISER").
dico("C", 7, "CROISES").
dico("C", 7, "CROISEZ").
dico("C", 7, "CROISSE").
dico("C", 7, "CROITRA").
dico("C", 7, "CROITRE").
dico("C", 7, "CROLLAI").
dico("C", 7, "CROLLAS").
dico("C", 7, "CROLLAT").
dico("C", 7, "CROLLEE").
dico("C", 7, "CROLLER").
dico("C", 7, "CROLLES").
dico("C", 7, "CROLLEZ").
dico("C", 7, "CROONER").
dico("C", 7, "CROQUAI").
dico("C", 7, "CROQUAS").
dico("C", 7, "CROQUAT").
dico("C", 7, "CROQUEE").
dico("C", 7, "CROQUER").
dico("C", 7, "CROQUES").
dico("C", 7, "CROQUET").
dico("C", 7, "CROQUEZ").
dico("C", 7, "CROQUIS").
dico("C", 7, "CROSNES").
dico("C", 7, "CROSSAI").
dico("C", 7, "CROSSAS").
dico("C", 7, "CROSSAT").
dico("C", 7, "CROSSEE").
dico("C", 7, "CROSSER").
dico("C", 7, "CROSSES").
dico("C", 7, "CROSSEZ").
dico("C", 7, "CROTALE").
dico("C", 7, "CROTONS").
dico("C", 7, "CROTTAI").
dico("C", 7, "CROTTAS").
dico("C", 7, "CROTTAT").
dico("C", 7, "CROTTEE").
dico("C", 7, "CROTTER").
dico("C", 7, "CROTTES").
dico("C", 7, "CROTTEZ").
dico("C", 7, "CROTTIN").
dico("C", 7, "CROULAI").
dico("C", 7, "CROULAS").
dico("C", 7, "CROULAT").
dico("C", 7, "CROULEE").
dico("C", 7, "CROULER").
dico("C", 7, "CROULES").
dico("C", 7, "CROULEZ").
dico("C", 7, "CROUPAL").
dico("C", 7, "CROUPES").
dico("C", 7, "CROUPIE").
dico("C", 7, "CROUPIR").
dico("C", 7, "CROUPIS").
dico("C", 7, "CROUPIT").
dico("C", 7, "CROUPON").
dico("C", 7, "CROUTAI").
dico("C", 7, "CROUTAS").
dico("C", 7, "CROUTAT").
dico("C", 7, "CROUTEE").
dico("C", 7, "CROUTER").
dico("C", 7, "CROUTES").
dico("C", 7, "CROUTEZ").
dico("C", 7, "CROUTON").
dico("C", 7, "CROYAIS").
dico("C", 7, "CROYAIT").
dico("C", 7, "CROYANT").
dico("C", 7, "CROYIEZ").
dico("C", 7, "CROYONS").
dico("C", 7, "CRUAUTE").
dico("C", 7, "CRUCHEE").
dico("C", 7, "CRUCHES").
dico("C", 7, "CRUCHON").
dico("C", 7, "CRUCIAL").
dico("C", 7, "CRUDITE").
dico("C", 7, "CRUELLE").
dico("C", 7, "CRUENTE").
dico("C", 7, "CRUISER").
dico("C", 7, "CRUMBLE").
dico("C", 7, "CRUMENT").
dico("C", 7, "CRURALE").
dico("C", 7, "CRURAUX").
dico("C", 7, "CRURENT").
dico("C", 7, "CRUSSES").
dico("C", 7, "CRUZADO").
dico("C", 7, "CRYPTAI").
dico("C", 7, "CRYPTAS").
dico("C", 7, "CRYPTAT").
dico("C", 7, "CRYPTEE").
dico("C", 7, "CRYPTER").
dico("C", 7, "CRYPTES").
dico("C", 7, "CRYPTEZ").
dico("C", 7, "CRYPTIE").
dico("C", 7, "CSARDAS").
dico("C", 7, "CUADROS").
dico("C", 7, "CUBAGES").
dico("C", 7, "CUBAINE").
dico("C", 7, "CUBAINS").
dico("C", 7, "CUBAMES").
dico("C", 7, "CUBASSE").
dico("C", 7, "CUBATES").
dico("C", 7, "CUBEBES").
dico("C", 7, "CUBERAI").
dico("C", 7, "CUBERAS").
dico("C", 7, "CUBEREZ").
dico("C", 7, "CUBILOT").
dico("C", 7, "CUBIONS").
dico("C", 7, "CUBIQUE").
dico("C", 7, "CUBISME").
dico("C", 7, "CUBISTE").
dico("C", 7, "CUBITAL").
dico("C", 7, "CUBITUS").
dico("C", 7, "CUBOIDE").
dico("C", 7, "CUCULLE").
dico("C", 7, "CUEILLE").
dico("C", 7, "CUEILLI").
dico("C", 7, "CUESTAS").
dico("C", 7, "CUFFATS").
dico("C", 7, "CUILLER").
dico("C", 7, "CUIRAIS").
dico("C", 7, "CUIRAIT").
dico("C", 7, "CUIRIEZ").
dico("C", 7, "CUIRONS").
dico("C", 7, "CUIRONT").
dico("C", 7, "CUISAIS").
dico("C", 7, "CUISAIT").
dico("C", 7, "CUISANT").
dico("C", 7, "CUISENT").
dico("C", 7, "CUISEUR").
dico("C", 7, "CUISIEZ").
dico("C", 7, "CUISINA").
dico("C", 7, "CUISINE").
dico("C", 7, "CUISONS").
dico("C", 7, "CUISSES").
dico("C", 7, "CUISSON").
dico("C", 7, "CUISSOT").
dico("C", 7, "CUISTAX").
dico("C", 7, "CUISTOT").
dico("C", 7, "CUISTRE").
dico("C", 7, "CUITAIS").
dico("C", 7, "CUITAIT").
dico("C", 7, "CUITANT").
dico("C", 7, "CUITEES").
dico("C", 7, "CUITENT").
dico("C", 7, "CUITERA").
dico("C", 7, "CUITIEZ").
dico("C", 7, "CUITONS").
dico("C", 7, "CUIVRAI").
dico("C", 7, "CUIVRAS").
dico("C", 7, "CUIVRAT").
dico("C", 7, "CUIVREE").
dico("C", 7, "CUIVRER").
dico("C", 7, "CUIVRES").
dico("C", 7, "CUIVREZ").
dico("C", 7, "CULAMES").
dico("C", 7, "CULARDS").
dico("C", 7, "CULASSE").
dico("C", 7, "CULATES").
dico("C", 7, "CULBUTA").
dico("C", 7, "CULBUTE").
dico("C", 7, "CULERAI").
dico("C", 7, "CULERAS").
dico("C", 7, "CULEREZ").
dico("C", 7, "CULERON").
dico("C", 7, "CULIERE").
dico("C", 7, "CULIONS").
dico("C", 7, "CULMINA").
dico("C", 7, "CULMINE").
dico("C", 7, "CULOTTA").
dico("C", 7, "CULOTTE").
dico("C", 7, "CULTIVA").
dico("C", 7, "CULTIVE").
dico("C", 7, "CULTUEL").
dico("C", 7, "CULTURE").
dico("C", 7, "CUMULAI").
dico("C", 7, "CUMULAS").
dico("C", 7, "CUMULAT").
dico("C", 7, "CUMULEE").
dico("C", 7, "CUMULER").
dico("C", 7, "CUMULES").
dico("C", 7, "CUMULET").
dico("C", 7, "CUMULEZ").
dico("C", 7, "CUMULUS").
dico("C", 7, "CUNETTE").
dico("C", 7, "CUPESSE").
dico("C", 7, "CUPIDES").
dico("C", 7, "CUPIDON").
dico("C", 7, "CUPRITE").
dico("C", 7, "CUPULES").
dico("C", 7, "CURABLE").
dico("C", 7, "CURACAO").
dico("C", 7, "CURAGES").
dico("C", 7, "CURAMES").
dico("C", 7, "CURARES").
dico("C", 7, "CURASSE").
dico("C", 7, "CURATES").
dico("C", 7, "CURATIF").
dico("C", 7, "CURCUMA").
dico("C", 7, "CURERAI").
dico("C", 7, "CURERAS").
dico("C", 7, "CUREREZ").
dico("C", 7, "CURETAI").
dico("C", 7, "CURETAS").
dico("C", 7, "CURETAT").
dico("C", 7, "CURETEE").
dico("C", 7, "CURETER").
dico("C", 7, "CURETES").
dico("C", 7, "CURETEZ").
dico("C", 7, "CURETON").
dico("C", 7, "CURETTE").
dico("C", 7, "CUREURS").
dico("C", 7, "CURIALE").
dico("C", 7, "CURIATE").
dico("C", 7, "CURIAUX").
dico("C", 7, "CURIDES").
dico("C", 7, "CURIEUX").
dico("C", 7, "CURIONS").
dico("C", 7, "CURISTE").
dico("C", 7, "CURIUMS").
dico("C", 7, "CURLEUR").
dico("C", 7, "CURLING").
dico("C", 7, "CURSEUR").
dico("C", 7, "CURSIFS").
dico("C", 7, "CURSIVE").
dico("C", 7, "CURULES").
dico("C", 7, "CURURES").
dico("C", 7, "CUSCUTE").
dico("C", 7, "CUSPIDE").
dico("C", 7, "CUSTODE").
dico("C", 7, "CUSTOMS").
dico("C", 7, "CUTANEE").
dico("C", 7, "CUTANES").
dico("C", 7, "CUTINES").
dico("C", 7, "CUTTERS").
dico("C", 7, "CUVAGES").
dico("C", 7, "CUVAMES").
dico("C", 7, "CUVASSE").
dico("C", 7, "CUVATES").
dico("C", 7, "CUVEAUX").
dico("C", 7, "CUVELAI").
dico("C", 7, "CUVELAS").
dico("C", 7, "CUVELAT").
dico("C", 7, "CUVELEE").
dico("C", 7, "CUVELER").
dico("C", 7, "CUVELES").
dico("C", 7, "CUVELEZ").
dico("C", 7, "CUVELLE").
dico("C", 7, "CUVERAI").
dico("C", 7, "CUVERAS").
dico("C", 7, "CUVEREZ").
dico("C", 7, "CUVETTE").
dico("C", 7, "CUVIERS").
dico("C", 7, "CUVIONS").
dico("C", 7, "CYANATE").
dico("C", 7, "CYANEAS").
dico("C", 7, "CYANEES").
dico("C", 7, "CYANOSA").
dico("C", 7, "CYANOSE").
dico("C", 7, "CYANURA").
dico("C", 7, "CYANURE").
dico("C", 7, "CYCLANE").
dico("C", 7, "CYCLENE").
dico("C", 7, "CYCLINE").
dico("C", 7, "CYCLISA").
dico("C", 7, "CYCLISE").
dico("C", 7, "CYCLONE").
dico("C", 7, "CYCLOPE").
dico("C", 7, "CYMAISE").
dico("C", 7, "CYMBALE").
dico("C", 7, "CYNIQUE").
dico("C", 7, "CYNISME").
dico("C", 7, "CYPHOSE").
dico("C", 7, "CYPRINE").
dico("C", 7, "CYPRINS").
dico("C", 7, "CYRARDS").
dico("C", 7, "CYSTINE").
dico("C", 7, "CYSTITE").
dico("C", 7, "CYTISES").
dico("C", 7, "CYTOSOL").
dico("C", 7, "CZARDAS").
