dico("D", 6, "DACRON").
dico("D", 6, "DADAIS").
dico("D", 6, "DAGUAI").
dico("D", 6, "DAGUAS").
dico("D", 6, "DAGUAT").
dico("D", 6, "DAGUEE").
dico("D", 6, "DAGUER").
dico("D", 6, "DAGUES").
dico("D", 6, "DAGUET").
dico("D", 6, "DAGUEZ").
dico("D", 6, "DAHIRS").
dico("D", 6, "DAHLIA").
dico("D", 6, "DAIGNA").
dico("D", 6, "DAIGNE").
dico("D", 6, "DAILLE").
dico("D", 6, "DAIMIO").
dico("D", 6, "DAIMYO").
dico("D", 6, "DAINES").
dico("D", 6, "DAIRAS").
dico("D", 6, "DAKINS").
dico("D", 6, "DALASI").
dico("D", 6, "DALEAU").
dico("D", 6, "DALLAI").
dico("D", 6, "DALLAS").
dico("D", 6, "DALLAT").
dico("D", 6, "DALLEE").
dico("D", 6, "DALLER").
dico("D", 6, "DALLES").
dico("D", 6, "DALLEZ").
dico("D", 6, "DALOTS").
dico("D", 6, "DALTON").
dico("D", 6, "DAMAGE").
dico("D", 6, "DAMAIS").
dico("D", 6, "DAMAIT").
dico("D", 6, "DAMANS").
dico("D", 6, "DAMANT").
dico("D", 6, "DAMEES").
dico("D", 6, "DAMENT").
dico("D", 6, "DAMERA").
dico("D", 6, "DAMEUR").
dico("D", 6, "DAMIER").
dico("D", 6, "DAMIEZ").
dico("D", 6, "DAMNAI").
dico("D", 6, "DAMNAS").
dico("D", 6, "DAMNAT").
dico("D", 6, "DAMNEE").
dico("D", 6, "DAMNER").
dico("D", 6, "DAMNES").
dico("D", 6, "DAMNEZ").
dico("D", 6, "DAMONS").
dico("D", 6, "DAMPER").
dico("D", 6, "DANCES").
dico("D", 6, "DANDIN").
dico("D", 6, "DANDYS").
dico("D", 6, "DANGER").
dico("D", 6, "DANIEN").
dico("D", 6, "DANOIS").
dico("D", 6, "DANSAI").
dico("D", 6, "DANSAS").
dico("D", 6, "DANSAT").
dico("D", 6, "DANSEE").
dico("D", 6, "DANSER").
dico("D", 6, "DANSES").
dico("D", 6, "DANSEZ").
dico("D", 6, "DAPHNE").
dico("D", 6, "DARCES").
dico("D", 6, "DARDAI").
dico("D", 6, "DARDAS").
dico("D", 6, "DARDAT").
dico("D", 6, "DARDEE").
dico("D", 6, "DARDER").
dico("D", 6, "DARDES").
dico("D", 6, "DARDEZ").
dico("D", 6, "DARNES").
dico("D", 6, "DARSES").
dico("D", 6, "DARTRE").
dico("D", 6, "DASEIN").
dico("D", 6, "DATAGE").
dico("D", 6, "DATAIS").
dico("D", 6, "DATAIT").
dico("D", 6, "DATANT").
dico("D", 6, "DATCHA").
dico("D", 6, "DATEES").
dico("D", 6, "DATENT").
dico("D", 6, "DATERA").
dico("D", 6, "DATEUR").
dico("D", 6, "DATIEZ").
dico("D", 6, "DATIFS").
dico("D", 6, "DATION").
dico("D", 6, "DATIVE").
dico("D", 6, "DATONS").
dico("D", 6, "DATTES").
dico("D", 6, "DATURA").
dico("D", 6, "DAUBAI").
dico("D", 6, "DAUBAS").
dico("D", 6, "DAUBAT").
dico("D", 6, "DAUBEE").
dico("D", 6, "DAUBER").
dico("D", 6, "DAUBES").
dico("D", 6, "DAUBEZ").
dico("D", 6, "DAVIER").
dico("D", 6, "DAYAKS").
dico("D", 6, "DEALAI").
dico("D", 6, "DEALAS").
dico("D", 6, "DEALAT").
dico("D", 6, "DEALEE").
dico("D", 6, "DEALER").
dico("D", 6, "DEALES").
dico("D", 6, "DEALEZ").
dico("D", 6, "DEBATA").
dico("D", 6, "DEBATE").
dico("D", 6, "DEBATI").
dico("D", 6, "DEBATS").
dico("D", 6, "DEBETS").
dico("D", 6, "DEBILE").
dico("D", 6, "DEBINA").
dico("D", 6, "DEBINE").
dico("D", 6, "DEBITA").
dico("D", 6, "DEBITE").
dico("D", 6, "DEBITS").
dico("D", 6, "DEBLAI").
dico("D", 6, "DEBORD").
dico("D", 6, "DEBOUS").
dico("D", 6, "DEBOUT").
dico("D", 6, "DEBRIS").
dico("D", 6, "DEBUTA").
dico("D", 6, "DEBUTE").
dico("D", 6, "DEBUTS").
dico("D", 6, "DEBYES").
dico("D", 6, "DECADE").
dico("D", 6, "DECADI").
dico("D", 6, "DECALA").
dico("D", 6, "DECALE").
dico("D", 6, "DECANS").
dico("D", 6, "DECAPA").
dico("D", 6, "DECAPE").
dico("D", 6, "DECATI").
dico("D", 6, "DECAVA").
dico("D", 6, "DECAVE").
dico("D", 6, "DECCAS").
dico("D", 6, "DECEDA").
dico("D", 6, "DECEDE").
dico("D", 6, "DECELA").
dico("D", 6, "DECELE").
dico("D", 6, "DECENT").
dico("D", 6, "DECHES").
dico("D", 6, "DECHET").
dico("D", 6, "DECHUE").
dico("D", 6, "DECHUS").
dico("D", 6, "DECHUT").
dico("D", 6, "DECIDA").
dico("D", 6, "DECIDE").
dico("D", 6, "DECIDU").
dico("D", 6, "DECILE").
dico("D", 6, "DECIMA").
dico("D", 6, "DECIME").
dico("D", 6, "DECIMO").
dico("D", 6, "DECLIC").
dico("D", 6, "DECLIN").
dico("D", 6, "DECLOS").
dico("D", 6, "DECLOT").
dico("D", 6, "DECODA").
dico("D", 6, "DECODE").
dico("D", 6, "DECOIS").
dico("D", 6, "DECOIT").
dico("D", 6, "DECORA").
dico("D", 6, "DECORE").
dico("D", 6, "DECORS").
dico("D", 6, "DECOTA").
dico("D", 6, "DECOTE").
dico("D", 6, "DECOUD").
dico("D", 6, "DECRET").
dico("D", 6, "DECRIA").
dico("D", 6, "DECRIE").
dico("D", 6, "DECRIS").
dico("D", 6, "DECRIT").
dico("D", 6, "DECRUA").
dico("D", 6, "DECRUE").
dico("D", 6, "DECRUS").
dico("D", 6, "DECRUT").
dico("D", 6, "DECUES").
dico("D", 6, "DECUIS").
dico("D", 6, "DECUIT").
dico("D", 6, "DECUVA").
dico("D", 6, "DECUVE").
dico("D", 6, "DEDAIN").
dico("D", 6, "DEDALE").
dico("D", 6, "DEDANS").
dico("D", 6, "DEDIAI").
dico("D", 6, "DEDIAS").
dico("D", 6, "DEDIAT").
dico("D", 6, "DEDIEE").
dico("D", 6, "DEDIER").
dico("D", 6, "DEDIES").
dico("D", 6, "DEDIEZ").
dico("D", 6, "DEDIRA").
dico("D", 6, "DEDIRE").
dico("D", 6, "DEDISE").
dico("D", 6, "DEDITE").
dico("D", 6, "DEDITS").
dico("D", 6, "DEDORA").
dico("D", 6, "DEDORE").
dico("D", 6, "DEDUIS").
dico("D", 6, "DEDUIT").
dico("D", 6, "DEESSE").
dico("D", 6, "DEFAIS").
dico("D", 6, "DEFAIT").
dico("D", 6, "DEFAUT").
dico("D", 6, "DEFEND").
dico("D", 6, "DEFENS").
dico("D", 6, "DEFERA").
dico("D", 6, "DEFERE").
dico("D", 6, "DEFETS").
dico("D", 6, "DEFIAI").
dico("D", 6, "DEFIAS").
dico("D", 6, "DEFIAT").
dico("D", 6, "DEFIEE").
dico("D", 6, "DEFIER").
dico("D", 6, "DEFIES").
dico("D", 6, "DEFIEZ").
dico("D", 6, "DEFIGE").
dico("D", 6, "DEFILA").
dico("D", 6, "DEFILE").
dico("D", 6, "DEFINI").
dico("D", 6, "DEFONT").
dico("D", 6, "DEFUNT").
dico("D", 6, "DEGAGE").
dico("D", 6, "DEGATS").
dico("D", 6, "DEGAZA").
dico("D", 6, "DEGAZE").
dico("D", 6, "DEGELA").
dico("D", 6, "DEGELE").
dico("D", 6, "DEGELS").
dico("D", 6, "DEGENA").
dico("D", 6, "DEGENE").
dico("D", 6, "DEGLUA").
dico("D", 6, "DEGLUE").
dico("D", 6, "DEGOTA").
dico("D", 6, "DEGOTE").
dico("D", 6, "DEGOUT").
dico("D", 6, "DEGRAS").
dico("D", 6, "DEGREA").
dico("D", 6, "DEGREE").
dico("D", 6, "DEGRES").
dico("D", 6, "DEGUEU").
dico("D", 6, "DEHALA").
dico("D", 6, "DEHALE").
dico("D", 6, "DEHORS").
dico("D", 6, "DEIFIA").
dico("D", 6, "DEIFIE").
dico("D", 6, "DEISME").
dico("D", 6, "DEISTE").
dico("D", 6, "DEITES").
dico("D", 6, "DEJETA").
dico("D", 6, "DEJETE").
dico("D", 6, "DEJOUA").
dico("D", 6, "DEJOUE").
dico("D", 6, "DEJUGE").
dico("D", 6, "DELACA").
dico("D", 6, "DELACE").
dico("D", 6, "DELAIE").
dico("D", 6, "DELAIS").
dico("D", 6, "DELAVA").
dico("D", 6, "DELAVE").
dico("D", 6, "DELAYA").
dico("D", 6, "DELAYE").
dico("D", 6, "DELCOS").
dico("D", 6, "DELIAI").
dico("D", 6, "DELIAS").
dico("D", 6, "DELIAT").
dico("D", 6, "DELICE").
dico("D", 6, "DELIEE").
dico("D", 6, "DELIEN").
dico("D", 6, "DELIER").
dico("D", 6, "DELIES").
dico("D", 6, "DELIEZ").
dico("D", 6, "DELIRA").
dico("D", 6, "DELIRE").
dico("D", 6, "DELITA").
dico("D", 6, "DELITE").
dico("D", 6, "DELITS").
dico("D", 6, "DELOGE").
dico("D", 6, "DELOTS").
dico("D", 6, "DELOVA").
dico("D", 6, "DELOVE").
dico("D", 6, "DELTAS").
dico("D", 6, "DELUGE").
dico("D", 6, "DELURA").
dico("D", 6, "DELURE").
dico("D", 6, "DELUTA").
dico("D", 6, "DELUTE").
dico("D", 6, "DEMAGO").
dico("D", 6, "DEMAIN").
dico("D", 6, "DEMATA").
dico("D", 6, "DEMATE").
dico("D", 6, "DEMELA").
dico("D", 6, "DEMELE").
dico("D", 6, "DEMENA").
dico("D", 6, "DEMENE").
dico("D", 6, "DEMENS").
dico("D", 6, "DEMENT").
dico("D", 6, "DEMETS").
dico("D", 6, "DEMIES").
dico("D", 6, "DEMINA").
dico("D", 6, "DEMINE").
dico("D", 6, "DEMISE").
dico("D", 6, "DEMODA").
dico("D", 6, "DEMODE").
dico("D", 6, "DEMOLI").
dico("D", 6, "DEMONE").
dico("D", 6, "DEMONS").
dico("D", 6, "DEMORD").
dico("D", 6, "DEMUNI").
dico("D", 6, "DENARS").
dico("D", 6, "DENGUE").
dico("D", 6, "DENIAI").
dico("D", 6, "DENIAS").
dico("D", 6, "DENIAT").
dico("D", 6, "DENIEE").
dico("D", 6, "DENIER").
dico("D", 6, "DENIES").
dico("D", 6, "DENIEZ").
dico("D", 6, "DENIMS").
dico("D", 6, "DENOIE").
dico("D", 6, "DENOTA").
dico("D", 6, "DENOTE").
dico("D", 6, "DENOUA").
dico("D", 6, "DENOUE").
dico("D", 6, "DENOYA").
dico("D", 6, "DENOYE").
dico("D", 6, "DENREE").
dico("D", 6, "DENSES").
dico("D", 6, "DENTAI").
dico("D", 6, "DENTAL").
dico("D", 6, "DENTAS").
dico("D", 6, "DENTAT").
dico("D", 6, "DENTEE").
dico("D", 6, "DENTER").
dico("D", 6, "DENTES").
dico("D", 6, "DENTEZ").
dico("D", 6, "DENTUE").
dico("D", 6, "DENTUS").
dico("D", 6, "DENUAI").
dico("D", 6, "DENUAS").
dico("D", 6, "DENUAT").
dico("D", 6, "DENUDA").
dico("D", 6, "DENUDE").
dico("D", 6, "DENUEE").
dico("D", 6, "DENUER").
dico("D", 6, "DENUES").
dico("D", 6, "DENUEZ").
dico("D", 6, "DEPARA").
dico("D", 6, "DEPARE").
dico("D", 6, "DEPARS").
dico("D", 6, "DEPART").
dico("D", 6, "DEPAVA").
dico("D", 6, "DEPAVE").
dico("D", 6, "DEPECA").
dico("D", 6, "DEPECE").
dico("D", 6, "DEPEND").
dico("D", 6, "DEPENS").
dico("D", 6, "DEPERI").
dico("D", 6, "DEPILA").
dico("D", 6, "DEPILE").
dico("D", 6, "DEPITA").
dico("D", 6, "DEPITE").
dico("D", 6, "DEPITS").
dico("D", 6, "DEPLIA").
dico("D", 6, "DEPLIE").
dico("D", 6, "DEPLUS").
dico("D", 6, "DEPLUT").
dico("D", 6, "DEPOLI").
dico("D", 6, "DEPORT").
dico("D", 6, "DEPOSA").
dico("D", 6, "DEPOSE").
dico("D", 6, "DEPOTA").
dico("D", 6, "DEPOTE").
dico("D", 6, "DEPOTS").
dico("D", 6, "DEPRIS").
dico("D", 6, "DEPRIT").
dico("D", 6, "DEPUIS").
dico("D", 6, "DEPURA").
dico("D", 6, "DEPURE").
dico("D", 6, "DEPUTA").
dico("D", 6, "DEPUTE").
dico("D", 6, "DERADA").
dico("D", 6, "DERADE").
dico("D", 6, "DERAGE").
dico("D", 6, "DERAIE").
dico("D", 6, "DERAMA").
dico("D", 6, "DERAME").
dico("D", 6, "DERAPA").
dico("D", 6, "DERAPE").
dico("D", 6, "DERASA").
dico("D", 6, "DERASE").
dico("D", 6, "DERATA").
dico("D", 6, "DERATE").
dico("D", 6, "DERAYA").
dico("D", 6, "DERAYE").
dico("D", 6, "DERBYS").
dico("D", 6, "DERCHE").
dico("D", 6, "DEREEL").
dico("D", 6, "DERIDA").
dico("D", 6, "DERIDE").
dico("D", 6, "DERIVA").
dico("D", 6, "DERIVE").
dico("D", 6, "DERMES").
dico("D", 6, "DERNYS").
dico("D", 6, "DEROBA").
dico("D", 6, "DEROBE").
dico("D", 6, "DERODA").
dico("D", 6, "DERODE").
dico("D", 6, "DEROGE").
dico("D", 6, "DERUPE").
dico("D", 6, "DESAMA").
dico("D", 6, "DESAME").
dico("D", 6, "DESAPA").
dico("D", 6, "DESAPE").
dico("D", 6, "DESAXA").
dico("D", 6, "DESAXE").
dico("D", 6, "DESERT").
dico("D", 6, "DESIGN").
dico("D", 6, "DESILA").
dico("D", 6, "DESILE").
dico("D", 6, "DESIRA").
dico("D", 6, "DESIRE").
dico("D", 6, "DESIRS").
dico("D", 6, "DESMAN").
dico("D", 6, "DESODE").
dico("D", 6, "DESOLA").
dico("D", 6, "DESOLE").
dico("D", 6, "DESSIN").
dico("D", 6, "DESSUS").
dico("D", 6, "DESTIN").
dico("D", 6, "DESUET").
dico("D", 6, "DESUNI").
dico("D", 6, "DETAIL").
dico("D", 6, "DETALA").
dico("D", 6, "DETALE").
dico("D", 6, "DETAXA").
dico("D", 6, "DETAXE").
dico("D", 6, "DETELA").
dico("D", 6, "DETELE").
dico("D", 6, "DETEND").
dico("D", 6, "DETENU").
dico("D", 6, "DETINS").
dico("D", 6, "DETINT").
dico("D", 6, "DETIRA").
dico("D", 6, "DETIRE").
dico("D", 6, "DETONA").
dico("D", 6, "DETONE").
dico("D", 6, "DETORD").
dico("D", 6, "DETORS").
dico("D", 6, "DETOUR").
dico("D", 6, "DETTES").
dico("D", 6, "DEUILS").
dico("D", 6, "DEUSIO").
dico("D", 6, "DEUSTS").
dico("D", 6, "DEUTON").
dico("D", 6, "DEUZIO").
dico("D", 6, "DEVAIS").
dico("D", 6, "DEVAIT").
dico("D", 6, "DEVALA").
dico("D", 6, "DEVALE").
dico("D", 6, "DEVANT").
dico("D", 6, "DEVASA").
dico("D", 6, "DEVASE").
dico("D", 6, "DEVENU").
dico("D", 6, "DEVERS").
dico("D", 6, "DEVETE").
dico("D", 6, "DEVETS").
dico("D", 6, "DEVETU").
dico("D", 6, "DEVIAI").
dico("D", 6, "DEVIAS").
dico("D", 6, "DEVIAT").
dico("D", 6, "DEVIDA").
dico("D", 6, "DEVIDE").
dico("D", 6, "DEVIEE").
dico("D", 6, "DEVIER").
dico("D", 6, "DEVIES").
dico("D", 6, "DEVIEZ").
dico("D", 6, "DEVINA").
dico("D", 6, "DEVINE").
dico("D", 6, "DEVINS").
dico("D", 6, "DEVINT").
dico("D", 6, "DEVIRA").
dico("D", 6, "DEVIRE").
dico("D", 6, "DEVISA").
dico("D", 6, "DEVISE").
dico("D", 6, "DEVOIE").
dico("D", 6, "DEVOIR").
dico("D", 6, "DEVOLU").
dico("D", 6, "DEVONS").
dico("D", 6, "DEVORA").
dico("D", 6, "DEVORE").
dico("D", 6, "DEVOTE").
dico("D", 6, "DEVOTS").
dico("D", 6, "DEVOUA").
dico("D", 6, "DEVOUE").
dico("D", 6, "DEVOYA").
dico("D", 6, "DEVOYE").
dico("D", 6, "DEVRAI").
dico("D", 6, "DEVRAS").
dico("D", 6, "DEVREZ").
dico("D", 6, "DEWARS").
dico("D", 6, "DEXTRE").
dico("D", 6, "DEZONA").
dico("D", 6, "DEZONE").
dico("D", 6, "DHARMA").
dico("D", 6, "DHOLES").
dico("D", 6, "DIABLE").
dico("D", 6, "DIACRE").
dico("D", 6, "DIANES").
dico("D", 6, "DIAPIR").
dico("D", 6, "DIAPOS").
dico("D", 6, "DIAPRA").
dico("D", 6, "DIAPRE").
dico("D", 6, "DIAULE").
dico("D", 6, "DICTAI").
dico("D", 6, "DICTAS").
dico("D", 6, "DICTAT").
dico("D", 6, "DICTEE").
dico("D", 6, "DICTER").
dico("D", 6, "DICTES").
dico("D", 6, "DICTEZ").
dico("D", 6, "DICTON").
dico("D", 6, "DIDYME").
dico("D", 6, "DIEDRE").
dico("D", 6, "DIENES").
dico("D", 6, "DIESAI").
dico("D", 6, "DIESAS").
dico("D", 6, "DIESAT").
dico("D", 6, "DIESEE").
dico("D", 6, "DIESEL").
dico("D", 6, "DIESER").
dico("D", 6, "DIESES").
dico("D", 6, "DIESEZ").
dico("D", 6, "DIETES").
dico("D", 6, "DIFFAS").
dico("D", 6, "DIFFUS").
dico("D", 6, "DIGERA").
dico("D", 6, "DIGERE").
dico("D", 6, "DIGEST").
dico("D", 6, "DIGITE").
dico("D", 6, "DIGITS").
dico("D", 6, "DIGNES").
dico("D", 6, "DIGONS").
dico("D", 6, "DIGUES").
dico("D", 6, "DIKTAT").
dico("D", 6, "DILATA").
dico("D", 6, "DILATE").
dico("D", 6, "DILUAI").
dico("D", 6, "DILUAS").
dico("D", 6, "DILUAT").
dico("D", 6, "DILUEE").
dico("D", 6, "DILUER").
dico("D", 6, "DILUES").
dico("D", 6, "DILUEZ").
dico("D", 6, "DIMERE").
dico("D", 6, "DINAIS").
dico("D", 6, "DINAIT").
dico("D", 6, "DINANT").
dico("D", 6, "DINARS").
dico("D", 6, "DINDES").
dico("D", 6, "DINDON").
dico("D", 6, "DINENT").
dico("D", 6, "DINERA").
dico("D", 6, "DINERS").
dico("D", 6, "DINEUR").
dico("D", 6, "DINGHY").
dico("D", 6, "DINGOS").
dico("D", 6, "DINGUA").
dico("D", 6, "DINGUE").
dico("D", 6, "DINIEZ").
dico("D", 6, "DINONS").
dico("D", 6, "DIODES").
dico("D", 6, "DIODON").
dico("D", 6, "DIONEE").
dico("D", 6, "DIOULA").
dico("D", 6, "DIPLOE").
dico("D", 6, "DIPODE").
dico("D", 6, "DIPOLE").
dico("D", 6, "DIRAIS").
dico("D", 6, "DIRAIT").
dico("D", 6, "DIRCOM").
dico("D", 6, "DIRECT").
dico("D", 6, "DIRENT").
dico("D", 6, "DIRHAM").
dico("D", 6, "DIRHEM").
dico("D", 6, "DIRIEZ").
dico("D", 6, "DIRIGE").
dico("D", 6, "DIRLOS").
dico("D", 6, "DIRONS").
dico("D", 6, "DIRONT").
dico("D", 6, "DISAIS").
dico("D", 6, "DISAIT").
dico("D", 6, "DISANT").
dico("D", 6, "DISCAL").
dico("D", 6, "DISCOS").
dico("D", 6, "DISENT").
dico("D", 6, "DISERT").
dico("D", 6, "DISEUR").
dico("D", 6, "DISIEZ").
dico("D", 6, "DISONS").
dico("D", 6, "DISPOS").
dico("D", 6, "DISQUA").
dico("D", 6, "DISQUE").
dico("D", 6, "DISSES").
dico("D", 6, "DISTAL").
dico("D", 6, "DIURNE").
dico("D", 6, "DIVANS").
dico("D", 6, "DIVERS").
dico("D", 6, "DIVINE").
dico("D", 6, "DIVINS").
dico("D", 6, "DIVISA").
dico("D", 6, "DIVISE").
dico("D", 6, "DIXIES").
dico("D", 6, "DIZAIN").
dico("D", 6, "DJAINA").
dico("D", 6, "DJAINE").
dico("D", 6, "DJAINS").
dico("D", 6, "DJAMAA").
dico("D", 6, "DJEBEL").
dico("D", 6, "DJEMAA").
dico("D", 6, "DJEMBE").
dico("D", 6, "DJIHAD").
dico("D", 6, "DJINNS").
dico("D", 6, "DOBRAS").
dico("D", 6, "DOCILE").
dico("D", 6, "DOCKER").
dico("D", 6, "DOCTES").
dico("D", 6, "DODINA").
dico("D", 6, "DODINE").
dico("D", 6, "DODUES").
dico("D", 6, "DOGATS").
dico("D", 6, "DOGGER").
dico("D", 6, "DOGMES").
dico("D", 6, "DOGONS").
dico("D", 6, "DOGUES").
dico("D", 6, "DOGUIN").
dico("D", 6, "DOIGTA").
dico("D", 6, "DOIGTE").
dico("D", 6, "DOIGTS").
dico("D", 6, "DOIVES").
dico("D", 6, "DOLAGE").
dico("D", 6, "DOLAIS").
dico("D", 6, "DOLAIT").
dico("D", 6, "DOLANT").
dico("D", 6, "DOLBYS").
dico("D", 6, "DOLEAU").
dico("D", 6, "DOLEES").
dico("D", 6, "DOLENT").
dico("D", 6, "DOLERA").
dico("D", 6, "DOLICS").
dico("D", 6, "DOLIEZ").
dico("D", 6, "DOLINE").
dico("D", 6, "DOLLAR").
dico("D", 6, "DOLMAN").
dico("D", 6, "DOLMEN").
dico("D", 6, "DOLONS").
dico("D", 6, "DOMBRE").
dico("D", 6, "DOMIEN").
dico("D", 6, "DOMINA").
dico("D", 6, "DOMINE").
dico("D", 6, "DOMINO").
dico("D", 6, "DOMPTA").
dico("D", 6, "DOMPTE").
dico("D", 6, "DONAUS").
dico("D", 6, "DONDON").
dico("D", 6, "DONJON").
dico("D", 6, "DONNAI").
dico("D", 6, "DONNAS").
dico("D", 6, "DONNAT").
dico("D", 6, "DONNEE").
dico("D", 6, "DONNER").
dico("D", 6, "DONNES").
dico("D", 6, "DONNEZ").
dico("D", 6, "DOPAGE").
dico("D", 6, "DOPAIS").
dico("D", 6, "DOPAIT").
dico("D", 6, "DOPANT").
dico("D", 6, "DOPEES").
dico("D", 6, "DOPENT").
dico("D", 6, "DOPERA").
dico("D", 6, "DOPEUR").
dico("D", 6, "DOPIEZ").
dico("D", 6, "DOPING").
dico("D", 6, "DOPONS").
dico("D", 6, "DORADE").
dico("D", 6, "DORAGE").
dico("D", 6, "DORAIS").
dico("D", 6, "DORAIT").
dico("D", 6, "DORANT").
dico("D", 6, "DOREES").
dico("D", 6, "DORENT").
dico("D", 6, "DORERA").
dico("D", 6, "DOREUR").
dico("D", 6, "DORIEN").
dico("D", 6, "DORIEZ").
dico("D", 6, "DORINS").
dico("D", 6, "DORMES").
dico("D", 6, "DORMEZ").
dico("D", 6, "DORMIE").
dico("D", 6, "DORMIR").
dico("D", 6, "DORMIS").
dico("D", 6, "DORMIT").
dico("D", 6, "DORONS").
dico("D", 6, "DORSAL").
dico("D", 6, "DORURE").
dico("D", 6, "DOSAGE").
dico("D", 6, "DOSAIS").
dico("D", 6, "DOSAIT").
dico("D", 6, "DOSANT").
dico("D", 6, "DOSEES").
dico("D", 6, "DOSENT").
dico("D", 6, "DOSERA").
dico("D", 6, "DOSEUR").
dico("D", 6, "DOSIEZ").
dico("D", 6, "DOSONS").
dico("D", 6, "DOSSES").
dico("D", 6, "DOTAIS").
dico("D", 6, "DOTAIT").
dico("D", 6, "DOTALE").
dico("D", 6, "DOTANT").
dico("D", 6, "DOTAUX").
dico("D", 6, "DOTEES").
dico("D", 6, "DOTENT").
dico("D", 6, "DOTERA").
dico("D", 6, "DOTIEZ").
dico("D", 6, "DOTONS").
dico("D", 6, "DOUAIS").
dico("D", 6, "DOUAIT").
dico("D", 6, "DOUANE").
dico("D", 6, "DOUANT").
dico("D", 6, "DOUARS").
dico("D", 6, "DOUBLA").
dico("D", 6, "DOUBLE").
dico("D", 6, "DOUCES").
dico("D", 6, "DOUCET").
dico("D", 6, "DOUCHA").
dico("D", 6, "DOUCHE").
dico("D", 6, "DOUCIE").
dico("D", 6, "DOUCIN").
dico("D", 6, "DOUCIR").
dico("D", 6, "DOUCIS").
dico("D", 6, "DOUCIT").
dico("D", 6, "DOUDOU").
dico("D", 6, "DOUEES").
dico("D", 6, "DOUENT").
dico("D", 6, "DOUERA").
dico("D", 6, "DOUFES").
dico("D", 6, "DOUIEZ").
dico("D", 6, "DOUMAS").
dico("D", 6, "DOUONS").
dico("D", 6, "DOUROS").
dico("D", 6, "DOUTAI").
dico("D", 6, "DOUTAS").
dico("D", 6, "DOUTAT").
dico("D", 6, "DOUTEE").
dico("D", 6, "DOUTER").
dico("D", 6, "DOUTES").
dico("D", 6, "DOUTEZ").
dico("D", 6, "DOUVES").
dico("D", 6, "DOYENS").
dico("D", 6, "DRACHA").
dico("D", 6, "DRACHE").
dico("D", 6, "DRAGEE").
dico("D", 6, "DRAGON").
dico("D", 6, "DRAGUA").
dico("D", 6, "DRAGUE").
dico("D", 6, "DRAIES").
dico("D", 6, "DRAINA").
dico("D", 6, "DRAINE").
dico("D", 6, "DRAINS").
dico("D", 6, "DRALON").
dico("D", 6, "DRAMES").
dico("D", 6, "DRAPAI").
dico("D", 6, "DRAPAS").
dico("D", 6, "DRAPAT").
dico("D", 6, "DRAPEE").
dico("D", 6, "DRAPER").
dico("D", 6, "DRAPES").
dico("D", 6, "DRAPEZ").
dico("D", 6, "DRAVAI").
dico("D", 6, "DRAVAS").
dico("D", 6, "DRAVAT").
dico("D", 6, "DRAVEE").
dico("D", 6, "DRAVER").
dico("D", 6, "DRAVES").
dico("D", 6, "DRAVEZ").
dico("D", 6, "DRAYAI").
dico("D", 6, "DRAYAS").
dico("D", 6, "DRAYAT").
dico("D", 6, "DRAYEE").
dico("D", 6, "DRAYER").
dico("D", 6, "DRAYES").
dico("D", 6, "DRAYEZ").
dico("D", 6, "DRECHE").
dico("D", 6, "DREGES").
dico("D", 6, "DREIGE").
dico("D", 6, "DRELIN").
dico("D", 6, "DRENNE").
dico("D", 6, "DRESSA").
dico("D", 6, "DRESSE").
dico("D", 6, "DREVES").
dico("D", 6, "DRIFTS").
dico("D", 6, "DRILLA").
dico("D", 6, "DRILLE").
dico("D", 6, "DRILLS").
dico("D", 6, "DRINKS").
dico("D", 6, "DRISSE").
dico("D", 6, "DRIVAI").
dico("D", 6, "DRIVAS").
dico("D", 6, "DRIVAT").
dico("D", 6, "DRIVEE").
dico("D", 6, "DRIVER").
dico("D", 6, "DRIVES").
dico("D", 6, "DRIVEZ").
dico("D", 6, "DROGUA").
dico("D", 6, "DROGUE").
dico("D", 6, "DROITE").
dico("D", 6, "DROITS").
dico("D", 6, "DROLES").
dico("D", 6, "DROLET").
dico("D", 6, "DROMES").
dico("D", 6, "DROMON").
dico("D", 6, "DRONES").
dico("D", 6, "DRONTE").
dico("D", 6, "DROPAI").
dico("D", 6, "DROPAS").
dico("D", 6, "DROPAT").
dico("D", 6, "DROPEE").
dico("D", 6, "DROPER").
dico("D", 6, "DROPES").
dico("D", 6, "DROPEZ").
dico("D", 6, "DROPPA").
dico("D", 6, "DROPPE").
dico("D", 6, "DROSSA").
dico("D", 6, "DROSSE").
dico("D", 6, "DRUIDE").
dico("D", 6, "DRUPES").
dico("D", 6, "DRUSES").
dico("D", 6, "DRUZES").
dico("D", 6, "DRYADE").
dico("D", 6, "DUALES").
dico("D", 6, "DUCALE").
dico("D", 6, "DUCATS").
dico("D", 6, "DUCAUX").
dico("D", 6, "DUCHES").
dico("D", 6, "DUEGNE").
dico("D", 6, "DUELLE").
dico("D", 6, "DUETTO").
dico("D", 6, "DUGONG").
dico("D", 6, "DUGONS").
dico("D", 6, "DUITAI").
dico("D", 6, "DUITAS").
dico("D", 6, "DUITAT").
dico("D", 6, "DUITEE").
dico("D", 6, "DUITER").
dico("D", 6, "DUITES").
dico("D", 6, "DUITEZ").
dico("D", 6, "DUMENT").
dico("D", 6, "DUMPER").
dico("D", 6, "DUNDEE").
dico("D", 6, "DUODIS").
dico("D", 6, "DUPAIS").
dico("D", 6, "DUPAIT").
dico("D", 6, "DUPANT").
dico("D", 6, "DUPEES").
dico("D", 6, "DUPENT").
dico("D", 6, "DUPERA").
dico("D", 6, "DUPEUR").
dico("D", 6, "DUPIEZ").
dico("D", 6, "DUPLEX").
dico("D", 6, "DUPONS").
dico("D", 6, "DUQUAI").
dico("D", 6, "DUQUAS").
dico("D", 6, "DUQUAT").
dico("D", 6, "DUQUEE").
dico("D", 6, "DUQUEL").
dico("D", 6, "DUQUER").
dico("D", 6, "DUQUES").
dico("D", 6, "DUQUEZ").
dico("D", 6, "DURAIN").
dico("D", 6, "DURAIS").
dico("D", 6, "DURAIT").
dico("D", 6, "DURALE").
dico("D", 6, "DURANT").
dico("D", 6, "DURAUX").
dico("D", 6, "DURCIE").
dico("D", 6, "DURCIR").
dico("D", 6, "DURCIS").
dico("D", 6, "DURCIT").
dico("D", 6, "DUREES").
dico("D", 6, "DURENT").
dico("D", 6, "DURERA").
dico("D", 6, "DURETE").
dico("D", 6, "DURHAM").
dico("D", 6, "DURIAN").
dico("D", 6, "DURIEZ").
dico("D", 6, "DURION").
dico("D", 6, "DURITS").
dico("D", 6, "DURONS").
dico("D", 6, "DUSSES").
dico("D", 6, "DUVETA").
dico("D", 6, "DUVETE").
dico("D", 6, "DUVETS").
dico("D", 6, "DYADES").
dico("D", 6, "DYNAMO").
