dico("D", 8, "DACQUOIS").
dico("D", 8, "DACTYLEE").
dico("D", 8, "DACTYLES").
dico("D", 8, "DACTYLOS").
dico("D", 8, "DADAISME").
dico("D", 8, "DADAISTE").
dico("D", 8, "DAGUAMES").
dico("D", 8, "DAGUASSE").
dico("D", 8, "DAGUATES").
dico("D", 8, "DAGUERAI").
dico("D", 8, "DAGUERAS").
dico("D", 8, "DAGUEREZ").
dico("D", 8, "DAGUIONS").
dico("D", 8, "DAHABIEH").
dico("D", 8, "DAHOMEEN").
dico("D", 8, "DAIGNAIS").
dico("D", 8, "DAIGNAIT").
dico("D", 8, "DAIGNANT").
dico("D", 8, "DAIGNENT").
dico("D", 8, "DAIGNERA").
dico("D", 8, "DAIGNIEZ").
dico("D", 8, "DAIGNONS").
dico("D", 8, "DAIKIRIS").
dico("D", 8, "DAIQUIRI").
dico("D", 8, "DAKAROIS").
dico("D", 8, "DALLAGES").
dico("D", 8, "DALLAMES").
dico("D", 8, "DALLASSE").
dico("D", 8, "DALLATES").
dico("D", 8, "DALLERAI").
dico("D", 8, "DALLERAS").
dico("D", 8, "DALLEREZ").
dico("D", 8, "DALLEURS").
dico("D", 8, "DALLIONS").
dico("D", 8, "DALMATES").
dico("D", 8, "DAMAIENT").
dico("D", 8, "DAMASSAI").
dico("D", 8, "DAMASSAS").
dico("D", 8, "DAMASSAT").
dico("D", 8, "DAMASSEE").
dico("D", 8, "DAMASSER").
dico("D", 8, "DAMASSES").
dico("D", 8, "DAMASSEZ").
dico("D", 8, "DAMERAIS").
dico("D", 8, "DAMERAIT").
dico("D", 8, "DAMERENT").
dico("D", 8, "DAMERIEZ").
dico("D", 8, "DAMERONS").
dico("D", 8, "DAMERONT").
dico("D", 8, "DAMEUSES").
dico("D", 8, "DAMNABLE").
dico("D", 8, "DAMNAMES").
dico("D", 8, "DAMNASSE").
dico("D", 8, "DAMNATES").
dico("D", 8, "DAMNERAI").
dico("D", 8, "DAMNERAS").
dico("D", 8, "DAMNEREZ").
dico("D", 8, "DAMNIONS").
dico("D", 8, "DANAIDES").
dico("D", 8, "DANCINGS").
dico("D", 8, "DANDINAI").
dico("D", 8, "DANDINAS").
dico("D", 8, "DANDINAT").
dico("D", 8, "DANDINEE").
dico("D", 8, "DANDINER").
dico("D", 8, "DANDINES").
dico("D", 8, "DANDINEZ").
dico("D", 8, "DANDYSME").
dico("D", 8, "DANIENNE").
dico("D", 8, "DANOISES").
dico("D", 8, "DANSABLE").
dico("D", 8, "DANSAMES").
dico("D", 8, "DANSANTE").
dico("D", 8, "DANSANTS").
dico("D", 8, "DANSASSE").
dico("D", 8, "DANSATES").
dico("D", 8, "DANSERAI").
dico("D", 8, "DANSERAS").
dico("D", 8, "DANSEREZ").
dico("D", 8, "DANSEURS").
dico("D", 8, "DANSEUSE").
dico("D", 8, "DANSIONS").
dico("D", 8, "DANSOTAI").
dico("D", 8, "DANSOTAS").
dico("D", 8, "DANSOTAT").
dico("D", 8, "DANSOTER").
dico("D", 8, "DANSOTES").
dico("D", 8, "DANSOTEZ").
dico("D", 8, "DANSOTTA").
dico("D", 8, "DANSOTTE").
dico("D", 8, "DANUBIEN").
dico("D", 8, "DAPHNIES").
dico("D", 8, "DARAISES").
dico("D", 8, "DARBOUKA").
dico("D", 8, "DARBYSME").
dico("D", 8, "DARBYSTE").
dico("D", 8, "DARDAMES").
dico("D", 8, "DARDASSE").
dico("D", 8, "DARDATES").
dico("D", 8, "DARDERAI").
dico("D", 8, "DARDERAS").
dico("D", 8, "DARDEREZ").
dico("D", 8, "DARDIONS").
dico("D", 8, "DARIOLES").
dico("D", 8, "DARIQUES").
dico("D", 8, "DARSANAS").
dico("D", 8, "DARSHANA").
dico("D", 8, "DARSHANS").
dico("D", 8, "DARTREUX").
dico("D", 8, "DARTROSE").
dico("D", 8, "DASYURES").
dico("D", 8, "DATABLES").
dico("D", 8, "DATAIENT").
dico("D", 8, "DATAIRES").
dico("D", 8, "DATASSES").
dico("D", 8, "DATATION").
dico("D", 8, "DATERAIS").
dico("D", 8, "DATERAIT").
dico("D", 8, "DATERENT").
dico("D", 8, "DATERIES").
dico("D", 8, "DATERIEZ").
dico("D", 8, "DATERONS").
dico("D", 8, "DATERONT").
dico("D", 8, "DATEUSES").
dico("D", 8, "DATTIERS").
dico("D", 8, "DAUBAMES").
dico("D", 8, "DAUBASSE").
dico("D", 8, "DAUBATES").
dico("D", 8, "DAUBERAI").
dico("D", 8, "DAUBERAS").
dico("D", 8, "DAUBEREZ").
dico("D", 8, "DAUBEURS").
dico("D", 8, "DAUBEUSE").
dico("D", 8, "DAUBIERE").
dico("D", 8, "DAUBIONS").
dico("D", 8, "DAUPHINE").
dico("D", 8, "DAUPHINS").
dico("D", 8, "DAURADES").
dico("D", 8, "DAVIDIEN").
dico("D", 8, "DAZIBAOS").
dico("D", 8, "DEALAMES").
dico("D", 8, "DEALASSE").
dico("D", 8, "DEALATES").
dico("D", 8, "DEALERAI").
dico("D", 8, "DEALERAS").
dico("D", 8, "DEALEREZ").
dico("D", 8, "DEALEURS").
dico("D", 8, "DEALEUSE").
dico("D", 8, "DEALIONS").
dico("D", 8, "DEAMBULA").
dico("D", 8, "DEAMBULE").
dico("D", 8, "DEBACHAI").
dico("D", 8, "DEBACHAS").
dico("D", 8, "DEBACHAT").
dico("D", 8, "DEBACHEE").
dico("D", 8, "DEBACHER").
dico("D", 8, "DEBACHES").
dico("D", 8, "DEBACHEZ").
dico("D", 8, "DEBACLAI").
dico("D", 8, "DEBACLAS").
dico("D", 8, "DEBACLAT").
dico("D", 8, "DEBACLEE").
dico("D", 8, "DEBACLER").
dico("D", 8, "DEBACLES").
dico("D", 8, "DEBACLEZ").
dico("D", 8, "DEBADGEA").
dico("D", 8, "DEBADGEE").
dico("D", 8, "DEBADGER").
dico("D", 8, "DEBADGES").
dico("D", 8, "DEBADGEZ").
dico("D", 8, "DEBALLAI").
dico("D", 8, "DEBALLAS").
dico("D", 8, "DEBALLAT").
dico("D", 8, "DEBALLEE").
dico("D", 8, "DEBALLER").
dico("D", 8, "DEBALLES").
dico("D", 8, "DEBALLEZ").
dico("D", 8, "DEBANDAI").
dico("D", 8, "DEBANDAS").
dico("D", 8, "DEBANDAT").
dico("D", 8, "DEBANDEE").
dico("D", 8, "DEBANDER").
dico("D", 8, "DEBANDES").
dico("D", 8, "DEBANDEZ").
dico("D", 8, "DEBARDAI").
dico("D", 8, "DEBARDAS").
dico("D", 8, "DEBARDAT").
dico("D", 8, "DEBARDEE").
dico("D", 8, "DEBARDER").
dico("D", 8, "DEBARDES").
dico("D", 8, "DEBARDEZ").
dico("D", 8, "DEBARQUA").
dico("D", 8, "DEBARQUE").
dico("D", 8, "DEBARRAI").
dico("D", 8, "DEBARRAS").
dico("D", 8, "DEBARRAT").
dico("D", 8, "DEBARREE").
dico("D", 8, "DEBARRER").
dico("D", 8, "DEBARRES").
dico("D", 8, "DEBARREZ").
dico("D", 8, "DEBATAIS").
dico("D", 8, "DEBATAIT").
dico("D", 8, "DEBATANT").
dico("D", 8, "DEBATEES").
dico("D", 8, "DEBATENT").
dico("D", 8, "DEBATERA").
dico("D", 8, "DEBATERS").
dico("D", 8, "DEBATIES").
dico("D", 8, "DEBATIEZ").
dico("D", 8, "DEBATIRA").
dico("D", 8, "DEBATONS").
dico("D", 8, "DEBATTES").
dico("D", 8, "DEBATTEZ").
dico("D", 8, "DEBATTIS").
dico("D", 8, "DEBATTIT").
dico("D", 8, "DEBATTRA").
dico("D", 8, "DEBATTRE").
dico("D", 8, "DEBATTUE").
dico("D", 8, "DEBATTUS").
dico("D", 8, "DEBAUCHA").
dico("D", 8, "DEBAUCHE").
dico("D", 8, "DEBECTAI").
dico("D", 8, "DEBECTAS").
dico("D", 8, "DEBECTAT").
dico("D", 8, "DEBECTEE").
dico("D", 8, "DEBECTER").
dico("D", 8, "DEBECTES").
dico("D", 8, "DEBECTEZ").
dico("D", 8, "DEBILITA").
dico("D", 8, "DEBILITE").
dico("D", 8, "DEBINAGE").
dico("D", 8, "DEBINAIS").
dico("D", 8, "DEBINAIT").
dico("D", 8, "DEBINANT").
dico("D", 8, "DEBINEES").
dico("D", 8, "DEBINENT").
dico("D", 8, "DEBINERA").
dico("D", 8, "DEBINEUR").
dico("D", 8, "DEBINIEZ").
dico("D", 8, "DEBINONS").
dico("D", 8, "DEBITAGE").
dico("D", 8, "DEBITAIS").
dico("D", 8, "DEBITAIT").
dico("D", 8, "DEBITANT").
dico("D", 8, "DEBITEES").
dico("D", 8, "DEBITENT").
dico("D", 8, "DEBITERA").
dico("D", 8, "DEBITEUR").
dico("D", 8, "DEBITIEZ").
dico("D", 8, "DEBITONS").
dico("D", 8, "DEBLAIES").
dico("D", 8, "DEBLAYAI").
dico("D", 8, "DEBLAYAS").
dico("D", 8, "DEBLAYAT").
dico("D", 8, "DEBLAYEE").
dico("D", 8, "DEBLAYER").
dico("D", 8, "DEBLAYES").
dico("D", 8, "DEBLAYEZ").
dico("D", 8, "DEBLOQUA").
dico("D", 8, "DEBLOQUE").
dico("D", 8, "DEBOBINA").
dico("D", 8, "DEBOBINE").
dico("D", 8, "DEBOGAGE").
dico("D", 8, "DEBOGUAI").
dico("D", 8, "DEBOGUAS").
dico("D", 8, "DEBOGUAT").
dico("D", 8, "DEBOGUEE").
dico("D", 8, "DEBOGUER").
dico("D", 8, "DEBOGUES").
dico("D", 8, "DEBOGUEZ").
dico("D", 8, "DEBOIRES").
dico("D", 8, "DEBOISAI").
dico("D", 8, "DEBOISAS").
dico("D", 8, "DEBOISAT").
dico("D", 8, "DEBOISEE").
dico("D", 8, "DEBOISER").
dico("D", 8, "DEBOISES").
dico("D", 8, "DEBOISEZ").
dico("D", 8, "DEBOITAI").
dico("D", 8, "DEBOITAS").
dico("D", 8, "DEBOITAT").
dico("D", 8, "DEBOITEE").
dico("D", 8, "DEBOITER").
dico("D", 8, "DEBOITES").
dico("D", 8, "DEBOITEZ").
dico("D", 8, "DEBONDAI").
dico("D", 8, "DEBONDAS").
dico("D", 8, "DEBONDAT").
dico("D", 8, "DEBONDEE").
dico("D", 8, "DEBONDER").
dico("D", 8, "DEBONDES").
dico("D", 8, "DEBONDEZ").
dico("D", 8, "DEBORDAI").
dico("D", 8, "DEBORDAS").
dico("D", 8, "DEBORDAT").
dico("D", 8, "DEBORDEE").
dico("D", 8, "DEBORDER").
dico("D", 8, "DEBORDES").
dico("D", 8, "DEBORDEZ").
dico("D", 8, "DEBOSSAI").
dico("D", 8, "DEBOSSAS").
dico("D", 8, "DEBOSSAT").
dico("D", 8, "DEBOSSEE").
dico("D", 8, "DEBOSSER").
dico("D", 8, "DEBOSSES").
dico("D", 8, "DEBOSSEZ").
dico("D", 8, "DEBOTTAI").
dico("D", 8, "DEBOTTAS").
dico("D", 8, "DEBOTTAT").
dico("D", 8, "DEBOTTEE").
dico("D", 8, "DEBOTTER").
dico("D", 8, "DEBOTTES").
dico("D", 8, "DEBOTTEZ").
dico("D", 8, "DEBOUCHA").
dico("D", 8, "DEBOUCHE").
dico("D", 8, "DEBOUCLA").
dico("D", 8, "DEBOUCLE").
dico("D", 8, "DEBOULAI").
dico("D", 8, "DEBOULAS").
dico("D", 8, "DEBOULAT").
dico("D", 8, "DEBOULEE").
dico("D", 8, "DEBOULER").
dico("D", 8, "DEBOULES").
dico("D", 8, "DEBOULEZ").
dico("D", 8, "DEBOUQUA").
dico("D", 8, "DEBOUQUE").
dico("D", 8, "DEBOURBA").
dico("D", 8, "DEBOURBE").
dico("D", 8, "DEBOURRA").
dico("D", 8, "DEBOURRE").
dico("D", 8, "DEBOURSA").
dico("D", 8, "DEBOURSE").
dico("D", 8, "DEBOUTAI").
dico("D", 8, "DEBOUTAS").
dico("D", 8, "DEBOUTAT").
dico("D", 8, "DEBOUTEE").
dico("D", 8, "DEBOUTER").
dico("D", 8, "DEBOUTES").
dico("D", 8, "DEBOUTEZ").
dico("D", 8, "DEBRAIES").
dico("D", 8, "DEBRASAI").
dico("D", 8, "DEBRASAS").
dico("D", 8, "DEBRASAT").
dico("D", 8, "DEBRASEE").
dico("D", 8, "DEBRASER").
dico("D", 8, "DEBRASES").
dico("D", 8, "DEBRASEZ").
dico("D", 8, "DEBRAYAI").
dico("D", 8, "DEBRAYAS").
dico("D", 8, "DEBRAYAT").
dico("D", 8, "DEBRAYEE").
dico("D", 8, "DEBRAYER").
dico("D", 8, "DEBRAYES").
dico("D", 8, "DEBRAYEZ").
dico("D", 8, "DEBRIDAI").
dico("D", 8, "DEBRIDAS").
dico("D", 8, "DEBRIDAT").
dico("D", 8, "DEBRIDEE").
dico("D", 8, "DEBRIDER").
dico("D", 8, "DEBRIDES").
dico("D", 8, "DEBRIDEZ").
dico("D", 8, "DEBRIEFA").
dico("D", 8, "DEBRIEFE").
dico("D", 8, "DEBROCHA").
dico("D", 8, "DEBROCHE").
dico("D", 8, "DEBRONZA").
dico("D", 8, "DEBRONZE").
dico("D", 8, "DEBRUTIE").
dico("D", 8, "DEBRUTIR").
dico("D", 8, "DEBRUTIS").
dico("D", 8, "DEBRUTIT").
dico("D", 8, "DEBUCHAI").
dico("D", 8, "DEBUCHAS").
dico("D", 8, "DEBUCHAT").
dico("D", 8, "DEBUCHEE").
dico("D", 8, "DEBUCHER").
dico("D", 8, "DEBUCHES").
dico("D", 8, "DEBUCHEZ").
dico("D", 8, "DEBUGGAI").
dico("D", 8, "DEBUGGAS").
dico("D", 8, "DEBUGGAT").
dico("D", 8, "DEBUGGEE").
dico("D", 8, "DEBUGGER").
dico("D", 8, "DEBUGGES").
dico("D", 8, "DEBUGGEZ").
dico("D", 8, "DEBUSQUA").
dico("D", 8, "DEBUSQUE").
dico("D", 8, "DEBUTAIS").
dico("D", 8, "DEBUTAIT").
dico("D", 8, "DEBUTANT").
dico("D", 8, "DEBUTEES").
dico("D", 8, "DEBUTENT").
dico("D", 8, "DEBUTERA").
dico("D", 8, "DEBUTIEZ").
dico("D", 8, "DEBUTONS").
dico("D", 8, "DECADENT").
dico("D", 8, "DECADRAI").
dico("D", 8, "DECADRAS").
dico("D", 8, "DECADRAT").
dico("D", 8, "DECADREE").
dico("D", 8, "DECADRER").
dico("D", 8, "DECADRES").
dico("D", 8, "DECADREZ").
dico("D", 8, "DECAEDRE").
dico("D", 8, "DECAGONE").
dico("D", 8, "DECAISSA").
dico("D", 8, "DECAISSE").
dico("D", 8, "DECALAGE").
dico("D", 8, "DECALAIS").
dico("D", 8, "DECALAIT").
dico("D", 8, "DECALANT").
dico("D", 8, "DECALEES").
dico("D", 8, "DECALENT").
dico("D", 8, "DECALERA").
dico("D", 8, "DECALIEZ").
dico("D", 8, "DECALONS").
dico("D", 8, "DECALQUA").
dico("D", 8, "DECALQUE").
dico("D", 8, "DECAMPAI").
dico("D", 8, "DECAMPAS").
dico("D", 8, "DECAMPAT").
dico("D", 8, "DECAMPEE").
dico("D", 8, "DECAMPER").
dico("D", 8, "DECAMPES").
dico("D", 8, "DECAMPEZ").
dico("D", 8, "DECANALE").
dico("D", 8, "DECANATS").
dico("D", 8, "DECANAUX").
dico("D", 8, "DECANTAI").
dico("D", 8, "DECANTAS").
dico("D", 8, "DECANTAT").
dico("D", 8, "DECANTEE").
dico("D", 8, "DECANTER").
dico("D", 8, "DECANTES").
dico("D", 8, "DECANTEZ").
dico("D", 8, "DECAPAGE").
dico("D", 8, "DECAPAIS").
dico("D", 8, "DECAPAIT").
dico("D", 8, "DECAPANT").
dico("D", 8, "DECAPEES").
dico("D", 8, "DECAPELA").
dico("D", 8, "DECAPELE").
dico("D", 8, "DECAPENT").
dico("D", 8, "DECAPERA").
dico("D", 8, "DECAPEUR").
dico("D", 8, "DECAPIEZ").
dico("D", 8, "DECAPITA").
dico("D", 8, "DECAPITE").
dico("D", 8, "DECAPODE").
dico("D", 8, "DECAPOLE").
dico("D", 8, "DECAPONS").
dico("D", 8, "DECAPOTA").
dico("D", 8, "DECAPOTE").
dico("D", 8, "DECATIES").
dico("D", 8, "DECATIRA").
dico("D", 8, "DECAUSAI").
dico("D", 8, "DECAUSAS").
dico("D", 8, "DECAUSAT").
dico("D", 8, "DECAUSEE").
dico("D", 8, "DECAUSER").
dico("D", 8, "DECAUSES").
dico("D", 8, "DECAUSEZ").
dico("D", 8, "DECAVAIS").
dico("D", 8, "DECAVAIT").
dico("D", 8, "DECAVANT").
dico("D", 8, "DECAVEES").
dico("D", 8, "DECAVENT").
dico("D", 8, "DECAVERA").
dico("D", 8, "DECAVIEZ").
dico("D", 8, "DECAVONS").
dico("D", 8, "DECEDAIS").
dico("D", 8, "DECEDAIT").
dico("D", 8, "DECEDANT").
dico("D", 8, "DECEDEES").
dico("D", 8, "DECEDENT").
dico("D", 8, "DECEDERA").
dico("D", 8, "DECEDIEZ").
dico("D", 8, "DECEDONS").
dico("D", 8, "DECELAIS").
dico("D", 8, "DECELAIT").
dico("D", 8, "DECELANT").
dico("D", 8, "DECELEES").
dico("D", 8, "DECELENT").
dico("D", 8, "DECELERA").
dico("D", 8, "DECELERE").
dico("D", 8, "DECELIEZ").
dico("D", 8, "DECELONS").
dico("D", 8, "DECEMBRE").
dico("D", 8, "DECEMVIR").
dico("D", 8, "DECENCES").
dico("D", 8, "DECENNAL").
dico("D", 8, "DECENNIE").
dico("D", 8, "DECENTES").
dico("D", 8, "DECENTRA").
dico("D", 8, "DECENTRE").
dico("D", 8, "DECERCLA").
dico("D", 8, "DECERCLE").
dico("D", 8, "DECERNAI").
dico("D", 8, "DECERNAS").
dico("D", 8, "DECERNAT").
dico("D", 8, "DECERNEE").
dico("D", 8, "DECERNER").
dico("D", 8, "DECERNES").
dico("D", 8, "DECERNEZ").
dico("D", 8, "DECEVAIS").
dico("D", 8, "DECEVAIT").
dico("D", 8, "DECEVANT").
dico("D", 8, "DECEVIEZ").
dico("D", 8, "DECEVOIR").
dico("D", 8, "DECEVONS").
dico("D", 8, "DECEVRAI").
dico("D", 8, "DECEVRAS").
dico("D", 8, "DECEVREZ").
dico("D", 8, "DECHAINA").
dico("D", 8, "DECHAINE").
dico("D", 8, "DECHANTA").
dico("D", 8, "DECHANTE").
dico("D", 8, "DECHANTS").
dico("D", 8, "DECHARGE").
dico("D", 8, "DECHARNA").
dico("D", 8, "DECHARNE").
dico("D", 8, "DECHAUMA").
dico("D", 8, "DECHAUME").
dico("D", 8, "DECHIRAI").
dico("D", 8, "DECHIRAS").
dico("D", 8, "DECHIRAT").
dico("D", 8, "DECHIREE").
dico("D", 8, "DECHIRER").
dico("D", 8, "DECHIRES").
dico("D", 8, "DECHIREZ").
dico("D", 8, "DECHOIES").
dico("D", 8, "DECHOIRA").
dico("D", 8, "DECHOYEZ").
dico("D", 8, "DECHUMES").
dico("D", 8, "DECHUSSE").
dico("D", 8, "DECHUTES").
dico("D", 8, "DECIBELS").
dico("D", 8, "DECIDAIS").
dico("D", 8, "DECIDAIT").
dico("D", 8, "DECIDANT").
dico("D", 8, "DECIDEES").
dico("D", 8, "DECIDENT").
dico("D", 8, "DECIDERA").
dico("D", 8, "DECIDEUR").
dico("D", 8, "DECIDIEZ").
dico("D", 8, "DECIDONS").
dico("D", 8, "DECIDUAL").
dico("D", 8, "DECIDUES").
dico("D", 8, "DECILAGE").
dico("D", 8, "DECIMAIS").
dico("D", 8, "DECIMAIT").
dico("D", 8, "DECIMALE").
dico("D", 8, "DECIMANT").
dico("D", 8, "DECIMAUX").
dico("D", 8, "DECIMEES").
dico("D", 8, "DECIMENT").
dico("D", 8, "DECIMERA").
dico("D", 8, "DECIMIEZ").
dico("D", 8, "DECIMONS").
dico("D", 8, "DECINTRA").
dico("D", 8, "DECINTRE").
dico("D", 8, "DECISIFS").
dico("D", 8, "DECISION").
dico("D", 8, "DECISIVE").
dico("D", 8, "DECLAMAI").
dico("D", 8, "DECLAMAS").
dico("D", 8, "DECLAMAT").
dico("D", 8, "DECLAMEE").
dico("D", 8, "DECLAMER").
dico("D", 8, "DECLAMES").
dico("D", 8, "DECLAMEZ").
dico("D", 8, "DECLARAI").
dico("D", 8, "DECLARAS").
dico("D", 8, "DECLARAT").
dico("D", 8, "DECLAREE").
dico("D", 8, "DECLARER").
dico("D", 8, "DECLARES").
dico("D", 8, "DECLAREZ").
dico("D", 8, "DECLASSA").
dico("D", 8, "DECLASSE").
dico("D", 8, "DECLINAI").
dico("D", 8, "DECLINAS").
dico("D", 8, "DECLINAT").
dico("D", 8, "DECLINEE").
dico("D", 8, "DECLINER").
dico("D", 8, "DECLINES").
dico("D", 8, "DECLINEZ").
dico("D", 8, "DECLIVES").
dico("D", 8, "DECLORAI").
dico("D", 8, "DECLORAS").
dico("D", 8, "DECLOREZ").
dico("D", 8, "DECLOSES").
dico("D", 8, "DECLOSEZ").
dico("D", 8, "DECLOUAI").
dico("D", 8, "DECLOUAS").
dico("D", 8, "DECLOUAT").
dico("D", 8, "DECLOUEE").
dico("D", 8, "DECLOUER").
dico("D", 8, "DECLOUES").
dico("D", 8, "DECLOUEZ").
dico("D", 8, "DECOCHAI").
dico("D", 8, "DECOCHAS").
dico("D", 8, "DECOCHAT").
dico("D", 8, "DECOCHEE").
dico("D", 8, "DECOCHER").
dico("D", 8, "DECOCHES").
dico("D", 8, "DECOCHEZ").
dico("D", 8, "DECOCTES").
dico("D", 8, "DECODAGE").
dico("D", 8, "DECODAIS").
dico("D", 8, "DECODAIT").
dico("D", 8, "DECODANT").
dico("D", 8, "DECODEES").
dico("D", 8, "DECODENT").
dico("D", 8, "DECODERA").
dico("D", 8, "DECODEUR").
dico("D", 8, "DECODIEZ").
dico("D", 8, "DECODONS").
dico("D", 8, "DECOFFRA").
dico("D", 8, "DECOFFRE").
dico("D", 8, "DECOIFFA").
dico("D", 8, "DECOIFFE").
dico("D", 8, "DECOINCA").
dico("D", 8, "DECOINCE").
dico("D", 8, "DECOIVES").
dico("D", 8, "DECOLERA").
dico("D", 8, "DECOLERE").
dico("D", 8, "DECOLLAI").
dico("D", 8, "DECOLLAS").
dico("D", 8, "DECOLLAT").
dico("D", 8, "DECOLLEE").
dico("D", 8, "DECOLLER").
dico("D", 8, "DECOLLES").
dico("D", 8, "DECOLLEZ").
dico("D", 8, "DECOLORA").
dico("D", 8, "DECOLORE").
dico("D", 8, "DECOMMET").
dico("D", 8, "DECOMMIS").
dico("D", 8, "DECOMMIT").
dico("D", 8, "DECOMPTA").
dico("D", 8, "DECOMPTE").
dico("D", 8, "DECONFIS").
dico("D", 8, "DECONFIT").
dico("D", 8, "DECONNAI").
dico("D", 8, "DECONNAS").
dico("D", 8, "DECONNAT").
dico("D", 8, "DECONNER").
dico("D", 8, "DECONNES").
dico("D", 8, "DECONNEZ").
dico("D", 8, "DECORAIS").
dico("D", 8, "DECORAIT").
dico("D", 8, "DECORANT").
dico("D", 8, "DECORDAI").
dico("D", 8, "DECORDAS").
dico("D", 8, "DECORDAT").
dico("D", 8, "DECORDEE").
dico("D", 8, "DECORDER").
dico("D", 8, "DECORDES").
dico("D", 8, "DECORDEZ").
dico("D", 8, "DECOREES").
dico("D", 8, "DECORENT").
dico("D", 8, "DECORERA").
dico("D", 8, "DECORIEZ").
dico("D", 8, "DECORNAI").
dico("D", 8, "DECORNAS").
dico("D", 8, "DECORNAT").
dico("D", 8, "DECORNEE").
dico("D", 8, "DECORNER").
dico("D", 8, "DECORNES").
dico("D", 8, "DECORNEZ").
dico("D", 8, "DECORONS").
dico("D", 8, "DECORUMS").
dico("D", 8, "DECOTAIS").
dico("D", 8, "DECOTAIT").
dico("D", 8, "DECOTANT").
dico("D", 8, "DECOTEES").
dico("D", 8, "DECOTENT").
dico("D", 8, "DECOTERA").
dico("D", 8, "DECOTIEZ").
dico("D", 8, "DECOTONS").
dico("D", 8, "DECOUCHA").
dico("D", 8, "DECOUCHE").
dico("D", 8, "DECOUDRA").
dico("D", 8, "DECOUDRE").
dico("D", 8, "DECOULAI").
dico("D", 8, "DECOULAS").
dico("D", 8, "DECOULAT").
dico("D", 8, "DECOULER").
dico("D", 8, "DECOULES").
dico("D", 8, "DECOULEZ").
dico("D", 8, "DECOUPAI").
dico("D", 8, "DECOUPAS").
dico("D", 8, "DECOUPAT").
dico("D", 8, "DECOUPEE").
dico("D", 8, "DECOUPER").
dico("D", 8, "DECOUPES").
dico("D", 8, "DECOUPEZ").
dico("D", 8, "DECOUPLA").
dico("D", 8, "DECOUPLE").
dico("D", 8, "DECOUSES").
dico("D", 8, "DECOUSEZ").
dico("D", 8, "DECOUSIS").
dico("D", 8, "DECOUSIT").
dico("D", 8, "DECOUSUE").
dico("D", 8, "DECOUSUS").
dico("D", 8, "DECOUVRE").
dico("D", 8, "DECRASSA").
dico("D", 8, "DECRASSE").
dico("D", 8, "DECREPAI").
dico("D", 8, "DECREPAS").
dico("D", 8, "DECREPAT").
dico("D", 8, "DECREPEE").
dico("D", 8, "DECREPER").
dico("D", 8, "DECREPES").
dico("D", 8, "DECREPEZ").
dico("D", 8, "DECREPIE").
dico("D", 8, "DECREPIR").
dico("D", 8, "DECREPIS").
dico("D", 8, "DECREPIT").
dico("D", 8, "DECRETAI").
dico("D", 8, "DECRETAS").
dico("D", 8, "DECRETAT").
dico("D", 8, "DECRETEE").
dico("D", 8, "DECRETER").
dico("D", 8, "DECRETES").
dico("D", 8, "DECRETEZ").
dico("D", 8, "DECREUSA").
dico("D", 8, "DECREUSE").
dico("D", 8, "DECRIAIS").
dico("D", 8, "DECRIAIT").
dico("D", 8, "DECRIANT").
dico("D", 8, "DECRIEES").
dico("D", 8, "DECRIENT").
dico("D", 8, "DECRIERA").
dico("D", 8, "DECRIIEZ").
dico("D", 8, "DECRIONS").
dico("D", 8, "DECRIRAI").
dico("D", 8, "DECRIRAS").
dico("D", 8, "DECRIREZ").
dico("D", 8, "DECRISPA").
dico("D", 8, "DECRISPE").
dico("D", 8, "DECRITES").
dico("D", 8, "DECRIVES").
dico("D", 8, "DECRIVEZ").
dico("D", 8, "DECRIVIS").
dico("D", 8, "DECRIVIT").
dico("D", 8, "DECROCHA").
dico("D", 8, "DECROCHE").
dico("D", 8, "DECROISA").
dico("D", 8, "DECROISE").
dico("D", 8, "DECROITS").
dico("D", 8, "DECROTTA").
dico("D", 8, "DECROTTE").
dico("D", 8, "DECRUAGE").
dico("D", 8, "DECRUAIS").
dico("D", 8, "DECRUAIT").
dico("D", 8, "DECRUANT").
dico("D", 8, "DECRUEES").
dico("D", 8, "DECRUENT").
dico("D", 8, "DECRUERA").
dico("D", 8, "DECRUIEZ").
dico("D", 8, "DECRUMES").
dico("D", 8, "DECRUONS").
dico("D", 8, "DECRUSAI").
dico("D", 8, "DECRUSAS").
dico("D", 8, "DECRUSAT").
dico("D", 8, "DECRUSEE").
dico("D", 8, "DECRUSER").
dico("D", 8, "DECRUSES").
dico("D", 8, "DECRUSEZ").
dico("D", 8, "DECRUSSE").
dico("D", 8, "DECRUTES").
dico("D", 8, "DECRYPTA").
dico("D", 8, "DECRYPTE").
dico("D", 8, "DECUIRAI").
dico("D", 8, "DECUIRAS").
dico("D", 8, "DECUIREZ").
dico("D", 8, "DECUISES").
dico("D", 8, "DECUISEZ").
dico("D", 8, "DECUISIS").
dico("D", 8, "DECUISIT").
dico("D", 8, "DECUITES").
dico("D", 8, "DECUIVRA").
dico("D", 8, "DECUIVRE").
dico("D", 8, "DECUMULS").
dico("D", 8, "DECUPLAI").
dico("D", 8, "DECUPLAS").
dico("D", 8, "DECUPLAT").
dico("D", 8, "DECUPLEE").
dico("D", 8, "DECUPLER").
dico("D", 8, "DECUPLES").
dico("D", 8, "DECUPLEZ").
dico("D", 8, "DECURENT").
dico("D", 8, "DECURIES").
dico("D", 8, "DECURION").
dico("D", 8, "DECUSSEE").
dico("D", 8, "DECUSSES").
dico("D", 8, "DECUVAGE").
dico("D", 8, "DECUVAIS").
dico("D", 8, "DECUVAIT").
dico("D", 8, "DECUVANT").
dico("D", 8, "DECUVEES").
dico("D", 8, "DECUVENT").
dico("D", 8, "DECUVERA").
dico("D", 8, "DECUVIEZ").
dico("D", 8, "DECUVONS").
dico("D", 8, "DEDAIGNA").
dico("D", 8, "DEDAIGNE").
dico("D", 8, "DEDALEEN").
dico("D", 8, "DEDIAMES").
dico("D", 8, "DEDIASSE").
dico("D", 8, "DEDIATES").
dico("D", 8, "DEDICACA").
dico("D", 8, "DEDICACE").
dico("D", 8, "DEDIERAI").
dico("D", 8, "DEDIERAS").
dico("D", 8, "DEDIEREZ").
dico("D", 8, "DEDIIONS").
dico("D", 8, "DEDIRAIS").
dico("D", 8, "DEDIRAIT").
dico("D", 8, "DEDIRENT").
dico("D", 8, "DEDIRIEZ").
dico("D", 8, "DEDIRONS").
dico("D", 8, "DEDIRONT").
dico("D", 8, "DEDISAIS").
dico("D", 8, "DEDISAIT").
dico("D", 8, "DEDISANT").
dico("D", 8, "DEDISENT").
dico("D", 8, "DEDISIEZ").
dico("D", 8, "DEDISONS").
dico("D", 8, "DEDISSES").
dico("D", 8, "DEDORAGE").
dico("D", 8, "DEDORAIS").
dico("D", 8, "DEDORAIT").
dico("D", 8, "DEDORANT").
dico("D", 8, "DEDOREES").
dico("D", 8, "DEDORENT").
dico("D", 8, "DEDORERA").
dico("D", 8, "DEDORIEZ").
dico("D", 8, "DEDORONS").
dico("D", 8, "DEDORURE").
dico("D", 8, "DEDOUANA").
dico("D", 8, "DEDOUANE").
dico("D", 8, "DEDOUBLA").
dico("D", 8, "DEDOUBLE").
dico("D", 8, "DEDUCTIF").
dico("D", 8, "DEDUIRAI").
dico("D", 8, "DEDUIRAS").
dico("D", 8, "DEDUIREZ").
dico("D", 8, "DEDUISES").
dico("D", 8, "DEDUISEZ").
dico("D", 8, "DEDUISIS").
dico("D", 8, "DEDUISIT").
dico("D", 8, "DEDUITES").
dico("D", 8, "DEFAILLE").
dico("D", 8, "DEFAILLI").
dico("D", 8, "DEFAITES").
dico("D", 8, "DEFALQUA").
dico("D", 8, "DEFALQUE").
dico("D", 8, "DEFANANT").
dico("D", 8, "DEFASSES").
dico("D", 8, "DEFAUSSA").
dico("D", 8, "DEFAUSSE").
dico("D", 8, "DEFAVEUR").
dico("D", 8, "DEFECTIF").
dico("D", 8, "DEFENDES").
dico("D", 8, "DEFENDEZ").
dico("D", 8, "DEFENDIS").
dico("D", 8, "DEFENDIT").
dico("D", 8, "DEFENDRA").
dico("D", 8, "DEFENDRE").
dico("D", 8, "DEFENDUE").
dico("D", 8, "DEFENDUS").
dico("D", 8, "DEFENSES").
dico("D", 8, "DEFENSIF").
dico("D", 8, "DEFEQUAI").
dico("D", 8, "DEFEQUAS").
dico("D", 8, "DEFEQUAT").
dico("D", 8, "DEFEQUEE").
dico("D", 8, "DEFEQUER").
dico("D", 8, "DEFEQUES").
dico("D", 8, "DEFEQUEZ").
dico("D", 8, "DEFERAIS").
dico("D", 8, "DEFERAIT").
dico("D", 8, "DEFERANT").
dico("D", 8, "DEFEREES").
dico("D", 8, "DEFERENT").
dico("D", 8, "DEFERERA").
dico("D", 8, "DEFERIEZ").
dico("D", 8, "DEFERLAI").
dico("D", 8, "DEFERLAS").
dico("D", 8, "DEFERLAT").
dico("D", 8, "DEFERLEE").
dico("D", 8, "DEFERLER").
dico("D", 8, "DEFERLES").
dico("D", 8, "DEFERLEZ").
dico("D", 8, "DEFERONS").
dico("D", 8, "DEFERONT").
dico("D", 8, "DEFERRAI").
dico("D", 8, "DEFERRAS").
dico("D", 8, "DEFERRAT").
dico("D", 8, "DEFERREE").
dico("D", 8, "DEFERRER").
dico("D", 8, "DEFERRES").
dico("D", 8, "DEFERREZ").
dico("D", 8, "DEFEUTRA").
dico("D", 8, "DEFEUTRE").
dico("D", 8, "DEFIAMES").
dico("D", 8, "DEFIANCE").
dico("D", 8, "DEFIANTE").
dico("D", 8, "DEFIANTS").
dico("D", 8, "DEFIASSE").
dico("D", 8, "DEFIATES").
dico("D", 8, "DEFIBRAI").
dico("D", 8, "DEFIBRAS").
dico("D", 8, "DEFIBRAT").
dico("D", 8, "DEFIBREE").
dico("D", 8, "DEFIBRER").
dico("D", 8, "DEFIBRES").
dico("D", 8, "DEFIBREZ").
dico("D", 8, "DEFICELA").
dico("D", 8, "DEFICELE").
dico("D", 8, "DEFICITS").
dico("D", 8, "DEFIERAI").
dico("D", 8, "DEFIERAS").
dico("D", 8, "DEFIEREZ").
dico("D", 8, "DEFIGEAI").
dico("D", 8, "DEFIGEAS").
dico("D", 8, "DEFIGEAT").
dico("D", 8, "DEFIGEES").
dico("D", 8, "DEFIGENT").
dico("D", 8, "DEFIGERA").
dico("D", 8, "DEFIGIEZ").
dico("D", 8, "DEFIGURA").
dico("D", 8, "DEFIGURE").
dico("D", 8, "DEFIIONS").
dico("D", 8, "DEFILAGE").
dico("D", 8, "DEFILAIS").
dico("D", 8, "DEFILAIT").
dico("D", 8, "DEFILANT").
dico("D", 8, "DEFILEES").
dico("D", 8, "DEFILENT").
dico("D", 8, "DEFILERA").
dico("D", 8, "DEFILEUR").
dico("D", 8, "DEFILIEZ").
dico("D", 8, "DEFILONS").
dico("D", 8, "DEFINIES").
dico("D", 8, "DEFINIRA").
dico("D", 8, "DEFIRENT").
dico("D", 8, "DEFISSES").
dico("D", 8, "DEFLAGRA").
dico("D", 8, "DEFLAGRE").
dico("D", 8, "DEFLATAI").
dico("D", 8, "DEFLATAS").
dico("D", 8, "DEFLATAT").
dico("D", 8, "DEFLATEE").
dico("D", 8, "DEFLATER").
dico("D", 8, "DEFLATES").
dico("D", 8, "DEFLATEZ").
dico("D", 8, "DEFLECHI").
dico("D", 8, "DEFLEURI").
dico("D", 8, "DEFLOQUA").
dico("D", 8, "DEFLOQUE").
dico("D", 8, "DEFLORAI").
dico("D", 8, "DEFLORAS").
dico("D", 8, "DEFLORAT").
dico("D", 8, "DEFLOREE").
dico("D", 8, "DEFLORER").
dico("D", 8, "DEFLORES").
dico("D", 8, "DEFLOREZ").
dico("D", 8, "DEFLUENT").
dico("D", 8, "DEFOLIAI").
dico("D", 8, "DEFOLIAS").
dico("D", 8, "DEFOLIAT").
dico("D", 8, "DEFOLIEE").
dico("D", 8, "DEFOLIER").
dico("D", 8, "DEFOLIES").
dico("D", 8, "DEFOLIEZ").
dico("D", 8, "DEFONCAI").
dico("D", 8, "DEFONCAS").
dico("D", 8, "DEFONCAT").
dico("D", 8, "DEFONCEE").
dico("D", 8, "DEFONCER").
dico("D", 8, "DEFONCES").
dico("D", 8, "DEFONCEZ").
dico("D", 8, "DEFORCAI").
dico("D", 8, "DEFORCAS").
dico("D", 8, "DEFORCAT").
dico("D", 8, "DEFORCEE").
dico("D", 8, "DEFORCER").
dico("D", 8, "DEFORCES").
dico("D", 8, "DEFORCEZ").
dico("D", 8, "DEFORMAI").
dico("D", 8, "DEFORMAS").
dico("D", 8, "DEFORMAT").
dico("D", 8, "DEFORMEE").
dico("D", 8, "DEFORMER").
dico("D", 8, "DEFORMES").
dico("D", 8, "DEFORMEZ").
dico("D", 8, "DEFOULAI").
dico("D", 8, "DEFOULAS").
dico("D", 8, "DEFOULAT").
dico("D", 8, "DEFOULEE").
dico("D", 8, "DEFOULER").
dico("D", 8, "DEFOULES").
dico("D", 8, "DEFOULEZ").
dico("D", 8, "DEFOURNA").
dico("D", 8, "DEFOURNE").
dico("D", 8, "DEFRAIES").
dico("D", 8, "DEFRAYAI").
dico("D", 8, "DEFRAYAS").
dico("D", 8, "DEFRAYAT").
dico("D", 8, "DEFRAYEE").
dico("D", 8, "DEFRAYER").
dico("D", 8, "DEFRAYES").
dico("D", 8, "DEFRAYEZ").
dico("D", 8, "DEFRICHA").
dico("D", 8, "DEFRICHE").
dico("D", 8, "DEFRIPAI").
dico("D", 8, "DEFRIPAS").
dico("D", 8, "DEFRIPAT").
dico("D", 8, "DEFRIPEE").
dico("D", 8, "DEFRIPER").
dico("D", 8, "DEFRIPES").
dico("D", 8, "DEFRIPEZ").
dico("D", 8, "DEFRISAI").
dico("D", 8, "DEFRISAS").
dico("D", 8, "DEFRISAT").
dico("D", 8, "DEFRISEE").
dico("D", 8, "DEFRISER").
dico("D", 8, "DEFRISES").
dico("D", 8, "DEFRISEZ").
dico("D", 8, "DEFRONCA").
dico("D", 8, "DEFRONCE").
dico("D", 8, "DEFROQUA").
dico("D", 8, "DEFROQUE").
dico("D", 8, "DEFRUITA").
dico("D", 8, "DEFRUITE").
dico("D", 8, "DEFUNTAI").
dico("D", 8, "DEFUNTAS").
dico("D", 8, "DEFUNTAT").
dico("D", 8, "DEFUNTER").
dico("D", 8, "DEFUNTES").
dico("D", 8, "DEFUNTEZ").
dico("D", 8, "DEGAGEAI").
dico("D", 8, "DEGAGEAS").
dico("D", 8, "DEGAGEAT").
dico("D", 8, "DEGAGEES").
dico("D", 8, "DEGAGENT").
dico("D", 8, "DEGAGERA").
dico("D", 8, "DEGAGIEZ").
dico("D", 8, "DEGAINAI").
dico("D", 8, "DEGAINAS").
dico("D", 8, "DEGAINAT").
dico("D", 8, "DEGAINEE").
dico("D", 8, "DEGAINER").
dico("D", 8, "DEGAINES").
dico("D", 8, "DEGAINEZ").
dico("D", 8, "DEGAMMAI").
dico("D", 8, "DEGAMMAS").
dico("D", 8, "DEGAMMAT").
dico("D", 8, "DEGAMMER").
dico("D", 8, "DEGAMMES").
dico("D", 8, "DEGAMMEZ").
dico("D", 8, "DEGANTAI").
dico("D", 8, "DEGANTAS").
dico("D", 8, "DEGANTAT").
dico("D", 8, "DEGANTEE").
dico("D", 8, "DEGANTER").
dico("D", 8, "DEGANTES").
dico("D", 8, "DEGANTEZ").
dico("D", 8, "DEGARNIE").
dico("D", 8, "DEGARNIR").
dico("D", 8, "DEGARNIS").
dico("D", 8, "DEGARNIT").
dico("D", 8, "DEGAUCHI").
dico("D", 8, "DEGAZAGE").
dico("D", 8, "DEGAZAIS").
dico("D", 8, "DEGAZAIT").
dico("D", 8, "DEGAZANT").
dico("D", 8, "DEGAZEES").
dico("D", 8, "DEGAZENT").
dico("D", 8, "DEGAZERA").
dico("D", 8, "DEGAZIEZ").
dico("D", 8, "DEGAZONS").
dico("D", 8, "DEGELAIS").
dico("D", 8, "DEGELAIT").
dico("D", 8, "DEGELANT").
dico("D", 8, "DEGELEES").
dico("D", 8, "DEGELENT").
dico("D", 8, "DEGELERA").
dico("D", 8, "DEGELIEZ").
dico("D", 8, "DEGELONS").
dico("D", 8, "DEGENAIS").
dico("D", 8, "DEGENAIT").
dico("D", 8, "DEGENANT").
dico("D", 8, "DEGENEES").
dico("D", 8, "DEGENENT").
dico("D", 8, "DEGENERA").
dico("D", 8, "DEGENERE").
dico("D", 8, "DEGENIEZ").
dico("D", 8, "DEGENONS").
dico("D", 8, "DEGERMAI").
dico("D", 8, "DEGERMAS").
dico("D", 8, "DEGERMAT").
dico("D", 8, "DEGERMEE").
dico("D", 8, "DEGERMER").
dico("D", 8, "DEGERMES").
dico("D", 8, "DEGERMEZ").
dico("D", 8, "DEGIVRAI").
dico("D", 8, "DEGIVRAS").
dico("D", 8, "DEGIVRAT").
dico("D", 8, "DEGIVREE").
dico("D", 8, "DEGIVRER").
dico("D", 8, "DEGIVRES").
dico("D", 8, "DEGIVREZ").
dico("D", 8, "DEGLACAI").
dico("D", 8, "DEGLACAS").
dico("D", 8, "DEGLACAT").
dico("D", 8, "DEGLACEE").
dico("D", 8, "DEGLACER").
dico("D", 8, "DEGLACES").
dico("D", 8, "DEGLACEZ").
dico("D", 8, "DEGLUAIS").
dico("D", 8, "DEGLUAIT").
dico("D", 8, "DEGLUANT").
dico("D", 8, "DEGLUEES").
dico("D", 8, "DEGLUENT").
dico("D", 8, "DEGLUERA").
dico("D", 8, "DEGLUIEZ").
dico("D", 8, "DEGLUONS").
dico("D", 8, "DEGLUTIE").
dico("D", 8, "DEGLUTIR").
dico("D", 8, "DEGLUTIS").
dico("D", 8, "DEGLUTIT").
dico("D", 8, "DEGOISAI").
dico("D", 8, "DEGOISAS").
dico("D", 8, "DEGOISAT").
dico("D", 8, "DEGOISEE").
dico("D", 8, "DEGOISER").
dico("D", 8, "DEGOISES").
dico("D", 8, "DEGOISEZ").
dico("D", 8, "DEGOMMAI").
dico("D", 8, "DEGOMMAS").
dico("D", 8, "DEGOMMAT").
dico("D", 8, "DEGOMMEE").
dico("D", 8, "DEGOMMER").
dico("D", 8, "DEGOMMES").
dico("D", 8, "DEGOMMEZ").
dico("D", 8, "DEGONDAI").
dico("D", 8, "DEGONDAS").
dico("D", 8, "DEGONDAT").
dico("D", 8, "DEGONDEE").
dico("D", 8, "DEGONDER").
dico("D", 8, "DEGONDES").
dico("D", 8, "DEGONDEZ").
dico("D", 8, "DEGONFLA").
dico("D", 8, "DEGONFLE").
dico("D", 8, "DEGORGEA").
dico("D", 8, "DEGORGEE").
dico("D", 8, "DEGORGER").
dico("D", 8, "DEGORGES").
dico("D", 8, "DEGORGEZ").
dico("D", 8, "DEGOTAIS").
dico("D", 8, "DEGOTAIT").
dico("D", 8, "DEGOTANT").
dico("D", 8, "DEGOTEES").
dico("D", 8, "DEGOTENT").
dico("D", 8, "DEGOTERA").
dico("D", 8, "DEGOTIEZ").
dico("D", 8, "DEGOTONS").
dico("D", 8, "DEGOTTAI").
dico("D", 8, "DEGOTTAS").
dico("D", 8, "DEGOTTAT").
dico("D", 8, "DEGOTTEE").
dico("D", 8, "DEGOTTER").
dico("D", 8, "DEGOTTES").
dico("D", 8, "DEGOTTEZ").
dico("D", 8, "DEGOURDI").
dico("D", 8, "DEGOUTAI").
dico("D", 8, "DEGOUTAS").
dico("D", 8, "DEGOUTAT").
dico("D", 8, "DEGOUTEE").
dico("D", 8, "DEGOUTER").
dico("D", 8, "DEGOUTES").
dico("D", 8, "DEGOUTEZ").
dico("D", 8, "DEGOUTTA").
dico("D", 8, "DEGOUTTE").
dico("D", 8, "DEGRADAI").
dico("D", 8, "DEGRADAS").
dico("D", 8, "DEGRADAT").
dico("D", 8, "DEGRADEE").
dico("D", 8, "DEGRADER").
dico("D", 8, "DEGRADES").
dico("D", 8, "DEGRADEZ").
dico("D", 8, "DEGRAFAI").
dico("D", 8, "DEGRAFAS").
dico("D", 8, "DEGRAFAT").
dico("D", 8, "DEGRAFEE").
dico("D", 8, "DEGRAFER").
dico("D", 8, "DEGRAFES").
dico("D", 8, "DEGRAFEZ").
dico("D", 8, "DEGREAIS").
dico("D", 8, "DEGREAIT").
dico("D", 8, "DEGREANT").
dico("D", 8, "DEGREEES").
dico("D", 8, "DEGREENT").
dico("D", 8, "DEGREERA").
dico("D", 8, "DEGREIEZ").
dico("D", 8, "DEGREONS").
dico("D", 8, "DEGREVAI").
dico("D", 8, "DEGREVAS").
dico("D", 8, "DEGREVAT").
dico("D", 8, "DEGREVEE").
dico("D", 8, "DEGREVER").
dico("D", 8, "DEGREVES").
dico("D", 8, "DEGREVEZ").
dico("D", 8, "DEGRIFFA").
dico("D", 8, "DEGRIFFE").
dico("D", 8, "DEGRIPPA").
dico("D", 8, "DEGRIPPE").
dico("D", 8, "DEGRISAI").
dico("D", 8, "DEGRISAS").
dico("D", 8, "DEGRISAT").
dico("D", 8, "DEGRISEE").
dico("D", 8, "DEGRISER").
dico("D", 8, "DEGRISES").
dico("D", 8, "DEGRISEZ").
dico("D", 8, "DEGROSSA").
dico("D", 8, "DEGROSSE").
dico("D", 8, "DEGROSSI").
dico("D", 8, "DEGROUPA").
dico("D", 8, "DEGROUPE").
dico("D", 8, "DEGUERPI").
dico("D", 8, "DEGUEULA").
dico("D", 8, "DEGUEULE").
dico("D", 8, "DEGUILLA").
dico("D", 8, "DEGUILLE").
dico("D", 8, "DEGUISAI").
dico("D", 8, "DEGUISAS").
dico("D", 8, "DEGUISAT").
dico("D", 8, "DEGUISEE").
dico("D", 8, "DEGUISER").
dico("D", 8, "DEGUISES").
dico("D", 8, "DEGUISEZ").
dico("D", 8, "DEGUSTAI").
dico("D", 8, "DEGUSTAS").
dico("D", 8, "DEGUSTAT").
dico("D", 8, "DEGUSTEE").
dico("D", 8, "DEGUSTER").
dico("D", 8, "DEGUSTES").
dico("D", 8, "DEGUSTEZ").
dico("D", 8, "DEHALAGE").
dico("D", 8, "DEHALAIS").
dico("D", 8, "DEHALAIT").
dico("D", 8, "DEHALANT").
dico("D", 8, "DEHALEES").
dico("D", 8, "DEHALENT").
dico("D", 8, "DEHALERA").
dico("D", 8, "DEHALIEZ").
dico("D", 8, "DEHALONS").
dico("D", 8, "DEHANCHA").
dico("D", 8, "DEHANCHE").
dico("D", 8, "DEHOTTAI").
dico("D", 8, "DEHOTTAS").
dico("D", 8, "DEHOTTAT").
dico("D", 8, "DEHOTTER").
dico("D", 8, "DEHOTTES").
dico("D", 8, "DEHOTTEZ").
dico("D", 8, "DEHOUSSA").
dico("D", 8, "DEHOUSSE").
dico("D", 8, "DEICIDES").
dico("D", 8, "DEIFIAIS").
dico("D", 8, "DEIFIAIT").
dico("D", 8, "DEIFIANT").
dico("D", 8, "DEIFIEES").
dico("D", 8, "DEIFIENT").
dico("D", 8, "DEIFIERA").
dico("D", 8, "DEIFIIEZ").
dico("D", 8, "DEIFIONS").
dico("D", 8, "DEJANTAI").
dico("D", 8, "DEJANTAS").
dico("D", 8, "DEJANTAT").
dico("D", 8, "DEJANTEE").
dico("D", 8, "DEJANTER").
dico("D", 8, "DEJANTES").
dico("D", 8, "DEJANTEZ").
dico("D", 8, "DEJAUGEA").
dico("D", 8, "DEJAUGEE").
dico("D", 8, "DEJAUGER").
dico("D", 8, "DEJAUGES").
dico("D", 8, "DEJAUGEZ").
dico("D", 8, "DEJAUNIE").
dico("D", 8, "DEJAUNIR").
dico("D", 8, "DEJAUNIS").
dico("D", 8, "DEJAUNIT").
dico("D", 8, "DEJETAIS").
dico("D", 8, "DEJETAIT").
dico("D", 8, "DEJETANT").
dico("D", 8, "DEJETEES").
dico("D", 8, "DEJETIEZ").
dico("D", 8, "DEJETONS").
dico("D", 8, "DEJETTES").
dico("D", 8, "DEJEUNAI").
dico("D", 8, "DEJEUNAS").
dico("D", 8, "DEJEUNAT").
dico("D", 8, "DEJEUNER").
dico("D", 8, "DEJEUNES").
dico("D", 8, "DEJEUNEZ").
dico("D", 8, "DEJOUAIS").
dico("D", 8, "DEJOUAIT").
dico("D", 8, "DEJOUANT").
dico("D", 8, "DEJOUEES").
dico("D", 8, "DEJOUENT").
dico("D", 8, "DEJOUERA").
dico("D", 8, "DEJOUIEZ").
dico("D", 8, "DEJOUONS").
dico("D", 8, "DEJUCHAI").
dico("D", 8, "DEJUCHAS").
dico("D", 8, "DEJUCHAT").
dico("D", 8, "DEJUCHEE").
dico("D", 8, "DEJUCHER").
dico("D", 8, "DEJUCHES").
dico("D", 8, "DEJUCHEZ").
dico("D", 8, "DEJUGEAI").
dico("D", 8, "DEJUGEAS").
dico("D", 8, "DEJUGEAT").
dico("D", 8, "DEJUGEES").
dico("D", 8, "DEJUGENT").
dico("D", 8, "DEJUGERA").
dico("D", 8, "DEJUGIEZ").
dico("D", 8, "DELABRAI").
dico("D", 8, "DELABRAS").
dico("D", 8, "DELABRAT").
dico("D", 8, "DELABREE").
dico("D", 8, "DELABRER").
dico("D", 8, "DELABRES").
dico("D", 8, "DELABREZ").
dico("D", 8, "DELACAIS").
dico("D", 8, "DELACAIT").
dico("D", 8, "DELACANT").
dico("D", 8, "DELACEES").
dico("D", 8, "DELACENT").
dico("D", 8, "DELACERA").
dico("D", 8, "DELACIEZ").
dico("D", 8, "DELACONS").
dico("D", 8, "DELAIENT").
dico("D", 8, "DELAIERA").
dico("D", 8, "DELAINAI").
dico("D", 8, "DELAINAS").
dico("D", 8, "DELAINAT").
dico("D", 8, "DELAINEE").
dico("D", 8, "DELAINER").
dico("D", 8, "DELAINES").
dico("D", 8, "DELAINEZ").
dico("D", 8, "DELAISSA").
dico("D", 8, "DELAISSE").
dico("D", 8, "DELAITAI").
dico("D", 8, "DELAITAS").
dico("D", 8, "DELAITAT").
dico("D", 8, "DELAITEE").
dico("D", 8, "DELAITER").
dico("D", 8, "DELAITES").
dico("D", 8, "DELAITEZ").
dico("D", 8, "DELARDAI").
dico("D", 8, "DELARDAS").
dico("D", 8, "DELARDAT").
dico("D", 8, "DELARDEE").
dico("D", 8, "DELARDER").
dico("D", 8, "DELARDES").
dico("D", 8, "DELARDEZ").
dico("D", 8, "DELASSAI").
dico("D", 8, "DELASSAS").
dico("D", 8, "DELASSAT").
dico("D", 8, "DELASSEE").
dico("D", 8, "DELASSER").
dico("D", 8, "DELASSES").
dico("D", 8, "DELASSEZ").
dico("D", 8, "DELATEUR").
dico("D", 8, "DELATION").
dico("D", 8, "DELATTAI").
dico("D", 8, "DELATTAS").
dico("D", 8, "DELATTAT").
dico("D", 8, "DELATTEE").
dico("D", 8, "DELATTER").
dico("D", 8, "DELATTES").
dico("D", 8, "DELATTEZ").
dico("D", 8, "DELAVAGE").
dico("D", 8, "DELAVAIS").
dico("D", 8, "DELAVAIT").
dico("D", 8, "DELAVANT").
dico("D", 8, "DELAVEES").
dico("D", 8, "DELAVENT").
dico("D", 8, "DELAVERA").
dico("D", 8, "DELAVIEZ").
dico("D", 8, "DELAVONS").
dico("D", 8, "DELAYAGE").
dico("D", 8, "DELAYAIS").
dico("D", 8, "DELAYAIT").
dico("D", 8, "DELAYANT").
dico("D", 8, "DELAYEES").
dico("D", 8, "DELAYENT").
dico("D", 8, "DELAYERA").
dico("D", 8, "DELAYIEZ").
dico("D", 8, "DELAYONS").
dico("D", 8, "DELEATUR").
dico("D", 8, "DELEBILE").
dico("D", 8, "DELECTAI").
dico("D", 8, "DELECTAS").
dico("D", 8, "DELECTAT").
dico("D", 8, "DELECTEE").
dico("D", 8, "DELECTER").
dico("D", 8, "DELECTES").
dico("D", 8, "DELECTEZ").
dico("D", 8, "DELEGANT").
dico("D", 8, "DELEGUAI").
dico("D", 8, "DELEGUAS").
dico("D", 8, "DELEGUAT").
dico("D", 8, "DELEGUEE").
dico("D", 8, "DELEGUER").
dico("D", 8, "DELEGUES").
dico("D", 8, "DELEGUEZ").
dico("D", 8, "DELESTAI").
dico("D", 8, "DELESTAS").
dico("D", 8, "DELESTAT").
dico("D", 8, "DELESTEE").
dico("D", 8, "DELESTER").
dico("D", 8, "DELESTES").
dico("D", 8, "DELESTEZ").
dico("D", 8, "DELETERE").
dico("D", 8, "DELETION").
dico("D", 8, "DELIAMES").
dico("D", 8, "DELIAQUE").
dico("D", 8, "DELIASSA").
dico("D", 8, "DELIASSE").
dico("D", 8, "DELIATES").
dico("D", 8, "DELIBERA").
dico("D", 8, "DELIBERE").
dico("D", 8, "DELICATE").
dico("D", 8, "DELICATS").
dico("D", 8, "DELIENNE").
dico("D", 8, "DELIERAI").
dico("D", 8, "DELIERAS").
dico("D", 8, "DELIEREZ").
dico("D", 8, "DELIGNAI").
dico("D", 8, "DELIGNAS").
dico("D", 8, "DELIGNAT").
dico("D", 8, "DELIGNEE").
dico("D", 8, "DELIGNER").
dico("D", 8, "DELIGNES").
dico("D", 8, "DELIGNEZ").
dico("D", 8, "DELIIONS").
dico("D", 8, "DELIMITA").
dico("D", 8, "DELIMITE").
dico("D", 8, "DELINEAI").
dico("D", 8, "DELINEAS").
dico("D", 8, "DELINEAT").
dico("D", 8, "DELINEEE").
dico("D", 8, "DELINEER").
dico("D", 8, "DELINEES").
dico("D", 8, "DELINEEZ").
dico("D", 8, "DELIRAIS").
dico("D", 8, "DELIRAIT").
dico("D", 8, "DELIRANT").
dico("D", 8, "DELIRENT").
dico("D", 8, "DELIRERA").
dico("D", 8, "DELIRIEZ").
dico("D", 8, "DELIRIUM").
dico("D", 8, "DELIRONS").
dico("D", 8, "DELISSAI").
dico("D", 8, "DELISSAS").
dico("D", 8, "DELISSAT").
dico("D", 8, "DELISSEE").
dico("D", 8, "DELISSER").
dico("D", 8, "DELISSES").
dico("D", 8, "DELISSEZ").
dico("D", 8, "DELITAGE").
dico("D", 8, "DELITAIS").
dico("D", 8, "DELITAIT").
dico("D", 8, "DELITANT").
dico("D", 8, "DELITEES").
dico("D", 8, "DELITENT").
dico("D", 8, "DELITERA").
dico("D", 8, "DELITIEZ").
dico("D", 8, "DELITONS").
dico("D", 8, "DELIVRAI").
dico("D", 8, "DELIVRAS").
dico("D", 8, "DELIVRAT").
dico("D", 8, "DELIVREE").
dico("D", 8, "DELIVRER").
dico("D", 8, "DELIVRES").
dico("D", 8, "DELIVREZ").
dico("D", 8, "DELOGEAI").
dico("D", 8, "DELOGEAS").
dico("D", 8, "DELOGEAT").
dico("D", 8, "DELOGEES").
dico("D", 8, "DELOGENT").
dico("D", 8, "DELOGERA").
dico("D", 8, "DELOGIEZ").
dico("D", 8, "DELOGUAI").
dico("D", 8, "DELOGUAS").
dico("D", 8, "DELOGUAT").
dico("D", 8, "DELOGUEE").
dico("D", 8, "DELOGUER").
dico("D", 8, "DELOGUES").
dico("D", 8, "DELOGUEZ").
dico("D", 8, "DELOVAIS").
dico("D", 8, "DELOVAIT").
dico("D", 8, "DELOVANT").
dico("D", 8, "DELOVEES").
dico("D", 8, "DELOVENT").
dico("D", 8, "DELOVERA").
dico("D", 8, "DELOVIEZ").
dico("D", 8, "DELOVONS").
dico("D", 8, "DELOYALE").
dico("D", 8, "DELOYAUX").
dico("D", 8, "DELTISTE").
dico("D", 8, "DELTOIDE").
dico("D", 8, "DELURAIS").
dico("D", 8, "DELURAIT").
dico("D", 8, "DELURANT").
dico("D", 8, "DELUREES").
dico("D", 8, "DELURENT").
dico("D", 8, "DELURERA").
dico("D", 8, "DELURIEZ").
dico("D", 8, "DELURONS").
dico("D", 8, "DELUSTRA").
dico("D", 8, "DELUSTRE").
dico("D", 8, "DELUTAGE").
dico("D", 8, "DELUTAIS").
dico("D", 8, "DELUTAIT").
dico("D", 8, "DELUTANT").
dico("D", 8, "DELUTEES").
dico("D", 8, "DELUTENT").
dico("D", 8, "DELUTERA").
dico("D", 8, "DELUTIEZ").
dico("D", 8, "DELUTONS").
dico("D", 8, "DEMAIGRI").
dico("D", 8, "DEMAILLA").
dico("D", 8, "DEMAILLE").
dico("D", 8, "DEMANCHA").
dico("D", 8, "DEMANCHE").
dico("D", 8, "DEMANDAI").
dico("D", 8, "DEMANDAS").
dico("D", 8, "DEMANDAT").
dico("D", 8, "DEMANDEE").
dico("D", 8, "DEMANDER").
dico("D", 8, "DEMANDES").
dico("D", 8, "DEMANDEZ").
dico("D", 8, "DEMANGEA").
dico("D", 8, "DEMANGEE").
dico("D", 8, "DEMANGER").
dico("D", 8, "DEMANGES").
dico("D", 8, "DEMANGEZ").
dico("D", 8, "DEMARCHA").
dico("D", 8, "DEMARCHE").
dico("D", 8, "DEMARIAI").
dico("D", 8, "DEMARIAS").
dico("D", 8, "DEMARIAT").
dico("D", 8, "DEMARIEE").
dico("D", 8, "DEMARIER").
dico("D", 8, "DEMARIES").
dico("D", 8, "DEMARIEZ").
dico("D", 8, "DEMARQUA").
dico("D", 8, "DEMARQUE").
dico("D", 8, "DEMARRAI").
dico("D", 8, "DEMARRAS").
dico("D", 8, "DEMARRAT").
dico("D", 8, "DEMARREE").
dico("D", 8, "DEMARRER").
dico("D", 8, "DEMARRES").
dico("D", 8, "DEMARREZ").
dico("D", 8, "DEMASCLA").
dico("D", 8, "DEMASCLE").
dico("D", 8, "DEMASQUA").
dico("D", 8, "DEMASQUE").
dico("D", 8, "DEMATAGE").
dico("D", 8, "DEMATAIS").
dico("D", 8, "DEMATAIT").
dico("D", 8, "DEMATANT").
dico("D", 8, "DEMATEES").
dico("D", 8, "DEMATENT").
dico("D", 8, "DEMATERA").
dico("D", 8, "DEMATIEZ").
dico("D", 8, "DEMATINA").
dico("D", 8, "DEMATINE").
dico("D", 8, "DEMATONS").
dico("D", 8, "DEMELAGE").
dico("D", 8, "DEMELAIS").
dico("D", 8, "DEMELAIT").
dico("D", 8, "DEMELANT").
dico("D", 8, "DEMELEES").
dico("D", 8, "DEMELENT").
dico("D", 8, "DEMELERA").
dico("D", 8, "DEMELEUR").
dico("D", 8, "DEMELIEZ").
dico("D", 8, "DEMELOIR").
dico("D", 8, "DEMELONS").
dico("D", 8, "DEMELURE").
dico("D", 8, "DEMEMBRA").
dico("D", 8, "DEMEMBRE").
dico("D", 8, "DEMENAGE").
dico("D", 8, "DEMENAIS").
dico("D", 8, "DEMENAIT").
dico("D", 8, "DEMENANT").
dico("D", 8, "DEMENCES").
dico("D", 8, "DEMENEES").
dico("D", 8, "DEMENENT").
dico("D", 8, "DEMENERA").
dico("D", 8, "DEMENIEZ").
dico("D", 8, "DEMENONS").
dico("D", 8, "DEMENTES").
dico("D", 8, "DEMENTEZ").
dico("D", 8, "DEMENTIE").
dico("D", 8, "DEMENTIR").
dico("D", 8, "DEMENTIS").
dico("D", 8, "DEMENTIT").
dico("D", 8, "DEMERDAI").
dico("D", 8, "DEMERDAS").
dico("D", 8, "DEMERDAT").
dico("D", 8, "DEMERDEE").
dico("D", 8, "DEMERDER").
dico("D", 8, "DEMERDES").
dico("D", 8, "DEMERDEZ").
dico("D", 8, "DEMERITA").
dico("D", 8, "DEMERITE").
dico("D", 8, "DEMESURE").
dico("D", 8, "DEMETTES").
dico("D", 8, "DEMETTEZ").
dico("D", 8, "DEMETTRA").
dico("D", 8, "DEMETTRE").
dico("D", 8, "DEMEUBLA").
dico("D", 8, "DEMEUBLE").
dico("D", 8, "DEMEURAI").
dico("D", 8, "DEMEURAS").
dico("D", 8, "DEMEURAT").
dico("D", 8, "DEMEUREE").
dico("D", 8, "DEMEURER").
dico("D", 8, "DEMEURES").
dico("D", 8, "DEMEUREZ").
dico("D", 8, "DEMIARDS").
dico("D", 8, "DEMIELLA").
dico("D", 8, "DEMIELLE").
dico("D", 8, "DEMINAGE").
dico("D", 8, "DEMINAIS").
dico("D", 8, "DEMINAIT").
dico("D", 8, "DEMINANT").
dico("D", 8, "DEMINEES").
dico("D", 8, "DEMINENT").
dico("D", 8, "DEMINERA").
dico("D", 8, "DEMINEUR").
dico("D", 8, "DEMINIEZ").
dico("D", 8, "DEMINONS").
dico("D", 8, "DEMIRENT").
dico("D", 8, "DEMISSES").
dico("D", 8, "DEMIURGE").
dico("D", 8, "DEMODAIS").
dico("D", 8, "DEMODAIT").
dico("D", 8, "DEMODANT").
dico("D", 8, "DEMODEES").
dico("D", 8, "DEMODENT").
dico("D", 8, "DEMODERA").
dico("D", 8, "DEMODIEZ").
dico("D", 8, "DEMODONS").
dico("D", 8, "DEMODULA").
dico("D", 8, "DEMODULE").
dico("D", 8, "DEMOLIES").
dico("D", 8, "DEMOLIRA").
dico("D", 8, "DEMONTAI").
dico("D", 8, "DEMONTAS").
dico("D", 8, "DEMONTAT").
dico("D", 8, "DEMONTEE").
dico("D", 8, "DEMONTER").
dico("D", 8, "DEMONTES").
dico("D", 8, "DEMONTEZ").
dico("D", 8, "DEMONTRA").
dico("D", 8, "DEMONTRE").
dico("D", 8, "DEMORDES").
dico("D", 8, "DEMORDEZ").
dico("D", 8, "DEMORDIS").
dico("D", 8, "DEMORDIT").
dico("D", 8, "DEMORDRA").
dico("D", 8, "DEMORDRE").
dico("D", 8, "DEMOTIVA").
dico("D", 8, "DEMOTIVE").
dico("D", 8, "DEMOULAI").
dico("D", 8, "DEMOULAS").
dico("D", 8, "DEMOULAT").
dico("D", 8, "DEMOULEE").
dico("D", 8, "DEMOULER").
dico("D", 8, "DEMOULES").
dico("D", 8, "DEMOULEZ").
dico("D", 8, "DEMUNIES").
dico("D", 8, "DEMUNIRA").
dico("D", 8, "DEMUSELA").
dico("D", 8, "DEMUSELE").
dico("D", 8, "DEMUTISA").
dico("D", 8, "DEMUTISE").
dico("D", 8, "DENANTIE").
dico("D", 8, "DENANTIR").
dico("D", 8, "DENANTIS").
dico("D", 8, "DENANTIT").
dico("D", 8, "DENATTAI").
dico("D", 8, "DENATTAS").
dico("D", 8, "DENATTAT").
dico("D", 8, "DENATTEE").
dico("D", 8, "DENATTER").
dico("D", 8, "DENATTES").
dico("D", 8, "DENATTEZ").
dico("D", 8, "DENATURA").
dico("D", 8, "DENATURE").
dico("D", 8, "DENDRITE").
dico("D", 8, "DENEBULA").
dico("D", 8, "DENEBULE").
dico("D", 8, "DENEIGEA").
dico("D", 8, "DENEIGEE").
dico("D", 8, "DENEIGER").
dico("D", 8, "DENEIGES").
dico("D", 8, "DENEIGEZ").
dico("D", 8, "DENERVAI").
dico("D", 8, "DENERVAS").
dico("D", 8, "DENERVAT").
dico("D", 8, "DENERVEE").
dico("D", 8, "DENERVER").
dico("D", 8, "DENERVES").
dico("D", 8, "DENERVEZ").
dico("D", 8, "DENIAISA").
dico("D", 8, "DENIAISE").
dico("D", 8, "DENIAMES").
dico("D", 8, "DENIASSE").
dico("D", 8, "DENIATES").
dico("D", 8, "DENICHAI").
dico("D", 8, "DENICHAS").
dico("D", 8, "DENICHAT").
dico("D", 8, "DENICHEE").
dico("D", 8, "DENICHER").
dico("D", 8, "DENICHES").
dico("D", 8, "DENICHEZ").
dico("D", 8, "DENIERAI").
dico("D", 8, "DENIERAS").
dico("D", 8, "DENIEREZ").
dico("D", 8, "DENIGRAI").
dico("D", 8, "DENIGRAS").
dico("D", 8, "DENIGRAT").
dico("D", 8, "DENIGREE").
dico("D", 8, "DENIGRER").
dico("D", 8, "DENIGRES").
dico("D", 8, "DENIGREZ").
dico("D", 8, "DENIIONS").
dico("D", 8, "DENITRAI").
dico("D", 8, "DENITRAS").
dico("D", 8, "DENITRAT").
dico("D", 8, "DENITREE").
dico("D", 8, "DENITRER").
dico("D", 8, "DENITRES").
dico("D", 8, "DENITREZ").
dico("D", 8, "DENIVELA").
dico("D", 8, "DENIVELE").
dico("D", 8, "DENOIENT").
dico("D", 8, "DENOIERA").
dico("D", 8, "DENOMBRA").
dico("D", 8, "DENOMBRE").
dico("D", 8, "DENOMMAI").
dico("D", 8, "DENOMMAS").
dico("D", 8, "DENOMMAT").
dico("D", 8, "DENOMMEE").
dico("D", 8, "DENOMMER").
dico("D", 8, "DENOMMES").
dico("D", 8, "DENOMMEZ").
dico("D", 8, "DENONCAI").
dico("D", 8, "DENONCAS").
dico("D", 8, "DENONCAT").
dico("D", 8, "DENONCEE").
dico("D", 8, "DENONCER").
dico("D", 8, "DENONCES").
dico("D", 8, "DENONCEZ").
dico("D", 8, "DENOTAIS").
dico("D", 8, "DENOTAIT").
dico("D", 8, "DENOTANT").
dico("D", 8, "DENOTEES").
dico("D", 8, "DENOTENT").
dico("D", 8, "DENOTERA").
dico("D", 8, "DENOTIEZ").
dico("D", 8, "DENOTONS").
dico("D", 8, "DENOUAIS").
dico("D", 8, "DENOUAIT").
dico("D", 8, "DENOUANT").
dico("D", 8, "DENOUEES").
dico("D", 8, "DENOUENT").
dico("D", 8, "DENOUERA").
dico("D", 8, "DENOUIEZ").
dico("D", 8, "DENOUONS").
dico("D", 8, "DENOYAGE").
dico("D", 8, "DENOYAIS").
dico("D", 8, "DENOYAIT").
dico("D", 8, "DENOYANT").
dico("D", 8, "DENOYEES").
dico("D", 8, "DENOYIEZ").
dico("D", 8, "DENOYONS").
dico("D", 8, "DENSIFIA").
dico("D", 8, "DENSIFIE").
dico("D", 8, "DENSITES").
dico("D", 8, "DENTAIRE").
dico("D", 8, "DENTALES").
dico("D", 8, "DENTAMES").
dico("D", 8, "DENTASSE").
dico("D", 8, "DENTATES").
dico("D", 8, "DENTELAI").
dico("D", 8, "DENTELAS").
dico("D", 8, "DENTELAT").
dico("D", 8, "DENTELEE").
dico("D", 8, "DENTELER").
dico("D", 8, "DENTELES").
dico("D", 8, "DENTELEZ").
dico("D", 8, "DENTELLE").
dico("D", 8, "DENTERAI").
dico("D", 8, "DENTERAS").
dico("D", 8, "DENTEREZ").
dico("D", 8, "DENTIERS").
dico("D", 8, "DENTINES").
dico("D", 8, "DENTIONS").
dico("D", 8, "DENTISTE").
dico("D", 8, "DENTURES").
dico("D", 8, "DENUAMES").
dico("D", 8, "DENUASSE").
dico("D", 8, "DENUATES").
dico("D", 8, "DENUDAIS").
dico("D", 8, "DENUDAIT").
dico("D", 8, "DENUDANT").
dico("D", 8, "DENUDEES").
dico("D", 8, "DENUDENT").
dico("D", 8, "DENUDERA").
dico("D", 8, "DENUDIEZ").
dico("D", 8, "DENUDONS").
dico("D", 8, "DENUERAI").
dico("D", 8, "DENUERAS").
dico("D", 8, "DENUEREZ").
dico("D", 8, "DENUIONS").
dico("D", 8, "DENUTRIE").
dico("D", 8, "DENUTRIS").
dico("D", 8, "DEPAILLA").
dico("D", 8, "DEPAILLE").
dico("D", 8, "DEPANNAI").
dico("D", 8, "DEPANNAS").
dico("D", 8, "DEPANNAT").
dico("D", 8, "DEPANNEE").
dico("D", 8, "DEPANNER").
dico("D", 8, "DEPANNES").
dico("D", 8, "DEPANNEZ").
dico("D", 8, "DEPARAIS").
dico("D", 8, "DEPARAIT").
dico("D", 8, "DEPARANT").
dico("D", 8, "DEPAREES").
dico("D", 8, "DEPARENT").
dico("D", 8, "DEPARERA").
dico("D", 8, "DEPARIAI").
dico("D", 8, "DEPARIAS").
dico("D", 8, "DEPARIAT").
dico("D", 8, "DEPARIEE").
dico("D", 8, "DEPARIER").
dico("D", 8, "DEPARIES").
dico("D", 8, "DEPARIEZ").
dico("D", 8, "DEPARLAI").
dico("D", 8, "DEPARLAS").
dico("D", 8, "DEPARLAT").
dico("D", 8, "DEPARLER").
dico("D", 8, "DEPARLES").
dico("D", 8, "DEPARLEZ").
dico("D", 8, "DEPARONS").
dico("D", 8, "DEPARTES").
dico("D", 8, "DEPARTEZ").
dico("D", 8, "DEPARTIE").
dico("D", 8, "DEPARTIR").
dico("D", 8, "DEPARTIS").
dico("D", 8, "DEPARTIT").
dico("D", 8, "DEPASSAI").
dico("D", 8, "DEPASSAS").
dico("D", 8, "DEPASSAT").
dico("D", 8, "DEPASSEE").
dico("D", 8, "DEPASSER").
dico("D", 8, "DEPASSES").
dico("D", 8, "DEPASSEZ").
dico("D", 8, "DEPATRIA").
dico("D", 8, "DEPATRIE").
dico("D", 8, "DEPAVAGE").
dico("D", 8, "DEPAVAIS").
dico("D", 8, "DEPAVAIT").
dico("D", 8, "DEPAVANT").
dico("D", 8, "DEPAVEES").
dico("D", 8, "DEPAVENT").
dico("D", 8, "DEPAVERA").
dico("D", 8, "DEPAVIEZ").
dico("D", 8, "DEPAVONS").
dico("D", 8, "DEPAYSAI").
dico("D", 8, "DEPAYSAS").
dico("D", 8, "DEPAYSAT").
dico("D", 8, "DEPAYSEE").
dico("D", 8, "DEPAYSER").
dico("D", 8, "DEPAYSES").
dico("D", 8, "DEPAYSEZ").
dico("D", 8, "DEPECAGE").
dico("D", 8, "DEPECAIS").
dico("D", 8, "DEPECAIT").
dico("D", 8, "DEPECANT").
dico("D", 8, "DEPECEES").
dico("D", 8, "DEPECENT").
dico("D", 8, "DEPECERA").
dico("D", 8, "DEPECEUR").
dico("D", 8, "DEPECHAI").
dico("D", 8, "DEPECHAS").
dico("D", 8, "DEPECHAT").
dico("D", 8, "DEPECHEE").
dico("D", 8, "DEPECHER").
dico("D", 8, "DEPECHES").
dico("D", 8, "DEPECHEZ").
dico("D", 8, "DEPECIEZ").
dico("D", 8, "DEPECONS").
dico("D", 8, "DEPEIGNA").
dico("D", 8, "DEPEIGNE").
dico("D", 8, "DEPEINTE").
dico("D", 8, "DEPEINTS").
dico("D", 8, "DEPENDES").
dico("D", 8, "DEPENDEZ").
dico("D", 8, "DEPENDIS").
dico("D", 8, "DEPENDIT").
dico("D", 8, "DEPENDRA").
dico("D", 8, "DEPENDRE").
dico("D", 8, "DEPENDUE").
dico("D", 8, "DEPENDUS").
dico("D", 8, "DEPENSAI").
dico("D", 8, "DEPENSAS").
dico("D", 8, "DEPENSAT").
dico("D", 8, "DEPENSEE").
dico("D", 8, "DEPENSER").
dico("D", 8, "DEPENSES").
dico("D", 8, "DEPENSEZ").
dico("D", 8, "DEPERIRA").
dico("D", 8, "DEPETRAI").
dico("D", 8, "DEPETRAS").
dico("D", 8, "DEPETRAT").
dico("D", 8, "DEPETREE").
dico("D", 8, "DEPETRER").
dico("D", 8, "DEPETRES").
dico("D", 8, "DEPETREZ").
dico("D", 8, "DEPEUPLA").
dico("D", 8, "DEPEUPLE").
dico("D", 8, "DEPHASAI").
dico("D", 8, "DEPHASAS").
dico("D", 8, "DEPHASAT").
dico("D", 8, "DEPHASEE").
dico("D", 8, "DEPHASER").
dico("D", 8, "DEPHASES").
dico("D", 8, "DEPHASEZ").
dico("D", 8, "DEPIAUTA").
dico("D", 8, "DEPIAUTE").
dico("D", 8, "DEPICAGE").
dico("D", 8, "DEPILAGE").
dico("D", 8, "DEPILAIS").
dico("D", 8, "DEPILAIT").
dico("D", 8, "DEPILANT").
dico("D", 8, "DEPILEES").
dico("D", 8, "DEPILENT").
dico("D", 8, "DEPILERA").
dico("D", 8, "DEPILIEZ").
dico("D", 8, "DEPILONS").
dico("D", 8, "DEPIQUAI").
dico("D", 8, "DEPIQUAS").
dico("D", 8, "DEPIQUAT").
dico("D", 8, "DEPIQUEE").
dico("D", 8, "DEPIQUER").
dico("D", 8, "DEPIQUES").
dico("D", 8, "DEPIQUEZ").
dico("D", 8, "DEPISTAI").
dico("D", 8, "DEPISTAS").
dico("D", 8, "DEPISTAT").
dico("D", 8, "DEPISTEE").
dico("D", 8, "DEPISTER").
dico("D", 8, "DEPISTES").
dico("D", 8, "DEPISTEZ").
dico("D", 8, "DEPITAIS").
dico("D", 8, "DEPITAIT").
dico("D", 8, "DEPITANT").
dico("D", 8, "DEPITEES").
dico("D", 8, "DEPITENT").
dico("D", 8, "DEPITERA").
dico("D", 8, "DEPITIEZ").
dico("D", 8, "DEPITONS").
dico("D", 8, "DEPLACAI").
dico("D", 8, "DEPLACAS").
dico("D", 8, "DEPLACAT").
dico("D", 8, "DEPLACEE").
dico("D", 8, "DEPLACER").
dico("D", 8, "DEPLACES").
dico("D", 8, "DEPLACEZ").
dico("D", 8, "DEPLAIRA").
dico("D", 8, "DEPLAIRE").
dico("D", 8, "DEPLAISE").
dico("D", 8, "DEPLANAI").
dico("D", 8, "DEPLANAS").
dico("D", 8, "DEPLANAT").
dico("D", 8, "DEPLANEE").
dico("D", 8, "DEPLANER").
dico("D", 8, "DEPLANES").
dico("D", 8, "DEPLANEZ").
dico("D", 8, "DEPLANTA").
dico("D", 8, "DEPLANTE").
dico("D", 8, "DEPLATRA").
dico("D", 8, "DEPLATRE").
dico("D", 8, "DEPLIAGE").
dico("D", 8, "DEPLIAIS").
dico("D", 8, "DEPLIAIT").
dico("D", 8, "DEPLIANT").
dico("D", 8, "DEPLIEES").
dico("D", 8, "DEPLIENT").
dico("D", 8, "DEPLIERA").
dico("D", 8, "DEPLIIEZ").
dico("D", 8, "DEPLIONS").
dico("D", 8, "DEPLISSA").
dico("D", 8, "DEPLISSE").
dico("D", 8, "DEPLOIES").
dico("D", 8, "DEPLOMBA").
dico("D", 8, "DEPLOMBE").
dico("D", 8, "DEPLORAI").
dico("D", 8, "DEPLORAS").
dico("D", 8, "DEPLORAT").
dico("D", 8, "DEPLOREE").
dico("D", 8, "DEPLORER").
dico("D", 8, "DEPLORES").
dico("D", 8, "DEPLOREZ").
dico("D", 8, "DEPLOYAI").
dico("D", 8, "DEPLOYAS").
dico("D", 8, "DEPLOYAT").
dico("D", 8, "DEPLOYEE").
dico("D", 8, "DEPLOYER").
dico("D", 8, "DEPLOYES").
dico("D", 8, "DEPLOYEZ").
dico("D", 8, "DEPLUMAI").
dico("D", 8, "DEPLUMAS").
dico("D", 8, "DEPLUMAT").
dico("D", 8, "DEPLUMEE").
dico("D", 8, "DEPLUMER").
dico("D", 8, "DEPLUMES").
dico("D", 8, "DEPLUMEZ").
dico("D", 8, "DEPLUSSE").
dico("D", 8, "DEPLUTES").
dico("D", 8, "DEPOINTA").
dico("D", 8, "DEPOINTE").
dico("D", 8, "DEPOLIES").
dico("D", 8, "DEPOLIRA").
dico("D", 8, "DEPOLLUA").
dico("D", 8, "DEPOLLUE").
dico("D", 8, "DEPONENT").
dico("D", 8, "DEPORTAI").
dico("D", 8, "DEPORTAS").
dico("D", 8, "DEPORTAT").
dico("D", 8, "DEPORTEE").
dico("D", 8, "DEPORTER").
dico("D", 8, "DEPORTES").
dico("D", 8, "DEPORTEZ").
dico("D", 8, "DEPOSAIS").
dico("D", 8, "DEPOSAIT").
dico("D", 8, "DEPOSANT").
dico("D", 8, "DEPOSEES").
dico("D", 8, "DEPOSENT").
dico("D", 8, "DEPOSERA").
dico("D", 8, "DEPOSIEZ").
dico("D", 8, "DEPOSONS").
dico("D", 8, "DEPOTAGE").
dico("D", 8, "DEPOTAIS").
dico("D", 8, "DEPOTAIT").
dico("D", 8, "DEPOTANT").
dico("D", 8, "DEPOTEES").
dico("D", 8, "DEPOTENT").
dico("D", 8, "DEPOTERA").
dico("D", 8, "DEPOTIEZ").
dico("D", 8, "DEPOTOIR").
dico("D", 8, "DEPOTONS").
dico("D", 8, "DEPOUDRA").
dico("D", 8, "DEPOUDRE").
dico("D", 8, "DEPOURVU").
dico("D", 8, "DEPRAVAI").
dico("D", 8, "DEPRAVAS").
dico("D", 8, "DEPRAVAT").
dico("D", 8, "DEPRAVEE").
dico("D", 8, "DEPRAVER").
dico("D", 8, "DEPRAVES").
dico("D", 8, "DEPRAVEZ").
dico("D", 8, "DEPRECIA").
dico("D", 8, "DEPRECIE").
dico("D", 8, "DEPRENDS").
dico("D", 8, "DEPRENEZ").
dico("D", 8, "DEPRENNE").
dico("D", 8, "DEPRIMAI").
dico("D", 8, "DEPRIMAS").
dico("D", 8, "DEPRIMAT").
dico("D", 8, "DEPRIMEE").
dico("D", 8, "DEPRIMER").
dico("D", 8, "DEPRIMES").
dico("D", 8, "DEPRIMEZ").
dico("D", 8, "DEPRISAI").
dico("D", 8, "DEPRISAS").
dico("D", 8, "DEPRISAT").
dico("D", 8, "DEPRISEE").
dico("D", 8, "DEPRISER").
dico("D", 8, "DEPRISES").
dico("D", 8, "DEPRISEZ").
dico("D", 8, "DEPRISSE").
dico("D", 8, "DEPRITES").
dico("D", 8, "DEPUCELA").
dico("D", 8, "DEPUCELE").
dico("D", 8, "DEPULPAI").
dico("D", 8, "DEPULPAS").
dico("D", 8, "DEPULPAT").
dico("D", 8, "DEPULPEE").
dico("D", 8, "DEPULPER").
dico("D", 8, "DEPULPES").
dico("D", 8, "DEPULPEZ").
dico("D", 8, "DEPURAIS").
dico("D", 8, "DEPURAIT").
dico("D", 8, "DEPURANT").
dico("D", 8, "DEPUREES").
dico("D", 8, "DEPURENT").
dico("D", 8, "DEPURERA").
dico("D", 8, "DEPURIEZ").
dico("D", 8, "DEPURONS").
dico("D", 8, "DEPUTAIS").
dico("D", 8, "DEPUTAIT").
dico("D", 8, "DEPUTANT").
dico("D", 8, "DEPUTEES").
dico("D", 8, "DEPUTENT").
dico("D", 8, "DEPUTERA").
dico("D", 8, "DEPUTIEZ").
dico("D", 8, "DEPUTONS").
dico("D", 8, "DEQUILLA").
dico("D", 8, "DEQUILLE").
dico("D", 8, "DERACINA").
dico("D", 8, "DERACINE").
dico("D", 8, "DERADAIS").
dico("D", 8, "DERADAIT").
dico("D", 8, "DERADANT").
dico("D", 8, "DERADENT").
dico("D", 8, "DERADERA").
dico("D", 8, "DERADIEZ").
dico("D", 8, "DERADONS").
dico("D", 8, "DERAGEAI").
dico("D", 8, "DERAGEAS").
dico("D", 8, "DERAGEAT").
dico("D", 8, "DERAGENT").
dico("D", 8, "DERAGERA").
dico("D", 8, "DERAGIEZ").
dico("D", 8, "DERAIDIE").
dico("D", 8, "DERAIDIR").
dico("D", 8, "DERAIDIS").
dico("D", 8, "DERAIDIT").
dico("D", 8, "DERAIENT").
dico("D", 8, "DERAIERA").
dico("D", 8, "DERAILLA").
dico("D", 8, "DERAILLE").
dico("D", 8, "DERAISON").
dico("D", 8, "DERAMAIS").
dico("D", 8, "DERAMAIT").
dico("D", 8, "DERAMANT").
dico("D", 8, "DERAMEES").
dico("D", 8, "DERAMENT").
dico("D", 8, "DERAMERA").
dico("D", 8, "DERAMIEZ").
dico("D", 8, "DERAMONS").
dico("D", 8, "DERANGEA").
dico("D", 8, "DERANGEE").
dico("D", 8, "DERANGER").
dico("D", 8, "DERANGES").
dico("D", 8, "DERANGEZ").
dico("D", 8, "DERAPAGE").
dico("D", 8, "DERAPAIS").
dico("D", 8, "DERAPAIT").
dico("D", 8, "DERAPANT").
dico("D", 8, "DERAPENT").
dico("D", 8, "DERAPERA").
dico("D", 8, "DERAPIEZ").
dico("D", 8, "DERAPONS").
dico("D", 8, "DERASAIS").
dico("D", 8, "DERASAIT").
dico("D", 8, "DERASANT").
dico("D", 8, "DERASEES").
dico("D", 8, "DERASENT").
dico("D", 8, "DERASERA").
dico("D", 8, "DERASIEZ").
dico("D", 8, "DERASONS").
dico("D", 8, "DERATAIS").
dico("D", 8, "DERATAIT").
dico("D", 8, "DERATANT").
dico("D", 8, "DERATEES").
dico("D", 8, "DERATENT").
dico("D", 8, "DERATERA").
dico("D", 8, "DERATIEZ").
dico("D", 8, "DERATISA").
dico("D", 8, "DERATISE").
dico("D", 8, "DERATONS").
dico("D", 8, "DERAYAGE").
dico("D", 8, "DERAYAIS").
dico("D", 8, "DERAYAIT").
dico("D", 8, "DERAYANT").
dico("D", 8, "DERAYEES").
dico("D", 8, "DERAYENT").
dico("D", 8, "DERAYERA").
dico("D", 8, "DERAYIEZ").
dico("D", 8, "DERAYONS").
dico("D", 8, "DERAYURE").
dico("D", 8, "DERBOUKA").
dico("D", 8, "DERECHEF").
dico("D", 8, "DEREELLE").
dico("D", 8, "DEREGLAI").
dico("D", 8, "DEREGLAS").
dico("D", 8, "DEREGLAT").
dico("D", 8, "DEREGLEE").
dico("D", 8, "DEREGLER").
dico("D", 8, "DEREGLES").
dico("D", 8, "DEREGLEZ").
dico("D", 8, "DEREGULA").
dico("D", 8, "DEREGULE").
dico("D", 8, "DERIDAGE").
dico("D", 8, "DERIDAIS").
dico("D", 8, "DERIDAIT").
dico("D", 8, "DERIDANT").
dico("D", 8, "DERIDEES").
dico("D", 8, "DERIDENT").
dico("D", 8, "DERIDERA").
dico("D", 8, "DERIDIEZ").
dico("D", 8, "DERIDONS").
dico("D", 8, "DERISION").
dico("D", 8, "DERIVAIS").
dico("D", 8, "DERIVAIT").
dico("D", 8, "DERIVANT").
dico("D", 8, "DERIVEES").
dico("D", 8, "DERIVENT").
dico("D", 8, "DERIVERA").
dico("D", 8, "DERIVETA").
dico("D", 8, "DERIVETE").
dico("D", 8, "DERIVEUR").
dico("D", 8, "DERIVIEZ").
dico("D", 8, "DERIVONS").
dico("D", 8, "DERMATOS").
dico("D", 8, "DERMESTE").
dico("D", 8, "DERMIQUE").
dico("D", 8, "DERMITES").
dico("D", 8, "DERNIERE").
dico("D", 8, "DERNIERS").
dico("D", 8, "DEROBADE").
dico("D", 8, "DEROBAIS").
dico("D", 8, "DEROBAIT").
dico("D", 8, "DEROBANT").
dico("D", 8, "DEROBEES").
dico("D", 8, "DEROBENT").
dico("D", 8, "DEROBERA").
dico("D", 8, "DEROBEUR").
dico("D", 8, "DEROBIEZ").
dico("D", 8, "DEROBONS").
dico("D", 8, "DEROCHAI").
dico("D", 8, "DEROCHAS").
dico("D", 8, "DEROCHAT").
dico("D", 8, "DEROCHEE").
dico("D", 8, "DEROCHER").
dico("D", 8, "DEROCHES").
dico("D", 8, "DEROCHEZ").
dico("D", 8, "DERODAIS").
dico("D", 8, "DERODAIT").
dico("D", 8, "DERODANT").
dico("D", 8, "DERODEES").
dico("D", 8, "DERODENT").
dico("D", 8, "DERODERA").
dico("D", 8, "DERODIEZ").
dico("D", 8, "DERODONS").
dico("D", 8, "DEROGEAI").
dico("D", 8, "DEROGEAS").
dico("D", 8, "DEROGEAT").
dico("D", 8, "DEROGENT").
dico("D", 8, "DEROGERA").
dico("D", 8, "DEROGIEZ").
dico("D", 8, "DEROQUAI").
dico("D", 8, "DEROQUAS").
dico("D", 8, "DEROQUAT").
dico("D", 8, "DEROQUEE").
dico("D", 8, "DEROQUER").
dico("D", 8, "DEROQUES").
dico("D", 8, "DEROQUEZ").
dico("D", 8, "DEROUGIE").
dico("D", 8, "DEROUGIR").
dico("D", 8, "DEROUGIS").
dico("D", 8, "DEROUGIT").
dico("D", 8, "DEROULAI").
dico("D", 8, "DEROULAS").
dico("D", 8, "DEROULAT").
dico("D", 8, "DEROULEE").
dico("D", 8, "DEROULER").
dico("D", 8, "DEROULES").
dico("D", 8, "DEROULEZ").
dico("D", 8, "DEROUTAI").
dico("D", 8, "DEROUTAS").
dico("D", 8, "DEROUTAT").
dico("D", 8, "DEROUTEE").
dico("D", 8, "DEROUTER").
dico("D", 8, "DEROUTES").
dico("D", 8, "DEROUTEZ").
dico("D", 8, "DERRICKS").
dico("D", 8, "DERRIERE").
dico("D", 8, "DERUPITA").
dico("D", 8, "DERUPITE").
dico("D", 8, "DERVICHE").
dico("D", 8, "DESABUSA").
dico("D", 8, "DESABUSE").
dico("D", 8, "DESAERAI").
dico("D", 8, "DESAERAS").
dico("D", 8, "DESAERAT").
dico("D", 8, "DESAEREE").
dico("D", 8, "DESAERER").
dico("D", 8, "DESAERES").
dico("D", 8, "DESAEREZ").
dico("D", 8, "DESALPAI").
dico("D", 8, "DESALPAS").
dico("D", 8, "DESALPAT").
dico("D", 8, "DESALPER").
dico("D", 8, "DESALPES").
dico("D", 8, "DESALPEZ").
dico("D", 8, "DESAMAIS").
dico("D", 8, "DESAMAIT").
dico("D", 8, "DESAMANT").
dico("D", 8, "DESAMEES").
dico("D", 8, "DESAMENT").
dico("D", 8, "DESAMERA").
dico("D", 8, "DESAMIEZ").
dico("D", 8, "DESAMINA").
dico("D", 8, "DESAMINE").
dico("D", 8, "DESAMONS").
dico("D", 8, "DESAMOUR").
dico("D", 8, "DESAPAIS").
dico("D", 8, "DESAPAIT").
dico("D", 8, "DESAPANT").
dico("D", 8, "DESAPEES").
dico("D", 8, "DESAPENT").
dico("D", 8, "DESAPERA").
dico("D", 8, "DESAPIEZ").
dico("D", 8, "DESAPONS").
dico("D", 8, "DESARETA").
dico("D", 8, "DESARETE").
dico("D", 8, "DESARMAI").
dico("D", 8, "DESARMAS").
dico("D", 8, "DESARMAT").
dico("D", 8, "DESARMEE").
dico("D", 8, "DESARMER").
dico("D", 8, "DESARMES").
dico("D", 8, "DESARMEZ").
dico("D", 8, "DESARROI").
dico("D", 8, "DESASTRE").
dico("D", 8, "DESAVEUX").
dico("D", 8, "DESAVOUA").
dico("D", 8, "DESAVOUE").
dico("D", 8, "DESAXAIS").
dico("D", 8, "DESAXAIT").
dico("D", 8, "DESAXANT").
dico("D", 8, "DESAXEES").
dico("D", 8, "DESAXENT").
dico("D", 8, "DESAXERA").
dico("D", 8, "DESAXIEZ").
dico("D", 8, "DESAXONS").
dico("D", 8, "DESCELLA").
dico("D", 8, "DESCELLE").
dico("D", 8, "DESCENDE").
dico("D", 8, "DESCENDS").
dico("D", 8, "DESCENDU").
dico("D", 8, "DESCENTE").
dico("D", 8, "DESDITES").
dico("D", 8, "DESEMBUA").
dico("D", 8, "DESEMBUE").
dico("D", 8, "DESEMPLI").
dico("D", 8, "DESENCRA").
dico("D", 8, "DESENCRE").
dico("D", 8, "DESENFLA").
dico("D", 8, "DESENFLE").
dico("D", 8, "DESERTAI").
dico("D", 8, "DESERTAS").
dico("D", 8, "DESERTAT").
dico("D", 8, "DESERTEE").
dico("D", 8, "DESERTER").
dico("D", 8, "DESERTES").
dico("D", 8, "DESERTEZ").
dico("D", 8, "DESETAMA").
dico("D", 8, "DESETAME").
dico("D", 8, "DESHERBA").
dico("D", 8, "DESHERBE").
dico("D", 8, "DESHUILA").
dico("D", 8, "DESHUILE").
dico("D", 8, "DESIGNAI").
dico("D", 8, "DESIGNAS").
dico("D", 8, "DESIGNAT").
dico("D", 8, "DESIGNEE").
dico("D", 8, "DESIGNER").
dico("D", 8, "DESIGNES").
dico("D", 8, "DESIGNEZ").
dico("D", 8, "DESILAIS").
dico("D", 8, "DESILAIT").
dico("D", 8, "DESILANT").
dico("D", 8, "DESILEES").
dico("D", 8, "DESILENT").
dico("D", 8, "DESILERA").
dico("D", 8, "DESILIEZ").
dico("D", 8, "DESILONS").
dico("D", 8, "DESIRAIS").
dico("D", 8, "DESIRAIT").
dico("D", 8, "DESIRANT").
dico("D", 8, "DESIREES").
dico("D", 8, "DESIRENT").
dico("D", 8, "DESIRERA").
dico("D", 8, "DESIREUX").
dico("D", 8, "DESIRIEZ").
dico("D", 8, "DESIRONS").
dico("D", 8, "DESISTAI").
dico("D", 8, "DESISTAS").
dico("D", 8, "DESISTAT").
dico("D", 8, "DESISTEE").
dico("D", 8, "DESISTER").
dico("D", 8, "DESISTES").
dico("D", 8, "DESISTEZ").
dico("D", 8, "DESOBEIE").
dico("D", 8, "DESOBEIR").
dico("D", 8, "DESOBEIS").
dico("D", 8, "DESOBEIT").
dico("D", 8, "DESODEES").
dico("D", 8, "DESOLAIS").
dico("D", 8, "DESOLAIT").
dico("D", 8, "DESOLANT").
dico("D", 8, "DESOLEES").
dico("D", 8, "DESOLENT").
dico("D", 8, "DESOLERA").
dico("D", 8, "DESOLIEZ").
dico("D", 8, "DESOLONS").
dico("D", 8, "DESOPILA").
dico("D", 8, "DESOPILE").
dico("D", 8, "DESORDRE").
dico("D", 8, "DESOSSAI").
dico("D", 8, "DESOSSAS").
dico("D", 8, "DESOSSAT").
dico("D", 8, "DESOSSEE").
dico("D", 8, "DESOSSER").
dico("D", 8, "DESOSSES").
dico("D", 8, "DESOSSEZ").
dico("D", 8, "DESOXYDA").
dico("D", 8, "DESOXYDE").
dico("D", 8, "DESPOTAT").
dico("D", 8, "DESPOTES").
dico("D", 8, "DESQUAMA").
dico("D", 8, "DESQUAME").
dico("D", 8, "DESQUELS").
dico("D", 8, "DESSABLA").
dico("D", 8, "DESSABLE").
dico("D", 8, "DESSAISI").
dico("D", 8, "DESSALAI").
dico("D", 8, "DESSALAS").
dico("D", 8, "DESSALAT").
dico("D", 8, "DESSALEE").
dico("D", 8, "DESSALER").
dico("D", 8, "DESSALES").
dico("D", 8, "DESSALEZ").
dico("D", 8, "DESSAPAI").
dico("D", 8, "DESSAPAS").
dico("D", 8, "DESSAPAT").
dico("D", 8, "DESSAPEE").
dico("D", 8, "DESSAPER").
dico("D", 8, "DESSAPES").
dico("D", 8, "DESSAPEZ").
dico("D", 8, "DESSECHA").
dico("D", 8, "DESSECHE").
dico("D", 8, "DESSEINS").
dico("D", 8, "DESSELLA").
dico("D", 8, "DESSELLE").
dico("D", 8, "DESSERRA").
dico("D", 8, "DESSERRE").
dico("D", 8, "DESSERTE").
dico("D", 8, "DESSERTI").
dico("D", 8, "DESSERTS").
dico("D", 8, "DESSERVE").
dico("D", 8, "DESSERVI").
dico("D", 8, "DESSILLA").
dico("D", 8, "DESSILLE").
dico("D", 8, "DESSINAI").
dico("D", 8, "DESSINAS").
dico("D", 8, "DESSINAT").
dico("D", 8, "DESSINEE").
dico("D", 8, "DESSINER").
dico("D", 8, "DESSINES").
dico("D", 8, "DESSINEZ").
dico("D", 8, "DESSOLAI").
dico("D", 8, "DESSOLAS").
dico("D", 8, "DESSOLAT").
dico("D", 8, "DESSOLEE").
dico("D", 8, "DESSOLER").
dico("D", 8, "DESSOLES").
dico("D", 8, "DESSOLEZ").
dico("D", 8, "DESSOUDA").
dico("D", 8, "DESSOUDE").
dico("D", 8, "DESSOULA").
dico("D", 8, "DESSOULE").
dico("D", 8, "DESTINAI").
dico("D", 8, "DESTINAS").
dico("D", 8, "DESTINAT").
dico("D", 8, "DESTINEE").
dico("D", 8, "DESTINER").
dico("D", 8, "DESTINES").
dico("D", 8, "DESTINEZ").
dico("D", 8, "DESTITUA").
dico("D", 8, "DESTITUE").
dico("D", 8, "DESTOCKA").
dico("D", 8, "DESTOCKE").
dico("D", 8, "DESTRIER").
dico("D", 8, "DESUETES").
dico("D", 8, "DESUNIES").
dico("D", 8, "DESUNION").
dico("D", 8, "DESUNIRA").
dico("D", 8, "DETACHAI").
dico("D", 8, "DETACHAS").
dico("D", 8, "DETACHAT").
dico("D", 8, "DETACHEE").
dico("D", 8, "DETACHER").
dico("D", 8, "DETACHES").
dico("D", 8, "DETACHEZ").
dico("D", 8, "DETAILLA").
dico("D", 8, "DETAILLE").
dico("D", 8, "DETALAIS").
dico("D", 8, "DETALAIT").
dico("D", 8, "DETALANT").
dico("D", 8, "DETALENT").
dico("D", 8, "DETALERA").
dico("D", 8, "DETALIEZ").
dico("D", 8, "DETALONS").
dico("D", 8, "DETARTRA").
dico("D", 8, "DETARTRE").
dico("D", 8, "DETAXAIS").
dico("D", 8, "DETAXAIT").
dico("D", 8, "DETAXANT").
dico("D", 8, "DETAXEES").
dico("D", 8, "DETAXENT").
dico("D", 8, "DETAXERA").
dico("D", 8, "DETAXIEZ").
dico("D", 8, "DETAXONS").
dico("D", 8, "DETECTAI").
dico("D", 8, "DETECTAS").
dico("D", 8, "DETECTAT").
dico("D", 8, "DETECTEE").
dico("D", 8, "DETECTER").
dico("D", 8, "DETECTES").
dico("D", 8, "DETECTEZ").
dico("D", 8, "DETEIGNE").
dico("D", 8, "DETEINTE").
dico("D", 8, "DETEINTS").
dico("D", 8, "DETELAGE").
dico("D", 8, "DETELAIS").
dico("D", 8, "DETELAIT").
dico("D", 8, "DETELANT").
dico("D", 8, "DETELEES").
dico("D", 8, "DETELIEZ").
dico("D", 8, "DETELLES").
dico("D", 8, "DETELONS").
dico("D", 8, "DETENAIS").
dico("D", 8, "DETENAIT").
dico("D", 8, "DETENANT").
dico("D", 8, "DETENDES").
dico("D", 8, "DETENDEZ").
dico("D", 8, "DETENDIS").
dico("D", 8, "DETENDIT").
dico("D", 8, "DETENDRA").
dico("D", 8, "DETENDRE").
dico("D", 8, "DETENDUE").
dico("D", 8, "DETENDUS").
dico("D", 8, "DETENIEZ").
dico("D", 8, "DETENONS").
dico("D", 8, "DETENTES").
dico("D", 8, "DETENUES").
dico("D", 8, "DETERGEA").
dico("D", 8, "DETERGEE").
dico("D", 8, "DETERGER").
dico("D", 8, "DETERGES").
dico("D", 8, "DETERGEZ").
dico("D", 8, "DETERRAI").
dico("D", 8, "DETERRAS").
dico("D", 8, "DETERRAT").
dico("D", 8, "DETERREE").
dico("D", 8, "DETERRER").
dico("D", 8, "DETERRES").
dico("D", 8, "DETERREZ").
dico("D", 8, "DETERSIF").
dico("D", 8, "DETESTAI").
dico("D", 8, "DETESTAS").
dico("D", 8, "DETESTAT").
dico("D", 8, "DETESTEE").
dico("D", 8, "DETESTER").
dico("D", 8, "DETESTES").
dico("D", 8, "DETESTEZ").
dico("D", 8, "DETHEINA").
dico("D", 8, "DETHEINE").
dico("D", 8, "DETIENNE").
dico("D", 8, "DETINMES").
dico("D", 8, "DETINSSE").
dico("D", 8, "DETINTES").
dico("D", 8, "DETIRAIS").
dico("D", 8, "DETIRAIT").
dico("D", 8, "DETIRANT").
dico("D", 8, "DETIREES").
dico("D", 8, "DETIRENT").
dico("D", 8, "DETIRERA").
dico("D", 8, "DETIRIEZ").
dico("D", 8, "DETIRONS").
dico("D", 8, "DETONAIS").
dico("D", 8, "DETONAIT").
dico("D", 8, "DETONANT").
dico("D", 8, "DETONENT").
dico("D", 8, "DETONERA").
dico("D", 8, "DETONIEZ").
dico("D", 8, "DETONNAI").
dico("D", 8, "DETONNAS").
dico("D", 8, "DETONNAT").
dico("D", 8, "DETONNER").
dico("D", 8, "DETONNES").
dico("D", 8, "DETONNEZ").
dico("D", 8, "DETONONS").
dico("D", 8, "DETORDES").
dico("D", 8, "DETORDEZ").
dico("D", 8, "DETORDIS").
dico("D", 8, "DETORDIT").
dico("D", 8, "DETORDRA").
dico("D", 8, "DETORDRE").
dico("D", 8, "DETORDUE").
dico("D", 8, "DETORDUS").
dico("D", 8, "DETORSES").
dico("D", 8, "DETOURAI").
dico("D", 8, "DETOURAS").
dico("D", 8, "DETOURAT").
dico("D", 8, "DETOUREE").
dico("D", 8, "DETOURER").
dico("D", 8, "DETOURES").
dico("D", 8, "DETOUREZ").
dico("D", 8, "DETOURNA").
dico("D", 8, "DETOURNE").
dico("D", 8, "DETRACTA").
dico("D", 8, "DETRACTE").
dico("D", 8, "DETRAQUA").
dico("D", 8, "DETRAQUE").
dico("D", 8, "DETREMPA").
dico("D", 8, "DETREMPE").
dico("D", 8, "DETRESSE").
dico("D", 8, "DETRITUS").
dico("D", 8, "DETROITS").
dico("D", 8, "DETROMPA").
dico("D", 8, "DETROMPE").
dico("D", 8, "DETRONAI").
dico("D", 8, "DETRONAS").
dico("D", 8, "DETRONAT").
dico("D", 8, "DETRONEE").
dico("D", 8, "DETRONER").
dico("D", 8, "DETRONES").
dico("D", 8, "DETRONEZ").
dico("D", 8, "DETROQUA").
dico("D", 8, "DETROQUE").
dico("D", 8, "DETRUIRA").
dico("D", 8, "DETRUIRE").
dico("D", 8, "DETRUISE").
dico("D", 8, "DETRUITE").
dico("D", 8, "DETRUITS").
dico("D", 8, "DEUTERON").
dico("D", 8, "DEUXIEME").
dico("D", 8, "DEVADASI").
dico("D", 8, "DEVAIENT").
dico("D", 8, "DEVALAIS").
dico("D", 8, "DEVALAIT").
dico("D", 8, "DEVALANT").
dico("D", 8, "DEVALEES").
dico("D", 8, "DEVALENT").
dico("D", 8, "DEVALERA").
dico("D", 8, "DEVALIEZ").
dico("D", 8, "DEVALISA").
dico("D", 8, "DEVALISE").
dico("D", 8, "DEVALOIR").
dico("D", 8, "DEVALONS").
dico("D", 8, "DEVALUAI").
dico("D", 8, "DEVALUAS").
dico("D", 8, "DEVALUAT").
dico("D", 8, "DEVALUEE").
dico("D", 8, "DEVALUER").
dico("D", 8, "DEVALUES").
dico("D", 8, "DEVALUEZ").
dico("D", 8, "DEVANCAI").
dico("D", 8, "DEVANCAS").
dico("D", 8, "DEVANCAT").
dico("D", 8, "DEVANCEE").
dico("D", 8, "DEVANCER").
dico("D", 8, "DEVANCES").
dico("D", 8, "DEVANCEZ").
dico("D", 8, "DEVASAIS").
dico("D", 8, "DEVASAIT").
dico("D", 8, "DEVASANT").
dico("D", 8, "DEVASEES").
dico("D", 8, "DEVASENT").
dico("D", 8, "DEVASERA").
dico("D", 8, "DEVASIEZ").
dico("D", 8, "DEVASONS").
dico("D", 8, "DEVASTAI").
dico("D", 8, "DEVASTAS").
dico("D", 8, "DEVASTAT").
dico("D", 8, "DEVASTEE").
dico("D", 8, "DEVASTER").
dico("D", 8, "DEVASTES").
dico("D", 8, "DEVASTEZ").
dico("D", 8, "DEVEINES").
dico("D", 8, "DEVENAIS").
dico("D", 8, "DEVENAIT").
dico("D", 8, "DEVENANT").
dico("D", 8, "DEVENIEZ").
dico("D", 8, "DEVENIRS").
dico("D", 8, "DEVENONS").
dico("D", 8, "DEVENTAI").
dico("D", 8, "DEVENTAS").
dico("D", 8, "DEVENTAT").
dico("D", 8, "DEVENTEE").
dico("D", 8, "DEVENTER").
dico("D", 8, "DEVENTES").
dico("D", 8, "DEVENTEZ").
dico("D", 8, "DEVENUES").
dico("D", 8, "DEVERBAL").
dico("D", 8, "DEVERDIE").
dico("D", 8, "DEVERDIR").
dico("D", 8, "DEVERDIS").
dico("D", 8, "DEVERDIT").
dico("D", 8, "DEVERGUA").
dico("D", 8, "DEVERGUE").
dico("D", 8, "DEVERNIE").
dico("D", 8, "DEVERNIR").
dico("D", 8, "DEVERNIS").
dico("D", 8, "DEVERNIT").
dico("D", 8, "DEVERSAI").
dico("D", 8, "DEVERSAS").
dico("D", 8, "DEVERSAT").
dico("D", 8, "DEVERSEE").
dico("D", 8, "DEVERSER").
dico("D", 8, "DEVERSES").
dico("D", 8, "DEVERSEZ").
dico("D", 8, "DEVETAIS").
dico("D", 8, "DEVETAIT").
dico("D", 8, "DEVETANT").
dico("D", 8, "DEVETENT").
dico("D", 8, "DEVETIEZ").
dico("D", 8, "DEVETIRA").
dico("D", 8, "DEVETONS").
dico("D", 8, "DEVETUES").
dico("D", 8, "DEVIAMES").
dico("D", 8, "DEVIANCE").
dico("D", 8, "DEVIANTE").
dico("D", 8, "DEVIANTS").
dico("D", 8, "DEVIASSE").
dico("D", 8, "DEVIATES").
dico("D", 8, "DEVIDAGE").
dico("D", 8, "DEVIDAIS").
dico("D", 8, "DEVIDAIT").
dico("D", 8, "DEVIDANT").
dico("D", 8, "DEVIDEES").
dico("D", 8, "DEVIDENT").
dico("D", 8, "DEVIDERA").
dico("D", 8, "DEVIDEUR").
dico("D", 8, "DEVIDIEZ").
dico("D", 8, "DEVIDOIR").
dico("D", 8, "DEVIDONS").
dico("D", 8, "DEVIENNE").
dico("D", 8, "DEVIERAI").
dico("D", 8, "DEVIERAS").
dico("D", 8, "DEVIEREZ").
dico("D", 8, "DEVIIONS").
dico("D", 8, "DEVINAIS").
dico("D", 8, "DEVINAIT").
dico("D", 8, "DEVINANT").
dico("D", 8, "DEVINEES").
dico("D", 8, "DEVINENT").
dico("D", 8, "DEVINERA").
dico("D", 8, "DEVINEUR").
dico("D", 8, "DEVINIEZ").
dico("D", 8, "DEVINMES").
dico("D", 8, "DEVINONS").
dico("D", 8, "DEVINSSE").
dico("D", 8, "DEVINTES").
dico("D", 8, "DEVIRAIS").
dico("D", 8, "DEVIRAIT").
dico("D", 8, "DEVIRANT").
dico("D", 8, "DEVIREES").
dico("D", 8, "DEVIRENT").
dico("D", 8, "DEVIRERA").
dico("D", 8, "DEVIRIEZ").
dico("D", 8, "DEVIRONS").
dico("D", 8, "DEVISAGE").
dico("D", 8, "DEVISAIS").
dico("D", 8, "DEVISAIT").
dico("D", 8, "DEVISANT").
dico("D", 8, "DEVISEES").
dico("D", 8, "DEVISENT").
dico("D", 8, "DEVISERA").
dico("D", 8, "DEVISIEZ").
dico("D", 8, "DEVISONS").
dico("D", 8, "DEVISSAI").
dico("D", 8, "DEVISSAS").
dico("D", 8, "DEVISSAT").
dico("D", 8, "DEVISSEE").
dico("D", 8, "DEVISSER").
dico("D", 8, "DEVISSES").
dico("D", 8, "DEVISSEZ").
dico("D", 8, "DEVOIENT").
dico("D", 8, "DEVOIERA").
dico("D", 8, "DEVOILAI").
dico("D", 8, "DEVOILAS").
dico("D", 8, "DEVOILAT").
dico("D", 8, "DEVOILEE").
dico("D", 8, "DEVOILER").
dico("D", 8, "DEVOILES").
dico("D", 8, "DEVOILEZ").
dico("D", 8, "DEVOISEE").
dico("D", 8, "DEVOISES").
dico("D", 8, "DEVOLTAI").
dico("D", 8, "DEVOLTAS").
dico("D", 8, "DEVOLTAT").
dico("D", 8, "DEVOLTEE").
dico("D", 8, "DEVOLTER").
dico("D", 8, "DEVOLTES").
dico("D", 8, "DEVOLTEZ").
dico("D", 8, "DEVOLUES").
dico("D", 8, "DEVONIEN").
dico("D", 8, "DEVORAIS").
dico("D", 8, "DEVORAIT").
dico("D", 8, "DEVORANT").
dico("D", 8, "DEVOREES").
dico("D", 8, "DEVORENT").
dico("D", 8, "DEVORERA").
dico("D", 8, "DEVOREUR").
dico("D", 8, "DEVORIEZ").
dico("D", 8, "DEVORONS").
dico("D", 8, "DEVOTION").
dico("D", 8, "DEVOUAIS").
dico("D", 8, "DEVOUAIT").
dico("D", 8, "DEVOUANT").
dico("D", 8, "DEVOUEES").
dico("D", 8, "DEVOUENT").
dico("D", 8, "DEVOUERA").
dico("D", 8, "DEVOUIEZ").
dico("D", 8, "DEVOUONS").
dico("D", 8, "DEVOYAIS").
dico("D", 8, "DEVOYAIT").
dico("D", 8, "DEVOYANT").
dico("D", 8, "DEVOYEES").
dico("D", 8, "DEVOYIEZ").
dico("D", 8, "DEVOYONS").
dico("D", 8, "DEVRILLA").
dico("D", 8, "DEVRILLE").
dico("D", 8, "DEVRIONS").
dico("D", 8, "DEWATTEE").
dico("D", 8, "DEWATTES").
dico("D", 8, "DEXTRINE").
dico("D", 8, "DEXTROSE").
dico("D", 8, "DEZINGUA").
dico("D", 8, "DEZINGUE").
dico("D", 8, "DEZIPPAI").
dico("D", 8, "DEZIPPAS").
dico("D", 8, "DEZIPPAT").
dico("D", 8, "DEZIPPEE").
dico("D", 8, "DEZIPPER").
dico("D", 8, "DEZIPPES").
dico("D", 8, "DEZIPPEZ").
dico("D", 8, "DEZONAGE").
dico("D", 8, "DEZONAIS").
dico("D", 8, "DEZONAIT").
dico("D", 8, "DEZONANT").
dico("D", 8, "DEZONEES").
dico("D", 8, "DEZONENT").
dico("D", 8, "DEZONERA").
dico("D", 8, "DEZONIEZ").
dico("D", 8, "DEZONONS").
dico("D", 8, "DIABETES").
dico("D", 8, "DIABOLOS").
dico("D", 8, "DIACIDES").
dico("D", 8, "DIACLASE").
dico("D", 8, "DIACODES").
dico("D", 8, "DIACONAL").
dico("D", 8, "DIACONAT").
dico("D", 8, "DIADEMES").
dico("D", 8, "DIADOQUE").
dico("D", 8, "DIAGNOSE").
dico("D", 8, "DIAGONAL").
dico("D", 8, "DIAKENES").
dico("D", 8, "DIALCOOL").
dico("D", 8, "DIALECTE").
dico("D", 8, "DIALLELE").
dico("D", 8, "DIALOGUA").
dico("D", 8, "DIALOGUE").
dico("D", 8, "DIALYSAI").
dico("D", 8, "DIALYSAS").
dico("D", 8, "DIALYSAT").
dico("D", 8, "DIALYSEE").
dico("D", 8, "DIALYSER").
dico("D", 8, "DIALYSES").
dico("D", 8, "DIALYSEZ").
dico("D", 8, "DIAMANTA").
dico("D", 8, "DIAMANTE").
dico("D", 8, "DIAMANTS").
dico("D", 8, "DIAMETRE").
dico("D", 8, "DIAMIDES").
dico("D", 8, "DIAMINES").
dico("D", 8, "DIAPASON").
dico("D", 8, "DIAPAUSE").
dico("D", 8, "DIAPHANE").
dico("D", 8, "DIAPHYSE").
dico("D", 8, "DIAPRAIS").
dico("D", 8, "DIAPRAIT").
dico("D", 8, "DIAPRANT").
dico("D", 8, "DIAPREES").
dico("D", 8, "DIAPRENT").
dico("D", 8, "DIAPRERA").
dico("D", 8, "DIAPRIEZ").
dico("D", 8, "DIAPRONS").
dico("D", 8, "DIAPRURE").
dico("D", 8, "DIARISTE").
dico("D", 8, "DIARRHEE").
dico("D", 8, "DIASCOPE").
dico("D", 8, "DIASPORA").
dico("D", 8, "DIASTASE").
dico("D", 8, "DIASTOLE").
dico("D", 8, "DIATHESE").
dico("D", 8, "DIATOMEE").
dico("D", 8, "DIATRIBE").
dico("D", 8, "DIAZEPAM").
dico("D", 8, "DIAZOTES").
dico("D", 8, "DICARYON").
dico("D", 8, "DICENTRA").
dico("D", 8, "DICETONE").
dico("D", 8, "DICLINES").
dico("D", 8, "DICROTES").
dico("D", 8, "DICTAMES").
dico("D", 8, "DICTASSE").
dico("D", 8, "DICTATES").
dico("D", 8, "DICTERAI").
dico("D", 8, "DICTERAS").
dico("D", 8, "DICTEREZ").
dico("D", 8, "DICTIONS").
dico("D", 8, "DIENIQUE").
dico("D", 8, "DIEPPOIS").
dico("D", 8, "DIERESES").
dico("D", 8, "DIERGOLS").
dico("D", 8, "DIESAMES").
dico("D", 8, "DIESASSE").
dico("D", 8, "DIESATES").
dico("D", 8, "DIESERAI").
dico("D", 8, "DIESERAS").
dico("D", 8, "DIESEREZ").
dico("D", 8, "DIESIONS").
dico("D", 8, "DIESTERS").
dico("D", 8, "DIFFAMAI").
dico("D", 8, "DIFFAMAS").
dico("D", 8, "DIFFAMAT").
dico("D", 8, "DIFFAMEE").
dico("D", 8, "DIFFAMER").
dico("D", 8, "DIFFAMES").
dico("D", 8, "DIFFAMEZ").
dico("D", 8, "DIFFERAI").
dico("D", 8, "DIFFERAS").
dico("D", 8, "DIFFERAT").
dico("D", 8, "DIFFEREE").
dico("D", 8, "DIFFERER").
dico("D", 8, "DIFFERES").
dico("D", 8, "DIFFEREZ").
dico("D", 8, "DIFFLUAI").
dico("D", 8, "DIFFLUAS").
dico("D", 8, "DIFFLUAT").
dico("D", 8, "DIFFLUER").
dico("D", 8, "DIFFLUES").
dico("D", 8, "DIFFLUEZ").
dico("D", 8, "DIFFORME").
dico("D", 8, "DIFFUSAI").
dico("D", 8, "DIFFUSAS").
dico("D", 8, "DIFFUSAT").
dico("D", 8, "DIFFUSEE").
dico("D", 8, "DIFFUSER").
dico("D", 8, "DIFFUSES").
dico("D", 8, "DIFFUSEZ").
dico("D", 8, "DIGERAIS").
dico("D", 8, "DIGERAIT").
dico("D", 8, "DIGERANT").
dico("D", 8, "DIGEREES").
dico("D", 8, "DIGERENT").
dico("D", 8, "DIGERERA").
dico("D", 8, "DIGERIEZ").
dico("D", 8, "DIGERONS").
dico("D", 8, "DIGESTES").
dico("D", 8, "DIGESTIF").
dico("D", 8, "DIGICODE").
dico("D", 8, "DIGITALE").
dico("D", 8, "DIGITAUX").
dico("D", 8, "DIGITEES").
dico("D", 8, "DIGNITES").
dico("D", 8, "DIGNOISE").
dico("D", 8, "DIGRAMME").
dico("D", 8, "DIGRESSA").
dico("D", 8, "DIGRESSE").
dico("D", 8, "DILACERA").
dico("D", 8, "DILACERE").
dico("D", 8, "DILAPIDA").
dico("D", 8, "DILAPIDE").
dico("D", 8, "DILATAIS").
dico("D", 8, "DILATAIT").
dico("D", 8, "DILATANT").
dico("D", 8, "DILATEES").
dico("D", 8, "DILATENT").
dico("D", 8, "DILATERA").
dico("D", 8, "DILATIEZ").
dico("D", 8, "DILATION").
dico("D", 8, "DILATONS").
dico("D", 8, "DILEMMES").
dico("D", 8, "DILIGENT").
dico("D", 8, "DILUAMES").
dico("D", 8, "DILUANTS").
dico("D", 8, "DILUASSE").
dico("D", 8, "DILUATES").
dico("D", 8, "DILUERAI").
dico("D", 8, "DILUERAS").
dico("D", 8, "DILUEREZ").
dico("D", 8, "DILUEURS").
dico("D", 8, "DILUIONS").
dico("D", 8, "DILUTION").
dico("D", 8, "DILUVIAL").
dico("D", 8, "DILUVIEN").
dico("D", 8, "DILUVIUM").
dico("D", 8, "DIMANCHE").
dico("D", 8, "DIMINUAI").
dico("D", 8, "DIMINUAS").
dico("D", 8, "DIMINUAT").
dico("D", 8, "DIMINUEE").
dico("D", 8, "DIMINUER").
dico("D", 8, "DIMINUES").
dico("D", 8, "DIMINUEZ").
dico("D", 8, "DIMORPHE").
dico("D", 8, "DINAIENT").
dico("D", 8, "DINASSES").
dico("D", 8, "DINDONNA").
dico("D", 8, "DINDONNE").
dico("D", 8, "DINERAIS").
dico("D", 8, "DINERAIT").
dico("D", 8, "DINERENT").
dico("D", 8, "DINERIEZ").
dico("D", 8, "DINERONS").
dico("D", 8, "DINERONT").
dico("D", 8, "DINETTES").
dico("D", 8, "DINEUSES").
dico("D", 8, "DINGBATS").
dico("D", 8, "DINGHIES").
dico("D", 8, "DINGUAIS").
dico("D", 8, "DINGUAIT").
dico("D", 8, "DINGUANT").
dico("D", 8, "DINGUENT").
dico("D", 8, "DINGUERA").
dico("D", 8, "DINGUIEZ").
dico("D", 8, "DINGUONS").
dico("D", 8, "DINORNIS").
dico("D", 8, "DIOCESES").
dico("D", 8, "DIOECIES").
dico("D", 8, "DIOIQUES").
dico("D", 8, "DIOPTRES").
dico("D", 8, "DIOPTRIE").
dico("D", 8, "DIORAMAS").
dico("D", 8, "DIORITES").
dico("D", 8, "DIOXINES").
dico("D", 8, "DIOXYDES").
dico("D", 8, "DIPETALE").
dico("D", 8, "DIPHASEE").
dico("D", 8, "DIPHASES").
dico("D", 8, "DIPHENOL").
dico("D", 8, "DIPLOIDE").
dico("D", 8, "DIPLOMAI").
dico("D", 8, "DIPLOMAS").
dico("D", 8, "DIPLOMAT").
dico("D", 8, "DIPLOMEE").
dico("D", 8, "DIPLOMER").
dico("D", 8, "DIPLOMES").
dico("D", 8, "DIPLOMEZ").
dico("D", 8, "DIPLOPIE").
dico("D", 8, "DIPSACEE").
dico("D", 8, "DIPTERES").
dico("D", 8, "DIPTYQUE").
dico("D", 8, "DIRAIENT").
dico("D", 8, "DIRECTES").
dico("D", 8, "DIRECTIF").
dico("D", 8, "DIRIGEAI").
dico("D", 8, "DIRIGEAS").
dico("D", 8, "DIRIGEAT").
dico("D", 8, "DIRIGEES").
dico("D", 8, "DIRIGENT").
dico("D", 8, "DIRIGERA").
dico("D", 8, "DIRIGIEZ").
dico("D", 8, "DIRIMANT").
dico("D", 8, "DISABLES").
dico("D", 8, "DISAIENT").
dico("D", 8, "DISAMARE").
dico("D", 8, "DISCALES").
dico("D", 8, "DISCERNA").
dico("D", 8, "DISCERNE").
dico("D", 8, "DISCIPLE").
dico("D", 8, "DISCOIDE").
dico("D", 8, "DISCORDA").
dico("D", 8, "DISCORDE").
dico("D", 8, "DISCORDS").
dico("D", 8, "DISCOUNT").
dico("D", 8, "DISCOURE").
dico("D", 8, "DISCOURS").
dico("D", 8, "DISCOURT").
dico("D", 8, "DISCOURU").
dico("D", 8, "DISCRETE").
dico("D", 8, "DISCRETS").
dico("D", 8, "DISCULPA").
dico("D", 8, "DISCULPE").
dico("D", 8, "DISCUTAI").
dico("D", 8, "DISCUTAS").
dico("D", 8, "DISCUTAT").
dico("D", 8, "DISCUTEE").
dico("D", 8, "DISCUTER").
dico("D", 8, "DISCUTES").
dico("D", 8, "DISCUTEZ").
dico("D", 8, "DISERTES").
dico("D", 8, "DISETTES").
dico("D", 8, "DISEUSES").
dico("D", 8, "DISGRACE").
dico("D", 8, "DISJOINS").
dico("D", 8, "DISJOINT").
dico("D", 8, "DISLOQUA").
dico("D", 8, "DISLOQUE").
dico("D", 8, "DISPARUE").
dico("D", 8, "DISPARUS").
dico("D", 8, "DISPARUT").
dico("D", 8, "DISPENSA").
dico("D", 8, "DISPENSE").
dico("D", 8, "DISPERSA").
dico("D", 8, "DISPERSE").
dico("D", 8, "DISPOSAI").
dico("D", 8, "DISPOSAS").
dico("D", 8, "DISPOSAT").
dico("D", 8, "DISPOSEE").
dico("D", 8, "DISPOSER").
dico("D", 8, "DISPOSES").
dico("D", 8, "DISPOSEZ").
dico("D", 8, "DISPUTAI").
dico("D", 8, "DISPUTAS").
dico("D", 8, "DISPUTAT").
dico("D", 8, "DISPUTEE").
dico("D", 8, "DISPUTER").
dico("D", 8, "DISPUTES").
dico("D", 8, "DISPUTEZ").
dico("D", 8, "DISQUAIS").
dico("D", 8, "DISQUAIT").
dico("D", 8, "DISQUANT").
dico("D", 8, "DISQUEES").
dico("D", 8, "DISQUENT").
dico("D", 8, "DISQUERA").
dico("D", 8, "DISQUIEZ").
dico("D", 8, "DISQUONS").
dico("D", 8, "DISSEQUA").
dico("D", 8, "DISSEQUE").
dico("D", 8, "DISSERTA").
dico("D", 8, "DISSERTE").
dico("D", 8, "DISSIONS").
dico("D", 8, "DISSIPAI").
dico("D", 8, "DISSIPAS").
dico("D", 8, "DISSIPAT").
dico("D", 8, "DISSIPEE").
dico("D", 8, "DISSIPER").
dico("D", 8, "DISSIPES").
dico("D", 8, "DISSIPEZ").
dico("D", 8, "DISSOCIA").
dico("D", 8, "DISSOCIE").
dico("D", 8, "DISSOLUE").
dico("D", 8, "DISSOLUS").
dico("D", 8, "DISSOLUT").
dico("D", 8, "DISSOLVE").
dico("D", 8, "DISSONAI").
dico("D", 8, "DISSONAS").
dico("D", 8, "DISSONAT").
dico("D", 8, "DISSONER").
dico("D", 8, "DISSONES").
dico("D", 8, "DISSONEZ").
dico("D", 8, "DISSOUTE").
dico("D", 8, "DISSUADA").
dico("D", 8, "DISSUADE").
dico("D", 8, "DISTALES").
dico("D", 8, "DISTANCA").
dico("D", 8, "DISTANCE").
dico("D", 8, "DISTANTE").
dico("D", 8, "DISTANTS").
dico("D", 8, "DISTENDE").
dico("D", 8, "DISTENDS").
dico("D", 8, "DISTENDU").
dico("D", 8, "DISTHENE").
dico("D", 8, "DISTILLA").
dico("D", 8, "DISTILLE").
dico("D", 8, "DISTINCT").
dico("D", 8, "DISTIQUE").
dico("D", 8, "DISTOMES").
dico("D", 8, "DISTORDE").
dico("D", 8, "DISTORDS").
dico("D", 8, "DISTORDU").
dico("D", 8, "DISTORSE").
dico("D", 8, "DISTRAIE").
dico("D", 8, "DISTRAIS").
dico("D", 8, "DISTRAIT").
dico("D", 8, "DISTRICT").
dico("D", 8, "DISTYLES").
dico("D", 8, "DIURESES").
dico("D", 8, "DIURNAUX").
dico("D", 8, "DIVAGUAI").
dico("D", 8, "DIVAGUAS").
dico("D", 8, "DIVAGUAT").
dico("D", 8, "DIVAGUER").
dico("D", 8, "DIVAGUES").
dico("D", 8, "DIVAGUEZ").
dico("D", 8, "DIVALENT").
dico("D", 8, "DIVERGEA").
dico("D", 8, "DIVERGER").
dico("D", 8, "DIVERGES").
dico("D", 8, "DIVERGEZ").
dico("D", 8, "DIVERSES").
dico("D", 8, "DIVERTIE").
dico("D", 8, "DIVERTIR").
dico("D", 8, "DIVERTIS").
dico("D", 8, "DIVERTIT").
dico("D", 8, "DIVETTES").
dico("D", 8, "DIVINISA").
dico("D", 8, "DIVINISE").
dico("D", 8, "DIVINITE").
dico("D", 8, "DIVISAIS").
dico("D", 8, "DIVISAIT").
dico("D", 8, "DIVISANT").
dico("D", 8, "DIVISEES").
dico("D", 8, "DIVISENT").
dico("D", 8, "DIVISERA").
dico("D", 8, "DIVISEUR").
dico("D", 8, "DIVISIEZ").
dico("D", 8, "DIVISION").
dico("D", 8, "DIVISONS").
dico("D", 8, "DIVORCAI").
dico("D", 8, "DIVORCAS").
dico("D", 8, "DIVORCAT").
dico("D", 8, "DIVORCEE").
dico("D", 8, "DIVORCER").
dico("D", 8, "DIVORCES").
dico("D", 8, "DIVORCEZ").
dico("D", 8, "DIVULGUA").
dico("D", 8, "DIVULGUE").
dico("D", 8, "DIXIEMES").
dico("D", 8, "DIZAINES").
dico("D", 8, "DIZENIER").
dico("D", 8, "DIZYGOTE").
dico("D", 8, "DJELLABA").
dico("D", 8, "DOBERMAN").
dico("D", 8, "DOCILITE").
dico("D", 8, "DOCTEURS").
dico("D", 8, "DOCTORAL").
dico("D", 8, "DOCTORAT").
dico("D", 8, "DOCTRINE").
dico("D", 8, "DOCUMENT").
dico("D", 8, "DODELINA").
dico("D", 8, "DODELINE").
dico("D", 8, "DODINAGE").
dico("D", 8, "DODINAIS").
dico("D", 8, "DODINAIT").
dico("D", 8, "DODINANT").
dico("D", 8, "DODINEES").
dico("D", 8, "DODINENT").
dico("D", 8, "DODINERA").
dico("D", 8, "DODINIEZ").
dico("D", 8, "DODINONS").
dico("D", 8, "DODOMAIS").
dico("D", 8, "DOGUINES").
dico("D", 8, "DOIGTAIS").
dico("D", 8, "DOIGTAIT").
dico("D", 8, "DOIGTANT").
dico("D", 8, "DOIGTEES").
dico("D", 8, "DOIGTENT").
dico("D", 8, "DOIGTERA").
dico("D", 8, "DOIGTIER").
dico("D", 8, "DOIGTIEZ").
dico("D", 8, "DOIGTONS").
dico("D", 8, "DOLAIENT").
dico("D", 8, "DOLASSES").
dico("D", 8, "DOLDRUMS").
dico("D", 8, "DOLEANCE").
dico("D", 8, "DOLENTES").
dico("D", 8, "DOLERAIS").
dico("D", 8, "DOLERAIT").
dico("D", 8, "DOLERENT").
dico("D", 8, "DOLERIEZ").
dico("D", 8, "DOLERONS").
dico("D", 8, "DOLERONT").
dico("D", 8, "DOLIQUES").
dico("D", 8, "DOLOIRES").
dico("D", 8, "DOLOMIES").
dico("D", 8, "DOLOMITE").
dico("D", 8, "DOLOSIFS").
dico("D", 8, "DOLOSIVE").
dico("D", 8, "DOMAINES").
dico("D", 8, "DOMANIAL").
dico("D", 8, "DOMICILE").
dico("D", 8, "DOMIENNE").
dico("D", 8, "DOMINAIS").
dico("D", 8, "DOMINAIT").
dico("D", 8, "DOMINANT").
dico("D", 8, "DOMINEES").
dico("D", 8, "DOMINENT").
dico("D", 8, "DOMINERA").
dico("D", 8, "DOMINIEZ").
dico("D", 8, "DOMINION").
dico("D", 8, "DOMINONS").
dico("D", 8, "DOMISMES").
dico("D", 8, "DOMMAGES").
dico("D", 8, "DOMPTAGE").
dico("D", 8, "DOMPTAIS").
dico("D", 8, "DOMPTAIT").
dico("D", 8, "DOMPTANT").
dico("D", 8, "DOMPTEES").
dico("D", 8, "DOMPTENT").
dico("D", 8, "DOMPTERA").
dico("D", 8, "DOMPTEUR").
dico("D", 8, "DOMPTIEZ").
dico("D", 8, "DOMPTONS").
dico("D", 8, "DONACIES").
dico("D", 8, "DONATEUR").
dico("D", 8, "DONATION").
dico("D", 8, "DONDAINE").
dico("D", 8, "DONNAMES").
dico("D", 8, "DONNANTE").
dico("D", 8, "DONNANTS").
dico("D", 8, "DONNASSE").
dico("D", 8, "DONNATES").
dico("D", 8, "DONNERAI").
dico("D", 8, "DONNERAS").
dico("D", 8, "DONNEREZ").
dico("D", 8, "DONNEURS").
dico("D", 8, "DONNEUSE").
dico("D", 8, "DONNIONS").
dico("D", 8, "DONZELLE").
dico("D", 8, "DOPAIENT").
dico("D", 8, "DOPAMINE").
dico("D", 8, "DOPANTES").
dico("D", 8, "DOPASSES").
dico("D", 8, "DOPERAIS").
dico("D", 8, "DOPERAIT").
dico("D", 8, "DOPERENT").
dico("D", 8, "DOPERIEZ").
dico("D", 8, "DOPERONS").
dico("D", 8, "DOPERONT").
dico("D", 8, "DOPPLERS").
dico("D", 8, "DORAIENT").
dico("D", 8, "DORASSES").
dico("D", 8, "DORERAIS").
dico("D", 8, "DORERAIT").
dico("D", 8, "DORERENT").
dico("D", 8, "DORERIEZ").
dico("D", 8, "DORERONS").
dico("D", 8, "DORERONT").
dico("D", 8, "DOREUSES").
dico("D", 8, "DORIENNE").
dico("D", 8, "DORIQUES").
dico("D", 8, "DORLOTAI").
dico("D", 8, "DORLOTAS").
dico("D", 8, "DORLOTAT").
dico("D", 8, "DORLOTEE").
dico("D", 8, "DORLOTER").
dico("D", 8, "DORLOTES").
dico("D", 8, "DORLOTEZ").
dico("D", 8, "DORMANCE").
dico("D", 8, "DORMANTE").
dico("D", 8, "DORMANTS").
dico("D", 8, "DORMEURS").
dico("D", 8, "DORMEUSE").
dico("D", 8, "DORMIMES").
dico("D", 8, "DORMIONS").
dico("D", 8, "DORMIRAI").
dico("D", 8, "DORMIRAS").
dico("D", 8, "DORMIREZ").
dico("D", 8, "DORMISSE").
dico("D", 8, "DORMITES").
dico("D", 8, "DORMITIF").
dico("D", 8, "DORSALES").
dico("D", 8, "DORTOIRS").
dico("D", 8, "DOSABLES").
dico("D", 8, "DOSAIENT").
dico("D", 8, "DOSASSES").
dico("D", 8, "DOSERAIS").
dico("D", 8, "DOSERAIT").
dico("D", 8, "DOSERENT").
dico("D", 8, "DOSERIEZ").
dico("D", 8, "DOSERONS").
dico("D", 8, "DOSERONT").
dico("D", 8, "DOSETTES").
dico("D", 8, "DOSSARDS").
dico("D", 8, "DOSSERET").
dico("D", 8, "DOSSIERE").
dico("D", 8, "DOSSIERS").
dico("D", 8, "DOSSISTE").
dico("D", 8, "DOTAIENT").
dico("D", 8, "DOTALITE").
dico("D", 8, "DOTASSES").
dico("D", 8, "DOTATION").
dico("D", 8, "DOTERAIS").
dico("D", 8, "DOTERAIT").
dico("D", 8, "DOTERENT").
dico("D", 8, "DOTERIEZ").
dico("D", 8, "DOTERONS").
dico("D", 8, "DOTERONT").
dico("D", 8, "DOUAIENT").
dico("D", 8, "DOUAIRES").
dico("D", 8, "DOUANCES").
dico("D", 8, "DOUANIER").
dico("D", 8, "DOUASSES").
dico("D", 8, "DOUBIENS").
dico("D", 8, "DOUBISTE").
dico("D", 8, "DOUBLAGE").
dico("D", 8, "DOUBLAIS").
dico("D", 8, "DOUBLAIT").
dico("D", 8, "DOUBLANT").
dico("D", 8, "DOUBLEAU").
dico("D", 8, "DOUBLEES").
dico("D", 8, "DOUBLENT").
dico("D", 8, "DOUBLERA").
dico("D", 8, "DOUBLERS").
dico("D", 8, "DOUBLETS").
dico("D", 8, "DOUBLEUR").
dico("D", 8, "DOUBLIER").
dico("D", 8, "DOUBLIEZ").
dico("D", 8, "DOUBLONS").
dico("D", 8, "DOUBLURE").
dico("D", 8, "DOUCAINS").
dico("D", 8, "DOUCETTE").
dico("D", 8, "DOUCEURS").
dico("D", 8, "DOUCHAIS").
dico("D", 8, "DOUCHAIT").
dico("D", 8, "DOUCHANT").
dico("D", 8, "DOUCHEES").
dico("D", 8, "DOUCHENT").
dico("D", 8, "DOUCHERA").
dico("D", 8, "DOUCHEUR").
dico("D", 8, "DOUCHIEZ").
dico("D", 8, "DOUCHONS").
dico("D", 8, "DOUCIMES").
dico("D", 8, "DOUCINES").
dico("D", 8, "DOUCIRAI").
dico("D", 8, "DOUCIRAS").
dico("D", 8, "DOUCIREZ").
dico("D", 8, "DOUCISSE").
dico("D", 8, "DOUCITES").
dico("D", 8, "DOUDOUNE").
dico("D", 8, "DOUELLES").
dico("D", 8, "DOUERAIS").
dico("D", 8, "DOUERAIT").
dico("D", 8, "DOUERENT").
dico("D", 8, "DOUERIEZ").
dico("D", 8, "DOUERONS").
dico("D", 8, "DOUERONT").
dico("D", 8, "DOUILLAI").
dico("D", 8, "DOUILLAS").
dico("D", 8, "DOUILLAT").
dico("D", 8, "DOUILLEE").
dico("D", 8, "DOUILLER").
dico("D", 8, "DOUILLES").
dico("D", 8, "DOUILLET").
dico("D", 8, "DOUILLEZ").
dico("D", 8, "DOULEURS").
dico("D", 8, "DOUPIONS").
dico("D", 8, "DOURINES").
dico("D", 8, "DOUSSIES").
dico("D", 8, "DOUTAMES").
dico("D", 8, "DOUTASSE").
dico("D", 8, "DOUTATES").
dico("D", 8, "DOUTERAI").
dico("D", 8, "DOUTERAS").
dico("D", 8, "DOUTEREZ").
dico("D", 8, "DOUTEURS").
dico("D", 8, "DOUTEUSE").
dico("D", 8, "DOUTIONS").
dico("D", 8, "DOUVAINS").
dico("D", 8, "DOUVELLE").
dico("D", 8, "DOUZAINE").
dico("D", 8, "DOUZAINS").
dico("D", 8, "DOUZIEME").
dico("D", 8, "DOYENNES").
dico("D", 8, "DRACAENA").
dico("D", 8, "DRACENAS").
dico("D", 8, "DRACHAIT").
dico("D", 8, "DRACHERA").
dico("D", 8, "DRACHMES").
dico("D", 8, "DRAGAGES").
dico("D", 8, "DRAGEOIR").
dico("D", 8, "DRAGEONS").
dico("D", 8, "DRAGLINE").
dico("D", 8, "DRAGONNE").
dico("D", 8, "DRAGSTER").
dico("D", 8, "DRAGUAIS").
dico("D", 8, "DRAGUAIT").
dico("D", 8, "DRAGUANT").
dico("D", 8, "DRAGUEES").
dico("D", 8, "DRAGUENT").
dico("D", 8, "DRAGUERA").
dico("D", 8, "DRAGUEUR").
dico("D", 8, "DRAGUIEZ").
dico("D", 8, "DRAGUONS").
dico("D", 8, "DRAIERAI").
dico("D", 8, "DRAIERAS").
dico("D", 8, "DRAIEREZ").
dico("D", 8, "DRAILLES").
dico("D", 8, "DRAINAGE").
dico("D", 8, "DRAINAIS").
dico("D", 8, "DRAINAIT").
dico("D", 8, "DRAINANT").
dico("D", 8, "DRAINEES").
dico("D", 8, "DRAINENT").
dico("D", 8, "DRAINERA").
dico("D", 8, "DRAINEUR").
dico("D", 8, "DRAINIEZ").
dico("D", 8, "DRAINONS").
dico("D", 8, "DRAISINE").
dico("D", 8, "DRAKKARS").
dico("D", 8, "DRAPAMES").
dico("D", 8, "DRAPASSE").
dico("D", 8, "DRAPATES").
dico("D", 8, "DRAPEAUX").
dico("D", 8, "DRAPERAI").
dico("D", 8, "DRAPERAS").
dico("D", 8, "DRAPEREZ").
dico("D", 8, "DRAPERIE").
dico("D", 8, "DRAPIERE").
dico("D", 8, "DRAPIERS").
dico("D", 8, "DRAPIONS").
dico("D", 8, "DRAVAMES").
dico("D", 8, "DRAVASSE").
dico("D", 8, "DRAVATES").
dico("D", 8, "DRAVERAI").
dico("D", 8, "DRAVERAS").
dico("D", 8, "DRAVEREZ").
dico("D", 8, "DRAVEURS").
dico("D", 8, "DRAVEUSE").
dico("D", 8, "DRAVIONS").
dico("D", 8, "DRAWBACK").
dico("D", 8, "DRAYAGES").
dico("D", 8, "DRAYAMES").
dico("D", 8, "DRAYASSE").
dico("D", 8, "DRAYATES").
dico("D", 8, "DRAYERAI").
dico("D", 8, "DRAYERAS").
dico("D", 8, "DRAYEREZ").
dico("D", 8, "DRAYIONS").
dico("D", 8, "DRAYOIRE").
dico("D", 8, "DRAYOIRS").
dico("D", 8, "DRESSAGE").
dico("D", 8, "DRESSAIS").
dico("D", 8, "DRESSAIT").
dico("D", 8, "DRESSANT").
dico("D", 8, "DRESSEES").
dico("D", 8, "DRESSENT").
dico("D", 8, "DRESSERA").
dico("D", 8, "DRESSEUR").
dico("D", 8, "DRESSIEZ").
dico("D", 8, "DRESSING").
dico("D", 8, "DRESSOIR").
dico("D", 8, "DRESSONS").
dico("D", 8, "DRIBBLAI").
dico("D", 8, "DRIBBLAS").
dico("D", 8, "DRIBBLAT").
dico("D", 8, "DRIBBLEE").
dico("D", 8, "DRIBBLER").
dico("D", 8, "DRIBBLES").
dico("D", 8, "DRIBBLEZ").
dico("D", 8, "DRIFTERS").
dico("D", 8, "DRILLAIS").
dico("D", 8, "DRILLAIT").
dico("D", 8, "DRILLANT").
dico("D", 8, "DRILLEES").
dico("D", 8, "DRILLENT").
dico("D", 8, "DRILLERA").
dico("D", 8, "DRILLIEZ").
dico("D", 8, "DRILLONS").
dico("D", 8, "DRIVAMES").
dico("D", 8, "DRIVASSE").
dico("D", 8, "DRIVATES").
dico("D", 8, "DRIVERAI").
dico("D", 8, "DRIVERAS").
dico("D", 8, "DRIVEREZ").
dico("D", 8, "DRIVEURS").
dico("D", 8, "DRIVIONS").
dico("D", 8, "DROGMANS").
dico("D", 8, "DROGUAIS").
dico("D", 8, "DROGUAIT").
dico("D", 8, "DROGUANT").
dico("D", 8, "DROGUEES").
dico("D", 8, "DROGUENT").
dico("D", 8, "DROGUERA").
dico("D", 8, "DROGUETS").
dico("D", 8, "DROGUIEZ").
dico("D", 8, "DROGUONS").
dico("D", 8, "DROITIER").
dico("D", 8, "DROITURE").
dico("D", 8, "DROLERIE").
dico("D", 8, "DROLESSE").
dico("D", 8, "DROLETTE").
dico("D", 8, "DROMOISE").
dico("D", 8, "DROPAMES").
dico("D", 8, "DROPASSE").
dico("D", 8, "DROPATES").
dico("D", 8, "DROPERAI").
dico("D", 8, "DROPERAS").
dico("D", 8, "DROPEREZ").
dico("D", 8, "DROPIONS").
dico("D", 8, "DROPPAGE").
dico("D", 8, "DROPPAIS").
dico("D", 8, "DROPPAIT").
dico("D", 8, "DROPPANT").
dico("D", 8, "DROPPEES").
dico("D", 8, "DROPPENT").
dico("D", 8, "DROPPERA").
dico("D", 8, "DROPPIEZ").
dico("D", 8, "DROPPONS").
dico("D", 8, "DROSERAS").
dico("D", 8, "DROSSAIS").
dico("D", 8, "DROSSAIT").
dico("D", 8, "DROSSANT").
dico("D", 8, "DROSSEES").
dico("D", 8, "DROSSENT").
dico("D", 8, "DROSSERA").
dico("D", 8, "DROSSIEZ").
dico("D", 8, "DROSSONS").
dico("D", 8, "DROUAISE").
dico("D", 8, "DRUMLINS").
dico("D", 8, "DRUMMERS").
dico("D", 8, "DRUPACEE").
dico("D", 8, "DRUPACES").
dico("D", 8, "DRUPEOLE").
dico("D", 8, "DUALISAI").
dico("D", 8, "DUALISAS").
dico("D", 8, "DUALISAT").
dico("D", 8, "DUALISEE").
dico("D", 8, "DUALISER").
dico("D", 8, "DUALISES").
dico("D", 8, "DUALISEZ").
dico("D", 8, "DUALISME").
dico("D", 8, "DUALISTE").
dico("D", 8, "DUALITES").
dico("D", 8, "DUBNIUMS").
dico("D", 8, "DUCASSES").
dico("D", 8, "DUCATONS").
dico("D", 8, "DUCHESSE").
dico("D", 8, "DUCROIRE").
dico("D", 8, "DUCTILES").
dico("D", 8, "DUDGEONS").
dico("D", 8, "DUGAZONS").
dico("D", 8, "DUITAGES").
dico("D", 8, "DUITAMES").
dico("D", 8, "DUITASSE").
dico("D", 8, "DUITATES").
dico("D", 8, "DUITERAI").
dico("D", 8, "DUITERAS").
dico("D", 8, "DUITEREZ").
dico("D", 8, "DUITIONS").
dico("D", 8, "DULCIFIA").
dico("D", 8, "DULCIFIE").
dico("D", 8, "DULCINEE").
dico("D", 8, "DULCITES").
dico("D", 8, "DULCITOL").
dico("D", 8, "DUMPINGS").
dico("D", 8, "DUNETTES").
dico("D", 8, "DUODENAL").
dico("D", 8, "DUODENUM").
dico("D", 8, "DUOPOLES").
dico("D", 8, "DUPAIENT").
dico("D", 8, "DUPASSES").
dico("D", 8, "DUPERAIS").
dico("D", 8, "DUPERAIT").
dico("D", 8, "DUPERENT").
dico("D", 8, "DUPERIES").
dico("D", 8, "DUPERIEZ").
dico("D", 8, "DUPERONS").
dico("D", 8, "DUPERONT").
dico("D", 8, "DUPEUSES").
dico("D", 8, "DUPLEXAI").
dico("D", 8, "DUPLEXAS").
dico("D", 8, "DUPLEXAT").
dico("D", 8, "DUPLEXEE").
dico("D", 8, "DUPLEXER").
dico("D", 8, "DUPLEXES").
dico("D", 8, "DUPLEXEZ").
dico("D", 8, "DUPLIQUA").
dico("D", 8, "DUPLIQUE").
dico("D", 8, "DUQUAMES").
dico("D", 8, "DUQUASSE").
dico("D", 8, "DUQUATES").
dico("D", 8, "DUQUERAI").
dico("D", 8, "DUQUERAS").
dico("D", 8, "DUQUEREZ").
dico("D", 8, "DUQUIONS").
dico("D", 8, "DURABLES").
dico("D", 8, "DURAIENT").
dico("D", 8, "DURAILLE").
dico("D", 8, "DURAMENS").
dico("D", 8, "DURASSES").
dico("D", 8, "DURATIFS").
dico("D", 8, "DURATIVE").
dico("D", 8, "DURCIMES").
dico("D", 8, "DURCIRAI").
dico("D", 8, "DURCIRAS").
dico("D", 8, "DURCIREZ").
dico("D", 8, "DURCISSE").
dico("D", 8, "DURCITES").
dico("D", 8, "DUREMENT").
dico("D", 8, "DURERAIS").
dico("D", 8, "DURERAIT").
dico("D", 8, "DURERENT").
dico("D", 8, "DURERIEZ").
dico("D", 8, "DURERONS").
dico("D", 8, "DURERONT").
dico("D", 8, "DURILLON").
dico("D", 8, "DUSSIONS").
dico("D", 8, "DUUMVIRS").
dico("D", 8, "DUVETAIS").
dico("D", 8, "DUVETAIT").
dico("D", 8, "DUVETANT").
dico("D", 8, "DUVETEES").
dico("D", 8, "DUVETENT").
dico("D", 8, "DUVETERA").
dico("D", 8, "DUVETEUX").
dico("D", 8, "DUVETIEZ").
dico("D", 8, "DUVETONS").
dico("D", 8, "DUVETTES").
dico("D", 8, "DUXELLES").
dico("D", 8, "DYADIQUE").
dico("D", 8, "DYARCHIE").
dico("D", 8, "DYARQUES").
dico("D", 8, "DYNAMISA").
dico("D", 8, "DYNAMISE").
dico("D", 8, "DYNAMITA").
dico("D", 8, "DYNAMITE").
dico("D", 8, "DYNASTES").
dico("D", 8, "DYNASTIE").
dico("D", 8, "DYSBASIE").
dico("D", 8, "DYSLALIE").
dico("D", 8, "DYSLEXIE").
dico("D", 8, "DYSLOGIE").
dico("D", 8, "DYSMELIE").
dico("D", 8, "DYSOSMIE").
dico("D", 8, "DYSPNEES").
dico("D", 8, "DYSTASIE").
dico("D", 8, "DYSTOCIE").
dico("D", 8, "DYSTOMIE").
dico("D", 8, "DYSTONIE").
dico("D", 8, "DYSURIES").
dico("D", 8, "DYTIQUES").
