dico("E", 5, "EAGLE").
dico("E", 5, "EBAHI").
dico("E", 5, "EBATS").
dico("E", 5, "EBENE").
dico("E", 5, "EBOUA").
dico("E", 5, "EBOUE").
dico("E", 5, "ECALA").
dico("E", 5, "ECALE").
dico("E", 5, "ECANG").
dico("E", 5, "ECART").
dico("E", 5, "ECHAI").
dico("E", 5, "ECHAS").
dico("E", 5, "ECHAT").
dico("E", 5, "ECHEC").
dico("E", 5, "ECHEE").
dico("E", 5, "ECHER").
dico("E", 5, "ECHES").
dico("E", 5, "ECHET").
dico("E", 5, "ECHEZ").
dico("E", 5, "ECHOS").
dico("E", 5, "ECHUE").
dico("E", 5, "ECHUS").
dico("E", 5, "ECHUT").
dico("E", 5, "ECIMA").
dico("E", 5, "ECIME").
dico("E", 5, "ECLAT").
dico("E", 5, "ECLOS").
dico("E", 5, "ECLOT").
dico("E", 5, "ECOIN").
dico("E", 5, "ECOLE").
dico("E", 5, "ECOLO").
dico("E", 5, "ECOPA").
dico("E", 5, "ECOPE").
dico("E", 5, "ECOTA").
dico("E", 5, "ECOTE").
dico("E", 5, "ECOTS").
dico("E", 5, "ECRAN").
dico("E", 5, "ECRIA").
dico("E", 5, "ECRIE").
dico("E", 5, "ECRIN").
dico("E", 5, "ECRIS").
dico("E", 5, "ECRIT").
dico("E", 5, "ECROU").
dico("E", 5, "ECRUE").
dico("E", 5, "ECRUS").
dico("E", 5, "ECULA").
dico("E", 5, "ECULE").
dico("E", 5, "ECUMA").
dico("E", 5, "ECUME").
dico("E", 5, "ECURA").
dico("E", 5, "ECURE").
dico("E", 5, "EDAMS").
dico("E", 5, "EDENS").
dico("E", 5, "EDILE").
dico("E", 5, "EDITA").
dico("E", 5, "EDITE").
dico("E", 5, "EDITO").
dico("E", 5, "EDITS").
dico("E", 5, "EFFET").
dico("E", 5, "EFRIT").
dico("E", 5, "EGAIE").
dico("E", 5, "EGALA").
dico("E", 5, "EGALE").
dico("E", 5, "EGARA").
dico("E", 5, "EGARD").
dico("E", 5, "EGARE").
dico("E", 5, "EGAUX").
dico("E", 5, "EGAYA").
dico("E", 5, "EGAYE").
dico("E", 5, "EGEEN").
dico("E", 5, "EGIDE").
dico("E", 5, "EGOUT").
dico("E", 5, "EIDER").
dico("E", 5, "EJECT").
dico("E", 5, "EJETS").
dico("E", 5, "ELAND").
dico("E", 5, "ELANS").
dico("E", 5, "ELAVE").
dico("E", 5, "ELBOT").
dico("E", 5, "ELEGI").
dico("E", 5, "ELEIS").
dico("E", 5, "ELEMI").
dico("E", 5, "ELEVA").
dico("E", 5, "ELEVE").
dico("E", 5, "ELFES").
dico("E", 5, "ELIAI").
dico("E", 5, "ELIAS").
dico("E", 5, "ELIAT").
dico("E", 5, "ELIDA").
dico("E", 5, "ELIDE").
dico("E", 5, "ELIEE").
dico("E", 5, "ELIER").
dico("E", 5, "ELIES").
dico("E", 5, "ELIEZ").
dico("E", 5, "ELIMA").
dico("E", 5, "ELIME").
dico("E", 5, "ELIRA").
dico("E", 5, "ELIRE").
dico("E", 5, "ELISE").
dico("E", 5, "ELITE").
dico("E", 5, "ELLES").
dico("E", 5, "ELOGE").
dico("E", 5, "ELOXE").
dico("E", 5, "ELUAI").
dico("E", 5, "ELUAS").
dico("E", 5, "ELUAT").
dico("E", 5, "ELUDA").
dico("E", 5, "ELUDE").
dico("E", 5, "ELUEE").
dico("E", 5, "ELUER").
dico("E", 5, "ELUES").
dico("E", 5, "ELUEZ").
dico("E", 5, "ELYME").
dico("E", 5, "EMAIL").
dico("E", 5, "EMANA").
dico("E", 5, "EMANE").
dico("E", 5, "EMAUX").
dico("E", 5, "EMBAT").
dico("E", 5, "EMBUA").
dico("E", 5, "EMBUE").
dico("E", 5, "EMBUS").
dico("E", 5, "EMBUT").
dico("E", 5, "EMERI").
dico("E", 5, "EMETS").
dico("E", 5, "EMEUS").
dico("E", 5, "EMEUT").
dico("E", 5, "EMIAI").
dico("E", 5, "EMIAS").
dico("E", 5, "EMIAT").
dico("E", 5, "EMIEE").
dico("E", 5, "EMIER").
dico("E", 5, "EMIES").
dico("E", 5, "EMIEZ").
dico("E", 5, "EMIRS").
dico("E", 5, "EMISE").
dico("E", 5, "EMOIS").
dico("E", 5, "EMOUD").
dico("E", 5, "EMOUS").
dico("E", 5, "EMPAN").
dico("E", 5, "EMPLI").
dico("E", 5, "EMUES").
dico("E", 5, "EMULA").
dico("E", 5, "EMULE").
dico("E", 5, "ENCAN").
dico("E", 5, "ENCAS").
dico("E", 5, "ENCOR").
dico("E", 5, "ENCRA").
dico("E", 5, "ENCRE").
dico("E", 5, "ENDOS").
dico("E", 5, "ENEMA").
dico("E", 5, "ENFER").
dico("E", 5, "ENFEU").
dico("E", 5, "ENFIN").
dico("E", 5, "ENFLA").
dico("E", 5, "ENFLE").
dico("E", 5, "ENFUI").
dico("E", 5, "ENGIN").
dico("E", 5, "ENJEU").
dico("E", 5, "ENLIA").
dico("E", 5, "ENLIE").
dico("E", 5, "ENNUI").
dico("E", 5, "ENOLS").
dico("E", 5, "ENOUA").
dico("E", 5, "ENOUE").
dico("E", 5, "ENTAI").
dico("E", 5, "ENTAS").
dico("E", 5, "ENTAT").
dico("E", 5, "ENTEE").
dico("E", 5, "ENTER").
dico("E", 5, "ENTES").
dico("E", 5, "ENTEZ").
dico("E", 5, "ENTRA").
dico("E", 5, "ENTRE").
dico("E", 5, "ENVIA").
dico("E", 5, "ENVIE").
dico("E", 5, "ENVOI").
dico("E", 5, "ENVOL").
dico("E", 5, "EPAIR").
dico("E", 5, "EPAIS").
dico("E", 5, "EPAND").
dico("E", 5, "EPARS").
dico("E", 5, "EPART").
dico("E", 5, "EPATA").
dico("E", 5, "EPATE").
dico("E", 5, "EPAVE").
dico("E", 5, "EPEES").
dico("E", 5, "EPELA").
dico("E", 5, "EPELE").
dico("E", 5, "EPHOD").
dico("E", 5, "EPIAI").
dico("E", 5, "EPIAS").
dico("E", 5, "EPIAT").
dico("E", 5, "EPICA").
dico("E", 5, "EPICE").
dico("E", 5, "EPIEE").
dico("E", 5, "EPIER").
dico("E", 5, "EPIES").
dico("E", 5, "EPIEU").
dico("E", 5, "EPIEZ").
dico("E", 5, "EPIGE").
dico("E", 5, "EPILA").
dico("E", 5, "EPILE").
dico("E", 5, "EPINA").
dico("E", 5, "EPINE").
dico("E", 5, "EPITE").
dico("E", 5, "EPODE").
dico("E", 5, "EPOIS").
dico("E", 5, "EPOUX").
dico("E", 5, "EPOXY").
dico("E", 5, "EPRIS").
dico("E", 5, "EPRIT").
dico("E", 5, "EPROM").
dico("E", 5, "EPUCA").
dico("E", 5, "EPUCE").
dico("E", 5, "EPURA").
dico("E", 5, "EPURE").
dico("E", 5, "EQUIN").
dico("E", 5, "ERBUE").
dico("E", 5, "ERGOL").
dico("E", 5, "ERGOT").
dico("E", 5, "ERIGE").
dico("E", 5, "ERINE").
dico("E", 5, "ERODA").
dico("E", 5, "ERODE").
dico("E", 5, "ERRAI").
dico("E", 5, "ERRAS").
dico("E", 5, "ERRAT").
dico("E", 5, "ERRER").
dico("E", 5, "ERRES").
dico("E", 5, "ERREZ").
dico("E", 5, "ERSES").
dico("E", 5, "ESCHA").
dico("E", 5, "ESCHE").
dico("E", 5, "ESCOT").
dico("E", 5, "ESPAR").
dico("E", 5, "ESSAI").
dico("E", 5, "ESSES").
dico("E", 5, "ESSOR").
dico("E", 5, "ESTER").
dico("E", 5, "ESTES").
dico("E", 5, "ESTOC").
dico("E", 5, "ETAGE").
dico("E", 5, "ETAIE").
dico("E", 5, "ETAIN").
dico("E", 5, "ETAIS").
dico("E", 5, "ETAIT").
dico("E", 5, "ETALA").
dico("E", 5, "ETALE").
dico("E", 5, "ETALS").
dico("E", 5, "ETAMA").
dico("E", 5, "ETAME").
dico("E", 5, "ETANG").
dico("E", 5, "ETANT").
dico("E", 5, "ETAPE").
dico("E", 5, "ETATS").
dico("E", 5, "ETAUX").
dico("E", 5, "ETAYA").
dico("E", 5, "ETAYE").
dico("E", 5, "ETEND").
dico("E", 5, "ETETA").
dico("E", 5, "ETETE").
dico("E", 5, "ETEUF").
dico("E", 5, "ETHER").
dico("E", 5, "ETHOS").
dico("E", 5, "ETIER").
dico("E", 5, "ETIEZ").
dico("E", 5, "ETIGE").
dico("E", 5, "ETIRA").
dico("E", 5, "ETIRE").
dico("E", 5, "ETOCS").
dico("E", 5, "ETOLE").
dico("E", 5, "ETRES").
dico("E", 5, "ETRON").
dico("E", 5, "ETUDE").
dico("E", 5, "ETUIS").
dico("E", 5, "ETUVA").
dico("E", 5, "ETUVE").
dico("E", 5, "EUMES").
dico("E", 5, "EUROS").
dico("E", 5, "EUSSE").
dico("E", 5, "EUTES").
dico("E", 5, "EVADA").
dico("E", 5, "EVADE").
dico("E", 5, "EVASA").
dico("E", 5, "EVASE").
dico("E", 5, "EVEIL").
dico("E", 5, "EVENT").
dico("E", 5, "EVIDA").
dico("E", 5, "EVIDE").
dico("E", 5, "EVIER").
dico("E", 5, "EVITA").
dico("E", 5, "EVITE").
dico("E", 5, "EVOHE").
dico("E", 5, "EXACT").
dico("E", 5, "EXAMS").
dico("E", 5, "EXCES").
dico("E", 5, "EXCLU").
dico("E", 5, "EXEAT").
dico("E", 5, "EXIGE").
dico("E", 5, "EXIGU").
dico("E", 5, "EXILA").
dico("E", 5, "EXILE").
dico("E", 5, "EXILS").
dico("E", 5, "EXODE").
dico("E", 5, "EXONS").
dico("E", 5, "EXPIA").
dico("E", 5, "EXPIE").
dico("E", 5, "EXPOS").
dico("E", 5, "EXTRA").
dico("E", 5, "EYRAS").
