dico("E", 6, "EAGLES").
dico("E", 6, "EBAHIE").
dico("E", 6, "EBAHIR").
dico("E", 6, "EBAHIS").
dico("E", 6, "EBAHIT").
dico("E", 6, "EBARBA").
dico("E", 6, "EBARBE").
dico("E", 6, "EBATTE").
dico("E", 6, "EBATTU").
dico("E", 6, "EBAUBI").
dico("E", 6, "EBAUDI").
dico("E", 6, "EBENES").
dico("E", 6, "EBLOUI").
dico("E", 6, "EBOUAI").
dico("E", 6, "EBOUAS").
dico("E", 6, "EBOUAT").
dico("E", 6, "EBOUEE").
dico("E", 6, "EBOUER").
dico("E", 6, "EBOUES").
dico("E", 6, "EBOUEZ").
dico("E", 6, "EBOULA").
dico("E", 6, "EBOULE").
dico("E", 6, "EBOUTA").
dico("E", 6, "EBOUTE").
dico("E", 6, "EBRASA").
dico("E", 6, "EBRASE").
dico("E", 6, "EBROUA").
dico("E", 6, "EBROUE").
dico("E", 6, "EBURNE").
dico("E", 6, "ECACHA").
dico("E", 6, "ECACHE").
dico("E", 6, "ECALAI").
dico("E", 6, "ECALAS").
dico("E", 6, "ECALAT").
dico("E", 6, "ECALEE").
dico("E", 6, "ECALER").
dico("E", 6, "ECALES").
dico("E", 6, "ECALEZ").
dico("E", 6, "ECANGS").
dico("E", 6, "ECARTA").
dico("E", 6, "ECARTE").
dico("E", 6, "ECARTS").
dico("E", 6, "ECHAIS").
dico("E", 6, "ECHAIT").
dico("E", 6, "ECHANT").
dico("E", 6, "ECHARS").
dico("E", 6, "ECHECS").
dico("E", 6, "ECHEES").
dico("E", 6, "ECHENT").
dico("E", 6, "ECHERA").
dico("E", 6, "ECHIEZ").
dico("E", 6, "ECHINA").
dico("E", 6, "ECHINE").
dico("E", 6, "ECHOIE").
dico("E", 6, "ECHOIR").
dico("E", 6, "ECHOIT").
dico("E", 6, "ECHONS").
dico("E", 6, "ECHOUA").
dico("E", 6, "ECHOUE").
dico("E", 6, "ECHUES").
dico("E", 6, "ECIDIE").
dico("E", 6, "ECIMAI").
dico("E", 6, "ECIMAS").
dico("E", 6, "ECIMAT").
dico("E", 6, "ECIMEE").
dico("E", 6, "ECIMER").
dico("E", 6, "ECIMES").
dico("E", 6, "ECIMEZ").
dico("E", 6, "ECLAFA").
dico("E", 6, "ECLAFE").
dico("E", 6, "ECLAIR").
dico("E", 6, "ECLATA").
dico("E", 6, "ECLATE").
dico("E", 6, "ECLATS").
dico("E", 6, "ECLOPE").
dico("E", 6, "ECLORA").
dico("E", 6, "ECLORE").
dico("E", 6, "ECLOSE").
dico("E", 6, "ECLUSA").
dico("E", 6, "ECLUSE").
dico("E", 6, "ECOBUA").
dico("E", 6, "ECOBUE").
dico("E", 6, "ECOINS").
dico("E", 6, "ECOLES").
dico("E", 6, "ECOLOS").
dico("E", 6, "ECOPAI").
dico("E", 6, "ECOPAS").
dico("E", 6, "ECOPAT").
dico("E", 6, "ECOPEE").
dico("E", 6, "ECOPER").
dico("E", 6, "ECOPES").
dico("E", 6, "ECOPEZ").
dico("E", 6, "ECORCA").
dico("E", 6, "ECORCE").
dico("E", 6, "ECORNA").
dico("E", 6, "ECORNE").
dico("E", 6, "ECOSSA").
dico("E", 6, "ECOSSE").
dico("E", 6, "ECOTAI").
dico("E", 6, "ECOTAS").
dico("E", 6, "ECOTAT").
dico("E", 6, "ECOTEE").
dico("E", 6, "ECOTER").
dico("E", 6, "ECOTES").
dico("E", 6, "ECOTEZ").
dico("E", 6, "ECOULA").
dico("E", 6, "ECOULE").
dico("E", 6, "ECOUTA").
dico("E", 6, "ECOUTE").
dico("E", 6, "ECRANS").
dico("E", 6, "ECRASA").
dico("E", 6, "ECRASE").
dico("E", 6, "ECREMA").
dico("E", 6, "ECREME").
dico("E", 6, "ECRETA").
dico("E", 6, "ECRETE").
dico("E", 6, "ECRIAI").
dico("E", 6, "ECRIAS").
dico("E", 6, "ECRIAT").
dico("E", 6, "ECRIEE").
dico("E", 6, "ECRIER").
dico("E", 6, "ECRIES").
dico("E", 6, "ECRIEZ").
dico("E", 6, "ECRINS").
dico("E", 6, "ECRIRA").
dico("E", 6, "ECRIRE").
dico("E", 6, "ECRITE").
dico("E", 6, "ECRITS").
dico("E", 6, "ECRIVE").
dico("E", 6, "ECROUA").
dico("E", 6, "ECROUE").
dico("E", 6, "ECROUI").
dico("E", 6, "ECROUS").
dico("E", 6, "ECRUES").
dico("E", 6, "ECTASE").
dico("E", 6, "ECTYPE").
dico("E", 6, "ECUEIL").
dico("E", 6, "ECULAI").
dico("E", 6, "ECULAS").
dico("E", 6, "ECULAT").
dico("E", 6, "ECULEE").
dico("E", 6, "ECULER").
dico("E", 6, "ECULES").
dico("E", 6, "ECULEZ").
dico("E", 6, "ECUMAI").
dico("E", 6, "ECUMAS").
dico("E", 6, "ECUMAT").
dico("E", 6, "ECUMEE").
dico("E", 6, "ECUMER").
dico("E", 6, "ECUMES").
dico("E", 6, "ECUMEZ").
dico("E", 6, "ECURAI").
dico("E", 6, "ECURAS").
dico("E", 6, "ECURAT").
dico("E", 6, "ECUREE").
dico("E", 6, "ECURER").
dico("E", 6, "ECURES").
dico("E", 6, "ECUREZ").
dico("E", 6, "ECURIE").
dico("E", 6, "ECUYER").
dico("E", 6, "ECZEMA").
dico("E", 6, "EDENTA").
dico("E", 6, "EDENTE").
dico("E", 6, "EDICTA").
dico("E", 6, "EDICTE").
dico("E", 6, "EDIFIA").
dico("E", 6, "EDIFIE").
dico("E", 6, "EDILES").
dico("E", 6, "EDITAI").
dico("E", 6, "EDITAS").
dico("E", 6, "EDITAT").
dico("E", 6, "EDITEE").
dico("E", 6, "EDITER").
dico("E", 6, "EDITES").
dico("E", 6, "EDITEZ").
dico("E", 6, "EDITOS").
dico("E", 6, "EDUQUA").
dico("E", 6, "EDUQUE").
dico("E", 6, "EFENDI").
dico("E", 6, "EFFACA").
dico("E", 6, "EFFACE").
dico("E", 6, "EFFANA").
dico("E", 6, "EFFANE").
dico("E", 6, "EFFARA").
dico("E", 6, "EFFARE").
dico("E", 6, "EFFETS").
dico("E", 6, "EFFILA").
dico("E", 6, "EFFILE").
dico("E", 6, "EFFORT").
dico("E", 6, "EFFROI").
dico("E", 6, "EFRITS").
dico("E", 6, "EGAIES").
dico("E", 6, "EGALAI").
dico("E", 6, "EGALAS").
dico("E", 6, "EGALAT").
dico("E", 6, "EGALEE").
dico("E", 6, "EGALER").
dico("E", 6, "EGALES").
dico("E", 6, "EGALEZ").
dico("E", 6, "EGARAI").
dico("E", 6, "EGARAS").
dico("E", 6, "EGARAT").
dico("E", 6, "EGARDS").
dico("E", 6, "EGAREE").
dico("E", 6, "EGARER").
dico("E", 6, "EGARES").
dico("E", 6, "EGAREZ").
dico("E", 6, "EGAYAI").
dico("E", 6, "EGAYAS").
dico("E", 6, "EGAYAT").
dico("E", 6, "EGAYEE").
dico("E", 6, "EGAYER").
dico("E", 6, "EGAYES").
dico("E", 6, "EGAYEZ").
dico("E", 6, "EGEENS").
dico("E", 6, "EGERIE").
dico("E", 6, "EGERMA").
dico("E", 6, "EGERME").
dico("E", 6, "EGIDES").
dico("E", 6, "EGLISE").
dico("E", 6, "EGOINE").
dico("E", 6, "EGORGE").
dico("E", 6, "EGOUTS").
dico("E", 6, "EGRENA").
dico("E", 6, "EGRENE").
dico("E", 6, "EGRISA").
dico("E", 6, "EGRISE").
dico("E", 6, "EGRUGE").
dico("E", 6, "EHONTE").
dico("E", 6, "EIDERS").
dico("E", 6, "EJECTA").
dico("E", 6, "EJECTE").
dico("E", 6, "EJECTS").
dico("E", 6, "ELAEIS").
dico("E", 6, "ELAGUA").
dico("E", 6, "ELAGUE").
dico("E", 6, "ELANCA").
dico("E", 6, "ELANCE").
dico("E", 6, "ELANDS").
dico("E", 6, "ELAPHE").
dico("E", 6, "ELARGI").
dico("E", 6, "ELATIF").
dico("E", 6, "ELAVEE").
dico("E", 6, "ELAVES").
dico("E", 6, "ELBEUF").
dico("E", 6, "ELBOTS").
dico("E", 6, "ELEATE").
dico("E", 6, "ELEGIE").
dico("E", 6, "ELEGIR").
dico("E", 6, "ELEGIS").
dico("E", 6, "ELEGIT").
dico("E", 6, "ELEMIS").
dico("E", 6, "ELEVAI").
dico("E", 6, "ELEVAS").
dico("E", 6, "ELEVAT").
dico("E", 6, "ELEVEE").
dico("E", 6, "ELEVER").
dico("E", 6, "ELEVES").
dico("E", 6, "ELEVEZ").
dico("E", 6, "ELEVON").
dico("E", 6, "ELIAIS").
dico("E", 6, "ELIAIT").
dico("E", 6, "ELIANT").
dico("E", 6, "ELIDAI").
dico("E", 6, "ELIDAS").
dico("E", 6, "ELIDAT").
dico("E", 6, "ELIDEE").
dico("E", 6, "ELIDER").
dico("E", 6, "ELIDES").
dico("E", 6, "ELIDEZ").
dico("E", 6, "ELIEES").
dico("E", 6, "ELIENT").
dico("E", 6, "ELIERA").
dico("E", 6, "ELIIEZ").
dico("E", 6, "ELIMAI").
dico("E", 6, "ELIMAS").
dico("E", 6, "ELIMAT").
dico("E", 6, "ELIMEE").
dico("E", 6, "ELIMER").
dico("E", 6, "ELIMES").
dico("E", 6, "ELIMEZ").
dico("E", 6, "ELINDE").
dico("E", 6, "ELIONS").
dico("E", 6, "ELIRAI").
dico("E", 6, "ELIRAS").
dico("E", 6, "ELIREZ").
dico("E", 6, "ELISES").
dico("E", 6, "ELISEZ").
dico("E", 6, "ELITES").
dico("E", 6, "ELIXIR").
dico("E", 6, "ELODEE").
dico("E", 6, "ELOGES").
dico("E", 6, "ELONGE").
dico("E", 6, "ELOXEE").
dico("E", 6, "ELOXES").
dico("E", 6, "ELUAIS").
dico("E", 6, "ELUAIT").
dico("E", 6, "ELUANT").
dico("E", 6, "ELUDAI").
dico("E", 6, "ELUDAS").
dico("E", 6, "ELUDAT").
dico("E", 6, "ELUDEE").
dico("E", 6, "ELUDER").
dico("E", 6, "ELUDES").
dico("E", 6, "ELUDEZ").
dico("E", 6, "ELUEES").
dico("E", 6, "ELUENT").
dico("E", 6, "ELUERA").
dico("E", 6, "ELUIEZ").
dico("E", 6, "ELUMES").
dico("E", 6, "ELUONS").
dico("E", 6, "ELUSIF").
dico("E", 6, "ELUSSE").
dico("E", 6, "ELUTES").
dico("E", 6, "ELYMES").
dico("E", 6, "ELYTRE").
dico("E", 6, "EMACIA").
dico("E", 6, "EMACIE").
dico("E", 6, "EMAILS").
dico("E", 6, "EMANAI").
dico("E", 6, "EMANAS").
dico("E", 6, "EMANAT").
dico("E", 6, "EMANEE").
dico("E", 6, "EMANER").
dico("E", 6, "EMANES").
dico("E", 6, "EMANEZ").
dico("E", 6, "EMARGE").
dico("E", 6, "EMBASE").
dico("E", 6, "EMBATA").
dico("E", 6, "EMBATE").
dico("E", 6, "EMBATS").
dico("E", 6, "EMBATU").
dico("E", 6, "EMBETA").
dico("E", 6, "EMBETE").
dico("E", 6, "EMBLEE").
dico("E", 6, "EMBOIS").
dico("E", 6, "EMBOIT").
dico("E", 6, "EMBOLE").
dico("E", 6, "EMBOUA").
dico("E", 6, "EMBOUE").
dico("E", 6, "EMBOUT").
dico("E", 6, "EMBRUN").
dico("E", 6, "EMBUAI").
dico("E", 6, "EMBUAS").
dico("E", 6, "EMBUAT").
dico("E", 6, "EMBUEE").
dico("E", 6, "EMBUER").
dico("E", 6, "EMBUES").
dico("E", 6, "EMBUEZ").
dico("E", 6, "EMECHA").
dico("E", 6, "EMECHE").
dico("E", 6, "EMENDA").
dico("E", 6, "EMENDE").
dico("E", 6, "EMERGE").
dico("E", 6, "EMERIS").
dico("E", 6, "EMETTE").
dico("E", 6, "EMEUTE").
dico("E", 6, "EMEUVE").
dico("E", 6, "EMIAIS").
dico("E", 6, "EMIAIT").
dico("E", 6, "EMIANT").
dico("E", 6, "EMIEES").
dico("E", 6, "EMIENT").
dico("E", 6, "EMIERA").
dico("E", 6, "EMIGRA").
dico("E", 6, "EMIGRE").
dico("E", 6, "EMIIEZ").
dico("E", 6, "EMIMES").
dico("E", 6, "EMINCA").
dico("E", 6, "EMINCE").
dico("E", 6, "EMIONS").
dico("E", 6, "EMIRAT").
dico("E", 6, "EMISES").
dico("E", 6, "EMISSE").
dico("E", 6, "EMITES").
dico("E", 6, "EMMELA").
dico("E", 6, "EMMELE").
dico("E", 6, "EMMENA").
dico("E", 6, "EMMENE").
dico("E", 6, "EMMURA").
dico("E", 6, "EMMURE").
dico("E", 6, "EMONDA").
dico("E", 6, "EMONDE").
dico("E", 6, "EMOTIF").
dico("E", 6, "EMOTTA").
dico("E", 6, "EMOTTE").
dico("E", 6, "EMOUDS").
dico("E", 6, "EMOULE").
dico("E", 6, "EMOULU").
dico("E", 6, "EMPALA").
dico("E", 6, "EMPALE").
dico("E", 6, "EMPANS").
dico("E", 6, "EMPARA").
dico("E", 6, "EMPARE").
dico("E", 6, "EMPATA").
dico("E", 6, "EMPATE").
dico("E", 6, "EMPESA").
dico("E", 6, "EMPESE").
dico("E", 6, "EMPILA").
dico("E", 6, "EMPILE").
dico("E", 6, "EMPIRA").
dico("E", 6, "EMPIRE").
dico("E", 6, "EMPLIE").
dico("E", 6, "EMPLIR").
dico("E", 6, "EMPLIS").
dico("E", 6, "EMPLIT").
dico("E", 6, "EMPLOI").
dico("E", 6, "EMPOIS").
dico("E", 6, "EMPORT").
dico("E", 6, "EMPOTA").
dico("E", 6, "EMPOTE").
dico("E", 6, "EMPUSE").
dico("E", 6, "EMULAI").
dico("E", 6, "EMULAS").
dico("E", 6, "EMULAT").
dico("E", 6, "EMULEE").
dico("E", 6, "EMULER").
dico("E", 6, "EMULES").
dico("E", 6, "EMULEZ").
dico("E", 6, "EMUMES").
dico("E", 6, "EMUSSE").
dico("E", 6, "EMUTES").
dico("E", 6, "ENCAGE").
dico("E", 6, "ENCANS").
dico("E", 6, "ENCART").
dico("E", 6, "ENCAVA").
dico("E", 6, "ENCAVE").
dico("E", 6, "ENCENS").
dico("E", 6, "ENCLIN").
dico("E", 6, "ENCLOS").
dico("E", 6, "ENCLOT").
dico("E", 6, "ENCODA").
dico("E", 6, "ENCODE").
dico("E", 6, "ENCORE").
dico("E", 6, "ENCRAI").
dico("E", 6, "ENCRAS").
dico("E", 6, "ENCRAT").
dico("E", 6, "ENCREE").
dico("E", 6, "ENCRER").
dico("E", 6, "ENCRES").
dico("E", 6, "ENCREZ").
dico("E", 6, "ENCULA").
dico("E", 6, "ENCULE").
dico("E", 6, "ENCUVA").
dico("E", 6, "ENCUVE").
dico("E", 6, "ENDIVE").
dico("E", 6, "ENDOGE").
dico("E", 6, "ENDORS").
dico("E", 6, "ENDORT").
dico("E", 6, "ENDUIS").
dico("E", 6, "ENDUIT").
dico("E", 6, "ENDURA").
dico("E", 6, "ENDURE").
dico("E", 6, "ENDURO").
dico("E", 6, "ENEMAS").
dico("E", 6, "ENERVA").
dico("E", 6, "ENERVE").
dico("E", 6, "ENFANT").
dico("E", 6, "ENFERS").
dico("E", 6, "ENFEUS").
dico("E", 6, "ENFEUX").
dico("E", 6, "ENFILA").
dico("E", 6, "ENFILE").
dico("E", 6, "ENFLAI").
dico("E", 6, "ENFLAS").
dico("E", 6, "ENFLAT").
dico("E", 6, "ENFLEE").
dico("E", 6, "ENFLER").
dico("E", 6, "ENFLES").
dico("E", 6, "ENFLEZ").
dico("E", 6, "ENFOUI").
dico("E", 6, "ENFUIE").
dico("E", 6, "ENFUIR").
dico("E", 6, "ENFUIS").
dico("E", 6, "ENFUIT").
dico("E", 6, "ENFUMA").
dico("E", 6, "ENFUME").
dico("E", 6, "ENFUTA").
dico("E", 6, "ENFUTE").
dico("E", 6, "ENGAGE").
dico("E", 6, "ENGAMA").
dico("E", 6, "ENGAME").
dico("E", 6, "ENGANE").
dico("E", 6, "ENGINS").
dico("E", 6, "ENGLUA").
dico("E", 6, "ENGLUE").
dico("E", 6, "ENGOBA").
dico("E", 6, "ENGOBE").
dico("E", 6, "ENGOUA").
dico("E", 6, "ENGOUE").
dico("E", 6, "ENIEME").
dico("E", 6, "ENIGME").
dico("E", 6, "ENIVRA").
dico("E", 6, "ENIVRE").
dico("E", 6, "ENJEUX").
dico("E", 6, "ENJOLA").
dico("E", 6, "ENJOLE").
dico("E", 6, "ENJOUE").
dico("E", 6, "ENLACA").
dico("E", 6, "ENLACE").
dico("E", 6, "ENLEVA").
dico("E", 6, "ENLEVE").
dico("E", 6, "ENLIAI").
dico("E", 6, "ENLIAS").
dico("E", 6, "ENLIAT").
dico("E", 6, "ENLIEE").
dico("E", 6, "ENLIER").
dico("E", 6, "ENLIES").
dico("E", 6, "ENLIEZ").
dico("E", 6, "ENLISA").
dico("E", 6, "ENLISE").
dico("E", 6, "ENLOGE").
dico("E", 6, "ENNEMI").
dico("E", 6, "ENNOIE").
dico("E", 6, "ENNOYA").
dico("E", 6, "ENNOYE").
dico("E", 6, "ENNUIE").
dico("E", 6, "ENNUIS").
dico("E", 6, "ENNUYA").
dico("E", 6, "ENNUYE").
dico("E", 6, "ENONCA").
dico("E", 6, "ENONCE").
dico("E", 6, "ENORME").
dico("E", 6, "ENOUAI").
dico("E", 6, "ENOUAS").
dico("E", 6, "ENOUAT").
dico("E", 6, "ENOUEE").
dico("E", 6, "ENOUER").
dico("E", 6, "ENOUES").
dico("E", 6, "ENOUEZ").
dico("E", 6, "ENQUIS").
dico("E", 6, "ENQUIT").
dico("E", 6, "ENRAGE").
dico("E", 6, "ENRAIE").
dico("E", 6, "ENRAYA").
dico("E", 6, "ENRAYE").
dico("E", 6, "ENRENA").
dico("E", 6, "ENRENE").
dico("E", 6, "ENROBA").
dico("E", 6, "ENROBE").
dico("E", 6, "ENROLA").
dico("E", 6, "ENROLE").
dico("E", 6, "ENROUA").
dico("E", 6, "ENROUE").
dico("E", 6, "ENSILA").
dico("E", 6, "ENSILE").
dico("E", 6, "ENSIMA").
dico("E", 6, "ENSIME").
dico("E", 6, "ENSUIT").
dico("E", 6, "ENTAIS").
dico("E", 6, "ENTAIT").
dico("E", 6, "ENTAMA").
dico("E", 6, "ENTAME").
dico("E", 6, "ENTANT").
dico("E", 6, "ENTEES").
dico("E", 6, "ENTEND").
dico("E", 6, "ENTENT").
dico("E", 6, "ENTERA").
dico("E", 6, "ENTETA").
dico("E", 6, "ENTETE").
dico("E", 6, "ENTIER").
dico("E", 6, "ENTIEZ").
dico("E", 6, "ENTITE").
dico("E", 6, "ENTOIR").
dico("E", 6, "ENTOLA").
dico("E", 6, "ENTOLE").
dico("E", 6, "ENTONS").
dico("E", 6, "ENTOUR").
dico("E", 6, "ENTRAI").
dico("E", 6, "ENTRAS").
dico("E", 6, "ENTRAT").
dico("E", 6, "ENTREE").
dico("E", 6, "ENTRER").
dico("E", 6, "ENTRES").
dico("E", 6, "ENTREZ").
dico("E", 6, "ENTUBA").
dico("E", 6, "ENTUBE").
dico("E", 6, "ENTURE").
dico("E", 6, "ENUQUA").
dico("E", 6, "ENUQUE").
dico("E", 6, "ENVAHI").
dico("E", 6, "ENVASA").
dico("E", 6, "ENVASE").
dico("E", 6, "ENVERS").
dico("E", 6, "ENVIAI").
dico("E", 6, "ENVIAS").
dico("E", 6, "ENVIAT").
dico("E", 6, "ENVIDA").
dico("E", 6, "ENVIDE").
dico("E", 6, "ENVIEE").
dico("E", 6, "ENVIER").
dico("E", 6, "ENVIES").
dico("E", 6, "ENVIEZ").
dico("E", 6, "ENVINE").
dico("E", 6, "ENVOIE").
dico("E", 6, "ENVOIS").
dico("E", 6, "ENVOLA").
dico("E", 6, "ENVOLE").
dico("E", 6, "ENVOLS").
dico("E", 6, "ENVOYA").
dico("E", 6, "ENVOYE").
dico("E", 6, "ENZYME").
dico("E", 6, "EOCENE").
dico("E", 6, "EOGENE").
dico("E", 6, "EOLIEN").
dico("E", 6, "EOSINE").
dico("E", 6, "EPACTE").
dico("E", 6, "EPAIRS").
dico("E", 6, "EPANDE").
dico("E", 6, "EPANDS").
dico("E", 6, "EPANDU").
dico("E", 6, "EPANNA").
dico("E", 6, "EPANNE").
dico("E", 6, "EPARSE").
dico("E", 6, "EPARTS").
dico("E", 6, "EPATAI").
dico("E", 6, "EPATAS").
dico("E", 6, "EPATAT").
dico("E", 6, "EPATEE").
dico("E", 6, "EPATER").
dico("E", 6, "EPATES").
dico("E", 6, "EPATEZ").
dico("E", 6, "EPAULA").
dico("E", 6, "EPAULE").
dico("E", 6, "EPAVES").
dico("E", 6, "EPECLA").
dico("E", 6, "EPECLE").
dico("E", 6, "EPEIRE").
dico("E", 6, "EPELAI").
dico("E", 6, "EPELAS").
dico("E", 6, "EPELAT").
dico("E", 6, "EPELEE").
dico("E", 6, "EPELER").
dico("E", 6, "EPELES").
dico("E", 6, "EPELEZ").
dico("E", 6, "EPELLE").
dico("E", 6, "EPERDU").
dico("E", 6, "EPERON").
dico("E", 6, "EPEURA").
dico("E", 6, "EPEURE").
dico("E", 6, "EPHEBE").
dico("E", 6, "EPHODS").
dico("E", 6, "EPHORE").
dico("E", 6, "EPIAGE").
dico("E", 6, "EPIAIS").
dico("E", 6, "EPIAIT").
dico("E", 6, "EPIANT").
dico("E", 6, "EPICAI").
dico("E", 6, "EPICAS").
dico("E", 6, "EPICAT").
dico("E", 6, "EPICEA").
dico("E", 6, "EPICEE").
dico("E", 6, "EPICER").
dico("E", 6, "EPICES").
dico("E", 6, "EPICEZ").
dico("E", 6, "EPIEES").
dico("E", 6, "EPIENT").
dico("E", 6, "EPIERA").
dico("E", 6, "EPIEUR").
dico("E", 6, "EPIEUX").
dico("E", 6, "EPIGEE").
dico("E", 6, "EPIGES").
dico("E", 6, "EPIIEZ").
dico("E", 6, "EPILAI").
dico("E", 6, "EPILAS").
dico("E", 6, "EPILAT").
dico("E", 6, "EPILEE").
dico("E", 6, "EPILER").
dico("E", 6, "EPILES").
dico("E", 6, "EPILEZ").
dico("E", 6, "EPINAI").
dico("E", 6, "EPINAS").
dico("E", 6, "EPINAT").
dico("E", 6, "EPINCA").
dico("E", 6, "EPINCE").
dico("E", 6, "EPINEE").
dico("E", 6, "EPINER").
dico("E", 6, "EPINES").
dico("E", 6, "EPINEZ").
dico("E", 6, "EPIONS").
dico("E", 6, "EPIQUE").
dico("E", 6, "EPISSA").
dico("E", 6, "EPISSE").
dico("E", 6, "EPITES").
dico("E", 6, "EPITRE").
dico("E", 6, "EPLOIE").
dico("E", 6, "EPLORE").
dico("E", 6, "EPLOYA").
dico("E", 6, "EPLOYE").
dico("E", 6, "EPOCHE").
dico("E", 6, "EPODES").
dico("E", 6, "EPONGE").
dico("E", 6, "EPONTE").
dico("E", 6, "EPOPEE").
dico("E", 6, "EPOQUE").
dico("E", 6, "EPOUSA").
dico("E", 6, "EPOUSE").
dico("E", 6, "EPOUTI").
dico("E", 6, "EPOXYS").
dico("E", 6, "EPREND").
dico("E", 6, "EPRISE").
dico("E", 6, "EPUCAI").
dico("E", 6, "EPUCAS").
dico("E", 6, "EPUCAT").
dico("E", 6, "EPUCEE").
dico("E", 6, "EPUCER").
dico("E", 6, "EPUCES").
dico("E", 6, "EPUCEZ").
dico("E", 6, "EPUISA").
dico("E", 6, "EPUISE").
dico("E", 6, "EPULIE").
dico("E", 6, "EPULIS").
dico("E", 6, "EPULON").
dico("E", 6, "EPURAI").
dico("E", 6, "EPURAS").
dico("E", 6, "EPURAT").
dico("E", 6, "EPUREE").
dico("E", 6, "EPURER").
dico("E", 6, "EPURES").
dico("E", 6, "EPUREZ").
dico("E", 6, "EPURGE").
dico("E", 6, "EQUIDE").
dico("E", 6, "EQUINE").
dico("E", 6, "EQUINS").
dico("E", 6, "EQUIPA").
dico("E", 6, "EQUIPE").
dico("E", 6, "EQUITE").
dico("E", 6, "ERABLE").
dico("E", 6, "ERAFLA").
dico("E", 6, "ERAFLE").
dico("E", 6, "ERBINE").
dico("E", 6, "ERBIUM").
dico("E", 6, "ERBUES").
dico("E", 6, "ERGOLS").
dico("E", 6, "ERGOTA").
dico("E", 6, "ERGOTE").
dico("E", 6, "ERGOTS").
dico("E", 6, "ERIGEA").
dico("E", 6, "ERIGEE").
dico("E", 6, "ERIGER").
dico("E", 6, "ERIGES").
dico("E", 6, "ERIGEZ").
dico("E", 6, "ERIGNE").
dico("E", 6, "ERINES").
dico("E", 6, "ERMITE").
dico("E", 6, "ERODAI").
dico("E", 6, "ERODAS").
dico("E", 6, "ERODAT").
dico("E", 6, "ERODEE").
dico("E", 6, "ERODER").
dico("E", 6, "ERODES").
dico("E", 6, "ERODEZ").
dico("E", 6, "EROSIF").
dico("E", 6, "ERRAIS").
dico("E", 6, "ERRAIT").
dico("E", 6, "ERRANT").
dico("E", 6, "ERRATA").
dico("E", 6, "ERRENT").
dico("E", 6, "ERRERA").
dico("E", 6, "ERREUR").
dico("E", 6, "ERRIEZ").
dico("E", 6, "ERRONE").
dico("E", 6, "ERRONS").
dico("E", 6, "ERSATZ").
dico("E", 6, "ERSEAU").
dico("E", 6, "ERUCTA").
dico("E", 6, "ERUCTE").
dico("E", 6, "ERUDIT").
dico("E", 6, "ESCALE").
dico("E", 6, "ESCAPE").
dico("E", 6, "ESCHAI").
dico("E", 6, "ESCHAS").
dico("E", 6, "ESCHAT").
dico("E", 6, "ESCHEE").
dico("E", 6, "ESCHER").
dico("E", 6, "ESCHES").
dico("E", 6, "ESCHEZ").
dico("E", 6, "ESCOTS").
dico("E", 6, "ESCROC").
dico("E", 6, "ESCUDO").
dico("E", 6, "ESKIMO").
dico("E", 6, "ESPACA").
dico("E", 6, "ESPACE").
dico("E", 6, "ESPADA").
dico("E", 6, "ESPARS").
dico("E", 6, "ESPECE").
dico("E", 6, "ESPERA").
dico("E", 6, "ESPERE").
dico("E", 6, "ESPION").
dico("E", 6, "ESPOIR").
dico("E", 6, "ESPRIT").
dico("E", 6, "ESQUIF").
dico("E", 6, "ESSAIE").
dico("E", 6, "ESSAIM").
dico("E", 6, "ESSAIS").
dico("E", 6, "ESSART").
dico("E", 6, "ESSAYA").
dico("E", 6, "ESSAYE").
dico("E", 6, "ESSIEU").
dico("E", 6, "ESSORA").
dico("E", 6, "ESSORE").
dico("E", 6, "ESSORS").
dico("E", 6, "ESSUIE").
dico("E", 6, "ESSUYA").
dico("E", 6, "ESSUYE").
dico("E", 6, "ESTERS").
dico("E", 6, "ESTIMA").
dico("E", 6, "ESTIME").
dico("E", 6, "ESTIVA").
dico("E", 6, "ESTIVE").
dico("E", 6, "ESTOCS").
dico("E", 6, "ESTRAN").
dico("E", 6, "ETABLA").
dico("E", 6, "ETABLE").
dico("E", 6, "ETABLI").
dico("E", 6, "ETAGEA").
dico("E", 6, "ETAGEE").
dico("E", 6, "ETAGER").
dico("E", 6, "ETAGES").
dico("E", 6, "ETAGEZ").
dico("E", 6, "ETAIES").
dico("E", 6, "ETAINS").
dico("E", 6, "ETALAI").
dico("E", 6, "ETALAS").
dico("E", 6, "ETALAT").
dico("E", 6, "ETALEE").
dico("E", 6, "ETALER").
dico("E", 6, "ETALES").
dico("E", 6, "ETALEZ").
dico("E", 6, "ETALON").
dico("E", 6, "ETAMAI").
dico("E", 6, "ETAMAS").
dico("E", 6, "ETAMAT").
dico("E", 6, "ETAMEE").
dico("E", 6, "ETAMER").
dico("E", 6, "ETAMES").
dico("E", 6, "ETAMEZ").
dico("E", 6, "ETAMPA").
dico("E", 6, "ETAMPE").
dico("E", 6, "ETANGS").
dico("E", 6, "ETANTS").
dico("E", 6, "ETAPES").
dico("E", 6, "ETAYAI").
dico("E", 6, "ETAYAS").
dico("E", 6, "ETAYAT").
dico("E", 6, "ETAYEE").
dico("E", 6, "ETAYER").
dico("E", 6, "ETAYES").
dico("E", 6, "ETAYEZ").
dico("E", 6, "ETEINS").
dico("E", 6, "ETEINT").
dico("E", 6, "ETENDE").
dico("E", 6, "ETENDS").
dico("E", 6, "ETENDU").
dico("E", 6, "ETETAI").
dico("E", 6, "ETETAS").
dico("E", 6, "ETETAT").
dico("E", 6, "ETETEE").
dico("E", 6, "ETETER").
dico("E", 6, "ETETES").
dico("E", 6, "ETETEZ").
dico("E", 6, "ETEUFS").
dico("E", 6, "ETEULE").
dico("E", 6, "ETHANE").
dico("E", 6, "ETHERE").
dico("E", 6, "ETHERS").
dico("E", 6, "ETHNIE").
dico("E", 6, "ETHUSE").
dico("E", 6, "ETHYLE").
dico("E", 6, "ETIAGE").
dico("E", 6, "ETIERS").
dico("E", 6, "ETIGEA").
dico("E", 6, "ETIGEE").
dico("E", 6, "ETIGER").
dico("E", 6, "ETIGES").
dico("E", 6, "ETIGEZ").
dico("E", 6, "ETIOLA").
dico("E", 6, "ETIOLE").
dico("E", 6, "ETIONS").
dico("E", 6, "ETIQUE").
dico("E", 6, "ETIRAI").
dico("E", 6, "ETIRAS").
dico("E", 6, "ETIRAT").
dico("E", 6, "ETIREE").
dico("E", 6, "ETIRER").
dico("E", 6, "ETIRES").
dico("E", 6, "ETIREZ").
dico("E", 6, "ETISIE").
dico("E", 6, "ETOFFA").
dico("E", 6, "ETOFFE").
dico("E", 6, "ETOILA").
dico("E", 6, "ETOILE").
dico("E", 6, "ETOLES").
dico("E", 6, "ETONNA").
dico("E", 6, "ETONNE").
dico("E", 6, "ETOUPA").
dico("E", 6, "ETOUPE").
dico("E", 6, "ETRAVE").
dico("E", 6, "ETRECI").
dico("E", 6, "ETRIER").
dico("E", 6, "ETRIPA").
dico("E", 6, "ETRIPE").
dico("E", 6, "ETRIVA").
dico("E", 6, "ETRIVE").
dico("E", 6, "ETROIT").
dico("E", 6, "ETRONS").
dico("E", 6, "ETUDES").
dico("E", 6, "ETUDIA").
dico("E", 6, "ETUDIE").
dico("E", 6, "ETUVAI").
dico("E", 6, "ETUVAS").
dico("E", 6, "ETUVAT").
dico("E", 6, "ETUVEE").
dico("E", 6, "ETUVER").
dico("E", 6, "ETUVES").
dico("E", 6, "ETUVEZ").
dico("E", 6, "ETYMON").
dico("E", 6, "EUBAGE").
dico("E", 6, "EUMENE").
dico("E", 6, "EUREKA").
dico("E", 6, "EURENT").
dico("E", 6, "EUSSES").
dico("E", 6, "EVACUA").
dico("E", 6, "EVACUE").
dico("E", 6, "EVADAI").
dico("E", 6, "EVADAS").
dico("E", 6, "EVADAT").
dico("E", 6, "EVADEE").
dico("E", 6, "EVADER").
dico("E", 6, "EVADES").
dico("E", 6, "EVADEZ").
dico("E", 6, "EVALUA").
dico("E", 6, "EVALUE").
dico("E", 6, "EVASAI").
dico("E", 6, "EVASAS").
dico("E", 6, "EVASAT").
dico("E", 6, "EVASEE").
dico("E", 6, "EVASER").
dico("E", 6, "EVASES").
dico("E", 6, "EVASEZ").
dico("E", 6, "EVASIF").
dico("E", 6, "EVECHE").
dico("E", 6, "EVEILS").
dico("E", 6, "EVENTA").
dico("E", 6, "EVENTE").
dico("E", 6, "EVENTS").
dico("E", 6, "EVEQUE").
dico("E", 6, "EVIDAI").
dico("E", 6, "EVIDAS").
dico("E", 6, "EVIDAT").
dico("E", 6, "EVIDEE").
dico("E", 6, "EVIDER").
dico("E", 6, "EVIDES").
dico("E", 6, "EVIDEZ").
dico("E", 6, "EVIERS").
dico("E", 6, "EVINCA").
dico("E", 6, "EVINCE").
dico("E", 6, "EVITAI").
dico("E", 6, "EVITAS").
dico("E", 6, "EVITAT").
dico("E", 6, "EVITEE").
dico("E", 6, "EVITER").
dico("E", 6, "EVITES").
dico("E", 6, "EVITEZ").
dico("E", 6, "EVOLUA").
dico("E", 6, "EVOLUE").
dico("E", 6, "EVOQUA").
dico("E", 6, "EVOQUE").
dico("E", 6, "EVRYEN").
dico("E", 6, "EVZONE").
dico("E", 6, "EXACTE").
dico("E", 6, "EXACTS").
dico("E", 6, "EXALTA").
dico("E", 6, "EXALTE").
dico("E", 6, "EXAMEN").
dico("E", 6, "EXAUCA").
dico("E", 6, "EXAUCE").
dico("E", 6, "EXCAVA").
dico("E", 6, "EXCAVE").
dico("E", 6, "EXCEDA").
dico("E", 6, "EXCEDE").
dico("E", 6, "EXCIPA").
dico("E", 6, "EXCIPE").
dico("E", 6, "EXCISA").
dico("E", 6, "EXCISE").
dico("E", 6, "EXCITA").
dico("E", 6, "EXCITE").
dico("E", 6, "EXCLUE").
dico("E", 6, "EXCLUS").
dico("E", 6, "EXCLUT").
dico("E", 6, "EXCUSA").
dico("E", 6, "EXCUSE").
dico("E", 6, "EXECRA").
dico("E", 6, "EXECRE").
dico("E", 6, "EXEDRE").
dico("E", 6, "EXEMPT").
dico("E", 6, "EXERCA").
dico("E", 6, "EXERCE").
dico("E", 6, "EXEUNT").
dico("E", 6, "EXHALA").
dico("E", 6, "EXHALE").
dico("E", 6, "EXHIBA").
dico("E", 6, "EXHIBE").
dico("E", 6, "EXHUMA").
dico("E", 6, "EXHUME").
dico("E", 6, "EXIGEA").
dico("E", 6, "EXIGEE").
dico("E", 6, "EXIGER").
dico("E", 6, "EXIGES").
dico("E", 6, "EXIGEZ").
dico("E", 6, "EXIGUE").
dico("E", 6, "EXIGUS").
dico("E", 6, "EXILAI").
dico("E", 6, "EXILAS").
dico("E", 6, "EXILAT").
dico("E", 6, "EXILEE").
dico("E", 6, "EXILER").
dico("E", 6, "EXILES").
dico("E", 6, "EXILEZ").
dico("E", 6, "EXISTA").
dico("E", 6, "EXISTE").
dico("E", 6, "EXOCET").
dico("E", 6, "EXODES").
dico("E", 6, "EXONDA").
dico("E", 6, "EXONDE").
dico("E", 6, "EXORDE").
dico("E", 6, "EXPERT").
dico("E", 6, "EXPIAI").
dico("E", 6, "EXPIAS").
dico("E", 6, "EXPIAT").
dico("E", 6, "EXPIEE").
dico("E", 6, "EXPIER").
dico("E", 6, "EXPIES").
dico("E", 6, "EXPIEZ").
dico("E", 6, "EXPIRA").
dico("E", 6, "EXPIRE").
dico("E", 6, "EXPORT").
dico("E", 6, "EXPOSA").
dico("E", 6, "EXPOSE").
dico("E", 6, "EXPRES").
dico("E", 6, "EXQUIS").
dico("E", 6, "EXSUDA").
dico("E", 6, "EXSUDE").
dico("E", 6, "EXTASE").
dico("E", 6, "EXTRAS").
dico("E", 6, "EXTUBA").
dico("E", 6, "EXTUBE").
dico("E", 6, "EXULTA").
dico("E", 6, "EXULTE").
dico("E", 6, "EXUVIE").
dico("E", 6, "EYALET").
