dico("F", 10, "FABRICANTE").
dico("F", 10, "FABRICANTS").
dico("F", 10, "FABRICIENS").
dico("F", 10, "FABRIQUAIS").
dico("F", 10, "FABRIQUAIT").
dico("F", 10, "FABRIQUANT").
dico("F", 10, "FABRIQUEES").
dico("F", 10, "FABRIQUENT").
dico("F", 10, "FABRIQUERA").
dico("F", 10, "FABRIQUIEZ").
dico("F", 10, "FABRIQUONS").
dico("F", 10, "FABULAIENT").
dico("F", 10, "FABULASSES").
dico("F", 10, "FABULATEUR").
dico("F", 10, "FABULATION").
dico("F", 10, "FABULERAIS").
dico("F", 10, "FABULERAIT").
dico("F", 10, "FABULERENT").
dico("F", 10, "FABULERIEZ").
dico("F", 10, "FABULERONS").
dico("F", 10, "FABULERONT").
dico("F", 10, "FABULEUSES").
dico("F", 10, "FABULISTES").
dico("F", 10, "FACETIEUSE").
dico("F", 10, "FACETTAMES").
dico("F", 10, "FACETTASSE").
dico("F", 10, "FACETTATES").
dico("F", 10, "FACETTERAI").
dico("F", 10, "FACETTERAS").
dico("F", 10, "FACETTEREZ").
dico("F", 10, "FACETTIONS").
dico("F", 10, "FACHASSENT").
dico("F", 10, "FACHASSIEZ").
dico("F", 10, "FACHERIONS").
dico("F", 10, "FACILEMENT").
dico("F", 10, "FACILITAIS").
dico("F", 10, "FACILITAIT").
dico("F", 10, "FACILITANT").
dico("F", 10, "FACILITEES").
dico("F", 10, "FACILITENT").
dico("F", 10, "FACILITERA").
dico("F", 10, "FACILITIEZ").
dico("F", 10, "FACILITONS").
dico("F", 10, "FACONNAGES").
dico("F", 10, "FACONNAMES").
dico("F", 10, "FACONNASSE").
dico("F", 10, "FACONNATES").
dico("F", 10, "FACONNERAI").
dico("F", 10, "FACONNERAS").
dico("F", 10, "FACONNEREZ").
dico("F", 10, "FACONNEURS").
dico("F", 10, "FACONNEUSE").
dico("F", 10, "FACONNIERE").
dico("F", 10, "FACONNIERS").
dico("F", 10, "FACONNIONS").
dico("F", 10, "FACTICITES").
dico("F", 10, "FACTIEUSES").
dico("F", 10, "FACTITIVES").
dico("F", 10, "FACTORAGES").
dico("F", 10, "FACTORERIE").
dico("F", 10, "FACTORIELS").
dico("F", 10, "FACTORINGS").
dico("F", 10, "FACTORISAI").
dico("F", 10, "FACTORISAS").
dico("F", 10, "FACTORISAT").
dico("F", 10, "FACTORISEE").
dico("F", 10, "FACTORISER").
dico("F", 10, "FACTORISES").
dico("F", 10, "FACTORISEZ").
dico("F", 10, "FACTUELLES").
dico("F", 10, "FACTURAMES").
dico("F", 10, "FACTURASSE").
dico("F", 10, "FACTURATES").
dico("F", 10, "FACTURERAI").
dico("F", 10, "FACTURERAS").
dico("F", 10, "FACTUREREZ").
dico("F", 10, "FACTURETTE").
dico("F", 10, "FACTURIERE").
dico("F", 10, "FACTURIERS").
dico("F", 10, "FACTURIONS").
dico("F", 10, "FACULTAIRE").
dico("F", 10, "FACULTATIF").
dico("F", 10, "FADASSERIE").
dico("F", 10, "FADASSIONS").
dico("F", 10, "FADERAIENT").
dico("F", 10, "FAGOTAIENT").
dico("F", 10, "FAGOTASSES").
dico("F", 10, "FAGOTERAIS").
dico("F", 10, "FAGOTERAIT").
dico("F", 10, "FAGOTERENT").
dico("F", 10, "FAGOTERIEZ").
dico("F", 10, "FAGOTERONS").
dico("F", 10, "FAGOTERONT").
dico("F", 10, "FAGOTEUSES").
dico("F", 10, "FAGOTIERES").
dico("F", 10, "FAHRENHEIT").
dico("F", 10, "FAIBLARDES").
dico("F", 10, "FAIBLEMENT").
dico("F", 10, "FAIBLESSES").
dico("F", 10, "FAIBLIRAIS").
dico("F", 10, "FAIBLIRAIT").
dico("F", 10, "FAIBLIRENT").
dico("F", 10, "FAIBLIRIEZ").
dico("F", 10, "FAIBLIRONS").
dico("F", 10, "FAIBLIRONT").
dico("F", 10, "FAIBLISSES").
dico("F", 10, "FAIBLISSEZ").
dico("F", 10, "FAIENCAGES").
dico("F", 10, "FAIENCERIE").
dico("F", 10, "FAIENCIERE").
dico("F", 10, "FAIENCIERS").
dico("F", 10, "FAIGNANTES").
dico("F", 10, "FAILLAIENT").
dico("F", 10, "FAILLASSES").
dico("F", 10, "FAILLERAIS").
dico("F", 10, "FAILLERAIT").
dico("F", 10, "FAILLERENT").
dico("F", 10, "FAILLERIEZ").
dico("F", 10, "FAILLERONS").
dico("F", 10, "FAILLERONT").
dico("F", 10, "FAILLIBLES").
dico("F", 10, "FAILLIRAIS").
dico("F", 10, "FAILLIRAIT").
dico("F", 10, "FAILLIRENT").
dico("F", 10, "FAILLIRIEZ").
dico("F", 10, "FAILLIRONS").
dico("F", 10, "FAILLIRONT").
dico("F", 10, "FAILLISSES").
dico("F", 10, "FAILLISSEZ").
dico("F", 10, "FAINEANTAI").
dico("F", 10, "FAINEANTAS").
dico("F", 10, "FAINEANTAT").
dico("F", 10, "FAINEANTER").
dico("F", 10, "FAINEANTES").
dico("F", 10, "FAINEANTEZ").
dico("F", 10, "FAISANDAGE").
dico("F", 10, "FAISANDAIS").
dico("F", 10, "FAISANDAIT").
dico("F", 10, "FAISANDANT").
dico("F", 10, "FAISANDEAU").
dico("F", 10, "FAISANDEES").
dico("F", 10, "FAISANDENT").
dico("F", 10, "FAISANDERA").
dico("F", 10, "FAISANDIER").
dico("F", 10, "FAISANDIEZ").
dico("F", 10, "FAISANDONS").
dico("F", 10, "FAISANNEAU").
dico("F", 10, "FAISSELLES").
dico("F", 10, "FAKIRISMES").
dico("F", 10, "FALARIQUES").
dico("F", 10, "FALCIFORME").
dico("F", 10, "FALCONIDES").
dico("F", 10, "FALLACIEUX").
dico("F", 10, "FALSIFIAIS").
dico("F", 10, "FALSIFIAIT").
dico("F", 10, "FALSIFIANT").
dico("F", 10, "FALSIFIEES").
dico("F", 10, "FALSIFIENT").
dico("F", 10, "FALSIFIERA").
dico("F", 10, "FALSIFIIEZ").
dico("F", 10, "FALSIFIONS").
dico("F", 10, "FALUNAIENT").
dico("F", 10, "FALUNASSES").
dico("F", 10, "FALUNERAIS").
dico("F", 10, "FALUNERAIT").
dico("F", 10, "FALUNERENT").
dico("F", 10, "FALUNERIEZ").
dico("F", 10, "FALUNERONS").
dico("F", 10, "FALUNERONT").
dico("F", 10, "FALUNIERES").
dico("F", 10, "FAMELIQUES").
dico("F", 10, "FAMENNOISE").
dico("F", 10, "FAMILIALES").
dico("F", 10, "FAMILIERES").
dico("F", 10, "FANASSIONS").
dico("F", 10, "FANATIQUES").
dico("F", 10, "FANATISAIS").
dico("F", 10, "FANATISAIT").
dico("F", 10, "FANATISANT").
dico("F", 10, "FANATISEES").
dico("F", 10, "FANATISENT").
dico("F", 10, "FANATISERA").
dico("F", 10, "FANATISEUR").
dico("F", 10, "FANATISIEZ").
dico("F", 10, "FANATISMES").
dico("F", 10, "FANATISONS").
dico("F", 10, "FANERAIENT").
dico("F", 10, "FANFARONNA").
dico("F", 10, "FANFARONNE").
dico("F", 10, "FANTAISIES").
dico("F", 10, "FANTASMAIS").
dico("F", 10, "FANTASMAIT").
dico("F", 10, "FANTASMANT").
dico("F", 10, "FANTASMEES").
dico("F", 10, "FANTASMENT").
dico("F", 10, "FANTASMERA").
dico("F", 10, "FANTASMIEZ").
dico("F", 10, "FANTASMONS").
dico("F", 10, "FANTASQUES").
dico("F", 10, "FANTASSINS").
dico("F", 10, "FANTOMALES").
dico("F", 10, "FARADIQUES").
dico("F", 10, "FARAMINEUX").
dico("F", 10, "FARANDOLAI").
dico("F", 10, "FARANDOLAS").
dico("F", 10, "FARANDOLAT").
dico("F", 10, "FARANDOLER").
dico("F", 10, "FARANDOLES").
dico("F", 10, "FARANDOLEZ").
dico("F", 10, "FARCIRIONS").
dico("F", 10, "FARCISSAIS").
dico("F", 10, "FARCISSAIT").
dico("F", 10, "FARCISSANT").
dico("F", 10, "FARCISSENT").
dico("F", 10, "FARCISSIEZ").
dico("F", 10, "FARCISSONS").
dico("F", 10, "FARDASSENT").
dico("F", 10, "FARDASSIEZ").
dico("F", 10, "FARDERIONS").
dico("F", 10, "FARFOUILLA").
dico("F", 10, "FARFOUILLE").
dico("F", 10, "FARIGOULES").
dico("F", 10, "FARINACEES").
dico("F", 10, "FARINAIENT").
dico("F", 10, "FARINASSES").
dico("F", 10, "FARINERAIS").
dico("F", 10, "FARINERAIT").
dico("F", 10, "FARINERENT").
dico("F", 10, "FARINERIEZ").
dico("F", 10, "FARINERONS").
dico("F", 10, "FARINERONT").
dico("F", 10, "FARINEUSES").
dico("F", 10, "FARINIERES").
dico("F", 10, "FARLOUCHES").
dico("F", 10, "FARNIENTES").
dico("F", 10, "FARTASSENT").
dico("F", 10, "FARTASSIEZ").
dico("F", 10, "FARTERIONS").
dico("F", 10, "FASCIATION").
dico("F", 10, "FASCICULEE").
dico("F", 10, "FASCICULES").
dico("F", 10, "FASCINAGES").
dico("F", 10, "FASCINAMES").
dico("F", 10, "FASCINANTE").
dico("F", 10, "FASCINANTS").
dico("F", 10, "FASCINASSE").
dico("F", 10, "FASCINATES").
dico("F", 10, "FASCINERAI").
dico("F", 10, "FASCINERAS").
dico("F", 10, "FASCINEREZ").
dico("F", 10, "FASCINIONS").
dico("F", 10, "FASCISAMES").
dico("F", 10, "FASCISANTE").
dico("F", 10, "FASCISANTS").
dico("F", 10, "FASCISASSE").
dico("F", 10, "FASCISATES").
dico("F", 10, "FASCISERAI").
dico("F", 10, "FASCISERAS").
dico("F", 10, "FASCISEREZ").
dico("F", 10, "FASCISIONS").
dico("F", 10, "FASEILLAIS").
dico("F", 10, "FASEILLAIT").
dico("F", 10, "FASEILLANT").
dico("F", 10, "FASEILLENT").
dico("F", 10, "FASEILLERA").
dico("F", 10, "FASEILLIEZ").
dico("F", 10, "FASEILLONS").
dico("F", 10, "FASEYAIENT").
dico("F", 10, "FASEYASSES").
dico("F", 10, "FASEYERAIS").
dico("F", 10, "FASEYERAIT").
dico("F", 10, "FASEYERENT").
dico("F", 10, "FASEYERIEZ").
dico("F", 10, "FASEYERONS").
dico("F", 10, "FASEYERONT").
dico("F", 10, "FASTIDIEUX").
dico("F", 10, "FASTIGIEES").
dico("F", 10, "FASTUEUSES").
dico("F", 10, "FATALEMENT").
dico("F", 10, "FATALISMES").
dico("F", 10, "FATALISTES").
dico("F", 10, "FATIDIQUES").
dico("F", 10, "FATIGABLES").
dico("F", 10, "FATIGANTES").
dico("F", 10, "FATIGUAMES").
dico("F", 10, "FATIGUASSE").
dico("F", 10, "FATIGUATES").
dico("F", 10, "FATIGUERAI").
dico("F", 10, "FATIGUERAS").
dico("F", 10, "FATIGUEREZ").
dico("F", 10, "FATIGUIONS").
dico("F", 10, "FAUBOURIEN").
dico("F", 10, "FAUCARDAGE").
dico("F", 10, "FAUCARDAIS").
dico("F", 10, "FAUCARDAIT").
dico("F", 10, "FAUCARDANT").
dico("F", 10, "FAUCARDEES").
dico("F", 10, "FAUCARDENT").
dico("F", 10, "FAUCARDERA").
dico("F", 10, "FAUCARDEUR").
dico("F", 10, "FAUCARDIEZ").
dico("F", 10, "FAUCARDONS").
dico("F", 10, "FAUCHAIENT").
dico("F", 10, "FAUCHAISON").
dico("F", 10, "FAUCHASSES").
dico("F", 10, "FAUCHERAIS").
dico("F", 10, "FAUCHERAIT").
dico("F", 10, "FAUCHERENT").
dico("F", 10, "FAUCHERIEZ").
dico("F", 10, "FAUCHERONS").
dico("F", 10, "FAUCHERONT").
dico("F", 10, "FAUCHETTES").
dico("F", 10, "FAUCHEUSES").
dico("F", 10, "FAUCILLONS").
dico("F", 10, "FAUCONNEAU").
dico("F", 10, "FAUCONNIER").
dico("F", 10, "FAUFILAGES").
dico("F", 10, "FAUFILAMES").
dico("F", 10, "FAUFILASSE").
dico("F", 10, "FAUFILATES").
dico("F", 10, "FAUFILERAI").
dico("F", 10, "FAUFILERAS").
dico("F", 10, "FAUFILEREZ").
dico("F", 10, "FAUFILIONS").
dico("F", 10, "FAUFILURES").
dico("F", 10, "FAUNESQUES").
dico("F", 10, "FAUSSAIENT").
dico("F", 10, "FAUSSAIRES").
dico("F", 10, "FAUSSASSES").
dico("F", 10, "FAUSSEMENT").
dico("F", 10, "FAUSSERAIS").
dico("F", 10, "FAUSSERAIT").
dico("F", 10, "FAUSSERENT").
dico("F", 10, "FAUSSERIEZ").
dico("F", 10, "FAUSSERONS").
dico("F", 10, "FAUSSERONT").
dico("F", 10, "FAUTASSENT").
dico("F", 10, "FAUTASSIEZ").
dico("F", 10, "FAUTERIONS").
dico("F", 10, "FAVORABLES").
dico("F", 10, "FAVORISAIS").
dico("F", 10, "FAVORISAIT").
dico("F", 10, "FAVORISANT").
dico("F", 10, "FAVORISEES").
dico("F", 10, "FAVORISENT").
dico("F", 10, "FAVORISERA").
dico("F", 10, "FAVORISIEZ").
dico("F", 10, "FAVORISONS").
dico("F", 10, "FAXASSIONS").
dico("F", 10, "FAXERAIENT").
dico("F", 10, "FAYOTAIENT").
dico("F", 10, "FAYOTASSES").
dico("F", 10, "FAYOTERAIS").
dico("F", 10, "FAYOTERAIT").
dico("F", 10, "FAYOTERENT").
dico("F", 10, "FAYOTERIEZ").
dico("F", 10, "FAYOTERONS").
dico("F", 10, "FAYOTERONT").
dico("F", 10, "FEBRICULES").
dico("F", 10, "FEBRIFUGES").
dico("F", 10, "FEBRILITES").
dico("F", 10, "FECALOIDES").
dico("F", 10, "FECONDABLE").
dico("F", 10, "FECONDAMES").
dico("F", 10, "FECONDANTE").
dico("F", 10, "FECONDANTS").
dico("F", 10, "FECONDASSE").
dico("F", 10, "FECONDATES").
dico("F", 10, "FECONDERAI").
dico("F", 10, "FECONDERAS").
dico("F", 10, "FECONDEREZ").
dico("F", 10, "FECONDIONS").
dico("F", 10, "FECONDITES").
dico("F", 10, "FECULAIENT").
dico("F", 10, "FECULASSES").
dico("F", 10, "FECULENCES").
dico("F", 10, "FECULENTES").
dico("F", 10, "FECULERAIS").
dico("F", 10, "FECULERAIT").
dico("F", 10, "FECULERENT").
dico("F", 10, "FECULERIES").
dico("F", 10, "FECULERIEZ").
dico("F", 10, "FECULERONS").
dico("F", 10, "FECULERONT").
dico("F", 10, "FECULEUSES").
dico("F", 10, "FECULIERES").
dico("F", 10, "FEDERAIENT").
dico("F", 10, "FEDERALISA").
dico("F", 10, "FEDERALISE").
dico("F", 10, "FEDERASSES").
dico("F", 10, "FEDERATEUR").
dico("F", 10, "FEDERATIFS").
dico("F", 10, "FEDERATION").
dico("F", 10, "FEDERATIVE").
dico("F", 10, "FEDERERAIS").
dico("F", 10, "FEDERERAIT").
dico("F", 10, "FEDERERENT").
dico("F", 10, "FEDERERIEZ").
dico("F", 10, "FEDERERONS").
dico("F", 10, "FEDERERONT").
dico("F", 10, "FEIGNAIENT").
dico("F", 10, "FEIGNANTES").
dico("F", 10, "FEIGNIRENT").
dico("F", 10, "FEIGNISSES").
dico("F", 10, "FEINDRIONS").
dico("F", 10, "FEINTAIENT").
dico("F", 10, "FEINTASSES").
dico("F", 10, "FEINTERAIS").
dico("F", 10, "FEINTERAIT").
dico("F", 10, "FEINTERENT").
dico("F", 10, "FEINTERIEZ").
dico("F", 10, "FEINTERONS").
dico("F", 10, "FEINTERONT").
dico("F", 10, "FEINTEUSES").
dico("F", 10, "FELASSIONS").
dico("F", 10, "FELDSPATHS").
dico("F", 10, "FELDWEBELS").
dico("F", 10, "FELERAIENT").
dico("F", 10, "FELIBRIGES").
dico("F", 10, "FELICITAIS").
dico("F", 10, "FELICITAIT").
dico("F", 10, "FELICITANT").
dico("F", 10, "FELICITEES").
dico("F", 10, "FELICITENT").
dico("F", 10, "FELICITERA").
dico("F", 10, "FELICITIEZ").
dico("F", 10, "FELICITONS").
dico("F", 10, "FELLATIONS").
dico("F", 10, "FELLINIENS").
dico("F", 10, "FELQUISTES").
dico("F", 10, "FEMINISAIS").
dico("F", 10, "FEMINISAIT").
dico("F", 10, "FEMINISANT").
dico("F", 10, "FEMINISEES").
dico("F", 10, "FEMINISENT").
dico("F", 10, "FEMINISERA").
dico("F", 10, "FEMINISIEZ").
dico("F", 10, "FEMINISMES").
dico("F", 10, "FEMINISONS").
dico("F", 10, "FEMINISTES").
dico("F", 10, "FEMINITUDE").
dico("F", 10, "FEMMELETTE").
dico("F", 10, "FENDILLAIS").
dico("F", 10, "FENDILLAIT").
dico("F", 10, "FENDILLANT").
dico("F", 10, "FENDILLEES").
dico("F", 10, "FENDILLENT").
dico("F", 10, "FENDILLERA").
dico("F", 10, "FENDILLIEZ").
dico("F", 10, "FENDILLONS").
dico("F", 10, "FENDISSENT").
dico("F", 10, "FENDISSIEZ").
dico("F", 10, "FENDRAIENT").
dico("F", 10, "FENESTRAGE").
dico("F", 10, "FENESTRAIS").
dico("F", 10, "FENESTRAIT").
dico("F", 10, "FENESTRANT").
dico("F", 10, "FENESTREES").
dico("F", 10, "FENESTRENT").
dico("F", 10, "FENESTRERA").
dico("F", 10, "FENESTRIEZ").
dico("F", 10, "FENESTRONS").
dico("F", 10, "FENETRAGES").
dico("F", 10, "FENETRAMES").
dico("F", 10, "FENETRASSE").
dico("F", 10, "FENETRATES").
dico("F", 10, "FENETRERAI").
dico("F", 10, "FENETRERAS").
dico("F", 10, "FENETREREZ").
dico("F", 10, "FENETRIONS").
dico("F", 10, "FENOUILLET").
dico("F", 10, "FEODALISME").
dico("F", 10, "FEODALITES").
dico("F", 10, "FERINGIENS").
dico("F", 10, "FERLASSENT").
dico("F", 10, "FERLASSIEZ").
dico("F", 10, "FERLERIONS").
dico("F", 10, "FERLOUCHES").
dico("F", 10, "FERMASSENT").
dico("F", 10, "FERMASSIEZ").
dico("F", 10, "FERMENTAIS").
dico("F", 10, "FERMENTAIT").
dico("F", 10, "FERMENTANT").
dico("F", 10, "FERMENTEES").
dico("F", 10, "FERMENTENT").
dico("F", 10, "FERMENTERA").
dico("F", 10, "FERMENTEUR").
dico("F", 10, "FERMENTIEZ").
dico("F", 10, "FERMENTONS").
dico("F", 10, "FERMERIONS").
dico("F", 10, "FERMETURES").
dico("F", 10, "FEROCEMENT").
dico("F", 10, "FEROIENNES").
dico("F", 10, "FERRAILLAI").
dico("F", 10, "FERRAILLAS").
dico("F", 10, "FERRAILLAT").
dico("F", 10, "FERRAILLEE").
dico("F", 10, "FERRAILLER").
dico("F", 10, "FERRAILLES").
dico("F", 10, "FERRAILLEZ").
dico("F", 10, "FERRARAISE").
dico("F", 10, "FERRASSENT").
dico("F", 10, "FERRASSIEZ").
dico("F", 10, "FERRATIERS").
dico("F", 10, "FERREMENTS").
dico("F", 10, "FERRERIONS").
dico("F", 10, "FERRETIERS").
dico("F", 10, "FERRONNIER").
dico("F", 10, "FERROTYPIE").
dico("F", 10, "FERROUTAGE").
dico("F", 10, "FERROUTAIS").
dico("F", 10, "FERROUTAIT").
dico("F", 10, "FERROUTANT").
dico("F", 10, "FERROUTEES").
dico("F", 10, "FERROUTENT").
dico("F", 10, "FERROUTERA").
dico("F", 10, "FERROUTIER").
dico("F", 10, "FERROUTIEZ").
dico("F", 10, "FERROUTONS").
dico("F", 10, "FERTILISAI").
dico("F", 10, "FERTILISAS").
dico("F", 10, "FERTILISAT").
dico("F", 10, "FERTILISEE").
dico("F", 10, "FERTILISER").
dico("F", 10, "FERTILISES").
dico("F", 10, "FERTILISEZ").
dico("F", 10, "FERTILITES").
dico("F", 10, "FERVEMMENT").
dico("F", 10, "FESSASSENT").
dico("F", 10, "FESSASSIEZ").
dico("F", 10, "FESSERIONS").
dico("F", 10, "FESTINAMES").
dico("F", 10, "FESTINASSE").
dico("F", 10, "FESTINATES").
dico("F", 10, "FESTINERAI").
dico("F", 10, "FESTINERAS").
dico("F", 10, "FESTINEREZ").
dico("F", 10, "FESTINIONS").
dico("F", 10, "FESTIVITES").
dico("F", 10, "FESTOIERAI").
dico("F", 10, "FESTOIERAS").
dico("F", 10, "FESTOIEREZ").
dico("F", 10, "FESTONNAIS").
dico("F", 10, "FESTONNAIT").
dico("F", 10, "FESTONNANT").
dico("F", 10, "FESTONNEES").
dico("F", 10, "FESTONNENT").
dico("F", 10, "FESTONNERA").
dico("F", 10, "FESTONNIEZ").
dico("F", 10, "FESTONNONS").
dico("F", 10, "FESTOYAMES").
dico("F", 10, "FESTOYASSE").
dico("F", 10, "FESTOYATES").
dico("F", 10, "FESTOYEURS").
dico("F", 10, "FESTOYEUSE").
dico("F", 10, "FESTOYIONS").
dico("F", 10, "FETASSIONS").
dico("F", 10, "FETERAIENT").
dico("F", 10, "FETICHEURS").
dico("F", 10, "FETICHEUSE").
dico("F", 10, "FETICHISAI").
dico("F", 10, "FETICHISAS").
dico("F", 10, "FETICHISAT").
dico("F", 10, "FETICHISEE").
dico("F", 10, "FETICHISER").
dico("F", 10, "FETICHISES").
dico("F", 10, "FETICHISEZ").
dico("F", 10, "FETICHISME").
dico("F", 10, "FETICHISTE").
dico("F", 10, "FETTUCCINE").
dico("F", 10, "FEUDATAIRE").
dico("F", 10, "FEUILLAGEE").
dico("F", 10, "FEUILLAGES").
dico("F", 10, "FEUILLAMES").
dico("F", 10, "FEUILLANTS").
dico("F", 10, "FEUILLARDS").
dico("F", 10, "FEUILLASSE").
dico("F", 10, "FEUILLATES").
dico("F", 10, "FEUILLERAI").
dico("F", 10, "FEUILLERAS").
dico("F", 10, "FEUILLERET").
dico("F", 10, "FEUILLEREZ").
dico("F", 10, "FEUILLETAI").
dico("F", 10, "FEUILLETAS").
dico("F", 10, "FEUILLETAT").
dico("F", 10, "FEUILLETEE").
dico("F", 10, "FEUILLETER").
dico("F", 10, "FEUILLETES").
dico("F", 10, "FEUILLETEZ").
dico("F", 10, "FEUILLETIS").
dico("F", 10, "FEUILLETON").
dico("F", 10, "FEUILLETTE").
dico("F", 10, "FEUILLIONS").
dico("F", 10, "FEUILLURES").
dico("F", 10, "FEULASSENT").
dico("F", 10, "FEULASSIEZ").
dico("F", 10, "FEULEMENTS").
dico("F", 10, "FEULERIONS").
dico("F", 10, "FEUTRABLES").
dico("F", 10, "FEUTRAIENT").
dico("F", 10, "FEUTRANTES").
dico("F", 10, "FEUTRASSES").
dico("F", 10, "FEUTRERAIS").
dico("F", 10, "FEUTRERAIT").
dico("F", 10, "FEUTRERENT").
dico("F", 10, "FEUTRERIEZ").
dico("F", 10, "FEUTRERONS").
dico("F", 10, "FEUTRERONT").
dico("F", 10, "FIABILISAI").
dico("F", 10, "FIABILISAS").
dico("F", 10, "FIABILISAT").
dico("F", 10, "FIABILISEE").
dico("F", 10, "FIABILISER").
dico("F", 10, "FIABILISES").
dico("F", 10, "FIABILISEZ").
dico("F", 10, "FIABILISTE").
dico("F", 10, "FIABILITES").
dico("F", 10, "FIANCAIENT").
dico("F", 10, "FIANCASSES").
dico("F", 10, "FIANCERAIS").
dico("F", 10, "FIANCERAIT").
dico("F", 10, "FIANCERENT").
dico("F", 10, "FIANCERIEZ").
dico("F", 10, "FIANCERONS").
dico("F", 10, "FIANCERONT").
dico("F", 10, "FIBRINEUSE").
dico("F", 10, "FIBROCYTES").
dico("F", 10, "FIBROMYOME").
dico("F", 10, "FIBROSCOPE").
dico("F", 10, "FICELAIENT").
dico("F", 10, "FICELASSES").
dico("F", 10, "FICELERENT").
dico("F", 10, "FICELLERAI").
dico("F", 10, "FICELLERAS").
dico("F", 10, "FICELLEREZ").
dico("F", 10, "FICELLERIE").
dico("F", 10, "FICHASSENT").
dico("F", 10, "FICHASSIEZ").
dico("F", 10, "FICHERIONS").
dico("F", 10, "FICTIONNEL").
dico("F", 10, "FIDELEMENT").
dico("F", 10, "FIDELISAIS").
dico("F", 10, "FIDELISAIT").
dico("F", 10, "FIDELISANT").
dico("F", 10, "FIDELISEES").
dico("F", 10, "FIDELISENT").
dico("F", 10, "FIDELISERA").
dico("F", 10, "FIDELISIEZ").
dico("F", 10, "FIDELISONS").
dico("F", 10, "FIDJIENNES").
dico("F", 10, "FIDUCIAIRE").
dico("F", 10, "FIDUCIANTS").
dico("F", 10, "FIEFFAIENT").
dico("F", 10, "FIEFFASSES").
dico("F", 10, "FIEFFERAIS").
dico("F", 10, "FIEFFERAIT").
dico("F", 10, "FIEFFERENT").
dico("F", 10, "FIEFFERIEZ").
dico("F", 10, "FIEFFERONS").
dico("F", 10, "FIEFFERONT").
dico("F", 10, "FIELLEUSES").
dico("F", 10, "FIENTAIENT").
dico("F", 10, "FIENTASSES").
dico("F", 10, "FIENTERAIS").
dico("F", 10, "FIENTERAIT").
dico("F", 10, "FIENTERENT").
dico("F", 10, "FIENTERIEZ").
dico("F", 10, "FIENTERONS").
dico("F", 10, "FIENTERONT").
dico("F", 10, "FIEVREUSES").
dico("F", 10, "FIGEASSENT").
dico("F", 10, "FIGEASSIEZ").
dico("F", 10, "FIGERAIENT").
dico("F", 10, "FIGNOLAGES").
dico("F", 10, "FIGNOLAMES").
dico("F", 10, "FIGNOLASSE").
dico("F", 10, "FIGNOLATES").
dico("F", 10, "FIGNOLERAI").
dico("F", 10, "FIGNOLERAS").
dico("F", 10, "FIGNOLEREZ").
dico("F", 10, "FIGNOLEURS").
dico("F", 10, "FIGNOLEUSE").
dico("F", 10, "FIGNOLIONS").
dico("F", 10, "FIGUERAIES").
dico("F", 10, "FIGURAIENT").
dico("F", 10, "FIGURANTES").
dico("F", 10, "FIGURASSES").
dico("F", 10, "FIGURATIFS").
dico("F", 10, "FIGURATION").
dico("F", 10, "FIGURATIVE").
dico("F", 10, "FIGUREMENT").
dico("F", 10, "FIGURERAIS").
dico("F", 10, "FIGURERAIT").
dico("F", 10, "FIGURERENT").
dico("F", 10, "FIGURERIEZ").
dico("F", 10, "FIGURERONS").
dico("F", 10, "FIGURERONT").
dico("F", 10, "FIGURISMES").
dico("F", 10, "FIGURISTES").
dico("F", 10, "FILANDIERE").
dico("F", 10, "FILANDIERS").
dico("F", 10, "FILANDREUX").
dico("F", 10, "FILANZANES").
dico("F", 10, "FILARIOSES").
dico("F", 10, "FILASSIONS").
dico("F", 10, "FILERAIENT").
dico("F", 10, "FILETAIENT").
dico("F", 10, "FILETASSES").
dico("F", 10, "FILETERAIS").
dico("F", 10, "FILETERAIT").
dico("F", 10, "FILETERENT").
dico("F", 10, "FILETERIEZ").
dico("F", 10, "FILETERONS").
dico("F", 10, "FILETERONT").
dico("F", 10, "FILIALISAI").
dico("F", 10, "FILIALISAS").
dico("F", 10, "FILIALISAT").
dico("F", 10, "FILIALISEE").
dico("F", 10, "FILIALISER").
dico("F", 10, "FILIALISES").
dico("F", 10, "FILIALISEZ").
dico("F", 10, "FILIATIONS").
dico("F", 10, "FILICINEES").
dico("F", 10, "FILIFORMES").
dico("F", 10, "FILIGRANAI").
dico("F", 10, "FILIGRANAS").
dico("F", 10, "FILIGRANAT").
dico("F", 10, "FILIGRANEE").
dico("F", 10, "FILIGRANER").
dico("F", 10, "FILIGRANES").
dico("F", 10, "FILIGRANEZ").
dico("F", 10, "FILMASSENT").
dico("F", 10, "FILMASSIEZ").
dico("F", 10, "FILMERIONS").
dico("F", 10, "FILMOGENES").
dico("F", 10, "FILMOLOGIE").
dico("F", 10, "FILOCHAMES").
dico("F", 10, "FILOCHASSE").
dico("F", 10, "FILOCHATES").
dico("F", 10, "FILOCHERAI").
dico("F", 10, "FILOCHERAS").
dico("F", 10, "FILOCHEREZ").
dico("F", 10, "FILOCHIONS").
dico("F", 10, "FILOGUIDEE").
dico("F", 10, "FILOGUIDES").
dico("F", 10, "FILONIENNE").
dico("F", 10, "FILOSELLES").
dico("F", 10, "FILOUTAGES").
dico("F", 10, "FILOUTAMES").
dico("F", 10, "FILOUTASSE").
dico("F", 10, "FILOUTATES").
dico("F", 10, "FILOUTERAI").
dico("F", 10, "FILOUTERAS").
dico("F", 10, "FILOUTEREZ").
dico("F", 10, "FILOUTERIE").
dico("F", 10, "FILOUTIONS").
dico("F", 10, "FILTRABLES").
dico("F", 10, "FILTRAIENT").
dico("F", 10, "FILTRANTES").
dico("F", 10, "FILTRASSES").
dico("F", 10, "FILTRATION").
dico("F", 10, "FILTRERAIS").
dico("F", 10, "FILTRERAIT").
dico("F", 10, "FILTRERENT").
dico("F", 10, "FILTRERIEZ").
dico("F", 10, "FILTRERONS").
dico("F", 10, "FILTRERONT").
dico("F", 10, "FINALEMENT").
dico("F", 10, "FINALISAIS").
dico("F", 10, "FINALISAIT").
dico("F", 10, "FINALISANT").
dico("F", 10, "FINALISEES").
dico("F", 10, "FINALISENT").
dico("F", 10, "FINALISERA").
dico("F", 10, "FINALISIEZ").
dico("F", 10, "FINALISMES").
dico("F", 10, "FINALISONS").
dico("F", 10, "FINALISTES").
dico("F", 10, "FINANCABLE").
dico("F", 10, "FINANCAMES").
dico("F", 10, "FINANCASSE").
dico("F", 10, "FINANCATES").
dico("F", 10, "FINANCERAI").
dico("F", 10, "FINANCERAS").
dico("F", 10, "FINANCEREZ").
dico("F", 10, "FINANCIERE").
dico("F", 10, "FINANCIERS").
dico("F", 10, "FINANCIONS").
dico("F", 10, "FINASSAMES").
dico("F", 10, "FINASSASSE").
dico("F", 10, "FINASSATES").
dico("F", 10, "FINASSERAI").
dico("F", 10, "FINASSERAS").
dico("F", 10, "FINASSEREZ").
dico("F", 10, "FINASSERIE").
dico("F", 10, "FINASSEURS").
dico("F", 10, "FINASSEUSE").
dico("F", 10, "FINASSIERE").
dico("F", 10, "FINASSIERS").
dico("F", 10, "FINASSIONS").
dico("F", 10, "FINAUDERIE").
dico("F", 10, "FINIRAIENT").
dico("F", 10, "FINISSAGES").
dico("F", 10, "FINISSANTE").
dico("F", 10, "FINISSANTS").
dico("F", 10, "FINISSEURS").
dico("F", 10, "FINISSEUSE").
dico("F", 10, "FINISSIONS").
dico("F", 10, "FINISSURES").
dico("F", 10, "FINITISMES").
dico("F", 10, "FINLANDAIS").
dico("F", 10, "FIORITURES").
dico("F", 10, "FIRMAMENTS").
dico("F", 10, "FISCALISAI").
dico("F", 10, "FISCALISAS").
dico("F", 10, "FISCALISAT").
dico("F", 10, "FISCALISEE").
dico("F", 10, "FISCALISER").
dico("F", 10, "FISCALISES").
dico("F", 10, "FISCALISEZ").
dico("F", 10, "FISCALISTE").
dico("F", 10, "FISCALITES").
dico("F", 10, "FISSIONNAI").
dico("F", 10, "FISSIONNAS").
dico("F", 10, "FISSIONNAT").
dico("F", 10, "FISSIONNEE").
dico("F", 10, "FISSIONNER").
dico("F", 10, "FISSIONNES").
dico("F", 10, "FISSIONNEZ").
dico("F", 10, "FISSIPARES").
dico("F", 10, "FISSIPEDES").
dico("F", 10, "FISSURAMES").
dico("F", 10, "FISSURASSE").
dico("F", 10, "FISSURATES").
dico("F", 10, "FISSURERAI").
dico("F", 10, "FISSURERAS").
dico("F", 10, "FISSUREREZ").
dico("F", 10, "FISSURIONS").
dico("F", 10, "FISTULAIRE").
dico("F", 10, "FISTULEUSE").
dico("F", 10, "FISTULINES").
dico("F", 10, "FITTASSENT").
dico("F", 10, "FITTASSIEZ").
dico("F", 10, "FITTERIONS").
dico("F", 10, "FIXASSIONS").
dico("F", 10, "FIXATRICES").
dico("F", 10, "FIXERAIENT").
dico("F", 10, "FLACCIDITE").
dico("F", 10, "FLACHERIES").
dico("F", 10, "FLACHEUSES").
dico("F", 10, "FLACONNAGE").
dico("F", 10, "FLACONNIER").
dico("F", 10, "FLAGELLAIS").
dico("F", 10, "FLAGELLAIT").
dico("F", 10, "FLAGELLANT").
dico("F", 10, "FLAGELLEES").
dico("F", 10, "FLAGELLENT").
dico("F", 10, "FLAGELLERA").
dico("F", 10, "FLAGELLIEZ").
dico("F", 10, "FLAGELLONS").
dico("F", 10, "FLAGELLUMS").
dico("F", 10, "FLAGEOLAIS").
dico("F", 10, "FLAGEOLAIT").
dico("F", 10, "FLAGEOLANT").
dico("F", 10, "FLAGEOLENT").
dico("F", 10, "FLAGEOLERA").
dico("F", 10, "FLAGEOLETS").
dico("F", 10, "FLAGEOLIEZ").
dico("F", 10, "FLAGEOLONS").
dico("F", 10, "FLAGORNAIS").
dico("F", 10, "FLAGORNAIT").
dico("F", 10, "FLAGORNANT").
dico("F", 10, "FLAGORNEES").
dico("F", 10, "FLAGORNENT").
dico("F", 10, "FLAGORNERA").
dico("F", 10, "FLAGORNEUR").
dico("F", 10, "FLAGORNIEZ").
dico("F", 10, "FLAGORNONS").
dico("F", 10, "FLAGRANCES").
dico("F", 10, "FLAGRANTES").
dico("F", 10, "FLAIRAIENT").
dico("F", 10, "FLAIRASSES").
dico("F", 10, "FLAIRERAIS").
dico("F", 10, "FLAIRERAIT").
dico("F", 10, "FLAIRERENT").
dico("F", 10, "FLAIRERIEZ").
dico("F", 10, "FLAIRERONS").
dico("F", 10, "FLAIRERONT").
dico("F", 10, "FLAIREUSES").
dico("F", 10, "FLAMBAIENT").
dico("F", 10, "FLAMBANTES").
dico("F", 10, "FLAMBARDES").
dico("F", 10, "FLAMBASSES").
dico("F", 10, "FLAMBEMENT").
dico("F", 10, "FLAMBERAIS").
dico("F", 10, "FLAMBERAIT").
dico("F", 10, "FLAMBERENT").
dico("F", 10, "FLAMBERGES").
dico("F", 10, "FLAMBERIEZ").
dico("F", 10, "FLAMBERONS").
dico("F", 10, "FLAMBERONT").
dico("F", 10, "FLAMBEUSES").
dico("F", 10, "FLAMBOIENT").
dico("F", 10, "FLAMBOIERA").
dico("F", 10, "FLAMBOYAIS").
dico("F", 10, "FLAMBOYAIT").
dico("F", 10, "FLAMBOYANT").
dico("F", 10, "FLAMBOYIEZ").
dico("F", 10, "FLAMBOYONS").
dico("F", 10, "FLAMINGANT").
dico("F", 10, "FLAMMECHES").
dico("F", 10, "FLAMMEROLE").
dico("F", 10, "FLAMMETTES").
dico("F", 10, "FLANASSENT").
dico("F", 10, "FLANASSIEZ").
dico("F", 10, "FLANCHAMES").
dico("F", 10, "FLANCHASSE").
dico("F", 10, "FLANCHATES").
dico("F", 10, "FLANCHERAI").
dico("F", 10, "FLANCHERAS").
dico("F", 10, "FLANCHEREZ").
dico("F", 10, "FLANCHIONS").
dico("F", 10, "FLANCONADE").
dico("F", 10, "FLANDRIENS").
dico("F", 10, "FLANERIONS").
dico("F", 10, "FLANQUAMES").
dico("F", 10, "FLANQUANTE").
dico("F", 10, "FLANQUANTS").
dico("F", 10, "FLANQUASSE").
dico("F", 10, "FLANQUATES").
dico("F", 10, "FLANQUERAI").
dico("F", 10, "FLANQUERAS").
dico("F", 10, "FLANQUEREZ").
dico("F", 10, "FLANQUIONS").
dico("F", 10, "FLASHAIENT").
dico("F", 10, "FLASHANTES").
dico("F", 10, "FLASHASSES").
dico("F", 10, "FLASHERAIS").
dico("F", 10, "FLASHERAIT").
dico("F", 10, "FLASHERENT").
dico("F", 10, "FLASHERIEZ").
dico("F", 10, "FLASHERONS").
dico("F", 10, "FLASHERONT").
dico("F", 10, "FLASHEUSES").
dico("F", 10, "FLATTAIENT").
dico("F", 10, "FLATTASSES").
dico("F", 10, "FLATTERAIS").
dico("F", 10, "FLATTERAIT").
dico("F", 10, "FLATTERENT").
dico("F", 10, "FLATTERIES").
dico("F", 10, "FLATTERIEZ").
dico("F", 10, "FLATTERONS").
dico("F", 10, "FLATTERONT").
dico("F", 10, "FLATTEUSES").
dico("F", 10, "FLATULENCE").
dico("F", 10, "FLATULENTE").
dico("F", 10, "FLATULENTS").
dico("F", 10, "FLATUOSITE").
dico("F", 10, "FLAVESCENT").
dico("F", 10, "FLECHAIENT").
dico("F", 10, "FLECHASSES").
dico("F", 10, "FLECHERAIS").
dico("F", 10, "FLECHERAIT").
dico("F", 10, "FLECHERENT").
dico("F", 10, "FLECHERIEZ").
dico("F", 10, "FLECHERONS").
dico("F", 10, "FLECHERONT").
dico("F", 10, "FLECHETTES").
dico("F", 10, "FLECHIRAIS").
dico("F", 10, "FLECHIRAIT").
dico("F", 10, "FLECHIRENT").
dico("F", 10, "FLECHIRIEZ").
dico("F", 10, "FLECHIRONS").
dico("F", 10, "FLECHIRONT").
dico("F", 10, "FLECHISSES").
dico("F", 10, "FLECHISSEZ").
dico("F", 10, "FLEMMARDAI").
dico("F", 10, "FLEMMARDAS").
dico("F", 10, "FLEMMARDAT").
dico("F", 10, "FLEMMARDER").
dico("F", 10, "FLEMMARDES").
dico("F", 10, "FLEMMARDEZ").
dico("F", 10, "FLETRIRAIS").
dico("F", 10, "FLETRIRAIT").
dico("F", 10, "FLETRIRENT").
dico("F", 10, "FLETRIRIEZ").
dico("F", 10, "FLETRIRONS").
dico("F", 10, "FLETRIRONT").
dico("F", 10, "FLETRISSES").
dico("F", 10, "FLETRISSEZ").
dico("F", 10, "FLEURAIENT").
dico("F", 10, "FLEURAISON").
dico("F", 10, "FLEURASSES").
dico("F", 10, "FLEURERAIS").
dico("F", 10, "FLEURERAIT").
dico("F", 10, "FLEURERENT").
dico("F", 10, "FLEURERIEZ").
dico("F", 10, "FLEURERONS").
dico("F", 10, "FLEURERONT").
dico("F", 10, "FLEURETAIS").
dico("F", 10, "FLEURETAIT").
dico("F", 10, "FLEURETANT").
dico("F", 10, "FLEURETIEZ").
dico("F", 10, "FLEURETONS").
dico("F", 10, "FLEURETTES").
dico("F", 10, "FLEURIRAIS").
dico("F", 10, "FLEURIRAIT").
dico("F", 10, "FLEURIRENT").
dico("F", 10, "FLEURIRIEZ").
dico("F", 10, "FLEURIRONS").
dico("F", 10, "FLEURIRONT").
dico("F", 10, "FLEURISSES").
dico("F", 10, "FLEURISSEZ").
dico("F", 10, "FLEURISTES").
dico("F", 10, "FLEURONNEE").
dico("F", 10, "FLEURONNES").
dico("F", 10, "FLEXIONNEL").
dico("F", 10, "FLEXUEUSES").
dico("F", 10, "FLEXUOSITE").
dico("F", 10, "FLIBUSTAIS").
dico("F", 10, "FLIBUSTAIT").
dico("F", 10, "FLIBUSTANT").
dico("F", 10, "FLIBUSTEES").
dico("F", 10, "FLIBUSTENT").
dico("F", 10, "FLIBUSTERA").
dico("F", 10, "FLIBUSTIER").
dico("F", 10, "FLIBUSTIEZ").
dico("F", 10, "FLIBUSTONS").
dico("F", 10, "FLICAILLES").
dico("F", 10, "FLINGUAMES").
dico("F", 10, "FLINGUASSE").
dico("F", 10, "FLINGUATES").
dico("F", 10, "FLINGUERAI").
dico("F", 10, "FLINGUERAS").
dico("F", 10, "FLINGUEREZ").
dico("F", 10, "FLINGUEURS").
dico("F", 10, "FLINGUEUSE").
dico("F", 10, "FLINGUIONS").
dico("F", 10, "FLIPPAIENT").
dico("F", 10, "FLIPPANTES").
dico("F", 10, "FLIPPASSES").
dico("F", 10, "FLIPPERAIS").
dico("F", 10, "FLIPPERAIT").
dico("F", 10, "FLIPPERENT").
dico("F", 10, "FLIPPERIEZ").
dico("F", 10, "FLIPPERONS").
dico("F", 10, "FLIPPERONT").
dico("F", 10, "FLIQUAIENT").
dico("F", 10, "FLIQUASSES").
dico("F", 10, "FLIQUERAIS").
dico("F", 10, "FLIQUERAIT").
dico("F", 10, "FLIQUERENT").
dico("F", 10, "FLIQUERIEZ").
dico("F", 10, "FLIQUERONS").
dico("F", 10, "FLIQUERONT").
dico("F", 10, "FLIQUESSES").
dico("F", 10, "FLIQUETTES").
dico("F", 10, "FLIRTAIENT").
dico("F", 10, "FLIRTASSES").
dico("F", 10, "FLIRTERAIS").
dico("F", 10, "FLIRTERAIT").
dico("F", 10, "FLIRTERENT").
dico("F", 10, "FLIRTERIEZ").
dico("F", 10, "FLIRTERONS").
dico("F", 10, "FLIRTERONT").
dico("F", 10, "FLIRTEUSES").
dico("F", 10, "FLOCONNAIS").
dico("F", 10, "FLOCONNAIT").
dico("F", 10, "FLOCONNANT").
dico("F", 10, "FLOCONNENT").
dico("F", 10, "FLOCONNERA").
dico("F", 10, "FLOCONNEUX").
dico("F", 10, "FLOCONNIEZ").
dico("F", 10, "FLOCONNONS").
dico("F", 10, "FLOCULAMES").
dico("F", 10, "FLOCULANTS").
dico("F", 10, "FLOCULASSE").
dico("F", 10, "FLOCULATES").
dico("F", 10, "FLOCULERAI").
dico("F", 10, "FLOCULERAS").
dico("F", 10, "FLOCULEREZ").
dico("F", 10, "FLOCULIONS").
dico("F", 10, "FLOQUAIENT").
dico("F", 10, "FLOQUASSES").
dico("F", 10, "FLOQUERAIS").
dico("F", 10, "FLOQUERAIT").
dico("F", 10, "FLOQUERENT").
dico("F", 10, "FLOQUERIEZ").
dico("F", 10, "FLOQUERONS").
dico("F", 10, "FLOQUERONT").
dico("F", 10, "FLORAISONS").
dico("F", 10, "FLORENTINE").
dico("F", 10, "FLORENTINS").
dico("F", 10, "FLORIBONDE").
dico("F", 10, "FLORIBONDS").
dico("F", 10, "FLORICOLES").
dico("F", 10, "FLORIFERES").
dico("F", 10, "FLORILEGES").
dico("F", 10, "FLORISSAIS").
dico("F", 10, "FLORISSAIT").
dico("F", 10, "FLORISSANT").
dico("F", 10, "FLORISSIEZ").
dico("F", 10, "FLOSCULEUX").
dico("F", 10, "FLOTTABLES").
dico("F", 10, "FLOTTAIENT").
dico("F", 10, "FLOTTAISON").
dico("F", 10, "FLOTTANTES").
dico("F", 10, "FLOTTARDES").
dico("F", 10, "FLOTTASSES").
dico("F", 10, "FLOTTATION").
dico("F", 10, "FLOTTEMENT").
dico("F", 10, "FLOTTERAIS").
dico("F", 10, "FLOTTERAIT").
dico("F", 10, "FLOTTERENT").
dico("F", 10, "FLOTTERIEZ").
dico("F", 10, "FLOTTERONS").
dico("F", 10, "FLOTTERONT").
dico("F", 10, "FLOTTILLES").
dico("F", 10, "FLOUASSENT").
dico("F", 10, "FLOUASSIEZ").
dico("F", 10, "FLOUERIONS").
dico("F", 10, "FLUASSIONS").
dico("F", 10, "FLUATATION").
dico("F", 10, "FLUCTUAMES").
dico("F", 10, "FLUCTUANTE").
dico("F", 10, "FLUCTUANTS").
dico("F", 10, "FLUCTUASSE").
dico("F", 10, "FLUCTUATES").
dico("F", 10, "FLUCTUERAI").
dico("F", 10, "FLUCTUERAS").
dico("F", 10, "FLUCTUEREZ").
dico("F", 10, "FLUCTUIONS").
dico("F", 10, "FLUERAIENT").
dico("F", 10, "FLUIDIFIAI").
dico("F", 10, "FLUIDIFIAS").
dico("F", 10, "FLUIDIFIAT").
dico("F", 10, "FLUIDIFIEE").
dico("F", 10, "FLUIDIFIER").
dico("F", 10, "FLUIDIFIES").
dico("F", 10, "FLUIDIFIEZ").
dico("F", 10, "FLUIDIQUES").
dico("F", 10, "FLUIDISAIS").
dico("F", 10, "FLUIDISAIT").
dico("F", 10, "FLUIDISANT").
dico("F", 10, "FLUIDISEES").
dico("F", 10, "FLUIDISENT").
dico("F", 10, "FLUIDISERA").
dico("F", 10, "FLUIDISIEZ").
dico("F", 10, "FLUIDISONS").
dico("F", 10, "FLUORATION").
dico("F", 10, "FLUTASSENT").
dico("F", 10, "FLUTASSIEZ").
dico("F", 10, "FLUTERIONS").
dico("F", 10, "FLUVIATILE").
dico("F", 10, "FLUXASSENT").
dico("F", 10, "FLUXASSIEZ").
dico("F", 10, "FLUXERIONS").
dico("F", 10, "FLUXMETRES").
dico("F", 10, "FOCALISAIS").
dico("F", 10, "FOCALISAIT").
dico("F", 10, "FOCALISANT").
dico("F", 10, "FOCALISEES").
dico("F", 10, "FOCALISENT").
dico("F", 10, "FOCALISERA").
dico("F", 10, "FOCALISIEZ").
dico("F", 10, "FOCALISONS").
dico("F", 10, "FOCOMETRES").
dico("F", 10, "FOEHNAIENT").
dico("F", 10, "FOEHNASSES").
dico("F", 10, "FOEHNERAIS").
dico("F", 10, "FOEHNERAIT").
dico("F", 10, "FOEHNERENT").
dico("F", 10, "FOEHNERIEZ").
dico("F", 10, "FOEHNERONS").
dico("F", 10, "FOEHNERONT").
dico("F", 10, "FOETICIDES").
dico("F", 10, "FOETOLOGIE").
dico("F", 10, "FOHNASSENT").
dico("F", 10, "FOHNASSIEZ").
dico("F", 10, "FOHNERIONS").
dico("F", 10, "FOIRASSENT").
dico("F", 10, "FOIRASSIEZ").
dico("F", 10, "FOIRERIONS").
dico("F", 10, "FOISONNAIS").
dico("F", 10, "FOISONNAIT").
dico("F", 10, "FOISONNANT").
dico("F", 10, "FOISONNENT").
dico("F", 10, "FOISONNERA").
dico("F", 10, "FOISONNIEZ").
dico("F", 10, "FOISONNONS").
dico("F", 10, "FOLATRAMES").
dico("F", 10, "FOLATRASSE").
dico("F", 10, "FOLATRATES").
dico("F", 10, "FOLATRERAI").
dico("F", 10, "FOLATRERAS").
dico("F", 10, "FOLATREREZ").
dico("F", 10, "FOLATRERIE").
dico("F", 10, "FOLATRIONS").
dico("F", 10, "FOLDINGUES").
dico("F", 10, "FOLIATIONS").
dico("F", 10, "FOLICHONNA").
dico("F", 10, "FOLICHONNE").
dico("F", 10, "FOLIOTAGES").
dico("F", 10, "FOLIOTAMES").
dico("F", 10, "FOLIOTASSE").
dico("F", 10, "FOLIOTATES").
dico("F", 10, "FOLIOTERAI").
dico("F", 10, "FOLIOTERAS").
dico("F", 10, "FOLIOTEREZ").
dico("F", 10, "FOLIOTEURS").
dico("F", 10, "FOLIOTEUSE").
dico("F", 10, "FOLIOTIONS").
dico("F", 10, "FOLKLORISA").
dico("F", 10, "FOLKLORISE").
dico("F", 10, "FOLLICULES").
dico("F", 10, "FOMENTAMES").
dico("F", 10, "FOMENTASSE").
dico("F", 10, "FOMENTATES").
dico("F", 10, "FOMENTERAI").
dico("F", 10, "FOMENTERAS").
dico("F", 10, "FOMENTEREZ").
dico("F", 10, "FOMENTEURS").
dico("F", 10, "FOMENTEUSE").
dico("F", 10, "FOMENTIONS").
dico("F", 10, "FONCAILLES").
dico("F", 10, "FONCASSENT").
dico("F", 10, "FONCASSIEZ").
dico("F", 10, "FONCEMENTS").
dico("F", 10, "FONCERIONS").
dico("F", 10, "FONCTIONNA").
dico("F", 10, "FONCTIONNE").
dico("F", 10, "FONDASSENT").
dico("F", 10, "FONDASSIEZ").
dico("F", 10, "FONDATEURS").
dico("F", 10, "FONDATIONS").
dico("F", 10, "FONDATRICE").
dico("F", 10, "FONDEMENTS").
dico("F", 10, "FONDERIONS").
dico("F", 10, "FONDISSENT").
dico("F", 10, "FONDISSIEZ").
dico("F", 10, "FONDRAIENT").
dico("F", 10, "FONDRIERES").
dico("F", 10, "FONGICIDES").
dico("F", 10, "FONGIFORME").
dico("F", 10, "FONGOSITES").
dico("F", 10, "FONGUEUSES").
dico("F", 10, "FONTAINIER").
dico("F", 10, "FONTANELLE").
dico("F", 10, "FORAMINEES").
dico("F", 10, "FORASSIONS").
dico("F", 10, "FORCASSENT").
dico("F", 10, "FORCASSIEZ").
dico("F", 10, "FORCEMENTS").
dico("F", 10, "FORCERIONS").
dico("F", 10, "FORCIRIONS").
dico("F", 10, "FORCISSAIS").
dico("F", 10, "FORCISSAIT").
dico("F", 10, "FORCISSANT").
dico("F", 10, "FORCISSENT").
dico("F", 10, "FORCISSIEZ").
dico("F", 10, "FORCISSONS").
dico("F", 10, "FORCLUSION").
dico("F", 10, "FORERAIENT").
dico("F", 10, "FORESTAGES").
dico("F", 10, "FORESTERIE").
dico("F", 10, "FORESTIERE").
dico("F", 10, "FORESTIERS").
dico("F", 10, "FOREZIENNE").
dico("F", 10, "FORFAITISA").
dico("F", 10, "FORFAITISE").
dico("F", 10, "FORFAITURE").
dico("F", 10, "FORFICULES").
dico("F", 10, "FORGEABLES").
dico("F", 10, "FORGEAIENT").
dico("F", 10, "FORGEASSES").
dico("F", 10, "FORGERIONS").
dico("F", 10, "FORJETAMES").
dico("F", 10, "FORJETASSE").
dico("F", 10, "FORJETATES").
dico("F", 10, "FORJETIONS").
dico("F", 10, "FORJETTENT").
dico("F", 10, "FORJETTERA").
dico("F", 10, "FORLANCAIS").
dico("F", 10, "FORLANCAIT").
dico("F", 10, "FORLANCANT").
dico("F", 10, "FORLANCEES").
dico("F", 10, "FORLANCENT").
dico("F", 10, "FORLANCERA").
dico("F", 10, "FORLANCIEZ").
dico("F", 10, "FORLANCONS").
dico("F", 10, "FORLIGNAIS").
dico("F", 10, "FORLIGNAIT").
dico("F", 10, "FORLIGNANT").
dico("F", 10, "FORLIGNENT").
dico("F", 10, "FORLIGNERA").
dico("F", 10, "FORLIGNIEZ").
dico("F", 10, "FORLIGNONS").
dico("F", 10, "FORLONGEAI").
dico("F", 10, "FORLONGEAS").
dico("F", 10, "FORLONGEAT").
dico("F", 10, "FORLONGEES").
dico("F", 10, "FORLONGENT").
dico("F", 10, "FORLONGERA").
dico("F", 10, "FORLONGIEZ").
dico("F", 10, "FORMALISAI").
dico("F", 10, "FORMALISAS").
dico("F", 10, "FORMALISAT").
dico("F", 10, "FORMALISEE").
dico("F", 10, "FORMALISER").
dico("F", 10, "FORMALISES").
dico("F", 10, "FORMALISEZ").
dico("F", 10, "FORMALISME").
dico("F", 10, "FORMALISTE").
dico("F", 10, "FORMALITES").
dico("F", 10, "FORMARIAGE").
dico("F", 10, "FORMASSENT").
dico("F", 10, "FORMASSIEZ").
dico("F", 10, "FORMATAGES").
dico("F", 10, "FORMATAMES").
dico("F", 10, "FORMATASSE").
dico("F", 10, "FORMATATES").
dico("F", 10, "FORMATERAI").
dico("F", 10, "FORMATERAS").
dico("F", 10, "FORMATEREZ").
dico("F", 10, "FORMATEURS").
dico("F", 10, "FORMATIONS").
dico("F", 10, "FORMATIVES").
dico("F", 10, "FORMATRICE").
dico("F", 10, "FORMERIONS").
dico("F", 10, "FORMICANTE").
dico("F", 10, "FORMICANTS").
dico("F", 10, "FORMICIDES").
dico("F", 10, "FORMIDABLE").
dico("F", 10, "FORMOLAGES").
dico("F", 10, "FORMOLAMES").
dico("F", 10, "FORMOLASSE").
dico("F", 10, "FORMOLATES").
dico("F", 10, "FORMOLERAI").
dico("F", 10, "FORMOLERAS").
dico("F", 10, "FORMOLEREZ").
dico("F", 10, "FORMOLIONS").
dico("F", 10, "FORMOSANES").
dico("F", 10, "FORMULABLE").
dico("F", 10, "FORMULAIRE").
dico("F", 10, "FORMULAMES").
dico("F", 10, "FORMULASSE").
dico("F", 10, "FORMULATES").
dico("F", 10, "FORMULERAI").
dico("F", 10, "FORMULERAS").
dico("F", 10, "FORMULEREZ").
dico("F", 10, "FORMULIONS").
dico("F", 10, "FORNIQUAIS").
dico("F", 10, "FORNIQUAIT").
dico("F", 10, "FORNIQUANT").
dico("F", 10, "FORNIQUENT").
dico("F", 10, "FORNIQUERA").
dico("F", 10, "FORNIQUIEZ").
dico("F", 10, "FORNIQUONS").
dico("F", 10, "FORSYTHIAS").
dico("F", 10, "FORTERESSE").
dico("F", 10, "FORTIFIAIS").
dico("F", 10, "FORTIFIAIT").
dico("F", 10, "FORTIFIANT").
dico("F", 10, "FORTIFIEES").
dico("F", 10, "FORTIFIENT").
dico("F", 10, "FORTIFIERA").
dico("F", 10, "FORTIFIIEZ").
dico("F", 10, "FORTIFIONS").
dico("F", 10, "FORTISSIMO").
dico("F", 10, "FORTRAITES").
dico("F", 10, "FOSSILISAI").
dico("F", 10, "FOSSILISAS").
dico("F", 10, "FOSSILISAT").
dico("F", 10, "FOSSILISEE").
dico("F", 10, "FOSSILISER").
dico("F", 10, "FOSSILISES").
dico("F", 10, "FOSSILISEZ").
dico("F", 10, "FOSSOIERAI").
dico("F", 10, "FOSSOIERAS").
dico("F", 10, "FOSSOIEREZ").
dico("F", 10, "FOSSORIERS").
dico("F", 10, "FOSSOYAGES").
dico("F", 10, "FOSSOYAMES").
dico("F", 10, "FOSSOYASSE").
dico("F", 10, "FOSSOYATES").
dico("F", 10, "FOSSOYEURS").
dico("F", 10, "FOSSOYEUSE").
dico("F", 10, "FOSSOYIONS").
dico("F", 10, "FOUAILLAIS").
dico("F", 10, "FOUAILLAIT").
dico("F", 10, "FOUAILLANT").
dico("F", 10, "FOUAILLEES").
dico("F", 10, "FOUAILLENT").
dico("F", 10, "FOUAILLERA").
dico("F", 10, "FOUAILLIEZ").
dico("F", 10, "FOUAILLONS").
dico("F", 10, "FOUDROIENT").
dico("F", 10, "FOUDROIERA").
dico("F", 10, "FOUDROYAGE").
dico("F", 10, "FOUDROYAIS").
dico("F", 10, "FOUDROYAIT").
dico("F", 10, "FOUDROYANT").
dico("F", 10, "FOUDROYEES").
dico("F", 10, "FOUDROYIEZ").
dico("F", 10, "FOUDROYONS").
dico("F", 10, "FOUETTAMES").
dico("F", 10, "FOUETTARDE").
dico("F", 10, "FOUETTARDS").
dico("F", 10, "FOUETTASSE").
dico("F", 10, "FOUETTATES").
dico("F", 10, "FOUETTERAI").
dico("F", 10, "FOUETTERAS").
dico("F", 10, "FOUETTEREZ").
dico("F", 10, "FOUETTEURS").
dico("F", 10, "FOUETTIONS").
dico("F", 10, "FOUGEAIENT").
dico("F", 10, "FOUGEASSES").
dico("F", 10, "FOUGERAIES").
dico("F", 10, "FOUGERIONS").
dico("F", 10, "FOUGEROLES").
dico("F", 10, "FOUGUEUSES").
dico("F", 10, "FOUILLAGES").
dico("F", 10, "FOUILLAMES").
dico("F", 10, "FOUILLASSE").
dico("F", 10, "FOUILLATES").
dico("F", 10, "FOUILLERAI").
dico("F", 10, "FOUILLERAS").
dico("F", 10, "FOUILLEREZ").
dico("F", 10, "FOUILLEURS").
dico("F", 10, "FOUILLEUSE").
dico("F", 10, "FOUILLIONS").
dico("F", 10, "FOUINAIENT").
dico("F", 10, "FOUINARDES").
dico("F", 10, "FOUINASSES").
dico("F", 10, "FOUINERAIS").
dico("F", 10, "FOUINERAIT").
dico("F", 10, "FOUINERENT").
dico("F", 10, "FOUINERIEZ").
dico("F", 10, "FOUINERONS").
dico("F", 10, "FOUINERONT").
dico("F", 10, "FOUINEUSES").
dico("F", 10, "FOUIRAIENT").
dico("F", 10, "FOUISSAGES").
dico("F", 10, "FOUISSEURS").
dico("F", 10, "FOUISSEUSE").
dico("F", 10, "FOUISSIONS").
dico("F", 10, "FOULASSENT").
dico("F", 10, "FOULASSIEZ").
dico("F", 10, "FOULERIONS").
dico("F", 10, "FOULONNAGE").
dico("F", 10, "FOULONNAIS").
dico("F", 10, "FOULONNAIT").
dico("F", 10, "FOULONNANT").
dico("F", 10, "FOULONNEES").
dico("F", 10, "FOULONNENT").
dico("F", 10, "FOULONNERA").
dico("F", 10, "FOULONNIER").
dico("F", 10, "FOULONNIEZ").
dico("F", 10, "FOULONNONS").
dico("F", 10, "FOULTITUDE").
dico("F", 10, "FOURBERIES").
dico("F", 10, "FOURBIRAIS").
dico("F", 10, "FOURBIRAIT").
dico("F", 10, "FOURBIRENT").
dico("F", 10, "FOURBIRIEZ").
dico("F", 10, "FOURBIRONS").
dico("F", 10, "FOURBIRONT").
dico("F", 10, "FOURBISSES").
dico("F", 10, "FOURBISSEZ").
dico("F", 10, "FOURCHAMES").
dico("F", 10, "FOURCHASSE").
dico("F", 10, "FOURCHATES").
dico("F", 10, "FOURCHERAI").
dico("F", 10, "FOURCHERAS").
dico("F", 10, "FOURCHEREZ").
dico("F", 10, "FOURCHETEE").
dico("F", 10, "FOURCHETTE").
dico("F", 10, "FOURCHIONS").
dico("F", 10, "FOURGONNAI").
dico("F", 10, "FOURGONNAS").
dico("F", 10, "FOURGONNAT").
dico("F", 10, "FOURGONNEE").
dico("F", 10, "FOURGONNER").
dico("F", 10, "FOURGONNES").
dico("F", 10, "FOURGONNEZ").
dico("F", 10, "FOURGUAMES").
dico("F", 10, "FOURGUASSE").
dico("F", 10, "FOURGUATES").
dico("F", 10, "FOURGUERAI").
dico("F", 10, "FOURGUERAS").
dico("F", 10, "FOURGUEREZ").
dico("F", 10, "FOURGUIONS").
dico("F", 10, "FOURMILIER").
dico("F", 10, "FOURMILION").
dico("F", 10, "FOURMILLAI").
dico("F", 10, "FOURMILLAS").
dico("F", 10, "FOURMILLAT").
dico("F", 10, "FOURMILLER").
dico("F", 10, "FOURMILLES").
dico("F", 10, "FOURMILLEZ").
dico("F", 10, "FOURNAISES").
dico("F", 10, "FOURNIERES").
dico("F", 10, "FOURNIMENT").
dico("F", 10, "FOURNIRAIS").
dico("F", 10, "FOURNIRAIT").
dico("F", 10, "FOURNIRENT").
dico("F", 10, "FOURNIRIEZ").
dico("F", 10, "FOURNIRONS").
dico("F", 10, "FOURNIRONT").
dico("F", 10, "FOURNISSES").
dico("F", 10, "FOURNISSEZ").
dico("F", 10, "FOURNITURE").
dico("F", 10, "FOURRAGEAI").
dico("F", 10, "FOURRAGEAS").
dico("F", 10, "FOURRAGEAT").
dico("F", 10, "FOURRAGEES").
dico("F", 10, "FOURRAGENT").
dico("F", 10, "FOURRAGERA").
dico("F", 10, "FOURRAGERE").
dico("F", 10, "FOURRAGERS").
dico("F", 10, "FOURRAGEUR").
dico("F", 10, "FOURRAGIEZ").
dico("F", 10, "FOURRAIENT").
dico("F", 10, "FOURRASSES").
dico("F", 10, "FOURRERAIS").
dico("F", 10, "FOURRERAIT").
dico("F", 10, "FOURRERENT").
dico("F", 10, "FOURRERIEZ").
dico("F", 10, "FOURRERONS").
dico("F", 10, "FOURRERONT").
dico("F", 10, "FOURREUSES").
dico("F", 10, "FOURRIERES").
dico("F", 10, "FOURVOIENT").
dico("F", 10, "FOURVOIERA").
dico("F", 10, "FOURVOYAIS").
dico("F", 10, "FOURVOYAIT").
dico("F", 10, "FOURVOYANT").
dico("F", 10, "FOURVOYEES").
dico("F", 10, "FOURVOYIEZ").
dico("F", 10, "FOURVOYONS").
dico("F", 10, "FOUTIMASSA").
dico("F", 10, "FOUTIMASSE").
dico("F", 10, "FOUTRAIENT").
dico("F", 10, "FOUTRAQUES").
dico("F", 10, "FOUTREMENT").
dico("F", 10, "FOUTRIQUET").
dico("F", 10, "FOYALAISES").
dico("F", 10, "FRACASSAIS").
dico("F", 10, "FRACASSAIT").
dico("F", 10, "FRACASSANT").
dico("F", 10, "FRACASSEES").
dico("F", 10, "FRACASSENT").
dico("F", 10, "FRACASSERA").
dico("F", 10, "FRACASSIEZ").
dico("F", 10, "FRACASSONS").
dico("F", 10, "FRACTIONNA").
dico("F", 10, "FRACTIONNE").
dico("F", 10, "FRACTURAIS").
dico("F", 10, "FRACTURAIT").
dico("F", 10, "FRACTURANT").
dico("F", 10, "FRACTUREES").
dico("F", 10, "FRACTURENT").
dico("F", 10, "FRACTURERA").
dico("F", 10, "FRACTURIEZ").
dico("F", 10, "FRACTURONS").
dico("F", 10, "FRAGILISAI").
dico("F", 10, "FRAGILISAS").
dico("F", 10, "FRAGILISAT").
dico("F", 10, "FRAGILISEE").
dico("F", 10, "FRAGILISER").
dico("F", 10, "FRAGILISES").
dico("F", 10, "FRAGILISEZ").
dico("F", 10, "FRAGILITES").
dico("F", 10, "FRAGMENTAI").
dico("F", 10, "FRAGMENTAS").
dico("F", 10, "FRAGMENTAT").
dico("F", 10, "FRAGMENTEE").
dico("F", 10, "FRAGMENTER").
dico("F", 10, "FRAGMENTES").
dico("F", 10, "FRAGMENTEZ").
dico("F", 10, "FRAGRANCES").
dico("F", 10, "FRAGRANTES").
dico("F", 10, "FRAICHEURS").
dico("F", 10, "FRAICHIMES").
dico("F", 10, "FRAICHIRAI").
dico("F", 10, "FRAICHIRAS").
dico("F", 10, "FRAICHIREZ").
dico("F", 10, "FRAICHISSE").
dico("F", 10, "FRAICHITES").
dico("F", 10, "FRAIERIONS").
dico("F", 10, "FRAISAIENT").
dico("F", 10, "FRAISASSES").
dico("F", 10, "FRAISERAIE").
dico("F", 10, "FRAISERAIS").
dico("F", 10, "FRAISERAIT").
dico("F", 10, "FRAISERENT").
dico("F", 10, "FRAISERIEZ").
dico("F", 10, "FRAISERONS").
dico("F", 10, "FRAISERONT").
dico("F", 10, "FRAISETTES").
dico("F", 10, "FRAISEUSES").
dico("F", 10, "FRAISIERES").
dico("F", 10, "FRAMBOISAI").
dico("F", 10, "FRAMBOISAS").
dico("F", 10, "FRAMBOISAT").
dico("F", 10, "FRAMBOISEE").
dico("F", 10, "FRAMBOISER").
dico("F", 10, "FRAMBOISES").
dico("F", 10, "FRAMBOISEZ").
dico("F", 10, "FRANCAISES").
dico("F", 10, "FRANCFORTS").
dico("F", 10, "FRANCHIMES").
dico("F", 10, "FRANCHIRAI").
dico("F", 10, "FRANCHIRAS").
dico("F", 10, "FRANCHIREZ").
dico("F", 10, "FRANCHISAI").
dico("F", 10, "FRANCHISAS").
dico("F", 10, "FRANCHISAT").
dico("F", 10, "FRANCHISEE").
dico("F", 10, "FRANCHISER").
dico("F", 10, "FRANCHISES").
dico("F", 10, "FRANCHISEZ").
dico("F", 10, "FRANCHISSE").
dico("F", 10, "FRANCHITES").
dico("F", 10, "FRANCIENNE").
dico("F", 10, "FRANCILIEN").
dico("F", 10, "FRANCIQUES").
dico("F", 10, "FRANCISAIS").
dico("F", 10, "FRANCISAIT").
dico("F", 10, "FRANCISANT").
dico("F", 10, "FRANCISEES").
dico("F", 10, "FRANCISENT").
dico("F", 10, "FRANCISERA").
dico("F", 10, "FRANCISIEZ").
dico("F", 10, "FRANCISONS").
dico("F", 10, "FRANCISQUE").
dico("F", 10, "FRANCISTES").
dico("F", 10, "FRANCOLINS").
dico("F", 10, "FRANGEAMES").
dico("F", 10, "FRANGEANTE").
dico("F", 10, "FRANGEANTS").
dico("F", 10, "FRANGEASSE").
dico("F", 10, "FRANGEATES").
dico("F", 10, "FRANGERAIS").
dico("F", 10, "FRANGERAIT").
dico("F", 10, "FRANGERENT").
dico("F", 10, "FRANGERIEZ").
dico("F", 10, "FRANGERONS").
dico("F", 10, "FRANGERONT").
dico("F", 10, "FRANGIPANE").
dico("F", 10, "FRANGLAISE").
dico("F", 10, "FRANQUETTE").
dico("F", 10, "FRANQUISME").
dico("F", 10, "FRANQUISTE").
dico("F", 10, "FRAPPAIENT").
dico("F", 10, "FRAPPANTES").
dico("F", 10, "FRAPPASSES").
dico("F", 10, "FRAPPEMENT").
dico("F", 10, "FRAPPERAIS").
dico("F", 10, "FRAPPERAIT").
dico("F", 10, "FRAPPERENT").
dico("F", 10, "FRAPPERIEZ").
dico("F", 10, "FRAPPERONS").
dico("F", 10, "FRAPPERONT").
dico("F", 10, "FRAPPEUSES").
dico("F", 10, "FRASASSENT").
dico("F", 10, "FRASASSIEZ").
dico("F", 10, "FRASERIONS").
dico("F", 10, "FRATERNELS").
dico("F", 10, "FRATERNISA").
dico("F", 10, "FRATERNISE").
dico("F", 10, "FRATERNITE").
dico("F", 10, "FRATRICIDE").
dico("F", 10, "FRAUDAIENT").
dico("F", 10, "FRAUDASSES").
dico("F", 10, "FRAUDERAIS").
dico("F", 10, "FRAUDERAIT").
dico("F", 10, "FRAUDERENT").
dico("F", 10, "FRAUDERIEZ").
dico("F", 10, "FRAUDERONS").
dico("F", 10, "FRAUDERONT").
dico("F", 10, "FRAUDEUSES").
dico("F", 10, "FRAUDULEUX").
dico("F", 10, "FRAXINELLE").
dico("F", 10, "FRAYASSENT").
dico("F", 10, "FRAYASSIEZ").
dico("F", 10, "FRAYEMENTS").
dico("F", 10, "FRAYERIONS").
dico("F", 10, "FREDONNAIS").
dico("F", 10, "FREDONNAIT").
dico("F", 10, "FREDONNANT").
dico("F", 10, "FREDONNEES").
dico("F", 10, "FREDONNENT").
dico("F", 10, "FREDONNERA").
dico("F", 10, "FREDONNIEZ").
dico("F", 10, "FREDONNONS").
dico("F", 10, "FREGATAGES").
dico("F", 10, "FREGATAMES").
dico("F", 10, "FREGATASSE").
dico("F", 10, "FREGATATES").
dico("F", 10, "FREGATERAI").
dico("F", 10, "FREGATERAS").
dico("F", 10, "FREGATEREZ").
dico("F", 10, "FREGATIONS").
dico("F", 10, "FREINAIENT").
dico("F", 10, "FREINASSES").
dico("F", 10, "FREINERAIS").
dico("F", 10, "FREINERAIT").
dico("F", 10, "FREINERENT").
dico("F", 10, "FREINERIEZ").
dico("F", 10, "FREINERONS").
dico("F", 10, "FREINERONT").
dico("F", 10, "FREINEUSES").
dico("F", 10, "FRELATAGES").
dico("F", 10, "FRELATAMES").
dico("F", 10, "FRELATASSE").
dico("F", 10, "FRELATATES").
dico("F", 10, "FRELATERAI").
dico("F", 10, "FRELATERAS").
dico("F", 10, "FRELATEREZ").
dico("F", 10, "FRELATIONS").
dico("F", 10, "FRELUQUETS").
dico("F", 10, "FREMIRIONS").
dico("F", 10, "FREMISSAIS").
dico("F", 10, "FREMISSAIT").
dico("F", 10, "FREMISSANT").
dico("F", 10, "FREMISSENT").
dico("F", 10, "FREMISSIEZ").
dico("F", 10, "FREMISSONS").
dico("F", 10, "FRENATEURS").
dico("F", 10, "FRENATRICE").
dico("F", 10, "FRENETIQUE").
dico("F", 10, "FREQUENCES").
dico("F", 10, "FREQUENTAI").
dico("F", 10, "FREQUENTAS").
dico("F", 10, "FREQUENTAT").
dico("F", 10, "FREQUENTEE").
dico("F", 10, "FREQUENTER").
dico("F", 10, "FREQUENTES").
dico("F", 10, "FREQUENTEZ").
dico("F", 10, "FRESQUISTE").
dico("F", 10, "FRETASSENT").
dico("F", 10, "FRETASSIEZ").
dico("F", 10, "FRETERIONS").
dico("F", 10, "FRETILLAIS").
dico("F", 10, "FRETILLAIT").
dico("F", 10, "FRETILLANT").
dico("F", 10, "FRETILLENT").
dico("F", 10, "FRETILLERA").
dico("F", 10, "FRETILLIEZ").
dico("F", 10, "FRETILLONS").
dico("F", 10, "FRETTAIENT").
dico("F", 10, "FRETTASSES").
dico("F", 10, "FRETTERAIS").
dico("F", 10, "FRETTERAIT").
dico("F", 10, "FRETTERENT").
dico("F", 10, "FRETTERIEZ").
dico("F", 10, "FRETTERONS").
dico("F", 10, "FRETTERONT").
dico("F", 10, "FREUDIENNE").
dico("F", 10, "FREUDISMES").
dico("F", 10, "FRIABILITE").
dico("F", 10, "FRIANDISES").
dico("F", 10, "FRICADELLE").
dico("F", 10, "FRICANDEAU").
dico("F", 10, "FRICASSAIS").
dico("F", 10, "FRICASSAIT").
dico("F", 10, "FRICASSANT").
dico("F", 10, "FRICASSEES").
dico("F", 10, "FRICASSENT").
dico("F", 10, "FRICASSERA").
dico("F", 10, "FRICASSIEZ").
dico("F", 10, "FRICASSONS").
dico("F", 10, "FRICATIVES").
dico("F", 10, "FRICOTAGES").
dico("F", 10, "FRICOTAMES").
dico("F", 10, "FRICOTASSE").
dico("F", 10, "FRICOTATES").
dico("F", 10, "FRICOTERAI").
dico("F", 10, "FRICOTERAS").
dico("F", 10, "FRICOTEREZ").
dico("F", 10, "FRICOTEURS").
dico("F", 10, "FRICOTEUSE").
dico("F", 10, "FRICOTIONS").
dico("F", 10, "FRICTIONNA").
dico("F", 10, "FRICTIONNE").
dico("F", 10, "FRIGIDAIRE").
dico("F", 10, "FRIGIDITES").
dico("F", 10, "FRIGOLITES").
dico("F", 10, "FRIGORIFIA").
dico("F", 10, "FRIGORIFIE").
dico("F", 10, "FRIGORISTE").
dico("F", 10, "FRILOSITES").
dico("F", 10, "FRIMASSAIS").
dico("F", 10, "FRIMASSAIT").
dico("F", 10, "FRIMASSANT").
dico("F", 10, "FRIMASSEES").
dico("F", 10, "FRIMASSENT").
dico("F", 10, "FRIMASSERA").
dico("F", 10, "FRIMASSIEZ").
dico("F", 10, "FRIMASSONS").
dico("F", 10, "FRIMERIONS").
dico("F", 10, "FRIMOUSSES").
dico("F", 10, "FRINGANTES").
dico("F", 10, "FRINGUAMES").
dico("F", 10, "FRINGUASSE").
dico("F", 10, "FRINGUATES").
dico("F", 10, "FRINGUERAI").
dico("F", 10, "FRINGUERAS").
dico("F", 10, "FRINGUEREZ").
dico("F", 10, "FRINGUIONS").
dico("F", 10, "FRIPASSENT").
dico("F", 10, "FRIPASSIEZ").
dico("F", 10, "FRIPERIONS").
dico("F", 10, "FRIPONNAIS").
dico("F", 10, "FRIPONNAIT").
dico("F", 10, "FRIPONNANT").
dico("F", 10, "FRIPONNEES").
dico("F", 10, "FRIPONNENT").
dico("F", 10, "FRIPONNERA").
dico("F", 10, "FRIPONNIEZ").
dico("F", 10, "FRIPONNONS").
dico("F", 10, "FRIPOUILLE").
dico("F", 10, "FRISASSENT").
dico("F", 10, "FRISASSIEZ").
dico("F", 10, "FRISERIONS").
dico("F", 10, "FRISOTTAIS").
dico("F", 10, "FRISOTTAIT").
dico("F", 10, "FRISOTTANT").
dico("F", 10, "FRISOTTEES").
dico("F", 10, "FRISOTTENT").
dico("F", 10, "FRISOTTERA").
dico("F", 10, "FRISOTTIEZ").
dico("F", 10, "FRISOTTONS").
dico("F", 10, "FRISQUETTE").
dico("F", 10, "FRISSONNAI").
dico("F", 10, "FRISSONNAS").
dico("F", 10, "FRISSONNAT").
dico("F", 10, "FRISSONNER").
dico("F", 10, "FRISSONNES").
dico("F", 10, "FRISSONNEZ").
dico("F", 10, "FRITASSENT").
dico("F", 10, "FRITASSIEZ").
dico("F", 10, "FRITERIONS").
dico("F", 10, "FRITTAIENT").
dico("F", 10, "FRITTASSES").
dico("F", 10, "FRITTERAIS").
dico("F", 10, "FRITTERAIT").
dico("F", 10, "FRITTERENT").
dico("F", 10, "FRITTERIEZ").
dico("F", 10, "FRITTERONS").
dico("F", 10, "FRITTERONT").
dico("F", 10, "FRITURIERE").
dico("F", 10, "FRITURIERS").
dico("F", 10, "FRIVOLITES").
dico("F", 10, "FROEBELIEN").
dico("F", 10, "FROIDEMENT").
dico("F", 10, "FROISSABLE").
dico("F", 10, "FROISSAMES").
dico("F", 10, "FROISSANTE").
dico("F", 10, "FROISSANTS").
dico("F", 10, "FROISSASSE").
dico("F", 10, "FROISSATES").
dico("F", 10, "FROISSERAI").
dico("F", 10, "FROISSERAS").
dico("F", 10, "FROISSEREZ").
dico("F", 10, "FROISSIONS").
dico("F", 10, "FROISSURES").
dico("F", 10, "FROLASSENT").
dico("F", 10, "FROLASSIEZ").
dico("F", 10, "FROLEMENTS").
dico("F", 10, "FROLERIONS").
dico("F", 10, "FROMAGEONS").
dico("F", 10, "FROMAGERES").
dico("F", 10, "FROMAGERIE").
dico("F", 10, "FROMENTALE").
dico("F", 10, "FROMENTAUX").
dico("F", 10, "FRONCAIENT").
dico("F", 10, "FRONCASSES").
dico("F", 10, "FRONCEMENT").
dico("F", 10, "FRONCERAIS").
dico("F", 10, "FRONCERAIT").
dico("F", 10, "FRONCERENT").
dico("F", 10, "FRONCERIEZ").
dico("F", 10, "FRONCERONS").
dico("F", 10, "FRONCERONT").
dico("F", 10, "FRONDAIENT").
dico("F", 10, "FRONDAISON").
dico("F", 10, "FRONDASSES").
dico("F", 10, "FRONDERAIS").
dico("F", 10, "FRONDERAIT").
dico("F", 10, "FRONDERENT").
dico("F", 10, "FRONDERIEZ").
dico("F", 10, "FRONDERONS").
dico("F", 10, "FRONDERONT").
dico("F", 10, "FRONDEUSES").
dico("F", 10, "FRONTALIER").
dico("F", 10, "FRONTALITE").
dico("F", 10, "FRONTIERES").
dico("F", 10, "FRONTIGNAN").
dico("F", 10, "FRONTISTES").
dico("F", 10, "FROTTAIENT").
dico("F", 10, "FROTTANTES").
dico("F", 10, "FROTTASSES").
dico("F", 10, "FROTTEMENT").
dico("F", 10, "FROTTERAIS").
dico("F", 10, "FROTTERAIT").
dico("F", 10, "FROTTERENT").
dico("F", 10, "FROTTERIEZ").
dico("F", 10, "FROTTERONS").
dico("F", 10, "FROTTERONT").
dico("F", 10, "FROTTEUSES").
dico("F", 10, "FROUASSENT").
dico("F", 10, "FROUASSIEZ").
dico("F", 10, "FROUERIONS").
dico("F", 10, "FROUFROUTA").
dico("F", 10, "FROUFROUTE").
dico("F", 10, "FROUILLAIS").
dico("F", 10, "FROUILLAIT").
dico("F", 10, "FROUILLANT").
dico("F", 10, "FROUILLENT").
dico("F", 10, "FROUILLERA").
dico("F", 10, "FROUILLIEZ").
dico("F", 10, "FROUILLONS").
dico("F", 10, "FROUSSARDE").
dico("F", 10, "FROUSSARDS").
dico("F", 10, "FRUCTIDORS").
dico("F", 10, "FRUCTIFERE").
dico("F", 10, "FRUCTIFIAI").
dico("F", 10, "FRUCTIFIAS").
dico("F", 10, "FRUCTIFIAT").
dico("F", 10, "FRUCTIFIER").
dico("F", 10, "FRUCTIFIES").
dico("F", 10, "FRUCTIFIEZ").
dico("F", 10, "FRUCTUEUSE").
dico("F", 10, "FRUGALITES").
dico("F", 10, "FRUGIVORES").
dico("F", 10, "FRUITERIES").
dico("F", 10, "FRUITIERES").
dico("F", 10, "FRUMENTACE").
dico("F", 10, "FRUSTRAMES").
dico("F", 10, "FRUSTRANTE").
dico("F", 10, "FRUSTRANTS").
dico("F", 10, "FRUSTRASSE").
dico("F", 10, "FRUSTRATES").
dico("F", 10, "FRUSTRERAI").
dico("F", 10, "FRUSTRERAS").
dico("F", 10, "FRUSTREREZ").
dico("F", 10, "FRUSTRIONS").
dico("F", 10, "FRUTESCENT").
dico("F", 10, "FUCHSIENNE").
dico("F", 10, "FUEGIENNES").
dico("F", 10, "FUGUASSENT").
dico("F", 10, "FUGUASSIEZ").
dico("F", 10, "FUGUERIONS").
dico("F", 10, "FULGURALES").
dico("F", 10, "FULGURAMES").
dico("F", 10, "FULGURANCE").
dico("F", 10, "FULGURANTE").
dico("F", 10, "FULGURANTS").
dico("F", 10, "FULGURASSE").
dico("F", 10, "FULGURATES").
dico("F", 10, "FULGURERAI").
dico("F", 10, "FULGURERAS").
dico("F", 10, "FULGUREREZ").
dico("F", 10, "FULGURIONS").
dico("F", 10, "FULGURITES").
dico("F", 10, "FULIGINEUX").
dico("F", 10, "FULLERENES").
dico("F", 10, "FULMICOTON").
dico("F", 10, "FULMINAMES").
dico("F", 10, "FULMINANTE").
dico("F", 10, "FULMINANTS").
dico("F", 10, "FULMINASSE").
dico("F", 10, "FULMINATES").
dico("F", 10, "FULMINERAI").
dico("F", 10, "FULMINERAS").
dico("F", 10, "FULMINEREZ").
dico("F", 10, "FULMINIONS").
dico("F", 10, "FULMINIQUE").
dico("F", 10, "FUMARIACEE").
dico("F", 10, "FUMASSIONS").
dico("F", 10, "FUMERAIENT").
dico("F", 10, "FUMEROLLES").
dico("F", 10, "FUMERONNAI").
dico("F", 10, "FUMERONNAS").
dico("F", 10, "FUMERONNAT").
dico("F", 10, "FUMERONNER").
dico("F", 10, "FUMERONNES").
dico("F", 10, "FUMERONNEZ").
dico("F", 10, "FUMETERRES").
dico("F", 10, "FUMIGATEUR").
dico("F", 10, "FUMIGATION").
dico("F", 10, "FUMIGEAMES").
dico("F", 10, "FUMIGEASSE").
dico("F", 10, "FUMIGEATES").
dico("F", 10, "FUMIGERAIS").
dico("F", 10, "FUMIGERAIT").
dico("F", 10, "FUMIGERENT").
dico("F", 10, "FUMIGERIEZ").
dico("F", 10, "FUMIGERONS").
dico("F", 10, "FUMIGERONT").
dico("F", 10, "FUMISTERIE").
dico("F", 10, "FUMIVORITE").
dico("F", 10, "FUNAMBULES").
dico("F", 10, "FUNERAIRES").
dico("F", 10, "FUNERARIUM").
dico("F", 10, "FURETAIENT").
dico("F", 10, "FURETASSES").
dico("F", 10, "FURETERAIS").
dico("F", 10, "FURETERAIT").
dico("F", 10, "FURETERENT").
dico("F", 10, "FURETERIEZ").
dico("F", 10, "FURETERONS").
dico("F", 10, "FURETERONT").
dico("F", 10, "FURETEUSES").
dico("F", 10, "FURFURACEE").
dico("F", 10, "FURFURACES").
dico("F", 10, "FURIBARDES").
dico("F", 10, "FURIBONDES").
dico("F", 10, "FUROSEMIDE").
dico("F", 10, "FURTIVITES").
dico("F", 10, "FUSAINISTE").
dico("F", 10, "FUSARIOSES").
dico("F", 10, "FUSASSIONS").
dico("F", 10, "FUSELAIENT").
dico("F", 10, "FUSELASSES").
dico("F", 10, "FUSELERENT").
dico("F", 10, "FUSELLERAI").
dico("F", 10, "FUSELLERAS").
dico("F", 10, "FUSELLEREZ").
dico("F", 10, "FUSEOLOGIE").
dico("F", 10, "FUSERAIENT").
dico("F", 10, "FUSIBILITE").
dico("F", 10, "FUSIFORMES").
dico("F", 10, "FUSILLADES").
dico("F", 10, "FUSILLAMES").
dico("F", 10, "FUSILLASSE").
dico("F", 10, "FUSILLATES").
dico("F", 10, "FUSILLERAI").
dico("F", 10, "FUSILLERAS").
dico("F", 10, "FUSILLEREZ").
dico("F", 10, "FUSILLEURS").
dico("F", 10, "FUSILLIONS").
dico("F", 10, "FUSINISTES").
dico("F", 10, "FUSIONNAIS").
dico("F", 10, "FUSIONNAIT").
dico("F", 10, "FUSIONNANT").
dico("F", 10, "FUSIONNEES").
dico("F", 10, "FUSIONNELS").
dico("F", 10, "FUSIONNENT").
dico("F", 10, "FUSIONNERA").
dico("F", 10, "FUSIONNIEZ").
dico("F", 10, "FUSIONNONS").
dico("F", 10, "FUSTANELLE").
dico("F", 10, "FUSTIBALES").
dico("F", 10, "FUSTIGEAIS").
dico("F", 10, "FUSTIGEAIT").
dico("F", 10, "FUSTIGEANT").
dico("F", 10, "FUSTIGEONS").
dico("F", 10, "FUSTIGERAI").
dico("F", 10, "FUSTIGERAS").
dico("F", 10, "FUSTIGEREZ").
dico("F", 10, "FUSTIGIONS").
dico("F", 10, "FUTILEMENT").
dico("F", 10, "FUTUNIENNE").
dico("F", 10, "FUTURIBLES").
dico("F", 10, "FUTURISMES").
dico("F", 10, "FUTURISTES").
