dico("F", 7, "FABACEE").
dico("F", 7, "FABLIAU").
dico("F", 7, "FABLIER").
dico("F", 7, "FABULAI").
dico("F", 7, "FABULAS").
dico("F", 7, "FABULAT").
dico("F", 7, "FABULEE").
dico("F", 7, "FABULER").
dico("F", 7, "FABULES").
dico("F", 7, "FABULEZ").
dico("F", 7, "FACADES").
dico("F", 7, "FACETIE").
dico("F", 7, "FACETTA").
dico("F", 7, "FACETTE").
dico("F", 7, "FACHAIS").
dico("F", 7, "FACHAIT").
dico("F", 7, "FACHANT").
dico("F", 7, "FACHEES").
dico("F", 7, "FACHENT").
dico("F", 7, "FACHERA").
dico("F", 7, "FACHEUX").
dico("F", 7, "FACHIEZ").
dico("F", 7, "FACHONS").
dico("F", 7, "FACIALE").
dico("F", 7, "FACIALS").
dico("F", 7, "FACIAUX").
dico("F", 7, "FACILES").
dico("F", 7, "FACONDE").
dico("F", 7, "FACONNA").
dico("F", 7, "FACONNE").
dico("F", 7, "FACTAGE").
dico("F", 7, "FACTEUR").
dico("F", 7, "FACTICE").
dico("F", 7, "FACTION").
dico("F", 7, "FACTUEL").
dico("F", 7, "FACTUMS").
dico("F", 7, "FACTURA").
dico("F", 7, "FACTURE").
dico("F", 7, "FACULES").
dico("F", 7, "FACULTE").
dico("F", 7, "FADAISE").
dico("F", 7, "FADAMES").
dico("F", 7, "FADASSE").
dico("F", 7, "FADATES").
dico("F", 7, "FADERAI").
dico("F", 7, "FADERAS").
dico("F", 7, "FADEREZ").
dico("F", 7, "FADETTE").
dico("F", 7, "FADEURS").
dico("F", 7, "FADINGS").
dico("F", 7, "FADIONS").
dico("F", 7, "FAFIOTS").
dico("F", 7, "FAGACEE").
dico("F", 7, "FAGALES").
dico("F", 7, "FAGNARD").
dico("F", 7, "FAGOTAI").
dico("F", 7, "FAGOTAS").
dico("F", 7, "FAGOTAT").
dico("F", 7, "FAGOTEE").
dico("F", 7, "FAGOTER").
dico("F", 7, "FAGOTES").
dico("F", 7, "FAGOTEZ").
dico("F", 7, "FAGOTIN").
dico("F", 7, "FAGOUES").
dico("F", 7, "FAIBLES").
dico("F", 7, "FAIBLIR").
dico("F", 7, "FAIBLIS").
dico("F", 7, "FAIBLIT").
dico("F", 7, "FAIENCE").
dico("F", 7, "FAILLAI").
dico("F", 7, "FAILLAS").
dico("F", 7, "FAILLAT").
dico("F", 7, "FAILLEE").
dico("F", 7, "FAILLER").
dico("F", 7, "FAILLES").
dico("F", 7, "FAILLEZ").
dico("F", 7, "FAILLIE").
dico("F", 7, "FAILLIR").
dico("F", 7, "FAILLIS").
dico("F", 7, "FAILLIT").
dico("F", 7, "FAIRWAY").
dico("F", 7, "FAISAIS").
dico("F", 7, "FAISAIT").
dico("F", 7, "FAISANE").
dico("F", 7, "FAISANS").
dico("F", 7, "FAISANT").
dico("F", 7, "FAISEUR").
dico("F", 7, "FAISIEZ").
dico("F", 7, "FAISONS").
dico("F", 7, "FAITAGE").
dico("F", 7, "FAITEAU").
dico("F", 7, "FAITIER").
dico("F", 7, "FAITOUT").
dico("F", 7, "FAJITAS").
dico("F", 7, "FALACHA").
dico("F", 7, "FALAFEL").
dico("F", 7, "FALAISE").
dico("F", 7, "FALBALA").
dico("F", 7, "FALERNE").
dico("F", 7, "FALLAIT").
dico("F", 7, "FALLOIR").
dico("F", 7, "FALOTES").
dico("F", 7, "FALSAFA").
dico("F", 7, "FALUCHE").
dico("F", 7, "FALUNAI").
dico("F", 7, "FALUNAS").
dico("F", 7, "FALUNAT").
dico("F", 7, "FALUNEE").
dico("F", 7, "FALUNER").
dico("F", 7, "FALUNES").
dico("F", 7, "FALUNEZ").
dico("F", 7, "FALZARS").
dico("F", 7, "FAMEUSE").
dico("F", 7, "FAMILLE").
dico("F", 7, "FAMINES").
dico("F", 7, "FANAGES").
dico("F", 7, "FANAMES").
dico("F", 7, "FANASSE").
dico("F", 7, "FANATES").
dico("F", 7, "FANCHON").
dico("F", 7, "FANERAI").
dico("F", 7, "FANERAS").
dico("F", 7, "FANEREZ").
dico("F", 7, "FANEURS").
dico("F", 7, "FANEUSE").
dico("F", 7, "FANFANS").
dico("F", 7, "FANFARE").
dico("F", 7, "FANGEUX").
dico("F", 7, "FANIONS").
dico("F", 7, "FANTOME").
dico("F", 7, "FANTONS").
dico("F", 7, "FANURES").
dico("F", 7, "FANZINE").
dico("F", 7, "FAQUINS").
dico("F", 7, "FARADAY").
dico("F", 7, "FARAUDE").
dico("F", 7, "FARAUDS").
dico("F", 7, "FARCEUR").
dico("F", 7, "FARCIES").
dico("F", 7, "FARCINS").
dico("F", 7, "FARCIRA").
dico("F", 7, "FARDAGE").
dico("F", 7, "FARDAIS").
dico("F", 7, "FARDAIT").
dico("F", 7, "FARDANT").
dico("F", 7, "FARDEAU").
dico("F", 7, "FARDEES").
dico("F", 7, "FARDENT").
dico("F", 7, "FARDERA").
dico("F", 7, "FARDIER").
dico("F", 7, "FARDIEZ").
dico("F", 7, "FARDONS").
dico("F", 7, "FARFELU").
dico("F", 7, "FARGUES").
dico("F", 7, "FARINAI").
dico("F", 7, "FARINAS").
dico("F", 7, "FARINAT").
dico("F", 7, "FARINEE").
dico("F", 7, "FARINER").
dico("F", 7, "FARINES").
dico("F", 7, "FARINEZ").
dico("F", 7, "FAROUCH").
dico("F", 7, "FARRAGO").
dico("F", 7, "FARTAGE").
dico("F", 7, "FARTAIS").
dico("F", 7, "FARTAIT").
dico("F", 7, "FARTANT").
dico("F", 7, "FARTEES").
dico("F", 7, "FARTENT").
dico("F", 7, "FARTERA").
dico("F", 7, "FARTIEZ").
dico("F", 7, "FARTONS").
dico("F", 7, "FASCEES").
dico("F", 7, "FASCIAS").
dico("F", 7, "FASCIEE").
dico("F", 7, "FASCIES").
dico("F", 7, "FASCINA").
dico("F", 7, "FASCINE").
dico("F", 7, "FASCISA").
dico("F", 7, "FASCISE").
dico("F", 7, "FASEOLE").
dico("F", 7, "FASEYAI").
dico("F", 7, "FASEYAS").
dico("F", 7, "FASEYAT").
dico("F", 7, "FASEYER").
dico("F", 7, "FASEYES").
dico("F", 7, "FASEYEZ").
dico("F", 7, "FASSENT").
dico("F", 7, "FASSIES").
dico("F", 7, "FASSIEZ").
dico("F", 7, "FATALES").
dico("F", 7, "FATIGUA").
dico("F", 7, "FATIGUE").
dico("F", 7, "FATUITE").
dico("F", 7, "FAUBERS").
dico("F", 7, "FAUBERT").
dico("F", 7, "FAUCARD").
dico("F", 7, "FAUCHAI").
dico("F", 7, "FAUCHAS").
dico("F", 7, "FAUCHAT").
dico("F", 7, "FAUCHEE").
dico("F", 7, "FAUCHER").
dico("F", 7, "FAUCHES").
dico("F", 7, "FAUCHET").
dico("F", 7, "FAUCHEZ").
dico("F", 7, "FAUCHON").
dico("F", 7, "FAUCONS").
dico("F", 7, "FAUCRES").
dico("F", 7, "FAUFILA").
dico("F", 7, "FAUFILE").
dico("F", 7, "FAUFILS").
dico("F", 7, "FAUSSAI").
dico("F", 7, "FAUSSAS").
dico("F", 7, "FAUSSAT").
dico("F", 7, "FAUSSEE").
dico("F", 7, "FAUSSER").
dico("F", 7, "FAUSSES").
dico("F", 7, "FAUSSET").
dico("F", 7, "FAUSSEZ").
dico("F", 7, "FAUTAIS").
dico("F", 7, "FAUTAIT").
dico("F", 7, "FAUTANT").
dico("F", 7, "FAUTENT").
dico("F", 7, "FAUTERA").
dico("F", 7, "FAUTEUR").
dico("F", 7, "FAUTIEZ").
dico("F", 7, "FAUTIFS").
dico("F", 7, "FAUTIVE").
dico("F", 7, "FAUTONS").
dico("F", 7, "FAVELAS").
dico("F", 7, "FAVEURS").
dico("F", 7, "FAVISME").
dico("F", 7, "FAVORIS").
dico("F", 7, "FAXAMES").
dico("F", 7, "FAXASSE").
dico("F", 7, "FAXATES").
dico("F", 7, "FAXERAI").
dico("F", 7, "FAXERAS").
dico("F", 7, "FAXEREZ").
dico("F", 7, "FAXIONS").
dico("F", 7, "FAYARDS").
dico("F", 7, "FAYOTAI").
dico("F", 7, "FAYOTAS").
dico("F", 7, "FAYOTAT").
dico("F", 7, "FAYOTEE").
dico("F", 7, "FAYOTER").
dico("F", 7, "FAYOTES").
dico("F", 7, "FAYOTEZ").
dico("F", 7, "FAZENDA").
dico("F", 7, "FEBRILE").
dico("F", 7, "FECALES").
dico("F", 7, "FECIALE").
dico("F", 7, "FECIAUX").
dico("F", 7, "FECONDA").
dico("F", 7, "FECONDE").
dico("F", 7, "FECONDS").
dico("F", 7, "FECULAI").
dico("F", 7, "FECULAS").
dico("F", 7, "FECULAT").
dico("F", 7, "FECULEE").
dico("F", 7, "FECULER").
dico("F", 7, "FECULES").
dico("F", 7, "FECULEZ").
dico("F", 7, "FEDAYIN").
dico("F", 7, "FEDERAI").
dico("F", 7, "FEDERAL").
dico("F", 7, "FEDERAS").
dico("F", 7, "FEDERAT").
dico("F", 7, "FEDEREE").
dico("F", 7, "FEDERER").
dico("F", 7, "FEDERES").
dico("F", 7, "FEDEREZ").
dico("F", 7, "FEEDERS").
dico("F", 7, "FEELING").
dico("F", 7, "FEERIES").
dico("F", 7, "FEIGNES").
dico("F", 7, "FEIGNEZ").
dico("F", 7, "FEIGNIS").
dico("F", 7, "FEIGNIT").
dico("F", 7, "FEINDRA").
dico("F", 7, "FEINDRE").
dico("F", 7, "FEINTAI").
dico("F", 7, "FEINTAS").
dico("F", 7, "FEINTAT").
dico("F", 7, "FEINTEE").
dico("F", 7, "FEINTER").
dico("F", 7, "FEINTES").
dico("F", 7, "FEINTEZ").
dico("F", 7, "FELAMES").
dico("F", 7, "FELASSE").
dico("F", 7, "FELATES").
dico("F", 7, "FELERAI").
dico("F", 7, "FELERAS").
dico("F", 7, "FELEREZ").
dico("F", 7, "FELIBRE").
dico("F", 7, "FELIDES").
dico("F", 7, "FELINES").
dico("F", 7, "FELIONS").
dico("F", 7, "FELLAGA").
dico("F", 7, "FELLAHS").
dico("F", 7, "FELONIE").
dico("F", 7, "FELONNE").
dico("F", 7, "FELURES").
dico("F", 7, "FEMELLE").
dico("F", 7, "FEMELOT").
dico("F", 7, "FEMININ").
dico("F", 7, "FEMORAL").
dico("F", 7, "FENDAGE").
dico("F", 7, "FENDAIS").
dico("F", 7, "FENDAIT").
dico("F", 7, "FENDANT").
dico("F", 7, "FENDARD").
dico("F", 7, "FENDART").
dico("F", 7, "FENDENT").
dico("F", 7, "FENDEUR").
dico("F", 7, "FENDIEZ").
dico("F", 7, "FENDOIR").
dico("F", 7, "FENDONS").
dico("F", 7, "FENDRAI").
dico("F", 7, "FENDRAS").
dico("F", 7, "FENDREZ").
dico("F", 7, "FENDUES").
dico("F", 7, "FENETRA").
dico("F", 7, "FENETRE").
dico("F", 7, "FENIANE").
dico("F", 7, "FENIANS").
dico("F", 7, "FENNECS").
dico("F", 7, "FENOUIL").
dico("F", 7, "FENTONS").
dico("F", 7, "FEODALE").
dico("F", 7, "FEODAUX").
dico("F", 7, "FERALES").
dico("F", 7, "FERIALE").
dico("F", 7, "FERIAUX").
dico("F", 7, "FERIEES").
dico("F", 7, "FERIONS").
dico("F", 7, "FERLAGE").
dico("F", 7, "FERLAIS").
dico("F", 7, "FERLAIT").
dico("F", 7, "FERLANT").
dico("F", 7, "FERLEES").
dico("F", 7, "FERLENT").
dico("F", 7, "FERLERA").
dico("F", 7, "FERLIEZ").
dico("F", 7, "FERLONS").
dico("F", 7, "FERMAGE").
dico("F", 7, "FERMAIL").
dico("F", 7, "FERMAIS").
dico("F", 7, "FERMAIT").
dico("F", 7, "FERMANT").
dico("F", 7, "FERMAUX").
dico("F", 7, "FERMEES").
dico("F", 7, "FERMENT").
dico("F", 7, "FERMERA").
dico("F", 7, "FERMETE").
dico("F", 7, "FERMIER").
dico("F", 7, "FERMIEZ").
dico("F", 7, "FERMION").
dico("F", 7, "FERMIUM").
dico("F", 7, "FERMOIR").
dico("F", 7, "FERMONS").
dico("F", 7, "FEROCES").
dico("F", 7, "FEROIEN").
dico("F", 7, "FERRADE").
dico("F", 7, "FERRAGE").
dico("F", 7, "FERRAIS").
dico("F", 7, "FERRAIT").
dico("F", 7, "FERRANT").
dico("F", 7, "FERRATE").
dico("F", 7, "FERREES").
dico("F", 7, "FERRENT").
dico("F", 7, "FERRERA").
dico("F", 7, "FERRETS").
dico("F", 7, "FERREUR").
dico("F", 7, "FERREUX").
dico("F", 7, "FERRIES").
dico("F", 7, "FERRIEZ").
dico("F", 7, "FERRITE").
dico("F", 7, "FERRONS").
dico("F", 7, "FERRURE").
dico("F", 7, "FERTILE").
dico("F", 7, "FERULES").
dico("F", 7, "FERVENT").
dico("F", 7, "FERVEUR").
dico("F", 7, "FESSAIS").
dico("F", 7, "FESSAIT").
dico("F", 7, "FESSANT").
dico("F", 7, "FESSEES").
dico("F", 7, "FESSENT").
dico("F", 7, "FESSERA").
dico("F", 7, "FESSIER").
dico("F", 7, "FESSIEZ").
dico("F", 7, "FESSONS").
dico("F", 7, "FESSUES").
dico("F", 7, "FESTIFS").
dico("F", 7, "FESTINA").
dico("F", 7, "FESTINE").
dico("F", 7, "FESTINS").
dico("F", 7, "FESTIVE").
dico("F", 7, "FESTOIE").
dico("F", 7, "FESTONS").
dico("F", 7, "FESTOYA").
dico("F", 7, "FESTOYE").
dico("F", 7, "FETAMES").
dico("F", 7, "FETARDE").
dico("F", 7, "FETARDS").
dico("F", 7, "FETASSE").
dico("F", 7, "FETATES").
dico("F", 7, "FETERAI").
dico("F", 7, "FETERAS").
dico("F", 7, "FETEREZ").
dico("F", 7, "FETIALE").
dico("F", 7, "FETIAUX").
dico("F", 7, "FETICHE").
dico("F", 7, "FETIDES").
dico("F", 7, "FETIONS").
dico("F", 7, "FETUQUE").
dico("F", 7, "FEUILLA").
dico("F", 7, "FEUILLE").
dico("F", 7, "FEUILLU").
dico("F", 7, "FEULAIS").
dico("F", 7, "FEULAIT").
dico("F", 7, "FEULANT").
dico("F", 7, "FEULENT").
dico("F", 7, "FEULERA").
dico("F", 7, "FEULIEZ").
dico("F", 7, "FEULONS").
dico("F", 7, "FEUTRAI").
dico("F", 7, "FEUTRAS").
dico("F", 7, "FEUTRAT").
dico("F", 7, "FEUTREE").
dico("F", 7, "FEUTRER").
dico("F", 7, "FEUTRES").
dico("F", 7, "FEUTREZ").
dico("F", 7, "FEVIERS").
dico("F", 7, "FEVRIER").
dico("F", 7, "FIABLES").
dico("F", 7, "FIACRES").
dico("F", 7, "FIAIENT").
dico("F", 7, "FIANCAI").
dico("F", 7, "FIANCAS").
dico("F", 7, "FIANCAT").
dico("F", 7, "FIANCEE").
dico("F", 7, "FIANCER").
dico("F", 7, "FIANCES").
dico("F", 7, "FIANCEZ").
dico("F", 7, "FIASCOS").
dico("F", 7, "FIASQUE").
dico("F", 7, "FIASSES").
dico("F", 7, "FIBREUX").
dico("F", 7, "FIBRINE").
dico("F", 7, "FIBROME").
dico("F", 7, "FIBROSE").
dico("F", 7, "FIBULAS").
dico("F", 7, "FIBULES").
dico("F", 7, "FICAIRE").
dico("F", 7, "FICELAI").
dico("F", 7, "FICELAS").
dico("F", 7, "FICELAT").
dico("F", 7, "FICELEE").
dico("F", 7, "FICELER").
dico("F", 7, "FICELES").
dico("F", 7, "FICELEZ").
dico("F", 7, "FICELLE").
dico("F", 7, "FICHAGE").
dico("F", 7, "FICHAIS").
dico("F", 7, "FICHAIT").
dico("F", 7, "FICHANT").
dico("F", 7, "FICHEES").
dico("F", 7, "FICHENT").
dico("F", 7, "FICHERA").
dico("F", 7, "FICHETS").
dico("F", 7, "FICHIER").
dico("F", 7, "FICHIEZ").
dico("F", 7, "FICHOIR").
dico("F", 7, "FICHONS").
dico("F", 7, "FICHTRE").
dico("F", 7, "FICHUES").
dico("F", 7, "FICTIFS").
dico("F", 7, "FICTION").
dico("F", 7, "FICTIVE").
dico("F", 7, "FIDEENS").
dico("F", 7, "FIDELES").
dico("F", 7, "FIDJIEN").
dico("F", 7, "FIDUCIE").
dico("F", 7, "FIEFFAI").
dico("F", 7, "FIEFFAS").
dico("F", 7, "FIEFFAT").
dico("F", 7, "FIEFFEE").
dico("F", 7, "FIEFFER").
dico("F", 7, "FIEFFES").
dico("F", 7, "FIEFFEZ").
dico("F", 7, "FIENTAI").
dico("F", 7, "FIENTAS").
dico("F", 7, "FIENTAT").
dico("F", 7, "FIENTER").
dico("F", 7, "FIENTES").
dico("F", 7, "FIENTEZ").
dico("F", 7, "FIERAIS").
dico("F", 7, "FIERAIT").
dico("F", 7, "FIERENT").
dico("F", 7, "FIERIEZ").
dico("F", 7, "FIERONS").
dico("F", 7, "FIERONT").
dico("F", 7, "FIEROTE").
dico("F", 7, "FIEROTS").
dico("F", 7, "FIERTES").
dico("F", 7, "FIESTAS").
dico("F", 7, "FIEVRES").
dico("F", 7, "FIFILLE").
dico("F", 7, "FIGAROS").
dico("F", 7, "FIGEAIS").
dico("F", 7, "FIGEAIT").
dico("F", 7, "FIGEANT").
dico("F", 7, "FIGEONS").
dico("F", 7, "FIGERAI").
dico("F", 7, "FIGERAS").
dico("F", 7, "FIGEREZ").
dico("F", 7, "FIGIONS").
dico("F", 7, "FIGNOLA").
dico("F", 7, "FIGNOLE").
dico("F", 7, "FIGUIER").
dico("F", 7, "FIGULIN").
dico("F", 7, "FIGURAI").
dico("F", 7, "FIGURAS").
dico("F", 7, "FIGURAT").
dico("F", 7, "FIGUREE").
dico("F", 7, "FIGURER").
dico("F", 7, "FIGURES").
dico("F", 7, "FIGUREZ").
dico("F", 7, "FILABLE").
dico("F", 7, "FILAGES").
dico("F", 7, "FILAIRE").
dico("F", 7, "FILAMES").
dico("F", 7, "FILANTE").
dico("F", 7, "FILANTS").
dico("F", 7, "FILASSE").
dico("F", 7, "FILATES").
dico("F", 7, "FILERAI").
dico("F", 7, "FILERAS").
dico("F", 7, "FILEREZ").
dico("F", 7, "FILETAI").
dico("F", 7, "FILETAS").
dico("F", 7, "FILETAT").
dico("F", 7, "FILETEE").
dico("F", 7, "FILETER").
dico("F", 7, "FILETES").
dico("F", 7, "FILETEZ").
dico("F", 7, "FILEURS").
dico("F", 7, "FILEUSE").
dico("F", 7, "FILIALE").
dico("F", 7, "FILIAUX").
dico("F", 7, "FILIBEG").
dico("F", 7, "FILIERE").
dico("F", 7, "FILIONS").
dico("F", 7, "FILLERS").
dico("F", 7, "FILLEUL").
dico("F", 7, "FILMAGE").
dico("F", 7, "FILMAIS").
dico("F", 7, "FILMAIT").
dico("F", 7, "FILMANT").
dico("F", 7, "FILMEES").
dico("F", 7, "FILMENT").
dico("F", 7, "FILMERA").
dico("F", 7, "FILMIEZ").
dico("F", 7, "FILMONS").
dico("F", 7, "FILOCHA").
dico("F", 7, "FILOCHE").
dico("F", 7, "FILOUTA").
dico("F", 7, "FILOUTE").
dico("F", 7, "FILTRAI").
dico("F", 7, "FILTRAS").
dico("F", 7, "FILTRAT").
dico("F", 7, "FILTREE").
dico("F", 7, "FILTRER").
dico("F", 7, "FILTRES").
dico("F", 7, "FILTREZ").
dico("F", 7, "FINAGES").
dico("F", 7, "FINALES").
dico("F", 7, "FINANCA").
dico("F", 7, "FINANCE").
dico("F", 7, "FINASSA").
dico("F", 7, "FINASSE").
dico("F", 7, "FINAUDE").
dico("F", 7, "FINAUDS").
dico("F", 7, "FINERIE").
dico("F", 7, "FINESSE").
dico("F", 7, "FINETTE").
dico("F", 7, "FINIMES").
dico("F", 7, "FINIRAI").
dico("F", 7, "FINIRAS").
dico("F", 7, "FINIREZ").
dico("F", 7, "FINISHS").
dico("F", 7, "FINISSE").
dico("F", 7, "FINITES").
dico("F", 7, "FINNOIS").
dico("F", 7, "FIRMANS").
dico("F", 7, "FISCALE").
dico("F", 7, "FISCAUX").
dico("F", 7, "FISSENT").
dico("F", 7, "FISSIEZ").
dico("F", 7, "FISSILE").
dico("F", 7, "FISSION").
dico("F", 7, "FISSURA").
dico("F", 7, "FISSURE").
dico("F", 7, "FISTONS").
dico("F", 7, "FISTOTS").
dico("F", 7, "FISTULE").
dico("F", 7, "FITNESS").
dico("F", 7, "FITTAIS").
dico("F", 7, "FITTAIT").
dico("F", 7, "FITTANT").
dico("F", 7, "FITTEES").
dico("F", 7, "FITTENT").
dico("F", 7, "FITTERA").
dico("F", 7, "FITTIEZ").
dico("F", 7, "FITTONS").
dico("F", 7, "FIVETES").
dico("F", 7, "FIXAGES").
dico("F", 7, "FIXAMES").
dico("F", 7, "FIXANTE").
dico("F", 7, "FIXANTS").
dico("F", 7, "FIXASSE").
dico("F", 7, "FIXATES").
dico("F", 7, "FIXATIF").
dico("F", 7, "FIXERAI").
dico("F", 7, "FIXERAS").
dico("F", 7, "FIXEREZ").
dico("F", 7, "FIXETTE").
dico("F", 7, "FIXINGS").
dico("F", 7, "FIXIONS").
dico("F", 7, "FIXISME").
dico("F", 7, "FIXISTE").
dico("F", 7, "FIXITES").
dico("F", 7, "FLACHES").
dico("F", 7, "FLACONS").
dico("F", 7, "FLAFLAS").
dico("F", 7, "FLAGADA").
dico("F", 7, "FLAIRAI").
dico("F", 7, "FLAIRAS").
dico("F", 7, "FLAIRAT").
dico("F", 7, "FLAIREE").
dico("F", 7, "FLAIRER").
dico("F", 7, "FLAIRES").
dico("F", 7, "FLAIREZ").
dico("F", 7, "FLAMAND").
dico("F", 7, "FLAMANT").
dico("F", 7, "FLAMBAI").
dico("F", 7, "FLAMBAS").
dico("F", 7, "FLAMBAT").
dico("F", 7, "FLAMBEE").
dico("F", 7, "FLAMBER").
dico("F", 7, "FLAMBES").
dico("F", 7, "FLAMBEZ").
dico("F", 7, "FLAMINE").
dico("F", 7, "FLAMMEE").
dico("F", 7, "FLAMMES").
dico("F", 7, "FLANAIS").
dico("F", 7, "FLANAIT").
dico("F", 7, "FLANANT").
dico("F", 7, "FLANCHA").
dico("F", 7, "FLANCHE").
dico("F", 7, "FLANDRE").
dico("F", 7, "FLANENT").
dico("F", 7, "FLANERA").
dico("F", 7, "FLANEUR").
dico("F", 7, "FLANIEZ").
dico("F", 7, "FLANONS").
dico("F", 7, "FLANQUA").
dico("F", 7, "FLANQUE").
dico("F", 7, "FLAPIES").
dico("F", 7, "FLAQUES").
dico("F", 7, "FLASHAI").
dico("F", 7, "FLASHAS").
dico("F", 7, "FLASHAT").
dico("F", 7, "FLASHEE").
dico("F", 7, "FLASHER").
dico("F", 7, "FLASHES").
dico("F", 7, "FLASHEZ").
dico("F", 7, "FLASQUE").
dico("F", 7, "FLATTAI").
dico("F", 7, "FLATTAS").
dico("F", 7, "FLATTAT").
dico("F", 7, "FLATTEE").
dico("F", 7, "FLATTER").
dico("F", 7, "FLATTES").
dico("F", 7, "FLATTEZ").
dico("F", 7, "FLAVEUR").
dico("F", 7, "FLAVINE").
dico("F", 7, "FLECHAI").
dico("F", 7, "FLECHAS").
dico("F", 7, "FLECHAT").
dico("F", 7, "FLECHEE").
dico("F", 7, "FLECHER").
dico("F", 7, "FLECHES").
dico("F", 7, "FLECHEZ").
dico("F", 7, "FLECHIE").
dico("F", 7, "FLECHIR").
dico("F", 7, "FLECHIS").
dico("F", 7, "FLECHIT").
dico("F", 7, "FLEGMES").
dico("F", 7, "FLEGMON").
dico("F", 7, "FLEMARD").
dico("F", 7, "FLEMMES").
dico("F", 7, "FLENUES").
dico("F", 7, "FLEOLES").
dico("F", 7, "FLETANS").
dico("F", 7, "FLETRIE").
dico("F", 7, "FLETRIR").
dico("F", 7, "FLETRIS").
dico("F", 7, "FLETRIT").
dico("F", 7, "FLETTES").
dico("F", 7, "FLEURAI").
dico("F", 7, "FLEURAS").
dico("F", 7, "FLEURAT").
dico("F", 7, "FLEUREE").
dico("F", 7, "FLEURER").
dico("F", 7, "FLEURES").
dico("F", 7, "FLEURET").
dico("F", 7, "FLEUREZ").
dico("F", 7, "FLEURIE").
dico("F", 7, "FLEURIR").
dico("F", 7, "FLEURIS").
dico("F", 7, "FLEURIT").
dico("F", 7, "FLEURON").
dico("F", 7, "FLEUVES").
dico("F", 7, "FLEXION").
dico("F", 7, "FLEXURE").
dico("F", 7, "FLICAGE").
dico("F", 7, "FLICARD").
dico("F", 7, "FLINGOT").
dico("F", 7, "FLINGUA").
dico("F", 7, "FLINGUE").
dico("F", 7, "FLIPOTS").
dico("F", 7, "FLIPPAI").
dico("F", 7, "FLIPPAS").
dico("F", 7, "FLIPPAT").
dico("F", 7, "FLIPPER").
dico("F", 7, "FLIPPES").
dico("F", 7, "FLIPPEZ").
dico("F", 7, "FLIQUAI").
dico("F", 7, "FLIQUAS").
dico("F", 7, "FLIQUAT").
dico("F", 7, "FLIQUEE").
dico("F", 7, "FLIQUER").
dico("F", 7, "FLIQUES").
dico("F", 7, "FLIQUEZ").
dico("F", 7, "FLIRTAI").
dico("F", 7, "FLIRTAS").
dico("F", 7, "FLIRTAT").
dico("F", 7, "FLIRTER").
dico("F", 7, "FLIRTES").
dico("F", 7, "FLIRTEZ").
dico("F", 7, "FLOBERT").
dico("F", 7, "FLOCAGE").
dico("F", 7, "FLOCHES").
dico("F", 7, "FLOCONS").
dico("F", 7, "FLOCULA").
dico("F", 7, "FLOCULE").
dico("F", 7, "FLOPEES").
dico("F", 7, "FLOQUAI").
dico("F", 7, "FLOQUAS").
dico("F", 7, "FLOQUAT").
dico("F", 7, "FLOQUEE").
dico("F", 7, "FLOQUER").
dico("F", 7, "FLOQUES").
dico("F", 7, "FLOQUEZ").
dico("F", 7, "FLORALE").
dico("F", 7, "FLORAUX").
dico("F", 7, "FLOREAL").
dico("F", 7, "FLORINS").
dico("F", 7, "FLOTTAI").
dico("F", 7, "FLOTTAS").
dico("F", 7, "FLOTTAT").
dico("F", 7, "FLOTTEE").
dico("F", 7, "FLOTTER").
dico("F", 7, "FLOTTES").
dico("F", 7, "FLOTTEZ").
dico("F", 7, "FLOUAIS").
dico("F", 7, "FLOUAIT").
dico("F", 7, "FLOUANT").
dico("F", 7, "FLOUEES").
dico("F", 7, "FLOUENT").
dico("F", 7, "FLOUERA").
dico("F", 7, "FLOUIEZ").
dico("F", 7, "FLOUONS").
dico("F", 7, "FLOUSES").
dico("F", 7, "FLOUSSE").
dico("F", 7, "FLOUVES").
dico("F", 7, "FLOUZES").
dico("F", 7, "FLUAGES").
dico("F", 7, "FLUAMES").
dico("F", 7, "FLUASSE").
dico("F", 7, "FLUATES").
dico("F", 7, "FLUCTUA").
dico("F", 7, "FLUCTUE").
dico("F", 7, "FLUENCE").
dico("F", 7, "FLUENTE").
dico("F", 7, "FLUENTS").
dico("F", 7, "FLUERAI").
dico("F", 7, "FLUERAS").
dico("F", 7, "FLUEREZ").
dico("F", 7, "FLUETTE").
dico("F", 7, "FLUIDES").
dico("F", 7, "FLUIONS").
dico("F", 7, "FLUOREE").
dico("F", 7, "FLUORES").
dico("F", 7, "FLUSHES").
dico("F", 7, "FLUSTRE").
dico("F", 7, "FLUTAIS").
dico("F", 7, "FLUTAIT").
dico("F", 7, "FLUTANT").
dico("F", 7, "FLUTEAU").
dico("F", 7, "FLUTEES").
dico("F", 7, "FLUTENT").
dico("F", 7, "FLUTERA").
dico("F", 7, "FLUTIAU").
dico("F", 7, "FLUTIEZ").
dico("F", 7, "FLUTONS").
dico("F", 7, "FLUTTER").
dico("F", 7, "FLUVIAL").
dico("F", 7, "FLUXAGE").
dico("F", 7, "FLUXAIS").
dico("F", 7, "FLUXAIT").
dico("F", 7, "FLUXANT").
dico("F", 7, "FLUXEES").
dico("F", 7, "FLUXENT").
dico("F", 7, "FLUXERA").
dico("F", 7, "FLUXIEZ").
dico("F", 7, "FLUXION").
dico("F", 7, "FLUXONS").
dico("F", 7, "FLYSCHS").
dico("F", 7, "FOCALES").
dico("F", 7, "FOEHNAI").
dico("F", 7, "FOEHNAS").
dico("F", 7, "FOEHNAT").
dico("F", 7, "FOEHNEE").
dico("F", 7, "FOEHNER").
dico("F", 7, "FOEHNES").
dico("F", 7, "FOEHNEZ").
dico("F", 7, "FOETALE").
dico("F", 7, "FOETAUX").
dico("F", 7, "FOFOLLE").
dico("F", 7, "FOGGARA").
dico("F", 7, "FOHNAIS").
dico("F", 7, "FOHNAIT").
dico("F", 7, "FOHNANT").
dico("F", 7, "FOHNEES").
dico("F", 7, "FOHNENT").
dico("F", 7, "FOHNERA").
dico("F", 7, "FOHNIEZ").
dico("F", 7, "FOHNONS").
dico("F", 7, "FOIRADE").
dico("F", 7, "FOIRAIL").
dico("F", 7, "FOIRAIS").
dico("F", 7, "FOIRAIT").
dico("F", 7, "FOIRALS").
dico("F", 7, "FOIRANT").
dico("F", 7, "FOIREES").
dico("F", 7, "FOIRENT").
dico("F", 7, "FOIRERA").
dico("F", 7, "FOIREUX").
dico("F", 7, "FOIRIEZ").
dico("F", 7, "FOIRONS").
dico("F", 7, "FOISONS").
dico("F", 7, "FOLACHE").
dico("F", 7, "FOLASSE").
dico("F", 7, "FOLATRA").
dico("F", 7, "FOLATRE").
dico("F", 7, "FOLDERS").
dico("F", 7, "FOLIACE").
dico("F", 7, "FOLIEES").
dico("F", 7, "FOLIOLE").
dico("F", 7, "FOLIOTA").
dico("F", 7, "FOLIOTE").
dico("F", 7, "FOLIOTS").
dico("F", 7, "FOLIQUE").
dico("F", 7, "FOLKEUX").
dico("F", 7, "FOLLETS").
dico("F", 7, "FOMENTA").
dico("F", 7, "FOMENTE").
dico("F", 7, "FONCAGE").
dico("F", 7, "FONCAIS").
dico("F", 7, "FONCAIT").
dico("F", 7, "FONCANT").
dico("F", 7, "FONCEES").
dico("F", 7, "FONCENT").
dico("F", 7, "FONCERA").
dico("F", 7, "FONCEUR").
dico("F", 7, "FONCIER").
dico("F", 7, "FONCIEZ").
dico("F", 7, "FONCONS").
dico("F", 7, "FONDAIS").
dico("F", 7, "FONDAIT").
dico("F", 7, "FONDANT").
dico("F", 7, "FONDEES").
dico("F", 7, "FONDENT").
dico("F", 7, "FONDERA").
dico("F", 7, "FONDEUR").
dico("F", 7, "FONDIEZ").
dico("F", 7, "FONDOIR").
dico("F", 7, "FONDONS").
dico("F", 7, "FONDOUK").
dico("F", 7, "FONDRAI").
dico("F", 7, "FONDRAS").
dico("F", 7, "FONDREZ").
dico("F", 7, "FONDUES").
dico("F", 7, "FONTINE").
dico("F", 7, "FOOTEUX").
dico("F", 7, "FOOTING").
dico("F", 7, "FORABLE").
dico("F", 7, "FORAGES").
dico("F", 7, "FORAINE").
dico("F", 7, "FORAINS").
dico("F", 7, "FORAMES").
dico("F", 7, "FORASSE").
dico("F", 7, "FORATES").
dico("F", 7, "FORBANS").
dico("F", 7, "FORCAGE").
dico("F", 7, "FORCAIL").
dico("F", 7, "FORCAIS").
dico("F", 7, "FORCAIT").
dico("F", 7, "FORCANT").
dico("F", 7, "FORCATS").
dico("F", 7, "FORCEES").
dico("F", 7, "FORCENE").
dico("F", 7, "FORCENT").
dico("F", 7, "FORCEPS").
dico("F", 7, "FORCERA").
dico("F", 7, "FORCEUR").
dico("F", 7, "FORCIES").
dico("F", 7, "FORCIEZ").
dico("F", 7, "FORCING").
dico("F", 7, "FORCIRA").
dico("F", 7, "FORCLOS").
dico("F", 7, "FORCONS").
dico("F", 7, "FORERAI").
dico("F", 7, "FORERAS").
dico("F", 7, "FOREREZ").
dico("F", 7, "FOREURS").
dico("F", 7, "FOREUSE").
dico("F", 7, "FORFAIS").
dico("F", 7, "FORFAIT").
dico("F", 7, "FORGEAI").
dico("F", 7, "FORGEAS").
dico("F", 7, "FORGEAT").
dico("F", 7, "FORGEES").
dico("F", 7, "FORGENT").
dico("F", 7, "FORGERA").
dico("F", 7, "FORGEUR").
dico("F", 7, "FORGIEZ").
dico("F", 7, "FORINTS").
dico("F", 7, "FORIONS").
dico("F", 7, "FORJETA").
dico("F", 7, "FORJETE").
dico("F", 7, "FORJETS").
dico("F", 7, "FORLANE").
dico("F", 7, "FORMAGE").
dico("F", 7, "FORMAIS").
dico("F", 7, "FORMAIT").
dico("F", 7, "FORMANT").
dico("F", 7, "FORMATA").
dico("F", 7, "FORMATE").
dico("F", 7, "FORMATS").
dico("F", 7, "FORMEES").
dico("F", 7, "FORMELS").
dico("F", 7, "FORMENE").
dico("F", 7, "FORMENT").
dico("F", 7, "FORMERA").
dico("F", 7, "FORMICA").
dico("F", 7, "FORMIER").
dico("F", 7, "FORMIEZ").
dico("F", 7, "FORMOLA").
dico("F", 7, "FORMOLE").
dico("F", 7, "FORMOLS").
dico("F", 7, "FORMONS").
dico("F", 7, "FORMULA").
dico("F", 7, "FORMULE").
dico("F", 7, "FORMYLE").
dico("F", 7, "FORTAGE").
dico("F", 7, "FORTIFS").
dico("F", 7, "FORTINS").
dico("F", 7, "FORTRAN").
dico("F", 7, "FORTUIT").
dico("F", 7, "FORTUNE").
dico("F", 7, "FORURES").
dico("F", 7, "FOSBURY").
dico("F", 7, "FOSSANE").
dico("F", 7, "FOSSILE").
dico("F", 7, "FOSSOIE").
dico("F", 7, "FOSSOIR").
dico("F", 7, "FOSSOYA").
dico("F", 7, "FOSSOYE").
dico("F", 7, "FOUACES").
dico("F", 7, "FOUAGES").
dico("F", 7, "FOUCADE").
dico("F", 7, "FOUDRES").
dico("F", 7, "FOUENES").
dico("F", 7, "FOUETTA").
dico("F", 7, "FOUETTE").
dico("F", 7, "FOUFOUS").
dico("F", 7, "FOUGEAI").
dico("F", 7, "FOUGEAS").
dico("F", 7, "FOUGEAT").
dico("F", 7, "FOUGEES").
dico("F", 7, "FOUGENT").
dico("F", 7, "FOUGERA").
dico("F", 7, "FOUGERE").
dico("F", 7, "FOUGIEZ").
dico("F", 7, "FOUGUES").
dico("F", 7, "FOUILLA").
dico("F", 7, "FOUILLE").
dico("F", 7, "FOUIMES").
dico("F", 7, "FOUINAI").
dico("F", 7, "FOUINAS").
dico("F", 7, "FOUINAT").
dico("F", 7, "FOUINER").
dico("F", 7, "FOUINES").
dico("F", 7, "FOUINEZ").
dico("F", 7, "FOUIRAI").
dico("F", 7, "FOUIRAS").
dico("F", 7, "FOUIREZ").
dico("F", 7, "FOUISSE").
dico("F", 7, "FOUITES").
dico("F", 7, "FOULAGE").
dico("F", 7, "FOULAIS").
dico("F", 7, "FOULAIT").
dico("F", 7, "FOULANT").
dico("F", 7, "FOULARD").
dico("F", 7, "FOULEES").
dico("F", 7, "FOULENT").
dico("F", 7, "FOULERA").
dico("F", 7, "FOULEUR").
dico("F", 7, "FOULIEZ").
dico("F", 7, "FOULING").
dico("F", 7, "FOULOIR").
dico("F", 7, "FOULONS").
dico("F", 7, "FOULQUE").
dico("F", 7, "FOULURE").
dico("F", 7, "FOURBES").
dico("F", 7, "FOURBIE").
dico("F", 7, "FOURBIR").
dico("F", 7, "FOURBIS").
dico("F", 7, "FOURBIT").
dico("F", 7, "FOURBUE").
dico("F", 7, "FOURBUS").
dico("F", 7, "FOURCHA").
dico("F", 7, "FOURCHE").
dico("F", 7, "FOURCHU").
dico("F", 7, "FOURGON").
dico("F", 7, "FOURGUA").
dico("F", 7, "FOURGUE").
dico("F", 7, "FOURMES").
dico("F", 7, "FOURMIS").
dico("F", 7, "FOURNEE").
dico("F", 7, "FOURNIE").
dico("F", 7, "FOURNIL").
dico("F", 7, "FOURNIR").
dico("F", 7, "FOURNIS").
dico("F", 7, "FOURNIT").
dico("F", 7, "FOURRAI").
dico("F", 7, "FOURRAS").
dico("F", 7, "FOURRAT").
dico("F", 7, "FOURREE").
dico("F", 7, "FOURRER").
dico("F", 7, "FOURRES").
dico("F", 7, "FOURREZ").
dico("F", 7, "FOUTAIS").
dico("F", 7, "FOUTAIT").
dico("F", 7, "FOUTANT").
dico("F", 7, "FOUTEAU").
dico("F", 7, "FOUTENT").
dico("F", 7, "FOUTEUR").
dico("F", 7, "FOUTIEZ").
dico("F", 7, "FOUTOIR").
dico("F", 7, "FOUTONS").
dico("F", 7, "FOUTOUS").
dico("F", 7, "FOUTRAI").
dico("F", 7, "FOUTRAL").
dico("F", 7, "FOUTRAS").
dico("F", 7, "FOUTRES").
dico("F", 7, "FOUTREZ").
dico("F", 7, "FOUTUES").
dico("F", 7, "FOVEALE").
dico("F", 7, "FOVEAUX").
dico("F", 7, "FOYARDS").
dico("F", 7, "FRACTAL").
dico("F", 7, "FRAGILE").
dico("F", 7, "FRAGONS").
dico("F", 7, "FRAICHE").
dico("F", 7, "FRAICHI").
dico("F", 7, "FRAIENT").
dico("F", 7, "FRAIERA").
dico("F", 7, "FRAIRIE").
dico("F", 7, "FRAISAI").
dico("F", 7, "FRAISAS").
dico("F", 7, "FRAISAT").
dico("F", 7, "FRAISEE").
dico("F", 7, "FRAISER").
dico("F", 7, "FRAISES").
dico("F", 7, "FRAISEZ").
dico("F", 7, "FRAISIL").
dico("F", 7, "FRAMEES").
dico("F", 7, "FRANCHE").
dico("F", 7, "FRANCHI").
dico("F", 7, "FRANGEA").
dico("F", 7, "FRANGEE").
dico("F", 7, "FRANGER").
dico("F", 7, "FRANGES").
dico("F", 7, "FRANGEZ").
dico("F", 7, "FRANGIN").
dico("F", 7, "FRANQUE").
dico("F", 7, "FRAPPAI").
dico("F", 7, "FRAPPAS").
dico("F", 7, "FRAPPAT").
dico("F", 7, "FRAPPEE").
dico("F", 7, "FRAPPER").
dico("F", 7, "FRAPPES").
dico("F", 7, "FRAPPEZ").
dico("F", 7, "FRASAIS").
dico("F", 7, "FRASAIT").
dico("F", 7, "FRASANT").
dico("F", 7, "FRASEES").
dico("F", 7, "FRASENT").
dico("F", 7, "FRASERA").
dico("F", 7, "FRASIEZ").
dico("F", 7, "FRASILS").
dico("F", 7, "FRASONS").
dico("F", 7, "FRASQUE").
dico("F", 7, "FRATERS").
dico("F", 7, "FRATRIE").
dico("F", 7, "FRAUDAI").
dico("F", 7, "FRAUDAS").
dico("F", 7, "FRAUDAT").
dico("F", 7, "FRAUDEE").
dico("F", 7, "FRAUDER").
dico("F", 7, "FRAUDES").
dico("F", 7, "FRAUDEZ").
dico("F", 7, "FRAYAGE").
dico("F", 7, "FRAYAIS").
dico("F", 7, "FRAYAIT").
dico("F", 7, "FRAYANT").
dico("F", 7, "FRAYEES").
dico("F", 7, "FRAYENT").
dico("F", 7, "FRAYERA").
dico("F", 7, "FRAYERE").
dico("F", 7, "FRAYEUR").
dico("F", 7, "FRAYIEZ").
dico("F", 7, "FRAYOIR").
dico("F", 7, "FRAYONS").
dico("F", 7, "FRAYURE").
dico("F", 7, "FREDONS").
dico("F", 7, "FREESIA").
dico("F", 7, "FREEZER").
dico("F", 7, "FREGATA").
dico("F", 7, "FREGATE").
dico("F", 7, "FREINAI").
dico("F", 7, "FREINAS").
dico("F", 7, "FREINAT").
dico("F", 7, "FREINEE").
dico("F", 7, "FREINER").
dico("F", 7, "FREINES").
dico("F", 7, "FREINEZ").
dico("F", 7, "FREINTE").
dico("F", 7, "FRELATA").
dico("F", 7, "FRELATE").
dico("F", 7, "FRELONS").
dico("F", 7, "FREMIRA").
dico("F", 7, "FRENAIE").
dico("F", 7, "FREROTS").
dico("F", 7, "FRESQUE").
dico("F", 7, "FRETAIS").
dico("F", 7, "FRETAIT").
dico("F", 7, "FRETANT").
dico("F", 7, "FRETEES").
dico("F", 7, "FRETENT").
dico("F", 7, "FRETERA").
dico("F", 7, "FRETEUR").
dico("F", 7, "FRETIEZ").
dico("F", 7, "FRETINS").
dico("F", 7, "FRETONS").
dico("F", 7, "FRETTAI").
dico("F", 7, "FRETTAS").
dico("F", 7, "FRETTAT").
dico("F", 7, "FRETTEE").
dico("F", 7, "FRETTER").
dico("F", 7, "FRETTES").
dico("F", 7, "FRETTEZ").
dico("F", 7, "FRIABLE").
dico("F", 7, "FRIANDE").
dico("F", 7, "FRIANDS").
dico("F", 7, "FRICHES").
dico("F", 7, "FRICHTI").
dico("F", 7, "FRICOTA").
dico("F", 7, "FRICOTE").
dico("F", 7, "FRICOTS").
dico("F", 7, "FRIGIDE").
dico("F", 7, "FRILEUX").
dico("F", 7, "FRIMAIS").
dico("F", 7, "FRIMAIT").
dico("F", 7, "FRIMANT").
dico("F", 7, "FRIMEES").
dico("F", 7, "FRIMENT").
dico("F", 7, "FRIMERA").
dico("F", 7, "FRIMEUR").
dico("F", 7, "FRIMIEZ").
dico("F", 7, "FRIMONS").
dico("F", 7, "FRINGUA").
dico("F", 7, "FRINGUE").
dico("F", 7, "FRIPAIS").
dico("F", 7, "FRIPAIT").
dico("F", 7, "FRIPANT").
dico("F", 7, "FRIPEES").
dico("F", 7, "FRIPENT").
dico("F", 7, "FRIPERA").
dico("F", 7, "FRIPIER").
dico("F", 7, "FRIPIEZ").
dico("F", 7, "FRIPONS").
dico("F", 7, "FRIQUEE").
dico("F", 7, "FRIQUES").
dico("F", 7, "FRIQUET").
dico("F", 7, "FRIRAIS").
dico("F", 7, "FRIRAIT").
dico("F", 7, "FRIRIEZ").
dico("F", 7, "FRIRONS").
dico("F", 7, "FRIRONT").
dico("F", 7, "FRISAGE").
dico("F", 7, "FRISAIS").
dico("F", 7, "FRISAIT").
dico("F", 7, "FRISANT").
dico("F", 7, "FRISBEE").
dico("F", 7, "FRISEES").
dico("F", 7, "FRISENT").
dico("F", 7, "FRISERA").
dico("F", 7, "FRISIEZ").
dico("F", 7, "FRISKOS").
dico("F", 7, "FRISONS").
dico("F", 7, "FRISSON").
dico("F", 7, "FRISURE").
dico("F", 7, "FRITAIS").
dico("F", 7, "FRITAIT").
dico("F", 7, "FRITANT").
dico("F", 7, "FRITEES").
dico("F", 7, "FRITENT").
dico("F", 7, "FRITERA").
dico("F", 7, "FRITIEZ").
dico("F", 7, "FRITONS").
dico("F", 7, "FRITTAI").
dico("F", 7, "FRITTAS").
dico("F", 7, "FRITTAT").
dico("F", 7, "FRITTEE").
dico("F", 7, "FRITTER").
dico("F", 7, "FRITTES").
dico("F", 7, "FRITTEZ").
dico("F", 7, "FRITURE").
dico("F", 7, "FRIVOLE").
dico("F", 7, "FROCARD").
dico("F", 7, "FROIDES").
dico("F", 7, "FROISSA").
dico("F", 7, "FROISSE").
dico("F", 7, "FROLAIS").
dico("F", 7, "FROLAIT").
dico("F", 7, "FROLANT").
dico("F", 7, "FROLEES").
dico("F", 7, "FROLENT").
dico("F", 7, "FROLERA").
dico("F", 7, "FROLEUR").
dico("F", 7, "FROLIEZ").
dico("F", 7, "FROLONS").
dico("F", 7, "FROMAGE").
dico("F", 7, "FROMEGI").
dico("F", 7, "FROMENT").
dico("F", 7, "FROMGIS").
dico("F", 7, "FROMTON").
dico("F", 7, "FRONCAI").
dico("F", 7, "FRONCAS").
dico("F", 7, "FRONCAT").
dico("F", 7, "FRONCEE").
dico("F", 7, "FRONCER").
dico("F", 7, "FRONCES").
dico("F", 7, "FRONCEZ").
dico("F", 7, "FRONCIS").
dico("F", 7, "FRONDAI").
dico("F", 7, "FRONDAS").
dico("F", 7, "FRONDAT").
dico("F", 7, "FRONDEE").
dico("F", 7, "FRONDER").
dico("F", 7, "FRONDES").
dico("F", 7, "FRONDEZ").
dico("F", 7, "FRONSAC").
dico("F", 7, "FRONTAL").
dico("F", 7, "FRONTON").
dico("F", 7, "FROTTAI").
dico("F", 7, "FROTTAS").
dico("F", 7, "FROTTAT").
dico("F", 7, "FROTTEE").
dico("F", 7, "FROTTER").
dico("F", 7, "FROTTES").
dico("F", 7, "FROTTEZ").
dico("F", 7, "FROTTIS").
dico("F", 7, "FROUAIS").
dico("F", 7, "FROUAIT").
dico("F", 7, "FROUANT").
dico("F", 7, "FROUENT").
dico("F", 7, "FROUERA").
dico("F", 7, "FROUIEZ").
dico("F", 7, "FROUONS").
dico("F", 7, "FROUSSE").
dico("F", 7, "FRUCTUS").
dico("F", 7, "FRUGALE").
dico("F", 7, "FRUGAUX").
dico("F", 7, "FRUITEE").
dico("F", 7, "FRUITES").
dico("F", 7, "FRUSTES").
dico("F", 7, "FRUSTRA").
dico("F", 7, "FRUSTRE").
dico("F", 7, "FUCACEE").
dico("F", 7, "FUCALES").
dico("F", 7, "FUCHSIA").
dico("F", 7, "FUEGIEN").
dico("F", 7, "FUGACES").
dico("F", 7, "FUGITIF").
dico("F", 7, "FUGUAIS").
dico("F", 7, "FUGUAIT").
dico("F", 7, "FUGUANT").
dico("F", 7, "FUGUEES").
dico("F", 7, "FUGUENT").
dico("F", 7, "FUGUERA").
dico("F", 7, "FUGUEUR").
dico("F", 7, "FUGUIEZ").
dico("F", 7, "FUGUONS").
dico("F", 7, "FUHRERS").
dico("F", 7, "FUIRAIS").
dico("F", 7, "FUIRAIT").
dico("F", 7, "FUIRENT").
dico("F", 7, "FUIRIEZ").
dico("F", 7, "FUIRONS").
dico("F", 7, "FUIRONT").
dico("F", 7, "FUISSES").
dico("F", 7, "FULGORE").
dico("F", 7, "FULGURA").
dico("F", 7, "FULGURE").
dico("F", 7, "FULMINA").
dico("F", 7, "FULMINE").
dico("F", 7, "FUMABLE").
dico("F", 7, "FUMAGES").
dico("F", 7, "FUMAMES").
dico("F", 7, "FUMANTE").
dico("F", 7, "FUMANTS").
dico("F", 7, "FUMASSE").
dico("F", 7, "FUMATES").
dico("F", 7, "FUMERAI").
dico("F", 7, "FUMERAS").
dico("F", 7, "FUMEREZ").
dico("F", 7, "FUMERIE").
dico("F", 7, "FUMERON").
dico("F", 7, "FUMETTE").
dico("F", 7, "FUMEURS").
dico("F", 7, "FUMEUSE").
dico("F", 7, "FUMIERS").
dico("F", 7, "FUMIGEA").
dico("F", 7, "FUMIGEE").
dico("F", 7, "FUMIGER").
dico("F", 7, "FUMIGES").
dico("F", 7, "FUMIGEZ").
dico("F", 7, "FUMIONS").
dico("F", 7, "FUMISTE").
dico("F", 7, "FUMOIRS").
dico("F", 7, "FUMURES").
dico("F", 7, "FUNEBRE").
dico("F", 7, "FUNESTE").
dico("F", 7, "FURANES").
dico("F", 7, "FURANNE").
dico("F", 7, "FURCULA").
dico("F", 7, "FURETAI").
dico("F", 7, "FURETAS").
dico("F", 7, "FURETAT").
dico("F", 7, "FURETER").
dico("F", 7, "FURETES").
dico("F", 7, "FURETEZ").
dico("F", 7, "FUREURS").
dico("F", 7, "FURIEUX").
dico("F", 7, "FURIOSO").
dico("F", 7, "FUROLES").
dico("F", 7, "FURTIFS").
dico("F", 7, "FURTIVE").
dico("F", 7, "FUSAINS").
dico("F", 7, "FUSAMES").
dico("F", 7, "FUSANTE").
dico("F", 7, "FUSANTS").
dico("F", 7, "FUSASSE").
dico("F", 7, "FUSATES").
dico("F", 7, "FUSCINE").
dico("F", 7, "FUSEAUX").
dico("F", 7, "FUSELAI").
dico("F", 7, "FUSELAS").
dico("F", 7, "FUSELAT").
dico("F", 7, "FUSELEE").
dico("F", 7, "FUSELER").
dico("F", 7, "FUSELES").
dico("F", 7, "FUSELEZ").
dico("F", 7, "FUSELLE").
dico("F", 7, "FUSERAI").
dico("F", 7, "FUSERAS").
dico("F", 7, "FUSEREZ").
dico("F", 7, "FUSETTE").
dico("F", 7, "FUSIBLE").
dico("F", 7, "FUSILLA").
dico("F", 7, "FUSILLE").
dico("F", 7, "FUSIONS").
dico("F", 7, "FUSSENT").
dico("F", 7, "FUSSIEZ").
dico("F", 7, "FUSTETS").
dico("F", 7, "FUSTIGE").
dico("F", 7, "FUSTINE").
dico("F", 7, "FUTAIES").
dico("F", 7, "FUTAINE").
dico("F", 7, "FUTILES").
dico("F", 7, "FUTURES").
dico("F", 7, "FUXEENS").
dico("F", 7, "FUYANTE").
dico("F", 7, "FUYANTS").
dico("F", 7, "FUYARDE").
dico("F", 7, "FUYARDS").
dico("F", 7, "FUYIONS").
