dico("G", 5, "GABAS").
dico("G", 5, "GABIE").
dico("G", 5, "GABLE").
dico("G", 5, "GACHA").
dico("G", 5, "GACHE").
dico("G", 5, "GADES").
dico("G", 5, "GADIN").
dico("G", 5, "GADJE").
dico("G", 5, "GADJO").
dico("G", 5, "GAFFA").
dico("G", 5, "GAFFE").
dico("G", 5, "GAGAS").
dico("G", 5, "GAGEA").
dico("G", 5, "GAGEE").
dico("G", 5, "GAGER").
dico("G", 5, "GAGES").
dico("G", 5, "GAGEZ").
dico("G", 5, "GAGNA").
dico("G", 5, "GAGNE").
dico("G", 5, "GAIAC").
dico("G", 5, "GAIES").
dico("G", 5, "GAINA").
dico("G", 5, "GAINE").
dico("G", 5, "GAINS").
dico("G", 5, "GAITE").
dico("G", 5, "GAIZE").
dico("G", 5, "GALAS").
dico("G", 5, "GALBA").
dico("G", 5, "GALBE").
dico("G", 5, "GALES").
dico("G", 5, "GALET").
dico("G", 5, "GALLA").
dico("G", 5, "GALLE").
dico("G", 5, "GALLO").
dico("G", 5, "GALON").
dico("G", 5, "GALOP").
dico("G", 5, "GAMAY").
dico("G", 5, "GAMBA").
dico("G", 5, "GAMBE").
dico("G", 5, "GAMET").
dico("G", 5, "GAMIN").
dico("G", 5, "GAMMA").
dico("G", 5, "GAMME").
dico("G", 5, "GAMOU").
dico("G", 5, "GANGA").
dico("G", 5, "GANGS").
dico("G", 5, "GANSA").
dico("G", 5, "GANSE").
dico("G", 5, "GANTA").
dico("G", 5, "GANTE").
dico("G", 5, "GANTS").
dico("G", 5, "GARAI").
dico("G", 5, "GARAS").
dico("G", 5, "GARAT").
dico("G", 5, "GARCE").
dico("G", 5, "GARDA").
dico("G", 5, "GARDE").
dico("G", 5, "GAREE").
dico("G", 5, "GARER").
dico("G", 5, "GARES").
dico("G", 5, "GAREZ").
dico("G", 5, "GARIS").
dico("G", 5, "GARNI").
dico("G", 5, "GAROU").
dico("G", 5, "GASPI").
dico("G", 5, "GATAI").
dico("G", 5, "GATAS").
dico("G", 5, "GATAT").
dico("G", 5, "GATEE").
dico("G", 5, "GATER").
dico("G", 5, "GATES").
dico("G", 5, "GATEZ").
dico("G", 5, "GATTA").
dico("G", 5, "GATTE").
dico("G", 5, "GAUDE").
dico("G", 5, "GAUDI").
dico("G", 5, "GAULA").
dico("G", 5, "GAULE").
dico("G", 5, "GAUPE").
dico("G", 5, "GAURS").
dico("G", 5, "GAUSS").
dico("G", 5, "GAVAI").
dico("G", 5, "GAVAS").
dico("G", 5, "GAVAT").
dico("G", 5, "GAVEE").
dico("G", 5, "GAVER").
dico("G", 5, "GAVES").
dico("G", 5, "GAVEZ").
dico("G", 5, "GAVOT").
dico("G", 5, "GAYAL").
dico("G", 5, "GAZAI").
dico("G", 5, "GAZAS").
dico("G", 5, "GAZAT").
dico("G", 5, "GAZEE").
dico("G", 5, "GAZER").
dico("G", 5, "GAZES").
dico("G", 5, "GAZEZ").
dico("G", 5, "GAZON").
dico("G", 5, "GAZOU").
dico("G", 5, "GEAIS").
dico("G", 5, "GEANT").
dico("G", 5, "GECKO").
dico("G", 5, "GEINS").
dico("G", 5, "GEINT").
dico("G", 5, "GELAI").
dico("G", 5, "GELAS").
dico("G", 5, "GELAT").
dico("G", 5, "GELEE").
dico("G", 5, "GELER").
dico("G", 5, "GELES").
dico("G", 5, "GELEZ").
dico("G", 5, "GELIF").
dico("G", 5, "GEMIE").
dico("G", 5, "GEMIR").
dico("G", 5, "GEMIS").
dico("G", 5, "GEMIT").
dico("G", 5, "GEMMA").
dico("G", 5, "GEMME").
dico("G", 5, "GENAI").
dico("G", 5, "GENAL").
dico("G", 5, "GENAS").
dico("G", 5, "GENAT").
dico("G", 5, "GENEE").
dico("G", 5, "GENER").
dico("G", 5, "GENES").
dico("G", 5, "GENET").
dico("G", 5, "GENEZ").
dico("G", 5, "GENIE").
dico("G", 5, "GENOU").
dico("G", 5, "GENRE").
dico("G", 5, "GENTE").
dico("G", 5, "GENTS").
dico("G", 5, "GEODE").
dico("G", 5, "GEOLE").
dico("G", 5, "GERAI").
dico("G", 5, "GERAS").
dico("G", 5, "GERAT").
dico("G", 5, "GERBA").
dico("G", 5, "GERBE").
dico("G", 5, "GERCA").
dico("G", 5, "GERCE").
dico("G", 5, "GEREE").
dico("G", 5, "GERER").
dico("G", 5, "GERES").
dico("G", 5, "GEREZ").
dico("G", 5, "GERMA").
dico("G", 5, "GERME").
dico("G", 5, "GESIR").
dico("G", 5, "GESSE").
dico("G", 5, "GESTE").
dico("G", 5, "GIBET").
dico("G", 5, "GIBUS").
dico("G", 5, "GICLA").
dico("G", 5, "GICLE").
dico("G", 5, "GIFLA").
dico("G", 5, "GIFLE").
dico("G", 5, "GIFTS").
dico("G", 5, "GIGAS").
dico("G", 5, "GIGOT").
dico("G", 5, "GIGUA").
dico("G", 5, "GIGUE").
dico("G", 5, "GILDE").
dico("G", 5, "GILET").
dico("G", 5, "GILLE").
dico("G", 5, "GIRIE").
dico("G", 5, "GIRLS").
dico("G", 5, "GIRON").
dico("G", 5, "GISEZ").
dico("G", 5, "GITAI").
dico("G", 5, "GITAN").
dico("G", 5, "GITAS").
dico("G", 5, "GITAT").
dico("G", 5, "GITEE").
dico("G", 5, "GITER").
dico("G", 5, "GITES").
dico("G", 5, "GITEZ").
dico("G", 5, "GITON").
dico("G", 5, "GIVRA").
dico("G", 5, "GIVRE").
dico("G", 5, "GLACA").
dico("G", 5, "GLACE").
dico("G", 5, "GLANA").
dico("G", 5, "GLAND").
dico("G", 5, "GLANE").
dico("G", 5, "GLAPI").
dico("G", 5, "GLASS").
dico("G", 5, "GLATI").
dico("G", 5, "GLEBE").
dico("G", 5, "GLENA").
dico("G", 5, "GLENE").
dico("G", 5, "GLIAL").
dico("G", 5, "GLIDE").
dico("G", 5, "GLIES").
dico("G", 5, "GLOBE").
dico("G", 5, "GLOME").
dico("G", 5, "GLOSA").
dico("G", 5, "GLOSE").
dico("G", 5, "GLUAI").
dico("G", 5, "GLUAS").
dico("G", 5, "GLUAT").
dico("G", 5, "GLUAU").
dico("G", 5, "GLUEE").
dico("G", 5, "GLUER").
dico("G", 5, "GLUES").
dico("G", 5, "GLUEZ").
dico("G", 5, "GLUIS").
dico("G", 5, "GLUME").
dico("G", 5, "GLUON").
dico("G", 5, "GNETE").
dico("G", 5, "GNOLE").
dico("G", 5, "GNOME").
dico("G", 5, "GNONS").
dico("G", 5, "GNOSE").
dico("G", 5, "GNOUF").
dico("G", 5, "GNOUS").
dico("G", 5, "GOALS").
dico("G", 5, "GOBAI").
dico("G", 5, "GOBAS").
dico("G", 5, "GOBAT").
dico("G", 5, "GOBEE").
dico("G", 5, "GOBER").
dico("G", 5, "GOBES").
dico("G", 5, "GOBEZ").
dico("G", 5, "GOBIE").
dico("G", 5, "GODAI").
dico("G", 5, "GODAS").
dico("G", 5, "GODAT").
dico("G", 5, "GODEE").
dico("G", 5, "GODER").
dico("G", 5, "GODES").
dico("G", 5, "GODET").
dico("G", 5, "GODEZ").
dico("G", 5, "GOGEA").
dico("G", 5, "GOGEE").
dico("G", 5, "GOGER").
dico("G", 5, "GOGES").
dico("G", 5, "GOGEZ").
dico("G", 5, "GOGLU").
dico("G", 5, "GOGOS").
dico("G", 5, "GOLEE").
dico("G", 5, "GOLEM").
dico("G", 5, "GOLFA").
dico("G", 5, "GOLFE").
dico("G", 5, "GOLFS").
dico("G", 5, "GOMBO").
dico("G", 5, "GOMMA").
dico("G", 5, "GOMME").
dico("G", 5, "GONDS").
dico("G", 5, "GONES").
dico("G", 5, "GONGS").
dico("G", 5, "GONIO").
dico("G", 5, "GONZE").
dico("G", 5, "GOPAK").
dico("G", 5, "GORDS").
dico("G", 5, "GORES").
dico("G", 5, "GORET").
dico("G", 5, "GORGE").
dico("G", 5, "GORON").
dico("G", 5, "GOSSA").
dico("G", 5, "GOSSE").
dico("G", 5, "GOTHA").
dico("G", 5, "GOTHE").
dico("G", 5, "GOTHS").
dico("G", 5, "GOTON").
dico("G", 5, "GOUDA").
dico("G", 5, "GOUET").
dico("G", 5, "GOUGE").
dico("G", 5, "GOULE").
dico("G", 5, "GOULU").
dico("G", 5, "GOUMS").
dico("G", 5, "GOURA").
dico("G", 5, "GOURD").
dico("G", 5, "GOURE").
dico("G", 5, "GOURS").
dico("G", 5, "GOUTA").
dico("G", 5, "GOUTE").
dico("G", 5, "GOUTS").
dico("G", 5, "GOYIM").
dico("G", 5, "GRAAL").
dico("G", 5, "GRACE").
dico("G", 5, "GRADA").
dico("G", 5, "GRADE").
dico("G", 5, "GRAFF").
dico("G", 5, "GRAIN").
dico("G", 5, "GRANA").
dico("G", 5, "GRAND").
dico("G", 5, "GRAUS").
dico("G", 5, "GRAUX").
dico("G", 5, "GRAVA").
dico("G", 5, "GRAVE").
dico("G", 5, "GRAVI").
dico("G", 5, "GRAYS").
dico("G", 5, "GREAI").
dico("G", 5, "GREAS").
dico("G", 5, "GREAT").
dico("G", 5, "GREBE").
dico("G", 5, "GRECS").
dico("G", 5, "GREEE").
dico("G", 5, "GREEN").
dico("G", 5, "GREER").
dico("G", 5, "GREES").
dico("G", 5, "GREEZ").
dico("G", 5, "GREGE").
dico("G", 5, "GRELA").
dico("G", 5, "GRELE").
dico("G", 5, "GRENA").
dico("G", 5, "GRENE").
dico("G", 5, "GRENU").
dico("G", 5, "GRESA").
dico("G", 5, "GRESE").
dico("G", 5, "GREVA").
dico("G", 5, "GREVE").
dico("G", 5, "GRIEF").
dico("G", 5, "GRILL").
dico("G", 5, "GRILS").
dico("G", 5, "GRIMA").
dico("G", 5, "GRIME").
dico("G", 5, "GRIOT").
dico("G", 5, "GRIPS").
dico("G", 5, "GRISA").
dico("G", 5, "GRISE").
dico("G", 5, "GRIVE").
dico("G", 5, "GROGS").
dico("G", 5, "GROIE").
dico("G", 5, "GROIN").
dico("G", 5, "GROLE").
dico("G", 5, "GROOM").
dico("G", 5, "GROUP").
dico("G", 5, "GRUAU").
dico("G", 5, "GRUES").
dico("G", 5, "GRUGE").
dico("G", 5, "GRUME").
dico("G", 5, "GRUON").
dico("G", 5, "GRUTA").
dico("G", 5, "GRUTE").
dico("G", 5, "GUAIS").
dico("G", 5, "GUANO").
dico("G", 5, "GUEAI").
dico("G", 5, "GUEAS").
dico("G", 5, "GUEAT").
dico("G", 5, "GUEDE").
dico("G", 5, "GUEEE").
dico("G", 5, "GUEER").
dico("G", 5, "GUEES").
dico("G", 5, "GUEEZ").
dico("G", 5, "GUEPE").
dico("G", 5, "GUERE").
dico("G", 5, "GUERI").
dico("G", 5, "GUETE").
dico("G", 5, "GUETS").
dico("G", 5, "GUEUX").
dico("G", 5, "GUEZE").
dico("G", 5, "GUGUS").
dico("G", 5, "GUIBS").
dico("G", 5, "GUIDA").
dico("G", 5, "GUIDE").
dico("G", 5, "GUIPA").
dico("G", 5, "GUIPE").
dico("G", 5, "GUISE").
dico("G", 5, "GUPPY").
dico("G", 5, "GURUS").
dico("G", 5, "GUSSE").
dico("G", 5, "GUYOT").
dico("G", 5, "GUZLA").
dico("G", 5, "GYPSE").
dico("G", 5, "GYRIN").
