dico("G", 6, "GABARE").
dico("G", 6, "GABBRO").
dico("G", 6, "GABIER").
dico("G", 6, "GABIES").
dico("G", 6, "GABION").
dico("G", 6, "GABLES").
dico("G", 6, "GACHAI").
dico("G", 6, "GACHAS").
dico("G", 6, "GACHAT").
dico("G", 6, "GACHEE").
dico("G", 6, "GACHER").
dico("G", 6, "GACHES").
dico("G", 6, "GACHEZ").
dico("G", 6, "GACHIS").
dico("G", 6, "GADGET").
dico("G", 6, "GADIDE").
dico("G", 6, "GADINS").
dico("G", 6, "GADJOS").
dico("G", 6, "GADOUE").
dico("G", 6, "GAFFAI").
dico("G", 6, "GAFFAS").
dico("G", 6, "GAFFAT").
dico("G", 6, "GAFFEE").
dico("G", 6, "GAFFER").
dico("G", 6, "GAFFES").
dico("G", 6, "GAFFEZ").
dico("G", 6, "GAGAKU").
dico("G", 6, "GAGEAI").
dico("G", 6, "GAGEAS").
dico("G", 6, "GAGEAT").
dico("G", 6, "GAGEES").
dico("G", 6, "GAGENT").
dico("G", 6, "GAGERA").
dico("G", 6, "GAGEUR").
dico("G", 6, "GAGIEZ").
dico("G", 6, "GAGMAN").
dico("G", 6, "GAGMEN").
dico("G", 6, "GAGNAI").
dico("G", 6, "GAGNAS").
dico("G", 6, "GAGNAT").
dico("G", 6, "GAGNEE").
dico("G", 6, "GAGNER").
dico("G", 6, "GAGNES").
dico("G", 6, "GAGNEZ").
dico("G", 6, "GAIACS").
dico("G", 6, "GAIETE").
dico("G", 6, "GAINAI").
dico("G", 6, "GAINAS").
dico("G", 6, "GAINAT").
dico("G", 6, "GAINEE").
dico("G", 6, "GAINER").
dico("G", 6, "GAINES").
dico("G", 6, "GAINEZ").
dico("G", 6, "GAITES").
dico("G", 6, "GAIZES").
dico("G", 6, "GALAGO").
dico("G", 6, "GALANT").
dico("G", 6, "GALATE").
dico("G", 6, "GALBAI").
dico("G", 6, "GALBAS").
dico("G", 6, "GALBAT").
dico("G", 6, "GALBEE").
dico("G", 6, "GALBER").
dico("G", 6, "GALBES").
dico("G", 6, "GALBEZ").
dico("G", 6, "GALEJA").
dico("G", 6, "GALEJE").
dico("G", 6, "GALENE").
dico("G", 6, "GALERA").
dico("G", 6, "GALERE").
dico("G", 6, "GALETA").
dico("G", 6, "GALETE").
dico("G", 6, "GALETS").
dico("G", 6, "GALEUX").
dico("G", 6, "GALGAL").
dico("G", 6, "GALION").
dico("G", 6, "GALLAS").
dico("G", 6, "GALLEC").
dico("G", 6, "GALLES").
dico("G", 6, "GALLON").
dico("G", 6, "GALLOS").
dico("G", 6, "GALLOT").
dico("G", 6, "GALLUP").
dico("G", 6, "GALONS").
dico("G", 6, "GALOPA").
dico("G", 6, "GALOPE").
dico("G", 6, "GALOPS").
dico("G", 6, "GALURE").
dico("G", 6, "GAMAYS").
dico("G", 6, "GAMBAS").
dico("G", 6, "GAMBES").
dico("G", 6, "GAMBIT").
dico("G", 6, "GAMETE").
dico("G", 6, "GAMETS").
dico("G", 6, "GAMINA").
dico("G", 6, "GAMINE").
dico("G", 6, "GAMINS").
dico("G", 6, "GAMMEE").
dico("G", 6, "GAMMES").
dico("G", 6, "GAMMON").
dico("G", 6, "GAMOUS").
dico("G", 6, "GANDIN").
dico("G", 6, "GANGAS").
dico("G", 6, "GANGUE").
dico("G", 6, "GANSAI").
dico("G", 6, "GANSAS").
dico("G", 6, "GANSAT").
dico("G", 6, "GANSEE").
dico("G", 6, "GANSER").
dico("G", 6, "GANSES").
dico("G", 6, "GANSEZ").
dico("G", 6, "GANTAI").
dico("G", 6, "GANTAS").
dico("G", 6, "GANTAT").
dico("G", 6, "GANTEE").
dico("G", 6, "GANTER").
dico("G", 6, "GANTES").
dico("G", 6, "GANTEZ").
dico("G", 6, "GARAGE").
dico("G", 6, "GARAIS").
dico("G", 6, "GARAIT").
dico("G", 6, "GARANT").
dico("G", 6, "GARCES").
dico("G", 6, "GARCON").
dico("G", 6, "GARDAI").
dico("G", 6, "GARDAS").
dico("G", 6, "GARDAT").
dico("G", 6, "GARDEE").
dico("G", 6, "GARDER").
dico("G", 6, "GARDES").
dico("G", 6, "GARDEZ").
dico("G", 6, "GARDON").
dico("G", 6, "GAREES").
dico("G", 6, "GARENT").
dico("G", 6, "GARERA").
dico("G", 6, "GARIEZ").
dico("G", 6, "GARNIE").
dico("G", 6, "GARNIR").
dico("G", 6, "GARNIS").
dico("G", 6, "GARNIT").
dico("G", 6, "GARONS").
dico("G", 6, "GAROUS").
dico("G", 6, "GARROT").
dico("G", 6, "GASCON").
dico("G", 6, "GASOIL").
dico("G", 6, "GASPIS").
dico("G", 6, "GATAIS").
dico("G", 6, "GATAIT").
dico("G", 6, "GATANT").
dico("G", 6, "GATEAU").
dico("G", 6, "GATEES").
dico("G", 6, "GATENT").
dico("G", 6, "GATERA").
dico("G", 6, "GATEUR").
dico("G", 6, "GATEUX").
dico("G", 6, "GATIEZ").
dico("G", 6, "GATINE").
dico("G", 6, "GATION").
dico("G", 6, "GATONS").
dico("G", 6, "GATTAI").
dico("G", 6, "GATTAS").
dico("G", 6, "GATTAT").
dico("G", 6, "GATTEE").
dico("G", 6, "GATTER").
dico("G", 6, "GATTES").
dico("G", 6, "GATTEZ").
dico("G", 6, "GAUCHE").
dico("G", 6, "GAUCHI").
dico("G", 6, "GAUCHO").
dico("G", 6, "GAUDES").
dico("G", 6, "GAUDIE").
dico("G", 6, "GAUDIR").
dico("G", 6, "GAUDIS").
dico("G", 6, "GAUDIT").
dico("G", 6, "GAUFRA").
dico("G", 6, "GAUFRE").
dico("G", 6, "GAULAI").
dico("G", 6, "GAULAS").
dico("G", 6, "GAULAT").
dico("G", 6, "GAULEE").
dico("G", 6, "GAULER").
dico("G", 6, "GAULES").
dico("G", 6, "GAULEZ").
dico("G", 6, "GAULIS").
dico("G", 6, "GAUPES").
dico("G", 6, "GAUSSA").
dico("G", 6, "GAUSSE").
dico("G", 6, "GAVAGE").
dico("G", 6, "GAVAIS").
dico("G", 6, "GAVAIT").
dico("G", 6, "GAVANT").
dico("G", 6, "GAVEES").
dico("G", 6, "GAVENT").
dico("G", 6, "GAVERA").
dico("G", 6, "GAVEUR").
dico("G", 6, "GAVIAL").
dico("G", 6, "GAVIEZ").
dico("G", 6, "GAVONS").
dico("G", 6, "GAVOTE").
dico("G", 6, "GAVOTS").
dico("G", 6, "GAYALS").
dico("G", 6, "GAZAGE").
dico("G", 6, "GAZAIS").
dico("G", 6, "GAZAIT").
dico("G", 6, "GAZANT").
dico("G", 6, "GAZEES").
dico("G", 6, "GAZENT").
dico("G", 6, "GAZERA").
dico("G", 6, "GAZEUX").
dico("G", 6, "GAZIER").
dico("G", 6, "GAZIEZ").
dico("G", 6, "GAZOLE").
dico("G", 6, "GAZONS").
dico("G", 6, "GAZOUS").
dico("G", 6, "GEANTE").
dico("G", 6, "GEANTS").
dico("G", 6, "GECKOS").
dico("G", 6, "GEGENE").
dico("G", 6, "GEIGNE").
dico("G", 6, "GEISHA").
dico("G", 6, "GELAIS").
dico("G", 6, "GELAIT").
dico("G", 6, "GELANT").
dico("G", 6, "GELEES").
dico("G", 6, "GELENT").
dico("G", 6, "GELERA").
dico("G", 6, "GELIEZ").
dico("G", 6, "GELIFS").
dico("G", 6, "GELINE").
dico("G", 6, "GELIVE").
dico("G", 6, "GELONS").
dico("G", 6, "GELOSE").
dico("G", 6, "GELULE").
dico("G", 6, "GELURE").
dico("G", 6, "GEMEAU").
dico("G", 6, "GEMIES").
dico("G", 6, "GEMINA").
dico("G", 6, "GEMINE").
dico("G", 6, "GEMIRA").
dico("G", 6, "GEMMAI").
dico("G", 6, "GEMMAS").
dico("G", 6, "GEMMAT").
dico("G", 6, "GEMMEE").
dico("G", 6, "GEMMER").
dico("G", 6, "GEMMES").
dico("G", 6, "GEMMEZ").
dico("G", 6, "GENAIS").
dico("G", 6, "GENAIT").
dico("G", 6, "GENALE").
dico("G", 6, "GENANT").
dico("G", 6, "GENAUX").
dico("G", 6, "GENDRE").
dico("G", 6, "GENEES").
dico("G", 6, "GENENT").
dico("G", 6, "GENEPI").
dico("G", 6, "GENERA").
dico("G", 6, "GENERE").
dico("G", 6, "GENESE").
dico("G", 6, "GENETS").
dico("G", 6, "GENEUR").
dico("G", 6, "GENIAL").
dico("G", 6, "GENIEN").
dico("G", 6, "GENIES").
dico("G", 6, "GENIEZ").
dico("G", 6, "GENOIS").
dico("G", 6, "GENOME").
dico("G", 6, "GENONS").
dico("G", 6, "GENOUX").
dico("G", 6, "GENRES").
dico("G", 6, "GENTES").
dico("G", 6, "GENTIL").
dico("G", 6, "GENTRY").
dico("G", 6, "GEODES").
dico("G", 6, "GEOIDE").
dico("G", 6, "GEOLES").
dico("G", 6, "GERAIS").
dico("G", 6, "GERAIT").
dico("G", 6, "GERANT").
dico("G", 6, "GERBAI").
dico("G", 6, "GERBAS").
dico("G", 6, "GERBAT").
dico("G", 6, "GERBEE").
dico("G", 6, "GERBER").
dico("G", 6, "GERBES").
dico("G", 6, "GERBEZ").
dico("G", 6, "GERCAI").
dico("G", 6, "GERCAS").
dico("G", 6, "GERCAT").
dico("G", 6, "GERCEE").
dico("G", 6, "GERCER").
dico("G", 6, "GERCES").
dico("G", 6, "GERCEZ").
dico("G", 6, "GEREES").
dico("G", 6, "GERENT").
dico("G", 6, "GERERA").
dico("G", 6, "GERIEZ").
dico("G", 6, "GERMAI").
dico("G", 6, "GERMAS").
dico("G", 6, "GERMAT").
dico("G", 6, "GERMEE").
dico("G", 6, "GERMEN").
dico("G", 6, "GERMER").
dico("G", 6, "GERMES").
dico("G", 6, "GERMEZ").
dico("G", 6, "GERMON").
dico("G", 6, "GEROME").
dico("G", 6, "GERONS").
dico("G", 6, "GERRIS").
dico("G", 6, "GESIER").
dico("G", 6, "GESINE").
dico("G", 6, "GESSES").
dico("G", 6, "GESTES").
dico("G", 6, "GETTER").
dico("G", 6, "GEYSER").
dico("G", 6, "GHETTO").
dico("G", 6, "GHILDE").
dico("G", 6, "GIAOUR").
dico("G", 6, "GIBBON").
dico("G", 6, "GIBETS").
dico("G", 6, "GIBIER").
dico("G", 6, "GIBOIE").
dico("G", 6, "GIBOYA").
dico("G", 6, "GIBOYE").
dico("G", 6, "GICLAI").
dico("G", 6, "GICLAS").
dico("G", 6, "GICLAT").
dico("G", 6, "GICLEE").
dico("G", 6, "GICLER").
dico("G", 6, "GICLES").
dico("G", 6, "GICLEZ").
dico("G", 6, "GIFLAI").
dico("G", 6, "GIFLAS").
dico("G", 6, "GIFLAT").
dico("G", 6, "GIFLEE").
dico("G", 6, "GIFLER").
dico("G", 6, "GIFLES").
dico("G", 6, "GIFLEZ").
dico("G", 6, "GIGOLO").
dico("G", 6, "GIGOTA").
dico("G", 6, "GIGOTE").
dico("G", 6, "GIGOTS").
dico("G", 6, "GIGUAI").
dico("G", 6, "GIGUAS").
dico("G", 6, "GIGUAT").
dico("G", 6, "GIGUEE").
dico("G", 6, "GIGUER").
dico("G", 6, "GIGUES").
dico("G", 6, "GIGUEZ").
dico("G", 6, "GILDES").
dico("G", 6, "GILETS").
dico("G", 6, "GILLES").
dico("G", 6, "GINDRE").
dico("G", 6, "GINKGO").
dico("G", 6, "GIORNO").
dico("G", 6, "GIRAFE").
dico("G", 6, "GIRIES").
dico("G", 6, "GIROND").
dico("G", 6, "GIRONS").
dico("G", 6, "GISAIS").
dico("G", 6, "GISAIT").
dico("G", 6, "GISANT").
dico("G", 6, "GISENT").
dico("G", 6, "GISIEZ").
dico("G", 6, "GISONS").
dico("G", 6, "GITAGE").
dico("G", 6, "GITAIS").
dico("G", 6, "GITAIT").
dico("G", 6, "GITANE").
dico("G", 6, "GITANS").
dico("G", 6, "GITANT").
dico("G", 6, "GITEES").
dico("G", 6, "GITENT").
dico("G", 6, "GITERA").
dico("G", 6, "GITIEZ").
dico("G", 6, "GITONS").
dico("G", 6, "GIVRAI").
dico("G", 6, "GIVRAS").
dico("G", 6, "GIVRAT").
dico("G", 6, "GIVREE").
dico("G", 6, "GIVRER").
dico("G", 6, "GIVRES").
dico("G", 6, "GIVREZ").
dico("G", 6, "GLABRE").
dico("G", 6, "GLACAI").
dico("G", 6, "GLACAS").
dico("G", 6, "GLACAT").
dico("G", 6, "GLACEE").
dico("G", 6, "GLACER").
dico("G", 6, "GLACES").
dico("G", 6, "GLACEZ").
dico("G", 6, "GLACIS").
dico("G", 6, "GLACON").
dico("G", 6, "GLAIRA").
dico("G", 6, "GLAIRE").
dico("G", 6, "GLAISA").
dico("G", 6, "GLAISE").
dico("G", 6, "GLAIVE").
dico("G", 6, "GLANAI").
dico("G", 6, "GLANAS").
dico("G", 6, "GLANAT").
dico("G", 6, "GLANDA").
dico("G", 6, "GLANDE").
dico("G", 6, "GLANDS").
dico("G", 6, "GLANEE").
dico("G", 6, "GLANER").
dico("G", 6, "GLANES").
dico("G", 6, "GLANEZ").
dico("G", 6, "GLAPIE").
dico("G", 6, "GLAPIR").
dico("G", 6, "GLAPIS").
dico("G", 6, "GLAPIT").
dico("G", 6, "GLATIR").
dico("G", 6, "GLATIS").
dico("G", 6, "GLATIT").
dico("G", 6, "GLEBES").
dico("G", 6, "GLENAI").
dico("G", 6, "GLENAS").
dico("G", 6, "GLENAT").
dico("G", 6, "GLENEE").
dico("G", 6, "GLENER").
dico("G", 6, "GLENES").
dico("G", 6, "GLENEZ").
dico("G", 6, "GLIALE").
dico("G", 6, "GLIAUX").
dico("G", 6, "GLIDES").
dico("G", 6, "GLIOME").
dico("G", 6, "GLISSA").
dico("G", 6, "GLISSE").
dico("G", 6, "GLOBAL").
dico("G", 6, "GLOBES").
dico("G", 6, "GLOIRE").
dico("G", 6, "GLOMES").
dico("G", 6, "GLORIA").
dico("G", 6, "GLOSAI").
dico("G", 6, "GLOSAS").
dico("G", 6, "GLOSAT").
dico("G", 6, "GLOSEE").
dico("G", 6, "GLOSER").
dico("G", 6, "GLOSES").
dico("G", 6, "GLOSEZ").
dico("G", 6, "GLOTTE").
dico("G", 6, "GLUAIS").
dico("G", 6, "GLUAIT").
dico("G", 6, "GLUANT").
dico("G", 6, "GLUAUX").
dico("G", 6, "GLUEES").
dico("G", 6, "GLUENT").
dico("G", 6, "GLUERA").
dico("G", 6, "GLUIEZ").
dico("G", 6, "GLUMES").
dico("G", 6, "GLUONS").
dico("G", 6, "GLUTEN").
dico("G", 6, "GLYCOL").
dico("G", 6, "GLYPHE").
dico("G", 6, "GNAULE").
dico("G", 6, "GNEISS").
dico("G", 6, "GNETES").
dico("G", 6, "GNETUM").
dico("G", 6, "GNIOLE").
dico("G", 6, "GNIOUF").
dico("G", 6, "GNOLES").
dico("G", 6, "GNOMES").
dico("G", 6, "GNOMON").
dico("G", 6, "GNOSES").
dico("G", 6, "GNOSIE").
dico("G", 6, "GNOUFS").
dico("G", 6, "GOBAGE").
dico("G", 6, "GOBAIS").
dico("G", 6, "GOBAIT").
dico("G", 6, "GOBANT").
dico("G", 6, "GOBEES").
dico("G", 6, "GOBENT").
dico("G", 6, "GOBERA").
dico("G", 6, "GOBEUR").
dico("G", 6, "GOBIES").
dico("G", 6, "GOBIEZ").
dico("G", 6, "GOBONS").
dico("G", 6, "GODAGE").
dico("G", 6, "GODAIS").
dico("G", 6, "GODAIT").
dico("G", 6, "GODANT").
dico("G", 6, "GODEES").
dico("G", 6, "GODENT").
dico("G", 6, "GODERA").
dico("G", 6, "GODETS").
dico("G", 6, "GODIEZ").
dico("G", 6, "GODONS").
dico("G", 6, "GODRON").
dico("G", 6, "GOEMON").
dico("G", 6, "GOETIE").
dico("G", 6, "GOGEAI").
dico("G", 6, "GOGEAS").
dico("G", 6, "GOGEAT").
dico("G", 6, "GOGEES").
dico("G", 6, "GOGENT").
dico("G", 6, "GOGERA").
dico("G", 6, "GOGIEZ").
dico("G", 6, "GOGLUS").
dico("G", 6, "GOGUES").
dico("G", 6, "GOITRE").
dico("G", 6, "GOLDEN").
dico("G", 6, "GOLEES").
dico("G", 6, "GOLEMS").
dico("G", 6, "GOLFAI").
dico("G", 6, "GOLFAS").
dico("G", 6, "GOLFAT").
dico("G", 6, "GOLFER").
dico("G", 6, "GOLFES").
dico("G", 6, "GOLFEZ").
dico("G", 6, "GOMBOS").
dico("G", 6, "GOMINA").
dico("G", 6, "GOMINE").
dico("G", 6, "GOMMAI").
dico("G", 6, "GOMMAS").
dico("G", 6, "GOMMAT").
dico("G", 6, "GOMMEE").
dico("G", 6, "GOMMER").
dico("G", 6, "GOMMES").
dico("G", 6, "GOMMEZ").
dico("G", 6, "GONADE").
dico("G", 6, "GONFLA").
dico("G", 6, "GONFLE").
dico("G", 6, "GONIOS").
dico("G", 6, "GONZES").
dico("G", 6, "GOPAKS").
dico("G", 6, "GOPURA").
dico("G", 6, "GOREEN").
dico("G", 6, "GORETS").
dico("G", 6, "GORFOU").
dico("G", 6, "GORGEA").
dico("G", 6, "GORGEE").
dico("G", 6, "GORGER").
dico("G", 6, "GORGES").
dico("G", 6, "GORGET").
dico("G", 6, "GORGEZ").
dico("G", 6, "GORONS").
dico("G", 6, "GOSIER").
dico("G", 6, "GOSPEL").
dico("G", 6, "GOSSAI").
dico("G", 6, "GOSSAS").
dico("G", 6, "GOSSAT").
dico("G", 6, "GOSSEE").
dico("G", 6, "GOSSER").
dico("G", 6, "GOSSES").
dico("G", 6, "GOSSEZ").
dico("G", 6, "GOTHAS").
dico("G", 6, "GOTHES").
dico("G", 6, "GOTONS").
dico("G", 6, "GOUAPE").
dico("G", 6, "GOUDAS").
dico("G", 6, "GOUETS").
dico("G", 6, "GOUGEA").
dico("G", 6, "GOUGEE").
dico("G", 6, "GOUGER").
dico("G", 6, "GOUGES").
dico("G", 6, "GOUGEZ").
dico("G", 6, "GOUINE").
dico("G", 6, "GOUJAT").
dico("G", 6, "GOUJON").
dico("G", 6, "GOULAG").
dico("G", 6, "GOULEE").
dico("G", 6, "GOULES").
dico("G", 6, "GOULET").
dico("G", 6, "GOULOT").
dico("G", 6, "GOULUE").
dico("G", 6, "GOULUS").
dico("G", 6, "GOUPIL").
dico("G", 6, "GOURAI").
dico("G", 6, "GOURAS").
dico("G", 6, "GOURAT").
dico("G", 6, "GOURBI").
dico("G", 6, "GOURDE").
dico("G", 6, "GOURDS").
dico("G", 6, "GOUREE").
dico("G", 6, "GOUREN").
dico("G", 6, "GOURER").
dico("G", 6, "GOURES").
dico("G", 6, "GOUREZ").
dico("G", 6, "GOURME").
dico("G", 6, "GOUROU").
dico("G", 6, "GOUSSE").
dico("G", 6, "GOUTAI").
dico("G", 6, "GOUTAS").
dico("G", 6, "GOUTAT").
dico("G", 6, "GOUTEE").
dico("G", 6, "GOUTER").
dico("G", 6, "GOUTES").
dico("G", 6, "GOUTEZ").
dico("G", 6, "GOUTTA").
dico("G", 6, "GOUTTE").
dico("G", 6, "GOYAVE").
dico("G", 6, "GRAALS").
dico("G", 6, "GRABAT").
dico("G", 6, "GRABEN").
dico("G", 6, "GRACES").
dico("G", 6, "GRACIA").
dico("G", 6, "GRACIE").
dico("G", 6, "GRADAI").
dico("G", 6, "GRADAS").
dico("G", 6, "GRADAT").
dico("G", 6, "GRADEE").
dico("G", 6, "GRADER").
dico("G", 6, "GRADES").
dico("G", 6, "GRADEZ").
dico("G", 6, "GRADIN").
dico("G", 6, "GRADUA").
dico("G", 6, "GRADUE").
dico("G", 6, "GRADUS").
dico("G", 6, "GRAFFS").
dico("G", 6, "GRAINA").
dico("G", 6, "GRAINE").
dico("G", 6, "GRAINS").
dico("G", 6, "GRAMEN").
dico("G", 6, "GRAMME").
dico("G", 6, "GRANAS").
dico("G", 6, "GRANDE").
dico("G", 6, "GRANDI").
dico("G", 6, "GRANDS").
dico("G", 6, "GRANGE").
dico("G", 6, "GRANIT").
dico("G", 6, "GRANUM").
dico("G", 6, "GRAPHE").
dico("G", 6, "GRAPPA").
dico("G", 6, "GRAPPE").
dico("G", 6, "GRASSE").
dico("G", 6, "GRATIN").
dico("G", 6, "GRATIS").
dico("G", 6, "GRATOS").
dico("G", 6, "GRATTA").
dico("G", 6, "GRATTE").
dico("G", 6, "GRAVAI").
dico("G", 6, "GRAVAS").
dico("G", 6, "GRAVAT").
dico("G", 6, "GRAVEE").
dico("G", 6, "GRAVER").
dico("G", 6, "GRAVES").
dico("G", 6, "GRAVEZ").
dico("G", 6, "GRAVIE").
dico("G", 6, "GRAVIR").
dico("G", 6, "GRAVIS").
dico("G", 6, "GRAVIT").
dico("G", 6, "GREAGE").
dico("G", 6, "GREAIS").
dico("G", 6, "GREAIT").
dico("G", 6, "GREANT").
dico("G", 6, "GREBES").
dico("G", 6, "GREDIN").
dico("G", 6, "GREEES").
dico("G", 6, "GREENS").
dico("G", 6, "GREENT").
dico("G", 6, "GREERA").
dico("G", 6, "GREEUR").
dico("G", 6, "GREFFA").
dico("G", 6, "GREFFE").
dico("G", 6, "GREGES").
dico("G", 6, "GREIEZ").
dico("G", 6, "GRELAI").
dico("G", 6, "GRELAS").
dico("G", 6, "GRELAT").
dico("G", 6, "GRELEE").
dico("G", 6, "GRELER").
dico("G", 6, "GRELES").
dico("G", 6, "GRELEZ").
dico("G", 6, "GRELIN").
dico("G", 6, "GRELON").
dico("G", 6, "GRELOT").
dico("G", 6, "GREMIL").
dico("G", 6, "GRENAI").
dico("G", 6, "GRENAS").
dico("G", 6, "GRENAT").
dico("G", 6, "GRENEE").
dico("G", 6, "GRENER").
dico("G", 6, "GRENES").
dico("G", 6, "GRENEZ").
dico("G", 6, "GRENUE").
dico("G", 6, "GRENUS").
dico("G", 6, "GREONS").
dico("G", 6, "GRESAI").
dico("G", 6, "GRESAS").
dico("G", 6, "GRESAT").
dico("G", 6, "GRESEE").
dico("G", 6, "GRESER").
dico("G", 6, "GRESES").
dico("G", 6, "GRESEZ").
dico("G", 6, "GRESIL").
dico("G", 6, "GREVAI").
dico("G", 6, "GREVAS").
dico("G", 6, "GREVAT").
dico("G", 6, "GREVEE").
dico("G", 6, "GREVER").
dico("G", 6, "GREVES").
dico("G", 6, "GREVEZ").
dico("G", 6, "GRIEFS").
dico("G", 6, "GRIFFA").
dico("G", 6, "GRIFFE").
dico("G", 6, "GRIFFU").
dico("G", 6, "GRIGNA").
dico("G", 6, "GRIGNE").
dico("G", 6, "GRIGOU").
dico("G", 6, "GRIGRI").
dico("G", 6, "GRILLA").
dico("G", 6, "GRILLE").
dico("G", 6, "GRILLS").
dico("G", 6, "GRIMAI").
dico("G", 6, "GRIMAS").
dico("G", 6, "GRIMAT").
dico("G", 6, "GRIMEE").
dico("G", 6, "GRIMER").
dico("G", 6, "GRIMES").
dico("G", 6, "GRIMEZ").
dico("G", 6, "GRIMPA").
dico("G", 6, "GRIMPE").
dico("G", 6, "GRINCA").
dico("G", 6, "GRINCE").
dico("G", 6, "GRINGE").
dico("G", 6, "GRINGO").
dico("G", 6, "GRIOTS").
dico("G", 6, "GRIPPA").
dico("G", 6, "GRIPPE").
dico("G", 6, "GRISAI").
dico("G", 6, "GRISAS").
dico("G", 6, "GRISAT").
dico("G", 6, "GRISBI").
dico("G", 6, "GRISEE").
dico("G", 6, "GRISER").
dico("G", 6, "GRISES").
dico("G", 6, "GRISET").
dico("G", 6, "GRISEZ").
dico("G", 6, "GRISON").
dico("G", 6, "GRISOU").
dico("G", 6, "GRIVES").
dico("G", 6, "GRIVET").
dico("G", 6, "GRIVNA").
dico("G", 6, "GROGGY").
dico("G", 6, "GROGNA").
dico("G", 6, "GROGNE").
dico("G", 6, "GROIES").
dico("G", 6, "GROINS").
dico("G", 6, "GROLES").
dico("G", 6, "GROLLE").
dico("G", 6, "GRONDA").
dico("G", 6, "GRONDE").
dico("G", 6, "GROOMS").
dico("G", 6, "GROOVE").
dico("G", 6, "GROSSE").
dico("G", 6, "GROSSI").
dico("G", 6, "GROTTE").
dico("G", 6, "GROUPA").
dico("G", 6, "GROUPE").
dico("G", 6, "GROUPS").
dico("G", 6, "GROUSE").
dico("G", 6, "GRUAUX").
dico("G", 6, "GRUGEA").
dico("G", 6, "GRUGEE").
dico("G", 6, "GRUGER").
dico("G", 6, "GRUGES").
dico("G", 6, "GRUGEZ").
dico("G", 6, "GRUMES").
dico("G", 6, "GRUNGE").
dico("G", 6, "GRUONS").
dico("G", 6, "GRUTAI").
dico("G", 6, "GRUTAS").
dico("G", 6, "GRUTAT").
dico("G", 6, "GRUTEE").
dico("G", 6, "GRUTER").
dico("G", 6, "GRUTES").
dico("G", 6, "GRUTEZ").
dico("G", 6, "GRUYER").
dico("G", 6, "GUANOS").
dico("G", 6, "GUEAIS").
dico("G", 6, "GUEAIT").
dico("G", 6, "GUEANT").
dico("G", 6, "GUEBRE").
dico("G", 6, "GUEDES").
dico("G", 6, "GUEEES").
dico("G", 6, "GUEENT").
dico("G", 6, "GUEERA").
dico("G", 6, "GUEIEZ").
dico("G", 6, "GUELFE").
dico("G", 6, "GUELTE").
dico("G", 6, "GUENON").
dico("G", 6, "GUEONS").
dico("G", 6, "GUEPES").
dico("G", 6, "GUERES").
dico("G", 6, "GUERET").
dico("G", 6, "GUERIE").
dico("G", 6, "GUERIR").
dico("G", 6, "GUERIS").
dico("G", 6, "GUERIT").
dico("G", 6, "GUERRE").
dico("G", 6, "GUETES").
dico("G", 6, "GUETRA").
dico("G", 6, "GUETRE").
dico("G", 6, "GUETTA").
dico("G", 6, "GUETTE").
dico("G", 6, "GUEULA").
dico("G", 6, "GUEULE").
dico("G", 6, "GUEUSA").
dico("G", 6, "GUEUSE").
dico("G", 6, "GUEUZE").
dico("G", 6, "GUEZES").
dico("G", 6, "GUGUSS").
dico("G", 6, "GUIBRE").
dico("G", 6, "GUICHE").
dico("G", 6, "GUIDAI").
dico("G", 6, "GUIDAS").
dico("G", 6, "GUIDAT").
dico("G", 6, "GUIDEE").
dico("G", 6, "GUIDER").
dico("G", 6, "GUIDES").
dico("G", 6, "GUIDEZ").
dico("G", 6, "GUIDON").
dico("G", 6, "GUIGNA").
dico("G", 6, "GUIGNE").
dico("G", 6, "GUILDE").
dico("G", 6, "GUIMPA").
dico("G", 6, "GUIMPE").
dico("G", 6, "GUINDA").
dico("G", 6, "GUINDE").
dico("G", 6, "GUINEE").
dico("G", 6, "GUIPAI").
dico("G", 6, "GUIPAS").
dico("G", 6, "GUIPAT").
dico("G", 6, "GUIPEE").
dico("G", 6, "GUIPER").
dico("G", 6, "GUIPES").
dico("G", 6, "GUIPEZ").
dico("G", 6, "GUIPON").
dico("G", 6, "GUIVRE").
dico("G", 6, "GULDEN").
dico("G", 6, "GUNITA").
dico("G", 6, "GUNITE").
dico("G", 6, "GUPPYS").
dico("G", 6, "GUSSES").
dico("G", 6, "GUYOTS").
dico("G", 6, "GUZLAS").
dico("G", 6, "GYNECO").
dico("G", 6, "GYPSES").
dico("G", 6, "GYRINS").
