dico("H", 10, "HABILEMENT").
dico("H", 10, "HABILITAIS").
dico("H", 10, "HABILITAIT").
dico("H", 10, "HABILITANT").
dico("H", 10, "HABILITEES").
dico("H", 10, "HABILITENT").
dico("H", 10, "HABILITERA").
dico("H", 10, "HABILITIEZ").
dico("H", 10, "HABILITONS").
dico("H", 10, "HABILLABLE").
dico("H", 10, "HABILLAGES").
dico("H", 10, "HABILLAMES").
dico("H", 10, "HABILLASSE").
dico("H", 10, "HABILLATES").
dico("H", 10, "HABILLERAI").
dico("H", 10, "HABILLERAS").
dico("H", 10, "HABILLEREZ").
dico("H", 10, "HABILLEURS").
dico("H", 10, "HABILLEUSE").
dico("H", 10, "HABILLIONS").
dico("H", 10, "HABITABLES").
dico("H", 10, "HABITACLES").
dico("H", 10, "HABITAIENT").
dico("H", 10, "HABITANTES").
dico("H", 10, "HABITASSES").
dico("H", 10, "HABITATION").
dico("H", 10, "HABITERAIS").
dico("H", 10, "HABITERAIT").
dico("H", 10, "HABITERENT").
dico("H", 10, "HABITERIEZ").
dico("H", 10, "HABITERONS").
dico("H", 10, "HABITERONT").
dico("H", 10, "HABITUAMES").
dico("H", 10, "HABITUASSE").
dico("H", 10, "HABITUATES").
dico("H", 10, "HABITUELLE").
dico("H", 10, "HABITUERAI").
dico("H", 10, "HABITUERAS").
dico("H", 10, "HABITUEREZ").
dico("H", 10, "HABITUIONS").
dico("H", 10, "HABLASSENT").
dico("H", 10, "HABLASSIEZ").
dico("H", 10, "HABLERIONS").
dico("H", 10, "HACHASSENT").
dico("H", 10, "HACHASSIEZ").
dico("H", 10, "HACHEMENTS").
dico("H", 10, "HACHEMITES").
dico("H", 10, "HACHEREAUX").
dico("H", 10, "HACHERIONS").
dico("H", 10, "HACHURAMES").
dico("H", 10, "HACHURASSE").
dico("H", 10, "HACHURATES").
dico("H", 10, "HACHURERAI").
dico("H", 10, "HACHURERAS").
dico("H", 10, "HACHUREREZ").
dico("H", 10, "HACHURIONS").
dico("H", 10, "HACQUEBUTE").
dico("H", 10, "HAGIOLOGIE").
dico("H", 10, "HAGUENOISE").
dico("H", 10, "HAINUYERES").
dico("H", 10, "HAISSABLES").
dico("H", 10, "HAISSAIENT").
dico("H", 10, "HAITIENNES").
dico("H", 10, "HALASSIONS").
dico("H", 10, "HALBRENEES").
dico("H", 10, "HALENAIENT").
dico("H", 10, "HALENASSES").
dico("H", 10, "HALENERAIS").
dico("H", 10, "HALENERAIT").
dico("H", 10, "HALENERENT").
dico("H", 10, "HALENERIEZ").
dico("H", 10, "HALENERONS").
dico("H", 10, "HALENERONT").
dico("H", 10, "HALERAIENT").
dico("H", 10, "HALETAIENT").
dico("H", 10, "HALETANTES").
dico("H", 10, "HALETASSES").
dico("H", 10, "HALETEMENT").
dico("H", 10, "HALETERAIS").
dico("H", 10, "HALETERAIT").
dico("H", 10, "HALETERENT").
dico("H", 10, "HALETERIEZ").
dico("H", 10, "HALETERONS").
dico("H", 10, "HALETERONT").
dico("H", 10, "HALIGONIEN").
dico("H", 10, "HALIOTIDES").
dico("H", 10, "HALITUEUSE").
dico("H", 10, "HALLEBARDE").
dico("H", 10, "HALLOWEENS").
dico("H", 10, "HALLUCINAI").
dico("H", 10, "HALLUCINAS").
dico("H", 10, "HALLUCINAT").
dico("H", 10, "HALLUCINEE").
dico("H", 10, "HALLUCINER").
dico("H", 10, "HALLUCINES").
dico("H", 10, "HALLUCINEZ").
dico("H", 10, "HALOGENAIS").
dico("H", 10, "HALOGENAIT").
dico("H", 10, "HALOGENANT").
dico("H", 10, "HALOGENEES").
dico("H", 10, "HALOGENENT").
dico("H", 10, "HALOGENERA").
dico("H", 10, "HALOGENIEZ").
dico("H", 10, "HALOGENONS").
dico("H", 10, "HALOGENURE").
dico("H", 10, "HALOPHILES").
dico("H", 10, "HALOPHYTES").
dico("H", 10, "HALOTHANES").
dico("H", 10, "HAMADRYADE").
dico("H", 10, "HAMBURGERS").
dico("H", 10, "HAMECONNAI").
dico("H", 10, "HAMECONNAS").
dico("H", 10, "HAMECONNAT").
dico("H", 10, "HAMECONNEE").
dico("H", 10, "HAMECONNER").
dico("H", 10, "HAMECONNES").
dico("H", 10, "HAMECONNEZ").
dico("H", 10, "HAMMERLESS").
dico("H", 10, "HANAFISMES").
dico("H", 10, "HANBALISME").
dico("H", 10, "HANBALITES").
dico("H", 10, "HANCHAIENT").
dico("H", 10, "HANCHASSES").
dico("H", 10, "HANCHEMENT").
dico("H", 10, "HANCHERAIS").
dico("H", 10, "HANCHERAIT").
dico("H", 10, "HANCHERENT").
dico("H", 10, "HANCHERIEZ").
dico("H", 10, "HANCHERONS").
dico("H", 10, "HANCHERONT").
dico("H", 10, "HANDICAPAI").
dico("H", 10, "HANDICAPAS").
dico("H", 10, "HANDICAPAT").
dico("H", 10, "HANDICAPEE").
dico("H", 10, "HANDICAPER").
dico("H", 10, "HANDICAPES").
dico("H", 10, "HANDICAPEZ").
dico("H", 10, "HANDISPORT").
dico("H", 10, "HANNETONNA").
dico("H", 10, "HANNETONNE").
dico("H", 10, "HANOVRIENS").
dico("H", 10, "HANTASSENT").
dico("H", 10, "HANTASSIEZ").
dico("H", 10, "HANTAVIRUS").
dico("H", 10, "HANTERIONS").
dico("H", 10, "HAPLOIDIES").
dico("H", 10, "HAPLOLOGIE").
dico("H", 10, "HAPPASSENT").
dico("H", 10, "HAPPASSIEZ").
dico("H", 10, "HAPPEMENTS").
dico("H", 10, "HAPPENINGS").
dico("H", 10, "HAPPERIONS").
dico("H", 10, "HAPTONOMIE").
dico("H", 10, "HAQUEBUTES").
dico("H", 10, "HARANGUAIS").
dico("H", 10, "HARANGUAIT").
dico("H", 10, "HARANGUANT").
dico("H", 10, "HARANGUEES").
dico("H", 10, "HARANGUENT").
dico("H", 10, "HARANGUERA").
dico("H", 10, "HARANGUEUR").
dico("H", 10, "HARANGUIEZ").
dico("H", 10, "HARANGUONS").
dico("H", 10, "HARARAISES").
dico("H", 10, "HARASSAMES").
dico("H", 10, "HARASSANTE").
dico("H", 10, "HARASSANTS").
dico("H", 10, "HARASSASSE").
dico("H", 10, "HARASSATES").
dico("H", 10, "HARASSERAI").
dico("H", 10, "HARASSERAS").
dico("H", 10, "HARASSEREZ").
dico("H", 10, "HARASSIONS").
dico("H", 10, "HARCELAMES").
dico("H", 10, "HARCELANTE").
dico("H", 10, "HARCELANTS").
dico("H", 10, "HARCELASSE").
dico("H", 10, "HARCELATES").
dico("H", 10, "HARCELERAI").
dico("H", 10, "HARCELERAS").
dico("H", 10, "HARCELEREZ").
dico("H", 10, "HARCELEURS").
dico("H", 10, "HARCELEUSE").
dico("H", 10, "HARCELIONS").
dico("H", 10, "HARCELLENT").
dico("H", 10, "HARCELLERA").
dico("H", 10, "HARDASSENT").
dico("H", 10, "HARDASSIEZ").
dico("H", 10, "HARDERIONS").
dico("H", 10, "HARDIESSES").
dico("H", 10, "HARENGERES").
dico("H", 10, "HARENGUETS").
dico("H", 10, "HARENGUEUX").
dico("H", 10, "HARENGUIER").
dico("H", 10, "HARGNEUSES").
dico("H", 10, "HARIDELLES").
dico("H", 10, "HARMATTANS").
dico("H", 10, "HARMONICAS").
dico("H", 10, "HARMONIEUX").
dico("H", 10, "HARMONIQUE").
dico("H", 10, "HARMONISAI").
dico("H", 10, "HARMONISAS").
dico("H", 10, "HARMONISAT").
dico("H", 10, "HARMONISEE").
dico("H", 10, "HARMONISER").
dico("H", 10, "HARMONISES").
dico("H", 10, "HARMONISEZ").
dico("H", 10, "HARMONISTE").
dico("H", 10, "HARMONIUMS").
dico("H", 10, "HARNACHAIS").
dico("H", 10, "HARNACHAIT").
dico("H", 10, "HARNACHANT").
dico("H", 10, "HARNACHEES").
dico("H", 10, "HARNACHENT").
dico("H", 10, "HARNACHERA").
dico("H", 10, "HARNACHEUR").
dico("H", 10, "HARNACHIEZ").
dico("H", 10, "HARNACHONS").
dico("H", 10, "HARPAILLES").
dico("H", 10, "HARPASSENT").
dico("H", 10, "HARPASSIEZ").
dico("H", 10, "HARPERIONS").
dico("H", 10, "HARPONNAGE").
dico("H", 10, "HARPONNAIS").
dico("H", 10, "HARPONNAIT").
dico("H", 10, "HARPONNANT").
dico("H", 10, "HARPONNEES").
dico("H", 10, "HARPONNENT").
dico("H", 10, "HARPONNERA").
dico("H", 10, "HARPONNEUR").
dico("H", 10, "HARPONNIEZ").
dico("H", 10, "HARPONNONS").
dico("H", 10, "HARUSPICES").
dico("H", 10, "HASARDAMES").
dico("H", 10, "HASARDASSE").
dico("H", 10, "HASARDATES").
dico("H", 10, "HASARDERAI").
dico("H", 10, "HASARDERAS").
dico("H", 10, "HASARDEREZ").
dico("H", 10, "HASARDEUSE").
dico("H", 10, "HASARDIONS").
dico("H", 10, "HASCHISCHS").
dico("H", 10, "HASSELTOIS").
dico("H", 10, "HASSIDIQUE").
dico("H", 10, "HASSIDISME").
dico("H", 10, "HATASSIONS").
dico("H", 10, "HATELETTES").
dico("H", 10, "HATERAIENT").
dico("H", 10, "HATIVEMENT").
dico("H", 10, "HAUBANAGES").
dico("H", 10, "HAUBANAMES").
dico("H", 10, "HAUBANASSE").
dico("H", 10, "HAUBANATES").
dico("H", 10, "HAUBANERAI").
dico("H", 10, "HAUBANERAS").
dico("H", 10, "HAUBANEREZ").
dico("H", 10, "HAUBANIONS").
dico("H", 10, "HAUBERGEON").
dico("H", 10, "HAUSSAIENT").
dico("H", 10, "HAUSSASSES").
dico("H", 10, "HAUSSEMENT").
dico("H", 10, "HAUSSERAIS").
dico("H", 10, "HAUSSERAIT").
dico("H", 10, "HAUSSERENT").
dico("H", 10, "HAUSSERIEZ").
dico("H", 10, "HAUSSERONS").
dico("H", 10, "HAUSSERONT").
dico("H", 10, "HAUSSIERES").
dico("H", 10, "HAUTBOISTE").
dico("H", 10, "HAUTURIERE").
dico("H", 10, "HAUTURIERS").
dico("H", 10, "HAVANAISES").
dico("H", 10, "HAVASSIONS").
dico("H", 10, "HAVERAIENT").
dico("H", 10, "HAVIRAIENT").
dico("H", 10, "HAVISSIONS").
dico("H", 10, "HAWAIENNES").
dico("H", 10, "HAWAIIENNE").
dico("H", 10, "HEAUMIERES").
dico("H", 10, "HEBEPHRENE").
dico("H", 10, "HEBERGEAIS").
dico("H", 10, "HEBERGEAIT").
dico("H", 10, "HEBERGEANT").
dico("H", 10, "HEBERGEONS").
dico("H", 10, "HEBERGERAI").
dico("H", 10, "HEBERGERAS").
dico("H", 10, "HEBERGEREZ").
dico("H", 10, "HEBERGEURS").
dico("H", 10, "HEBERGIONS").
dico("H", 10, "HEBERTISME").
dico("H", 10, "HEBERTISTE").
dico("H", 10, "HEBETAIENT").
dico("H", 10, "HEBETASSES").
dico("H", 10, "HEBETEMENT").
dico("H", 10, "HEBETERAIS").
dico("H", 10, "HEBETERAIT").
dico("H", 10, "HEBETERENT").
dico("H", 10, "HEBETERIEZ").
dico("H", 10, "HEBETERONS").
dico("H", 10, "HEBETERONT").
dico("H", 10, "HEBRAIQUES").
dico("H", 10, "HEBRAISAIS").
dico("H", 10, "HEBRAISAIT").
dico("H", 10, "HEBRAISANT").
dico("H", 10, "HEBRAISEES").
dico("H", 10, "HEBRAISENT").
dico("H", 10, "HEBRAISERA").
dico("H", 10, "HEBRAISIEZ").
dico("H", 10, "HEBRAISMES").
dico("H", 10, "HEBRAISONS").
dico("H", 10, "HEBRAISTES").
dico("H", 10, "HECATOMBES").
dico("H", 10, "HECTOLITRE").
dico("H", 10, "HECTOMETRE").
dico("H", 10, "HECTOPIEZE").
dico("H", 10, "HECTOWATTS").
dico("H", 10, "HEDERACEES").
dico("H", 10, "HEDONISMES").
dico("H", 10, "HEDONISTES").
dico("H", 10, "HEGELIENNE").
dico("H", 10, "HEGEMONIES").
dico("H", 10, "HELASSIONS").
dico("H", 10, "HELERAIENT").
dico("H", 10, "HELIANTHES").
dico("H", 10, "HELICOIDAL").
dico("H", 10, "HELICOIDES").
dico("H", 10, "HELIODORES").
dico("H", 10, "HELIOMARIN").
dico("H", 10, "HELIOMETRE").
dico("H", 10, "HELIOSTATS").
dico("H", 10, "HELIOTROPE").
dico("H", 10, "HELIPORTEE").
dico("H", 10, "HELIPORTES").
dico("H", 10, "HELLADIQUE").
dico("H", 10, "HELLEBORES").
dico("H", 10, "HELLENIQUE").
dico("H", 10, "HELLENISAI").
dico("H", 10, "HELLENISAS").
dico("H", 10, "HELLENISAT").
dico("H", 10, "HELLENISEE").
dico("H", 10, "HELLENISER").
dico("H", 10, "HELLENISES").
dico("H", 10, "HELLENISEZ").
dico("H", 10, "HELLENISME").
dico("H", 10, "HELLENISTE").
dico("H", 10, "HELMINTHES").
dico("H", 10, "HELOBIALES").
dico("H", 10, "HELODERMES").
dico("H", 10, "HELSINKIEN").
dico("H", 10, "HELVETIENS").
dico("H", 10, "HELVETIQUE").
dico("H", 10, "HELVETISME").
dico("H", 10, "HEMANGIOME").
dico("H", 10, "HEMATEMESE").
dico("H", 10, "HEMATIQUES").
dico("H", 10, "HEMATOBIES").
dico("H", 10, "HEMATOCELE").
dico("H", 10, "HEMATURIES").
dico("H", 10, "HEMERALOPE").
dico("H", 10, "HEMIALGIES").
dico("H", 10, "HEMICORDES").
dico("H", 10, "HEMICRANIE").
dico("H", 10, "HEMICYCLES").
dico("H", 10, "HEMIEDRIES").
dico("H", 10, "HEMIOXYDES").
dico("H", 10, "HEMIPLEGIE").
dico("H", 10, "HEMIPTERES").
dico("H", 10, "HEMISPHERE").
dico("H", 10, "HEMISTICHE").
dico("H", 10, "HEMITROPES").
dico("H", 10, "HEMITROPIE").
dico("H", 10, "HEMOGENIES").
dico("H", 10, "HEMOGRAMME").
dico("H", 10, "HEMOLYMPHE").
dico("H", 10, "HEMOLYSINE").
dico("H", 10, "HEMOPATHIE").
dico("H", 10, "HEMOPHILES").
dico("H", 10, "HEMOPHILIE").
dico("H", 10, "HEMOPTYSIE").
dico("H", 10, "HEMORRAGIE").
dico("H", 10, "HEMORROIDE").
dico("H", 10, "HEMOSTASES").
dico("H", 10, "HEMOSTASIE").
dico("H", 10, "HENDIADYIN").
dico("H", 10, "HENNIRIONS").
dico("H", 10, "HENNISSAIS").
dico("H", 10, "HENNISSAIT").
dico("H", 10, "HENNISSANT").
dico("H", 10, "HENNISSENT").
dico("H", 10, "HENNISSIEZ").
dico("H", 10, "HENNISSONS").
dico("H", 10, "HENNUYERES").
dico("H", 10, "HEPATALGIE").
dico("H", 10, "HEPATIQUES").
dico("H", 10, "HEPATISMES").
dico("H", 10, "HEPATOCELE").
dico("H", 10, "HEPATOCYTE").
dico("H", 10, "HEPTACORDE").
dico("H", 10, "HEPTAEDRES").
dico("H", 10, "HEPTAGONAL").
dico("H", 10, "HEPTAGONES").
dico("H", 10, "HEPTAMETRE").
dico("H", 10, "HEPTARCHIE").
dico("H", 10, "HEPTATHLON").
dico("H", 10, "HERALDIQUE").
dico("H", 10, "HERALDISTE").
dico("H", 10, "HERAULTAIS").
dico("H", 10, "HERBAGEAIS").
dico("H", 10, "HERBAGEAIT").
dico("H", 10, "HERBAGEANT").
dico("H", 10, "HERBAGEONS").
dico("H", 10, "HERBAGERAI").
dico("H", 10, "HERBAGERAS").
dico("H", 10, "HERBAGERES").
dico("H", 10, "HERBAGEREZ").
dico("H", 10, "HERBAGEUSE").
dico("H", 10, "HERBAGIONS").
dico("H", 10, "HERBASSENT").
dico("H", 10, "HERBASSIEZ").
dico("H", 10, "HERBERIONS").
dico("H", 10, "HERBICIDES").
dico("H", 10, "HERBICOLES").
dico("H", 10, "HERBIVORES").
dico("H", 10, "HERBORISAI").
dico("H", 10, "HERBORISAS").
dico("H", 10, "HERBORISAT").
dico("H", 10, "HERBORISEE").
dico("H", 10, "HERBORISER").
dico("H", 10, "HERBORISES").
dico("H", 10, "HERBORISEZ").
dico("H", 10, "HERBORISTE").
dico("H", 10, "HERCHAIENT").
dico("H", 10, "HERCHASSES").
dico("H", 10, "HERCHERAIS").
dico("H", 10, "HERCHERAIT").
dico("H", 10, "HERCHERENT").
dico("H", 10, "HERCHERIEZ").
dico("H", 10, "HERCHERONS").
dico("H", 10, "HERCHERONT").
dico("H", 10, "HERCHEUSES").
dico("H", 10, "HERCULEENS").
dico("H", 10, "HERCYNIENS").
dico("H", 10, "HERETICITE").
dico("H", 10, "HERETIQUES").
dico("H", 10, "HERISSAMES").
dico("H", 10, "HERISSASSE").
dico("H", 10, "HERISSATES").
dico("H", 10, "HERISSERAI").
dico("H", 10, "HERISSERAS").
dico("H", 10, "HERISSEREZ").
dico("H", 10, "HERISSIONS").
dico("H", 10, "HERISSONNA").
dico("H", 10, "HERISSONNE").
dico("H", 10, "HERITAIENT").
dico("H", 10, "HERITASSES").
dico("H", 10, "HERITERAIS").
dico("H", 10, "HERITERAIT").
dico("H", 10, "HERITERENT").
dico("H", 10, "HERITERIEZ").
dico("H", 10, "HERITERONS").
dico("H", 10, "HERITERONT").
dico("H", 10, "HERITIERES").
dico("H", 10, "HERMANDADS").
dico("H", 10, "HERMETIQUE").
dico("H", 10, "HERMETISME").
dico("H", 10, "HERMETISTE").
dico("H", 10, "HERMINETTE").
dico("H", 10, "HERMITIENS").
dico("H", 10, "HERNIAIRES").
dico("H", 10, "HERNIEUSES").
dico("H", 10, "HEROICITES").
dico("H", 10, "HERONNEAUX").
dico("H", 10, "HERONNIERE").
dico("H", 10, "HERONNIERS").
dico("H", 10, "HERPETIQUE").
dico("H", 10, "HERPETISME").
dico("H", 10, "HERSASSENT").
dico("H", 10, "HERSASSIEZ").
dico("H", 10, "HERSCHAGES").
dico("H", 10, "HERSCHAMES").
dico("H", 10, "HERSCHASSE").
dico("H", 10, "HERSCHATES").
dico("H", 10, "HERSCHERAI").
dico("H", 10, "HERSCHERAS").
dico("H", 10, "HERSCHEREZ").
dico("H", 10, "HERSCHEURS").
dico("H", 10, "HERSCHEUSE").
dico("H", 10, "HERSCHIONS").
dico("H", 10, "HERSERIONS").
dico("H", 10, "HERTZIENNE").
dico("H", 10, "HESBIGNONS").
dico("H", 10, "HESITAIENT").
dico("H", 10, "HESITANTES").
dico("H", 10, "HESITASSES").
dico("H", 10, "HESITATION").
dico("H", 10, "HESITERAIS").
dico("H", 10, "HESITERAIT").
dico("H", 10, "HESITERENT").
dico("H", 10, "HESITERIEZ").
dico("H", 10, "HESITERONS").
dico("H", 10, "HESITERONT").
dico("H", 10, "HESYCHASME").
dico("H", 10, "HETAIRISME").
dico("H", 10, "HETERODOXE").
dico("H", 10, "HETERODYNE").
dico("H", 10, "HETEROGAME").
dico("H", 10, "HETEROGENE").
dico("H", 10, "HETEROGYNE").
dico("H", 10, "HETERONOME").
dico("H", 10, "HETERONYME").
dico("H", 10, "HETEROPODE").
dico("H", 10, "HETEROSIDE").
dico("H", 10, "HEURTAIENT").
dico("H", 10, "HEURTASSES").
dico("H", 10, "HEURTERAIS").
dico("H", 10, "HEURTERAIT").
dico("H", 10, "HEURTERENT").
dico("H", 10, "HEURTERIEZ").
dico("H", 10, "HEURTERONS").
dico("H", 10, "HEURTERONT").
dico("H", 10, "HEXACORDES").
dico("H", 10, "HEXADECANE").
dico("H", 10, "HEXAGONALE").
dico("H", 10, "HEXAGONAUX").
dico("H", 10, "HEXAMETRES").
dico("H", 10, "HEXAMIDINE").
dico("H", 10, "HEXASTYLES").
dico("H", 10, "HIBERNALES").
dico("H", 10, "HIBERNAMES").
dico("H", 10, "HIBERNANTE").
dico("H", 10, "HIBERNANTS").
dico("H", 10, "HIBERNASSE").
dico("H", 10, "HIBERNATES").
dico("H", 10, "HIBERNERAI").
dico("H", 10, "HIBERNERAS").
dico("H", 10, "HIBERNEREZ").
dico("H", 10, "HIBERNIONS").
dico("H", 10, "HIEMATIONS").
dico("H", 10, "HIERARCHIE").
dico("H", 10, "HIERARQUES").
dico("H", 10, "HIERATIQUE").
dico("H", 10, "HIERATISME").
dico("H", 10, "HIERODULES").
dico("H", 10, "HIEROGAMIE").
dico("H", 10, "HIGHLANDER").
dico("H", 10, "HIGOUMENES").
dico("H", 10, "HILARANTES").
dico("H", 10, "HILOTISMES").
dico("H", 10, "HIMALAYENS").
dico("H", 10, "HINDOUISME").
dico("H", 10, "HINDOUISTE").
dico("H", 10, "HINTERLAND").
dico("H", 10, "HIPPARCHIE").
dico("H", 10, "HIPPARIONS").
dico("H", 10, "HIPPARQUES").
dico("H", 10, "HIPPIATRES").
dico("H", 10, "HIPPIATRIE").
dico("H", 10, "HIPPOCAMPE").
dico("H", 10, "HIPPODROME").
dico("H", 10, "HIPPOLOGIE").
dico("H", 10, "HIPPOPHAES").
dico("H", 10, "HIPPOPHAGE").
dico("H", 10, "HIPPURIQUE").
dico("H", 10, "HIRONDEAUX").
dico("H", 10, "HIRONDELLE").
dico("H", 10, "HIRSUTISME").
dico("H", 10, "HIRUDINEES").
dico("H", 10, "HISPANIQUE").
dico("H", 10, "HISPANISAI").
dico("H", 10, "HISPANISAS").
dico("H", 10, "HISPANISAT").
dico("H", 10, "HISPANISEE").
dico("H", 10, "HISPANISER").
dico("H", 10, "HISPANISES").
dico("H", 10, "HISPANISEZ").
dico("H", 10, "HISPANISME").
dico("H", 10, "HISPANISTE").
dico("H", 10, "HISSASSENT").
dico("H", 10, "HISSASSIEZ").
dico("H", 10, "HISSERIONS").
dico("H", 10, "HISTAMINES").
dico("H", 10, "HISTIDINES").
dico("H", 10, "HISTIOCYTE").
dico("H", 10, "HISTOLOGIE").
dico("H", 10, "HISTOLYSES").
dico("H", 10, "HISTORIAIS").
dico("H", 10, "HISTORIAIT").
dico("H", 10, "HISTORIANT").
dico("H", 10, "HISTORIEES").
dico("H", 10, "HISTORIENS").
dico("H", 10, "HISTORIENT").
dico("H", 10, "HISTORIERA").
dico("H", 10, "HISTORIIEZ").
dico("H", 10, "HISTORIONS").
dico("H", 10, "HISTORIQUE").
dico("H", 10, "HISTORISME").
dico("H", 10, "HITLERIENS").
dico("H", 10, "HITLERISME").
dico("H", 10, "HIVERNAGES").
dico("H", 10, "HIVERNALES").
dico("H", 10, "HIVERNAMES").
dico("H", 10, "HIVERNANTE").
dico("H", 10, "HIVERNANTS").
dico("H", 10, "HIVERNASSE").
dico("H", 10, "HIVERNATES").
dico("H", 10, "HIVERNERAI").
dico("H", 10, "HIVERNERAS").
dico("H", 10, "HIVERNEREZ").
dico("H", 10, "HIVERNIONS").
dico("H", 10, "HOCHASSENT").
dico("H", 10, "HOCHASSIEZ").
dico("H", 10, "HOCHEMENTS").
dico("H", 10, "HOCHEQUEUE").
dico("H", 10, "HOCHERIONS").
dico("H", 10, "HOCKEYEURS").
dico("H", 10, "HOCKEYEUSE").
dico("H", 10, "HODOGRAPHE").
dico("H", 10, "HOLISTIQUE").
dico("H", 10, "HOLLANDAIS").
dico("H", 10, "HOLOCAUSTE").
dico("H", 10, "HOLOEDRIES").
dico("H", 10, "HOLOGAMIES").
dico("H", 10, "HOLOGRAMME").
dico("H", 10, "HOLOGRAPHE").
dico("H", 10, "HOLOMETRES").
dico("H", 10, "HOLOMORPHE").
dico("H", 10, "HOLOSTEENS").
dico("H", 10, "HOLOTHURIE").
dico("H", 10, "HOLOTRICHE").
dico("H", 10, "HOMARDERIE").
dico("H", 10, "HOMARDIERS").
dico("H", 10, "HOMEOPATHE").
dico("H", 10, "HOMEOSTATS").
dico("H", 10, "HOMEOTIQUE").
dico("H", 10, "HOMERIQUES").
dico("H", 10, "HOMINISEES").
dico("H", 10, "HOMINOIDES").
dico("H", 10, "HOMOCENTRE").
dico("H", 10, "HOMOCERQUE").
dico("H", 10, "HOMODONTES").
dico("H", 10, "HOMOFOCALE").
dico("H", 10, "HOMOFOCAUX").
dico("H", 10, "HOMOGAMIES").
dico("H", 10, "HOMOGRAPHE").
dico("H", 10, "HOMOGREFFE").
dico("H", 10, "HOMOLOGIES").
dico("H", 10, "HOMOLOGUAI").
dico("H", 10, "HOMOLOGUAS").
dico("H", 10, "HOMOLOGUAT").
dico("H", 10, "HOMOLOGUEE").
dico("H", 10, "HOMOLOGUER").
dico("H", 10, "HOMOLOGUES").
dico("H", 10, "HOMOLOGUEZ").
dico("H", 10, "HOMONCULES").
dico("H", 10, "HOMONYMIES").
dico("H", 10, "HOMOPHILES").
dico("H", 10, "HOMOPHILIE").
dico("H", 10, "HOMOPHOBES").
dico("H", 10, "HOMOPHOBIE").
dico("H", 10, "HOMOPHONES").
dico("H", 10, "HOMOPHONIE").
dico("H", 10, "HOMOPTERES").
dico("H", 10, "HOMOSEXUEL").
dico("H", 10, "HOMOSPHERE").
dico("H", 10, "HOMOTHERME").
dico("H", 10, "HOMOTHETIE").
dico("H", 10, "HOMOZYGOTE").
dico("H", 10, "HOMUNCULES").
dico("H", 10, "HONDURIENS").
dico("H", 10, "HONGRAIENT").
dico("H", 10, "HONGRASSES").
dico("H", 10, "HONGRERAIS").
dico("H", 10, "HONGRERAIT").
dico("H", 10, "HONGRERENT").
dico("H", 10, "HONGRERIEZ").
dico("H", 10, "HONGRERONS").
dico("H", 10, "HONGRERONT").
dico("H", 10, "HONGROIENT").
dico("H", 10, "HONGROIERA").
dico("H", 10, "HONGROISES").
dico("H", 10, "HONGROYAGE").
dico("H", 10, "HONGROYAIS").
dico("H", 10, "HONGROYAIT").
dico("H", 10, "HONGROYANT").
dico("H", 10, "HONGROYEES").
dico("H", 10, "HONGROYEUR").
dico("H", 10, "HONGROYIEZ").
dico("H", 10, "HONGROYONS").
dico("H", 10, "HONNETETES").
dico("H", 10, "HONNIRIONS").
dico("H", 10, "HONNISSAIS").
dico("H", 10, "HONNISSAIT").
dico("H", 10, "HONNISSANT").
dico("H", 10, "HONNISSENT").
dico("H", 10, "HONNISSIEZ").
dico("H", 10, "HONNISSONS").
dico("H", 10, "HONORABLES").
dico("H", 10, "HONORAIENT").
dico("H", 10, "HONORAIRES").
dico("H", 10, "HONORARIAT").
dico("H", 10, "HONORASSES").
dico("H", 10, "HONORERAIS").
dico("H", 10, "HONORERAIT").
dico("H", 10, "HONORERENT").
dico("H", 10, "HONORERIEZ").
dico("H", 10, "HONORERONS").
dico("H", 10, "HONORERONT").
dico("H", 10, "HOQUETAMES").
dico("H", 10, "HOQUETASSE").
dico("H", 10, "HOQUETATES").
dico("H", 10, "HOQUETIONS").
dico("H", 10, "HOQUETTENT").
dico("H", 10, "HOQUETTERA").
dico("H", 10, "HORDEACEES").
dico("H", 10, "HORIZONTAL").
dico("H", 10, "HORLOGERES").
dico("H", 10, "HORLOGERIE").
dico("H", 10, "HORMONALES").
dico("H", 10, "HORMONAMES").
dico("H", 10, "HORMONASSE").
dico("H", 10, "HORMONATES").
dico("H", 10, "HORMONERAI").
dico("H", 10, "HORMONERAS").
dico("H", 10, "HORMONEREZ").
dico("H", 10, "HORMONIONS").
dico("H", 10, "HORNBLENDE").
dico("H", 10, "HORODATEES").
dico("H", 10, "HORODATEUR").
dico("H", 10, "HOROMETRIE").
dico("H", 10, "HOROPTERES").
dico("H", 10, "HOROSCOPES").
dico("H", 10, "HORRIFIAIS").
dico("H", 10, "HORRIFIAIT").
dico("H", 10, "HORRIFIANT").
dico("H", 10, "HORRIFIEES").
dico("H", 10, "HORRIFIENT").
dico("H", 10, "HORRIFIERA").
dico("H", 10, "HORRIFIIEZ").
dico("H", 10, "HORRIFIONS").
dico("H", 10, "HORRIFIQUE").
dico("H", 10, "HORRIPILAI").
dico("H", 10, "HORRIPILAS").
dico("H", 10, "HORRIPILAT").
dico("H", 10, "HORRIPILEE").
dico("H", 10, "HORRIPILER").
dico("H", 10, "HORRIPILES").
dico("H", 10, "HORRIPILEZ").
dico("H", 10, "HORTENSIAS").
dico("H", 10, "HORTICOLES").
dico("H", 10, "HORTILLONS").
dico("H", 10, "HOSTILITES").
dico("H", 10, "HOTELIERES").
dico("H", 10, "HOTELLERIE").
dico("H", 10, "HOTTASSENT").
dico("H", 10, "HOTTASSIEZ").
dico("H", 10, "HOTTENTOTE").
dico("H", 10, "HOTTENTOTS").
dico("H", 10, "HOTTEREAUX").
dico("H", 10, "HOTTERIONS").
dico("H", 10, "HOUASSIONS").
dico("H", 10, "HOUBLONNAI").
dico("H", 10, "HOUBLONNAS").
dico("H", 10, "HOUBLONNAT").
dico("H", 10, "HOUBLONNEE").
dico("H", 10, "HOUBLONNER").
dico("H", 10, "HOUBLONNES").
dico("H", 10, "HOUBLONNEZ").
dico("H", 10, "HOUERAIENT").
dico("H", 10, "HOUILLERES").
dico("H", 10, "HOUILLEUSE").
dico("H", 10, "HOUPPAIENT").
dico("H", 10, "HOUPPASSES").
dico("H", 10, "HOUPPERAIS").
dico("H", 10, "HOUPPERAIT").
dico("H", 10, "HOUPPERENT").
dico("H", 10, "HOUPPERIEZ").
dico("H", 10, "HOUPPERONS").
dico("H", 10, "HOUPPERONT").
dico("H", 10, "HOUPPETTES").
dico("H", 10, "HOURDAIENT").
dico("H", 10, "HOURDASSES").
dico("H", 10, "HOURDERAIS").
dico("H", 10, "HOURDERAIT").
dico("H", 10, "HOURDERENT").
dico("H", 10, "HOURDERIEZ").
dico("H", 10, "HOURDERONS").
dico("H", 10, "HOURDERONT").
dico("H", 10, "HOUSPILLAI").
dico("H", 10, "HOUSPILLAS").
dico("H", 10, "HOUSPILLAT").
dico("H", 10, "HOUSPILLEE").
dico("H", 10, "HOUSPILLER").
dico("H", 10, "HOUSPILLES").
dico("H", 10, "HOUSPILLEZ").
dico("H", 10, "HOUSSAIENT").
dico("H", 10, "HOUSSASSES").
dico("H", 10, "HOUSSERAIS").
dico("H", 10, "HOUSSERAIT").
dico("H", 10, "HOUSSERENT").
dico("H", 10, "HOUSSERIEZ").
dico("H", 10, "HOUSSERONS").
dico("H", 10, "HOUSSERONT").
dico("H", 10, "HOUSSIERES").
dico("H", 10, "HOUSSINAIS").
dico("H", 10, "HOUSSINAIT").
dico("H", 10, "HOUSSINANT").
dico("H", 10, "HOUSSINEES").
dico("H", 10, "HOUSSINENT").
dico("H", 10, "HOUSSINERA").
dico("H", 10, "HOUSSINIEZ").
dico("H", 10, "HOUSSINONS").
dico("H", 10, "HOVERCRAFT").
dico("H", 10, "HOVERPORTS").
dico("H", 10, "HUCHASSENT").
dico("H", 10, "HUCHASSIEZ").
dico("H", 10, "HUCHERIONS").
dico("H", 10, "HUGOLIENNE").
dico("H", 10, "HUGUENOTES").
dico("H", 10, "HUILASSENT").
dico("H", 10, "HUILASSIEZ").
dico("H", 10, "HUILERIONS").
dico("H", 10, "HUISSERIES").
dico("H", 10, "HUISSIERES").
dico("H", 10, "HUITRIERES").
dico("H", 10, "HULULAIENT").
dico("H", 10, "HULULASSES").
dico("H", 10, "HULULEMENT").
dico("H", 10, "HULULERAIS").
dico("H", 10, "HULULERAIT").
dico("H", 10, "HULULERENT").
dico("H", 10, "HULULERIEZ").
dico("H", 10, "HULULERONS").
dico("H", 10, "HULULERONT").
dico("H", 10, "HUMANISAIS").
dico("H", 10, "HUMANISAIT").
dico("H", 10, "HUMANISANT").
dico("H", 10, "HUMANISEES").
dico("H", 10, "HUMANISENT").
dico("H", 10, "HUMANISERA").
dico("H", 10, "HUMANISIEZ").
dico("H", 10, "HUMANISMES").
dico("H", 10, "HUMANISONS").
dico("H", 10, "HUMANISTES").
dico("H", 10, "HUMANOIDES").
dico("H", 10, "HUMASSIONS").
dico("H", 10, "HUMBLEMENT").
dico("H", 10, "HUMECTAGES").
dico("H", 10, "HUMECTAMES").
dico("H", 10, "HUMECTASSE").
dico("H", 10, "HUMECTATES").
dico("H", 10, "HUMECTERAI").
dico("H", 10, "HUMECTERAS").
dico("H", 10, "HUMECTEREZ").
dico("H", 10, "HUMECTEURS").
dico("H", 10, "HUMECTIONS").
dico("H", 10, "HUMERAIENT").
dico("H", 10, "HUMIDIFIAI").
dico("H", 10, "HUMIDIFIAS").
dico("H", 10, "HUMIDIFIAT").
dico("H", 10, "HUMIDIFIEE").
dico("H", 10, "HUMIDIFIER").
dico("H", 10, "HUMIDIFIES").
dico("H", 10, "HUMIDIFIEZ").
dico("H", 10, "HUMIDIFUGE").
dico("H", 10, "HUMILIAMES").
dico("H", 10, "HUMILIANTE").
dico("H", 10, "HUMILIANTS").
dico("H", 10, "HUMILIASSE").
dico("H", 10, "HUMILIATES").
dico("H", 10, "HUMILIERAI").
dico("H", 10, "HUMILIERAS").
dico("H", 10, "HUMILIEREZ").
dico("H", 10, "HUMILIIONS").
dico("H", 10, "HUMORISMES").
dico("H", 10, "HUMORISTES").
dico("H", 10, "HURLASSENT").
dico("H", 10, "HURLASSIEZ").
dico("H", 10, "HURLEMENTS").
dico("H", 10, "HURLERIONS").
dico("H", 10, "HURLUBERLU").
dico("H", 10, "HURONIENNE").
dico("H", 10, "HURRICANES").
dico("H", 10, "HYACINTHES").
dico("H", 10, "HYBRIDAMES").
dico("H", 10, "HYBRIDASSE").
dico("H", 10, "HYBRIDATES").
dico("H", 10, "HYBRIDERAI").
dico("H", 10, "HYBRIDERAS").
dico("H", 10, "HYBRIDEREZ").
dico("H", 10, "HYBRIDIONS").
dico("H", 10, "HYBRIDISME").
dico("H", 10, "HYBRIDITES").
dico("H", 10, "HYBRIDOMES").
dico("H", 10, "HYDATIQUES").
dico("H", 10, "HYDRACIDES").
dico("H", 10, "HYDRAMNIOS").
dico("H", 10, "HYDRANGEES").
dico("H", 10, "HYDRANTHES").
dico("H", 10, "HYDRARGIES").
dico("H", 10, "HYDRARGYRE").
dico("H", 10, "HYDRATABLE").
dico("H", 10, "HYDRATAMES").
dico("H", 10, "HYDRATANTE").
dico("H", 10, "HYDRATANTS").
dico("H", 10, "HYDRATASSE").
dico("H", 10, "HYDRATATES").
dico("H", 10, "HYDRATERAI").
dico("H", 10, "HYDRATERAS").
dico("H", 10, "HYDRATEREZ").
dico("H", 10, "HYDRATIONS").
dico("H", 10, "HYDRAVIONS").
dico("H", 10, "HYDRAZINES").
dico("H", 10, "HYDROBASES").
dico("H", 10, "HYDROCELES").
dico("H", 10, "HYDROCUTAI").
dico("H", 10, "HYDROCUTAS").
dico("H", 10, "HYDROCUTAT").
dico("H", 10, "HYDROCUTEE").
dico("H", 10, "HYDROCUTER").
dico("H", 10, "HYDROCUTES").
dico("H", 10, "HYDROCUTEZ").
dico("H", 10, "HYDROFOILS").
dico("H", 10, "HYDROFUGEA").
dico("H", 10, "HYDROFUGEE").
dico("H", 10, "HYDROFUGER").
dico("H", 10, "HYDROFUGES").
dico("H", 10, "HYDROFUGEZ").
dico("H", 10, "HYDROGENAI").
dico("H", 10, "HYDROGENAS").
dico("H", 10, "HYDROGENAT").
dico("H", 10, "HYDROGENEE").
dico("H", 10, "HYDROGENER").
dico("H", 10, "HYDROGENES").
dico("H", 10, "HYDROGENEZ").
dico("H", 10, "HYDROHEMIE").
dico("H", 10, "HYDROLASES").
dico("H", 10, "HYDROLITHE").
dico("H", 10, "HYDROLOGIE").
dico("H", 10, "HYDROLOGUE").
dico("H", 10, "HYDROLYSAI").
dico("H", 10, "HYDROLYSAS").
dico("H", 10, "HYDROLYSAT").
dico("H", 10, "HYDROLYSEE").
dico("H", 10, "HYDROLYSER").
dico("H", 10, "HYDROLYSES").
dico("H", 10, "HYDROLYSEZ").
dico("H", 10, "HYDROMETRE").
dico("H", 10, "HYDROPHILE").
dico("H", 10, "HYDROPHOBE").
dico("H", 10, "HYDROPHONE").
dico("H", 10, "HYDROPIQUE").
dico("H", 10, "HYDROPISIE").
dico("H", 10, "HYDROPLANE").
dico("H", 10, "HYDROPTERE").
dico("H", 10, "HYDROXYDES").
dico("H", 10, "HYDROXYLES").
dico("H", 10, "HYGIAPHONE").
dico("H", 10, "HYGIENIQUE").
dico("H", 10, "HYGIENISTE").
dico("H", 10, "HYGROMETRE").
dico("H", 10, "HYGROPHILE").
dico("H", 10, "HYGROPHOBE").
dico("H", 10, "HYGROPHORE").
dico("H", 10, "HYGROSCOPE").
dico("H", 10, "HYGROSTATS").
dico("H", 10, "HYLETIQUES").
dico("H", 10, "HYLOZOISME").
dico("H", 10, "HYOIDIENNE").
dico("H", 10, "HYPALLAGES").
dico("H", 10, "HYPERACTIF").
dico("H", 10, "HYPERALGIE").
dico("H", 10, "HYPERBARES").
dico("H", 10, "HYPERBATES").
dico("H", 10, "HYPERBOLES").
dico("H", 10, "HYPERDULIE").
dico("H", 10, "HYPEREMIES").
dico("H", 10, "HYPERFINES").
dico("H", 10, "HYPERFOCAL").
dico("H", 10, "HYPERGAMIE").
dico("H", 10, "HYPERHEMIE").
dico("H", 10, "HYPERLIENS").
dico("H", 10, "HYPERMEDIA").
dico("H", 10, "HYPERMETRE").
dico("H", 10, "HYPERONYME").
dico("H", 10, "HYPERPLANS").
dico("H", 10, "HYPERTELIE").
dico("H", 10, "HYPERTENDU").
dico("H", 10, "HYPERTEXTE").
dico("H", 10, "HYPERTONIE").
dico("H", 10, "HYPHOLOMES").
dico("H", 10, "HYPNOLOGIE").
dico("H", 10, "HYPNOTIQUE").
dico("H", 10, "HYPNOTISAI").
dico("H", 10, "HYPNOTISAS").
dico("H", 10, "HYPNOTISAT").
dico("H", 10, "HYPNOTISEE").
dico("H", 10, "HYPNOTISER").
dico("H", 10, "HYPNOTISES").
dico("H", 10, "HYPNOTISEZ").
dico("H", 10, "HYPNOTISME").
dico("H", 10, "HYPOCAGNES").
dico("H", 10, "HYPOCAPNIE").
dico("H", 10, "HYPOCAUSTE").
dico("H", 10, "HYPOCENTRE").
dico("H", 10, "HYPOCHROME").
dico("H", 10, "HYPOCONDRE").
dico("H", 10, "HYPOCRISIE").
dico("H", 10, "HYPOCRITES").
dico("H", 10, "HYPODERMES").
dico("H", 10, "HYPOGASTRE").
dico("H", 10, "HYPOGLOSSE").
dico("H", 10, "HYPOKHAGNE").
dico("H", 10, "HYPOMANIES").
dico("H", 10, "HYPOPHYSES").
dico("H", 10, "HYPOPLASIE").
dico("H", 10, "HYPOSODEES").
dico("H", 10, "HYPOSTASES").
dico("H", 10, "HYPOSTASIA").
dico("H", 10, "HYPOSTASIE").
dico("H", 10, "HYPOSTYLES").
dico("H", 10, "HYPOTAUPES").
dico("H", 10, "HYPOTENDUE").
dico("H", 10, "HYPOTENDUS").
dico("H", 10, "HYPOTENSIF").
dico("H", 10, "HYPOTENUSE").
dico("H", 10, "HYPOTHENAR").
dico("H", 10, "HYPOTHEQUA").
dico("H", 10, "HYPOTHEQUE").
dico("H", 10, "HYPOTHESES").
dico("H", 10, "HYPOTONIES").
dico("H", 10, "HYPOTYPOSE").
dico("H", 10, "HYPOXEMIES").
dico("H", 10, "HYPSOMETRE").
dico("H", 10, "HYSTERESES").
dico("H", 10, "HYSTERESIS").
dico("H", 10, "HYSTERIQUE").
