dico("H", 6, "HABILE").
dico("H", 6, "HABITA").
dico("H", 6, "HABITE").
dico("H", 6, "HABITS").
dico("H", 6, "HABLAI").
dico("H", 6, "HABLAS").
dico("H", 6, "HABLAT").
dico("H", 6, "HABLER").
dico("H", 6, "HABLES").
dico("H", 6, "HABLEZ").
dico("H", 6, "HACHAI").
dico("H", 6, "HACHAS").
dico("H", 6, "HACHAT").
dico("H", 6, "HACHEE").
dico("H", 6, "HACHER").
dico("H", 6, "HACHES").
dico("H", 6, "HACHEZ").
dico("H", 6, "HACHIS").
dico("H", 6, "HACKER").
dico("H", 6, "HADALE").
dico("H", 6, "HADAUX").
dico("H", 6, "HADITH").
dico("H", 6, "HADJDJ").
dico("H", 6, "HADJIS").
dico("H", 6, "HADRON").
dico("H", 6, "HAGARD").
dico("H", 6, "HAGGIS").
dico("H", 6, "HAIKAI").
dico("H", 6, "HAIKUS").
dico("H", 6, "HAIMES").
dico("H", 6, "HAINES").
dico("H", 6, "HAIRAI").
dico("H", 6, "HAIRAS").
dico("H", 6, "HAIRES").
dico("H", 6, "HAIREZ").
dico("H", 6, "HAISSE").
dico("H", 6, "HAITES").
dico("H", 6, "HAKKAS").
dico("H", 6, "HALAGE").
dico("H", 6, "HALAIS").
dico("H", 6, "HALAIT").
dico("H", 6, "HALANT").
dico("H", 6, "HALBIS").
dico("H", 6, "HALEES").
dico("H", 6, "HALENA").
dico("H", 6, "HALENE").
dico("H", 6, "HALENT").
dico("H", 6, "HALERA").
dico("H", 6, "HALETA").
dico("H", 6, "HALETE").
dico("H", 6, "HALEUR").
dico("H", 6, "HALIEZ").
dico("H", 6, "HALITE").
dico("H", 6, "HALLAL").
dico("H", 6, "HALLES").
dico("H", 6, "HALOIR").
dico("H", 6, "HALONS").
dico("H", 6, "HALTES").
dico("H", 6, "HALVAS").
dico("H", 6, "HAMACS").
dico("H", 6, "HAMADA").
dico("H", 6, "HAMEAU").
dico("H", 6, "HAMMAM").
dico("H", 6, "HAMPES").
dico("H", 6, "HANAFI").
dico("H", 6, "HANAPS").
dico("H", 6, "HANCHA").
dico("H", 6, "HANCHE").
dico("H", 6, "HANGAR").
dico("H", 6, "HANGUL").
dico("H", 6, "HANSES").
dico("H", 6, "HANTAI").
dico("H", 6, "HANTAS").
dico("H", 6, "HANTAT").
dico("H", 6, "HANTEE").
dico("H", 6, "HANTER").
dico("H", 6, "HANTES").
dico("H", 6, "HANTEZ").
dico("H", 6, "HAPPAI").
dico("H", 6, "HAPPAS").
dico("H", 6, "HAPPAT").
dico("H", 6, "HAPPEE").
dico("H", 6, "HAPPER").
dico("H", 6, "HAPPES").
dico("H", 6, "HAPPEZ").
dico("H", 6, "HAQUET").
dico("H", 6, "HARDAI").
dico("H", 6, "HARDAS").
dico("H", 6, "HARDAT").
dico("H", 6, "HARDEE").
dico("H", 6, "HARDER").
dico("H", 6, "HARDES").
dico("H", 6, "HARDEZ").
dico("H", 6, "HARDIE").
dico("H", 6, "HARDIS").
dico("H", 6, "HAREMS").
dico("H", 6, "HARENG").
dico("H", 6, "HARETS").
dico("H", 6, "HARGNE").
dico("H", 6, "HARKAS").
dico("H", 6, "HARKIE").
dico("H", 6, "HARKIS").
dico("H", 6, "HARLES").
dico("H", 6, "HARPAI").
dico("H", 6, "HARPAS").
dico("H", 6, "HARPAT").
dico("H", 6, "HARPEE").
dico("H", 6, "HARPER").
dico("H", 6, "HARPES").
dico("H", 6, "HARPEZ").
dico("H", 6, "HARPIE").
dico("H", 6, "HARPON").
dico("H", 6, "HASARD").
dico("H", 6, "HASCHS").
dico("H", 6, "HASSID").
dico("H", 6, "HASTEE").
dico("H", 6, "HASTES").
dico("H", 6, "HATAIS").
dico("H", 6, "HATAIT").
dico("H", 6, "HATANT").
dico("H", 6, "HATEES").
dico("H", 6, "HATENT").
dico("H", 6, "HATERA").
dico("H", 6, "HATIER").
dico("H", 6, "HATIEZ").
dico("H", 6, "HATIFS").
dico("H", 6, "HATIVE").
dico("H", 6, "HATONS").
dico("H", 6, "HATURE").
dico("H", 6, "HAUBAN").
dico("H", 6, "HAUSSA").
dico("H", 6, "HAUSSE").
dico("H", 6, "HAUTES").
dico("H", 6, "HAUTIN").
dico("H", 6, "HAUYNE").
dico("H", 6, "HAVAGE").
dico("H", 6, "HAVAIS").
dico("H", 6, "HAVAIT").
dico("H", 6, "HAVANE").
dico("H", 6, "HAVANT").
dico("H", 6, "HAVEES").
dico("H", 6, "HAVENT").
dico("H", 6, "HAVERA").
dico("H", 6, "HAVEUR").
dico("H", 6, "HAVIES").
dico("H", 6, "HAVIEZ").
dico("H", 6, "HAVIRA").
dico("H", 6, "HAVONS").
dico("H", 6, "HAVRES").
dico("H", 6, "HAVRIT").
dico("H", 6, "HAYONS").
dico("H", 6, "HEAUME").
dico("H", 6, "HEBDOS").
dico("H", 6, "HEBETA").
dico("H", 6, "HEBETE").
dico("H", 6, "HEBREU").
dico("H", 6, "HECTOS").
dico("H", 6, "HEGIRE").
dico("H", 6, "HELAIS").
dico("H", 6, "HELAIT").
dico("H", 6, "HELANT").
dico("H", 6, "HELEES").
dico("H", 6, "HELENT").
dico("H", 6, "HELERA").
dico("H", 6, "HELICE").
dico("H", 6, "HELICO").
dico("H", 6, "HELIEE").
dico("H", 6, "HELIEZ").
dico("H", 6, "HELION").
dico("H", 6, "HELIOS").
dico("H", 6, "HELIUM").
dico("H", 6, "HELONS").
dico("H", 6, "HEMINE").
dico("H", 6, "HENNES").
dico("H", 6, "HENNIN").
dico("H", 6, "HENNIR").
dico("H", 6, "HENNIS").
dico("H", 6, "HENNIT").
dico("H", 6, "HENRYS").
dico("H", 6, "HERAUT").
dico("H", 6, "HERBAI").
dico("H", 6, "HERBAS").
dico("H", 6, "HERBAT").
dico("H", 6, "HERBEE").
dico("H", 6, "HERBER").
dico("H", 6, "HERBES").
dico("H", 6, "HERBEZ").
dico("H", 6, "HERBUE").
dico("H", 6, "HERBUS").
dico("H", 6, "HERCHA").
dico("H", 6, "HERCHE").
dico("H", 6, "HEREDO").
dico("H", 6, "HERITA").
dico("H", 6, "HERITE").
dico("H", 6, "HERMES").
dico("H", 6, "HERNIE").
dico("H", 6, "HERONS").
dico("H", 6, "HERPES").
dico("H", 6, "HERSAI").
dico("H", 6, "HERSAS").
dico("H", 6, "HERSAT").
dico("H", 6, "HERSEE").
dico("H", 6, "HERSER").
dico("H", 6, "HERSES").
dico("H", 6, "HERSEZ").
dico("H", 6, "HERVES").
dico("H", 6, "HESITA").
dico("H", 6, "HESITE").
dico("H", 6, "HETERO").
dico("H", 6, "HETMAN").
dico("H", 6, "HETRES").
dico("H", 6, "HEURES").
dico("H", 6, "HEURTA").
dico("H", 6, "HEURTE").
dico("H", 6, "HEURTS").
dico("H", 6, "HEVEAS").
dico("H", 6, "HEXANE").
dico("H", 6, "HEXOSE").
dico("H", 6, "HIAMES").
dico("H", 6, "HIASSE").
dico("H", 6, "HIATAL").
dico("H", 6, "HIATES").
dico("H", 6, "HIATUS").
dico("H", 6, "HIBOUX").
dico("H", 6, "HIDEUR").
dico("H", 6, "HIDEUX").
dico("H", 6, "HIDJAB").
dico("H", 6, "HIEBLE").
dico("H", 6, "HIEMAL").
dico("H", 6, "HIERAI").
dico("H", 6, "HIERAS").
dico("H", 6, "HIEREZ").
dico("H", 6, "HIIONS").
dico("H", 6, "HILARE").
dico("H", 6, "HILOTE").
dico("H", 6, "HINDIE").
dico("H", 6, "HINDIS").
dico("H", 6, "HINDOU").
dico("H", 6, "HIPPIE").
dico("H", 6, "HIPPYS").
dico("H", 6, "HIRCIN").
dico("H", 6, "HISSAI").
dico("H", 6, "HISSAS").
dico("H", 6, "HISSAT").
dico("H", 6, "HISSEE").
dico("H", 6, "HISSER").
dico("H", 6, "HISSES").
dico("H", 6, "HISSEZ").
dico("H", 6, "HIVERS").
dico("H", 6, "HOAZIN").
dico("H", 6, "HOBBYS").
dico("H", 6, "HOCCOS").
dico("H", 6, "HOCHAI").
dico("H", 6, "HOCHAS").
dico("H", 6, "HOCHAT").
dico("H", 6, "HOCHEE").
dico("H", 6, "HOCHER").
dico("H", 6, "HOCHES").
dico("H", 6, "HOCHET").
dico("H", 6, "HOCHEZ").
dico("H", 6, "HOCKEY").
dico("H", 6, "HOIRIE").
dico("H", 6, "HOMARD").
dico("H", 6, "HOMBRE").
dico("H", 6, "HOMMES").
dico("H", 6, "HONGRA").
dico("H", 6, "HONGRE").
dico("H", 6, "HONING").
dico("H", 6, "HONNIE").
dico("H", 6, "HONNIR").
dico("H", 6, "HONNIS").
dico("H", 6, "HONNIT").
dico("H", 6, "HONORA").
dico("H", 6, "HONORE").
dico("H", 6, "HONTES").
dico("H", 6, "HOPAKS").
dico("H", 6, "HOQUET").
dico("H", 6, "HORDES").
dico("H", 6, "HORION").
dico("H", 6, "HORMIS").
dico("H", 6, "HORSIN").
dico("H", 6, "HORSTS").
dico("H", 6, "HOSTIE").
dico("H", 6, "HOSTOS").
dico("H", 6, "HOTELS").
dico("H", 6, "HOTTAI").
dico("H", 6, "HOTTAS").
dico("H", 6, "HOTTAT").
dico("H", 6, "HOTTEE").
dico("H", 6, "HOTTER").
dico("H", 6, "HOTTES").
dico("H", 6, "HOTTEZ").
dico("H", 6, "HOUAGE").
dico("H", 6, "HOUAIS").
dico("H", 6, "HOUAIT").
dico("H", 6, "HOUANT").
dico("H", 6, "HOUARI").
dico("H", 6, "HOUDAN").
dico("H", 6, "HOUEES").
dico("H", 6, "HOUENT").
dico("H", 6, "HOUERA").
dico("H", 6, "HOUIEZ").
dico("H", 6, "HOUKAS").
dico("H", 6, "HOULES").
dico("H", 6, "HOUONS").
dico("H", 6, "HOUPPA").
dico("H", 6, "HOUPPE").
dico("H", 6, "HOUQUE").
dico("H", 6, "HOURDA").
dico("H", 6, "HOURDE").
dico("H", 6, "HOURDS").
dico("H", 6, "HOURIS").
dico("H", 6, "HOURRA").
dico("H", 6, "HOUSES").
dico("H", 6, "HOUSSA").
dico("H", 6, "HOUSSE").
dico("H", 6, "HOYAUX").
dico("H", 6, "HRIVNA").
dico("H", 6, "HUAMES").
dico("H", 6, "HUARDS").
dico("H", 6, "HUARTS").
dico("H", 6, "HUASSE").
dico("H", 6, "HUATES").
dico("H", 6, "HUBLOT").
dico("H", 6, "HUCHAI").
dico("H", 6, "HUCHAS").
dico("H", 6, "HUCHAT").
dico("H", 6, "HUCHEE").
dico("H", 6, "HUCHER").
dico("H", 6, "HUCHES").
dico("H", 6, "HUCHET").
dico("H", 6, "HUCHEZ").
dico("H", 6, "HUERAI").
dico("H", 6, "HUERAS").
dico("H", 6, "HUEREZ").
dico("H", 6, "HUERTA").
dico("H", 6, "HUILAI").
dico("H", 6, "HUILAS").
dico("H", 6, "HUILAT").
dico("H", 6, "HUILEE").
dico("H", 6, "HUILER").
dico("H", 6, "HUILES").
dico("H", 6, "HUILEZ").
dico("H", 6, "HUIONS").
dico("H", 6, "HUITRE").
dico("H", 6, "HULULA").
dico("H", 6, "HULULE").
dico("H", 6, "HUMAGE").
dico("H", 6, "HUMAIN").
dico("H", 6, "HUMAIS").
dico("H", 6, "HUMAIT").
dico("H", 6, "HUMANT").
dico("H", 6, "HUMBLE").
dico("H", 6, "HUMEES").
dico("H", 6, "HUMENT").
dico("H", 6, "HUMERA").
dico("H", 6, "HUMEUR").
dico("H", 6, "HUMIDE").
dico("H", 6, "HUMIEZ").
dico("H", 6, "HUMONS").
dico("H", 6, "HUMOUR").
dico("H", 6, "HUNIER").
dico("H", 6, "HUNTER").
dico("H", 6, "HUPPEE").
dico("H", 6, "HUPPES").
dico("H", 6, "HURLAI").
dico("H", 6, "HURLAS").
dico("H", 6, "HURLAT").
dico("H", 6, "HURLEE").
dico("H", 6, "HURLER").
dico("H", 6, "HURLES").
dico("H", 6, "HURLEZ").
dico("H", 6, "HURONS").
dico("H", 6, "HURRAH").
dico("H", 6, "HUSKYS").
dico("H", 6, "HUTINS").
dico("H", 6, "HUTOIS").
dico("H", 6, "HUTTES").
dico("H", 6, "HUTUES").
dico("H", 6, "HYADES").
dico("H", 6, "HYALIN").
dico("H", 6, "HYDNES").
dico("H", 6, "HYDRES").
dico("H", 6, "HYDRIE").
dico("H", 6, "HYENES").
dico("H", 6, "HYMENS").
dico("H", 6, "HYMNES").
dico("H", 6, "HYOIDE").
dico("H", 6, "HYPERS").
dico("H", 6, "HYPHES").
dico("H", 6, "HYPNES").
dico("H", 6, "HYPOGE").
dico("H", 6, "HYSOPE").
