dico("H", 7, "HABILES").
dico("H", 7, "HABILLA").
dico("H", 7, "HABILLE").
dico("H", 7, "HABITAI").
dico("H", 7, "HABITAS").
dico("H", 7, "HABITAT").
dico("H", 7, "HABITEE").
dico("H", 7, "HABITER").
dico("H", 7, "HABITES").
dico("H", 7, "HABITEZ").
dico("H", 7, "HABITUA").
dico("H", 7, "HABITUE").
dico("H", 7, "HABITUS").
dico("H", 7, "HABLAIS").
dico("H", 7, "HABLAIT").
dico("H", 7, "HABLANT").
dico("H", 7, "HABLENT").
dico("H", 7, "HABLERA").
dico("H", 7, "HABLEUR").
dico("H", 7, "HABLIEZ").
dico("H", 7, "HABLONS").
dico("H", 7, "HACHAGE").
dico("H", 7, "HACHAIS").
dico("H", 7, "HACHAIT").
dico("H", 7, "HACHANT").
dico("H", 7, "HACHEES").
dico("H", 7, "HACHENT").
dico("H", 7, "HACHERA").
dico("H", 7, "HACHEUR").
dico("H", 7, "HACHIEZ").
dico("H", 7, "HACHOIR").
dico("H", 7, "HACHONS").
dico("H", 7, "HACHURA").
dico("H", 7, "HACHURE").
dico("H", 7, "HACKERS").
dico("H", 7, "HADALES").
dico("H", 7, "HADDOCK").
dico("H", 7, "HADITHS").
dico("H", 7, "HADJDJS").
dico("H", 7, "HADRONS").
dico("H", 7, "HAFNIUM").
dico("H", 7, "HAGARDE").
dico("H", 7, "HAGARDS").
dico("H", 7, "HAHNIUM").
dico("H", 7, "HAIDOUC").
dico("H", 7, "HAIDOUK").
dico("H", 7, "HAIKAIS").
dico("H", 7, "HAILLON").
dico("H", 7, "HAINEUX").
dico("H", 7, "HAIRAIS").
dico("H", 7, "HAIRAIT").
dico("H", 7, "HAIRENT").
dico("H", 7, "HAIRIEZ").
dico("H", 7, "HAIRONS").
dico("H", 7, "HAIRONT").
dico("H", 7, "HAISSES").
dico("H", 7, "HAISSEZ").
dico("H", 7, "HAITIEN").
dico("H", 7, "HALAGES").
dico("H", 7, "HALAMES").
dico("H", 7, "HALASSE").
dico("H", 7, "HALATES").
dico("H", 7, "HALBRAN").
dico("H", 7, "HALEINE").
dico("H", 7, "HALENAI").
dico("H", 7, "HALENAS").
dico("H", 7, "HALENAT").
dico("H", 7, "HALENEE").
dico("H", 7, "HALENER").
dico("H", 7, "HALENES").
dico("H", 7, "HALENEZ").
dico("H", 7, "HALERAI").
dico("H", 7, "HALERAS").
dico("H", 7, "HALEREZ").
dico("H", 7, "HALETAI").
dico("H", 7, "HALETAS").
dico("H", 7, "HALETAT").
dico("H", 7, "HALETER").
dico("H", 7, "HALETES").
dico("H", 7, "HALETEZ").
dico("H", 7, "HALETTE").
dico("H", 7, "HALEURS").
dico("H", 7, "HALEUSE").
dico("H", 7, "HALICTE").
dico("H", 7, "HALIONS").
dico("H", 7, "HALIPLE").
dico("H", 7, "HALITES").
dico("H", 7, "HALLAGE").
dico("H", 7, "HALLALI").
dico("H", 7, "HALLIER").
dico("H", 7, "HALOIRS").
dico("H", 7, "HALTERE").
dico("H", 7, "HAMADAS").
dico("H", 7, "HAMEAUX").
dico("H", 7, "HAMECON").
dico("H", 7, "HAMMAMS").
dico("H", 7, "HAMSTER").
dico("H", 7, "HANAFIS").
dico("H", 7, "HANBALI").
dico("H", 7, "HANCHAI").
dico("H", 7, "HANCHAS").
dico("H", 7, "HANCHAT").
dico("H", 7, "HANCHEE").
dico("H", 7, "HANCHER").
dico("H", 7, "HANCHES").
dico("H", 7, "HANCHEZ").
dico("H", 7, "HANGARS").
dico("H", 7, "HANGULS").
dico("H", 7, "HANSART").
dico("H", 7, "HANTAIS").
dico("H", 7, "HANTAIT").
dico("H", 7, "HANTANT").
dico("H", 7, "HANTEES").
dico("H", 7, "HANTENT").
dico("H", 7, "HANTERA").
dico("H", 7, "HANTIEZ").
dico("H", 7, "HANTISE").
dico("H", 7, "HANTONS").
dico("H", 7, "HAOUSSA").
dico("H", 7, "HAPPAIS").
dico("H", 7, "HAPPAIT").
dico("H", 7, "HAPPANT").
dico("H", 7, "HAPPEES").
dico("H", 7, "HAPPENT").
dico("H", 7, "HAPPERA").
dico("H", 7, "HAPPIEZ").
dico("H", 7, "HAPPONS").
dico("H", 7, "HAPTENE").
dico("H", 7, "HAQUETS").
dico("H", 7, "HARASSA").
dico("H", 7, "HARASSE").
dico("H", 7, "HARCELA").
dico("H", 7, "HARCELE").
dico("H", 7, "HARDAIS").
dico("H", 7, "HARDAIT").
dico("H", 7, "HARDANT").
dico("H", 7, "HARDEES").
dico("H", 7, "HARDENT").
dico("H", 7, "HARDERA").
dico("H", 7, "HARDIES").
dico("H", 7, "HARDIEZ").
dico("H", 7, "HARDONS").
dico("H", 7, "HARENGS").
dico("H", 7, "HARFANG").
dico("H", 7, "HARGNES").
dico("H", 7, "HARICOT").
dico("H", 7, "HARISSA").
dico("H", 7, "HARKIES").
dico("H", 7, "HARNAIS").
dico("H", 7, "HARNOIS").
dico("H", 7, "HARPAIL").
dico("H", 7, "HARPAIS").
dico("H", 7, "HARPAIT").
dico("H", 7, "HARPANT").
dico("H", 7, "HARPEES").
dico("H", 7, "HARPENT").
dico("H", 7, "HARPERA").
dico("H", 7, "HARPIES").
dico("H", 7, "HARPIEZ").
dico("H", 7, "HARPONS").
dico("H", 7, "HARRIER").
dico("H", 7, "HASARDA").
dico("H", 7, "HASARDE").
dico("H", 7, "HASARDS").
dico("H", 7, "HASSIDS").
dico("H", 7, "HASSIUM").
dico("H", 7, "HASTATI").
dico("H", 7, "HASTEES").
dico("H", 7, "HATAMES").
dico("H", 7, "HATASSE").
dico("H", 7, "HATATES").
dico("H", 7, "HATELET").
dico("H", 7, "HATELLE").
dico("H", 7, "HATERAI").
dico("H", 7, "HATERAS").
dico("H", 7, "HATEREZ").
dico("H", 7, "HATIERS").
dico("H", 7, "HATIONS").
dico("H", 7, "HATIVES").
dico("H", 7, "HATURES").
dico("H", 7, "HAUBANA").
dico("H", 7, "HAUBANE").
dico("H", 7, "HAUBANS").
dico("H", 7, "HAUBERT").
dico("H", 7, "HAUSSAI").
dico("H", 7, "HAUSSAS").
dico("H", 7, "HAUSSAT").
dico("H", 7, "HAUSSEE").
dico("H", 7, "HAUSSER").
dico("H", 7, "HAUSSES").
dico("H", 7, "HAUSSEZ").
dico("H", 7, "HAUTAIN").
dico("H", 7, "HAUTEUR").
dico("H", 7, "HAUTINS").
dico("H", 7, "HAUYNES").
dico("H", 7, "HAVAGES").
dico("H", 7, "HAVAMES").
dico("H", 7, "HAVANES").
dico("H", 7, "HAVASSE").
dico("H", 7, "HAVATES").
dico("H", 7, "HAVENET").
dico("H", 7, "HAVERAI").
dico("H", 7, "HAVERAS").
dico("H", 7, "HAVEREZ").
dico("H", 7, "HAVEURS").
dico("H", 7, "HAVEUSE").
dico("H", 7, "HAVIMES").
dico("H", 7, "HAVIONS").
dico("H", 7, "HAVIRAI").
dico("H", 7, "HAVIRAS").
dico("H", 7, "HAVIREZ").
dico("H", 7, "HAVISSE").
dico("H", 7, "HAVITES").
dico("H", 7, "HAVRAIS").
dico("H", 7, "HAVRITS").
dico("H", 7, "HAWAIEN").
dico("H", 7, "HEAUMES").
dico("H", 7, "HEBERGE").
dico("H", 7, "HEBETAI").
dico("H", 7, "HEBETAS").
dico("H", 7, "HEBETAT").
dico("H", 7, "HEBETEE").
dico("H", 7, "HEBETER").
dico("H", 7, "HEBETES").
dico("H", 7, "HEBETEZ").
dico("H", 7, "HEBREUX").
dico("H", 7, "HECTARE").
dico("H", 7, "HEGIRES").
dico("H", 7, "HELAMES").
dico("H", 7, "HELASSE").
dico("H", 7, "HELATES").
dico("H", 7, "HELERAI").
dico("H", 7, "HELERAS").
dico("H", 7, "HELEREZ").
dico("H", 7, "HELICES").
dico("H", 7, "HELICON").
dico("H", 7, "HELICOS").
dico("H", 7, "HELIEES").
dico("H", 7, "HELIONS").
dico("H", 7, "HELISKI").
dico("H", 7, "HELIUMS").
dico("H", 7, "HELLENE").
dico("H", 7, "HELODEE").
dico("H", 7, "HELVETE").
dico("H", 7, "HEMATIE").
dico("H", 7, "HEMINEE").
dico("H", 7, "HEMINES").
dico("H", 7, "HEMIOLE").
dico("H", 7, "HEMIONE").
dico("H", 7, "HENNINS").
dico("H", 7, "HENNIRA").
dico("H", 7, "HEPTANE").
dico("H", 7, "HERAUTS").
dico("H", 7, "HERBACE").
dico("H", 7, "HERBAGE").
dico("H", 7, "HERBAIS").
dico("H", 7, "HERBAIT").
dico("H", 7, "HERBANT").
dico("H", 7, "HERBEES").
dico("H", 7, "HERBENT").
dico("H", 7, "HERBERA").
dico("H", 7, "HERBEUX").
dico("H", 7, "HERBIER").
dico("H", 7, "HERBIEZ").
dico("H", 7, "HERBONS").
dico("H", 7, "HERBUES").
dico("H", 7, "HERCHAI").
dico("H", 7, "HERCHAS").
dico("H", 7, "HERCHAT").
dico("H", 7, "HERCHER").
dico("H", 7, "HERCHES").
dico("H", 7, "HERCHEZ").
dico("H", 7, "HERCULE").
dico("H", 7, "HEREDOS").
dico("H", 7, "HERESIE").
dico("H", 7, "HERISSA").
dico("H", 7, "HERISSE").
dico("H", 7, "HERITAI").
dico("H", 7, "HERITAS").
dico("H", 7, "HERITAT").
dico("H", 7, "HERITEE").
dico("H", 7, "HERITER").
dico("H", 7, "HERITES").
dico("H", 7, "HERITEZ").
dico("H", 7, "HERMINE").
dico("H", 7, "HERNIEE").
dico("H", 7, "HERNIES").
dico("H", 7, "HEROIDE").
dico("H", 7, "HEROINE").
dico("H", 7, "HERSAGE").
dico("H", 7, "HERSAIS").
dico("H", 7, "HERSAIT").
dico("H", 7, "HERSANT").
dico("H", 7, "HERSCHA").
dico("H", 7, "HERSCHE").
dico("H", 7, "HERSEES").
dico("H", 7, "HERSENT").
dico("H", 7, "HERSERA").
dico("H", 7, "HERSEUR").
dico("H", 7, "HERSIEZ").
dico("H", 7, "HERSONS").
dico("H", 7, "HESITAI").
dico("H", 7, "HESITAS").
dico("H", 7, "HESITAT").
dico("H", 7, "HESITER").
dico("H", 7, "HESITES").
dico("H", 7, "HESITEZ").
dico("H", 7, "HESSOIS").
dico("H", 7, "HETAIRE").
dico("H", 7, "HETERIE").
dico("H", 7, "HETEROS").
dico("H", 7, "HETMANS").
dico("H", 7, "HETRAIE").
dico("H", 7, "HEUREUX").
dico("H", 7, "HEURTAI").
dico("H", 7, "HEURTAS").
dico("H", 7, "HEURTAT").
dico("H", 7, "HEURTEE").
dico("H", 7, "HEURTER").
dico("H", 7, "HEURTES").
dico("H", 7, "HEURTEZ").
dico("H", 7, "HEXANES").
dico("H", 7, "HEXOSES").
dico("H", 7, "HIAIENT").
dico("H", 7, "HIASSES").
dico("H", 7, "HIATALE").
dico("H", 7, "HIATAUX").
dico("H", 7, "HIBERNA").
dico("H", 7, "HIBERNE").
dico("H", 7, "HICKORY").
dico("H", 7, "HIDALGO").
dico("H", 7, "HIDEURS").
dico("H", 7, "HIDEUSE").
dico("H", 7, "HIDJABS").
dico("H", 7, "HIEBLES").
dico("H", 7, "HIEMALE").
dico("H", 7, "HIEMAUX").
dico("H", 7, "HIEMENT").
dico("H", 7, "HIERAIS").
dico("H", 7, "HIERAIT").
dico("H", 7, "HIERENT").
dico("H", 7, "HIERIEZ").
dico("H", 7, "HIERONS").
dico("H", 7, "HIERONT").
dico("H", 7, "HILAIRE").
dico("H", 7, "HILARES").
dico("H", 7, "HILOIRE").
dico("H", 7, "HILOTES").
dico("H", 7, "HINDIES").
dico("H", 7, "HINDOUE").
dico("H", 7, "HINDOUS").
dico("H", 7, "HIPPEIS").
dico("H", 7, "HIPPEUS").
dico("H", 7, "HIPPIES").
dico("H", 7, "HIRCINE").
dico("H", 7, "HIRCINS").
dico("H", 7, "HIRSUTE").
dico("H", 7, "HISPIDE").
dico("H", 7, "HISSAGE").
dico("H", 7, "HISSAIS").
dico("H", 7, "HISSAIT").
dico("H", 7, "HISSANT").
dico("H", 7, "HISSEES").
dico("H", 7, "HISSENT").
dico("H", 7, "HISSERA").
dico("H", 7, "HISSIEZ").
dico("H", 7, "HISSONS").
dico("H", 7, "HISTONE").
dico("H", 7, "HITTITE").
dico("H", 7, "HIVERNA").
dico("H", 7, "HIVERNE").
dico("H", 7, "HOAZINS").
dico("H", 7, "HOBBIES").
dico("H", 7, "HOCHAIS").
dico("H", 7, "HOCHAIT").
dico("H", 7, "HOCHANT").
dico("H", 7, "HOCHEES").
dico("H", 7, "HOCHENT").
dico("H", 7, "HOCHERA").
dico("H", 7, "HOCHETS").
dico("H", 7, "HOCHIEZ").
dico("H", 7, "HOCHONS").
dico("H", 7, "HOCKEYS").
dico("H", 7, "HOIRIES").
dico("H", 7, "HOLDING").
dico("H", 7, "HOLISME").
dico("H", 7, "HOLISTE").
dico("H", 7, "HOLMIUM").
dico("H", 7, "HOLSTER").
dico("H", 7, "HOMARDS").
dico("H", 7, "HOMBRES").
dico("H", 7, "HOMELIE").
dico("H", 7, "HOMMAGE").
dico("H", 7, "HONCHET").
dico("H", 7, "HONGRAI").
dico("H", 7, "HONGRAS").
dico("H", 7, "HONGRAT").
dico("H", 7, "HONGREE").
dico("H", 7, "HONGRER").
dico("H", 7, "HONGRES").
dico("H", 7, "HONGREZ").
dico("H", 7, "HONINGS").
dico("H", 7, "HONNETE").
dico("H", 7, "HONNEUR").
dico("H", 7, "HONNIES").
dico("H", 7, "HONNIRA").
dico("H", 7, "HONORAI").
dico("H", 7, "HONORAS").
dico("H", 7, "HONORAT").
dico("H", 7, "HONOREE").
dico("H", 7, "HONORER").
dico("H", 7, "HONORES").
dico("H", 7, "HONOREZ").
dico("H", 7, "HONTEUX").
dico("H", 7, "HOPITAL").
dico("H", 7, "HOPLITE").
dico("H", 7, "HOQUETA").
dico("H", 7, "HOQUETE").
dico("H", 7, "HOQUETS").
dico("H", 7, "HORAIRE").
dico("H", 7, "HORIONS").
dico("H", 7, "HORIZON").
dico("H", 7, "HORLOGE").
dico("H", 7, "HORMONA").
dico("H", 7, "HORMONE").
dico("H", 7, "HORREUR").
dico("H", 7, "HORSAIN").
dico("H", 7, "HORSINS").
dico("H", 7, "HOSANNA").
dico("H", 7, "HOSPICE").
dico("H", 7, "HOSTEAU").
dico("H", 7, "HOSTIES").
dico("H", 7, "HOSTILE").
dico("H", 7, "HOTESSE").
dico("H", 7, "HOTTAIS").
dico("H", 7, "HOTTAIT").
dico("H", 7, "HOTTANT").
dico("H", 7, "HOTTEES").
dico("H", 7, "HOTTENT").
dico("H", 7, "HOTTERA").
dico("H", 7, "HOTTEUR").
dico("H", 7, "HOTTIEZ").
dico("H", 7, "HOTTONS").
dico("H", 7, "HOUACHE").
dico("H", 7, "HOUAGES").
dico("H", 7, "HOUAMES").
dico("H", 7, "HOUARIS").
dico("H", 7, "HOUASSE").
dico("H", 7, "HOUATES").
dico("H", 7, "HOUBLON").
dico("H", 7, "HOUDANS").
dico("H", 7, "HOUERAI").
dico("H", 7, "HOUERAS").
dico("H", 7, "HOUEREZ").
dico("H", 7, "HOUILLE").
dico("H", 7, "HOUIONS").
dico("H", 7, "HOULEUX").
dico("H", 7, "HOULQUE").
dico("H", 7, "HOUPPAI").
dico("H", 7, "HOUPPAS").
dico("H", 7, "HOUPPAT").
dico("H", 7, "HOUPPEE").
dico("H", 7, "HOUPPER").
dico("H", 7, "HOUPPES").
dico("H", 7, "HOUPPEZ").
dico("H", 7, "HOUQUES").
dico("H", 7, "HOURDAI").
dico("H", 7, "HOURDAS").
dico("H", 7, "HOURDAT").
dico("H", 7, "HOURDEE").
dico("H", 7, "HOURDER").
dico("H", 7, "HOURDES").
dico("H", 7, "HOURDEZ").
dico("H", 7, "HOURDIS").
dico("H", 7, "HOURQUE").
dico("H", 7, "HOURRAH").
dico("H", 7, "HOURRAS").
dico("H", 7, "HOUSARD").
dico("H", 7, "HOUSEAU").
dico("H", 7, "HOUSSAI").
dico("H", 7, "HOUSSAS").
dico("H", 7, "HOUSSAT").
dico("H", 7, "HOUSSEE").
dico("H", 7, "HOUSSER").
dico("H", 7, "HOUSSES").
dico("H", 7, "HOUSSEZ").
dico("H", 7, "HRIVNAS").
dico("H", 7, "HUAIENT").
dico("H", 7, "HUASSES").
dico("H", 7, "HUBLOTS").
dico("H", 7, "HUCHAIS").
dico("H", 7, "HUCHAIT").
dico("H", 7, "HUCHANT").
dico("H", 7, "HUCHEES").
dico("H", 7, "HUCHENT").
dico("H", 7, "HUCHERA").
dico("H", 7, "HUCHETS").
dico("H", 7, "HUCHIER").
dico("H", 7, "HUCHIEZ").
dico("H", 7, "HUCHONS").
dico("H", 7, "HUERAIS").
dico("H", 7, "HUERAIT").
dico("H", 7, "HUERENT").
dico("H", 7, "HUERIEZ").
dico("H", 7, "HUERONS").
dico("H", 7, "HUERONT").
dico("H", 7, "HUERTAS").
dico("H", 7, "HUILAGE").
dico("H", 7, "HUILAIS").
dico("H", 7, "HUILAIT").
dico("H", 7, "HUILANT").
dico("H", 7, "HUILEES").
dico("H", 7, "HUILENT").
dico("H", 7, "HUILERA").
dico("H", 7, "HUILEUX").
dico("H", 7, "HUILIER").
dico("H", 7, "HUILIEZ").
dico("H", 7, "HUILONS").
dico("H", 7, "HUITAIN").
dico("H", 7, "HUITRES").
dico("H", 7, "HULLOIS").
dico("H", 7, "HULOTTE").
dico("H", 7, "HULULAI").
dico("H", 7, "HULULAS").
dico("H", 7, "HULULAT").
dico("H", 7, "HULULER").
dico("H", 7, "HULULES").
dico("H", 7, "HULULEZ").
dico("H", 7, "HUMAGES").
dico("H", 7, "HUMAGNE").
dico("H", 7, "HUMAINE").
dico("H", 7, "HUMAINS").
dico("H", 7, "HUMAMES").
dico("H", 7, "HUMASSE").
dico("H", 7, "HUMATES").
dico("H", 7, "HUMBLES").
dico("H", 7, "HUMECTA").
dico("H", 7, "HUMECTE").
dico("H", 7, "HUMERAI").
dico("H", 7, "HUMERAL").
dico("H", 7, "HUMERAS").
dico("H", 7, "HUMEREZ").
dico("H", 7, "HUMERUS").
dico("H", 7, "HUMEURS").
dico("H", 7, "HUMIDES").
dico("H", 7, "HUMILIA").
dico("H", 7, "HUMILIE").
dico("H", 7, "HUMIONS").
dico("H", 7, "HUMIQUE").
dico("H", 7, "HUMORAL").
dico("H", 7, "HUMOURS").
dico("H", 7, "HUNIERS").
dico("H", 7, "HUNTERS").
dico("H", 7, "HUPPEES").
dico("H", 7, "HURDLER").
dico("H", 7, "HURLAIS").
dico("H", 7, "HURLAIT").
dico("H", 7, "HURLANT").
dico("H", 7, "HURLEES").
dico("H", 7, "HURLENT").
dico("H", 7, "HURLERA").
dico("H", 7, "HURLEUR").
dico("H", 7, "HURLIEZ").
dico("H", 7, "HURLONS").
dico("H", 7, "HURONNE").
dico("H", 7, "HURRAHS").
dico("H", 7, "HUSKIES").
dico("H", 7, "HUSSARD").
dico("H", 7, "HUSSITE").
dico("H", 7, "HUTINET").
dico("H", 7, "HUTOISE").
dico("H", 7, "HYALINE").
dico("H", 7, "HYALINS").
dico("H", 7, "HYALITE").
dico("H", 7, "HYBRIDA").
dico("H", 7, "HYBRIDE").
dico("H", 7, "HYDRANT").
dico("H", 7, "HYDRATA").
dico("H", 7, "HYDRATE").
dico("H", 7, "HYDRIES").
dico("H", 7, "HYDROLE").
dico("H", 7, "HYDRURE").
dico("H", 7, "HYGIENE").
dico("H", 7, "HYGROMA").
dico("H", 7, "HYMENEE").
dico("H", 7, "HYOIDES").
dico("H", 7, "HYPERON").
dico("H", 7, "HYPNOSE").
dico("H", 7, "HYPOGEE").
dico("H", 7, "HYPOGES").
dico("H", 7, "HYPOIDE").
dico("H", 7, "HYPOXIE").
dico("H", 7, "HYSOPES").
