dico("H", 9, "HABANERAS").
dico("H", 9, "HABILETES").
dico("H", 9, "HABILITAI").
dico("H", 9, "HABILITAS").
dico("H", 9, "HABILITAT").
dico("H", 9, "HABILITEE").
dico("H", 9, "HABILITER").
dico("H", 9, "HABILITES").
dico("H", 9, "HABILITEZ").
dico("H", 9, "HABILLAGE").
dico("H", 9, "HABILLAIS").
dico("H", 9, "HABILLAIT").
dico("H", 9, "HABILLANT").
dico("H", 9, "HABILLEES").
dico("H", 9, "HABILLENT").
dico("H", 9, "HABILLERA").
dico("H", 9, "HABILLEUR").
dico("H", 9, "HABILLIEZ").
dico("H", 9, "HABILLONS").
dico("H", 9, "HABITABLE").
dico("H", 9, "HABITACLE").
dico("H", 9, "HABITAMES").
dico("H", 9, "HABITANTE").
dico("H", 9, "HABITANTS").
dico("H", 9, "HABITASSE").
dico("H", 9, "HABITATES").
dico("H", 9, "HABITERAI").
dico("H", 9, "HABITERAS").
dico("H", 9, "HABITEREZ").
dico("H", 9, "HABITIONS").
dico("H", 9, "HABITUAIS").
dico("H", 9, "HABITUAIT").
dico("H", 9, "HABITUANT").
dico("H", 9, "HABITUDES").
dico("H", 9, "HABITUEES").
dico("H", 9, "HABITUELS").
dico("H", 9, "HABITUENT").
dico("H", 9, "HABITUERA").
dico("H", 9, "HABITUIEZ").
dico("H", 9, "HABITUONS").
dico("H", 9, "HABLAIENT").
dico("H", 9, "HABLASSES").
dico("H", 9, "HABLERAIS").
dico("H", 9, "HABLERAIT").
dico("H", 9, "HABLERENT").
dico("H", 9, "HABLERIES").
dico("H", 9, "HABLERIEZ").
dico("H", 9, "HABLERONS").
dico("H", 9, "HABLERONT").
dico("H", 9, "HABLEUSES").
dico("H", 9, "HACHAIENT").
dico("H", 9, "HACHASSES").
dico("H", 9, "HACHEMENT").
dico("H", 9, "HACHEMITE").
dico("H", 9, "HACHERAIS").
dico("H", 9, "HACHERAIT").
dico("H", 9, "HACHEREAU").
dico("H", 9, "HACHERENT").
dico("H", 9, "HACHERIEZ").
dico("H", 9, "HACHERONS").
dico("H", 9, "HACHERONT").
dico("H", 9, "HACHETTES").
dico("H", 9, "HACHEUSES").
dico("H", 9, "HACHISCHS").
dico("H", 9, "HACHURAIS").
dico("H", 9, "HACHURAIT").
dico("H", 9, "HACHURANT").
dico("H", 9, "HACHUREES").
dico("H", 9, "HACHURENT").
dico("H", 9, "HACHURERA").
dico("H", 9, "HACHURIEZ").
dico("H", 9, "HACHURONS").
dico("H", 9, "HACIENDAS").
dico("H", 9, "HAGUENOIS").
dico("H", 9, "HAINEUSES").
dico("H", 9, "HAINUYERE").
dico("H", 9, "HAINUYERS").
dico("H", 9, "HAIRAIENT").
dico("H", 9, "HAISSABLE").
dico("H", 9, "HAISSIONS").
dico("H", 9, "HAITIENNE").
dico("H", 9, "HALASSENT").
dico("H", 9, "HALASSIEZ").
dico("H", 9, "HALBRENEE").
dico("H", 9, "HALBRENES").
dico("H", 9, "HALECRETS").
dico("H", 9, "HALENAMES").
dico("H", 9, "HALENASSE").
dico("H", 9, "HALENATES").
dico("H", 9, "HALENERAI").
dico("H", 9, "HALENERAS").
dico("H", 9, "HALENEREZ").
dico("H", 9, "HALENIONS").
dico("H", 9, "HALERIONS").
dico("H", 9, "HALETAMES").
dico("H", 9, "HALETANTE").
dico("H", 9, "HALETANTS").
dico("H", 9, "HALETASSE").
dico("H", 9, "HALETATES").
dico("H", 9, "HALETERAI").
dico("H", 9, "HALETERAS").
dico("H", 9, "HALETEREZ").
dico("H", 9, "HALETIONS").
dico("H", 9, "HALIOTIDE").
dico("H", 9, "HALITUEUX").
dico("H", 9, "HALLOWEEN").
dico("H", 9, "HALLUCINA").
dico("H", 9, "HALLUCINE").
dico("H", 9, "HALOGENAI").
dico("H", 9, "HALOGENAS").
dico("H", 9, "HALOGENAT").
dico("H", 9, "HALOGENEE").
dico("H", 9, "HALOGENER").
dico("H", 9, "HALOGENES").
dico("H", 9, "HALOGENEZ").
dico("H", 9, "HALOPHILE").
dico("H", 9, "HALOPHYTE").
dico("H", 9, "HALOTHANE").
dico("H", 9, "HAMADRYAS").
dico("H", 9, "HAMAMELIS").
dico("H", 9, "HAMBURGER").
dico("H", 9, "HAMECONNA").
dico("H", 9, "HAMECONNE").
dico("H", 9, "HANAFISME").
dico("H", 9, "HANAFITES").
dico("H", 9, "HANBALITE").
dico("H", 9, "HANCHAMES").
dico("H", 9, "HANCHASSE").
dico("H", 9, "HANCHATES").
dico("H", 9, "HANCHERAI").
dico("H", 9, "HANCHERAS").
dico("H", 9, "HANCHEREZ").
dico("H", 9, "HANCHIONS").
dico("H", 9, "HANDBALLS").
dico("H", 9, "HANDICAPA").
dico("H", 9, "HANDICAPE").
dico("H", 9, "HANDICAPS").
dico("H", 9, "HANNETONS").
dico("H", 9, "HANOUKKAS").
dico("H", 9, "HANOVRIEN").
dico("H", 9, "HANSEATES").
dico("H", 9, "HANTAIENT").
dico("H", 9, "HANTASSES").
dico("H", 9, "HANTERAIS").
dico("H", 9, "HANTERAIT").
dico("H", 9, "HANTERENT").
dico("H", 9, "HANTERIEZ").
dico("H", 9, "HANTERONS").
dico("H", 9, "HANTERONT").
dico("H", 9, "HAPALIDES").
dico("H", 9, "HAPLOIDES").
dico("H", 9, "HAPLOIDIE").
dico("H", 9, "HAPLONTES").
dico("H", 9, "HAPPAIENT").
dico("H", 9, "HAPPASSES").
dico("H", 9, "HAPPEMENT").
dico("H", 9, "HAPPENING").
dico("H", 9, "HAPPERAIS").
dico("H", 9, "HAPPERAIT").
dico("H", 9, "HAPPERENT").
dico("H", 9, "HAPPERIEZ").
dico("H", 9, "HAPPERONS").
dico("H", 9, "HAPPERONT").
dico("H", 9, "HAPTIQUES").
dico("H", 9, "HAQUEBUTE").
dico("H", 9, "HAQUENEES").
dico("H", 9, "HARANGUAI").
dico("H", 9, "HARANGUAS").
dico("H", 9, "HARANGUAT").
dico("H", 9, "HARANGUEE").
dico("H", 9, "HARANGUER").
dico("H", 9, "HARANGUES").
dico("H", 9, "HARANGUEZ").
dico("H", 9, "HARARAISE").
dico("H", 9, "HARASSAIS").
dico("H", 9, "HARASSAIT").
dico("H", 9, "HARASSANT").
dico("H", 9, "HARASSEES").
dico("H", 9, "HARASSENT").
dico("H", 9, "HARASSERA").
dico("H", 9, "HARASSIEZ").
dico("H", 9, "HARASSONS").
dico("H", 9, "HARCELAIS").
dico("H", 9, "HARCELAIT").
dico("H", 9, "HARCELANT").
dico("H", 9, "HARCELEES").
dico("H", 9, "HARCELENT").
dico("H", 9, "HARCELERA").
dico("H", 9, "HARCELEUR").
dico("H", 9, "HARCELIEZ").
dico("H", 9, "HARCELLES").
dico("H", 9, "HARCELONS").
dico("H", 9, "HARDAIENT").
dico("H", 9, "HARDASSES").
dico("H", 9, "HARDCORES").
dico("H", 9, "HARDERAIS").
dico("H", 9, "HARDERAIT").
dico("H", 9, "HARDERENT").
dico("H", 9, "HARDERIEZ").
dico("H", 9, "HARDERONS").
dico("H", 9, "HARDERONT").
dico("H", 9, "HARDIESSE").
dico("H", 9, "HARDIMENT").
dico("H", 9, "HARDWARES").
dico("H", 9, "HARENGERE").
dico("H", 9, "HARENGUET").
dico("H", 9, "HARGNEUSE").
dico("H", 9, "HARIDELLE").
dico("H", 9, "HARMATTAN").
dico("H", 9, "HARMONICA").
dico("H", 9, "HARMONIES").
dico("H", 9, "HARMONISA").
dico("H", 9, "HARMONISE").
dico("H", 9, "HARMONIUM").
dico("H", 9, "HARNACHAI").
dico("H", 9, "HARNACHAS").
dico("H", 9, "HARNACHAT").
dico("H", 9, "HARNACHEE").
dico("H", 9, "HARNACHER").
dico("H", 9, "HARNACHES").
dico("H", 9, "HARNACHEZ").
dico("H", 9, "HARPAGONS").
dico("H", 9, "HARPAIENT").
dico("H", 9, "HARPAILLE").
dico("H", 9, "HARPASSES").
dico("H", 9, "HARPERAIS").
dico("H", 9, "HARPERAIT").
dico("H", 9, "HARPERENT").
dico("H", 9, "HARPERIEZ").
dico("H", 9, "HARPERONS").
dico("H", 9, "HARPERONT").
dico("H", 9, "HARPISTES").
dico("H", 9, "HARPOISES").
dico("H", 9, "HARPONNAI").
dico("H", 9, "HARPONNAS").
dico("H", 9, "HARPONNAT").
dico("H", 9, "HARPONNEE").
dico("H", 9, "HARPONNER").
dico("H", 9, "HARPONNES").
dico("H", 9, "HARPONNEZ").
dico("H", 9, "HARUSPICE").
dico("H", 9, "HASARDAIS").
dico("H", 9, "HASARDAIT").
dico("H", 9, "HASARDANT").
dico("H", 9, "HASARDEES").
dico("H", 9, "HASARDENT").
dico("H", 9, "HASARDERA").
dico("H", 9, "HASARDEUX").
dico("H", 9, "HASARDIEZ").
dico("H", 9, "HASARDONS").
dico("H", 9, "HASCHICHS").
dico("H", 9, "HASCHISCH").
dico("H", 9, "HASTAIRES").
dico("H", 9, "HATASSENT").
dico("H", 9, "HATASSIEZ").
dico("H", 9, "HATELETTE").
dico("H", 9, "HATEREAUX").
dico("H", 9, "HATERIONS").
dico("H", 9, "HATIVEAUX").
dico("H", 9, "HATTERIAS").
dico("H", 9, "HAUBANAGE").
dico("H", 9, "HAUBANAIS").
dico("H", 9, "HAUBANAIT").
dico("H", 9, "HAUBANANT").
dico("H", 9, "HAUBANEES").
dico("H", 9, "HAUBANENT").
dico("H", 9, "HAUBANERA").
dico("H", 9, "HAUBANIEZ").
dico("H", 9, "HAUBANONS").
dico("H", 9, "HAUSSAMES").
dico("H", 9, "HAUSSASSE").
dico("H", 9, "HAUSSATES").
dico("H", 9, "HAUSSERAI").
dico("H", 9, "HAUSSERAS").
dico("H", 9, "HAUSSEREZ").
dico("H", 9, "HAUSSIERE").
dico("H", 9, "HAUSSIERS").
dico("H", 9, "HAUSSIONS").
dico("H", 9, "HAUTAINES").
dico("H", 9, "HAUTEMENT").
dico("H", 9, "HAUTESSES").
dico("H", 9, "HAUTURIER").
dico("H", 9, "HAVANAISE").
dico("H", 9, "HAVASSENT").
dico("H", 9, "HAVASSIEZ").
dico("H", 9, "HAVENEAUX").
dico("H", 9, "HAVERIONS").
dico("H", 9, "HAVIRIONS").
dico("H", 9, "HAVISSAIS").
dico("H", 9, "HAVISSAIT").
dico("H", 9, "HAVISSANT").
dico("H", 9, "HAVISSENT").
dico("H", 9, "HAVISSIEZ").
dico("H", 9, "HAVISSONS").
dico("H", 9, "HAVRAISES").
dico("H", 9, "HAVRESACS").
dico("H", 9, "HAWAIENNE").
dico("H", 9, "HAWAIIENS").
dico("H", 9, "HEAUMIERE").
dico("H", 9, "HEAUMIERS").
dico("H", 9, "HEBERGEAI").
dico("H", 9, "HEBERGEAS").
dico("H", 9, "HEBERGEAT").
dico("H", 9, "HEBERGEES").
dico("H", 9, "HEBERGENT").
dico("H", 9, "HEBERGERA").
dico("H", 9, "HEBERGEUR").
dico("H", 9, "HEBERGIEZ").
dico("H", 9, "HEBETAMES").
dico("H", 9, "HEBETASSE").
dico("H", 9, "HEBETATES").
dico("H", 9, "HEBETERAI").
dico("H", 9, "HEBETERAS").
dico("H", 9, "HEBETEREZ").
dico("H", 9, "HEBETIONS").
dico("H", 9, "HEBETUDES").
dico("H", 9, "HEBRAIQUE").
dico("H", 9, "HEBRAISAI").
dico("H", 9, "HEBRAISAS").
dico("H", 9, "HEBRAISAT").
dico("H", 9, "HEBRAISEE").
dico("H", 9, "HEBRAISER").
dico("H", 9, "HEBRAISES").
dico("H", 9, "HEBRAISEZ").
dico("H", 9, "HEBRAISME").
dico("H", 9, "HEBRAISTE").
dico("H", 9, "HECATOMBE").
dico("H", 9, "HECTIQUES").
dico("H", 9, "HECTISIES").
dico("H", 9, "HECTOWATT").
dico("H", 9, "HEDERACEE").
dico("H", 9, "HEDONISME").
dico("H", 9, "HEDONISTE").
dico("H", 9, "HEGELIENS").
dico("H", 9, "HEGEMONIE").
dico("H", 9, "HEIDUQUES").
dico("H", 9, "HEIMATLOS").
dico("H", 9, "HELASSENT").
dico("H", 9, "HELASSIEZ").
dico("H", 9, "HELEPOLES").
dico("H", 9, "HELERIONS").
dico("H", 9, "HELIANTHE").
dico("H", 9, "HELIAQUES").
dico("H", 9, "HELIASTES").
dico("H", 9, "HELICIERS").
dico("H", 9, "HELICOIDE").
dico("H", 9, "HELIGARES").
dico("H", 9, "HELIODORE").
dico("H", 9, "HELIOSTAT").
dico("H", 9, "HELIPORTE").
dico("H", 9, "HELIPORTS").
dico("H", 9, "HELLEBORE").
dico("H", 9, "HELLENISA").
dico("H", 9, "HELLENISE").
dico("H", 9, "HELMINTHE").
dico("H", 9, "HELOBIALE").
dico("H", 9, "HELODERME").
dico("H", 9, "HELVELLES").
dico("H", 9, "HELVETIEN").
dico("H", 9, "HEMATINES").
dico("H", 9, "HEMATIQUE").
dico("H", 9, "HEMATITES").
dico("H", 9, "HEMATOBIE").
dico("H", 9, "HEMATOMES").
dico("H", 9, "HEMATOSES").
dico("H", 9, "HEMATURIE").
dico("H", 9, "HEMIALGIE").
dico("H", 9, "HEMICORDE").
dico("H", 9, "HEMICYCLE").
dico("H", 9, "HEMIEDRES").
dico("H", 9, "HEMIEDRIE").
dico("H", 9, "HEMIOXYDE").
dico("H", 9, "HEMIPTERE").
dico("H", 9, "HEMITROPE").
dico("H", 9, "HEMOGENIE").
dico("H", 9, "HEMOLYSES").
dico("H", 9, "HEMOPHILE").
dico("H", 9, "HEMOSTASE").
dico("H", 9, "HENDIADIS").
dico("H", 9, "HENDIADYS").
dico("H", 9, "HENNIRAIS").
dico("H", 9, "HENNIRAIT").
dico("H", 9, "HENNIRENT").
dico("H", 9, "HENNIRIEZ").
dico("H", 9, "HENNIRONS").
dico("H", 9, "HENNIRONT").
dico("H", 9, "HENNISSES").
dico("H", 9, "HENNISSEZ").
dico("H", 9, "HENNUYERE").
dico("H", 9, "HENNUYERS").
dico("H", 9, "HEPARINES").
dico("H", 9, "HEPATIQUE").
dico("H", 9, "HEPATISME").
dico("H", 9, "HEPATITES").
dico("H", 9, "HEPTAEDRE").
dico("H", 9, "HEPTAGONE").
dico("H", 9, "HERBACEES").
dico("H", 9, "HERBAGEAI").
dico("H", 9, "HERBAGEAS").
dico("H", 9, "HERBAGEAT").
dico("H", 9, "HERBAGEES").
dico("H", 9, "HERBAGENT").
dico("H", 9, "HERBAGERA").
dico("H", 9, "HERBAGERE").
dico("H", 9, "HERBAGERS").
dico("H", 9, "HERBAGEUX").
dico("H", 9, "HERBAGIEZ").
dico("H", 9, "HERBAIENT").
dico("H", 9, "HERBASSES").
dico("H", 9, "HERBERAIS").
dico("H", 9, "HERBERAIT").
dico("H", 9, "HERBERENT").
dico("H", 9, "HERBERIES").
dico("H", 9, "HERBERIEZ").
dico("H", 9, "HERBERONS").
dico("H", 9, "HERBERONT").
dico("H", 9, "HERBETTES").
dico("H", 9, "HERBEUSES").
dico("H", 9, "HERBICIDE").
dico("H", 9, "HERBICOLE").
dico("H", 9, "HERBIVORE").
dico("H", 9, "HERBORISA").
dico("H", 9, "HERBORISE").
dico("H", 9, "HERCHAGES").
dico("H", 9, "HERCHAMES").
dico("H", 9, "HERCHASSE").
dico("H", 9, "HERCHATES").
dico("H", 9, "HERCHERAI").
dico("H", 9, "HERCHERAS").
dico("H", 9, "HERCHEREZ").
dico("H", 9, "HERCHEURS").
dico("H", 9, "HERCHEUSE").
dico("H", 9, "HERCHIONS").
dico("H", 9, "HERCULEEN").
dico("H", 9, "HERCYNIEN").
dico("H", 9, "HEREDITES").
dico("H", 9, "HEREFORDS").
dico("H", 9, "HERETIQUE").
dico("H", 9, "HERISSAIS").
dico("H", 9, "HERISSAIT").
dico("H", 9, "HERISSANT").
dico("H", 9, "HERISSEES").
dico("H", 9, "HERISSENT").
dico("H", 9, "HERISSERA").
dico("H", 9, "HERISSIEZ").
dico("H", 9, "HERISSONS").
dico("H", 9, "HERITAGES").
dico("H", 9, "HERITAMES").
dico("H", 9, "HERITASSE").
dico("H", 9, "HERITATES").
dico("H", 9, "HERITERAI").
dico("H", 9, "HERITERAS").
dico("H", 9, "HERITEREZ").
dico("H", 9, "HERITIERE").
dico("H", 9, "HERITIERS").
dico("H", 9, "HERITIONS").
dico("H", 9, "HERMANDAD").
dico("H", 9, "HERMITIEN").
dico("H", 9, "HERNIAIRE").
dico("H", 9, "HERNIEUSE").
dico("H", 9, "HEROICITE").
dico("H", 9, "HEROIQUES").
dico("H", 9, "HEROISMES").
dico("H", 9, "HERONNEAU").
dico("H", 9, "HERONNIER").
dico("H", 9, "HERSAIENT").
dico("H", 9, "HERSASSES").
dico("H", 9, "HERSCHAGE").
dico("H", 9, "HERSCHAIS").
dico("H", 9, "HERSCHAIT").
dico("H", 9, "HERSCHANT").
dico("H", 9, "HERSCHENT").
dico("H", 9, "HERSCHERA").
dico("H", 9, "HERSCHEUR").
dico("H", 9, "HERSCHIEZ").
dico("H", 9, "HERSCHONS").
dico("H", 9, "HERSERAIS").
dico("H", 9, "HERSERAIT").
dico("H", 9, "HERSERENT").
dico("H", 9, "HERSERIEZ").
dico("H", 9, "HERSERONS").
dico("H", 9, "HERSERONT").
dico("H", 9, "HERSEUSES").
dico("H", 9, "HERTZIENS").
dico("H", 9, "HESBIGNON").
dico("H", 9, "HESITAMES").
dico("H", 9, "HESITANTE").
dico("H", 9, "HESITANTS").
dico("H", 9, "HESITASSE").
dico("H", 9, "HESITATES").
dico("H", 9, "HESITERAI").
dico("H", 9, "HESITERAS").
dico("H", 9, "HESITEREZ").
dico("H", 9, "HESITIONS").
dico("H", 9, "HESSOISES").
dico("H", 9, "HETAIRIES").
dico("H", 9, "HETEROSIS").
dico("H", 9, "HETMANATS").
dico("H", 9, "HEUREUSES").
dico("H", 9, "HEURTAMES").
dico("H", 9, "HEURTASSE").
dico("H", 9, "HEURTATES").
dico("H", 9, "HEURTERAI").
dico("H", 9, "HEURTERAS").
dico("H", 9, "HEURTEREZ").
dico("H", 9, "HEURTIONS").
dico("H", 9, "HEURTOIRS").
dico("H", 9, "HEXACORDE").
dico("H", 9, "HEXAEDRES").
dico("H", 9, "HEXAGONAL").
dico("H", 9, "HEXAGONES").
dico("H", 9, "HEXAMETRE").
dico("H", 9, "HEXAPODES").
dico("H", 9, "HEXASTYLE").
dico("H", 9, "HEXOGENES").
dico("H", 9, "HIASSIONS").
dico("H", 9, "HIBERNAIS").
dico("H", 9, "HIBERNAIT").
dico("H", 9, "HIBERNALE").
dico("H", 9, "HIBERNANT").
dico("H", 9, "HIBERNAUX").
dico("H", 9, "HIBERNENT").
dico("H", 9, "HIBERNERA").
dico("H", 9, "HIBERNIEZ").
dico("H", 9, "HIBERNONS").
dico("H", 9, "HIEMATION").
dico("H", 9, "HIERAIENT").
dico("H", 9, "HIERARQUE").
dico("H", 9, "HIERODULE").
dico("H", 9, "HIGOUMENE").
dico("H", 9, "HILARANTE").
dico("H", 9, "HILARANTS").
dico("H", 9, "HILARITES").
dico("H", 9, "HILOTISME").
dico("H", 9, "HIMALAYEN").
dico("H", 9, "HIMATIONS").
dico("H", 9, "HINAYANAS").
dico("H", 9, "HIPPARION").
dico("H", 9, "HIPPARQUE").
dico("H", 9, "HIPPIATRE").
dico("H", 9, "HIPPIQUES").
dico("H", 9, "HIPPISMES").
dico("H", 9, "HIPPOPHAE").
dico("H", 9, "HIRAGANAS").
dico("H", 9, "HIRONDEAU").
dico("H", 9, "HIRUDINEE").
dico("H", 9, "HIRUDINES").
dico("H", 9, "HISPANISA").
dico("H", 9, "HISPANISE").
dico("H", 9, "HISSAIENT").
dico("H", 9, "HISSASSES").
dico("H", 9, "HISSERAIS").
dico("H", 9, "HISSERAIT").
dico("H", 9, "HISSERENT").
dico("H", 9, "HISSERIEZ").
dico("H", 9, "HISSERONS").
dico("H", 9, "HISSERONT").
dico("H", 9, "HISTAMINE").
dico("H", 9, "HISTIDINE").
dico("H", 9, "HISTOIRES").
dico("H", 9, "HISTOLYSE").
dico("H", 9, "HISTORIAI").
dico("H", 9, "HISTORIAS").
dico("H", 9, "HISTORIAT").
dico("H", 9, "HISTORIEE").
dico("H", 9, "HISTORIEN").
dico("H", 9, "HISTORIER").
dico("H", 9, "HISTORIES").
dico("H", 9, "HISTORIEZ").
dico("H", 9, "HISTRIONS").
dico("H", 9, "HITLERIEN").
dico("H", 9, "HIVERNAGE").
dico("H", 9, "HIVERNAIS").
dico("H", 9, "HIVERNAIT").
dico("H", 9, "HIVERNALE").
dico("H", 9, "HIVERNANT").
dico("H", 9, "HIVERNAUX").
dico("H", 9, "HIVERNEES").
dico("H", 9, "HIVERNENT").
dico("H", 9, "HIVERNERA").
dico("H", 9, "HIVERNIEZ").
dico("H", 9, "HIVERNONS").
dico("H", 9, "HOBEREAUX").
dico("H", 9, "HOCHAIENT").
dico("H", 9, "HOCHASSES").
dico("H", 9, "HOCHEMENT").
dico("H", 9, "HOCHEPOTS").
dico("H", 9, "HOCHERAIS").
dico("H", 9, "HOCHERAIT").
dico("H", 9, "HOCHERENT").
dico("H", 9, "HOCHERIEZ").
dico("H", 9, "HOCHERONS").
dico("H", 9, "HOCHERONT").
dico("H", 9, "HOCKEYEUR").
dico("H", 9, "HOLLANDES").
dico("H", 9, "HOLOCENES").
dico("H", 9, "HOLOEDRES").
dico("H", 9, "HOLOEDRIE").
dico("H", 9, "HOLOGAMIE").
dico("H", 9, "HOLOMETRE").
dico("H", 9, "HOLORIMES").
dico("H", 9, "HOLOSIDES").
dico("H", 9, "HOLOSTEEN").
dico("H", 9, "HOLOTYPES").
dico("H", 9, "HOLSTEINS").
dico("H", 9, "HOMARDIER").
dico("H", 9, "HOMELANDS").
dico("H", 9, "HOMEOSTAT").
dico("H", 9, "HOMERIQUE").
dico("H", 9, "HOMESPUNS").
dico("H", 9, "HOMICIDES").
dico("H", 9, "HOMINIDES").
dico("H", 9, "HOMINIENS").
dico("H", 9, "HOMININES").
dico("H", 9, "HOMINISEE").
dico("H", 9, "HOMINISES").
dico("H", 9, "HOMINOIDE").
dico("H", 9, "HOMMASSES").
dico("H", 9, "HOMODONTE").
dico("H", 9, "HOMOFOCAL").
dico("H", 9, "HOMOGAMES").
dico("H", 9, "HOMOGAMIE").
dico("H", 9, "HOMOGENES").
dico("H", 9, "HOMOLOGIE").
dico("H", 9, "HOMOLOGUA").
dico("H", 9, "HOMOLOGUE").
dico("H", 9, "HOMONCULE").
dico("H", 9, "HOMONYMES").
dico("H", 9, "HOMONYMIE").
dico("H", 9, "HOMOPHILE").
dico("H", 9, "HOMOPHOBE").
dico("H", 9, "HOMOPHONE").
dico("H", 9, "HOMOPTERE").
dico("H", 9, "HOMUNCULE").
dico("H", 9, "HONDURIEN").
dico("H", 9, "HONGRAMES").
dico("H", 9, "HONGRASSE").
dico("H", 9, "HONGRATES").
dico("H", 9, "HONGRERAI").
dico("H", 9, "HONGRERAS").
dico("H", 9, "HONGREREZ").
dico("H", 9, "HONGREURS").
dico("H", 9, "HONGRIONS").
dico("H", 9, "HONGROIES").
dico("H", 9, "HONGROISE").
dico("H", 9, "HONGROYAI").
dico("H", 9, "HONGROYAS").
dico("H", 9, "HONGROYAT").
dico("H", 9, "HONGROYEE").
dico("H", 9, "HONGROYER").
dico("H", 9, "HONGROYES").
dico("H", 9, "HONGROYEZ").
dico("H", 9, "HONNETETE").
dico("H", 9, "HONNIRAIS").
dico("H", 9, "HONNIRAIT").
dico("H", 9, "HONNIRENT").
dico("H", 9, "HONNIRIEZ").
dico("H", 9, "HONNIRONS").
dico("H", 9, "HONNIRONT").
dico("H", 9, "HONNISSES").
dico("H", 9, "HONNISSEZ").
dico("H", 9, "HONORABLE").
dico("H", 9, "HONORAIRE").
dico("H", 9, "HONORAMES").
dico("H", 9, "HONORASSE").
dico("H", 9, "HONORATES").
dico("H", 9, "HONORERAI").
dico("H", 9, "HONORERAS").
dico("H", 9, "HONOREREZ").
dico("H", 9, "HONORIONS").
dico("H", 9, "HONTEUSES").
dico("H", 9, "HOOLIGANS").
dico("H", 9, "HOQUETAIS").
dico("H", 9, "HOQUETAIT").
dico("H", 9, "HOQUETANT").
dico("H", 9, "HOQUETIEZ").
dico("H", 9, "HOQUETONS").
dico("H", 9, "HOQUETTES").
dico("H", 9, "HORDEACEE").
dico("H", 9, "HORDEACES").
dico("H", 9, "HORDEINES").
dico("H", 9, "HORLOGERE").
dico("H", 9, "HORLOGERS").
dico("H", 9, "HORMONAIS").
dico("H", 9, "HORMONAIT").
dico("H", 9, "HORMONALE").
dico("H", 9, "HORMONANT").
dico("H", 9, "HORMONAUX").
dico("H", 9, "HORMONEES").
dico("H", 9, "HORMONENT").
dico("H", 9, "HORMONERA").
dico("H", 9, "HORMONIEZ").
dico("H", 9, "HORMONONS").
dico("H", 9, "HORODATEE").
dico("H", 9, "HORODATES").
dico("H", 9, "HOROPTERE").
dico("H", 9, "HOROSCOPE").
dico("H", 9, "HORRIBLES").
dico("H", 9, "HORRIFIAI").
dico("H", 9, "HORRIFIAS").
dico("H", 9, "HORRIFIAT").
dico("H", 9, "HORRIFIEE").
dico("H", 9, "HORRIFIER").
dico("H", 9, "HORRIFIES").
dico("H", 9, "HORRIFIEZ").
dico("H", 9, "HORRIPILA").
dico("H", 9, "HORRIPILE").
dico("H", 9, "HORTENSIA").
dico("H", 9, "HORTICOLE").
dico("H", 9, "HORTILLON").
dico("H", 9, "HOSPODARS").
dico("H", 9, "HOSTILITE").
dico("H", 9, "HOTELIERE").
dico("H", 9, "HOTELIERS").
dico("H", 9, "HOTTAIENT").
dico("H", 9, "HOTTASSES").
dico("H", 9, "HOTTENTOT").
dico("H", 9, "HOTTERAIS").
dico("H", 9, "HOTTERAIT").
dico("H", 9, "HOTTEREAU").
dico("H", 9, "HOTTERENT").
dico("H", 9, "HOTTERETS").
dico("H", 9, "HOTTERIEZ").
dico("H", 9, "HOTTERONS").
dico("H", 9, "HOTTERONT").
dico("H", 9, "HOTTEUSES").
dico("H", 9, "HOUAICHES").
dico("H", 9, "HOUASSENT").
dico("H", 9, "HOUASSIEZ").
dico("H", 9, "HOUBLONNA").
dico("H", 9, "HOUBLONNE").
dico("H", 9, "HOUERIONS").
dico("H", 9, "HOUILLERE").
dico("H", 9, "HOUILLERS").
dico("H", 9, "HOUILLEUX").
dico("H", 9, "HOULETTES").
dico("H", 9, "HOULEUSES").
dico("H", 9, "HOULIGANS").
dico("H", 9, "HOUPPAMES").
dico("H", 9, "HOUPPASSE").
dico("H", 9, "HOUPPATES").
dico("H", 9, "HOUPPERAI").
dico("H", 9, "HOUPPERAS").
dico("H", 9, "HOUPPEREZ").
dico("H", 9, "HOUPPETTE").
dico("H", 9, "HOUPPIERS").
dico("H", 9, "HOUPPIONS").
dico("H", 9, "HOURDAGES").
dico("H", 9, "HOURDAMES").
dico("H", 9, "HOURDASSE").
dico("H", 9, "HOURDATES").
dico("H", 9, "HOURDERAI").
dico("H", 9, "HOURDERAS").
dico("H", 9, "HOURDEREZ").
dico("H", 9, "HOURDIONS").
dico("H", 9, "HOURVARIS").
dico("H", 9, "HOUSPILLA").
dico("H", 9, "HOUSPILLE").
dico("H", 9, "HOUSSAGES").
dico("H", 9, "HOUSSAIES").
dico("H", 9, "HOUSSAMES").
dico("H", 9, "HOUSSASSE").
dico("H", 9, "HOUSSATES").
dico("H", 9, "HOUSSERAI").
dico("H", 9, "HOUSSERAS").
dico("H", 9, "HOUSSEREZ").
dico("H", 9, "HOUSSIERE").
dico("H", 9, "HOUSSINAI").
dico("H", 9, "HOUSSINAS").
dico("H", 9, "HOUSSINAT").
dico("H", 9, "HOUSSINEE").
dico("H", 9, "HOUSSINER").
dico("H", 9, "HOUSSINES").
dico("H", 9, "HOUSSINEZ").
dico("H", 9, "HOUSSIONS").
dico("H", 9, "HOUSSOIRS").
dico("H", 9, "HOVERPORT").
dico("H", 9, "HUASSIONS").
dico("H", 9, "HUCHAIENT").
dico("H", 9, "HUCHASSES").
dico("H", 9, "HUCHERAIS").
dico("H", 9, "HUCHERAIT").
dico("H", 9, "HUCHERENT").
dico("H", 9, "HUCHERIEZ").
dico("H", 9, "HUCHERONS").
dico("H", 9, "HUCHERONT").
dico("H", 9, "HUERAIENT").
dico("H", 9, "HUGOLIENS").
dico("H", 9, "HUGUENOTE").
dico("H", 9, "HUGUENOTS").
dico("H", 9, "HUILAIENT").
dico("H", 9, "HUILASSES").
dico("H", 9, "HUILERAIS").
dico("H", 9, "HUILERAIT").
dico("H", 9, "HUILERENT").
dico("H", 9, "HUILERIES").
dico("H", 9, "HUILERIEZ").
dico("H", 9, "HUILERONS").
dico("H", 9, "HUILERONT").
dico("H", 9, "HUILEUSES").
dico("H", 9, "HUILIERES").
dico("H", 9, "HUISSERIE").
dico("H", 9, "HUISSIERE").
dico("H", 9, "HUISSIERS").
dico("H", 9, "HUITAINES").
dico("H", 9, "HUITIEMES").
dico("H", 9, "HUITRIERE").
dico("H", 9, "HUITRIERS").
dico("H", 9, "HULLOISES").
dico("H", 9, "HULULAMES").
dico("H", 9, "HULULASSE").
dico("H", 9, "HULULATES").
dico("H", 9, "HULULERAI").
dico("H", 9, "HULULERAS").
dico("H", 9, "HULULEREZ").
dico("H", 9, "HULULIONS").
dico("H", 9, "HUMANISAI").
dico("H", 9, "HUMANISAS").
dico("H", 9, "HUMANISAT").
dico("H", 9, "HUMANISEE").
dico("H", 9, "HUMANISER").
dico("H", 9, "HUMANISES").
dico("H", 9, "HUMANISEZ").
dico("H", 9, "HUMANISME").
dico("H", 9, "HUMANISTE").
dico("H", 9, "HUMANITES").
dico("H", 9, "HUMANOIDE").
dico("H", 9, "HUMASSENT").
dico("H", 9, "HUMASSIEZ").
dico("H", 9, "HUMECTAGE").
dico("H", 9, "HUMECTAIS").
dico("H", 9, "HUMECTAIT").
dico("H", 9, "HUMECTANT").
dico("H", 9, "HUMECTEES").
dico("H", 9, "HUMECTENT").
dico("H", 9, "HUMECTERA").
dico("H", 9, "HUMECTEUR").
dico("H", 9, "HUMECTIEZ").
dico("H", 9, "HUMECTONS").
dico("H", 9, "HUMERALES").
dico("H", 9, "HUMERIONS").
dico("H", 9, "HUMICOLES").
dico("H", 9, "HUMIDIFIA").
dico("H", 9, "HUMIDIFIE").
dico("H", 9, "HUMIDITES").
dico("H", 9, "HUMILIAIS").
dico("H", 9, "HUMILIAIT").
dico("H", 9, "HUMILIANT").
dico("H", 9, "HUMILIEES").
dico("H", 9, "HUMILIENT").
dico("H", 9, "HUMILIERA").
dico("H", 9, "HUMILIIEZ").
dico("H", 9, "HUMILIONS").
dico("H", 9, "HUMILITES").
dico("H", 9, "HUMORALES").
dico("H", 9, "HUMORISME").
dico("H", 9, "HUMORISTE").
dico("H", 9, "HUNNIQUES").
dico("H", 9, "HURLAIENT").
dico("H", 9, "HURLANTES").
dico("H", 9, "HURLASSES").
dico("H", 9, "HURLEMENT").
dico("H", 9, "HURLERAIS").
dico("H", 9, "HURLERAIT").
dico("H", 9, "HURLERENT").
dico("H", 9, "HURLERIEZ").
dico("H", 9, "HURLERONS").
dico("H", 9, "HURLERONT").
dico("H", 9, "HURLEUSES").
dico("H", 9, "HURONIENS").
dico("H", 9, "HURRICANE").
dico("H", 9, "HUSSARDES").
dico("H", 9, "HYACINTHE").
dico("H", 9, "HYALOIDES").
dico("H", 9, "HYBRIDAIS").
dico("H", 9, "HYBRIDAIT").
dico("H", 9, "HYBRIDANT").
dico("H", 9, "HYBRIDEES").
dico("H", 9, "HYBRIDENT").
dico("H", 9, "HYBRIDERA").
dico("H", 9, "HYBRIDIEZ").
dico("H", 9, "HYBRIDITE").
dico("H", 9, "HYBRIDOME").
dico("H", 9, "HYBRIDONS").
dico("H", 9, "HYDATIDES").
dico("H", 9, "HYDATIQUE").
dico("H", 9, "HYDRACIDE").
dico("H", 9, "HYDRAIRES").
dico("H", 9, "HYDRANGEE").
dico("H", 9, "HYDRANTES").
dico("H", 9, "HYDRANTHE").
dico("H", 9, "HYDRARGIE").
dico("H", 9, "HYDRASTIS").
dico("H", 9, "HYDRATAIS").
dico("H", 9, "HYDRATAIT").
dico("H", 9, "HYDRATANT").
dico("H", 9, "HYDRATEES").
dico("H", 9, "HYDRATENT").
dico("H", 9, "HYDRATERA").
dico("H", 9, "HYDRATIEZ").
dico("H", 9, "HYDRATONS").
dico("H", 9, "HYDRAULES").
dico("H", 9, "HYDRAVION").
dico("H", 9, "HYDRAZINE").
dico("H", 9, "HYDREMIES").
dico("H", 9, "HYDRIQUES").
dico("H", 9, "HYDROBASE").
dico("H", 9, "HYDROCELE").
dico("H", 9, "HYDROCUTA").
dico("H", 9, "HYDROCUTE").
dico("H", 9, "HYDROFOIL").
dico("H", 9, "HYDROFUGE").
dico("H", 9, "HYDROGELS").
dico("H", 9, "HYDROGENA").
dico("H", 9, "HYDROGENE").
dico("H", 9, "HYDROLASE").
dico("H", 9, "HYDROLATS").
dico("H", 9, "HYDROLYSA").
dico("H", 9, "HYDROLYSE").
dico("H", 9, "HYDROMELS").
dico("H", 9, "HYDROSOLS").
dico("H", 9, "HYDROXYDE").
dico("H", 9, "HYDROXYLE").
dico("H", 9, "HYGROSTAT").
dico("H", 9, "HYLETIQUE").
dico("H", 9, "HYMENIUMS").
dico("H", 9, "HYMNIQUES").
dico("H", 9, "HYOIDIENS").
dico("H", 9, "HYPALLAGE").
dico("H", 9, "HYPERBARE").
dico("H", 9, "HYPERBATE").
dico("H", 9, "HYPERBOLE").
dico("H", 9, "HYPEREMIE").
dico("H", 9, "HYPERFINE").
dico("H", 9, "HYPERFINS").
dico("H", 9, "HYPERGOLS").
dico("H", 9, "HYPERLIEN").
dico("H", 9, "HYPERPLAN").
dico("H", 9, "HYPETHRES").
dico("H", 9, "HYPHOLOME").
dico("H", 9, "HYPNOIDES").
dico("H", 9, "HYPNOTISA").
dico("H", 9, "HYPNOTISE").
dico("H", 9, "HYPOCAGNE").
dico("H", 9, "HYPOCRITE").
dico("H", 9, "HYPODERME").
dico("H", 9, "HYPOGYNES").
dico("H", 9, "HYPOMANES").
dico("H", 9, "HYPOMANIE").
dico("H", 9, "HYPONYMES").
dico("H", 9, "HYPOPHYSE").
dico("H", 9, "HYPOSODEE").
dico("H", 9, "HYPOSODES").
dico("H", 9, "HYPOSTASE").
dico("H", 9, "HYPOSTYLE").
dico("H", 9, "HYPOTAUPE").
dico("H", 9, "HYPOTENDU").
dico("H", 9, "HYPOTHESE").
dico("H", 9, "HYPOTONIE").
dico("H", 9, "HYPOXEMIE").
dico("H", 9, "HYSTERESE").
dico("H", 9, "HYSTERIES").
