dico("I", 5, "IAMBE").
dico("I", 5, "IBERE").
dico("I", 5, "ICEUX").
dico("I", 5, "ICHOR").
dico("I", 5, "ICONE").
dico("I", 5, "ICTUS").
dico("I", 5, "IDEAL").
dico("I", 5, "IDEEL").
dico("I", 5, "IDEES").
dico("I", 5, "IDIOT").
dico("I", 5, "IDOLE").
dico("I", 5, "IGAME").
dico("I", 5, "IGLOO").
dico("I", 5, "IGLOU").
dico("I", 5, "IGNEE").
dico("I", 5, "IGNES").
dico("I", 5, "IGUES").
dico("I", 5, "IKATS").
dico("I", 5, "ILEAL").
dico("I", 5, "ILEON").
dico("I", 5, "ILETS").
dico("I", 5, "ILEUS").
dico("I", 5, "ILIEN").
dico("I", 5, "ILION").
dico("I", 5, "ILOTE").
dico("I", 5, "ILOTS").
dico("I", 5, "IMAGE").
dico("I", 5, "IMAGO").
dico("I", 5, "IMAMS").
dico("I", 5, "IMANS").
dico("I", 5, "IMBUE").
dico("I", 5, "IMBUS").
dico("I", 5, "IMIDE").
dico("I", 5, "IMINE").
dico("I", 5, "IMITA").
dico("I", 5, "IMITE").
dico("I", 5, "IMMUN").
dico("I", 5, "IMPEC").
dico("I", 5, "IMPER").
dico("I", 5, "IMPIE").
dico("I", 5, "IMPOT").
dico("I", 5, "IMPRO").
dico("I", 5, "IMPUR").
dico("I", 5, "INCAS").
dico("I", 5, "INCHS").
dico("I", 5, "INCUS").
dico("I", 5, "INDES").
dico("I", 5, "INDEX").
dico("I", 5, "INDIC").
dico("I", 5, "INDOU").
dico("I", 5, "INDRI").
dico("I", 5, "INDUE").
dico("I", 5, "INDUS").
dico("I", 5, "INFOS").
dico("I", 5, "INFRA").
dico("I", 5, "INFUS").
dico("I", 5, "INLAY").
dico("I", 5, "INNEE").
dico("I", 5, "INNES").
dico("I", 5, "INOUI").
dico("I", 5, "INPUT").
dico("I", 5, "INSTI").
dico("I", 5, "INTER").
dico("I", 5, "INTIS").
dico("I", 5, "INTOX").
dico("I", 5, "INTRO").
dico("I", 5, "INUIT").
dico("I", 5, "INUKS").
dico("I", 5, "INULE").
dico("I", 5, "INVAR").
dico("I", 5, "IODAI").
dico("I", 5, "IODAS").
dico("I", 5, "IODAT").
dico("I", 5, "IODEE").
dico("I", 5, "IODER").
dico("I", 5, "IODES").
dico("I", 5, "IODEZ").
dico("I", 5, "IODLA").
dico("I", 5, "IODLE").
dico("I", 5, "IOULA").
dico("I", 5, "IOULE").
dico("I", 5, "IPECA").
dico("I", 5, "IPPON").
dico("I", 5, "IRAIS").
dico("I", 5, "IRAIT").
dico("I", 5, "IRIEN").
dico("I", 5, "IRIEZ").
dico("I", 5, "IRISA").
dico("I", 5, "IRISE").
dico("I", 5, "IROKO").
dico("I", 5, "IRONE").
dico("I", 5, "IRONS").
dico("I", 5, "IRONT").
dico("I", 5, "ISARD").
dico("I", 5, "ISBAS").
dico("I", 5, "ISLAM").
dico("I", 5, "ISOLA").
dico("I", 5, "ISOLE").
dico("I", 5, "ISSUE").
dico("I", 5, "ISSUS").
dico("I", 5, "ITEMS").
dico("I", 5, "ITERA").
dico("I", 5, "ITERE").
dico("I", 5, "ITHOS").
dico("I", 5, "IULES").
dico("I", 5, "IVRES").
dico("I", 5, "IWANS").
dico("I", 5, "IXAGE").
dico("I", 5, "IXAIS").
dico("I", 5, "IXAIT").
dico("I", 5, "IXANT").
dico("I", 5, "IXEES").
dico("I", 5, "IXENT").
dico("I", 5, "IXERA").
dico("I", 5, "IXIAS").
dico("I", 5, "IXIEZ").
dico("I", 5, "IXODE").
dico("I", 5, "IXONS").
