dico("I", 8, "IAKOUTES").
dico("I", 8, "IAMBIQUE").
dico("I", 8, "IBERIDES").
dico("I", 8, "IBERIENS").
dico("I", 8, "IBERIQUE").
dico("I", 8, "ICAQUIER").
dico("I", 8, "ICARIENS").
dico("I", 8, "ICAUNAIS").
dico("I", 8, "ICEBERGS").
dico("I", 8, "ICEFIELD").
dico("I", 8, "ICHOREUX").
dico("I", 8, "ICHTYOLS").
dico("I", 8, "ICHTYOSE").
dico("I", 8, "ICOGLANS").
dico("I", 8, "ICONIQUE").
dico("I", 8, "IDEALISA").
dico("I", 8, "IDEALISE").
dico("I", 8, "IDEALITE").
dico("I", 8, "IDEATION").
dico("I", 8, "IDEELLES").
dico("I", 8, "IDENTITE").
dico("I", 8, "IDIOTIES").
dico("I", 8, "IDOLATRA").
dico("I", 8, "IDOLATRE").
dico("I", 8, "IGNICOLE").
dico("I", 8, "IGNIFERE").
dico("I", 8, "IGNIFUGE").
dico("I", 8, "IGNITION").
dico("I", 8, "IGNITRON").
dico("I", 8, "IGNIVOME").
dico("I", 8, "IGNIVORE").
dico("I", 8, "IGNOBLES").
dico("I", 8, "IGNORAIS").
dico("I", 8, "IGNORAIT").
dico("I", 8, "IGNORANT").
dico("I", 8, "IGNOREES").
dico("I", 8, "IGNORENT").
dico("I", 8, "IGNORERA").
dico("I", 8, "IGNORIEZ").
dico("I", 8, "IGNORONS").
dico("I", 8, "IGUANIDE").
dico("I", 8, "IJOLITES").
dico("I", 8, "IKEBANAS").
dico("I", 8, "ILIAQUES").
dico("I", 8, "ILIENNES").
dico("I", 8, "ILLEGALE").
dico("I", 8, "ILLEGAUX").
dico("I", 8, "ILLETTRE").
dico("I", 8, "ILLICITE").
dico("I", 8, "ILLIMITE").
dico("I", 8, "ILLUMINA").
dico("I", 8, "ILLUMINE").
dico("I", 8, "ILLUSION").
dico("I", 8, "ILLUSTRA").
dico("I", 8, "ILLUSTRE").
dico("I", 8, "ILLUTAIS").
dico("I", 8, "ILLUTAIT").
dico("I", 8, "ILLUTANT").
dico("I", 8, "ILLUTEES").
dico("I", 8, "ILLUTENT").
dico("I", 8, "ILLUTERA").
dico("I", 8, "ILLUTIEZ").
dico("I", 8, "ILLUTONS").
dico("I", 8, "ILLUVIAL").
dico("I", 8, "ILLUVION").
dico("I", 8, "ILLUVIUM").
dico("I", 8, "ILLYRIEN").
dico("I", 8, "ILMENITE").
dico("I", 8, "ILOTAGES").
dico("I", 8, "ILOTIERE").
dico("I", 8, "ILOTIERS").
dico("I", 8, "ILOTISME").
dico("I", 8, "IMAGEAIS").
dico("I", 8, "IMAGEAIT").
dico("I", 8, "IMAGEANT").
dico("I", 8, "IMAGEONS").
dico("I", 8, "IMAGERAI").
dico("I", 8, "IMAGERAS").
dico("I", 8, "IMAGEREZ").
dico("I", 8, "IMAGERIE").
dico("I", 8, "IMAGEURS").
dico("I", 8, "IMAGEUSE").
dico("I", 8, "IMAGIERE").
dico("I", 8, "IMAGIERS").
dico("I", 8, "IMAGINAI").
dico("I", 8, "IMAGINAL").
dico("I", 8, "IMAGINAS").
dico("I", 8, "IMAGINAT").
dico("I", 8, "IMAGINEE").
dico("I", 8, "IMAGINER").
dico("I", 8, "IMAGINES").
dico("I", 8, "IMAGINEZ").
dico("I", 8, "IMAGIONS").
dico("I", 8, "IMBECILE").
dico("I", 8, "IMBERBES").
dico("I", 8, "IMBIBAIS").
dico("I", 8, "IMBIBAIT").
dico("I", 8, "IMBIBANT").
dico("I", 8, "IMBIBEES").
dico("I", 8, "IMBIBENT").
dico("I", 8, "IMBIBERA").
dico("I", 8, "IMBIBIEZ").
dico("I", 8, "IMBIBONS").
dico("I", 8, "IMBRIQUA").
dico("I", 8, "IMBRIQUE").
dico("I", 8, "IMBRULEE").
dico("I", 8, "IMBRULES").
dico("I", 8, "IMITABLE").
dico("I", 8, "IMITAMES").
dico("I", 8, "IMITASSE").
dico("I", 8, "IMITATES").
dico("I", 8, "IMITATIF").
dico("I", 8, "IMITERAI").
dico("I", 8, "IMITERAS").
dico("I", 8, "IMITEREZ").
dico("I", 8, "IMITIONS").
dico("I", 8, "IMMACULE").
dico("I", 8, "IMMANENT").
dico("I", 8, "IMMATURE").
dico("I", 8, "IMMEDIAT").
dico("I", 8, "IMMENSES").
dico("I", 8, "IMMERGEA").
dico("I", 8, "IMMERGEE").
dico("I", 8, "IMMERGER").
dico("I", 8, "IMMERGES").
dico("I", 8, "IMMERGEZ").
dico("I", 8, "IMMERITE").
dico("I", 8, "IMMERSIF").
dico("I", 8, "IMMEUBLE").
dico("I", 8, "IMMIGRAI").
dico("I", 8, "IMMIGRAS").
dico("I", 8, "IMMIGRAT").
dico("I", 8, "IMMIGREE").
dico("I", 8, "IMMIGRER").
dico("I", 8, "IMMIGRES").
dico("I", 8, "IMMIGREZ").
dico("I", 8, "IMMINENT").
dico("I", 8, "IMMISCAI").
dico("I", 8, "IMMISCAS").
dico("I", 8, "IMMISCAT").
dico("I", 8, "IMMISCEE").
dico("I", 8, "IMMISCER").
dico("I", 8, "IMMISCES").
dico("I", 8, "IMMISCEZ").
dico("I", 8, "IMMOBILE").
dico("I", 8, "IMMODERE").
dico("I", 8, "IMMOLAIS").
dico("I", 8, "IMMOLAIT").
dico("I", 8, "IMMOLANT").
dico("I", 8, "IMMOLEES").
dico("I", 8, "IMMOLENT").
dico("I", 8, "IMMOLERA").
dico("I", 8, "IMMOLIEZ").
dico("I", 8, "IMMOLONS").
dico("I", 8, "IMMONDES").
dico("I", 8, "IMMORALE").
dico("I", 8, "IMMORAUX").
dico("I", 8, "IMMORTEL").
dico("I", 8, "IMMOTIVE").
dico("I", 8, "IMMUABLE").
dico("I", 8, "IMMUNISA").
dico("I", 8, "IMMUNISE").
dico("I", 8, "IMMUNITE").
dico("I", 8, "IMPACTAI").
dico("I", 8, "IMPACTAS").
dico("I", 8, "IMPACTAT").
dico("I", 8, "IMPACTEE").
dico("I", 8, "IMPACTER").
dico("I", 8, "IMPACTES").
dico("I", 8, "IMPACTEZ").
dico("I", 8, "IMPAIRES").
dico("I", 8, "IMPALUDE").
dico("I", 8, "IMPARITE").
dico("I", 8, "IMPARTIE").
dico("I", 8, "IMPARTIR").
dico("I", 8, "IMPARTIS").
dico("I", 8, "IMPARTIT").
dico("I", 8, "IMPASSES").
dico("I", 8, "IMPAVIDE").
dico("I", 8, "IMPAYEES").
dico("I", 8, "IMPENSES").
dico("I", 8, "IMPERIAL").
dico("I", 8, "IMPERIUM").
dico("I", 8, "IMPETIGO").
dico("I", 8, "IMPETRAI").
dico("I", 8, "IMPETRAS").
dico("I", 8, "IMPETRAT").
dico("I", 8, "IMPETREE").
dico("I", 8, "IMPETRER").
dico("I", 8, "IMPETRES").
dico("I", 8, "IMPETREZ").
dico("I", 8, "IMPIETES").
dico("I", 8, "IMPLANTA").
dico("I", 8, "IMPLANTE").
dico("I", 8, "IMPLANTS").
dico("I", 8, "IMPLEXES").
dico("I", 8, "IMPLIQUA").
dico("I", 8, "IMPLIQUE").
dico("I", 8, "IMPLORAI").
dico("I", 8, "IMPLORAS").
dico("I", 8, "IMPLORAT").
dico("I", 8, "IMPLOREE").
dico("I", 8, "IMPLORER").
dico("I", 8, "IMPLORES").
dico("I", 8, "IMPLOREZ").
dico("I", 8, "IMPLOSAI").
dico("I", 8, "IMPLOSAS").
dico("I", 8, "IMPLOSAT").
dico("I", 8, "IMPLOSER").
dico("I", 8, "IMPLOSES").
dico("I", 8, "IMPLOSEZ").
dico("I", 8, "IMPLOSIF").
dico("I", 8, "IMPOLIES").
dico("I", 8, "IMPORTAI").
dico("I", 8, "IMPORTAS").
dico("I", 8, "IMPORTAT").
dico("I", 8, "IMPORTEE").
dico("I", 8, "IMPORTER").
dico("I", 8, "IMPORTES").
dico("I", 8, "IMPORTEZ").
dico("I", 8, "IMPORTUN").
dico("I", 8, "IMPOSAIS").
dico("I", 8, "IMPOSAIT").
dico("I", 8, "IMPOSANT").
dico("I", 8, "IMPOSEES").
dico("I", 8, "IMPOSENT").
dico("I", 8, "IMPOSERA").
dico("I", 8, "IMPOSEUR").
dico("I", 8, "IMPOSIEZ").
dico("I", 8, "IMPOSONS").
dico("I", 8, "IMPOSTES").
dico("I", 8, "IMPOTENT").
dico("I", 8, "IMPRECIS").
dico("I", 8, "IMPREGNA").
dico("I", 8, "IMPREGNE").
dico("I", 8, "IMPREVUE").
dico("I", 8, "IMPREVUS").
dico("I", 8, "IMPRIMAI").
dico("I", 8, "IMPRIMAS").
dico("I", 8, "IMPRIMAT").
dico("I", 8, "IMPRIMEE").
dico("I", 8, "IMPRIMER").
dico("I", 8, "IMPRIMES").
dico("I", 8, "IMPRIMEZ").
dico("I", 8, "IMPROPRE").
dico("I", 8, "IMPROUVA").
dico("I", 8, "IMPROUVE").
dico("I", 8, "IMPUBERE").
dico("I", 8, "IMPUDENT").
dico("I", 8, "IMPUDEUR").
dico("I", 8, "IMPULSAI").
dico("I", 8, "IMPULSAS").
dico("I", 8, "IMPULSAT").
dico("I", 8, "IMPULSEE").
dico("I", 8, "IMPULSER").
dico("I", 8, "IMPULSES").
dico("I", 8, "IMPULSEZ").
dico("I", 8, "IMPULSIF").
dico("I", 8, "IMPUNIES").
dico("I", 8, "IMPUNITE").
dico("I", 8, "IMPURETE").
dico("I", 8, "IMPUTAIS").
dico("I", 8, "IMPUTAIT").
dico("I", 8, "IMPUTANT").
dico("I", 8, "IMPUTEES").
dico("I", 8, "IMPUTENT").
dico("I", 8, "IMPUTERA").
dico("I", 8, "IMPUTIEZ").
dico("I", 8, "IMPUTONS").
dico("I", 8, "INABOUTI").
dico("I", 8, "INABRITE").
dico("I", 8, "INACHEVE").
dico("I", 8, "INACTIFS").
dico("I", 8, "INACTION").
dico("I", 8, "INACTIVA").
dico("I", 8, "INACTIVE").
dico("I", 8, "INACTUEL").
dico("I", 8, "INADAPTE").
dico("I", 8, "INALIENE").
dico("I", 8, "INALPAGE").
dico("I", 8, "INALPAIS").
dico("I", 8, "INALPAIT").
dico("I", 8, "INALPANT").
dico("I", 8, "INALPEES").
dico("I", 8, "INALPENT").
dico("I", 8, "INALPERA").
dico("I", 8, "INALPIEZ").
dico("I", 8, "INALPONS").
dico("I", 8, "INALTERE").
dico("I", 8, "INAMICAL").
dico("I", 8, "INANIMEE").
dico("I", 8, "INANIMES").
dico("I", 8, "INANITES").
dico("I", 8, "INAPAISE").
dico("I", 8, "INAPERCU").
dico("I", 8, "INAUGURA").
dico("I", 8, "INAUGURE").
dico("I", 8, "INAVOUEE").
dico("I", 8, "INAVOUES").
dico("I", 8, "INCARNAI").
dico("I", 8, "INCARNAS").
dico("I", 8, "INCARNAT").
dico("I", 8, "INCARNEE").
dico("I", 8, "INCARNER").
dico("I", 8, "INCARNES").
dico("I", 8, "INCARNEZ").
dico("I", 8, "INCENDIA").
dico("I", 8, "INCENDIE").
dico("I", 8, "INCESTES").
dico("I", 8, "INCHANGE").
dico("I", 8, "INCIDENT").
dico("I", 8, "INCINERA").
dico("I", 8, "INCINERE").
dico("I", 8, "INCISAIS").
dico("I", 8, "INCISAIT").
dico("I", 8, "INCISANT").
dico("I", 8, "INCISEES").
dico("I", 8, "INCISENT").
dico("I", 8, "INCISERA").
dico("I", 8, "INCISIEZ").
dico("I", 8, "INCISIFS").
dico("I", 8, "INCISION").
dico("I", 8, "INCISIVE").
dico("I", 8, "INCISONS").
dico("I", 8, "INCISURE").
dico("I", 8, "INCITAIS").
dico("I", 8, "INCITAIT").
dico("I", 8, "INCITANT").
dico("I", 8, "INCITEES").
dico("I", 8, "INCITENT").
dico("I", 8, "INCITERA").
dico("I", 8, "INCITIEZ").
dico("I", 8, "INCITONS").
dico("I", 8, "INCIVILE").
dico("I", 8, "INCIVILS").
dico("I", 8, "INCLINAI").
dico("I", 8, "INCLINAS").
dico("I", 8, "INCLINAT").
dico("I", 8, "INCLINEE").
dico("I", 8, "INCLINER").
dico("I", 8, "INCLINES").
dico("I", 8, "INCLINEZ").
dico("I", 8, "INCLUAIS").
dico("I", 8, "INCLUAIT").
dico("I", 8, "INCLUANT").
dico("I", 8, "INCLUENT").
dico("I", 8, "INCLUIEZ").
dico("I", 8, "INCLUMES").
dico("I", 8, "INCLUONS").
dico("I", 8, "INCLURAI").
dico("I", 8, "INCLURAS").
dico("I", 8, "INCLUREZ").
dico("I", 8, "INCLUSES").
dico("I", 8, "INCLUSIF").
dico("I", 8, "INCLUSSE").
dico("I", 8, "INCLUTES").
dico("I", 8, "INCOLORE").
dico("I", 8, "INCOMBAT").
dico("I", 8, "INCOMBER").
dico("I", 8, "INCONELS").
dico("I", 8, "INCONGRU").
dico("I", 8, "INCONNUE").
dico("I", 8, "INCONNUS").
dico("I", 8, "INCOTERM").
dico("I", 8, "INCREEES").
dico("I", 8, "INCRUSTA").
dico("I", 8, "INCRUSTE").
dico("I", 8, "INCUBAIS").
dico("I", 8, "INCUBAIT").
dico("I", 8, "INCUBANT").
dico("I", 8, "INCUBEES").
dico("I", 8, "INCUBENT").
dico("I", 8, "INCUBERA").
dico("I", 8, "INCUBIEZ").
dico("I", 8, "INCUBONS").
dico("I", 8, "INCUITES").
dico("I", 8, "INCULPAI").
dico("I", 8, "INCULPAS").
dico("I", 8, "INCULPAT").
dico("I", 8, "INCULPEE").
dico("I", 8, "INCULPER").
dico("I", 8, "INCULPES").
dico("I", 8, "INCULPEZ").
dico("I", 8, "INCULQUA").
dico("I", 8, "INCULQUE").
dico("I", 8, "INCULTES").
dico("I", 8, "INCURIES").
dico("I", 8, "INCURVAI").
dico("I", 8, "INCURVAS").
dico("I", 8, "INCURVAT").
dico("I", 8, "INCURVEE").
dico("I", 8, "INCURVER").
dico("I", 8, "INCURVES").
dico("I", 8, "INCURVEZ").
dico("I", 8, "INDAGUAI").
dico("I", 8, "INDAGUAS").
dico("I", 8, "INDAGUAT").
dico("I", 8, "INDAGUER").
dico("I", 8, "INDAGUES").
dico("I", 8, "INDAGUEZ").
dico("I", 8, "INDECENT").
dico("I", 8, "INDECISE").
dico("I", 8, "INDEFINI").
dico("I", 8, "INDEMNES").
dico("I", 8, "INDENTAI").
dico("I", 8, "INDENTAS").
dico("I", 8, "INDENTAT").
dico("I", 8, "INDENTEE").
dico("I", 8, "INDENTER").
dico("I", 8, "INDENTES").
dico("I", 8, "INDENTEZ").
dico("I", 8, "INDEXAGE").
dico("I", 8, "INDEXAIS").
dico("I", 8, "INDEXAIT").
dico("I", 8, "INDEXANT").
dico("I", 8, "INDEXEES").
dico("I", 8, "INDEXENT").
dico("I", 8, "INDEXERA").
dico("I", 8, "INDEXEUR").
dico("I", 8, "INDEXIEZ").
dico("I", 8, "INDEXONS").
dico("I", 8, "INDICAIS").
dico("I", 8, "INDICAIT").
dico("I", 8, "INDICANS").
dico("I", 8, "INDICANT").
dico("I", 8, "INDICEES").
dico("I", 8, "INDICENT").
dico("I", 8, "INDICERA").
dico("I", 8, "INDICIEL").
dico("I", 8, "INDICIEZ").
dico("I", 8, "INDICONS").
dico("I", 8, "INDIENNE").
dico("I", 8, "INDIGENE").
dico("I", 8, "INDIGENT").
dico("I", 8, "INDIGETE").
dico("I", 8, "INDIGNAI").
dico("I", 8, "INDIGNAS").
dico("I", 8, "INDIGNAT").
dico("I", 8, "INDIGNEE").
dico("I", 8, "INDIGNER").
dico("I", 8, "INDIGNES").
dico("I", 8, "INDIGNEZ").
dico("I", 8, "INDIQUAI").
dico("I", 8, "INDIQUAS").
dico("I", 8, "INDIQUAT").
dico("I", 8, "INDIQUEE").
dico("I", 8, "INDIQUER").
dico("I", 8, "INDIQUES").
dico("I", 8, "INDIQUEZ").
dico("I", 8, "INDIRECT").
dico("I", 8, "INDIVIDU").
dico("I", 8, "INDIVISE").
dico("I", 8, "INDOCILE").
dico("I", 8, "INDOLENT").
dico("I", 8, "INDOLORE").
dico("I", 8, "INDOMPTE").
dico("I", 8, "INDRIENS").
dico("I", 8, "INDUCTIF").
dico("I", 8, "INDUIRAI").
dico("I", 8, "INDUIRAS").
dico("I", 8, "INDUIREZ").
dico("I", 8, "INDUISES").
dico("I", 8, "INDUISEZ").
dico("I", 8, "INDUISIS").
dico("I", 8, "INDUISIT").
dico("I", 8, "INDUITES").
dico("I", 8, "INDULINE").
dico("I", 8, "INDUMENT").
dico("I", 8, "INDURAIS").
dico("I", 8, "INDURAIT").
dico("I", 8, "INDURANT").
dico("I", 8, "INDUREES").
dico("I", 8, "INDURENT").
dico("I", 8, "INDURERA").
dico("I", 8, "INDURIEZ").
dico("I", 8, "INDURONS").
dico("I", 8, "INDUSIES").
dico("I", 8, "INDUVIEE").
dico("I", 8, "INDUVIES").
dico("I", 8, "INECOUTE").
dico("I", 8, "INEDITES").
dico("I", 8, "INEGALEE").
dico("I", 8, "INEGALES").
dico("I", 8, "INEMPLOI").
dico("I", 8, "INENTAME").
dico("I", 8, "INEPTIES").
dico("I", 8, "INEPUISE").
dico("I", 8, "INERTAGE").
dico("I", 8, "INERTAIS").
dico("I", 8, "INERTAIT").
dico("I", 8, "INERTANT").
dico("I", 8, "INERTEES").
dico("I", 8, "INERTENT").
dico("I", 8, "INERTERA").
dico("I", 8, "INERTIEL").
dico("I", 8, "INERTIES").
dico("I", 8, "INERTIEZ").
dico("I", 8, "INERTONS").
dico("I", 8, "INESPERE").
dico("I", 8, "INETENDU").
dico("I", 8, "INEXACTE").
dico("I", 8, "INEXACTS").
dico("I", 8, "INEXAUCE").
dico("I", 8, "INEXERCE").
dico("I", 8, "INEXPERT").
dico("I", 8, "INEXPIEE").
dico("I", 8, "INEXPIES").
dico("I", 8, "INFAMANT").
dico("I", 8, "INFAMIES").
dico("I", 8, "INFANTES").
dico("I", 8, "INFARCIE").
dico("I", 8, "INFARCIR").
dico("I", 8, "INFARCIS").
dico("I", 8, "INFARCIT").
dico("I", 8, "INFATUAI").
dico("I", 8, "INFATUAS").
dico("I", 8, "INFATUAT").
dico("I", 8, "INFATUEE").
dico("I", 8, "INFATUER").
dico("I", 8, "INFATUES").
dico("I", 8, "INFATUEZ").
dico("I", 8, "INFECOND").
dico("I", 8, "INFECTAI").
dico("I", 8, "INFECTAS").
dico("I", 8, "INFECTAT").
dico("I", 8, "INFECTEE").
dico("I", 8, "INFECTER").
dico("I", 8, "INFECTES").
dico("I", 8, "INFECTEZ").
dico("I", 8, "INFEODAI").
dico("I", 8, "INFEODAS").
dico("I", 8, "INFEODAT").
dico("I", 8, "INFEODEE").
dico("I", 8, "INFEODER").
dico("I", 8, "INFEODES").
dico("I", 8, "INFEODEZ").
dico("I", 8, "INFERAIS").
dico("I", 8, "INFERAIT").
dico("I", 8, "INFERANT").
dico("I", 8, "INFEREES").
dico("I", 8, "INFERENT").
dico("I", 8, "INFERERA").
dico("I", 8, "INFERIEZ").
dico("I", 8, "INFERNAL").
dico("I", 8, "INFERONS").
dico("I", 8, "INFESTAI").
dico("I", 8, "INFESTAS").
dico("I", 8, "INFESTAT").
dico("I", 8, "INFESTEE").
dico("I", 8, "INFESTER").
dico("I", 8, "INFESTES").
dico("I", 8, "INFESTEZ").
dico("I", 8, "INFIBULA").
dico("I", 8, "INFIBULE").
dico("I", 8, "INFICHUE").
dico("I", 8, "INFICHUS").
dico("I", 8, "INFIDELE").
dico("I", 8, "INFILTRA").
dico("I", 8, "INFILTRE").
dico("I", 8, "INFINIES").
dico("I", 8, "INFINITE").
dico("I", 8, "INFIRMAI").
dico("I", 8, "INFIRMAS").
dico("I", 8, "INFIRMAT").
dico("I", 8, "INFIRMEE").
dico("I", 8, "INFIRMER").
dico("I", 8, "INFIRMES").
dico("I", 8, "INFIRMEZ").
dico("I", 8, "INFLECHI").
dico("I", 8, "INFLIGEA").
dico("I", 8, "INFLIGEE").
dico("I", 8, "INFLIGER").
dico("I", 8, "INFLIGES").
dico("I", 8, "INFLIGEZ").
dico("I", 8, "INFLUAIS").
dico("I", 8, "INFLUAIT").
dico("I", 8, "INFLUANT").
dico("I", 8, "INFLUEES").
dico("I", 8, "INFLUENT").
dico("I", 8, "INFLUERA").
dico("I", 8, "INFLUIEZ").
dico("I", 8, "INFLUONS").
dico("I", 8, "INFONDEE").
dico("I", 8, "INFONDES").
dico("I", 8, "INFORMAI").
dico("I", 8, "INFORMAS").
dico("I", 8, "INFORMAT").
dico("I", 8, "INFORMEE").
dico("I", 8, "INFORMEL").
dico("I", 8, "INFORMER").
dico("I", 8, "INFORMES").
dico("I", 8, "INFORMEZ").
dico("I", 8, "INFOUTUE").
dico("I", 8, "INFOUTUS").
dico("I", 8, "INFRASON").
dico("I", 8, "INFUSAIS").
dico("I", 8, "INFUSAIT").
dico("I", 8, "INFUSANT").
dico("I", 8, "INFUSEES").
dico("I", 8, "INFUSENT").
dico("I", 8, "INFUSERA").
dico("I", 8, "INFUSIEZ").
dico("I", 8, "INFUSION").
dico("I", 8, "INFUSONS").
dico("I", 8, "INGAMBES").
dico("I", 8, "INGELIFS").
dico("I", 8, "INGELIVE").
dico("I", 8, "INGENIAI").
dico("I", 8, "INGENIAS").
dico("I", 8, "INGENIAT").
dico("I", 8, "INGENIEE").
dico("I", 8, "INGENIER").
dico("I", 8, "INGENIES").
dico("I", 8, "INGENIEZ").
dico("I", 8, "INGENUES").
dico("I", 8, "INGERAIS").
dico("I", 8, "INGERAIT").
dico("I", 8, "INGERANT").
dico("I", 8, "INGEREES").
dico("I", 8, "INGERENT").
dico("I", 8, "INGERERA").
dico("I", 8, "INGERIEZ").
dico("I", 8, "INGERONS").
dico("I", 8, "INGRATES").
dico("I", 8, "INGRISME").
dico("I", 8, "INGRISTE").
dico("I", 8, "INGUINAL").
dico("I", 8, "INHABILE").
dico("I", 8, "INHABITE").
dico("I", 8, "INHALAIS").
dico("I", 8, "INHALAIT").
dico("I", 8, "INHALANT").
dico("I", 8, "INHALEES").
dico("I", 8, "INHALENT").
dico("I", 8, "INHALERA").
dico("I", 8, "INHALIEZ").
dico("I", 8, "INHALONS").
dico("I", 8, "INHERENT").
dico("I", 8, "INHIBAIS").
dico("I", 8, "INHIBAIT").
dico("I", 8, "INHIBANT").
dico("I", 8, "INHIBEES").
dico("I", 8, "INHIBENT").
dico("I", 8, "INHIBERA").
dico("I", 8, "INHIBIEZ").
dico("I", 8, "INHIBONS").
dico("I", 8, "INHUMAIN").
dico("I", 8, "INHUMAIS").
dico("I", 8, "INHUMAIT").
dico("I", 8, "INHUMANT").
dico("I", 8, "INHUMEES").
dico("I", 8, "INHUMENT").
dico("I", 8, "INHUMERA").
dico("I", 8, "INHUMIEZ").
dico("I", 8, "INHUMONS").
dico("I", 8, "INIMITEE").
dico("I", 8, "INIMITES").
dico("I", 8, "INIMITIE").
dico("I", 8, "INIQUITE").
dico("I", 8, "INITIAIS").
dico("I", 8, "INITIAIT").
dico("I", 8, "INITIALA").
dico("I", 8, "INITIALE").
dico("I", 8, "INITIANT").
dico("I", 8, "INITIAUX").
dico("I", 8, "INITIEES").
dico("I", 8, "INITIENT").
dico("I", 8, "INITIERA").
dico("I", 8, "INITIIEZ").
dico("I", 8, "INITIONS").
dico("I", 8, "INJECTAI").
dico("I", 8, "INJECTAS").
dico("I", 8, "INJECTAT").
dico("I", 8, "INJECTEE").
dico("I", 8, "INJECTER").
dico("I", 8, "INJECTES").
dico("I", 8, "INJECTEZ").
dico("I", 8, "INJECTIF").
dico("I", 8, "INJURIAI").
dico("I", 8, "INJURIAS").
dico("I", 8, "INJURIAT").
dico("I", 8, "INJURIEE").
dico("I", 8, "INJURIER").
dico("I", 8, "INJURIES").
dico("I", 8, "INJURIEZ").
dico("I", 8, "INJUSTES").
dico("I", 8, "INNEISME").
dico("I", 8, "INNEISTE").
dico("I", 8, "INNEITES").
dico("I", 8, "INNERVAI").
dico("I", 8, "INNERVAS").
dico("I", 8, "INNERVAT").
dico("I", 8, "INNERVEE").
dico("I", 8, "INNERVER").
dico("I", 8, "INNERVES").
dico("I", 8, "INNERVEZ").
dico("I", 8, "INNOCENT").
dico("I", 8, "INNOMEES").
dico("I", 8, "INNOMINE").
dico("I", 8, "INNOMMEE").
dico("I", 8, "INNOMMES").
dico("I", 8, "INNOVAIS").
dico("I", 8, "INNOVAIT").
dico("I", 8, "INNOVANT").
dico("I", 8, "INNOVEES").
dico("I", 8, "INNOVENT").
dico("I", 8, "INNOVERA").
dico("I", 8, "INNOVIEZ").
dico("I", 8, "INNOVONS").
dico("I", 8, "INOCCUPE").
dico("I", 8, "INOCULAI").
dico("I", 8, "INOCULAS").
dico("I", 8, "INOCULAT").
dico("I", 8, "INOCULEE").
dico("I", 8, "INOCULER").
dico("I", 8, "INOCULES").
dico("I", 8, "INOCULEZ").
dico("I", 8, "INOCULUM").
dico("I", 8, "INOCYBES").
dico("I", 8, "INODORES").
dico("I", 8, "INONDAIS").
dico("I", 8, "INONDAIT").
dico("I", 8, "INONDANT").
dico("I", 8, "INONDEES").
dico("I", 8, "INONDENT").
dico("I", 8, "INONDERA").
dico("I", 8, "INONDIEZ").
dico("I", 8, "INONDONS").
dico("I", 8, "INOPINEE").
dico("I", 8, "INOPINES").
dico("I", 8, "INOTROPE").
dico("I", 8, "INQUARTS").
dico("I", 8, "INQUIETA").
dico("I", 8, "INQUIETE").
dico("I", 8, "INQUIETS").
dico("I", 8, "INQUILIN").
dico("I", 8, "INSANITE").
dico("I", 8, "INSATURE").
dico("I", 8, "INSCRIRA").
dico("I", 8, "INSCRIRE").
dico("I", 8, "INSCRITE").
dico("I", 8, "INSCRITS").
dico("I", 8, "INSCRIVE").
dico("I", 8, "INSCULPA").
dico("I", 8, "INSCULPE").
dico("I", 8, "INSECTES").
dico("I", 8, "INSEMINA").
dico("I", 8, "INSEMINE").
dico("I", 8, "INSENSEE").
dico("I", 8, "INSENSES").
dico("I", 8, "INSERAIS").
dico("I", 8, "INSERAIT").
dico("I", 8, "INSERANT").
dico("I", 8, "INSEREES").
dico("I", 8, "INSERENT").
dico("I", 8, "INSERERA").
dico("I", 8, "INSERIEZ").
dico("I", 8, "INSERONS").
dico("I", 8, "INSIGHTS").
dico("I", 8, "INSIGNES").
dico("I", 8, "INSINUAI").
dico("I", 8, "INSINUAS").
dico("I", 8, "INSINUAT").
dico("I", 8, "INSINUEE").
dico("I", 8, "INSINUER").
dico("I", 8, "INSINUES").
dico("I", 8, "INSINUEZ").
dico("I", 8, "INSIPIDE").
dico("I", 8, "INSISTAI").
dico("I", 8, "INSISTAS").
dico("I", 8, "INSISTAT").
dico("I", 8, "INSISTER").
dico("I", 8, "INSISTES").
dico("I", 8, "INSISTEZ").
dico("I", 8, "INSOLAIS").
dico("I", 8, "INSOLAIT").
dico("I", 8, "INSOLANT").
dico("I", 8, "INSOLEES").
dico("I", 8, "INSOLENT").
dico("I", 8, "INSOLERA").
dico("I", 8, "INSOLIEZ").
dico("I", 8, "INSOLITE").
dico("I", 8, "INSOLONS").
dico("I", 8, "INSOMNIE").
dico("I", 8, "INSONORE").
dico("I", 8, "INSOUMIS").
dico("I", 8, "INSPECTA").
dico("I", 8, "INSPECTE").
dico("I", 8, "INSPIRAI").
dico("I", 8, "INSPIRAS").
dico("I", 8, "INSPIRAT").
dico("I", 8, "INSPIREE").
dico("I", 8, "INSPIRER").
dico("I", 8, "INSPIRES").
dico("I", 8, "INSPIREZ").
dico("I", 8, "INSTABLE").
dico("I", 8, "INSTALLA").
dico("I", 8, "INSTALLE").
dico("I", 8, "INSTANCE").
dico("I", 8, "INSTANTE").
dico("I", 8, "INSTANTS").
dico("I", 8, "INSTAURA").
dico("I", 8, "INSTAURE").
dico("I", 8, "INSTIGUA").
dico("I", 8, "INSTIGUE").
dico("I", 8, "INSTILLA").
dico("I", 8, "INSTILLE").
dico("I", 8, "INSTINCT").
dico("I", 8, "INSTITUA").
dico("I", 8, "INSTITUE").
dico("I", 8, "INSTITUT").
dico("I", 8, "INSTRUIS").
dico("I", 8, "INSTRUIT").
dico("I", 8, "INSUCCES").
dico("I", 8, "INSUFFLA").
dico("I", 8, "INSUFFLE").
dico("I", 8, "INSULINE").
dico("I", 8, "INSULTAI").
dico("I", 8, "INSULTAS").
dico("I", 8, "INSULTAT").
dico("I", 8, "INSULTEE").
dico("I", 8, "INSULTER").
dico("I", 8, "INSULTES").
dico("I", 8, "INSULTEZ").
dico("I", 8, "INSURGEA").
dico("I", 8, "INSURGEE").
dico("I", 8, "INSURGER").
dico("I", 8, "INSURGES").
dico("I", 8, "INSURGEZ").
dico("I", 8, "INTACTES").
dico("I", 8, "INTAILLA").
dico("I", 8, "INTAILLE").
dico("I", 8, "INTEGRAI").
dico("I", 8, "INTEGRAL").
dico("I", 8, "INTEGRAS").
dico("I", 8, "INTEGRAT").
dico("I", 8, "INTEGREE").
dico("I", 8, "INTEGRER").
dico("I", 8, "INTEGRES").
dico("I", 8, "INTEGREZ").
dico("I", 8, "INTELLOS").
dico("I", 8, "INTENSES").
dico("I", 8, "INTENSIF").
dico("I", 8, "INTENTAI").
dico("I", 8, "INTENTAS").
dico("I", 8, "INTENTAT").
dico("I", 8, "INTENTEE").
dico("I", 8, "INTENTER").
dico("I", 8, "INTENTES").
dico("I", 8, "INTENTEZ").
dico("I", 8, "INTERAGI").
dico("I", 8, "INTERDIS").
dico("I", 8, "INTERDIT").
dico("I", 8, "INTERETS").
dico("I", 8, "INTERIMS").
dico("I", 8, "INTERNAI").
dico("I", 8, "INTERNAS").
dico("I", 8, "INTERNAT").
dico("I", 8, "INTERNEE").
dico("I", 8, "INTERNER").
dico("I", 8, "INTERNES").
dico("I", 8, "INTERNET").
dico("I", 8, "INTERNEZ").
dico("I", 8, "INTERROI").
dico("I", 8, "INTERROS").
dico("I", 8, "INTESTAT").
dico("I", 8, "INTESTIN").
dico("I", 8, "INTIFADA").
dico("I", 8, "INTIMAIS").
dico("I", 8, "INTIMAIT").
dico("I", 8, "INTIMANT").
dico("I", 8, "INTIMEES").
dico("I", 8, "INTIMENT").
dico("I", 8, "INTIMERA").
dico("I", 8, "INTIMIDA").
dico("I", 8, "INTIMIDE").
dico("I", 8, "INTIMIEZ").
dico("I", 8, "INTIMITE").
dico("I", 8, "INTIMONS").
dico("I", 8, "INTITULA").
dico("I", 8, "INTITULE").
dico("I", 8, "INTOUCHE").
dico("I", 8, "INTRADOS").
dico("I", 8, "INTRANET").
dico("I", 8, "INTRANTS").
dico("I", 8, "INTRIGUA").
dico("I", 8, "INTRIGUE").
dico("I", 8, "INTRIQUA").
dico("I", 8, "INTRIQUE").
dico("I", 8, "INTROITS").
dico("I", 8, "INTRORSE").
dico("I", 8, "INTRUSES").
dico("I", 8, "INTRUSIF").
dico("I", 8, "INTUBAIS").
dico("I", 8, "INTUBAIT").
dico("I", 8, "INTUBANT").
dico("I", 8, "INTUBEES").
dico("I", 8, "INTUBENT").
dico("I", 8, "INTUBERA").
dico("I", 8, "INTUBIEZ").
dico("I", 8, "INTUBONS").
dico("I", 8, "INTUITAI").
dico("I", 8, "INTUITAS").
dico("I", 8, "INTUITAT").
dico("I", 8, "INTUITEE").
dico("I", 8, "INTUITER").
dico("I", 8, "INTUITES").
dico("I", 8, "INTUITEZ").
dico("I", 8, "INTUITIF").
dico("I", 8, "INULINES").
dico("I", 8, "INUSABLE").
dico("I", 8, "INUSITEE").
dico("I", 8, "INUSITES").
dico("I", 8, "INUSUELS").
dico("I", 8, "INUTILES").
dico("I", 8, "INVAGINA").
dico("I", 8, "INVAGINE").
dico("I", 8, "INVAINCU").
dico("I", 8, "INVALIDA").
dico("I", 8, "INVALIDE").
dico("I", 8, "INVASIFS").
dico("I", 8, "INVASION").
dico("I", 8, "INVASIVE").
dico("I", 8, "INVENDUE").
dico("I", 8, "INVENDUS").
dico("I", 8, "INVENGEE").
dico("I", 8, "INVENGES").
dico("I", 8, "INVENTAI").
dico("I", 8, "INVENTAS").
dico("I", 8, "INVENTAT").
dico("I", 8, "INVENTEE").
dico("I", 8, "INVENTER").
dico("I", 8, "INVENTES").
dico("I", 8, "INVENTEZ").
dico("I", 8, "INVENTIF").
dico("I", 8, "INVERSAI").
dico("I", 8, "INVERSAS").
dico("I", 8, "INVERSAT").
dico("I", 8, "INVERSEE").
dico("I", 8, "INVERSER").
dico("I", 8, "INVERSES").
dico("I", 8, "INVERSEZ").
dico("I", 8, "INVERSIF").
dico("I", 8, "INVERTIE").
dico("I", 8, "INVERTIR").
dico("I", 8, "INVERTIS").
dico("I", 8, "INVERTIT").
dico("I", 8, "INVESTIE").
dico("I", 8, "INVESTIR").
dico("I", 8, "INVESTIS").
dico("I", 8, "INVESTIT").
dico("I", 8, "INVETERA").
dico("I", 8, "INVETERE").
dico("I", 8, "INVIOLEE").
dico("I", 8, "INVIOLES").
dico("I", 8, "INVITAIS").
dico("I", 8, "INVITAIT").
dico("I", 8, "INVITANT").
dico("I", 8, "INVITEES").
dico("I", 8, "INVITENT").
dico("I", 8, "INVITERA").
dico("I", 8, "INVITEUR").
dico("I", 8, "INVITIEZ").
dico("I", 8, "INVITONS").
dico("I", 8, "INVOLUTE").
dico("I", 8, "INVOQUAI").
dico("I", 8, "INVOQUAS").
dico("I", 8, "INVOQUAT").
dico("I", 8, "INVOQUEE").
dico("I", 8, "INVOQUER").
dico("I", 8, "INVOQUES").
dico("I", 8, "INVOQUEZ").
dico("I", 8, "IODAIENT").
dico("I", 8, "IODASSES").
dico("I", 8, "IODERAIS").
dico("I", 8, "IODERAIT").
dico("I", 8, "IODERENT").
dico("I", 8, "IODERIEZ").
dico("I", 8, "IODERONS").
dico("I", 8, "IODERONT").
dico("I", 8, "IODEUSES").
dico("I", 8, "IODIQUES").
dico("I", 8, "IODISMES").
dico("I", 8, "IODLAMES").
dico("I", 8, "IODLASSE").
dico("I", 8, "IODLATES").
dico("I", 8, "IODLERAI").
dico("I", 8, "IODLERAS").
dico("I", 8, "IODLEREZ").
dico("I", 8, "IODLIONS").
dico("I", 8, "IODUREES").
dico("I", 8, "IONIENNE").
dico("I", 8, "IONIQUES").
dico("I", 8, "IONISAIS").
dico("I", 8, "IONISAIT").
dico("I", 8, "IONISANT").
dico("I", 8, "IONISEES").
dico("I", 8, "IONISENT").
dico("I", 8, "IONISERA").
dico("I", 8, "IONISIEZ").
dico("I", 8, "IONISMES").
dico("I", 8, "IONISONS").
dico("I", 8, "IOULAMES").
dico("I", 8, "IOULASSE").
dico("I", 8, "IOULATES").
dico("I", 8, "IOULERAI").
dico("I", 8, "IOULERAS").
dico("I", 8, "IOULEREZ").
dico("I", 8, "IOULIONS").
dico("I", 8, "IPSEITES").
dico("I", 8, "IRAKIENS").
dico("I", 8, "IRANIENS").
dico("I", 8, "IRAQIENS").
dico("I", 8, "IRAQUIEN").
dico("I", 8, "IRENIQUE").
dico("I", 8, "IRENISME").
dico("I", 8, "IRIDACEE").
dico("I", 8, "IRIDIEES").
dico("I", 8, "IRIDIENS").
dico("I", 8, "IRIDIUMS").
dico("I", 8, "IRIENNES").
dico("I", 8, "IRISABLE").
dico("I", 8, "IRISAMES").
dico("I", 8, "IRISASSE").
dico("I", 8, "IRISATES").
dico("I", 8, "IRISERAI").
dico("I", 8, "IRISERAS").
dico("I", 8, "IRISEREZ").
dico("I", 8, "IRISIONS").
dico("I", 8, "IRONIQUE").
dico("I", 8, "IRONISAI").
dico("I", 8, "IRONISAS").
dico("I", 8, "IRONISAT").
dico("I", 8, "IRONISER").
dico("I", 8, "IRONISES").
dico("I", 8, "IRONISEZ").
dico("I", 8, "IRONISTE").
dico("I", 8, "IROQUOIS").
dico("I", 8, "IRRADIAI").
dico("I", 8, "IRRADIAS").
dico("I", 8, "IRRADIAT").
dico("I", 8, "IRRADIEE").
dico("I", 8, "IRRADIER").
dico("I", 8, "IRRADIES").
dico("I", 8, "IRRADIEZ").
dico("I", 8, "IRREELLE").
dico("I", 8, "IRREFUTE").
dico("I", 8, "IRRESOLU").
dico("I", 8, "IRRIGUAI").
dico("I", 8, "IRRIGUAS").
dico("I", 8, "IRRIGUAT").
dico("I", 8, "IRRIGUEE").
dico("I", 8, "IRRIGUER").
dico("I", 8, "IRRIGUES").
dico("I", 8, "IRRIGUEZ").
dico("I", 8, "IRRITAIS").
dico("I", 8, "IRRITAIT").
dico("I", 8, "IRRITANT").
dico("I", 8, "IRRITEES").
dico("I", 8, "IRRITENT").
dico("I", 8, "IRRITERA").
dico("I", 8, "IRRITIEZ").
dico("I", 8, "IRRITONS").
dico("I", 8, "ISABELLE").
dico("I", 8, "ISARIENS").
dico("I", 8, "ISCHEMIE").
dico("I", 8, "ISCHIONS").
dico("I", 8, "ISERANES").
dico("I", 8, "ISEROISE").
dico("I", 8, "ISIAQUES").
dico("I", 8, "ISLAMISA").
dico("I", 8, "ISLAMISE").
dico("I", 8, "ISOBARES").
dico("I", 8, "ISOBATHE").
dico("I", 8, "ISOCARDE").
dico("I", 8, "ISOCELES").
dico("I", 8, "ISOCHORE").
dico("I", 8, "ISOCLINE").
dico("I", 8, "ISODOMES").
dico("I", 8, "ISOGAMES").
dico("I", 8, "ISOGAMIE").
dico("I", 8, "ISOGONAL").
dico("I", 8, "ISOGONES").
dico("I", 8, "ISOHYETE").
dico("I", 8, "ISOHYPSE").
dico("I", 8, "ISOLABLE").
dico("I", 8, "ISOLAMES").
dico("I", 8, "ISOLANTE").
dico("I", 8, "ISOLANTS").
dico("I", 8, "ISOLASSE").
dico("I", 8, "ISOLATES").
dico("I", 8, "ISOLERAI").
dico("I", 8, "ISOLERAS").
dico("I", 8, "ISOLEREZ").
dico("I", 8, "ISOLIONS").
dico("I", 8, "ISOLOGUE").
dico("I", 8, "ISOLOIRS").
dico("I", 8, "ISOMERES").
dico("I", 8, "ISOMERIE").
dico("I", 8, "ISONOMIE").
dico("I", 8, "ISOPHASE").
dico("I", 8, "ISOPODES").
dico("I", 8, "ISOPRENE").
dico("I", 8, "ISOPTERE").
dico("I", 8, "ISOSISTE").
dico("I", 8, "ISOSPINS").
dico("I", 8, "ISOTONES").
dico("I", 8, "ISOTONIE").
dico("I", 8, "ISOTOPES").
dico("I", 8, "ISOTOPIE").
dico("I", 8, "ISOTRONS").
dico("I", 8, "ISOTROPE").
dico("I", 8, "ISSANTES").
dico("I", 8, "ISTREENS").
dico("I", 8, "ITALIENS").
dico("I", 8, "ITALIQUE").
dico("I", 8, "ITERAMES").
dico("I", 8, "ITERASSE").
dico("I", 8, "ITERATES").
dico("I", 8, "ITERATIF").
dico("I", 8, "ITERERAI").
dico("I", 8, "ITERERAS").
dico("I", 8, "ITEREREZ").
dico("I", 8, "ITERIONS").
dico("I", 8, "IVOIRIEN").
dico("I", 8, "IVOIRIER").
dico("I", 8, "IVOIRINE").
dico("I", 8, "IVOIRINS").
dico("I", 8, "IVRESSES").
dico("I", 8, "IVROGNES").
dico("I", 8, "IXASSENT").
dico("I", 8, "IXASSIEZ").
dico("I", 8, "IXERIONS").
