dico("I", 9, "IAMBIQUES").
dico("I", 9, "IATROGENE").
dico("I", 9, "IBERIENNE").
dico("I", 9, "IBERIQUES").
dico("I", 9, "ICAQUIERS").
dico("I", 9, "ICARIENNE").
dico("I", 9, "ICAUNAISE").
dico("I", 9, "ICEFIELDS").
dico("I", 9, "ICHNEUMON").
dico("I", 9, "ICHOREUSE").
dico("I", 9, "ICHTHYOSE").
dico("I", 9, "ICHTYOIDE").
dico("I", 9, "ICHTYOSES").
dico("I", 9, "ICONICITE").
dico("I", 9, "ICONIQUES").
dico("I", 9, "ICONOGENE").
dico("I", 9, "ICOSAEDRE").
dico("I", 9, "ICTERIQUE").
dico("I", 9, "IDEALISAI").
dico("I", 9, "IDEALISAS").
dico("I", 9, "IDEALISAT").
dico("I", 9, "IDEALISEE").
dico("I", 9, "IDEALISER").
dico("I", 9, "IDEALISES").
dico("I", 9, "IDEALISEZ").
dico("I", 9, "IDEALISME").
dico("I", 9, "IDEALISTE").
dico("I", 9, "IDEALITES").
dico("I", 9, "IDEATIONS").
dico("I", 9, "IDENTIFIA").
dico("I", 9, "IDENTIFIE").
dico("I", 9, "IDENTIQUE").
dico("I", 9, "IDENTITES").
dico("I", 9, "IDEOLOGIE").
dico("I", 9, "IDEOLOGUE").
dico("I", 9, "IDIOLECTE").
dico("I", 9, "IDIOTIFIA").
dico("I", 9, "IDIOTIFIE").
dico("I", 9, "IDIOTISME").
dico("I", 9, "IDOLATRAI").
dico("I", 9, "IDOLATRAS").
dico("I", 9, "IDOLATRAT").
dico("I", 9, "IDOLATREE").
dico("I", 9, "IDOLATRER").
dico("I", 9, "IDOLATRES").
dico("I", 9, "IDOLATREZ").
dico("I", 9, "IDOLATRIE").
dico("I", 9, "IDYLLIQUE").
dico("I", 9, "IGNICOLES").
dico("I", 9, "IGNIFERES").
dico("I", 9, "IGNIFUGEA").
dico("I", 9, "IGNIFUGEE").
dico("I", 9, "IGNIFUGER").
dico("I", 9, "IGNIFUGES").
dico("I", 9, "IGNIFUGEZ").
dico("I", 9, "IGNITIONS").
dico("I", 9, "IGNITRONS").
dico("I", 9, "IGNIVOMES").
dico("I", 9, "IGNIVORES").
dico("I", 9, "IGNOMINIE").
dico("I", 9, "IGNORAMES").
dico("I", 9, "IGNORANCE").
dico("I", 9, "IGNORANTE").
dico("I", 9, "IGNORANTS").
dico("I", 9, "IGNORASSE").
dico("I", 9, "IGNORATES").
dico("I", 9, "IGNORERAI").
dico("I", 9, "IGNORERAS").
dico("I", 9, "IGNOREREZ").
dico("I", 9, "IGNORIONS").
dico("I", 9, "IGUANIDES").
dico("I", 9, "IGUANODON").
dico("I", 9, "ILLEGALES").
dico("I", 9, "ILLETTREE").
dico("I", 9, "ILLETTRES").
dico("I", 9, "ILLICITES").
dico("I", 9, "ILLIMITEE").
dico("I", 9, "ILLIMITES").
dico("I", 9, "ILLISIBLE").
dico("I", 9, "ILLOGIQUE").
dico("I", 9, "ILLOGISME").
dico("I", 9, "ILLUMINAI").
dico("I", 9, "ILLUMINAS").
dico("I", 9, "ILLUMINAT").
dico("I", 9, "ILLUMINEE").
dico("I", 9, "ILLUMINER").
dico("I", 9, "ILLUMINES").
dico("I", 9, "ILLUMINEZ").
dico("I", 9, "ILLUSIONS").
dico("I", 9, "ILLUSOIRE").
dico("I", 9, "ILLUSTRAI").
dico("I", 9, "ILLUSTRAS").
dico("I", 9, "ILLUSTRAT").
dico("I", 9, "ILLUSTREE").
dico("I", 9, "ILLUSTRER").
dico("I", 9, "ILLUSTRES").
dico("I", 9, "ILLUSTREZ").
dico("I", 9, "ILLUTAMES").
dico("I", 9, "ILLUTASSE").
dico("I", 9, "ILLUTATES").
dico("I", 9, "ILLUTERAI").
dico("I", 9, "ILLUTERAS").
dico("I", 9, "ILLUTEREZ").
dico("I", 9, "ILLUTIONS").
dico("I", 9, "ILLUVIALE").
dico("I", 9, "ILLUVIAUX").
dico("I", 9, "ILLUVIONS").
dico("I", 9, "ILLUVIUMS").
dico("I", 9, "ILLYRIENS").
dico("I", 9, "ILMENITES").
dico("I", 9, "ILOTIERES").
dico("I", 9, "ILOTISMES").
dico("I", 9, "IMAGEAMES").
dico("I", 9, "IMAGEASSE").
dico("I", 9, "IMAGEATES").
dico("I", 9, "IMAGERAIS").
dico("I", 9, "IMAGERAIT").
dico("I", 9, "IMAGERENT").
dico("I", 9, "IMAGERIES").
dico("I", 9, "IMAGERIEZ").
dico("I", 9, "IMAGERONS").
dico("I", 9, "IMAGERONT").
dico("I", 9, "IMAGEUSES").
dico("I", 9, "IMAGIERES").
dico("I", 9, "IMAGINAIS").
dico("I", 9, "IMAGINAIT").
dico("I", 9, "IMAGINALE").
dico("I", 9, "IMAGINANT").
dico("I", 9, "IMAGINAUX").
dico("I", 9, "IMAGINEES").
dico("I", 9, "IMAGINENT").
dico("I", 9, "IMAGINERA").
dico("I", 9, "IMAGINIEZ").
dico("I", 9, "IMAGINONS").
dico("I", 9, "IMBECILES").
dico("I", 9, "IMBIBAMES").
dico("I", 9, "IMBIBASSE").
dico("I", 9, "IMBIBATES").
dico("I", 9, "IMBIBERAI").
dico("I", 9, "IMBIBERAS").
dico("I", 9, "IMBIBEREZ").
dico("I", 9, "IMBIBIONS").
dico("I", 9, "IMBITABLE").
dico("I", 9, "IMBRIQUAI").
dico("I", 9, "IMBRIQUAS").
dico("I", 9, "IMBRIQUAT").
dico("I", 9, "IMBRIQUEE").
dico("I", 9, "IMBRIQUER").
dico("I", 9, "IMBRIQUES").
dico("I", 9, "IMBRIQUEZ").
dico("I", 9, "IMBROGLIO").
dico("I", 9, "IMBRULEES").
dico("I", 9, "IMBUVABLE").
dico("I", 9, "IMIDAZOLE").
dico("I", 9, "IMITABLES").
dico("I", 9, "IMITAIENT").
dico("I", 9, "IMITASSES").
dico("I", 9, "IMITATEUR").
dico("I", 9, "IMITATIFS").
dico("I", 9, "IMITATION").
dico("I", 9, "IMITATIVE").
dico("I", 9, "IMITERAIS").
dico("I", 9, "IMITERAIT").
dico("I", 9, "IMITERENT").
dico("I", 9, "IMITERIEZ").
dico("I", 9, "IMITERONS").
dico("I", 9, "IMITERONT").
dico("I", 9, "IMMACULEE").
dico("I", 9, "IMMACULES").
dico("I", 9, "IMMANENCE").
dico("I", 9, "IMMANENTE").
dico("I", 9, "IMMANENTS").
dico("I", 9, "IMMATURES").
dico("I", 9, "IMMEDIATE").
dico("I", 9, "IMMEDIATS").
dico("I", 9, "IMMELMANN").
dico("I", 9, "IMMENSITE").
dico("I", 9, "IMMERGEAI").
dico("I", 9, "IMMERGEAS").
dico("I", 9, "IMMERGEAT").
dico("I", 9, "IMMERGEES").
dico("I", 9, "IMMERGENT").
dico("I", 9, "IMMERGERA").
dico("I", 9, "IMMERGIEZ").
dico("I", 9, "IMMERITEE").
dico("I", 9, "IMMERITES").
dico("I", 9, "IMMERSIFS").
dico("I", 9, "IMMERSION").
dico("I", 9, "IMMERSIVE").
dico("I", 9, "IMMEUBLES").
dico("I", 9, "IMMIGRAIS").
dico("I", 9, "IMMIGRAIT").
dico("I", 9, "IMMIGRANT").
dico("I", 9, "IMMIGREES").
dico("I", 9, "IMMIGRENT").
dico("I", 9, "IMMIGRERA").
dico("I", 9, "IMMIGRIEZ").
dico("I", 9, "IMMIGRONS").
dico("I", 9, "IMMINENCE").
dico("I", 9, "IMMINENTE").
dico("I", 9, "IMMINENTS").
dico("I", 9, "IMMISCAIS").
dico("I", 9, "IMMISCAIT").
dico("I", 9, "IMMISCANT").
dico("I", 9, "IMMISCEES").
dico("I", 9, "IMMISCENT").
dico("I", 9, "IMMISCERA").
dico("I", 9, "IMMISCIEZ").
dico("I", 9, "IMMISCONS").
dico("I", 9, "IMMIXTION").
dico("I", 9, "IMMOBILES").
dico("I", 9, "IMMODEREE").
dico("I", 9, "IMMODERES").
dico("I", 9, "IMMODESTE").
dico("I", 9, "IMMOLAMES").
dico("I", 9, "IMMOLASSE").
dico("I", 9, "IMMOLATES").
dico("I", 9, "IMMOLERAI").
dico("I", 9, "IMMOLERAS").
dico("I", 9, "IMMOLEREZ").
dico("I", 9, "IMMOLIONS").
dico("I", 9, "IMMONDICE").
dico("I", 9, "IMMORALES").
dico("I", 9, "IMMORTELS").
dico("I", 9, "IMMOTIVEE").
dico("I", 9, "IMMOTIVES").
dico("I", 9, "IMMUABLES").
dico("I", 9, "IMMUNISAI").
dico("I", 9, "IMMUNISAS").
dico("I", 9, "IMMUNISAT").
dico("I", 9, "IMMUNISEE").
dico("I", 9, "IMMUNISER").
dico("I", 9, "IMMUNISES").
dico("I", 9, "IMMUNISEZ").
dico("I", 9, "IMMUNITES").
dico("I", 9, "IMPACTAIS").
dico("I", 9, "IMPACTAIT").
dico("I", 9, "IMPACTANT").
dico("I", 9, "IMPACTEES").
dico("I", 9, "IMPACTENT").
dico("I", 9, "IMPACTERA").
dico("I", 9, "IMPACTIEZ").
dico("I", 9, "IMPACTION").
dico("I", 9, "IMPACTITE").
dico("I", 9, "IMPACTONS").
dico("I", 9, "IMPALUDEE").
dico("I", 9, "IMPALUDES").
dico("I", 9, "IMPARABLE").
dico("I", 9, "IMPARFAIT").
dico("I", 9, "IMPARITES").
dico("I", 9, "IMPARTIAL").
dico("I", 9, "IMPARTIES").
dico("I", 9, "IMPARTIRA").
dico("I", 9, "IMPATIENS").
dico("I", 9, "IMPATIENT").
dico("I", 9, "IMPAVIDES").
dico("I", 9, "IMPAYABLE").
dico("I", 9, "IMPEDANCE").
dico("I", 9, "IMPERATIF").
dico("I", 9, "IMPERFORE").
dico("I", 9, "IMPERIALE").
dico("I", 9, "IMPERIAUX").
dico("I", 9, "IMPERIEUX").
dico("I", 9, "IMPERITIE").
dico("I", 9, "IMPERIUMS").
dico("I", 9, "IMPETIGOS").
dico("I", 9, "IMPETRAIS").
dico("I", 9, "IMPETRAIT").
dico("I", 9, "IMPETRANT").
dico("I", 9, "IMPETREES").
dico("I", 9, "IMPETRENT").
dico("I", 9, "IMPETRERA").
dico("I", 9, "IMPETRIEZ").
dico("I", 9, "IMPETRONS").
dico("I", 9, "IMPETUEUX").
dico("I", 9, "IMPLANTAI").
dico("I", 9, "IMPLANTAS").
dico("I", 9, "IMPLANTAT").
dico("I", 9, "IMPLANTEE").
dico("I", 9, "IMPLANTER").
dico("I", 9, "IMPLANTES").
dico("I", 9, "IMPLANTEZ").
dico("I", 9, "IMPLICITE").
dico("I", 9, "IMPLIQUAI").
dico("I", 9, "IMPLIQUAS").
dico("I", 9, "IMPLIQUAT").
dico("I", 9, "IMPLIQUEE").
dico("I", 9, "IMPLIQUER").
dico("I", 9, "IMPLIQUES").
dico("I", 9, "IMPLIQUEZ").
dico("I", 9, "IMPLORAIS").
dico("I", 9, "IMPLORAIT").
dico("I", 9, "IMPLORANT").
dico("I", 9, "IMPLOREES").
dico("I", 9, "IMPLORENT").
dico("I", 9, "IMPLORERA").
dico("I", 9, "IMPLORIEZ").
dico("I", 9, "IMPLORONS").
dico("I", 9, "IMPLOSAIS").
dico("I", 9, "IMPLOSAIT").
dico("I", 9, "IMPLOSANT").
dico("I", 9, "IMPLOSENT").
dico("I", 9, "IMPLOSERA").
dico("I", 9, "IMPLOSIEZ").
dico("I", 9, "IMPLOSIFS").
dico("I", 9, "IMPLOSION").
dico("I", 9, "IMPLOSIVE").
dico("I", 9, "IMPLOSONS").
dico("I", 9, "IMPLUVIUM").
dico("I", 9, "IMPORTAIS").
dico("I", 9, "IMPORTAIT").
dico("I", 9, "IMPORTANT").
dico("I", 9, "IMPORTEES").
dico("I", 9, "IMPORTENT").
dico("I", 9, "IMPORTERA").
dico("I", 9, "IMPORTIEZ").
dico("I", 9, "IMPORTONS").
dico("I", 9, "IMPORTUNA").
dico("I", 9, "IMPORTUNE").
dico("I", 9, "IMPORTUNS").
dico("I", 9, "IMPOSABLE").
dico("I", 9, "IMPOSAMES").
dico("I", 9, "IMPOSANTE").
dico("I", 9, "IMPOSANTS").
dico("I", 9, "IMPOSASSE").
dico("I", 9, "IMPOSATES").
dico("I", 9, "IMPOSERAI").
dico("I", 9, "IMPOSERAS").
dico("I", 9, "IMPOSEREZ").
dico("I", 9, "IMPOSEURS").
dico("I", 9, "IMPOSEUSE").
dico("I", 9, "IMPOSIONS").
dico("I", 9, "IMPOSTEUR").
dico("I", 9, "IMPOSTURE").
dico("I", 9, "IMPOTENCE").
dico("I", 9, "IMPOTENTE").
dico("I", 9, "IMPOTENTS").
dico("I", 9, "IMPRECISE").
dico("I", 9, "IMPREGNAI").
dico("I", 9, "IMPREGNAS").
dico("I", 9, "IMPREGNAT").
dico("I", 9, "IMPREGNEE").
dico("I", 9, "IMPREGNER").
dico("I", 9, "IMPREGNES").
dico("I", 9, "IMPREGNEZ").
dico("I", 9, "IMPRESSIF").
dico("I", 9, "IMPREVUES").
dico("I", 9, "IMPRIMAIS").
dico("I", 9, "IMPRIMAIT").
dico("I", 9, "IMPRIMANT").
dico("I", 9, "IMPRIMEES").
dico("I", 9, "IMPRIMENT").
dico("I", 9, "IMPRIMERA").
dico("I", 9, "IMPRIMEUR").
dico("I", 9, "IMPRIMIEZ").
dico("I", 9, "IMPRIMONS").
dico("I", 9, "IMPROBITE").
dico("I", 9, "IMPROMPTU").
dico("I", 9, "IMPROPRES").
dico("I", 9, "IMPROUVAI").
dico("I", 9, "IMPROUVAS").
dico("I", 9, "IMPROUVAT").
dico("I", 9, "IMPROUVEE").
dico("I", 9, "IMPROUVER").
dico("I", 9, "IMPROUVES").
dico("I", 9, "IMPROUVEZ").
dico("I", 9, "IMPROVISA").
dico("I", 9, "IMPROVISE").
dico("I", 9, "IMPRUDENT").
dico("I", 9, "IMPUBERES").
dico("I", 9, "IMPUBERTE").
dico("I", 9, "IMPUDENCE").
dico("I", 9, "IMPUDENTE").
dico("I", 9, "IMPUDENTS").
dico("I", 9, "IMPUDEURS").
dico("I", 9, "IMPUDIQUE").
dico("I", 9, "IMPULSAIS").
dico("I", 9, "IMPULSAIT").
dico("I", 9, "IMPULSANT").
dico("I", 9, "IMPULSEES").
dico("I", 9, "IMPULSENT").
dico("I", 9, "IMPULSERA").
dico("I", 9, "IMPULSIEZ").
dico("I", 9, "IMPULSIFS").
dico("I", 9, "IMPULSION").
dico("I", 9, "IMPULSIVE").
dico("I", 9, "IMPULSONS").
dico("I", 9, "IMPUNITES").
dico("I", 9, "IMPURETES").
dico("I", 9, "IMPUTABLE").
dico("I", 9, "IMPUTAMES").
dico("I", 9, "IMPUTASSE").
dico("I", 9, "IMPUTATES").
dico("I", 9, "IMPUTERAI").
dico("I", 9, "IMPUTERAS").
dico("I", 9, "IMPUTEREZ").
dico("I", 9, "IMPUTIONS").
dico("I", 9, "INABOUTIE").
dico("I", 9, "INABOUTIS").
dico("I", 9, "INABRITEE").
dico("I", 9, "INABRITES").
dico("I", 9, "INACCEPTE").
dico("I", 9, "INACHEVEE").
dico("I", 9, "INACHEVES").
dico("I", 9, "INACTIONS").
dico("I", 9, "INACTIVAI").
dico("I", 9, "INACTIVAS").
dico("I", 9, "INACTIVAT").
dico("I", 9, "INACTIVEE").
dico("I", 9, "INACTIVER").
dico("I", 9, "INACTIVES").
dico("I", 9, "INACTIVEZ").
dico("I", 9, "INACTUELS").
dico("I", 9, "INADAPTEE").
dico("I", 9, "INADAPTES").
dico("I", 9, "INADEQUAT").
dico("I", 9, "INALIENEE").
dico("I", 9, "INALIENES").
dico("I", 9, "INALPAGES").
dico("I", 9, "INALPAMES").
dico("I", 9, "INALPASSE").
dico("I", 9, "INALPATES").
dico("I", 9, "INALPERAI").
dico("I", 9, "INALPERAS").
dico("I", 9, "INALPEREZ").
dico("I", 9, "INALPIONS").
dico("I", 9, "INALTEREE").
dico("I", 9, "INALTERES").
dico("I", 9, "INAMICALE").
dico("I", 9, "INAMICAUX").
dico("I", 9, "INANIMEES").
dico("I", 9, "INANITION").
dico("I", 9, "INAPAISEE").
dico("I", 9, "INAPAISES").
dico("I", 9, "INAPERCUE").
dico("I", 9, "INAPERCUS").
dico("I", 9, "INASSOUVI").
dico("I", 9, "INATTENDU").
dico("I", 9, "INAUDIBLE").
dico("I", 9, "INAUGURAI").
dico("I", 9, "INAUGURAL").
dico("I", 9, "INAUGURAS").
dico("I", 9, "INAUGURAT").
dico("I", 9, "INAUGUREE").
dico("I", 9, "INAUGURER").
dico("I", 9, "INAUGURES").
dico("I", 9, "INAUGUREZ").
dico("I", 9, "INAVOUEES").
dico("I", 9, "INCAPABLE").
dico("I", 9, "INCARCERA").
dico("I", 9, "INCARCERE").
dico("I", 9, "INCARNAIS").
dico("I", 9, "INCARNAIT").
dico("I", 9, "INCARNANT").
dico("I", 9, "INCARNATE").
dico("I", 9, "INCARNATS").
dico("I", 9, "INCARNEES").
dico("I", 9, "INCARNENT").
dico("I", 9, "INCARNERA").
dico("I", 9, "INCARNIEZ").
dico("I", 9, "INCARNONS").
dico("I", 9, "INCARTADE").
dico("I", 9, "INCASABLE").
dico("I", 9, "INCASIQUE").
dico("I", 9, "INCENDIAI").
dico("I", 9, "INCENDIAS").
dico("I", 9, "INCENDIAT").
dico("I", 9, "INCENDIEE").
dico("I", 9, "INCENDIER").
dico("I", 9, "INCENDIES").
dico("I", 9, "INCENDIEZ").
dico("I", 9, "INCERTAIN").
dico("I", 9, "INCESSANT").
dico("I", 9, "INCHANGEE").
dico("I", 9, "INCHANGES").
dico("I", 9, "INCHOATIF").
dico("I", 9, "INCIDENCE").
dico("I", 9, "INCIDENTE").
dico("I", 9, "INCIDENTS").
dico("I", 9, "INCINERAI").
dico("I", 9, "INCINERAS").
dico("I", 9, "INCINERAT").
dico("I", 9, "INCINEREE").
dico("I", 9, "INCINERER").
dico("I", 9, "INCINERES").
dico("I", 9, "INCINEREZ").
dico("I", 9, "INCISAMES").
dico("I", 9, "INCISASSE").
dico("I", 9, "INCISATES").
dico("I", 9, "INCISERAI").
dico("I", 9, "INCISERAS").
dico("I", 9, "INCISEREZ").
dico("I", 9, "INCISIONS").
dico("I", 9, "INCISIVES").
dico("I", 9, "INCISURES").
dico("I", 9, "INCITAMES").
dico("I", 9, "INCITANTE").
dico("I", 9, "INCITANTS").
dico("I", 9, "INCITASSE").
dico("I", 9, "INCITATES").
dico("I", 9, "INCITATIF").
dico("I", 9, "INCITERAI").
dico("I", 9, "INCITERAS").
dico("I", 9, "INCITEREZ").
dico("I", 9, "INCITIONS").
dico("I", 9, "INCIVILES").
dico("I", 9, "INCIVIQUE").
dico("I", 9, "INCIVISME").
dico("I", 9, "INCLEMENT").
dico("I", 9, "INCLINAIS").
dico("I", 9, "INCLINAIT").
dico("I", 9, "INCLINANT").
dico("I", 9, "INCLINEES").
dico("I", 9, "INCLINENT").
dico("I", 9, "INCLINERA").
dico("I", 9, "INCLINIEZ").
dico("I", 9, "INCLINONS").
dico("I", 9, "INCLUANTS").
dico("I", 9, "INCLUIONS").
dico("I", 9, "INCLURAIS").
dico("I", 9, "INCLURAIT").
dico("I", 9, "INCLURENT").
dico("I", 9, "INCLURIEZ").
dico("I", 9, "INCLURONS").
dico("I", 9, "INCLURONT").
dico("I", 9, "INCLUSIFS").
dico("I", 9, "INCLUSION").
dico("I", 9, "INCLUSIVE").
dico("I", 9, "INCLUSSES").
dico("I", 9, "INCOGNITO").
dico("I", 9, "INCOLORES").
dico("I", 9, "INCOMBAIT").
dico("I", 9, "INCOMBANT").
dico("I", 9, "INCOMBENT").
dico("I", 9, "INCOMBERA").
dico("I", 9, "INCOMMODA").
dico("I", 9, "INCOMMODE").
dico("I", 9, "INCOMPLET").
dico("I", 9, "INCOMPRIS").
dico("I", 9, "INCONFORT").
dico("I", 9, "INCONGRUE").
dico("I", 9, "INCONGRUS").
dico("I", 9, "INCONNUES").
dico("I", 9, "INCONSOLE").
dico("I", 9, "INCORPORA").
dico("I", 9, "INCORPORE").
dico("I", 9, "INCORRECT").
dico("I", 9, "INCOTERMS").
dico("I", 9, "INCREDULE").
dico("I", 9, "INCREMENT").
dico("I", 9, "INCRIMINA").
dico("I", 9, "INCRIMINE").
dico("I", 9, "INCROYANT").
dico("I", 9, "INCRUSTAI").
dico("I", 9, "INCRUSTAS").
dico("I", 9, "INCRUSTAT").
dico("I", 9, "INCRUSTEE").
dico("I", 9, "INCRUSTER").
dico("I", 9, "INCRUSTES").
dico("I", 9, "INCRUSTEZ").
dico("I", 9, "INCUBAMES").
dico("I", 9, "INCUBASSE").
dico("I", 9, "INCUBATES").
dico("I", 9, "INCUBERAI").
dico("I", 9, "INCUBERAS").
dico("I", 9, "INCUBEREZ").
dico("I", 9, "INCUBIONS").
dico("I", 9, "INCULPAIS").
dico("I", 9, "INCULPAIT").
dico("I", 9, "INCULPANT").
dico("I", 9, "INCULPEES").
dico("I", 9, "INCULPENT").
dico("I", 9, "INCULPERA").
dico("I", 9, "INCULPIEZ").
dico("I", 9, "INCULPONS").
dico("I", 9, "INCULQUAI").
dico("I", 9, "INCULQUAS").
dico("I", 9, "INCULQUAT").
dico("I", 9, "INCULQUEE").
dico("I", 9, "INCULQUER").
dico("I", 9, "INCULQUES").
dico("I", 9, "INCULQUEZ").
dico("I", 9, "INCULTIVE").
dico("I", 9, "INCULTURE").
dico("I", 9, "INCUNABLE").
dico("I", 9, "INCURABLE").
dico("I", 9, "INCURIEUX").
dico("I", 9, "INCURSION").
dico("I", 9, "INCURVAIS").
dico("I", 9, "INCURVAIT").
dico("I", 9, "INCURVANT").
dico("I", 9, "INCURVEES").
dico("I", 9, "INCURVENT").
dico("I", 9, "INCURVERA").
dico("I", 9, "INCURVIEZ").
dico("I", 9, "INCURVONS").
dico("I", 9, "INDAGUAIS").
dico("I", 9, "INDAGUAIT").
dico("I", 9, "INDAGUANT").
dico("I", 9, "INDAGUENT").
dico("I", 9, "INDAGUERA").
dico("I", 9, "INDAGUIEZ").
dico("I", 9, "INDAGUONS").
dico("I", 9, "INDATABLE").
dico("I", 9, "INDECENCE").
dico("I", 9, "INDECENTE").
dico("I", 9, "INDECENTS").
dico("I", 9, "INDECISES").
dico("I", 9, "INDEFINIE").
dico("I", 9, "INDEFINIS").
dico("I", 9, "INDELICAT").
dico("I", 9, "INDEMNISA").
dico("I", 9, "INDEMNISE").
dico("I", 9, "INDEMNITE").
dico("I", 9, "INDENTAIS").
dico("I", 9, "INDENTAIT").
dico("I", 9, "INDENTANT").
dico("I", 9, "INDENTEES").
dico("I", 9, "INDENTENT").
dico("I", 9, "INDENTERA").
dico("I", 9, "INDENTIEZ").
dico("I", 9, "INDENTONS").
dico("I", 9, "INDEXABLE").
dico("I", 9, "INDEXAGES").
dico("I", 9, "INDEXAMES").
dico("I", 9, "INDEXASSE").
dico("I", 9, "INDEXATES").
dico("I", 9, "INDEXERAI").
dico("I", 9, "INDEXERAS").
dico("I", 9, "INDEXEREZ").
dico("I", 9, "INDEXEURS").
dico("I", 9, "INDEXEUSE").
dico("I", 9, "INDEXIONS").
dico("I", 9, "INDICAMES").
dico("I", 9, "INDICASSE").
dico("I", 9, "INDICATES").
dico("I", 9, "INDICATIF").
dico("I", 9, "INDICERAI").
dico("I", 9, "INDICERAS").
dico("I", 9, "INDICEREZ").
dico("I", 9, "INDICIBLE").
dico("I", 9, "INDICIELS").
dico("I", 9, "INDICIONS").
dico("I", 9, "INDICTION").
dico("I", 9, "INDIENNES").
dico("I", 9, "INDIFFERA").
dico("I", 9, "INDIFFERE").
dico("I", 9, "INDIGENAT").
dico("I", 9, "INDIGENCE").
dico("I", 9, "INDIGENES").
dico("I", 9, "INDIGENTE").
dico("I", 9, "INDIGENTS").
dico("I", 9, "INDIGESTE").
dico("I", 9, "INDIGETES").
dico("I", 9, "INDIGNAIS").
dico("I", 9, "INDIGNAIT").
dico("I", 9, "INDIGNANT").
dico("I", 9, "INDIGNEES").
dico("I", 9, "INDIGNENT").
dico("I", 9, "INDIGNERA").
dico("I", 9, "INDIGNIEZ").
dico("I", 9, "INDIGNITE").
dico("I", 9, "INDIGNONS").
dico("I", 9, "INDIQUAIS").
dico("I", 9, "INDIQUAIT").
dico("I", 9, "INDIQUANT").
dico("I", 9, "INDIQUEES").
dico("I", 9, "INDIQUENT").
dico("I", 9, "INDIQUERA").
dico("I", 9, "INDIQUIEZ").
dico("I", 9, "INDIQUONS").
dico("I", 9, "INDIRECTE").
dico("I", 9, "INDIRECTS").
dico("I", 9, "INDISCRET").
dico("I", 9, "INDISCUTE").
dico("I", 9, "INDISPOSA").
dico("I", 9, "INDISPOSE").
dico("I", 9, "INDIVIDUS").
dico("I", 9, "INDIVISES").
dico("I", 9, "INDOCILES").
dico("I", 9, "INDOLENCE").
dico("I", 9, "INDOLENTE").
dico("I", 9, "INDOLENTS").
dico("I", 9, "INDOLORES").
dico("I", 9, "INDOMPTEE").
dico("I", 9, "INDOMPTES").
dico("I", 9, "INDRIENNE").
dico("I", 9, "INDUCTEUR").
dico("I", 9, "INDUCTIFS").
dico("I", 9, "INDUCTION").
dico("I", 9, "INDUCTIVE").
dico("I", 9, "INDUIRAIS").
dico("I", 9, "INDUIRAIT").
dico("I", 9, "INDUIRIEZ").
dico("I", 9, "INDUIRONS").
dico("I", 9, "INDUIRONT").
dico("I", 9, "INDUISAIS").
dico("I", 9, "INDUISAIT").
dico("I", 9, "INDUISANT").
dico("I", 9, "INDUISENT").
dico("I", 9, "INDUISIEZ").
dico("I", 9, "INDUISONS").
dico("I", 9, "INDULGENT").
dico("I", 9, "INDULINES").
dico("I", 9, "INDURAMES").
dico("I", 9, "INDURASSE").
dico("I", 9, "INDURATES").
dico("I", 9, "INDURERAI").
dico("I", 9, "INDURERAS").
dico("I", 9, "INDUREREZ").
dico("I", 9, "INDURIONS").
dico("I", 9, "INDUSTRIE").
dico("I", 9, "INDUVIEES").
dico("I", 9, "INECOUTEE").
dico("I", 9, "INECOUTES").
dico("I", 9, "INEFFABLE").
dico("I", 9, "INEGALEES").
dico("I", 9, "INEGALITE").
dico("I", 9, "INELEGANT").
dico("I", 9, "INEMPLOIS").
dico("I", 9, "INEMPLOYE").
dico("I", 9, "INENTAMEE").
dico("I", 9, "INENTAMES").
dico("I", 9, "INEPROUVE").
dico("I", 9, "INEPUISEE").
dico("I", 9, "INEPUISES").
dico("I", 9, "INERTAGES").
dico("I", 9, "INERTAMES").
dico("I", 9, "INERTASSE").
dico("I", 9, "INERTATES").
dico("I", 9, "INERTERAI").
dico("I", 9, "INERTERAS").
dico("I", 9, "INERTEREZ").
dico("I", 9, "INERTIELS").
dico("I", 9, "INERTIONS").
dico("I", 9, "INESPEREE").
dico("I", 9, "INESPERES").
dico("I", 9, "INETENDUE").
dico("I", 9, "INETENDUS").
dico("I", 9, "INEXACTES").
dico("I", 9, "INEXAUCEE").
dico("I", 9, "INEXAUCES").
dico("I", 9, "INEXECUTE").
dico("I", 9, "INEXERCEE").
dico("I", 9, "INEXERCES").
dico("I", 9, "INEXPERTE").
dico("I", 9, "INEXPERTS").
dico("I", 9, "INEXPIEES").
dico("I", 9, "INEXPLORE").
dico("I", 9, "INEXPRIME").
dico("I", 9, "INFAMANTE").
dico("I", 9, "INFAMANTS").
dico("I", 9, "INFANTILE").
dico("I", 9, "INFARCIES").
dico("I", 9, "INFARCIRA").
dico("I", 9, "INFARCTUS").
dico("I", 9, "INFATUAIS").
dico("I", 9, "INFATUAIT").
dico("I", 9, "INFATUANT").
dico("I", 9, "INFATUEES").
dico("I", 9, "INFATUENT").
dico("I", 9, "INFATUERA").
dico("I", 9, "INFATUIEZ").
dico("I", 9, "INFATUONS").
dico("I", 9, "INFECONDE").
dico("I", 9, "INFECONDS").
dico("I", 9, "INFECTAIS").
dico("I", 9, "INFECTAIT").
dico("I", 9, "INFECTANT").
dico("I", 9, "INFECTEES").
dico("I", 9, "INFECTENT").
dico("I", 9, "INFECTERA").
dico("I", 9, "INFECTIEZ").
dico("I", 9, "INFECTION").
dico("I", 9, "INFECTONS").
dico("I", 9, "INFEODAIS").
dico("I", 9, "INFEODAIT").
dico("I", 9, "INFEODANT").
dico("I", 9, "INFEODEES").
dico("I", 9, "INFEODENT").
dico("I", 9, "INFEODERA").
dico("I", 9, "INFEODIEZ").
dico("I", 9, "INFEODONS").
dico("I", 9, "INFERAMES").
dico("I", 9, "INFERASSE").
dico("I", 9, "INFERATES").
dico("I", 9, "INFERENCE").
dico("I", 9, "INFERERAI").
dico("I", 9, "INFERERAS").
dico("I", 9, "INFEREREZ").
dico("I", 9, "INFERIEUR").
dico("I", 9, "INFERIONS").
dico("I", 9, "INFERNALE").
dico("I", 9, "INFERNAUX").
dico("I", 9, "INFERTILE").
dico("I", 9, "INFESTAIS").
dico("I", 9, "INFESTAIT").
dico("I", 9, "INFESTANT").
dico("I", 9, "INFESTEES").
dico("I", 9, "INFESTENT").
dico("I", 9, "INFESTERA").
dico("I", 9, "INFESTIEZ").
dico("I", 9, "INFESTONS").
dico("I", 9, "INFIBULAI").
dico("I", 9, "INFIBULAS").
dico("I", 9, "INFIBULAT").
dico("I", 9, "INFIBULEE").
dico("I", 9, "INFIBULER").
dico("I", 9, "INFIBULES").
dico("I", 9, "INFIBULEZ").
dico("I", 9, "INFICHUES").
dico("I", 9, "INFIDELES").
dico("I", 9, "INFILTRAI").
dico("I", 9, "INFILTRAS").
dico("I", 9, "INFILTRAT").
dico("I", 9, "INFILTREE").
dico("I", 9, "INFILTRER").
dico("I", 9, "INFILTRES").
dico("I", 9, "INFILTREZ").
dico("I", 9, "INFINITES").
dico("I", 9, "INFINITIF").
dico("I", 9, "INFIRMAIS").
dico("I", 9, "INFIRMAIT").
dico("I", 9, "INFIRMANT").
dico("I", 9, "INFIRMEES").
dico("I", 9, "INFIRMENT").
dico("I", 9, "INFIRMERA").
dico("I", 9, "INFIRMIER").
dico("I", 9, "INFIRMIEZ").
dico("I", 9, "INFIRMITE").
dico("I", 9, "INFIRMONS").
dico("I", 9, "INFLATION").
dico("I", 9, "INFLECHIE").
dico("I", 9, "INFLECHIR").
dico("I", 9, "INFLECHIS").
dico("I", 9, "INFLECHIT").
dico("I", 9, "INFLEXION").
dico("I", 9, "INFLIGEAI").
dico("I", 9, "INFLIGEAS").
dico("I", 9, "INFLIGEAT").
dico("I", 9, "INFLIGEES").
dico("I", 9, "INFLIGENT").
dico("I", 9, "INFLIGERA").
dico("I", 9, "INFLIGIEZ").
dico("I", 9, "INFLUAMES").
dico("I", 9, "INFLUASSE").
dico("I", 9, "INFLUATES").
dico("I", 9, "INFLUENCA").
dico("I", 9, "INFLUENCE").
dico("I", 9, "INFLUENTE").
dico("I", 9, "INFLUENTS").
dico("I", 9, "INFLUENZA").
dico("I", 9, "INFLUERAI").
dico("I", 9, "INFLUERAS").
dico("I", 9, "INFLUEREZ").
dico("I", 9, "INFLUIONS").
dico("I", 9, "INFONDEES").
dico("I", 9, "INFORMAIS").
dico("I", 9, "INFORMAIT").
dico("I", 9, "INFORMANT").
dico("I", 9, "INFORMEES").
dico("I", 9, "INFORMELS").
dico("I", 9, "INFORMENT").
dico("I", 9, "INFORMERA").
dico("I", 9, "INFORMIEZ").
dico("I", 9, "INFORMONS").
dico("I", 9, "INFORMULE").
dico("I", 9, "INFOROUTE").
dico("I", 9, "INFORTUNE").
dico("I", 9, "INFOUTUES").
dico("I", 9, "INFRADIEN").
dico("I", 9, "INFRASONS").
dico("I", 9, "INFUMABLE").
dico("I", 9, "INFUSAMES").
dico("I", 9, "INFUSASSE").
dico("I", 9, "INFUSATES").
dico("I", 9, "INFUSERAI").
dico("I", 9, "INFUSERAS").
dico("I", 9, "INFUSEREZ").
dico("I", 9, "INFUSETTE").
dico("I", 9, "INFUSIBLE").
dico("I", 9, "INFUSIONS").
dico("I", 9, "INFUSOIRE").
dico("I", 9, "INGELIVES").
dico("I", 9, "INGENIAIS").
dico("I", 9, "INGENIAIT").
dico("I", 9, "INGENIANT").
dico("I", 9, "INGENIEES").
dico("I", 9, "INGENIENT").
dico("I", 9, "INGENIERA").
dico("I", 9, "INGENIEUR").
dico("I", 9, "INGENIEUX").
dico("I", 9, "INGENIIEZ").
dico("I", 9, "INGENIONS").
dico("I", 9, "INGENUITE").
dico("I", 9, "INGERABLE").
dico("I", 9, "INGERAMES").
dico("I", 9, "INGERASSE").
dico("I", 9, "INGERATES").
dico("I", 9, "INGERENCE").
dico("I", 9, "INGERERAI").
dico("I", 9, "INGERERAS").
dico("I", 9, "INGEREREZ").
dico("I", 9, "INGERIONS").
dico("I", 9, "INGESTION").
dico("I", 9, "INGRESQUE").
dico("I", 9, "INGRISMES").
dico("I", 9, "INGRISTES").
dico("I", 9, "INGUINALE").
dico("I", 9, "INGUINAUX").
dico("I", 9, "INGURGITA").
dico("I", 9, "INGURGITE").
dico("I", 9, "INHABILES").
dico("I", 9, "INHABITEE").
dico("I", 9, "INHABITES").
dico("I", 9, "INHABITUE").
dico("I", 9, "INHALAMES").
dico("I", 9, "INHALASSE").
dico("I", 9, "INHALATES").
dico("I", 9, "INHALERAI").
dico("I", 9, "INHALERAS").
dico("I", 9, "INHALEREZ").
dico("I", 9, "INHALIONS").
dico("I", 9, "INHERENCE").
dico("I", 9, "INHERENTE").
dico("I", 9, "INHERENTS").
dico("I", 9, "INHIBAMES").
dico("I", 9, "INHIBASSE").
dico("I", 9, "INHIBATES").
dico("I", 9, "INHIBERAI").
dico("I", 9, "INHIBERAS").
dico("I", 9, "INHIBEREZ").
dico("I", 9, "INHIBIONS").
dico("I", 9, "INHIBITIF").
dico("I", 9, "INHUMAINE").
dico("I", 9, "INHUMAINS").
dico("I", 9, "INHUMAMES").
dico("I", 9, "INHUMASSE").
dico("I", 9, "INHUMATES").
dico("I", 9, "INHUMERAI").
dico("I", 9, "INHUMERAS").
dico("I", 9, "INHUMEREZ").
dico("I", 9, "INHUMIONS").
dico("I", 9, "INIMITEES").
dico("I", 9, "INIMITIES").
dico("I", 9, "ININTERET").
dico("I", 9, "INIQUITES").
dico("I", 9, "INITIALAI").
dico("I", 9, "INITIALAS").
dico("I", 9, "INITIALAT").
dico("I", 9, "INITIALEE").
dico("I", 9, "INITIALER").
dico("I", 9, "INITIALES").
dico("I", 9, "INITIALEZ").
dico("I", 9, "INITIAMES").
dico("I", 9, "INITIASSE").
dico("I", 9, "INITIATES").
dico("I", 9, "INITIERAI").
dico("I", 9, "INITIERAS").
dico("I", 9, "INITIEREZ").
dico("I", 9, "INITIIONS").
dico("I", 9, "INJECTAIS").
dico("I", 9, "INJECTAIT").
dico("I", 9, "INJECTANT").
dico("I", 9, "INJECTEES").
dico("I", 9, "INJECTENT").
dico("I", 9, "INJECTERA").
dico("I", 9, "INJECTEUR").
dico("I", 9, "INJECTIEZ").
dico("I", 9, "INJECTIFS").
dico("I", 9, "INJECTION").
dico("I", 9, "INJECTIVE").
dico("I", 9, "INJECTONS").
dico("I", 9, "INJONCTIF").
dico("I", 9, "INJOUABLE").
dico("I", 9, "INJURIAIS").
dico("I", 9, "INJURIAIT").
dico("I", 9, "INJURIANT").
dico("I", 9, "INJURIEES").
dico("I", 9, "INJURIENT").
dico("I", 9, "INJURIERA").
dico("I", 9, "INJURIEUX").
dico("I", 9, "INJURIIEZ").
dico("I", 9, "INJURIONS").
dico("I", 9, "INJUSTICE").
dico("I", 9, "INLANDSIS").
dico("I", 9, "INNEISMES").
dico("I", 9, "INNEISTES").
dico("I", 9, "INNERVAIS").
dico("I", 9, "INNERVAIT").
dico("I", 9, "INNERVANT").
dico("I", 9, "INNERVEES").
dico("I", 9, "INNERVENT").
dico("I", 9, "INNERVERA").
dico("I", 9, "INNERVIEZ").
dico("I", 9, "INNERVONS").
dico("I", 9, "INNOCENCE").
dico("I", 9, "INNOCENTA").
dico("I", 9, "INNOCENTE").
dico("I", 9, "INNOCENTS").
dico("I", 9, "INNOCUITE").
dico("I", 9, "INNOMINEE").
dico("I", 9, "INNOMINES").
dico("I", 9, "INNOMMEES").
dico("I", 9, "INNOVAMES").
dico("I", 9, "INNOVANTE").
dico("I", 9, "INNOVANTS").
dico("I", 9, "INNOVASSE").
dico("I", 9, "INNOVATES").
dico("I", 9, "INNOVERAI").
dico("I", 9, "INNOVERAS").
dico("I", 9, "INNOVEREZ").
dico("I", 9, "INNOVIONS").
dico("I", 9, "INOBSERVE").
dico("I", 9, "INOCCUPEE").
dico("I", 9, "INOCCUPES").
dico("I", 9, "INOCULAIS").
dico("I", 9, "INOCULAIT").
dico("I", 9, "INOCULANT").
dico("I", 9, "INOCULEES").
dico("I", 9, "INOCULENT").
dico("I", 9, "INOCULERA").
dico("I", 9, "INOCULIEZ").
dico("I", 9, "INOCULONS").
dico("I", 9, "INOCULUMS").
dico("I", 9, "INONDABLE").
dico("I", 9, "INONDAMES").
dico("I", 9, "INONDASSE").
dico("I", 9, "INONDATES").
dico("I", 9, "INONDERAI").
dico("I", 9, "INONDERAS").
dico("I", 9, "INONDEREZ").
dico("I", 9, "INONDIONS").
dico("I", 9, "INOPERANT").
dico("I", 9, "INOPINEES").
dico("I", 9, "INOTROPES").
dico("I", 9, "INQUIETAI").
dico("I", 9, "INQUIETAS").
dico("I", 9, "INQUIETAT").
dico("I", 9, "INQUIETEE").
dico("I", 9, "INQUIETER").
dico("I", 9, "INQUIETES").
dico("I", 9, "INQUIETEZ").
dico("I", 9, "INQUILINE").
dico("I", 9, "INQUILINS").
dico("I", 9, "INRATABLE").
dico("I", 9, "INRAYABLE").
dico("I", 9, "INSALUBRE").
dico("I", 9, "INSANITES").
dico("I", 9, "INSATUREE").
dico("I", 9, "INSATURES").
dico("I", 9, "INSCRIRAI").
dico("I", 9, "INSCRIRAS").
dico("I", 9, "INSCRIREZ").
dico("I", 9, "INSCRITES").
dico("I", 9, "INSCRIVES").
dico("I", 9, "INSCRIVEZ").
dico("I", 9, "INSCRIVIS").
dico("I", 9, "INSCRIVIT").
dico("I", 9, "INSCULPAI").
dico("I", 9, "INSCULPAS").
dico("I", 9, "INSCULPAT").
dico("I", 9, "INSCULPEE").
dico("I", 9, "INSCULPER").
dico("I", 9, "INSCULPES").
dico("I", 9, "INSCULPEZ").
dico("I", 9, "INSECABLE").
dico("I", 9, "INSELBERG").
dico("I", 9, "INSEMINAI").
dico("I", 9, "INSEMINAS").
dico("I", 9, "INSEMINAT").
dico("I", 9, "INSEMINEE").
dico("I", 9, "INSEMINER").
dico("I", 9, "INSEMINES").
dico("I", 9, "INSEMINEZ").
dico("I", 9, "INSENSEES").
dico("I", 9, "INSERABLE").
dico("I", 9, "INSERAMES").
dico("I", 9, "INSERASSE").
dico("I", 9, "INSERATES").
dico("I", 9, "INSERERAI").
dico("I", 9, "INSERERAS").
dico("I", 9, "INSEREREZ").
dico("I", 9, "INSERIONS").
dico("I", 9, "INSERTION").
dico("I", 9, "INSIDIEUX").
dico("I", 9, "INSINCERE").
dico("I", 9, "INSINUAIS").
dico("I", 9, "INSINUAIT").
dico("I", 9, "INSINUANT").
dico("I", 9, "INSINUEES").
dico("I", 9, "INSINUENT").
dico("I", 9, "INSINUERA").
dico("I", 9, "INSINUIEZ").
dico("I", 9, "INSINUONS").
dico("I", 9, "INSIPIDES").
dico("I", 9, "INSISTAIS").
dico("I", 9, "INSISTAIT").
dico("I", 9, "INSISTANT").
dico("I", 9, "INSISTENT").
dico("I", 9, "INSISTERA").
dico("I", 9, "INSISTIEZ").
dico("I", 9, "INSISTONS").
dico("I", 9, "INSOLAMES").
dico("I", 9, "INSOLASSE").
dico("I", 9, "INSOLATES").
dico("I", 9, "INSOLENCE").
dico("I", 9, "INSOLENTE").
dico("I", 9, "INSOLENTS").
dico("I", 9, "INSOLERAI").
dico("I", 9, "INSOLERAS").
dico("I", 9, "INSOLEREZ").
dico("I", 9, "INSOLIONS").
dico("I", 9, "INSOLITES").
dico("I", 9, "INSOLUBLE").
dico("I", 9, "INSOMNIES").
dico("I", 9, "INSONORES").
dico("I", 9, "INSOUMISE").
dico("I", 9, "INSPECTAI").
dico("I", 9, "INSPECTAS").
dico("I", 9, "INSPECTAT").
dico("I", 9, "INSPECTEE").
dico("I", 9, "INSPECTER").
dico("I", 9, "INSPECTES").
dico("I", 9, "INSPECTEZ").
dico("I", 9, "INSPIRAIS").
dico("I", 9, "INSPIRAIT").
dico("I", 9, "INSPIRANT").
dico("I", 9, "INSPIREES").
dico("I", 9, "INSPIRENT").
dico("I", 9, "INSPIRERA").
dico("I", 9, "INSPIRIEZ").
dico("I", 9, "INSPIRONS").
dico("I", 9, "INSTABLES").
dico("I", 9, "INSTALLAI").
dico("I", 9, "INSTALLAS").
dico("I", 9, "INSTALLAT").
dico("I", 9, "INSTALLEE").
dico("I", 9, "INSTALLER").
dico("I", 9, "INSTALLES").
dico("I", 9, "INSTALLEZ").
dico("I", 9, "INSTANCES").
dico("I", 9, "INSTANTES").
dico("I", 9, "INSTAURAI").
dico("I", 9, "INSTAURAS").
dico("I", 9, "INSTAURAT").
dico("I", 9, "INSTAUREE").
dico("I", 9, "INSTAURER").
dico("I", 9, "INSTAURES").
dico("I", 9, "INSTAUREZ").
dico("I", 9, "INSTIGUAI").
dico("I", 9, "INSTIGUAS").
dico("I", 9, "INSTIGUAT").
dico("I", 9, "INSTIGUEE").
dico("I", 9, "INSTIGUER").
dico("I", 9, "INSTIGUES").
dico("I", 9, "INSTIGUEZ").
dico("I", 9, "INSTILLAI").
dico("I", 9, "INSTILLAS").
dico("I", 9, "INSTILLAT").
dico("I", 9, "INSTILLEE").
dico("I", 9, "INSTILLER").
dico("I", 9, "INSTILLES").
dico("I", 9, "INSTILLEZ").
dico("I", 9, "INSTINCTS").
dico("I", 9, "INSTITUAI").
dico("I", 9, "INSTITUAS").
dico("I", 9, "INSTITUAT").
dico("I", 9, "INSTITUEE").
dico("I", 9, "INSTITUER").
dico("I", 9, "INSTITUES").
dico("I", 9, "INSTITUEZ").
dico("I", 9, "INSTITUTS").
dico("I", 9, "INSTRUIRA").
dico("I", 9, "INSTRUIRE").
dico("I", 9, "INSTRUISE").
dico("I", 9, "INSTRUITE").
dico("I", 9, "INSTRUITS").
dico("I", 9, "INSUFFLAI").
dico("I", 9, "INSUFFLAS").
dico("I", 9, "INSUFFLAT").
dico("I", 9, "INSUFFLEE").
dico("I", 9, "INSUFFLER").
dico("I", 9, "INSUFFLES").
dico("I", 9, "INSUFFLEZ").
dico("I", 9, "INSULAIRE").
dico("I", 9, "INSULINES").
dico("I", 9, "INSULTAIS").
dico("I", 9, "INSULTAIT").
dico("I", 9, "INSULTANT").
dico("I", 9, "INSULTEES").
dico("I", 9, "INSULTENT").
dico("I", 9, "INSULTERA").
dico("I", 9, "INSULTEUR").
dico("I", 9, "INSULTIEZ").
dico("I", 9, "INSULTONS").
dico("I", 9, "INSURGEAI").
dico("I", 9, "INSURGEAS").
dico("I", 9, "INSURGEAT").
dico("I", 9, "INSURGEES").
dico("I", 9, "INSURGENT").
dico("I", 9, "INSURGERA").
dico("I", 9, "INSURGIEZ").
dico("I", 9, "INTACTILE").
dico("I", 9, "INTAILLAI").
dico("I", 9, "INTAILLAS").
dico("I", 9, "INTAILLAT").
dico("I", 9, "INTAILLEE").
dico("I", 9, "INTAILLER").
dico("I", 9, "INTAILLES").
dico("I", 9, "INTAILLEZ").
dico("I", 9, "INTEGRAIS").
dico("I", 9, "INTEGRAIT").
dico("I", 9, "INTEGRALE").
dico("I", 9, "INTEGRANT").
dico("I", 9, "INTEGRAUX").
dico("I", 9, "INTEGREES").
dico("I", 9, "INTEGRENT").
dico("I", 9, "INTEGRERA").
dico("I", 9, "INTEGRIEZ").
dico("I", 9, "INTEGRITE").
dico("I", 9, "INTEGRONS").
dico("I", 9, "INTELLECT").
dico("I", 9, "INTENABLE").
dico("I", 9, "INTENDANT").
dico("I", 9, "INTENSIFS").
dico("I", 9, "INTENSION").
dico("I", 9, "INTENSITE").
dico("I", 9, "INTENSIVE").
dico("I", 9, "INTENTAIS").
dico("I", 9, "INTENTAIT").
dico("I", 9, "INTENTANT").
dico("I", 9, "INTENTEES").
dico("I", 9, "INTENTENT").
dico("I", 9, "INTENTERA").
dico("I", 9, "INTENTIEZ").
dico("I", 9, "INTENTION").
dico("I", 9, "INTENTONS").
dico("I", 9, "INTERAGIR").
dico("I", 9, "INTERAGIS").
dico("I", 9, "INTERAGIT").
dico("I", 9, "INTERCALA").
dico("I", 9, "INTERCALE").
dico("I", 9, "INTERCEDA").
dico("I", 9, "INTERCEDE").
dico("I", 9, "INTERDIRA").
dico("I", 9, "INTERDIRE").
dico("I", 9, "INTERDISE").
dico("I", 9, "INTERDITE").
dico("I", 9, "INTERDITS").
dico("I", 9, "INTERESSA").
dico("I", 9, "INTERESSE").
dico("I", 9, "INTERFACE").
dico("I", 9, "INTERFERA").
dico("I", 9, "INTERFERE").
dico("I", 9, "INTERIEUR").
dico("I", 9, "INTERJETA").
dico("I", 9, "INTERJETE").
dico("I", 9, "INTERLOCK").
dico("I", 9, "INTERLOPE").
dico("I", 9, "INTERLUDE").
dico("I", 9, "INTERMEDE").
dico("I", 9, "INTERNAIS").
dico("I", 9, "INTERNAIT").
dico("I", 9, "INTERNANT").
dico("I", 9, "INTERNATS").
dico("I", 9, "INTERNEES").
dico("I", 9, "INTERNENT").
dico("I", 9, "INTERNERA").
dico("I", 9, "INTERNETS").
dico("I", 9, "INTERNIEZ").
dico("I", 9, "INTERNONS").
dico("I", 9, "INTERPOLA").
dico("I", 9, "INTERPOLE").
dico("I", 9, "INTERPOSA").
dico("I", 9, "INTERPOSE").
dico("I", 9, "INTERROGE").
dico("I", 9, "INTERROIS").
dico("I", 9, "INTERVENU").
dico("I", 9, "INTERVIEW").
dico("I", 9, "INTERVINS").
dico("I", 9, "INTERVINT").
dico("I", 9, "INTERZONE").
dico("I", 9, "INTESTATS").
dico("I", 9, "INTESTINE").
dico("I", 9, "INTESTINS").
dico("I", 9, "INTIFADAS").
dico("I", 9, "INTIMAMES").
dico("I", 9, "INTIMASSE").
dico("I", 9, "INTIMATES").
dico("I", 9, "INTIMERAI").
dico("I", 9, "INTIMERAS").
dico("I", 9, "INTIMEREZ").
dico("I", 9, "INTIMIDAI").
dico("I", 9, "INTIMIDAS").
dico("I", 9, "INTIMIDAT").
dico("I", 9, "INTIMIDEE").
dico("I", 9, "INTIMIDER").
dico("I", 9, "INTIMIDES").
dico("I", 9, "INTIMIDEZ").
dico("I", 9, "INTIMIONS").
dico("I", 9, "INTIMISME").
dico("I", 9, "INTIMISTE").
dico("I", 9, "INTIMITES").
dico("I", 9, "INTITULAI").
dico("I", 9, "INTITULAS").
dico("I", 9, "INTITULAT").
dico("I", 9, "INTITULEE").
dico("I", 9, "INTITULER").
dico("I", 9, "INTITULES").
dico("I", 9, "INTITULEZ").
dico("I", 9, "INTONATIF").
dico("I", 9, "INTOUCHEE").
dico("I", 9, "INTOUCHES").
dico("I", 9, "INTOXIQUA").
dico("I", 9, "INTOXIQUE").
dico("I", 9, "INTRANETS").
dico("I", 9, "INTREPIDE").
dico("I", 9, "INTRIGANT").
dico("I", 9, "INTRIGUAI").
dico("I", 9, "INTRIGUAS").
dico("I", 9, "INTRIGUAT").
dico("I", 9, "INTRIGUEE").
dico("I", 9, "INTRIGUER").
dico("I", 9, "INTRIGUES").
dico("I", 9, "INTRIGUEZ").
dico("I", 9, "INTRIQUAI").
dico("I", 9, "INTRIQUAS").
dico("I", 9, "INTRIQUAT").
dico("I", 9, "INTRIQUEE").
dico("I", 9, "INTRIQUER").
dico("I", 9, "INTRIQUES").
dico("I", 9, "INTRIQUEZ").
dico("I", 9, "INTRODUIS").
dico("I", 9, "INTRODUIT").
dico("I", 9, "INTRONISA").
dico("I", 9, "INTRONISE").
dico("I", 9, "INTRORSES").
dico("I", 9, "INTRUSIFS").
dico("I", 9, "INTRUSION").
dico("I", 9, "INTRUSIVE").
dico("I", 9, "INTUBAMES").
dico("I", 9, "INTUBASSE").
dico("I", 9, "INTUBATES").
dico("I", 9, "INTUBERAI").
dico("I", 9, "INTUBERAS").
dico("I", 9, "INTUBEREZ").
dico("I", 9, "INTUBIONS").
dico("I", 9, "INTUITAIS").
dico("I", 9, "INTUITAIT").
dico("I", 9, "INTUITANT").
dico("I", 9, "INTUITEES").
dico("I", 9, "INTUITENT").
dico("I", 9, "INTUITERA").
dico("I", 9, "INTUITIEZ").
dico("I", 9, "INTUITIFS").
dico("I", 9, "INTUITION").
dico("I", 9, "INTUITIVE").
dico("I", 9, "INTUITONS").
dico("I", 9, "INUKTITUT").
dico("I", 9, "INUSABLES").
dico("I", 9, "INUSITEES").
dico("I", 9, "INUSUELLE").
dico("I", 9, "INUTILISE").
dico("I", 9, "INUTILITE").
dico("I", 9, "INVAGINAI").
dico("I", 9, "INVAGINAS").
dico("I", 9, "INVAGINAT").
dico("I", 9, "INVAGINEE").
dico("I", 9, "INVAGINER").
dico("I", 9, "INVAGINES").
dico("I", 9, "INVAGINEZ").
dico("I", 9, "INVAINCUE").
dico("I", 9, "INVAINCUS").
dico("I", 9, "INVALIDAI").
dico("I", 9, "INVALIDAS").
dico("I", 9, "INVALIDAT").
dico("I", 9, "INVALIDEE").
dico("I", 9, "INVALIDER").
dico("I", 9, "INVALIDES").
dico("I", 9, "INVALIDEZ").
dico("I", 9, "INVARIANT").
dico("I", 9, "INVASIONS").
dico("I", 9, "INVASIVES").
dico("I", 9, "INVECTIVA").
dico("I", 9, "INVECTIVE").
dico("I", 9, "INVENDUES").
dico("I", 9, "INVENGEES").
dico("I", 9, "INVENTAIS").
dico("I", 9, "INVENTAIT").
dico("I", 9, "INVENTANT").
dico("I", 9, "INVENTEES").
dico("I", 9, "INVENTENT").
dico("I", 9, "INVENTERA").
dico("I", 9, "INVENTEUR").
dico("I", 9, "INVENTIEZ").
dico("I", 9, "INVENTIFS").
dico("I", 9, "INVENTION").
dico("I", 9, "INVENTIVE").
dico("I", 9, "INVENTONS").
dico("I", 9, "INVERIFIE").
dico("I", 9, "INVERSAIS").
dico("I", 9, "INVERSAIT").
dico("I", 9, "INVERSANT").
dico("I", 9, "INVERSEES").
dico("I", 9, "INVERSENT").
dico("I", 9, "INVERSERA").
dico("I", 9, "INVERSEUR").
dico("I", 9, "INVERSIEZ").
dico("I", 9, "INVERSIFS").
dico("I", 9, "INVERSION").
dico("I", 9, "INVERSIVE").
dico("I", 9, "INVERSONS").
dico("I", 9, "INVERTASE").
dico("I", 9, "INVERTIES").
dico("I", 9, "INVERTINE").
dico("I", 9, "INVERTIRA").
dico("I", 9, "INVESTIES").
dico("I", 9, "INVESTIRA").
dico("I", 9, "INVETERAI").
dico("I", 9, "INVETERAS").
dico("I", 9, "INVETERAT").
dico("I", 9, "INVETEREE").
dico("I", 9, "INVETERER").
dico("I", 9, "INVETERES").
dico("I", 9, "INVETEREZ").
dico("I", 9, "INVIOLEES").
dico("I", 9, "INVISIBLE").
dico("I", 9, "INVITAMES").
dico("I", 9, "INVITANTE").
dico("I", 9, "INVITANTS").
dico("I", 9, "INVITASSE").
dico("I", 9, "INVITATES").
dico("I", 9, "INVITERAI").
dico("I", 9, "INVITERAS").
dico("I", 9, "INVITEREZ").
dico("I", 9, "INVITEURS").
dico("I", 9, "INVITEUSE").
dico("I", 9, "INVITIONS").
dico("I", 9, "INVIVABLE").
dico("I", 9, "INVOLUCRE").
dico("I", 9, "INVOLUTEE").
dico("I", 9, "INVOLUTES").
dico("I", 9, "INVOLUTIF").
dico("I", 9, "INVOQUAIS").
dico("I", 9, "INVOQUAIT").
dico("I", 9, "INVOQUANT").
dico("I", 9, "INVOQUEES").
dico("I", 9, "INVOQUENT").
dico("I", 9, "INVOQUERA").
dico("I", 9, "INVOQUIEZ").
dico("I", 9, "INVOQUONS").
dico("I", 9, "IODASSENT").
dico("I", 9, "IODASSIEZ").
dico("I", 9, "IODERIONS").
dico("I", 9, "IODLAIENT").
dico("I", 9, "IODLASSES").
dico("I", 9, "IODLERAIS").
dico("I", 9, "IODLERAIT").
dico("I", 9, "IODLERENT").
dico("I", 9, "IODLERIEZ").
dico("I", 9, "IODLERONS").
dico("I", 9, "IODLERONT").
dico("I", 9, "IODOFORME").
dico("I", 9, "IONIENNES").
dico("I", 9, "IONISAMES").
dico("I", 9, "IONISANTE").
dico("I", 9, "IONISANTS").
dico("I", 9, "IONISASSE").
dico("I", 9, "IONISATES").
dico("I", 9, "IONISERAI").
dico("I", 9, "IONISERAS").
dico("I", 9, "IONISEREZ").
dico("I", 9, "IONISIONS").
dico("I", 9, "IOTACISME").
dico("I", 9, "IOULAIENT").
dico("I", 9, "IOULASSES").
dico("I", 9, "IOULERAIS").
dico("I", 9, "IOULERAIT").
dico("I", 9, "IOULERENT").
dico("I", 9, "IOULERIEZ").
dico("I", 9, "IOULERONS").
dico("I", 9, "IOULERONT").
dico("I", 9, "IRAKIENNE").
dico("I", 9, "IRANIENNE").
dico("I", 9, "IRAQIENNE").
dico("I", 9, "IRAQUIENS").
dico("I", 9, "IRASCIBLE").
dico("I", 9, "IRENIQUES").
dico("I", 9, "IRENISMES").
dico("I", 9, "IRIDACEES").
dico("I", 9, "IRIDIENNE").
dico("I", 9, "IRISABLES").
dico("I", 9, "IRISAIENT").
dico("I", 9, "IRISASSES").
dico("I", 9, "IRISATION").
dico("I", 9, "IRISERAIS").
dico("I", 9, "IRISERAIT").
dico("I", 9, "IRISERENT").
dico("I", 9, "IRISERIEZ").
dico("I", 9, "IRISERONS").
dico("I", 9, "IRISERONT").
dico("I", 9, "IRLANDAIS").
dico("I", 9, "IRONIQUES").
dico("I", 9, "IRONISAIS").
dico("I", 9, "IRONISAIT").
dico("I", 9, "IRONISANT").
dico("I", 9, "IRONISENT").
dico("I", 9, "IRONISERA").
dico("I", 9, "IRONISIEZ").
dico("I", 9, "IRONISONS").
dico("I", 9, "IRONISTES").
dico("I", 9, "IROQUOIEN").
dico("I", 9, "IROQUOISE").
dico("I", 9, "IRRADIAIS").
dico("I", 9, "IRRADIAIT").
dico("I", 9, "IRRADIANT").
dico("I", 9, "IRRADIEES").
dico("I", 9, "IRRADIENT").
dico("I", 9, "IRRADIERA").
dico("I", 9, "IRRADIIEZ").
dico("I", 9, "IRRADIONS").
dico("I", 9, "IRREALISE").
dico("I", 9, "IRREALITE").
dico("I", 9, "IRREELLES").
dico("I", 9, "IRREFUTEE").
dico("I", 9, "IRREFUTES").
dico("I", 9, "IRRESOLUE").
dico("I", 9, "IRRESOLUS").
dico("I", 9, "IRRESPECT").
dico("I", 9, "IRRIGABLE").
dico("I", 9, "IRRIGUAIS").
dico("I", 9, "IRRIGUAIT").
dico("I", 9, "IRRIGUANT").
dico("I", 9, "IRRIGUEES").
dico("I", 9, "IRRIGUENT").
dico("I", 9, "IRRIGUERA").
dico("I", 9, "IRRIGUIEZ").
dico("I", 9, "IRRIGUONS").
dico("I", 9, "IRRITABLE").
dico("I", 9, "IRRITAMES").
dico("I", 9, "IRRITANTE").
dico("I", 9, "IRRITANTS").
dico("I", 9, "IRRITASSE").
dico("I", 9, "IRRITATES").
dico("I", 9, "IRRITATIF").
dico("I", 9, "IRRITERAI").
dico("I", 9, "IRRITERAS").
dico("I", 9, "IRRITEREZ").
dico("I", 9, "IRRITIONS").
dico("I", 9, "IRRUPTION").
dico("I", 9, "ISABELLES").
dico("I", 9, "ISARIENNE").
dico("I", 9, "ISCHEMIES").
dico("I", 9, "ISEROISES").
dico("I", 9, "ISLAMIQUE").
dico("I", 9, "ISLAMISAI").
dico("I", 9, "ISLAMISAS").
dico("I", 9, "ISLAMISAT").
dico("I", 9, "ISLAMISEE").
dico("I", 9, "ISLAMISER").
dico("I", 9, "ISLAMISES").
dico("I", 9, "ISLAMISEZ").
dico("I", 9, "ISLAMISME").
dico("I", 9, "ISLAMISTE").
dico("I", 9, "ISLANDAIS").
dico("I", 9, "ISMAELIEN").
dico("I", 9, "ISMAELITE").
dico("I", 9, "ISMAILIEN").
dico("I", 9, "ISOBATHES").
dico("I", 9, "ISOCARDES").
dico("I", 9, "ISOCARENE").
dico("I", 9, "ISOCHORES").
dico("I", 9, "ISOCHRONE").
dico("I", 9, "ISOCLINAL").
dico("I", 9, "ISOCLINES").
dico("I", 9, "ISODYNAME").
dico("I", 9, "ISOGAMIES").
dico("I", 9, "ISOGLOSSE").
dico("I", 9, "ISOGONALE").
dico("I", 9, "ISOGONAUX").
dico("I", 9, "ISOGREFFE").
dico("I", 9, "ISOHYETES").
dico("I", 9, "ISOHYPSES").
dico("I", 9, "ISOLABLES").
dico("I", 9, "ISOLAIENT").
dico("I", 9, "ISOLANTES").
dico("I", 9, "ISOLASSES").
dico("I", 9, "ISOLATEUR").
dico("I", 9, "ISOLATION").
dico("I", 9, "ISOLEMENT").
dico("I", 9, "ISOLERAIS").
dico("I", 9, "ISOLERAIT").
dico("I", 9, "ISOLERENT").
dico("I", 9, "ISOLERIEZ").
dico("I", 9, "ISOLERONS").
dico("I", 9, "ISOLERONT").
dico("I", 9, "ISOLOGUES").
dico("I", 9, "ISOMERASE").
dico("I", 9, "ISOMERIES").
dico("I", 9, "ISOMETRIE").
dico("I", 9, "ISOMORPHE").
dico("I", 9, "ISONOMIES").
dico("I", 9, "ISOOCTANE").
dico("I", 9, "ISOPHASES").
dico("I", 9, "ISOPRENES").
dico("I", 9, "ISOPTERES").
dico("I", 9, "ISOSEISTE").
dico("I", 9, "ISOSISTES").
dico("I", 9, "ISOSTASIE").
dico("I", 9, "ISOTHERME").
dico("I", 9, "ISOTONIES").
dico("I", 9, "ISOTOPIES").
dico("I", 9, "ISOTROPES").
dico("I", 9, "ISOTROPIE").
dico("I", 9, "ISRAELIEN").
dico("I", 9, "ISRAELITE").
dico("I", 9, "ISTHMIQUE").
dico("I", 9, "ISTREENNE").
dico("I", 9, "ITALIENNE").
dico("I", 9, "ITALIQUES").
dico("I", 9, "ITERAIENT").
dico("I", 9, "ITERASSES").
dico("I", 9, "ITERATIFS").
dico("I", 9, "ITERATION").
dico("I", 9, "ITERATIVE").
dico("I", 9, "ITERERAIS").
dico("I", 9, "ITERERAIT").
dico("I", 9, "ITERERENT").
dico("I", 9, "ITERERIEZ").
dico("I", 9, "ITERERONS").
dico("I", 9, "ITERERONT").
dico("I", 9, "ITINERANT").
dico("I", 9, "IVOIRERIE").
dico("I", 9, "IVOIRIENS").
dico("I", 9, "IVOIRIERE").
dico("I", 9, "IVOIRIERS").
dico("I", 9, "IVOIRINES").
dico("I", 9, "IXASSIONS").
dico("I", 9, "IXERAIENT").
