dico("J", 10, "JABLASSENT").
dico("J", 10, "JABLASSIEZ").
dico("J", 10, "JABLERIONS").
dico("J", 10, "JABORANDIS").
dico("J", 10, "JABOTAIENT").
dico("J", 10, "JABOTASSES").
dico("J", 10, "JABOTERAIS").
dico("J", 10, "JABOTERAIT").
dico("J", 10, "JABOTERENT").
dico("J", 10, "JABOTERIEZ").
dico("J", 10, "JABOTERONS").
dico("J", 10, "JABOTERONT").
dico("J", 10, "JABOTEUSES").
dico("J", 10, "JACAPUCAYO").
dico("J", 10, "JACARANDAS").
dico("J", 10, "JACASSAMES").
dico("J", 10, "JACASSASSE").
dico("J", 10, "JACASSATES").
dico("J", 10, "JACASSERAI").
dico("J", 10, "JACASSERAS").
dico("J", 10, "JACASSEREZ").
dico("J", 10, "JACASSERIE").
dico("J", 10, "JACASSEURS").
dico("J", 10, "JACASSEUSE").
dico("J", 10, "JACASSIERE").
dico("J", 10, "JACASSIERS").
dico("J", 10, "JACASSIONS").
dico("J", 10, "JACOBIENNE").
dico("J", 10, "JACQUARDEE").
dico("J", 10, "JACQUARDES").
dico("J", 10, "JACQUELINE").
dico("J", 10, "JACQUEMART").
dico("J", 10, "JACQUERIES").
dico("J", 10, "JACTASSENT").
dico("J", 10, "JACTASSIEZ").
dico("J", 10, "JACTERIONS").
dico("J", 10, "JAGUARONDI").
dico("J", 10, "JAILLIRAIS").
dico("J", 10, "JAILLIRAIT").
dico("J", 10, "JAILLIRENT").
dico("J", 10, "JAILLIRIEZ").
dico("J", 10, "JAILLIRONS").
dico("J", 10, "JAILLIRONT").
dico("J", 10, "JAILLISSES").
dico("J", 10, "JAILLISSEZ").
dico("J", 10, "JALONNAMES").
dico("J", 10, "JALONNASSE").
dico("J", 10, "JALONNATES").
dico("J", 10, "JALONNERAI").
dico("J", 10, "JALONNERAS").
dico("J", 10, "JALONNEREZ").
dico("J", 10, "JALONNEURS").
dico("J", 10, "JALONNEUSE").
dico("J", 10, "JALONNIONS").
dico("J", 10, "JALOUSAMES").
dico("J", 10, "JALOUSASSE").
dico("J", 10, "JALOUSATES").
dico("J", 10, "JALOUSERAI").
dico("J", 10, "JALOUSERAS").
dico("J", 10, "JALOUSEREZ").
dico("J", 10, "JALOUSIONS").
dico("J", 10, "JAMAICAINE").
dico("J", 10, "JAMAICAINS").
dico("J", 10, "JAMAIQUAIN").
dico("J", 10, "JAMBONNEAU").
dico("J", 10, "JAMBOSIERS").
dico("J", 10, "JAMEROSIER").
dico("J", 10, "JANISSAIRE").
dico("J", 10, "JANOTISMES").
dico("J", 10, "JANSENISME").
dico("J", 10, "JANSENISTE").
dico("J", 10, "JAPONAISES").
dico("J", 10, "JAPONERIES").
dico("J", 10, "JAPONISAIS").
dico("J", 10, "JAPONISAIT").
dico("J", 10, "JAPONISANT").
dico("J", 10, "JAPONISEES").
dico("J", 10, "JAPONISENT").
dico("J", 10, "JAPONISERA").
dico("J", 10, "JAPONISIEZ").
dico("J", 10, "JAPONISMES").
dico("J", 10, "JAPONISONS").
dico("J", 10, "JAPONISTES").
dico("J", 10, "JAPPASSENT").
dico("J", 10, "JAPPASSIEZ").
dico("J", 10, "JAPPEMENTS").
dico("J", 10, "JAPPERIONS").
dico("J", 10, "JAQUELINES").
dico("J", 10, "JAQUEMARTS").
dico("J", 10, "JARDINAGES").
dico("J", 10, "JARDINAMES").
dico("J", 10, "JARDINASSE").
dico("J", 10, "JARDINATES").
dico("J", 10, "JARDINERAI").
dico("J", 10, "JARDINERAS").
dico("J", 10, "JARDINEREZ").
dico("J", 10, "JARDINERIE").
dico("J", 10, "JARDINEUSE").
dico("J", 10, "JARDINIERE").
dico("J", 10, "JARDINIERS").
dico("J", 10, "JARDINIONS").
dico("J", 10, "JARDINISTE").
dico("J", 10, "JARGONNAIS").
dico("J", 10, "JARGONNAIT").
dico("J", 10, "JARGONNANT").
dico("J", 10, "JARGONNENT").
dico("J", 10, "JARGONNERA").
dico("J", 10, "JARGONNEUR").
dico("J", 10, "JARGONNEUX").
dico("J", 10, "JARGONNIEZ").
dico("J", 10, "JARGONNONS").
dico("J", 10, "JARNICOTON").
dico("J", 10, "JARNIGOINE").
dico("J", 10, "JARRETAMES").
dico("J", 10, "JARRETASSE").
dico("J", 10, "JARRETATES").
dico("J", 10, "JARRETELLE").
dico("J", 10, "JARRETIERE").
dico("J", 10, "JARRETIONS").
dico("J", 10, "JARRETTENT").
dico("J", 10, "JARRETTERA").
dico("J", 10, "JASASSIONS").
dico("J", 10, "JASERAIENT").
dico("J", 10, "JASPASSENT").
dico("J", 10, "JASPASSIEZ").
dico("J", 10, "JASPERIONS").
dico("J", 10, "JASPINAMES").
dico("J", 10, "JASPINASSE").
dico("J", 10, "JASPINATES").
dico("J", 10, "JASPINERAI").
dico("J", 10, "JASPINERAS").
dico("J", 10, "JASPINEREZ").
dico("J", 10, "JASPINIONS").
dico("J", 10, "JASSASSENT").
dico("J", 10, "JASSASSIEZ").
dico("J", 10, "JASSERIONS").
dico("J", 10, "JAUGEAIENT").
dico("J", 10, "JAUGEASSES").
dico("J", 10, "JAUGERIONS").
dico("J", 10, "JAUNIRIONS").
dico("J", 10, "JAUNISSAGE").
dico("J", 10, "JAUNISSAIS").
dico("J", 10, "JAUNISSAIT").
dico("J", 10, "JAUNISSANT").
dico("J", 10, "JAUNISSENT").
dico("J", 10, "JAUNISSIEZ").
dico("J", 10, "JAUNISSONS").
dico("J", 10, "JAVANAISES").
dico("J", 10, "JAVASCRIPT").
dico("J", 10, "JAVELAIENT").
dico("J", 10, "JAVELASSES").
dico("J", 10, "JAVELERENT").
dico("J", 10, "JAVELEUSES").
dico("J", 10, "JAVELLERAI").
dico("J", 10, "JAVELLERAS").
dico("J", 10, "JAVELLEREZ").
dico("J", 10, "JAVELLISAI").
dico("J", 10, "JAVELLISAS").
dico("J", 10, "JAVELLISAT").
dico("J", 10, "JAVELLISEE").
dico("J", 10, "JAVELLISER").
dico("J", 10, "JAVELLISES").
dico("J", 10, "JAVELLISEZ").
dico("J", 10, "JEANNETTES").
dico("J", 10, "JEANNOISES").
dico("J", 10, "JENNERIENS").
dico("J", 10, "JEREMIADES").
dico("J", 10, "JERKASSENT").
dico("J", 10, "JERKASSIEZ").
dico("J", 10, "JERKERIONS").
dico("J", 10, "JEROMIENNE").
dico("J", 10, "JERRICANES").
dico("J", 10, "JERSIAISES").
dico("J", 10, "JESUITIQUE").
dico("J", 10, "JESUITISME").
dico("J", 10, "JETASSIONS").
dico("J", 10, "JETONNIERS").
dico("J", 10, "JETTATURAS").
dico("J", 10, "JETTERIONS").
dico("J", 10, "JEUNASSENT").
dico("J", 10, "JEUNASSIEZ").
dico("J", 10, "JEUNERIONS").
dico("J", 10, "JOAILLERIE").
dico("J", 10, "JOAILLIERE").
dico("J", 10, "JOAILLIERS").
dico("J", 10, "JOBARDAMES").
dico("J", 10, "JOBARDASSE").
dico("J", 10, "JOBARDATES").
dico("J", 10, "JOBARDERAI").
dico("J", 10, "JOBARDERAS").
dico("J", 10, "JOBARDEREZ").
dico("J", 10, "JOBARDERIE").
dico("J", 10, "JOBARDIONS").
dico("J", 10, "JOBARDISES").
dico("J", 10, "JODLASSENT").
dico("J", 10, "JODLASSIEZ").
dico("J", 10, "JODLERIONS").
dico("J", 10, "JOGGASSENT").
dico("J", 10, "JOGGASSIEZ").
dico("J", 10, "JOGGERIONS").
dico("J", 10, "JOHANNAISE").
dico("J", 10, "JOHANNIQUE").
dico("J", 10, "JOHANNITES").
dico("J", 10, "JOIGNABLES").
dico("J", 10, "JOIGNAIENT").
dico("J", 10, "JOIGNIRENT").
dico("J", 10, "JOIGNISSES").
dico("J", 10, "JOINDRIONS").
dico("J", 10, "JOINTAIENT").
dico("J", 10, "JOINTASSES").
dico("J", 10, "JOINTEMENT").
dico("J", 10, "JOINTERAIS").
dico("J", 10, "JOINTERAIT").
dico("J", 10, "JOINTERENT").
dico("J", 10, "JOINTERIEZ").
dico("J", 10, "JOINTERONS").
dico("J", 10, "JOINTERONT").
dico("J", 10, "JOINTOIENT").
dico("J", 10, "JOINTOIERA").
dico("J", 10, "JOINTOYAIS").
dico("J", 10, "JOINTOYAIT").
dico("J", 10, "JOINTOYANT").
dico("J", 10, "JOINTOYEES").
dico("J", 10, "JOINTOYEUR").
dico("J", 10, "JOINTOYIEZ").
dico("J", 10, "JOINTOYONS").
dico("J", 10, "JONCASSENT").
dico("J", 10, "JONCASSIEZ").
dico("J", 10, "JONCERIONS").
dico("J", 10, "JONCHAIENT").
dico("J", 10, "JONCHASSES").
dico("J", 10, "JONCHEMENT").
dico("J", 10, "JONCHERAIE").
dico("J", 10, "JONCHERAIS").
dico("J", 10, "JONCHERAIT").
dico("J", 10, "JONCHERENT").
dico("J", 10, "JONCHERIEZ").
dico("J", 10, "JONCHERONS").
dico("J", 10, "JONCHERONT").
dico("J", 10, "JONGLAIENT").
dico("J", 10, "JONGLASSES").
dico("J", 10, "JONGLERAIS").
dico("J", 10, "JONGLERAIT").
dico("J", 10, "JONGLERENT").
dico("J", 10, "JONGLERIES").
dico("J", 10, "JONGLERIEZ").
dico("J", 10, "JONGLERONS").
dico("J", 10, "JONGLERONT").
dico("J", 10, "JONGLEUSES").
dico("J", 10, "JONQUILLES").
dico("J", 10, "JORDANIENS").
dico("J", 10, "JOSEPHISME").
dico("J", 10, "JOSEPHISTE").
dico("J", 10, "JOTTEREAUX").
dico("J", 10, "JOUABILITE").
dico("J", 10, "JOUAILLAIS").
dico("J", 10, "JOUAILLAIT").
dico("J", 10, "JOUAILLANT").
dico("J", 10, "JOUAILLENT").
dico("J", 10, "JOUAILLERA").
dico("J", 10, "JOUAILLIEZ").
dico("J", 10, "JOUAILLONS").
dico("J", 10, "JOUASSIONS").
dico("J", 10, "JOUERAIENT").
dico("J", 10, "JOUIRAIENT").
dico("J", 10, "JOUISSANCE").
dico("J", 10, "JOUISSANTE").
dico("J", 10, "JOUISSANTS").
dico("J", 10, "JOUISSEURS").
dico("J", 10, "JOUISSEUSE").
dico("J", 10, "JOUISSIONS").
dico("J", 10, "JOUISSIVES").
dico("J", 10, "JOURNALIER").
dico("J", 10, "JOURNALISA").
dico("J", 10, "JOURNALISE").
dico("J", 10, "JOUTASSENT").
dico("J", 10, "JOUTASSIEZ").
dico("J", 10, "JOUTERIONS").
dico("J", 10, "JOUVENCEAU").
dico("J", 10, "JOUXTAIENT").
dico("J", 10, "JOUXTASSES").
dico("J", 10, "JOUXTERAIS").
dico("J", 10, "JOUXTERAIT").
dico("J", 10, "JOUXTERENT").
dico("J", 10, "JOUXTERIEZ").
dico("J", 10, "JOUXTERONS").
dico("J", 10, "JOUXTERONT").
dico("J", 10, "JOVIALITES").
dico("J", 10, "JOYEUSETES").
dico("J", 10, "JUBILAIENT").
dico("J", 10, "JUBILAIRES").
dico("J", 10, "JUBILANTES").
dico("J", 10, "JUBILASSES").
dico("J", 10, "JUBILATION").
dico("J", 10, "JUBILERAIS").
dico("J", 10, "JUBILERAIT").
dico("J", 10, "JUBILERENT").
dico("J", 10, "JUBILERIEZ").
dico("J", 10, "JUBILERONS").
dico("J", 10, "JUBILERONT").
dico("J", 10, "JUCHASSENT").
dico("J", 10, "JUCHASSIEZ").
dico("J", 10, "JUCHERIONS").
dico("J", 10, "JUDAICITES").
dico("J", 10, "JUDAISAMES").
dico("J", 10, "JUDAISANTE").
dico("J", 10, "JUDAISANTS").
dico("J", 10, "JUDAISASSE").
dico("J", 10, "JUDAISATES").
dico("J", 10, "JUDAISERAI").
dico("J", 10, "JUDAISERAS").
dico("J", 10, "JUDAISEREZ").
dico("J", 10, "JUDAISIONS").
dico("J", 10, "JUDICATURE").
dico("J", 10, "JUDICIAIRE").
dico("J", 10, "JUDICIEUSE").
dico("J", 10, "JUGEASSENT").
dico("J", 10, "JUGEASSIEZ").
dico("J", 10, "JUGERAIENT").
dico("J", 10, "JUGLANDALE").
dico("J", 10, "JUGULAIENT").
dico("J", 10, "JUGULAIRES").
dico("J", 10, "JUGULASSES").
dico("J", 10, "JUGULERAIS").
dico("J", 10, "JUGULERAIT").
dico("J", 10, "JUGULERENT").
dico("J", 10, "JUGULERIEZ").
dico("J", 10, "JUGULERONS").
dico("J", 10, "JUGULERONT").
dico("J", 10, "JUMELAIENT").
dico("J", 10, "JUMELASSES").
dico("J", 10, "JUMELERENT").
dico("J", 10, "JUMELLERAI").
dico("J", 10, "JUMELLERAS").
dico("J", 10, "JUMELLEREZ").
dico("J", 10, "JUMENTERIE").
dico("J", 10, "JUMPASSENT").
dico("J", 10, "JUMPASSIEZ").
dico("J", 10, "JUMPERIONS").
dico("J", 10, "JUNONIENNE").
dico("J", 10, "JUPITERIEN").
dico("J", 10, "JUPONNAMES").
dico("J", 10, "JUPONNASSE").
dico("J", 10, "JUPONNATES").
dico("J", 10, "JUPONNERAI").
dico("J", 10, "JUPONNERAS").
dico("J", 10, "JUPONNEREZ").
dico("J", 10, "JUPONNIONS").
dico("J", 10, "JURASSIENS").
dico("J", 10, "JURASSIONS").
dico("J", 10, "JURASSIQUE").
dico("J", 10, "JURATOIRES").
dico("J", 10, "JURERAIENT").
dico("J", 10, "JURIDIQUES").
dico("J", 10, "JURIDISMES").
dico("J", 10, "JUSQUIAMES").
dico("J", 10, "JUSTICIERE").
dico("J", 10, "JUSTICIERS").
dico("J", 10, "JUSTIFIAIS").
dico("J", 10, "JUSTIFIAIT").
dico("J", 10, "JUSTIFIANT").
dico("J", 10, "JUSTIFIEES").
dico("J", 10, "JUSTIFIENT").
dico("J", 10, "JUSTIFIERA").
dico("J", 10, "JUSTIFIIEZ").
dico("J", 10, "JUSTIFIONS").
dico("J", 10, "JUTASSIONS").
dico("J", 10, "JUTERAIENT").
dico("J", 10, "JUVENILITE").
dico("J", 10, "JUXTAPOSAI").
dico("J", 10, "JUXTAPOSAS").
dico("J", 10, "JUXTAPOSAT").
dico("J", 10, "JUXTAPOSEE").
dico("J", 10, "JUXTAPOSER").
dico("J", 10, "JUXTAPOSES").
dico("J", 10, "JUXTAPOSEZ").
