dico("J", 5, "JABLA").
dico("J", 5, "JABLE").
dico("J", 5, "JABOT").
dico("J", 5, "JACEE").
dico("J", 5, "JACKS").
dico("J", 5, "JACOS").
dico("J", 5, "JACOT").
dico("J", 5, "JACTA").
dico("J", 5, "JACTE").
dico("J", 5, "JADES").
dico("J", 5, "JADIS").
dico("J", 5, "JAINA").
dico("J", 5, "JAINE").
dico("J", 5, "JAINS").
dico("J", 5, "JALAP").
dico("J", 5, "JALES").
dico("J", 5, "JALON").
dico("J", 5, "JAMBE").
dico("J", 5, "JANTE").
dico("J", 5, "JAPON").
dico("J", 5, "JAPPA").
dico("J", 5, "JAPPE").
dico("J", 5, "JAQUE").
dico("J", 5, "JARDE").
dico("J", 5, "JARDS").
dico("J", 5, "JARRE").
dico("J", 5, "JASAI").
dico("J", 5, "JASAS").
dico("J", 5, "JASAT").
dico("J", 5, "JASEE").
dico("J", 5, "JASER").
dico("J", 5, "JASES").
dico("J", 5, "JASEZ").
dico("J", 5, "JASPA").
dico("J", 5, "JASPE").
dico("J", 5, "JASSA").
dico("J", 5, "JASSE").
dico("J", 5, "JATTE").
dico("J", 5, "JAUGE").
dico("J", 5, "JAUNE").
dico("J", 5, "JAUNI").
dico("J", 5, "JAVAS").
dico("J", 5, "JAVEL").
dico("J", 5, "JAYET").
dico("J", 5, "JAZZY").
dico("J", 5, "JEANS").
dico("J", 5, "JEEPS").
dico("J", 5, "JENNY").
dico("J", 5, "JEREZ").
dico("J", 5, "JERKA").
dico("J", 5, "JERKE").
dico("J", 5, "JERKS").
dico("J", 5, "JESUS").
dico("J", 5, "JETAI").
dico("J", 5, "JETAS").
dico("J", 5, "JETAT").
dico("J", 5, "JETEE").
dico("J", 5, "JETER").
dico("J", 5, "JETES").
dico("J", 5, "JETEZ").
dico("J", 5, "JETON").
dico("J", 5, "JETTE").
dico("J", 5, "JEUDI").
dico("J", 5, "JEUNA").
dico("J", 5, "JEUNE").
dico("J", 5, "JEZES").
dico("J", 5, "JIHAD").
dico("J", 5, "JOCKO").
dico("J", 5, "JODLA").
dico("J", 5, "JODLE").
dico("J", 5, "JOGGA").
dico("J", 5, "JOGGE").
dico("J", 5, "JOICE").
dico("J", 5, "JOIES").
dico("J", 5, "JOINS").
dico("J", 5, "JOINT").
dico("J", 5, "JOJOS").
dico("J", 5, "JOKER").
dico("J", 5, "JOLIE").
dico("J", 5, "JOLIS").
dico("J", 5, "JOMON").
dico("J", 5, "JONCA").
dico("J", 5, "JONCE").
dico("J", 5, "JONCS").
dico("J", 5, "JORAN").
dico("J", 5, "JOTAS").
dico("J", 5, "JOUAI").
dico("J", 5, "JOUAL").
dico("J", 5, "JOUAS").
dico("J", 5, "JOUAT").
dico("J", 5, "JOUEE").
dico("J", 5, "JOUER").
dico("J", 5, "JOUES").
dico("J", 5, "JOUET").
dico("J", 5, "JOUEZ").
dico("J", 5, "JOUGS").
dico("J", 5, "JOUIR").
dico("J", 5, "JOUIS").
dico("J", 5, "JOUIT").
dico("J", 5, "JOULE").
dico("J", 5, "JOURS").
dico("J", 5, "JOUTA").
dico("J", 5, "JOUTE").
dico("J", 5, "JOYAU").
dico("J", 5, "JUBES").
dico("J", 5, "JUCHA").
dico("J", 5, "JUCHE").
dico("J", 5, "JUDAS").
dico("J", 5, "JUDDS").
dico("J", 5, "JUDOS").
dico("J", 5, "JUGAL").
dico("J", 5, "JUGEA").
dico("J", 5, "JUGEE").
dico("J", 5, "JUGER").
dico("J", 5, "JUGES").
dico("J", 5, "JUGEZ").
dico("J", 5, "JUIFS").
dico("J", 5, "JUINS").
dico("J", 5, "JUIVE").
dico("J", 5, "JULEP").
dico("J", 5, "JULES").
dico("J", 5, "JULIE").
dico("J", 5, "JULOT").
dico("J", 5, "JUMAR").
dico("J", 5, "JUMBO").
dico("J", 5, "JUMEL").
dico("J", 5, "JUMPA").
dico("J", 5, "JUMPE").
dico("J", 5, "JUMPS").
dico("J", 5, "JUNCO").
dico("J", 5, "JUNKS").
dico("J", 5, "JUNKY").
dico("J", 5, "JUNTE").
dico("J", 5, "JUPES").
dico("J", 5, "JUPON").
dico("J", 5, "JURAI").
dico("J", 5, "JURAS").
dico("J", 5, "JURAT").
dico("J", 5, "JUREE").
dico("J", 5, "JURER").
dico("J", 5, "JURES").
dico("J", 5, "JUREZ").
dico("J", 5, "JURON").
dico("J", 5, "JURYS").
dico("J", 5, "JUSEE").
dico("J", 5, "JUSTE").
dico("J", 5, "JUTAI").
dico("J", 5, "JUTAS").
dico("J", 5, "JUTAT").
dico("J", 5, "JUTER").
dico("J", 5, "JUTES").
dico("J", 5, "JUTEZ").
