dico("J", 6, "JABIRU").
dico("J", 6, "JABLAI").
dico("J", 6, "JABLAS").
dico("J", 6, "JABLAT").
dico("J", 6, "JABLEE").
dico("J", 6, "JABLER").
dico("J", 6, "JABLES").
dico("J", 6, "JABLEZ").
dico("J", 6, "JABOTA").
dico("J", 6, "JABOTE").
dico("J", 6, "JABOTS").
dico("J", 6, "JACANA").
dico("J", 6, "JACEES").
dico("J", 6, "JACENT").
dico("J", 6, "JACKET").
dico("J", 6, "JACOTS").
dico("J", 6, "JACTAI").
dico("J", 6, "JACTAS").
dico("J", 6, "JACTAT").
dico("J", 6, "JACTEE").
dico("J", 6, "JACTER").
dico("J", 6, "JACTES").
dico("J", 6, "JACTEZ").
dico("J", 6, "JAGUAR").
dico("J", 6, "JAILLI").
dico("J", 6, "JAINAS").
dico("J", 6, "JAINES").
dico("J", 6, "JALAPS").
dico("J", 6, "JALONS").
dico("J", 6, "JALOUX").
dico("J", 6, "JAMAIS").
dico("J", 6, "JAMBEE").
dico("J", 6, "JAMBES").
dico("J", 6, "JAMBON").
dico("J", 6, "JANTES").
dico("J", 6, "JAPONS").
dico("J", 6, "JAPPAI").
dico("J", 6, "JAPPAS").
dico("J", 6, "JAPPAT").
dico("J", 6, "JAPPER").
dico("J", 6, "JAPPES").
dico("J", 6, "JAPPEZ").
dico("J", 6, "JAQUES").
dico("J", 6, "JAQUET").
dico("J", 6, "JARDES").
dico("J", 6, "JARDIN").
dico("J", 6, "JARDON").
dico("J", 6, "JARGON").
dico("J", 6, "JARRES").
dico("J", 6, "JARRET").
dico("J", 6, "JASAIS").
dico("J", 6, "JASAIT").
dico("J", 6, "JASANT").
dico("J", 6, "JASEES").
dico("J", 6, "JASENT").
dico("J", 6, "JASERA").
dico("J", 6, "JASEUR").
dico("J", 6, "JASIEZ").
dico("J", 6, "JASMIN").
dico("J", 6, "JASONS").
dico("J", 6, "JASPAI").
dico("J", 6, "JASPAS").
dico("J", 6, "JASPAT").
dico("J", 6, "JASPEE").
dico("J", 6, "JASPER").
dico("J", 6, "JASPES").
dico("J", 6, "JASPEZ").
dico("J", 6, "JASSAI").
dico("J", 6, "JASSAS").
dico("J", 6, "JASSAT").
dico("J", 6, "JASSER").
dico("J", 6, "JASSES").
dico("J", 6, "JASSEZ").
dico("J", 6, "JATAKA").
dico("J", 6, "JATTEE").
dico("J", 6, "JATTES").
dico("J", 6, "JAUGEA").
dico("J", 6, "JAUGEE").
dico("J", 6, "JAUGER").
dico("J", 6, "JAUGES").
dico("J", 6, "JAUGEZ").
dico("J", 6, "JAUNES").
dico("J", 6, "JAUNET").
dico("J", 6, "JAUNIE").
dico("J", 6, "JAUNIR").
dico("J", 6, "JAUNIS").
dico("J", 6, "JAUNIT").
dico("J", 6, "JAVART").
dico("J", 6, "JAVEAU").
dico("J", 6, "JAVELA").
dico("J", 6, "JAVELE").
dico("J", 6, "JAYETS").
dico("J", 6, "JENNYS").
dico("J", 6, "JERKAI").
dico("J", 6, "JERKAS").
dico("J", 6, "JERKAT").
dico("J", 6, "JERKER").
dico("J", 6, "JERKES").
dico("J", 6, "JERKEZ").
dico("J", 6, "JERSEY").
dico("J", 6, "JETAGE").
dico("J", 6, "JETAIS").
dico("J", 6, "JETAIT").
dico("J", 6, "JETANT").
dico("J", 6, "JETEES").
dico("J", 6, "JETEUR").
dico("J", 6, "JETIEZ").
dico("J", 6, "JETONS").
dico("J", 6, "JETTES").
dico("J", 6, "JEUDIS").
dico("J", 6, "JEUNAI").
dico("J", 6, "JEUNAS").
dico("J", 6, "JEUNAT").
dico("J", 6, "JEUNER").
dico("J", 6, "JEUNES").
dico("J", 6, "JEUNET").
dico("J", 6, "JEUNEZ").
dico("J", 6, "JEUNOT").
dico("J", 6, "JIGGER").
dico("J", 6, "JIHADS").
dico("J", 6, "JINGLE").
dico("J", 6, "JINGXI").
dico("J", 6, "JIVARO").
dico("J", 6, "JOBARD").
dico("J", 6, "JOCKEY").
dico("J", 6, "JOCKOS").
dico("J", 6, "JODLAI").
dico("J", 6, "JODLAS").
dico("J", 6, "JODLAT").
dico("J", 6, "JODLER").
dico("J", 6, "JODLES").
dico("J", 6, "JODLEZ").
dico("J", 6, "JOGGAI").
dico("J", 6, "JOGGAS").
dico("J", 6, "JOGGAT").
dico("J", 6, "JOGGER").
dico("J", 6, "JOGGES").
dico("J", 6, "JOGGEZ").
dico("J", 6, "JOICES").
dico("J", 6, "JOIGNE").
dico("J", 6, "JOINTA").
dico("J", 6, "JOINTE").
dico("J", 6, "JOINTS").
dico("J", 6, "JOJOBA").
dico("J", 6, "JOKARI").
dico("J", 6, "JOKERS").
dico("J", 6, "JOLIES").
dico("J", 6, "JOLIET").
dico("J", 6, "JOMONS").
dico("J", 6, "JONCAI").
dico("J", 6, "JONCAS").
dico("J", 6, "JONCAT").
dico("J", 6, "JONCEE").
dico("J", 6, "JONCER").
dico("J", 6, "JONCES").
dico("J", 6, "JONCEZ").
dico("J", 6, "JONCHA").
dico("J", 6, "JONCHE").
dico("J", 6, "JONGLA").
dico("J", 6, "JONGLE").
dico("J", 6, "JONQUE").
dico("J", 6, "JORANS").
dico("J", 6, "JORURI").
dico("J", 6, "JOSEPH").
dico("J", 6, "JOUAIS").
dico("J", 6, "JOUAIT").
dico("J", 6, "JOUALE").
dico("J", 6, "JOUALS").
dico("J", 6, "JOUANT").
dico("J", 6, "JOUAUX").
dico("J", 6, "JOUEES").
dico("J", 6, "JOUENT").
dico("J", 6, "JOUERA").
dico("J", 6, "JOUETS").
dico("J", 6, "JOUEUR").
dico("J", 6, "JOUIEZ").
dico("J", 6, "JOUIRA").
dico("J", 6, "JOUJOU").
dico("J", 6, "JOULES").
dico("J", 6, "JOUONS").
dico("J", 6, "JOUTAI").
dico("J", 6, "JOUTAS").
dico("J", 6, "JOUTAT").
dico("J", 6, "JOUTER").
dico("J", 6, "JOUTES").
dico("J", 6, "JOUTEZ").
dico("J", 6, "JOUXTA").
dico("J", 6, "JOUXTE").
dico("J", 6, "JOVIAL").
dico("J", 6, "JOVIEN").
dico("J", 6, "JOYAUX").
dico("J", 6, "JOYEUX").
dico("J", 6, "JUBILA").
dico("J", 6, "JUBILE").
dico("J", 6, "JUCHAI").
dico("J", 6, "JUCHAS").
dico("J", 6, "JUCHAT").
dico("J", 6, "JUCHEE").
dico("J", 6, "JUCHER").
dico("J", 6, "JUCHES").
dico("J", 6, "JUCHEZ").
dico("J", 6, "JUDEEN").
dico("J", 6, "JUDOGI").
dico("J", 6, "JUDOKA").
dico("J", 6, "JUGALE").
dico("J", 6, "JUGAUX").
dico("J", 6, "JUGEAI").
dico("J", 6, "JUGEAS").
dico("J", 6, "JUGEAT").
dico("J", 6, "JUGEES").
dico("J", 6, "JUGENT").
dico("J", 6, "JUGERA").
dico("J", 6, "JUGEUR").
dico("J", 6, "JUGIEZ").
dico("J", 6, "JUGULA").
dico("J", 6, "JUGULE").
dico("J", 6, "JUIVES").
dico("J", 6, "JUJUBE").
dico("J", 6, "JULEPS").
dico("J", 6, "JULIEN").
dico("J", 6, "JULIES").
dico("J", 6, "JULOTS").
dico("J", 6, "JUMARS").
dico("J", 6, "JUMBOS").
dico("J", 6, "JUMEAU").
dico("J", 6, "JUMELA").
dico("J", 6, "JUMELE").
dico("J", 6, "JUMELS").
dico("J", 6, "JUMENT").
dico("J", 6, "JUMPAI").
dico("J", 6, "JUMPAS").
dico("J", 6, "JUMPAT").
dico("J", 6, "JUMPER").
dico("J", 6, "JUMPES").
dico("J", 6, "JUMPEZ").
dico("J", 6, "JUNCOS").
dico("J", 6, "JUNGLE").
dico("J", 6, "JUNIOR").
dico("J", 6, "JUNKER").
dico("J", 6, "JUNKIE").
dico("J", 6, "JUNKYS").
dico("J", 6, "JUNTES").
dico("J", 6, "JUPIER").
dico("J", 6, "JUPONS").
dico("J", 6, "JURAIS").
dico("J", 6, "JURAIT").
dico("J", 6, "JURANT").
dico("J", 6, "JURATS").
dico("J", 6, "JUREES").
dico("J", 6, "JURENT").
dico("J", 6, "JURERA").
dico("J", 6, "JUREUR").
dico("J", 6, "JURIEZ").
dico("J", 6, "JURONS").
dico("J", 6, "JUSANT").
dico("J", 6, "JUSEES").
dico("J", 6, "JUSQUE").
dico("J", 6, "JUSSIF").
dico("J", 6, "JUSTES").
dico("J", 6, "JUTAIS").
dico("J", 6, "JUTAIT").
dico("J", 6, "JUTANT").
dico("J", 6, "JUTENT").
dico("J", 6, "JUTERA").
dico("J", 6, "JUTEUX").
dico("J", 6, "JUTIEZ").
dico("J", 6, "JUTONS").
