dico("K", 5, "KABIC").
dico("K", 5, "KABIG").
dico("K", 5, "KACHA").
dico("K", 5, "KACHE").
dico("K", 5, "KADIS").
dico("K", 5, "KAGOU").
dico("K", 5, "KAKIS").
dico("K", 5, "KALES").
dico("K", 5, "KALIS").
dico("K", 5, "KAMIS").
dico("K", 5, "KANAK").
dico("K", 5, "KANAS").
dico("K", 5, "KANJI").
dico("K", 5, "KAONS").
dico("K", 5, "KAPOK").
dico("K", 5, "KAPOS").
dico("K", 5, "KAPPA").
dico("K", 5, "KAREN").
dico("K", 5, "KARMA").
dico("K", 5, "KARST").
dico("K", 5, "KARTS").
dico("K", 5, "KATAS").
dico("K", 5, "KAVAS").
dico("K", 5, "KAWAS").
dico("K", 5, "KAWIS").
dico("K", 5, "KAYAC").
dico("K", 5, "KAYAK").
dico("K", 5, "KEBAB").
dico("K", 5, "KEFIR").
dico("K", 5, "KENDO").
dico("K", 5, "KEPIS").
dico("K", 5, "KERMA").
dico("K", 5, "KETCH").
dico("K", 5, "KEUFS").
dico("K", 5, "KEUMS").
dico("K", 5, "KHANS").
dico("K", 5, "KHATS").
dico("K", 5, "KHMER").
dico("K", 5, "KHOIN").
dico("K", 5, "KHOLS").
dico("K", 5, "KICKS").
dico("K", 5, "KIEFS").
dico("K", 5, "KIFAI").
dico("K", 5, "KIFAS").
dico("K", 5, "KIFAT").
dico("K", 5, "KIFEE").
dico("K", 5, "KIFER").
dico("K", 5, "KIFES").
dico("K", 5, "KIFEZ").
dico("K", 5, "KIFFA").
dico("K", 5, "KIFFE").
dico("K", 5, "KIKIS").
dico("K", 5, "KILIM").
dico("K", 5, "KILOS").
dico("K", 5, "KILTS").
dico("K", 5, "KINAS").
dico("K", 5, "KINES").
dico("K", 5, "KIPPA").
dico("K", 5, "KITCH").
dico("K", 5, "KIWIS").
dico("K", 5, "KNACK").
dico("K", 5, "KNOUT").
dico("K", 5, "KOALA").
dico("K", 5, "KODAK").
dico("K", 5, "KOHOL").
dico("K", 5, "KOINE").
dico("K", 5, "KOKAS").
dico("K", 5, "KOLAS").
dico("K", 5, "KONDO").
dico("K", 5, "KOPPA").
dico("K", 5, "KORAS").
dico("K", 5, "KORES").
dico("K", 5, "KOTAI").
dico("K", 5, "KOTAS").
dico("K", 5, "KOTAT").
dico("K", 5, "KOTER").
dico("K", 5, "KOTES").
dico("K", 5, "KOTEZ").
dico("K", 5, "KOTOS").
dico("K", 5, "KRAAL").
dico("K", 5, "KRACH").
dico("K", 5, "KRAFT").
dico("K", 5, "KRAKS").
dico("K", 5, "KREML").
dico("K", 5, "KRIEK").
dico("K", 5, "KRILL").
dico("K", 5, "KRISS").
dico("K", 5, "KSARS").
dico("K", 5, "KSOUR").
dico("K", 5, "KUNAS").
dico("K", 5, "KURDE").
dico("K", 5, "KURUS").
dico("K", 5, "KYATS").
dico("K", 5, "KYRIE").
dico("K", 5, "KYSTE").
dico("K", 5, "KYUDO").
