dico("K", 6, "KABICS").
dico("K", 6, "KABIGS").
dico("K", 6, "KABUKI").
dico("K", 6, "KABYLE").
dico("K", 6, "KACHAS").
dico("K", 6, "KACHES").
dico("K", 6, "KAGOUS").
dico("K", 6, "KAISER").
dico("K", 6, "KAKAWI").
dico("K", 6, "KALIUM").
dico("K", 6, "KAMALA").
dico("K", 6, "KANAKE").
dico("K", 6, "KANAKS").
dico("K", 6, "KANJIS").
dico("K", 6, "KAOLIN").
dico("K", 6, "KAPOKS").
dico("K", 6, "KARATE").
dico("K", 6, "KARBAU").
dico("K", 6, "KARENS").
dico("K", 6, "KARITE").
dico("K", 6, "KARMAN").
dico("K", 6, "KARMAS").
dico("K", 6, "KARSTS").
dico("K", 6, "KASHER").
dico("K", 6, "KAYACS").
dico("K", 6, "KAYAKS").
dico("K", 6, "KAZAKH").
dico("K", 6, "KEBABS").
dico("K", 6, "KEFIRS").
dico("K", 6, "KEIRIN").
dico("K", 6, "KELVIN").
dico("K", 6, "KENDOS").
dico("K", 6, "KENTIA").
dico("K", 6, "KENYAN").
dico("K", 6, "KEPHIR").
dico("K", 6, "KEPHYR").
dico("K", 6, "KERMAS").
dico("K", 6, "KERMES").
dico("K", 6, "KERRIA").
dico("K", 6, "KERRIE").
dico("K", 6, "KETCHS").
dico("K", 6, "KETMIE").
dico("K", 6, "KEVLAR").
dico("K", 6, "KHAGNE").
dico("K", 6, "KHANAT").
dico("K", 6, "KHMERE").
dico("K", 6, "KHMERS").
dico("K", 6, "KHOINS").
dico("K", 6, "KIBITZ").
dico("K", 6, "KICKER").
dico("K", 6, "KIFAIS").
dico("K", 6, "KIFAIT").
dico("K", 6, "KIFANT").
dico("K", 6, "KIFEES").
dico("K", 6, "KIFENT").
dico("K", 6, "KIFERA").
dico("K", 6, "KIFFAI").
dico("K", 6, "KIFFAS").
dico("K", 6, "KIFFAT").
dico("K", 6, "KIFFEE").
dico("K", 6, "KIFFER").
dico("K", 6, "KIFFES").
dico("K", 6, "KIFFEZ").
dico("K", 6, "KIFIEZ").
dico("K", 6, "KIFONS").
dico("K", 6, "KILIMS").
dico("K", 6, "KILOHM").
dico("K", 6, "KIMONO").
dico("K", 6, "KINASE").
dico("K", 6, "KINOIS").
dico("K", 6, "KIPPAS").
dico("K", 6, "KIPPER").
dico("K", 6, "KIRSCH").
dico("K", 6, "KITSCH").
dico("K", 6, "KLAXON").
dico("K", 6, "KLIPPE").
dico("K", 6, "KNACKS").
dico("K", 6, "KNOUTS").
dico("K", 6, "KOALAS").
dico("K", 6, "KOBOLD").
dico("K", 6, "KODAKS").
dico("K", 6, "KODIAK").
dico("K", 6, "KOHEUL").
dico("K", 6, "KOHOLS").
dico("K", 6, "KOINES").
dico("K", 6, "KONDOS").
dico("K", 6, "KOPECK").
dico("K", 6, "KOTAIS").
dico("K", 6, "KOTAIT").
dico("K", 6, "KOTANT").
dico("K", 6, "KOTENT").
dico("K", 6, "KOTERA").
dico("K", 6, "KOTEUR").
dico("K", 6, "KOTIEZ").
dico("K", 6, "KOTONS").
dico("K", 6, "KOUBBA").
dico("K", 6, "KOUDOU").
dico("K", 6, "KOUFFA").
dico("K", 6, "KOULAK").
dico("K", 6, "KOUMIS").
dico("K", 6, "KOUMYS").
dico("K", 6, "KOUROI").
dico("K", 6, "KOUROS").
dico("K", 6, "KRAALS").
dico("K", 6, "KRACHS").
dico("K", 6, "KRAFTS").
dico("K", 6, "KRAKEN").
dico("K", 6, "KREMLS").
dico("K", 6, "KRIEKS").
dico("K", 6, "KRILLS").
dico("K", 6, "KUMMEL").
dico("K", 6, "KURDES").
dico("K", 6, "KWACHA").
dico("K", 6, "KWANZA").
dico("K", 6, "KYSTES").
dico("K", 6, "KYUDOS").
