dico("K", 7, "KABBALE").
dico("K", 7, "KABOULI").
dico("K", 7, "KABUKIS").
dico("K", 7, "KABYLES").
dico("K", 7, "KADDISH").
dico("K", 7, "KAINITE").
dico("K", 7, "KAISERS").
dico("K", 7, "KAKAWIS").
dico("K", 7, "KALIUMS").
dico("K", 7, "KALMOUK").
dico("K", 7, "KAMALAS").
dico("K", 7, "KAMICHI").
dico("K", 7, "KANAKES").
dico("K", 7, "KANDJAR").
dico("K", 7, "KANGLAR").
dico("K", 7, "KANNARA").
dico("K", 7, "KANTIEN").
dico("K", 7, "KAOLINS").
dico("K", 7, "KARAITE").
dico("K", 7, "KARAKUL").
dico("K", 7, "KARAOKE").
dico("K", 7, "KARATES").
dico("K", 7, "KARBAUS").
dico("K", 7, "KARBAUX").
dico("K", 7, "KARITES").
dico("K", 7, "KARMANS").
dico("K", 7, "KARTING").
dico("K", 7, "KASAIEN").
dico("K", 7, "KASCHER").
dico("K", 7, "KASSITE").
dico("K", 7, "KAZAKHE").
dico("K", 7, "KAZAKHS").
dico("K", 7, "KEFFIEH").
dico("K", 7, "KEIRINS").
dico("K", 7, "KELVINS").
dico("K", 7, "KENTIAS").
dico("K", 7, "KENYANE").
dico("K", 7, "KENYANS").
dico("K", 7, "KEPHIRS").
dico("K", 7, "KEPHYRS").
dico("K", 7, "KERABAU").
dico("K", 7, "KERRIAS").
dico("K", 7, "KERRIES").
dico("K", 7, "KETCHUP").
dico("K", 7, "KETMIES").
dico("K", 7, "KEVLARS").
dico("K", 7, "KHAGNES").
dico("K", 7, "KHALIFE").
dico("K", 7, "KHALKHA").
dico("K", 7, "KHAMMES").
dico("K", 7, "KHAMSIN").
dico("K", 7, "KHANATS").
dico("K", 7, "KHEDIVE").
dico("K", 7, "KHMERES").
dico("K", 7, "KHOISAN").
dico("K", 7, "KIBITZA").
dico("K", 7, "KIBITZE").
dico("K", 7, "KICKERS").
dico("K", 7, "KIEVIEN").
dico("K", 7, "KIFAMES").
dico("K", 7, "KIFASSE").
dico("K", 7, "KIFATES").
dico("K", 7, "KIFERAI").
dico("K", 7, "KIFERAS").
dico("K", 7, "KIFEREZ").
dico("K", 7, "KIFFAIS").
dico("K", 7, "KIFFAIT").
dico("K", 7, "KIFFANT").
dico("K", 7, "KIFFEES").
dico("K", 7, "KIFFENT").
dico("K", 7, "KIFFERA").
dico("K", 7, "KIFFIEZ").
dico("K", 7, "KIFFONS").
dico("K", 7, "KIFIONS").
dico("K", 7, "KILOBIT").
dico("K", 7, "KILOHMS").
dico("K", 7, "KILOVAR").
dico("K", 7, "KIMONOS").
dico("K", 7, "KINASES").
dico("K", 7, "KINESIE").
dico("K", 7, "KINOISE").
dico("K", 7, "KIOSQUE").
dico("K", 7, "KIPPERS").
dico("K", 7, "KIPPOUR").
dico("K", 7, "KIRGHIZ").
dico("K", 7, "KIRSCHS").
dico("K", 7, "KLAXONS").
dico("K", 7, "KLEENEX").
dico("K", 7, "KLEPHTE").
dico("K", 7, "KLIPPES").
dico("K", 7, "KNESSET").
dico("K", 7, "KNICKER").
dico("K", 7, "KOBOLDS").
dico("K", 7, "KODIAKS").
dico("K", 7, "KOHEULS").
dico("K", 7, "KOLKHOZ").
dico("K", 7, "KONZERN").
dico("K", 7, "KOPECKS").
dico("K", 7, "KORISTE").
dico("K", 7, "KOSOVAR").
dico("K", 7, "KOTAMES").
dico("K", 7, "KOTASSE").
dico("K", 7, "KOTATES").
dico("K", 7, "KOTERAI").
dico("K", 7, "KOTERAS").
dico("K", 7, "KOTEREZ").
dico("K", 7, "KOTEURS").
dico("K", 7, "KOTEUSE").
dico("K", 7, "KOTIONS").
dico("K", 7, "KOUBBAS").
dico("K", 7, "KOUDOUS").
dico("K", 7, "KOUFFAS").
dico("K", 7, "KOUGLOF").
dico("K", 7, "KOULAKS").
dico("K", 7, "KOWEITI").
dico("K", 7, "KRAKENS").
dico("K", 7, "KREMLIN").
dico("K", 7, "KREUZER").
dico("K", 7, "KROUMIR").
dico("K", 7, "KRYPTON").
dico("K", 7, "KUFIQUE").
dico("K", 7, "KUMMELS").
dico("K", 7, "KUMQUAT").
dico("K", 7, "KURSAAL").
dico("K", 7, "KWACHAS").
dico("K", 7, "KWANZAS").
