dico("K", 8, "KABBALES").
dico("K", 8, "KABOULIE").
dico("K", 8, "KABOULIS").
dico("K", 8, "KADDISHS").
dico("K", 8, "KAFKAIEN").
dico("K", 8, "KAINITES").
dico("K", 8, "KAKATOES").
dico("K", 8, "KAKEMONO").
dico("K", 8, "KALIEMIE").
dico("K", 8, "KALMOUKE").
dico("K", 8, "KALMOUKS").
dico("K", 8, "KAMICHIS").
dico("K", 8, "KAMIKAZE").
dico("K", 8, "KANDJARS").
dico("K", 8, "KANDJLAR").
dico("K", 8, "KANGLARS").
dico("K", 8, "KANNARAS").
dico("K", 8, "KANTIENS").
dico("K", 8, "KANTISME").
dico("K", 8, "KANTISTE").
dico("K", 8, "KAOLIANG").
dico("K", 8, "KAPOKIER").
dico("K", 8, "KARAITES").
dico("K", 8, "KARAKULS").
dico("K", 8, "KARAOKES").
dico("K", 8, "KARATEKA").
dico("K", 8, "KARTINGS").
dico("K", 8, "KASAIENS").
dico("K", 8, "KASHROUT").
dico("K", 8, "KASSITES").
dico("K", 8, "KATAKANA").
dico("K", 8, "KATCHINA").
dico("K", 8, "KAZAKHES").
dico("K", 8, "KEEPSAKE").
dico("K", 8, "KEFFIEHS").
dico("K", 8, "KEIRETSU").
dico("K", 8, "KENOTRON").
dico("K", 8, "KENYANES").
dico("K", 8, "KERABAUS").
dico("K", 8, "KERABAUX").
dico("K", 8, "KERATINE").
dico("K", 8, "KERATITE").
dico("K", 8, "KERATOME").
dico("K", 8, "KERATOSE").
dico("K", 8, "KERMESSE").
dico("K", 8, "KEROGENE").
dico("K", 8, "KEROSENE").
dico("K", 8, "KETCHUPS").
dico("K", 8, "KEVATRON").
dico("K", 8, "KHAGNEUX").
dico("K", 8, "KHALIFAT").
dico("K", 8, "KHALIFES").
dico("K", 8, "KHALKHAS").
dico("K", 8, "KHAMSINS").
dico("K", 8, "KHARIDJI").
dico("K", 8, "KHEDIVAL").
dico("K", 8, "KHEDIVAT").
dico("K", 8, "KHEDIVES").
dico("K", 8, "KHOISANE").
dico("K", 8, "KHOISANS").
dico("K", 8, "KIBBOUTZ").
dico("K", 8, "KIBITZAI").
dico("K", 8, "KIBITZAS").
dico("K", 8, "KIBITZAT").
dico("K", 8, "KIBITZEE").
dico("K", 8, "KIBITZER").
dico("K", 8, "KIBITZES").
dico("K", 8, "KIBITZEZ").
dico("K", 8, "KIDNAPPA").
dico("K", 8, "KIDNAPPE").
dico("K", 8, "KIEVIENS").
dico("K", 8, "KIFAIENT").
dico("K", 8, "KIFASSES").
dico("K", 8, "KIFERAIS").
dico("K", 8, "KIFERAIT").
dico("K", 8, "KIFERENT").
dico("K", 8, "KIFERIEZ").
dico("K", 8, "KIFERONS").
dico("K", 8, "KIFERONT").
dico("K", 8, "KIFFAMES").
dico("K", 8, "KIFFASSE").
dico("K", 8, "KIFFATES").
dico("K", 8, "KIFFERAI").
dico("K", 8, "KIFFERAS").
dico("K", 8, "KIFFEREZ").
dico("K", 8, "KIFFIONS").
dico("K", 8, "KILOBITS").
dico("K", 8, "KILOBYTE").
dico("K", 8, "KILOVARS").
dico("K", 8, "KILOVOLT").
dico("K", 8, "KILOWATT").
dico("K", 8, "KINESIES").
dico("K", 8, "KINKAJOU").
dico("K", 8, "KINOISES").
dico("K", 8, "KIOSQUES").
dico("K", 8, "KIPPOURS").
dico("K", 8, "KIRGHIZE").
dico("K", 8, "KLAXONNA").
dico("K", 8, "KLAXONNE").
dico("K", 8, "KLEPHTES").
dico("K", 8, "KLEVENER").
dico("K", 8, "KLYSTRON").
dico("K", 8, "KNESSETS").
dico("K", 8, "KNICKERS").
dico("K", 8, "KOLATIER").
dico("K", 8, "KOLINSKI").
dico("K", 8, "KOLKHOZE").
dico("K", 8, "KOMSOMOL").
dico("K", 8, "KONZERNS").
dico("K", 8, "KORISTES").
dico("K", 8, "KORRIGAN").
dico("K", 8, "KORTHALS").
dico("K", 8, "KOSOVARE").
dico("K", 8, "KOSOVARS").
dico("K", 8, "KOTAIENT").
dico("K", 8, "KOTASSES").
dico("K", 8, "KOTERAIS").
dico("K", 8, "KOTERAIT").
dico("K", 8, "KOTERENT").
dico("K", 8, "KOTERIEZ").
dico("K", 8, "KOTERONS").
dico("K", 8, "KOTERONT").
dico("K", 8, "KOTEUSES").
dico("K", 8, "KOUGLOFS").
dico("K", 8, "KOURGANE").
dico("K", 8, "KOWEITIE").
dico("K", 8, "KOWEITIS").
dico("K", 8, "KREMLINS").
dico("K", 8, "KREUTZER").
dico("K", 8, "KREUZERS").
dico("K", 8, "KROUMIRS").
dico("K", 8, "KRYPTONS").
dico("K", 8, "KSATRIYA").
dico("K", 8, "KUFIQUES").
dico("K", 8, "KUMQUATS").
dico("K", 8, "KURSAALS").
dico("K", 8, "KYMRIQUE").
dico("K", 8, "KYRIELLE").
dico("K", 8, "KYSTIQUE").
