dico("K", 9, "KABOULIEN").
dico("K", 9, "KABOULIES").
dico("K", 9, "KAFKAIENS").
dico("K", 9, "KAKEMONOS").
dico("K", 9, "KALANCHOE").
dico("K", 9, "KALICYTIE").
dico("K", 9, "KALIEMIES").
dico("K", 9, "KALMOUKES").
dico("K", 9, "KAMIKAZES").
dico("K", 9, "KANANGAIS").
dico("K", 9, "KANDJLARS").
dico("K", 9, "KANGOUROU").
dico("K", 9, "KANTIENNE").
dico("K", 9, "KANTISMES").
dico("K", 9, "KANTISTES").
dico("K", 9, "KAOLIANGS").
dico("K", 9, "KAOLINISA").
dico("K", 9, "KAOLINISE").
dico("K", 9, "KAOLINITE").
dico("K", 9, "KAPOKIERS").
dico("K", 9, "KARATEKAS").
dico("K", 9, "KARSTIQUE").
dico("K", 9, "KASAIENNE").
dico("K", 9, "KASHROUTS").
dico("K", 9, "KATAKANAS").
dico("K", 9, "KATANGAIS").
dico("K", 9, "KATCHINAS").
dico("K", 9, "KATHAKALI").
dico("K", 9, "KAYAKABLE").
dico("K", 9, "KAYAKISTE").
dico("K", 9, "KEEPSAKES").
dico("K", 9, "KEIRETSUS").
dico("K", 9, "KEMALISME").
dico("K", 9, "KENOTRONS").
dico("K", 9, "KEPLERIEN").
dico("K", 9, "KERATINES").
dico("K", 9, "KERATIQUE").
dico("K", 9, "KERATITES").
dico("K", 9, "KERATOMES").
dico("K", 9, "KERATOSES").
dico("K", 9, "KERMESSES").
dico("K", 9, "KEROGENES").
dico("K", 9, "KEROSENES").
dico("K", 9, "KEVATRONS").
dico("K", 9, "KEYNESIEN").
dico("K", 9, "KHAGNEUSE").
dico("K", 9, "KHALIFATS").
dico("K", 9, "KHARIDJIS").
dico("K", 9, "KHEDIVALE").
dico("K", 9, "KHEDIVATS").
dico("K", 9, "KHEDIVAUX").
dico("K", 9, "KHEDIVIAL").
dico("K", 9, "KHEDIVIAT").
dico("K", 9, "KHOISANES").
dico("K", 9, "KIBITZAIS").
dico("K", 9, "KIBITZAIT").
dico("K", 9, "KIBITZANT").
dico("K", 9, "KIBITZEES").
dico("K", 9, "KIBITZENT").
dico("K", 9, "KIBITZERA").
dico("K", 9, "KIBITZIEZ").
dico("K", 9, "KIBITZONS").
dico("K", 9, "KIDNAPPAI").
dico("K", 9, "KIDNAPPAS").
dico("K", 9, "KIDNAPPAT").
dico("K", 9, "KIDNAPPEE").
dico("K", 9, "KIDNAPPER").
dico("K", 9, "KIDNAPPES").
dico("K", 9, "KIDNAPPEZ").
dico("K", 9, "KIESELGUR").
dico("K", 9, "KIESERITE").
dico("K", 9, "KIEVIENNE").
dico("K", 9, "KIFASSENT").
dico("K", 9, "KIFASSIEZ").
dico("K", 9, "KIFERIONS").
dico("K", 9, "KIFFAIENT").
dico("K", 9, "KIFFASSES").
dico("K", 9, "KIFFERAIS").
dico("K", 9, "KIFFERAIT").
dico("K", 9, "KIFFERENT").
dico("K", 9, "KIFFERIEZ").
dico("K", 9, "KIFFERONS").
dico("K", 9, "KIFFERONT").
dico("K", 9, "KILOBYTES").
dico("K", 9, "KILOCYCLE").
dico("K", 9, "KILOFRANC").
dico("K", 9, "KILOHERTZ").
dico("K", 9, "KILOJOULE").
dico("K", 9, "KILOMETRA").
dico("K", 9, "KILOMETRE").
dico("K", 9, "KILOOCTET").
dico("K", 9, "KILOTONNE").
dico("K", 9, "KILOVOLTS").
dico("K", 9, "KILOWATTS").
dico("K", 9, "KINESCOPE").
dico("K", 9, "KINESISTE").
dico("K", 9, "KINKAJOUS").
dico("K", 9, "KIOSQUIER").
dico("K", 9, "KIRGHIZES").
dico("K", 9, "KITTITIEN").
dico("K", 9, "KLAXONNAI").
dico("K", 9, "KLAXONNAS").
dico("K", 9, "KLAXONNAT").
dico("K", 9, "KLAXONNEE").
dico("K", 9, "KLAXONNER").
dico("K", 9, "KLAXONNES").
dico("K", 9, "KLAXONNEZ").
dico("K", 9, "KLEVENERS").
dico("K", 9, "KLYSTRONS").
dico("K", 9, "KOLATIERS").
dico("K", 9, "KOLINSKIS").
dico("K", 9, "KOLKHOZES").
dico("K", 9, "KOMSOMOLE").
dico("K", 9, "KOMSOMOLS").
dico("K", 9, "KORRIGANE").
dico("K", 9, "KORRIGANS").
dico("K", 9, "KOSOVARES").
dico("K", 9, "KOTASSENT").
dico("K", 9, "KOTASSIEZ").
dico("K", 9, "KOTERIONS").
dico("K", 9, "KOULIBIAC").
dico("K", 9, "KOURGANES").
dico("K", 9, "KOWEITIEN").
dico("K", 9, "KOWEITIES").
dico("K", 9, "KREUTZERS").
dico("K", 9, "KRONPRINZ").
dico("K", 9, "KSATRIYAS").
dico("K", 9, "KSHATRIYA").
dico("K", 9, "KUGELHOPF").
dico("K", 9, "KYMRIQUES").
dico("K", 9, "KYRIELLES").
dico("K", 9, "KYSTIQUES").
