dico("L", 10, "LABELISAIS").
dico("L", 10, "LABELISAIT").
dico("L", 10, "LABELISANT").
dico("L", 10, "LABELISEES").
dico("L", 10, "LABELISENT").
dico("L", 10, "LABELISERA").
dico("L", 10, "LABELISIEZ").
dico("L", 10, "LABELISONS").
dico("L", 10, "LABELLISAI").
dico("L", 10, "LABELLISAS").
dico("L", 10, "LABELLISAT").
dico("L", 10, "LABELLISEE").
dico("L", 10, "LABELLISER").
dico("L", 10, "LABELLISES").
dico("L", 10, "LABELLISEZ").
dico("L", 10, "LABFERMENT").
dico("L", 10, "LABIALISAI").
dico("L", 10, "LABIALISAS").
dico("L", 10, "LABIALISAT").
dico("L", 10, "LABIALISEE").
dico("L", 10, "LABIALISER").
dico("L", 10, "LABIALISES").
dico("L", 10, "LABIALISEZ").
dico("L", 10, "LABORANTIN").
dico("L", 10, "LABORIEUSE").
dico("L", 10, "LABOURABLE").
dico("L", 10, "LABOURAGES").
dico("L", 10, "LABOURAMES").
dico("L", 10, "LABOURASSE").
dico("L", 10, "LABOURATES").
dico("L", 10, "LABOURERAI").
dico("L", 10, "LABOURERAS").
dico("L", 10, "LABOUREREZ").
dico("L", 10, "LABOUREURS").
dico("L", 10, "LABOURIONS").
dico("L", 10, "LABYRINTHE").
dico("L", 10, "LACASSIONS").
dico("L", 10, "LACCOLITES").
dico("L", 10, "LACCOLITHE").
dico("L", 10, "LACERAIENT").
dico("L", 10, "LACERASSES").
dico("L", 10, "LACERATION").
dico("L", 10, "LACERERAIS").
dico("L", 10, "LACERERAIT").
dico("L", 10, "LACERERENT").
dico("L", 10, "LACERERIEZ").
dico("L", 10, "LACERERONS").
dico("L", 10, "LACERERONT").
dico("L", 10, "LACERTIDES").
dico("L", 10, "LACERTIENS").
dico("L", 10, "LACHASSENT").
dico("L", 10, "LACHASSIEZ").
dico("L", 10, "LACHERIONS").
dico("L", 10, "LACONIQUES").
dico("L", 10, "LACONISMES").
dico("L", 10, "LACRYMALES").
dico("L", 10, "LACTARIUMS").
dico("L", 10, "LACTATIONS").
dico("L", 10, "LACTESCENT").
dico("L", 10, "LACTIFERES").
dico("L", 10, "LACTOGENES").
dico("L", 10, "LACTOMETRE").
dico("L", 10, "LACTOSERUM").
dico("L", 10, "LACUNAIRES").
dico("L", 10, "LACUNEUSES").
dico("L", 10, "LAGOMORPHE").
dico("L", 10, "LAGOTRICHE").
dico("L", 10, "LAGUNAIRES").
dico("L", 10, "LAICISAMES").
dico("L", 10, "LAICISASSE").
dico("L", 10, "LAICISATES").
dico("L", 10, "LAICISERAI").
dico("L", 10, "LAICISERAS").
dico("L", 10, "LAICISEREZ").
dico("L", 10, "LAICISIONS").
dico("L", 10, "LAIDERONNE").
dico("L", 10, "LAIERAIENT").
dico("L", 10, "LAIMARGUES").
dico("L", 10, "LAINASSENT").
dico("L", 10, "LAINASSIEZ").
dico("L", 10, "LAINERIONS").
dico("L", 10, "LAISSAIENT").
dico("L", 10, "LAISSASSES").
dico("L", 10, "LAISSERAIS").
dico("L", 10, "LAISSERAIT").
dico("L", 10, "LAISSERENT").
dico("L", 10, "LAISSERIEZ").
dico("L", 10, "LAISSERONS").
dico("L", 10, "LAISSERONT").
dico("L", 10, "LAITONNAGE").
dico("L", 10, "LAITONNAIS").
dico("L", 10, "LAITONNAIT").
dico("L", 10, "LAITONNANT").
dico("L", 10, "LAITONNEES").
dico("L", 10, "LAITONNENT").
dico("L", 10, "LAITONNERA").
dico("L", 10, "LAITONNIEZ").
dico("L", 10, "LAITONNONS").
dico("L", 10, "LAIUSSAMES").
dico("L", 10, "LAIUSSASSE").
dico("L", 10, "LAIUSSATES").
dico("L", 10, "LAIUSSERAI").
dico("L", 10, "LAIUSSERAS").
dico("L", 10, "LAIUSSEREZ").
dico("L", 10, "LAIUSSEURS").
dico("L", 10, "LAIUSSEUSE").
dico("L", 10, "LAIUSSIONS").
dico("L", 10, "LALLATIONS").
dico("L", 10, "LAMARCKIEN").
dico("L", 10, "LAMASERIES").
dico("L", 10, "LAMASSIONS").
dico("L", 10, "LAMBDOIDES").
dico("L", 10, "LAMBINAGES").
dico("L", 10, "LAMBINAMES").
dico("L", 10, "LAMBINASSE").
dico("L", 10, "LAMBINATES").
dico("L", 10, "LAMBINERAI").
dico("L", 10, "LAMBINERAS").
dico("L", 10, "LAMBINEREZ").
dico("L", 10, "LAMBINIONS").
dico("L", 10, "LAMBLIASES").
dico("L", 10, "LAMBOURDES").
dico("L", 10, "LAMBREQUIN").
dico("L", 10, "LAMBRISSAI").
dico("L", 10, "LAMBRISSAS").
dico("L", 10, "LAMBRISSAT").
dico("L", 10, "LAMBRISSEE").
dico("L", 10, "LAMBRISSER").
dico("L", 10, "LAMBRISSES").
dico("L", 10, "LAMBRISSEZ").
dico("L", 10, "LAMBRUCHES").
dico("L", 10, "LAMBRUSQUE").
dico("L", 10, "LAMBSWOOLS").
dico("L", 10, "LAMELLAIRE").
dico("L", 10, "LAMELLEUSE").
dico("L", 10, "LAMENTABLE").
dico("L", 10, "LAMENTAMES").
dico("L", 10, "LAMENTASSE").
dico("L", 10, "LAMENTATES").
dico("L", 10, "LAMENTERAI").
dico("L", 10, "LAMENTERAS").
dico("L", 10, "LAMENTEREZ").
dico("L", 10, "LAMENTIONS").
dico("L", 10, "LAMERAIENT").
dico("L", 10, "LAMINAIENT").
dico("L", 10, "LAMINAIRES").
dico("L", 10, "LAMINASSES").
dico("L", 10, "LAMINERAIS").
dico("L", 10, "LAMINERAIT").
dico("L", 10, "LAMINERENT").
dico("L", 10, "LAMINERIES").
dico("L", 10, "LAMINERIEZ").
dico("L", 10, "LAMINERONS").
dico("L", 10, "LAMINERONT").
dico("L", 10, "LAMINEUSES").
dico("L", 10, "LAMPADAIRE").
dico("L", 10, "LAMPASSEES").
dico("L", 10, "LAMPASSENT").
dico("L", 10, "LAMPASSIEZ").
dico("L", 10, "LAMPEMETRE").
dico("L", 10, "LAMPERIONS").
dico("L", 10, "LAMPOURDES").
dico("L", 10, "LAMPRILLON").
dico("L", 10, "LANAUDOISE").
dico("L", 10, "LANCASSENT").
dico("L", 10, "LANCASSIEZ").
dico("L", 10, "LANCEMENTS").
dico("L", 10, "LANCEOLEES").
dico("L", 10, "LANCERIONS").
dico("L", 10, "LANCINAMES").
dico("L", 10, "LANCINANTE").
dico("L", 10, "LANCINANTS").
dico("L", 10, "LANCINASSE").
dico("L", 10, "LANCINATES").
dico("L", 10, "LANCINERAI").
dico("L", 10, "LANCINERAS").
dico("L", 10, "LANCINEREZ").
dico("L", 10, "LANCINIONS").
dico("L", 10, "LANDAMMANN").
dico("L", 10, "LANDAULETS").
dico("L", 10, "LANDERNEAU").
dico("L", 10, "LANDGRAVES").
dico("L", 10, "LANDOLPHIA").
dico("L", 10, "LANDOLPHIE").
dico("L", 10, "LANDSTURMS").
dico("L", 10, "LANGAGIERE").
dico("L", 10, "LANGAGIERS").
dico("L", 10, "LANGEAIENT").
dico("L", 10, "LANGEASSES").
dico("L", 10, "LANGERIONS").
dico("L", 10, "LANGOUREUX").
dico("L", 10, "LANGOUSTES").
dico("L", 10, "LANGUETTES").
dico("L", 10, "LANGUEYAGE").
dico("L", 10, "LANGUEYAIS").
dico("L", 10, "LANGUEYAIT").
dico("L", 10, "LANGUEYANT").
dico("L", 10, "LANGUEYEES").
dico("L", 10, "LANGUEYENT").
dico("L", 10, "LANGUEYERA").
dico("L", 10, "LANGUEYIEZ").
dico("L", 10, "LANGUEYONS").
dico("L", 10, "LANGUIRAIS").
dico("L", 10, "LANGUIRAIT").
dico("L", 10, "LANGUIRENT").
dico("L", 10, "LANGUIRIEZ").
dico("L", 10, "LANGUIRONS").
dico("L", 10, "LANGUIRONT").
dico("L", 10, "LANGUISSES").
dico("L", 10, "LANGUISSEZ").
dico("L", 10, "LANSQUENET").
dico("L", 10, "LANTANIERS").
dico("L", 10, "LANTERNAIS").
dico("L", 10, "LANTERNAIT").
dico("L", 10, "LANTERNANT").
dico("L", 10, "LANTERNEAU").
dico("L", 10, "LANTERNEES").
dico("L", 10, "LANTERNENT").
dico("L", 10, "LANTERNERA").
dico("L", 10, "LANTERNIER").
dico("L", 10, "LANTERNIEZ").
dico("L", 10, "LANTERNONS").
dico("L", 10, "LANTHANIDE").
dico("L", 10, "LANUGINEUX").
dico("L", 10, "LAONNOISES").
dico("L", 10, "LAOTIENNES").
dico("L", 10, "LAPASSIONS").
dico("L", 10, "LAPERAIENT").
dico("L", 10, "LAPIDAIENT").
dico("L", 10, "LAPIDAIRES").
dico("L", 10, "LAPIDASSES").
dico("L", 10, "LAPIDATION").
dico("L", 10, "LAPIDERAIS").
dico("L", 10, "LAPIDERAIT").
dico("L", 10, "LAPIDERENT").
dico("L", 10, "LAPIDERIEZ").
dico("L", 10, "LAPIDERONS").
dico("L", 10, "LAPIDERONT").
dico("L", 10, "LAPIDEUSES").
dico("L", 10, "LAPIDIFIAI").
dico("L", 10, "LAPIDIFIAS").
dico("L", 10, "LAPIDIFIAT").
dico("L", 10, "LAPIDIFIEE").
dico("L", 10, "LAPIDIFIER").
dico("L", 10, "LAPIDIFIES").
dico("L", 10, "LAPIDIFIEZ").
dico("L", 10, "LAPINAIENT").
dico("L", 10, "LAPINASSES").
dico("L", 10, "LAPINERAIS").
dico("L", 10, "LAPINERAIT").
dico("L", 10, "LAPINERENT").
dico("L", 10, "LAPINERIEZ").
dico("L", 10, "LAPINERONS").
dico("L", 10, "LAPINERONT").
dico("L", 10, "LAPINIERES").
dico("L", 10, "LAPINISMES").
dico("L", 10, "LAPLACIENS").
dico("L", 10, "LAQUASSENT").
dico("L", 10, "LAQUASSIEZ").
dico("L", 10, "LAQUERIONS").
dico("L", 10, "LARDASSENT").
dico("L", 10, "LARDASSIEZ").
dico("L", 10, "LARDERIONS").
dico("L", 10, "LARDONNAIS").
dico("L", 10, "LARDONNAIT").
dico("L", 10, "LARDONNANT").
dico("L", 10, "LARDONNEES").
dico("L", 10, "LARDONNENT").
dico("L", 10, "LARDONNERA").
dico("L", 10, "LARDONNIEZ").
dico("L", 10, "LARDONNONS").
dico("L", 10, "LARGHETTOS").
dico("L", 10, "LARGUAIENT").
dico("L", 10, "LARGUASSES").
dico("L", 10, "LARGUERAIS").
dico("L", 10, "LARGUERAIT").
dico("L", 10, "LARGUERENT").
dico("L", 10, "LARGUERIEZ").
dico("L", 10, "LARGUERONS").
dico("L", 10, "LARGUERONT").
dico("L", 10, "LARIFORMES").
dico("L", 10, "LARMOIERAI").
dico("L", 10, "LARMOIERAS").
dico("L", 10, "LARMOIEREZ").
dico("L", 10, "LARMOYAMES").
dico("L", 10, "LARMOYANTE").
dico("L", 10, "LARMOYANTS").
dico("L", 10, "LARMOYASSE").
dico("L", 10, "LARMOYATES").
dico("L", 10, "LARMOYEURS").
dico("L", 10, "LARMOYEUSE").
dico("L", 10, "LARMOYIONS").
dico("L", 10, "LARVICIDES").
dico("L", 10, "LARVICOLES").
dico("L", 10, "LARYNGALES").
dico("L", 10, "LARYNGIENS").
dico("L", 10, "LARYNGITES").
dico("L", 10, "LASCIVETES").
dico("L", 10, "LASCIVITES").
dico("L", 10, "LASSASSENT").
dico("L", 10, "LASSASSIEZ").
dico("L", 10, "LASSERIONS").
dico("L", 10, "LASSITUDES").
dico("L", 10, "LATERALISE").
dico("L", 10, "LATERALITE").
dico("L", 10, "LATHYRISME").
dico("L", 10, "LATICIFERE").
dico("L", 10, "LATICLAVES").
dico("L", 10, "LATIFOLIEE").
dico("L", 10, "LATIFOLIES").
dico("L", 10, "LATIFUNDIA").
dico("L", 10, "LATINISAIS").
dico("L", 10, "LATINISAIT").
dico("L", 10, "LATINISANT").
dico("L", 10, "LATINISEES").
dico("L", 10, "LATINISENT").
dico("L", 10, "LATINISERA").
dico("L", 10, "LATINISIEZ").
dico("L", 10, "LATINISMES").
dico("L", 10, "LATINISONS").
dico("L", 10, "LATINISTES").
dico("L", 10, "LATRODECTE").
dico("L", 10, "LATTASSENT").
dico("L", 10, "LATTASSIEZ").
dico("L", 10, "LATTERIONS").
dico("L", 10, "LAUDANISEE").
dico("L", 10, "LAUDANISES").
dico("L", 10, "LAUDATEURS").
dico("L", 10, "LAUDATIVES").
dico("L", 10, "LAUDATRICE").
dico("L", 10, "LAUDIENNES").
dico("L", 10, "LAURENTIEN").
dico("L", 10, "LAUSANNOIS").
dico("L", 10, "LAVABILITE").
dico("L", 10, "LAVALLIERE").
dico("L", 10, "LAVALLOISE").
dico("L", 10, "LAVANDIERE").
dico("L", 10, "LAVASSIONS").
dico("L", 10, "LAVATORIES").
dico("L", 10, "LAVERAIENT").
dico("L", 10, "LAWRENCIUM").
dico("L", 10, "LAYASSIONS").
dico("L", 10, "LAYERAIENT").
dico("L", 10, "LAZARISTES").
dico("L", 10, "LAZZARONES").
dico("L", 10, "LEADERSHIP").
dico("L", 10, "LECHASSENT").
dico("L", 10, "LECHASSIEZ").
dico("L", 10, "LECHEFRITE").
dico("L", 10, "LECHEMENTS").
dico("L", 10, "LECHERIONS").
dico("L", 10, "LECITHINES").
dico("L", 10, "LEDONIENNE").
dico("L", 10, "LEGALEMENT").
dico("L", 10, "LEGALISAIS").
dico("L", 10, "LEGALISAIT").
dico("L", 10, "LEGALISANT").
dico("L", 10, "LEGALISEES").
dico("L", 10, "LEGALISENT").
dico("L", 10, "LEGALISERA").
dico("L", 10, "LEGALISIEZ").
dico("L", 10, "LEGALISMES").
dico("L", 10, "LEGALISONS").
dico("L", 10, "LEGALISTES").
dico("L", 10, "LEGATAIRES").
dico("L", 10, "LEGENDAIRE").
dico("L", 10, "LEGENDAMES").
dico("L", 10, "LEGENDASSE").
dico("L", 10, "LEGENDATES").
dico("L", 10, "LEGENDERAI").
dico("L", 10, "LEGENDERAS").
dico("L", 10, "LEGENDEREZ").
dico("L", 10, "LEGENDIONS").
dico("L", 10, "LEGEREMENT").
dico("L", 10, "LEGIFERAIS").
dico("L", 10, "LEGIFERAIT").
dico("L", 10, "LEGIFERANT").
dico("L", 10, "LEGIFERENT").
dico("L", 10, "LEGIFERERA").
dico("L", 10, "LEGIFERIEZ").
dico("L", 10, "LEGIFERONS").
dico("L", 10, "LEGIONELLA").
dico("L", 10, "LEGIONELLE").
dico("L", 10, "LEGISLATIF").
dico("L", 10, "LEGITIMAIS").
dico("L", 10, "LEGITIMAIT").
dico("L", 10, "LEGITIMANT").
dico("L", 10, "LEGITIMEES").
dico("L", 10, "LEGITIMENT").
dico("L", 10, "LEGITIMERA").
dico("L", 10, "LEGITIMIEZ").
dico("L", 10, "LEGITIMITE").
dico("L", 10, "LEGITIMONS").
dico("L", 10, "LEGUASSENT").
dico("L", 10, "LEGUASSIEZ").
dico("L", 10, "LEGUERIONS").
dico("L", 10, "LEGUMIERES").
dico("L", 10, "LEGUMINEUX").
dico("L", 10, "LEIOMYOMES").
dico("L", 10, "LEIPZIGOIS").
dico("L", 10, "LEISHMANIA").
dico("L", 10, "LEISHMANIE").
dico("L", 10, "LEITMOTIVE").
dico("L", 10, "LEITMOTIVS").
dico("L", 10, "LEMANIQUES").
dico("L", 10, "LEMMATISAI").
dico("L", 10, "LEMMATISAS").
dico("L", 10, "LEMMATISAT").
dico("L", 10, "LEMMATISEE").
dico("L", 10, "LEMMATISER").
dico("L", 10, "LEMMATISES").
dico("L", 10, "LEMMATISEZ").
dico("L", 10, "LEMNISCATE").
dico("L", 10, "LENDEMAINS").
dico("L", 10, "LENIFIAMES").
dico("L", 10, "LENIFIANTE").
dico("L", 10, "LENIFIANTS").
dico("L", 10, "LENIFIASSE").
dico("L", 10, "LENIFIATES").
dico("L", 10, "LENIFIERAI").
dico("L", 10, "LENIFIERAS").
dico("L", 10, "LENIFIEREZ").
dico("L", 10, "LENIFIIONS").
dico("L", 10, "LENINISMES").
dico("L", 10, "LENINISTES").
dico("L", 10, "LENTICELLE").
dico("L", 10, "LENTICULEE").
dico("L", 10, "LENTICULES").
dico("L", 10, "LENTIFORME").
dico("L", 10, "LENTIGINES").
dico("L", 10, "LENTILLONS").
dico("L", 10, "LENTISQUES").
dico("L", 10, "LENTIVIRUS").
dico("L", 10, "LEOPARDEES").
dico("L", 10, "LEPIDOLITE").
dico("L", 10, "LEPIDOSTEE").
dico("L", 10, "LEPISOSTEE").
dico("L", 10, "LEPROLOGIE").
dico("L", 10, "LEPROLOGUE").
dico("L", 10, "LEPROSERIE").
dico("L", 10, "LEPTONIQUE").
dico("L", 10, "LEPTOSOMES").
dico("L", 10, "LEPTOSPIRE").
dico("L", 10, "LEPTOTENES").
dico("L", 10, "LESASSIONS").
dico("L", 10, "LESBIENNES").
dico("L", 10, "LESERAIENT").
dico("L", 10, "LESINAIENT").
dico("L", 10, "LESINASSES").
dico("L", 10, "LESINERAIS").
dico("L", 10, "LESINERAIT").
dico("L", 10, "LESINERENT").
dico("L", 10, "LESINERIES").
dico("L", 10, "LESINERIEZ").
dico("L", 10, "LESINERONS").
dico("L", 10, "LESINERONT").
dico("L", 10, "LESINEUSES").
dico("L", 10, "LESIONNAIS").
dico("L", 10, "LESIONNAIT").
dico("L", 10, "LESIONNANT").
dico("L", 10, "LESIONNEES").
dico("L", 10, "LESIONNELS").
dico("L", 10, "LESIONNENT").
dico("L", 10, "LESIONNERA").
dico("L", 10, "LESIONNIEZ").
dico("L", 10, "LESIONNONS").
dico("L", 10, "LESOTHANES").
dico("L", 10, "LESQUELLES").
dico("L", 10, "LESSIVABLE").
dico("L", 10, "LESSIVAGES").
dico("L", 10, "LESSIVAMES").
dico("L", 10, "LESSIVASSE").
dico("L", 10, "LESSIVATES").
dico("L", 10, "LESSIVERAI").
dico("L", 10, "LESSIVERAS").
dico("L", 10, "LESSIVEREZ").
dico("L", 10, "LESSIVEURS").
dico("L", 10, "LESSIVEUSE").
dico("L", 10, "LESSIVIELS").
dico("L", 10, "LESSIVIERS").
dico("L", 10, "LESSIVIONS").
dico("L", 10, "LESTASSENT").
dico("L", 10, "LESTASSIEZ").
dico("L", 10, "LESTERIONS").
dico("L", 10, "LETHARGIES").
dico("L", 10, "LETHEENNES").
dico("L", 10, "LETTRAIENT").
dico("L", 10, "LETTRASSES").
dico("L", 10, "LETTRERAIS").
dico("L", 10, "LETTRERAIT").
dico("L", 10, "LETTRERENT").
dico("L", 10, "LETTRERIEZ").
dico("L", 10, "LETTRERONS").
dico("L", 10, "LETTRERONT").
dico("L", 10, "LETTREUSES").
dico("L", 10, "LETTRISMES").
dico("L", 10, "LETTRISTES").
dico("L", 10, "LEUCEMIQUE").
dico("L", 10, "LEUCOBRYUM").
dico("L", 10, "LEUCOCYTES").
dico("L", 10, "LEUCODERME").
dico("L", 10, "LEUCOPENIE").
dico("L", 10, "LEUCORRHEE").
dico("L", 10, "LEUCOTOMIE").
dico("L", 10, "LEURRAIENT").
dico("L", 10, "LEURRASSES").
dico("L", 10, "LEURRERAIS").
dico("L", 10, "LEURRERAIT").
dico("L", 10, "LEURRERENT").
dico("L", 10, "LEURRERIEZ").
dico("L", 10, "LEURRERONS").
dico("L", 10, "LEURRERONT").
dico("L", 10, "LEVANTINES").
dico("L", 10, "LEVASSIONS").
dico("L", 10, "LEVERAIENT").
dico("L", 10, "LEVIGATION").
dico("L", 10, "LEVIGEAMES").
dico("L", 10, "LEVIGEASSE").
dico("L", 10, "LEVIGEATES").
dico("L", 10, "LEVIGERAIS").
dico("L", 10, "LEVIGERAIT").
dico("L", 10, "LEVIGERENT").
dico("L", 10, "LEVIGERIEZ").
dico("L", 10, "LEVIGERONS").
dico("L", 10, "LEVIGERONT").
dico("L", 10, "LEVIROSTRE").
dico("L", 10, "LEVISIENNE").
dico("L", 10, "LEVITAIENT").
dico("L", 10, "LEVITASSES").
dico("L", 10, "LEVITATION").
dico("L", 10, "LEVITERAIS").
dico("L", 10, "LEVITERAIT").
dico("L", 10, "LEVITERENT").
dico("L", 10, "LEVITERIEZ").
dico("L", 10, "LEVITERONS").
dico("L", 10, "LEVITERONT").
dico("L", 10, "LEVITIQUES").
dico("L", 10, "LEVRETTAIS").
dico("L", 10, "LEVRETTAIT").
dico("L", 10, "LEVRETTANT").
dico("L", 10, "LEVRETTEES").
dico("L", 10, "LEVRETTENT").
dico("L", 10, "LEVRETTERA").
dico("L", 10, "LEVRETTIEZ").
dico("L", 10, "LEVRETTONS").
dico("L", 10, "LEVURAIENT").
dico("L", 10, "LEVURASSES").
dico("L", 10, "LEVURERAIS").
dico("L", 10, "LEVURERAIT").
dico("L", 10, "LEVURERENT").
dico("L", 10, "LEVURERIEZ").
dico("L", 10, "LEVURERONS").
dico("L", 10, "LEVURERONT").
dico("L", 10, "LEXICALISA").
dico("L", 10, "LEXICALISE").
dico("L", 10, "LEZARDAMES").
dico("L", 10, "LEZARDASSE").
dico("L", 10, "LEZARDATES").
dico("L", 10, "LEZARDERAI").
dico("L", 10, "LEZARDERAS").
dico("L", 10, "LEZARDEREZ").
dico("L", 10, "LEZARDIONS").
dico("L", 10, "LIAISONNAI").
dico("L", 10, "LIAISONNAS").
dico("L", 10, "LIAISONNAT").
dico("L", 10, "LIAISONNEE").
dico("L", 10, "LIAISONNER").
dico("L", 10, "LIAISONNES").
dico("L", 10, "LIAISONNEZ").
dico("L", 10, "LIANESCENT").
dico("L", 10, "LIARDAIENT").
dico("L", 10, "LIARDASSES").
dico("L", 10, "LIARDERAIS").
dico("L", 10, "LIARDERAIT").
dico("L", 10, "LIARDERENT").
dico("L", 10, "LIARDERIEZ").
dico("L", 10, "LIARDERONS").
dico("L", 10, "LIARDERONT").
dico("L", 10, "LIBANAISES").
dico("L", 10, "LIBELLAMES").
dico("L", 10, "LIBELLASSE").
dico("L", 10, "LIBELLATES").
dico("L", 10, "LIBELLERAI").
dico("L", 10, "LIBELLERAS").
dico("L", 10, "LIBELLEREZ").
dico("L", 10, "LIBELLIONS").
dico("L", 10, "LIBELLISTE").
dico("L", 10, "LIBELLULES").
dico("L", 10, "LIBERABLES").
dico("L", 10, "LIBERAIENT").
dico("L", 10, "LIBERALISA").
dico("L", 10, "LIBERALISE").
dico("L", 10, "LIBERALITE").
dico("L", 10, "LIBERASSES").
dico("L", 10, "LIBERATEUR").
dico("L", 10, "LIBERATION").
dico("L", 10, "LIBERERAIS").
dico("L", 10, "LIBERERAIT").
dico("L", 10, "LIBERERENT").
dico("L", 10, "LIBERERIEZ").
dico("L", 10, "LIBERERONS").
dico("L", 10, "LIBERERONT").
dico("L", 10, "LIBERIENNE").
dico("L", 10, "LIBERISTES").
dico("L", 10, "LIBERTAIRE").
dico("L", 10, "LIBERTINES").
dico("L", 10, "LIBIDINALE").
dico("L", 10, "LIBIDINAUX").
dico("L", 10, "LIBIDINEUX").
dico("L", 10, "LIBRAIRIES").
dico("L", 10, "LIBRATIONS").
dico("L", 10, "LICENCIAIS").
dico("L", 10, "LICENCIAIT").
dico("L", 10, "LICENCIANT").
dico("L", 10, "LICENCIEES").
dico("L", 10, "LICENCIENT").
dico("L", 10, "LICENCIERA").
dico("L", 10, "LICENCIEUX").
dico("L", 10, "LICENCIIEZ").
dico("L", 10, "LICENCIONS").
dico("L", 10, "LICHASSENT").
dico("L", 10, "LICHASSIEZ").
dico("L", 10, "LICHERIONS").
dico("L", 10, "LICITAIENT").
dico("L", 10, "LICITASSES").
dico("L", 10, "LICITATION").
dico("L", 10, "LICITEMENT").
dico("L", 10, "LICITERAIS").
dico("L", 10, "LICITERAIT").
dico("L", 10, "LICITERENT").
dico("L", 10, "LICITERIEZ").
dico("L", 10, "LICITERONS").
dico("L", 10, "LICITERONT").
dico("L", 10, "LIDOCAINES").
dico("L", 10, "LIEGEAIENT").
dico("L", 10, "LIEGEASSES").
dico("L", 10, "LIEGEOISES").
dico("L", 10, "LIEGERIONS").
dico("L", 10, "LIEUTENANT").
dico("L", 10, "LIFTASSENT").
dico("L", 10, "LIFTASSIEZ").
dico("L", 10, "LIFTERIONS").
dico("L", 10, "LIGATURAIS").
dico("L", 10, "LIGATURAIT").
dico("L", 10, "LIGATURANT").
dico("L", 10, "LIGATUREES").
dico("L", 10, "LIGATURENT").
dico("L", 10, "LIGATURERA").
dico("L", 10, "LIGATURIEZ").
dico("L", 10, "LIGATURONS").
dico("L", 10, "LIGERIENNE").
dico("L", 10, "LIGNAGERES").
dico("L", 10, "LIGNASSENT").
dico("L", 10, "LIGNASSIEZ").
dico("L", 10, "LIGNERIONS").
dico("L", 10, "LIGNEROLLE").
dico("L", 10, "LIGNICOLES").
dico("L", 10, "LIGNIFIAIS").
dico("L", 10, "LIGNIFIAIT").
dico("L", 10, "LIGNIFIANT").
dico("L", 10, "LIGNIFIEES").
dico("L", 10, "LIGNIFIENT").
dico("L", 10, "LIGNIFIERA").
dico("L", 10, "LIGNIFIIEZ").
dico("L", 10, "LIGNIFIONS").
dico("L", 10, "LIGNIVORES").
dico("L", 10, "LIGNOMETRE").
dico("L", 10, "LIGOTAIENT").
dico("L", 10, "LIGOTASSES").
dico("L", 10, "LIGOTERAIS").
dico("L", 10, "LIGOTERAIT").
dico("L", 10, "LIGOTERENT").
dico("L", 10, "LIGOTERIEZ").
dico("L", 10, "LIGOTERONS").
dico("L", 10, "LIGOTERONT").
dico("L", 10, "LIGUASSENT").
dico("L", 10, "LIGUASSIEZ").
dico("L", 10, "LIGUERIONS").
dico("L", 10, "LIGURIENNE").
dico("L", 10, "LILANGENIS").
dico("L", 10, "LILIIFLORE").
dico("L", 10, "LIMASSIONS").
dico("L", 10, "LIMENIENNE").
dico("L", 10, "LIMERAIENT").
dico("L", 10, "LIMETTIERS").
dico("L", 10, "LIMINAIRES").
dico("L", 10, "LIMITABLES").
dico("L", 10, "LIMITAIENT").
dico("L", 10, "LIMITASSES").
dico("L", 10, "LIMITATIFS").
dico("L", 10, "LIMITATION").
dico("L", 10, "LIMITATIVE").
dico("L", 10, "LIMITERAIS").
dico("L", 10, "LIMITERAIT").
dico("L", 10, "LIMITERENT").
dico("L", 10, "LIMITERIEZ").
dico("L", 10, "LIMITERONS").
dico("L", 10, "LIMITERONT").
dico("L", 10, "LIMITROPHE").
dico("L", 10, "LIMNOLOGIE").
dico("L", 10, "LIMOGEAGES").
dico("L", 10, "LIMOGEAMES").
dico("L", 10, "LIMOGEASSE").
dico("L", 10, "LIMOGEATES").
dico("L", 10, "LIMOGERAIS").
dico("L", 10, "LIMOGERAIT").
dico("L", 10, "LIMOGERENT").
dico("L", 10, "LIMOGERIEZ").
dico("L", 10, "LIMOGERONS").
dico("L", 10, "LIMOGERONT").
dico("L", 10, "LIMONADIER").
dico("L", 10, "LIMONAIRES").
dico("L", 10, "LIMONEUSES").
dico("L", 10, "LIMONIERES").
dico("L", 10, "LIMOSELLES").
dico("L", 10, "LIMOUGEAUD").
dico("L", 10, "LIMOUSINAI").
dico("L", 10, "LIMOUSINAS").
dico("L", 10, "LIMOUSINAT").
dico("L", 10, "LIMOUSINEE").
dico("L", 10, "LIMOUSINER").
dico("L", 10, "LIMOUSINES").
dico("L", 10, "LIMOUSINEZ").
dico("L", 10, "LIMPIDITES").
dico("L", 10, "LINEAMENTS").
dico("L", 10, "LINEARITES").
dico("L", 10, "LINEATURES").
dico("L", 10, "LINGOTAMES").
dico("L", 10, "LINGOTASSE").
dico("L", 10, "LINGOTATES").
dico("L", 10, "LINGOTERAI").
dico("L", 10, "LINGOTERAS").
dico("L", 10, "LINGOTEREZ").
dico("L", 10, "LINGOTIERE").
dico("L", 10, "LINGOTIERS").
dico("L", 10, "LINGOTIONS").
dico("L", 10, "LINGUATULE").
dico("L", 10, "LINGUETTES").
dico("L", 10, "LINGUISTES").
dico("L", 10, "LINNEENNES").
dico("L", 10, "LINOLEINES").
dico("L", 10, "LINOLEIQUE").
dico("L", 10, "LINOTYPIES").
dico("L", 10, "LIPIDEMIES").
dico("L", 10, "LIPIDIQUES").
dico("L", 10, "LIPOCHROME").
dico("L", 10, "LIPOGENESE").
dico("L", 10, "LIPOGRAMME").
dico("L", 10, "LIPOIDIQUE").
dico("L", 10, "LIPOPHILES").
dico("L", 10, "LIPOPHOBES").
dico("L", 10, "LIPOSUCAIS").
dico("L", 10, "LIPOSUCAIT").
dico("L", 10, "LIPOSUCANT").
dico("L", 10, "LIPOSUCEES").
dico("L", 10, "LIPOSUCENT").
dico("L", 10, "LIPOSUCERA").
dico("L", 10, "LIPOSUCIEZ").
dico("L", 10, "LIPOSUCONS").
dico("L", 10, "LIPOTHYMIE").
dico("L", 10, "LIPOTROPES").
dico("L", 10, "LIPOVACCIN").
dico("L", 10, "LIQUATIONS").
dico("L", 10, "LIQUEFIAIS").
dico("L", 10, "LIQUEFIAIT").
dico("L", 10, "LIQUEFIANT").
dico("L", 10, "LIQUEFIEES").
dico("L", 10, "LIQUEFIENT").
dico("L", 10, "LIQUEFIERA").
dico("L", 10, "LIQUEFIIEZ").
dico("L", 10, "LIQUEFIONS").
dico("L", 10, "LIQUIDABLE").
dico("L", 10, "LIQUIDAMES").
dico("L", 10, "LIQUIDASSE").
dico("L", 10, "LIQUIDATES").
dico("L", 10, "LIQUIDATIF").
dico("L", 10, "LIQUIDERAI").
dico("L", 10, "LIQUIDERAS").
dico("L", 10, "LIQUIDEREZ").
dico("L", 10, "LIQUIDIENS").
dico("L", 10, "LIQUIDIONS").
dico("L", 10, "LIQUIDITES").
dico("L", 10, "LIQUOREUSE").
dico("L", 10, "LIQUORISTE").
dico("L", 10, "LISBONNAIS").
dico("L", 10, "LISBONNINE").
dico("L", 10, "LISBONNINS").
dico("L", 10, "LISERAIENT").
dico("L", 10, "LISERASSES").
dico("L", 10, "LISERERAIS").
dico("L", 10, "LISERERAIT").
dico("L", 10, "LISERERENT").
dico("L", 10, "LISERERIEZ").
dico("L", 10, "LISERERONS").
dico("L", 10, "LISERERONT").
dico("L", 10, "LISIBILITE").
dico("L", 10, "LISSASSENT").
dico("L", 10, "LISSASSIEZ").
dico("L", 10, "LISSERIONS").
dico("L", 10, "LISTASSENT").
dico("L", 10, "LISTASSIEZ").
dico("L", 10, "LISTERIONS").
dico("L", 10, "LISTERIOSE").
dico("L", 10, "LITASSIONS").
dico("L", 10, "LITERAIENT").
dico("L", 10, "LITHERGOLS").
dico("L", 10, "LITHODOMES").
dico("L", 10, "LITHOGENES").
dico("L", 10, "LITHOLOGIE").
dico("L", 10, "LITHOPHAGE").
dico("L", 10, "LITHOPONES").
dico("L", 10, "LITHOTOMIE").
dico("L", 10, "LITHUANIEN").
dico("L", 10, "LITIGANTES").
dico("L", 10, "LITIGIEUSE").
dico("L", 10, "LITRASSENT").
dico("L", 10, "LITRASSIEZ").
dico("L", 10, "LITRERIONS").
dico("L", 10, "LITTERAIRE").
dico("L", 10, "LITTERALES").
dico("L", 10, "LITTORALES").
dico("L", 10, "LITTORINES").
dico("L", 10, "LITUANIENS").
dico("L", 10, "LITURGIQUE").
dico("L", 10, "LITURGISTE").
dico("L", 10, "LIVOURNAIS").
dico("L", 10, "LIVRAISONS").
dico("L", 10, "LIVRASSENT").
dico("L", 10, "LIVRASSIEZ").
dico("L", 10, "LIVRERIONS").
dico("L", 10, "LIVRESQUES").
dico("L", 10, "LIXIVIAMES").
dico("L", 10, "LIXIVIASSE").
dico("L", 10, "LIXIVIATES").
dico("L", 10, "LIXIVIERAI").
dico("L", 10, "LIXIVIERAS").
dico("L", 10, "LIXIVIEREZ").
dico("L", 10, "LIXIVIIONS").
dico("L", 10, "LOBASSIONS").
dico("L", 10, "LOBBYISMES").
dico("L", 10, "LOBBYISTES").
dico("L", 10, "LOBECTOMIE").
dico("L", 10, "LOBERAIENT").
dico("L", 10, "LOBOTOMIES").
dico("L", 10, "LOBOTOMISA").
dico("L", 10, "LOBOTOMISE").
dico("L", 10, "LOBULAIRES").
dico("L", 10, "LOBULEUSES").
dico("L", 10, "LOCALEMENT").
dico("L", 10, "LOCALISAIS").
dico("L", 10, "LOCALISAIT").
dico("L", 10, "LOCALISANT").
dico("L", 10, "LOCALISEES").
dico("L", 10, "LOCALISENT").
dico("L", 10, "LOCALISERA").
dico("L", 10, "LOCALISIEZ").
dico("L", 10, "LOCALISONS").
dico("L", 10, "LOCATAIRES").
dico("L", 10, "LOCATRICES").
dico("L", 10, "LOCHASSENT").
dico("L", 10, "LOCHASSIEZ").
dico("L", 10, "LOCHERIONS").
dico("L", 10, "LOCKOUTAIS").
dico("L", 10, "LOCKOUTAIT").
dico("L", 10, "LOCKOUTANT").
dico("L", 10, "LOCKOUTEES").
dico("L", 10, "LOCKOUTENT").
dico("L", 10, "LOCKOUTERA").
dico("L", 10, "LOCKOUTIEZ").
dico("L", 10, "LOCKOUTONS").
dico("L", 10, "LOCOMOBILE").
dico("L", 10, "LOCOMOTEUR").
dico("L", 10, "LOCOMOTIFS").
dico("L", 10, "LOCOMOTION").
dico("L", 10, "LOCOMOTIVE").
dico("L", 10, "LOCULAIRES").
dico("L", 10, "LOCULEUSES").
dico("L", 10, "LOCUTRICES").
dico("L", 10, "LOFASSIONS").
dico("L", 10, "LOFERAIENT").
dico("L", 10, "LOGARITHME").
dico("L", 10, "LOGEASSENT").
dico("L", 10, "LOGEASSIEZ").
dico("L", 10, "LOGERAIENT").
dico("L", 10, "LOGICIELLE").
dico("L", 10, "LOGICIENNE").
dico("L", 10, "LOGICISMES").
dico("L", 10, "LOGIGRAMME").
dico("L", 10, "LOGIGRILLE").
dico("L", 10, "LOGISTIQUE").
dico("L", 10, "LOGITHEQUE").
dico("L", 10, "LOGOGRAMME").
dico("L", 10, "LOGOGRAPHE").
dico("L", 10, "LOGOGRIPHE").
dico("L", 10, "LOGOMACHIE").
dico("L", 10, "LOGOPATHIE").
dico("L", 10, "LOGOPEDIES").
dico("L", 10, "LOGORRHEES").
dico("L", 10, "LOGOTHETES").
dico("L", 10, "LOGUASSENT").
dico("L", 10, "LOGUASSIEZ").
dico("L", 10, "LOGUERIONS").
dico("L", 10, "LOINTAINES").
dico("L", 10, "LOMBALGIES").
dico("L", 10, "LOMBOSACRE").
dico("L", 10, "LOMBOSTATS").
dico("L", 10, "LOMECHUSES").
dico("L", 10, "LONDONIENS").
dico("L", 10, "LONGEAIENT").
dico("L", 10, "LONGEASSES").
dico("L", 10, "LONGERIONS").
dico("L", 10, "LONGEVITES").
dico("L", 10, "LONGICORNE").
dico("L", 10, "LONGILIGNE").
dico("L", 10, "LONGIPENNE").
dico("L", 10, "LONGITUDES").
dico("L", 10, "LONGUEMENT").
dico("L", 10, "LONGUETTES").
dico("L", 10, "LOPHOPHORE").
dico("L", 10, "LOQUACITES").
dico("L", 10, "LOQUETAMES").
dico("L", 10, "LOQUETASSE").
dico("L", 10, "LOQUETATES").
dico("L", 10, "LOQUETEAUX").
dico("L", 10, "LOQUETEUSE").
dico("L", 10, "LOQUETIONS").
dico("L", 10, "LOQUETTENT").
dico("L", 10, "LOQUETTERA").
dico("L", 10, "LORGNAIENT").
dico("L", 10, "LORGNASSES").
dico("L", 10, "LORGNERAIS").
dico("L", 10, "LORGNERAIT").
dico("L", 10, "LORGNERENT").
dico("L", 10, "LORGNERIEZ").
dico("L", 10, "LORGNERONS").
dico("L", 10, "LORGNERONT").
dico("L", 10, "LORGNETTES").
dico("L", 10, "LORGNEUSES").
dico("L", 10, "LORICAIRES").
dico("L", 10, "LORIENTAIS").
dico("L", 10, "LOSANGIQUE").
dico("L", 10, "LOTIONNAIS").
dico("L", 10, "LOTIONNAIT").
dico("L", 10, "LOTIONNANT").
dico("L", 10, "LOTIONNEES").
dico("L", 10, "LOTIONNENT").
dico("L", 10, "LOTIONNERA").
dico("L", 10, "LOTIONNIEZ").
dico("L", 10, "LOTIONNONS").
dico("L", 10, "LOTIRAIENT").
dico("L", 10, "LOTISSEURS").
dico("L", 10, "LOTISSEUSE").
dico("L", 10, "LOTISSIONS").
dico("L", 10, "LOUANGEAIS").
dico("L", 10, "LOUANGEAIT").
dico("L", 10, "LOUANGEANT").
dico("L", 10, "LOUANGEONS").
dico("L", 10, "LOUANGERAI").
dico("L", 10, "LOUANGERAS").
dico("L", 10, "LOUANGEREZ").
dico("L", 10, "LOUANGEURS").
dico("L", 10, "LOUANGEUSE").
dico("L", 10, "LOUANGIONS").
dico("L", 10, "LOUASSIONS").
dico("L", 10, "LOUCHAIENT").
dico("L", 10, "LOUCHASSES").
dico("L", 10, "LOUCHEBEME").
dico("L", 10, "LOUCHEMENT").
dico("L", 10, "LOUCHERAIS").
dico("L", 10, "LOUCHERAIT").
dico("L", 10, "LOUCHERBEM").
dico("L", 10, "LOUCHERENT").
dico("L", 10, "LOUCHERIES").
dico("L", 10, "LOUCHERIEZ").
dico("L", 10, "LOUCHERONS").
dico("L", 10, "LOUCHERONT").
dico("L", 10, "LOUCHEUSES").
dico("L", 10, "LOUCHIRAIS").
dico("L", 10, "LOUCHIRAIT").
dico("L", 10, "LOUCHIRENT").
dico("L", 10, "LOUCHIRIEZ").
dico("L", 10, "LOUCHIRONS").
dico("L", 10, "LOUCHIRONT").
dico("L", 10, "LOUCHISSES").
dico("L", 10, "LOUCHISSEZ").
dico("L", 10, "LOUCHONNES").
dico("L", 10, "LOUERAIENT").
dico("L", 10, "LOUFTINGUE").
dico("L", 10, "LOULOUTTES").
dico("L", 10, "LOUPASSENT").
dico("L", 10, "LOUPASSIEZ").
dico("L", 10, "LOUPERIONS").
dico("L", 10, "LOUPIOTTES").
dico("L", 10, "LOURASSENT").
dico("L", 10, "LOURASSIEZ").
dico("L", 10, "LOURDAIENT").
dico("L", 10, "LOURDAISES").
dico("L", 10, "LOURDASSES").
dico("L", 10, "LOURDAUDES").
dico("L", 10, "LOURDEMENT").
dico("L", 10, "LOURDERAIS").
dico("L", 10, "LOURDERAIT").
dico("L", 10, "LOURDERENT").
dico("L", 10, "LOURDERIES").
dico("L", 10, "LOURDERIEZ").
dico("L", 10, "LOURDERONS").
dico("L", 10, "LOURDERONT").
dico("L", 10, "LOURDINGUE").
dico("L", 10, "LOURERIONS").
dico("L", 10, "LOUTRERIES").
dico("L", 10, "LOUVANISTE").
dico("L", 10, "LOUVASSENT").
dico("L", 10, "LOUVASSIEZ").
dico("L", 10, "LOUVERIONS").
dico("L", 10, "LOUVETAMES").
dico("L", 10, "LOUVETASSE").
dico("L", 10, "LOUVETATES").
dico("L", 10, "LOUVETEAUX").
dico("L", 10, "LOUVETERIE").
dico("L", 10, "LOUVETIERS").
dico("L", 10, "LOUVETIONS").
dico("L", 10, "LOUVETTENT").
dico("L", 10, "LOUVETTERA").
dico("L", 10, "LOUVIEROIS").
dico("L", 10, "LOUVOIERAI").
dico("L", 10, "LOUVOIERAS").
dico("L", 10, "LOUVOIEREZ").
dico("L", 10, "LOUVOYAGES").
dico("L", 10, "LOUVOYAMES").
dico("L", 10, "LOUVOYASSE").
dico("L", 10, "LOUVOYATES").
dico("L", 10, "LOUVOYIONS").
dico("L", 10, "LOVASSIONS").
dico("L", 10, "LOVERAIENT").
dico("L", 10, "LOXODROMIE").
dico("L", 10, "LOYALEMENT").
dico("L", 10, "LOYALISMES").
dico("L", 10, "LOYALISTES").
dico("L", 10, "LOZERIENNE").
dico("L", 10, "LUANDAISES").
dico("L", 10, "LUBRICITES").
dico("L", 10, "LUBRIFIAIS").
dico("L", 10, "LUBRIFIAIT").
dico("L", 10, "LUBRIFIANT").
dico("L", 10, "LUBRIFIEES").
dico("L", 10, "LUBRIFIENT").
dico("L", 10, "LUBRIFIERA").
dico("L", 10, "LUBRIFIIEZ").
dico("L", 10, "LUBRIFIONS").
dico("L", 10, "LUCANIENNE").
dico("L", 10, "LUCANISTES").
dico("L", 10, "LUCERNAIRE").
dico("L", 10, "LUCERNOISE").
dico("L", 10, "LUCIDEMENT").
dico("L", 10, "LUCIFERASE").
dico("L", 10, "LUCIFERIEN").
dico("L", 10, "LUCIFERINE").
dico("L", 10, "LUCIMETRES").
dico("L", 10, "LUCQUOISES").
dico("L", 10, "LUCRATIVES").
dico("L", 10, "LUDOLOGUES").
dico("L", 10, "LUDOTHEQUE").
dico("L", 10, "LUGEASSENT").
dico("L", 10, "LUGEASSIEZ").
dico("L", 10, "LUGERAIENT").
dico("L", 10, "LUISISSENT").
dico("L", 10, "LUISISSIEZ").
dico("L", 10, "LUMACHELLE").
dico("L", 10, "LUMINAIRES").
dico("L", 10, "LUMINANCES").
dico("L", 10, "LUMINEUSES").
dico("L", 10, "LUMINIFERE").
dico("L", 10, "LUMINISMES").
dico("L", 10, "LUMINISTES").
dico("L", 10, "LUMINOSITE").
dico("L", 10, "LUNATIQUES").
dico("L", 10, "LUNCHAIENT").
dico("L", 10, "LUNCHASSES").
dico("L", 10, "LUNCHERAIS").
dico("L", 10, "LUNCHERAIT").
dico("L", 10, "LUNCHERENT").
dico("L", 10, "LUNCHERIEZ").
dico("L", 10, "LUNCHERONS").
dico("L", 10, "LUNCHERONT").
dico("L", 10, "LUNETIERES").
dico("L", 10, "LUNETTERIE").
dico("L", 10, "LUNETTIERE").
dico("L", 10, "LUNETTIERS").
dico("L", 10, "LUPERCALES").
dico("L", 10, "LUSAKOISES").
dico("L", 10, "LUSITAINES").
dico("L", 10, "LUSITANIEN").
dico("L", 10, "LUSOPHONES").
dico("L", 10, "LUSTRAIENT").
dico("L", 10, "LUSTRASSES").
dico("L", 10, "LUSTRATION").
dico("L", 10, "LUSTRERAIS").
dico("L", 10, "LUSTRERAIT").
dico("L", 10, "LUSTRERENT").
dico("L", 10, "LUSTRERIES").
dico("L", 10, "LUSTRERIEZ").
dico("L", 10, "LUSTRERONS").
dico("L", 10, "LUSTRERONT").
dico("L", 10, "LUSTREUSES").
dico("L", 10, "LUTASSIONS").
dico("L", 10, "LUTECIENNE").
dico("L", 10, "LUTEINIQUE").
dico("L", 10, "LUTERAIENT").
dico("L", 10, "LUTETIENNE").
dico("L", 10, "LUTHERIENS").
dico("L", 10, "LUTINAIENT").
dico("L", 10, "LUTINASSES").
dico("L", 10, "LUTINERAIS").
dico("L", 10, "LUTINERAIT").
dico("L", 10, "LUTINERENT").
dico("L", 10, "LUTINERIES").
dico("L", 10, "LUTINERIEZ").
dico("L", 10, "LUTINERONS").
dico("L", 10, "LUTINERONT").
dico("L", 10, "LUTTASSENT").
dico("L", 10, "LUTTASSIEZ").
dico("L", 10, "LUTTERIONS").
dico("L", 10, "LUXASSIONS").
dico("L", 10, "LUXERAIENT").
dico("L", 10, "LUXURIANCE").
dico("L", 10, "LUXURIANTE").
dico("L", 10, "LUXURIANTS").
dico("L", 10, "LUXURIEUSE").
dico("L", 10, "LUZERNIERE").
dico("L", 10, "LYCOPERDON").
dico("L", 10, "LYCOPHYTES").
dico("L", 10, "LYMPHOCYTE").
dico("L", 10, "LYMPHOIDES").
dico("L", 10, "LYMPHOKINE").
dico("L", 10, "LYNCHAIENT").
dico("L", 10, "LYNCHASSES").
dico("L", 10, "LYNCHERAIS").
dico("L", 10, "LYNCHERAIT").
dico("L", 10, "LYNCHERENT").
dico("L", 10, "LYNCHERIEZ").
dico("L", 10, "LYNCHERONS").
dico("L", 10, "LYNCHERONT").
dico("L", 10, "LYNCHEUSES").
dico("L", 10, "LYONNAISES").
dico("L", 10, "LYOPHILISA").
dico("L", 10, "LYOPHILISE").
dico("L", 10, "LYRASSIONS").
dico("L", 10, "LYRERAIENT").
dico("L", 10, "LYSASSIONS").
dico("L", 10, "LYSERAIENT").
dico("L", 10, "LYSERGIDES").
dico("L", 10, "LYSERGIQUE").
dico("L", 10, "LYSIMAQUES").
