dico("L", 5, "LABBE").
dico("L", 5, "LABEL").
dico("L", 5, "LABIE").
dico("L", 5, "LABOS").
dico("L", 5, "LABRE").
dico("L", 5, "LABRI").
dico("L", 5, "LACAI").
dico("L", 5, "LACAS").
dico("L", 5, "LACAT").
dico("L", 5, "LACEE").
dico("L", 5, "LACER").
dico("L", 5, "LACES").
dico("L", 5, "LACET").
dico("L", 5, "LACEZ").
dico("L", 5, "LACHA").
dico("L", 5, "LACHE").
dico("L", 5, "LACIS").
dico("L", 5, "LACKS").
dico("L", 5, "LACTE").
dico("L", 5, "LADIN").
dico("L", 5, "LADRE").
dico("L", 5, "LADYS").
dico("L", 5, "LAGAN").
dico("L", 5, "LAGON").
dico("L", 5, "LAHAR").
dico("L", 5, "LAICS").
dico("L", 5, "LAIDE").
dico("L", 5, "LAIDS").
dico("L", 5, "LAIES").
dico("L", 5, "LAINA").
dico("L", 5, "LAINE").
dico("L", 5, "LAIRD").
dico("L", 5, "LAITE").
dico("L", 5, "LAITS").
dico("L", 5, "LAIUS").
dico("L", 5, "LAIZE").
dico("L", 5, "LAKHS").
dico("L", 5, "LAMAI").
dico("L", 5, "LAMAS").
dico("L", 5, "LAMAT").
dico("L", 5, "LAMBI").
dico("L", 5, "LAMEE").
dico("L", 5, "LAMER").
dico("L", 5, "LAMES").
dico("L", 5, "LAMEZ").
dico("L", 5, "LAMIE").
dico("L", 5, "LAMPA").
dico("L", 5, "LAMPE").
dico("L", 5, "LANCA").
dico("L", 5, "LANCE").
dico("L", 5, "LANDE").
dico("L", 5, "LANDS").
dico("L", 5, "LANGE").
dico("L", 5, "LAPAI").
dico("L", 5, "LAPAS").
dico("L", 5, "LAPAT").
dico("L", 5, "LAPEE").
dico("L", 5, "LAPER").
dico("L", 5, "LAPES").
dico("L", 5, "LAPEZ").
dico("L", 5, "LAPIE").
dico("L", 5, "LAPIN").
dico("L", 5, "LAPIS").
dico("L", 5, "LAPON").
dico("L", 5, "LAPSE").
dico("L", 5, "LAPSI").
dico("L", 5, "LAQUA").
dico("L", 5, "LAQUE").
dico("L", 5, "LARDA").
dico("L", 5, "LARDE").
dico("L", 5, "LARDS").
dico("L", 5, "LARES").
dico("L", 5, "LARGE").
dico("L", 5, "LARGO").
dico("L", 5, "LARIS").
dico("L", 5, "LARIX").
dico("L", 5, "LARME").
dico("L", 5, "LARVE").
dico("L", 5, "LASER").
dico("L", 5, "LASSA").
dico("L", 5, "LASSE").
dico("L", 5, "LASSO").
dico("L", 5, "LATEX").
dico("L", 5, "LATIF").
dico("L", 5, "LATIN").
dico("L", 5, "LATTA").
dico("L", 5, "LATTE").
dico("L", 5, "LAURE").
dico("L", 5, "LAUSE").
dico("L", 5, "LAUZE").
dico("L", 5, "LAVAI").
dico("L", 5, "LAVAS").
dico("L", 5, "LAVAT").
dico("L", 5, "LAVEE").
dico("L", 5, "LAVER").
dico("L", 5, "LAVES").
dico("L", 5, "LAVEZ").
dico("L", 5, "LAVIS").
dico("L", 5, "LAVRA").
dico("L", 5, "LAYAI").
dico("L", 5, "LAYAS").
dico("L", 5, "LAYAT").
dico("L", 5, "LAYEE").
dico("L", 5, "LAYER").
dico("L", 5, "LAYES").
dico("L", 5, "LAYEZ").
dico("L", 5, "LAYON").
dico("L", 5, "LAZZI").
dico("L", 5, "LEBEL").
dico("L", 5, "LECHA").
dico("L", 5, "LECHE").
dico("L", 5, "LECON").
dico("L", 5, "LEDIT").
dico("L", 5, "LEGAL").
dico("L", 5, "LEGAT").
dico("L", 5, "LEGER").
dico("L", 5, "LEGES").
dico("L", 5, "LEGOS").
dico("L", 5, "LEGUA").
dico("L", 5, "LEGUE").
dico("L", 5, "LEHMS").
dico("L", 5, "LEMME").
dico("L", 5, "LEMUR").
dico("L", 5, "LENTE").
dico("L", 5, "LENTO").
dico("L", 5, "LENTS").
dico("L", 5, "LEONE").
dico("L", 5, "LEPRE").
dico("L", 5, "LEPTA").
dico("L", 5, "LEPTE").
dico("L", 5, "LERCH").
dico("L", 5, "LEROT").
dico("L", 5, "LESAI").
dico("L", 5, "LESAS").
dico("L", 5, "LESAT").
dico("L", 5, "LESEE").
dico("L", 5, "LESER").
dico("L", 5, "LESES").
dico("L", 5, "LESEZ").
dico("L", 5, "LESTA").
dico("L", 5, "LESTE").
dico("L", 5, "LESTS").
dico("L", 5, "LETAL").
dico("L", 5, "LETTE").
dico("L", 5, "LEUDE").
dico("L", 5, "LEURS").
dico("L", 5, "LEVAI").
dico("L", 5, "LEVAS").
dico("L", 5, "LEVAT").
dico("L", 5, "LEVEE").
dico("L", 5, "LEVER").
dico("L", 5, "LEVES").
dico("L", 5, "LEVEZ").
dico("L", 5, "LEVIS").
dico("L", 5, "LEVRE").
dico("L", 5, "LEXIE").
dico("L", 5, "LEXIS").
dico("L", 5, "LIAGE").
dico("L", 5, "LIAIS").
dico("L", 5, "LIAIT").
dico("L", 5, "LIANE").
dico("L", 5, "LIANT").
dico("L", 5, "LIARD").
dico("L", 5, "LIBER").
dico("L", 5, "LIBRE").
dico("L", 5, "LICES").
dico("L", 5, "LICHA").
dico("L", 5, "LICHE").
dico("L", 5, "LICOL").
dico("L", 5, "LICOU").
dico("L", 5, "LIDAR").
dico("L", 5, "LIDOS").
dico("L", 5, "LIEDS").
dico("L", 5, "LIEES").
dico("L", 5, "LIEGE").
dico("L", 5, "LIENS").
dico("L", 5, "LIENT").
dico("L", 5, "LIERA").
dico("L", 5, "LIEUE").
dico("L", 5, "LIEUR").
dico("L", 5, "LIEUS").
dico("L", 5, "LIEUX").
dico("L", 5, "LIFTA").
dico("L", 5, "LIFTE").
dico("L", 5, "LIFTS").
dico("L", 5, "LIGES").
dico("L", 5, "LIGHT").
dico("L", 5, "LIGIE").
dico("L", 5, "LIGNA").
dico("L", 5, "LIGNE").
dico("L", 5, "LIGOT").
dico("L", 5, "LIGUA").
dico("L", 5, "LIGUE").
dico("L", 5, "LIIEZ").
dico("L", 5, "LILAS").
dico("L", 5, "LIMAI").
dico("L", 5, "LIMAN").
dico("L", 5, "LIMAS").
dico("L", 5, "LIMAT").
dico("L", 5, "LIMBA").
dico("L", 5, "LIMBE").
dico("L", 5, "LIMEE").
dico("L", 5, "LIMER").
dico("L", 5, "LIMES").
dico("L", 5, "LIMEZ").
dico("L", 5, "LIMON").
dico("L", 5, "LINER").
dico("L", 5, "LINGA").
dico("L", 5, "LINGE").
dico("L", 5, "LINKS").
dico("L", 5, "LINON").
dico("L", 5, "LINOS").
dico("L", 5, "LIONS").
dico("L", 5, "LIPPE").
dico("L", 5, "LIPPU").
dico("L", 5, "LIRAI").
dico("L", 5, "LIRAS").
dico("L", 5, "LIRES").
dico("L", 5, "LIREZ").
dico("L", 5, "LIRON").
dico("L", 5, "LISES").
dico("L", 5, "LISEZ").
dico("L", 5, "LISPS").
dico("L", 5, "LISSA").
dico("L", 5, "LISSE").
dico("L", 5, "LISTA").
dico("L", 5, "LISTE").
dico("L", 5, "LITAI").
dico("L", 5, "LITAS").
dico("L", 5, "LITAT").
dico("L", 5, "LITEE").
dico("L", 5, "LITER").
dico("L", 5, "LITES").
dico("L", 5, "LITEZ").
dico("L", 5, "LITHO").
dico("L", 5, "LITRA").
dico("L", 5, "LITRE").
dico("L", 5, "LIURE").
dico("L", 5, "LIVET").
dico("L", 5, "LIVRA").
dico("L", 5, "LIVRE").
dico("L", 5, "LLOYD").
dico("L", 5, "LOBAI").
dico("L", 5, "LOBAS").
dico("L", 5, "LOBAT").
dico("L", 5, "LOBBY").
dico("L", 5, "LOBEE").
dico("L", 5, "LOBER").
dico("L", 5, "LOBES").
dico("L", 5, "LOBEZ").
dico("L", 5, "LOCAL").
dico("L", 5, "LOCHA").
dico("L", 5, "LOCHE").
dico("L", 5, "LOCHS").
dico("L", 5, "LOCOS").
dico("L", 5, "LOCUS").
dico("L", 5, "LODEN").
dico("L", 5, "LOESS").
dico("L", 5, "LOFAI").
dico("L", 5, "LOFAS").
dico("L", 5, "LOFAT").
dico("L", 5, "LOFER").
dico("L", 5, "LOFES").
dico("L", 5, "LOFEZ").
dico("L", 5, "LOFTS").
dico("L", 5, "LOGEA").
dico("L", 5, "LOGEE").
dico("L", 5, "LOGER").
dico("L", 5, "LOGES").
dico("L", 5, "LOGEZ").
dico("L", 5, "LOGIS").
dico("L", 5, "LOGOS").
dico("L", 5, "LOGUA").
dico("L", 5, "LOGUE").
dico("L", 5, "LOIRS").
dico("L", 5, "LOLOS").
dico("L", 5, "LOMPE").
dico("L", 5, "LONGE").
dico("L", 5, "LONGS").
dico("L", 5, "LOOCH").
dico("L", 5, "LOOFA").
dico("L", 5, "LOOKE").
dico("L", 5, "LOOKS").
dico("L", 5, "LOPES").
dico("L", 5, "LOPIN").
dico("L", 5, "LOQUE").
dico("L", 5, "LORAN").
dico("L", 5, "LORDS").
dico("L", 5, "LORIS").
dico("L", 5, "LORRY").
dico("L", 5, "LOSER").
dico("L", 5, "LOTES").
dico("L", 5, "LOTIE").
dico("L", 5, "LOTIR").
dico("L", 5, "LOTIS").
dico("L", 5, "LOTIT").
dico("L", 5, "LOTOS").
dico("L", 5, "LOTTA").
dico("L", 5, "LOTTE").
dico("L", 5, "LOTUS").
dico("L", 5, "LOUAI").
dico("L", 5, "LOUAS").
dico("L", 5, "LOUAT").
dico("L", 5, "LOUEE").
dico("L", 5, "LOUER").
dico("L", 5, "LOUES").
dico("L", 5, "LOUEZ").
dico("L", 5, "LOUFS").
dico("L", 5, "LOUIS").
dico("L", 5, "LOUPA").
dico("L", 5, "LOUPE").
dico("L", 5, "LOUPS").
dico("L", 5, "LOURA").
dico("L", 5, "LOURD").
dico("L", 5, "LOURE").
dico("L", 5, "LOUVA").
dico("L", 5, "LOUVE").
dico("L", 5, "LOVAI").
dico("L", 5, "LOVAS").
dico("L", 5, "LOVAT").
dico("L", 5, "LOVEE").
dico("L", 5, "LOVER").
dico("L", 5, "LOVES").
dico("L", 5, "LOVEZ").
dico("L", 5, "LOYAL").
dico("L", 5, "LOYER").
dico("L", 5, "LUBIE").
dico("L", 5, "LUCRE").
dico("L", 5, "LUEUR").
dico("L", 5, "LUFFA").
dico("L", 5, "LUGEA").
dico("L", 5, "LUGEE").
dico("L", 5, "LUGER").
dico("L", 5, "LUGES").
dico("L", 5, "LUGEZ").
dico("L", 5, "LUIRA").
dico("L", 5, "LUIRE").
dico("L", 5, "LUISE").
dico("L", 5, "LULUS").
dico("L", 5, "LUMEN").
dico("L", 5, "LUMES").
dico("L", 5, "LUMPS").
dico("L", 5, "LUNCH").
dico("L", 5, "LUNDI").
dico("L", 5, "LUNEE").
dico("L", 5, "LUNES").
dico("L", 5, "LUPIN").
dico("L", 5, "LUPUS").
dico("L", 5, "LUREX").
dico("L", 5, "LURON").
dico("L", 5, "LUSIN").
dico("L", 5, "LUSSE").
dico("L", 5, "LUTAI").
dico("L", 5, "LUTAS").
dico("L", 5, "LUTAT").
dico("L", 5, "LUTEE").
dico("L", 5, "LUTER").
dico("L", 5, "LUTES").
dico("L", 5, "LUTEZ").
dico("L", 5, "LUTHS").
dico("L", 5, "LUTIN").
dico("L", 5, "LUTTA").
dico("L", 5, "LUTTE").
dico("L", 5, "LUXAI").
dico("L", 5, "LUXAS").
dico("L", 5, "LUXAT").
dico("L", 5, "LUXEE").
dico("L", 5, "LUXER").
dico("L", 5, "LUXES").
dico("L", 5, "LUXEZ").
dico("L", 5, "LUZIN").
dico("L", 5, "LYCEE").
dico("L", 5, "LYCRA").
dico("L", 5, "LYRAI").
dico("L", 5, "LYRAS").
dico("L", 5, "LYRAT").
dico("L", 5, "LYRER").
dico("L", 5, "LYRES").
dico("L", 5, "LYREZ").
dico("L", 5, "LYRIC").
dico("L", 5, "LYSAI").
dico("L", 5, "LYSAS").
dico("L", 5, "LYSAT").
dico("L", 5, "LYSEE").
dico("L", 5, "LYSER").
dico("L", 5, "LYSES").
dico("L", 5, "LYSEZ").
