dico("M", 10, "MABOULISME").
dico("M", 10, "MACADAMISA").
dico("M", 10, "MACADAMISE").
dico("M", 10, "MACANEENNE").
dico("M", 10, "MACARONEES").
dico("M", 10, "MACCHABEES").
dico("M", 10, "MACEDOINES").
dico("M", 10, "MACEDONIEN").
dico("M", 10, "MACERAIENT").
dico("M", 10, "MACERASSES").
dico("M", 10, "MACERATEUR").
dico("M", 10, "MACERATION").
dico("M", 10, "MACERERAIS").
dico("M", 10, "MACERERAIT").
dico("M", 10, "MACERERENT").
dico("M", 10, "MACERERIEZ").
dico("M", 10, "MACERERONS").
dico("M", 10, "MACERERONT").
dico("M", 10, "MACFARLANE").
dico("M", 10, "MACHASSENT").
dico("M", 10, "MACHASSIEZ").
dico("M", 10, "MACHEMENTS").
dico("M", 10, "MACHERIONS").
dico("M", 10, "MACHIAVELS").
dico("M", 10, "MACHICOTAI").
dico("M", 10, "MACHICOTAS").
dico("M", 10, "MACHICOTAT").
dico("M", 10, "MACHICOTER").
dico("M", 10, "MACHICOTES").
dico("M", 10, "MACHICOTEZ").
dico("M", 10, "MACHINALES").
dico("M", 10, "MACHINAMES").
dico("M", 10, "MACHINASSE").
dico("M", 10, "MACHINATES").
dico("M", 10, "MACHINERAI").
dico("M", 10, "MACHINERAS").
dico("M", 10, "MACHINEREZ").
dico("M", 10, "MACHINERIE").
dico("M", 10, "MACHINIONS").
dico("M", 10, "MACHINISME").
dico("M", 10, "MACHINISTE").
dico("M", 10, "MACHMETRES").
dico("M", 10, "MACHONNAIS").
dico("M", 10, "MACHONNAIT").
dico("M", 10, "MACHONNANT").
dico("M", 10, "MACHONNEES").
dico("M", 10, "MACHONNENT").
dico("M", 10, "MACHONNERA").
dico("M", 10, "MACHONNIEZ").
dico("M", 10, "MACHONNONS").
dico("M", 10, "MACHOUILLA").
dico("M", 10, "MACHOUILLE").
dico("M", 10, "MACHURAMES").
dico("M", 10, "MACHURASSE").
dico("M", 10, "MACHURATES").
dico("M", 10, "MACHURERAI").
dico("M", 10, "MACHURERAS").
dico("M", 10, "MACHUREREZ").
dico("M", 10, "MACHURIONS").
dico("M", 10, "MACKINTOSH").
dico("M", 10, "MACLASSENT").
dico("M", 10, "MACLASSIEZ").
dico("M", 10, "MACLERIONS").
dico("M", 10, "MACONNAGES").
dico("M", 10, "MACONNAISE").
dico("M", 10, "MACONNAMES").
dico("M", 10, "MACONNASSE").
dico("M", 10, "MACONNATES").
dico("M", 10, "MACONNERAI").
dico("M", 10, "MACONNERAS").
dico("M", 10, "MACONNEREZ").
dico("M", 10, "MACONNERIE").
dico("M", 10, "MACONNIONS").
dico("M", 10, "MACONNIQUE").
dico("M", 10, "MACQUAIENT").
dico("M", 10, "MACQUASSES").
dico("M", 10, "MACQUERAIS").
dico("M", 10, "MACQUERAIT").
dico("M", 10, "MACQUERENT").
dico("M", 10, "MACQUERIEZ").
dico("M", 10, "MACQUERONS").
dico("M", 10, "MACQUERONT").
dico("M", 10, "MACROBIOTE").
dico("M", 10, "MACROCOSME").
dico("M", 10, "MACROCYSTE").
dico("M", 10, "MACROCYTES").
dico("M", 10, "MACROFAUNE").
dico("M", 10, "MACROLIDES").
dico("M", 10, "MACROPHAGE").
dico("M", 10, "MACROPHOTO").
dico("M", 10, "MACROPODES").
dico("M", 10, "MACROPSIES").
dico("M", 10, "MACROSPORE").
dico("M", 10, "MACULAIENT").
dico("M", 10, "MACULAIRES").
dico("M", 10, "MACULASSES").
dico("M", 10, "MACULATION").
dico("M", 10, "MACULATURE").
dico("M", 10, "MACULERAIS").
dico("M", 10, "MACULERAIT").
dico("M", 10, "MACULERENT").
dico("M", 10, "MACULERIEZ").
dico("M", 10, "MACULERONS").
dico("M", 10, "MACULERONT").
dico("M", 10, "MADAPOLAMS").
dico("M", 10, "MADECASSES").
dico("M", 10, "MADELEINES").
dico("M", 10, "MADELINOTE").
dico("M", 10, "MADELINOTS").
dico("M", 10, "MADERIENNE").
dico("M", 10, "MADERISAIS").
dico("M", 10, "MADERISAIT").
dico("M", 10, "MADERISANT").
dico("M", 10, "MADERISEES").
dico("M", 10, "MADERISENT").
dico("M", 10, "MADERISERA").
dico("M", 10, "MADERISIEZ").
dico("M", 10, "MADERISONS").
dico("M", 10, "MADREPORES").
dico("M", 10, "MADRILENES").
dico("M", 10, "MAELSTROMS").
dico("M", 10, "MAFFIEUSES").
dico("M", 10, "MAGANAIENT").
dico("M", 10, "MAGANASSES").
dico("M", 10, "MAGANERAIS").
dico("M", 10, "MAGANERAIT").
dico("M", 10, "MAGANERENT").
dico("M", 10, "MAGANERIEZ").
dico("M", 10, "MAGANERONS").
dico("M", 10, "MAGANERONT").
dico("M", 10, "MAGASINAGE").
dico("M", 10, "MAGASINAIS").
dico("M", 10, "MAGASINAIT").
dico("M", 10, "MAGASINANT").
dico("M", 10, "MAGASINEES").
dico("M", 10, "MAGASINENT").
dico("M", 10, "MAGASINERA").
dico("M", 10, "MAGASINEUR").
dico("M", 10, "MAGASINIER").
dico("M", 10, "MAGASINIEZ").
dico("M", 10, "MAGASINONS").
dico("M", 10, "MAGHREBINE").
dico("M", 10, "MAGHREBINS").
dico("M", 10, "MAGICIENNE").
dico("M", 10, "MAGISTERES").
dico("M", 10, "MAGISTRALE").
dico("M", 10, "MAGISTRATE").
dico("M", 10, "MAGISTRATS").
dico("M", 10, "MAGISTRAUX").
dico("M", 10, "MAGMATIQUE").
dico("M", 10, "MAGMATISME").
dico("M", 10, "MAGNANERIE").
dico("M", 10, "MAGNANIERE").
dico("M", 10, "MAGNANIERS").
dico("M", 10, "MAGNANIMES").
dico("M", 10, "MAGNARELLE").
dico("M", 10, "MAGNASSENT").
dico("M", 10, "MAGNASSIEZ").
dico("M", 10, "MAGNERIONS").
dico("M", 10, "MAGNESIENS").
dico("M", 10, "MAGNESITES").
dico("M", 10, "MAGNESIUMS").
dico("M", 10, "MAGNETIQUE").
dico("M", 10, "MAGNETISAI").
dico("M", 10, "MAGNETISAS").
dico("M", 10, "MAGNETISAT").
dico("M", 10, "MAGNETISEE").
dico("M", 10, "MAGNETISER").
dico("M", 10, "MAGNETISES").
dico("M", 10, "MAGNETISEZ").
dico("M", 10, "MAGNETISME").
dico("M", 10, "MAGNETITES").
dico("M", 10, "MAGNETRONS").
dico("M", 10, "MAGNIFIAIS").
dico("M", 10, "MAGNIFIAIT").
dico("M", 10, "MAGNIFIANT").
dico("M", 10, "MAGNIFICAT").
dico("M", 10, "MAGNIFIEES").
dico("M", 10, "MAGNIFIENT").
dico("M", 10, "MAGNIFIERA").
dico("M", 10, "MAGNIFIIEZ").
dico("M", 10, "MAGNIFIONS").
dico("M", 10, "MAGNIFIQUE").
dico("M", 10, "MAGNITUDES").
dico("M", 10, "MAGNOLIALE").
dico("M", 10, "MAGNOLIERS").
dico("M", 10, "MAGOUILLAI").
dico("M", 10, "MAGOUILLAS").
dico("M", 10, "MAGOUILLAT").
dico("M", 10, "MAGOUILLEE").
dico("M", 10, "MAGOUILLER").
dico("M", 10, "MAGOUILLES").
dico("M", 10, "MAGOUILLEZ").
dico("M", 10, "MAHARADJAH").
dico("M", 10, "MAHARADJAS").
dico("M", 10, "MAHARAJAHS").
dico("M", 10, "MAHOMETANE").
dico("M", 10, "MAHOMETANS").
dico("M", 10, "MAHORAISES").
dico("M", 10, "MAIEUTIQUE").
dico("M", 10, "MAIGRELETS").
dico("M", 10, "MAIGREMENT").
dico("M", 10, "MAIGRICHON").
dico("M", 10, "MAIGRIOTTE").
dico("M", 10, "MAIGRIRAIS").
dico("M", 10, "MAIGRIRAIT").
dico("M", 10, "MAIGRIRENT").
dico("M", 10, "MAIGRIRIEZ").
dico("M", 10, "MAIGRIRONS").
dico("M", 10, "MAIGRIRONT").
dico("M", 10, "MAIGRISSES").
dico("M", 10, "MAIGRISSEZ").
dico("M", 10, "MAILLAIENT").
dico("M", 10, "MAILLANTES").
dico("M", 10, "MAILLASSES").
dico("M", 10, "MAILLERAIS").
dico("M", 10, "MAILLERAIT").
dico("M", 10, "MAILLERENT").
dico("M", 10, "MAILLERIEZ").
dico("M", 10, "MAILLERONS").
dico("M", 10, "MAILLERONT").
dico("M", 10, "MAILLETAGE").
dico("M", 10, "MAILLETAIS").
dico("M", 10, "MAILLETAIT").
dico("M", 10, "MAILLETANT").
dico("M", 10, "MAILLETEES").
dico("M", 10, "MAILLETIEZ").
dico("M", 10, "MAILLETONS").
dico("M", 10, "MAILLETTES").
dico("M", 10, "MAILLOCHES").
dico("M", 10, "MAILLOTINS").
dico("M", 10, "MAINLEVEES").
dico("M", 10, "MAINMORTES").
dico("M", 10, "MAINTENAIS").
dico("M", 10, "MAINTENAIT").
dico("M", 10, "MAINTENANT").
dico("M", 10, "MAINTENEUR").
dico("M", 10, "MAINTENIEZ").
dico("M", 10, "MAINTENONS").
dico("M", 10, "MAINTENUES").
dico("M", 10, "MAINTIENNE").
dico("M", 10, "MAINTINMES").
dico("M", 10, "MAINTINSSE").
dico("M", 10, "MAINTINTES").
dico("M", 10, "MAIOLIQUES").
dico("M", 10, "MAISONNEES").
dico("M", 10, "MAISTRANCE").
dico("M", 10, "MAITRESSES").
dico("M", 10, "MAITRISAIS").
dico("M", 10, "MAITRISAIT").
dico("M", 10, "MAITRISANT").
dico("M", 10, "MAITRISEES").
dico("M", 10, "MAITRISENT").
dico("M", 10, "MAITRISERA").
dico("M", 10, "MAITRISIEZ").
dico("M", 10, "MAITRISONS").
dico("M", 10, "MAJESTUEUX").
dico("M", 10, "MAJOLIQUES").
dico("M", 10, "MAJORAIENT").
dico("M", 10, "MAJORANTES").
dico("M", 10, "MAJORASSES").
dico("M", 10, "MAJORATION").
dico("M", 10, "MAJORDOMES").
dico("M", 10, "MAJORERAIS").
dico("M", 10, "MAJORERAIT").
dico("M", 10, "MAJORERENT").
dico("M", 10, "MAJORERIEZ").
dico("M", 10, "MAJORERONS").
dico("M", 10, "MAJORERONT").
dico("M", 10, "MAJORETTES").
dico("M", 10, "MAJORQUINE").
dico("M", 10, "MAJORQUINS").
dico("M", 10, "MAJUSCULES").
dico("M", 10, "MALACHITES").
dico("M", 10, "MALADRERIE").
dico("M", 10, "MALADRESSE").
dico("M", 10, "MALADROITE").
dico("M", 10, "MALADROITS").
dico("M", 10, "MALAISIENS").
dico("M", 10, "MALANDREUX").
dico("M", 10, "MALANDRINS").
dico("M", 10, "MALAPPRISE").
dico("M", 10, "MALAVISEES").
dico("M", 10, "MALAXAIENT").
dico("M", 10, "MALAXASSES").
dico("M", 10, "MALAXATION").
dico("M", 10, "MALAXERAIS").
dico("M", 10, "MALAXERAIT").
dico("M", 10, "MALAXERENT").
dico("M", 10, "MALAXERIEZ").
dico("M", 10, "MALAXERONS").
dico("M", 10, "MALAXERONT").
dico("M", 10, "MALAYALAMS").
dico("M", 10, "MALAYSIENS").
dico("M", 10, "MALBARAISE").
dico("M", 10, "MALBOUFFES").
dico("M", 10, "MALCHANCES").
dico("M", 10, "MALCOMMODE").
dico("M", 10, "MALCONTENT").
dico("M", 10, "MALDIVIENS").
dico("M", 10, "MALEFIQUES").
dico("M", 10, "MALEKISMES").
dico("M", 10, "MALENTENDU").
dico("M", 10, "MALEPESTES").
dico("M", 10, "MALFAISANT").
dico("M", 10, "MALFAITEUR").
dico("M", 10, "MALHABILES").
dico("M", 10, "MALHEUREUX").
dico("M", 10, "MALHONNETE").
dico("M", 10, "MALICIEUSE").
dico("M", 10, "MALIGNITES").
dico("M", 10, "MALIKISMES").
dico("M", 10, "MALINOISES").
dico("M", 10, "MALITORNES").
dico("M", 10, "MALLEABLES").
dico("M", 10, "MALLETIERE").
dico("M", 10, "MALLETIERS").
dico("M", 10, "MALLOPHAGE").
dico("M", 10, "MALMENAMES").
dico("M", 10, "MALMENASSE").
dico("M", 10, "MALMENATES").
dico("M", 10, "MALMENERAI").
dico("M", 10, "MALMENERAS").
dico("M", 10, "MALMENEREZ").
dico("M", 10, "MALMENIONS").
dico("M", 10, "MALODORANT").
dico("M", 10, "MALONIQUES").
dico("M", 10, "MALPIGHIES").
dico("M", 10, "MALPROPRES").
dico("M", 10, "MALSEANCES").
dico("M", 10, "MALSEANTES").
dico("M", 10, "MALSONNANT").
dico("M", 10, "MALTASSENT").
dico("M", 10, "MALTASSIEZ").
dico("M", 10, "MALTERIONS").
dico("M", 10, "MALTHUSIEN").
dico("M", 10, "MALTOTIERS").
dico("M", 10, "MALTRAITAI").
dico("M", 10, "MALTRAITAS").
dico("M", 10, "MALTRAITAT").
dico("M", 10, "MALTRAITEE").
dico("M", 10, "MALTRAITER").
dico("M", 10, "MALTRAITES").
dico("M", 10, "MALTRAITEZ").
dico("M", 10, "MALVOISIES").
dico("M", 10, "MALVOYANTE").
dico("M", 10, "MALVOYANTS").
dico("M", 10, "MAMAMOUCHI").
dico("M", 10, "MAMELONNEE").
dico("M", 10, "MAMELONNES").
dico("M", 10, "MAMELOUKES").
dico("M", 10, "MAMILLAIRE").
dico("M", 10, "MAMMALIENS").
dico("M", 10, "MAMMALOGIE").
dico("M", 10, "MAMMIFERES").
dico("M", 10, "MANAGEAMES").
dico("M", 10, "MANAGEASSE").
dico("M", 10, "MANAGEATES").
dico("M", 10, "MANAGEMENT").
dico("M", 10, "MANAGERAIS").
dico("M", 10, "MANAGERAIT").
dico("M", 10, "MANAGERENT").
dico("M", 10, "MANAGERIAL").
dico("M", 10, "MANAGERIEZ").
dico("M", 10, "MANAGERONS").
dico("M", 10, "MANAGERONT").
dico("M", 10, "MANAGEUSES").
dico("M", 10, "MANAGUAYEN").
dico("M", 10, "MANAMEENNE").
dico("M", 10, "MANCENILLE").
dico("M", 10, "MANCHERONS").
dico("M", 10, "MANCHETTES").
dico("M", 10, "MANCHOISES").
dico("M", 10, "MANDARINAL").
dico("M", 10, "MANDARINAT").
dico("M", 10, "MANDARINES").
dico("M", 10, "MANDASSENT").
dico("M", 10, "MANDASSIEZ").
dico("M", 10, "MANDATAIRE").
dico("M", 10, "MANDATAMES").
dico("M", 10, "MANDATASSE").
dico("M", 10, "MANDATATES").
dico("M", 10, "MANDATERAI").
dico("M", 10, "MANDATERAS").
dico("M", 10, "MANDATEREZ").
dico("M", 10, "MANDATIONS").
dico("M", 10, "MANDATURES").
dico("M", 10, "MANDCHOUES").
dico("M", 10, "MANDEENNES").
dico("M", 10, "MANDEISMES").
dico("M", 10, "MANDEMENTS").
dico("M", 10, "MANDERIONS").
dico("M", 10, "MANDIBULES").
dico("M", 10, "MANDINGUES").
dico("M", 10, "MANDOLINES").
dico("M", 10, "MANDRAGORE").
dico("M", 10, "MANDRINAGE").
dico("M", 10, "MANDRINAIS").
dico("M", 10, "MANDRINAIT").
dico("M", 10, "MANDRINANT").
dico("M", 10, "MANDRINEES").
dico("M", 10, "MANDRINENT").
dico("M", 10, "MANDRINERA").
dico("M", 10, "MANDRINIEZ").
dico("M", 10, "MANDRINONS").
dico("M", 10, "MANEGEAMES").
dico("M", 10, "MANEGEASSE").
dico("M", 10, "MANEGEATES").
dico("M", 10, "MANEGERAIS").
dico("M", 10, "MANEGERAIT").
dico("M", 10, "MANEGERENT").
dico("M", 10, "MANEGERIEZ").
dico("M", 10, "MANEGERONS").
dico("M", 10, "MANEGERONT").
dico("M", 10, "MANGANATES").
dico("M", 10, "MANGANESES").
dico("M", 10, "MANGANEUSE").
dico("M", 10, "MANGANIDES").
dico("M", 10, "MANGANINES").
dico("M", 10, "MANGANIQUE").
dico("M", 10, "MANGANITES").
dico("M", 10, "MANGEABLES").
dico("M", 10, "MANGEAIENT").
dico("M", 10, "MANGEAILLE").
dico("M", 10, "MANGEASSES").
dico("M", 10, "MANGEOIRES").
dico("M", 10, "MANGEOTAIS").
dico("M", 10, "MANGEOTAIT").
dico("M", 10, "MANGEOTANT").
dico("M", 10, "MANGEOTEES").
dico("M", 10, "MANGEOTENT").
dico("M", 10, "MANGEOTERA").
dico("M", 10, "MANGEOTIEZ").
dico("M", 10, "MANGEOTONS").
dico("M", 10, "MANGEOTTAI").
dico("M", 10, "MANGEOTTAS").
dico("M", 10, "MANGEOTTAT").
dico("M", 10, "MANGEOTTEE").
dico("M", 10, "MANGEOTTER").
dico("M", 10, "MANGEOTTES").
dico("M", 10, "MANGEOTTEZ").
dico("M", 10, "MANGERIONS").
dico("M", 10, "MANGETOUTS").
dico("M", 10, "MANGONNEAU").
dico("M", 10, "MANGOUSTAN").
dico("M", 10, "MANGOUSTES").
dico("M", 10, "MANIASSENT").
dico("M", 10, "MANIASSIEZ").
dico("M", 10, "MANICHEENS").
dico("M", 10, "MANICORDES").
dico("M", 10, "MANIEMENTS").
dico("M", 10, "MANIERIONS").
dico("M", 10, "MANIERISME").
dico("M", 10, "MANIERISTE").
dico("M", 10, "MANIFESTAI").
dico("M", 10, "MANIFESTAS").
dico("M", 10, "MANIFESTAT").
dico("M", 10, "MANIFESTEE").
dico("M", 10, "MANIFESTER").
dico("M", 10, "MANIFESTES").
dico("M", 10, "MANIFESTEZ").
dico("M", 10, "MANIGANCAI").
dico("M", 10, "MANIGANCAS").
dico("M", 10, "MANIGANCAT").
dico("M", 10, "MANIGANCEE").
dico("M", 10, "MANIGANCER").
dico("M", 10, "MANIGANCES").
dico("M", 10, "MANIGANCEZ").
dico("M", 10, "MANIGUETTE").
dico("M", 10, "MANILLAISE").
dico("M", 10, "MANILLAMES").
dico("M", 10, "MANILLASSE").
dico("M", 10, "MANILLATES").
dico("M", 10, "MANILLERAI").
dico("M", 10, "MANILLERAS").
dico("M", 10, "MANILLEREZ").
dico("M", 10, "MANILLEURS").
dico("M", 10, "MANILLEUSE").
dico("M", 10, "MANILLIONS").
dico("M", 10, "MANIPULAIS").
dico("M", 10, "MANIPULAIT").
dico("M", 10, "MANIPULANT").
dico("M", 10, "MANIPULEES").
dico("M", 10, "MANIPULENT").
dico("M", 10, "MANIPULERA").
dico("M", 10, "MANIPULIEZ").
dico("M", 10, "MANIPULONS").
dico("M", 10, "MANITOBAIN").
dico("M", 10, "MANIVELLES").
dico("M", 10, "MANNEQUINS").
dico("M", 10, "MANOEUVRAI").
dico("M", 10, "MANOEUVRAS").
dico("M", 10, "MANOEUVRAT").
dico("M", 10, "MANOEUVREE").
dico("M", 10, "MANOEUVRER").
dico("M", 10, "MANOEUVRES").
dico("M", 10, "MANOEUVREZ").
dico("M", 10, "MANOGRAPHE").
dico("M", 10, "MANOMETRES").
dico("M", 10, "MANOMETRIE").
dico("M", 10, "MANOQUAGES").
dico("M", 10, "MANOQUAMES").
dico("M", 10, "MANOQUASSE").
dico("M", 10, "MANOQUATES").
dico("M", 10, "MANOQUERAI").
dico("M", 10, "MANOQUERAS").
dico("M", 10, "MANOQUEREZ").
dico("M", 10, "MANOQUIONS").
dico("M", 10, "MANOUVRIER").
dico("M", 10, "MANQUAIENT").
dico("M", 10, "MANQUANTES").
dico("M", 10, "MANQUASSES").
dico("M", 10, "MANQUEMENT").
dico("M", 10, "MANQUERAIS").
dico("M", 10, "MANQUERAIT").
dico("M", 10, "MANQUERENT").
dico("M", 10, "MANQUERIEZ").
dico("M", 10, "MANQUERONS").
dico("M", 10, "MANQUERONT").
dico("M", 10, "MANSARDEES").
dico("M", 10, "MANSUETUDE").
dico("M", 10, "MANTELINES").
dico("M", 10, "MANTELURES").
dico("M", 10, "MANTOUANES").
dico("M", 10, "MANUALITES").
dico("M", 10, "MANUBRIUMS").
dico("M", 10, "MANUCURAIS").
dico("M", 10, "MANUCURAIT").
dico("M", 10, "MANUCURANT").
dico("M", 10, "MANUCUREES").
dico("M", 10, "MANUCURENT").
dico("M", 10, "MANUCURERA").
dico("M", 10, "MANUCURIEZ").
dico("M", 10, "MANUCURONS").
dico("M", 10, "MANUELINES").
dico("M", 10, "MANUSCRITE").
dico("M", 10, "MANUSCRITS").
dico("M", 10, "MANUTERGES").
dico("M", 10, "MANZANILLA").
dico("M", 10, "MAPPASSENT").
dico("M", 10, "MAPPASSIEZ").
dico("M", 10, "MAPPEMONDE").
dico("M", 10, "MAPPERIONS").
dico("M", 10, "MAPUTAISES").
dico("M", 10, "MAQUASSENT").
dico("M", 10, "MAQUASSIEZ").
dico("M", 10, "MAQUEREAUX").
dico("M", 10, "MAQUERELLA").
dico("M", 10, "MAQUERELLE").
dico("M", 10, "MAQUERIONS").
dico("M", 10, "MAQUETTAGE").
dico("M", 10, "MAQUETTAIS").
dico("M", 10, "MAQUETTAIT").
dico("M", 10, "MAQUETTANT").
dico("M", 10, "MAQUETTEES").
dico("M", 10, "MAQUETTENT").
dico("M", 10, "MAQUETTERA").
dico("M", 10, "MAQUETTIEZ").
dico("M", 10, "MAQUETTONS").
dico("M", 10, "MAQUIGNONS").
dico("M", 10, "MAQUILLAGE").
dico("M", 10, "MAQUILLAIS").
dico("M", 10, "MAQUILLAIT").
dico("M", 10, "MAQUILLANT").
dico("M", 10, "MAQUILLEES").
dico("M", 10, "MAQUILLENT").
dico("M", 10, "MAQUILLERA").
dico("M", 10, "MAQUILLEUR").
dico("M", 10, "MAQUILLIEZ").
dico("M", 10, "MAQUILLONS").
dico("M", 10, "MAQUISARDE").
dico("M", 10, "MAQUISARDS").
dico("M", 10, "MARABOUTAI").
dico("M", 10, "MARABOUTAS").
dico("M", 10, "MARABOUTAT").
dico("M", 10, "MARABOUTEE").
dico("M", 10, "MARABOUTER").
dico("M", 10, "MARABOUTES").
dico("M", 10, "MARABOUTEZ").
dico("M", 10, "MARACUDJAS").
dico("M", 10, "MARAICHAGE").
dico("M", 10, "MARAICHERE").
dico("M", 10, "MARAICHERS").
dico("M", 10, "MARAICHINE").
dico("M", 10, "MARAICHINS").
dico("M", 10, "MARASQUINS").
dico("M", 10, "MARAUDAGES").
dico("M", 10, "MARAUDAMES").
dico("M", 10, "MARAUDASSE").
dico("M", 10, "MARAUDATES").
dico("M", 10, "MARAUDERAI").
dico("M", 10, "MARAUDERAS").
dico("M", 10, "MARAUDEREZ").
dico("M", 10, "MARAUDEURS").
dico("M", 10, "MARAUDEUSE").
dico("M", 10, "MARAUDIONS").
dico("M", 10, "MARBRAIENT").
dico("M", 10, "MARBRASSES").
dico("M", 10, "MARBRERAIS").
dico("M", 10, "MARBRERAIT").
dico("M", 10, "MARBRERENT").
dico("M", 10, "MARBRERIES").
dico("M", 10, "MARBRERIEZ").
dico("M", 10, "MARBRERONS").
dico("M", 10, "MARBRERONT").
dico("M", 10, "MARBREUSES").
dico("M", 10, "MARBRIERES").
dico("M", 10, "MARCASITES").
dico("M", 10, "MARCASSINS").
dico("M", 10, "MARCASSITE").
dico("M", 10, "MARCELINES").
dico("M", 10, "MARCESCENT").
dico("M", 10, "MARCHAIENT").
dico("M", 10, "MARCHANDAI").
dico("M", 10, "MARCHANDAS").
dico("M", 10, "MARCHANDAT").
dico("M", 10, "MARCHANDEE").
dico("M", 10, "MARCHANDER").
dico("M", 10, "MARCHANDES").
dico("M", 10, "MARCHANDEZ").
dico("M", 10, "MARCHANTES").
dico("M", 10, "MARCHANTIA").
dico("M", 10, "MARCHANTIE").
dico("M", 10, "MARCHASSES").
dico("M", 10, "MARCHEAGES").
dico("M", 10, "MARCHEPIED").
dico("M", 10, "MARCHERAIS").
dico("M", 10, "MARCHERAIT").
dico("M", 10, "MARCHERENT").
dico("M", 10, "MARCHERIEZ").
dico("M", 10, "MARCHERONS").
dico("M", 10, "MARCHERONT").
dico("M", 10, "MARCHETTES").
dico("M", 10, "MARCHEUSES").
dico("M", 10, "MARCOTTAGE").
dico("M", 10, "MARCOTTAIS").
dico("M", 10, "MARCOTTAIT").
dico("M", 10, "MARCOTTANT").
dico("M", 10, "MARCOTTEES").
dico("M", 10, "MARCOTTENT").
dico("M", 10, "MARCOTTERA").
dico("M", 10, "MARCOTTIEZ").
dico("M", 10, "MARCOTTONS").
dico("M", 10, "MARECAGEUX").
dico("M", 10, "MARECHALAT").
dico("M", 10, "MARECHALES").
dico("M", 10, "MAREGRAMME").
dico("M", 10, "MAREGRAPHE").
dico("M", 10, "MAREMOTEUR").
dico("M", 10, "MAREOMETRE").
dico("M", 10, "MAREYEUSES").
dico("M", 10, "MARGAILLES").
dico("M", 10, "MARGARINES").
dico("M", 10, "MARGAUDAIS").
dico("M", 10, "MARGAUDAIT").
dico("M", 10, "MARGAUDANT").
dico("M", 10, "MARGAUDENT").
dico("M", 10, "MARGAUDERA").
dico("M", 10, "MARGAUDIEZ").
dico("M", 10, "MARGAUDONS").
dico("M", 10, "MARGEAIENT").
dico("M", 10, "MARGEASSES").
dico("M", 10, "MARGERIONS").
dico("M", 10, "MARGINALES").
dico("M", 10, "MARGINAMES").
dico("M", 10, "MARGINASSE").
dico("M", 10, "MARGINATES").
dico("M", 10, "MARGINERAI").
dico("M", 10, "MARGINERAS").
dico("M", 10, "MARGINEREZ").
dico("M", 10, "MARGINIONS").
dico("M", 10, "MARGOTAMES").
dico("M", 10, "MARGOTASSE").
dico("M", 10, "MARGOTATES").
dico("M", 10, "MARGOTERAI").
dico("M", 10, "MARGOTERAS").
dico("M", 10, "MARGOTEREZ").
dico("M", 10, "MARGOTIONS").
dico("M", 10, "MARGOTTAIS").
dico("M", 10, "MARGOTTAIT").
dico("M", 10, "MARGOTTANT").
dico("M", 10, "MARGOTTENT").
dico("M", 10, "MARGOTTERA").
dico("M", 10, "MARGOTTIEZ").
dico("M", 10, "MARGOTTONS").
dico("M", 10, "MARGOULINE").
dico("M", 10, "MARGOULINS").
dico("M", 10, "MARGOUSIER").
dico("M", 10, "MARGRAVIAT").
dico("M", 10, "MARGRAVINE").
dico("M", 10, "MARGRITINS").
dico("M", 10, "MARGUERITE").
dico("M", 10, "MARIANISTE").
dico("M", 10, "MARIASSENT").
dico("M", 10, "MARIASSIEZ").
dico("M", 10, "MARIERIONS").
dico("M", 10, "MARIHUANAS").
dico("M", 10, "MARIJUANAS").
dico("M", 10, "MARINAIENT").
dico("M", 10, "MARINASSES").
dico("M", 10, "MARINERAIS").
dico("M", 10, "MARINERAIT").
dico("M", 10, "MARINERENT").
dico("M", 10, "MARINERIEZ").
dico("M", 10, "MARINERONS").
dico("M", 10, "MARINERONT").
dico("M", 10, "MARINGOTES").
dico("M", 10, "MARINGOTTE").
dico("M", 10, "MARINGOUIN").
dico("M", 10, "MARINIERES").
dico("M", 10, "MARINISMES").
dico("M", 10, "MARIOLOGIE").
dico("M", 10, "MARITORNES").
dico("M", 10, "MARIVAUDAI").
dico("M", 10, "MARIVAUDAS").
dico("M", 10, "MARIVAUDAT").
dico("M", 10, "MARIVAUDER").
dico("M", 10, "MARIVAUDES").
dico("M", 10, "MARIVAUDEZ").
dico("M", 10, "MARJOLAINE").
dico("M", 10, "MARKETINGS").
dico("M", 10, "MARMAILLES").
dico("M", 10, "MARMELADES").
dico("M", 10, "MARMENTEAU").
dico("M", 10, "MARMITAGES").
dico("M", 10, "MARMITAMES").
dico("M", 10, "MARMITASSE").
dico("M", 10, "MARMITATES").
dico("M", 10, "MARMITERAI").
dico("M", 10, "MARMITERAS").
dico("M", 10, "MARMITEREZ").
dico("M", 10, "MARMITIONS").
dico("M", 10, "MARMONNAIS").
dico("M", 10, "MARMONNAIT").
dico("M", 10, "MARMONNANT").
dico("M", 10, "MARMONNEES").
dico("M", 10, "MARMONNENT").
dico("M", 10, "MARMONNERA").
dico("M", 10, "MARMONNIEZ").
dico("M", 10, "MARMONNONS").
dico("M", 10, "MARMOREENS").
dico("M", 10, "MARMORISAI").
dico("M", 10, "MARMORISAS").
dico("M", 10, "MARMORISAT").
dico("M", 10, "MARMORISEE").
dico("M", 10, "MARMORISER").
dico("M", 10, "MARMORISES").
dico("M", 10, "MARMORISEZ").
dico("M", 10, "MARMOTTAGE").
dico("M", 10, "MARMOTTAIS").
dico("M", 10, "MARMOTTAIT").
dico("M", 10, "MARMOTTANT").
dico("M", 10, "MARMOTTEES").
dico("M", 10, "MARMOTTENT").
dico("M", 10, "MARMOTTERA").
dico("M", 10, "MARMOTTEUR").
dico("M", 10, "MARMOTTIER").
dico("M", 10, "MARMOTTIEZ").
dico("M", 10, "MARMOTTONS").
dico("M", 10, "MARMOUSETS").
dico("M", 10, "MARNASSENT").
dico("M", 10, "MARNASSIEZ").
dico("M", 10, "MARNERIONS").
dico("M", 10, "MAROCAINES").
dico("M", 10, "MAROLLIENS").
dico("M", 10, "MARONNAMES").
dico("M", 10, "MARONNASSE").
dico("M", 10, "MARONNATES").
dico("M", 10, "MARONNERAI").
dico("M", 10, "MARONNERAS").
dico("M", 10, "MARONNEREZ").
dico("M", 10, "MARONNIONS").
dico("M", 10, "MAROQUINAI").
dico("M", 10, "MAROQUINAS").
dico("M", 10, "MAROQUINAT").
dico("M", 10, "MAROQUINEE").
dico("M", 10, "MAROQUINER").
dico("M", 10, "MAROQUINES").
dico("M", 10, "MAROQUINEZ").
dico("M", 10, "MAROTIQUES").
dico("M", 10, "MAROUETTES").
dico("M", 10, "MAROUFLAGE").
dico("M", 10, "MAROUFLAIS").
dico("M", 10, "MAROUFLAIT").
dico("M", 10, "MAROUFLANT").
dico("M", 10, "MAROUFLEES").
dico("M", 10, "MAROUFLENT").
dico("M", 10, "MAROUFLERA").
dico("M", 10, "MAROUFLIEZ").
dico("M", 10, "MAROUFLONS").
dico("M", 10, "MARQUAIENT").
dico("M", 10, "MARQUANTES").
dico("M", 10, "MARQUASSES").
dico("M", 10, "MARQUERAIS").
dico("M", 10, "MARQUERAIT").
dico("M", 10, "MARQUERENT").
dico("M", 10, "MARQUERIEZ").
dico("M", 10, "MARQUERONS").
dico("M", 10, "MARQUERONT").
dico("M", 10, "MARQUESANE").
dico("M", 10, "MARQUESANS").
dico("M", 10, "MARQUETAIS").
dico("M", 10, "MARQUETAIT").
dico("M", 10, "MARQUETANT").
dico("M", 10, "MARQUETEES").
dico("M", 10, "MARQUETEUR").
dico("M", 10, "MARQUETIEZ").
dico("M", 10, "MARQUETONS").
dico("M", 10, "MARQUETTES").
dico("M", 10, "MARQUEUSES").
dico("M", 10, "MARQUISATS").
dico("M", 10, "MARQUISIEN").
dico("M", 10, "MARRASSENT").
dico("M", 10, "MARRASSIEZ").
dico("M", 10, "MARRERIONS").
dico("M", 10, "MARRONNAGE").
dico("M", 10, "MARRONNAIS").
dico("M", 10, "MARRONNAIT").
dico("M", 10, "MARRONNANT").
dico("M", 10, "MARRONNENT").
dico("M", 10, "MARRONNERA").
dico("M", 10, "MARRONNIER").
dico("M", 10, "MARRONNIEZ").
dico("M", 10, "MARRONNONS").
dico("M", 10, "MARSOUINAI").
dico("M", 10, "MARSOUINAS").
dico("M", 10, "MARSOUINAT").
dico("M", 10, "MARSOUINER").
dico("M", 10, "MARSOUINES").
dico("M", 10, "MARSOUINEZ").
dico("M", 10, "MARSUPIALE").
dico("M", 10, "MARSUPIAUX").
dico("M", 10, "MARSUPIUMS").
dico("M", 10, "MARTELAGES").
dico("M", 10, "MARTELAMES").
dico("M", 10, "MARTELASSE").
dico("M", 10, "MARTELATES").
dico("M", 10, "MARTELERAI").
dico("M", 10, "MARTELERAS").
dico("M", 10, "MARTELEREZ").
dico("M", 10, "MARTELEURS").
dico("M", 10, "MARTELIONS").
dico("M", 10, "MARTENSITE").
dico("M", 10, "MARTIENNES").
dico("M", 10, "MARTINGALE").
dico("M", 10, "MARTINISME").
dico("M", 10, "MARTYRISAI").
dico("M", 10, "MARTYRISAS").
dico("M", 10, "MARTYRISAT").
dico("M", 10, "MARTYRISEE").
dico("M", 10, "MARTYRISER").
dico("M", 10, "MARTYRISES").
dico("M", 10, "MARTYRISEZ").
dico("M", 10, "MARTYRIUMS").
dico("M", 10, "MARXIENNES").
dico("M", 10, "MARXISAMES").
dico("M", 10, "MARXISANTE").
dico("M", 10, "MARXISANTS").
dico("M", 10, "MARXISASSE").
dico("M", 10, "MARXISATES").
dico("M", 10, "MARXISERAI").
dico("M", 10, "MARXISERAS").
dico("M", 10, "MARXISEREZ").
dico("M", 10, "MARXISIONS").
dico("M", 10, "MARXOLOGIE").
dico("M", 10, "MARXOLOGUE").
dico("M", 10, "MASCARADES").
dico("M", 10, "MASCARPONE").
dico("M", 10, "MASCATAISE").
dico("M", 10, "MASCULINES").
dico("M", 10, "MASEROISES").
dico("M", 10, "MASKINONGE").
dico("M", 10, "MASKOUTAIN").
dico("M", 10, "MASOCHISME").
dico("M", 10, "MASOCHISTE").
dico("M", 10, "MASQUAIENT").
dico("M", 10, "MASQUANTES").
dico("M", 10, "MASQUASSES").
dico("M", 10, "MASQUERAIS").
dico("M", 10, "MASQUERAIT").
dico("M", 10, "MASQUERENT").
dico("M", 10, "MASQUERIEZ").
dico("M", 10, "MASQUERONS").
dico("M", 10, "MASQUERONT").
dico("M", 10, "MASSACRAIS").
dico("M", 10, "MASSACRAIT").
dico("M", 10, "MASSACRANT").
dico("M", 10, "MASSACREES").
dico("M", 10, "MASSACRENT").
dico("M", 10, "MASSACRERA").
dico("M", 10, "MASSACREUR").
dico("M", 10, "MASSACRIEZ").
dico("M", 10, "MASSACRONS").
dico("M", 10, "MASSALIOTE").
dico("M", 10, "MASSASSENT").
dico("M", 10, "MASSASSIEZ").
dico("M", 10, "MASSELOTTE").
dico("M", 10, "MASSEPAINS").
dico("M", 10, "MASSERIONS").
dico("M", 10, "MASSICOTAI").
dico("M", 10, "MASSICOTAS").
dico("M", 10, "MASSICOTAT").
dico("M", 10, "MASSICOTEE").
dico("M", 10, "MASSICOTER").
dico("M", 10, "MASSICOTES").
dico("M", 10, "MASSICOTEZ").
dico("M", 10, "MASSIFIAIS").
dico("M", 10, "MASSIFIAIT").
dico("M", 10, "MASSIFIANT").
dico("M", 10, "MASSIFIEES").
dico("M", 10, "MASSIFIENT").
dico("M", 10, "MASSIFIERA").
dico("M", 10, "MASSIFIIEZ").
dico("M", 10, "MASSIFIONS").
dico("M", 10, "MASSIVETES").
dico("M", 10, "MASSIVITES").
dico("M", 10, "MASSORETES").
dico("M", 10, "MASTICAGES").
dico("M", 10, "MASTIQUAIS").
dico("M", 10, "MASTIQUAIT").
dico("M", 10, "MASTIQUANT").
dico("M", 10, "MASTIQUEES").
dico("M", 10, "MASTIQUENT").
dico("M", 10, "MASTIQUERA").
dico("M", 10, "MASTIQUIEZ").
dico("M", 10, "MASTIQUONS").
dico("M", 10, "MASTOCYTES").
dico("M", 10, "MASTODONTE").
dico("M", 10, "MASTOIDIEN").
dico("M", 10, "MASTOIDITE").
dico("M", 10, "MASTOLOGIE").
dico("M", 10, "MASTOLOGUE").
dico("M", 10, "MASTROQUET").
dico("M", 10, "MASTURBAIS").
dico("M", 10, "MASTURBAIT").
dico("M", 10, "MASTURBANT").
dico("M", 10, "MASTURBEES").
dico("M", 10, "MASTURBENT").
dico("M", 10, "MASTURBERA").
dico("M", 10, "MASTURBIEZ").
dico("M", 10, "MASTURBONS").
dico("M", 10, "MATABICHES").
dico("M", 10, "MATASSIONS").
dico("M", 10, "MATCHAIENT").
dico("M", 10, "MATCHASSES").
dico("M", 10, "MATCHERAIS").
dico("M", 10, "MATCHERAIT").
dico("M", 10, "MATCHERENT").
dico("M", 10, "MATCHERIEZ").
dico("M", 10, "MATCHERONS").
dico("M", 10, "MATCHERONT").
dico("M", 10, "MATCHICHES").
dico("M", 10, "MATELASSAI").
dico("M", 10, "MATELASSAS").
dico("M", 10, "MATELASSAT").
dico("M", 10, "MATELASSEE").
dico("M", 10, "MATELASSER").
dico("M", 10, "MATELASSES").
dico("M", 10, "MATELASSEZ").
dico("M", 10, "MATELOTAGE").
dico("M", 10, "MATERAIENT").
dico("M", 10, "MATERIELLE").
dico("M", 10, "MATERNAGES").
dico("M", 10, "MATERNAMES").
dico("M", 10, "MATERNASSE").
dico("M", 10, "MATERNATES").
dico("M", 10, "MATERNELLE").
dico("M", 10, "MATERNERAI").
dico("M", 10, "MATERNERAS").
dico("M", 10, "MATERNEREZ").
dico("M", 10, "MATERNIONS").
dico("M", 10, "MATERNISAI").
dico("M", 10, "MATERNISAS").
dico("M", 10, "MATERNISAT").
dico("M", 10, "MATERNISEE").
dico("M", 10, "MATERNISER").
dico("M", 10, "MATERNISES").
dico("M", 10, "MATERNISEZ").
dico("M", 10, "MATERNITES").
dico("M", 10, "MATHUSALEM").
dico("M", 10, "MATIERISME").
dico("M", 10, "MATIERISTE").
dico("M", 10, "MATIFIAMES").
dico("M", 10, "MATIFIANTE").
dico("M", 10, "MATIFIANTS").
dico("M", 10, "MATIFIASSE").
dico("M", 10, "MATIFIATES").
dico("M", 10, "MATIFIERAI").
dico("M", 10, "MATIFIERAS").
dico("M", 10, "MATIFIEREZ").
dico("M", 10, "MATIFIIONS").
dico("M", 10, "MATINAIENT").
dico("M", 10, "MATINASSES").
dico("M", 10, "MATINERAIS").
dico("M", 10, "MATINERAIT").
dico("M", 10, "MATINERENT").
dico("M", 10, "MATINERIEZ").
dico("M", 10, "MATINERONS").
dico("M", 10, "MATINERONT").
dico("M", 10, "MATINEUSES").
dico("M", 10, "MATINIERES").
dico("M", 10, "MATIRAIENT").
dico("M", 10, "MATISSIONS").
dico("M", 10, "MATOISERIE").
dico("M", 10, "MATRAQUAGE").
dico("M", 10, "MATRAQUAIS").
dico("M", 10, "MATRAQUAIT").
dico("M", 10, "MATRAQUANT").
dico("M", 10, "MATRAQUEES").
dico("M", 10, "MATRAQUENT").
dico("M", 10, "MATRAQUERA").
dico("M", 10, "MATRAQUEUR").
dico("M", 10, "MATRAQUIEZ").
dico("M", 10, "MATRAQUONS").
dico("M", 10, "MATRIARCAL").
dico("M", 10, "MATRIARCAT").
dico("M", 10, "MATRIARCHE").
dico("M", 10, "MATRICAGES").
dico("M", 10, "MATRICAIRE").
dico("M", 10, "MATRICAMES").
dico("M", 10, "MATRICASSE").
dico("M", 10, "MATRICATES").
dico("M", 10, "MATRICERAI").
dico("M", 10, "MATRICERAS").
dico("M", 10, "MATRICEREZ").
dico("M", 10, "MATRICIDES").
dico("M", 10, "MATRICIELS").
dico("M", 10, "MATRICIONS").
dico("M", 10, "MATRICLANS").
dico("M", 10, "MATRICULAI").
dico("M", 10, "MATRICULAS").
dico("M", 10, "MATRICULAT").
dico("M", 10, "MATRICULEE").
dico("M", 10, "MATRICULER").
dico("M", 10, "MATRICULES").
dico("M", 10, "MATRICULEZ").
dico("M", 10, "MATRILOCAL").
dico("M", 10, "MATRIOCHKA").
dico("M", 10, "MATRONYMES").
dico("M", 10, "MATTHIOLES").
dico("M", 10, "MATURAIENT").
dico("M", 10, "MATURASSES").
dico("M", 10, "MATURATION").
dico("M", 10, "MATURERAIS").
dico("M", 10, "MATURERAIT").
dico("M", 10, "MATURERENT").
dico("M", 10, "MATURERIEZ").
dico("M", 10, "MATURERONS").
dico("M", 10, "MATURERONT").
dico("M", 10, "MATUTINALE").
dico("M", 10, "MATUTINAUX").
dico("M", 10, "MAUDIRIONS").
dico("M", 10, "MAUDISSAIS").
dico("M", 10, "MAUDISSAIT").
dico("M", 10, "MAUDISSANT").
dico("M", 10, "MAUDISSENT").
dico("M", 10, "MAUDISSIEZ").
dico("M", 10, "MAUDISSONS").
dico("M", 10, "MAUGRABINE").
dico("M", 10, "MAUGRABINS").
dico("M", 10, "MAUGREAMES").
dico("M", 10, "MAUGREASSE").
dico("M", 10, "MAUGREATES").
dico("M", 10, "MAUGREBINE").
dico("M", 10, "MAUGREBINS").
dico("M", 10, "MAUGREERAI").
dico("M", 10, "MAUGREERAS").
dico("M", 10, "MAUGREEREZ").
dico("M", 10, "MAUGREIONS").
dico("M", 10, "MAURANDIAS").
dico("M", 10, "MAURANDIES").
dico("M", 10, "MAURESQUES").
dico("M", 10, "MAURICIENS").
dico("M", 10, "MAUVAISETE").
dico("M", 10, "MAUVIETTES").
dico("M", 10, "MAXILLAIRE").
dico("M", 10, "MAXIMALISA").
dico("M", 10, "MAXIMALISE").
dico("M", 10, "MAXIMANTES").
dico("M", 10, "MAXIMISAIS").
dico("M", 10, "MAXIMISAIT").
dico("M", 10, "MAXIMISANT").
dico("M", 10, "MAXIMISEES").
dico("M", 10, "MAXIMISENT").
dico("M", 10, "MAXIMISERA").
dico("M", 10, "MAXIMISIEZ").
dico("M", 10, "MAXIMISONS").
dico("M", 10, "MAYENCAISE").
dico("M", 10, "MAYENNAISE").
dico("M", 10, "MAYONNAISE").
dico("M", 10, "MAZARINADE").
dico("M", 10, "MAZASSIONS").
dico("M", 10, "MAZDEENNES").
dico("M", 10, "MAZDEISMES").
dico("M", 10, "MAZERAIENT").
dico("M", 10, "MAZOUTAGES").
dico("M", 10, "MAZOUTAMES").
dico("M", 10, "MAZOUTASSE").
dico("M", 10, "MAZOUTATES").
dico("M", 10, "MAZOUTERAI").
dico("M", 10, "MAZOUTERAS").
dico("M", 10, "MAZOUTEREZ").
dico("M", 10, "MAZOUTIONS").
dico("M", 10, "MBABANAISE").
dico("M", 10, "MEANDREUSE").
dico("M", 10, "MEANDRINES").
dico("M", 10, "MECANICIEN").
dico("M", 10, "MECANIQUES").
dico("M", 10, "MECANISAIS").
dico("M", 10, "MECANISAIT").
dico("M", 10, "MECANISANT").
dico("M", 10, "MECANISEES").
dico("M", 10, "MECANISENT").
dico("M", 10, "MECANISERA").
dico("M", 10, "MECANISIEZ").
dico("M", 10, "MECANISMES").
dico("M", 10, "MECANISONS").
dico("M", 10, "MECANISTES").
dico("M", 10, "MECHAMMENT").
dico("M", 10, "MECHANCETE").
dico("M", 10, "MECHASSENT").
dico("M", 10, "MECHASSIEZ").
dico("M", 10, "MECHERIONS").
dico("M", 10, "MECONDUIRA").
dico("M", 10, "MECONDUIRE").
dico("M", 10, "MECONDUISE").
dico("M", 10, "MECONDUITE").
dico("M", 10, "MECONDUITS").
dico("M", 10, "MECONIALES").
dico("M", 10, "MECONNUMES").
dico("M", 10, "MECONNUSSE").
dico("M", 10, "MECONNUTES").
dico("M", 10, "MECONTENTA").
dico("M", 10, "MECONTENTE").
dico("M", 10, "MECONTENTS").
dico("M", 10, "MECOPTERES").
dico("M", 10, "MECREANCES").
dico("M", 10, "MECREANTES").
dico("M", 10, "MEDAILLAIS").
dico("M", 10, "MEDAILLAIT").
dico("M", 10, "MEDAILLANT").
dico("M", 10, "MEDAILLEES").
dico("M", 10, "MEDAILLENT").
dico("M", 10, "MEDAILLERA").
dico("M", 10, "MEDAILLEUR").
dico("M", 10, "MEDAILLIER").
dico("M", 10, "MEDAILLIEZ").
dico("M", 10, "MEDAILLONS").
dico("M", 10, "MEDIANOCHE").
dico("M", 10, "MEDIASCOPE").
dico("M", 10, "MEDIASTINS").
dico("M", 10, "MEDIATEURS").
dico("M", 10, "MEDIATIONS").
dico("M", 10, "MEDIATIQUE").
dico("M", 10, "MEDIATISAI").
dico("M", 10, "MEDIATISAS").
dico("M", 10, "MEDIATISAT").
dico("M", 10, "MEDIATISEE").
dico("M", 10, "MEDIATISER").
dico("M", 10, "MEDIATISES").
dico("M", 10, "MEDIATISEZ").
dico("M", 10, "MEDIATRICE").
dico("M", 10, "MEDICALISA").
dico("M", 10, "MEDICALISE").
dico("M", 10, "MEDICAMENT").
dico("M", 10, "MEDICASTRE").
dico("M", 10, "MEDICATION").
dico("M", 10, "MEDICINALE").
dico("M", 10, "MEDICINAUX").
dico("M", 10, "MEDICINIER").
dico("M", 10, "MEDIEVALES").
dico("M", 10, "MEDIEVISME").
dico("M", 10, "MEDIEVISTE").
dico("M", 10, "MEDIOCRITE").
dico("M", 10, "MEDIRAIENT").
dico("M", 10, "MEDISAIENT").
dico("M", 10, "MEDISANCES").
dico("M", 10, "MEDISANTES").
dico("M", 10, "MEDISSIONS").
dico("M", 10, "MEDITAIENT").
dico("M", 10, "MEDITASSES").
dico("M", 10, "MEDITATIFS").
dico("M", 10, "MEDITATION").
dico("M", 10, "MEDITATIVE").
dico("M", 10, "MEDITERAIS").
dico("M", 10, "MEDITERAIT").
dico("M", 10, "MEDITERENT").
dico("M", 10, "MEDITERIEZ").
dico("M", 10, "MEDITERONS").
dico("M", 10, "MEDITERONT").
dico("M", 10, "MEDIUMNITE").
dico("M", 10, "MEDULLAIRE").
dico("M", 10, "MEDULLEUSE").
dico("M", 10, "MEDUSAIENT").
dico("M", 10, "MEDUSASSES").
dico("M", 10, "MEDUSERAIS").
dico("M", 10, "MEDUSERAIT").
dico("M", 10, "MEDUSERENT").
dico("M", 10, "MEDUSERIEZ").
dico("M", 10, "MEDUSERONS").
dico("M", 10, "MEDUSERONT").
dico("M", 10, "MEFIASSENT").
dico("M", 10, "MEFIASSIEZ").
dico("M", 10, "MEFIERIONS").
dico("M", 10, "MEGACOLONS").
dico("M", 10, "MEGACYCLES").
dico("M", 10, "MEGAJOULES").
dico("M", 10, "MEGALITHES").
dico("M", 10, "MEGALOCYTE").
dico("M", 10, "MEGALOMANE").
dico("M", 10, "MEGALOPOLE").
dico("M", 10, "MEGAOCTETS").
dico("M", 10, "MEGAPHONES").
dico("M", 10, "MEGAPTERES").
dico("M", 10, "MEGARIQUES").
dico("M", 10, "MEGATONNES").
dico("M", 10, "MEGIRAIENT").
dico("M", 10, "MEGISSAGES").
dico("M", 10, "MEGISSAMES").
dico("M", 10, "MEGISSASSE").
dico("M", 10, "MEGISSATES").
dico("M", 10, "MEGISSERAI").
dico("M", 10, "MEGISSERAS").
dico("M", 10, "MEGISSEREZ").
dico("M", 10, "MEGISSERIE").
dico("M", 10, "MEGISSIERS").
dico("M", 10, "MEGISSIONS").
dico("M", 10, "MEGOTAIENT").
dico("M", 10, "MEGOTASSES").
dico("M", 10, "MEGOTERAIS").
dico("M", 10, "MEGOTERAIT").
dico("M", 10, "MEGOTERENT").
dico("M", 10, "MEGOTERIEZ").
dico("M", 10, "MEGOTERONS").
dico("M", 10, "MEGOTERONT").
dico("M", 10, "MEHARISTES").
dico("M", 10, "MEILLEURES").
dico("M", 10, "MEIOTIQUES").
dico("M", 10, "MEITNERIUM").
dico("M", 10, "MEJUGEAMES").
dico("M", 10, "MEJUGEASSE").
dico("M", 10, "MEJUGEATES").
dico("M", 10, "MEJUGERAIS").
dico("M", 10, "MEJUGERAIT").
dico("M", 10, "MEJUGERENT").
dico("M", 10, "MEJUGERIEZ").
dico("M", 10, "MEJUGERONS").
dico("M", 10, "MEJUGERONT").
dico("M", 10, "MELAMINEES").
dico("M", 10, "MELAMPYRES").
dico("M", 10, "MELANCOLIE").
dico("M", 10, "MELANESIEN").
dico("M", 10, "MELANGEAIS").
dico("M", 10, "MELANGEAIT").
dico("M", 10, "MELANGEANT").
dico("M", 10, "MELANGEONS").
dico("M", 10, "MELANGERAI").
dico("M", 10, "MELANGERAS").
dico("M", 10, "MELANGEREZ").
dico("M", 10, "MELANGEURS").
dico("M", 10, "MELANGEUSE").
dico("M", 10, "MELANGIONS").
dico("M", 10, "MELANIQUES").
dico("M", 10, "MELANISMES").
dico("M", 10, "MELANOCYTE").
dico("M", 10, "MELASSIONS").
dico("M", 10, "MELATONINE").
dico("M", 10, "MELEAGRINE").
dico("M", 10, "MELECASSES").
dico("M", 10, "MELERAIENT").
dico("M", 10, "MELIORATIF").
dico("M", 10, "MELLIFERES").
dico("M", 10, "MELLIFIQUE").
dico("M", 10, "MELLIFLUES").
dico("M", 10, "MELODIEUSE").
dico("M", 10, "MELODIQUES").
dico("M", 10, "MELODISTES").
dico("M", 10, "MELODRAMES").
dico("M", 10, "MELOMANIES").
dico("M", 10, "MELOMELIES").
dico("M", 10, "MELONGENES").
dico("M", 10, "MELONGINES").
dico("M", 10, "MELONNIERE").
dico("M", 10, "MELOPHAGES").
dico("M", 10, "MELUNAISES").
dico("M", 10, "MEMBRANEUX").
dico("M", 10, "MEMBRANULE").
dico("M", 10, "MEMERAIENT").
dico("M", 10, "MEMERASSES").
dico("M", 10, "MEMERERAIS").
dico("M", 10, "MEMERERAIT").
dico("M", 10, "MEMERERENT").
dico("M", 10, "MEMERERIEZ").
dico("M", 10, "MEMERERONS").
dico("M", 10, "MEMERERONT").
dico("M", 10, "MEMORABLES").
dico("M", 10, "MEMORANDUM").
dico("M", 10, "MEMORATION").
dico("M", 10, "MEMORIELLE").
dico("M", 10, "MEMORISAIS").
dico("M", 10, "MEMORISAIT").
dico("M", 10, "MEMORISANT").
dico("M", 10, "MEMORISEES").
dico("M", 10, "MEMORISENT").
dico("M", 10, "MEMORISERA").
dico("M", 10, "MEMORISIEZ").
dico("M", 10, "MEMORISONS").
dico("M", 10, "MENACAIENT").
dico("M", 10, "MENACANTES").
dico("M", 10, "MENACASSES").
dico("M", 10, "MENACERAIS").
dico("M", 10, "MENACERAIT").
dico("M", 10, "MENACERENT").
dico("M", 10, "MENACERIEZ").
dico("M", 10, "MENACERONS").
dico("M", 10, "MENACERONT").
dico("M", 10, "MENAGEAMES").
dico("M", 10, "MENAGEASSE").
dico("M", 10, "MENAGEATES").
dico("M", 10, "MENAGEMENT").
dico("M", 10, "MENAGERAIS").
dico("M", 10, "MENAGERAIT").
dico("M", 10, "MENAGERENT").
dico("M", 10, "MENAGERIES").
dico("M", 10, "MENAGERIEZ").
dico("M", 10, "MENAGERONS").
dico("M", 10, "MENAGERONT").
dico("M", 10, "MENAGISTES").
dico("M", 10, "MENASSIONS").
dico("M", 10, "MENCHEVIKS").
dico("M", 10, "MENDELIENS").
dico("M", 10, "MENDELISME").
dico("M", 10, "MENDIAIENT").
dico("M", 10, "MENDIANTES").
dico("M", 10, "MENDIASSES").
dico("M", 10, "MENDICITES").
dico("M", 10, "MENDIERAIS").
dico("M", 10, "MENDIERAIT").
dico("M", 10, "MENDIERENT").
dico("M", 10, "MENDIERIEZ").
dico("M", 10, "MENDIERONS").
dico("M", 10, "MENDIERONT").
dico("M", 10, "MENDIGOTAI").
dico("M", 10, "MENDIGOTAS").
dico("M", 10, "MENDIGOTAT").
dico("M", 10, "MENDIGOTEE").
dico("M", 10, "MENDIGOTER").
dico("M", 10, "MENDIGOTES").
dico("M", 10, "MENDIGOTEZ").
dico("M", 10, "MENERAIENT").
dico("M", 10, "MENESTRELS").
dico("M", 10, "MENETRIERS").
dico("M", 10, "MENINGIOME").
dico("M", 10, "MENINGITES").
dico("M", 10, "MENISCALES").
dico("M", 10, "MENISCITES").
dico("M", 10, "MENNONITES").
dico("M", 10, "MENOPAUSEE").
dico("M", 10, "MENOPAUSES").
dico("M", 10, "MENORRAGIE").
dico("M", 10, "MENOTAXIES").
dico("M", 10, "MENOTTAMES").
dico("M", 10, "MENOTTASSE").
dico("M", 10, "MENOTTATES").
dico("M", 10, "MENOTTERAI").
dico("M", 10, "MENOTTERAS").
dico("M", 10, "MENOTTEREZ").
dico("M", 10, "MENOTTIONS").
dico("M", 10, "MENSONGERE").
dico("M", 10, "MENSONGERS").
dico("M", 10, "MENSTRUEES").
dico("M", 10, "MENSTRUELS").
dico("M", 10, "MENSUALISA").
dico("M", 10, "MENSUALISE").
dico("M", 10, "MENSUALITE").
dico("M", 10, "MENSUELLES").
dico("M", 10, "MENTALISAI").
dico("M", 10, "MENTALISAS").
dico("M", 10, "MENTALISAT").
dico("M", 10, "MENTALISEE").
dico("M", 10, "MENTALISER").
dico("M", 10, "MENTALISES").
dico("M", 10, "MENTALISEZ").
dico("M", 10, "MENTALISME").
dico("M", 10, "MENTALITES").
dico("M", 10, "MENTHOLEES").
dico("M", 10, "MENTIONNAI").
dico("M", 10, "MENTIONNAS").
dico("M", 10, "MENTIONNAT").
dico("M", 10, "MENTIONNEE").
dico("M", 10, "MENTIONNER").
dico("M", 10, "MENTIONNES").
dico("M", 10, "MENTIONNEZ").
dico("M", 10, "MENTIRIONS").
dico("M", 10, "MENTISSENT").
dico("M", 10, "MENTISSIEZ").
dico("M", 10, "MENTONNETS").
dico("M", 10, "MENTONNIER").
dico("M", 10, "MENUISAGES").
dico("M", 10, "MENUISAMES").
dico("M", 10, "MENUISASSE").
dico("M", 10, "MENUISATES").
dico("M", 10, "MENUISERAI").
dico("M", 10, "MENUISERAS").
dico("M", 10, "MENUISEREZ").
dico("M", 10, "MENUISERIE").
dico("M", 10, "MENUISIERE").
dico("M", 10, "MENUISIERS").
dico("M", 10, "MENUISIONS").
dico("M", 10, "MENYANTHES").
dico("M", 10, "MEPHITIQUE").
dico("M", 10, "MEPHITISME").
dico("M", 10, "MEPRENDRAI").
dico("M", 10, "MEPRENDRAS").
dico("M", 10, "MEPRENDREZ").
dico("M", 10, "MEPRENIONS").
dico("M", 10, "MEPRENNENT").
dico("M", 10, "MEPRISABLE").
dico("M", 10, "MEPRISAMES").
dico("M", 10, "MEPRISANTE").
dico("M", 10, "MEPRISANTS").
dico("M", 10, "MEPRISASSE").
dico("M", 10, "MEPRISATES").
dico("M", 10, "MEPRISERAI").
dico("M", 10, "MEPRISERAS").
dico("M", 10, "MEPRISEREZ").
dico("M", 10, "MEPRISIONS").
dico("M", 10, "MEPRISSENT").
dico("M", 10, "MEPRISSIEZ").
dico("M", 10, "MERCANTILE").
dico("M", 10, "MERCAPTANS").
dico("M", 10, "MERCATIQUE").
dico("M", 10, "MERCENAIRE").
dico("M", 10, "MERCERISAI").
dico("M", 10, "MERCERISAS").
dico("M", 10, "MERCERISAT").
dico("M", 10, "MERCERISEE").
dico("M", 10, "MERCERISER").
dico("M", 10, "MERCERISES").
dico("M", 10, "MERCERISEZ").
dico("M", 10, "MERCUREUSE").
dico("M", 10, "MERCURIALE").
dico("M", 10, "MERCURIELS").
dico("M", 10, "MERCURIQUE").
dico("M", 10, "MERDAILLON").
dico("M", 10, "MERDASSENT").
dico("M", 10, "MERDASSIEZ").
dico("M", 10, "MERDERIONS").
dico("M", 10, "MERDOIERAI").
dico("M", 10, "MERDOIERAS").
dico("M", 10, "MERDOIEREZ").
dico("M", 10, "MERDOUILLA").
dico("M", 10, "MERDOUILLE").
dico("M", 10, "MERDOYAMES").
dico("M", 10, "MERDOYASSE").
dico("M", 10, "MERDOYATES").
dico("M", 10, "MERDOYIONS").
dico("M", 10, "MERICARPES").
dico("M", 10, "MERIDIENNE").
dico("M", 10, "MERIDIONAL").
dico("M", 10, "MERINGAGES").
dico("M", 10, "MERINGUAIS").
dico("M", 10, "MERINGUAIT").
dico("M", 10, "MERINGUANT").
dico("M", 10, "MERINGUEES").
dico("M", 10, "MERINGUENT").
dico("M", 10, "MERINGUERA").
dico("M", 10, "MERINGUIEZ").
dico("M", 10, "MERINGUONS").
dico("M", 10, "MERISTEMES").
dico("M", 10, "MERITAIENT").
dico("M", 10, "MERITANTES").
dico("M", 10, "MERITASSES").
dico("M", 10, "MERITERAIS").
dico("M", 10, "MERITERAIT").
dico("M", 10, "MERITERENT").
dico("M", 10, "MERITERIEZ").
dico("M", 10, "MERITERONS").
dico("M", 10, "MERITERONT").
dico("M", 10, "MERITOIRES").
dico("M", 10, "MERLONNAIS").
dico("M", 10, "MERLONNAIT").
dico("M", 10, "MERLONNANT").
dico("M", 10, "MERLONNEES").
dico("M", 10, "MERLONNENT").
dico("M", 10, "MERLONNERA").
dico("M", 10, "MERLONNIEZ").
dico("M", 10, "MERLONNONS").
dico("M", 10, "MEROSTOMES").
dico("M", 10, "MERVEILLES").
dico("M", 10, "MERYCISMES").
dico("M", 10, "MESADAPTEE").
dico("M", 10, "MESADAPTES").
dico("M", 10, "MESALLIAIS").
dico("M", 10, "MESALLIAIT").
dico("M", 10, "MESALLIANT").
dico("M", 10, "MESALLIEES").
dico("M", 10, "MESALLIENT").
dico("M", 10, "MESALLIERA").
dico("M", 10, "MESALLIIEZ").
dico("M", 10, "MESALLIONS").
dico("M", 10, "MESANGETTE").
dico("M", 10, "MESAXONIEN").
dico("M", 10, "MESCALINES").
dico("M", 10, "MESENCHYME").
dico("M", 10, "MESENTENTE").
dico("M", 10, "MESENTERES").
dico("M", 10, "MESESTIMAI").
dico("M", 10, "MESESTIMAS").
dico("M", 10, "MESESTIMAT").
dico("M", 10, "MESESTIMEE").
dico("M", 10, "MESESTIMER").
dico("M", 10, "MESESTIMES").
dico("M", 10, "MESESTIMEZ").
dico("M", 10, "MESMERIENS").
dico("M", 10, "MESMERISME").
dico("M", 10, "MESOBLASTE").
dico("M", 10, "MESOCARPES").
dico("M", 10, "MESODERMES").
dico("M", 10, "MESOMERIES").
dico("M", 10, "MESOMORPHE").
dico("M", 10, "MESOPAUSES").
dico("M", 10, "MESOSCAPHE").
dico("M", 10, "MESOSPHERE").
dico("M", 10, "MESOTHORAX").
dico("M", 10, "MESOZOAIRE").
dico("M", 10, "MESOZOIQUE").
dico("M", 10, "MESSAGERES").
dico("M", 10, "MESSAGERIE").
dico("M", 10, "MESSALINES").
dico("M", 10, "MESSEANTES").
dico("M", 10, "MESSIERAIT").
dico("M", 10, "MESSIERONT").
dico("M", 10, "MESTRANCES").
dico("M", 10, "MESURABLES").
dico("M", 10, "MESURAIENT").
dico("M", 10, "MESURASSES").
dico("M", 10, "MESUREMENT").
dico("M", 10, "MESURERAIS").
dico("M", 10, "MESURERAIT").
dico("M", 10, "MESURERENT").
dico("M", 10, "MESURERIEZ").
dico("M", 10, "MESURERONS").
dico("M", 10, "MESURERONT").
dico("M", 10, "MESURETTES").
dico("M", 10, "MESUREUSES").
dico("M", 10, "MESUSAIENT").
dico("M", 10, "MESUSASSES").
dico("M", 10, "MESUSERAIS").
dico("M", 10, "MESUSERAIT").
dico("M", 10, "MESUSERENT").
dico("M", 10, "MESUSERIEZ").
dico("M", 10, "MESUSERONS").
dico("M", 10, "MESUSERONT").
dico("M", 10, "METABOLISA").
dico("M", 10, "METABOLISE").
dico("M", 10, "METABOLITE").
dico("M", 10, "METACARPES").
dico("M", 10, "METACENTRE").
dico("M", 10, "METALANGUE").
dico("M", 10, "METALEPSES").
dico("M", 10, "METALLERIE").
dico("M", 10, "METALLIERE").
dico("M", 10, "METALLIERS").
dico("M", 10, "METALLIQUE").
dico("M", 10, "METALLISAI").
dico("M", 10, "METALLISAS").
dico("M", 10, "METALLISAT").
dico("M", 10, "METALLISEE").
dico("M", 10, "METALLISER").
dico("M", 10, "METALLISES").
dico("M", 10, "METALLISEZ").
dico("M", 10, "METALLOIDE").
dico("M", 10, "METAMERIES").
dico("M", 10, "METAMERISE").
dico("M", 10, "METAPHASES").
dico("M", 10, "METAPHORES").
dico("M", 10, "METAPHRASE").
dico("M", 10, "METAPHYSES").
dico("M", 10, "METAPLASIE").
dico("M", 10, "METASTABLE").
dico("M", 10, "METASTASAI").
dico("M", 10, "METASTASAS").
dico("M", 10, "METASTASAT").
dico("M", 10, "METASTASEE").
dico("M", 10, "METASTASER").
dico("M", 10, "METASTASES").
dico("M", 10, "METASTASEZ").
dico("M", 10, "METATARSES").
dico("M", 10, "METATHESES").
dico("M", 10, "METATHORAX").
dico("M", 10, "METAZOAIRE").
dico("M", 10, "METEORIQUE").
dico("M", 10, "METEORISAI").
dico("M", 10, "METEORISAS").
dico("M", 10, "METEORISAT").
dico("M", 10, "METEORISEE").
dico("M", 10, "METEORISER").
dico("M", 10, "METEORISES").
dico("M", 10, "METEORISEZ").
dico("M", 10, "METEORISME").
dico("M", 10, "METEORITES").
dico("M", 10, "METHADONES").
dico("M", 10, "METHANIERE").
dico("M", 10, "METHANIERS").
dico("M", 10, "METHANISAI").
dico("M", 10, "METHANISAS").
dico("M", 10, "METHANISAT").
dico("M", 10, "METHANISEE").
dico("M", 10, "METHANISER").
dico("M", 10, "METHANISES").
dico("M", 10, "METHANISEZ").
dico("M", 10, "METHANODUC").
dico("M", 10, "METHIONINE").
dico("M", 10, "METHODIQUE").
dico("M", 10, "METHODISME").
dico("M", 10, "METHODISTE").
dico("M", 10, "METHYLENES").
dico("M", 10, "METHYLIQUE").
dico("M", 10, "METICULEUX").
dico("M", 10, "METISSAGES").
dico("M", 10, "METISSAMES").
dico("M", 10, "METISSASSE").
dico("M", 10, "METISSATES").
dico("M", 10, "METISSERAI").
dico("M", 10, "METISSERAS").
dico("M", 10, "METISSEREZ").
dico("M", 10, "METISSIONS").
dico("M", 10, "METONYMIES").
dico("M", 10, "METOPIQUES").
dico("M", 10, "METRASSENT").
dico("M", 10, "METRASSIEZ").
dico("M", 10, "METRERIONS").
dico("M", 10, "METRICIENS").
dico("M", 10, "METRISABLE").
dico("M", 10, "METROLOGIE").
dico("M", 10, "METROLOGUE").
dico("M", 10, "METROMANES").
dico("M", 10, "METROMANIE").
dico("M", 10, "METRONOMES").
dico("M", 10, "METROPOLES").
dico("M", 10, "METTRAIENT").
dico("M", 10, "MEUBLAIENT").
dico("M", 10, "MEUBLANTES").
dico("M", 10, "MEUBLASSES").
dico("M", 10, "MEUBLERAIS").
dico("M", 10, "MEUBLERAIT").
dico("M", 10, "MEUBLERENT").
dico("M", 10, "MEUBLERIEZ").
dico("M", 10, "MEUBLERONS").
dico("M", 10, "MEUBLERONT").
dico("M", 10, "MEUGLAIENT").
dico("M", 10, "MEUGLASSES").
dico("M", 10, "MEUGLEMENT").
dico("M", 10, "MEUGLERAIS").
dico("M", 10, "MEUGLERAIT").
dico("M", 10, "MEUGLERENT").
dico("M", 10, "MEUGLERIEZ").
dico("M", 10, "MEUGLERONS").
dico("M", 10, "MEUGLERONT").
dico("M", 10, "MEULASSENT").
dico("M", 10, "MEULASSIEZ").
dico("M", 10, "MEULERIONS").
dico("M", 10, "MEURSAULTS").
dico("M", 10, "MEURTRIERE").
dico("M", 10, "MEURTRIERS").
dico("M", 10, "MEURTRIMES").
dico("M", 10, "MEURTRIRAI").
dico("M", 10, "MEURTRIRAS").
dico("M", 10, "MEURTRIREZ").
dico("M", 10, "MEURTRISSE").
dico("M", 10, "MEURTRITES").
dico("M", 10, "MEUSIENNES").
dico("M", 10, "MEVENDIMES").
dico("M", 10, "MEVENDIONS").
dico("M", 10, "MEVENDISSE").
dico("M", 10, "MEVENDITES").
dico("M", 10, "MEVENDRAIS").
dico("M", 10, "MEVENDRAIT").
dico("M", 10, "MEVENDRIEZ").
dico("M", 10, "MEVENDRONS").
dico("M", 10, "MEVENDRONT").
dico("M", 10, "MEXICAINES").
dico("M", 10, "MEZZANINES").
dico("M", 10, "MEZZOTINTO").
dico("M", 10, "MIAULAIENT").
dico("M", 10, "MIAULASSES").
dico("M", 10, "MIAULEMENT").
dico("M", 10, "MIAULERAIS").
dico("M", 10, "MIAULERAIT").
dico("M", 10, "MIAULERENT").
dico("M", 10, "MIAULERIEZ").
dico("M", 10, "MIAULERONS").
dico("M", 10, "MIAULERONT").
dico("M", 10, "MIAULEUSES").
dico("M", 10, "MICELLAIRE").
dico("M", 10, "MICHELINES").
dico("M", 10, "MICHETONNA").
dico("M", 10, "MICHETONNE").
dico("M", 10, "MICOQUIENS").
dico("M", 10, "MICROBIENS").
dico("M", 10, "MICROBILLE").
dico("M", 10, "MICROCARTE").
dico("M", 10, "MICROCLINE").
dico("M", 10, "MICROCOPIA").
dico("M", 10, "MICROCOPIE").
dico("M", 10, "MICROCOQUE").
dico("M", 10, "MICROCOSME").
dico("M", 10, "MICROCURIE").
dico("M", 10, "MICROFARAD").
dico("M", 10, "MICROFAUNE").
dico("M", 10, "MICROFIBRE").
dico("M", 10, "MICROFICHA").
dico("M", 10, "MICROFICHE").
dico("M", 10, "MICROFILMA").
dico("M", 10, "MICROFILME").
dico("M", 10, "MICROFILMS").
dico("M", 10, "MICROFLORE").
dico("M", 10, "MICROFORME").
dico("M", 10, "MICROGLIES").
dico("M", 10, "MICROGRENU").
dico("M", 10, "MICROLITES").
dico("M", 10, "MICROLITHE").
dico("M", 10, "MICROMETRE").
dico("M", 10, "MICRONISAI").
dico("M", 10, "MICRONISAS").
dico("M", 10, "MICRONISAT").
dico("M", 10, "MICRONISEE").
dico("M", 10, "MICRONISER").
dico("M", 10, "MICRONISES").
dico("M", 10, "MICRONISEZ").
dico("M", 10, "MICRONOYAU").
dico("M", 10, "MICROPHAGE").
dico("M", 10, "MICROPHONE").
dico("M", 10, "MICROPSIES").
dico("M", 10, "MICROPYLES").
dico("M", 10, "MICROSCOPE").
dico("M", 10, "MICROSONDE").
dico("M", 10, "MICROSPORE").
dico("M", 10, "MICROTOMES").
dico("M", 10, "MICTIONNEL").
dico("M", 10, "MIDINETTES").
dico("M", 10, "MIDSHIPMAN").
dico("M", 10, "MIDSHIPMEN").
dico("M", 10, "MIELLEUSES").
dico("M", 10, "MIEVREMENT").
dico("M", 10, "MIEVRERIES").
dico("M", 10, "MIGMATITES").
dico("M", 10, "MIGNARDAIS").
dico("M", 10, "MIGNARDAIT").
dico("M", 10, "MIGNARDANT").
dico("M", 10, "MIGNARDEES").
dico("M", 10, "MIGNARDENT").
dico("M", 10, "MIGNARDERA").
dico("M", 10, "MIGNARDIEZ").
dico("M", 10, "MIGNARDISE").
dico("M", 10, "MIGNARDONS").
dico("M", 10, "MIGNONNETS").
dico("M", 10, "MIGNOTAMES").
dico("M", 10, "MIGNOTASSE").
dico("M", 10, "MIGNOTATES").
dico("M", 10, "MIGNOTERAI").
dico("M", 10, "MIGNOTERAS").
dico("M", 10, "MIGNOTEREZ").
dico("M", 10, "MIGNOTIONS").
dico("M", 10, "MIGRAINEUX").
dico("M", 10, "MIGRASSENT").
dico("M", 10, "MIGRASSIEZ").
dico("M", 10, "MIGRATEURS").
dico("M", 10, "MIGRATIONS").
dico("M", 10, "MIGRATOIRE").
dico("M", 10, "MIGRATRICE").
dico("M", 10, "MIGRERIONS").
dico("M", 10, "MIJOTAIENT").
dico("M", 10, "MIJOTASSES").
dico("M", 10, "MIJOTERAIS").
dico("M", 10, "MIJOTERAIT").
dico("M", 10, "MIJOTERENT").
dico("M", 10, "MIJOTERIEZ").
dico("M", 10, "MIJOTERONS").
dico("M", 10, "MIJOTERONT").
dico("M", 10, "MIJOTEUSES").
dico("M", 10, "MILANAISES").
dico("M", 10, "MILDIOUSEE").
dico("M", 10, "MILDIOUSES").
dico("M", 10, "MILICIENNE").
dico("M", 10, "MILITAIENT").
dico("M", 10, "MILITAIRES").
dico("M", 10, "MILITANCES").
dico("M", 10, "MILITANTES").
dico("M", 10, "MILITARISA").
dico("M", 10, "MILITARISE").
dico("M", 10, "MILITASSES").
dico("M", 10, "MILITERAIS").
dico("M", 10, "MILITERAIT").
dico("M", 10, "MILITERENT").
dico("M", 10, "MILITERIEZ").
dico("M", 10, "MILITERONS").
dico("M", 10, "MILITERONT").
dico("M", 10, "MILLEFIORI").
dico("M", 10, "MILLENAIRE").
dico("M", 10, "MILLENIUMS").
dico("M", 10, "MILLEPORES").
dico("M", 10, "MILLERAIES").
dico("M", 10, "MILLERANDE").
dico("M", 10, "MILLESIMAI").
dico("M", 10, "MILLESIMAS").
dico("M", 10, "MILLESIMAT").
dico("M", 10, "MILLESIMEE").
dico("M", 10, "MILLESIMER").
dico("M", 10, "MILLESIMES").
dico("M", 10, "MILLESIMEZ").
dico("M", 10, "MILLIAIRES").
dico("M", 10, "MILLIASSES").
dico("M", 10, "MILLICURIE").
dico("M", 10, "MILLILITRE").
dico("M", 10, "MILLIMETRA").
dico("M", 10, "MILLIMETRE").
dico("M", 10, "MILLIVOLTS").
dico("M", 10, "MIMASSIONS").
dico("M", 10, "MIMERAIENT").
dico("M", 10, "MIMETIQUES").
dico("M", 10, "MIMETISMES").
dico("M", 10, "MIMODRAMES").
dico("M", 10, "MIMOGRAPHE").
dico("M", 10, "MIMOLETTES").
dico("M", 10, "MIMOLOGIES").
dico("M", 10, "MIMOSACEES").
dico("M", 10, "MINAHOUETS").
dico("M", 10, "MINASSIONS").
dico("M", 10, "MINAUDAMES").
dico("M", 10, "MINAUDASSE").
dico("M", 10, "MINAUDATES").
dico("M", 10, "MINAUDERAI").
dico("M", 10, "MINAUDERAS").
dico("M", 10, "MINAUDEREZ").
dico("M", 10, "MINAUDERIE").
dico("M", 10, "MINAUDIERE").
dico("M", 10, "MINAUDIERS").
dico("M", 10, "MINAUDIONS").
dico("M", 10, "MINCIRIONS").
dico("M", 10, "MINCISSAIS").
dico("M", 10, "MINCISSAIT").
dico("M", 10, "MINCISSANT").
dico("M", 10, "MINCISSENT").
dico("M", 10, "MINCISSIEZ").
dico("M", 10, "MINCISSONS").
dico("M", 10, "MINCOLETTE").
dico("M", 10, "MINERAIENT").
dico("M", 10, "MINERALIER").
dico("M", 10, "MINERALISA").
dico("M", 10, "MINERALISE").
dico("M", 10, "MINERALITE").
dico("M", 10, "MINERVISTE").
dico("M", 10, "MINESTRONE").
dico("M", 10, "MINIATUREE").
dico("M", 10, "MINIATURES").
dico("M", 10, "MINICHAINE").
dico("M", 10, "MINIDISQUE").
dico("M", 10, "MINIMALISA").
dico("M", 10, "MINIMALISE").
dico("M", 10, "MINIMANTES").
dico("M", 10, "MINIMEXEES").
dico("M", 10, "MINIMISAIS").
dico("M", 10, "MINIMISAIT").
dico("M", 10, "MINIMISANT").
dico("M", 10, "MINIMISEES").
dico("M", 10, "MINIMISENT").
dico("M", 10, "MINIMISERA").
dico("M", 10, "MINIMISIEZ").
dico("M", 10, "MINIMISONS").
dico("M", 10, "MINIPILULE").
dico("M", 10, "MINISTERES").
dico("M", 10, "MINIVAGUES").
dico("M", 10, "MINNESANGS").
dico("M", 10, "MINORAIENT").
dico("M", 10, "MINORANTES").
dico("M", 10, "MINORASSES").
dico("M", 10, "MINORATIFS").
dico("M", 10, "MINORATION").
dico("M", 10, "MINORATIVE").
dico("M", 10, "MINORERAIS").
dico("M", 10, "MINORERAIT").
dico("M", 10, "MINORERENT").
dico("M", 10, "MINORERIEZ").
dico("M", 10, "MINORERONS").
dico("M", 10, "MINORERONT").
dico("M", 10, "MINORISAIS").
dico("M", 10, "MINORISAIT").
dico("M", 10, "MINORISANT").
dico("M", 10, "MINORISEES").
dico("M", 10, "MINORISENT").
dico("M", 10, "MINORISERA").
dico("M", 10, "MINORISIEZ").
dico("M", 10, "MINORISONS").
dico("M", 10, "MINORQUINE").
dico("M", 10, "MINORQUINS").
dico("M", 10, "MINOTERIES").
dico("M", 10, "MINOTIERES").
dico("M", 10, "MINOUCHAIS").
dico("M", 10, "MINOUCHAIT").
dico("M", 10, "MINOUCHANT").
dico("M", 10, "MINOUCHEES").
dico("M", 10, "MINOUCHENT").
dico("M", 10, "MINOUCHERA").
dico("M", 10, "MINOUCHIEZ").
dico("M", 10, "MINOUCHONS").
dico("M", 10, "MINUSCULES").
dico("M", 10, "MINUTAIENT").
dico("M", 10, "MINUTAIRES").
dico("M", 10, "MINUTASSES").
dico("M", 10, "MINUTERAIS").
dico("M", 10, "MINUTERAIT").
dico("M", 10, "MINUTERENT").
dico("M", 10, "MINUTERIES").
dico("M", 10, "MINUTERIEZ").
dico("M", 10, "MINUTERONS").
dico("M", 10, "MINUTERONT").
dico("M", 10, "MINUTIEUSE").
dico("M", 10, "MIRABELLES").
dico("M", 10, "MIRACIDIUM").
dico("M", 10, "MIRACULEES").
dico("M", 10, "MIRACULEUX").
dico("M", 10, "MIRASSIONS").
dico("M", 10, "MIRERAIENT").
dico("M", 10, "MIRIFIQUES").
dico("M", 10, "MIRLIFLORE").
dico("M", 10, "MIRLIFLORS").
dico("M", 10, "MIRMILLONS").
dico("M", 10, "MIROBOLANT").
dico("M", 10, "MIRODROMES").
dico("M", 10, "MIROITAMES").
dico("M", 10, "MIROITANTE").
dico("M", 10, "MIROITANTS").
dico("M", 10, "MIROITASSE").
dico("M", 10, "MIROITATES").
dico("M", 10, "MIROITERAI").
dico("M", 10, "MIROITERAS").
dico("M", 10, "MIROITEREZ").
dico("M", 10, "MIROITERIE").
dico("M", 10, "MIROITIERE").
dico("M", 10, "MIROITIERS").
dico("M", 10, "MIROITIONS").
dico("M", 10, "MISANDRIES").
dico("M", 10, "MISASSIONS").
dico("M", 10, "MISERABLES").
dico("M", 10, "MISERAIENT").
dico("M", 10, "MISEREUSES").
dico("M", 10, "MISOGAMIES").
dico("M", 10, "MISOGYNIES").
dico("M", 10, "MISONEISME").
dico("M", 10, "MISONEISTE").
dico("M", 10, "MISPICKELS").
dico("M", 10, "MISSILIERS").
dico("M", 10, "MISSIONNAI").
dico("M", 10, "MISSIONNAS").
dico("M", 10, "MISSIONNAT").
dico("M", 10, "MISSIONNEE").
dico("M", 10, "MISSIONNER").
dico("M", 10, "MISSIONNES").
dico("M", 10, "MISSIONNEZ").
dico("M", 10, "MISTOUFLES").
dico("M", 10, "MITASSIONS").
dico("M", 10, "MITERAIENT").
dico("M", 10, "MITHRAISME").
dico("M", 10, "MITHRIAQUE").
dico("M", 10, "MITIGATION").
dico("M", 10, "MITIGEAMES").
dico("M", 10, "MITIGEASSE").
dico("M", 10, "MITIGEATES").
dico("M", 10, "MITIGERAIS").
dico("M", 10, "MITIGERAIT").
dico("M", 10, "MITIGERENT").
dico("M", 10, "MITIGERIEZ").
dico("M", 10, "MITIGERONS").
dico("M", 10, "MITIGERONT").
dico("M", 10, "MITONNAMES").
dico("M", 10, "MITONNASSE").
dico("M", 10, "MITONNATES").
dico("M", 10, "MITONNERAI").
dico("M", 10, "MITONNERAS").
dico("M", 10, "MITONNEREZ").
dico("M", 10, "MITONNIONS").
dico("M", 10, "MITOTIQUES").
dico("M", 10, "MITOYENNES").
dico("M", 10, "MITRAILLAI").
dico("M", 10, "MITRAILLAS").
dico("M", 10, "MITRAILLAT").
dico("M", 10, "MITRAILLEE").
dico("M", 10, "MITRAILLER").
dico("M", 10, "MITRAILLES").
dico("M", 10, "MITRAILLEZ").
dico("M", 10, "MIXASSIONS").
dico("M", 10, "MIXERAIENT").
dico("M", 10, "MIXTILIGNE").
dico("M", 10, "MIXTIONNAI").
dico("M", 10, "MIXTIONNAS").
dico("M", 10, "MIXTIONNAT").
dico("M", 10, "MIXTIONNEE").
dico("M", 10, "MIXTIONNER").
dico("M", 10, "MIXTIONNES").
dico("M", 10, "MIXTIONNEZ").
dico("M", 10, "MNEMONIQUE").
dico("M", 10, "MOBILHOMES").
dico("M", 10, "MOBILIERES").
dico("M", 10, "MOBILISAIS").
dico("M", 10, "MOBILISAIT").
dico("M", 10, "MOBILISANT").
dico("M", 10, "MOBILISEES").
dico("M", 10, "MOBILISENT").
dico("M", 10, "MOBILISERA").
dico("M", 10, "MOBILISIEZ").
dico("M", 10, "MOBILISMES").
dico("M", 10, "MOBILISONS").
dico("M", 10, "MOBILISTES").
dico("M", 10, "MOBYLETTES").
dico("M", 10, "MODALISAIS").
dico("M", 10, "MODALISAIT").
dico("M", 10, "MODALISANT").
dico("M", 10, "MODALISEES").
dico("M", 10, "MODALISENT").
dico("M", 10, "MODALISERA").
dico("M", 10, "MODALISIEZ").
dico("M", 10, "MODALISONS").
dico("M", 10, "MODELAIENT").
dico("M", 10, "MODELASSES").
dico("M", 10, "MODELERAIS").
dico("M", 10, "MODELERAIT").
dico("M", 10, "MODELERENT").
dico("M", 10, "MODELERIEZ").
dico("M", 10, "MODELERONS").
dico("M", 10, "MODELERONT").
dico("M", 10, "MODELEUSES").
dico("M", 10, "MODELISAIS").
dico("M", 10, "MODELISAIT").
dico("M", 10, "MODELISANT").
dico("M", 10, "MODELISEES").
dico("M", 10, "MODELISENT").
dico("M", 10, "MODELISERA").
dico("M", 10, "MODELISIEZ").
dico("M", 10, "MODELISMES").
dico("M", 10, "MODELISONS").
dico("M", 10, "MODELISTES").
dico("M", 10, "MODENAISES").
dico("M", 10, "MODENATURE").
dico("M", 10, "MODERABLES").
dico("M", 10, "MODERAIENT").
dico("M", 10, "MODERASSES").
dico("M", 10, "MODERATEUR").
dico("M", 10, "MODERATION").
dico("M", 10, "MODEREMENT").
dico("M", 10, "MODERERAIS").
dico("M", 10, "MODERERAIT").
dico("M", 10, "MODERERENT").
dico("M", 10, "MODERERIEZ").
dico("M", 10, "MODERERONS").
dico("M", 10, "MODERERONT").
dico("M", 10, "MODERNISAI").
dico("M", 10, "MODERNISAS").
dico("M", 10, "MODERNISAT").
dico("M", 10, "MODERNISEE").
dico("M", 10, "MODERNISER").
dico("M", 10, "MODERNISES").
dico("M", 10, "MODERNISEZ").
dico("M", 10, "MODERNISME").
dico("M", 10, "MODERNISTE").
dico("M", 10, "MODERNITES").
dico("M", 10, "MODIFIABLE").
dico("M", 10, "MODIFIAMES").
dico("M", 10, "MODIFIANTE").
dico("M", 10, "MODIFIANTS").
dico("M", 10, "MODIFIASSE").
dico("M", 10, "MODIFIATES").
dico("M", 10, "MODIFIERAI").
dico("M", 10, "MODIFIERAS").
dico("M", 10, "MODIFIEREZ").
dico("M", 10, "MODIFIIONS").
dico("M", 10, "MODULABLES").
dico("M", 10, "MODULAIENT").
dico("M", 10, "MODULAIRES").
dico("M", 10, "MODULANTES").
dico("M", 10, "MODULARITE").
dico("M", 10, "MODULASSES").
dico("M", 10, "MODULATEUR").
dico("M", 10, "MODULATION").
dico("M", 10, "MODULERAIS").
dico("M", 10, "MODULERAIT").
dico("M", 10, "MODULERENT").
dico("M", 10, "MODULERIEZ").
dico("M", 10, "MODULERONS").
dico("M", 10, "MODULERONT").
dico("M", 10, "MOELLEUSES").
dico("M", 10, "MOELLONAGE").
dico("M", 10, "MOFFLAIENT").
dico("M", 10, "MOFFLASSES").
dico("M", 10, "MOFFLERAIS").
dico("M", 10, "MOFFLERAIT").
dico("M", 10, "MOFFLERENT").
dico("M", 10, "MOFFLERIEZ").
dico("M", 10, "MOFFLERONS").
dico("M", 10, "MOFFLERONT").
dico("M", 10, "MOFLASSENT").
dico("M", 10, "MOFLASSIEZ").
dico("M", 10, "MOFLERIONS").
dico("M", 10, "MOIERAIENT").
dico("M", 10, "MOINILLONS").
dico("M", 10, "MOIRASSENT").
dico("M", 10, "MOIRASSIEZ").
dico("M", 10, "MOIRERIONS").
dico("M", 10, "MOISASSENT").
dico("M", 10, "MOISASSIEZ").
dico("M", 10, "MOISERIONS").
dico("M", 10, "MOISIRIONS").
dico("M", 10, "MOISISSAIS").
dico("M", 10, "MOISISSAIT").
dico("M", 10, "MOISISSANT").
dico("M", 10, "MOISISSENT").
dico("M", 10, "MOISISSIEZ").
dico("M", 10, "MOISISSONS").
dico("M", 10, "MOISISSURE").
dico("M", 10, "MOISSONNAI").
dico("M", 10, "MOISSONNAS").
dico("M", 10, "MOISSONNAT").
dico("M", 10, "MOISSONNEE").
dico("M", 10, "MOISSONNER").
dico("M", 10, "MOISSONNES").
dico("M", 10, "MOISSONNEZ").
dico("M", 10, "MOITIRIONS").
dico("M", 10, "MOITISSAIS").
dico("M", 10, "MOITISSAIT").
dico("M", 10, "MOITISSANT").
dico("M", 10, "MOITISSENT").
dico("M", 10, "MOITISSIEZ").
dico("M", 10, "MOITISSONS").
dico("M", 10, "MOLARDAMES").
dico("M", 10, "MOLARDASSE").
dico("M", 10, "MOLARDATES").
dico("M", 10, "MOLARDERAI").
dico("M", 10, "MOLARDERAS").
dico("M", 10, "MOLARDEREZ").
dico("M", 10, "MOLARDIONS").
dico("M", 10, "MOLASSIQUE").
dico("M", 10, "MOLESKINES").
dico("M", 10, "MOLESTAMES").
dico("M", 10, "MOLESTASSE").
dico("M", 10, "MOLESTATES").
dico("M", 10, "MOLESTERAI").
dico("M", 10, "MOLESTERAS").
dico("M", 10, "MOLESTEREZ").
dico("M", 10, "MOLESTIONS").
dico("M", 10, "MOLETAIENT").
dico("M", 10, "MOLETASSES").
dico("M", 10, "MOLETERENT").
dico("M", 10, "MOLETTERAI").
dico("M", 10, "MOLETTERAS").
dico("M", 10, "MOLETTEREZ").
dico("M", 10, "MOLINISMES").
dico("M", 10, "MOLINISTES").
dico("M", 10, "MOLLARCHIE").
dico("M", 10, "MOLLARDAIS").
dico("M", 10, "MOLLARDAIT").
dico("M", 10, "MOLLARDANT").
dico("M", 10, "MOLLARDENT").
dico("M", 10, "MOLLARDERA").
dico("M", 10, "MOLLARDIEZ").
dico("M", 10, "MOLLARDONS").
dico("M", 10, "MOLLASSONS").
dico("M", 10, "MOLLETIERE").
dico("M", 10, "MOLLETONNA").
dico("M", 10, "MOLLETONNE").
dico("M", 10, "MOLLIRIONS").
dico("M", 10, "MOLLISSAIS").
dico("M", 10, "MOLLISSAIT").
dico("M", 10, "MOLLISSANT").
dico("M", 10, "MOLLISSENT").
dico("M", 10, "MOLLISSIEZ").
dico("M", 10, "MOLLISSONS").
dico("M", 10, "MOLLUSCUMS").
dico("M", 10, "MOLLUSQUES").
dico("M", 10, "MOLOSSOIDE").
dico("M", 10, "MOLYBDATES").
dico("M", 10, "MOLYBDENES").
dico("M", 10, "MOLYBDIQUE").
dico("M", 10, "MOMENTANEE").
dico("M", 10, "MOMENTANES").
dico("M", 10, "MOMIFIAMES").
dico("M", 10, "MOMIFIASSE").
dico("M", 10, "MOMIFIATES").
dico("M", 10, "MOMIFIERAI").
dico("M", 10, "MOMIFIERAS").
dico("M", 10, "MOMIFIEREZ").
dico("M", 10, "MOMIFIIONS").
dico("M", 10, "MOMIGNARDE").
dico("M", 10, "MOMIGNARDS").
dico("M", 10, "MOMINETTES").
dico("M", 10, "MOMORDIQUE").
dico("M", 10, "MONACHISME").
dico("M", 10, "MONADELPHE").
dico("M", 10, "MONADISMES").
dico("M", 10, "MONARCHIEN").
dico("M", 10, "MONARCHIES").
dico("M", 10, "MONARCHISA").
dico("M", 10, "MONARCHISE").
dico("M", 10, "MONASTERES").
dico("M", 10, "MONASTIQUE").
dico("M", 10, "MONAURALES").
dico("M", 10, "MONCTONIEN").
dico("M", 10, "MONDANITES").
dico("M", 10, "MONDASSENT").
dico("M", 10, "MONDASSIEZ").
dico("M", 10, "MONDERIONS").
dico("M", 10, "MONDIALISA").
dico("M", 10, "MONDIALISE").
dico("M", 10, "MONDIALITE").
dico("M", 10, "MONEGASQUE").
dico("M", 10, "MONETAIRES").
dico("M", 10, "MONETIQUES").
dico("M", 10, "MONETISAIS").
dico("M", 10, "MONETISAIT").
dico("M", 10, "MONETISANT").
dico("M", 10, "MONETISEES").
dico("M", 10, "MONETISENT").
dico("M", 10, "MONETISERA").
dico("M", 10, "MONETISIEZ").
dico("M", 10, "MONETISONS").
dico("M", 10, "MONGOLIENS").
dico("M", 10, "MONGOLIQUE").
dico("M", 10, "MONGOLISME").
dico("M", 10, "MONGOLOIDE").
dico("M", 10, "MONILIOSES").
dico("M", 10, "MONITOIRES").
dico("M", 10, "MONITORAGE").
dico("M", 10, "MONITORATS").
dico("M", 10, "MONITORING").
dico("M", 10, "MONITRICES").
dico("M", 10, "MONNAIERAI").
dico("M", 10, "MONNAIERAS").
dico("M", 10, "MONNAIEREZ").
dico("M", 10, "MONNAYABLE").
dico("M", 10, "MONNAYAGES").
dico("M", 10, "MONNAYAMES").
dico("M", 10, "MONNAYASSE").
dico("M", 10, "MONNAYATES").
dico("M", 10, "MONNAYERAI").
dico("M", 10, "MONNAYERAS").
dico("M", 10, "MONNAYEREZ").
dico("M", 10, "MONNAYEURS").
dico("M", 10, "MONNAYIONS").
dico("M", 10, "MONOACIDES").
dico("M", 10, "MONOAMINES").
dico("M", 10, "MONOBLASTE").
dico("M", 10, "MONOCABLES").
dico("M", 10, "MONOCHROME").
dico("M", 10, "MONOCLINAL").
dico("M", 10, "MONOCLONAL").
dico("M", 10, "MONOCOLORE").
dico("M", 10, "MONOCOQUES").
dico("M", 10, "MONOCORDES").
dico("M", 10, "MONOCRATIE").
dico("M", 10, "MONOCYCLES").
dico("M", 10, "MONODIQUES").
dico("M", 10, "MONOGAMIES").
dico("M", 10, "MONOGATARI").
dico("M", 10, "MONOGRAMME").
dico("M", 10, "MONOLINGUE").
dico("M", 10, "MONOLITHES").
dico("M", 10, "MONOLOGUAI").
dico("M", 10, "MONOLOGUAS").
dico("M", 10, "MONOLOGUAT").
dico("M", 10, "MONOLOGUER").
dico("M", 10, "MONOLOGUES").
dico("M", 10, "MONOLOGUEZ").
dico("M", 10, "MONOMANIES").
dico("M", 10, "MONOMETRES").
dico("M", 10, "MONOMOTEUR").
dico("M", 10, "MONONUCLEE").
dico("M", 10, "MONOPHASEE").
dico("M", 10, "MONOPHASES").
dico("M", 10, "MONOPHONIE").
dico("M", 10, "MONOPLACES").
dico("M", 10, "MONOPLEGIE").
dico("M", 10, "MONOPOLEUR").
dico("M", 10, "MONOPOLISA").
dico("M", 10, "MONOPOLISE").
dico("M", 10, "MONOPOSTES").
dico("M", 10, "MONOPSONES").
dico("M", 10, "MONOPTERES").
dico("M", 10, "MONORCHIDE").
dico("M", 10, "MONOSEMIES").
dico("M", 10, "MONOSEPALE").
dico("M", 10, "MONOSKIEUR").
dico("M", 10, "MONOSPACES").
dico("M", 10, "MONOSPERME").
dico("M", 10, "MONOSTABLE").
dico("M", 10, "MONOSTYLES").
dico("M", 10, "MONOTACHES").
dico("M", 10, "MONOTONIES").
dico("M", 10, "MONOTRACES").
dico("M", 10, "MONOTREMES").
dico("M", 10, "MONOTROPES").
dico("M", 10, "MONOVALENT").
dico("M", 10, "MONOZYGOTE").
dico("M", 10, "MONROVIENS").
dico("M", 10, "MONSIGNORE").
dico("M", 10, "MONSIGNORI").
dico("M", 10, "MONSIGNORS").
dico("M", 10, "MONSTRANCE").
dico("M", 10, "MONSTRESSE").
dico("M", 10, "MONSTRUEUX").
dico("M", 10, "MONTAGNAIS").
dico("M", 10, "MONTAGNARD").
dico("M", 10, "MONTAGNEUX").
dico("M", 10, "MONTAISONS").
dico("M", 10, "MONTANISME").
dico("M", 10, "MONTANISTE").
dico("M", 10, "MONTASSENT").
dico("M", 10, "MONTASSIEZ").
dico("M", 10, "MONTERIONS").
dico("M", 10, "MONTICOLES").
dico("M", 10, "MONTICULES").
dico("M", 10, "MONTIENNES").
dico("M", 10, "MONTRABLES").
dico("M", 10, "MONTRACHET").
dico("M", 10, "MONTRAIENT").
dico("M", 10, "MONTRASSES").
dico("M", 10, "MONTRERAIS").
dico("M", 10, "MONTRERAIT").
dico("M", 10, "MONTRERENT").
dico("M", 10, "MONTRERIEZ").
dico("M", 10, "MONTRERONS").
dico("M", 10, "MONTRERONT").
dico("M", 10, "MONTREUSES").
dico("M", 10, "MONTUEUSES").
dico("M", 10, "MONUMENTAL").
dico("M", 10, "MOQUASSENT").
dico("M", 10, "MOQUASSIEZ").
dico("M", 10, "MOQUERIONS").
dico("M", 10, "MOQUETTAIS").
dico("M", 10, "MOQUETTAIT").
dico("M", 10, "MOQUETTANT").
dico("M", 10, "MOQUETTEES").
dico("M", 10, "MOQUETTENT").
dico("M", 10, "MOQUETTERA").
dico("M", 10, "MOQUETTIEZ").
dico("M", 10, "MOQUETTONS").
dico("M", 10, "MORAILLAIS").
dico("M", 10, "MORAILLAIT").
dico("M", 10, "MORAILLANT").
dico("M", 10, "MORAILLEES").
dico("M", 10, "MORAILLENT").
dico("M", 10, "MORAILLERA").
dico("M", 10, "MORAILLIEZ").
dico("M", 10, "MORAILLONS").
dico("M", 10, "MORAINIQUE").
dico("M", 10, "MORALEMENT").
dico("M", 10, "MORALISAIS").
dico("M", 10, "MORALISAIT").
dico("M", 10, "MORALISANT").
dico("M", 10, "MORALISEES").
dico("M", 10, "MORALISENT").
dico("M", 10, "MORALISERA").
dico("M", 10, "MORALISEUR").
dico("M", 10, "MORALISIEZ").
dico("M", 10, "MORALISMES").
dico("M", 10, "MORALISONS").
dico("M", 10, "MORALISTES").
dico("M", 10, "MORATOIRES").
dico("M", 10, "MORATORIUM").
dico("M", 10, "MORBIDESSE").
dico("M", 10, "MORBIDITES").
dico("M", 10, "MORBILLEUX").
dico("M", 10, "MORCELABLE").
dico("M", 10, "MORCELAMES").
dico("M", 10, "MORCELASSE").
dico("M", 10, "MORCELATES").
dico("M", 10, "MORCELIONS").
dico("M", 10, "MORCELLENT").
dico("M", 10, "MORCELLERA").
dico("M", 10, "MORDACITES").
dico("M", 10, "MORDANCAGE").
dico("M", 10, "MORDANCAIS").
dico("M", 10, "MORDANCAIT").
dico("M", 10, "MORDANCANT").
dico("M", 10, "MORDANCEES").
dico("M", 10, "MORDANCENT").
dico("M", 10, "MORDANCERA").
dico("M", 10, "MORDANCIEZ").
dico("M", 10, "MORDANCONS").
dico("M", 10, "MORDICANTE").
dico("M", 10, "MORDICANTS").
dico("M", 10, "MORDILLAGE").
dico("M", 10, "MORDILLAIS").
dico("M", 10, "MORDILLAIT").
dico("M", 10, "MORDILLANT").
dico("M", 10, "MORDILLEES").
dico("M", 10, "MORDILLENT").
dico("M", 10, "MORDILLERA").
dico("M", 10, "MORDILLIEZ").
dico("M", 10, "MORDILLONS").
dico("M", 10, "MORDISSENT").
dico("M", 10, "MORDISSIEZ").
dico("M", 10, "MORDORAMES").
dico("M", 10, "MORDORASSE").
dico("M", 10, "MORDORATES").
dico("M", 10, "MORDORERAI").
dico("M", 10, "MORDORERAS").
dico("M", 10, "MORDOREREZ").
dico("M", 10, "MORDORIONS").
dico("M", 10, "MORDORURES").
dico("M", 10, "MORDRAIENT").
dico("M", 10, "MORFALAMES").
dico("M", 10, "MORFALASSE").
dico("M", 10, "MORFALATES").
dico("M", 10, "MORFALERAI").
dico("M", 10, "MORFALERAS").
dico("M", 10, "MORFALEREZ").
dico("M", 10, "MORFALIONS").
dico("M", 10, "MORFILAGES").
dico("M", 10, "MORFILAMES").
dico("M", 10, "MORFILASSE").
dico("M", 10, "MORFILATES").
dico("M", 10, "MORFILERAI").
dico("M", 10, "MORFILERAS").
dico("M", 10, "MORFILEREZ").
dico("M", 10, "MORFILIONS").
dico("M", 10, "MORFLAIENT").
dico("M", 10, "MORFLASSES").
dico("M", 10, "MORFLERAIS").
dico("M", 10, "MORFLERAIT").
dico("M", 10, "MORFLERENT").
dico("M", 10, "MORFLERIEZ").
dico("M", 10, "MORFLERONS").
dico("M", 10, "MORFLERONT").
dico("M", 10, "MORFONDAIS").
dico("M", 10, "MORFONDAIT").
dico("M", 10, "MORFONDANT").
dico("M", 10, "MORFONDENT").
dico("M", 10, "MORFONDIEZ").
dico("M", 10, "MORFONDONS").
dico("M", 10, "MORFONDRAI").
dico("M", 10, "MORFONDRAS").
dico("M", 10, "MORFONDREZ").
dico("M", 10, "MORFONDUES").
dico("M", 10, "MORGANITES").
dico("M", 10, "MORGELINES").
dico("M", 10, "MORGUAIENT").
dico("M", 10, "MORGUASSES").
dico("M", 10, "MORGUERAIS").
dico("M", 10, "MORGUERAIT").
dico("M", 10, "MORGUERENT").
dico("M", 10, "MORGUERIEZ").
dico("M", 10, "MORGUERONS").
dico("M", 10, "MORGUERONT").
dico("M", 10, "MORGUIENNE").
dico("M", 10, "MORIBONDES").
dico("M", 10, "MORICAUDES").
dico("M", 10, "MORIGENAIS").
dico("M", 10, "MORIGENAIT").
dico("M", 10, "MORIGENANT").
dico("M", 10, "MORIGENEES").
dico("M", 10, "MORIGENENT").
dico("M", 10, "MORIGENERA").
dico("M", 10, "MORIGENIEZ").
dico("M", 10, "MORIGENONS").
dico("M", 10, "MORMONISME").
dico("M", 10, "MORONAISES").
dico("M", 10, "MORPHISMES").
dico("M", 10, "MORPHOGENE").
dico("M", 10, "MORTADELLE").
dico("M", 10, "MORTAISAGE").
dico("M", 10, "MORTAISAIS").
dico("M", 10, "MORTAISAIT").
dico("M", 10, "MORTAISANT").
dico("M", 10, "MORTAISEES").
dico("M", 10, "MORTAISENT").
dico("M", 10, "MORTAISERA").
dico("M", 10, "MORTAISEUR").
dico("M", 10, "MORTAISIEZ").
dico("M", 10, "MORTAISONS").
dico("M", 10, "MORTALITES").
dico("M", 10, "MORTIFERES").
dico("M", 10, "MORTIFIAIS").
dico("M", 10, "MORTIFIAIT").
dico("M", 10, "MORTIFIANT").
dico("M", 10, "MORTIFIEES").
dico("M", 10, "MORTIFIENT").
dico("M", 10, "MORTIFIERA").
dico("M", 10, "MORTIFIIEZ").
dico("M", 10, "MORTIFIONS").
dico("M", 10, "MORTUAIRES").
dico("M", 10, "MORUTIERES").
dico("M", 10, "MORVANDEAU").
dico("M", 10, "MORVANDIAU").
dico("M", 10, "MORVANDIOT").
dico("M", 10, "MOSAIQUEES").
dico("M", 10, "MOSCOVITES").
dico("M", 10, "MOSELLANES").
dico("M", 10, "MOTIONNAIS").
dico("M", 10, "MOTIONNAIT").
dico("M", 10, "MOTIONNANT").
dico("M", 10, "MOTIONNENT").
dico("M", 10, "MOTIONNERA").
dico("M", 10, "MOTIONNIEZ").
dico("M", 10, "MOTIONNONS").
dico("M", 10, "MOTIVAIENT").
dico("M", 10, "MOTIVANTES").
dico("M", 10, "MOTIVASSES").
dico("M", 10, "MOTIVATION").
dico("M", 10, "MOTIVERAIS").
dico("M", 10, "MOTIVERAIT").
dico("M", 10, "MOTIVERENT").
dico("M", 10, "MOTIVERIEZ").
dico("M", 10, "MOTIVERONS").
dico("M", 10, "MOTIVERONT").
dico("M", 10, "MOTOCISTES").
dico("M", 10, "MOTOCROTTE").
dico("M", 10, "MOTOCYCLES").
dico("M", 10, "MOTOMARINE").
dico("M", 10, "MOTONEIGES").
dico("M", 10, "MOTOPAVERS").
dico("M", 10, "MOTOPAVEUR").
dico("M", 10, "MOTOPOMPES").
dico("M", 10, "MOTORHOMES").
dico("M", 10, "MOTORISAIS").
dico("M", 10, "MOTORISAIT").
dico("M", 10, "MOTORISANT").
dico("M", 10, "MOTORISEES").
dico("M", 10, "MOTORISENT").
dico("M", 10, "MOTORISERA").
dico("M", 10, "MOTORISIEZ").
dico("M", 10, "MOTORISONS").
dico("M", 10, "MOTORISTES").
dico("M", 10, "MOTORSHIPS").
dico("M", 10, "MOTRICITES").
dico("M", 10, "MOTTASSENT").
dico("M", 10, "MOTTASSIEZ").
dico("M", 10, "MOTTERIONS").
dico("M", 10, "MOUCHAIENT").
dico("M", 10, "MOUCHARDAI").
dico("M", 10, "MOUCHARDAS").
dico("M", 10, "MOUCHARDAT").
dico("M", 10, "MOUCHARDEE").
dico("M", 10, "MOUCHARDER").
dico("M", 10, "MOUCHARDES").
dico("M", 10, "MOUCHARDEZ").
dico("M", 10, "MOUCHASSES").
dico("M", 10, "MOUCHERAIS").
dico("M", 10, "MOUCHERAIT").
dico("M", 10, "MOUCHERENT").
dico("M", 10, "MOUCHERIEZ").
dico("M", 10, "MOUCHERONS").
dico("M", 10, "MOUCHERONT").
dico("M", 10, "MOUCHETAIS").
dico("M", 10, "MOUCHETAIT").
dico("M", 10, "MOUCHETANT").
dico("M", 10, "MOUCHETEES").
dico("M", 10, "MOUCHETIEZ").
dico("M", 10, "MOUCHETONS").
dico("M", 10, "MOUCHETTES").
dico("M", 10, "MOUCHETURE").
dico("M", 10, "MOUDJAHIDS").
dico("M", 10, "MOUDRAIENT").
dico("M", 10, "MOUFETAMES").
dico("M", 10, "MOUFETASSE").
dico("M", 10, "MOUFETATES").
dico("M", 10, "MOUFETERAI").
dico("M", 10, "MOUFETERAS").
dico("M", 10, "MOUFETEREZ").
dico("M", 10, "MOUFETIONS").
dico("M", 10, "MOUFFETTES").
dico("M", 10, "MOUFLAIENT").
dico("M", 10, "MOUFLASSES").
dico("M", 10, "MOUFLERAIS").
dico("M", 10, "MOUFLERAIT").
dico("M", 10, "MOUFLERENT").
dico("M", 10, "MOUFLERIEZ").
dico("M", 10, "MOUFLERONS").
dico("M", 10, "MOUFLERONT").
dico("M", 10, "MOUFLETTES").
dico("M", 10, "MOUFTAIENT").
dico("M", 10, "MOUFTASSES").
dico("M", 10, "MOUFTERAIS").
dico("M", 10, "MOUFTERAIT").
dico("M", 10, "MOUFTERENT").
dico("M", 10, "MOUFTERIEZ").
dico("M", 10, "MOUFTERONS").
dico("M", 10, "MOUFTERONT").
dico("M", 10, "MOUILLABLE").
dico("M", 10, "MOUILLADES").
dico("M", 10, "MOUILLAGES").
dico("M", 10, "MOUILLAMES").
dico("M", 10, "MOUILLANCE").
dico("M", 10, "MOUILLANTE").
dico("M", 10, "MOUILLANTS").
dico("M", 10, "MOUILLASSE").
dico("M", 10, "MOUILLATES").
dico("M", 10, "MOUILLERAI").
dico("M", 10, "MOUILLERAS").
dico("M", 10, "MOUILLERES").
dico("M", 10, "MOUILLEREZ").
dico("M", 10, "MOUILLETTE").
dico("M", 10, "MOUILLEURS").
dico("M", 10, "MOUILLEUSE").
dico("M", 10, "MOUILLIONS").
dico("M", 10, "MOUILLOIRS").
dico("M", 10, "MOUILLURES").
dico("M", 10, "MOUJINGUES").
dico("M", 10, "MOULASSENT").
dico("M", 10, "MOULASSIEZ").
dico("M", 10, "MOULERIONS").
dico("M", 10, "MOULINAGES").
dico("M", 10, "MOULINAMES").
dico("M", 10, "MOULINASSE").
dico("M", 10, "MOULINATES").
dico("M", 10, "MOULINERAI").
dico("M", 10, "MOULINERAS").
dico("M", 10, "MOULINEREZ").
dico("M", 10, "MOULINETTE").
dico("M", 10, "MOULINEURS").
dico("M", 10, "MOULINEUSE").
dico("M", 10, "MOULINIERE").
dico("M", 10, "MOULINIERS").
dico("M", 10, "MOULINIONS").
dico("M", 10, "MOULINOISE").
dico("M", 10, "MOULURAGES").
dico("M", 10, "MOULURAMES").
dico("M", 10, "MOULURASSE").
dico("M", 10, "MOULURATES").
dico("M", 10, "MOULURERAI").
dico("M", 10, "MOULURERAS").
dico("M", 10, "MOULUREREZ").
dico("M", 10, "MOULURIERE").
dico("M", 10, "MOULURIERS").
dico("M", 10, "MOULURIONS").
dico("M", 10, "MOULUSSENT").
dico("M", 10, "MOULUSSIEZ").
dico("M", 10, "MOURRAIENT").
dico("M", 10, "MOURUSSENT").
dico("M", 10, "MOURUSSIEZ").
dico("M", 10, "MOUSCAILLE").
dico("M", 10, "MOUSQUETON").
dico("M", 10, "MOUSSAIENT").
dico("M", 10, "MOUSSANTES").
dico("M", 10, "MOUSSASSES").
dico("M", 10, "MOUSSELINE").
dico("M", 10, "MOUSSERAIS").
dico("M", 10, "MOUSSERAIT").
dico("M", 10, "MOUSSERENT").
dico("M", 10, "MOUSSERIEZ").
dico("M", 10, "MOUSSERONS").
dico("M", 10, "MOUSSERONT").
dico("M", 10, "MOUSSEUSES").
dico("M", 10, "MOUSTACHES").
dico("M", 10, "MOUSTACHUE").
dico("M", 10, "MOUSTACHUS").
dico("M", 10, "MOUSTERIEN").
dico("M", 10, "MOUSTIQUES").
dico("M", 10, "MOUTARDAIS").
dico("M", 10, "MOUTARDAIT").
dico("M", 10, "MOUTARDANT").
dico("M", 10, "MOUTARDEES").
dico("M", 10, "MOUTARDENT").
dico("M", 10, "MOUTARDERA").
dico("M", 10, "MOUTARDIER").
dico("M", 10, "MOUTARDIEZ").
dico("M", 10, "MOUTARDONS").
dico("M", 10, "MOUTONNAGE").
dico("M", 10, "MOUTONNAIS").
dico("M", 10, "MOUTONNAIT").
dico("M", 10, "MOUTONNANT").
dico("M", 10, "MOUTONNEES").
dico("M", 10, "MOUTONNENT").
dico("M", 10, "MOUTONNERA").
dico("M", 10, "MOUTONNEUX").
dico("M", 10, "MOUTONNIER").
dico("M", 10, "MOUTONNIEZ").
dico("M", 10, "MOUTONNONS").
dico("M", 10, "MOUVAISONS").
dico("M", 10, "MOUVEMENTA").
dico("M", 10, "MOUVEMENTE").
dico("M", 10, "MOUVEMENTS").
dico("M", 10, "MOUVRAIENT").
dico("M", 10, "MOYASSIONS").
dico("M", 10, "MOYENAGEUX").
dico("M", 10, "MOYENNAMES").
dico("M", 10, "MOYENNASSE").
dico("M", 10, "MOYENNATES").
dico("M", 10, "MOYENNERAI").
dico("M", 10, "MOYENNERAS").
dico("M", 10, "MOYENNEREZ").
dico("M", 10, "MOYENNIONS").
dico("M", 10, "MOZARTIENS").
dico("M", 10, "MOZZARELLA").
dico("M", 10, "MOZZARELLE").
dico("M", 10, "MUCHASSENT").
dico("M", 10, "MUCHASSIEZ").
dico("M", 10, "MUCHERIONS").
dico("M", 10, "MUCORACEES").
dico("M", 10, "MUCORINEES").
dico("M", 10, "MUGIRAIENT").
dico("M", 10, "MUGISSANTE").
dico("M", 10, "MUGISSANTS").
dico("M", 10, "MUGISSIONS").
dico("M", 10, "MULASSERIE").
dico("M", 10, "MULASSIERE").
dico("M", 10, "MULASSIERS").
dico("M", 10, "MULATRESSE").
dico("M", 10, "MULETIERES").
dico("M", 10, "MULHOUSIEN").
dico("M", 10, "MULTIBRINS").
dico("M", 10, "MULTICABLE").
dico("M", 10, "MULTICARTE").
dico("M", 10, "MULTICAULE").
dico("M", 10, "MULTICOQUE").
dico("M", 10, "MULTIFLORE").
dico("M", 10, "MULTIFORME").
dico("M", 10, "MULTIGRADE").
dico("M", 10, "MULTILOBEE").
dico("M", 10, "MULTILOBES").
dico("M", 10, "MULTIMEDIA").
dico("M", 10, "MULTIMETRE").
dico("M", 10, "MULTIMODAL").
dico("M", 10, "MULTIMODES").
dico("M", 10, "MULTINORME").
dico("M", 10, "MULTIPARES").
dico("M", 10, "MULTIPLETS").
dico("M", 10, "MULTIPLEXE").
dico("M", 10, "MULTIPLIAI").
dico("M", 10, "MULTIPLIAS").
dico("M", 10, "MULTIPLIAT").
dico("M", 10, "MULTIPLIEE").
dico("M", 10, "MULTIPLIER").
dico("M", 10, "MULTIPLIES").
dico("M", 10, "MULTIPLIEZ").
dico("M", 10, "MULTIPOINT").
dico("M", 10, "MULTIPOSTE").
dico("M", 10, "MULTIPRISE").
dico("M", 10, "MULTISALLE").
dico("M", 10, "MULTITACHE").
dico("M", 10, "MULTITUBES").
dico("M", 10, "MULTITUDES").
dico("M", 10, "MULTIVARIE").
dico("M", 10, "MULTIVOIES").
dico("M", 10, "MUNICHOISE").
dico("M", 10, "MUNICIPALE").
dico("M", 10, "MUNICIPAUX").
dico("M", 10, "MUNIFICENT").
dico("M", 10, "MUNIRAIENT").
dico("M", 10, "MUNISSIONS").
dico("M", 10, "MUNITIONNA").
dico("M", 10, "MUNITIONNE").
dico("M", 10, "MURAILLAIS").
dico("M", 10, "MURAILLAIT").
dico("M", 10, "MURAILLANT").
dico("M", 10, "MURAILLEES").
dico("M", 10, "MURAILLENT").
dico("M", 10, "MURAILLERA").
dico("M", 10, "MURAILLIEZ").
dico("M", 10, "MURAILLONS").
dico("M", 10, "MURALISMES").
dico("M", 10, "MURALISTES").
dico("M", 10, "MURASSIONS").
dico("M", 10, "MURERAIENT").
dico("M", 10, "MURIATIQUE").
dico("M", 10, "MURIRAIENT").
dico("M", 10, "MURISSAGES").
dico("M", 10, "MURISSANTE").
dico("M", 10, "MURISSANTS").
dico("M", 10, "MURISSERIE").
dico("M", 10, "MURISSIONS").
dico("M", 10, "MURMURAMES").
dico("M", 10, "MURMURANTE").
dico("M", 10, "MURMURANTS").
dico("M", 10, "MURMURASSE").
dico("M", 10, "MURMURATES").
dico("M", 10, "MURMURERAI").
dico("M", 10, "MURMURERAS").
dico("M", 10, "MURMUREREZ").
dico("M", 10, "MURMURIONS").
dico("M", 10, "MUSARAIGNE").
dico("M", 10, "MUSARDAMES").
dico("M", 10, "MUSARDASSE").
dico("M", 10, "MUSARDATES").
dico("M", 10, "MUSARDERAI").
dico("M", 10, "MUSARDERAS").
dico("M", 10, "MUSARDEREZ").
dico("M", 10, "MUSARDERIE").
dico("M", 10, "MUSARDEURS").
dico("M", 10, "MUSARDEUSE").
dico("M", 10, "MUSARDIONS").
dico("M", 10, "MUSARDISES").
dico("M", 10, "MUSASSIONS").
dico("M", 10, "MUSCADELLE").
dico("M", 10, "MUSCADIERS").
dico("M", 10, "MUSCADINES").
dico("M", 10, "MUSCARDINE").
dico("M", 10, "MUSCARDINS").
dico("M", 10, "MUSCARINES").
dico("M", 10, "MUSCICOLES").
dico("M", 10, "MUSCINALES").
dico("M", 10, "MUSCLAIENT").
dico("M", 10, "MUSCLASSES").
dico("M", 10, "MUSCLERAIS").
dico("M", 10, "MUSCLERAIT").
dico("M", 10, "MUSCLERENT").
dico("M", 10, "MUSCLERIEZ").
dico("M", 10, "MUSCLERONS").
dico("M", 10, "MUSCLERONT").
dico("M", 10, "MUSCOVITES").
dico("M", 10, "MUSCULAIRE").
dico("M", 10, "MUSCULEUSE").
dico("M", 10, "MUSEIFIAIS").
dico("M", 10, "MUSEIFIAIT").
dico("M", 10, "MUSEIFIANT").
dico("M", 10, "MUSEIFIEES").
dico("M", 10, "MUSEIFIENT").
dico("M", 10, "MUSEIFIERA").
dico("M", 10, "MUSEIFIIEZ").
dico("M", 10, "MUSEIFIONS").
dico("M", 10, "MUSELAIENT").
dico("M", 10, "MUSELASSES").
dico("M", 10, "MUSELERENT").
dico("M", 10, "MUSELIERES").
dico("M", 10, "MUSELLERAI").
dico("M", 10, "MUSELLERAS").
dico("M", 10, "MUSELLEREZ").
dico("M", 10, "MUSEOLOGIE").
dico("M", 10, "MUSEOLOGUE").
dico("M", 10, "MUSERAIENT").
dico("M", 10, "MUSEROLLES").
dico("M", 10, "MUSICALITE").
dico("M", 10, "MUSICIENNE").
dico("M", 10, "MUSIQUAMES").
dico("M", 10, "MUSIQUASSE").
dico("M", 10, "MUSIQUATES").
dico("M", 10, "MUSIQUERAI").
dico("M", 10, "MUSIQUERAS").
dico("M", 10, "MUSIQUEREZ").
dico("M", 10, "MUSIQUETTE").
dico("M", 10, "MUSIQUIONS").
dico("M", 10, "MUSQUAIENT").
dico("M", 10, "MUSQUASSES").
dico("M", 10, "MUSQUERAIS").
dico("M", 10, "MUSQUERAIT").
dico("M", 10, "MUSQUERENT").
dico("M", 10, "MUSQUERIEZ").
dico("M", 10, "MUSQUERONS").
dico("M", 10, "MUSQUERONT").
dico("M", 10, "MUSSASSENT").
dico("M", 10, "MUSSASSIEZ").
dico("M", 10, "MUSSERIONS").
dico("M", 10, "MUSTELIDES").
dico("M", 10, "MUSULMANES").
dico("M", 10, "MUTABILITE").
dico("M", 10, "MUTAGENESE").
dico("M", 10, "MUTASSIONS").
dico("M", 10, "MUTAZILITE").
dico("M", 10, "MUTERAIENT").
dico("M", 10, "MUTILAIENT").
dico("M", 10, "MUTILANTES").
dico("M", 10, "MUTILASSES").
dico("M", 10, "MUTILATEUR").
dico("M", 10, "MUTILATION").
dico("M", 10, "MUTILERAIS").
dico("M", 10, "MUTILERAIT").
dico("M", 10, "MUTILERENT").
dico("M", 10, "MUTILERIEZ").
dico("M", 10, "MUTILERONS").
dico("M", 10, "MUTILERONT").
dico("M", 10, "MUTINAIENT").
dico("M", 10, "MUTINASSES").
dico("M", 10, "MUTINERAIS").
dico("M", 10, "MUTINERAIT").
dico("M", 10, "MUTINERENT").
dico("M", 10, "MUTINERIES").
dico("M", 10, "MUTINERIEZ").
dico("M", 10, "MUTINERONS").
dico("M", 10, "MUTINERONT").
dico("M", 10, "MUTUALISAI").
dico("M", 10, "MUTUALISAS").
dico("M", 10, "MUTUALISAT").
dico("M", 10, "MUTUALISEE").
dico("M", 10, "MUTUALISER").
dico("M", 10, "MUTUALISES").
dico("M", 10, "MUTUALISEZ").
dico("M", 10, "MUTUALISME").
dico("M", 10, "MUTUALISTE").
dico("M", 10, "MUTUALITES").
dico("M", 10, "MYALGIQUES").
dico("M", 10, "MYASTHENIE").
dico("M", 10, "MYCELIENNE").
dico("M", 10, "MYCENIENNE").
dico("M", 10, "MYCODERMES").
dico("M", 10, "MYCOLOGIES").
dico("M", 10, "MYCOLOGUES").
dico("M", 10, "MYCOPLASME").
dico("M", 10, "MYCORHIZES").
dico("M", 10, "MYCOSIQUES").
dico("M", 10, "MYELINISEE").
dico("M", 10, "MYELINISES").
dico("M", 10, "MYELOCYTES").
dico("M", 10, "MYOCARDITE").
dico("M", 10, "MYOCASTORS").
dico("M", 10, "MYOGLOBINE").
dico("M", 10, "MYOGRAMMES").
dico("M", 10, "MYOGRAPHES").
dico("M", 10, "MYOGRAPHIE").
dico("M", 10, "MYOLOGIQUE").
dico("M", 10, "MYOMORPHES").
dico("M", 10, "MYOPATHIES").
dico("M", 10, "MYOPOTAMES").
dico("M", 10, "MYRIAMETRE").
dico("M", 10, "MYRIAPODES").
dico("M", 10, "MYRICACEES").
dico("M", 10, "MYROBALANS").
dico("M", 10, "MYROBOLANS").
dico("M", 10, "MYROXYLONS").
dico("M", 10, "MYRTIFORME").
dico("M", 10, "MYRTILLIER").
dico("M", 10, "MYSTAGOGIE").
dico("M", 10, "MYSTAGOGUE").
dico("M", 10, "MYSTERIEUX").
dico("M", 10, "MYSTICETES").
dico("M", 10, "MYSTICISME").
dico("M", 10, "MYSTICITES").
dico("M", 10, "MYSTIFIAIS").
dico("M", 10, "MYSTIFIAIT").
dico("M", 10, "MYSTIFIANT").
dico("M", 10, "MYSTIFIEES").
dico("M", 10, "MYSTIFIENT").
dico("M", 10, "MYSTIFIERA").
dico("M", 10, "MYSTIFIIEZ").
dico("M", 10, "MYSTIFIONS").
dico("M", 10, "MYTHIFIAIS").
dico("M", 10, "MYTHIFIAIT").
dico("M", 10, "MYTHIFIANT").
dico("M", 10, "MYTHIFIEES").
dico("M", 10, "MYTHIFIENT").
dico("M", 10, "MYTHIFIERA").
dico("M", 10, "MYTHIFIIEZ").
dico("M", 10, "MYTHIFIONS").
dico("M", 10, "MYTHOLOGIE").
dico("M", 10, "MYTHOLOGUE").
dico("M", 10, "MYTHOMANES").
dico("M", 10, "MYTHOMANIE").
dico("M", 10, "MYTILICOLE").
dico("M", 10, "MYXOEDEMES").
dico("M", 10, "MYXOMATOSE").
dico("M", 10, "MYXOMYCETE").
