dico("M", 5, "MAARS").
dico("M", 5, "MACHA").
dico("M", 5, "MACHE").
dico("M", 5, "MACHO").
dico("M", 5, "MACIS").
dico("M", 5, "MACLA").
dico("M", 5, "MACLE").
dico("M", 5, "MACON").
dico("M", 5, "MACRE").
dico("M", 5, "MACRO").
dico("M", 5, "MADRE").
dico("M", 5, "MAERL").
dico("M", 5, "MAFES").
dico("M", 5, "MAFIA").
dico("M", 5, "MAGES").
dico("M", 5, "MAGIE").
dico("M", 5, "MAGMA").
dico("M", 5, "MAGNA").
dico("M", 5, "MAGNE").
dico("M", 5, "MAGOT").
dico("M", 5, "MAHDI").
dico("M", 5, "MAIAS").
dico("M", 5, "MAIES").
dico("M", 5, "MAILS").
dico("M", 5, "MAINS").
dico("M", 5, "MAINT").
dico("M", 5, "MAIRE").
dico("M", 5, "MAJES").
dico("M", 5, "MAJOR").
dico("M", 5, "MAKIS").
dico("M", 5, "MALES").
dico("M", 5, "MALIN").
dico("M", 5, "MALIS").
dico("M", 5, "MALLE").
dico("M", 5, "MALMS").
dico("M", 5, "MALTA").
dico("M", 5, "MALTE").
dico("M", 5, "MALTS").
dico("M", 5, "MALUS").
dico("M", 5, "MAMAN").
dico("M", 5, "MAMBA").
dico("M", 5, "MAMBO").
dico("M", 5, "MAMIE").
dico("M", 5, "MAMMA").
dico("M", 5, "MAMMY").
dico("M", 5, "MAMYS").
dico("M", 5, "MANAS").
dico("M", 5, "MANAT").
dico("M", 5, "MANDA").
dico("M", 5, "MANDE").
dico("M", 5, "MANES").
dico("M", 5, "MANGA").
dico("M", 5, "MANGE").
dico("M", 5, "MANIA").
dico("M", 5, "MANIE").
dico("M", 5, "MANIF").
dico("M", 5, "MANIP").
dico("M", 5, "MANNE").
dico("M", 5, "MANON").
dico("M", 5, "MANOU").
dico("M", 5, "MANSE").
dico("M", 5, "MANTA").
dico("M", 5, "MANTE").
dico("M", 5, "MAORI").
dico("M", 5, "MAOUS").
dico("M", 5, "MAPPA").
dico("M", 5, "MAPPE").
dico("M", 5, "MAQUA").
dico("M", 5, "MAQUE").
dico("M", 5, "MARAS").
dico("M", 5, "MARCS").
dico("M", 5, "MARDI").
dico("M", 5, "MAREE").
dico("M", 5, "MARES").
dico("M", 5, "MARGE").
dico("M", 5, "MARIA").
dico("M", 5, "MARIE").
dico("M", 5, "MARIN").
dico("M", 5, "MARIS").
dico("M", 5, "MARKS").
dico("M", 5, "MARLE").
dico("M", 5, "MARLI").
dico("M", 5, "MARNA").
dico("M", 5, "MARNE").
dico("M", 5, "MARRA").
dico("M", 5, "MARRE").
dico("M", 5, "MARRI").
dico("M", 5, "MARTE").
dico("M", 5, "MASAI").
dico("M", 5, "MASER").
dico("M", 5, "MASOS").
dico("M", 5, "MASSA").
dico("M", 5, "MASSE").
dico("M", 5, "MATAF").
dico("M", 5, "MATAI").
dico("M", 5, "MATAS").
dico("M", 5, "MATAT").
dico("M", 5, "MATCH").
dico("M", 5, "MATEE").
dico("M", 5, "MATER").
dico("M", 5, "MATES").
dico("M", 5, "MATEZ").
dico("M", 5, "MATHS").
dico("M", 5, "MATIE").
dico("M", 5, "MATIF").
dico("M", 5, "MATIN").
dico("M", 5, "MATIR").
dico("M", 5, "MATIS").
dico("M", 5, "MATIT").
dico("M", 5, "MATON").
dico("M", 5, "MATOS").
dico("M", 5, "MATOU").
dico("M", 5, "MATTE").
dico("M", 5, "MATUS").
dico("M", 5, "MAULS").
dico("M", 5, "MAURE").
dico("M", 5, "MAUVE").
dico("M", 5, "MAXIS").
dico("M", 5, "MAYAS").
dico("M", 5, "MAYEN").
dico("M", 5, "MAYES").
dico("M", 5, "MAZAI").
dico("M", 5, "MAZAS").
dico("M", 5, "MAZAT").
dico("M", 5, "MAZEE").
dico("M", 5, "MAZER").
dico("M", 5, "MAZES").
dico("M", 5, "MAZEZ").
dico("M", 5, "MAZOT").
dico("M", 5, "MEATS").
dico("M", 5, "MECHA").
dico("M", 5, "MECHE").
dico("M", 5, "MEDES").
dico("M", 5, "MEDIA").
dico("M", 5, "MEDIS").
dico("M", 5, "MEDIT").
dico("M", 5, "MEDOC").
dico("M", 5, "MEFIA").
dico("M", 5, "MEFIE").
dico("M", 5, "MEGAS").
dico("M", 5, "MEGIE").
dico("M", 5, "MEGIR").
dico("M", 5, "MEGIS").
dico("M", 5, "MEGIT").
dico("M", 5, "MEGOT").
dico("M", 5, "MEIJI").
dico("M", 5, "MELAI").
dico("M", 5, "MELAS").
dico("M", 5, "MELAT").
dico("M", 5, "MELBA").
dico("M", 5, "MELEE").
dico("M", 5, "MELER").
dico("M", 5, "MELES").
dico("M", 5, "MELEZ").
dico("M", 5, "MELIA").
dico("M", 5, "MELOE").
dico("M", 5, "MELON").
dico("M", 5, "MELOS").
dico("M", 5, "MEMES").
dico("M", 5, "MEMOS").
dico("M", 5, "MENAI").
dico("M", 5, "MENAS").
dico("M", 5, "MENAT").
dico("M", 5, "MENEE").
dico("M", 5, "MENER").
dico("M", 5, "MENES").
dico("M", 5, "MENEZ").
dico("M", 5, "MENIN").
dico("M", 5, "MENON").
dico("M", 5, "MENSE").
dico("M", 5, "MENTE").
dico("M", 5, "MENTI").
dico("M", 5, "MENUE").
dico("M", 5, "MENUS").
dico("M", 5, "MERCI").
dico("M", 5, "MERDA").
dico("M", 5, "MERDE").
dico("M", 5, "MERES").
dico("M", 5, "MERLE").
dico("M", 5, "MERLS").
dico("M", 5, "MERLU").
dico("M", 5, "MEROU").
dico("M", 5, "MESAS").
dico("M", 5, "MESON").
dico("M", 5, "MESSE").
dico("M", 5, "METAL").
dico("M", 5, "METAS").
dico("M", 5, "METEO").
dico("M", 5, "METIS").
dico("M", 5, "METRA").
dico("M", 5, "METRE").
dico("M", 5, "METRO").
dico("M", 5, "METTE").
dico("M", 5, "MEUFS").
dico("M", 5, "MEULA").
dico("M", 5, "MEULE").
dico("M", 5, "MEURE").
dico("M", 5, "MEURS").
dico("M", 5, "MEURT").
dico("M", 5, "MEUTE").
dico("M", 5, "MEUVE").
dico("M", 5, "MEZES").
dico("M", 5, "MEZIG").
dico("M", 5, "MEZZE").
dico("M", 5, "MEZZO").
dico("M", 5, "MIAOU").
dico("M", 5, "MICAS").
dico("M", 5, "MICHE").
dico("M", 5, "MICRO").
dico("M", 5, "MIDIS").
dico("M", 5, "MIELS").
dico("M", 5, "MIENS").
dico("M", 5, "MIEUX").
dico("M", 5, "MIGRA").
dico("M", 5, "MIGRE").
dico("M", 5, "MILAN").
dico("M", 5, "MILER").
dico("M", 5, "MILES").
dico("M", 5, "MILLE").
dico("M", 5, "MIMAI").
dico("M", 5, "MIMAS").
dico("M", 5, "MIMAT").
dico("M", 5, "MIMEE").
dico("M", 5, "MIMER").
dico("M", 5, "MIMES").
dico("M", 5, "MIMEZ").
dico("M", 5, "MIMIS").
dico("M", 5, "MINAI").
dico("M", 5, "MINAS").
dico("M", 5, "MINAT").
dico("M", 5, "MINCE").
dico("M", 5, "MINCI").
dico("M", 5, "MINEE").
dico("M", 5, "MINER").
dico("M", 5, "MINES").
dico("M", 5, "MINET").
dico("M", 5, "MINEZ").
dico("M", 5, "MINGS").
dico("M", 5, "MINIS").
dico("M", 5, "MINON").
dico("M", 5, "MINOT").
dico("M", 5, "MINOU").
dico("M", 5, "MINUS").
dico("M", 5, "MIRAI").
dico("M", 5, "MIRAS").
dico("M", 5, "MIRAT").
dico("M", 5, "MIREE").
dico("M", 5, "MIRER").
dico("M", 5, "MIRES").
dico("M", 5, "MIREZ").
dico("M", 5, "MIROS").
dico("M", 5, "MISAI").
dico("M", 5, "MISAS").
dico("M", 5, "MISAT").
dico("M", 5, "MISEE").
dico("M", 5, "MISER").
dico("M", 5, "MISES").
dico("M", 5, "MISEZ").
dico("M", 5, "MISSE").
dico("M", 5, "MITAI").
dico("M", 5, "MITAN").
dico("M", 5, "MITAS").
dico("M", 5, "MITAT").
dico("M", 5, "MITEE").
dico("M", 5, "MITER").
dico("M", 5, "MITES").
dico("M", 5, "MITEZ").
dico("M", 5, "MITON").
dico("M", 5, "MITRE").
dico("M", 5, "MIXAI").
dico("M", 5, "MIXAS").
dico("M", 5, "MIXAT").
dico("M", 5, "MIXEE").
dico("M", 5, "MIXER").
dico("M", 5, "MIXES").
dico("M", 5, "MIXEZ").
dico("M", 5, "MIXTE").
dico("M", 5, "MNEME").
dico("M", 5, "MOCHE").
dico("M", 5, "MOCOS").
dico("M", 5, "MODAL").
dico("M", 5, "MODEM").
dico("M", 5, "MODES").
dico("M", 5, "MOERE").
dico("M", 5, "MOFLA").
dico("M", 5, "MOFLE").
dico("M", 5, "MOGOL").
dico("M", 5, "MOHOS").
dico("M", 5, "MOIES").
dico("M", 5, "MOINE").
dico("M", 5, "MOINS").
dico("M", 5, "MOIRA").
dico("M", 5, "MOIRE").
dico("M", 5, "MOISA").
dico("M", 5, "MOISE").
dico("M", 5, "MOISI").
dico("M", 5, "MOITE").
dico("M", 5, "MOITI").
dico("M", 5, "MOKAS").
dico("M", 5, "MOKOS").
dico("M", 5, "MOLES").
dico("M", 5, "MOLLE").
dico("M", 5, "MOLLI").
dico("M", 5, "MOLLO").
dico("M", 5, "MOLTO").
dico("M", 5, "MOLYS").
dico("M", 5, "MOMES").
dico("M", 5, "MOMIE").
dico("M", 5, "MONDA").
dico("M", 5, "MONDE").
dico("M", 5, "MONEL").
dico("M", 5, "MONEP").
dico("M", 5, "MONOI").
dico("M", 5, "MONOS").
dico("M", 5, "MONTA").
dico("M", 5, "MONTE").
dico("M", 5, "MONTS").
dico("M", 5, "MOQUA").
dico("M", 5, "MOQUE").
dico("M", 5, "MORAL").
dico("M", 5, "MORCE").
dico("M", 5, "MORDE").
dico("M", 5, "MORDS").
dico("M", 5, "MORDU").
dico("M", 5, "MORES").
dico("M", 5, "MORIO").
dico("M", 5, "MORNE").
dico("M", 5, "MORSE").
dico("M", 5, "MORTE").
dico("M", 5, "MORTS").
dico("M", 5, "MORUE").
dico("M", 5, "MORVE").
dico("M", 5, "MOSAN").
dico("M", 5, "MOTEL").
dico("M", 5, "MOTET").
dico("M", 5, "MOTIF").
dico("M", 5, "MOTOS").
dico("M", 5, "MOTTA").
dico("M", 5, "MOTTE").
dico("M", 5, "MOTUS").
dico("M", 5, "MOUDS").
dico("M", 5, "MOUES").
dico("M", 5, "MOULA").
dico("M", 5, "MOULE").
dico("M", 5, "MOULT").
dico("M", 5, "MOULU").
dico("M", 5, "MOUND").
dico("M", 5, "MOUTS").
dico("M", 5, "MOXAS").
dico("M", 5, "MOYAI").
dico("M", 5, "MOYAS").
dico("M", 5, "MOYAT").
dico("M", 5, "MOYEE").
dico("M", 5, "MOYEN").
dico("M", 5, "MOYER").
dico("M", 5, "MOYES").
dico("M", 5, "MOYEU").
dico("M", 5, "MOYEZ").
dico("M", 5, "MUAIS").
dico("M", 5, "MUAIT").
dico("M", 5, "MUANT").
dico("M", 5, "MUCHA").
dico("M", 5, "MUCHE").
dico("M", 5, "MUCOR").
dico("M", 5, "MUCUS").
dico("M", 5, "MUDRA").
dico("M", 5, "MUEES").
dico("M", 5, "MUENT").
dico("M", 5, "MUERA").
dico("M", 5, "MUETS").
dico("M", 5, "MUFLE").
dico("M", 5, "MUFTI").
dico("M", 5, "MUGES").
dico("M", 5, "MUGIE").
dico("M", 5, "MUGIR").
dico("M", 5, "MUGIS").
dico("M", 5, "MUGIT").
dico("M", 5, "MUIDS").
dico("M", 5, "MUIEZ").
dico("M", 5, "MULES").
dico("M", 5, "MULET").
dico("M", 5, "MULLA").
dico("M", 5, "MULON").
dico("M", 5, "MULOT").
dico("M", 5, "MULUD").
dico("M", 5, "MUMES").
dico("M", 5, "MUNDA").
dico("M", 5, "MUNGO").
dico("M", 5, "MUNIE").
dico("M", 5, "MUNIR").
dico("M", 5, "MUNIS").
dico("M", 5, "MUNIT").
dico("M", 5, "MUONS").
dico("M", 5, "MURAI").
dico("M", 5, "MURAL").
dico("M", 5, "MURAS").
dico("M", 5, "MURAT").
dico("M", 5, "MUREE").
dico("M", 5, "MURER").
dico("M", 5, "MURES").
dico("M", 5, "MURET").
dico("M", 5, "MUREX").
dico("M", 5, "MUREZ").
dico("M", 5, "MURIE").
dico("M", 5, "MURIN").
dico("M", 5, "MURIR").
dico("M", 5, "MURIS").
dico("M", 5, "MURIT").
dico("M", 5, "MURON").
dico("M", 5, "MUSAI").
dico("M", 5, "MUSAS").
dico("M", 5, "MUSAT").
dico("M", 5, "MUSCS").
dico("M", 5, "MUSEE").
dico("M", 5, "MUSER").
dico("M", 5, "MUSES").
dico("M", 5, "MUSEZ").
dico("M", 5, "MUSLI").
dico("M", 5, "MUSSA").
dico("M", 5, "MUSSE").
dico("M", 5, "MUSTS").
dico("M", 5, "MUTAI").
dico("M", 5, "MUTAS").
dico("M", 5, "MUTAT").
dico("M", 5, "MUTEE").
dico("M", 5, "MUTER").
dico("M", 5, "MUTES").
dico("M", 5, "MUTEZ").
dico("M", 5, "MUTIN").
dico("M", 5, "MYOME").
dico("M", 5, "MYOPE").
dico("M", 5, "MYRTE").
dico("M", 5, "MYTHE").
dico("M", 5, "MYTHO").
