dico("M", 6, "MAATJE").
dico("M", 6, "MABOUL").
dico("M", 6, "MACERA").
dico("M", 6, "MACERE").
dico("M", 6, "MACHAI").
dico("M", 6, "MACHAS").
dico("M", 6, "MACHAT").
dico("M", 6, "MACHEE").
dico("M", 6, "MACHER").
dico("M", 6, "MACHES").
dico("M", 6, "MACHEZ").
dico("M", 6, "MACHIN").
dico("M", 6, "MACHON").
dico("M", 6, "MACHOS").
dico("M", 6, "MACLAI").
dico("M", 6, "MACLAS").
dico("M", 6, "MACLAT").
dico("M", 6, "MACLEE").
dico("M", 6, "MACLER").
dico("M", 6, "MACLES").
dico("M", 6, "MACLEZ").
dico("M", 6, "MACONS").
dico("M", 6, "MACQUA").
dico("M", 6, "MACQUE").
dico("M", 6, "MACRES").
dico("M", 6, "MACROS").
dico("M", 6, "MACULA").
dico("M", 6, "MACULE").
dico("M", 6, "MADAME").
dico("M", 6, "MADERE").
dico("M", 6, "MADONE").
dico("M", 6, "MADRAS").
dico("M", 6, "MADREE").
dico("M", 6, "MADRES").
dico("M", 6, "MAERLS").
dico("M", 6, "MAFFIA").
dico("M", 6, "MAFFLU").
dico("M", 6, "MAFIAS").
dico("M", 6, "MAGANA").
dico("M", 6, "MAGANE").
dico("M", 6, "MAGIES").
dico("M", 6, "MAGMAS").
dico("M", 6, "MAGNAI").
dico("M", 6, "MAGNAN").
dico("M", 6, "MAGNAS").
dico("M", 6, "MAGNAT").
dico("M", 6, "MAGNEE").
dico("M", 6, "MAGNER").
dico("M", 6, "MAGNES").
dico("M", 6, "MAGNET").
dico("M", 6, "MAGNEZ").
dico("M", 6, "MAGNUM").
dico("M", 6, "MAGOTS").
dico("M", 6, "MAGRET").
dico("M", 6, "MAGYAR").
dico("M", 6, "MAHDIS").
dico("M", 6, "MAHOUS").
dico("M", 6, "MAICHE").
dico("M", 6, "MAIEUR").
dico("M", 6, "MAIGRE").
dico("M", 6, "MAIGRI").
dico("M", 6, "MAILLA").
dico("M", 6, "MAILLE").
dico("M", 6, "MAINTE").
dico("M", 6, "MAINTS").
dico("M", 6, "MAIRES").
dico("M", 6, "MAIRIE").
dico("M", 6, "MAISON").
dico("M", 6, "MAITRE").
dico("M", 6, "MAJEUR").
dico("M", 6, "MAJORA").
dico("M", 6, "MAJORE").
dico("M", 6, "MAJORS").
dico("M", 6, "MAKILA").
dico("M", 6, "MALADE").
dico("M", 6, "MALAGA").
dico("M", 6, "MALAIS").
dico("M", 6, "MALARD").
dico("M", 6, "MALART").
dico("M", 6, "MALAXA").
dico("M", 6, "MALAXE").
dico("M", 6, "MALBAR").
dico("M", 6, "MALBEC").
dico("M", 6, "MALEKI").
dico("M", 6, "MALGRE").
dico("M", 6, "MALICE").
dico("M", 6, "MALIEN").
dico("M", 6, "MALINE").
dico("M", 6, "MALINS").
dico("M", 6, "MALLES").
dico("M", 6, "MALOYA").
dico("M", 6, "MALTAI").
dico("M", 6, "MALTAS").
dico("M", 6, "MALTAT").
dico("M", 6, "MALTEE").
dico("M", 6, "MALTER").
dico("M", 6, "MALTES").
dico("M", 6, "MALTEZ").
dico("M", 6, "MALURE").
dico("M", 6, "MAMANS").
dico("M", 6, "MAMBAS").
dico("M", 6, "MAMBOS").
dico("M", 6, "MAMELU").
dico("M", 6, "MAMIES").
dico("M", 6, "MAMMAS").
dico("M", 6, "MAMMYS").
dico("M", 6, "MANADE").
dico("M", 6, "MANAGE").
dico("M", 6, "MANANT").
dico("M", 6, "MANATS").
dico("M", 6, "MANCHE").
dico("M", 6, "MANCIE").
dico("M", 6, "MANDAI").
dico("M", 6, "MANDAS").
dico("M", 6, "MANDAT").
dico("M", 6, "MANDEE").
dico("M", 6, "MANDER").
dico("M", 6, "MANDES").
dico("M", 6, "MANDEZ").
dico("M", 6, "MANEGE").
dico("M", 6, "MANGAS").
dico("M", 6, "MANGEA").
dico("M", 6, "MANGEE").
dico("M", 6, "MANGER").
dico("M", 6, "MANGES").
dico("M", 6, "MANGEZ").
dico("M", 6, "MANGLE").
dico("M", 6, "MANGUE").
dico("M", 6, "MANIAI").
dico("M", 6, "MANIAS").
dico("M", 6, "MANIAT").
dico("M", 6, "MANIEE").
dico("M", 6, "MANIER").
dico("M", 6, "MANIES").
dico("M", 6, "MANIEZ").
dico("M", 6, "MANIFS").
dico("M", 6, "MANIOC").
dico("M", 6, "MANIPE").
dico("M", 6, "MANIPS").
dico("M", 6, "MANNES").
dico("M", 6, "MANOIR").
dico("M", 6, "MANONS").
dico("M", 6, "MANOUS").
dico("M", 6, "MANQUA").
dico("M", 6, "MANQUE").
dico("M", 6, "MANSES").
dico("M", 6, "MANTAS").
dico("M", 6, "MANTES").
dico("M", 6, "MANTRA").
dico("M", 6, "MANUEL").
dico("M", 6, "MAORIE").
dico("M", 6, "MAORIS").
dico("M", 6, "MAPPAI").
dico("M", 6, "MAPPAS").
dico("M", 6, "MAPPAT").
dico("M", 6, "MAPPEE").
dico("M", 6, "MAPPER").
dico("M", 6, "MAPPES").
dico("M", 6, "MAPPEZ").
dico("M", 6, "MAQUAI").
dico("M", 6, "MAQUAS").
dico("M", 6, "MAQUAT").
dico("M", 6, "MAQUEE").
dico("M", 6, "MAQUER").
dico("M", 6, "MAQUES").
dico("M", 6, "MAQUEZ").
dico("M", 6, "MAQUIS").
dico("M", 6, "MARACA").
dico("M", 6, "MARAIS").
dico("M", 6, "MARANS").
dico("M", 6, "MARAUD").
dico("M", 6, "MARBRA").
dico("M", 6, "MARBRE").
dico("M", 6, "MARCEL").
dico("M", 6, "MARCHA").
dico("M", 6, "MARCHE").
dico("M", 6, "MARDIS").
dico("M", 6, "MAREES").
dico("M", 6, "MARFIL").
dico("M", 6, "MARGAY").
dico("M", 6, "MARGEA").
dico("M", 6, "MARGEE").
dico("M", 6, "MARGER").
dico("M", 6, "MARGES").
dico("M", 6, "MARGEZ").
dico("M", 6, "MARGIS").
dico("M", 6, "MARGOT").
dico("M", 6, "MARIAI").
dico("M", 6, "MARIAL").
dico("M", 6, "MARIAS").
dico("M", 6, "MARIAT").
dico("M", 6, "MARIEE").
dico("M", 6, "MARIER").
dico("M", 6, "MARIES").
dico("M", 6, "MARIEZ").
dico("M", 6, "MARINA").
dico("M", 6, "MARINE").
dico("M", 6, "MARINS").
dico("M", 6, "MARIOL").
dico("M", 6, "MARKKA").
dico("M", 6, "MARLES").
dico("M", 6, "MARLIN").
dico("M", 6, "MARLIS").
dico("M", 6, "MARLOU").
dico("M", 6, "MARMOT").
dico("M", 6, "MARNAI").
dico("M", 6, "MARNAS").
dico("M", 6, "MARNAT").
dico("M", 6, "MARNEE").
dico("M", 6, "MARNER").
dico("M", 6, "MARNES").
dico("M", 6, "MARNEZ").
dico("M", 6, "MARQUA").
dico("M", 6, "MARQUE").
dico("M", 6, "MARRAI").
dico("M", 6, "MARRAS").
dico("M", 6, "MARRAT").
dico("M", 6, "MARREE").
dico("M", 6, "MARRER").
dico("M", 6, "MARRES").
dico("M", 6, "MARREZ").
dico("M", 6, "MARRIE").
dico("M", 6, "MARRIS").
dico("M", 6, "MARRON").
dico("M", 6, "MARTEL").
dico("M", 6, "MARTES").
dico("M", 6, "MARTIN").
dico("M", 6, "MARTRE").
dico("M", 6, "MARTYR").
dico("M", 6, "MASAIS").
dico("M", 6, "MASERS").
dico("M", 6, "MASQUA").
dico("M", 6, "MASQUE").
dico("M", 6, "MASSAI").
dico("M", 6, "MASSAS").
dico("M", 6, "MASSAT").
dico("M", 6, "MASSEE").
dico("M", 6, "MASSER").
dico("M", 6, "MASSES").
dico("M", 6, "MASSEZ").
dico("M", 6, "MASSIF").
dico("M", 6, "MASSUE").
dico("M", 6, "MASTIC").
dico("M", 6, "MASTOC").
dico("M", 6, "MASURE").
dico("M", 6, "MATAFS").
dico("M", 6, "MATAGE").
dico("M", 6, "MATAIS").
dico("M", 6, "MATAIT").
dico("M", 6, "MATANT").
dico("M", 6, "MATCHA").
dico("M", 6, "MATCHE").
dico("M", 6, "MATCHS").
dico("M", 6, "MATEES").
dico("M", 6, "MATENT").
dico("M", 6, "MATERA").
dico("M", 6, "MATERS").
dico("M", 6, "MATETE").
dico("M", 6, "MATEUR").
dico("M", 6, "MATIES").
dico("M", 6, "MATIEZ").
dico("M", 6, "MATIFS").
dico("M", 6, "MATINA").
dico("M", 6, "MATINE").
dico("M", 6, "MATINS").
dico("M", 6, "MATIRA").
dico("M", 6, "MATITE").
dico("M", 6, "MATOIR").
dico("M", 6, "MATOIS").
dico("M", 6, "MATONS").
dico("M", 6, "MATOUS").
dico("M", 6, "MATRAS").
dico("M", 6, "MATTES").
dico("M", 6, "MATURA").
dico("M", 6, "MATURE").
dico("M", 6, "MAUDIS").
dico("M", 6, "MAUDIT").
dico("M", 6, "MAURES").
dico("M", 6, "MAUSER").
dico("M", 6, "MAUVES").
dico("M", 6, "MAUVIS").
dico("M", 6, "MAXIMA").
dico("M", 6, "MAXIME").
dico("M", 6, "MAYDAY").
dico("M", 6, "MAYENS").
dico("M", 6, "MAYEUR").
dico("M", 6, "MAZAIS").
dico("M", 6, "MAZAIT").
dico("M", 6, "MAZAMA").
dico("M", 6, "MAZANT").
dico("M", 6, "MAZEES").
dico("M", 6, "MAZENT").
dico("M", 6, "MAZERA").
dico("M", 6, "MAZIEZ").
dico("M", 6, "MAZONS").
dico("M", 6, "MAZOTS").
dico("M", 6, "MAZOUT").
dico("M", 6, "MECANO").
dico("M", 6, "MECENE").
dico("M", 6, "MECHAI").
dico("M", 6, "MECHAS").
dico("M", 6, "MECHAT").
dico("M", 6, "MECHEE").
dico("M", 6, "MECHER").
dico("M", 6, "MECHES").
dico("M", 6, "MECHEZ").
dico("M", 6, "MECHTA").
dico("M", 6, "MECTON").
dico("M", 6, "MEDIAL").
dico("M", 6, "MEDIAN").
dico("M", 6, "MEDIAS").
dico("M", 6, "MEDIAT").
dico("M", 6, "MEDINA").
dico("M", 6, "MEDIRA").
dico("M", 6, "MEDIRE").
dico("M", 6, "MEDISE").
dico("M", 6, "MEDITA").
dico("M", 6, "MEDITE").
dico("M", 6, "MEDIUM").
dico("M", 6, "MEDIUS").
dico("M", 6, "MEDLEY").
dico("M", 6, "MEDOCS").
dico("M", 6, "MEDUSA").
dico("M", 6, "MEDUSE").
dico("M", 6, "MEFAIT").
dico("M", 6, "MEFIAI").
dico("M", 6, "MEFIAS").
dico("M", 6, "MEFIAT").
dico("M", 6, "MEFIEE").
dico("M", 6, "MEFIER").
dico("M", 6, "MEFIES").
dico("M", 6, "MEFIEZ").
dico("M", 6, "MEGALO").
dico("M", 6, "MEGERE").
dico("M", 6, "MEGIES").
dico("M", 6, "MEGIRA").
dico("M", 6, "MEGOHM").
dico("M", 6, "MEGOTA").
dico("M", 6, "MEGOTE").
dico("M", 6, "MEGOTS").
dico("M", 6, "MEHARA").
dico("M", 6, "MEHARI").
dico("M", 6, "MEIJIS").
dico("M", 6, "MEIOSE").
dico("M", 6, "MEJUGE").
dico("M", 6, "MELAIS").
dico("M", 6, "MELAIT").
dico("M", 6, "MELANT").
dico("M", 6, "MELEES").
dico("M", 6, "MELENA").
dico("M", 6, "MELENT").
dico("M", 6, "MELERA").
dico("M", 6, "MELEZE").
dico("M", 6, "MELIAS").
dico("M", 6, "MELIEZ").
dico("M", 6, "MELLAH").
dico("M", 6, "MELOES").
dico("M", 6, "MELONS").
dico("M", 6, "MEMBRE").
dico("M", 6, "MEMBRU").
dico("M", 6, "MEMERA").
dico("M", 6, "MEMERE").
dico("M", 6, "MENACA").
dico("M", 6, "MENACE").
dico("M", 6, "MENADE").
dico("M", 6, "MENAGE").
dico("M", 6, "MENAIS").
dico("M", 6, "MENAIT").
dico("M", 6, "MENANT").
dico("M", 6, "MENDIA").
dico("M", 6, "MENDIE").
dico("M", 6, "MENEAU").
dico("M", 6, "MENEES").
dico("M", 6, "MENENT").
dico("M", 6, "MENERA").
dico("M", 6, "MENEUR").
dico("M", 6, "MENHIR").
dico("M", 6, "MENIEZ").
dico("M", 6, "MENINE").
dico("M", 6, "MENINS").
dico("M", 6, "MENONS").
dico("M", 6, "MENORA").
dico("M", 6, "MENSES").
dico("M", 6, "MENSUR").
dico("M", 6, "MENTAL").
dico("M", 6, "MENTES").
dico("M", 6, "MENTEZ").
dico("M", 6, "MENTHE").
dico("M", 6, "MENTIR").
dico("M", 6, "MENTIS").
dico("M", 6, "MENTIT").
dico("M", 6, "MENTON").
dico("M", 6, "MENTOR").
dico("M", 6, "MENUES").
dico("M", 6, "MENUET").
dico("M", 6, "MENURE").
dico("M", 6, "MEPLAT").
dico("M", 6, "MEPRIS").
dico("M", 6, "MEPRIT").
dico("M", 6, "MERCIS").
dico("M", 6, "MERDAI").
dico("M", 6, "MERDAS").
dico("M", 6, "MERDAT").
dico("M", 6, "MERDEE").
dico("M", 6, "MERDER").
dico("M", 6, "MERDES").
dico("M", 6, "MERDEZ").
dico("M", 6, "MEREAU").
dico("M", 6, "MERENS").
dico("M", 6, "MERISE").
dico("M", 6, "MERITA").
dico("M", 6, "MERITE").
dico("M", 6, "MERLAN").
dico("M", 6, "MERLES").
dico("M", 6, "MERLIN").
dico("M", 6, "MERLON").
dico("M", 6, "MERLOT").
dico("M", 6, "MERLUS").
dico("M", 6, "MEROUS").
dico("M", 6, "MERULE").
dico("M", 6, "MESCAL").
dico("M", 6, "MESONS").
dico("M", 6, "MESSER").
dico("M", 6, "MESSES").
dico("M", 6, "MESSIE").
dico("M", 6, "MESSIN").
dico("M", 6, "MESTRE").
dico("M", 6, "MESURA").
dico("M", 6, "MESURE").
dico("M", 6, "MESUSA").
dico("M", 6, "MESUSE").
dico("M", 6, "METAUX").
dico("M", 6, "METEIL").
dico("M", 6, "METEOS").
dico("M", 6, "METIER").
dico("M", 6, "METOPE").
dico("M", 6, "METRAI").
dico("M", 6, "METRAS").
dico("M", 6, "METRAT").
dico("M", 6, "METREE").
dico("M", 6, "METRER").
dico("M", 6, "METRES").
dico("M", 6, "METREZ").
dico("M", 6, "METROS").
dico("M", 6, "METTES").
dico("M", 6, "METTEZ").
dico("M", 6, "METTRA").
dico("M", 6, "METTRE").
dico("M", 6, "MEUBLA").
dico("M", 6, "MEUBLE").
dico("M", 6, "MEUGLA").
dico("M", 6, "MEUGLE").
dico("M", 6, "MEULAI").
dico("M", 6, "MEULAS").
dico("M", 6, "MEULAT").
dico("M", 6, "MEULEE").
dico("M", 6, "MEULER").
dico("M", 6, "MEULES").
dico("M", 6, "MEULEZ").
dico("M", 6, "MEULON").
dico("M", 6, "MEURES").
dico("M", 6, "MEURON").
dico("M", 6, "MEUTES").
dico("M", 6, "MEUVES").
dico("M", 6, "MEVEND").
dico("M", 6, "MEZAIL").
dico("M", 6, "MEZCAL").
dico("M", 6, "MEZZES").
dico("M", 6, "MEZZOS").
dico("M", 6, "MIAOUS").
dico("M", 6, "MIASME").
dico("M", 6, "MIAULA").
dico("M", 6, "MIAULE").
dico("M", 6, "MICACE").
dico("M", 6, "MICHES").
dico("M", 6, "MICMAC").
dico("M", 6, "MICRON").
dico("M", 6, "MICROS").
dico("M", 6, "MIELLE").
dico("M", 6, "MIENNE").
dico("M", 6, "MIETTE").
dico("M", 6, "MIEVRE").
dico("M", 6, "MIGNON").
dico("M", 6, "MIGRAI").
dico("M", 6, "MIGRAS").
dico("M", 6, "MIGRAT").
dico("M", 6, "MIGRER").
dico("M", 6, "MIGRES").
dico("M", 6, "MIGREZ").
dico("M", 6, "MIHRAB").
dico("M", 6, "MIJOTA").
dico("M", 6, "MIJOTE").
dico("M", 6, "MIKADO").
dico("M", 6, "MILADY").
dico("M", 6, "MILANS").
dico("M", 6, "MILERS").
dico("M", 6, "MILICE").
dico("M", 6, "MILIEU").
dico("M", 6, "MILITA").
dico("M", 6, "MILITE").
dico("M", 6, "MILIUM").
dico("M", 6, "MILLAS").
dico("M", 6, "MILLES").
dico("M", 6, "MILLET").
dico("M", 6, "MILORD").
dico("M", 6, "MIMAIS").
dico("M", 6, "MIMAIT").
dico("M", 6, "MIMANT").
dico("M", 6, "MIMEES").
dico("M", 6, "MIMENT").
dico("M", 6, "MIMERA").
dico("M", 6, "MIMIEZ").
dico("M", 6, "MIMINE").
dico("M", 6, "MIMONS").
dico("M", 6, "MIMOSA").
dico("M", 6, "MINAGE").
dico("M", 6, "MINAIS").
dico("M", 6, "MINAIT").
dico("M", 6, "MINANT").
dico("M", 6, "MINBAR").
dico("M", 6, "MINCES").
dico("M", 6, "MINCIE").
dico("M", 6, "MINCIR").
dico("M", 6, "MINCIS").
dico("M", 6, "MINCIT").
dico("M", 6, "MINDEL").
dico("M", 6, "MINEES").
dico("M", 6, "MINENT").
dico("M", 6, "MINERA").
dico("M", 6, "MINETS").
dico("M", 6, "MINEUR").
dico("M", 6, "MINIER").
dico("M", 6, "MINIEZ").
dico("M", 6, "MINIMA").
dico("M", 6, "MINIME").
dico("M", 6, "MINIUM").
dico("M", 6, "MINOEN").
dico("M", 6, "MINOIS").
dico("M", 6, "MINONS").
dico("M", 6, "MINORA").
dico("M", 6, "MINORE").
dico("M", 6, "MINOTS").
dico("M", 6, "MINOUS").
dico("M", 6, "MINQUE").
dico("M", 6, "MINUIT").
dico("M", 6, "MINUTA").
dico("M", 6, "MINUTE").
dico("M", 6, "MIOCHE").
dico("M", 6, "MIRAGE").
dico("M", 6, "MIRAIS").
dico("M", 6, "MIRAIT").
dico("M", 6, "MIRANT").
dico("M", 6, "MIRAUD").
dico("M", 6, "MIREES").
dico("M", 6, "MIRENT").
dico("M", 6, "MIRERA").
dico("M", 6, "MIREUR").
dico("M", 6, "MIRIEZ").
dico("M", 6, "MIROIR").
dico("M", 6, "MIRONS").
dico("M", 6, "MISAIS").
dico("M", 6, "MISAIT").
dico("M", 6, "MISANT").
dico("M", 6, "MISEES").
dico("M", 6, "MISENT").
dico("M", 6, "MISERA").
dico("M", 6, "MISERE").
dico("M", 6, "MISFIT").
dico("M", 6, "MISIEZ").
dico("M", 6, "MISONS").
dico("M", 6, "MISSEL").
dico("M", 6, "MISSES").
dico("M", 6, "MISTER").
dico("M", 6, "MISTON").
dico("M", 6, "MITAGE").
dico("M", 6, "MITAIS").
dico("M", 6, "MITAIT").
dico("M", 6, "MITANS").
dico("M", 6, "MITANT").
dico("M", 6, "MITARD").
dico("M", 6, "MITEES").
dico("M", 6, "MITENT").
dico("M", 6, "MITERA").
dico("M", 6, "MITEUX").
dico("M", 6, "MITIEZ").
dico("M", 6, "MITIGE").
dico("M", 6, "MITONS").
dico("M", 6, "MITOSE").
dico("M", 6, "MITRAL").
dico("M", 6, "MITREE").
dico("M", 6, "MITRES").
dico("M", 6, "MITRON").
dico("M", 6, "MIXAGE").
dico("M", 6, "MIXAIS").
dico("M", 6, "MIXAIT").
dico("M", 6, "MIXANT").
dico("M", 6, "MIXEES").
dico("M", 6, "MIXENT").
dico("M", 6, "MIXERA").
dico("M", 6, "MIXERS").
dico("M", 6, "MIXEUR").
dico("M", 6, "MIXIEZ").
dico("M", 6, "MIXITE").
dico("M", 6, "MIXONS").
dico("M", 6, "MIXTES").
dico("M", 6, "MNEMES").
dico("M", 6, "MOAMBE").
dico("M", 6, "MOBILE").
dico("M", 6, "MOBLOT").
dico("M", 6, "MOCHES").
dico("M", 6, "MODALE").
dico("M", 6, "MODAUX").
dico("M", 6, "MODELA").
dico("M", 6, "MODELE").
dico("M", 6, "MODEMS").
dico("M", 6, "MODERA").
dico("M", 6, "MODERE").
dico("M", 6, "MODULA").
dico("M", 6, "MODULE").
dico("M", 6, "MODULO").
dico("M", 6, "MOELLE").
dico("M", 6, "MOERES").
dico("M", 6, "MOEURS").
dico("M", 6, "MOFFLA").
dico("M", 6, "MOFFLE").
dico("M", 6, "MOFLAI").
dico("M", 6, "MOFLAS").
dico("M", 6, "MOFLAT").
dico("M", 6, "MOFLEE").
dico("M", 6, "MOFLER").
dico("M", 6, "MOFLES").
dico("M", 6, "MOFLEZ").
dico("M", 6, "MOGHOL").
dico("M", 6, "MOGOLE").
dico("M", 6, "MOGOLS").
dico("M", 6, "MOHAIR").
dico("M", 6, "MOHAWK").
dico("M", 6, "MOIENT").
dico("M", 6, "MOIERA").
dico("M", 6, "MOINES").
dico("M", 6, "MOIRAI").
dico("M", 6, "MOIRAS").
dico("M", 6, "MOIRAT").
dico("M", 6, "MOIREE").
dico("M", 6, "MOIRER").
dico("M", 6, "MOIRES").
dico("M", 6, "MOIREZ").
dico("M", 6, "MOISAI").
dico("M", 6, "MOISAS").
dico("M", 6, "MOISAT").
dico("M", 6, "MOISEE").
dico("M", 6, "MOISER").
dico("M", 6, "MOISES").
dico("M", 6, "MOISEZ").
dico("M", 6, "MOISIE").
dico("M", 6, "MOISIR").
dico("M", 6, "MOISIS").
dico("M", 6, "MOISIT").
dico("M", 6, "MOITES").
dico("M", 6, "MOITIE").
dico("M", 6, "MOITIR").
dico("M", 6, "MOITIS").
dico("M", 6, "MOITIT").
dico("M", 6, "MOLARD").
dico("M", 6, "MOLENE").
dico("M", 6, "MOLETA").
dico("M", 6, "MOLETE").
dico("M", 6, "MOLLAH").
dico("M", 6, "MOLLES").
dico("M", 6, "MOLLET").
dico("M", 6, "MOLLIE").
dico("M", 6, "MOLLIR").
dico("M", 6, "MOLLIS").
dico("M", 6, "MOLLIT").
dico("M", 6, "MOLOCH").
dico("M", 6, "MOLURE").
dico("M", 6, "MOMBIN").
dico("M", 6, "MOMENT").
dico("M", 6, "MOMIER").
dico("M", 6, "MOMIES").
dico("M", 6, "MONACO").
dico("M", 6, "MONADE").
dico("M", 6, "MONDAI").
dico("M", 6, "MONDAS").
dico("M", 6, "MONDAT").
dico("M", 6, "MONDEE").
dico("M", 6, "MONDER").
dico("M", 6, "MONDES").
dico("M", 6, "MONDEZ").
dico("M", 6, "MONELS").
dico("M", 6, "MONEME").
dico("M", 6, "MONEPS").
dico("M", 6, "MONERE").
dico("M", 6, "MONGOL").
dico("M", 6, "MONIAL").
dico("M", 6, "MONOIS").
dico("M", 6, "MONOME").
dico("M", 6, "MONTAI").
dico("M", 6, "MONTAS").
dico("M", 6, "MONTAT").
dico("M", 6, "MONTEE").
dico("M", 6, "MONTER").
dico("M", 6, "MONTES").
dico("M", 6, "MONTEZ").
dico("M", 6, "MONTRA").
dico("M", 6, "MONTRE").
dico("M", 6, "MOQUAI").
dico("M", 6, "MOQUAS").
dico("M", 6, "MOQUAT").
dico("M", 6, "MOQUEE").
dico("M", 6, "MOQUER").
dico("M", 6, "MOQUES").
dico("M", 6, "MOQUEZ").
dico("M", 6, "MORALE").
dico("M", 6, "MORAUX").
dico("M", 6, "MORAVE").
dico("M", 6, "MORBUS").
dico("M", 6, "MORCES").
dico("M", 6, "MORDEE").
dico("M", 6, "MORDES").
dico("M", 6, "MORDEZ").
dico("M", 6, "MORDIS").
dico("M", 6, "MORDIT").
dico("M", 6, "MORDRA").
dico("M", 6, "MORDRE").
dico("M", 6, "MORDUE").
dico("M", 6, "MORDUS").
dico("M", 6, "MOREAU").
dico("M", 6, "MORENE").
dico("M", 6, "MORFAL").
dico("M", 6, "MORFIL").
dico("M", 6, "MORFLA").
dico("M", 6, "MORFLE").
dico("M", 6, "MORGON").
dico("M", 6, "MORGUA").
dico("M", 6, "MORGUE").
dico("M", 6, "MORION").
dico("M", 6, "MORIOS").
dico("M", 6, "MORMON").
dico("M", 6, "MORNAY").
dico("M", 6, "MORNEE").
dico("M", 6, "MORNES").
dico("M", 6, "MOROSE").
dico("M", 6, "MORPHO").
dico("M", 6, "MORSES").
dico("M", 6, "MORTEL").
dico("M", 6, "MORTES").
dico("M", 6, "MORUES").
dico("M", 6, "MORULA").
dico("M", 6, "MORVES").
dico("M", 6, "MOSANE").
dico("M", 6, "MOSANS").
dico("M", 6, "MOSHAV").
dico("M", 6, "MOTARD").
dico("M", 6, "MOTELS").
dico("M", 6, "MOTETS").
dico("M", 6, "MOTEUR").
dico("M", 6, "MOTIFS").
dico("M", 6, "MOTILE").
dico("M", 6, "MOTION").
dico("M", 6, "MOTIVA").
dico("M", 6, "MOTIVE").
dico("M", 6, "MOTTAI").
dico("M", 6, "MOTTAS").
dico("M", 6, "MOTTAT").
dico("M", 6, "MOTTEE").
dico("M", 6, "MOTTER").
dico("M", 6, "MOTTES").
dico("M", 6, "MOTTEZ").
dico("M", 6, "MOTTON").
dico("M", 6, "MOUAIS").
dico("M", 6, "MOUCHA").
dico("M", 6, "MOUCHE").
dico("M", 6, "MOUDRA").
dico("M", 6, "MOUDRE").
dico("M", 6, "MOUFLA").
dico("M", 6, "MOUFLE").
dico("M", 6, "MOUFTA").
dico("M", 6, "MOUFTE").
dico("M", 6, "MOUISE").
dico("M", 6, "MOUJIK").
dico("M", 6, "MOULAI").
dico("M", 6, "MOULAS").
dico("M", 6, "MOULAT").
dico("M", 6, "MOULEE").
dico("M", 6, "MOULER").
dico("M", 6, "MOULES").
dico("M", 6, "MOULEZ").
dico("M", 6, "MOULIN").
dico("M", 6, "MOULUE").
dico("M", 6, "MOULUS").
dico("M", 6, "MOULUT").
dico("M", 6, "MOUNDA").
dico("M", 6, "MOUNDS").
dico("M", 6, "MOUREZ").
dico("M", 6, "MOURIR").
dico("M", 6, "MOURON").
dico("M", 6, "MOURRA").
dico("M", 6, "MOURRE").
dico("M", 6, "MOURUS").
dico("M", 6, "MOURUT").
dico("M", 6, "MOUSME").
dico("M", 6, "MOUSSA").
dico("M", 6, "MOUSSE").
dico("M", 6, "MOUSSU").
dico("M", 6, "MOUTON").
dico("M", 6, "MOUVEZ").
dico("M", 6, "MOUVRA").
dico("M", 6, "MOYAIS").
dico("M", 6, "MOYAIT").
dico("M", 6, "MOYANT").
dico("M", 6, "MOYEES").
dico("M", 6, "MOYENS").
dico("M", 6, "MOYEUX").
dico("M", 6, "MOYIEZ").
dico("M", 6, "MOYONS").
dico("M", 6, "MUAMES").
dico("M", 6, "MUANCE").
dico("M", 6, "MUASSE").
dico("M", 6, "MUATES").
dico("M", 6, "MUCHAI").
dico("M", 6, "MUCHAS").
dico("M", 6, "MUCHAT").
dico("M", 6, "MUCHEE").
dico("M", 6, "MUCHER").
dico("M", 6, "MUCHES").
dico("M", 6, "MUCHEZ").
dico("M", 6, "MUCINE").
dico("M", 6, "MUCORS").
dico("M", 6, "MUCRON").
dico("M", 6, "MUDRAS").
dico("M", 6, "MUERAI").
dico("M", 6, "MUERAS").
dico("M", 6, "MUEREZ").
dico("M", 6, "MUESLI").
dico("M", 6, "MUETTE").
dico("M", 6, "MUFFIN").
dico("M", 6, "MUFLES").
dico("M", 6, "MUFTIS").
dico("M", 6, "MUGIES").
dico("M", 6, "MUGIRA").
dico("M", 6, "MUGUET").
dico("M", 6, "MUIONS").
dico("M", 6, "MULARD").
dico("M", 6, "MULETA").
dico("M", 6, "MULETS").
dico("M", 6, "MULLAH").
dico("M", 6, "MULLAS").
dico("M", 6, "MULONS").
dico("M", 6, "MULOTS").
dico("M", 6, "MULUDS").
dico("M", 6, "MUMUSE").
dico("M", 6, "MUNDAS").
dico("M", 6, "MUNGOS").
dico("M", 6, "MUNIES").
dico("M", 6, "MUNIRA").
dico("M", 6, "MUPHTI").
dico("M", 6, "MURAGE").
dico("M", 6, "MURAIE").
dico("M", 6, "MURAIS").
dico("M", 6, "MURAIT").
dico("M", 6, "MURALE").
dico("M", 6, "MURALS").
dico("M", 6, "MURANT").
dico("M", 6, "MURAUX").
dico("M", 6, "MUREES").
dico("M", 6, "MURENE").
dico("M", 6, "MURENT").
dico("M", 6, "MURERA").
dico("M", 6, "MURETS").
dico("M", 6, "MURGER").
dico("M", 6, "MURIDE").
dico("M", 6, "MURIER").
dico("M", 6, "MURIES").
dico("M", 6, "MURIEZ").
dico("M", 6, "MURINE").
dico("M", 6, "MURINS").
dico("M", 6, "MURIRA").
dico("M", 6, "MURMEL").
dico("M", 6, "MURONS").
dico("M", 6, "MURRHE").
dico("M", 6, "MUSAIS").
dico("M", 6, "MUSAIT").
dico("M", 6, "MUSANT").
dico("M", 6, "MUSARD").
dico("M", 6, "MUSCAT").
dico("M", 6, "MUSCLA").
dico("M", 6, "MUSCLE").
dico("M", 6, "MUSEAL").
dico("M", 6, "MUSEAU").
dico("M", 6, "MUSEES").
dico("M", 6, "MUSELA").
dico("M", 6, "MUSELE").
dico("M", 6, "MUSENT").
dico("M", 6, "MUSERA").
dico("M", 6, "MUSEUM").
dico("M", 6, "MUSHER").
dico("M", 6, "MUSIEZ").
dico("M", 6, "MUSLIS").
dico("M", 6, "MUSOIR").
dico("M", 6, "MUSONS").
dico("M", 6, "MUSQUA").
dico("M", 6, "MUSQUE").
dico("M", 6, "MUSSAI").
dico("M", 6, "MUSSAS").
dico("M", 6, "MUSSAT").
dico("M", 6, "MUSSEE").
dico("M", 6, "MUSSER").
dico("M", 6, "MUSSES").
dico("M", 6, "MUSSEZ").
dico("M", 6, "MUSSIF").
dico("M", 6, "MUTAGE").
dico("M", 6, "MUTAIS").
dico("M", 6, "MUTAIT").
dico("M", 6, "MUTANT").
dico("M", 6, "MUTEES").
dico("M", 6, "MUTENT").
dico("M", 6, "MUTERA").
dico("M", 6, "MUTIEZ").
dico("M", 6, "MUTILA").
dico("M", 6, "MUTILE").
dico("M", 6, "MUTINA").
dico("M", 6, "MUTINE").
dico("M", 6, "MUTINS").
dico("M", 6, "MUTITE").
dico("M", 6, "MUTONS").
dico("M", 6, "MUTUEL").
dico("M", 6, "MUTULE").
dico("M", 6, "MYCOSE").
dico("M", 6, "MYGALE").
dico("M", 6, "MYIASE").
dico("M", 6, "MYOMES").
dico("M", 6, "MYOPES").
dico("M", 6, "MYOPIE").
dico("M", 6, "MYOSIS").
dico("M", 6, "MYRICA").
dico("M", 6, "MYRRHE").
dico("M", 6, "MYRTES").
dico("M", 6, "MYTHES").
dico("M", 6, "MYTHOS").
dico("M", 6, "MYXINE").
dico("M", 6, "MYXOME").
