dico("M", 7, "MAATJES").
dico("M", 7, "MABOULE").
dico("M", 7, "MABOULS").
dico("M", 7, "MACABRE").
dico("M", 7, "MACACHE").
dico("M", 7, "MACADAM").
dico("M", 7, "MACAQUE").
dico("M", 7, "MACARON").
dico("M", 7, "MACERAI").
dico("M", 7, "MACERAS").
dico("M", 7, "MACERAT").
dico("M", 7, "MACEREE").
dico("M", 7, "MACERER").
dico("M", 7, "MACERES").
dico("M", 7, "MACEREZ").
dico("M", 7, "MACERON").
dico("M", 7, "MACHAIS").
dico("M", 7, "MACHAIT").
dico("M", 7, "MACHANT").
dico("M", 7, "MACHAON").
dico("M", 7, "MACHEES").
dico("M", 7, "MACHENT").
dico("M", 7, "MACHERA").
dico("M", 7, "MACHEUR").
dico("M", 7, "MACHIEZ").
dico("M", 7, "MACHINA").
dico("M", 7, "MACHINE").
dico("M", 7, "MACHINS").
dico("M", 7, "MACHONS").
dico("M", 7, "MACHURA").
dico("M", 7, "MACHURE").
dico("M", 7, "MACLAGE").
dico("M", 7, "MACLAIS").
dico("M", 7, "MACLAIT").
dico("M", 7, "MACLANT").
dico("M", 7, "MACLEES").
dico("M", 7, "MACLENT").
dico("M", 7, "MACLERA").
dico("M", 7, "MACLIEZ").
dico("M", 7, "MACLONS").
dico("M", 7, "MACONNA").
dico("M", 7, "MACONNE").
dico("M", 7, "MACOUTE").
dico("M", 7, "MACQUAI").
dico("M", 7, "MACQUAS").
dico("M", 7, "MACQUAT").
dico("M", 7, "MACQUEE").
dico("M", 7, "MACQUER").
dico("M", 7, "MACQUES").
dico("M", 7, "MACQUEZ").
dico("M", 7, "MACRAME").
dico("M", 7, "MACULAI").
dico("M", 7, "MACULAS").
dico("M", 7, "MACULAT").
dico("M", 7, "MACULEE").
dico("M", 7, "MACULER").
dico("M", 7, "MACULES").
dico("M", 7, "MACULEZ").
dico("M", 7, "MACUMBA").
dico("M", 7, "MADAMES").
dico("M", 7, "MADERES").
dico("M", 7, "MADIRAN").
dico("M", 7, "MADISON").
dico("M", 7, "MADONES").
dico("M", 7, "MADRASA").
dico("M", 7, "MADREES").
dico("M", 7, "MADRIER").
dico("M", 7, "MADRURE").
dico("M", 7, "MAESTRO").
dico("M", 7, "MAFFIAS").
dico("M", 7, "MAFFLUE").
dico("M", 7, "MAFFLUS").
dico("M", 7, "MAFIEUX").
dico("M", 7, "MAFIOSI").
dico("M", 7, "MAFIOSO").
dico("M", 7, "MAGANAI").
dico("M", 7, "MAGANAS").
dico("M", 7, "MAGANAT").
dico("M", 7, "MAGANEE").
dico("M", 7, "MAGANER").
dico("M", 7, "MAGANES").
dico("M", 7, "MAGANEZ").
dico("M", 7, "MAGASIN").
dico("M", 7, "MAGENTA").
dico("M", 7, "MAGHZEN").
dico("M", 7, "MAGIQUE").
dico("M", 7, "MAGNAIS").
dico("M", 7, "MAGNAIT").
dico("M", 7, "MAGNANS").
dico("M", 7, "MAGNANT").
dico("M", 7, "MAGNATS").
dico("M", 7, "MAGNEES").
dico("M", 7, "MAGNENT").
dico("M", 7, "MAGNERA").
dico("M", 7, "MAGNETO").
dico("M", 7, "MAGNETS").
dico("M", 7, "MAGNIEZ").
dico("M", 7, "MAGNONS").
dico("M", 7, "MAGNUMS").
dico("M", 7, "MAGRETS").
dico("M", 7, "MAGYARE").
dico("M", 7, "MAGYARS").
dico("M", 7, "MAHALEB").
dico("M", 7, "MAHATMA").
dico("M", 7, "MAHONIA").
dico("M", 7, "MAHONNE").
dico("M", 7, "MAICHES").
dico("M", 7, "MAIEURE").
dico("M", 7, "MAIEURS").
dico("M", 7, "MAIGRES").
dico("M", 7, "MAIGRIE").
dico("M", 7, "MAIGRIR").
dico("M", 7, "MAIGRIS").
dico("M", 7, "MAIGRIT").
dico("M", 7, "MAILING").
dico("M", 7, "MAILLAI").
dico("M", 7, "MAILLAS").
dico("M", 7, "MAILLAT").
dico("M", 7, "MAILLEE").
dico("M", 7, "MAILLER").
dico("M", 7, "MAILLES").
dico("M", 7, "MAILLET").
dico("M", 7, "MAILLEZ").
dico("M", 7, "MAILLON").
dico("M", 7, "MAILLOT").
dico("M", 7, "MAINATE").
dico("M", 7, "MAINTES").
dico("M", 7, "MAIORAL").
dico("M", 7, "MAIORAT").
dico("M", 7, "MAIRIES").
dico("M", 7, "MAISONS").
dico("M", 7, "MAITRES").
dico("M", 7, "MAIZENA").
dico("M", 7, "MAJESTE").
dico("M", 7, "MAJEURE").
dico("M", 7, "MAJEURS").
dico("M", 7, "MAJORAI").
dico("M", 7, "MAJORAL").
dico("M", 7, "MAJORAS").
dico("M", 7, "MAJORAT").
dico("M", 7, "MAJOREE").
dico("M", 7, "MAJORER").
dico("M", 7, "MAJORES").
dico("M", 7, "MAJOREZ").
dico("M", 7, "MAKAIRE").
dico("M", 7, "MAKHZEN").
dico("M", 7, "MAKILAS").
dico("M", 7, "MALABAR").
dico("M", 7, "MALACIE").
dico("M", 7, "MALADES").
dico("M", 7, "MALADIE").
dico("M", 7, "MALADIF").
dico("M", 7, "MALAGAS").
dico("M", 7, "MALAIME").
dico("M", 7, "MALAIRE").
dico("M", 7, "MALAISE").
dico("M", 7, "MALARDS").
dico("M", 7, "MALARIA").
dico("M", 7, "MALARTS").
dico("M", 7, "MALAXAI").
dico("M", 7, "MALAXAS").
dico("M", 7, "MALAXAT").
dico("M", 7, "MALAXEE").
dico("M", 7, "MALAXER").
dico("M", 7, "MALAXES").
dico("M", 7, "MALAXEZ").
dico("M", 7, "MALBARS").
dico("M", 7, "MALBATI").
dico("M", 7, "MALBECS").
dico("M", 7, "MALEKIS").
dico("M", 7, "MALFAME").
dico("M", 7, "MALFRAT").
dico("M", 7, "MALHEUR").
dico("M", 7, "MALICES").
dico("M", 7, "MALIENS").
dico("M", 7, "MALIGNE").
dico("M", 7, "MALINES").
dico("M", 7, "MALINKE").
dico("M", 7, "MALIQUE").
dico("M", 7, "MALMENA").
dico("M", 7, "MALMENE").
dico("M", 7, "MALOTRU").
dico("M", 7, "MALOUIN").
dico("M", 7, "MALOYAS").
dico("M", 7, "MALPOLI").
dico("M", 7, "MALSAIN").
dico("M", 7, "MALTAGE").
dico("M", 7, "MALTAIS").
dico("M", 7, "MALTAIT").
dico("M", 7, "MALTANT").
dico("M", 7, "MALTASE").
dico("M", 7, "MALTEES").
dico("M", 7, "MALTENT").
dico("M", 7, "MALTERA").
dico("M", 7, "MALTEUR").
dico("M", 7, "MALTIEZ").
dico("M", 7, "MALTONS").
dico("M", 7, "MALTOSE").
dico("M", 7, "MALTOTE").
dico("M", 7, "MALURES").
dico("M", 7, "MALVALE").
dico("M", 7, "MALVENU").
dico("M", 7, "MAMELLE").
dico("M", 7, "MAMELON").
dico("M", 7, "MAMELUE").
dico("M", 7, "MAMELUK").
dico("M", 7, "MAMELUS").
dico("M", 7, "MAMMITE").
dico("M", 7, "MAMOURS").
dico("M", 7, "MANADES").
dico("M", 7, "MANAGEA").
dico("M", 7, "MANAGEE").
dico("M", 7, "MANAGER").
dico("M", 7, "MANAGES").
dico("M", 7, "MANAGEZ").
dico("M", 7, "MANANTS").
dico("M", 7, "MANCEAU").
dico("M", 7, "MANCHES").
dico("M", 7, "MANCHON").
dico("M", 7, "MANCHOT").
dico("M", 7, "MANCHOU").
dico("M", 7, "MANCIES").
dico("M", 7, "MANDAIS").
dico("M", 7, "MANDAIT").
dico("M", 7, "MANDALA").
dico("M", 7, "MANDALE").
dico("M", 7, "MANDANT").
dico("M", 7, "MANDATA").
dico("M", 7, "MANDATE").
dico("M", 7, "MANDATS").
dico("M", 7, "MANDEEN").
dico("M", 7, "MANDEES").
dico("M", 7, "MANDENT").
dico("M", 7, "MANDERA").
dico("M", 7, "MANDIEZ").
dico("M", 7, "MANDOLE").
dico("M", 7, "MANDONS").
dico("M", 7, "MANDORE").
dico("M", 7, "MANDRIN").
dico("M", 7, "MANEGEA").
dico("M", 7, "MANEGEE").
dico("M", 7, "MANEGER").
dico("M", 7, "MANEGES").
dico("M", 7, "MANEGEZ").
dico("M", 7, "MANETON").
dico("M", 7, "MANETTE").
dico("M", 7, "MANGEAI").
dico("M", 7, "MANGEAS").
dico("M", 7, "MANGEAT").
dico("M", 7, "MANGEES").
dico("M", 7, "MANGENT").
dico("M", 7, "MANGERA").
dico("M", 7, "MANGERS").
dico("M", 7, "MANGEUR").
dico("M", 7, "MANGIEZ").
dico("M", 7, "MANGLES").
dico("M", 7, "MANGUES").
dico("M", 7, "MANIAGE").
dico("M", 7, "MANIAIS").
dico("M", 7, "MANIAIT").
dico("M", 7, "MANIANT").
dico("M", 7, "MANICLE").
dico("M", 7, "MANIEES").
dico("M", 7, "MANIENT").
dico("M", 7, "MANIERA").
dico("M", 7, "MANIERE").
dico("M", 7, "MANIEUR").
dico("M", 7, "MANIIEZ").
dico("M", 7, "MANILLA").
dico("M", 7, "MANILLE").
dico("M", 7, "MANIOCS").
dico("M", 7, "MANIONS").
dico("M", 7, "MANIPES").
dico("M", 7, "MANIQUE").
dico("M", 7, "MANITOU").
dico("M", 7, "MANNITE").
dico("M", 7, "MANNOIS").
dico("M", 7, "MANNOSE").
dico("M", 7, "MANOIRS").
dico("M", 7, "MANOQUA").
dico("M", 7, "MANOQUE").
dico("M", 7, "MANQUAI").
dico("M", 7, "MANQUAS").
dico("M", 7, "MANQUAT").
dico("M", 7, "MANQUEE").
dico("M", 7, "MANQUER").
dico("M", 7, "MANQUES").
dico("M", 7, "MANQUEZ").
dico("M", 7, "MANSION").
dico("M", 7, "MANTEAU").
dico("M", 7, "MANTELE").
dico("M", 7, "MANTRAS").
dico("M", 7, "MANUELS").
dico("M", 7, "MAOISME").
dico("M", 7, "MAOISTE").
dico("M", 7, "MAORIES").
dico("M", 7, "MAOUSSE").
dico("M", 7, "MAPPAGE").
dico("M", 7, "MAPPAIS").
dico("M", 7, "MAPPAIT").
dico("M", 7, "MAPPANT").
dico("M", 7, "MAPPEES").
dico("M", 7, "MAPPENT").
dico("M", 7, "MAPPERA").
dico("M", 7, "MAPPIEZ").
dico("M", 7, "MAPPONS").
dico("M", 7, "MAQUAIS").
dico("M", 7, "MAQUAIT").
dico("M", 7, "MAQUANT").
dico("M", 7, "MAQUEES").
dico("M", 7, "MAQUENT").
dico("M", 7, "MAQUERA").
dico("M", 7, "MAQUIEZ").
dico("M", 7, "MAQUONS").
dico("M", 7, "MARACAS").
dico("M", 7, "MARANTA").
dico("M", 7, "MARANTE").
dico("M", 7, "MARASME").
dico("M", 7, "MARATHE").
dico("M", 7, "MARATHI").
dico("M", 7, "MARATRE").
dico("M", 7, "MARAUDA").
dico("M", 7, "MARAUDE").
dico("M", 7, "MARAUDS").
dico("M", 7, "MARBRAI").
dico("M", 7, "MARBRAS").
dico("M", 7, "MARBRAT").
dico("M", 7, "MARBREE").
dico("M", 7, "MARBRER").
dico("M", 7, "MARBRES").
dico("M", 7, "MARBREZ").
dico("M", 7, "MARCELS").
dico("M", 7, "MARCHAI").
dico("M", 7, "MARCHAS").
dico("M", 7, "MARCHAT").
dico("M", 7, "MARCHER").
dico("M", 7, "MARCHES").
dico("M", 7, "MARCHEZ").
dico("M", 7, "MARCONI").
dico("M", 7, "MARELLE").
dico("M", 7, "MAREMME").
dico("M", 7, "MARENGO").
dico("M", 7, "MARFILS").
dico("M", 7, "MARGAUX").
dico("M", 7, "MARGAYS").
dico("M", 7, "MARGEAI").
dico("M", 7, "MARGEAS").
dico("M", 7, "MARGEAT").
dico("M", 7, "MARGEES").
dico("M", 7, "MARGENT").
dico("M", 7, "MARGERA").
dico("M", 7, "MARGEUR").
dico("M", 7, "MARGIEZ").
dico("M", 7, "MARGINA").
dico("M", 7, "MARGINE").
dico("M", 7, "MARGOTA").
dico("M", 7, "MARGOTE").
dico("M", 7, "MARGOTS").
dico("M", 7, "MARIAGE").
dico("M", 7, "MARIAIS").
dico("M", 7, "MARIAIT").
dico("M", 7, "MARIALE").
dico("M", 7, "MARIALS").
dico("M", 7, "MARIANT").
dico("M", 7, "MARIAUX").
dico("M", 7, "MARIEES").
dico("M", 7, "MARIENT").
dico("M", 7, "MARIERA").
dico("M", 7, "MARIEUR").
dico("M", 7, "MARIGOT").
dico("M", 7, "MARIIEZ").
dico("M", 7, "MARIMBA").
dico("M", 7, "MARINAI").
dico("M", 7, "MARINAS").
dico("M", 7, "MARINAT").
dico("M", 7, "MARINEE").
dico("M", 7, "MARINER").
dico("M", 7, "MARINES").
dico("M", 7, "MARINEZ").
dico("M", 7, "MARIOLE").
dico("M", 7, "MARIOLS").
dico("M", 7, "MARIONS").
dico("M", 7, "MARISTE").
dico("M", 7, "MARITAL").
dico("M", 7, "MARKKAA").
dico("M", 7, "MARKKAS").
dico("M", 7, "MARLINS").
dico("M", 7, "MARLOUS").
dico("M", 7, "MARMITA").
dico("M", 7, "MARMITE").
dico("M", 7, "MARMOTS").
dico("M", 7, "MARNAGE").
dico("M", 7, "MARNAIS").
dico("M", 7, "MARNAIT").
dico("M", 7, "MARNANT").
dico("M", 7, "MARNEES").
dico("M", 7, "MARNENT").
dico("M", 7, "MARNERA").
dico("M", 7, "MARNEUR").
dico("M", 7, "MARNEUX").
dico("M", 7, "MARNIEZ").
dico("M", 7, "MARNONS").
dico("M", 7, "MARONNA").
dico("M", 7, "MARONNE").
dico("M", 7, "MAROTTE").
dico("M", 7, "MAROUTE").
dico("M", 7, "MARQUAI").
dico("M", 7, "MARQUAS").
dico("M", 7, "MARQUAT").
dico("M", 7, "MARQUEE").
dico("M", 7, "MARQUER").
dico("M", 7, "MARQUES").
dico("M", 7, "MARQUEZ").
dico("M", 7, "MARQUIS").
dico("M", 7, "MARRAIS").
dico("M", 7, "MARRAIT").
dico("M", 7, "MARRANE").
dico("M", 7, "MARRANT").
dico("M", 7, "MARREES").
dico("M", 7, "MARRENT").
dico("M", 7, "MARRERA").
dico("M", 7, "MARRIES").
dico("M", 7, "MARRIEZ").
dico("M", 7, "MARRONS").
dico("M", 7, "MARRUBE").
dico("M", 7, "MARSALA").
dico("M", 7, "MARSEAU").
dico("M", 7, "MARSHAL").
dico("M", 7, "MARTEAU").
dico("M", 7, "MARTELA").
dico("M", 7, "MARTELE").
dico("M", 7, "MARTIAL").
dico("M", 7, "MARTIEN").
dico("M", 7, "MARTINI").
dico("M", 7, "MARTINS").
dico("M", 7, "MARTRES").
dico("M", 7, "MARTYRE").
dico("M", 7, "MARTYRS").
dico("M", 7, "MARXIEN").
dico("M", 7, "MARXISA").
dico("M", 7, "MARXISE").
dico("M", 7, "MASCARA").
dico("M", 7, "MASQUAI").
dico("M", 7, "MASQUAS").
dico("M", 7, "MASQUAT").
dico("M", 7, "MASQUEE").
dico("M", 7, "MASQUER").
dico("M", 7, "MASQUES").
dico("M", 7, "MASQUEZ").
dico("M", 7, "MASSAGE").
dico("M", 7, "MASSAIS").
dico("M", 7, "MASSAIT").
dico("M", 7, "MASSANT").
dico("M", 7, "MASSEES").
dico("M", 7, "MASSENT").
dico("M", 7, "MASSERA").
dico("M", 7, "MASSEUR").
dico("M", 7, "MASSIER").
dico("M", 7, "MASSIEZ").
dico("M", 7, "MASSIFS").
dico("M", 7, "MASSIVE").
dico("M", 7, "MASSONS").
dico("M", 7, "MASSORE").
dico("M", 7, "MASSUES").
dico("M", 7, "MASTABA").
dico("M", 7, "MASTARD").
dico("M", 7, "MASTERE").
dico("M", 7, "MASTERS").
dico("M", 7, "MASTICS").
dico("M", 7, "MASTIFF").
dico("M", 7, "MASTITE").
dico("M", 7, "MASTOCS").
dico("M", 7, "MASTOSE").
dico("M", 7, "MASURES").
dico("M", 7, "MATADOR").
dico("M", 7, "MATAGES").
dico("M", 7, "MATAMES").
dico("M", 7, "MATASSE").
dico("M", 7, "MATATES").
dico("M", 7, "MATCHAI").
dico("M", 7, "MATCHAS").
dico("M", 7, "MATCHAT").
dico("M", 7, "MATCHEE").
dico("M", 7, "MATCHER").
dico("M", 7, "MATCHES").
dico("M", 7, "MATCHEZ").
dico("M", 7, "MATELAS").
dico("M", 7, "MATELOT").
dico("M", 7, "MATERAI").
dico("M", 7, "MATERAS").
dico("M", 7, "MATEREZ").
dico("M", 7, "MATERNA").
dico("M", 7, "MATERNE").
dico("M", 7, "MATETES").
dico("M", 7, "MATEURS").
dico("M", 7, "MATEUSE").
dico("M", 7, "MATHEUX").
dico("M", 7, "MATIERE").
dico("M", 7, "MATIFIA").
dico("M", 7, "MATIFIE").
dico("M", 7, "MATIMES").
dico("M", 7, "MATINAI").
dico("M", 7, "MATINAL").
dico("M", 7, "MATINAS").
dico("M", 7, "MATINAT").
dico("M", 7, "MATINEE").
dico("M", 7, "MATINER").
dico("M", 7, "MATINES").
dico("M", 7, "MATINEZ").
dico("M", 7, "MATIONS").
dico("M", 7, "MATIRAI").
dico("M", 7, "MATIRAS").
dico("M", 7, "MATIREZ").
dico("M", 7, "MATISSE").
dico("M", 7, "MATITES").
dico("M", 7, "MATOIRS").
dico("M", 7, "MATOISE").
dico("M", 7, "MATONNE").
dico("M", 7, "MATRICA").
dico("M", 7, "MATRICE").
dico("M", 7, "MATRONE").
dico("M", 7, "MATURAI").
dico("M", 7, "MATURAS").
dico("M", 7, "MATURAT").
dico("M", 7, "MATUREE").
dico("M", 7, "MATURER").
dico("M", 7, "MATURES").
dico("M", 7, "MATUREZ").
dico("M", 7, "MAUDIRA").
dico("M", 7, "MAUDIRE").
dico("M", 7, "MAUDITE").
dico("M", 7, "MAUDITS").
dico("M", 7, "MAUGREA").
dico("M", 7, "MAUGREE").
dico("M", 7, "MAUSERS").
dico("M", 7, "MAUVAIS").
dico("M", 7, "MAXILLE").
dico("M", 7, "MAXIMAL").
dico("M", 7, "MAXIMES").
dico("M", 7, "MAXIMUM").
dico("M", 7, "MAXWELL").
dico("M", 7, "MAYEURE").
dico("M", 7, "MAYEURS").
dico("M", 7, "MAYORAL").
dico("M", 7, "MAYORAT").
dico("M", 7, "MAZAMAS").
dico("M", 7, "MAZAMES").
dico("M", 7, "MAZASSE").
dico("M", 7, "MAZATES").
dico("M", 7, "MAZDEEN").
dico("M", 7, "MAZEAGE").
dico("M", 7, "MAZERAI").
dico("M", 7, "MAZERAS").
dico("M", 7, "MAZEREZ").
dico("M", 7, "MAZETTE").
dico("M", 7, "MAZIONS").
dico("M", 7, "MAZOUTA").
dico("M", 7, "MAZOUTE").
dico("M", 7, "MAZOUTS").
dico("M", 7, "MAZURKA").
dico("M", 7, "MBALAKH").
dico("M", 7, "MEANDRE").
dico("M", 7, "MECANOS").
dico("M", 7, "MECCANO").
dico("M", 7, "MECENAT").
dico("M", 7, "MECENES").
dico("M", 7, "MECHAGE").
dico("M", 7, "MECHAIS").
dico("M", 7, "MECHAIT").
dico("M", 7, "MECHANT").
dico("M", 7, "MECHEES").
dico("M", 7, "MECHENT").
dico("M", 7, "MECHERA").
dico("M", 7, "MECHEUX").
dico("M", 7, "MECHIEZ").
dico("M", 7, "MECHONS").
dico("M", 7, "MECHOUI").
dico("M", 7, "MECHTAS").
dico("M", 7, "MECONNU").
dico("M", 7, "MECTONS").
dico("M", 7, "MEDECIN").
dico("M", 7, "MEDERSA").
dico("M", 7, "MEDIALE").
dico("M", 7, "MEDIANE").
dico("M", 7, "MEDIANS").
dico("M", 7, "MEDIATE").
dico("M", 7, "MEDIATS").
dico("M", 7, "MEDIAUX").
dico("M", 7, "MEDICAL").
dico("M", 7, "MEDICAT").
dico("M", 7, "MEDIMES").
dico("M", 7, "MEDIMNE").
dico("M", 7, "MEDINAS").
dico("M", 7, "MEDIQUE").
dico("M", 7, "MEDIRAI").
dico("M", 7, "MEDIRAS").
dico("M", 7, "MEDIREZ").
dico("M", 7, "MEDISES").
dico("M", 7, "MEDISEZ").
dico("M", 7, "MEDISSE").
dico("M", 7, "MEDITAI").
dico("M", 7, "MEDITAS").
dico("M", 7, "MEDITAT").
dico("M", 7, "MEDITEE").
dico("M", 7, "MEDITER").
dico("M", 7, "MEDITES").
dico("M", 7, "MEDITEZ").
dico("M", 7, "MEDIUMS").
dico("M", 7, "MEDLEYS").
dico("M", 7, "MEDULLA").
dico("M", 7, "MEDUSAI").
dico("M", 7, "MEDUSAS").
dico("M", 7, "MEDUSAT").
dico("M", 7, "MEDUSEE").
dico("M", 7, "MEDUSER").
dico("M", 7, "MEDUSES").
dico("M", 7, "MEDUSEZ").
dico("M", 7, "MEETING").
dico("M", 7, "MEFAITS").
dico("M", 7, "MEFIAIS").
dico("M", 7, "MEFIAIT").
dico("M", 7, "MEFIANT").
dico("M", 7, "MEFIEES").
dico("M", 7, "MEFIENT").
dico("M", 7, "MEFIERA").
dico("M", 7, "MEFIIEZ").
dico("M", 7, "MEFIONS").
dico("M", 7, "MEFORME").
dico("M", 7, "MEGABIT").
dico("M", 7, "MEGALOS").
dico("M", 7, "MEGARDE").
dico("M", 7, "MEGARON").
dico("M", 7, "MEGERES").
dico("M", 7, "MEGIMES").
dico("M", 7, "MEGIRAI").
dico("M", 7, "MEGIRAS").
dico("M", 7, "MEGIREZ").
dico("M", 7, "MEGISSA").
dico("M", 7, "MEGISSE").
dico("M", 7, "MEGITES").
dico("M", 7, "MEGOHMS").
dico("M", 7, "MEGOTAI").
dico("M", 7, "MEGOTAS").
dico("M", 7, "MEGOTAT").
dico("M", 7, "MEGOTEE").
dico("M", 7, "MEGOTER").
dico("M", 7, "MEGOTES").
dico("M", 7, "MEGOTEZ").
dico("M", 7, "MEHALLA").
dico("M", 7, "MEHAREE").
dico("M", 7, "MEHARIS").
dico("M", 7, "MEIOSES").
dico("M", 7, "MEISTRE").
dico("M", 7, "MEJUGEA").
dico("M", 7, "MEJUGEE").
dico("M", 7, "MEJUGER").
dico("M", 7, "MEJUGES").
dico("M", 7, "MEJUGEZ").
dico("M", 7, "MELAENA").
dico("M", 7, "MELAMES").
dico("M", 7, "MELANGE").
dico("M", 7, "MELANTE").
dico("M", 7, "MELANTS").
dico("M", 7, "MELASSE").
dico("M", 7, "MELATES").
dico("M", 7, "MELDOIS").
dico("M", 7, "MELENAS").
dico("M", 7, "MELERAI").
dico("M", 7, "MELERAS").
dico("M", 7, "MELEREZ").
dico("M", 7, "MELEZES").
dico("M", 7, "MELILOT").
dico("M", 7, "MELIONS").
dico("M", 7, "MELIQUE").
dico("M", 7, "MELISSE").
dico("M", 7, "MELITTE").
dico("M", 7, "MELKITE").
dico("M", 7, "MELLAHS").
dico("M", 7, "MELLITE").
dico("M", 7, "MELODIE").
dico("M", 7, "MELOIDE").
dico("M", 7, "MELONNE").
dico("M", 7, "MELOPEE").
dico("M", 7, "MEMBREE").
dico("M", 7, "MEMBRES").
dico("M", 7, "MEMBRON").
dico("M", 7, "MEMBRUE").
dico("M", 7, "MEMBRUS").
dico("M", 7, "MEMENTO").
dico("M", 7, "MEMERAI").
dico("M", 7, "MEMERAS").
dico("M", 7, "MEMERAT").
dico("M", 7, "MEMERER").
dico("M", 7, "MEMERES").
dico("M", 7, "MEMEREZ").
dico("M", 7, "MEMOIRE").
dico("M", 7, "MENACAI").
dico("M", 7, "MENACAS").
dico("M", 7, "MENACAT").
dico("M", 7, "MENACEE").
dico("M", 7, "MENACER").
dico("M", 7, "MENACES").
dico("M", 7, "MENACEZ").
dico("M", 7, "MENADES").
dico("M", 7, "MENAGEA").
dico("M", 7, "MENAGEE").
dico("M", 7, "MENAGER").
dico("M", 7, "MENAGES").
dico("M", 7, "MENAGEZ").
dico("M", 7, "MENAMES").
dico("M", 7, "MENANTE").
dico("M", 7, "MENANTS").
dico("M", 7, "MENASSE").
dico("M", 7, "MENATES").
dico("M", 7, "MENDIAI").
dico("M", 7, "MENDIAS").
dico("M", 7, "MENDIAT").
dico("M", 7, "MENDIEE").
dico("M", 7, "MENDIER").
dico("M", 7, "MENDIES").
dico("M", 7, "MENDIEZ").
dico("M", 7, "MENDOIS").
dico("M", 7, "MENDOLE").
dico("M", 7, "MENEAUX").
dico("M", 7, "MENERAI").
dico("M", 7, "MENERAS").
dico("M", 7, "MENEREZ").
dico("M", 7, "MENEURS").
dico("M", 7, "MENEUSE").
dico("M", 7, "MENHIRS").
dico("M", 7, "MENIANE").
dico("M", 7, "MENINES").
dico("M", 7, "MENINGE").
dico("M", 7, "MENIONS").
dico("M", 7, "MENORAS").
dico("M", 7, "MENOTTA").
dico("M", 7, "MENOTTE").
dico("M", 7, "MENSUEL").
dico("M", 7, "MENSURS").
dico("M", 7, "MENTAIS").
dico("M", 7, "MENTAIT").
dico("M", 7, "MENTALE").
dico("M", 7, "MENTANT").
dico("M", 7, "MENTAUX").
dico("M", 7, "MENTENT").
dico("M", 7, "MENTEUR").
dico("M", 7, "MENTHES").
dico("M", 7, "MENTHOL").
dico("M", 7, "MENTIEZ").
dico("M", 7, "MENTION").
dico("M", 7, "MENTIRA").
dico("M", 7, "MENTONS").
dico("M", 7, "MENTORS").
dico("M", 7, "MENUETS").
dico("M", 7, "MENUISA").
dico("M", 7, "MENUISE").
dico("M", 7, "MENURES").
dico("M", 7, "MEPLATE").
dico("M", 7, "MEPLATS").
dico("M", 7, "MEPREND").
dico("M", 7, "MEPRISA").
dico("M", 7, "MEPRISE").
dico("M", 7, "MERANTI").
dico("M", 7, "MERCIER").
dico("M", 7, "MERCURE").
dico("M", 7, "MERDAIS").
dico("M", 7, "MERDAIT").
dico("M", 7, "MERDANT").
dico("M", 7, "MERDEES").
dico("M", 7, "MERDENT").
dico("M", 7, "MERDERA").
dico("M", 7, "MERDEUX").
dico("M", 7, "MERDIER").
dico("M", 7, "MERDIEZ").
dico("M", 7, "MERDOIE").
dico("M", 7, "MERDONS").
dico("M", 7, "MERDOYA").
dico("M", 7, "MERDOYE").
dico("M", 7, "MEREAUX").
dico("M", 7, "MERGUEZ").
dico("M", 7, "MERGULE").
dico("M", 7, "MERINOS").
dico("M", 7, "MERISES").
dico("M", 7, "MERISME").
dico("M", 7, "MERITAI").
dico("M", 7, "MERITAS").
dico("M", 7, "MERITAT").
dico("M", 7, "MERITEE").
dico("M", 7, "MERITER").
dico("M", 7, "MERITES").
dico("M", 7, "MERITEZ").
dico("M", 7, "MERLANS").
dico("M", 7, "MERLEAU").
dico("M", 7, "MERLINS").
dico("M", 7, "MERLONS").
dico("M", 7, "MERLOTS").
dico("M", 7, "MERRAIN").
dico("M", 7, "MERULES").
dico("M", 7, "MESAISE").
dico("M", 7, "MESANGE").
dico("M", 7, "MESCALS").
dico("M", 7, "MESCLUN").
dico("M", 7, "MESQUIN").
dico("M", 7, "MESSAGE").
dico("M", 7, "MESSERS").
dico("M", 7, "MESSIED").
dico("M", 7, "MESSIEE").
dico("M", 7, "MESSIER").
dico("M", 7, "MESSIES").
dico("M", 7, "MESSINE").
dico("M", 7, "MESSINS").
dico("M", 7, "MESSIRE").
dico("M", 7, "MESTRES").
dico("M", 7, "MESURAI").
dico("M", 7, "MESURAS").
dico("M", 7, "MESURAT").
dico("M", 7, "MESUREE").
dico("M", 7, "MESURER").
dico("M", 7, "MESURES").
dico("M", 7, "MESUREZ").
dico("M", 7, "MESUSAI").
dico("M", 7, "MESUSAS").
dico("M", 7, "MESUSAT").
dico("M", 7, "MESUSER").
dico("M", 7, "MESUSES").
dico("M", 7, "MESUSEZ").
dico("M", 7, "METALLO").
dico("M", 7, "METAYER").
dico("M", 7, "METEILS").
dico("M", 7, "METEORE").
dico("M", 7, "METEQUE").
dico("M", 7, "METHANE").
dico("M", 7, "METHODE").
dico("M", 7, "METHYLE").
dico("M", 7, "METICAL").
dico("M", 7, "METIERS").
dico("M", 7, "METISSA").
dico("M", 7, "METISSE").
dico("M", 7, "METOPES").
dico("M", 7, "METRAGE").
dico("M", 7, "METRAIS").
dico("M", 7, "METRAIT").
dico("M", 7, "METRANT").
dico("M", 7, "METREES").
dico("M", 7, "METRENT").
dico("M", 7, "METRERA").
dico("M", 7, "METREUR").
dico("M", 7, "METRIEZ").
dico("M", 7, "METRITE").
dico("M", 7, "METRONS").
dico("M", 7, "METTAIS").
dico("M", 7, "METTAIT").
dico("M", 7, "METTANT").
dico("M", 7, "METTENT").
dico("M", 7, "METTEUR").
dico("M", 7, "METTIEZ").
dico("M", 7, "METTONS").
dico("M", 7, "METTRAI").
dico("M", 7, "METTRAS").
dico("M", 7, "METTREZ").
dico("M", 7, "MEUBLAI").
dico("M", 7, "MEUBLAS").
dico("M", 7, "MEUBLAT").
dico("M", 7, "MEUBLEE").
dico("M", 7, "MEUBLER").
dico("M", 7, "MEUBLES").
dico("M", 7, "MEUBLEZ").
dico("M", 7, "MEUGLAI").
dico("M", 7, "MEUGLAS").
dico("M", 7, "MEUGLAT").
dico("M", 7, "MEUGLER").
dico("M", 7, "MEUGLES").
dico("M", 7, "MEUGLEZ").
dico("M", 7, "MEULAGE").
dico("M", 7, "MEULAIS").
dico("M", 7, "MEULAIT").
dico("M", 7, "MEULANT").
dico("M", 7, "MEULARD").
dico("M", 7, "MEULEES").
dico("M", 7, "MEULENT").
dico("M", 7, "MEULERA").
dico("M", 7, "MEULIER").
dico("M", 7, "MEULIEZ").
dico("M", 7, "MEULONS").
dico("M", 7, "MEUNIER").
dico("M", 7, "MEURENT").
dico("M", 7, "MEURONS").
dico("M", 7, "MEURTRE").
dico("M", 7, "MEURTRI").
dico("M", 7, "MEUSIEN").
dico("M", 7, "MEUVENT").
dico("M", 7, "MEVENDE").
dico("M", 7, "MEVENDS").
dico("M", 7, "MEVENDU").
dico("M", 7, "MEVENTE").
dico("M", 7, "MEZAILS").
dico("M", 7, "MEZCALS").
dico("M", 7, "MEZIGUE").
dico("M", 7, "MIASMES").
dico("M", 7, "MIAULAI").
dico("M", 7, "MIAULAS").
dico("M", 7, "MIAULAT").
dico("M", 7, "MIAULER").
dico("M", 7, "MIAULES").
dico("M", 7, "MIAULEZ").
dico("M", 7, "MICACEE").
dico("M", 7, "MICACES").
dico("M", 7, "MICELLE").
dico("M", 7, "MICMACS").
dico("M", 7, "MICROBE").
dico("M", 7, "MICROHM").
dico("M", 7, "MICRONS").
dico("M", 7, "MICTION").
dico("M", 7, "MIDRASH").
dico("M", 7, "MIDSHIP").
dico("M", 7, "MIELLAT").
dico("M", 7, "MIELLEE").
dico("M", 7, "MIELLES").
dico("M", 7, "MIENNES").
dico("M", 7, "MIETTES").
dico("M", 7, "MIEVRES").
dico("M", 7, "MIGNARD").
dico("M", 7, "MIGNONS").
dico("M", 7, "MIGNOTA").
dico("M", 7, "MIGNOTE").
dico("M", 7, "MIGRAIS").
dico("M", 7, "MIGRAIT").
dico("M", 7, "MIGRANT").
dico("M", 7, "MIGRENT").
dico("M", 7, "MIGRERA").
dico("M", 7, "MIGRIEZ").
dico("M", 7, "MIGRONS").
dico("M", 7, "MIHRABS").
dico("M", 7, "MIJOTAI").
dico("M", 7, "MIJOTAS").
dico("M", 7, "MIJOTAT").
dico("M", 7, "MIJOTEE").
dico("M", 7, "MIJOTER").
dico("M", 7, "MIJOTES").
dico("M", 7, "MIJOTEZ").
dico("M", 7, "MIKADOS").
dico("M", 7, "MILADYS").
dico("M", 7, "MILDIOU").
dico("M", 7, "MILICES").
dico("M", 7, "MILIEUX").
dico("M", 7, "MILITAI").
dico("M", 7, "MILITAS").
dico("M", 7, "MILITAT").
dico("M", 7, "MILITER").
dico("M", 7, "MILITES").
dico("M", 7, "MILITEZ").
dico("M", 7, "MILIUMS").
dico("M", 7, "MILLAGE").
dico("M", 7, "MILLETS").
dico("M", 7, "MILLIER").
dico("M", 7, "MILLIME").
dico("M", 7, "MILLION").
dico("M", 7, "MILONGA").
dico("M", 7, "MILORDS").
dico("M", 7, "MILOUIN").
dico("M", 7, "MIMAMES").
dico("M", 7, "MIMASSE").
dico("M", 7, "MIMATES").
dico("M", 7, "MIMERAI").
dico("M", 7, "MIMERAS").
dico("M", 7, "MIMEREZ").
dico("M", 7, "MIMINES").
dico("M", 7, "MIMIONS").
dico("M", 7, "MIMIQUE").
dico("M", 7, "MIMOSAS").
dico("M", 7, "MIMOSEE").
dico("M", 7, "MINABLE").
dico("M", 7, "MINAGES").
dico("M", 7, "MINAMES").
dico("M", 7, "MINARET").
dico("M", 7, "MINASSE").
dico("M", 7, "MINATES").
dico("M", 7, "MINAUDA").
dico("M", 7, "MINAUDE").
dico("M", 7, "MINBARS").
dico("M", 7, "MINCEUR").
dico("M", 7, "MINCIES").
dico("M", 7, "MINCIRA").
dico("M", 7, "MINDELS").
dico("M", 7, "MINERAI").
dico("M", 7, "MINERAL").
dico("M", 7, "MINERAS").
dico("M", 7, "MINEREZ").
dico("M", 7, "MINERVE").
dico("M", 7, "MINETTE").
dico("M", 7, "MINEURE").
dico("M", 7, "MINEURS").
dico("M", 7, "MINEUSE").
dico("M", 7, "MINIBAR").
dico("M", 7, "MINIBUS").
dico("M", 7, "MINICAR").
dico("M", 7, "MINIERE").
dico("M", 7, "MINIERS").
dico("M", 7, "MINIMAL").
dico("M", 7, "MINIMES").
dico("M", 7, "MINIMEX").
dico("M", 7, "MINIMUM").
dico("M", 7, "MINIONS").
dico("M", 7, "MINITEL").
dico("M", 7, "MINIUMS").
dico("M", 7, "MINOENS").
dico("M", 7, "MINORAI").
dico("M", 7, "MINORAS").
dico("M", 7, "MINORAT").
dico("M", 7, "MINOREE").
dico("M", 7, "MINORER").
dico("M", 7, "MINORES").
dico("M", 7, "MINOREZ").
dico("M", 7, "MINOUNE").
dico("M", 7, "MINQUES").
dico("M", 7, "MINUITS").
dico("M", 7, "MINUTAI").
dico("M", 7, "MINUTAS").
dico("M", 7, "MINUTAT").
dico("M", 7, "MINUTEE").
dico("M", 7, "MINUTER").
dico("M", 7, "MINUTES").
dico("M", 7, "MINUTEZ").
dico("M", 7, "MINUTIE").
dico("M", 7, "MIOCENE").
dico("M", 7, "MIOCHES").
dico("M", 7, "MIRACLE").
dico("M", 7, "MIRADOR").
dico("M", 7, "MIRAGES").
dico("M", 7, "MIRAMES").
dico("M", 7, "MIRASSE").
dico("M", 7, "MIRATES").
dico("M", 7, "MIRAUDE").
dico("M", 7, "MIRAUDS").
dico("M", 7, "MIRBANE").
dico("M", 7, "MIRERAI").
dico("M", 7, "MIRERAS").
dico("M", 7, "MIREREZ").
dico("M", 7, "MIRETTE").
dico("M", 7, "MIREURS").
dico("M", 7, "MIREUSE").
dico("M", 7, "MIRIONS").
dico("M", 7, "MIROIRS").
dico("M", 7, "MIROITA").
dico("M", 7, "MIROITE").
dico("M", 7, "MIROTON").
dico("M", 7, "MISAINE").
dico("M", 7, "MISAMES").
dico("M", 7, "MISASSE").
dico("M", 7, "MISATES").
dico("M", 7, "MISERAI").
dico("M", 7, "MISERAS").
dico("M", 7, "MISERES").
dico("M", 7, "MISEREZ").
dico("M", 7, "MISFITS").
dico("M", 7, "MISIONS").
dico("M", 7, "MISSELS").
dico("M", 7, "MISSENT").
dico("M", 7, "MISSIEZ").
dico("M", 7, "MISSILE").
dico("M", 7, "MISSION").
dico("M", 7, "MISSIVE").
dico("M", 7, "MISTERS").
dico("M", 7, "MISTONS").
dico("M", 7, "MISTRAL").
dico("M", 7, "MITAGES").
dico("M", 7, "MITAINE").
dico("M", 7, "MITAMES").
dico("M", 7, "MITARDS").
dico("M", 7, "MITASSE").
dico("M", 7, "MITATES").
dico("M", 7, "MITERAI").
dico("M", 7, "MITERAS").
dico("M", 7, "MITEREZ").
dico("M", 7, "MITEUSE").
dico("M", 7, "MITIGEA").
dico("M", 7, "MITIGEE").
dico("M", 7, "MITIGER").
dico("M", 7, "MITIGES").
dico("M", 7, "MITIGEZ").
dico("M", 7, "MITIONS").
dico("M", 7, "MITONNA").
dico("M", 7, "MITONNE").
dico("M", 7, "MITOSES").
dico("M", 7, "MITOYEN").
dico("M", 7, "MITRALE").
dico("M", 7, "MITRAUX").
dico("M", 7, "MITREES").
dico("M", 7, "MITRONS").
dico("M", 7, "MIXAGES").
dico("M", 7, "MIXAMES").
dico("M", 7, "MIXASSE").
dico("M", 7, "MIXATES").
dico("M", 7, "MIXERAI").
dico("M", 7, "MIXERAS").
dico("M", 7, "MIXEREZ").
dico("M", 7, "MIXEURS").
dico("M", 7, "MIXIONS").
dico("M", 7, "MIXITES").
dico("M", 7, "MIXTION").
dico("M", 7, "MIXTURE").
dico("M", 7, "MOABITE").
dico("M", 7, "MOAMBES").
dico("M", 7, "MOBILES").
dico("M", 7, "MOBLOTS").
dico("M", 7, "MOCHARD").
dico("M", 7, "MOCHETE").
dico("M", 7, "MODALES").
dico("M", 7, "MODELAI").
dico("M", 7, "MODELAS").
dico("M", 7, "MODELAT").
dico("M", 7, "MODELEE").
dico("M", 7, "MODELER").
dico("M", 7, "MODELES").
dico("M", 7, "MODELEZ").
dico("M", 7, "MODERAI").
dico("M", 7, "MODERAS").
dico("M", 7, "MODERAT").
dico("M", 7, "MODEREE").
dico("M", 7, "MODERER").
dico("M", 7, "MODERES").
dico("M", 7, "MODEREZ").
dico("M", 7, "MODERNE").
dico("M", 7, "MODESTE").
dico("M", 7, "MODIFIA").
dico("M", 7, "MODIFIE").
dico("M", 7, "MODIQUE").
dico("M", 7, "MODISTE").
dico("M", 7, "MODULAI").
dico("M", 7, "MODULAS").
dico("M", 7, "MODULAT").
dico("M", 7, "MODULEE").
dico("M", 7, "MODULER").
dico("M", 7, "MODULES").
dico("M", 7, "MODULEZ").
dico("M", 7, "MODULOR").
dico("M", 7, "MOELLES").
dico("M", 7, "MOELLON").
dico("M", 7, "MOFETTE").
dico("M", 7, "MOFFLAI").
dico("M", 7, "MOFFLAS").
dico("M", 7, "MOFFLAT").
dico("M", 7, "MOFFLEE").
dico("M", 7, "MOFFLER").
dico("M", 7, "MOFFLES").
dico("M", 7, "MOFFLEZ").
dico("M", 7, "MOFLAIS").
dico("M", 7, "MOFLAIT").
dico("M", 7, "MOFLANT").
dico("M", 7, "MOFLEES").
dico("M", 7, "MOFLENT").
dico("M", 7, "MOFLERA").
dico("M", 7, "MOFLIEZ").
dico("M", 7, "MOFLONS").
dico("M", 7, "MOGETTE").
dico("M", 7, "MOGHOLE").
dico("M", 7, "MOGHOLS").
dico("M", 7, "MOGOLES").
dico("M", 7, "MOHAIRS").
dico("M", 7, "MOHAWKS").
dico("M", 7, "MOHICAN").
dico("M", 7, "MOIERAI").
dico("M", 7, "MOIERAS").
dico("M", 7, "MOIEREZ").
dico("M", 7, "MOIGNON").
dico("M", 7, "MOINDRE").
dico("M", 7, "MOINEAU").
dico("M", 7, "MOIRAGE").
dico("M", 7, "MOIRAIS").
dico("M", 7, "MOIRAIT").
dico("M", 7, "MOIRANT").
dico("M", 7, "MOIREES").
dico("M", 7, "MOIRENT").
dico("M", 7, "MOIRERA").
dico("M", 7, "MOIREUR").
dico("M", 7, "MOIRIEZ").
dico("M", 7, "MOIRONS").
dico("M", 7, "MOIRURE").
dico("M", 7, "MOISAGE").
dico("M", 7, "MOISAIS").
dico("M", 7, "MOISAIT").
dico("M", 7, "MOISANT").
dico("M", 7, "MOISEES").
dico("M", 7, "MOISENT").
dico("M", 7, "MOISERA").
dico("M", 7, "MOISIES").
dico("M", 7, "MOISIEZ").
dico("M", 7, "MOISIRA").
dico("M", 7, "MOISONS").
dico("M", 7, "MOISSAC").
dico("M", 7, "MOISSON").
dico("M", 7, "MOITEUR").
dico("M", 7, "MOITIES").
dico("M", 7, "MOITIRA").
dico("M", 7, "MOJETTE").
dico("M", 7, "MOLAIRE").
dico("M", 7, "MOLARDA").
dico("M", 7, "MOLARDE").
dico("M", 7, "MOLARDS").
dico("M", 7, "MOLASSE").
dico("M", 7, "MOLDAVE").
dico("M", 7, "MOLENES").
dico("M", 7, "MOLESTA").
dico("M", 7, "MOLESTE").
dico("M", 7, "MOLETAI").
dico("M", 7, "MOLETAS").
dico("M", 7, "MOLETAT").
dico("M", 7, "MOLETEE").
dico("M", 7, "MOLETER").
dico("M", 7, "MOLETES").
dico("M", 7, "MOLETEZ").
dico("M", 7, "MOLETTE").
dico("M", 7, "MOLIERE").
dico("M", 7, "MOLLAHS").
dico("M", 7, "MOLLARD").
dico("M", 7, "MOLLETS").
dico("M", 7, "MOLLIES").
dico("M", 7, "MOLLIRA").
dico("M", 7, "MOLOCHS").
dico("M", 7, "MOLOSSE").
dico("M", 7, "MOLURES").
dico("M", 7, "MOMBINS").
dico("M", 7, "MOMENTS").
dico("M", 7, "MOMERIE").
dico("M", 7, "MOMIERE").
dico("M", 7, "MOMIERS").
dico("M", 7, "MOMIFIA").
dico("M", 7, "MOMIFIE").
dico("M", 7, "MONACAL").
dico("M", 7, "MONACOS").
dico("M", 7, "MONADES").
dico("M", 7, "MONARDE").
dico("M", 7, "MONCEAU").
dico("M", 7, "MONDAIN").
dico("M", 7, "MONDAIS").
dico("M", 7, "MONDAIT").
dico("M", 7, "MONDANT").
dico("M", 7, "MONDEES").
dico("M", 7, "MONDENT").
dico("M", 7, "MONDERA").
dico("M", 7, "MONDIAL").
dico("M", 7, "MONDIEZ").
dico("M", 7, "MONDONS").
dico("M", 7, "MONEMES").
dico("M", 7, "MONERES").
dico("M", 7, "MONGOLE").
dico("M", 7, "MONGOLS").
dico("M", 7, "MONIALE").
dico("M", 7, "MONIAUX").
dico("M", 7, "MONILIA").
dico("M", 7, "MONISME").
dico("M", 7, "MONISTE").
dico("M", 7, "MONITOR").
dico("M", 7, "MONNAIE").
dico("M", 7, "MONNAYA").
dico("M", 7, "MONNAYE").
dico("M", 7, "MONOCLE").
dico("M", 7, "MONODIE").
dico("M", 7, "MONOIDE").
dico("M", 7, "MONOMES").
dico("M", 7, "MONOSKI").
dico("M", 7, "MONOSOC").
dico("M", 7, "MONSTRE").
dico("M", 7, "MONTAGE").
dico("M", 7, "MONTAIS").
dico("M", 7, "MONTAIT").
dico("M", 7, "MONTANT").
dico("M", 7, "MONTEES").
dico("M", 7, "MONTENT").
dico("M", 7, "MONTERA").
dico("M", 7, "MONTEUR").
dico("M", 7, "MONTIEN").
dico("M", 7, "MONTIEZ").
dico("M", 7, "MONTOIR").
dico("M", 7, "MONTOIS").
dico("M", 7, "MONTONS").
dico("M", 7, "MONTRAI").
dico("M", 7, "MONTRAS").
dico("M", 7, "MONTRAT").
dico("M", 7, "MONTREE").
dico("M", 7, "MONTRER").
dico("M", 7, "MONTRES").
dico("M", 7, "MONTREZ").
dico("M", 7, "MONTURE").
dico("M", 7, "MOQUAIS").
dico("M", 7, "MOQUAIT").
dico("M", 7, "MOQUANT").
dico("M", 7, "MOQUEES").
dico("M", 7, "MOQUENT").
dico("M", 7, "MOQUERA").
dico("M", 7, "MOQUEUR").
dico("M", 7, "MOQUIEZ").
dico("M", 7, "MOQUONS").
dico("M", 7, "MORACEE").
dico("M", 7, "MORAINE").
dico("M", 7, "MORALES").
dico("M", 7, "MORASSE").
dico("M", 7, "MORAVES").
dico("M", 7, "MORBIDE").
dico("M", 7, "MORBIER").
dico("M", 7, "MORBLEU").
dico("M", 7, "MORCEAU").
dico("M", 7, "MORCELA").
dico("M", 7, "MORCELE").
dico("M", 7, "MORDAIS").
dico("M", 7, "MORDAIT").
dico("M", 7, "MORDANT").
dico("M", 7, "MORDEES").
dico("M", 7, "MORDENT").
dico("M", 7, "MORDEUR").
dico("M", 7, "MORDIEU").
dico("M", 7, "MORDIEZ").
dico("M", 7, "MORDONS").
dico("M", 7, "MORDORA").
dico("M", 7, "MORDORE").
dico("M", 7, "MORDRAI").
dico("M", 7, "MORDRAS").
dico("M", 7, "MORDREZ").
dico("M", 7, "MORDUES").
dico("M", 7, "MOREAUX").
dico("M", 7, "MORELLE").
dico("M", 7, "MORENES").
dico("M", 7, "MORFALA").
dico("M", 7, "MORFALE").
dico("M", 7, "MORFALS").
dico("M", 7, "MORFILA").
dico("M", 7, "MORFILE").
dico("M", 7, "MORFILS").
dico("M", 7, "MORFLAI").
dico("M", 7, "MORFLAS").
dico("M", 7, "MORFLAT").
dico("M", 7, "MORFLEE").
dico("M", 7, "MORFLER").
dico("M", 7, "MORFLES").
dico("M", 7, "MORFLEZ").
dico("M", 7, "MORFOND").
dico("M", 7, "MORGONS").
dico("M", 7, "MORGUAI").
dico("M", 7, "MORGUAS").
dico("M", 7, "MORGUAT").
dico("M", 7, "MORGUEE").
dico("M", 7, "MORGUER").
dico("M", 7, "MORGUES").
dico("M", 7, "MORGUEZ").
dico("M", 7, "MORILLE").
dico("M", 7, "MORINGA").
dico("M", 7, "MORIONS").
dico("M", 7, "MORMONE").
dico("M", 7, "MORMONS").
dico("M", 7, "MORNAYS").
dico("M", 7, "MORNEES").
dico("M", 7, "MOROSES").
dico("M", 7, "MORPHOS").
dico("M", 7, "MORPION").
dico("M", 7, "MORSURE").
dico("M", 7, "MORTEAU").
dico("M", 7, "MORTELS").
dico("M", 7, "MORTIER").
dico("M", 7, "MORULAS").
dico("M", 7, "MORVEUX").
dico("M", 7, "MOSANES").
dico("M", 7, "MOSELLE").
dico("M", 7, "MOSETTE").
dico("M", 7, "MOSHAVS").
dico("M", 7, "MOSQUEE").
dico("M", 7, "MOTARDE").
dico("M", 7, "MOTARDS").
dico("M", 7, "MOTELLE").
dico("M", 7, "MOTEURS").
dico("M", 7, "MOTILES").
dico("M", 7, "MOTIONS").
dico("M", 7, "MOTIVAI").
dico("M", 7, "MOTIVAS").
dico("M", 7, "MOTIVAT").
dico("M", 7, "MOTIVEE").
dico("M", 7, "MOTIVER").
dico("M", 7, "MOTIVES").
dico("M", 7, "MOTIVEZ").
dico("M", 7, "MOTOSKI").
dico("M", 7, "MOTRICE").
dico("M", 7, "MOTTAIS").
dico("M", 7, "MOTTAIT").
dico("M", 7, "MOTTANT").
dico("M", 7, "MOTTEES").
dico("M", 7, "MOTTENT").
dico("M", 7, "MOTTERA").
dico("M", 7, "MOTTEUX").
dico("M", 7, "MOTTIEZ").
dico("M", 7, "MOTTONS").
dico("M", 7, "MOUCHAI").
dico("M", 7, "MOUCHAS").
dico("M", 7, "MOUCHAT").
dico("M", 7, "MOUCHEE").
dico("M", 7, "MOUCHER").
dico("M", 7, "MOUCHES").
dico("M", 7, "MOUCHET").
dico("M", 7, "MOUCHEZ").
dico("M", 7, "MOUDRAI").
dico("M", 7, "MOUDRAS").
dico("M", 7, "MOUDREZ").
dico("M", 7, "MOUETTE").
dico("M", 7, "MOUFETA").
dico("M", 7, "MOUFETE").
dico("M", 7, "MOUFLAI").
dico("M", 7, "MOUFLAS").
dico("M", 7, "MOUFLAT").
dico("M", 7, "MOUFLEE").
dico("M", 7, "MOUFLER").
dico("M", 7, "MOUFLES").
dico("M", 7, "MOUFLET").
dico("M", 7, "MOUFLEZ").
dico("M", 7, "MOUFLON").
dico("M", 7, "MOUFTAI").
dico("M", 7, "MOUFTAS").
dico("M", 7, "MOUFTAT").
dico("M", 7, "MOUFTER").
dico("M", 7, "MOUFTES").
dico("M", 7, "MOUFTEZ").
dico("M", 7, "MOUILLA").
dico("M", 7, "MOUILLE").
dico("M", 7, "MOUISES").
dico("M", 7, "MOUJIKS").
dico("M", 7, "MOUKERE").
dico("M", 7, "MOULAGE").
dico("M", 7, "MOULAIS").
dico("M", 7, "MOULAIT").
dico("M", 7, "MOULANT").
dico("M", 7, "MOULEES").
dico("M", 7, "MOULENT").
dico("M", 7, "MOULERA").
dico("M", 7, "MOULEUR").
dico("M", 7, "MOULIEZ").
dico("M", 7, "MOULINA").
dico("M", 7, "MOULINE").
dico("M", 7, "MOULINS").
dico("M", 7, "MOULONS").
dico("M", 7, "MOULOUD").
dico("M", 7, "MOULTES").
dico("M", 7, "MOULUES").
dico("M", 7, "MOULURA").
dico("M", 7, "MOULURE").
dico("M", 7, "MOUNDAS").
dico("M", 7, "MOURAIS").
dico("M", 7, "MOURAIT").
dico("M", 7, "MOURANT").
dico("M", 7, "MOURIEZ").
dico("M", 7, "MOUROIR").
dico("M", 7, "MOURONS").
dico("M", 7, "MOURRAI").
dico("M", 7, "MOURRAS").
dico("M", 7, "MOURRES").
dico("M", 7, "MOURREZ").
dico("M", 7, "MOUSMES").
dico("M", 7, "MOUSSAI").
dico("M", 7, "MOUSSAS").
dico("M", 7, "MOUSSAT").
dico("M", 7, "MOUSSEE").
dico("M", 7, "MOUSSER").
dico("M", 7, "MOUSSES").
dico("M", 7, "MOUSSEZ").
dico("M", 7, "MOUSSON").
dico("M", 7, "MOUSSOT").
dico("M", 7, "MOUSSUE").
dico("M", 7, "MOUSSUS").
dico("M", 7, "MOUTARD").
dico("M", 7, "MOUTIER").
dico("M", 7, "MOUTONS").
dico("M", 7, "MOUTURE").
dico("M", 7, "MOUVAIS").
dico("M", 7, "MOUVAIT").
dico("M", 7, "MOUVANT").
dico("M", 7, "MOUVIEZ").
dico("M", 7, "MOUVOIR").
dico("M", 7, "MOUVONS").
dico("M", 7, "MOUVRAI").
dico("M", 7, "MOUVRAS").
dico("M", 7, "MOUVREZ").
dico("M", 7, "MOVIOLA").
dico("M", 7, "MOYAMES").
dico("M", 7, "MOYASSE").
dico("M", 7, "MOYATES").
dico("M", 7, "MOYENNA").
dico("M", 7, "MOYENNE").
dico("M", 7, "MOYETTE").
dico("M", 7, "MOYIONS").
dico("M", 7, "MOZETTE").
dico("M", 7, "MUAIENT").
dico("M", 7, "MUANCES").
dico("M", 7, "MUASSES").
dico("M", 7, "MUCHAIS").
dico("M", 7, "MUCHAIT").
dico("M", 7, "MUCHANT").
dico("M", 7, "MUCHEES").
dico("M", 7, "MUCHENT").
dico("M", 7, "MUCHERA").
dico("M", 7, "MUCHIEZ").
dico("M", 7, "MUCHONS").
dico("M", 7, "MUCINES").
dico("M", 7, "MUCRONS").
dico("M", 7, "MUDEJAR").
dico("M", 7, "MUERAIS").
dico("M", 7, "MUERAIT").
dico("M", 7, "MUERENT").
dico("M", 7, "MUERIEZ").
dico("M", 7, "MUERONS").
dico("M", 7, "MUERONT").
dico("M", 7, "MUESLIS").
dico("M", 7, "MUETTES").
dico("M", 7, "MUEZZIN").
dico("M", 7, "MUFFINS").
dico("M", 7, "MUFLIER").
dico("M", 7, "MUGIMES").
dico("M", 7, "MUGIRAI").
dico("M", 7, "MUGIRAS").
dico("M", 7, "MUGIREZ").
dico("M", 7, "MUGISSE").
dico("M", 7, "MUGITES").
dico("M", 7, "MUGUETS").
dico("M", 7, "MULARDE").
dico("M", 7, "MULARDS").
dico("M", 7, "MULASSE").
dico("M", 7, "MULATRE").
dico("M", 7, "MULETAS").
dico("M", 7, "MULETTE").
dico("M", 7, "MULLAHS").
dico("M", 7, "MULSION").
dico("M", 7, "MUNIMES").
dico("M", 7, "MUNIRAI").
dico("M", 7, "MUNIRAS").
dico("M", 7, "MUNIREZ").
dico("M", 7, "MUNISSE").
dico("M", 7, "MUNITES").
dico("M", 7, "MUNSTER").
dico("M", 7, "MUNTJAC").
dico("M", 7, "MUPHTIS").
dico("M", 7, "MUQUEUX").
dico("M", 7, "MURAGES").
dico("M", 7, "MURAIES").
dico("M", 7, "MURALES").
dico("M", 7, "MURAMES").
dico("M", 7, "MURASSE").
dico("M", 7, "MURATES").
dico("M", 7, "MURENES").
dico("M", 7, "MURERAI").
dico("M", 7, "MURERAS").
dico("M", 7, "MUREREZ").
dico("M", 7, "MURETIN").
dico("M", 7, "MURETTE").
dico("M", 7, "MURGERS").
dico("M", 7, "MURIATE").
dico("M", 7, "MURIDES").
dico("M", 7, "MURIERS").
dico("M", 7, "MURIMES").
dico("M", 7, "MURINES").
dico("M", 7, "MURIONS").
dico("M", 7, "MURIRAI").
dico("M", 7, "MURIRAS").
dico("M", 7, "MURIREZ").
dico("M", 7, "MURISSE").
dico("M", 7, "MURITES").
dico("M", 7, "MURMELS").
dico("M", 7, "MURMURA").
dico("M", 7, "MURMURE").
dico("M", 7, "MURRHES").
dico("M", 7, "MURRHIN").
dico("M", 7, "MUSACEE").
dico("M", 7, "MUSAMES").
dico("M", 7, "MUSARDA").
dico("M", 7, "MUSARDE").
dico("M", 7, "MUSARDS").
dico("M", 7, "MUSASSE").
dico("M", 7, "MUSATES").
dico("M", 7, "MUSCADE").
dico("M", 7, "MUSCARI").
dico("M", 7, "MUSCATE").
dico("M", 7, "MUSCATS").
dico("M", 7, "MUSCIDE").
dico("M", 7, "MUSCLAI").
dico("M", 7, "MUSCLAS").
dico("M", 7, "MUSCLAT").
dico("M", 7, "MUSCLEE").
dico("M", 7, "MUSCLER").
dico("M", 7, "MUSCLES").
dico("M", 7, "MUSCLEZ").
dico("M", 7, "MUSEALE").
dico("M", 7, "MUSEAUX").
dico("M", 7, "MUSELAI").
dico("M", 7, "MUSELAS").
dico("M", 7, "MUSELAT").
dico("M", 7, "MUSELEE").
dico("M", 7, "MUSELER").
dico("M", 7, "MUSELES").
dico("M", 7, "MUSELET").
dico("M", 7, "MUSELEZ").
dico("M", 7, "MUSELLE").
dico("M", 7, "MUSERAI").
dico("M", 7, "MUSERAS").
dico("M", 7, "MUSEREZ").
dico("M", 7, "MUSETTE").
dico("M", 7, "MUSEUMS").
dico("M", 7, "MUSHERS").
dico("M", 7, "MUSICAL").
dico("M", 7, "MUSIONS").
dico("M", 7, "MUSIQUA").
dico("M", 7, "MUSIQUE").
dico("M", 7, "MUSOIRS").
dico("M", 7, "MUSQUAI").
dico("M", 7, "MUSQUAS").
dico("M", 7, "MUSQUAT").
dico("M", 7, "MUSQUEE").
dico("M", 7, "MUSQUER").
dico("M", 7, "MUSQUES").
dico("M", 7, "MUSQUEZ").
dico("M", 7, "MUSSAIS").
dico("M", 7, "MUSSAIT").
dico("M", 7, "MUSSANT").
dico("M", 7, "MUSSEES").
dico("M", 7, "MUSSENT").
dico("M", 7, "MUSSERA").
dico("M", 7, "MUSSIEZ").
dico("M", 7, "MUSSIFS").
dico("M", 7, "MUSSIVE").
dico("M", 7, "MUSSONS").
dico("M", 7, "MUSTANG").
dico("M", 7, "MUTABLE").
dico("M", 7, "MUTAGES").
dico("M", 7, "MUTAMES").
dico("M", 7, "MUTANTE").
dico("M", 7, "MUTANTS").
dico("M", 7, "MUTASSE").
dico("M", 7, "MUTATES").
dico("M", 7, "MUTERAI").
dico("M", 7, "MUTERAS").
dico("M", 7, "MUTEREZ").
dico("M", 7, "MUTILAI").
dico("M", 7, "MUTILAS").
dico("M", 7, "MUTILAT").
dico("M", 7, "MUTILEE").
dico("M", 7, "MUTILER").
dico("M", 7, "MUTILES").
dico("M", 7, "MUTILEZ").
dico("M", 7, "MUTINAI").
dico("M", 7, "MUTINAS").
dico("M", 7, "MUTINAT").
dico("M", 7, "MUTINEE").
dico("M", 7, "MUTINER").
dico("M", 7, "MUTINES").
dico("M", 7, "MUTINEZ").
dico("M", 7, "MUTIONS").
dico("M", 7, "MUTIQUE").
dico("M", 7, "MUTISME").
dico("M", 7, "MUTITES").
dico("M", 7, "MUTUELS").
dico("M", 7, "MUTULES").
dico("M", 7, "MYALGIE").
dico("M", 7, "MYCOSES").
dico("M", 7, "MYCOSIS").
dico("M", 7, "MYELINE").
dico("M", 7, "MYELITE").
dico("M", 7, "MYELOME").
dico("M", 7, "MYGALES").
dico("M", 7, "MYIASES").
dico("M", 7, "MYOPIES").
dico("M", 7, "MYOSINE").
dico("M", 7, "MYOSITE").
dico("M", 7, "MYRIADE").
dico("M", 7, "MYRICAS").
dico("M", 7, "MYRRHES").
dico("M", 7, "MYRTALE").
dico("M", 7, "MYSTERE").
dico("M", 7, "MYXINES").
dico("M", 7, "MYXOMES").
dico("M", 7, "MZABITE").
