dico("M", 8, "MABOULES").
dico("M", 8, "MACABRES").
dico("M", 8, "MACADAMS").
dico("M", 8, "MACANEEN").
dico("M", 8, "MACAQUES").
dico("M", 8, "MACAREUX").
dico("M", 8, "MACARONI").
dico("M", 8, "MACARONS").
dico("M", 8, "MACASSAR").
dico("M", 8, "MACERAIS").
dico("M", 8, "MACERAIT").
dico("M", 8, "MACERANT").
dico("M", 8, "MACEREES").
dico("M", 8, "MACERENT").
dico("M", 8, "MACERERA").
dico("M", 8, "MACERIEZ").
dico("M", 8, "MACERONS").
dico("M", 8, "MACHAMES").
dico("M", 8, "MACHAONS").
dico("M", 8, "MACHASSE").
dico("M", 8, "MACHATES").
dico("M", 8, "MACHEFER").
dico("M", 8, "MACHERAI").
dico("M", 8, "MACHERAS").
dico("M", 8, "MACHEREZ").
dico("M", 8, "MACHETTE").
dico("M", 8, "MACHEURS").
dico("M", 8, "MACHEUSE").
dico("M", 8, "MACHICOT").
dico("M", 8, "MACHINAI").
dico("M", 8, "MACHINAL").
dico("M", 8, "MACHINAS").
dico("M", 8, "MACHINAT").
dico("M", 8, "MACHINEE").
dico("M", 8, "MACHINER").
dico("M", 8, "MACHINES").
dico("M", 8, "MACHINEZ").
dico("M", 8, "MACHIONS").
dico("M", 8, "MACHISME").
dico("M", 8, "MACHISTE").
dico("M", 8, "MACHOIRE").
dico("M", 8, "MACHONNA").
dico("M", 8, "MACHONNE").
dico("M", 8, "MACHURAI").
dico("M", 8, "MACHURAS").
dico("M", 8, "MACHURAT").
dico("M", 8, "MACHUREE").
dico("M", 8, "MACHURER").
dico("M", 8, "MACHURES").
dico("M", 8, "MACHUREZ").
dico("M", 8, "MACLAGES").
dico("M", 8, "MACLAMES").
dico("M", 8, "MACLASSE").
dico("M", 8, "MACLATES").
dico("M", 8, "MACLERAI").
dico("M", 8, "MACLERAS").
dico("M", 8, "MACLEREZ").
dico("M", 8, "MACLIONS").
dico("M", 8, "MACONNAI").
dico("M", 8, "MACONNAS").
dico("M", 8, "MACONNAT").
dico("M", 8, "MACONNEE").
dico("M", 8, "MACONNER").
dico("M", 8, "MACONNES").
dico("M", 8, "MACONNEZ").
dico("M", 8, "MACOUTES").
dico("M", 8, "MACQUAGE").
dico("M", 8, "MACQUAIS").
dico("M", 8, "MACQUAIT").
dico("M", 8, "MACQUANT").
dico("M", 8, "MACQUEES").
dico("M", 8, "MACQUENT").
dico("M", 8, "MACQUERA").
dico("M", 8, "MACQUIEZ").
dico("M", 8, "MACQUONS").
dico("M", 8, "MACRAMES").
dico("M", 8, "MACREUSE").
dico("M", 8, "MACROURE").
dico("M", 8, "MACULAGE").
dico("M", 8, "MACULAIS").
dico("M", 8, "MACULAIT").
dico("M", 8, "MACULANT").
dico("M", 8, "MACULEES").
dico("M", 8, "MACULENT").
dico("M", 8, "MACULERA").
dico("M", 8, "MACULIEZ").
dico("M", 8, "MACULONS").
dico("M", 8, "MACUMBAS").
dico("M", 8, "MADERIEN").
dico("M", 8, "MADERISA").
dico("M", 8, "MADERISE").
dico("M", 8, "MADICOLE").
dico("M", 8, "MADIRANS").
dico("M", 8, "MADISONS").
dico("M", 8, "MADRAGUE").
dico("M", 8, "MADRASAS").
dico("M", 8, "MADRIERS").
dico("M", 8, "MADRIGAL").
dico("M", 8, "MADRURES").
dico("M", 8, "MAESTOSO").
dico("M", 8, "MAESTRIA").
dico("M", 8, "MAESTROS").
dico("M", 8, "MAFFIEUX").
dico("M", 8, "MAFFIOSI").
dico("M", 8, "MAFFIOSO").
dico("M", 8, "MAFFLUES").
dico("M", 8, "MAFIEUSE").
dico("M", 8, "MAFIOSOS").
dico("M", 8, "MAGANAIS").
dico("M", 8, "MAGANAIT").
dico("M", 8, "MAGANANT").
dico("M", 8, "MAGANEES").
dico("M", 8, "MAGANENT").
dico("M", 8, "MAGANERA").
dico("M", 8, "MAGANIEZ").
dico("M", 8, "MAGANONS").
dico("M", 8, "MAGASINA").
dico("M", 8, "MAGASINE").
dico("M", 8, "MAGASINS").
dico("M", 8, "MAGAZINE").
dico("M", 8, "MAGENTAS").
dico("M", 8, "MAGHZENS").
dico("M", 8, "MAGICIEN").
dico("M", 8, "MAGIQUES").
dico("M", 8, "MAGISTER").
dico("M", 8, "MAGNAMES").
dico("M", 8, "MAGNASSE").
dico("M", 8, "MAGNATES").
dico("M", 8, "MAGNERAI").
dico("M", 8, "MAGNERAS").
dico("M", 8, "MAGNEREZ").
dico("M", 8, "MAGNESIE").
dico("M", 8, "MAGNETON").
dico("M", 8, "MAGNETOS").
dico("M", 8, "MAGNIFIA").
dico("M", 8, "MAGNIFIE").
dico("M", 8, "MAGNIONS").
dico("M", 8, "MAGNOLIA").
dico("M", 8, "MAGYARES").
dico("M", 8, "MAHALEBS").
dico("M", 8, "MAHARAJA").
dico("M", 8, "MAHARANE").
dico("M", 8, "MAHARANI").
dico("M", 8, "MAHATMAS").
dico("M", 8, "MAHAYANA").
dico("M", 8, "MAHDISME").
dico("M", 8, "MAHDISTE").
dico("M", 8, "MAHONIAS").
dico("M", 8, "MAHONNES").
dico("M", 8, "MAHORAIS").
dico("M", 8, "MAHOUSSE").
dico("M", 8, "MAHRATTE").
dico("M", 8, "MAIEURES").
dico("M", 8, "MAIGREUR").
dico("M", 8, "MAIGRIES").
dico("M", 8, "MAIGRIOT").
dico("M", 8, "MAIGRIRA").
dico("M", 8, "MAILINGS").
dico("M", 8, "MAILLAGE").
dico("M", 8, "MAILLAIS").
dico("M", 8, "MAILLAIT").
dico("M", 8, "MAILLANT").
dico("M", 8, "MAILLEES").
dico("M", 8, "MAILLENT").
dico("M", 8, "MAILLERA").
dico("M", 8, "MAILLETA").
dico("M", 8, "MAILLETE").
dico("M", 8, "MAILLETS").
dico("M", 8, "MAILLIEZ").
dico("M", 8, "MAILLONS").
dico("M", 8, "MAILLOTS").
dico("M", 8, "MAILLURE").
dico("M", 8, "MAINATES").
dico("M", 8, "MAINMISE").
dico("M", 8, "MAINTENU").
dico("M", 8, "MAINTIEN").
dico("M", 8, "MAINTINS").
dico("M", 8, "MAINTINT").
dico("M", 8, "MAIORALE").
dico("M", 8, "MAIORATS").
dico("M", 8, "MAIORAUX").
dico("M", 8, "MAIRESSE").
dico("M", 8, "MAISERIE").
dico("M", 8, "MAITRANK").
dico("M", 8, "MAITRISA").
dico("M", 8, "MAITRISE").
dico("M", 8, "MAIZENAS").
dico("M", 8, "MAJESTES").
dico("M", 8, "MAJEURES").
dico("M", 8, "MAJORAIS").
dico("M", 8, "MAJORAIT").
dico("M", 8, "MAJORANT").
dico("M", 8, "MAJORATS").
dico("M", 8, "MAJORAUX").
dico("M", 8, "MAJOREES").
dico("M", 8, "MAJORENT").
dico("M", 8, "MAJORERA").
dico("M", 8, "MAJORIEZ").
dico("M", 8, "MAJORITE").
dico("M", 8, "MAJORONS").
dico("M", 8, "MAKAIRES").
dico("M", 8, "MAKEMONO").
dico("M", 8, "MAKHZENS").
dico("M", 8, "MAKIMONO").
dico("M", 8, "MALABARS").
dico("M", 8, "MALACIES").
dico("M", 8, "MALADIES").
dico("M", 8, "MALADIFS").
dico("M", 8, "MALADIVE").
dico("M", 8, "MALAIMEE").
dico("M", 8, "MALAIMES").
dico("M", 8, "MALAIRES").
dico("M", 8, "MALAISEE").
dico("M", 8, "MALAISES").
dico("M", 8, "MALAMUTE").
dico("M", 8, "MALANDRE").
dico("M", 8, "MALARIAS").
dico("M", 8, "MALAVISE").
dico("M", 8, "MALAWITE").
dico("M", 8, "MALAXAGE").
dico("M", 8, "MALAXAIS").
dico("M", 8, "MALAXAIT").
dico("M", 8, "MALAXANT").
dico("M", 8, "MALAXEES").
dico("M", 8, "MALAXENT").
dico("M", 8, "MALAXERA").
dico("M", 8, "MALAXEUR").
dico("M", 8, "MALAXIEZ").
dico("M", 8, "MALAXONS").
dico("M", 8, "MALBATIE").
dico("M", 8, "MALBATIS").
dico("M", 8, "MALDONNE").
dico("M", 8, "MALEFAIM").
dico("M", 8, "MALEFICE").
dico("M", 8, "MALEKITE").
dico("M", 8, "MALEMORT").
dico("M", 8, "MALFACON").
dico("M", 8, "MALFAIRE").
dico("M", 8, "MALFAMEE").
dico("M", 8, "MALFAMES").
dico("M", 8, "MALFRATS").
dico("M", 8, "MALGACHE").
dico("M", 8, "MALHERBE").
dico("M", 8, "MALHEURS").
dico("M", 8, "MALIENNE").
dico("M", 8, "MALIGNES").
dico("M", 8, "MALINGRE").
dico("M", 8, "MALINKES").
dico("M", 8, "MALINOIS").
dico("M", 8, "MALIQUES").
dico("M", 8, "MALLEOLE").
dico("M", 8, "MALLETTE").
dico("M", 8, "MALMENAI").
dico("M", 8, "MALMENAS").
dico("M", 8, "MALMENAT").
dico("M", 8, "MALMENEE").
dico("M", 8, "MALMENER").
dico("M", 8, "MALMENES").
dico("M", 8, "MALMENEZ").
dico("M", 8, "MALOTRUE").
dico("M", 8, "MALOTRUS").
dico("M", 8, "MALOUINE").
dico("M", 8, "MALOUINS").
dico("M", 8, "MALPEQUE").
dico("M", 8, "MALPOLIE").
dico("M", 8, "MALPOLIS").
dico("M", 8, "MALSAINE").
dico("M", 8, "MALSAINS").
dico("M", 8, "MALSEANT").
dico("M", 8, "MALSTROM").
dico("M", 8, "MALTAGES").
dico("M", 8, "MALTAISE").
dico("M", 8, "MALTAMES").
dico("M", 8, "MALTASES").
dico("M", 8, "MALTASSE").
dico("M", 8, "MALTATES").
dico("M", 8, "MALTERAI").
dico("M", 8, "MALTERAS").
dico("M", 8, "MALTEREZ").
dico("M", 8, "MALTERIE").
dico("M", 8, "MALTEURS").
dico("M", 8, "MALTIONS").
dico("M", 8, "MALTOSES").
dico("M", 8, "MALTOTES").
dico("M", 8, "MALVACEE").
dico("M", 8, "MALVALES").
dico("M", 8, "MALVENUE").
dico("M", 8, "MALVENUS").
dico("M", 8, "MAMELLES").
dico("M", 8, "MAMELONS").
dico("M", 8, "MAMELOUK").
dico("M", 8, "MAMELUES").
dico("M", 8, "MAMELUKE").
dico("M", 8, "MAMELUKS").
dico("M", 8, "MAMMAIRE").
dico("M", 8, "MAMMITES").
dico("M", 8, "MAMMOUTH").
dico("M", 8, "MANADIER").
dico("M", 8, "MANAGEAI").
dico("M", 8, "MANAGEAS").
dico("M", 8, "MANAGEAT").
dico("M", 8, "MANAGEES").
dico("M", 8, "MANAGENT").
dico("M", 8, "MANAGERA").
dico("M", 8, "MANAGERS").
dico("M", 8, "MANAGEUR").
dico("M", 8, "MANAGIEZ").
dico("M", 8, "MANAMEEN").
dico("M", 8, "MANCEAUX").
dico("M", 8, "MANCELLE").
dico("M", 8, "MANCHOIS").
dico("M", 8, "MANCHONS").
dico("M", 8, "MANCHOTE").
dico("M", 8, "MANCHOTS").
dico("M", 8, "MANCHOUE").
dico("M", 8, "MANCHOUS").
dico("M", 8, "MANDALAS").
dico("M", 8, "MANDALES").
dico("M", 8, "MANDAMES").
dico("M", 8, "MANDANTE").
dico("M", 8, "MANDANTS").
dico("M", 8, "MANDARIN").
dico("M", 8, "MANDASSE").
dico("M", 8, "MANDATAI").
dico("M", 8, "MANDATAS").
dico("M", 8, "MANDATAT").
dico("M", 8, "MANDATEE").
dico("M", 8, "MANDATER").
dico("M", 8, "MANDATES").
dico("M", 8, "MANDATEZ").
dico("M", 8, "MANDCHOU").
dico("M", 8, "MANDEENS").
dico("M", 8, "MANDERAI").
dico("M", 8, "MANDERAS").
dico("M", 8, "MANDEREZ").
dico("M", 8, "MANDILLE").
dico("M", 8, "MANDIONS").
dico("M", 8, "MANDOLES").
dico("M", 8, "MANDORES").
dico("M", 8, "MANDORLE").
dico("M", 8, "MANDRILL").
dico("M", 8, "MANDRINA").
dico("M", 8, "MANDRINE").
dico("M", 8, "MANDRINS").
dico("M", 8, "MANEGEAI").
dico("M", 8, "MANEGEAS").
dico("M", 8, "MANEGEAT").
dico("M", 8, "MANEGEES").
dico("M", 8, "MANEGENT").
dico("M", 8, "MANEGERA").
dico("M", 8, "MANEGIEZ").
dico("M", 8, "MANETONS").
dico("M", 8, "MANETTES").
dico("M", 8, "MANGABEY").
dico("M", 8, "MANGANIN").
dico("M", 8, "MANGEAIS").
dico("M", 8, "MANGEAIT").
dico("M", 8, "MANGEANT").
dico("M", 8, "MANGEONS").
dico("M", 8, "MANGEOTA").
dico("M", 8, "MANGEOTE").
dico("M", 8, "MANGERAI").
dico("M", 8, "MANGERAS").
dico("M", 8, "MANGEREZ").
dico("M", 8, "MANGERIE").
dico("M", 8, "MANGEURE").
dico("M", 8, "MANGEURS").
dico("M", 8, "MANGEUSE").
dico("M", 8, "MANGIONS").
dico("M", 8, "MANGLIER").
dico("M", 8, "MANGROVE").
dico("M", 8, "MANGUIER").
dico("M", 8, "MANIABLE").
dico("M", 8, "MANIAGES").
dico("M", 8, "MANIAMES").
dico("M", 8, "MANIAQUE").
dico("M", 8, "MANIASSE").
dico("M", 8, "MANIATES").
dico("M", 8, "MANICLES").
dico("M", 8, "MANIERAI").
dico("M", 8, "MANIERAS").
dico("M", 8, "MANIEREE").
dico("M", 8, "MANIERES").
dico("M", 8, "MANIEREZ").
dico("M", 8, "MANIEURS").
dico("M", 8, "MANIEUSE").
dico("M", 8, "MANIFOLD").
dico("M", 8, "MANIIONS").
dico("M", 8, "MANILLAI").
dico("M", 8, "MANILLAS").
dico("M", 8, "MANILLAT").
dico("M", 8, "MANILLEE").
dico("M", 8, "MANILLER").
dico("M", 8, "MANILLES").
dico("M", 8, "MANILLEZ").
dico("M", 8, "MANILLON").
dico("M", 8, "MANIPULA").
dico("M", 8, "MANIPULE").
dico("M", 8, "MANIQUES").
dico("M", 8, "MANITOUS").
dico("M", 8, "MANIVEAU").
dico("M", 8, "MANNETTE").
dico("M", 8, "MANNITES").
dico("M", 8, "MANNITOL").
dico("M", 8, "MANNOISE").
dico("M", 8, "MANNOSES").
dico("M", 8, "MANOQUAI").
dico("M", 8, "MANOQUAS").
dico("M", 8, "MANOQUAT").
dico("M", 8, "MANOQUEE").
dico("M", 8, "MANOQUER").
dico("M", 8, "MANOQUES").
dico("M", 8, "MANOQUEZ").
dico("M", 8, "MANOSTAT").
dico("M", 8, "MANOUCHE").
dico("M", 8, "MANQUAIS").
dico("M", 8, "MANQUAIT").
dico("M", 8, "MANQUANT").
dico("M", 8, "MANQUEES").
dico("M", 8, "MANQUENT").
dico("M", 8, "MANQUERA").
dico("M", 8, "MANQUIEZ").
dico("M", 8, "MANQUONS").
dico("M", 8, "MANSARDE").
dico("M", 8, "MANSIONS").
dico("M", 8, "MANTEAUX").
dico("M", 8, "MANTELEE").
dico("M", 8, "MANTELES").
dico("M", 8, "MANTELET").
dico("M", 8, "MANTILLE").
dico("M", 8, "MANTIQUE").
dico("M", 8, "MANTISSE").
dico("M", 8, "MANTOUAN").
dico("M", 8, "MANUCURA").
dico("M", 8, "MANUCURE").
dico("M", 8, "MANUELIN").
dico("M", 8, "MANUELLE").
dico("M", 8, "MAOISMES").
dico("M", 8, "MAOISTES").
dico("M", 8, "MAOUSSES").
dico("M", 8, "MAPPAGES").
dico("M", 8, "MAPPAMES").
dico("M", 8, "MAPPASSE").
dico("M", 8, "MAPPATES").
dico("M", 8, "MAPPERAI").
dico("M", 8, "MAPPERAS").
dico("M", 8, "MAPPEREZ").
dico("M", 8, "MAPPIONS").
dico("M", 8, "MAPUTAIS").
dico("M", 8, "MAQUAMES").
dico("M", 8, "MAQUASSE").
dico("M", 8, "MAQUATES").
dico("M", 8, "MAQUERAI").
dico("M", 8, "MAQUERAS").
dico("M", 8, "MAQUEREZ").
dico("M", 8, "MAQUETTA").
dico("M", 8, "MAQUETTE").
dico("M", 8, "MAQUILLA").
dico("M", 8, "MAQUILLE").
dico("M", 8, "MAQUIONS").
dico("M", 8, "MARABOUT").
dico("M", 8, "MARACUJA").
dico("M", 8, "MARAGING").
dico("M", 8, "MARANTAS").
dico("M", 8, "MARANTES").
dico("M", 8, "MARASMES").
dico("M", 8, "MARASQUE").
dico("M", 8, "MARATHES").
dico("M", 8, "MARATHIS").
dico("M", 8, "MARATHON").
dico("M", 8, "MARATRES").
dico("M", 8, "MARAUDAI").
dico("M", 8, "MARAUDAS").
dico("M", 8, "MARAUDAT").
dico("M", 8, "MARAUDEE").
dico("M", 8, "MARAUDER").
dico("M", 8, "MARAUDES").
dico("M", 8, "MARAUDEZ").
dico("M", 8, "MARBRAIS").
dico("M", 8, "MARBRAIT").
dico("M", 8, "MARBRANT").
dico("M", 8, "MARBREES").
dico("M", 8, "MARBRENT").
dico("M", 8, "MARBRERA").
dico("M", 8, "MARBREUR").
dico("M", 8, "MARBRIER").
dico("M", 8, "MARBRIEZ").
dico("M", 8, "MARBRONS").
dico("M", 8, "MARBRURE").
dico("M", 8, "MARCAIRE").
dico("M", 8, "MARCHAIS").
dico("M", 8, "MARCHAIT").
dico("M", 8, "MARCHAND").
dico("M", 8, "MARCHANT").
dico("M", 8, "MARCHENT").
dico("M", 8, "MARCHERA").
dico("M", 8, "MARCHERS").
dico("M", 8, "MARCHEUR").
dico("M", 8, "MARCHIEZ").
dico("M", 8, "MARCHONS").
dico("M", 8, "MARCONIS").
dico("M", 8, "MARCOTTA").
dico("M", 8, "MARCOTTE").
dico("M", 8, "MARECAGE").
dico("M", 8, "MARECHAL").
dico("M", 8, "MARELLES").
dico("M", 8, "MAREMMES").
dico("M", 8, "MARENGOS").
dico("M", 8, "MARENNES").
dico("M", 8, "MAREYAGE").
dico("M", 8, "MAREYEUR").
dico("M", 8, "MARGAUDA").
dico("M", 8, "MARGAUDE").
dico("M", 8, "MARGEAIS").
dico("M", 8, "MARGEAIT").
dico("M", 8, "MARGEANT").
dico("M", 8, "MARGELLE").
dico("M", 8, "MARGEOIR").
dico("M", 8, "MARGEONS").
dico("M", 8, "MARGERAI").
dico("M", 8, "MARGERAS").
dico("M", 8, "MARGEREZ").
dico("M", 8, "MARGEURS").
dico("M", 8, "MARGEUSE").
dico("M", 8, "MARGINAI").
dico("M", 8, "MARGINAL").
dico("M", 8, "MARGINAS").
dico("M", 8, "MARGINAT").
dico("M", 8, "MARGINEE").
dico("M", 8, "MARGINER").
dico("M", 8, "MARGINES").
dico("M", 8, "MARGINEZ").
dico("M", 8, "MARGIONS").
dico("M", 8, "MARGOTAI").
dico("M", 8, "MARGOTAS").
dico("M", 8, "MARGOTAT").
dico("M", 8, "MARGOTER").
dico("M", 8, "MARGOTES").
dico("M", 8, "MARGOTEZ").
dico("M", 8, "MARGOTIN").
dico("M", 8, "MARGOTTA").
dico("M", 8, "MARGOTTE").
dico("M", 8, "MARGRAVE").
dico("M", 8, "MARIABLE").
dico("M", 8, "MARIACHI").
dico("M", 8, "MARIAGES").
dico("M", 8, "MARIALES").
dico("M", 8, "MARIAMES").
dico("M", 8, "MARIASSE").
dico("M", 8, "MARIATES").
dico("M", 8, "MARIERAI").
dico("M", 8, "MARIERAS").
dico("M", 8, "MARIEREZ").
dico("M", 8, "MARIEURS").
dico("M", 8, "MARIEUSE").
dico("M", 8, "MARIGOTS").
dico("M", 8, "MARIIONS").
dico("M", 8, "MARIMBAS").
dico("M", 8, "MARINADE").
dico("M", 8, "MARINAGE").
dico("M", 8, "MARINAIS").
dico("M", 8, "MARINAIT").
dico("M", 8, "MARINANT").
dico("M", 8, "MARINEES").
dico("M", 8, "MARINENT").
dico("M", 8, "MARINERA").
dico("M", 8, "MARINIER").
dico("M", 8, "MARINIEZ").
dico("M", 8, "MARINONS").
dico("M", 8, "MARIOLES").
dico("M", 8, "MARIOLLE").
dico("M", 8, "MARISQUE").
dico("M", 8, "MARISTES").
dico("M", 8, "MARITALE").
dico("M", 8, "MARITAUX").
dico("M", 8, "MARITIME").
dico("M", 8, "MARMITAI").
dico("M", 8, "MARMITAS").
dico("M", 8, "MARMITAT").
dico("M", 8, "MARMITEE").
dico("M", 8, "MARMITER").
dico("M", 8, "MARMITES").
dico("M", 8, "MARMITEZ").
dico("M", 8, "MARMITON").
dico("M", 8, "MARMONNA").
dico("M", 8, "MARMONNE").
dico("M", 8, "MARMOTTA").
dico("M", 8, "MARMOTTE").
dico("M", 8, "MARNAGES").
dico("M", 8, "MARNAISE").
dico("M", 8, "MARNAMES").
dico("M", 8, "MARNASSE").
dico("M", 8, "MARNATES").
dico("M", 8, "MARNERAI").
dico("M", 8, "MARNERAS").
dico("M", 8, "MARNEREZ").
dico("M", 8, "MARNEURS").
dico("M", 8, "MARNEUSE").
dico("M", 8, "MARNIERE").
dico("M", 8, "MARNIONS").
dico("M", 8, "MAROCAIN").
dico("M", 8, "MAROLLES").
dico("M", 8, "MARONAGE").
dico("M", 8, "MARONITE").
dico("M", 8, "MARONNAI").
dico("M", 8, "MARONNAS").
dico("M", 8, "MARONNAT").
dico("M", 8, "MARONNER").
dico("M", 8, "MARONNES").
dico("M", 8, "MARONNEZ").
dico("M", 8, "MAROQUIN").
dico("M", 8, "MAROTTES").
dico("M", 8, "MAROUFLA").
dico("M", 8, "MAROUFLE").
dico("M", 8, "MAROUTES").
dico("M", 8, "MARQUAGE").
dico("M", 8, "MARQUAIS").
dico("M", 8, "MARQUAIT").
dico("M", 8, "MARQUANT").
dico("M", 8, "MARQUEES").
dico("M", 8, "MARQUENT").
dico("M", 8, "MARQUERA").
dico("M", 8, "MARQUETA").
dico("M", 8, "MARQUETE").
dico("M", 8, "MARQUEUR").
dico("M", 8, "MARQUIEZ").
dico("M", 8, "MARQUISE").
dico("M", 8, "MARQUOIR").
dico("M", 8, "MARQUONS").
dico("M", 8, "MARRAINE").
dico("M", 8, "MARRAMES").
dico("M", 8, "MARRANES").
dico("M", 8, "MARRANTE").
dico("M", 8, "MARRANTS").
dico("M", 8, "MARRASSE").
dico("M", 8, "MARRATES").
dico("M", 8, "MARRERAI").
dico("M", 8, "MARRERAS").
dico("M", 8, "MARREREZ").
dico("M", 8, "MARRIONS").
dico("M", 8, "MARRONNA").
dico("M", 8, "MARRONNE").
dico("M", 8, "MARRUBES").
dico("M", 8, "MARSALAS").
dico("M", 8, "MARSAULT").
dico("M", 8, "MARSEAUX").
dico("M", 8, "MARSHALS").
dico("M", 8, "MARSOUIN").
dico("M", 8, "MARTAGON").
dico("M", 8, "MARTEAUX").
dico("M", 8, "MARTELAI").
dico("M", 8, "MARTELAS").
dico("M", 8, "MARTELAT").
dico("M", 8, "MARTELEE").
dico("M", 8, "MARTELER").
dico("M", 8, "MARTELES").
dico("M", 8, "MARTELET").
dico("M", 8, "MARTELEZ").
dico("M", 8, "MARTIALE").
dico("M", 8, "MARTIAUX").
dico("M", 8, "MARTIENS").
dico("M", 8, "MARTINET").
dico("M", 8, "MARTINIS").
dico("M", 8, "MARTYRES").
dico("M", 8, "MARXIENS").
dico("M", 8, "MARXISAI").
dico("M", 8, "MARXISAS").
dico("M", 8, "MARXISAT").
dico("M", 8, "MARXISEE").
dico("M", 8, "MARXISER").
dico("M", 8, "MARXISES").
dico("M", 8, "MARXISEZ").
dico("M", 8, "MARXISME").
dico("M", 8, "MARXISTE").
dico("M", 8, "MARYLAND").
dico("M", 8, "MASCARAS").
dico("M", 8, "MASCARET").
dico("M", 8, "MASCARON").
dico("M", 8, "MASCOGNE").
dico("M", 8, "MASCOTTE").
dico("M", 8, "MASCULIN").
dico("M", 8, "MASEROIS").
dico("M", 8, "MASQUAGE").
dico("M", 8, "MASQUAIS").
dico("M", 8, "MASQUAIT").
dico("M", 8, "MASQUANT").
dico("M", 8, "MASQUEES").
dico("M", 8, "MASQUENT").
dico("M", 8, "MASQUERA").
dico("M", 8, "MASQUIEZ").
dico("M", 8, "MASQUONS").
dico("M", 8, "MASSACRA").
dico("M", 8, "MASSACRE").
dico("M", 8, "MASSAGES").
dico("M", 8, "MASSAMES").
dico("M", 8, "MASSASSE").
dico("M", 8, "MASSATES").
dico("M", 8, "MASSERAI").
dico("M", 8, "MASSERAS").
dico("M", 8, "MASSEREZ").
dico("M", 8, "MASSETER").
dico("M", 8, "MASSETTE").
dico("M", 8, "MASSEURS").
dico("M", 8, "MASSEUSE").
dico("M", 8, "MASSICOT").
dico("M", 8, "MASSIERE").
dico("M", 8, "MASSIERS").
dico("M", 8, "MASSIFIA").
dico("M", 8, "MASSIFIE").
dico("M", 8, "MASSIONS").
dico("M", 8, "MASSIQUE").
dico("M", 8, "MASSIVES").
dico("M", 8, "MASSORAH").
dico("M", 8, "MASSORES").
dico("M", 8, "MASTABAS").
dico("M", 8, "MASTARDS").
dico("M", 8, "MASTERES").
dico("M", 8, "MASTIFFS").
dico("M", 8, "MASTIQUA").
dico("M", 8, "MASTIQUE").
dico("M", 8, "MASTITES").
dico("M", 8, "MASTOIDE").
dico("M", 8, "MASTOSES").
dico("M", 8, "MASTURBA").
dico("M", 8, "MASTURBE").
dico("M", 8, "MASURIUM").
dico("M", 8, "MATADORS").
dico("M", 8, "MATAIENT").
dico("M", 8, "MATAMORE").
dico("M", 8, "MATASSES").
dico("M", 8, "MATCHAIS").
dico("M", 8, "MATCHAIT").
dico("M", 8, "MATCHANT").
dico("M", 8, "MATCHEES").
dico("M", 8, "MATCHENT").
dico("M", 8, "MATCHERA").
dico("M", 8, "MATCHIEZ").
dico("M", 8, "MATCHONS").
dico("M", 8, "MATEFAIM").
dico("M", 8, "MATELOTE").
dico("M", 8, "MATELOTS").
dico("M", 8, "MATERAIS").
dico("M", 8, "MATERAIT").
dico("M", 8, "MATEREAU").
dico("M", 8, "MATERENT").
dico("M", 8, "MATERIAU").
dico("M", 8, "MATERIEL").
dico("M", 8, "MATERIEZ").
dico("M", 8, "MATERNAI").
dico("M", 8, "MATERNAS").
dico("M", 8, "MATERNAT").
dico("M", 8, "MATERNEE").
dico("M", 8, "MATERNEL").
dico("M", 8, "MATERNER").
dico("M", 8, "MATERNES").
dico("M", 8, "MATERNEZ").
dico("M", 8, "MATERONS").
dico("M", 8, "MATERONT").
dico("M", 8, "MATEUSES").
dico("M", 8, "MATHEUSE").
dico("M", 8, "MATHURIN").
dico("M", 8, "MATIERES").
dico("M", 8, "MATIFIAI").
dico("M", 8, "MATIFIAS").
dico("M", 8, "MATIFIAT").
dico("M", 8, "MATIFIEE").
dico("M", 8, "MATIFIER").
dico("M", 8, "MATIFIES").
dico("M", 8, "MATIFIEZ").
dico("M", 8, "MATINAIS").
dico("M", 8, "MATINAIT").
dico("M", 8, "MATINALE").
dico("M", 8, "MATINANT").
dico("M", 8, "MATINAUX").
dico("M", 8, "MATINEES").
dico("M", 8, "MATINENT").
dico("M", 8, "MATINERA").
dico("M", 8, "MATINEUX").
dico("M", 8, "MATINIER").
dico("M", 8, "MATINIEZ").
dico("M", 8, "MATINONS").
dico("M", 8, "MATIRAIS").
dico("M", 8, "MATIRAIT").
dico("M", 8, "MATIRENT").
dico("M", 8, "MATIRIEZ").
dico("M", 8, "MATIRONS").
dico("M", 8, "MATIRONT").
dico("M", 8, "MATISSES").
dico("M", 8, "MATISSEZ").
dico("M", 8, "MATOISES").
dico("M", 8, "MATONNES").
dico("M", 8, "MATORRAL").
dico("M", 8, "MATOUTOU").
dico("M", 8, "MATRAQUA").
dico("M", 8, "MATRAQUE").
dico("M", 8, "MATRICAI").
dico("M", 8, "MATRICAS").
dico("M", 8, "MATRICAT").
dico("M", 8, "MATRICEE").
dico("M", 8, "MATRICER").
dico("M", 8, "MATRICES").
dico("M", 8, "MATRICEZ").
dico("M", 8, "MATRONES").
dico("M", 8, "MATURAIS").
dico("M", 8, "MATURAIT").
dico("M", 8, "MATURANT").
dico("M", 8, "MATURASE").
dico("M", 8, "MATUREES").
dico("M", 8, "MATURENT").
dico("M", 8, "MATURERA").
dico("M", 8, "MATURIEZ").
dico("M", 8, "MATURITE").
dico("M", 8, "MATURONS").
dico("M", 8, "MAUBECHE").
dico("M", 8, "MAUDIMES").
dico("M", 8, "MAUDIRAI").
dico("M", 8, "MAUDIRAS").
dico("M", 8, "MAUDIREZ").
dico("M", 8, "MAUDISSE").
dico("M", 8, "MAUDITES").
dico("M", 8, "MAUGREAI").
dico("M", 8, "MAUGREAS").
dico("M", 8, "MAUGREAT").
dico("M", 8, "MAUGREEE").
dico("M", 8, "MAUGREER").
dico("M", 8, "MAUGREES").
dico("M", 8, "MAUGREEZ").
dico("M", 8, "MAURELLE").
dico("M", 8, "MAURISTE").
dico("M", 8, "MAUSOLEE").
dico("M", 8, "MAUSSADE").
dico("M", 8, "MAUVAISE").
dico("M", 8, "MAUVEINE").
dico("M", 8, "MAXILLES").
dico("M", 8, "MAXIMALE").
dico("M", 8, "MAXIMANT").
dico("M", 8, "MAXIMAUX").
dico("M", 8, "MAXIMISA").
dico("M", 8, "MAXIMISE").
dico("M", 8, "MAXIMUMS").
dico("M", 8, "MAXWELLS").
dico("M", 8, "MAYEURES").
dico("M", 8, "MAYORALE").
dico("M", 8, "MAYORATS").
dico("M", 8, "MAYORAUX").
dico("M", 8, "MAZAGRAN").
dico("M", 8, "MAZAIENT").
dico("M", 8, "MAZASSES").
dico("M", 8, "MAZDEENS").
dico("M", 8, "MAZEAGES").
dico("M", 8, "MAZERAIS").
dico("M", 8, "MAZERAIT").
dico("M", 8, "MAZERENT").
dico("M", 8, "MAZERIEZ").
dico("M", 8, "MAZERONS").
dico("M", 8, "MAZERONT").
dico("M", 8, "MAZETTES").
dico("M", 8, "MAZOUTAI").
dico("M", 8, "MAZOUTAS").
dico("M", 8, "MAZOUTAT").
dico("M", 8, "MAZOUTEE").
dico("M", 8, "MAZOUTER").
dico("M", 8, "MAZOUTES").
dico("M", 8, "MAZOUTEZ").
dico("M", 8, "MAZURKAS").
dico("M", 8, "MBALAKHS").
dico("M", 8, "MEANDRES").
dico("M", 8, "MECANISA").
dico("M", 8, "MECANISE").
dico("M", 8, "MECCANOS").
dico("M", 8, "MECENATS").
dico("M", 8, "MECHAGES").
dico("M", 8, "MECHAMES").
dico("M", 8, "MECHANTE").
dico("M", 8, "MECHANTS").
dico("M", 8, "MECHASSE").
dico("M", 8, "MECHATES").
dico("M", 8, "MECHERAI").
dico("M", 8, "MECHERAS").
dico("M", 8, "MECHEREZ").
dico("M", 8, "MECHEUSE").
dico("M", 8, "MECHIONS").
dico("M", 8, "MECHOUIS").
dico("M", 8, "MECOMPTE").
dico("M", 8, "MECONIAL").
dico("M", 8, "MECONIUM").
dico("M", 8, "MECONNUE").
dico("M", 8, "MECONNUS").
dico("M", 8, "MECONNUT").
dico("M", 8, "MECREANT").
dico("M", 8, "MEDAILLA").
dico("M", 8, "MEDAILLE").
dico("M", 8, "MEDECINE").
dico("M", 8, "MEDECINS").
dico("M", 8, "MEDERSAS").
dico("M", 8, "MEDIALES").
dico("M", 8, "MEDIAMAT").
dico("M", 8, "MEDIANES").
dico("M", 8, "MEDIANTE").
dico("M", 8, "MEDIATES").
dico("M", 8, "MEDIATOR").
dico("M", 8, "MEDICALE").
dico("M", 8, "MEDICATS").
dico("M", 8, "MEDICAUX").
dico("M", 8, "MEDIEVAL").
dico("M", 8, "MEDIMNES").
dico("M", 8, "MEDIOCRE").
dico("M", 8, "MEDIQUES").
dico("M", 8, "MEDIRAIS").
dico("M", 8, "MEDIRAIT").
dico("M", 8, "MEDIRENT").
dico("M", 8, "MEDIRIEZ").
dico("M", 8, "MEDIRONS").
dico("M", 8, "MEDIRONT").
dico("M", 8, "MEDISAIS").
dico("M", 8, "MEDISAIT").
dico("M", 8, "MEDISANT").
dico("M", 8, "MEDISENT").
dico("M", 8, "MEDISIEZ").
dico("M", 8, "MEDISONS").
dico("M", 8, "MEDISSES").
dico("M", 8, "MEDITAIS").
dico("M", 8, "MEDITAIT").
dico("M", 8, "MEDITANT").
dico("M", 8, "MEDITEES").
dico("M", 8, "MEDITENT").
dico("M", 8, "MEDITERA").
dico("M", 8, "MEDITIEZ").
dico("M", 8, "MEDITONS").
dico("M", 8, "MEDULLAS").
dico("M", 8, "MEDUSAIS").
dico("M", 8, "MEDUSAIT").
dico("M", 8, "MEDUSANT").
dico("M", 8, "MEDUSEES").
dico("M", 8, "MEDUSENT").
dico("M", 8, "MEDUSERA").
dico("M", 8, "MEDUSIEZ").
dico("M", 8, "MEDUSONS").
dico("M", 8, "MEETINGS").
dico("M", 8, "MEFIAMES").
dico("M", 8, "MEFIANCE").
dico("M", 8, "MEFIANTE").
dico("M", 8, "MEFIANTS").
dico("M", 8, "MEFIASSE").
dico("M", 8, "MEFIATES").
dico("M", 8, "MEFIERAI").
dico("M", 8, "MEFIERAS").
dico("M", 8, "MEFIEREZ").
dico("M", 8, "MEFIIONS").
dico("M", 8, "MEFORMES").
dico("M", 8, "MEGABITS").
dico("M", 8, "MEGABYTE").
dico("M", 8, "MEGAPODE").
dico("M", 8, "MEGAPOLE").
dico("M", 8, "MEGARDES").
dico("M", 8, "MEGARONS").
dico("M", 8, "MEGAWATT").
dico("M", 8, "MEGIRAIS").
dico("M", 8, "MEGIRAIT").
dico("M", 8, "MEGIRENT").
dico("M", 8, "MEGIRIEZ").
dico("M", 8, "MEGIRONS").
dico("M", 8, "MEGIRONT").
dico("M", 8, "MEGISSAI").
dico("M", 8, "MEGISSAS").
dico("M", 8, "MEGISSAT").
dico("M", 8, "MEGISSEE").
dico("M", 8, "MEGISSER").
dico("M", 8, "MEGISSES").
dico("M", 8, "MEGISSEZ").
dico("M", 8, "MEGOTAGE").
dico("M", 8, "MEGOTAIS").
dico("M", 8, "MEGOTAIT").
dico("M", 8, "MEGOTANT").
dico("M", 8, "MEGOTEES").
dico("M", 8, "MEGOTENT").
dico("M", 8, "MEGOTERA").
dico("M", 8, "MEGOTIEZ").
dico("M", 8, "MEGOTONS").
dico("M", 8, "MEHALLAS").
dico("M", 8, "MEHAREES").
dico("M", 8, "MEILLEUR").
dico("M", 8, "MEISTRES").
dico("M", 8, "MEJANAGE").
dico("M", 8, "MEJUGEAI").
dico("M", 8, "MEJUGEAS").
dico("M", 8, "MEJUGEAT").
dico("M", 8, "MEJUGEES").
dico("M", 8, "MEJUGENT").
dico("M", 8, "MEJUGERA").
dico("M", 8, "MEJUGIEZ").
dico("M", 8, "MELAENAS").
dico("M", 8, "MELAIENT").
dico("M", 8, "MELAMINE").
dico("M", 8, "MELANGEA").
dico("M", 8, "MELANGEE").
dico("M", 8, "MELANGER").
dico("M", 8, "MELANGES").
dico("M", 8, "MELANGEZ").
dico("M", 8, "MELANINE").
dico("M", 8, "MELANOME").
dico("M", 8, "MELANOSE").
dico("M", 8, "MELANTES").
dico("M", 8, "MELASSES").
dico("M", 8, "MELCHIOR").
dico("M", 8, "MELCHITE").
dico("M", 8, "MELDOISE").
dico("M", 8, "MELERAIS").
dico("M", 8, "MELERAIT").
dico("M", 8, "MELERENT").
dico("M", 8, "MELERIEZ").
dico("M", 8, "MELERONS").
dico("M", 8, "MELERONT").
dico("M", 8, "MELIACEE").
dico("M", 8, "MELILOTS").
dico("M", 8, "MELINITE").
dico("M", 8, "MELIQUES").
dico("M", 8, "MELISSES").
dico("M", 8, "MELITTES").
dico("M", 8, "MELKITES").
dico("M", 8, "MELLIFLU").
dico("M", 8, "MELLITES").
dico("M", 8, "MELODICA").
dico("M", 8, "MELODIES").
dico("M", 8, "MELOIDES").
dico("M", 8, "MELOMANE").
dico("M", 8, "MELOMELE").
dico("M", 8, "MELONNEE").
dico("M", 8, "MELONNES").
dico("M", 8, "MELOPEES").
dico("M", 8, "MELUNAIS").
dico("M", 8, "MELUSINE").
dico("M", 8, "MEMBRANE").
dico("M", 8, "MEMBREES").
dico("M", 8, "MEMBRONS").
dico("M", 8, "MEMBRUES").
dico("M", 8, "MEMBRURE").
dico("M", 8, "MEMEMENT").
dico("M", 8, "MEMENTOS").
dico("M", 8, "MEMERAIS").
dico("M", 8, "MEMERAIT").
dico("M", 8, "MEMERANT").
dico("M", 8, "MEMERENT").
dico("M", 8, "MEMERERA").
dico("M", 8, "MEMERIEZ").
dico("M", 8, "MEMERONS").
dico("M", 8, "MEMOIRES").
dico("M", 8, "MEMORIAL").
dico("M", 8, "MEMORIEL").
dico("M", 8, "MEMORISA").
dico("M", 8, "MEMORISE").
dico("M", 8, "MENACAIS").
dico("M", 8, "MENACAIT").
dico("M", 8, "MENACANT").
dico("M", 8, "MENACEES").
dico("M", 8, "MENACENT").
dico("M", 8, "MENACERA").
dico("M", 8, "MENACIEZ").
dico("M", 8, "MENACONS").
dico("M", 8, "MENAGEAI").
dico("M", 8, "MENAGEAS").
dico("M", 8, "MENAGEAT").
dico("M", 8, "MENAGEES").
dico("M", 8, "MENAGENT").
dico("M", 8, "MENAGERA").
dico("M", 8, "MENAGERE").
dico("M", 8, "MENAGERS").
dico("M", 8, "MENAGIEZ").
dico("M", 8, "MENAIENT").
dico("M", 8, "MENANTES").
dico("M", 8, "MENASSES").
dico("M", 8, "MENDIAIS").
dico("M", 8, "MENDIAIT").
dico("M", 8, "MENDIANT").
dico("M", 8, "MENDIEES").
dico("M", 8, "MENDIENT").
dico("M", 8, "MENDIERA").
dico("M", 8, "MENDIGOT").
dico("M", 8, "MENDIIEZ").
dico("M", 8, "MENDIONS").
dico("M", 8, "MENDOISE").
dico("M", 8, "MENDOLES").
dico("M", 8, "MENERAIS").
dico("M", 8, "MENERAIT").
dico("M", 8, "MENERENT").
dico("M", 8, "MENERIEZ").
dico("M", 8, "MENERONS").
dico("M", 8, "MENERONT").
dico("M", 8, "MENEUSES").
dico("M", 8, "MENIANES").
dico("M", 8, "MENINGEE").
dico("M", 8, "MENINGES").
dico("M", 8, "MENISCAL").
dico("M", 8, "MENISQUE").
dico("M", 8, "MENOLOGE").
dico("M", 8, "MENOPOME").
dico("M", 8, "MENOTTAI").
dico("M", 8, "MENOTTAS").
dico("M", 8, "MENOTTAT").
dico("M", 8, "MENOTTEE").
dico("M", 8, "MENOTTER").
dico("M", 8, "MENOTTES").
dico("M", 8, "MENOTTEZ").
dico("M", 8, "MENSONGE").
dico("M", 8, "MENSTRUE").
dico("M", 8, "MENSUELS").
dico("M", 8, "MENTALES").
dico("M", 8, "MENTERIE").
dico("M", 8, "MENTEURS").
dico("M", 8, "MENTEUSE").
dico("M", 8, "MENTHANE").
dico("M", 8, "MENTHOLE").
dico("M", 8, "MENTHOLS").
dico("M", 8, "MENTIMES").
dico("M", 8, "MENTIONS").
dico("M", 8, "MENTIRAI").
dico("M", 8, "MENTIRAS").
dico("M", 8, "MENTIREZ").
dico("M", 8, "MENTISME").
dico("M", 8, "MENTISSE").
dico("M", 8, "MENTITES").
dico("M", 8, "MENUISAI").
dico("M", 8, "MENUISAS").
dico("M", 8, "MENUISAT").
dico("M", 8, "MENUISEE").
dico("M", 8, "MENUISER").
dico("M", 8, "MENUISES").
dico("M", 8, "MENUISEZ").
dico("M", 8, "MEPLATES").
dico("M", 8, "MEPRENDS").
dico("M", 8, "MEPRENEZ").
dico("M", 8, "MEPRENNE").
dico("M", 8, "MEPRIMES").
dico("M", 8, "MEPRISAI").
dico("M", 8, "MEPRISAS").
dico("M", 8, "MEPRISAT").
dico("M", 8, "MEPRISEE").
dico("M", 8, "MEPRISER").
dico("M", 8, "MEPRISES").
dico("M", 8, "MEPRISEZ").
dico("M", 8, "MEPRISSE").
dico("M", 8, "MEPRITES").
dico("M", 8, "MERANTIS").
dico("M", 8, "MERCANTI").
dico("M", 8, "MERCERIE").
dico("M", 8, "MERCIERE").
dico("M", 8, "MERCIERS").
dico("M", 8, "MERCREDI").
dico("M", 8, "MERCURES").
dico("M", 8, "MERCUREY").
dico("M", 8, "MERDAMES").
dico("M", 8, "MERDASSE").
dico("M", 8, "MERDATES").
dico("M", 8, "MERDERAI").
dico("M", 8, "MERDERAS").
dico("M", 8, "MERDEREZ").
dico("M", 8, "MERDEUSE").
dico("M", 8, "MERDIERS").
dico("M", 8, "MERDIONS").
dico("M", 8, "MERDIQUE").
dico("M", 8, "MERDOIES").
dico("M", 8, "MERDOYAI").
dico("M", 8, "MERDOYAS").
dico("M", 8, "MERDOYAT").
dico("M", 8, "MERDOYER").
dico("M", 8, "MERDOYEZ").
dico("M", 8, "MERENGUE").
dico("M", 8, "MERGULES").
dico("M", 8, "MERIDIEN").
dico("M", 8, "MERINGUA").
dico("M", 8, "MERINGUE").
dico("M", 8, "MERISIER").
dico("M", 8, "MERISMES").
dico("M", 8, "MERITAIS").
dico("M", 8, "MERITAIT").
dico("M", 8, "MERITANT").
dico("M", 8, "MERITEES").
dico("M", 8, "MERITENT").
dico("M", 8, "MERITERA").
dico("M", 8, "MERITIEZ").
dico("M", 8, "MERITONS").
dico("M", 8, "MERLEAUX").
dico("M", 8, "MERLETTE").
dico("M", 8, "MERLONNA").
dico("M", 8, "MERLONNE").
dico("M", 8, "MERLUCHE").
dico("M", 8, "MERRAINS").
dico("M", 8, "MERZLOTA").
dico("M", 8, "MESAISES").
dico("M", 8, "MESALLIA").
dico("M", 8, "MESALLIE").
dico("M", 8, "MESANGES").
dico("M", 8, "MESCLUNS").
dico("M", 8, "MESDAMES").
dico("M", 8, "MESOMERE").
dico("M", 8, "MESQUINE").
dico("M", 8, "MESQUINS").
dico("M", 8, "MESSAGER").
dico("M", 8, "MESSAGES").
dico("M", 8, "MESSEANT").
dico("M", 8, "MESSEOIR").
dico("M", 8, "MESSIDOR").
dico("M", 8, "MESSIERA").
dico("M", 8, "MESSIERS").
dico("M", 8, "MESSINES").
dico("M", 8, "MESSIRES").
dico("M", 8, "MESURAGE").
dico("M", 8, "MESURAIS").
dico("M", 8, "MESURAIT").
dico("M", 8, "MESURANT").
dico("M", 8, "MESUREES").
dico("M", 8, "MESURENT").
dico("M", 8, "MESURERA").
dico("M", 8, "MESUREUR").
dico("M", 8, "MESURIEZ").
dico("M", 8, "MESURONS").
dico("M", 8, "MESUSAGE").
dico("M", 8, "MESUSAIS").
dico("M", 8, "MESUSAIT").
dico("M", 8, "MESUSANT").
dico("M", 8, "MESUSENT").
dico("M", 8, "MESUSERA").
dico("M", 8, "MESUSIEZ").
dico("M", 8, "MESUSONS").
dico("M", 8, "METABOLE").
dico("M", 8, "METADONE").
dico("M", 8, "METAIRIE").
dico("M", 8, "METALLOS").
dico("M", 8, "METAMERE").
dico("M", 8, "METAYAGE").
dico("M", 8, "METAYERE").
dico("M", 8, "METAYERS").
dico("M", 8, "METEORES").
dico("M", 8, "METEQUES").
dico("M", 8, "METHANAL").
dico("M", 8, "METHANES").
dico("M", 8, "METHANOL").
dico("M", 8, "METHODES").
dico("M", 8, "METHYLES").
dico("M", 8, "METICALS").
dico("M", 8, "METISSAI").
dico("M", 8, "METISSAS").
dico("M", 8, "METISSAT").
dico("M", 8, "METISSEE").
dico("M", 8, "METISSER").
dico("M", 8, "METISSES").
dico("M", 8, "METISSEZ").
dico("M", 8, "METONIEN").
dico("M", 8, "METRAGES").
dico("M", 8, "METRAMES").
dico("M", 8, "METRASSE").
dico("M", 8, "METRATES").
dico("M", 8, "METRERAI").
dico("M", 8, "METRERAS").
dico("M", 8, "METREREZ").
dico("M", 8, "METREURS").
dico("M", 8, "METREUSE").
dico("M", 8, "METRIONS").
dico("M", 8, "METRIQUE").
dico("M", 8, "METRITES").
dico("M", 8, "METTABLE").
dico("M", 8, "METTEURS").
dico("M", 8, "METTEUSE").
dico("M", 8, "METTIONS").
dico("M", 8, "METTRAIS").
dico("M", 8, "METTRAIT").
dico("M", 8, "METTRIEZ").
dico("M", 8, "METTRONS").
dico("M", 8, "METTRONT").
dico("M", 8, "MEUBLAIS").
dico("M", 8, "MEUBLAIT").
dico("M", 8, "MEUBLANT").
dico("M", 8, "MEUBLEES").
dico("M", 8, "MEUBLENT").
dico("M", 8, "MEUBLERA").
dico("M", 8, "MEUBLIEZ").
dico("M", 8, "MEUBLONS").
dico("M", 8, "MEUGLAIS").
dico("M", 8, "MEUGLAIT").
dico("M", 8, "MEUGLANT").
dico("M", 8, "MEUGLENT").
dico("M", 8, "MEUGLERA").
dico("M", 8, "MEUGLIEZ").
dico("M", 8, "MEUGLONS").
dico("M", 8, "MEULAGES").
dico("M", 8, "MEULAMES").
dico("M", 8, "MEULARDE").
dico("M", 8, "MEULARDS").
dico("M", 8, "MEULASSE").
dico("M", 8, "MEULATES").
dico("M", 8, "MEULERAI").
dico("M", 8, "MEULERAS").
dico("M", 8, "MEULEREZ").
dico("M", 8, "MEULERIE").
dico("M", 8, "MEULETON").
dico("M", 8, "MEULETTE").
dico("M", 8, "MEULEUSE").
dico("M", 8, "MEULIERE").
dico("M", 8, "MEULIERS").
dico("M", 8, "MEULIONS").
dico("M", 8, "MEUNERIE").
dico("M", 8, "MEUNIERE").
dico("M", 8, "MEUNIERS").
dico("M", 8, "MEURETTE").
dico("M", 8, "MEURTIAT").
dico("M", 8, "MEURTRES").
dico("M", 8, "MEURTRIE").
dico("M", 8, "MEURTRIR").
dico("M", 8, "MEURTRIS").
dico("M", 8, "MEURTRIT").
dico("M", 8, "MEUSIENS").
dico("M", 8, "MEVENDES").
dico("M", 8, "MEVENDEZ").
dico("M", 8, "MEVENDIS").
dico("M", 8, "MEVENDIT").
dico("M", 8, "MEVENDRA").
dico("M", 8, "MEVENDRE").
dico("M", 8, "MEVENDUE").
dico("M", 8, "MEVENDUS").
dico("M", 8, "MEVENTES").
dico("M", 8, "MEXICAIN").
dico("M", 8, "MIAULAIS").
dico("M", 8, "MIAULAIT").
dico("M", 8, "MIAULANT").
dico("M", 8, "MIAULENT").
dico("M", 8, "MIAULERA").
dico("M", 8, "MIAULEUR").
dico("M", 8, "MIAULIEZ").
dico("M", 8, "MIAULONS").
dico("M", 8, "MICACEES").
dico("M", 8, "MICANITE").
dico("M", 8, "MICELLES").
dico("M", 8, "MICHETON").
dico("M", 8, "MICMAQUE").
dico("M", 8, "MICROBES").
dico("M", 8, "MICROBUS").
dico("M", 8, "MICROHMS").
dico("M", 8, "MICTIONS").
dico("M", 8, "MIDRASHS").
dico("M", 8, "MIDSHIPS").
dico("M", 8, "MIELLATS").
dico("M", 8, "MIELLEES").
dico("M", 8, "MIELLEUX").
dico("M", 8, "MIELLURE").
dico("M", 8, "MIEVRETE").
dico("M", 8, "MIGNARDA").
dico("M", 8, "MIGNARDE").
dico("M", 8, "MIGNARDS").
dico("M", 8, "MIGNONNE").
dico("M", 8, "MIGNOTAI").
dico("M", 8, "MIGNOTAS").
dico("M", 8, "MIGNOTAT").
dico("M", 8, "MIGNOTEE").
dico("M", 8, "MIGNOTER").
dico("M", 8, "MIGNOTES").
dico("M", 8, "MIGNOTEZ").
dico("M", 8, "MIGRAINE").
dico("M", 8, "MIGRAMES").
dico("M", 8, "MIGRANTE").
dico("M", 8, "MIGRANTS").
dico("M", 8, "MIGRASSE").
dico("M", 8, "MIGRATES").
dico("M", 8, "MIGRERAI").
dico("M", 8, "MIGRERAS").
dico("M", 8, "MIGREREZ").
dico("M", 8, "MIGRIONS").
dico("M", 8, "MIJAUREE").
dico("M", 8, "MIJOTAGE").
dico("M", 8, "MIJOTAIS").
dico("M", 8, "MIJOTAIT").
dico("M", 8, "MIJOTANT").
dico("M", 8, "MIJOTEES").
dico("M", 8, "MIJOTENT").
dico("M", 8, "MIJOTERA").
dico("M", 8, "MIJOTIEZ").
dico("M", 8, "MIJOTONS").
dico("M", 8, "MILADIES").
dico("M", 8, "MILANAIS").
dico("M", 8, "MILANDRE").
dico("M", 8, "MILANEAU").
dico("M", 8, "MILDIOUS").
dico("M", 8, "MILIAIRE").
dico("M", 8, "MILICIEN").
dico("M", 8, "MILITAIS").
dico("M", 8, "MILITAIT").
dico("M", 8, "MILITANT").
dico("M", 8, "MILITENT").
dico("M", 8, "MILITERA").
dico("M", 8, "MILITIEZ").
dico("M", 8, "MILITONS").
dico("M", 8, "MILLAGES").
dico("M", 8, "MILLASSE").
dico("M", 8, "MILLIARD").
dico("M", 8, "MILLIBAR").
dico("M", 8, "MILLIEME").
dico("M", 8, "MILLIERS").
dico("M", 8, "MILLIMES").
dico("M", 8, "MILLIONS").
dico("M", 8, "MILLIREM").
dico("M", 8, "MILONGAS").
dico("M", 8, "MILOUINS").
dico("M", 8, "MIMAIENT").
dico("M", 8, "MIMASSES").
dico("M", 8, "MIMERAIS").
dico("M", 8, "MIMERAIT").
dico("M", 8, "MIMERENT").
dico("M", 8, "MIMERIEZ").
dico("M", 8, "MIMERONS").
dico("M", 8, "MIMERONT").
dico("M", 8, "MIMIQUES").
dico("M", 8, "MIMOSEES").
dico("M", 8, "MINABLES").
dico("M", 8, "MINAIENT").
dico("M", 8, "MINARETS").
dico("M", 8, "MINASSES").
dico("M", 8, "MINAUDAI").
dico("M", 8, "MINAUDAS").
dico("M", 8, "MINAUDAT").
dico("M", 8, "MINAUDER").
dico("M", 8, "MINAUDES").
dico("M", 8, "MINAUDEZ").
dico("M", 8, "MINCEURS").
dico("M", 8, "MINCIMES").
dico("M", 8, "MINCIRAI").
dico("M", 8, "MINCIRAS").
dico("M", 8, "MINCIREZ").
dico("M", 8, "MINCISSE").
dico("M", 8, "MINCITES").
dico("M", 8, "MINCOLET").
dico("M", 8, "MINERAIS").
dico("M", 8, "MINERAIT").
dico("M", 8, "MINERALE").
dico("M", 8, "MINERAUX").
dico("M", 8, "MINERENT").
dico("M", 8, "MINERIEZ").
dico("M", 8, "MINERONS").
dico("M", 8, "MINERONT").
dico("M", 8, "MINERVAL").
dico("M", 8, "MINERVES").
dico("M", 8, "MINETTES").
dico("M", 8, "MINEURES").
dico("M", 8, "MINEUSES").
dico("M", 8, "MINIBARS").
dico("M", 8, "MINICARS").
dico("M", 8, "MINIERES").
dico("M", 8, "MINIGOLF").
dico("M", 8, "MINIJUPE").
dico("M", 8, "MINIMALE").
dico("M", 8, "MINIMANT").
dico("M", 8, "MINIMAUX").
dico("M", 8, "MINIMEXE").
dico("M", 8, "MINIMISA").
dico("M", 8, "MINIMISE").
dico("M", 8, "MINIMUMS").
dico("M", 8, "MINISTRE").
dico("M", 8, "MINITELS").
dico("M", 8, "MINITRIP").
dico("M", 8, "MINOENNE").
dico("M", 8, "MINORAIS").
dico("M", 8, "MINORAIT").
dico("M", 8, "MINORANT").
dico("M", 8, "MINORATS").
dico("M", 8, "MINOREES").
dico("M", 8, "MINORENT").
dico("M", 8, "MINORERA").
dico("M", 8, "MINORIEZ").
dico("M", 8, "MINORISA").
dico("M", 8, "MINORISE").
dico("M", 8, "MINORITE").
dico("M", 8, "MINORONS").
dico("M", 8, "MINOTIER").
dico("M", 8, "MINOUCHA").
dico("M", 8, "MINOUCHE").
dico("M", 8, "MINOUNES").
dico("M", 8, "MINUTAGE").
dico("M", 8, "MINUTAIS").
dico("M", 8, "MINUTAIT").
dico("M", 8, "MINUTANT").
dico("M", 8, "MINUTEES").
dico("M", 8, "MINUTENT").
dico("M", 8, "MINUTERA").
dico("M", 8, "MINUTEUR").
dico("M", 8, "MINUTIER").
dico("M", 8, "MINUTIES").
dico("M", 8, "MINUTIEZ").
dico("M", 8, "MINUTONS").
dico("M", 8, "MIOCENES").
dico("M", 8, "MIQUELET").
dico("M", 8, "MIRACLES").
dico("M", 8, "MIRACULE").
dico("M", 8, "MIRADORS").
dico("M", 8, "MIRAIENT").
dico("M", 8, "MIRASSES").
dico("M", 8, "MIRAUDES").
dico("M", 8, "MIREPOIX").
dico("M", 8, "MIRERAIS").
dico("M", 8, "MIRERAIT").
dico("M", 8, "MIRERENT").
dico("M", 8, "MIRERIEZ").
dico("M", 8, "MIRERONS").
dico("M", 8, "MIRERONT").
dico("M", 8, "MIRETTES").
dico("M", 8, "MIREUSES").
dico("M", 8, "MIRLITON").
dico("M", 8, "MIRMIDON").
dico("M", 8, "MIROITAI").
dico("M", 8, "MIROITAS").
dico("M", 8, "MIROITAT").
dico("M", 8, "MIROITEE").
dico("M", 8, "MIROITER").
dico("M", 8, "MIROITES").
dico("M", 8, "MIROITEZ").
dico("M", 8, "MIRONTON").
dico("M", 8, "MIROTONS").
dico("M", 8, "MISAIENT").
dico("M", 8, "MISAINES").
dico("M", 8, "MISANDRE").
dico("M", 8, "MISASSES").
dico("M", 8, "MISCIBLE").
dico("M", 8, "MISERAIS").
dico("M", 8, "MISERAIT").
dico("M", 8, "MISERENT").
dico("M", 8, "MISERERE").
dico("M", 8, "MISEREUX").
dico("M", 8, "MISERIEZ").
dico("M", 8, "MISERONS").
dico("M", 8, "MISERONT").
dico("M", 8, "MISOGYNE").
dico("M", 8, "MISSILES").
dico("M", 8, "MISSIONS").
dico("M", 8, "MISSIVES").
dico("M", 8, "MISTELLE").
dico("M", 8, "MISTIGRI").
dico("M", 8, "MISTONNE").
dico("M", 8, "MISTRALS").
dico("M", 8, "MISTRESS").
dico("M", 8, "MITAIENT").
dico("M", 8, "MITAINES").
dico("M", 8, "MITASSES").
dico("M", 8, "MITERAIS").
dico("M", 8, "MITERAIT").
dico("M", 8, "MITERENT").
dico("M", 8, "MITERIEZ").
dico("M", 8, "MITERONS").
dico("M", 8, "MITERONT").
dico("M", 8, "MITEUSES").
dico("M", 8, "MITIGEAI").
dico("M", 8, "MITIGEAS").
dico("M", 8, "MITIGEAT").
dico("M", 8, "MITIGEES").
dico("M", 8, "MITIGENT").
dico("M", 8, "MITIGERA").
dico("M", 8, "MITIGEUR").
dico("M", 8, "MITIGIEZ").
dico("M", 8, "MITOGENE").
dico("M", 8, "MITONNAI").
dico("M", 8, "MITONNAS").
dico("M", 8, "MITONNAT").
dico("M", 8, "MITONNEE").
dico("M", 8, "MITONNER").
dico("M", 8, "MITONNES").
dico("M", 8, "MITONNEZ").
dico("M", 8, "MITOYENS").
dico("M", 8, "MITRALES").
dico("M", 8, "MIXAIENT").
dico("M", 8, "MIXASSES").
dico("M", 8, "MIXERAIS").
dico("M", 8, "MIXERAIT").
dico("M", 8, "MIXERENT").
dico("M", 8, "MIXERIEZ").
dico("M", 8, "MIXERONS").
dico("M", 8, "MIXERONT").
dico("M", 8, "MIXTIONS").
dico("M", 8, "MIXTURES").
dico("M", 8, "MNESIQUE").
dico("M", 8, "MOABITES").
dico("M", 8, "MOBILIER").
dico("M", 8, "MOBILISA").
dico("M", 8, "MOBILISE").
dico("M", 8, "MOBILITE").
dico("M", 8, "MOCASSIN").
dico("M", 8, "MOCHARDE").
dico("M", 8, "MOCHARDS").
dico("M", 8, "MOCHETES").
dico("M", 8, "MODALISA").
dico("M", 8, "MODALISE").
dico("M", 8, "MODALITE").
dico("M", 8, "MODELAGE").
dico("M", 8, "MODELAIS").
dico("M", 8, "MODELAIT").
dico("M", 8, "MODELANT").
dico("M", 8, "MODELEES").
dico("M", 8, "MODELENT").
dico("M", 8, "MODELERA").
dico("M", 8, "MODELEUR").
dico("M", 8, "MODELIEZ").
dico("M", 8, "MODELISA").
dico("M", 8, "MODELISE").
dico("M", 8, "MODELONS").
dico("M", 8, "MODENAIS").
dico("M", 8, "MODERAIS").
dico("M", 8, "MODERAIT").
dico("M", 8, "MODERANT").
dico("M", 8, "MODERATO").
dico("M", 8, "MODEREES").
dico("M", 8, "MODERENT").
dico("M", 8, "MODERERA").
dico("M", 8, "MODERIEZ").
dico("M", 8, "MODERNES").
dico("M", 8, "MODERONS").
dico("M", 8, "MODESTES").
dico("M", 8, "MODESTIE").
dico("M", 8, "MODICITE").
dico("M", 8, "MODIFIAI").
dico("M", 8, "MODIFIAS").
dico("M", 8, "MODIFIAT").
dico("M", 8, "MODIFIEE").
dico("M", 8, "MODIFIER").
dico("M", 8, "MODIFIES").
dico("M", 8, "MODIFIEZ").
dico("M", 8, "MODILLON").
dico("M", 8, "MODIQUES").
dico("M", 8, "MODISTES").
dico("M", 8, "MODULAIS").
dico("M", 8, "MODULAIT").
dico("M", 8, "MODULANT").
dico("M", 8, "MODULEES").
dico("M", 8, "MODULENT").
dico("M", 8, "MODULERA").
dico("M", 8, "MODULIEZ").
dico("M", 8, "MODULONS").
dico("M", 8, "MODULORS").
dico("M", 8, "MOELLEUX").
dico("M", 8, "MOELLONS").
dico("M", 8, "MOFETTES").
dico("M", 8, "MOFFLAIS").
dico("M", 8, "MOFFLAIT").
dico("M", 8, "MOFFLANT").
dico("M", 8, "MOFFLEES").
dico("M", 8, "MOFFLENT").
dico("M", 8, "MOFFLERA").
dico("M", 8, "MOFFLIEZ").
dico("M", 8, "MOFFLONS").
dico("M", 8, "MOFLAMES").
dico("M", 8, "MOFLASSE").
dico("M", 8, "MOFLATES").
dico("M", 8, "MOFLERAI").
dico("M", 8, "MOFLERAS").
dico("M", 8, "MOFLEREZ").
dico("M", 8, "MOFLIONS").
dico("M", 8, "MOGETTES").
dico("M", 8, "MOGHOLES").
dico("M", 8, "MOHICANS").
dico("M", 8, "MOIERAIS").
dico("M", 8, "MOIERAIT").
dico("M", 8, "MOIERIEZ").
dico("M", 8, "MOIERONS").
dico("M", 8, "MOIERONT").
dico("M", 8, "MOIGNONS").
dico("M", 8, "MOINDRES").
dico("M", 8, "MOINEAUX").
dico("M", 8, "MOINERIE").
dico("M", 8, "MOIRAGES").
dico("M", 8, "MOIRAMES").
dico("M", 8, "MOIRASSE").
dico("M", 8, "MOIRATES").
dico("M", 8, "MOIRERAI").
dico("M", 8, "MOIRERAS").
dico("M", 8, "MOIREREZ").
dico("M", 8, "MOIREURS").
dico("M", 8, "MOIREUSE").
dico("M", 8, "MOIRIONS").
dico("M", 8, "MOIRURES").
dico("M", 8, "MOISAGES").
dico("M", 8, "MOISAMES").
dico("M", 8, "MOISASSE").
dico("M", 8, "MOISATES").
dico("M", 8, "MOISERAI").
dico("M", 8, "MOISERAS").
dico("M", 8, "MOISEREZ").
dico("M", 8, "MOISIMES").
dico("M", 8, "MOISIONS").
dico("M", 8, "MOISIRAI").
dico("M", 8, "MOISIRAS").
dico("M", 8, "MOISIREZ").
dico("M", 8, "MOISISSE").
dico("M", 8, "MOISITES").
dico("M", 8, "MOISSACS").
dico("M", 8, "MOISSINE").
dico("M", 8, "MOISSONS").
dico("M", 8, "MOITEURS").
dico("M", 8, "MOITIMES").
dico("M", 8, "MOITIRAI").
dico("M", 8, "MOITIRAS").
dico("M", 8, "MOITIREZ").
dico("M", 8, "MOITISSE").
dico("M", 8, "MOITITES").
dico("M", 8, "MOJETTES").
dico("M", 8, "MOLAIRES").
dico("M", 8, "MOLALITE").
dico("M", 8, "MOLARDAI").
dico("M", 8, "MOLARDAS").
dico("M", 8, "MOLARDAT").
dico("M", 8, "MOLARDER").
dico("M", 8, "MOLARDES").
dico("M", 8, "MOLARDEZ").
dico("M", 8, "MOLARITE").
dico("M", 8, "MOLASSES").
dico("M", 8, "MOLDAVES").
dico("M", 8, "MOLECULE").
dico("M", 8, "MOLESTAI").
dico("M", 8, "MOLESTAS").
dico("M", 8, "MOLESTAT").
dico("M", 8, "MOLESTEE").
dico("M", 8, "MOLESTER").
dico("M", 8, "MOLESTES").
dico("M", 8, "MOLESTEZ").
dico("M", 8, "MOLETAGE").
dico("M", 8, "MOLETAIS").
dico("M", 8, "MOLETAIT").
dico("M", 8, "MOLETANT").
dico("M", 8, "MOLETEES").
dico("M", 8, "MOLETIEZ").
dico("M", 8, "MOLETOIR").
dico("M", 8, "MOLETONS").
dico("M", 8, "MOLETTES").
dico("M", 8, "MOLIERES").
dico("M", 8, "MOLLARDA").
dico("M", 8, "MOLLARDE").
dico("M", 8, "MOLLARDS").
dico("M", 8, "MOLLASSE").
dico("M", 8, "MOLLESSE").
dico("M", 8, "MOLLETON").
dico("M", 8, "MOLLETTE").
dico("M", 8, "MOLLIMES").
dico("M", 8, "MOLLIRAI").
dico("M", 8, "MOLLIRAS").
dico("M", 8, "MOLLIREZ").
dico("M", 8, "MOLLISOL").
dico("M", 8, "MOLLISSE").
dico("M", 8, "MOLLITES").
dico("M", 8, "MOLOSSES").
dico("M", 8, "MOLUSSON").
dico("M", 8, "MOMERIES").
dico("M", 8, "MOMIERES").
dico("M", 8, "MOMIFIAI").
dico("M", 8, "MOMIFIAS").
dico("M", 8, "MOMIFIAT").
dico("M", 8, "MOMIFIEE").
dico("M", 8, "MOMIFIER").
dico("M", 8, "MOMIFIES").
dico("M", 8, "MOMIFIEZ").
dico("M", 8, "MONACALE").
dico("M", 8, "MONACAUX").
dico("M", 8, "MONANDRE").
dico("M", 8, "MONARDES").
dico("M", 8, "MONARQUE").
dico("M", 8, "MONAURAL").
dico("M", 8, "MONAZITE").
dico("M", 8, "MONCEAUX").
dico("M", 8, "MONDAINE").
dico("M", 8, "MONDAINS").
dico("M", 8, "MONDAMES").
dico("M", 8, "MONDASSE").
dico("M", 8, "MONDATES").
dico("M", 8, "MONDERAI").
dico("M", 8, "MONDERAS").
dico("M", 8, "MONDEREZ").
dico("M", 8, "MONDIALE").
dico("M", 8, "MONDIAUX").
dico("M", 8, "MONDIONS").
dico("M", 8, "MONERGOL").
dico("M", 8, "MONETISA").
dico("M", 8, "MONETISE").
dico("M", 8, "MONGOLES").
dico("M", 8, "MONIALES").
dico("M", 8, "MONILIAS").
dico("M", 8, "MONISMES").
dico("M", 8, "MONISTES").
dico("M", 8, "MONITEUR").
dico("M", 8, "MONITION").
dico("M", 8, "MONITORS").
dico("M", 8, "MONNAIES").
dico("M", 8, "MONNAYAI").
dico("M", 8, "MONNAYAS").
dico("M", 8, "MONNAYAT").
dico("M", 8, "MONNAYEE").
dico("M", 8, "MONNAYER").
dico("M", 8, "MONNAYES").
dico("M", 8, "MONNAYEZ").
dico("M", 8, "MONOBASE").
dico("M", 8, "MONOBLOC").
dico("M", 8, "MONOBRIN").
dico("M", 8, "MONOCLES").
dico("M", 8, "MONOCYTE").
dico("M", 8, "MONODIES").
dico("M", 8, "MONOECIE").
dico("M", 8, "MONOGAME").
dico("M", 8, "MONOGENE").
dico("M", 8, "MONOIDES").
dico("M", 8, "MONOIQUE").
dico("M", 8, "MONOKINI").
dico("M", 8, "MONOMANE").
dico("M", 8, "MONOMERE").
dico("M", 8, "MONOPLAN").
dico("M", 8, "MONOPOLE").
dico("M", 8, "MONOPOLY").
dico("M", 8, "MONOPRIX").
dico("M", 8, "MONORAIL").
dico("M", 8, "MONORIME").
dico("M", 8, "MONOSKIS").
dico("M", 8, "MONOSOCS").
dico("M", 8, "MONOTONE").
dico("M", 8, "MONOTYPE").
dico("M", 8, "MONOXYDE").
dico("M", 8, "MONOXYLE").
dico("M", 8, "MONSIEUR").
dico("M", 8, "MONSTERA").
dico("M", 8, "MONSTRES").
dico("M", 8, "MONTAGES").
dico("M", 8, "MONTAGNE").
dico("M", 8, "MONTAMES").
dico("M", 8, "MONTANTE").
dico("M", 8, "MONTANTS").
dico("M", 8, "MONTASSE").
dico("M", 8, "MONTATES").
dico("M", 8, "MONTERAI").
dico("M", 8, "MONTERAS").
dico("M", 8, "MONTEREZ").
dico("M", 8, "MONTEURS").
dico("M", 8, "MONTEUSE").
dico("M", 8, "MONTIENS").
dico("M", 8, "MONTIONS").
dico("M", 8, "MONTJOIE").
dico("M", 8, "MONTOIRS").
dico("M", 8, "MONTOISE").
dico("M", 8, "MONTRAIS").
dico("M", 8, "MONTRAIT").
dico("M", 8, "MONTRANT").
dico("M", 8, "MONTREES").
dico("M", 8, "MONTRENT").
dico("M", 8, "MONTRERA").
dico("M", 8, "MONTREUR").
dico("M", 8, "MONTRIEZ").
dico("M", 8, "MONTRONS").
dico("M", 8, "MONTUEUX").
dico("M", 8, "MONTURES").
dico("M", 8, "MONUMENT").
dico("M", 8, "MOQUAMES").
dico("M", 8, "MOQUASSE").
dico("M", 8, "MOQUATES").
dico("M", 8, "MOQUERAI").
dico("M", 8, "MOQUERAS").
dico("M", 8, "MOQUEREZ").
dico("M", 8, "MOQUERIE").
dico("M", 8, "MOQUETTA").
dico("M", 8, "MOQUETTE").
dico("M", 8, "MOQUEURS").
dico("M", 8, "MOQUEUSE").
dico("M", 8, "MOQUIONS").
dico("M", 8, "MORACEES").
dico("M", 8, "MORAILLA").
dico("M", 8, "MORAILLE").
dico("M", 8, "MORAINES").
dico("M", 8, "MORALISA").
dico("M", 8, "MORALISE").
dico("M", 8, "MORALITE").
dico("M", 8, "MORASSES").
dico("M", 8, "MORBAQUE").
dico("M", 8, "MORBIDES").
dico("M", 8, "MORBIERS").
dico("M", 8, "MORCEAUX").
dico("M", 8, "MORCELAI").
dico("M", 8, "MORCELAS").
dico("M", 8, "MORCELAT").
dico("M", 8, "MORCELEE").
dico("M", 8, "MORCELER").
dico("M", 8, "MORCELES").
dico("M", 8, "MORCELEZ").
dico("M", 8, "MORCELLE").
dico("M", 8, "MORDACHE").
dico("M", 8, "MORDANCA").
dico("M", 8, "MORDANCE").
dico("M", 8, "MORDANTE").
dico("M", 8, "MORDANTS").
dico("M", 8, "MORDELLE").
dico("M", 8, "MORDEURS").
dico("M", 8, "MORDEUSE").
dico("M", 8, "MORDICUS").
dico("M", 8, "MORDILLA").
dico("M", 8, "MORDILLE").
dico("M", 8, "MORDIMES").
dico("M", 8, "MORDIONS").
dico("M", 8, "MORDISSE").
dico("M", 8, "MORDITES").
dico("M", 8, "MORDORAI").
dico("M", 8, "MORDORAS").
dico("M", 8, "MORDORAT").
dico("M", 8, "MORDOREE").
dico("M", 8, "MORDORER").
dico("M", 8, "MORDORES").
dico("M", 8, "MORDOREZ").
dico("M", 8, "MORDRAIS").
dico("M", 8, "MORDRAIT").
dico("M", 8, "MORDRIEZ").
dico("M", 8, "MORDRONS").
dico("M", 8, "MORDRONT").
dico("M", 8, "MORELLES").
dico("M", 8, "MORESQUE").
dico("M", 8, "MORFALAI").
dico("M", 8, "MORFALAS").
dico("M", 8, "MORFALAT").
dico("M", 8, "MORFALEE").
dico("M", 8, "MORFALER").
dico("M", 8, "MORFALES").
dico("M", 8, "MORFALEZ").
dico("M", 8, "MORFILAI").
dico("M", 8, "MORFILAS").
dico("M", 8, "MORFILAT").
dico("M", 8, "MORFILEE").
dico("M", 8, "MORFILER").
dico("M", 8, "MORFILES").
dico("M", 8, "MORFILEZ").
dico("M", 8, "MORFLAIS").
dico("M", 8, "MORFLAIT").
dico("M", 8, "MORFLANT").
dico("M", 8, "MORFLEES").
dico("M", 8, "MORFLENT").
dico("M", 8, "MORFLERA").
dico("M", 8, "MORFLIEZ").
dico("M", 8, "MORFLONS").
dico("M", 8, "MORFONDE").
dico("M", 8, "MORFONDS").
dico("M", 8, "MORFONDU").
dico("M", 8, "MORGUAIS").
dico("M", 8, "MORGUAIT").
dico("M", 8, "MORGUANT").
dico("M", 8, "MORGUEES").
dico("M", 8, "MORGUENT").
dico("M", 8, "MORGUERA").
dico("M", 8, "MORGUIEZ").
dico("M", 8, "MORGUONS").
dico("M", 8, "MORIBOND").
dico("M", 8, "MORICAUD").
dico("M", 8, "MORIGENA").
dico("M", 8, "MORIGENE").
dico("M", 8, "MORILLES").
dico("M", 8, "MORILLON").
dico("M", 8, "MORINGAS").
dico("M", 8, "MORISQUE").
dico("M", 8, "MORMONES").
dico("M", 8, "MORNIFLE").
dico("M", 8, "MORONAIS").
dico("M", 8, "MOROSITE").
dico("M", 8, "MORPHEME").
dico("M", 8, "MORPHINE").
dico("M", 8, "MORPHING").
dico("M", 8, "MORPIONS").
dico("M", 8, "MORSURES").
dico("M", 8, "MORTAISA").
dico("M", 8, "MORTAISE").
dico("M", 8, "MORTEAUX").
dico("M", 8, "MORTELLE").
dico("M", 8, "MORTIERS").
dico("M", 8, "MORTIFIA").
dico("M", 8, "MORTIFIE").
dico("M", 8, "MORUTIER").
dico("M", 8, "MORVEUSE").
dico("M", 8, "MOSAIQUE").
dico("M", 8, "MOSAISME").
dico("M", 8, "MOSAISTE").
dico("M", 8, "MOSELLAN").
dico("M", 8, "MOSELLES").
dico("M", 8, "MOSETTES").
dico("M", 8, "MOSQUEES").
dico("M", 8, "MOSTELLE").
dico("M", 8, "MOTARDES").
dico("M", 8, "MOTELLES").
dico("M", 8, "MOTILITE").
dico("M", 8, "MOTIONNA").
dico("M", 8, "MOTIONNE").
dico("M", 8, "MOTIVAIS").
dico("M", 8, "MOTIVAIT").
dico("M", 8, "MOTIVANT").
dico("M", 8, "MOTIVEES").
dico("M", 8, "MOTIVENT").
dico("M", 8, "MOTIVERA").
dico("M", 8, "MOTIVIEZ").
dico("M", 8, "MOTIVONS").
dico("M", 8, "MOTOBALL").
dico("M", 8, "MOTORISA").
dico("M", 8, "MOTORISE").
dico("M", 8, "MOTOSKIS").
dico("M", 8, "MOTRICES").
dico("M", 8, "MOTTAMES").
dico("M", 8, "MOTTASSE").
dico("M", 8, "MOTTATES").
dico("M", 8, "MOTTERAI").
dico("M", 8, "MOTTERAS").
dico("M", 8, "MOTTEREZ").
dico("M", 8, "MOTTIONS").
dico("M", 8, "MOUCHAGE").
dico("M", 8, "MOUCHAIS").
dico("M", 8, "MOUCHAIT").
dico("M", 8, "MOUCHANT").
dico("M", 8, "MOUCHARD").
dico("M", 8, "MOUCHEES").
dico("M", 8, "MOUCHENT").
dico("M", 8, "MOUCHERA").
dico("M", 8, "MOUCHETA").
dico("M", 8, "MOUCHETE").
dico("M", 8, "MOUCHETS").
dico("M", 8, "MOUCHIEZ").
dico("M", 8, "MOUCHOIR").
dico("M", 8, "MOUCHONS").
dico("M", 8, "MOUCHURE").
dico("M", 8, "MOUCLADE").
dico("M", 8, "MOUDRAIS").
dico("M", 8, "MOUDRAIT").
dico("M", 8, "MOUDRIEZ").
dico("M", 8, "MOUDRONS").
dico("M", 8, "MOUDRONT").
dico("M", 8, "MOUETTES").
dico("M", 8, "MOUFETAI").
dico("M", 8, "MOUFETAS").
dico("M", 8, "MOUFETAT").
dico("M", 8, "MOUFETER").
dico("M", 8, "MOUFETES").
dico("M", 8, "MOUFETEZ").
dico("M", 8, "MOUFETTE").
dico("M", 8, "MOUFLAGE").
dico("M", 8, "MOUFLAIS").
dico("M", 8, "MOUFLAIT").
dico("M", 8, "MOUFLANT").
dico("M", 8, "MOUFLEES").
dico("M", 8, "MOUFLENT").
dico("M", 8, "MOUFLERA").
dico("M", 8, "MOUFLETS").
dico("M", 8, "MOUFLIEZ").
dico("M", 8, "MOUFLONS").
dico("M", 8, "MOUFTAIS").
dico("M", 8, "MOUFTAIT").
dico("M", 8, "MOUFTANT").
dico("M", 8, "MOUFTENT").
dico("M", 8, "MOUFTERA").
dico("M", 8, "MOUFTIEZ").
dico("M", 8, "MOUFTONS").
dico("M", 8, "MOUILLAI").
dico("M", 8, "MOUILLAS").
dico("M", 8, "MOUILLAT").
dico("M", 8, "MOUILLEE").
dico("M", 8, "MOUILLER").
dico("M", 8, "MOUILLES").
dico("M", 8, "MOUILLEZ").
dico("M", 8, "MOUILLON").
dico("M", 8, "MOUKERES").
dico("M", 8, "MOULABLE").
dico("M", 8, "MOULAGES").
dico("M", 8, "MOULAMES").
dico("M", 8, "MOULANTE").
dico("M", 8, "MOULANTS").
dico("M", 8, "MOULASSE").
dico("M", 8, "MOULATES").
dico("M", 8, "MOULERAI").
dico("M", 8, "MOULERAS").
dico("M", 8, "MOULEREZ").
dico("M", 8, "MOULEURS").
dico("M", 8, "MOULEUSE").
dico("M", 8, "MOULIERE").
dico("M", 8, "MOULINAI").
dico("M", 8, "MOULINAS").
dico("M", 8, "MOULINAT").
dico("M", 8, "MOULINEE").
dico("M", 8, "MOULINER").
dico("M", 8, "MOULINES").
dico("M", 8, "MOULINET").
dico("M", 8, "MOULINEZ").
dico("M", 8, "MOULIONS").
dico("M", 8, "MOULOUDS").
dico("M", 8, "MOULUMES").
dico("M", 8, "MOULURAI").
dico("M", 8, "MOULURAS").
dico("M", 8, "MOULURAT").
dico("M", 8, "MOULUREE").
dico("M", 8, "MOULURER").
dico("M", 8, "MOULURES").
dico("M", 8, "MOULUREZ").
dico("M", 8, "MOULUSSE").
dico("M", 8, "MOULUTES").
dico("M", 8, "MOUMOUTE").
dico("M", 8, "MOUQUERE").
dico("M", 8, "MOURANTE").
dico("M", 8, "MOURANTS").
dico("M", 8, "MOURIONS").
dico("M", 8, "MOUROIRS").
dico("M", 8, "MOURRAIS").
dico("M", 8, "MOURRAIT").
dico("M", 8, "MOURRIEZ").
dico("M", 8, "MOURRONS").
dico("M", 8, "MOURRONT").
dico("M", 8, "MOURUMES").
dico("M", 8, "MOURUSSE").
dico("M", 8, "MOURUTES").
dico("M", 8, "MOUSQUET").
dico("M", 8, "MOUSSAGE").
dico("M", 8, "MOUSSAIS").
dico("M", 8, "MOUSSAIT").
dico("M", 8, "MOUSSAKA").
dico("M", 8, "MOUSSANT").
dico("M", 8, "MOUSSEAU").
dico("M", 8, "MOUSSEES").
dico("M", 8, "MOUSSENT").
dico("M", 8, "MOUSSERA").
dico("M", 8, "MOUSSEUX").
dico("M", 8, "MOUSSIEZ").
dico("M", 8, "MOUSSOIR").
dico("M", 8, "MOUSSONS").
dico("M", 8, "MOUSSOTS").
dico("M", 8, "MOUSSUES").
dico("M", 8, "MOUSTIER").
dico("M", 8, "MOUTARDA").
dico("M", 8, "MOUTARDE").
dico("M", 8, "MOUTARDS").
dico("M", 8, "MOUTIERS").
dico("M", 8, "MOUTONNA").
dico("M", 8, "MOUTONNE").
dico("M", 8, "MOUTURES").
dico("M", 8, "MOUVANCE").
dico("M", 8, "MOUVANTE").
dico("M", 8, "MOUVANTS").
dico("M", 8, "MOUVETTE").
dico("M", 8, "MOUVIONS").
dico("M", 8, "MOUVRAIS").
dico("M", 8, "MOUVRAIT").
dico("M", 8, "MOUVRIEZ").
dico("M", 8, "MOUVRONS").
dico("M", 8, "MOUVRONT").
dico("M", 8, "MOVIOLAS").
dico("M", 8, "MOYAIENT").
dico("M", 8, "MOYASSES").
dico("M", 8, "MOYENNAI").
dico("M", 8, "MOYENNAS").
dico("M", 8, "MOYENNAT").
dico("M", 8, "MOYENNEE").
dico("M", 8, "MOYENNER").
dico("M", 8, "MOYENNES").
dico("M", 8, "MOYENNEZ").
dico("M", 8, "MOYERENT").
dico("M", 8, "MOYETTES").
dico("M", 8, "MOZABITE").
dico("M", 8, "MOZARABE").
dico("M", 8, "MOZETTES").
dico("M", 8, "MUASSENT").
dico("M", 8, "MUASSIEZ").
dico("M", 8, "MUCHAMES").
dico("M", 8, "MUCHASSE").
dico("M", 8, "MUCHATES").
dico("M", 8, "MUCHERAI").
dico("M", 8, "MUCHERAS").
dico("M", 8, "MUCHEREZ").
dico("M", 8, "MUCHIONS").
dico("M", 8, "MUCILAGE").
dico("M", 8, "MUCORALE").
dico("M", 8, "MUCOSITE").
dico("M", 8, "MUDEJARE").
dico("M", 8, "MUDEJARS").
dico("M", 8, "MUERIONS").
dico("M", 8, "MUEZZINS").
dico("M", 8, "MUFLERIE").
dico("M", 8, "MUFLIERS").
dico("M", 8, "MUGIRAIS").
dico("M", 8, "MUGIRAIT").
dico("M", 8, "MUGIRENT").
dico("M", 8, "MUGIRIEZ").
dico("M", 8, "MUGIRONS").
dico("M", 8, "MUGIRONT").
dico("M", 8, "MUGISSES").
dico("M", 8, "MUGISSEZ").
dico("M", 8, "MULARDES").
dico("M", 8, "MULASSES").
dico("M", 8, "MULATRES").
dico("M", 8, "MULETIER").
dico("M", 8, "MULETTES").
dico("M", 8, "MULSIONS").
dico("M", 8, "MULTIPLE").
dico("M", 8, "MULTISOC").
dico("M", 8, "MUNICIPE").
dico("M", 8, "MUNIRAIS").
dico("M", 8, "MUNIRAIT").
dico("M", 8, "MUNIRENT").
dico("M", 8, "MUNIRIEZ").
dico("M", 8, "MUNIRONS").
dico("M", 8, "MUNIRONT").
dico("M", 8, "MUNISSES").
dico("M", 8, "MUNISSEZ").
dico("M", 8, "MUNITION").
dico("M", 8, "MUNSTERS").
dico("M", 8, "MUNTJACS").
dico("M", 8, "MUQARNAS").
dico("M", 8, "MUQUEUSE").
dico("M", 8, "MURAIENT").
dico("M", 8, "MURAILLA").
dico("M", 8, "MURAILLE").
dico("M", 8, "MURASSES").
dico("M", 8, "MUREMENT").
dico("M", 8, "MURENIDE").
dico("M", 8, "MURERAIE").
dico("M", 8, "MURERAIS").
dico("M", 8, "MURERAIT").
dico("M", 8, "MURERENT").
dico("M", 8, "MURERIEZ").
dico("M", 8, "MURERONS").
dico("M", 8, "MURERONT").
dico("M", 8, "MURETINS").
dico("M", 8, "MURETTES").
dico("M", 8, "MURIATES").
dico("M", 8, "MURIRAIS").
dico("M", 8, "MURIRAIT").
dico("M", 8, "MURIRENT").
dico("M", 8, "MURIRIEZ").
dico("M", 8, "MURIRONS").
dico("M", 8, "MURIRONT").
dico("M", 8, "MURISSES").
dico("M", 8, "MURISSEZ").
dico("M", 8, "MURMURAI").
dico("M", 8, "MURMURAS").
dico("M", 8, "MURMURAT").
dico("M", 8, "MURMUREE").
dico("M", 8, "MURMURER").
dico("M", 8, "MURMURES").
dico("M", 8, "MURMUREZ").
dico("M", 8, "MURRHINE").
dico("M", 8, "MURRHINS").
dico("M", 8, "MUSACEES").
dico("M", 8, "MUSAGETE").
dico("M", 8, "MUSAIENT").
dico("M", 8, "MUSARDAI").
dico("M", 8, "MUSARDAS").
dico("M", 8, "MUSARDAT").
dico("M", 8, "MUSARDER").
dico("M", 8, "MUSARDES").
dico("M", 8, "MUSARDEZ").
dico("M", 8, "MUSASSES").
dico("M", 8, "MUSCADES").
dico("M", 8, "MUSCADET").
dico("M", 8, "MUSCADIN").
dico("M", 8, "MUSCARIS").
dico("M", 8, "MUSCATES").
dico("M", 8, "MUSCIDES").
dico("M", 8, "MUSCINAL").
dico("M", 8, "MUSCINEE").
dico("M", 8, "MUSCLAIS").
dico("M", 8, "MUSCLAIT").
dico("M", 8, "MUSCLANT").
dico("M", 8, "MUSCLEES").
dico("M", 8, "MUSCLENT").
dico("M", 8, "MUSCLERA").
dico("M", 8, "MUSCLIEZ").
dico("M", 8, "MUSCLONS").
dico("M", 8, "MUSEALES").
dico("M", 8, "MUSEIFIA").
dico("M", 8, "MUSEIFIE").
dico("M", 8, "MUSELAGE").
dico("M", 8, "MUSELAIS").
dico("M", 8, "MUSELAIT").
dico("M", 8, "MUSELANT").
dico("M", 8, "MUSELEES").
dico("M", 8, "MUSELETS").
dico("M", 8, "MUSELIEZ").
dico("M", 8, "MUSELLES").
dico("M", 8, "MUSELONS").
dico("M", 8, "MUSERAIS").
dico("M", 8, "MUSERAIT").
dico("M", 8, "MUSERENT").
dico("M", 8, "MUSERIEZ").
dico("M", 8, "MUSERONS").
dico("M", 8, "MUSERONT").
dico("M", 8, "MUSETTES").
dico("M", 8, "MUSICALE").
dico("M", 8, "MUSICALS").
dico("M", 8, "MUSICAUX").
dico("M", 8, "MUSICIEN").
dico("M", 8, "MUSIQUAI").
dico("M", 8, "MUSIQUAS").
dico("M", 8, "MUSIQUAT").
dico("M", 8, "MUSIQUEE").
dico("M", 8, "MUSIQUER").
dico("M", 8, "MUSIQUES").
dico("M", 8, "MUSIQUEZ").
dico("M", 8, "MUSQUAIS").
dico("M", 8, "MUSQUAIT").
dico("M", 8, "MUSQUANT").
dico("M", 8, "MUSQUEES").
dico("M", 8, "MUSQUENT").
dico("M", 8, "MUSQUERA").
dico("M", 8, "MUSQUIEZ").
dico("M", 8, "MUSQUONS").
dico("M", 8, "MUSSAMES").
dico("M", 8, "MUSSASSE").
dico("M", 8, "MUSSATES").
dico("M", 8, "MUSSERAI").
dico("M", 8, "MUSSERAS").
dico("M", 8, "MUSSEREZ").
dico("M", 8, "MUSSIONS").
dico("M", 8, "MUSSIVES").
dico("M", 8, "MUSTANGS").
dico("M", 8, "MUSULMAN").
dico("M", 8, "MUTABLES").
dico("M", 8, "MUTAGENE").
dico("M", 8, "MUTAIENT").
dico("M", 8, "MUTANTES").
dico("M", 8, "MUTASSES").
dico("M", 8, "MUTATEUR").
dico("M", 8, "MUTATION").
dico("M", 8, "MUTERAIS").
dico("M", 8, "MUTERAIT").
dico("M", 8, "MUTERENT").
dico("M", 8, "MUTERIEZ").
dico("M", 8, "MUTERONS").
dico("M", 8, "MUTERONT").
dico("M", 8, "MUTILAIS").
dico("M", 8, "MUTILAIT").
dico("M", 8, "MUTILANT").
dico("M", 8, "MUTILEES").
dico("M", 8, "MUTILENT").
dico("M", 8, "MUTILERA").
dico("M", 8, "MUTILIEZ").
dico("M", 8, "MUTILONS").
dico("M", 8, "MUTINAIS").
dico("M", 8, "MUTINAIT").
dico("M", 8, "MUTINANT").
dico("M", 8, "MUTINEES").
dico("M", 8, "MUTINENT").
dico("M", 8, "MUTINERA").
dico("M", 8, "MUTINIEZ").
dico("M", 8, "MUTINONS").
dico("M", 8, "MUTIQUES").
dico("M", 8, "MUTISMES").
dico("M", 8, "MUTUELLE").
dico("M", 8, "MYALGIES").
dico("M", 8, "MYATONIE").
dico("M", 8, "MYCELIEN").
dico("M", 8, "MYCELIUM").
dico("M", 8, "MYCENIEN").
dico("M", 8, "MYCETOME").
dico("M", 8, "MYDRIASE").
dico("M", 8, "MYELINES").
dico("M", 8, "MYELITES").
dico("M", 8, "MYELOIDE").
dico("M", 8, "MYELOMES").
dico("M", 8, "MYLONITE").
dico("M", 8, "MYOCARDE").
dico("M", 8, "MYOLOGIE").
dico("M", 8, "MYOPATHE").
dico("M", 8, "MYOSINES").
dico("M", 8, "MYOSITES").
dico("M", 8, "MYOSOTIS").
dico("M", 8, "MYOTIQUE").
dico("M", 8, "MYRIADES").
dico("M", 8, "MYRMIDON").
dico("M", 8, "MYROSINE").
dico("M", 8, "MYROXYLE").
dico("M", 8, "MYRTACEE").
dico("M", 8, "MYRTALES").
dico("M", 8, "MYRTILLE").
dico("M", 8, "MYSIDACE").
dico("M", 8, "MYSTERES").
dico("M", 8, "MYSTIFIA").
dico("M", 8, "MYSTIFIE").
dico("M", 8, "MYSTIQUE").
dico("M", 8, "MYTHIFIA").
dico("M", 8, "MYTHIFIE").
dico("M", 8, "MYTHIQUE").
dico("M", 8, "MYTILIDE").
dico("M", 8, "MZABITES").
