dico("N", 10, "NABATEENNE").
dico("N", 10, "NACRASSENT").
dico("N", 10, "NACRASSIEZ").
dico("N", 10, "NACRERIONS").
dico("N", 10, "NAGEASSENT").
dico("N", 10, "NAGEASSIEZ").
dico("N", 10, "NAGEOTAMES").
dico("N", 10, "NAGEOTASSE").
dico("N", 10, "NAGEOTATES").
dico("N", 10, "NAGEOTERAI").
dico("N", 10, "NAGEOTERAS").
dico("N", 10, "NAGEOTEREZ").
dico("N", 10, "NAGEOTIONS").
dico("N", 10, "NAGERAIENT").
dico("N", 10, "NAIADACEES").
dico("N", 10, "NAIROBIENS").
dico("N", 10, "NAISSAIENT").
dico("N", 10, "NAISSANCES").
dico("N", 10, "NAISSANTES").
dico("N", 10, "NAITRAIENT").
dico("N", 10, "NAMIBIENNE").
dico("N", 10, "NAMUROISES").
dico("N", 10, "NANCEIENNE").
dico("N", 10, "NANDROLONE").
dico("N", 10, "NANIFIAMES").
dico("N", 10, "NANIFIASSE").
dico("N", 10, "NANIFIATES").
dico("N", 10, "NANIFIERAI").
dico("N", 10, "NANIFIERAS").
dico("N", 10, "NANIFIEREZ").
dico("N", 10, "NANIFIIONS").
dico("N", 10, "NANISAIENT").
dico("N", 10, "NANISASSES").
dico("N", 10, "NANISERAIS").
dico("N", 10, "NANISERAIT").
dico("N", 10, "NANISERENT").
dico("N", 10, "NANISERIEZ").
dico("N", 10, "NANISERONS").
dico("N", 10, "NANISERONT").
dico("N", 10, "NANOFARADS").
dico("N", 10, "NANOMETRES").
dico("N", 10, "NANORESEAU").
dico("N", 10, "NANTERRIEN").
dico("N", 10, "NANTERROIS").
dico("N", 10, "NANTIRIONS").
dico("N", 10, "NANTISSAIS").
dico("N", 10, "NANTISSAIT").
dico("N", 10, "NANTISSANT").
dico("N", 10, "NANTISSENT").
dico("N", 10, "NANTISSIEZ").
dico("N", 10, "NANTISSONS").
dico("N", 10, "NAPHTALENE").
dico("N", 10, "NAPHTALINE").
dico("N", 10, "NAPOLITAIN").
dico("N", 10, "NAPPASSENT").
dico("N", 10, "NAPPASSIEZ").
dico("N", 10, "NAPPERIONS").
dico("N", 10, "NAQUISSENT").
dico("N", 10, "NAQUISSIEZ").
dico("N", 10, "NARBONNAIS").
dico("N", 10, "NARCOMANES").
dico("N", 10, "NARCOTINES").
dico("N", 10, "NARCOTIQUE").
dico("N", 10, "NARCOTISME").
dico("N", 10, "NARGHILEHS").
dico("N", 10, "NARGUAIENT").
dico("N", 10, "NARGUASSES").
dico("N", 10, "NARGUERAIS").
dico("N", 10, "NARGUERAIT").
dico("N", 10, "NARGUERENT").
dico("N", 10, "NARGUERIEZ").
dico("N", 10, "NARGUERONS").
dico("N", 10, "NARGUERONT").
dico("N", 10, "NARQUOISES").
dico("N", 10, "NARRASSENT").
dico("N", 10, "NARRASSIEZ").
dico("N", 10, "NARRATEURS").
dico("N", 10, "NARRATIONS").
dico("N", 10, "NARRATIVES").
dico("N", 10, "NARRATRICE").
dico("N", 10, "NARRERIONS").
dico("N", 10, "NASALISAIS").
dico("N", 10, "NASALISAIT").
dico("N", 10, "NASALISANT").
dico("N", 10, "NASALISEES").
dico("N", 10, "NASALISENT").
dico("N", 10, "NASALISERA").
dico("N", 10, "NASALISIEZ").
dico("N", 10, "NASALISONS").
dico("N", 10, "NASILLAMES").
dico("N", 10, "NASILLARDE").
dico("N", 10, "NASILLARDS").
dico("N", 10, "NASILLASSE").
dico("N", 10, "NASILLATES").
dico("N", 10, "NASILLERAI").
dico("N", 10, "NASILLERAS").
dico("N", 10, "NASILLEREZ").
dico("N", 10, "NASILLEURS").
dico("N", 10, "NASILLEUSE").
dico("N", 10, "NASILLIONS").
dico("N", 10, "NASONNAMES").
dico("N", 10, "NASONNASSE").
dico("N", 10, "NASONNATES").
dico("N", 10, "NASONNERAI").
dico("N", 10, "NASONNERAS").
dico("N", 10, "NASONNEREZ").
dico("N", 10, "NASONNIONS").
dico("N", 10, "NATALISTES").
dico("N", 10, "NATATOIRES").
dico("N", 10, "NATIONALES").
dico("N", 10, "NATIVEMENT").
dico("N", 10, "NATIVISMES").
dico("N", 10, "NATIVISTES").
dico("N", 10, "NATOUFIENS").
dico("N", 10, "NATRONITES").
dico("N", 10, "NATTASSENT").
dico("N", 10, "NATTASSIEZ").
dico("N", 10, "NATTERIONS").
dico("N", 10, "NATURALISA").
dico("N", 10, "NATURALISE").
dico("N", 10, "NATURALITE").
dico("N", 10, "NATURELLES").
dico("N", 10, "NATURISMES").
dico("N", 10, "NATURISTES").
dico("N", 10, "NAUFRAGEAI").
dico("N", 10, "NAUFRAGEAS").
dico("N", 10, "NAUFRAGEAT").
dico("N", 10, "NAUFRAGEES").
dico("N", 10, "NAUFRAGENT").
dico("N", 10, "NAUFRAGERA").
dico("N", 10, "NAUFRAGEUR").
dico("N", 10, "NAUFRAGIEZ").
dico("N", 10, "NAUMACHIES").
dico("N", 10, "NAUPATHIES").
dico("N", 10, "NAUSEABOND").
dico("N", 10, "NAUSEEUSES").
dico("N", 10, "NAUTONIERE").
dico("N", 10, "NAUTONIERS").
dico("N", 10, "NAVARRAISE").
dico("N", 10, "NAVARRINES").
dico("N", 10, "NAVETTAMES").
dico("N", 10, "NAVETTASSE").
dico("N", 10, "NAVETTATES").
dico("N", 10, "NAVETTERAI").
dico("N", 10, "NAVETTERAS").
dico("N", 10, "NAVETTEREZ").
dico("N", 10, "NAVETTEURS").
dico("N", 10, "NAVETTEUSE").
dico("N", 10, "NAVETTIONS").
dico("N", 10, "NAVICELLES").
dico("N", 10, "NAVIGABLES").
dico("N", 10, "NAVIGANTES").
dico("N", 10, "NAVIGATEUR").
dico("N", 10, "NAVIGATION").
dico("N", 10, "NAVIGUAMES").
dico("N", 10, "NAVIGUASSE").
dico("N", 10, "NAVIGUATES").
dico("N", 10, "NAVIGUERAI").
dico("N", 10, "NAVIGUERAS").
dico("N", 10, "NAVIGUEREZ").
dico("N", 10, "NAVIGUIONS").
dico("N", 10, "NAVIPLANES").
dico("N", 10, "NAVISPHERE").
dico("N", 10, "NAVRASSENT").
dico("N", 10, "NAVRASSIEZ").
dico("N", 10, "NAVREMENTS").
dico("N", 10, "NAVRERIONS").
dico("N", 10, "NAZAREENNE").
dico("N", 10, "NAZILLONNE").
dico("N", 10, "NEANTISAIS").
dico("N", 10, "NEANTISAIT").
dico("N", 10, "NEANTISANT").
dico("N", 10, "NEANTISEES").
dico("N", 10, "NEANTISENT").
dico("N", 10, "NEANTISERA").
dico("N", 10, "NEANTISIEZ").
dico("N", 10, "NEANTISONS").
dico("N", 10, "NEBULEUSES").
dico("N", 10, "NEBULISAIS").
dico("N", 10, "NEBULISAIT").
dico("N", 10, "NEBULISANT").
dico("N", 10, "NEBULISEES").
dico("N", 10, "NEBULISENT").
dico("N", 10, "NEBULISERA").
dico("N", 10, "NEBULISEUR").
dico("N", 10, "NEBULISIEZ").
dico("N", 10, "NEBULISONS").
dico("N", 10, "NEBULOSITE").
dico("N", 10, "NECESSAIRE").
dico("N", 10, "NECESSITAI").
dico("N", 10, "NECESSITAS").
dico("N", 10, "NECESSITAT").
dico("N", 10, "NECESSITEE").
dico("N", 10, "NECESSITER").
dico("N", 10, "NECESSITES").
dico("N", 10, "NECESSITEZ").
dico("N", 10, "NECROBIOSE").
dico("N", 10, "NECROLOGES").
dico("N", 10, "NECROLOGIE").
dico("N", 10, "NECROLOGUE").
dico("N", 10, "NECROMANTE").
dico("N", 10, "NECROMANTS").
dico("N", 10, "NECROPHAGE").
dico("N", 10, "NECROPHILE").
dico("N", 10, "NECROPHOBE").
dico("N", 10, "NECROPHORE").
dico("N", 10, "NECROPOLES").
dico("N", 10, "NECROPSIES").
dico("N", 10, "NECROSAMES").
dico("N", 10, "NECROSASSE").
dico("N", 10, "NECROSATES").
dico("N", 10, "NECROSERAI").
dico("N", 10, "NECROSERAS").
dico("N", 10, "NECROSEREZ").
dico("N", 10, "NECROSIONS").
dico("N", 10, "NECROSIQUE").
dico("N", 10, "NECROTIQUE").
dico("N", 10, "NECTARINES").
dico("N", 10, "NEGATIVITE").
dico("N", 10, "NEGATRICES").
dico("N", 10, "NEGLIGEAIS").
dico("N", 10, "NEGLIGEAIT").
dico("N", 10, "NEGLIGEANT").
dico("N", 10, "NEGLIGENCE").
dico("N", 10, "NEGLIGENTE").
dico("N", 10, "NEGLIGENTS").
dico("N", 10, "NEGLIGEONS").
dico("N", 10, "NEGLIGERAI").
dico("N", 10, "NEGLIGERAS").
dico("N", 10, "NEGLIGEREZ").
dico("N", 10, "NEGLIGIONS").
dico("N", 10, "NEGOCIABLE").
dico("N", 10, "NEGOCIAMES").
dico("N", 10, "NEGOCIANTE").
dico("N", 10, "NEGOCIANTS").
dico("N", 10, "NEGOCIASSE").
dico("N", 10, "NEGOCIATES").
dico("N", 10, "NEGOCIERAI").
dico("N", 10, "NEGOCIERAS").
dico("N", 10, "NEGOCIEREZ").
dico("N", 10, "NEGOCIIONS").
dico("N", 10, "NEGRILLONS").
dico("N", 10, "NEGRITUDES").
dico("N", 10, "NEIGEOTAIT").
dico("N", 10, "NEIGEOTERA").
dico("N", 10, "NEMATIQUES").
dico("N", 10, "NEMATOCERE").
dico("N", 10, "NEMERTIENS").
dico("N", 10, "NEOBLASTES").
dico("N", 10, "NEOCOMIENS").
dico("N", 10, "NEOFORMEES").
dico("N", 10, "NEOGRECQUE").
dico("N", 10, "NEOLIBERAL").
dico("N", 10, "NEOLOCALES").
dico("N", 10, "NEOLOGIQUE").
dico("N", 10, "NEOLOGISME").
dico("N", 10, "NEOMYCINES").
dico("N", 10, "NEONATALES").
dico("N", 10, "NEONAZISME").
dico("N", 10, "NEOPILINAS").
dico("N", 10, "NEOPLASIES").
dico("N", 10, "NEOPLASMES").
dico("N", 10, "NEOPLASTIE").
dico("N", 10, "NEOPROMUES").
dico("N", 10, "NEORURALES").
dico("N", 10, "NEOTENIQUE").
dico("N", 10, "NEOZOIQUES").
dico("N", 10, "NEPALAISES").
dico("N", 10, "NEPERIENNE").
dico("N", 10, "NEPHELINES").
dico("N", 10, "NEPHELIONS").
dico("N", 10, "NEPHRIDIES").
dico("N", 10, "NEPOTISMES").
dico("N", 10, "NEPTUNIENS").
dico("N", 10, "NEPTUNISME").
dico("N", 10, "NEPTUNIUMS").
dico("N", 10, "NERITIQUES").
dico("N", 10, "NERONIENNE").
dico("N", 10, "NERVATIONS").
dico("N", 10, "NERVOSISME").
dico("N", 10, "NERVOSITES").
dico("N", 10, "NERVURAGES").
dico("N", 10, "NERVURAMES").
dico("N", 10, "NERVURASSE").
dico("N", 10, "NERVURATES").
dico("N", 10, "NERVURERAI").
dico("N", 10, "NERVURERAS").
dico("N", 10, "NERVUREREZ").
dico("N", 10, "NERVURIONS").
dico("N", 10, "NESTORIENS").
dico("N", 10, "NETTOIERAI").
dico("N", 10, "NETTOIERAS").
dico("N", 10, "NETTOIEREZ").
dico("N", 10, "NETTOYABLE").
dico("N", 10, "NETTOYAGES").
dico("N", 10, "NETTOYAMES").
dico("N", 10, "NETTOYANTE").
dico("N", 10, "NETTOYANTS").
dico("N", 10, "NETTOYASSE").
dico("N", 10, "NETTOYATES").
dico("N", 10, "NETTOYEURS").
dico("N", 10, "NETTOYEUSE").
dico("N", 10, "NETTOYIONS").
dico("N", 10, "NEUCHATELS").
dico("N", 10, "NEUFCHATEL").
dico("N", 10, "NEUMATIQUE").
dico("N", 10, "NEURINOMES").
dico("N", 10, "NEUROLOGIE").
dico("N", 10, "NEUROLOGUE").
dico("N", 10, "NEURONALES").
dico("N", 10, "NEURONIQUE").
dico("N", 10, "NEUROTOMIE").
dico("N", 10, "NEUROTONIE").
dico("N", 10, "NEUROTROPE").
dico("N", 10, "NEUTRALISA").
dico("N", 10, "NEUTRALISE").
dico("N", 10, "NEUTRALITE").
dico("N", 10, "NEVERSOISE").
dico("N", 10, "NEVICIENNE").
dico("N", 10, "NEVRALGIES").
dico("N", 10, "NEVRILEMES").
dico("N", 10, "NEVRITIQUE").
dico("N", 10, "NEVROGLIES").
dico("N", 10, "NEVROPATHE").
dico("N", 10, "NEVROPTERE").
dico("N", 10, "NEVROSIQUE").
dico("N", 10, "NEVROTIQUE").
dico("N", 10, "NEVROTOMIE").
dico("N", 10, "NEWTONIENS").
dico("N", 10, "NIAISAIENT").
dico("N", 10, "NIAISASSES").
dico("N", 10, "NIAISEMENT").
dico("N", 10, "NIAISERAIS").
dico("N", 10, "NIAISERAIT").
dico("N", 10, "NIAISERENT").
dico("N", 10, "NIAISERIES").
dico("N", 10, "NIAISERIEZ").
dico("N", 10, "NIAISERONS").
dico("N", 10, "NIAISERONT").
dico("N", 10, "NIAISEUSES").
dico("N", 10, "NIAMEYENNE").
dico("N", 10, "NICHASSENT").
dico("N", 10, "NICHASSIEZ").
dico("N", 10, "NICHERIONS").
dico("N", 10, "NICKELAGES").
dico("N", 10, "NICKELAMES").
dico("N", 10, "NICKELASSE").
dico("N", 10, "NICKELATES").
dico("N", 10, "NICKELINES").
dico("N", 10, "NICKELIONS").
dico("N", 10, "NICKELLENT").
dico("N", 10, "NICKELLERA").
dico("N", 10, "NICKELURES").
dico("N", 10, "NICOLAISME").
dico("N", 10, "NICOLAITES").
dico("N", 10, "NICOSIENNE").
dico("N", 10, "NICOTISMES").
dico("N", 10, "NICTATIONS").
dico("N", 10, "NICTITANTE").
dico("N", 10, "NICTITANTS").
dico("N", 10, "NIDIFIAMES").
dico("N", 10, "NIDIFIASSE").
dico("N", 10, "NIDIFIATES").
dico("N", 10, "NIDIFIERAI").
dico("N", 10, "NIDIFIERAS").
dico("N", 10, "NIDIFIEREZ").
dico("N", 10, "NIDIFIIONS").
dico("N", 10, "NIDOREUSES").
dico("N", 10, "NIDWALDIEN").
dico("N", 10, "NIELLAIENT").
dico("N", 10, "NIELLASSES").
dico("N", 10, "NIELLERAIS").
dico("N", 10, "NIELLERAIT").
dico("N", 10, "NIELLERENT").
dico("N", 10, "NIELLERIEZ").
dico("N", 10, "NIELLERONS").
dico("N", 10, "NIELLERONT").
dico("N", 10, "NIELLEUSES").
dico("N", 10, "NIGAUDERIE").
dico("N", 10, "NIGERIANES").
dico("N", 10, "NIGERIENNE").
dico("N", 10, "NIGRITIQUE").
dico("N", 10, "NIHILISMES").
dico("N", 10, "NIHILISTES").
dico("N", 10, "NILOTIQUES").
dico("N", 10, "NILPOTENTE").
dico("N", 10, "NILPOTENTS").
dico("N", 10, "NIMBASSENT").
dico("N", 10, "NIMBASSIEZ").
dico("N", 10, "NIMBERIONS").
dico("N", 10, "NIORTAISES").
dico("N", 10, "NIPPASSENT").
dico("N", 10, "NIPPASSIEZ").
dico("N", 10, "NIPPERIONS").
dico("N", 10, "NIQUASSENT").
dico("N", 10, "NIQUASSIEZ").
dico("N", 10, "NIQUERIONS").
dico("N", 10, "NITESCENCE").
dico("N", 10, "NITRASSENT").
dico("N", 10, "NITRASSIEZ").
dico("N", 10, "NITRATAMES").
dico("N", 10, "NITRATASSE").
dico("N", 10, "NITRATATES").
dico("N", 10, "NITRATERAI").
dico("N", 10, "NITRATERAS").
dico("N", 10, "NITRATEREZ").
dico("N", 10, "NITRATIONS").
dico("N", 10, "NITRERIONS").
dico("N", 10, "NITRIFIAIS").
dico("N", 10, "NITRIFIAIT").
dico("N", 10, "NITRIFIANT").
dico("N", 10, "NITRIFIEES").
dico("N", 10, "NITRIFIENT").
dico("N", 10, "NITRIFIERA").
dico("N", 10, "NITRIFIIEZ").
dico("N", 10, "NITRIFIONS").
dico("N", 10, "NITROGENES").
dico("N", 10, "NITROPHILE").
dico("N", 10, "NITROSAMES").
dico("N", 10, "NITROSASSE").
dico("N", 10, "NITROSATES").
dico("N", 10, "NITROSERAI").
dico("N", 10, "NITROSERAS").
dico("N", 10, "NITROSEREZ").
dico("N", 10, "NITROSIONS").
dico("N", 10, "NITROSYLES").
dico("N", 10, "NITRURAMES").
dico("N", 10, "NITRURASSE").
dico("N", 10, "NITRURATES").
dico("N", 10, "NITRURERAI").
dico("N", 10, "NITRURERAS").
dico("N", 10, "NITRUREREZ").
dico("N", 10, "NITRURIONS").
dico("N", 10, "NIVELAIENT").
dico("N", 10, "NIVELASSES").
dico("N", 10, "NIVELERENT").
dico("N", 10, "NIVELETTES").
dico("N", 10, "NIVELEUSES").
dico("N", 10, "NIVELLERAI").
dico("N", 10, "NIVELLERAS").
dico("N", 10, "NIVELLEREZ").
dico("N", 10, "NIVERNAISE").
dico("N", 10, "NIVOLOGUES").
dico("N", 10, "NOBILIAIRE").
dico("N", 10, "NOBLAILLON").
dico("N", 10, "NOCASSIONS").
dico("N", 10, "NOCERAIENT").
dico("N", 10, "NOCTAMBULE").
dico("N", 10, "NOCTIFLORE").
dico("N", 10, "NOCTILUQUE").
dico("N", 10, "NOCTUELLES").
dico("N", 10, "NOCTURNAUX").
dico("N", 10, "NODULAIRES").
dico("N", 10, "NODULEUSES").
dico("N", 10, "NOEMATIQUE").
dico("N", 10, "NOIERAIENT").
dico("N", 10, "NOIRCIRAIS").
dico("N", 10, "NOIRCIRAIT").
dico("N", 10, "NOIRCIRENT").
dico("N", 10, "NOIRCIRIEZ").
dico("N", 10, "NOIRCIRONS").
dico("N", 10, "NOIRCIRONT").
dico("N", 10, "NOIRCISSES").
dico("N", 10, "NOIRCISSEZ").
dico("N", 10, "NOISERAIES").
dico("N", 10, "NOISETIERS").
dico("N", 10, "NOISETTINE").
dico("N", 10, "NOLISAIENT").
dico("N", 10, "NOLISASSES").
dico("N", 10, "NOLISEMENT").
dico("N", 10, "NOLISERAIS").
dico("N", 10, "NOLISERAIT").
dico("N", 10, "NOLISERENT").
dico("N", 10, "NOLISERIEZ").
dico("N", 10, "NOLISERONS").
dico("N", 10, "NOLISERONT").
dico("N", 10, "NOMADISAIS").
dico("N", 10, "NOMADISAIT").
dico("N", 10, "NOMADISANT").
dico("N", 10, "NOMADISEES").
dico("N", 10, "NOMADISENT").
dico("N", 10, "NOMADISERA").
dico("N", 10, "NOMADISIEZ").
dico("N", 10, "NOMADISMES").
dico("N", 10, "NOMADISONS").
dico("N", 10, "NOMBRABLES").
dico("N", 10, "NOMBRAIENT").
dico("N", 10, "NOMBRASSES").
dico("N", 10, "NOMBRERAIS").
dico("N", 10, "NOMBRERAIT").
dico("N", 10, "NOMBRERENT").
dico("N", 10, "NOMBRERIEZ").
dico("N", 10, "NOMBRERONS").
dico("N", 10, "NOMBRERONT").
dico("N", 10, "NOMBREUSES").
dico("N", 10, "NOMINAIENT").
dico("N", 10, "NOMINALISA").
dico("N", 10, "NOMINALISE").
dico("N", 10, "NOMINASSES").
dico("N", 10, "NOMINATIFS").
dico("N", 10, "NOMINATION").
dico("N", 10, "NOMINATIVE").
dico("N", 10, "NOMINERAIS").
dico("N", 10, "NOMINERAIT").
dico("N", 10, "NOMINERENT").
dico("N", 10, "NOMINERIEZ").
dico("N", 10, "NOMINERONS").
dico("N", 10, "NOMINERONT").
dico("N", 10, "NOMINETTES").
dico("N", 10, "NOMMASSENT").
dico("N", 10, "NOMMASSIEZ").
dico("N", 10, "NOMMERIONS").
dico("N", 10, "NOMOGRAMME").
dico("N", 10, "NOMOGRAPHE").
dico("N", 10, "NOMOLOGIES").
dico("N", 10, "NOMOTHETES").
dico("N", 10, "NONAGESIME").
dico("N", 10, "NONANTAINE").
dico("N", 10, "NONANTIEME").
dico("N", 10, "NONCHALANT").
dico("N", 10, "NONCHALOIR").
dico("N", 10, "NONCIATURE").
dico("N", 10, "NONOBSTANT").
dico("N", 10, "NONPAREILS").
dico("N", 10, "NONUPLAMES").
dico("N", 10, "NONUPLASSE").
dico("N", 10, "NONUPLATES").
dico("N", 10, "NONUPLERAI").
dico("N", 10, "NONUPLERAS").
dico("N", 10, "NONUPLEREZ").
dico("N", 10, "NONUPLIONS").
dico("N", 10, "NOOLOGIQUE").
dico("N", 10, "NOOSPHERES").
dico("N", 10, "NORDICITES").
dico("N", 10, "NORDIRIONS").
dico("N", 10, "NORDISSAIS").
dico("N", 10, "NORDISSAIT").
dico("N", 10, "NORDISSANT").
dico("N", 10, "NORDISSENT").
dico("N", 10, "NORDISSIEZ").
dico("N", 10, "NORDISSONS").
dico("N", 10, "NORMALIENS").
dico("N", 10, "NORMALISAI").
dico("N", 10, "NORMALISAS").
dico("N", 10, "NORMALISAT").
dico("N", 10, "NORMALISEE").
dico("N", 10, "NORMALISER").
dico("N", 10, "NORMALISES").
dico("N", 10, "NORMALISEZ").
dico("N", 10, "NORMALITES").
dico("N", 10, "NORMASSENT").
dico("N", 10, "NORMASSIEZ").
dico("N", 10, "NORMATIVES").
dico("N", 10, "NORMERIONS").
dico("N", 10, "NORVEGIENS").
dico("N", 10, "NOSOCOMIAL").
dico("N", 10, "NOSOLOGIES").
dico("N", 10, "NOSOPHOBIE").
dico("N", 10, "NOSTALGIES").
dico("N", 10, "NOTABILITE").
dico("N", 10, "NOTAIRESSE").
dico("N", 10, "NOTARIALES").
dico("N", 10, "NOTASSIONS").
dico("N", 10, "NOTATRICES").
dico("N", 10, "NOTERAIENT").
dico("N", 10, "NOTHOFAGUS").
dico("N", 10, "NOTIFIAMES").
dico("N", 10, "NOTIFIASSE").
dico("N", 10, "NOTIFIATES").
dico("N", 10, "NOTIFIERAI").
dico("N", 10, "NOTIFIERAS").
dico("N", 10, "NOTIFIEREZ").
dico("N", 10, "NOTIFIIONS").
dico("N", 10, "NOTIONNELS").
dico("N", 10, "NOTOCORDES").
dico("N", 10, "NOTONECTES").
dico("N", 10, "NOTORIETES").
dico("N", 10, "NOUASSIONS").
dico("N", 10, "NOUERAIENT").
dico("N", 10, "NOUGATINES").
dico("N", 10, "NOUMEENNES").
dico("N", 10, "NOUMENALES").
dico("N", 10, "NOURRICIER").
dico("N", 10, "NOURRIRAIS").
dico("N", 10, "NOURRIRAIT").
dico("N", 10, "NOURRIRENT").
dico("N", 10, "NOURRIRIEZ").
dico("N", 10, "NOURRIRONS").
dico("N", 10, "NOURRIRONT").
dico("N", 10, "NOURRISSES").
dico("N", 10, "NOURRISSEZ").
dico("N", 10, "NOURRISSON").
dico("N", 10, "NOURRITURE").
dico("N", 10, "NOUVEAUTES").
dico("N", 10, "NOVASSIONS").
dico("N", 10, "NOVATOIRES").
dico("N", 10, "NOVATRICES").
dico("N", 10, "NOVELETTES").
dico("N", 10, "NOVELISAIS").
dico("N", 10, "NOVELISAIT").
dico("N", 10, "NOVELISANT").
dico("N", 10, "NOVELISEES").
dico("N", 10, "NOVELISENT").
dico("N", 10, "NOVELISERA").
dico("N", 10, "NOVELISIEZ").
dico("N", 10, "NOVELISONS").
dico("N", 10, "NOVELLISAI").
dico("N", 10, "NOVELLISAS").
dico("N", 10, "NOVELLISAT").
dico("N", 10, "NOVELLISEE").
dico("N", 10, "NOVELLISER").
dico("N", 10, "NOVELLISES").
dico("N", 10, "NOVELLISEZ").
dico("N", 10, "NOVERAIENT").
dico("N", 10, "NOVILLADAS").
dico("N", 10, "NOVILLEROS").
dico("N", 10, "NOVLANGUES").
dico("N", 10, "NOVOCAINES").
dico("N", 10, "NOVOTIQUES").
dico("N", 10, "NOYASSIONS").
dico("N", 10, "NOYAUTAGES").
dico("N", 10, "NOYAUTAMES").
dico("N", 10, "NOYAUTASSE").
dico("N", 10, "NOYAUTATES").
dico("N", 10, "NOYAUTERAI").
dico("N", 10, "NOYAUTERAS").
dico("N", 10, "NOYAUTEREZ").
dico("N", 10, "NOYAUTEURS").
dico("N", 10, "NOYAUTEUSE").
dico("N", 10, "NOYAUTIONS").
dico("N", 10, "NUANCAIENT").
dico("N", 10, "NUANCASSES").
dico("N", 10, "NUANCEMENT").
dico("N", 10, "NUANCERAIS").
dico("N", 10, "NUANCERAIT").
dico("N", 10, "NUANCERENT").
dico("N", 10, "NUANCERIEZ").
dico("N", 10, "NUANCERONS").
dico("N", 10, "NUANCERONT").
dico("N", 10, "NUCELLAIRE").
dico("N", 10, "NUCLEAIRES").
dico("N", 10, "NUCLEARISA").
dico("N", 10, "NUCLEARISE").
dico("N", 10, "NUCLEIQUES").
dico("N", 10, "NUCLEOLYSE").
dico("N", 10, "NUCLEOSIDE").
dico("N", 10, "NUCLEOSOME").
dico("N", 10, "NUCLEOTIDE").
dico("N", 10, "NUISISSENT").
dico("N", 10, "NUISISSIEZ").
dico("N", 10, "NUITAMMENT").
dico("N", 10, "NULLIPARES").
dico("N", 10, "NUMERAIRES").
dico("N", 10, "NUMERATEUR").
dico("N", 10, "NUMERATIFS").
dico("N", 10, "NUMERATION").
dico("N", 10, "NUMERATIVE").
dico("N", 10, "NUMERIQUES").
dico("N", 10, "NUMERISAIS").
dico("N", 10, "NUMERISAIT").
dico("N", 10, "NUMERISANT").
dico("N", 10, "NUMERISEES").
dico("N", 10, "NUMERISENT").
dico("N", 10, "NUMERISERA").
dico("N", 10, "NUMERISEUR").
dico("N", 10, "NUMERISIEZ").
dico("N", 10, "NUMERISONS").
dico("N", 10, "NUMEROTAGE").
dico("N", 10, "NUMEROTAIS").
dico("N", 10, "NUMEROTAIT").
dico("N", 10, "NUMEROTANT").
dico("N", 10, "NUMEROTEES").
dico("N", 10, "NUMEROTENT").
dico("N", 10, "NUMEROTERA").
dico("N", 10, "NUMEROTEUR").
dico("N", 10, "NUMEROTIEZ").
dico("N", 10, "NUMEROTONS").
dico("N", 10, "NUMISMATES").
dico("N", 10, "NUMMULAIRE").
dico("N", 10, "NUMMULITES").
dico("N", 10, "NUNAVIMIUQ").
dico("N", 10, "NUNAVUMIUQ").
dico("N", 10, "NUNCUPATIF").
dico("N", 10, "NUPTIALITE").
dico("N", 10, "NURAGIQUES").
dico("N", 10, "NUTRICIERE").
dico("N", 10, "NUTRICIERS").
dico("N", 10, "NUTRIMENTS").
dico("N", 10, "NUTRITIONS").
dico("N", 10, "NUTRITIVES").
dico("N", 10, "NYCTALOPES").
dico("N", 10, "NYCTALOPIE").
dico("N", 10, "NYCTHEMERE").
dico("N", 10, "NYMPHALIDE").
dico("N", 10, "NYMPHEACEE").
dico("N", 10, "NYMPHETTES").
dico("N", 10, "NYMPHOMANE").
dico("N", 10, "NYSTATINES").
