dico("N", 5, "NABAB").
dico("N", 5, "NABIS").
dico("N", 5, "NABLA").
dico("N", 5, "NABLE").
dico("N", 5, "NABOT").
dico("N", 5, "NACRA").
dico("N", 5, "NACRE").
dico("N", 5, "NADIR").
dico("N", 5, "NAEVI").
dico("N", 5, "NAFES").
dico("N", 5, "NAGAS").
dico("N", 5, "NAGEA").
dico("N", 5, "NAGEE").
dico("N", 5, "NAGER").
dico("N", 5, "NAGES").
dico("N", 5, "NAGEZ").
dico("N", 5, "NAGIS").
dico("N", 5, "NAHUA").
dico("N", 5, "NAIAS").
dico("N", 5, "NAIFS").
dico("N", 5, "NAINE").
dico("N", 5, "NAINS").
dico("N", 5, "NAIRA").
dico("N", 5, "NAIVE").
dico("N", 5, "NAJAS").
dico("N", 5, "NAKFA").
dico("N", 5, "NANAN").
dico("N", 5, "NANAR").
dico("N", 5, "NANAS").
dico("N", 5, "NANTI").
dico("N", 5, "NAPEE").
dico("N", 5, "NAPEL").
dico("N", 5, "NAPPA").
dico("N", 5, "NAPPE").
dico("N", 5, "NARCO").
dico("N", 5, "NARDS").
dico("N", 5, "NARRA").
dico("N", 5, "NARRE").
dico("N", 5, "NARSE").
dico("N", 5, "NASAL").
dico("N", 5, "NASES").
dico("N", 5, "NASSE").
dico("N", 5, "NATAL").
dico("N", 5, "NATEL").
dico("N", 5, "NATIF").
dico("N", 5, "NATTA").
dico("N", 5, "NATTE").
dico("N", 5, "NAVAL").
dico("N", 5, "NAVEL").
dico("N", 5, "NAVES").
dico("N", 5, "NAVET").
dico("N", 5, "NAVRA").
dico("N", 5, "NAVRE").
dico("N", 5, "NAZCA").
dico("N", 5, "NAZES").
dico("N", 5, "NAZIE").
dico("N", 5, "NAZIS").
dico("N", 5, "NEANT").
dico("N", 5, "NEBKA").
dico("N", 5, "NECKS").
dico("N", 5, "NEFLE").
dico("N", 5, "NEGRE").
dico("N", 5, "NEGRO").
dico("N", 5, "NEGUS").
dico("N", 5, "NEIGE").
dico("N", 5, "NELLS").
dico("N", 5, "NENES").
dico("N", 5, "NENNI").
dico("N", 5, "NEONS").
dico("N", 5, "NEPES").
dico("N", 5, "NERES").
dico("N", 5, "NERFS").
dico("N", 5, "NERVI").
dico("N", 5, "NETTE").
dico("N", 5, "NEUFS").
dico("N", 5, "NEUME").
dico("N", 5, "NEUVE").
dico("N", 5, "NEVES").
dico("N", 5, "NEVEU").
dico("N", 5, "NIAIS").
dico("N", 5, "NIAIT").
dico("N", 5, "NIANT").
dico("N", 5, "NIBAR").
dico("N", 5, "NICAM").
dico("N", 5, "NICHA").
dico("N", 5, "NICHE").
dico("N", 5, "NICOL").
dico("N", 5, "NIDAS").
dico("N", 5, "NIEBE").
dico("N", 5, "NIECE").
dico("N", 5, "NIEES").
dico("N", 5, "NIEME").
dico("N", 5, "NIENT").
dico("N", 5, "NIERA").
dico("N", 5, "NIFES").
dico("N", 5, "NIIEZ").
dico("N", 5, "NILLE").
dico("N", 5, "NIMBA").
dico("N", 5, "NIMBE").
dico("N", 5, "NINAS").
dico("N", 5, "NINJA").
dico("N", 5, "NIOLE").
dico("N", 5, "NIOLO").
dico("N", 5, "NIOLU").
dico("N", 5, "NIONS").
dico("N", 5, "NIPPA").
dico("N", 5, "NIPPE").
dico("N", 5, "NIQUA").
dico("N", 5, "NIQUE").
dico("N", 5, "NITRA").
dico("N", 5, "NITRE").
dico("N", 5, "NIVAL").
dico("N", 5, "NIVES").
dico("N", 5, "NIXES").
dico("N", 5, "NIZAM").
dico("N", 5, "NOBEL").
dico("N", 5, "NOBLE").
dico("N", 5, "NOCAI").
dico("N", 5, "NOCAS").
dico("N", 5, "NOCAT").
dico("N", 5, "NOCER").
dico("N", 5, "NOCES").
dico("N", 5, "NOCEZ").
dico("N", 5, "NOCIF").
dico("N", 5, "NODAL").
dico("N", 5, "NOELS").
dico("N", 5, "NOEME").
dico("N", 5, "NOESE").
dico("N", 5, "NOEUD").
dico("N", 5, "NOIES").
dico("N", 5, "NOIRE").
dico("N", 5, "NOIRS").
dico("N", 5, "NOISE").
dico("N", 5, "NOLIS").
dico("N", 5, "NOMES").
dico("N", 5, "NOMMA").
dico("N", 5, "NOMME").
dico("N", 5, "NONCE").
dico("N", 5, "NONES").
dico("N", 5, "NONNE").
dico("N", 5, "NONOS").
dico("N", 5, "NOPAL").
dico("N", 5, "NORDE").
dico("N", 5, "NORDI").
dico("N", 5, "NORIA").
dico("N", 5, "NORMA").
dico("N", 5, "NORME").
dico("N", 5, "NOTAI").
dico("N", 5, "NOTAS").
dico("N", 5, "NOTAT").
dico("N", 5, "NOTEE").
dico("N", 5, "NOTER").
dico("N", 5, "NOTES").
dico("N", 5, "NOTEZ").
dico("N", 5, "NOTRE").
dico("N", 5, "NOUAI").
dico("N", 5, "NOUAS").
dico("N", 5, "NOUAT").
dico("N", 5, "NOUBA").
dico("N", 5, "NOUEE").
dico("N", 5, "NOUER").
dico("N", 5, "NOUES").
dico("N", 5, "NOUET").
dico("N", 5, "NOUEZ").
dico("N", 5, "NOVAE").
dico("N", 5, "NOVAI").
dico("N", 5, "NOVAS").
dico("N", 5, "NOVAT").
dico("N", 5, "NOVEE").
dico("N", 5, "NOVER").
dico("N", 5, "NOVES").
dico("N", 5, "NOVEZ").
dico("N", 5, "NOYAI").
dico("N", 5, "NOYAS").
dico("N", 5, "NOYAT").
dico("N", 5, "NOYAU").
dico("N", 5, "NOYEE").
dico("N", 5, "NOYER").
dico("N", 5, "NOYES").
dico("N", 5, "NOYEZ").
dico("N", 5, "NUAGE").
dico("N", 5, "NUAIS").
dico("N", 5, "NUAIT").
dico("N", 5, "NUANT").
dico("N", 5, "NUCAL").
dico("N", 5, "NUEES").
dico("N", 5, "NUENT").
dico("N", 5, "NUERA").
dico("N", 5, "NUIEZ").
dico("N", 5, "NUIRA").
dico("N", 5, "NUIRE").
dico("N", 5, "NUISE").
dico("N", 5, "NUITS").
dico("N", 5, "NULLE").
dico("N", 5, "NUONS").
dico("N", 5, "NUQUE").
dico("N", 5, "NURSE").
dico("N", 5, "NYLON").
