dico("N", 8, "NABATEEN").
dico("N", 8, "NABISMES").
dico("N", 8, "NACARATS").
dico("N", 8, "NACELLES").
dico("N", 8, "NACRAMES").
dico("N", 8, "NACRASSE").
dico("N", 8, "NACRATES").
dico("N", 8, "NACRERAI").
dico("N", 8, "NACRERAS").
dico("N", 8, "NACREREZ").
dico("N", 8, "NACRIONS").
dico("N", 8, "NACRURES").
dico("N", 8, "NADIRALE").
dico("N", 8, "NADIRAUX").
dico("N", 8, "NAGAIKAS").
dico("N", 8, "NAGEAMES").
dico("N", 8, "NAGEASSE").
dico("N", 8, "NAGEATES").
dico("N", 8, "NAGEOIRE").
dico("N", 8, "NAGEOTAI").
dico("N", 8, "NAGEOTAS").
dico("N", 8, "NAGEOTAT").
dico("N", 8, "NAGEOTER").
dico("N", 8, "NAGEOTES").
dico("N", 8, "NAGEOTEZ").
dico("N", 8, "NAGERAIS").
dico("N", 8, "NAGERAIT").
dico("N", 8, "NAGERENT").
dico("N", 8, "NAGERIEZ").
dico("N", 8, "NAGERONS").
dico("N", 8, "NAGERONT").
dico("N", 8, "NAGEUSES").
dico("N", 8, "NAGUERES").
dico("N", 8, "NAHAIKAS").
dico("N", 8, "NAHUATLS").
dico("N", 8, "NAISSAIN").
dico("N", 8, "NAISSAIS").
dico("N", 8, "NAISSAIT").
dico("N", 8, "NAISSANT").
dico("N", 8, "NAISSENT").
dico("N", 8, "NAISSIEZ").
dico("N", 8, "NAISSONS").
dico("N", 8, "NAITRAIS").
dico("N", 8, "NAITRAIT").
dico("N", 8, "NAITRIEZ").
dico("N", 8, "NAITRONS").
dico("N", 8, "NAITRONT").
dico("N", 8, "NAIVETES").
dico("N", 8, "NAMIBIEN").
dico("N", 8, "NAMUROIS").
dico("N", 8, "NANCEIEN").
dico("N", 8, "NANDINIE").
dico("N", 8, "NANIFIAI").
dico("N", 8, "NANIFIAS").
dico("N", 8, "NANIFIAT").
dico("N", 8, "NANIFIEE").
dico("N", 8, "NANIFIER").
dico("N", 8, "NANIFIES").
dico("N", 8, "NANIFIEZ").
dico("N", 8, "NANISAIS").
dico("N", 8, "NANISAIT").
dico("N", 8, "NANISANT").
dico("N", 8, "NANISEES").
dico("N", 8, "NANISENT").
dico("N", 8, "NANISERA").
dico("N", 8, "NANISIEZ").
dico("N", 8, "NANISMES").
dico("N", 8, "NANISONS").
dico("N", 8, "NANSOUKS").
dico("N", 8, "NANTAISE").
dico("N", 8, "NANTIMES").
dico("N", 8, "NANTIRAI").
dico("N", 8, "NANTIRAS").
dico("N", 8, "NANTIREZ").
dico("N", 8, "NANTISSE").
dico("N", 8, "NANTITES").
dico("N", 8, "NANZOUKS").
dico("N", 8, "NAPHTENE").
dico("N", 8, "NAPHTOLS").
dico("N", 8, "NAPOLEON").
dico("N", 8, "NAPPAGES").
dico("N", 8, "NAPPAMES").
dico("N", 8, "NAPPASSE").
dico("N", 8, "NAPPATES").
dico("N", 8, "NAPPERAI").
dico("N", 8, "NAPPERAS").
dico("N", 8, "NAPPEREZ").
dico("N", 8, "NAPPERON").
dico("N", 8, "NAPPIONS").
dico("N", 8, "NAQUIMES").
dico("N", 8, "NAQUISSE").
dico("N", 8, "NAQUITES").
dico("N", 8, "NARCEINE").
dico("N", 8, "NARCISSE").
dico("N", 8, "NARCOSES").
dico("N", 8, "NARGHILE").
dico("N", 8, "NARGUAIS").
dico("N", 8, "NARGUAIT").
dico("N", 8, "NARGUANT").
dico("N", 8, "NARGUEES").
dico("N", 8, "NARGUENT").
dico("N", 8, "NARGUERA").
dico("N", 8, "NARGUIEZ").
dico("N", 8, "NARGUILE").
dico("N", 8, "NARGUONS").
dico("N", 8, "NARQUOIS").
dico("N", 8, "NARRAMES").
dico("N", 8, "NARRASSE").
dico("N", 8, "NARRATES").
dico("N", 8, "NARRATIF").
dico("N", 8, "NARRERAI").
dico("N", 8, "NARRERAS").
dico("N", 8, "NARREREZ").
dico("N", 8, "NARRIONS").
dico("N", 8, "NASALISA").
dico("N", 8, "NASALISE").
dico("N", 8, "NASALITE").
dico("N", 8, "NASARDES").
dico("N", 8, "NASILLAI").
dico("N", 8, "NASILLAS").
dico("N", 8, "NASILLAT").
dico("N", 8, "NASILLEE").
dico("N", 8, "NASILLER").
dico("N", 8, "NASILLES").
dico("N", 8, "NASILLEZ").
dico("N", 8, "NASIQUES").
dico("N", 8, "NASITORT").
dico("N", 8, "NASKAPIE").
dico("N", 8, "NASKAPIS").
dico("N", 8, "NASONNAI").
dico("N", 8, "NASONNAS").
dico("N", 8, "NASONNAT").
dico("N", 8, "NASONNEE").
dico("N", 8, "NASONNER").
dico("N", 8, "NASONNES").
dico("N", 8, "NASONNEZ").
dico("N", 8, "NATALITE").
dico("N", 8, "NATATION").
dico("N", 8, "NATIONAL").
dico("N", 8, "NATIVITE").
dico("N", 8, "NATREMIE").
dico("N", 8, "NATRIUMS").
dico("N", 8, "NATTAGES").
dico("N", 8, "NATTAMES").
dico("N", 8, "NATTASSE").
dico("N", 8, "NATTATES").
dico("N", 8, "NATTERAI").
dico("N", 8, "NATTERAS").
dico("N", 8, "NATTEREZ").
dico("N", 8, "NATTIERE").
dico("N", 8, "NATTIERS").
dico("N", 8, "NATTIONS").
dico("N", 8, "NATURELS").
dico("N", 8, "NAUCORES").
dico("N", 8, "NAUFRAGE").
dico("N", 8, "NAUPLIUS").
dico("N", 8, "NAURUANE").
dico("N", 8, "NAURUANS").
dico("N", 8, "NAUSEEUX").
dico("N", 8, "NAUTILES").
dico("N", 8, "NAUTIQUE").
dico("N", 8, "NAUTISME").
dico("N", 8, "NAVARINS").
dico("N", 8, "NAVARQUE").
dico("N", 8, "NAVARRIN").
dico("N", 8, "NAVETTAI").
dico("N", 8, "NAVETTAS").
dico("N", 8, "NAVETTAT").
dico("N", 8, "NAVETTER").
dico("N", 8, "NAVETTES").
dico("N", 8, "NAVETTEZ").
dico("N", 8, "NAVICERT").
dico("N", 8, "NAVICULE").
dico("N", 8, "NAVIGANT").
dico("N", 8, "NAVIGUAI").
dico("N", 8, "NAVIGUAS").
dico("N", 8, "NAVIGUAT").
dico("N", 8, "NAVIGUER").
dico("N", 8, "NAVIGUES").
dico("N", 8, "NAVIGUEZ").
dico("N", 8, "NAVRAMES").
dico("N", 8, "NAVRANTE").
dico("N", 8, "NAVRANTS").
dico("N", 8, "NAVRASSE").
dico("N", 8, "NAVRATES").
dico("N", 8, "NAVRERAI").
dico("N", 8, "NAVRERAS").
dico("N", 8, "NAVREREZ").
dico("N", 8, "NAVRIONS").
dico("N", 8, "NAZAREEN").
dico("N", 8, "NAZILLON").
dico("N", 8, "NAZISMES").
dico("N", 8, "NEANTISA").
dico("N", 8, "NEANTISE").
dico("N", 8, "NEBULEUX").
dico("N", 8, "NEBULISA").
dico("N", 8, "NEBULISE").
dico("N", 8, "NECROBIE").
dico("N", 8, "NECROSAI").
dico("N", 8, "NECROSAS").
dico("N", 8, "NECROSAT").
dico("N", 8, "NECROSEE").
dico("N", 8, "NECROSER").
dico("N", 8, "NECROSES").
dico("N", 8, "NECROSEZ").
dico("N", 8, "NECTAIRE").
dico("N", 8, "NEFASTES").
dico("N", 8, "NEFLIERS").
dico("N", 8, "NEGATEUR").
dico("N", 8, "NEGATIFS").
dico("N", 8, "NEGATION").
dico("N", 8, "NEGATIVE").
dico("N", 8, "NEGATONS").
dico("N", 8, "NEGLIGEA").
dico("N", 8, "NEGLIGEE").
dico("N", 8, "NEGLIGER").
dico("N", 8, "NEGLIGES").
dico("N", 8, "NEGLIGEZ").
dico("N", 8, "NEGOCIAI").
dico("N", 8, "NEGOCIAS").
dico("N", 8, "NEGOCIAT").
dico("N", 8, "NEGOCIEE").
dico("N", 8, "NEGOCIER").
dico("N", 8, "NEGOCIES").
dico("N", 8, "NEGOCIEZ").
dico("N", 8, "NEGONDOS").
dico("N", 8, "NEGRESSE").
dico("N", 8, "NEGRIERE").
dico("N", 8, "NEGRIERS").
dico("N", 8, "NEGRILLE").
dico("N", 8, "NEGROIDE").
dico("N", 8, "NEGUNDOS").
dico("N", 8, "NEIGEAIT").
dico("N", 8, "NEIGEOTA").
dico("N", 8, "NEIGEOTE").
dico("N", 8, "NEIGEUSE").
dico("N", 8, "NELOMBOS").
dico("N", 8, "NELUMBOS").
dico("N", 8, "NEMALION").
dico("N", 8, "NEMATODE").
dico("N", 8, "NEMEENNE").
dico("N", 8, "NEMERTES").
dico("N", 8, "NEMORALE").
dico("N", 8, "NEMORAUX").
dico("N", 8, "NENETTES").
dico("N", 8, "NENUPHAR").
dico("N", 8, "NEODYMES").
dico("N", 8, "NEOFORME").
dico("N", 8, "NEOGENES").
dico("N", 8, "NEOGRECS").
dico("N", 8, "NEOLOCAL").
dico("N", 8, "NEOLOGIE").
dico("N", 8, "NEOMENIE").
dico("N", 8, "NEONATAL").
dico("N", 8, "NEONAZIE").
dico("N", 8, "NEONAZIS").
dico("N", 8, "NEOPHYTE").
dico("N", 8, "NEOPRENE").
dico("N", 8, "NEOPROMU").
dico("N", 8, "NEORURAL").
dico("N", 8, "NEOTENES").
dico("N", 8, "NEOTENIE").
dico("N", 8, "NEOTTIES").
dico("N", 8, "NEPALAIS").
dico("N", 8, "NEPERIEN").
dico("N", 8, "NEPHRITE").
dico("N", 8, "NEPHRONS").
dico("N", 8, "NEPHROSE").
dico("N", 8, "NEREIDES").
dico("N", 8, "NERONIEN").
dico("N", 8, "NERPRUNS").
dico("N", 8, "NERVEUSE").
dico("N", 8, "NERVINES").
dico("N", 8, "NERVURAI").
dico("N", 8, "NERVURAS").
dico("N", 8, "NERVURAT").
dico("N", 8, "NERVUREE").
dico("N", 8, "NERVURER").
dico("N", 8, "NERVURES").
dico("N", 8, "NERVUREZ").
dico("N", 8, "NESCAFES").
dico("N", 8, "NETSUKES").
dico("N", 8, "NETTETES").
dico("N", 8, "NETTOIES").
dico("N", 8, "NETTOYAI").
dico("N", 8, "NETTOYAS").
dico("N", 8, "NETTOYAT").
dico("N", 8, "NETTOYEE").
dico("N", 8, "NETTOYER").
dico("N", 8, "NETTOYES").
dico("N", 8, "NETTOYEZ").
dico("N", 8, "NETWORKS").
dico("N", 8, "NEURALES").
dico("N", 8, "NEURONAL").
dico("N", 8, "NEURONES").
dico("N", 8, "NEURULAS").
dico("N", 8, "NEUTRINO").
dico("N", 8, "NEUTRONS").
dico("N", 8, "NEUVAINE").
dico("N", 8, "NEUVAINS").
dico("N", 8, "NEUVIEME").
dico("N", 8, "NEVICIEN").
dico("N", 8, "NEVRAXES").
dico("N", 8, "NEVRITES").
dico("N", 8, "NEVROMES").
dico("N", 8, "NEVROSEE").
dico("N", 8, "NEVROSES").
dico("N", 8, "NGULTRUM").
dico("N", 8, "NIACINES").
dico("N", 8, "NIAISAGE").
dico("N", 8, "NIAISAIS").
dico("N", 8, "NIAISAIT").
dico("N", 8, "NIAISANT").
dico("N", 8, "NIAISEES").
dico("N", 8, "NIAISENT").
dico("N", 8, "NIAISERA").
dico("N", 8, "NIAISEUX").
dico("N", 8, "NIAISIEZ").
dico("N", 8, "NIAISONS").
dico("N", 8, "NIAMEYEN").
dico("N", 8, "NIAOULIS").
dico("N", 8, "NIASSENT").
dico("N", 8, "NIASSIEZ").
dico("N", 8, "NICHAMES").
dico("N", 8, "NICHASSE").
dico("N", 8, "NICHATES").
dico("N", 8, "NICHERAI").
dico("N", 8, "NICHERAS").
dico("N", 8, "NICHEREZ").
dico("N", 8, "NICHEURS").
dico("N", 8, "NICHEUSE").
dico("N", 8, "NICHIONS").
dico("N", 8, "NICHOIRS").
dico("N", 8, "NICHROME").
dico("N", 8, "NICKELAI").
dico("N", 8, "NICKELAS").
dico("N", 8, "NICKELAT").
dico("N", 8, "NICKELEE").
dico("N", 8, "NICKELER").
dico("N", 8, "NICKELES").
dico("N", 8, "NICKELEZ").
dico("N", 8, "NICKELLE").
dico("N", 8, "NICODEME").
dico("N", 8, "NICOISES").
dico("N", 8, "NICOSIEN").
dico("N", 8, "NICOTINE").
dico("N", 8, "NIDANGES").
dico("N", 8, "NIDATION").
dico("N", 8, "NIDICOLE").
dico("N", 8, "NIDIFIAI").
dico("N", 8, "NIDIFIAS").
dico("N", 8, "NIDIFIAT").
dico("N", 8, "NIDIFIER").
dico("N", 8, "NIDIFIES").
dico("N", 8, "NIDIFIEZ").
dico("N", 8, "NIDIFUGE").
dico("N", 8, "NIDOREUX").
dico("N", 8, "NIELLAGE").
dico("N", 8, "NIELLAIS").
dico("N", 8, "NIELLAIT").
dico("N", 8, "NIELLANT").
dico("N", 8, "NIELLEES").
dico("N", 8, "NIELLENT").
dico("N", 8, "NIELLERA").
dico("N", 8, "NIELLEUR").
dico("N", 8, "NIELLIEZ").
dico("N", 8, "NIELLONS").
dico("N", 8, "NIELLURE").
dico("N", 8, "NIERIONS").
dico("N", 8, "NIGAUDES").
dico("N", 8, "NIGELLES").
dico("N", 8, "NIGERIAN").
dico("N", 8, "NIGERIEN").
dico("N", 8, "NILGAUTS").
dico("N", 8, "NIMBAMES").
dico("N", 8, "NIMBASSE").
dico("N", 8, "NIMBATES").
dico("N", 8, "NIMBERAI").
dico("N", 8, "NIMBERAS").
dico("N", 8, "NIMBEREZ").
dico("N", 8, "NIMBIONS").
dico("N", 8, "NIMOISES").
dico("N", 8, "NIOBIUMS").
dico("N", 8, "NIORTAIS").
dico("N", 8, "NIPPAMES").
dico("N", 8, "NIPPASSE").
dico("N", 8, "NIPPATES").
dico("N", 8, "NIPPERAI").
dico("N", 8, "NIPPERAS").
dico("N", 8, "NIPPEREZ").
dico("N", 8, "NIPPIONS").
dico("N", 8, "NIPPONES").
dico("N", 8, "NIPPONNE").
dico("N", 8, "NIQUAMES").
dico("N", 8, "NIQUASSE").
dico("N", 8, "NIQUATES").
dico("N", 8, "NIQUERAI").
dico("N", 8, "NIQUERAS").
dico("N", 8, "NIQUEREZ").
dico("N", 8, "NIQUIONS").
dico("N", 8, "NIRVANAS").
dico("N", 8, "NISSARTS").
dico("N", 8, "NITOUCHE").
dico("N", 8, "NITRAMES").
dico("N", 8, "NITRANTE").
dico("N", 8, "NITRANTS").
dico("N", 8, "NITRASSE").
dico("N", 8, "NITRATAI").
dico("N", 8, "NITRATAS").
dico("N", 8, "NITRATAT").
dico("N", 8, "NITRATEE").
dico("N", 8, "NITRATER").
dico("N", 8, "NITRATES").
dico("N", 8, "NITRATEZ").
dico("N", 8, "NITRERAI").
dico("N", 8, "NITRERAS").
dico("N", 8, "NITREREZ").
dico("N", 8, "NITREUSE").
dico("N", 8, "NITRIERE").
dico("N", 8, "NITRIFIA").
dico("N", 8, "NITRIFIE").
dico("N", 8, "NITRILES").
dico("N", 8, "NITRIONS").
dico("N", 8, "NITRIQUE").
dico("N", 8, "NITRITES").
dico("N", 8, "NITROSAI").
dico("N", 8, "NITROSAS").
dico("N", 8, "NITROSAT").
dico("N", 8, "NITROSEE").
dico("N", 8, "NITROSER").
dico("N", 8, "NITROSES").
dico("N", 8, "NITROSEZ").
dico("N", 8, "NITRURAI").
dico("N", 8, "NITRURAS").
dico("N", 8, "NITRURAT").
dico("N", 8, "NITRUREE").
dico("N", 8, "NITRURER").
dico("N", 8, "NITRURES").
dico("N", 8, "NITRUREZ").
dico("N", 8, "NITRYLES").
dico("N", 8, "NIVATION").
dico("N", 8, "NIVEALES").
dico("N", 8, "NIVELAGE").
dico("N", 8, "NIVELAIS").
dico("N", 8, "NIVELAIT").
dico("N", 8, "NIVELANT").
dico("N", 8, "NIVELEES").
dico("N", 8, "NIVELEUR").
dico("N", 8, "NIVELIEZ").
dico("N", 8, "NIVELLES").
dico("N", 8, "NIVELONS").
dico("N", 8, "NIVEOLES").
dico("N", 8, "NIVICOLE").
dico("N", 8, "NIVOSITE").
dico("N", 8, "NOBELIUM").
dico("N", 8, "NOBLESSE").
dico("N", 8, "NOBLIAUX").
dico("N", 8, "NOCAIENT").
dico("N", 8, "NOCASSES").
dico("N", 8, "NOCERAIS").
dico("N", 8, "NOCERAIT").
dico("N", 8, "NOCERENT").
dico("N", 8, "NOCERIEZ").
dico("N", 8, "NOCERONS").
dico("N", 8, "NOCERONT").
dico("N", 8, "NOCEUSES").
dico("N", 8, "NOCHERES").
dico("N", 8, "NOCIVITE").
dico("N", 8, "NOCTUIDE").
dico("N", 8, "NOCTULES").
dico("N", 8, "NOCTURNE").
dico("N", 8, "NOCUITES").
dico("N", 8, "NODOSITE").
dico("N", 8, "NODULEUX").
dico("N", 8, "NOETIQUE").
dico("N", 8, "NOIERAIS").
dico("N", 8, "NOIERAIT").
dico("N", 8, "NOIERIEZ").
dico("N", 8, "NOIERONS").
dico("N", 8, "NOIERONT").
dico("N", 8, "NOIRATRE").
dico("N", 8, "NOIRAUDE").
dico("N", 8, "NOIRAUDS").
dico("N", 8, "NOIRCEUR").
dico("N", 8, "NOIRCIES").
dico("N", 8, "NOIRCIRA").
dico("N", 8, "NOISETTE").
dico("N", 8, "NOLISAIS").
dico("N", 8, "NOLISAIT").
dico("N", 8, "NOLISANT").
dico("N", 8, "NOLISEES").
dico("N", 8, "NOLISENT").
dico("N", 8, "NOLISERA").
dico("N", 8, "NOLISIEZ").
dico("N", 8, "NOLISONS").
dico("N", 8, "NOLITION").
dico("N", 8, "NOMADISA").
dico("N", 8, "NOMADISE").
dico("N", 8, "NOMBRAIS").
dico("N", 8, "NOMBRAIT").
dico("N", 8, "NOMBRANT").
dico("N", 8, "NOMBREES").
dico("N", 8, "NOMBRENT").
dico("N", 8, "NOMBRERA").
dico("N", 8, "NOMBREUX").
dico("N", 8, "NOMBRIEZ").
dico("N", 8, "NOMBRILS").
dico("N", 8, "NOMBRONS").
dico("N", 8, "NOMINAIS").
dico("N", 8, "NOMINAIT").
dico("N", 8, "NOMINALE").
dico("N", 8, "NOMINANT").
dico("N", 8, "NOMINAUX").
dico("N", 8, "NOMINEES").
dico("N", 8, "NOMINENT").
dico("N", 8, "NOMINERA").
dico("N", 8, "NOMINIEZ").
dico("N", 8, "NOMINONS").
dico("N", 8, "NOMMAGES").
dico("N", 8, "NOMMAMES").
dico("N", 8, "NOMMASSE").
dico("N", 8, "NOMMATES").
dico("N", 8, "NOMMERAI").
dico("N", 8, "NOMMERAS").
dico("N", 8, "NOMMEREZ").
dico("N", 8, "NOMMIONS").
dico("N", 8, "NONNETTE").
dico("N", 8, "NONUPLAI").
dico("N", 8, "NONUPLAS").
dico("N", 8, "NONUPLAT").
dico("N", 8, "NONUPLEE").
dico("N", 8, "NONUPLER").
dico("N", 8, "NONUPLES").
dico("N", 8, "NONUPLEZ").
dico("N", 8, "NORDIMES").
dico("N", 8, "NORDIQUE").
dico("N", 8, "NORDIRAI").
dico("N", 8, "NORDIRAS").
dico("N", 8, "NORDIREZ").
dico("N", 8, "NORDISSE").
dico("N", 8, "NORDISTE").
dico("N", 8, "NORDITES").
dico("N", 8, "NORMALES").
dico("N", 8, "NORMAMES").
dico("N", 8, "NORMANDE").
dico("N", 8, "NORMANDS").
dico("N", 8, "NORMASSE").
dico("N", 8, "NORMATES").
dico("N", 8, "NORMATIF").
dico("N", 8, "NORMERAI").
dico("N", 8, "NORMERAS").
dico("N", 8, "NORMEREZ").
dico("N", 8, "NORMIONS").
dico("N", 8, "NOROISES").
dico("N", 8, "NORROISE").
dico("N", 8, "NOSEMOSE").
dico("N", 8, "NOTABLES").
dico("N", 8, "NOTAIENT").
dico("N", 8, "NOTAIRES").
dico("N", 8, "NOTARIAL").
dico("N", 8, "NOTARIAT").
dico("N", 8, "NOTARIEE").
dico("N", 8, "NOTARIES").
dico("N", 8, "NOTASSES").
dico("N", 8, "NOTATEUR").
dico("N", 8, "NOTATION").
dico("N", 8, "NOTEBOOK").
dico("N", 8, "NOTERAIS").
dico("N", 8, "NOTERAIT").
dico("N", 8, "NOTERENT").
dico("N", 8, "NOTERIEZ").
dico("N", 8, "NOTERONS").
dico("N", 8, "NOTERONT").
dico("N", 8, "NOTIFIAI").
dico("N", 8, "NOTIFIAS").
dico("N", 8, "NOTIFIAT").
dico("N", 8, "NOTIFIEE").
dico("N", 8, "NOTIFIER").
dico("N", 8, "NOTIFIES").
dico("N", 8, "NOTIFIEZ").
dico("N", 8, "NOTOIRES").
dico("N", 8, "NOUAIENT").
dico("N", 8, "NOUAISON").
dico("N", 8, "NOUASSES").
dico("N", 8, "NOUEMENT").
dico("N", 8, "NOUERAIS").
dico("N", 8, "NOUERAIT").
dico("N", 8, "NOUERENT").
dico("N", 8, "NOUERIEZ").
dico("N", 8, "NOUERONS").
dico("N", 8, "NOUERONT").
dico("N", 8, "NOUEUSES").
dico("N", 8, "NOUILLES").
dico("N", 8, "NOUMEENS").
dico("N", 8, "NOUMENAL").
dico("N", 8, "NOUMENES").
dico("N", 8, "NOUNOURS").
dico("N", 8, "NOURRAIN").
dico("N", 8, "NOURRICE").
dico("N", 8, "NOURRIES").
dico("N", 8, "NOURRIRA").
dico("N", 8, "NOUVEAUX").
dico("N", 8, "NOUVELLE").
dico("N", 8, "NOVAIENT").
dico("N", 8, "NOVASSES").
dico("N", 8, "NOVATEUR").
dico("N", 8, "NOVATION").
dico("N", 8, "NOVELISA").
dico("N", 8, "NOVELISE").
dico("N", 8, "NOVELLES").
dico("N", 8, "NOVEMBRE").
dico("N", 8, "NOVERAIS").
dico("N", 8, "NOVERAIT").
dico("N", 8, "NOVERENT").
dico("N", 8, "NOVERIEZ").
dico("N", 8, "NOVERONS").
dico("N", 8, "NOVERONT").
dico("N", 8, "NOVICIAT").
dico("N", 8, "NOVILLOS").
dico("N", 8, "NOYAIENT").
dico("N", 8, "NOYASSES").
dico("N", 8, "NOYAUTAI").
dico("N", 8, "NOYAUTAS").
dico("N", 8, "NOYAUTAT").
dico("N", 8, "NOYAUTEE").
dico("N", 8, "NOYAUTER").
dico("N", 8, "NOYAUTES").
dico("N", 8, "NOYAUTEZ").
dico("N", 8, "NOYERENT").
dico("N", 8, "NUAGEUSE").
dico("N", 8, "NUAISONS").
dico("N", 8, "NUANCAIS").
dico("N", 8, "NUANCAIT").
dico("N", 8, "NUANCANT").
dico("N", 8, "NUANCEES").
dico("N", 8, "NUANCENT").
dico("N", 8, "NUANCERA").
dico("N", 8, "NUANCIER").
dico("N", 8, "NUANCIEZ").
dico("N", 8, "NUANCONS").
dico("N", 8, "NUASSENT").
dico("N", 8, "NUASSIEZ").
dico("N", 8, "NUBIENNE").
dico("N", 8, "NUBILITE").
dico("N", 8, "NUCELLES").
dico("N", 8, "NUCLEASE").
dico("N", 8, "NUCLEEES").
dico("N", 8, "NUCLEIDE").
dico("N", 8, "NUCLEINE").
dico("N", 8, "NUCLEOLE").
dico("N", 8, "NUCLEONS").
dico("N", 8, "NUCLIDES").
dico("N", 8, "NUDISMES").
dico("N", 8, "NUDISTES").
dico("N", 8, "NUERIONS").
dico("N", 8, "NUIRIONS").
dico("N", 8, "NUISANCE").
dico("N", 8, "NUISETTE").
dico("N", 8, "NUISIBLE").
dico("N", 8, "NUISIMES").
dico("N", 8, "NUISIONS").
dico("N", 8, "NUISISSE").
dico("N", 8, "NUISITES").
dico("N", 8, "NUITARDE").
dico("N", 8, "NUITARDS").
dico("N", 8, "NUITEUSE").
dico("N", 8, "NULLARDE").
dico("N", 8, "NULLARDS").
dico("N", 8, "NULLITES").
dico("N", 8, "NUMERALE").
dico("N", 8, "NUMERAUX").
dico("N", 8, "NUMERISA").
dico("N", 8, "NUMERISE").
dico("N", 8, "NUMEROTA").
dico("N", 8, "NUMEROTE").
dico("N", 8, "NUNATAKS").
dico("N", 8, "NUNCHAKU").
dico("N", 8, "NUNUCHES").
dico("N", 8, "NUPTIALE").
dico("N", 8, "NUPTIAUX").
dico("N", 8, "NURAGHES").
dico("N", 8, "NURSAGES").
dico("N", 8, "NURSERYS").
dico("N", 8, "NURSINGS").
dico("N", 8, "NUTATION").
dico("N", 8, "NUTRITIF").
dico("N", 8, "NYCTURIE").
dico("N", 8, "NYMPHALE").
dico("N", 8, "NYMPHALS").
dico("N", 8, "NYMPHAUX").
dico("N", 8, "NYMPHEAS").
dico("N", 8, "NYMPHEES").
dico("N", 8, "NYMPHOSE").
