dico("N", 9, "NABATEENS").
dico("N", 9, "NACRAIENT").
dico("N", 9, "NACRASSES").
dico("N", 9, "NACRERAIS").
dico("N", 9, "NACRERAIT").
dico("N", 9, "NACRERENT").
dico("N", 9, "NACRERIEZ").
dico("N", 9, "NACRERONS").
dico("N", 9, "NACRERONT").
dico("N", 9, "NADIRALES").
dico("N", 9, "NAGEAIENT").
dico("N", 9, "NAGEASSES").
dico("N", 9, "NAGEOIRES").
dico("N", 9, "NAGEOTAIS").
dico("N", 9, "NAGEOTAIT").
dico("N", 9, "NAGEOTANT").
dico("N", 9, "NAGEOTENT").
dico("N", 9, "NAGEOTERA").
dico("N", 9, "NAGEOTIEZ").
dico("N", 9, "NAGEOTONS").
dico("N", 9, "NAGERIONS").
dico("N", 9, "NAIADACEE").
dico("N", 9, "NAIROBIEN").
dico("N", 9, "NAISSAINS").
dico("N", 9, "NAISSANCE").
dico("N", 9, "NAISSANTE").
dico("N", 9, "NAISSANTS").
dico("N", 9, "NAISSIONS").
dico("N", 9, "NAITRIONS").
dico("N", 9, "NAIVEMENT").
dico("N", 9, "NAMIBIENS").
dico("N", 9, "NAMUROISE").
dico("N", 9, "NANCEIENS").
dico("N", 9, "NANDINIES").
dico("N", 9, "NANIFIAIS").
dico("N", 9, "NANIFIAIT").
dico("N", 9, "NANIFIANT").
dico("N", 9, "NANIFIEES").
dico("N", 9, "NANIFIENT").
dico("N", 9, "NANIFIERA").
dico("N", 9, "NANIFIIEZ").
dico("N", 9, "NANIFIONS").
dico("N", 9, "NANISAMES").
dico("N", 9, "NANISASSE").
dico("N", 9, "NANISATES").
dico("N", 9, "NANISERAI").
dico("N", 9, "NANISERAS").
dico("N", 9, "NANISEREZ").
dico("N", 9, "NANISIONS").
dico("N", 9, "NANOFARAD").
dico("N", 9, "NANOMETRE").
dico("N", 9, "NANTAISES").
dico("N", 9, "NANTIRAIS").
dico("N", 9, "NANTIRAIT").
dico("N", 9, "NANTIRENT").
dico("N", 9, "NANTIRIEZ").
dico("N", 9, "NANTIRONS").
dico("N", 9, "NANTIRONT").
dico("N", 9, "NANTISSES").
dico("N", 9, "NANTISSEZ").
dico("N", 9, "NAPHTENES").
dico("N", 9, "NAPOLEONS").
dico("N", 9, "NAPPAIENT").
dico("N", 9, "NAPPASSES").
dico("N", 9, "NAPPERAIS").
dico("N", 9, "NAPPERAIT").
dico("N", 9, "NAPPERENT").
dico("N", 9, "NAPPERIEZ").
dico("N", 9, "NAPPERONS").
dico("N", 9, "NAPPERONT").
dico("N", 9, "NAQUIRENT").
dico("N", 9, "NAQUISSES").
dico("N", 9, "NARCEINES").
dico("N", 9, "NARCISSES").
dico("N", 9, "NARCOMANE").
dico("N", 9, "NARCOTINE").
dico("N", 9, "NARGHILEH").
dico("N", 9, "NARGHILES").
dico("N", 9, "NARGUAMES").
dico("N", 9, "NARGUASSE").
dico("N", 9, "NARGUATES").
dico("N", 9, "NARGUERAI").
dico("N", 9, "NARGUERAS").
dico("N", 9, "NARGUEREZ").
dico("N", 9, "NARGUILES").
dico("N", 9, "NARGUIONS").
dico("N", 9, "NARQUOISE").
dico("N", 9, "NARRAIENT").
dico("N", 9, "NARRASSES").
dico("N", 9, "NARRATEUR").
dico("N", 9, "NARRATIFS").
dico("N", 9, "NARRATION").
dico("N", 9, "NARRATIVE").
dico("N", 9, "NARRERAIS").
dico("N", 9, "NARRERAIT").
dico("N", 9, "NARRERENT").
dico("N", 9, "NARRERIEZ").
dico("N", 9, "NARRERONS").
dico("N", 9, "NARRERONT").
dico("N", 9, "NASALISAI").
dico("N", 9, "NASALISAS").
dico("N", 9, "NASALISAT").
dico("N", 9, "NASALISEE").
dico("N", 9, "NASALISER").
dico("N", 9, "NASALISES").
dico("N", 9, "NASALISEZ").
dico("N", 9, "NASALITES").
dico("N", 9, "NASILLAIS").
dico("N", 9, "NASILLAIT").
dico("N", 9, "NASILLANT").
dico("N", 9, "NASILLARD").
dico("N", 9, "NASILLEES").
dico("N", 9, "NASILLENT").
dico("N", 9, "NASILLERA").
dico("N", 9, "NASILLEUR").
dico("N", 9, "NASILLIEZ").
dico("N", 9, "NASILLONS").
dico("N", 9, "NASITORTS").
dico("N", 9, "NASKAPIES").
dico("N", 9, "NASONNAIS").
dico("N", 9, "NASONNAIT").
dico("N", 9, "NASONNANT").
dico("N", 9, "NASONNEES").
dico("N", 9, "NASONNENT").
dico("N", 9, "NASONNERA").
dico("N", 9, "NASONNIEZ").
dico("N", 9, "NASONNONS").
dico("N", 9, "NATALISTE").
dico("N", 9, "NATALITES").
dico("N", 9, "NATATIONS").
dico("N", 9, "NATATOIRE").
dico("N", 9, "NATIONALE").
dico("N", 9, "NATIONAUX").
dico("N", 9, "NATIVISME").
dico("N", 9, "NATIVISTE").
dico("N", 9, "NATIVITES").
dico("N", 9, "NATOUFIEN").
dico("N", 9, "NATREMIES").
dico("N", 9, "NATRONITE").
dico("N", 9, "NATTAIENT").
dico("N", 9, "NATTASSES").
dico("N", 9, "NATTERAIS").
dico("N", 9, "NATTERAIT").
dico("N", 9, "NATTERENT").
dico("N", 9, "NATTERIEZ").
dico("N", 9, "NATTERONS").
dico("N", 9, "NATTERONT").
dico("N", 9, "NATTIERES").
dico("N", 9, "NATURELLE").
dico("N", 9, "NATURISME").
dico("N", 9, "NATURISTE").
dico("N", 9, "NAUFRAGEA").
dico("N", 9, "NAUFRAGEE").
dico("N", 9, "NAUFRAGER").
dico("N", 9, "NAUFRAGES").
dico("N", 9, "NAUFRAGEZ").
dico("N", 9, "NAUMACHIE").
dico("N", 9, "NAUPATHIE").
dico("N", 9, "NAURUANES").
dico("N", 9, "NAUSEEUSE").
dico("N", 9, "NAUTIQUES").
dico("N", 9, "NAUTISMES").
dico("N", 9, "NAUTONIER").
dico("N", 9, "NAVARQUES").
dico("N", 9, "NAVARRAIS").
dico("N", 9, "NAVARRINE").
dico("N", 9, "NAVARRINS").
dico("N", 9, "NAVETTAIS").
dico("N", 9, "NAVETTAIT").
dico("N", 9, "NAVETTANT").
dico("N", 9, "NAVETTENT").
dico("N", 9, "NAVETTERA").
dico("N", 9, "NAVETTEUR").
dico("N", 9, "NAVETTIEZ").
dico("N", 9, "NAVETTONS").
dico("N", 9, "NAVICELLE").
dico("N", 9, "NAVICERTS").
dico("N", 9, "NAVICULES").
dico("N", 9, "NAVIGABLE").
dico("N", 9, "NAVIGANTE").
dico("N", 9, "NAVIGANTS").
dico("N", 9, "NAVIGUAIS").
dico("N", 9, "NAVIGUAIT").
dico("N", 9, "NAVIGUANT").
dico("N", 9, "NAVIGUENT").
dico("N", 9, "NAVIGUERA").
dico("N", 9, "NAVIGUIEZ").
dico("N", 9, "NAVIGUONS").
dico("N", 9, "NAVIPLANE").
dico("N", 9, "NAVRAIENT").
dico("N", 9, "NAVRANTES").
dico("N", 9, "NAVRASSES").
dico("N", 9, "NAVREMENT").
dico("N", 9, "NAVRERAIS").
dico("N", 9, "NAVRERAIT").
dico("N", 9, "NAVRERENT").
dico("N", 9, "NAVRERIEZ").
dico("N", 9, "NAVRERONS").
dico("N", 9, "NAVRERONT").
dico("N", 9, "NAZAREENS").
dico("N", 9, "NAZILLONS").
dico("N", 9, "NEANMOINS").
dico("N", 9, "NEANTISAI").
dico("N", 9, "NEANTISAS").
dico("N", 9, "NEANTISAT").
dico("N", 9, "NEANTISEE").
dico("N", 9, "NEANTISER").
dico("N", 9, "NEANTISES").
dico("N", 9, "NEANTISEZ").
dico("N", 9, "NEBULEUSE").
dico("N", 9, "NEBULISAI").
dico("N", 9, "NEBULISAS").
dico("N", 9, "NEBULISAT").
dico("N", 9, "NEBULISEE").
dico("N", 9, "NEBULISER").
dico("N", 9, "NEBULISES").
dico("N", 9, "NEBULISEZ").
dico("N", 9, "NECESSITA").
dico("N", 9, "NECESSITE").
dico("N", 9, "NECROBIES").
dico("N", 9, "NECROLOGE").
dico("N", 9, "NECROMANT").
dico("N", 9, "NECROPOLE").
dico("N", 9, "NECROPSIE").
dico("N", 9, "NECROSAIS").
dico("N", 9, "NECROSAIT").
dico("N", 9, "NECROSANT").
dico("N", 9, "NECROSEES").
dico("N", 9, "NECROSENT").
dico("N", 9, "NECROSERA").
dico("N", 9, "NECROSIEZ").
dico("N", 9, "NECROSONS").
dico("N", 9, "NECTAIRES").
dico("N", 9, "NECTARINE").
dico("N", 9, "NEGATEURS").
dico("N", 9, "NEGATIONS").
dico("N", 9, "NEGATIVES").
dico("N", 9, "NEGATRICE").
dico("N", 9, "NEGLIGEAI").
dico("N", 9, "NEGLIGEAS").
dico("N", 9, "NEGLIGEAT").
dico("N", 9, "NEGLIGEES").
dico("N", 9, "NEGLIGENT").
dico("N", 9, "NEGLIGERA").
dico("N", 9, "NEGLIGIEZ").
dico("N", 9, "NEGOCIAIS").
dico("N", 9, "NEGOCIAIT").
dico("N", 9, "NEGOCIANT").
dico("N", 9, "NEGOCIEES").
dico("N", 9, "NEGOCIENT").
dico("N", 9, "NEGOCIERA").
dico("N", 9, "NEGOCIIEZ").
dico("N", 9, "NEGOCIONS").
dico("N", 9, "NEGRESSES").
dico("N", 9, "NEGRIERES").
dico("N", 9, "NEGRILLES").
dico("N", 9, "NEGRILLON").
dico("N", 9, "NEGRITUDE").
dico("N", 9, "NEGROIDES").
dico("N", 9, "NEIGEOTAT").
dico("N", 9, "NEIGEOTER").
dico("N", 9, "NEIGERAIT").
dico("N", 9, "NEIGEUSES").
dico("N", 9, "NEMALIONS").
dico("N", 9, "NEMATIQUE").
dico("N", 9, "NEMATODES").
dico("N", 9, "NEMEENNES").
dico("N", 9, "NEMERTIEN").
dico("N", 9, "NEMORALES").
dico("N", 9, "NENUPHARS").
dico("N", 9, "NEOBLASTE").
dico("N", 9, "NEOCOMIEN").
dico("N", 9, "NEOCORTEX").
dico("N", 9, "NEOFORMEE").
dico("N", 9, "NEOFORMES").
dico("N", 9, "NEOLOCALE").
dico("N", 9, "NEOLOCAUX").
dico("N", 9, "NEOLOGIES").
dico("N", 9, "NEOMENIES").
dico("N", 9, "NEOMYCINE").
dico("N", 9, "NEONATALE").
dico("N", 9, "NEONATALS").
dico("N", 9, "NEONATAUX").
dico("N", 9, "NEONAZIES").
dico("N", 9, "NEOPHYTES").
dico("N", 9, "NEOPILINA").
dico("N", 9, "NEOPLASIE").
dico("N", 9, "NEOPLASME").
dico("N", 9, "NEOPRENES").
dico("N", 9, "NEOPROMUE").
dico("N", 9, "NEOPROMUS").
dico("N", 9, "NEORURALE").
dico("N", 9, "NEORURAUX").
dico("N", 9, "NEOTENIES").
dico("N", 9, "NEOZOIQUE").
dico("N", 9, "NEPALAISE").
dico("N", 9, "NEPENTHES").
dico("N", 9, "NEPERIENS").
dico("N", 9, "NEPHELINE").
dico("N", 9, "NEPHELION").
dico("N", 9, "NEPHRIDIE").
dico("N", 9, "NEPHRITES").
dico("N", 9, "NEPHROSES").
dico("N", 9, "NEPOTISME").
dico("N", 9, "NEPTUNIEN").
dico("N", 9, "NEPTUNIUM").
dico("N", 9, "NERITIQUE").
dico("N", 9, "NERONIENS").
dico("N", 9, "NERVATION").
dico("N", 9, "NERVEUSES").
dico("N", 9, "NERVOSITE").
dico("N", 9, "NERVURAGE").
dico("N", 9, "NERVURAIS").
dico("N", 9, "NERVURAIT").
dico("N", 9, "NERVURANT").
dico("N", 9, "NERVUREES").
dico("N", 9, "NERVURENT").
dico("N", 9, "NERVURERA").
dico("N", 9, "NERVURIEZ").
dico("N", 9, "NERVURONS").
dico("N", 9, "NESTORIEN").
dico("N", 9, "NETTEMENT").
dico("N", 9, "NETTOIENT").
dico("N", 9, "NETTOIERA").
dico("N", 9, "NETTOYAGE").
dico("N", 9, "NETTOYAIS").
dico("N", 9, "NETTOYAIT").
dico("N", 9, "NETTOYANT").
dico("N", 9, "NETTOYEES").
dico("N", 9, "NETTOYEUR").
dico("N", 9, "NETTOYIEZ").
dico("N", 9, "NETTOYONS").
dico("N", 9, "NEUCHATEL").
dico("N", 9, "NEURINOME").
dico("N", 9, "NEURONALE").
dico("N", 9, "NEURONAUX").
dico("N", 9, "NEUTRINOS").
dico("N", 9, "NEUVAINES").
dico("N", 9, "NEUVIEMES").
dico("N", 9, "NEVERSOIS").
dico("N", 9, "NEVICIENS").
dico("N", 9, "NEVRALGIE").
dico("N", 9, "NEVRILEME").
dico("N", 9, "NEVROGLIE").
dico("N", 9, "NEVROSEES").
dico("N", 9, "NEWTONIEN").
dico("N", 9, "NGULTRUMS").
dico("N", 9, "NIAISAGES").
dico("N", 9, "NIAISAMES").
dico("N", 9, "NIAISASSE").
dico("N", 9, "NIAISATES").
dico("N", 9, "NIAISERAI").
dico("N", 9, "NIAISERAS").
dico("N", 9, "NIAISEREZ").
dico("N", 9, "NIAISERIE").
dico("N", 9, "NIAISEUSE").
dico("N", 9, "NIAISIONS").
dico("N", 9, "NIAMEYENS").
dico("N", 9, "NIASSIONS").
dico("N", 9, "NICHAIENT").
dico("N", 9, "NICHASSES").
dico("N", 9, "NICHERAIS").
dico("N", 9, "NICHERAIT").
dico("N", 9, "NICHERENT").
dico("N", 9, "NICHERIEZ").
dico("N", 9, "NICHERONS").
dico("N", 9, "NICHERONT").
dico("N", 9, "NICHEUSES").
dico("N", 9, "NICHROMES").
dico("N", 9, "NICKELAGE").
dico("N", 9, "NICKELAIS").
dico("N", 9, "NICKELAIT").
dico("N", 9, "NICKELANT").
dico("N", 9, "NICKELEES").
dico("N", 9, "NICKELIEZ").
dico("N", 9, "NICKELINE").
dico("N", 9, "NICKELLES").
dico("N", 9, "NICKELONS").
dico("N", 9, "NICKELURE").
dico("N", 9, "NICODEMES").
dico("N", 9, "NICOLAITE").
dico("N", 9, "NICOSIENS").
dico("N", 9, "NICOTINES").
dico("N", 9, "NICOTISME").
dico("N", 9, "NICTATION").
dico("N", 9, "NICTITANT").
dico("N", 9, "NIDATIONS").
dico("N", 9, "NIDICOLES").
dico("N", 9, "NIDIFIAIS").
dico("N", 9, "NIDIFIAIT").
dico("N", 9, "NIDIFIANT").
dico("N", 9, "NIDIFIENT").
dico("N", 9, "NIDIFIERA").
dico("N", 9, "NIDIFIIEZ").
dico("N", 9, "NIDIFIONS").
dico("N", 9, "NIDIFUGES").
dico("N", 9, "NIDOREUSE").
dico("N", 9, "NIELLAGES").
dico("N", 9, "NIELLAMES").
dico("N", 9, "NIELLASSE").
dico("N", 9, "NIELLATES").
dico("N", 9, "NIELLERAI").
dico("N", 9, "NIELLERAS").
dico("N", 9, "NIELLEREZ").
dico("N", 9, "NIELLEURS").
dico("N", 9, "NIELLEUSE").
dico("N", 9, "NIELLIONS").
dico("N", 9, "NIELLURES").
dico("N", 9, "NIERAIENT").
dico("N", 9, "NIGERIANE").
dico("N", 9, "NIGERIANS").
dico("N", 9, "NIGERIENS").
dico("N", 9, "NIHILISME").
dico("N", 9, "NIHILISTE").
dico("N", 9, "NILOTIQUE").
dico("N", 9, "NILPOTENT").
dico("N", 9, "NIMBAIENT").
dico("N", 9, "NIMBASSES").
dico("N", 9, "NIMBERAIS").
dico("N", 9, "NIMBERAIT").
dico("N", 9, "NIMBERENT").
dico("N", 9, "NIMBERIEZ").
dico("N", 9, "NIMBERONS").
dico("N", 9, "NIMBERONT").
dico("N", 9, "NIORTAISE").
dico("N", 9, "NIPPAIENT").
dico("N", 9, "NIPPASSES").
dico("N", 9, "NIPPERAIS").
dico("N", 9, "NIPPERAIT").
dico("N", 9, "NIPPERENT").
dico("N", 9, "NIPPERIEZ").
dico("N", 9, "NIPPERONS").
dico("N", 9, "NIPPERONT").
dico("N", 9, "NIPPONNES").
dico("N", 9, "NIQUAIENT").
dico("N", 9, "NIQUASSES").
dico("N", 9, "NIQUERAIS").
dico("N", 9, "NIQUERAIT").
dico("N", 9, "NIQUERENT").
dico("N", 9, "NIQUERIEZ").
dico("N", 9, "NIQUERONS").
dico("N", 9, "NIQUERONT").
dico("N", 9, "NITOUCHES").
dico("N", 9, "NITRAIENT").
dico("N", 9, "NITRANTES").
dico("N", 9, "NITRASSES").
dico("N", 9, "NITRATAIS").
dico("N", 9, "NITRATAIT").
dico("N", 9, "NITRATANT").
dico("N", 9, "NITRATEES").
dico("N", 9, "NITRATENT").
dico("N", 9, "NITRATERA").
dico("N", 9, "NITRATIEZ").
dico("N", 9, "NITRATION").
dico("N", 9, "NITRATONS").
dico("N", 9, "NITRERAIS").
dico("N", 9, "NITRERAIT").
dico("N", 9, "NITRERENT").
dico("N", 9, "NITRERIEZ").
dico("N", 9, "NITRERONS").
dico("N", 9, "NITRERONT").
dico("N", 9, "NITREUSES").
dico("N", 9, "NITRIERES").
dico("N", 9, "NITRIFIAI").
dico("N", 9, "NITRIFIAS").
dico("N", 9, "NITRIFIAT").
dico("N", 9, "NITRIFIEE").
dico("N", 9, "NITRIFIER").
dico("N", 9, "NITRIFIES").
dico("N", 9, "NITRIFIEZ").
dico("N", 9, "NITRIQUES").
dico("N", 9, "NITROGENE").
dico("N", 9, "NITROSAIS").
dico("N", 9, "NITROSAIT").
dico("N", 9, "NITROSANT").
dico("N", 9, "NITROSEES").
dico("N", 9, "NITROSENT").
dico("N", 9, "NITROSERA").
dico("N", 9, "NITROSIEZ").
dico("N", 9, "NITROSONS").
dico("N", 9, "NITROSYLE").
dico("N", 9, "NITRURAIS").
dico("N", 9, "NITRURAIT").
dico("N", 9, "NITRURANT").
dico("N", 9, "NITRUREES").
dico("N", 9, "NITRURENT").
dico("N", 9, "NITRURERA").
dico("N", 9, "NITRURIEZ").
dico("N", 9, "NITRURONS").
dico("N", 9, "NIVATIONS").
dico("N", 9, "NIVELAGES").
dico("N", 9, "NIVELAMES").
dico("N", 9, "NIVELASSE").
dico("N", 9, "NIVELATES").
dico("N", 9, "NIVELETTE").
dico("N", 9, "NIVELEURS").
dico("N", 9, "NIVELEUSE").
dico("N", 9, "NIVELIONS").
dico("N", 9, "NIVELLENT").
dico("N", 9, "NIVELLERA").
dico("N", 9, "NIVERNAIS").
dico("N", 9, "NIVICOLES").
dico("N", 9, "NIVOLOGUE").
dico("N", 9, "NIVOSITES").
dico("N", 9, "NOBELIUMS").
dico("N", 9, "NOBILITAS").
dico("N", 9, "NOBLEMENT").
dico("N", 9, "NOBLESSES").
dico("N", 9, "NOCASSENT").
dico("N", 9, "NOCASSIEZ").
dico("N", 9, "NOCERIONS").
dico("N", 9, "NOCIVITES").
dico("N", 9, "NOCTUELLE").
dico("N", 9, "NOCTUIDES").
dico("N", 9, "NOCTURNAL").
dico("N", 9, "NOCTURNES").
dico("N", 9, "NODOSITES").
dico("N", 9, "NODULAIRE").
dico("N", 9, "NODULEUSE").
dico("N", 9, "NOETIQUES").
dico("N", 9, "NOIERIONS").
dico("N", 9, "NOIRATRES").
dico("N", 9, "NOIRAUDES").
dico("N", 9, "NOIRCEURS").
dico("N", 9, "NOIRCIMES").
dico("N", 9, "NOIRCIRAI").
dico("N", 9, "NOIRCIRAS").
dico("N", 9, "NOIRCIREZ").
dico("N", 9, "NOIRCISSE").
dico("N", 9, "NOIRCITES").
dico("N", 9, "NOISERAIE").
dico("N", 9, "NOISETIER").
dico("N", 9, "NOISETTES").
dico("N", 9, "NOLISAMES").
dico("N", 9, "NOLISASSE").
dico("N", 9, "NOLISATES").
dico("N", 9, "NOLISERAI").
dico("N", 9, "NOLISERAS").
dico("N", 9, "NOLISEREZ").
dico("N", 9, "NOLISIONS").
dico("N", 9, "NOLITIONS").
dico("N", 9, "NOMADISAI").
dico("N", 9, "NOMADISAS").
dico("N", 9, "NOMADISAT").
dico("N", 9, "NOMADISEE").
dico("N", 9, "NOMADISER").
dico("N", 9, "NOMADISES").
dico("N", 9, "NOMADISEZ").
dico("N", 9, "NOMADISME").
dico("N", 9, "NOMBRABLE").
dico("N", 9, "NOMBRAMES").
dico("N", 9, "NOMBRASSE").
dico("N", 9, "NOMBRATES").
dico("N", 9, "NOMBRERAI").
dico("N", 9, "NOMBRERAS").
dico("N", 9, "NOMBREREZ").
dico("N", 9, "NOMBREUSE").
dico("N", 9, "NOMBRIONS").
dico("N", 9, "NOMINALES").
dico("N", 9, "NOMINAMES").
dico("N", 9, "NOMINASSE").
dico("N", 9, "NOMINATES").
dico("N", 9, "NOMINATIF").
dico("N", 9, "NOMINERAI").
dico("N", 9, "NOMINERAS").
dico("N", 9, "NOMINEREZ").
dico("N", 9, "NOMINETTE").
dico("N", 9, "NOMINIONS").
dico("N", 9, "NOMMAIENT").
dico("N", 9, "NOMMASSES").
dico("N", 9, "NOMMEMENT").
dico("N", 9, "NOMMERAIS").
dico("N", 9, "NOMMERAIT").
dico("N", 9, "NOMMERENT").
dico("N", 9, "NOMMERIEZ").
dico("N", 9, "NOMMERONS").
dico("N", 9, "NOMMERONT").
dico("N", 9, "NOMOLOGIE").
dico("N", 9, "NOMOTHETE").
dico("N", 9, "NONNETTES").
dico("N", 9, "NONPAREIL").
dico("N", 9, "NONUPLAIS").
dico("N", 9, "NONUPLAIT").
dico("N", 9, "NONUPLANT").
dico("N", 9, "NONUPLEES").
dico("N", 9, "NONUPLENT").
dico("N", 9, "NONUPLERA").
dico("N", 9, "NONUPLIEZ").
dico("N", 9, "NONUPLONS").
dico("N", 9, "NOOSPHERE").
dico("N", 9, "NORDICITE").
dico("N", 9, "NORDIQUES").
dico("N", 9, "NORDIRAIS").
dico("N", 9, "NORDIRAIT").
dico("N", 9, "NORDIRENT").
dico("N", 9, "NORDIRIEZ").
dico("N", 9, "NORDIRONS").
dico("N", 9, "NORDIRONT").
dico("N", 9, "NORDISSES").
dico("N", 9, "NORDISSEZ").
dico("N", 9, "NORDISTES").
dico("N", 9, "NORMAIENT").
dico("N", 9, "NORMALIEN").
dico("N", 9, "NORMALISA").
dico("N", 9, "NORMALISE").
dico("N", 9, "NORMALITE").
dico("N", 9, "NORMANDES").
dico("N", 9, "NORMASSES").
dico("N", 9, "NORMATIFS").
dico("N", 9, "NORMATIVE").
dico("N", 9, "NORMERAIS").
dico("N", 9, "NORMERAIT").
dico("N", 9, "NORMERENT").
dico("N", 9, "NORMERIEZ").
dico("N", 9, "NORMERONS").
dico("N", 9, "NORMERONT").
dico("N", 9, "NORROISES").
dico("N", 9, "NORVEGIEN").
dico("N", 9, "NOSEMOSES").
dico("N", 9, "NOSOLOGIE").
dico("N", 9, "NOSTALGIE").
dico("N", 9, "NOTAMMENT").
dico("N", 9, "NOTARIALE").
dico("N", 9, "NOTARIATS").
dico("N", 9, "NOTARIAUX").
dico("N", 9, "NOTARIEES").
dico("N", 9, "NOTASSENT").
dico("N", 9, "NOTASSIEZ").
dico("N", 9, "NOTATEURS").
dico("N", 9, "NOTATIONS").
dico("N", 9, "NOTATRICE").
dico("N", 9, "NOTEBOOKS").
dico("N", 9, "NOTERIONS").
dico("N", 9, "NOTIFIAIS").
dico("N", 9, "NOTIFIAIT").
dico("N", 9, "NOTIFIANT").
dico("N", 9, "NOTIFIEES").
dico("N", 9, "NOTIFIENT").
dico("N", 9, "NOTIFIERA").
dico("N", 9, "NOTIFIIEZ").
dico("N", 9, "NOTIFIONS").
dico("N", 9, "NOTIONNEL").
dico("N", 9, "NOTOCORDE").
dico("N", 9, "NOTONECTE").
dico("N", 9, "NOTORIETE").
dico("N", 9, "NOUAISONS").
dico("N", 9, "NOUASSENT").
dico("N", 9, "NOUASSIEZ").
dico("N", 9, "NOUEMENTS").
dico("N", 9, "NOUERIONS").
dico("N", 9, "NOUGATINE").
dico("N", 9, "NOUMEENNE").
dico("N", 9, "NOUMENALE").
dico("N", 9, "NOUMENAUX").
dico("N", 9, "NOURRAINS").
dico("N", 9, "NOURRICES").
dico("N", 9, "NOURRIMES").
dico("N", 9, "NOURRIRAI").
dico("N", 9, "NOURRIRAS").
dico("N", 9, "NOURRIREZ").
dico("N", 9, "NOURRISSE").
dico("N", 9, "NOURRITES").
dico("N", 9, "NOUVEAUTE").
dico("N", 9, "NOUVELLES").
dico("N", 9, "NOVASSENT").
dico("N", 9, "NOVASSIEZ").
dico("N", 9, "NOVATEURS").
dico("N", 9, "NOVATIONS").
dico("N", 9, "NOVATOIRE").
dico("N", 9, "NOVATRICE").
dico("N", 9, "NOVELETTE").
dico("N", 9, "NOVELISAI").
dico("N", 9, "NOVELISAS").
dico("N", 9, "NOVELISAT").
dico("N", 9, "NOVELISEE").
dico("N", 9, "NOVELISER").
dico("N", 9, "NOVELISES").
dico("N", 9, "NOVELISEZ").
dico("N", 9, "NOVELLISA").
dico("N", 9, "NOVELLISE").
dico("N", 9, "NOVEMBRES").
dico("N", 9, "NOVERIONS").
dico("N", 9, "NOVICIATS").
dico("N", 9, "NOVILLADA").
dico("N", 9, "NOVILLERO").
dico("N", 9, "NOVLANGUE").
dico("N", 9, "NOVOCAINE").
dico("N", 9, "NOVOTIQUE").
dico("N", 9, "NOYASSENT").
dico("N", 9, "NOYASSIEZ").
dico("N", 9, "NOYAUTAGE").
dico("N", 9, "NOYAUTAIS").
dico("N", 9, "NOYAUTAIT").
dico("N", 9, "NOYAUTANT").
dico("N", 9, "NOYAUTEES").
dico("N", 9, "NOYAUTENT").
dico("N", 9, "NOYAUTERA").
dico("N", 9, "NOYAUTEUR").
dico("N", 9, "NOYAUTIEZ").
dico("N", 9, "NOYAUTONS").
dico("N", 9, "NUAGEUSES").
dico("N", 9, "NUANCAMES").
dico("N", 9, "NUANCASSE").
dico("N", 9, "NUANCATES").
dico("N", 9, "NUANCERAI").
dico("N", 9, "NUANCERAS").
dico("N", 9, "NUANCEREZ").
dico("N", 9, "NUANCIERS").
dico("N", 9, "NUANCIONS").
dico("N", 9, "NUASSIONS").
dico("N", 9, "NUBIENNES").
dico("N", 9, "NUBILITES").
dico("N", 9, "NUCLEAIRE").
dico("N", 9, "NUCLEASES").
dico("N", 9, "NUCLEIDES").
dico("N", 9, "NUCLEINES").
dico("N", 9, "NUCLEIQUE").
dico("N", 9, "NUCLEOLES").
dico("N", 9, "NUERAIENT").
dico("N", 9, "NUIRAIENT").
dico("N", 9, "NUISAIENT").
dico("N", 9, "NUISANCES").
dico("N", 9, "NUISETTES").
dico("N", 9, "NUISIBLES").
dico("N", 9, "NUISIRENT").
dico("N", 9, "NUISISSES").
dico("N", 9, "NUITARDES").
dico("N", 9, "NUITEUSES").
dico("N", 9, "NULLARDES").
dico("N", 9, "NULLEMENT").
dico("N", 9, "NULLIPARE").
dico("N", 9, "NUMERAIRE").
dico("N", 9, "NUMERALES").
dico("N", 9, "NUMERATIF").
dico("N", 9, "NUMERIQUE").
dico("N", 9, "NUMERISAI").
dico("N", 9, "NUMERISAS").
dico("N", 9, "NUMERISAT").
dico("N", 9, "NUMERISEE").
dico("N", 9, "NUMERISER").
dico("N", 9, "NUMERISES").
dico("N", 9, "NUMERISEZ").
dico("N", 9, "NUMEROTAI").
dico("N", 9, "NUMEROTAS").
dico("N", 9, "NUMEROTAT").
dico("N", 9, "NUMEROTEE").
dico("N", 9, "NUMEROTER").
dico("N", 9, "NUMEROTES").
dico("N", 9, "NUMEROTEZ").
dico("N", 9, "NUMISMATE").
dico("N", 9, "NUMMULITE").
dico("N", 9, "NUNCHAKUS").
dico("N", 9, "NUPTIALES").
dico("N", 9, "NURAGIQUE").
dico("N", 9, "NURSERIES").
dico("N", 9, "NUTATIONS").
dico("N", 9, "NUTRICIER").
dico("N", 9, "NUTRIMENT").
dico("N", 9, "NUTRITIFS").
dico("N", 9, "NUTRITION").
dico("N", 9, "NUTRITIVE").
dico("N", 9, "NYCTALOPE").
dico("N", 9, "NYCTURIES").
dico("N", 9, "NYMPHALES").
dico("N", 9, "NYMPHETTE").
dico("N", 9, "NYMPHOSES").
dico("N", 9, "NYSTAGMUS").
dico("N", 9, "NYSTATINE").
