dico("O", 10, "OBEDIENCES").
dico("O", 10, "OBEIRAIENT").
dico("O", 10, "OBEISSANCE").
dico("O", 10, "OBEISSANTE").
dico("O", 10, "OBEISSANTS").
dico("O", 10, "OBEISSIONS").
dico("O", 10, "OBELISQUES").
dico("O", 10, "OBERASSENT").
dico("O", 10, "OBERASSIEZ").
dico("O", 10, "OBERERIONS").
dico("O", 10, "OBITUAIRES").
dico("O", 10, "OBJECTALES").
dico("O", 10, "OBJECTAMES").
dico("O", 10, "OBJECTASSE").
dico("O", 10, "OBJECTATES").
dico("O", 10, "OBJECTERAI").
dico("O", 10, "OBJECTERAS").
dico("O", 10, "OBJECTEREZ").
dico("O", 10, "OBJECTEURS").
dico("O", 10, "OBJECTIONS").
dico("O", 10, "OBJECTIVAI").
dico("O", 10, "OBJECTIVAS").
dico("O", 10, "OBJECTIVAT").
dico("O", 10, "OBJECTIVEE").
dico("O", 10, "OBJECTIVER").
dico("O", 10, "OBJECTIVES").
dico("O", 10, "OBJECTIVEZ").
dico("O", 10, "OBJECTRICE").
dico("O", 10, "OBLATIVITE").
dico("O", 10, "OBLIGATION").
dico("O", 10, "OBLIGEAMES").
dico("O", 10, "OBLIGEANCE").
dico("O", 10, "OBLIGEANTE").
dico("O", 10, "OBLIGEANTS").
dico("O", 10, "OBLIGEASSE").
dico("O", 10, "OBLIGEATES").
dico("O", 10, "OBLIGERAIS").
dico("O", 10, "OBLIGERAIT").
dico("O", 10, "OBLIGERENT").
dico("O", 10, "OBLIGERIEZ").
dico("O", 10, "OBLIGERONS").
dico("O", 10, "OBLIGERONT").
dico("O", 10, "OBLIQUAMES").
dico("O", 10, "OBLIQUASSE").
dico("O", 10, "OBLIQUATES").
dico("O", 10, "OBLIQUERAI").
dico("O", 10, "OBLIQUERAS").
dico("O", 10, "OBLIQUEREZ").
dico("O", 10, "OBLIQUIONS").
dico("O", 10, "OBLIQUITES").
dico("O", 10, "OBLITERAIS").
dico("O", 10, "OBLITERAIT").
dico("O", 10, "OBLITERANT").
dico("O", 10, "OBLITEREES").
dico("O", 10, "OBLITERENT").
dico("O", 10, "OBLITERERA").
dico("O", 10, "OBLITERIEZ").
dico("O", 10, "OBLITERONS").
dico("O", 10, "OBNUBILAIS").
dico("O", 10, "OBNUBILAIT").
dico("O", 10, "OBNUBILANT").
dico("O", 10, "OBNUBILEES").
dico("O", 10, "OBNUBILENT").
dico("O", 10, "OBNUBILERA").
dico("O", 10, "OBNUBILIEZ").
dico("O", 10, "OBNUBILONS").
dico("O", 10, "OBOMBRAMES").
dico("O", 10, "OBOMBRASSE").
dico("O", 10, "OBOMBRATES").
dico("O", 10, "OBOMBRERAI").
dico("O", 10, "OBOMBRERAS").
dico("O", 10, "OBOMBREREZ").
dico("O", 10, "OBOMBRIONS").
dico("O", 10, "OBSCENITES").
dico("O", 10, "OBSCURCIES").
dico("O", 10, "OBSCURCIRA").
dico("O", 10, "OBSCURITES").
dico("O", 10, "OBSEDAIENT").
dico("O", 10, "OBSEDANTES").
dico("O", 10, "OBSEDASSES").
dico("O", 10, "OBSEDERAIS").
dico("O", 10, "OBSEDERAIT").
dico("O", 10, "OBSEDERENT").
dico("O", 10, "OBSEDERIEZ").
dico("O", 10, "OBSEDERONS").
dico("O", 10, "OBSEDERONT").
dico("O", 10, "OBSEQUENTE").
dico("O", 10, "OBSEQUENTS").
dico("O", 10, "OBSEQUIEUX").
dico("O", 10, "OBSERVABLE").
dico("O", 10, "OBSERVAMES").
dico("O", 10, "OBSERVANCE").
dico("O", 10, "OBSERVASSE").
dico("O", 10, "OBSERVATES").
dico("O", 10, "OBSERVERAI").
dico("O", 10, "OBSERVERAS").
dico("O", 10, "OBSERVEREZ").
dico("O", 10, "OBSERVIONS").
dico("O", 10, "OBSESSIONS").
dico("O", 10, "OBSESSIVES").
dico("O", 10, "OBSIDIENNE").
dico("O", 10, "OBSIDIONAL").
dico("O", 10, "OBSTINAMES").
dico("O", 10, "OBSTINASSE").
dico("O", 10, "OBSTINATES").
dico("O", 10, "OBSTINERAI").
dico("O", 10, "OBSTINERAS").
dico("O", 10, "OBSTINEREZ").
dico("O", 10, "OBSTINEURS").
dico("O", 10, "OBSTINEUSE").
dico("O", 10, "OBSTINIONS").
dico("O", 10, "OBSTRUAMES").
dico("O", 10, "OBSTRUASSE").
dico("O", 10, "OBSTRUATES").
dico("O", 10, "OBSTRUCTIF").
dico("O", 10, "OBSTRUERAI").
dico("O", 10, "OBSTRUERAS").
dico("O", 10, "OBSTRUEREZ").
dico("O", 10, "OBSTRUIONS").
dico("O", 10, "OBTEMPERAI").
dico("O", 10, "OBTEMPERAS").
dico("O", 10, "OBTEMPERAT").
dico("O", 10, "OBTEMPERER").
dico("O", 10, "OBTEMPERES").
dico("O", 10, "OBTEMPEREZ").
dico("O", 10, "OBTENAIENT").
dico("O", 10, "OBTENTIONS").
dico("O", 10, "OBTIENDRAI").
dico("O", 10, "OBTIENDRAS").
dico("O", 10, "OBTIENDREZ").
dico("O", 10, "OBTIENNENT").
dico("O", 10, "OBTINSSENT").
dico("O", 10, "OBTINSSIEZ").
dico("O", 10, "OBTURAIENT").
dico("O", 10, "OBTURASSES").
dico("O", 10, "OBTURATEUR").
dico("O", 10, "OBTURATION").
dico("O", 10, "OBTURERAIS").
dico("O", 10, "OBTURERAIT").
dico("O", 10, "OBTURERENT").
dico("O", 10, "OBTURERIEZ").
dico("O", 10, "OBTURERONS").
dico("O", 10, "OBTURERONT").
dico("O", 10, "OBTUSANGLE").
dico("O", 10, "OBVENAIENT").
dico("O", 10, "OBVIASSENT").
dico("O", 10, "OBVIASSIEZ").
dico("O", 10, "OBVIENDRAI").
dico("O", 10, "OBVIENDRAS").
dico("O", 10, "OBVIENDREZ").
dico("O", 10, "OBVIENNENT").
dico("O", 10, "OBVIERIONS").
dico("O", 10, "OBVINSSENT").
dico("O", 10, "OBVINSSIEZ").
dico("O", 10, "OBWALDIENS").
dico("O", 10, "OCCASIONNA").
dico("O", 10, "OCCASIONNE").
dico("O", 10, "OCCIDENTAL").
dico("O", 10, "OCCIPITALE").
dico("O", 10, "OCCIPITAUX").
dico("O", 10, "OCCLUAIENT").
dico("O", 10, "OCCLURIONS").
dico("O", 10, "OCCLUSALES").
dico("O", 10, "OCCLUSIONS").
dico("O", 10, "OCCLUSIVES").
dico("O", 10, "OCCLUSSENT").
dico("O", 10, "OCCLUSSIEZ").
dico("O", 10, "OCCULTAMES").
dico("O", 10, "OCCULTASSE").
dico("O", 10, "OCCULTATES").
dico("O", 10, "OCCULTERAI").
dico("O", 10, "OCCULTERAS").
dico("O", 10, "OCCULTEREZ").
dico("O", 10, "OCCULTIONS").
dico("O", 10, "OCCULTISME").
dico("O", 10, "OCCULTISTE").
dico("O", 10, "OCCUPAIENT").
dico("O", 10, "OCCUPANTES").
dico("O", 10, "OCCUPASSES").
dico("O", 10, "OCCUPATION").
dico("O", 10, "OCCUPERAIS").
dico("O", 10, "OCCUPERAIT").
dico("O", 10, "OCCUPERENT").
dico("O", 10, "OCCUPERIEZ").
dico("O", 10, "OCCUPERONS").
dico("O", 10, "OCCUPERONT").
dico("O", 10, "OCCURRENCE").
dico("O", 10, "OCCURRENTE").
dico("O", 10, "OCCURRENTS").
dico("O", 10, "OCEANAUTES").
dico("O", 10, "OCEANIENNE").
dico("O", 10, "OCEANIQUES").
dico("O", 10, "OCRASSIONS").
dico("O", 10, "OCRERAIENT").
dico("O", 10, "OCTANTIEME").
dico("O", 10, "OCTASTYLES").
dico("O", 10, "OCTAVIAMES").
dico("O", 10, "OCTAVIASSE").
dico("O", 10, "OCTAVIATES").
dico("O", 10, "OCTAVIERAI").
dico("O", 10, "OCTAVIERAS").
dico("O", 10, "OCTAVIEREZ").
dico("O", 10, "OCTAVIIONS").
dico("O", 10, "OCTAVONNES").
dico("O", 10, "OCTOGONALE").
dico("O", 10, "OCTOGONAUX").
dico("O", 10, "OCTOSTYLES").
dico("O", 10, "OCTROIERAI").
dico("O", 10, "OCTROIERAS").
dico("O", 10, "OCTROIEREZ").
dico("O", 10, "OCTROYAMES").
dico("O", 10, "OCTROYASSE").
dico("O", 10, "OCTROYATES").
dico("O", 10, "OCTROYIONS").
dico("O", 10, "OCTUPLAMES").
dico("O", 10, "OCTUPLASSE").
dico("O", 10, "OCTUPLATES").
dico("O", 10, "OCTUPLERAI").
dico("O", 10, "OCTUPLERAS").
dico("O", 10, "OCTUPLEREZ").
dico("O", 10, "OCTUPLIONS").
dico("O", 10, "OCULARISTE").
dico("O", 10, "OCULOGYRES").
dico("O", 10, "OCYTOCINES").
dico("O", 10, "ODALISQUES").
dico("O", 10, "ODOMETRIES").
dico("O", 10, "ODONTALGIE").
dico("O", 10, "ODONTOCETE").
dico("O", 10, "ODONTOIDES").
dico("O", 10, "ODORISAMES").
dico("O", 10, "ODORISANTS").
dico("O", 10, "ODORISASSE").
dico("O", 10, "ODORISATES").
dico("O", 10, "ODORISERAI").
dico("O", 10, "ODORISERAS").
dico("O", 10, "ODORISEREZ").
dico("O", 10, "ODORISEURS").
dico("O", 10, "ODORISIONS").
dico("O", 10, "OEDEMATEUX").
dico("O", 10, "OEDEMATIEE").
dico("O", 10, "OEDEMATIES").
dico("O", 10, "OEDICNEMES").
dico("O", 10, "OEDIPIENNE").
dico("O", 10, "OEILLETONS").
dico("O", 10, "OEILLETTES").
dico("O", 10, "OEKOUMENES").
dico("O", 10, "OENILISMES").
dico("O", 10, "OENOLIQUES").
dico("O", 10, "OENOLISMES").
dico("O", 10, "OENOLOGIES").
dico("O", 10, "OENOLOGUES").
dico("O", 10, "OENOMETRES").
dico("O", 10, "OENOMETRIE").
dico("O", 10, "OENOPHILES").
dico("O", 10, "OENOTHEQUE").
dico("O", 10, "OENOTHERAS").
dico("O", 10, "OENOTHERES").
dico("O", 10, "OESOPHAGES").
dico("O", 10, "OESTRADIOL").
dico("O", 10, "OESTROGENE").
dico("O", 10, "OEUVRAIENT").
dico("O", 10, "OEUVRASSES").
dico("O", 10, "OEUVRERAIS").
dico("O", 10, "OEUVRERAIT").
dico("O", 10, "OEUVRERENT").
dico("O", 10, "OEUVRERIEZ").
dico("O", 10, "OEUVRERONS").
dico("O", 10, "OEUVRERONT").
dico("O", 10, "OEUVRETTES").
dico("O", 10, "OFFENSAMES").
dico("O", 10, "OFFENSANTE").
dico("O", 10, "OFFENSANTS").
dico("O", 10, "OFFENSASSE").
dico("O", 10, "OFFENSATES").
dico("O", 10, "OFFENSERAI").
dico("O", 10, "OFFENSERAS").
dico("O", 10, "OFFENSEREZ").
dico("O", 10, "OFFENSEURS").
dico("O", 10, "OFFENSIONS").
dico("O", 10, "OFFENSIVES").
dico("O", 10, "OFFERTOIRE").
dico("O", 10, "OFFICIAMES").
dico("O", 10, "OFFICIANTE").
dico("O", 10, "OFFICIANTS").
dico("O", 10, "OFFICIASSE").
dico("O", 10, "OFFICIATES").
dico("O", 10, "OFFICIELLE").
dico("O", 10, "OFFICIERAI").
dico("O", 10, "OFFICIERAS").
dico("O", 10, "OFFICIERES").
dico("O", 10, "OFFICIEREZ").
dico("O", 10, "OFFICIEUSE").
dico("O", 10, "OFFICIIONS").
dico("O", 10, "OFFICINALE").
dico("O", 10, "OFFICINAUX").
dico("O", 10, "OFFRIRIONS").
dico("O", 10, "OFFRISSENT").
dico("O", 10, "OFFRISSIEZ").
dico("O", 10, "OFFUSQUAIS").
dico("O", 10, "OFFUSQUAIT").
dico("O", 10, "OFFUSQUANT").
dico("O", 10, "OFFUSQUEES").
dico("O", 10, "OFFUSQUENT").
dico("O", 10, "OFFUSQUERA").
dico("O", 10, "OFFUSQUIEZ").
dico("O", 10, "OFFUSQUONS").
dico("O", 10, "OGHAMIQUES").
dico("O", 10, "OIGNISSENT").
dico("O", 10, "OIGNISSIEZ").
dico("O", 10, "OIGNONADES").
dico("O", 10, "OIGNONIERE").
dico("O", 10, "OINDRAIENT").
dico("O", 10, "OISELAIENT").
dico("O", 10, "OISELASSES").
dico("O", 10, "OISELERENT").
dico("O", 10, "OISELEUSES").
dico("O", 10, "OISELIERES").
dico("O", 10, "OISELLERAI").
dico("O", 10, "OISELLERAS").
dico("O", 10, "OISELLEREZ").
dico("O", 10, "OISELLERIE").
dico("O", 10, "OISIVEMENT").
dico("O", 10, "OLEAGINEUX").
dico("O", 10, "OLECRANIEN").
dico("O", 10, "OLEFIANTES").
dico("O", 10, "OLEIFIANTE").
dico("O", 10, "OLEIFIANTS").
dico("O", 10, "OLEIFORMES").
dico("O", 10, "OLEOMETRES").
dico("O", 10, "OLEORESINE").
dico("O", 10, "OLERONAISE").
dico("O", 10, "OLFACTIONS").
dico("O", 10, "OLFACTIVES").
dico("O", 10, "OLIGARCHIE").
dico("O", 10, "OLIGARQUES").
dico("O", 10, "OLIGOCENES").
dico("O", 10, "OLIGOCHETE").
dico("O", 10, "OLIGOCLASE").
dico("O", 10, "OLIGOMERES").
dico("O", 10, "OLIGOPOLES").
dico("O", 10, "OLIGOPSONE").
dico("O", 10, "OLIVAISONS").
dico("O", 10, "OLIVERAIES").
dico("O", 10, "OLIVETAINE").
dico("O", 10, "OLIVETAINS").
dico("O", 10, "OLOGRAPHES").
dico("O", 10, "OLYMPIADES").
dico("O", 10, "OLYMPIENNE").
dico("O", 10, "OLYMPIQUES").
dico("O", 10, "OLYMPISMES").
dico("O", 10, "OMBELLALES").
dico("O", 10, "OMBELLULES").
dico("O", 10, "OMBILICALE").
dico("O", 10, "OMBILICAUX").
dico("O", 10, "OMBILIQUEE").
dico("O", 10, "OMBILIQUES").
dico("O", 10, "OMBRAGEAIS").
dico("O", 10, "OMBRAGEAIT").
dico("O", 10, "OMBRAGEANT").
dico("O", 10, "OMBRAGEONS").
dico("O", 10, "OMBRAGERAI").
dico("O", 10, "OMBRAGERAS").
dico("O", 10, "OMBRAGEREZ").
dico("O", 10, "OMBRAGEUSE").
dico("O", 10, "OMBRAGIONS").
dico("O", 10, "OMBRASSENT").
dico("O", 10, "OMBRASSIEZ").
dico("O", 10, "OMBRERIONS").
dico("O", 10, "OMBRIENNES").
dico("O", 10, "OMBUDSMANS").
dico("O", 10, "OMETTAIENT").
dico("O", 10, "OMETTRIONS").
dico("O", 10, "OMMATIDIES").
dico("O", 10, "OMNICOLORE").
dico("O", 10, "OMNIPOTENT").
dico("O", 10, "OMNISCIENT").
dico("O", 10, "OMNISPORTS").
dico("O", 10, "ONAGRACEES").
dico("O", 10, "ONAGRAIRES").
dico("O", 10, "ONAGRARIEE").
dico("O", 10, "ONCOLOGIES").
dico("O", 10, "ONCOLOGUES").
dico("O", 10, "ONCOTIQUES").
dico("O", 10, "ONCTUEUSES").
dico("O", 10, "ONCTUOSITE").
dico("O", 10, "ONDEMETRES").
dico("O", 10, "ONDINISMES").
dico("O", 10, "ONDOIEMENT").
dico("O", 10, "ONDOIERAIS").
dico("O", 10, "ONDOIERAIT").
dico("O", 10, "ONDOIERIEZ").
dico("O", 10, "ONDOIERONS").
dico("O", 10, "ONDOIERONT").
dico("O", 10, "ONDOYAIENT").
dico("O", 10, "ONDOYANTES").
dico("O", 10, "ONDOYASSES").
dico("O", 10, "ONDOYERENT").
dico("O", 10, "ONDULAIENT").
dico("O", 10, "ONDULANTES").
dico("O", 10, "ONDULASSES").
dico("O", 10, "ONDULATION").
dico("O", 10, "ONDULERAIS").
dico("O", 10, "ONDULERAIT").
dico("O", 10, "ONDULERENT").
dico("O", 10, "ONDULERIEZ").
dico("O", 10, "ONDULERONS").
dico("O", 10, "ONDULERONT").
dico("O", 10, "ONDULEUSES").
dico("O", 10, "ONGUICULEE").
dico("O", 10, "ONGUICULES").
dico("O", 10, "ONGUIFORME").
dico("O", 10, "ONIROGENES").
dico("O", 10, "ONIROLOGIE").
dico("O", 10, "ONIROLOGUE").
dico("O", 10, "ONKOTIQUES").
dico("O", 10, "ONOMATOPEE").
dico("O", 10, "ONTARIENNE").
dico("O", 10, "ONTOGENESE").
dico("O", 10, "ONTOGENIES").
dico("O", 10, "ONTOLOGIES").
dico("O", 10, "ONUSIENNES").
dico("O", 10, "OOLITHIQUE").
dico("O", 10, "OPACIFIAIS").
dico("O", 10, "OPACIFIAIT").
dico("O", 10, "OPACIFIANT").
dico("O", 10, "OPACIFIEES").
dico("O", 10, "OPACIFIENT").
dico("O", 10, "OPACIFIERA").
dico("O", 10, "OPACIFIIEZ").
dico("O", 10, "OPACIFIONS").
dico("O", 10, "OPACIMETRE").
dico("O", 10, "OPALESCENT").
dico("O", 10, "OPALISAMES").
dico("O", 10, "OPALISASSE").
dico("O", 10, "OPALISATES").
dico("O", 10, "OPALISERAI").
dico("O", 10, "OPALISERAS").
dico("O", 10, "OPALISEREZ").
dico("O", 10, "OPALISIONS").
dico("O", 10, "OPENFIELDS").
dico("O", 10, "OPERASSENT").
dico("O", 10, "OPERASSIEZ").
dico("O", 10, "OPERATEURS").
dico("O", 10, "OPERATIONS").
dico("O", 10, "OPERATIQUE").
dico("O", 10, "OPERATOIRE").
dico("O", 10, "OPERATRICE").
dico("O", 10, "OPERCULEES").
dico("O", 10, "OPERERIONS").
dico("O", 10, "OPHICLEIDE").
dico("O", 10, "OPHIDIENNE").
dico("O", 10, "OPHIOLITES").
dico("O", 10, "OPHIOLOGIE").
dico("O", 10, "OPHIOPHAGE").
dico("O", 10, "OPHIURIDES").
dico("O", 10, "OPHTALMIES").
dico("O", 10, "OPIACAIENT").
dico("O", 10, "OPIACASSES").
dico("O", 10, "OPIACERAIS").
dico("O", 10, "OPIACERAIT").
dico("O", 10, "OPIACERENT").
dico("O", 10, "OPIACERIEZ").
dico("O", 10, "OPIACERONS").
dico("O", 10, "OPIACERONT").
dico("O", 10, "OPINASSENT").
dico("O", 10, "OPINASSIEZ").
dico("O", 10, "OPINERIONS").
dico("O", 10, "OPINIATRAI").
dico("O", 10, "OPINIATRAS").
dico("O", 10, "OPINIATRAT").
dico("O", 10, "OPINIATREE").
dico("O", 10, "OPINIATRER").
dico("O", 10, "OPINIATRES").
dico("O", 10, "OPINIATREZ").
dico("O", 10, "OPIOMANIES").
dico("O", 10, "OPODELDOCH").
dico("O", 10, "OPONTIACEE").
dico("O", 10, "OPPORTUNES").
dico("O", 10, "OPPOSABLES").
dico("O", 10, "OPPOSAIENT").
dico("O", 10, "OPPOSANTES").
dico("O", 10, "OPPOSASSES").
dico("O", 10, "OPPOSERAIS").
dico("O", 10, "OPPOSERAIT").
dico("O", 10, "OPPOSERENT").
dico("O", 10, "OPPOSERIEZ").
dico("O", 10, "OPPOSERONS").
dico("O", 10, "OPPOSERONT").
dico("O", 10, "OPPOSITION").
dico("O", 10, "OPPRESSAIS").
dico("O", 10, "OPPRESSAIT").
dico("O", 10, "OPPRESSANT").
dico("O", 10, "OPPRESSEES").
dico("O", 10, "OPPRESSENT").
dico("O", 10, "OPPRESSERA").
dico("O", 10, "OPPRESSEUR").
dico("O", 10, "OPPRESSIEZ").
dico("O", 10, "OPPRESSIFS").
dico("O", 10, "OPPRESSION").
dico("O", 10, "OPPRESSIVE").
dico("O", 10, "OPPRESSONS").
dico("O", 10, "OPPRIMAMES").
dico("O", 10, "OPPRIMANTE").
dico("O", 10, "OPPRIMANTS").
dico("O", 10, "OPPRIMASSE").
dico("O", 10, "OPPRIMATES").
dico("O", 10, "OPPRIMERAI").
dico("O", 10, "OPPRIMERAS").
dico("O", 10, "OPPRIMEREZ").
dico("O", 10, "OPPRIMIONS").
dico("O", 10, "OPSOMANIES").
dico("O", 10, "OPSONIQUES").
dico("O", 10, "OPTASSIONS").
dico("O", 10, "OPTERAIENT").
dico("O", 10, "OPTICIENNE").
dico("O", 10, "OPTIMALISA").
dico("O", 10, "OPTIMALISE").
dico("O", 10, "OPTIMISAIS").
dico("O", 10, "OPTIMISAIT").
dico("O", 10, "OPTIMISANT").
dico("O", 10, "OPTIMISEES").
dico("O", 10, "OPTIMISENT").
dico("O", 10, "OPTIMISERA").
dico("O", 10, "OPTIMISIEZ").
dico("O", 10, "OPTIMISMES").
dico("O", 10, "OPTIMISONS").
dico("O", 10, "OPTIMISTES").
dico("O", 10, "OPTIONNELS").
dico("O", 10, "OPTOMETRES").
dico("O", 10, "OPTOMETRIE").
dico("O", 10, "OPTRONIQUE").
dico("O", 10, "OPUNTIALES").
dico("O", 10, "ORALISAMES").
dico("O", 10, "ORALISASSE").
dico("O", 10, "ORALISATES").
dico("O", 10, "ORALISERAI").
dico("O", 10, "ORALISERAS").
dico("O", 10, "ORALISEREZ").
dico("O", 10, "ORALISIONS").
dico("O", 10, "ORANGEADES").
dico("O", 10, "ORANGEAMES").
dico("O", 10, "ORANGEASSE").
dico("O", 10, "ORANGEATES").
dico("O", 10, "ORANGERAIE").
dico("O", 10, "ORANGERAIS").
dico("O", 10, "ORANGERAIT").
dico("O", 10, "ORANGERENT").
dico("O", 10, "ORANGERIES").
dico("O", 10, "ORANGERIEZ").
dico("O", 10, "ORANGERONS").
dico("O", 10, "ORANGERONT").
dico("O", 10, "ORANGETTES").
dico("O", 10, "ORANGISMES").
dico("O", 10, "ORANGISTES").
dico("O", 10, "ORATORIENS").
dico("O", 10, "ORBITAIENT").
dico("O", 10, "ORBITAIRES").
dico("O", 10, "ORBITASSES").
dico("O", 10, "ORBITERAIS").
dico("O", 10, "ORBITERAIT").
dico("O", 10, "ORBITERENT").
dico("O", 10, "ORBITERIEZ").
dico("O", 10, "ORBITERONS").
dico("O", 10, "ORBITERONT").
dico("O", 10, "ORCANETTES").
dico("O", 10, "ORCHESTRAI").
dico("O", 10, "ORCHESTRAL").
dico("O", 10, "ORCHESTRAS").
dico("O", 10, "ORCHESTRAT").
dico("O", 10, "ORCHESTREE").
dico("O", 10, "ORCHESTRER").
dico("O", 10, "ORCHESTRES").
dico("O", 10, "ORCHESTREZ").
dico("O", 10, "ORCHIALGIE").
dico("O", 10, "ORCHIDACEE").
dico("O", 10, "ORCHIDALES").
dico("O", 10, "ORDALIQUES").
dico("O", 10, "ORDINAIRES").
dico("O", 10, "ORDINARIAT").
dico("O", 10, "ORDINATEUR").
dico("O", 10, "ORDINATION").
dico("O", 10, "ORDONNABLE").
dico("O", 10, "ORDONNAMES").
dico("O", 10, "ORDONNANCA").
dico("O", 10, "ORDONNANCE").
dico("O", 10, "ORDONNASSE").
dico("O", 10, "ORDONNATES").
dico("O", 10, "ORDONNERAI").
dico("O", 10, "ORDONNERAS").
dico("O", 10, "ORDONNEREZ").
dico("O", 10, "ORDONNIONS").
dico("O", 10, "ORDOVICIEN").
dico("O", 10, "ORDURIERES").
dico("O", 10, "OREILLARDE").
dico("O", 10, "OREILLARDS").
dico("O", 10, "OREILLETTE").
dico("O", 10, "ORFEVRERIE").
dico("O", 10, "ORGANELLES").
dico("O", 10, "ORGANICIEN").
dico("O", 10, "ORGANIERES").
dico("O", 10, "ORGANIQUES").
dico("O", 10, "ORGANISAIS").
dico("O", 10, "ORGANISAIT").
dico("O", 10, "ORGANISANT").
dico("O", 10, "ORGANISEES").
dico("O", 10, "ORGANISENT").
dico("O", 10, "ORGANISERA").
dico("O", 10, "ORGANISEUR").
dico("O", 10, "ORGANISIEZ").
dico("O", 10, "ORGANISMES").
dico("O", 10, "ORGANISONS").
dico("O", 10, "ORGANISTES").
dico("O", 10, "ORGANOSOLS").
dico("O", 10, "ORGANSINAI").
dico("O", 10, "ORGANSINAS").
dico("O", 10, "ORGANSINAT").
dico("O", 10, "ORGANSINEE").
dico("O", 10, "ORGANSINER").
dico("O", 10, "ORGANSINES").
dico("O", 10, "ORGANSINEZ").
dico("O", 10, "ORGASMIQUE").
dico("O", 10, "ORGASTIQUE").
dico("O", 10, "ORICHALQUE").
dico("O", 10, "ORIENTABLE").
dico("O", 10, "ORIENTALES").
dico("O", 10, "ORIENTAMES").
dico("O", 10, "ORIENTASSE").
dico("O", 10, "ORIENTATES").
dico("O", 10, "ORIENTERAI").
dico("O", 10, "ORIENTERAS").
dico("O", 10, "ORIENTEREZ").
dico("O", 10, "ORIENTEURS").
dico("O", 10, "ORIENTEUSE").
dico("O", 10, "ORIENTIONS").
dico("O", 10, "ORIFLAMMES").
dico("O", 10, "ORIGINAIRE").
dico("O", 10, "ORIGINALES").
dico("O", 10, "ORIGINAMES").
dico("O", 10, "ORIGINASSE").
dico("O", 10, "ORIGINATES").
dico("O", 10, "ORIGINELLE").
dico("O", 10, "ORIGINERAI").
dico("O", 10, "ORIGINERAS").
dico("O", 10, "ORIGINEREZ").
dico("O", 10, "ORIGINIONS").
dico("O", 10, "ORLEANAISE").
dico("O", 10, "ORLEANISME").
dico("O", 10, "ORLEANISTE").
dico("O", 10, "ORNASSIONS").
dico("O", 10, "ORNEMENTAI").
dico("O", 10, "ORNEMENTAL").
dico("O", 10, "ORNEMENTAS").
dico("O", 10, "ORNEMENTAT").
dico("O", 10, "ORNEMENTEE").
dico("O", 10, "ORNEMENTER").
dico("O", 10, "ORNEMENTES").
dico("O", 10, "ORNEMENTEZ").
dico("O", 10, "ORNERAIENT").
dico("O", 10, "ORNIERAGES").
dico("O", 10, "ORNITHOSES").
dico("O", 10, "OROBANCHES").
dico("O", 10, "OROGENESES").
dico("O", 10, "OROGENIQUE").
dico("O", 10, "OROGRAPHIE").
dico("O", 10, "OROMETRIES").
dico("O", 10, "OROPHARYNX").
dico("O", 10, "ORPAILLAGE").
dico("O", 10, "ORPAILLEUR").
dico("O", 10, "ORPHELINAT").
dico("O", 10, "ORPHELINES").
dico("O", 10, "ORTHODOXES").
dico("O", 10, "ORTHODOXIE").
dico("O", 10, "ORTHOEPIES").
dico("O", 10, "ORTHOGENIE").
dico("O", 10, "ORTHOGONAL").
dico("O", 10, "ORTHONORME").
dico("O", 10, "ORTHOPEDIE").
dico("O", 10, "ORTHOPNEES").
dico("O", 10, "ORTHOPTERE").
dico("O", 10, "ORTHOPTIES").
dico("O", 10, "ORTHOSTATE").
dico("O", 10, "ORTHOTROPE").
dico("O", 10, "ORYCTEROPE").
dico("O", 10, "OSCABRIONS").
dico("O", 10, "OSCILLAIRE").
dico("O", 10, "OSCILLAMES").
dico("O", 10, "OSCILLANTE").
dico("O", 10, "OSCILLANTS").
dico("O", 10, "OSCILLASSE").
dico("O", 10, "OSCILLATES").
dico("O", 10, "OSCILLERAI").
dico("O", 10, "OSCILLERAS").
dico("O", 10, "OSCILLEREZ").
dico("O", 10, "OSCILLIONS").
dico("O", 10, "OSCULATEUR").
dico("O", 10, "OSCULATION").
dico("O", 10, "OSMOMETRES").
dico("O", 10, "OSMOTIQUES").
dico("O", 10, "OSSIANIQUE").
dico("O", 10, "OSSIANISME").
dico("O", 10, "OSSIFIAMES").
dico("O", 10, "OSSIFIASSE").
dico("O", 10, "OSSIFIATES").
dico("O", 10, "OSSIFIERAI").
dico("O", 10, "OSSIFIERAS").
dico("O", 10, "OSSIFIEREZ").
dico("O", 10, "OSSIFIIONS").
dico("O", 10, "OSTEALGIES").
dico("O", 10, "OSTENDAISE").
dico("O", 10, "OSTENSIBLE").
dico("O", 10, "OSTENSIVES").
dico("O", 10, "OSTENSOIRS").
dico("O", 10, "OSTEOCYTES").
dico("O", 10, "OSTEOGENES").
dico("O", 10, "OSTEOGENIE").
dico("O", 10, "OSTEOLOGIE").
dico("O", 10, "OSTEOLYSES").
dico("O", 10, "OSTEOPATHE").
dico("O", 10, "OSTEOPHYTE").
dico("O", 10, "OSTEOTOMIE").
dico("O", 10, "OSTRACISAI").
dico("O", 10, "OSTRACISAS").
dico("O", 10, "OSTRACISAT").
dico("O", 10, "OSTRACISEE").
dico("O", 10, "OSTRACISER").
dico("O", 10, "OSTRACISES").
dico("O", 10, "OSTRACISEZ").
dico("O", 10, "OSTRACISME").
dico("O", 10, "OSTRACODES").
dico("O", 10, "OSTREICOLE").
dico("O", 10, "OSTROGOTES").
dico("O", 10, "OSTROGOTHE").
dico("O", 10, "OSTROGOTHS").
dico("O", 10, "OTALGIQUES").
dico("O", 10, "OTOLOGIQUE").
dico("O", 10, "OTORRAGIES").
dico("O", 10, "OTOSCOPIES").
dico("O", 10, "OTTONIENNE").
dico("O", 10, "OUAGALAISE").
dico("O", 10, "OUANANICHE").
dico("O", 10, "OUAOUARONS").
dico("O", 10, "OUATASSENT").
dico("O", 10, "OUATASSIEZ").
dico("O", 10, "OUATERIONS").
dico("O", 10, "OUATINAMES").
dico("O", 10, "OUATINASSE").
dico("O", 10, "OUATINATES").
dico("O", 10, "OUATINERAI").
dico("O", 10, "OUATINERAS").
dico("O", 10, "OUATINEREZ").
dico("O", 10, "OUATINIONS").
dico("O", 10, "OUBLIABLES").
dico("O", 10, "OUBLIAIENT").
dico("O", 10, "OUBLIASSES").
dico("O", 10, "OUBLIERAIS").
dico("O", 10, "OUBLIERAIT").
dico("O", 10, "OUBLIERENT").
dico("O", 10, "OUBLIERIEZ").
dico("O", 10, "OUBLIERONS").
dico("O", 10, "OUBLIERONT").
dico("O", 10, "OUBLIETTES").
dico("O", 10, "OUBLIEUSES").
dico("O", 10, "OUGANDAISE").
dico("O", 10, "OUGRIENNES").
dico("O", 10, "OUILLAIENT").
dico("O", 10, "OUILLASSES").
dico("O", 10, "OUILLERAIS").
dico("O", 10, "OUILLERAIT").
dico("O", 10, "OUILLERENT").
dico("O", 10, "OUILLERIEZ").
dico("O", 10, "OUILLERONS").
dico("O", 10, "OUILLERONT").
dico("O", 10, "OUILLIERES").
dico("O", 10, "OULIPIENNE").
dico("O", 10, "OURALIENNE").
dico("O", 10, "OURDIRIONS").
dico("O", 10, "OURDISSAGE").
dico("O", 10, "OURDISSAIS").
dico("O", 10, "OURDISSAIT").
dico("O", 10, "OURDISSANT").
dico("O", 10, "OURDISSENT").
dico("O", 10, "OURDISSEUR").
dico("O", 10, "OURDISSIEZ").
dico("O", 10, "OURDISSOIR").
dico("O", 10, "OURDISSONS").
dico("O", 10, "OURLASSENT").
dico("O", 10, "OURLASSIEZ").
dico("O", 10, "OURLERIONS").
dico("O", 10, "OURLIENNES").
dico("O", 10, "OUSTACHIES").
dico("O", 10, "OUTAOUAISE").
dico("O", 10, "OUTARDEAUX").
dico("O", 10, "OUTILLAGES").
dico("O", 10, "OUTILLAMES").
dico("O", 10, "OUTILLASSE").
dico("O", 10, "OUTILLATES").
dico("O", 10, "OUTILLERAI").
dico("O", 10, "OUTILLERAS").
dico("O", 10, "OUTILLEREZ").
dico("O", 10, "OUTILLEURS").
dico("O", 10, "OUTILLIONS").
dico("O", 10, "OUTRAGEAIS").
dico("O", 10, "OUTRAGEAIT").
dico("O", 10, "OUTRAGEANT").
dico("O", 10, "OUTRAGEONS").
dico("O", 10, "OUTRAGERAI").
dico("O", 10, "OUTRAGERAS").
dico("O", 10, "OUTRAGEREZ").
dico("O", 10, "OUTRAGEUSE").
dico("O", 10, "OUTRAGIONS").
dico("O", 10, "OUTRANCIER").
dico("O", 10, "OUTRASSENT").
dico("O", 10, "OUTRASSIEZ").
dico("O", 10, "OUTREPASSA").
dico("O", 10, "OUTREPASSE").
dico("O", 10, "OUTRERIONS").
dico("O", 10, "OUTRIGGERS").
dico("O", 10, "OUVERTURES").
dico("O", 10, "OUVRAGEAIS").
dico("O", 10, "OUVRAGEAIT").
dico("O", 10, "OUVRAGEANT").
dico("O", 10, "OUVRAGEONS").
dico("O", 10, "OUVRAGERAI").
dico("O", 10, "OUVRAGERAS").
dico("O", 10, "OUVRAGEREZ").
dico("O", 10, "OUVRAGIONS").
dico("O", 10, "OUVRAISONS").
dico("O", 10, "OUVRASSENT").
dico("O", 10, "OUVRASSIEZ").
dico("O", 10, "OUVRERIONS").
dico("O", 10, "OUVRIRIONS").
dico("O", 10, "OUVRISSENT").
dico("O", 10, "OUVRISSIEZ").
dico("O", 10, "OVALBUMINE").
dico("O", 10, "OVALISAMES").
dico("O", 10, "OVALISASSE").
dico("O", 10, "OVALISATES").
dico("O", 10, "OVALISERAI").
dico("O", 10, "OVALISERAS").
dico("O", 10, "OVALISEREZ").
dico("O", 10, "OVALISIONS").
dico("O", 10, "OVARIENNES").
dico("O", 10, "OVATIONNAI").
dico("O", 10, "OVATIONNAS").
dico("O", 10, "OVATIONNAT").
dico("O", 10, "OVATIONNEE").
dico("O", 10, "OVATIONNER").
dico("O", 10, "OVATIONNES").
dico("O", 10, "OVATIONNEZ").
dico("O", 10, "OVERDRIVES").
dico("O", 10, "OVIPARITES").
dico("O", 10, "OVISCAPTES").
dico("O", 10, "OVOGENESES").
dico("O", 10, "OVULASSENT").
dico("O", 10, "OVULASSIEZ").
dico("O", 10, "OVULATIONS").
dico("O", 10, "OVULATOIRE").
dico("O", 10, "OVULERIONS").
dico("O", 10, "OXFORDIENS").
dico("O", 10, "OXHYDRIQUE").
dico("O", 10, "OXHYDRYLES").
dico("O", 10, "OXONIENNES").
dico("O", 10, "OXYCARBONE").
dico("O", 10, "OXYCOUPAGE").
dico("O", 10, "OXYCOUPEUR").
dico("O", 10, "OXYDASSENT").
dico("O", 10, "OXYDASSIEZ").
dico("O", 10, "OXYDATIONS").
dico("O", 10, "OXYDERIONS").
dico("O", 10, "OXYGENABLE").
dico("O", 10, "OXYGENAMES").
dico("O", 10, "OXYGENANTE").
dico("O", 10, "OXYGENANTS").
dico("O", 10, "OXYGENASES").
dico("O", 10, "OXYGENASSE").
dico("O", 10, "OXYGENATES").
dico("O", 10, "OXYGENERAI").
dico("O", 10, "OXYGENERAS").
dico("O", 10, "OXYGENEREZ").
dico("O", 10, "OXYGENIONS").
dico("O", 10, "OXYMETRIES").
dico("O", 10, "OXYSULFURE").
dico("O", 10, "OZOCERITES").
dico("O", 10, "OZOKERITES").
dico("O", 10, "OZONASSENT").
dico("O", 10, "OZONASSIEZ").
dico("O", 10, "OZONATEURS").
dico("O", 10, "OZONATIONS").
dico("O", 10, "OZONERIONS").
dico("O", 10, "OZONISAMES").
dico("O", 10, "OZONISASSE").
dico("O", 10, "OZONISATES").
dico("O", 10, "OZONISERAI").
dico("O", 10, "OZONISERAS").
dico("O", 10, "OZONISEREZ").
dico("O", 10, "OZONISEURS").
dico("O", 10, "OZONISIONS").
