dico("O", 5, "OASIS").
dico("O", 5, "OBEIE").
dico("O", 5, "OBEIR").
dico("O", 5, "OBEIS").
dico("O", 5, "OBEIT").
dico("O", 5, "OBELE").
dico("O", 5, "OBELS").
dico("O", 5, "OBERA").
dico("O", 5, "OBERE").
dico("O", 5, "OBESE").
dico("O", 5, "OBIER").
dico("O", 5, "OBITS").
dico("O", 5, "OBJET").
dico("O", 5, "OBLAT").
dico("O", 5, "OBOLE").
dico("O", 5, "OBTUS").
dico("O", 5, "OBVIA").
dico("O", 5, "OBVIE").
dico("O", 5, "OCCIS").
dico("O", 5, "OCEAN").
dico("O", 5, "OCRAI").
dico("O", 5, "OCRAS").
dico("O", 5, "OCRAT").
dico("O", 5, "OCREE").
dico("O", 5, "OCRER").
dico("O", 5, "OCRES").
dico("O", 5, "OCREZ").
dico("O", 5, "OCTAL").
dico("O", 5, "OCTET").
dico("O", 5, "OCULE").
dico("O", 5, "OCULI").
dico("O", 5, "ODEON").
dico("O", 5, "ODEUR").
dico("O", 5, "OEILS").
dico("O", 5, "OEUFS").
dico("O", 5, "OEUVE").
dico("O", 5, "OFFRE").
dico("O", 5, "OFLAG").
dico("O", 5, "OGAMS").
dico("O", 5, "OGHAM").
dico("O", 5, "OGIVE").
dico("O", 5, "OGRES").
dico("O", 5, "OIDIE").
dico("O", 5, "OIGNE").
dico("O", 5, "OILLE").
dico("O", 5, "OINGS").
dico("O", 5, "OINTE").
dico("O", 5, "OINTS").
dico("O", 5, "OISIF").
dico("O", 5, "OISON").
dico("O", 5, "OKAPI").
dico("O", 5, "OLEUM").
dico("O", 5, "OLIVE").
dico("O", 5, "OMBLE").
dico("O", 5, "OMBRA").
dico("O", 5, "OMBRE").
dico("O", 5, "OMEGA").
dico("O", 5, "OMETS").
dico("O", 5, "OMISE").
dico("O", 5, "ONCES").
dico("O", 5, "ONCLE").
dico("O", 5, "ONDEE").
dico("O", 5, "ONDES").
dico("O", 5, "ONDIN").
dico("O", 5, "ONGLE").
dico("O", 5, "ONLAY").
dico("O", 5, "OPALE").
dico("O", 5, "OPENS").
dico("O", 5, "OPERA").
dico("O", 5, "OPERE").
dico("O", 5, "OPIAT").
dico("O", 5, "OPINA").
dico("O", 5, "OPINE").
dico("O", 5, "OPIUM").
dico("O", 5, "OPTAI").
dico("O", 5, "OPTAS").
dico("O", 5, "OPTAT").
dico("O", 5, "OPTER").
dico("O", 5, "OPTES").
dico("O", 5, "OPTEZ").
dico("O", 5, "ORAGE").
dico("O", 5, "ORALE").
dico("O", 5, "ORANT").
dico("O", 5, "ORAUX").
dico("O", 5, "ORBES").
dico("O", 5, "ORDIS").
dico("O", 5, "ORDRE").
dico("O", 5, "OREES").
dico("O", 5, "ORGES").
dico("O", 5, "ORGIE").
dico("O", 5, "ORGUE").
dico("O", 5, "ORIEL").
dico("O", 5, "ORINS").
dico("O", 5, "ORIYA").
dico("O", 5, "ORLES").
dico("O", 5, "ORLON").
dico("O", 5, "ORMES").
dico("O", 5, "ORMET").
dico("O", 5, "ORNAI").
dico("O", 5, "ORNAS").
dico("O", 5, "ORNAT").
dico("O", 5, "ORNEE").
dico("O", 5, "ORNER").
dico("O", 5, "ORNES").
dico("O", 5, "ORNEZ").
dico("O", 5, "OROBE").
dico("O", 5, "ORPIN").
dico("O", 5, "ORQUE").
dico("O", 5, "ORTIE").
dico("O", 5, "ORVET").
dico("O", 5, "OSAIS").
dico("O", 5, "OSAIT").
dico("O", 5, "OSANT").
dico("O", 5, "OSCAR").
dico("O", 5, "OSEES").
dico("O", 5, "OSENT").
dico("O", 5, "OSERA").
dico("O", 5, "OSIDE").
dico("O", 5, "OSIER").
dico("O", 5, "OSIEZ").
dico("O", 5, "OSONS").
dico("O", 5, "OSQUE").
dico("O", 5, "OSSUE").
dico("O", 5, "OSSUS").
dico("O", 5, "OSTOS").
dico("O", 5, "OTAGE").
dico("O", 5, "OTAIS").
dico("O", 5, "OTAIT").
dico("O", 5, "OTANT").
dico("O", 5, "OTEES").
dico("O", 5, "OTENT").
dico("O", 5, "OTERA").
dico("O", 5, "OTIEZ").
dico("O", 5, "OTITE").
dico("O", 5, "OTOMI").
dico("O", 5, "OTONS").
dico("O", 5, "OUAIS").
dico("O", 5, "OUATA").
dico("O", 5, "OUATE").
dico("O", 5, "OUBLI").
dico("O", 5, "OUCHE").
dico("O", 5, "OUEDS").
dico("O", 5, "OUEST").
dico("O", 5, "OUIES").
dico("O", 5, "OUNCE").
dico("O", 5, "OURDI").
dico("O", 5, "OURLA").
dico("O", 5, "OURLE").
dico("O", 5, "OURSE").
dico("O", 5, "OUSTE").
dico("O", 5, "OUTIL").
dico("O", 5, "OUTRA").
dico("O", 5, "OUTRE").
dico("O", 5, "OUVRA").
dico("O", 5, "OUVRE").
dico("O", 5, "OUZOS").
dico("O", 5, "OVALE").
dico("O", 5, "OVATE").
dico("O", 5, "OVEES").
dico("O", 5, "OVIDE").
dico("O", 5, "OVINE").
dico("O", 5, "OVINS").
dico("O", 5, "OVNIS").
dico("O", 5, "OVULA").
dico("O", 5, "OVULE").
dico("O", 5, "OXERS").
dico("O", 5, "OXIME").
dico("O", 5, "OXYDA").
dico("O", 5, "OXYDE").
dico("O", 5, "OYANT").
dico("O", 5, "OYATS").
dico("O", 5, "OZENE").
dico("O", 5, "OZONA").
dico("O", 5, "OZONE").
