dico("O", 6, "OASIEN").
dico("O", 6, "OBEIES").
dico("O", 6, "OBEIRA").
dico("O", 6, "OBELES").
dico("O", 6, "OBERAI").
dico("O", 6, "OBERAS").
dico("O", 6, "OBERAT").
dico("O", 6, "OBEREE").
dico("O", 6, "OBERER").
dico("O", 6, "OBERES").
dico("O", 6, "OBEREZ").
dico("O", 6, "OBESES").
dico("O", 6, "OBIERS").
dico("O", 6, "OBJETS").
dico("O", 6, "OBLADE").
dico("O", 6, "OBLATE").
dico("O", 6, "OBLATS").
dico("O", 6, "OBLIGE").
dico("O", 6, "OBLONG").
dico("O", 6, "OBOLES").
dico("O", 6, "OBSCUR").
dico("O", 6, "OBSEDA").
dico("O", 6, "OBSEDE").
dico("O", 6, "OBTENU").
dico("O", 6, "OBTINS").
dico("O", 6, "OBTINT").
dico("O", 6, "OBTURA").
dico("O", 6, "OBTURE").
dico("O", 6, "OBTUSE").
dico("O", 6, "OBVENU").
dico("O", 6, "OBVERS").
dico("O", 6, "OBVIAI").
dico("O", 6, "OBVIAS").
dico("O", 6, "OBVIAT").
dico("O", 6, "OBVIER").
dico("O", 6, "OBVIES").
dico("O", 6, "OBVIEZ").
dico("O", 6, "OBVINS").
dico("O", 6, "OBVINT").
dico("O", 6, "OCCASE").
dico("O", 6, "OCCIRE").
dico("O", 6, "OCCISE").
dico("O", 6, "OCCLUE").
dico("O", 6, "OCCLUS").
dico("O", 6, "OCCLUT").
dico("O", 6, "OCCUPA").
dico("O", 6, "OCCUPE").
dico("O", 6, "OCEANE").
dico("O", 6, "OCEANS").
dico("O", 6, "OCELLE").
dico("O", 6, "OCELOT").
dico("O", 6, "OCRAIS").
dico("O", 6, "OCRAIT").
dico("O", 6, "OCRANT").
dico("O", 6, "OCREES").
dico("O", 6, "OCRENT").
dico("O", 6, "OCRERA").
dico("O", 6, "OCREUX").
dico("O", 6, "OCRIEZ").
dico("O", 6, "OCRONS").
dico("O", 6, "OCTALE").
dico("O", 6, "OCTANE").
dico("O", 6, "OCTANT").
dico("O", 6, "OCTAUX").
dico("O", 6, "OCTAVE").
dico("O", 6, "OCTAVO").
dico("O", 6, "OCTETS").
dico("O", 6, "OCTIDI").
dico("O", 6, "OCTROI").
dico("O", 6, "OCTUOR").
dico("O", 6, "OCULEE").
dico("O", 6, "OCULES").
dico("O", 6, "OCULUS").
dico("O", 6, "ODEONS").
dico("O", 6, "ODEURS").
dico("O", 6, "ODIEUX").
dico("O", 6, "ODORAT").
dico("O", 6, "OEDEME").
dico("O", 6, "OEDIPE").
dico("O", 6, "OESTRE").
dico("O", 6, "OEUVEE").
dico("O", 6, "OEUVES").
dico("O", 6, "OEUVRA").
dico("O", 6, "OEUVRE").
dico("O", 6, "OFFERT").
dico("O", 6, "OFFICE").
dico("O", 6, "OFFRES").
dico("O", 6, "OFFREZ").
dico("O", 6, "OFFRIR").
dico("O", 6, "OFFRIS").
dico("O", 6, "OFFRIT").
dico("O", 6, "OFFSET").
dico("O", 6, "OFLAGS").
dico("O", 6, "OGHAMS").
dico("O", 6, "OGIVAL").
dico("O", 6, "OGIVES").
dico("O", 6, "OIDIES").
dico("O", 6, "OIDIUM").
dico("O", 6, "OIGNES").
dico("O", 6, "OIGNEZ").
dico("O", 6, "OIGNIS").
dico("O", 6, "OIGNIT").
dico("O", 6, "OIGNON").
dico("O", 6, "OILLES").
dico("O", 6, "OINDRA").
dico("O", 6, "OINDRE").
dico("O", 6, "OINTES").
dico("O", 6, "OISEAU").
dico("O", 6, "OISELA").
dico("O", 6, "OISELE").
dico("O", 6, "OISEUX").
dico("O", 6, "OISIFS").
dico("O", 6, "OISIVE").
dico("O", 6, "OISONS").
dico("O", 6, "OKAPIS").
dico("O", 6, "OKOUME").
dico("O", 6, "OLEATE").
dico("O", 6, "OLEINE").
dico("O", 6, "OLEUMS").
dico("O", 6, "OLIBAN").
dico("O", 6, "OLIVES").
dico("O", 6, "OLIVET").
dico("O", 6, "OLYMPE").
dico("O", 6, "OMBLES").
dico("O", 6, "OMBRAI").
dico("O", 6, "OMBRAS").
dico("O", 6, "OMBRAT").
dico("O", 6, "OMBREE").
dico("O", 6, "OMBRER").
dico("O", 6, "OMBRES").
dico("O", 6, "OMBREZ").
dico("O", 6, "OMERTA").
dico("O", 6, "OMETTE").
dico("O", 6, "OMIMES").
dico("O", 6, "OMISES").
dico("O", 6, "OMISSE").
dico("O", 6, "OMITES").
dico("O", 6, "OMNIUM").
dico("O", 6, "ONAGRE").
dico("O", 6, "ONCIAL").
dico("O", 6, "ONCLES").
dico("O", 6, "ONDEES").
dico("O", 6, "ONDINE").
dico("O", 6, "ONDINS").
dico("O", 6, "ONDOIE").
dico("O", 6, "ONDOYA").
dico("O", 6, "ONDOYE").
dico("O", 6, "ONDULA").
dico("O", 6, "ONDULE").
dico("O", 6, "ONGLEE").
dico("O", 6, "ONGLES").
dico("O", 6, "ONGLET").
dico("O", 6, "ONGLON").
dico("O", 6, "ONGULE").
dico("O", 6, "ONLAYS").
dico("O", 6, "ONQUES").
dico("O", 6, "ONYXIS").
dico("O", 6, "ONZAIN").
dico("O", 6, "OOCYTE").
dico("O", 6, "OOGONE").
dico("O", 6, "OOLITE").
dico("O", 6, "OPALES").
dico("O", 6, "OPALIN").
dico("O", 6, "OPAQUE").
dico("O", 6, "OPERAI").
dico("O", 6, "OPERAS").
dico("O", 6, "OPERAT").
dico("O", 6, "OPEREE").
dico("O", 6, "OPERER").
dico("O", 6, "OPERES").
dico("O", 6, "OPEREZ").
dico("O", 6, "OPERON").
dico("O", 6, "OPHITE").
dico("O", 6, "OPHRYS").
dico("O", 6, "OPIACA").
dico("O", 6, "OPIACE").
dico("O", 6, "OPIATS").
dico("O", 6, "OPIMES").
dico("O", 6, "OPINAI").
dico("O", 6, "OPINAS").
dico("O", 6, "OPINAT").
dico("O", 6, "OPINEL").
dico("O", 6, "OPINER").
dico("O", 6, "OPINES").
dico("O", 6, "OPINEZ").
dico("O", 6, "OPIUMS").
dico("O", 6, "OPONCE").
dico("O", 6, "OPPIDA").
dico("O", 6, "OPPOSA").
dico("O", 6, "OPPOSE").
dico("O", 6, "OPSINE").
dico("O", 6, "OPTAIS").
dico("O", 6, "OPTAIT").
dico("O", 6, "OPTANT").
dico("O", 6, "OPTENT").
dico("O", 6, "OPTERA").
dico("O", 6, "OPTIEZ").
dico("O", 6, "OPTIMA").
dico("O", 6, "OPTION").
dico("O", 6, "OPTONS").
dico("O", 6, "ORACLE").
dico("O", 6, "ORAGES").
dico("O", 6, "ORALES").
dico("O", 6, "ORANGE").
dico("O", 6, "ORANTE").
dico("O", 6, "ORANTS").
dico("O", 6, "ORBITA").
dico("O", 6, "ORBITE").
dico("O", 6, "ORCHIS").
dico("O", 6, "ORDREE").
dico("O", 6, "ORDRES").
dico("O", 6, "ORDURE").
dico("O", 6, "OREADE").
dico("O", 6, "OREMUS").
dico("O", 6, "ORFROI").
dico("O", 6, "ORGANE").
dico("O", 6, "ORGEAT").
dico("O", 6, "ORGIES").
dico("O", 6, "ORGUES").
dico("O", 6, "ORIBUS").
dico("O", 6, "ORIELS").
dico("O", 6, "ORIENT").
dico("O", 6, "ORIGAN").
dico("O", 6, "ORIOLE").
dico("O", 6, "ORIYAS").
dico("O", 6, "ORLONS").
dico("O", 6, "ORMAIE").
dico("O", 6, "ORMEAU").
dico("O", 6, "ORMETS").
dico("O", 6, "ORMIER").
dico("O", 6, "ORMOIE").
dico("O", 6, "ORNAIS").
dico("O", 6, "ORNAIT").
dico("O", 6, "ORNANT").
dico("O", 6, "ORNEES").
dico("O", 6, "ORNENT").
dico("O", 6, "ORNERA").
dico("O", 6, "ORNIEZ").
dico("O", 6, "ORNONS").
dico("O", 6, "OROBES").
dico("O", 6, "ORONGE").
dico("O", 6, "ORPHIE").
dico("O", 6, "ORPINS").
dico("O", 6, "ORQUES").
dico("O", 6, "ORTEIL").
dico("O", 6, "ORTIES").
dico("O", 6, "ORTIVE").
dico("O", 6, "ORVALE").
dico("O", 6, "ORVETS").
dico("O", 6, "OSAMES").
dico("O", 6, "OSASSE").
dico("O", 6, "OSATES").
dico("O", 6, "OSCARS").
dico("O", 6, "OSCINE").
dico("O", 6, "OSCULE").
dico("O", 6, "OSERAI").
dico("O", 6, "OSERAS").
dico("O", 6, "OSEREZ").
dico("O", 6, "OSIDES").
dico("O", 6, "OSIERS").
dico("O", 6, "OSIONS").
dico("O", 6, "OSMIUM").
dico("O", 6, "OSMOSE").
dico("O", 6, "OSQUES").
dico("O", 6, "OSSETE").
dico("O", 6, "OSSEUX").
dico("O", 6, "OSSUES").
dico("O", 6, "OSTIAK").
dico("O", 6, "OSTYAK").
dico("O", 6, "OTAGES").
dico("O", 6, "OTAMES").
dico("O", 6, "OTARIE").
dico("O", 6, "OTASSE").
dico("O", 6, "OTATES").
dico("O", 6, "OTERAI").
dico("O", 6, "OTERAS").
dico("O", 6, "OTEREZ").
dico("O", 6, "OTIONS").
dico("O", 6, "OTIQUE").
dico("O", 6, "OTITES").
dico("O", 6, "OTOMIS").
dico("O", 6, "OUATAI").
dico("O", 6, "OUATAS").
dico("O", 6, "OUATAT").
dico("O", 6, "OUATEE").
dico("O", 6, "OUATER").
dico("O", 6, "OUATES").
dico("O", 6, "OUATEZ").
dico("O", 6, "OUBLIA").
dico("O", 6, "OUBLIE").
dico("O", 6, "OUBLIS").
dico("O", 6, "OUCHES").
dico("O", 6, "OUDLER").
dico("O", 6, "OUICHE").
dico("O", 6, "OUILLA").
dico("O", 6, "OUILLE").
dico("O", 6, "OUKASE").
dico("O", 6, "OULEMA").
dico("O", 6, "OUMIAK").
dico("O", 6, "OUNCES").
dico("O", 6, "OUOLOF").
dico("O", 6, "OURDIE").
dico("O", 6, "OURDIR").
dico("O", 6, "OURDIS").
dico("O", 6, "OURDIT").
dico("O", 6, "OURDOU").
dico("O", 6, "OUREBI").
dico("O", 6, "OURLAI").
dico("O", 6, "OURLAS").
dico("O", 6, "OURLAT").
dico("O", 6, "OURLEE").
dico("O", 6, "OURLER").
dico("O", 6, "OURLES").
dico("O", 6, "OURLET").
dico("O", 6, "OURLEZ").
dico("O", 6, "OURSES").
dico("O", 6, "OURSIN").
dico("O", 6, "OURSON").
dico("O", 6, "OUTILS").
dico("O", 6, "OUTING").
dico("O", 6, "OUTLAW").
dico("O", 6, "OUTPUT").
dico("O", 6, "OUTRAI").
dico("O", 6, "OUTRAS").
dico("O", 6, "OUTRAT").
dico("O", 6, "OUTREE").
dico("O", 6, "OUTRER").
dico("O", 6, "OUTRES").
dico("O", 6, "OUTREZ").
dico("O", 6, "OUVALA").
dico("O", 6, "OUVERT").
dico("O", 6, "OUVRAI").
dico("O", 6, "OUVRAS").
dico("O", 6, "OUVRAT").
dico("O", 6, "OUVREE").
dico("O", 6, "OUVRER").
dico("O", 6, "OUVRES").
dico("O", 6, "OUVREZ").
dico("O", 6, "OUVRIR").
dico("O", 6, "OUVRIS").
dico("O", 6, "OUVRIT").
dico("O", 6, "OUZBEK").
dico("O", 6, "OVAIRE").
dico("O", 6, "OVALES").
dico("O", 6, "OVALIE").
dico("O", 6, "OVATES").
dico("O", 6, "OVIBOS").
dico("O", 6, "OVIDES").
dico("O", 6, "OVINES").
dico("O", 6, "OVOIDE").
dico("O", 6, "OVULAI").
dico("O", 6, "OVULAS").
dico("O", 6, "OVULAT").
dico("O", 6, "OVULER").
dico("O", 6, "OVULES").
dico("O", 6, "OVULEZ").
dico("O", 6, "OXALIS").
dico("O", 6, "OXFORD").
dico("O", 6, "OXIMES").
dico("O", 6, "OXTAIL").
dico("O", 6, "OXYDAI").
dico("O", 6, "OXYDAS").
dico("O", 6, "OXYDAT").
dico("O", 6, "OXYDEE").
dico("O", 6, "OXYDER").
dico("O", 6, "OXYDES").
dico("O", 6, "OXYDEZ").
dico("O", 6, "OXYMEL").
dico("O", 6, "OXYTON").
dico("O", 6, "OXYURE").
dico("O", 6, "OZALID").
dico("O", 6, "OZENES").
dico("O", 6, "OZONAI").
dico("O", 6, "OZONAS").
dico("O", 6, "OZONAT").
dico("O", 6, "OZONEE").
dico("O", 6, "OZONER").
dico("O", 6, "OZONES").
dico("O", 6, "OZONEZ").
