dico("O", 7, "OASIENS").
dico("O", 7, "OBEIMES").
dico("O", 7, "OBEIRAI").
dico("O", 7, "OBEIRAS").
dico("O", 7, "OBEIREZ").
dico("O", 7, "OBEISSE").
dico("O", 7, "OBEITES").
dico("O", 7, "OBERAIS").
dico("O", 7, "OBERAIT").
dico("O", 7, "OBERANT").
dico("O", 7, "OBEREES").
dico("O", 7, "OBERENT").
dico("O", 7, "OBERERA").
dico("O", 7, "OBERIEZ").
dico("O", 7, "OBERONS").
dico("O", 7, "OBESITE").
dico("O", 7, "OBJECTA").
dico("O", 7, "OBJECTE").
dico("O", 7, "OBLADES").
dico("O", 7, "OBLATES").
dico("O", 7, "OBLATIF").
dico("O", 7, "OBLIGEA").
dico("O", 7, "OBLIGEE").
dico("O", 7, "OBLIGER").
dico("O", 7, "OBLIGES").
dico("O", 7, "OBLIGEZ").
dico("O", 7, "OBLIQUA").
dico("O", 7, "OBLIQUE").
dico("O", 7, "OBLONGS").
dico("O", 7, "OBOMBRA").
dico("O", 7, "OBOMBRE").
dico("O", 7, "OBSCENE").
dico("O", 7, "OBSCURE").
dico("O", 7, "OBSCURS").
dico("O", 7, "OBSEDAI").
dico("O", 7, "OBSEDAS").
dico("O", 7, "OBSEDAT").
dico("O", 7, "OBSEDEE").
dico("O", 7, "OBSEDER").
dico("O", 7, "OBSEDES").
dico("O", 7, "OBSEDEZ").
dico("O", 7, "OBSERVA").
dico("O", 7, "OBSERVE").
dico("O", 7, "OBSTINA").
dico("O", 7, "OBSTINE").
dico("O", 7, "OBSTRUA").
dico("O", 7, "OBSTRUE").
dico("O", 7, "OBTENEZ").
dico("O", 7, "OBTENIR").
dico("O", 7, "OBTENUE").
dico("O", 7, "OBTENUS").
dico("O", 7, "OBTIENS").
dico("O", 7, "OBTIENT").
dico("O", 7, "OBTURAI").
dico("O", 7, "OBTURAS").
dico("O", 7, "OBTURAT").
dico("O", 7, "OBTUREE").
dico("O", 7, "OBTURER").
dico("O", 7, "OBTURES").
dico("O", 7, "OBTUREZ").
dico("O", 7, "OBTUSES").
dico("O", 7, "OBUSIER").
dico("O", 7, "OBVENEZ").
dico("O", 7, "OBVENIR").
dico("O", 7, "OBVENUE").
dico("O", 7, "OBVENUS").
dico("O", 7, "OBVERSE").
dico("O", 7, "OBVIAIS").
dico("O", 7, "OBVIAIT").
dico("O", 7, "OBVIANT").
dico("O", 7, "OBVIENS").
dico("O", 7, "OBVIENT").
dico("O", 7, "OBVIERA").
dico("O", 7, "OBVIIEZ").
dico("O", 7, "OBVIONS").
dico("O", 7, "OCARINA").
dico("O", 7, "OCCASES").
dico("O", 7, "OCCIPUT").
dico("O", 7, "OCCISES").
dico("O", 7, "OCCITAN").
dico("O", 7, "OCCLUES").
dico("O", 7, "OCCLUEZ").
dico("O", 7, "OCCLURA").
dico("O", 7, "OCCLURE").
dico("O", 7, "OCCLUSE").
dico("O", 7, "OCCULTA").
dico("O", 7, "OCCULTE").
dico("O", 7, "OCCUPAI").
dico("O", 7, "OCCUPAS").
dico("O", 7, "OCCUPAT").
dico("O", 7, "OCCUPEE").
dico("O", 7, "OCCUPER").
dico("O", 7, "OCCUPES").
dico("O", 7, "OCCUPEZ").
dico("O", 7, "OCEANES").
dico("O", 7, "OCELLEE").
dico("O", 7, "OCELLES").
dico("O", 7, "OCELOTS").
dico("O", 7, "OCHRACE").
dico("O", 7, "OCRAMES").
dico("O", 7, "OCRASSE").
dico("O", 7, "OCRATES").
dico("O", 7, "OCRERAI").
dico("O", 7, "OCRERAS").
dico("O", 7, "OCREREZ").
dico("O", 7, "OCREUSE").
dico("O", 7, "OCRIONS").
dico("O", 7, "OCTALES").
dico("O", 7, "OCTANES").
dico("O", 7, "OCTANTE").
dico("O", 7, "OCTANTS").
dico("O", 7, "OCTAVES").
dico("O", 7, "OCTAVIA").
dico("O", 7, "OCTAVIE").
dico("O", 7, "OCTAVIN").
dico("O", 7, "OCTAVON").
dico("O", 7, "OCTIDIS").
dico("O", 7, "OCTOBRE").
dico("O", 7, "OCTROIE").
dico("O", 7, "OCTROIS").
dico("O", 7, "OCTROYA").
dico("O", 7, "OCTROYE").
dico("O", 7, "OCTUORS").
dico("O", 7, "OCTUPLA").
dico("O", 7, "OCTUPLE").
dico("O", 7, "OCULEES").
dico("O", 7, "ODIEUSE").
dico("O", 7, "ODONATE").
dico("O", 7, "ODORANT").
dico("O", 7, "ODORATS").
dico("O", 7, "ODORISA").
dico("O", 7, "ODORISE").
dico("O", 7, "ODYSSEE").
dico("O", 7, "OEDEMES").
dico("O", 7, "OEDIPES").
dico("O", 7, "OEILLET").
dico("O", 7, "OERSTED").
dico("O", 7, "OESTRAL").
dico("O", 7, "OESTRES").
dico("O", 7, "OESTRUS").
dico("O", 7, "OEUVEES").
dico("O", 7, "OEUVRAI").
dico("O", 7, "OEUVRAS").
dico("O", 7, "OEUVRAT").
dico("O", 7, "OEUVRER").
dico("O", 7, "OEUVRES").
dico("O", 7, "OEUVREZ").
dico("O", 7, "OFFENSA").
dico("O", 7, "OFFENSE").
dico("O", 7, "OFFERTE").
dico("O", 7, "OFFERTS").
dico("O", 7, "OFFICES").
dico("O", 7, "OFFICIA").
dico("O", 7, "OFFICIE").
dico("O", 7, "OFFRAIS").
dico("O", 7, "OFFRAIT").
dico("O", 7, "OFFRANT").
dico("O", 7, "OFFRENT").
dico("O", 7, "OFFREUR").
dico("O", 7, "OFFRIEZ").
dico("O", 7, "OFFRIRA").
dico("O", 7, "OFFRONS").
dico("O", 7, "OFFSETS").
dico("O", 7, "OGIVALE").
dico("O", 7, "OGIVAUX").
dico("O", 7, "OGNETTE").
dico("O", 7, "OGRESSE").
dico("O", 7, "OHMIQUE").
dico("O", 7, "OIDIUMS").
dico("O", 7, "OIGNAIS").
dico("O", 7, "OIGNAIT").
dico("O", 7, "OIGNANT").
dico("O", 7, "OIGNENT").
dico("O", 7, "OIGNIEZ").
dico("O", 7, "OIGNONS").
dico("O", 7, "OINDRAI").
dico("O", 7, "OINDRAS").
dico("O", 7, "OINDREZ").
dico("O", 7, "OISEAUX").
dico("O", 7, "OISELAI").
dico("O", 7, "OISELAS").
dico("O", 7, "OISELAT").
dico("O", 7, "OISELEE").
dico("O", 7, "OISELER").
dico("O", 7, "OISELES").
dico("O", 7, "OISELET").
dico("O", 7, "OISELEZ").
dico("O", 7, "OISELLE").
dico("O", 7, "OISEUSE").
dico("O", 7, "OISIVES").
dico("O", 7, "OJIBWAY").
dico("O", 7, "OKOUMES").
dico("O", 7, "OLEACEE").
dico("O", 7, "OLEATES").
dico("O", 7, "OLEFINE").
dico("O", 7, "OLEINES").
dico("O", 7, "OLEIQUE").
dico("O", 7, "OLEODUC").
dico("O", 7, "OLEOLAT").
dico("O", 7, "OLIBANS").
dico("O", 7, "OLIFANT").
dico("O", 7, "OLISBOS").
dico("O", 7, "OLIVACE").
dico("O", 7, "OLIVADE").
dico("O", 7, "OLIVAIE").
dico("O", 7, "OLIVETS").
dico("O", 7, "OLIVIER").
dico("O", 7, "OLIVINE").
dico("O", 7, "OLLAIRE").
dico("O", 7, "OLMEQUE").
dico("O", 7, "OLORIME").
dico("O", 7, "OLYMPES").
dico("O", 7, "OMANAIS").
dico("O", 7, "OMBELLE").
dico("O", 7, "OMBILIC").
dico("O", 7, "OMBRAGE").
dico("O", 7, "OMBRAIS").
dico("O", 7, "OMBRAIT").
dico("O", 7, "OMBRANT").
dico("O", 7, "OMBREES").
dico("O", 7, "OMBRENT").
dico("O", 7, "OMBRERA").
dico("O", 7, "OMBREUX").
dico("O", 7, "OMBRIEN").
dico("O", 7, "OMBRIEZ").
dico("O", 7, "OMBRINE").
dico("O", 7, "OMBRONS").
dico("O", 7, "OMERTAS").
dico("O", 7, "OMETTES").
dico("O", 7, "OMETTEZ").
dico("O", 7, "OMETTRA").
dico("O", 7, "OMETTRE").
dico("O", 7, "OMICRON").
dico("O", 7, "OMIRENT").
dico("O", 7, "OMISSES").
dico("O", 7, "OMNIBUS").
dico("O", 7, "OMNIUMS").
dico("O", 7, "ONAGRES").
dico("O", 7, "ONCIALE").
dico("O", 7, "ONCIAUX").
dico("O", 7, "ONCQUES").
dico("O", 7, "ONCTION").
dico("O", 7, "ONDATRA").
dico("O", 7, "ONDINES").
dico("O", 7, "ONDOIES").
dico("O", 7, "ONDOYAI").
dico("O", 7, "ONDOYAS").
dico("O", 7, "ONDOYAT").
dico("O", 7, "ONDOYEE").
dico("O", 7, "ONDOYER").
dico("O", 7, "ONDOYES").
dico("O", 7, "ONDOYEZ").
dico("O", 7, "ONDULAI").
dico("O", 7, "ONDULAS").
dico("O", 7, "ONDULAT").
dico("O", 7, "ONDULEE").
dico("O", 7, "ONDULER").
dico("O", 7, "ONDULES").
dico("O", 7, "ONDULEZ").
dico("O", 7, "ONEREUX").
dico("O", 7, "ONGLEES").
dico("O", 7, "ONGLETS").
dico("O", 7, "ONGLIER").
dico("O", 7, "ONGLONS").
dico("O", 7, "ONGUENT").
dico("O", 7, "ONGULEE").
dico("O", 7, "ONGULES").
dico("O", 7, "ONTIQUE").
dico("O", 7, "ONUSIEN").
dico("O", 7, "ONZAINS").
dico("O", 7, "ONZIEME").
dico("O", 7, "OOCYTES").
dico("O", 7, "OOGAMIE").
dico("O", 7, "OOGONES").
dico("O", 7, "OOLITES").
dico("O", 7, "OOLITHE").
dico("O", 7, "OOSPORE").
dico("O", 7, "OPACITE").
dico("O", 7, "OPALINE").
dico("O", 7, "OPALINS").
dico("O", 7, "OPALISA").
dico("O", 7, "OPALISE").
dico("O", 7, "OPAQUES").
dico("O", 7, "OPEABLE").
dico("O", 7, "OPERAIS").
dico("O", 7, "OPERAIT").
dico("O", 7, "OPERANT").
dico("O", 7, "OPEREES").
dico("O", 7, "OPERENT").
dico("O", 7, "OPERERA").
dico("O", 7, "OPERIEZ").
dico("O", 7, "OPERONS").
dico("O", 7, "OPHITES").
dico("O", 7, "OPHIURE").
dico("O", 7, "OPIACAI").
dico("O", 7, "OPIACAS").
dico("O", 7, "OPIACAT").
dico("O", 7, "OPIACEE").
dico("O", 7, "OPIACER").
dico("O", 7, "OPIACES").
dico("O", 7, "OPIACEZ").
dico("O", 7, "OPILION").
dico("O", 7, "OPINAIS").
dico("O", 7, "OPINAIT").
dico("O", 7, "OPINANT").
dico("O", 7, "OPINELS").
dico("O", 7, "OPINENT").
dico("O", 7, "OPINERA").
dico("O", 7, "OPINIEZ").
dico("O", 7, "OPINION").
dico("O", 7, "OPINONS").
dico("O", 7, "OPIOIDE").
dico("O", 7, "OPONCES").
dico("O", 7, "OPOSSUM").
dico("O", 7, "OPPIDUM").
dico("O", 7, "OPPOSAI").
dico("O", 7, "OPPOSAS").
dico("O", 7, "OPPOSAT").
dico("O", 7, "OPPOSEE").
dico("O", 7, "OPPOSER").
dico("O", 7, "OPPOSES").
dico("O", 7, "OPPOSEZ").
dico("O", 7, "OPPRIMA").
dico("O", 7, "OPPRIME").
dico("O", 7, "OPSINES").
dico("O", 7, "OPTAMES").
dico("O", 7, "OPTASSE").
dico("O", 7, "OPTATES").
dico("O", 7, "OPTATIF").
dico("O", 7, "OPTERAI").
dico("O", 7, "OPTERAS").
dico("O", 7, "OPTEREZ").
dico("O", 7, "OPTIMAL").
dico("O", 7, "OPTIMUM").
dico("O", 7, "OPTIONS").
dico("O", 7, "OPTIQUE").
dico("O", 7, "OPULENT").
dico("O", 7, "OPUNTIA").
dico("O", 7, "ORACLES").
dico("O", 7, "ORAGEUX").
dico("O", 7, "ORAISON").
dico("O", 7, "ORALISA").
dico("O", 7, "ORALISE").
dico("O", 7, "ORALITE").
dico("O", 7, "ORANAIS").
dico("O", 7, "ORANGEA").
dico("O", 7, "ORANGEE").
dico("O", 7, "ORANGER").
dico("O", 7, "ORANGES").
dico("O", 7, "ORANGEZ").
dico("O", 7, "ORANTES").
dico("O", 7, "ORATEUR").
dico("O", 7, "ORBITAI").
dico("O", 7, "ORBITAL").
dico("O", 7, "ORBITAS").
dico("O", 7, "ORBITAT").
dico("O", 7, "ORBITER").
dico("O", 7, "ORBITES").
dico("O", 7, "ORBITEZ").
dico("O", 7, "ORCHITE").
dico("O", 7, "ORDALIE").
dico("O", 7, "ORDINAL").
dico("O", 7, "ORDONNA").
dico("O", 7, "ORDONNE").
dico("O", 7, "ORDREES").
dico("O", 7, "ORDURES").
dico("O", 7, "OREADES").
dico("O", 7, "OREILLE").
dico("O", 7, "ORFEVRE").
dico("O", 7, "ORFRAIE").
dico("O", 7, "ORFROIS").
dico("O", 7, "ORGANDI").
dico("O", 7, "ORGANES").
dico("O", 7, "ORGANZA").
dico("O", 7, "ORGASME").
dico("O", 7, "ORGEATS").
dico("O", 7, "ORGELET").
dico("O", 7, "ORGUEIL").
dico("O", 7, "ORIENTA").
dico("O", 7, "ORIENTE").
dico("O", 7, "ORIENTS").
dico("O", 7, "ORIFICE").
dico("O", 7, "ORIGAMI").
dico("O", 7, "ORIGANS").
dico("O", 7, "ORIGINA").
dico("O", 7, "ORIGINE").
dico("O", 7, "ORIGNAL").
dico("O", 7, "ORILLON").
dico("O", 7, "ORIOLES").
dico("O", 7, "ORIPEAU").
dico("O", 7, "ORMAIES").
dico("O", 7, "ORMEAUX").
dico("O", 7, "ORMIERS").
dico("O", 7, "ORMILLE").
dico("O", 7, "ORMOIES").
dico("O", 7, "ORNAISE").
dico("O", 7, "ORNAMES").
dico("O", 7, "ORNASSE").
dico("O", 7, "ORNATES").
dico("O", 7, "ORNERAI").
dico("O", 7, "ORNERAS").
dico("O", 7, "ORNEREZ").
dico("O", 7, "ORNIERE").
dico("O", 7, "ORNIONS").
dico("O", 7, "OROGENE").
dico("O", 7, "ORONGES").
dico("O", 7, "ORPHEON").
dico("O", 7, "ORPHIES").
dico("O", 7, "ORTEILS").
dico("O", 7, "ORTHESE").
dico("O", 7, "ORTHOSE").
dico("O", 7, "ORTIVES").
dico("O", 7, "ORTOLAN").
dico("O", 7, "ORVALES").
dico("O", 7, "OSAIENT").
dico("O", 7, "OSASSES").
dico("O", 7, "OSCILLA").
dico("O", 7, "OSCILLE").
dico("O", 7, "OSCINES").
dico("O", 7, "OSCULES").
dico("O", 7, "OSEILLE").
dico("O", 7, "OSERAIE").
dico("O", 7, "OSERAIS").
dico("O", 7, "OSERAIT").
dico("O", 7, "OSERENT").
dico("O", 7, "OSERIEZ").
dico("O", 7, "OSERONS").
dico("O", 7, "OSERONT").
dico("O", 7, "OSMANLI").
dico("O", 7, "OSMIQUE").
dico("O", 7, "OSMIUMS").
dico("O", 7, "OSMIURE").
dico("O", 7, "OSMONDE").
dico("O", 7, "OSMOSES").
dico("O", 7, "OSSEINE").
dico("O", 7, "OSSELET").
dico("O", 7, "OSSETES").
dico("O", 7, "OSSEUSE").
dico("O", 7, "OSSIFIA").
dico("O", 7, "OSSIFIE").
dico("O", 7, "OSTEITE").
dico("O", 7, "OSTEOME").
dico("O", 7, "OSTEOSE").
dico("O", 7, "OSTIAKS").
dico("O", 7, "OSTIOLE").
dico("O", 7, "OSTRACA").
dico("O", 7, "OSTRACE").
dico("O", 7, "OSTYAKS").
dico("O", 7, "OTAIENT").
dico("O", 7, "OTALGIE").
dico("O", 7, "OTARIES").
dico("O", 7, "OTASSES").
dico("O", 7, "OTERAIS").
dico("O", 7, "OTERAIT").
dico("O", 7, "OTERENT").
dico("O", 7, "OTERIEZ").
dico("O", 7, "OTERONS").
dico("O", 7, "OTERONT").
dico("O", 7, "OTHELLO").
dico("O", 7, "OTIDIDE").
dico("O", 7, "OTIQUES").
dico("O", 7, "OTOCYON").
dico("O", 7, "OTTOMAN").
dico("O", 7, "OUAILLE").
dico("O", 7, "OUARINE").
dico("O", 7, "OUASSOU").
dico("O", 7, "OUATAGE").
dico("O", 7, "OUATAIS").
dico("O", 7, "OUATAIT").
dico("O", 7, "OUATANT").
dico("O", 7, "OUATEES").
dico("O", 7, "OUATENT").
dico("O", 7, "OUATERA").
dico("O", 7, "OUATEUX").
dico("O", 7, "OUATIEZ").
dico("O", 7, "OUATINA").
dico("O", 7, "OUATINE").
dico("O", 7, "OUATONS").
dico("O", 7, "OUBLIAI").
dico("O", 7, "OUBLIAS").
dico("O", 7, "OUBLIAT").
dico("O", 7, "OUBLIEE").
dico("O", 7, "OUBLIER").
dico("O", 7, "OUBLIES").
dico("O", 7, "OUBLIEZ").
dico("O", 7, "OUDLERS").
dico("O", 7, "OUGRIEN").
dico("O", 7, "OUGUIYA").
dico("O", 7, "OUIGOUR").
dico("O", 7, "OUILLAI").
dico("O", 7, "OUILLAS").
dico("O", 7, "OUILLAT").
dico("O", 7, "OUILLEE").
dico("O", 7, "OUILLER").
dico("O", 7, "OUILLES").
dico("O", 7, "OUILLEZ").
dico("O", 7, "OUKASES").
dico("O", 7, "OULEMAS").
dico("O", 7, "OUMIAKS").
dico("O", 7, "OUOLOFS").
dico("O", 7, "OURAGAN").
dico("O", 7, "OURAQUE").
dico("O", 7, "OURDIES").
dico("O", 7, "OURDIRA").
dico("O", 7, "OURDOUE").
dico("O", 7, "OURDOUS").
dico("O", 7, "OUREBIS").
dico("O", 7, "OURLAIS").
dico("O", 7, "OURLAIT").
dico("O", 7, "OURLANT").
dico("O", 7, "OURLEES").
dico("O", 7, "OURLENT").
dico("O", 7, "OURLERA").
dico("O", 7, "OURLETS").
dico("O", 7, "OURLIEN").
dico("O", 7, "OURLIEZ").
dico("O", 7, "OURLONS").
dico("O", 7, "OURSINS").
dico("O", 7, "OURSONS").
dico("O", 7, "OUTARDE").
dico("O", 7, "OUTILLA").
dico("O", 7, "OUTILLE").
dico("O", 7, "OUTINGS").
dico("O", 7, "OUTLAWS").
dico("O", 7, "OUTPUTS").
dico("O", 7, "OUTRAGE").
dico("O", 7, "OUTRAIS").
dico("O", 7, "OUTRAIT").
dico("O", 7, "OUTRANT").
dico("O", 7, "OUTREES").
dico("O", 7, "OUTRENT").
dico("O", 7, "OUTRERA").
dico("O", 7, "OUTRIEZ").
dico("O", 7, "OUTRONS").
dico("O", 7, "OUVALAS").
dico("O", 7, "OUVERTE").
dico("O", 7, "OUVERTS").
dico("O", 7, "OUVRAGE").
dico("O", 7, "OUVRAIS").
dico("O", 7, "OUVRAIT").
dico("O", 7, "OUVRANT").
dico("O", 7, "OUVREAU").
dico("O", 7, "OUVREES").
dico("O", 7, "OUVRENT").
dico("O", 7, "OUVRERA").
dico("O", 7, "OUVREUR").
dico("O", 7, "OUVRIER").
dico("O", 7, "OUVRIEZ").
dico("O", 7, "OUVRIRA").
dico("O", 7, "OUVROIR").
dico("O", 7, "OUVRONS").
dico("O", 7, "OUZBEKE").
dico("O", 7, "OUZBEKS").
dico("O", 7, "OVAIRES").
dico("O", 7, "OVALIES").
dico("O", 7, "OVALISA").
dico("O", 7, "OVALISE").
dico("O", 7, "OVARIEN").
dico("O", 7, "OVARITE").
dico("O", 7, "OVATION").
dico("O", 7, "OVICULE").
dico("O", 7, "OVIPARE").
dico("O", 7, "OVOCYTE").
dico("O", 7, "OVOIDAL").
dico("O", 7, "OVOIDES").
dico("O", 7, "OVOTIDE").
dico("O", 7, "OVULAIS").
dico("O", 7, "OVULAIT").
dico("O", 7, "OVULANT").
dico("O", 7, "OVULENT").
dico("O", 7, "OVULERA").
dico("O", 7, "OVULIEZ").
dico("O", 7, "OVULONS").
dico("O", 7, "OXACIDE").
dico("O", 7, "OXALATE").
dico("O", 7, "OXALIDE").
dico("O", 7, "OXAMIDE").
dico("O", 7, "OXFORDS").
dico("O", 7, "OXONIEN").
dico("O", 7, "OXONIUM").
dico("O", 7, "OXTAILS").
dico("O", 7, "OXYCRAT").
dico("O", 7, "OXYDAIS").
dico("O", 7, "OXYDAIT").
dico("O", 7, "OXYDANT").
dico("O", 7, "OXYDASE").
dico("O", 7, "OXYDEES").
dico("O", 7, "OXYDENT").
dico("O", 7, "OXYDERA").
dico("O", 7, "OXYDIEZ").
dico("O", 7, "OXYDONS").
dico("O", 7, "OXYGENA").
dico("O", 7, "OXYGENE").
dico("O", 7, "OXYMELS").
dico("O", 7, "OXYMORE").
dico("O", 7, "OXYTONS").
dico("O", 7, "OXYURES").
dico("O", 7, "OZALIDS").
dico("O", 7, "OZENEUX").
dico("O", 7, "OZONAIS").
dico("O", 7, "OZONAIT").
dico("O", 7, "OZONANT").
dico("O", 7, "OZONEES").
dico("O", 7, "OZONENT").
dico("O", 7, "OZONERA").
dico("O", 7, "OZONEUR").
dico("O", 7, "OZONIDE").
dico("O", 7, "OZONIEZ").
dico("O", 7, "OZONISA").
dico("O", 7, "OZONISE").
dico("O", 7, "OZONONS").
