dico("O", 8, "OARISTYS").
dico("O", 8, "OASIENNE").
dico("O", 8, "OBEIRAIS").
dico("O", 8, "OBEIRAIT").
dico("O", 8, "OBEIRENT").
dico("O", 8, "OBEIRIEZ").
dico("O", 8, "OBEIRONS").
dico("O", 8, "OBEIRONT").
dico("O", 8, "OBEISSES").
dico("O", 8, "OBEISSEZ").
dico("O", 8, "OBERAMES").
dico("O", 8, "OBERASSE").
dico("O", 8, "OBERATES").
dico("O", 8, "OBERERAI").
dico("O", 8, "OBERERAS").
dico("O", 8, "OBEREREZ").
dico("O", 8, "OBERIONS").
dico("O", 8, "OBESITES").
dico("O", 8, "OBJECTAI").
dico("O", 8, "OBJECTAL").
dico("O", 8, "OBJECTAS").
dico("O", 8, "OBJECTAT").
dico("O", 8, "OBJECTEE").
dico("O", 8, "OBJECTER").
dico("O", 8, "OBJECTES").
dico("O", 8, "OBJECTEZ").
dico("O", 8, "OBJECTIF").
dico("O", 8, "OBLATIFS").
dico("O", 8, "OBLATION").
dico("O", 8, "OBLATIVE").
dico("O", 8, "OBLATURE").
dico("O", 8, "OBLIGEAI").
dico("O", 8, "OBLIGEAS").
dico("O", 8, "OBLIGEAT").
dico("O", 8, "OBLIGEES").
dico("O", 8, "OBLIGENT").
dico("O", 8, "OBLIGERA").
dico("O", 8, "OBLIGIEZ").
dico("O", 8, "OBLIQUAI").
dico("O", 8, "OBLIQUAS").
dico("O", 8, "OBLIQUAT").
dico("O", 8, "OBLIQUER").
dico("O", 8, "OBLIQUES").
dico("O", 8, "OBLIQUEZ").
dico("O", 8, "OBLITERA").
dico("O", 8, "OBLITERE").
dico("O", 8, "OBLONGUE").
dico("O", 8, "OBNUBILA").
dico("O", 8, "OBNUBILE").
dico("O", 8, "OBOMBRAI").
dico("O", 8, "OBOMBRAS").
dico("O", 8, "OBOMBRAT").
dico("O", 8, "OBOMBREE").
dico("O", 8, "OBOMBRER").
dico("O", 8, "OBOMBRES").
dico("O", 8, "OBOMBREZ").
dico("O", 8, "OBSCENES").
dico("O", 8, "OBSCURCI").
dico("O", 8, "OBSCURES").
dico("O", 8, "OBSEDAIS").
dico("O", 8, "OBSEDAIT").
dico("O", 8, "OBSEDANT").
dico("O", 8, "OBSEDEES").
dico("O", 8, "OBSEDENT").
dico("O", 8, "OBSEDERA").
dico("O", 8, "OBSEDIEZ").
dico("O", 8, "OBSEDONS").
dico("O", 8, "OBSEQUES").
dico("O", 8, "OBSERVAI").
dico("O", 8, "OBSERVAS").
dico("O", 8, "OBSERVAT").
dico("O", 8, "OBSERVEE").
dico("O", 8, "OBSERVER").
dico("O", 8, "OBSERVES").
dico("O", 8, "OBSERVEZ").
dico("O", 8, "OBSESSIF").
dico("O", 8, "OBSOLETE").
dico("O", 8, "OBSTACLE").
dico("O", 8, "OBSTINAI").
dico("O", 8, "OBSTINAS").
dico("O", 8, "OBSTINAT").
dico("O", 8, "OBSTINEE").
dico("O", 8, "OBSTINER").
dico("O", 8, "OBSTINES").
dico("O", 8, "OBSTINEZ").
dico("O", 8, "OBSTRUAI").
dico("O", 8, "OBSTRUAS").
dico("O", 8, "OBSTRUAT").
dico("O", 8, "OBSTRUEE").
dico("O", 8, "OBSTRUER").
dico("O", 8, "OBSTRUES").
dico("O", 8, "OBSTRUEZ").
dico("O", 8, "OBTENAIS").
dico("O", 8, "OBTENAIT").
dico("O", 8, "OBTENANT").
dico("O", 8, "OBTENIEZ").
dico("O", 8, "OBTENONS").
dico("O", 8, "OBTENUES").
dico("O", 8, "OBTIENNE").
dico("O", 8, "OBTINMES").
dico("O", 8, "OBTINSSE").
dico("O", 8, "OBTINTES").
dico("O", 8, "OBTURAIS").
dico("O", 8, "OBTURAIT").
dico("O", 8, "OBTURANT").
dico("O", 8, "OBTUREES").
dico("O", 8, "OBTURENT").
dico("O", 8, "OBTURERA").
dico("O", 8, "OBTURIEZ").
dico("O", 8, "OBTURONS").
dico("O", 8, "OBTUSION").
dico("O", 8, "OBUSIERS").
dico("O", 8, "OBVENAIS").
dico("O", 8, "OBVENAIT").
dico("O", 8, "OBVENANT").
dico("O", 8, "OBVENIEZ").
dico("O", 8, "OBVENONS").
dico("O", 8, "OBVENUES").
dico("O", 8, "OBVERSES").
dico("O", 8, "OBVIAMES").
dico("O", 8, "OBVIASSE").
dico("O", 8, "OBVIATES").
dico("O", 8, "OBVIENNE").
dico("O", 8, "OBVIERAI").
dico("O", 8, "OBVIERAS").
dico("O", 8, "OBVIEREZ").
dico("O", 8, "OBVIIONS").
dico("O", 8, "OBVINMES").
dico("O", 8, "OBVINSSE").
dico("O", 8, "OBVINTES").
dico("O", 8, "OCARINAS").
dico("O", 8, "OCCASION").
dico("O", 8, "OCCIDENT").
dico("O", 8, "OCCIPUTS").
dico("O", 8, "OCCITANE").
dico("O", 8, "OCCITANS").
dico("O", 8, "OCCLUAIS").
dico("O", 8, "OCCLUAIT").
dico("O", 8, "OCCLUANT").
dico("O", 8, "OCCLUENT").
dico("O", 8, "OCCLUIEZ").
dico("O", 8, "OCCLUMES").
dico("O", 8, "OCCLUONS").
dico("O", 8, "OCCLURAI").
dico("O", 8, "OCCLURAS").
dico("O", 8, "OCCLUREZ").
dico("O", 8, "OCCLUSAL").
dico("O", 8, "OCCLUSES").
dico("O", 8, "OCCLUSIF").
dico("O", 8, "OCCLUSSE").
dico("O", 8, "OCCLUTES").
dico("O", 8, "OCCULTAI").
dico("O", 8, "OCCULTAS").
dico("O", 8, "OCCULTAT").
dico("O", 8, "OCCULTEE").
dico("O", 8, "OCCULTER").
dico("O", 8, "OCCULTES").
dico("O", 8, "OCCULTEZ").
dico("O", 8, "OCCUPAIS").
dico("O", 8, "OCCUPAIT").
dico("O", 8, "OCCUPANT").
dico("O", 8, "OCCUPEES").
dico("O", 8, "OCCUPENT").
dico("O", 8, "OCCUPERA").
dico("O", 8, "OCCUPIEZ").
dico("O", 8, "OCCUPONS").
dico("O", 8, "OCEANIDE").
dico("O", 8, "OCEANIEN").
dico("O", 8, "OCELLEES").
dico("O", 8, "OCHRACEE").
dico("O", 8, "OCHRACES").
dico("O", 8, "OCRAIENT").
dico("O", 8, "OCRASSES").
dico("O", 8, "OCRERAIS").
dico("O", 8, "OCRERAIT").
dico("O", 8, "OCRERENT").
dico("O", 8, "OCRERIEZ").
dico("O", 8, "OCRERONS").
dico("O", 8, "OCRERONT").
dico("O", 8, "OCREUSES").
dico("O", 8, "OCTAEDRE").
dico("O", 8, "OCTAVIAI").
dico("O", 8, "OCTAVIAS").
dico("O", 8, "OCTAVIAT").
dico("O", 8, "OCTAVIEE").
dico("O", 8, "OCTAVIER").
dico("O", 8, "OCTAVIES").
dico("O", 8, "OCTAVIEZ").
dico("O", 8, "OCTAVINS").
dico("O", 8, "OCTAVONS").
dico("O", 8, "OCTOBRES").
dico("O", 8, "OCTOGONE").
dico("O", 8, "OCTOPODE").
dico("O", 8, "OCTROIES").
dico("O", 8, "OCTROYAI").
dico("O", 8, "OCTROYAS").
dico("O", 8, "OCTROYAT").
dico("O", 8, "OCTROYEE").
dico("O", 8, "OCTROYER").
dico("O", 8, "OCTROYES").
dico("O", 8, "OCTROYEZ").
dico("O", 8, "OCTUPLAI").
dico("O", 8, "OCTUPLAS").
dico("O", 8, "OCTUPLAT").
dico("O", 8, "OCTUPLEE").
dico("O", 8, "OCTUPLER").
dico("O", 8, "OCTUPLES").
dico("O", 8, "OCTUPLEZ").
dico("O", 8, "OCULAIRE").
dico("O", 8, "OCULISTE").
dico("O", 8, "ODELETTE").
dico("O", 8, "ODIEUSES").
dico("O", 8, "ODOMETRE").
dico("O", 8, "ODONATES").
dico("O", 8, "ODORANTE").
dico("O", 8, "ODORANTS").
dico("O", 8, "ODORISAI").
dico("O", 8, "ODORISAS").
dico("O", 8, "ODORISAT").
dico("O", 8, "ODORISEE").
dico("O", 8, "ODORISER").
dico("O", 8, "ODORISES").
dico("O", 8, "ODORISEZ").
dico("O", 8, "ODYSSEES").
dico("O", 8, "OEDIPIEN").
dico("O", 8, "OEILLADE").
dico("O", 8, "OEILLARD").
dico("O", 8, "OEILLERE").
dico("O", 8, "OEILLETS").
dico("O", 8, "OENANTHE").
dico("O", 8, "OERSTEDS").
dico("O", 8, "OERSTITE").
dico("O", 8, "OESTRALE").
dico("O", 8, "OESTRAUX").
dico("O", 8, "OESTRIDE").
dico("O", 8, "OESTRIOL").
dico("O", 8, "OESTRONE").
dico("O", 8, "OEUFRIER").
dico("O", 8, "OEUVRAIS").
dico("O", 8, "OEUVRAIT").
dico("O", 8, "OEUVRANT").
dico("O", 8, "OEUVRENT").
dico("O", 8, "OEUVRERA").
dico("O", 8, "OEUVRIEZ").
dico("O", 8, "OEUVRONS").
dico("O", 8, "OFFENSAI").
dico("O", 8, "OFFENSAS").
dico("O", 8, "OFFENSAT").
dico("O", 8, "OFFENSEE").
dico("O", 8, "OFFENSER").
dico("O", 8, "OFFENSES").
dico("O", 8, "OFFENSEZ").
dico("O", 8, "OFFENSIF").
dico("O", 8, "OFFERTES").
dico("O", 8, "OFFICIAI").
dico("O", 8, "OFFICIAL").
dico("O", 8, "OFFICIAS").
dico("O", 8, "OFFICIAT").
dico("O", 8, "OFFICIEL").
dico("O", 8, "OFFICIER").
dico("O", 8, "OFFICIES").
dico("O", 8, "OFFICIEZ").
dico("O", 8, "OFFICINE").
dico("O", 8, "OFFRANDE").
dico("O", 8, "OFFRANTS").
dico("O", 8, "OFFREURS").
dico("O", 8, "OFFREUSE").
dico("O", 8, "OFFRIMES").
dico("O", 8, "OFFRIONS").
dico("O", 8, "OFFRIRAI").
dico("O", 8, "OFFRIRAS").
dico("O", 8, "OFFRIREZ").
dico("O", 8, "OFFRISSE").
dico("O", 8, "OFFRITES").
dico("O", 8, "OFFSHORE").
dico("O", 8, "OFFUSQUA").
dico("O", 8, "OFFUSQUE").
dico("O", 8, "OGAMIQUE").
dico("O", 8, "OGIVALES").
dico("O", 8, "OGNETTES").
dico("O", 8, "OGRESSES").
dico("O", 8, "OHMIQUES").
dico("O", 8, "OHMMETRE").
dico("O", 8, "OIGNIMES").
dico("O", 8, "OIGNIONS").
dico("O", 8, "OIGNISSE").
dico("O", 8, "OIGNITES").
dico("O", 8, "OINDRAIS").
dico("O", 8, "OINDRAIT").
dico("O", 8, "OINDRIEZ").
dico("O", 8, "OINDRONS").
dico("O", 8, "OINDRONT").
dico("O", 8, "OISELAIS").
dico("O", 8, "OISELAIT").
dico("O", 8, "OISELANT").
dico("O", 8, "OISELEES").
dico("O", 8, "OISELETS").
dico("O", 8, "OISELEUR").
dico("O", 8, "OISELIER").
dico("O", 8, "OISELIEZ").
dico("O", 8, "OISELLES").
dico("O", 8, "OISELONS").
dico("O", 8, "OISEUSES").
dico("O", 8, "OISILLON").
dico("O", 8, "OISIVETE").
dico("O", 8, "OJIBWAYS").
dico("O", 8, "OLEACEES").
dico("O", 8, "OLEANDRE").
dico("O", 8, "OLEASTRE").
dico("O", 8, "OLECRANE").
dico("O", 8, "OLEFIANT").
dico("O", 8, "OLEFINES").
dico("O", 8, "OLEICOLE").
dico("O", 8, "OLEIFERE").
dico("O", 8, "OLEIQUES").
dico("O", 8, "OLEODUCS").
dico("O", 8, "OLEOLATS").
dico("O", 8, "OLFACTIF").
dico("O", 8, "OLIBRIUS").
dico("O", 8, "OLIFANTS").
dico("O", 8, "OLIGISTE").
dico("O", 8, "OLIGURIE").
dico("O", 8, "OLIPHANT").
dico("O", 8, "OLIVACEE").
dico("O", 8, "OLIVACES").
dico("O", 8, "OLIVADES").
dico("O", 8, "OLIVAIES").
dico("O", 8, "OLIVAIRE").
dico("O", 8, "OLIVATRE").
dico("O", 8, "OLIVERIE").
dico("O", 8, "OLIVETTE").
dico("O", 8, "OLIVIERS").
dico("O", 8, "OLIVINES").
dico("O", 8, "OLLAIRES").
dico("O", 8, "OLMEQUES").
dico("O", 8, "OLORIMES").
dico("O", 8, "OLYMPIEN").
dico("O", 8, "OMANAISE").
dico("O", 8, "OMBELLEE").
dico("O", 8, "OMBELLES").
dico("O", 8, "OMBILICS").
dico("O", 8, "OMBRAGEA").
dico("O", 8, "OMBRAGEE").
dico("O", 8, "OMBRAGER").
dico("O", 8, "OMBRAGES").
dico("O", 8, "OMBRAGEZ").
dico("O", 8, "OMBRAMES").
dico("O", 8, "OMBRASSE").
dico("O", 8, "OMBRATES").
dico("O", 8, "OMBRELLE").
dico("O", 8, "OMBRERAI").
dico("O", 8, "OMBRERAS").
dico("O", 8, "OMBREREZ").
dico("O", 8, "OMBRETTE").
dico("O", 8, "OMBREUSE").
dico("O", 8, "OMBRIENS").
dico("O", 8, "OMBRINES").
dico("O", 8, "OMBRIONS").
dico("O", 8, "OMELETTE").
dico("O", 8, "OMETTAIS").
dico("O", 8, "OMETTAIT").
dico("O", 8, "OMETTANT").
dico("O", 8, "OMETTENT").
dico("O", 8, "OMETTIEZ").
dico("O", 8, "OMETTONS").
dico("O", 8, "OMETTRAI").
dico("O", 8, "OMETTRAS").
dico("O", 8, "OMETTREZ").
dico("O", 8, "OMEYYADE").
dico("O", 8, "OMISSENT").
dico("O", 8, "OMISSIEZ").
dico("O", 8, "OMISSION").
dico("O", 8, "OMNIVORE").
dico("O", 8, "OMOPLATE").
dico("O", 8, "ONANISME").
dico("O", 8, "ONANISTE").
dico("O", 8, "ONCIALES").
dico("O", 8, "ONCOGENE").
dico("O", 8, "ONCTIONS").
dico("O", 8, "ONCTUEUX").
dico("O", 8, "ONDATRAS").
dico("O", 8, "ONDOIENT").
dico("O", 8, "ONDOIERA").
dico("O", 8, "ONDOYAIS").
dico("O", 8, "ONDOYAIT").
dico("O", 8, "ONDOYANT").
dico("O", 8, "ONDOYEES").
dico("O", 8, "ONDOYIEZ").
dico("O", 8, "ONDOYONS").
dico("O", 8, "ONDULAIS").
dico("O", 8, "ONDULAIT").
dico("O", 8, "ONDULANT").
dico("O", 8, "ONDULEES").
dico("O", 8, "ONDULENT").
dico("O", 8, "ONDULERA").
dico("O", 8, "ONDULEUR").
dico("O", 8, "ONDULEUX").
dico("O", 8, "ONDULIEZ").
dico("O", 8, "ONDULONS").
dico("O", 8, "ONEREUSE").
dico("O", 8, "ONGLETTE").
dico("O", 8, "ONGLIERS").
dico("O", 8, "ONGUENTS").
dico("O", 8, "ONGULEES").
dico("O", 8, "ONIRIQUE").
dico("O", 8, "ONIRISME").
dico("O", 8, "ONTARIEN").
dico("O", 8, "ONTIQUES").
dico("O", 8, "ONUSIENS").
dico("O", 8, "ONYCHOSE").
dico("O", 8, "ONZIEMES").
dico("O", 8, "OOGAMIES").
dico("O", 8, "OOGENESE").
dico("O", 8, "OOLITHES").
dico("O", 8, "OOMYCETE").
dico("O", 8, "OOSPHERE").
dico("O", 8, "OOSPORES").
dico("O", 8, "OOTHEQUE").
dico("O", 8, "OPACIFIA").
dico("O", 8, "OPACIFIE").
dico("O", 8, "OPACITES").
dico("O", 8, "OPALINES").
dico("O", 8, "OPALISAI").
dico("O", 8, "OPALISAS").
dico("O", 8, "OPALISAT").
dico("O", 8, "OPALISEE").
dico("O", 8, "OPALISER").
dico("O", 8, "OPALISES").
dico("O", 8, "OPALISEZ").
dico("O", 8, "OPEABLES").
dico("O", 8, "OPERABLE").
dico("O", 8, "OPERAMES").
dico("O", 8, "OPERANDE").
dico("O", 8, "OPERANTE").
dico("O", 8, "OPERANTS").
dico("O", 8, "OPERASSE").
dico("O", 8, "OPERATES").
dico("O", 8, "OPERCULE").
dico("O", 8, "OPERERAI").
dico("O", 8, "OPERERAS").
dico("O", 8, "OPEREREZ").
dico("O", 8, "OPERETTE").
dico("O", 8, "OPERIONS").
dico("O", 8, "OPHIDIEN").
dico("O", 8, "OPHIURES").
dico("O", 8, "OPHTALMO").
dico("O", 8, "OPIACAIS").
dico("O", 8, "OPIACAIT").
dico("O", 8, "OPIACANT").
dico("O", 8, "OPIACEES").
dico("O", 8, "OPIACENT").
dico("O", 8, "OPIACERA").
dico("O", 8, "OPIACIEZ").
dico("O", 8, "OPIACONS").
dico("O", 8, "OPILIONS").
dico("O", 8, "OPINAMES").
dico("O", 8, "OPINASSE").
dico("O", 8, "OPINATES").
dico("O", 8, "OPINERAI").
dico("O", 8, "OPINERAS").
dico("O", 8, "OPINEREZ").
dico("O", 8, "OPINIONS").
dico("O", 8, "OPIOIDES").
dico("O", 8, "OPIOMANE").
dico("O", 8, "OPOPANAX").
dico("O", 8, "OPOPONAX").
dico("O", 8, "OPOSSUMS").
dico("O", 8, "OPPIDUMS").
dico("O", 8, "OPPORTUN").
dico("O", 8, "OPPOSAIS").
dico("O", 8, "OPPOSAIT").
dico("O", 8, "OPPOSANT").
dico("O", 8, "OPPOSEES").
dico("O", 8, "OPPOSENT").
dico("O", 8, "OPPOSERA").
dico("O", 8, "OPPOSIEZ").
dico("O", 8, "OPPOSITE").
dico("O", 8, "OPPOSONS").
dico("O", 8, "OPPRESSA").
dico("O", 8, "OPPRESSE").
dico("O", 8, "OPPRIMAI").
dico("O", 8, "OPPRIMAS").
dico("O", 8, "OPPRIMAT").
dico("O", 8, "OPPRIMEE").
dico("O", 8, "OPPRIMER").
dico("O", 8, "OPPRIMES").
dico("O", 8, "OPPRIMEZ").
dico("O", 8, "OPPROBRE").
dico("O", 8, "OPSOMANE").
dico("O", 8, "OPSONINE").
dico("O", 8, "OPTAIENT").
dico("O", 8, "OPTASSES").
dico("O", 8, "OPTATIFS").
dico("O", 8, "OPTATIVE").
dico("O", 8, "OPTERAIS").
dico("O", 8, "OPTERAIT").
dico("O", 8, "OPTERENT").
dico("O", 8, "OPTERIEZ").
dico("O", 8, "OPTERONS").
dico("O", 8, "OPTERONT").
dico("O", 8, "OPTICIEN").
dico("O", 8, "OPTIMALE").
dico("O", 8, "OPTIMAUX").
dico("O", 8, "OPTIMISA").
dico("O", 8, "OPTIMISE").
dico("O", 8, "OPTIMUMS").
dico("O", 8, "OPTIQUES").
dico("O", 8, "OPTOTYPE").
dico("O", 8, "OPTRAKEN").
dico("O", 8, "OPULENCE").
dico("O", 8, "OPULENTE").
dico("O", 8, "OPULENTS").
dico("O", 8, "OPUNTIAS").
dico("O", 8, "OPUSCULE").
dico("O", 8, "ORAGEUSE").
dico("O", 8, "ORAISONS").
dico("O", 8, "ORALISAI").
dico("O", 8, "ORALISAS").
dico("O", 8, "ORALISAT").
dico("O", 8, "ORALISEE").
dico("O", 8, "ORALISER").
dico("O", 8, "ORALISES").
dico("O", 8, "ORALISEZ").
dico("O", 8, "ORALITES").
dico("O", 8, "ORANAISE").
dico("O", 8, "ORANGEAI").
dico("O", 8, "ORANGEAS").
dico("O", 8, "ORANGEAT").
dico("O", 8, "ORANGEES").
dico("O", 8, "ORANGENT").
dico("O", 8, "ORANGERA").
dico("O", 8, "ORANGERS").
dico("O", 8, "ORANGIEZ").
dico("O", 8, "ORATEURS").
dico("O", 8, "ORATOIRE").
dico("O", 8, "ORATORIO").
dico("O", 8, "ORATRICE").
dico("O", 8, "ORBICOLE").
dico("O", 8, "ORBITAIS").
dico("O", 8, "ORBITAIT").
dico("O", 8, "ORBITALE").
dico("O", 8, "ORBITANT").
dico("O", 8, "ORBITAUX").
dico("O", 8, "ORBITELE").
dico("O", 8, "ORBITENT").
dico("O", 8, "ORBITERA").
dico("O", 8, "ORBITEUR").
dico("O", 8, "ORBITIEZ").
dico("O", 8, "ORBITONS").
dico("O", 8, "ORCANETE").
dico("O", 8, "ORCHIDEE").
dico("O", 8, "ORCHITES").
dico("O", 8, "ORDALIES").
dico("O", 8, "ORDINALE").
dico("O", 8, "ORDINAND").
dico("O", 8, "ORDINANT").
dico("O", 8, "ORDINAUX").
dico("O", 8, "ORDONNAI").
dico("O", 8, "ORDONNAS").
dico("O", 8, "ORDONNAT").
dico("O", 8, "ORDONNEE").
dico("O", 8, "ORDONNER").
dico("O", 8, "ORDONNES").
dico("O", 8, "ORDONNEZ").
dico("O", 8, "ORDURIER").
dico("O", 8, "OREILLER").
dico("O", 8, "OREILLES").
dico("O", 8, "OREILLON").
dico("O", 8, "ORFEVREE").
dico("O", 8, "ORFEVRES").
dico("O", 8, "ORFRAIES").
dico("O", 8, "ORGANDIS").
dico("O", 8, "ORGANEAU").
dico("O", 8, "ORGANIER").
dico("O", 8, "ORGANISA").
dico("O", 8, "ORGANISE").
dico("O", 8, "ORGANITE").
dico("O", 8, "ORGANSIN").
dico("O", 8, "ORGANZAS").
dico("O", 8, "ORGASMES").
dico("O", 8, "ORGELETS").
dico("O", 8, "ORGIAQUE").
dico("O", 8, "ORGIASME").
dico("O", 8, "ORGIASTE").
dico("O", 8, "ORGUEILS").
dico("O", 8, "ORIENTAI").
dico("O", 8, "ORIENTAL").
dico("O", 8, "ORIENTAS").
dico("O", 8, "ORIENTAT").
dico("O", 8, "ORIENTEE").
dico("O", 8, "ORIENTER").
dico("O", 8, "ORIENTES").
dico("O", 8, "ORIENTEZ").
dico("O", 8, "ORIFICES").
dico("O", 8, "ORIGAMIS").
dico("O", 8, "ORIGINAI").
dico("O", 8, "ORIGINAL").
dico("O", 8, "ORIGINAS").
dico("O", 8, "ORIGINAT").
dico("O", 8, "ORIGINEE").
dico("O", 8, "ORIGINEL").
dico("O", 8, "ORIGINER").
dico("O", 8, "ORIGINES").
dico("O", 8, "ORIGINEZ").
dico("O", 8, "ORIGNAUX").
dico("O", 8, "ORILLONS").
dico("O", 8, "ORIPEAUX").
dico("O", 8, "ORMILLES").
dico("O", 8, "ORNAIENT").
dico("O", 8, "ORNAISES").
dico("O", 8, "ORNASSES").
dico("O", 8, "ORNEMENT").
dico("O", 8, "ORNERAIS").
dico("O", 8, "ORNERAIT").
dico("O", 8, "ORNERENT").
dico("O", 8, "ORNERIEZ").
dico("O", 8, "ORNERONS").
dico("O", 8, "ORNERONT").
dico("O", 8, "ORNIERES").
dico("O", 8, "OROGENES").
dico("O", 8, "OROGENIE").
dico("O", 8, "ORPHELIN").
dico("O", 8, "ORPHEONS").
dico("O", 8, "ORPHIQUE").
dico("O", 8, "ORPHISME").
dico("O", 8, "ORPIMENT").
dico("O", 8, "ORSEILLE").
dico("O", 8, "ORTHESES").
dico("O", 8, "ORTHOSES").
dico("O", 8, "ORTOLANS").
dico("O", 8, "ORVIETAN").
dico("O", 8, "OSASSENT").
dico("O", 8, "OSASSIEZ").
dico("O", 8, "OSCIETRE").
dico("O", 8, "OSCILLAI").
dico("O", 8, "OSCILLAS").
dico("O", 8, "OSCILLAT").
dico("O", 8, "OSCILLER").
dico("O", 8, "OSCILLES").
dico("O", 8, "OSCILLEZ").
dico("O", 8, "OSEILLES").
dico("O", 8, "OSERAIES").
dico("O", 8, "OSERIONS").
dico("O", 8, "OSMANLIE").
dico("O", 8, "OSMANLIS").
dico("O", 8, "OSMIQUES").
dico("O", 8, "OSMIURES").
dico("O", 8, "OSMONDES").
dico("O", 8, "OSSATURE").
dico("O", 8, "OSSEINES").
dico("O", 8, "OSSELETS").
dico("O", 8, "OSSEUSES").
dico("O", 8, "OSSICULE").
dico("O", 8, "OSSIFERE").
dico("O", 8, "OSSIFIAI").
dico("O", 8, "OSSIFIAS").
dico("O", 8, "OSSIFIAT").
dico("O", 8, "OSSIFIEE").
dico("O", 8, "OSSIFIER").
dico("O", 8, "OSSIFIES").
dico("O", 8, "OSSIFIEZ").
dico("O", 8, "OSSUAIRE").
dico("O", 8, "OSTEITES").
dico("O", 8, "OSTENSIF").
dico("O", 8, "OSTEOMES").
dico("O", 8, "OSTEOSES").
dico("O", 8, "OSTINATO").
dico("O", 8, "OSTIOLES").
dico("O", 8, "OSTRACEE").
dico("O", 8, "OSTRACES").
dico("O", 8, "OSTRACON").
dico("O", 8, "OSTREIDE").
dico("O", 8, "OSTROGOT").
dico("O", 8, "OTALGIES").
dico("O", 8, "OTASSENT").
dico("O", 8, "OTASSIEZ").
dico("O", 8, "OTERIONS").
dico("O", 8, "OTHELLOS").
dico("O", 8, "OTIDIDES").
dico("O", 8, "OTOCYONS").
dico("O", 8, "OTOCYSTE").
dico("O", 8, "OTOLITHE").
dico("O", 8, "OTOLOGIE").
dico("O", 8, "OTORHINO").
dico("O", 8, "OTORRHEE").
dico("O", 8, "OTOSCOPE").
dico("O", 8, "OTTOMANE").
dico("O", 8, "OTTOMANS").
dico("O", 8, "OTTONIEN").
dico("O", 8, "OUABAINE").
dico("O", 8, "OUAILLES").
dico("O", 8, "OUARINES").
dico("O", 8, "OUASSOUS").
dico("O", 8, "OUATAGES").
dico("O", 8, "OUATAMES").
dico("O", 8, "OUATASSE").
dico("O", 8, "OUATATES").
dico("O", 8, "OUATERAI").
dico("O", 8, "OUATERAS").
dico("O", 8, "OUATEREZ").
dico("O", 8, "OUATERIE").
dico("O", 8, "OUATEUSE").
dico("O", 8, "OUATINAI").
dico("O", 8, "OUATINAS").
dico("O", 8, "OUATINAT").
dico("O", 8, "OUATINEE").
dico("O", 8, "OUATINER").
dico("O", 8, "OUATINES").
dico("O", 8, "OUATINEZ").
dico("O", 8, "OUATIONS").
dico("O", 8, "OUBLIAIS").
dico("O", 8, "OUBLIAIT").
dico("O", 8, "OUBLIANT").
dico("O", 8, "OUBLIEES").
dico("O", 8, "OUBLIENT").
dico("O", 8, "OUBLIERA").
dico("O", 8, "OUBLIEUX").
dico("O", 8, "OUBLIIEZ").
dico("O", 8, "OUBLIONS").
dico("O", 8, "OUGRIENS").
dico("O", 8, "OUGUIYAS").
dico("O", 8, "OUIGHOUR").
dico("O", 8, "OUIGOURS").
dico("O", 8, "OUILLAGE").
dico("O", 8, "OUILLAIS").
dico("O", 8, "OUILLAIT").
dico("O", 8, "OUILLANT").
dico("O", 8, "OUILLEES").
dico("O", 8, "OUILLENT").
dico("O", 8, "OUILLERA").
dico("O", 8, "OUILLERE").
dico("O", 8, "OUILLIEZ").
dico("O", 8, "OUILLONS").
dico("O", 8, "OUISTITI").
dico("O", 8, "OULIPIEN").
dico("O", 8, "OULLIERE").
dico("O", 8, "OURAGANS").
dico("O", 8, "OURALIEN").
dico("O", 8, "OURAQUES").
dico("O", 8, "OURDIMES").
dico("O", 8, "OURDIRAI").
dico("O", 8, "OURDIRAS").
dico("O", 8, "OURDIREZ").
dico("O", 8, "OURDISSE").
dico("O", 8, "OURDITES").
dico("O", 8, "OURDOUES").
dico("O", 8, "OURLAMES").
dico("O", 8, "OURLASSE").
dico("O", 8, "OURLATES").
dico("O", 8, "OURLERAI").
dico("O", 8, "OURLERAS").
dico("O", 8, "OURLEREZ").
dico("O", 8, "OURLIENS").
dico("O", 8, "OURLIONS").
dico("O", 8, "OURSONNE").
dico("O", 8, "OUSTACHI").
dico("O", 8, "OUTARDES").
dico("O", 8, "OUTILLAI").
dico("O", 8, "OUTILLAS").
dico("O", 8, "OUTILLAT").
dico("O", 8, "OUTILLEE").
dico("O", 8, "OUTILLER").
dico("O", 8, "OUTILLES").
dico("O", 8, "OUTILLEZ").
dico("O", 8, "OUTRAGEA").
dico("O", 8, "OUTRAGEE").
dico("O", 8, "OUTRAGER").
dico("O", 8, "OUTRAGES").
dico("O", 8, "OUTRAGEZ").
dico("O", 8, "OUTRAMES").
dico("O", 8, "OUTRANCE").
dico("O", 8, "OUTRASSE").
dico("O", 8, "OUTRATES").
dico("O", 8, "OUTREMER").
dico("O", 8, "OUTRERAI").
dico("O", 8, "OUTRERAS").
dico("O", 8, "OUTREREZ").
dico("O", 8, "OUTRIONS").
dico("O", 8, "OUTSIDER").
dico("O", 8, "OUVERTES").
dico("O", 8, "OUVRABLE").
dico("O", 8, "OUVRAGEA").
dico("O", 8, "OUVRAGEE").
dico("O", 8, "OUVRAGER").
dico("O", 8, "OUVRAGES").
dico("O", 8, "OUVRAGEZ").
dico("O", 8, "OUVRAMES").
dico("O", 8, "OUVRANTE").
dico("O", 8, "OUVRANTS").
dico("O", 8, "OUVRASSE").
dico("O", 8, "OUVRATES").
dico("O", 8, "OUVREAUX").
dico("O", 8, "OUVRERAI").
dico("O", 8, "OUVRERAS").
dico("O", 8, "OUVREREZ").
dico("O", 8, "OUVREURS").
dico("O", 8, "OUVREUSE").
dico("O", 8, "OUVRIERE").
dico("O", 8, "OUVRIERS").
dico("O", 8, "OUVRIMES").
dico("O", 8, "OUVRIONS").
dico("O", 8, "OUVRIRAI").
dico("O", 8, "OUVRIRAS").
dico("O", 8, "OUVRIREZ").
dico("O", 8, "OUVRISSE").
dico("O", 8, "OUVRITES").
dico("O", 8, "OUVROIRS").
dico("O", 8, "OUZBEKES").
dico("O", 8, "OVALAIRE").
dico("O", 8, "OVALISAI").
dico("O", 8, "OVALISAS").
dico("O", 8, "OVALISAT").
dico("O", 8, "OVALISEE").
dico("O", 8, "OVALISER").
dico("O", 8, "OVALISES").
dico("O", 8, "OVALISEZ").
dico("O", 8, "OVARIENS").
dico("O", 8, "OVARITES").
dico("O", 8, "OVATIONS").
dico("O", 8, "OVERDOSE").
dico("O", 8, "OVICAPRE").
dico("O", 8, "OVICULES").
dico("O", 8, "OVIDUCTE").
dico("O", 8, "OVIFORME").
dico("O", 8, "OVIPARES").
dico("O", 8, "OVOCYTES").
dico("O", 8, "OVOGENIE").
dico("O", 8, "OVOGONIE").
dico("O", 8, "OVOIDALE").
dico("O", 8, "OVOIDAUX").
dico("O", 8, "OVOTIDES").
dico("O", 8, "OVULAIRE").
dico("O", 8, "OVULAMES").
dico("O", 8, "OVULASSE").
dico("O", 8, "OVULATES").
dico("O", 8, "OVULERAI").
dico("O", 8, "OVULERAS").
dico("O", 8, "OVULEREZ").
dico("O", 8, "OVULIONS").
dico("O", 8, "OXACIDES").
dico("O", 8, "OXALATES").
dico("O", 8, "OXALIDES").
dico("O", 8, "OXALIQUE").
dico("O", 8, "OXAMIDES").
dico("O", 8, "OXONIENS").
dico("O", 8, "OXONIUMS").
dico("O", 8, "OXYACIDE").
dico("O", 8, "OXYCRATS").
dico("O", 8, "OXYDABLE").
dico("O", 8, "OXYDAMES").
dico("O", 8, "OXYDANTE").
dico("O", 8, "OXYDANTS").
dico("O", 8, "OXYDASES").
dico("O", 8, "OXYDASSE").
dico("O", 8, "OXYDATES").
dico("O", 8, "OXYDERAI").
dico("O", 8, "OXYDERAS").
dico("O", 8, "OXYDEREZ").
dico("O", 8, "OXYDIONS").
dico("O", 8, "OXYGENAI").
dico("O", 8, "OXYGENAS").
dico("O", 8, "OXYGENAT").
dico("O", 8, "OXYGENEE").
dico("O", 8, "OXYGENER").
dico("O", 8, "OXYGENES").
dico("O", 8, "OXYGENEZ").
dico("O", 8, "OXYLITHE").
dico("O", 8, "OXYMORES").
dico("O", 8, "OXYMORON").
dico("O", 8, "OXYTONNE").
dico("O", 8, "OXYUROSE").
dico("O", 8, "OZENEUSE").
dico("O", 8, "OZONAMES").
dico("O", 8, "OZONASSE").
dico("O", 8, "OZONATES").
dico("O", 8, "OZONERAI").
dico("O", 8, "OZONERAS").
dico("O", 8, "OZONEREZ").
dico("O", 8, "OZONEURS").
dico("O", 8, "OZONIDES").
dico("O", 8, "OZONIONS").
dico("O", 8, "OZONISAI").
dico("O", 8, "OZONISAS").
dico("O", 8, "OZONISAT").
dico("O", 8, "OZONISEE").
dico("O", 8, "OZONISER").
dico("O", 8, "OZONISES").
dico("O", 8, "OZONISEZ").
