dico("P", 5, "PACAS").
dico("P", 5, "PACHA").
dico("P", 5, "PACKS").
dico("P", 5, "PACSA").
dico("P", 5, "PACSE").
dico("P", 5, "PACTE").
dico("P", 5, "PADAN").
dico("P", 5, "PADDY").
dico("P", 5, "PADOU").
dico("P", 5, "PAEAN").
dico("P", 5, "PAGEA").
dico("P", 5, "PAGEE").
dico("P", 5, "PAGEL").
dico("P", 5, "PAGER").
dico("P", 5, "PAGES").
dico("P", 5, "PAGEZ").
dico("P", 5, "PAGNE").
dico("P", 5, "PAGRE").
dico("P", 5, "PAGUS").
dico("P", 5, "PAIEN").
dico("P", 5, "PAIES").
dico("P", 5, "PAINS").
dico("P", 5, "PAIRE").
dico("P", 5, "PAIRS").
dico("P", 5, "PAJOT").
dico("P", 5, "PALAN").
dico("P", 5, "PALAS").
dico("P", 5, "PALEE").
dico("P", 5, "PALES").
dico("P", 5, "PALET").
dico("P", 5, "PALIE").
dico("P", 5, "PALIR").
dico("P", 5, "PALIS").
dico("P", 5, "PALIT").
dico("P", 5, "PALLE").
dico("P", 5, "PALMA").
dico("P", 5, "PALME").
dico("P", 5, "PALOT").
dico("P", 5, "PALOX").
dico("P", 5, "PALPA").
dico("P", 5, "PALPE").
dico("P", 5, "PALUD").
dico("P", 5, "PALUS").
dico("P", 5, "PAMAI").
dico("P", 5, "PAMAS").
dico("P", 5, "PAMAT").
dico("P", 5, "PAMEE").
dico("P", 5, "PAMER").
dico("P", 5, "PAMES").
dico("P", 5, "PAMEZ").
dico("P", 5, "PAMPA").
dico("P", 5, "PANAI").
dico("P", 5, "PANAS").
dico("P", 5, "PANAT").
dico("P", 5, "PANAX").
dico("P", 5, "PANCA").
dico("P", 5, "PANDA").
dico("P", 5, "PANEE").
dico("P", 5, "PANEL").
dico("P", 5, "PANER").
dico("P", 5, "PANES").
dico("P", 5, "PANEZ").
dico("P", 5, "PANIC").
dico("P", 5, "PANKA").
dico("P", 5, "PANNE").
dico("P", 5, "PANSA").
dico("P", 5, "PANSE").
dico("P", 5, "PANSU").
dico("P", 5, "PANTE").
dico("P", 5, "PANTY").
dico("P", 5, "PAONS").
dico("P", 5, "PAPAL").
dico("P", 5, "PAPAS").
dico("P", 5, "PAPES").
dico("P", 5, "PAPET").
dico("P", 5, "PAPIS").
dico("P", 5, "PAPOU").
dico("P", 5, "PAPYS").
dico("P", 5, "PAQUE").
dico("P", 5, "PARAI").
dico("P", 5, "PARAS").
dico("P", 5, "PARAT").
dico("P", 5, "PARCE").
dico("P", 5, "PARCS").
dico("P", 5, "PARDI").
dico("P", 5, "PAREE").
dico("P", 5, "PAREO").
dico("P", 5, "PARER").
dico("P", 5, "PARES").
dico("P", 5, "PAREZ").
dico("P", 5, "PARIA").
dico("P", 5, "PARIE").
dico("P", 5, "PARIS").
dico("P", 5, "PARKA").
dico("P", 5, "PARLA").
dico("P", 5, "PARLE").
dico("P", 5, "PARME").
dico("P", 5, "PARMI").
dico("P", 5, "PAROI").
dico("P", 5, "PAROS").
dico("P", 5, "PARSE").
dico("P", 5, "PARSI").
dico("P", 5, "PARTE").
dico("P", 5, "PARTI").
dico("P", 5, "PARTS").
dico("P", 5, "PARTY").
dico("P", 5, "PARUE").
dico("P", 5, "PARUS").
dico("P", 5, "PARUT").
dico("P", 5, "PASSA").
dico("P", 5, "PASSE").
dico("P", 5, "PATAS").
dico("P", 5, "PATCH").
dico("P", 5, "PATEE").
dico("P", 5, "PATER").
dico("P", 5, "PATES").
dico("P", 5, "PATIN").
dico("P", 5, "PATIO").
dico("P", 5, "PATIR").
dico("P", 5, "PATIS").
dico("P", 5, "PATIT").
dico("P", 5, "PATON").
dico("P", 5, "PATRE").
dico("P", 5, "PATTE").
dico("P", 5, "PATTU").
dico("P", 5, "PAUMA").
dico("P", 5, "PAUME").
dico("P", 5, "PAUSA").
dico("P", 5, "PAUSE").
dico("P", 5, "PAVAI").
dico("P", 5, "PAVAS").
dico("P", 5, "PAVAT").
dico("P", 5, "PAVEE").
dico("P", 5, "PAVER").
dico("P", 5, "PAVES").
dico("P", 5, "PAVEZ").
dico("P", 5, "PAVIE").
dico("P", 5, "PAVOT").
dico("P", 5, "PAXON").
dico("P", 5, "PAYAI").
dico("P", 5, "PAYAS").
dico("P", 5, "PAYAT").
dico("P", 5, "PAYEE").
dico("P", 5, "PAYER").
dico("P", 5, "PAYES").
dico("P", 5, "PAYEZ").
dico("P", 5, "PAYSE").
dico("P", 5, "PEAGE").
dico("P", 5, "PEANS").
dico("P", 5, "PEAUX").
dico("P", 5, "PECAN").
dico("P", 5, "PECHA").
dico("P", 5, "PECHE").
dico("P", 5, "PEDES").
dico("P", 5, "PEDUM").
dico("P", 5, "PEDZA").
dico("P", 5, "PEDZE").
dico("P", 5, "PEGOT").
dico("P", 5, "PEGRE").
dico("P", 5, "PEINA").
dico("P", 5, "PEINE").
dico("P", 5, "PEINS").
dico("P", 5, "PEINT").
dico("P", 5, "PEKAN").
dico("P", 5, "PEKET").
dico("P", 5, "PEKIN").
dico("P", 5, "PEKOE").
dico("P", 5, "PELAI").
dico("P", 5, "PELAS").
dico("P", 5, "PELAT").
dico("P", 5, "PELEE").
dico("P", 5, "PELER").
dico("P", 5, "PELES").
dico("P", 5, "PELEZ").
dico("P", 5, "PELLA").
dico("P", 5, "PELLE").
dico("P", 5, "PELTA").
dico("P", 5, "PELTE").
dico("P", 5, "PENAL").
dico("P", 5, "PENCE").
dico("P", 5, "PENDE").
dico("P", 5, "PENDS").
dico("P", 5, "PENDU").
dico("P", 5, "PENES").
dico("P", 5, "PENIL").
dico("P", 5, "PENIS").
dico("P", 5, "PENNE").
dico("P", 5, "PENNY").
dico("P", 5, "PENON").
dico("P", 5, "PENSA").
dico("P", 5, "PENSE").
dico("P", 5, "PENTE").
dico("P", 5, "PENTU").
dico("P", 5, "PENTY").
dico("P", 5, "PEONS").
dico("P", 5, "PEPEE").
dico("P", 5, "PEPES").
dico("P", 5, "PEPIA").
dico("P", 5, "PEPIE").
dico("P", 5, "PEPIN").
dico("P", 5, "PEPON").
dico("P", 5, "PERCA").
dico("P", 5, "PERCE").
dico("P", 5, "PERCU").
dico("P", 5, "PERDE").
dico("P", 5, "PERDS").
dico("P", 5, "PERDU").
dico("P", 5, "PERES").
dico("P", 5, "PERFS").
dico("P", 5, "PERIE").
dico("P", 5, "PERIF").
dico("P", 5, "PERIL").
dico("P", 5, "PERIR").
dico("P", 5, "PERIS").
dico("P", 5, "PERIT").
dico("P", 5, "PERLA").
dico("P", 5, "PERLE").
dico("P", 5, "PERME").
dico("P", 5, "PERMS").
dico("P", 5, "PEROT").
dico("P", 5, "PERRE").
dico("P", 5, "PERSE").
dico("P", 5, "PERSO").
dico("P", 5, "PERTE").
dico("P", 5, "PESAI").
dico("P", 5, "PESAS").
dico("P", 5, "PESAT").
dico("P", 5, "PESEE").
dico("P", 5, "PESER").
dico("P", 5, "PESES").
dico("P", 5, "PESEZ").
dico("P", 5, "PESON").
dico("P", 5, "PESOS").
dico("P", 5, "PESSE").
dico("P", 5, "PESTA").
dico("P", 5, "PESTE").
dico("P", 5, "PESTO").
dico("P", 5, "PETAI").
dico("P", 5, "PETAS").
dico("P", 5, "PETAT").
dico("P", 5, "PETEE").
dico("P", 5, "PETER").
dico("P", 5, "PETES").
dico("P", 5, "PETEZ").
dico("P", 5, "PETIT").
dico("P", 5, "PETON").
dico("P", 5, "PETRE").
dico("P", 5, "PETRI").
dico("P", 5, "PETUN").
dico("P", 5, "PEUHL").
dico("P", 5, "PEULE").
dico("P", 5, "PEULS").
dico("P", 5, "PEURS").
dico("P", 5, "PEZES").
dico("P", 5, "PHAGE").
dico("P", 5, "PHARE").
dico("P", 5, "PHASE").
dico("P", 5, "PHILO").
dico("P", 5, "PHLOX").
dico("P", 5, "PHONE").
dico("P", 5, "PHONO").
dico("P", 5, "PHOTO").
dico("P", 5, "PHOTS").
dico("P", 5, "PHYLA").
dico("P", 5, "PHYSE").
dico("P", 5, "PIAFS").
dico("P", 5, "PIANO").
dico("P", 5, "PIANS").
dico("P", 5, "PIBLE").
dico("P", 5, "PICAS").
dico("P", 5, "PICON").
dico("P", 5, "PICOT").
dico("P", 5, "PIECE").
dico("P", 5, "PIEDS").
dico("P", 5, "PIEGE").
dico("P", 5, "PIERS").
dico("P", 5, "PIETA").
dico("P", 5, "PIETE").
dico("P", 5, "PIEUX").
dico("P", 5, "PIEZE").
dico("P", 5, "PIFAI").
dico("P", 5, "PIFAS").
dico("P", 5, "PIFAT").
dico("P", 5, "PIFEE").
dico("P", 5, "PIFER").
dico("P", 5, "PIFES").
dico("P", 5, "PIFEZ").
dico("P", 5, "PIFFA").
dico("P", 5, "PIFFE").
dico("P", 5, "PIGEA").
dico("P", 5, "PIGEE").
dico("P", 5, "PIGER").
dico("P", 5, "PIGES").
dico("P", 5, "PIGEZ").
dico("P", 5, "PIGNE").
dico("P", 5, "PILAF").
dico("P", 5, "PILAI").
dico("P", 5, "PILAS").
dico("P", 5, "PILAT").
dico("P", 5, "PILAU").
dico("P", 5, "PILAW").
dico("P", 5, "PILEE").
dico("P", 5, "PILER").
dico("P", 5, "PILES").
dico("P", 5, "PILET").
dico("P", 5, "PILEZ").
dico("P", 5, "PILLA").
dico("P", 5, "PILLE").
dico("P", 5, "PILON").
dico("P", 5, "PILOT").
dico("P", 5, "PILOU").
dico("P", 5, "PILUM").
dico("P", 5, "PINCA").
dico("P", 5, "PINCE").
dico("P", 5, "PINES").
dico("P", 5, "PINNE").
dico("P", 5, "PINOT").
dico("P", 5, "PINTA").
dico("P", 5, "PINTE").
dico("P", 5, "PIONS").
dico("P", 5, "PIPAI").
dico("P", 5, "PIPAS").
dico("P", 5, "PIPAT").
dico("P", 5, "PIPEE").
dico("P", 5, "PIPER").
dico("P", 5, "PIPES").
dico("P", 5, "PIPEZ").
dico("P", 5, "PIPIS").
dico("P", 5, "PIPIT").
dico("P", 5, "PIPOS").
dico("P", 5, "PIQUA").
dico("P", 5, "PIQUE").
dico("P", 5, "PIRES").
dico("P", 5, "PISAN").
dico("P", 5, "PISES").
dico("P", 5, "PISSA").
dico("P", 5, "PISSE").
dico("P", 5, "PISTA").
dico("P", 5, "PISTE").
dico("P", 5, "PITAS").
dico("P", 5, "PITCH").
dico("P", 5, "PITES").
dico("P", 5, "PITIE").
dico("P", 5, "PITON").
dico("P", 5, "PITOU").
dico("P", 5, "PITRE").
dico("P", 5, "PITTA").
dico("P", 5, "PIVES").
dico("P", 5, "PIVOT").
dico("P", 5, "PIXEL").
dico("P", 5, "PIZZA").
dico("P", 5, "PLACA").
dico("P", 5, "PLACE").
dico("P", 5, "PLAGE").
dico("P", 5, "PLAID").
dico("P", 5, "PLAIE").
dico("P", 5, "PLAIN").
dico("P", 5, "PLAIS").
dico("P", 5, "PLAIT").
dico("P", 5, "PLANA").
dico("P", 5, "PLANE").
dico("P", 5, "PLANS").
dico("P", 5, "PLANT").
dico("P", 5, "PLATE").
dico("P", 5, "PLATS").
dico("P", 5, "PLEBE").
dico("P", 5, "PLEIN").
dico("P", 5, "PLEUR").
dico("P", 5, "PLEUT").
dico("P", 5, "PLIAI").
dico("P", 5, "PLIAS").
dico("P", 5, "PLIAT").
dico("P", 5, "PLIEE").
dico("P", 5, "PLIER").
dico("P", 5, "PLIES").
dico("P", 5, "PLIEZ").
dico("P", 5, "PLINT").
dico("P", 5, "PLION").
dico("P", 5, "PLOCS").
dico("P", 5, "PLOIE").
dico("P", 5, "PLOMB").
dico("P", 5, "PLOTS").
dico("P", 5, "PLOUC").
dico("P", 5, "PLOUF").
dico("P", 5, "PLOUK").
dico("P", 5, "PLOYA").
dico("P", 5, "PLOYE").
dico("P", 5, "PLUIE").
dico("P", 5, "PLUMA").
dico("P", 5, "PLUME").
dico("P", 5, "PNEUS").
dico("P", 5, "POCHA").
dico("P", 5, "POCHE").
dico("P", 5, "PODAL").
dico("P", 5, "PODIA").
dico("P", 5, "POELA").
dico("P", 5, "POELE").
dico("P", 5, "POEME").
dico("P", 5, "POETE").
dico("P", 5, "POGNE").
dico("P", 5, "POIDS").
dico("P", 5, "POILA").
dico("P", 5, "POILE").
dico("P", 5, "POILS").
dico("P", 5, "POILU").
dico("P", 5, "POING").
dico("P", 5, "POINS").
dico("P", 5, "POINT").
dico("P", 5, "POIRE").
dico("P", 5, "POISE").
dico("P", 5, "POKER").
dico("P", 5, "POLAR").
dico("P", 5, "POLES").
dico("P", 5, "POLIE").
dico("P", 5, "POLIO").
dico("P", 5, "POLIR").
dico("P", 5, "POLIS").
dico("P", 5, "POLIT").
dico("P", 5, "POLJE").
dico("P", 5, "POLKA").
dico("P", 5, "POLOS").
dico("P", 5, "POLYS").
dico("P", 5, "POMMA").
dico("P", 5, "POMME").
dico("P", 5, "POMPA").
dico("P", 5, "POMPE").
dico("P", 5, "PONCA").
dico("P", 5, "PONCE").
dico("P", 5, "PONDE").
dico("P", 5, "PONDS").
dico("P", 5, "PONDU").
dico("P", 5, "PONEY").
dico("P", 5, "PONGE").
dico("P", 5, "PONOT").
dico("P", 5, "PONTA").
dico("P", 5, "PONTE").
dico("P", 5, "PONTS").
dico("P", 5, "POOLS").
dico("P", 5, "POPAH").
dico("P", 5, "POPES").
dico("P", 5, "POQUA").
dico("P", 5, "POQUE").
dico("P", 5, "PORCS").
dico("P", 5, "PORES").
dico("P", 5, "PORNO").
dico("P", 5, "PORTA").
dico("P", 5, "PORTE").
dico("P", 5, "PORTO").
dico("P", 5, "PORTS").
dico("P", 5, "POSAI").
dico("P", 5, "POSAS").
dico("P", 5, "POSAT").
dico("P", 5, "POSEE").
dico("P", 5, "POSER").
dico("P", 5, "POSES").
dico("P", 5, "POSEZ").
dico("P", 5, "POSTA").
dico("P", 5, "POSTE").
dico("P", 5, "POTEE").
dico("P", 5, "POTES").
dico("P", 5, "POTIN").
dico("P", 5, "POTTO").
dico("P", 5, "POTUE").
dico("P", 5, "POTUS").
dico("P", 5, "POUAH").
dico("P", 5, "POUCA").
dico("P", 5, "POUCE").
dico("P", 5, "POUFS").
dico("P", 5, "POULE").
dico("P", 5, "POULS").
dico("P", 5, "POUND").
dico("P", 5, "POUPE").
dico("P", 5, "POYAS").
dico("P", 5, "PRAME").
dico("P", 5, "PRAOS").
dico("P", 5, "PREAU").
dico("P", 5, "PRELE").
dico("P", 5, "PREND").
dico("P", 5, "PREPA").
dico("P", 5, "PRETA").
dico("P", 5, "PRETE").
dico("P", 5, "PRETS").
dico("P", 5, "PREUX").
dico("P", 5, "PREVU").
dico("P", 5, "PRIAI").
dico("P", 5, "PRIAS").
dico("P", 5, "PRIAT").
dico("P", 5, "PRIEE").
dico("P", 5, "PRIER").
dico("P", 5, "PRIES").
dico("P", 5, "PRIEZ").
dico("P", 5, "PRIMA").
dico("P", 5, "PRIME").
dico("P", 5, "PRIMO").
dico("P", 5, "PRION").
dico("P", 5, "PRISA").
dico("P", 5, "PRISE").
dico("P", 5, "PRIVA").
dico("P", 5, "PRIVE").
dico("P", 5, "PROBA").
dico("P", 5, "PROBE").
dico("P", 5, "PROFS").
dico("P", 5, "PROIE").
dico("P", 5, "PROLO").
dico("P", 5, "PROMO").
dico("P", 5, "PROMU").
dico("P", 5, "PRONA").
dico("P", 5, "PRONE").
dico("P", 5, "PROSE").
dico("P", 5, "PROTE").
dico("P", 5, "PROTO").
dico("P", 5, "PROUE").
dico("P", 5, "PROUT").
dico("P", 5, "PROVO").
dico("P", 5, "PRUDE").
dico("P", 5, "PRUNE").
dico("P", 5, "PSITT").
dico("P", 5, "PSOAS").
dico("P", 5, "PSORE").
dico("P", 5, "PTOSE").
dico("P", 5, "PUAIS").
dico("P", 5, "PUAIT").
dico("P", 5, "PUANT").
dico("P", 5, "PUBIS").
dico("P", 5, "PUCES").
dico("P", 5, "PUCHE").
dico("P", 5, "PUCKS").
dico("P", 5, "PUEES").
dico("P", 5, "PUENT").
dico("P", 5, "PUERA").
dico("P", 5, "PUIEZ").
dico("P", 5, "PUINE").
dico("P", 5, "PUISA").
dico("P", 5, "PUISE").
dico("P", 5, "PUITS").
dico("P", 5, "PUJAS").
dico("P", 5, "PULAS").
dico("P", 5, "PULLS").
dico("P", 5, "PULPE").
dico("P", 5, "PULSA").
dico("P", 5, "PULSE").
dico("P", 5, "PUMAS").
dico("P", 5, "PUMES").
dico("P", 5, "PUNAS").
dico("P", 5, "PUNCH").
dico("P", 5, "PUNIE").
dico("P", 5, "PUNIR").
dico("P", 5, "PUNIS").
dico("P", 5, "PUNIT").
dico("P", 5, "PUNKS").
dico("P", 5, "PUNTS").
dico("P", 5, "PUONS").
dico("P", 5, "PUPES").
dico("P", 5, "PUREE").
dico("P", 5, "PURES").
dico("P", 5, "PURGE").
dico("P", 5, "PURIN").
dico("P", 5, "PUROT").
dico("P", 5, "PUSSE").
dico("P", 5, "PUTES").
dico("P", 5, "PUTTA").
dico("P", 5, "PUTTE").
dico("P", 5, "PUTTI").
dico("P", 5, "PUTTO").
dico("P", 5, "PUTTS").
dico("P", 5, "PYREX").
