dico("P", 6, "PACAGE").
dico("P", 6, "PACANE").
dico("P", 6, "PACHAS").
dico("P", 6, "PACHTO").
dico("P", 6, "PACQUA").
dico("P", 6, "PACQUE").
dico("P", 6, "PACSAI").
dico("P", 6, "PACSAS").
dico("P", 6, "PACSAT").
dico("P", 6, "PACSEE").
dico("P", 6, "PACSER").
dico("P", 6, "PACSES").
dico("P", 6, "PACSEZ").
dico("P", 6, "PACSON").
dico("P", 6, "PACTES").
dico("P", 6, "PADANE").
dico("P", 6, "PADANS").
dico("P", 6, "PADDYS").
dico("P", 6, "PADINE").
dico("P", 6, "PADOUE").
dico("P", 6, "PADOUS").
dico("P", 6, "PAEANS").
dico("P", 6, "PAELLA").
dico("P", 6, "PAGAIE").
dico("P", 6, "PAGAYA").
dico("P", 6, "PAGAYE").
dico("P", 6, "PAGEAI").
dico("P", 6, "PAGEAS").
dico("P", 6, "PAGEAT").
dico("P", 6, "PAGEES").
dico("P", 6, "PAGELS").
dico("P", 6, "PAGENT").
dico("P", 6, "PAGEOT").
dico("P", 6, "PAGERA").
dico("P", 6, "PAGERS").
dico("P", 6, "PAGEUR").
dico("P", 6, "PAGIEZ").
dico("P", 6, "PAGINA").
dico("P", 6, "PAGINE").
dico("P", 6, "PAGING").
dico("P", 6, "PAGNES").
dico("P", 6, "PAGNON").
dico("P", 6, "PAGNOT").
dico("P", 6, "PAGODE").
dico("P", 6, "PAGRES").
dico("P", 6, "PAGURE").
dico("P", 6, "PAIENS").
dico("P", 6, "PAIENT").
dico("P", 6, "PAIERA").
dico("P", 6, "PAILLA").
dico("P", 6, "PAILLE").
dico("P", 6, "PAIRES").
dico("P", 6, "PAIRIE").
dico("P", 6, "PAIRLE").
dico("P", 6, "PAISSE").
dico("P", 6, "PAITRA").
dico("P", 6, "PAITRE").
dico("P", 6, "PAJOTS").
dico("P", 6, "PALACE").
dico("P", 6, "PALAIS").
dico("P", 6, "PALANS").
dico("P", 6, "PALEES").
dico("P", 6, "PALETA").
dico("P", 6, "PALETS").
dico("P", 6, "PALEUR").
dico("P", 6, "PALIER").
dico("P", 6, "PALIES").
dico("P", 6, "PALIRA").
dico("P", 6, "PALLES").
dico("P", 6, "PALLIA").
dico("P", 6, "PALLIE").
dico("P", 6, "PALMAI").
dico("P", 6, "PALMAS").
dico("P", 6, "PALMAT").
dico("P", 6, "PALMEE").
dico("P", 6, "PALMER").
dico("P", 6, "PALMES").
dico("P", 6, "PALMEZ").
dico("P", 6, "PALOIS").
dico("P", 6, "PALOTA").
dico("P", 6, "PALOTE").
dico("P", 6, "PALOTS").
dico("P", 6, "PALPAI").
dico("P", 6, "PALPAS").
dico("P", 6, "PALPAT").
dico("P", 6, "PALPEE").
dico("P", 6, "PALPER").
dico("P", 6, "PALPES").
dico("P", 6, "PALPEZ").
dico("P", 6, "PALUDE").
dico("P", 6, "PALUDS").
dico("P", 6, "PAMAIS").
dico("P", 6, "PAMAIT").
dico("P", 6, "PAMANT").
dico("P", 6, "PAMEES").
dico("P", 6, "PAMENT").
dico("P", 6, "PAMERA").
dico("P", 6, "PAMIEZ").
dico("P", 6, "PAMONS").
dico("P", 6, "PAMPAS").
dico("P", 6, "PAMPRE").
dico("P", 6, "PANACE").
dico("P", 6, "PANADE").
dico("P", 6, "PANAIS").
dico("P", 6, "PANAIT").
dico("P", 6, "PANAMA").
dico("P", 6, "PANANT").
dico("P", 6, "PANARD").
dico("P", 6, "PANCAS").
dico("P", 6, "PANDAS").
dico("P", 6, "PANDIT").
dico("P", 6, "PANEES").
dico("P", 6, "PANELS").
dico("P", 6, "PANENT").
dico("P", 6, "PANERA").
dico("P", 6, "PANICS").
dico("P", 6, "PANIER").
dico("P", 6, "PANIEZ").
dico("P", 6, "PANINI").
dico("P", 6, "PANKAS").
dico("P", 6, "PANNEE").
dico("P", 6, "PANNES").
dico("P", 6, "PANONS").
dico("P", 6, "PANSAI").
dico("P", 6, "PANSAS").
dico("P", 6, "PANSAT").
dico("P", 6, "PANSEE").
dico("P", 6, "PANSER").
dico("P", 6, "PANSES").
dico("P", 6, "PANSEZ").
dico("P", 6, "PANSUE").
dico("P", 6, "PANSUS").
dico("P", 6, "PANTES").
dico("P", 6, "PANTET").
dico("P", 6, "PANTIN").
dico("P", 6, "PANTYS").
dico("P", 6, "PANURE").
dico("P", 6, "PANZER").
dico("P", 6, "PAONNE").
dico("P", 6, "PAPALE").
dico("P", 6, "PAPAUX").
dico("P", 6, "PAPAYE").
dico("P", 6, "PAPETS").
dico("P", 6, "PAPIER").
dico("P", 6, "PAPION").
dico("P", 6, "PAPOTA").
dico("P", 6, "PAPOTE").
dico("P", 6, "PAPOUE").
dico("P", 6, "PAPOUS").
dico("P", 6, "PAPULE").
dico("P", 6, "PAQSON").
dico("P", 6, "PAQUES").
dico("P", 6, "PAQUET").
dico("P", 6, "PAQUIS").
dico("P", 6, "PARADA").
dico("P", 6, "PARADE").
dico("P", 6, "PARAFA").
dico("P", 6, "PARAFE").
dico("P", 6, "PARAGE").
dico("P", 6, "PARAIS").
dico("P", 6, "PARAIT").
dico("P", 6, "PARANO").
dico("P", 6, "PARANT").
dico("P", 6, "PARDON").
dico("P", 6, "PAREES").
dico("P", 6, "PAREIL").
dico("P", 6, "PARENT").
dico("P", 6, "PAREOS").
dico("P", 6, "PARERA").
dico("P", 6, "PARERE").
dico("P", 6, "PAREUR").
dico("P", 6, "PARFIS").
dico("P", 6, "PARFIT").
dico("P", 6, "PARFUM").
dico("P", 6, "PARIAI").
dico("P", 6, "PARIAN").
dico("P", 6, "PARIAS").
dico("P", 6, "PARIAT").
dico("P", 6, "PARIDE").
dico("P", 6, "PARIEE").
dico("P", 6, "PARIER").
dico("P", 6, "PARIES").
dico("P", 6, "PARIEZ").
dico("P", 6, "PARITE").
dico("P", 6, "PARKAS").
dico("P", 6, "PARLAI").
dico("P", 6, "PARLAS").
dico("P", 6, "PARLAT").
dico("P", 6, "PARLEE").
dico("P", 6, "PARLER").
dico("P", 6, "PARLES").
dico("P", 6, "PARLEZ").
dico("P", 6, "PARMES").
dico("P", 6, "PAROIR").
dico("P", 6, "PAROIS").
dico("P", 6, "PAROLE").
dico("P", 6, "PAROLI").
dico("P", 6, "PARONS").
dico("P", 6, "PARQUA").
dico("P", 6, "PARQUE").
dico("P", 6, "PARSEC").
dico("P", 6, "PARSES").
dico("P", 6, "PARSIE").
dico("P", 6, "PARSIS").
dico("P", 6, "PARTES").
dico("P", 6, "PARTEZ").
dico("P", 6, "PARTHE").
dico("P", 6, "PARTIE").
dico("P", 6, "PARTIR").
dico("P", 6, "PARTIS").
dico("P", 6, "PARTIT").
dico("P", 6, "PARTON").
dico("P", 6, "PARTYS").
dico("P", 6, "PARUES").
dico("P", 6, "PARURE").
dico("P", 6, "PARVIS").
dico("P", 6, "PASCAL").
dico("P", 6, "PASSAI").
dico("P", 6, "PASSAS").
dico("P", 6, "PASSAT").
dico("P", 6, "PASSEE").
dico("P", 6, "PASSER").
dico("P", 6, "PASSES").
dico("P", 6, "PASSET").
dico("P", 6, "PASSEZ").
dico("P", 6, "PASSIF").
dico("P", 6, "PASSIM").
dico("P", 6, "PASTEL").
dico("P", 6, "PASTIS").
dico("P", 6, "PATACA").
dico("P", 6, "PATARD").
dico("P", 6, "PATATE").
dico("P", 6, "PATAUD").
dico("P", 6, "PATCHS").
dico("P", 6, "PATEES").
dico("P", 6, "PATENE").
dico("P", 6, "PATENT").
dico("P", 6, "PATERE").
dico("P", 6, "PATERS").
dico("P", 6, "PATEUX").
dico("P", 6, "PATHIE").
dico("P", 6, "PATHOS").
dico("P", 6, "PATINA").
dico("P", 6, "PATINE").
dico("P", 6, "PATINS").
dico("P", 6, "PATIOS").
dico("P", 6, "PATIRA").
dico("P", 6, "PATOIS").
dico("P", 6, "PATONS").
dico("P", 6, "PATRES").
dico("P", 6, "PATRIE").
dico("P", 6, "PATRON").
dico("P", 6, "PATTEE").
dico("P", 6, "PATTES").
dico("P", 6, "PATTUE").
dico("P", 6, "PATTUS").
dico("P", 6, "PATURA").
dico("P", 6, "PATURE").
dico("P", 6, "PAUMAI").
dico("P", 6, "PAUMAS").
dico("P", 6, "PAUMAT").
dico("P", 6, "PAUMEE").
dico("P", 6, "PAUMER").
dico("P", 6, "PAUMES").
dico("P", 6, "PAUMEZ").
dico("P", 6, "PAUSAI").
dico("P", 6, "PAUSAS").
dico("P", 6, "PAUSAT").
dico("P", 6, "PAUSER").
dico("P", 6, "PAUSES").
dico("P", 6, "PAUSEZ").
dico("P", 6, "PAUVRE").
dico("P", 6, "PAVAGE").
dico("P", 6, "PAVAIS").
dico("P", 6, "PAVAIT").
dico("P", 6, "PAVANA").
dico("P", 6, "PAVANE").
dico("P", 6, "PAVANT").
dico("P", 6, "PAVEES").
dico("P", 6, "PAVENT").
dico("P", 6, "PAVERA").
dico("P", 6, "PAVEUR").
dico("P", 6, "PAVIES").
dico("P", 6, "PAVIEZ").
dico("P", 6, "PAVOIS").
dico("P", 6, "PAVONS").
dico("P", 6, "PAVOTS").
dico("P", 6, "PAWNEE").
dico("P", 6, "PAXONS").
dico("P", 6, "PAYAIS").
dico("P", 6, "PAYAIT").
dico("P", 6, "PAYANT").
dico("P", 6, "PAYEES").
dico("P", 6, "PAYENT").
dico("P", 6, "PAYERA").
dico("P", 6, "PAYEUR").
dico("P", 6, "PAYIEZ").
dico("P", 6, "PAYONS").
dico("P", 6, "PAYSAN").
dico("P", 6, "PAYSES").
dico("P", 6, "PEAGER").
dico("P", 6, "PEAGES").
dico("P", 6, "PEBROC").
dico("P", 6, "PECANS").
dico("P", 6, "PECARI").
dico("P", 6, "PECHAI").
dico("P", 6, "PECHAS").
dico("P", 6, "PECHAT").
dico("P", 6, "PECHEE").
dico("P", 6, "PECHER").
dico("P", 6, "PECHES").
dico("P", 6, "PECHEZ").
dico("P", 6, "PECNOT").
dico("P", 6, "PECORE").
dico("P", 6, "PECQUE").
dico("P", 6, "PECTEN").
dico("P", 6, "PECULE").
dico("P", 6, "PECUNE").
dico("P", 6, "PEDALA").
dico("P", 6, "PEDALE").
dico("P", 6, "PEDALO").
dico("P", 6, "PEDANT").
dico("P", 6, "PEDEGE").
dico("P", 6, "PEDESE").
dico("P", 6, "PEDUMS").
dico("P", 6, "PEDZAI").
dico("P", 6, "PEDZAS").
dico("P", 6, "PEDZAT").
dico("P", 6, "PEDZER").
dico("P", 6, "PEDZES").
dico("P", 6, "PEDZEZ").
dico("P", 6, "PEGASE").
dico("P", 6, "PEGOTS").
dico("P", 6, "PEGRES").
dico("P", 6, "PEHLVI").
dico("P", 6, "PEIGNA").
dico("P", 6, "PEIGNE").
dico("P", 6, "PEILLE").
dico("P", 6, "PEINAI").
dico("P", 6, "PEINAS").
dico("P", 6, "PEINAT").
dico("P", 6, "PEINEE").
dico("P", 6, "PEINER").
dico("P", 6, "PEINES").
dico("P", 6, "PEINEZ").
dico("P", 6, "PEINTE").
dico("P", 6, "PEINTS").
dico("P", 6, "PEKANS").
dico("P", 6, "PEKETS").
dico("P", 6, "PEKINE").
dico("P", 6, "PEKINS").
dico("P", 6, "PEKOES").
dico("P", 6, "PELADE").
dico("P", 6, "PELAGE").
dico("P", 6, "PELAIS").
dico("P", 6, "PELAIT").
dico("P", 6, "PELANT").
dico("P", 6, "PELARD").
dico("P", 6, "PELEEN").
dico("P", 6, "PELEES").
dico("P", 6, "PELENT").
dico("P", 6, "PELERA").
dico("P", 6, "PELIEZ").
dico("P", 6, "PELLAI").
dico("P", 6, "PELLAS").
dico("P", 6, "PELLAT").
dico("P", 6, "PELLEE").
dico("P", 6, "PELLER").
dico("P", 6, "PELLES").
dico("P", 6, "PELLET").
dico("P", 6, "PELLEZ").
dico("P", 6, "PELONS").
dico("P", 6, "PELOTA").
dico("P", 6, "PELOTE").
dico("P", 6, "PELTAS").
dico("P", 6, "PELTEE").
dico("P", 6, "PELTES").
dico("P", 6, "PELURE").
dico("P", 6, "PELVIS").
dico("P", 6, "PENALE").
dico("P", 6, "PENARD").
dico("P", 6, "PENAUD").
dico("P", 6, "PENAUX").
dico("P", 6, "PENCHA").
dico("P", 6, "PENCHE").
dico("P", 6, "PENDES").
dico("P", 6, "PENDEZ").
dico("P", 6, "PENDIS").
dico("P", 6, "PENDIT").
dico("P", 6, "PENDRA").
dico("P", 6, "PENDRE").
dico("P", 6, "PENDUE").
dico("P", 6, "PENDUS").
dico("P", 6, "PENIEN").
dico("P", 6, "PENILS").
dico("P", 6, "PENNEE").
dico("P", 6, "PENNES").
dico("P", 6, "PENNON").
dico("P", 6, "PENNYS").
dico("P", 6, "PENONS").
dico("P", 6, "PENSAI").
dico("P", 6, "PENSAS").
dico("P", 6, "PENSAT").
dico("P", 6, "PENSEE").
dico("P", 6, "PENSER").
dico("P", 6, "PENSES").
dico("P", 6, "PENSEZ").
dico("P", 6, "PENSIF").
dico("P", 6, "PENSUM").
dico("P", 6, "PENTES").
dico("P", 6, "PENTUE").
dico("P", 6, "PENTUS").
dico("P", 6, "PENTYS").
dico("P", 6, "PEONES").
dico("P", 6, "PEOPLE").
dico("P", 6, "PEOTTE").
dico("P", 6, "PEPEES").
dico("P", 6, "PEPERE").
dico("P", 6, "PEPIAI").
dico("P", 6, "PEPIAS").
dico("P", 6, "PEPIAT").
dico("P", 6, "PEPIER").
dico("P", 6, "PEPIES").
dico("P", 6, "PEPIEZ").
dico("P", 6, "PEPINE").
dico("P", 6, "PEPINS").
dico("P", 6, "PEPITE").
dico("P", 6, "PEPLOS").
dico("P", 6, "PEPLUM").
dico("P", 6, "PEPONS").
dico("P", 6, "PEQUET").
dico("P", 6, "PEQUIN").
dico("P", 6, "PERCAI").
dico("P", 6, "PERCAS").
dico("P", 6, "PERCAT").
dico("P", 6, "PERCEE").
dico("P", 6, "PERCER").
dico("P", 6, "PERCES").
dico("P", 6, "PERCET").
dico("P", 6, "PERCEZ").
dico("P", 6, "PERCHA").
dico("P", 6, "PERCHE").
dico("P", 6, "PERCUE").
dico("P", 6, "PERCUS").
dico("P", 6, "PERCUT").
dico("P", 6, "PERDES").
dico("P", 6, "PERDEZ").
dico("P", 6, "PERDIS").
dico("P", 6, "PERDIT").
dico("P", 6, "PERDRA").
dico("P", 6, "PERDRE").
dico("P", 6, "PERDUE").
dico("P", 6, "PERDUS").
dico("P", 6, "PERIES").
dico("P", 6, "PERIFS").
dico("P", 6, "PERILS").
dico("P", 6, "PERIMA").
dico("P", 6, "PERIME").
dico("P", 6, "PERIPH").
dico("P", 6, "PERIRA").
dico("P", 6, "PERLAI").
dico("P", 6, "PERLAN").
dico("P", 6, "PERLAS").
dico("P", 6, "PERLAT").
dico("P", 6, "PERLEE").
dico("P", 6, "PERLER").
dico("P", 6, "PERLES").
dico("P", 6, "PERLEZ").
dico("P", 6, "PERLON").
dico("P", 6, "PERLOT").
dico("P", 6, "PERMES").
dico("P", 6, "PERMET").
dico("P", 6, "PERMIS").
dico("P", 6, "PERMIT").
dico("P", 6, "PERNOD").
dico("P", 6, "PERONE").
dico("P", 6, "PERORA").
dico("P", 6, "PERORE").
dico("P", 6, "PEROTS").
dico("P", 6, "PERRES").
dico("P", 6, "PERRON").
dico("P", 6, "PERSAN").
dico("P", 6, "PERSEL").
dico("P", 6, "PERSES").
dico("P", 6, "PERSIL").
dico("P", 6, "PERSOS").
dico("P", 6, "PERTES").
dico("P", 6, "PESADE").
dico("P", 6, "PESAGE").
dico("P", 6, "PESAIS").
dico("P", 6, "PESAIT").
dico("P", 6, "PESANT").
dico("P", 6, "PESEES").
dico("P", 6, "PESENT").
dico("P", 6, "PESERA").
dico("P", 6, "PESETA").
dico("P", 6, "PESEUR").
dico("P", 6, "PESIEZ").
dico("P", 6, "PESONS").
dico("P", 6, "PESSAH").
dico("P", 6, "PESSES").
dico("P", 6, "PESTAI").
dico("P", 6, "PESTAS").
dico("P", 6, "PESTAT").
dico("P", 6, "PESTER").
dico("P", 6, "PESTES").
dico("P", 6, "PESTEZ").
dico("P", 6, "PESTOS").
dico("P", 6, "PETAIS").
dico("P", 6, "PETAIT").
dico("P", 6, "PETALE").
dico("P", 6, "PETANT").
dico("P", 6, "PETARD").
dico("P", 6, "PETASE").
dico("P", 6, "PETEES").
dico("P", 6, "PETENT").
dico("P", 6, "PETERA").
dico("P", 6, "PETEUR").
dico("P", 6, "PETEUX").
dico("P", 6, "PETIEZ").
dico("P", 6, "PETIOT").
dico("P", 6, "PETITE").
dico("P", 6, "PETITS").
dico("P", 6, "PETOLE").
dico("P", 6, "PETONS").
dico("P", 6, "PETREE").
dico("P", 6, "PETREL").
dico("P", 6, "PETRES").
dico("P", 6, "PETRIE").
dico("P", 6, "PETRIN").
dico("P", 6, "PETRIR").
dico("P", 6, "PETRIS").
dico("P", 6, "PETRIT").
dico("P", 6, "PETUNA").
dico("P", 6, "PETUNE").
dico("P", 6, "PETUNS").
dico("P", 6, "PEUHLE").
dico("P", 6, "PEUHLS").
dico("P", 6, "PEULES").
dico("P", 6, "PEUPLA").
dico("P", 6, "PEUPLE").
dico("P", 6, "PEYOTL").
dico("P", 6, "PEZIZE").
dico("P", 6, "PHAGES").
dico("P", 6, "PHALLO").
dico("P", 6, "PHANIE").
dico("P", 6, "PHARES").
dico("P", 6, "PHASES").
dico("P", 6, "PHASME").
dico("P", 6, "PHENIX").
dico("P", 6, "PHENOL").
dico("P", 6, "PHILOS").
dico("P", 6, "PHOBIE").
dico("P", 6, "PHONES").
dico("P", 6, "PHONIE").
dico("P", 6, "PHONON").
dico("P", 6, "PHONOS").
dico("P", 6, "PHOQUE").
dico("P", 6, "PHOTON").
dico("P", 6, "PHOTOS").
dico("P", 6, "PHRASA").
dico("P", 6, "PHRASE").
dico("P", 6, "PHYLUM").
dico("P", 6, "PHYSES").
dico("P", 6, "PIAFFA").
dico("P", 6, "PIAFFE").
dico("P", 6, "PIANOS").
dico("P", 6, "PIAULA").
dico("P", 6, "PIAULE").
dico("P", 6, "PIAUTE").
dico("P", 6, "PIAZZA").
dico("P", 6, "PIBALE").
dico("P", 6, "PICAGE").
dico("P", 6, "PICARD").
dico("P", 6, "PICARO").
dico("P", 6, "PICHET").
dico("P", 6, "PICHOU").
dico("P", 6, "PICOLA").
dico("P", 6, "PICOLE").
dico("P", 6, "PICOLO").
dico("P", 6, "PICONS").
dico("P", 6, "PICORA").
dico("P", 6, "PICORE").
dico("P", 6, "PICOTA").
dico("P", 6, "PICOTE").
dico("P", 6, "PICOTS").
dico("P", 6, "PICRIS").
dico("P", 6, "PIDGIN").
dico("P", 6, "PIECES").
dico("P", 6, "PIEGEA").
dico("P", 6, "PIEGEE").
dico("P", 6, "PIEGER").
dico("P", 6, "PIEGES").
dico("P", 6, "PIEGEZ").
dico("P", 6, "PIERCA").
dico("P", 6, "PIERCE").
dico("P", 6, "PIERRE").
dico("P", 6, "PIETAI").
dico("P", 6, "PIETAS").
dico("P", 6, "PIETAT").
dico("P", 6, "PIETEE").
dico("P", 6, "PIETER").
dico("P", 6, "PIETES").
dico("P", 6, "PIETEZ").
dico("P", 6, "PIETIN").
dico("P", 6, "PIETON").
dico("P", 6, "PIETRE").
dico("P", 6, "PIEUSE").
dico("P", 6, "PIEUTA").
dico("P", 6, "PIEUTE").
dico("P", 6, "PIEZES").
dico("P", 6, "PIFAIS").
dico("P", 6, "PIFAIT").
dico("P", 6, "PIFANT").
dico("P", 6, "PIFEES").
dico("P", 6, "PIFENT").
dico("P", 6, "PIFERA").
dico("P", 6, "PIFFAI").
dico("P", 6, "PIFFAS").
dico("P", 6, "PIFFAT").
dico("P", 6, "PIFFEE").
dico("P", 6, "PIFFER").
dico("P", 6, "PIFFES").
dico("P", 6, "PIFFEZ").
dico("P", 6, "PIFIEZ").
dico("P", 6, "PIFONS").
dico("P", 6, "PIGEAI").
dico("P", 6, "PIGEAS").
dico("P", 6, "PIGEAT").
dico("P", 6, "PIGEES").
dico("P", 6, "PIGENT").
dico("P", 6, "PIGEON").
dico("P", 6, "PIGERA").
dico("P", 6, "PIGIEZ").
dico("P", 6, "PIGNES").
dico("P", 6, "PIGNON").
dico("P", 6, "PILAFS").
dico("P", 6, "PILAGE").
dico("P", 6, "PILAIS").
dico("P", 6, "PILAIT").
dico("P", 6, "PILANT").
dico("P", 6, "PILAUS").
dico("P", 6, "PILAWS").
dico("P", 6, "PILEES").
dico("P", 6, "PILENT").
dico("P", 6, "PILERA").
dico("P", 6, "PILETS").
dico("P", 6, "PILEUR").
dico("P", 6, "PILEUX").
dico("P", 6, "PILIER").
dico("P", 6, "PILIEZ").
dico("P", 6, "PILLAI").
dico("P", 6, "PILLAS").
dico("P", 6, "PILLAT").
dico("P", 6, "PILLEE").
dico("P", 6, "PILLER").
dico("P", 6, "PILLES").
dico("P", 6, "PILLEZ").
dico("P", 6, "PILONS").
dico("P", 6, "PILORI").
dico("P", 6, "PILOTA").
dico("P", 6, "PILOTE").
dico("P", 6, "PILOTS").
dico("P", 6, "PILOUS").
dico("P", 6, "PILULE").
dico("P", 6, "PILUMS").
dico("P", 6, "PIMENT").
dico("P", 6, "PINARD").
dico("P", 6, "PINCAI").
dico("P", 6, "PINCAS").
dico("P", 6, "PINCAT").
dico("P", 6, "PINCEE").
dico("P", 6, "PINCER").
dico("P", 6, "PINCES").
dico("P", 6, "PINCEZ").
dico("P", 6, "PINCON").
dico("P", 6, "PINEAL").
dico("P", 6, "PINEAU").
dico("P", 6, "PINEDE").
dico("P", 6, "PINENE").
dico("P", 6, "PINGRE").
dico("P", 6, "PINNES").
dico("P", 6, "PINOTS").
dico("P", 6, "PINSON").
dico("P", 6, "PINTAI").
dico("P", 6, "PINTAS").
dico("P", 6, "PINTAT").
dico("P", 6, "PINTEE").
dico("P", 6, "PINTER").
dico("P", 6, "PINTES").
dico("P", 6, "PINTEZ").
dico("P", 6, "PINYIN").
dico("P", 6, "PIOCHA").
dico("P", 6, "PIOCHE").
dico("P", 6, "PIOLET").
dico("P", 6, "PIONCA").
dico("P", 6, "PIONCE").
dico("P", 6, "PIONNA").
dico("P", 6, "PIONNE").
dico("P", 6, "PIORNA").
dico("P", 6, "PIORNE").
dico("P", 6, "PIPAIS").
dico("P", 6, "PIPAIT").
dico("P", 6, "PIPANT").
dico("P", 6, "PIPEAU").
dico("P", 6, "PIPEES").
dico("P", 6, "PIPENT").
dico("P", 6, "PIPERA").
dico("P", 6, "PIPEUR").
dico("P", 6, "PIPIER").
dico("P", 6, "PIPIEZ").
dico("P", 6, "PIPITS").
dico("P", 6, "PIPONS").
dico("P", 6, "PIQUAI").
dico("P", 6, "PIQUAS").
dico("P", 6, "PIQUAT").
dico("P", 6, "PIQUEE").
dico("P", 6, "PIQUER").
dico("P", 6, "PIQUES").
dico("P", 6, "PIQUET").
dico("P", 6, "PIQUEZ").
dico("P", 6, "PIQURE").
dico("P", 6, "PIRATA").
dico("P", 6, "PIRATE").
dico("P", 6, "PIRAYA").
dico("P", 6, "PIROLE").
dico("P", 6, "PISANE").
dico("P", 6, "PISANS").
dico("P", 6, "PISSAI").
dico("P", 6, "PISSAS").
dico("P", 6, "PISSAT").
dico("P", 6, "PISSEE").
dico("P", 6, "PISSER").
dico("P", 6, "PISSES").
dico("P", 6, "PISSEZ").
dico("P", 6, "PISTAI").
dico("P", 6, "PISTAS").
dico("P", 6, "PISTAT").
dico("P", 6, "PISTEE").
dico("P", 6, "PISTER").
dico("P", 6, "PISTES").
dico("P", 6, "PISTEZ").
dico("P", 6, "PISTIL").
dico("P", 6, "PISTON").
dico("P", 6, "PISTOU").
dico("P", 6, "PITCHS").
dico("P", 6, "PITEUX").
dico("P", 6, "PITIES").
dico("P", 6, "PITONS").
dico("P", 6, "PITOUS").
dico("P", 6, "PITPIT").
dico("P", 6, "PITRES").
dico("P", 6, "PITTAS").
dico("P", 6, "PIVERT").
dico("P", 6, "PIVOTA").
dico("P", 6, "PIVOTE").
dico("P", 6, "PIVOTS").
dico("P", 6, "PIXELS").
dico("P", 6, "PIZZAS").
dico("P", 6, "PLACAI").
dico("P", 6, "PLACAS").
dico("P", 6, "PLACAT").
dico("P", 6, "PLACEE").
dico("P", 6, "PLACER").
dico("P", 6, "PLACES").
dico("P", 6, "PLACET").
dico("P", 6, "PLACEZ").
dico("P", 6, "PLAGAL").
dico("P", 6, "PLAGES").
dico("P", 6, "PLAGIA").
dico("P", 6, "PLAGIE").
dico("P", 6, "PLAIDA").
dico("P", 6, "PLAIDE").
dico("P", 6, "PLAIDS").
dico("P", 6, "PLAIES").
dico("P", 6, "PLAINE").
dico("P", 6, "PLAINS").
dico("P", 6, "PLAINT").
dico("P", 6, "PLAIRA").
dico("P", 6, "PLAIRE").
dico("P", 6, "PLAISE").
dico("P", 6, "PLANAI").
dico("P", 6, "PLANAS").
dico("P", 6, "PLANAT").
dico("P", 6, "PLANEE").
dico("P", 6, "PLANER").
dico("P", 6, "PLANES").
dico("P", 6, "PLANEZ").
dico("P", 6, "PLANTA").
dico("P", 6, "PLANTE").
dico("P", 6, "PLANTS").
dico("P", 6, "PLAQUA").
dico("P", 6, "PLAQUE").
dico("P", 6, "PLASMA").
dico("P", 6, "PLASTE").
dico("P", 6, "PLATEE").
dico("P", 6, "PLATES").
dico("P", 6, "PLATRA").
dico("P", 6, "PLATRE").
dico("P", 6, "PLAYON").
dico("P", 6, "PLEBAN").
dico("P", 6, "PLEBES").
dico("P", 6, "PLEINE").
dico("P", 6, "PLEINS").
dico("P", 6, "PLENUM").
dico("P", 6, "PLEURA").
dico("P", 6, "PLEURE").
dico("P", 6, "PLEURS").
dico("P", 6, "PLEUVE").
dico("P", 6, "PLEVRE").
dico("P", 6, "PLEXUS").
dico("P", 6, "PLEYON").
dico("P", 6, "PLIAGE").
dico("P", 6, "PLIAIS").
dico("P", 6, "PLIAIT").
dico("P", 6, "PLIANT").
dico("P", 6, "PLIEES").
dico("P", 6, "PLIENT").
dico("P", 6, "PLIERA").
dico("P", 6, "PLIEUR").
dico("P", 6, "PLIIEZ").
dico("P", 6, "PLINTS").
dico("P", 6, "PLIOIR").
dico("P", 6, "PLIONS").
dico("P", 6, "PLIQUE").
dico("P", 6, "PLISSA").
dico("P", 6, "PLISSE").
dico("P", 6, "PLIURE").
dico("P", 6, "PLOIES").
dico("P", 6, "PLOMBA").
dico("P", 6, "PLOMBE").
dico("P", 6, "PLOMBS").
dico("P", 6, "PLONGE").
dico("P", 6, "PLOUCS").
dico("P", 6, "PLOUKS").
dico("P", 6, "PLOYAI").
dico("P", 6, "PLOYAS").
dico("P", 6, "PLOYAT").
dico("P", 6, "PLOYEE").
dico("P", 6, "PLOYER").
dico("P", 6, "PLOYES").
dico("P", 6, "PLOYEZ").
dico("P", 6, "PLUCHA").
dico("P", 6, "PLUCHE").
dico("P", 6, "PLUIES").
dico("P", 6, "PLUMAI").
dico("P", 6, "PLUMAS").
dico("P", 6, "PLUMAT").
dico("P", 6, "PLUMEE").
dico("P", 6, "PLUMER").
dico("P", 6, "PLUMES").
dico("P", 6, "PLUMET").
dico("P", 6, "PLUMEZ").
dico("P", 6, "PLURAL").
dico("P", 6, "PLUSSE").
dico("P", 6, "PLUTES").
dico("P", 6, "PLUTON").
dico("P", 6, "PLUTOT").
dico("P", 6, "PNEUMO").
dico("P", 6, "POCHAI").
dico("P", 6, "POCHAS").
dico("P", 6, "POCHAT").
dico("P", 6, "POCHEE").
dico("P", 6, "POCHER").
dico("P", 6, "POCHES").
dico("P", 6, "POCHEZ").
dico("P", 6, "POCHON").
dico("P", 6, "PODALE").
dico("P", 6, "PODAUX").
dico("P", 6, "PODION").
dico("P", 6, "PODIUM").
dico("P", 6, "PODZOL").
dico("P", 6, "POELAI").
dico("P", 6, "POELAS").
dico("P", 6, "POELAT").
dico("P", 6, "POELEE").
dico("P", 6, "POELER").
dico("P", 6, "POELES").
dico("P", 6, "POELEZ").
dico("P", 6, "POELON").
dico("P", 6, "POEMES").
dico("P", 6, "POESIE").
dico("P", 6, "POETES").
dico("P", 6, "POGNES").
dico("P", 6, "POGNON").
dico("P", 6, "POGROM").
dico("P", 6, "POIGNA").
dico("P", 6, "POIGNE").
dico("P", 6, "POILAI").
dico("P", 6, "POILAS").
dico("P", 6, "POILAT").
dico("P", 6, "POILEE").
dico("P", 6, "POILER").
dico("P", 6, "POILES").
dico("P", 6, "POILEZ").
dico("P", 6, "POILUE").
dico("P", 6, "POILUS").
dico("P", 6, "POINGS").
dico("P", 6, "POINTA").
dico("P", 6, "POINTE").
dico("P", 6, "POINTS").
dico("P", 6, "POINTU").
dico("P", 6, "POIREE").
dico("P", 6, "POIRES").
dico("P", 6, "POISES").
dico("P", 6, "POISON").
dico("P", 6, "POISSA").
dico("P", 6, "POISSE").
dico("P", 6, "POIVRA").
dico("P", 6, "POIVRE").
dico("P", 6, "POKERS").
dico("P", 6, "POLARD").
dico("P", 6, "POLARS").
dico("P", 6, "POLDER").
dico("P", 6, "POLICA").
dico("P", 6, "POLICE").
dico("P", 6, "POLIES").
dico("P", 6, "POLIOS").
dico("P", 6, "POLIRA").
dico("P", 6, "POLJES").
dico("P", 6, "POLKAS").
dico("P", 6, "POLLEN").
dico("P", 6, "POLLUA").
dico("P", 6, "POLLUE").
dico("P", 6, "POLYOL").
dico("P", 6, "POLYPE").
dico("P", 6, "POMELO").
dico("P", 6, "POMMAI").
dico("P", 6, "POMMAS").
dico("P", 6, "POMMAT").
dico("P", 6, "POMMEE").
dico("P", 6, "POMMER").
dico("P", 6, "POMMES").
dico("P", 6, "POMMEZ").
dico("P", 6, "POMPAI").
dico("P", 6, "POMPAS").
dico("P", 6, "POMPAT").
dico("P", 6, "POMPEE").
dico("P", 6, "POMPER").
dico("P", 6, "POMPES").
dico("P", 6, "POMPEZ").
dico("P", 6, "POMPON").
dico("P", 6, "PONANT").
dico("P", 6, "PONCAI").
dico("P", 6, "PONCAS").
dico("P", 6, "PONCAT").
dico("P", 6, "PONCEE").
dico("P", 6, "PONCER").
dico("P", 6, "PONCES").
dico("P", 6, "PONCEZ").
dico("P", 6, "PONCHO").
dico("P", 6, "PONCIF").
dico("P", 6, "PONDES").
dico("P", 6, "PONDEZ").
dico("P", 6, "PONDIS").
dico("P", 6, "PONDIT").
dico("P", 6, "PONDRA").
dico("P", 6, "PONDRE").
dico("P", 6, "PONDUE").
dico("P", 6, "PONDUS").
dico("P", 6, "PONEYS").
dico("P", 6, "PONGEE").
dico("P", 6, "PONGES").
dico("P", 6, "PONOTE").
dico("P", 6, "PONOTS").
dico("P", 6, "PONTAI").
dico("P", 6, "PONTAS").
dico("P", 6, "PONTAT").
dico("P", 6, "PONTEE").
dico("P", 6, "PONTER").
dico("P", 6, "PONTES").
dico("P", 6, "PONTET").
dico("P", 6, "PONTEZ").
dico("P", 6, "PONTIL").
dico("P", 6, "PONTON").
dico("P", 6, "POPAHS").
dico("P", 6, "POPOTE").
dico("P", 6, "POPULO").
dico("P", 6, "POQUAI").
dico("P", 6, "POQUAS").
dico("P", 6, "POQUAT").
dico("P", 6, "POQUEE").
dico("P", 6, "POQUER").
dico("P", 6, "POQUES").
dico("P", 6, "POQUET").
dico("P", 6, "POQUEZ").
dico("P", 6, "PORACE").
dico("P", 6, "PORCHE").
dico("P", 6, "PORCIN").
dico("P", 6, "POREUX").
dico("P", 6, "PORION").
dico("P", 6, "PORNOS").
dico("P", 6, "PORQUE").
dico("P", 6, "PORTAI").
dico("P", 6, "PORTAL").
dico("P", 6, "PORTAS").
dico("P", 6, "PORTAT").
dico("P", 6, "PORTEE").
dico("P", 6, "PORTER").
dico("P", 6, "PORTES").
dico("P", 6, "PORTEZ").
dico("P", 6, "PORTOR").
dico("P", 6, "PORTOS").
dico("P", 6, "POSADA").
dico("P", 6, "POSAIS").
dico("P", 6, "POSAIT").
dico("P", 6, "POSANT").
dico("P", 6, "POSEES").
dico("P", 6, "POSENT").
dico("P", 6, "POSERA").
dico("P", 6, "POSEUR").
dico("P", 6, "POSIEZ").
dico("P", 6, "POSONS").
dico("P", 6, "POSTAI").
dico("P", 6, "POSTAL").
dico("P", 6, "POSTAS").
dico("P", 6, "POSTAT").
dico("P", 6, "POSTEE").
dico("P", 6, "POSTER").
dico("P", 6, "POSTES").
dico("P", 6, "POSTEZ").
dico("P", 6, "POTAGE").
dico("P", 6, "POTALE").
dico("P", 6, "POTARD").
dico("P", 6, "POTEAU").
dico("P", 6, "POTEES").
dico("P", 6, "POTELE").
dico("P", 6, "POTIER").
dico("P", 6, "POTINA").
dico("P", 6, "POTINE").
dico("P", 6, "POTINS").
dico("P", 6, "POTION").
dico("P", 6, "POTTOK").
dico("P", 6, "POTTOS").
dico("P", 6, "POTUES").
dico("P", 6, "POUCAI").
dico("P", 6, "POUCAS").
dico("P", 6, "POUCAT").
dico("P", 6, "POUCER").
dico("P", 6, "POUCES").
dico("P", 6, "POUCEZ").
dico("P", 6, "POUDRA").
dico("P", 6, "POUDRE").
dico("P", 6, "POUFFA").
dico("P", 6, "POUFFE").
dico("P", 6, "POUGNA").
dico("P", 6, "POUGNE").
dico("P", 6, "POULES").
dico("P", 6, "POULET").
dico("P", 6, "POULIE").
dico("P", 6, "POULOT").
dico("P", 6, "POULPE").
dico("P", 6, "POUMON").
dico("P", 6, "POUNDS").
dico("P", 6, "POUPEE").
dico("P", 6, "POUPES").
dico("P", 6, "POUPIN").
dico("P", 6, "POUPON").
dico("P", 6, "POURIM").
dico("P", 6, "POURRA").
dico("P", 6, "POURRI").
dico("P", 6, "POURVU").
dico("P", 6, "POUSSA").
dico("P", 6, "POUSSE").
dico("P", 6, "POUTOU").
dico("P", 6, "POUTRE").
dico("P", 6, "POUTSA").
dico("P", 6, "POUTSE").
dico("P", 6, "POUVEZ").
dico("P", 6, "PRAIEN").
dico("P", 6, "PRAIRE").
dico("P", 6, "PRALIN").
dico("P", 6, "PRAMES").
dico("P", 6, "PRAXIE").
dico("P", 6, "PRAXIS").
dico("P", 6, "PREAUX").
dico("P", 6, "PRECHA").
dico("P", 6, "PRECHE").
dico("P", 6, "PRECIS").
dico("P", 6, "PREDIS").
dico("P", 6, "PREDIT").
dico("P", 6, "PREFET").
dico("P", 6, "PREFIX").
dico("P", 6, "PRELAT").
dico("P", 6, "PRELES").
dico("P", 6, "PRENDS").
dico("P", 6, "PRENEZ").
dico("P", 6, "PRENNE").
dico("P", 6, "PRENOM").
dico("P", 6, "PREPAS").
dico("P", 6, "PRESSA").
dico("P", 6, "PRESSE").
dico("P", 6, "PRESTA").
dico("P", 6, "PRESTE").
dico("P", 6, "PRESTO").
dico("P", 6, "PRETAI").
dico("P", 6, "PRETAS").
dico("P", 6, "PRETAT").
dico("P", 6, "PRETEE").
dico("P", 6, "PRETER").
dico("P", 6, "PRETES").
dico("P", 6, "PRETEZ").
dico("P", 6, "PRETRE").
dico("P", 6, "PREUVE").
dico("P", 6, "PREVIS").
dico("P", 6, "PREVIT").
dico("P", 6, "PREVOT").
dico("P", 6, "PREVUE").
dico("P", 6, "PREVUS").
dico("P", 6, "PRIAIS").
dico("P", 6, "PRIAIT").
dico("P", 6, "PRIANT").
dico("P", 6, "PRIEES").
dico("P", 6, "PRIENT").
dico("P", 6, "PRIERA").
dico("P", 6, "PRIERE").
dico("P", 6, "PRIEUR").
dico("P", 6, "PRIIEZ").
dico("P", 6, "PRIMAI").
dico("P", 6, "PRIMAL").
dico("P", 6, "PRIMAS").
dico("P", 6, "PRIMAT").
dico("P", 6, "PRIMEE").
dico("P", 6, "PRIMER").
dico("P", 6, "PRIMES").
dico("P", 6, "PRIMEZ").
dico("P", 6, "PRINCE").
dico("P", 6, "PRIONS").
dico("P", 6, "PRIORI").
dico("P", 6, "PRISAI").
dico("P", 6, "PRISAS").
dico("P", 6, "PRISAT").
dico("P", 6, "PRISEE").
dico("P", 6, "PRISER").
dico("P", 6, "PRISES").
dico("P", 6, "PRISEZ").
dico("P", 6, "PRISME").
dico("P", 6, "PRISON").
dico("P", 6, "PRISSE").
dico("P", 6, "PRITES").
dico("P", 6, "PRIVAI").
dico("P", 6, "PRIVAS").
dico("P", 6, "PRIVAT").
dico("P", 6, "PRIVEE").
dico("P", 6, "PRIVER").
dico("P", 6, "PRIVES").
dico("P", 6, "PRIVEZ").
dico("P", 6, "PROBAS").
dico("P", 6, "PROBES").
dico("P", 6, "PROCES").
dico("P", 6, "PROCHE").
dico("P", 6, "PROFES").
dico("P", 6, "PROFIL").
dico("P", 6, "PROFIT").
dico("P", 6, "PROFUS").
dico("P", 6, "PROIES").
dico("P", 6, "PROJET").
dico("P", 6, "PROLAN").
dico("P", 6, "PROLOG").
dico("P", 6, "PROLOS").
dico("P", 6, "PROMET").
dico("P", 6, "PROMIS").
dico("P", 6, "PROMIT").
dico("P", 6, "PROMOS").
dico("P", 6, "PROMPT").
dico("P", 6, "PROMUE").
dico("P", 6, "PROMUS").
dico("P", 6, "PROMUT").
dico("P", 6, "PRONAI").
dico("P", 6, "PRONAS").
dico("P", 6, "PRONAT").
dico("P", 6, "PRONEE").
dico("P", 6, "PRONER").
dico("P", 6, "PRONES").
dico("P", 6, "PRONEZ").
dico("P", 6, "PRONOM").
dico("P", 6, "PROPOS").
dico("P", 6, "PROPRE").
dico("P", 6, "PROSES").
dico("P", 6, "PROSIT").
dico("P", 6, "PROTAL").
dico("P", 6, "PROTEE").
dico("P", 6, "PROTES").
dico("P", 6, "PROTET").
dico("P", 6, "PROTON").
dico("P", 6, "PROTOS").
dico("P", 6, "PROUES").
dico("P", 6, "PROUTS").
dico("P", 6, "PROUVA").
dico("P", 6, "PROUVE").
dico("P", 6, "PROVIN").
dico("P", 6, "PROVOC").
dico("P", 6, "PROVOS").
dico("P", 6, "PROYER").
dico("P", 6, "PRUCHE").
dico("P", 6, "PRUDES").
dico("P", 6, "PRUINE").
dico("P", 6, "PRUNES").
dico("P", 6, "PRUNUS").
dico("P", 6, "PRURIT").
dico("P", 6, "PRUSSE").
dico("P", 6, "PSAUME").
dico("P", 6, "PSEUDO").
dico("P", 6, "PSOQUE").
dico("P", 6, "PSORES").
dico("P", 6, "PSYCHE").
dico("P", 6, "PSYCHO").
dico("P", 6, "PSYLLE").
dico("P", 6, "PTOSES").
dico("P", 6, "PTOSIS").
dico("P", 6, "PUAMES").
dico("P", 6, "PUANTE").
dico("P", 6, "PUANTS").
dico("P", 6, "PUASSE").
dico("P", 6, "PUATES").
dico("P", 6, "PUBERE").
dico("P", 6, "PUBIEN").
dico("P", 6, "PUBLIA").
dico("P", 6, "PUBLIC").
dico("P", 6, "PUBLIE").
dico("P", 6, "PUCEAU").
dico("P", 6, "PUCHES").
dico("P", 6, "PUCIER").
dico("P", 6, "PUDDLA").
dico("P", 6, "PUDDLE").
dico("P", 6, "PUDEUR").
dico("P", 6, "PUEBLO").
dico("P", 6, "PUERAI").
dico("P", 6, "PUERAS").
dico("P", 6, "PUEREZ").
dico("P", 6, "PUERIL").
dico("P", 6, "PUFFIN").
dico("P", 6, "PUINEE").
dico("P", 6, "PUINES").
dico("P", 6, "PUIONS").
dico("P", 6, "PUISAI").
dico("P", 6, "PUISAS").
dico("P", 6, "PUISAT").
dico("P", 6, "PUISEE").
dico("P", 6, "PUISER").
dico("P", 6, "PUISES").
dico("P", 6, "PUISEZ").
dico("P", 6, "PUISSE").
dico("P", 6, "PULPES").
dico("P", 6, "PULQUE").
dico("P", 6, "PULSAI").
dico("P", 6, "PULSAR").
dico("P", 6, "PULSAS").
dico("P", 6, "PULSAT").
dico("P", 6, "PULSEE").
dico("P", 6, "PULSER").
dico("P", 6, "PULSES").
dico("P", 6, "PULSEZ").
dico("P", 6, "PUNCHS").
dico("P", 6, "PUNIES").
dico("P", 6, "PUNIRA").
dico("P", 6, "PUREAU").
dico("P", 6, "PUREES").
dico("P", 6, "PURENT").
dico("P", 6, "PURETE").
dico("P", 6, "PURGEA").
dico("P", 6, "PURGEE").
dico("P", 6, "PURGER").
dico("P", 6, "PURGES").
dico("P", 6, "PURGEZ").
dico("P", 6, "PURINA").
dico("P", 6, "PURINE").
dico("P", 6, "PURINS").
dico("P", 6, "PUROTS").
dico("P", 6, "PUSSES").
dico("P", 6, "PUTAIN").
dico("P", 6, "PUTIER").
dico("P", 6, "PUTIET").
dico("P", 6, "PUTOIS").
dico("P", 6, "PUTSCH").
dico("P", 6, "PUTTAI").
dico("P", 6, "PUTTAS").
dico("P", 6, "PUTTAT").
dico("P", 6, "PUTTEE").
dico("P", 6, "PUTTER").
dico("P", 6, "PUTTES").
dico("P", 6, "PUTTEZ").
dico("P", 6, "PUTTOS").
dico("P", 6, "PUZZLE").
dico("P", 6, "PYGMEE").
dico("P", 6, "PYJAMA").
dico("P", 6, "PYLONE").
dico("P", 6, "PYLORE").
dico("P", 6, "PYRALE").
dico("P", 6, "PYRENE").
dico("P", 6, "PYRITE").
dico("P", 6, "PYROLE").
dico("P", 6, "PYRROL").
dico("P", 6, "PYTHIE").
dico("P", 6, "PYTHON").
dico("P", 6, "PYURIE").
dico("P", 6, "PYXIDE").
