dico("P", 8, "PACAGEAI").
dico("P", 8, "PACAGEAS").
dico("P", 8, "PACAGEAT").
dico("P", 8, "PACAGEES").
dico("P", 8, "PACAGENT").
dico("P", 8, "PACAGERA").
dico("P", 8, "PACAGIEZ").
dico("P", 8, "PACANIER").
dico("P", 8, "PACENIEN").
dico("P", 8, "PACFUNGS").
dico("P", 8, "PACHALIK").
dico("P", 8, "PACHTOUN").
dico("P", 8, "PACHTOUS").
dico("P", 8, "PACHYURE").
dico("P", 8, "PACIFIAI").
dico("P", 8, "PACIFIAS").
dico("P", 8, "PACIFIAT").
dico("P", 8, "PACIFIEE").
dico("P", 8, "PACIFIER").
dico("P", 8, "PACIFIES").
dico("P", 8, "PACIFIEZ").
dico("P", 8, "PACKAGER").
dico("P", 8, "PACKAGES").
dico("P", 8, "PACKFUNG").
dico("P", 8, "PACQUAGE").
dico("P", 8, "PACQUAIS").
dico("P", 8, "PACQUAIT").
dico("P", 8, "PACQUANT").
dico("P", 8, "PACQUEES").
dico("P", 8, "PACQUENT").
dico("P", 8, "PACQUERA").
dico("P", 8, "PACQUIEZ").
dico("P", 8, "PACQUONS").
dico("P", 8, "PACSAMES").
dico("P", 8, "PACSASSE").
dico("P", 8, "PACSATES").
dico("P", 8, "PACSERAI").
dico("P", 8, "PACSERAS").
dico("P", 8, "PACSEREZ").
dico("P", 8, "PACSIONS").
dico("P", 8, "PACTISAI").
dico("P", 8, "PACTISAS").
dico("P", 8, "PACTISAT").
dico("P", 8, "PACTISER").
dico("P", 8, "PACTISES").
dico("P", 8, "PACTISEZ").
dico("P", 8, "PACTOLES").
dico("P", 8, "PADDOCKS").
dico("P", 8, "PADICHAH").
dico("P", 8, "PADICHAS").
dico("P", 8, "PADOUANE").
dico("P", 8, "PADOUANS").
dico("P", 8, "PAGAIENT").
dico("P", 8, "PAGAIERA").
dico("P", 8, "PAGAILLE").
dico("P", 8, "PAGANISA").
dico("P", 8, "PAGANISE").
dico("P", 8, "PAGAYAIS").
dico("P", 8, "PAGAYAIT").
dico("P", 8, "PAGAYANT").
dico("P", 8, "PAGAYENT").
dico("P", 8, "PAGAYERA").
dico("P", 8, "PAGAYEUR").
dico("P", 8, "PAGAYIEZ").
dico("P", 8, "PAGAYONS").
dico("P", 8, "PAGEAMES").
dico("P", 8, "PAGEASSE").
dico("P", 8, "PAGEATES").
dico("P", 8, "PAGELLES").
dico("P", 8, "PAGEOTAI").
dico("P", 8, "PAGEOTAS").
dico("P", 8, "PAGEOTAT").
dico("P", 8, "PAGEOTEE").
dico("P", 8, "PAGEOTER").
dico("P", 8, "PAGEOTES").
dico("P", 8, "PAGEOTEZ").
dico("P", 8, "PAGERAIS").
dico("P", 8, "PAGERAIT").
dico("P", 8, "PAGERENT").
dico("P", 8, "PAGERIEZ").
dico("P", 8, "PAGERONS").
dico("P", 8, "PAGERONT").
dico("P", 8, "PAGINAIS").
dico("P", 8, "PAGINAIT").
dico("P", 8, "PAGINANT").
dico("P", 8, "PAGINEES").
dico("P", 8, "PAGINENT").
dico("P", 8, "PAGINERA").
dico("P", 8, "PAGINIEZ").
dico("P", 8, "PAGINONS").
dico("P", 8, "PAGNOTAI").
dico("P", 8, "PAGNOTAS").
dico("P", 8, "PAGNOTAT").
dico("P", 8, "PAGNOTEE").
dico("P", 8, "PAGNOTER").
dico("P", 8, "PAGNOTES").
dico("P", 8, "PAGNOTEZ").
dico("P", 8, "PAGODONS").
dico("P", 8, "PAHLAVIS").
dico("P", 8, "PAIEMENT").
dico("P", 8, "PAIENNES").
dico("P", 8, "PAIERAIS").
dico("P", 8, "PAIERAIT").
dico("P", 8, "PAIERIES").
dico("P", 8, "PAIERIEZ").
dico("P", 8, "PAIERONS").
dico("P", 8, "PAIERONT").
dico("P", 8, "PAILLAGE").
dico("P", 8, "PAILLAIS").
dico("P", 8, "PAILLAIT").
dico("P", 8, "PAILLANT").
dico("P", 8, "PAILLARD").
dico("P", 8, "PAILLEES").
dico("P", 8, "PAILLENT").
dico("P", 8, "PAILLERA").
dico("P", 8, "PAILLERS").
dico("P", 8, "PAILLETA").
dico("P", 8, "PAILLETE").
dico("P", 8, "PAILLETS").
dico("P", 8, "PAILLEUR").
dico("P", 8, "PAILLEUX").
dico("P", 8, "PAILLIEZ").
dico("P", 8, "PAILLONS").
dico("P", 8, "PAILLOTE").
dico("P", 8, "PAILLOTS").
dico("P", 8, "PAIRAGES").
dico("P", 8, "PAIRESSE").
dico("P", 8, "PAISIBLE").
dico("P", 8, "PAISSAIS").
dico("P", 8, "PAISSAIT").
dico("P", 8, "PAISSANT").
dico("P", 8, "PAISSEAU").
dico("P", 8, "PAISSENT").
dico("P", 8, "PAISSIEZ").
dico("P", 8, "PAISSONS").
dico("P", 8, "PAITRAIS").
dico("P", 8, "PAITRAIT").
dico("P", 8, "PAITRIEZ").
dico("P", 8, "PAITRONS").
dico("P", 8, "PAITRONT").
dico("P", 8, "PALABRAI").
dico("P", 8, "PALABRAS").
dico("P", 8, "PALABRAT").
dico("P", 8, "PALABRER").
dico("P", 8, "PALABRES").
dico("P", 8, "PALABREZ").
dico("P", 8, "PALADINS").
dico("P", 8, "PALANCHE").
dico("P", 8, "PALANCON").
dico("P", 8, "PALANGRE").
dico("P", 8, "PALANQUA").
dico("P", 8, "PALANQUE").
dico("P", 8, "PALASTRE").
dico("P", 8, "PALATALE").
dico("P", 8, "PALATAUX").
dico("P", 8, "PALATIAL").
dico("P", 8, "PALATINE").
dico("P", 8, "PALATINS").
dico("P", 8, "PALATRES").
dico("P", 8, "PALAUANE").
dico("P", 8, "PALAUANS").
dico("P", 8, "PALEFROI").
dico("P", 8, "PALEMONS").
dico("P", 8, "PALEOSOL").
dico("P", 8, "PALERONS").
dico("P", 8, "PALESTRE").
dico("P", 8, "PALETOTS").
dico("P", 8, "PALETTES").
dico("P", 8, "PALICARE").
dico("P", 8, "PALICHON").
dico("P", 8, "PALIERES").
dico("P", 8, "PALIFIAI").
dico("P", 8, "PALIFIAS").
dico("P", 8, "PALIFIAT").
dico("P", 8, "PALIFIEE").
dico("P", 8, "PALIFIER").
dico("P", 8, "PALIFIES").
dico("P", 8, "PALIFIEZ").
dico("P", 8, "PALIKARE").
dico("P", 8, "PALIRAIS").
dico("P", 8, "PALIRAIT").
dico("P", 8, "PALIRENT").
dico("P", 8, "PALIRIEZ").
dico("P", 8, "PALIRONS").
dico("P", 8, "PALIRONT").
dico("P", 8, "PALISSAI").
dico("P", 8, "PALISSAS").
dico("P", 8, "PALISSAT").
dico("P", 8, "PALISSEE").
dico("P", 8, "PALISSER").
dico("P", 8, "PALISSES").
dico("P", 8, "PALISSEZ").
dico("P", 8, "PALISSON").
dico("P", 8, "PALIURES").
dico("P", 8, "PALLEALE").
dico("P", 8, "PALLEAUX").
dico("P", 8, "PALLIAIS").
dico("P", 8, "PALLIAIT").
dico("P", 8, "PALLIANT").
dico("P", 8, "PALLIDUM").
dico("P", 8, "PALLIEES").
dico("P", 8, "PALLIENT").
dico("P", 8, "PALLIERA").
dico("P", 8, "PALLIIEZ").
dico("P", 8, "PALLIONS").
dico("P", 8, "PALLIUMS").
dico("P", 8, "PALMACEE").
dico("P", 8, "PALMAIRE").
dico("P", 8, "PALMAMES").
dico("P", 8, "PALMARES").
dico("P", 8, "PALMASSE").
dico("P", 8, "PALMATES").
dico("P", 8, "PALMERAI").
dico("P", 8, "PALMERAS").
dico("P", 8, "PALMEREZ").
dico("P", 8, "PALMETTE").
dico("P", 8, "PALMIERS").
dico("P", 8, "PALMIONS").
dico("P", 8, "PALMISTE").
dico("P", 8, "PALMITES").
dico("P", 8, "PALMURES").
dico("P", 8, "PALOISES").
dico("P", 8, "PALOMBES").
dico("P", 8, "PALOTAGE").
dico("P", 8, "PALOTAIS").
dico("P", 8, "PALOTAIT").
dico("P", 8, "PALOTANT").
dico("P", 8, "PALOTEES").
dico("P", 8, "PALOTENT").
dico("P", 8, "PALOTERA").
dico("P", 8, "PALOTEUR").
dico("P", 8, "PALOTIEZ").
dico("P", 8, "PALOTONS").
dico("P", 8, "PALOTTES").
dico("P", 8, "PALOURDE").
dico("P", 8, "PALPABLE").
dico("P", 8, "PALPAMES").
dico("P", 8, "PALPASSE").
dico("P", 8, "PALPATES").
dico("P", 8, "PALPERAI").
dico("P", 8, "PALPERAS").
dico("P", 8, "PALPEREZ").
dico("P", 8, "PALPEURS").
dico("P", 8, "PALPIONS").
dico("P", 8, "PALPITAI").
dico("P", 8, "PALPITAS").
dico("P", 8, "PALPITAT").
dico("P", 8, "PALPITER").
dico("P", 8, "PALPITES").
dico("P", 8, "PALPITEZ").
dico("P", 8, "PALUCHAI").
dico("P", 8, "PALUCHAS").
dico("P", 8, "PALUCHAT").
dico("P", 8, "PALUCHEE").
dico("P", 8, "PALUCHER").
dico("P", 8, "PALUCHES").
dico("P", 8, "PALUCHEZ").
dico("P", 8, "PALUDEEN").
dico("P", 8, "PALUDIER").
dico("P", 8, "PALUDINE").
dico("P", 8, "PALUSTRE").
dico("P", 8, "PAMAIENT").
dico("P", 8, "PAMASSES").
dico("P", 8, "PAMERAIS").
dico("P", 8, "PAMERAIT").
dico("P", 8, "PAMERENT").
dico("P", 8, "PAMERIEZ").
dico("P", 8, "PAMERONS").
dico("P", 8, "PAMERONT").
dico("P", 8, "PAMOISON").
dico("P", 8, "PAMPEROS").
dico("P", 8, "PAMPHLET").
dico("P", 8, "PAMPILLE").
dico("P", 8, "PANACEES").
dico("P", 8, "PANACHAI").
dico("P", 8, "PANACHAS").
dico("P", 8, "PANACHAT").
dico("P", 8, "PANACHEE").
dico("P", 8, "PANACHER").
dico("P", 8, "PANACHES").
dico("P", 8, "PANACHEZ").
dico("P", 8, "PANAIENT").
dico("P", 8, "PANAIRES").
dico("P", 8, "PANAMEEN").
dico("P", 8, "PANAMIEN").
dico("P", 8, "PANARABE").
dico("P", 8, "PANARDES").
dico("P", 8, "PANASSES").
dico("P", 8, "PANATELA").
dico("P", 8, "PANCAKES").
dico("P", 8, "PANCARTE").
dico("P", 8, "PANCETTA").
dico("P", 8, "PANCRACE").
dico("P", 8, "PANCREAS").
dico("P", 8, "PANDANUS").
dico("P", 8, "PANDEMES").
dico("P", 8, "PANDEMIE").
dico("P", 8, "PANDORES").
dico("P", 8, "PANDOURS").
dico("P", 8, "PANELISE").
dico("P", 8, "PANERAIS").
dico("P", 8, "PANERAIT").
dico("P", 8, "PANEREES").
dico("P", 8, "PANERENT").
dico("P", 8, "PANERIEZ").
dico("P", 8, "PANERONS").
dico("P", 8, "PANERONT").
dico("P", 8, "PANETIER").
dico("P", 8, "PANETONS").
dico("P", 8, "PANGOLIN").
dico("P", 8, "PANICAUT").
dico("P", 8, "PANICULE").
dico("P", 8, "PANICUMS").
dico("P", 8, "PANIERES").
dico("P", 8, "PANIFIAI").
dico("P", 8, "PANIFIAS").
dico("P", 8, "PANIFIAT").
dico("P", 8, "PANIFIEE").
dico("P", 8, "PANIFIER").
dico("P", 8, "PANIFIES").
dico("P", 8, "PANIFIEZ").
dico("P", 8, "PANIQUAI").
dico("P", 8, "PANIQUAS").
dico("P", 8, "PANIQUAT").
dico("P", 8, "PANIQUEE").
dico("P", 8, "PANIQUER").
dico("P", 8, "PANIQUES").
dico("P", 8, "PANIQUEZ").
dico("P", 8, "PANJABIS").
dico("P", 8, "PANMIXIE").
dico("P", 8, "PANNEAUX").
dico("P", 8, "PANNETON").
dico("P", 8, "PANOPLIE").
dico("P", 8, "PANORAMA").
dico("P", 8, "PANORPES").
dico("P", 8, "PANOSSAI").
dico("P", 8, "PANOSSAS").
dico("P", 8, "PANOSSAT").
dico("P", 8, "PANOSSEE").
dico("P", 8, "PANOSSER").
dico("P", 8, "PANOSSES").
dico("P", 8, "PANOSSEZ").
dico("P", 8, "PANOUFLE").
dico("P", 8, "PANSAGES").
dico("P", 8, "PANSAMES").
dico("P", 8, "PANSASSE").
dico("P", 8, "PANSATES").
dico("P", 8, "PANSERAI").
dico("P", 8, "PANSERAS").
dico("P", 8, "PANSEREZ").
dico("P", 8, "PANSEURS").
dico("P", 8, "PANSEUSE").
dico("P", 8, "PANSIONS").
dico("P", 8, "PANSLAVE").
dico("P", 8, "PANTACLE").
dico("P", 8, "PANTALON").
dico("P", 8, "PANTELAI").
dico("P", 8, "PANTELAS").
dico("P", 8, "PANTELAT").
dico("P", 8, "PANTELER").
dico("P", 8, "PANTELEZ").
dico("P", 8, "PANTELLE").
dico("P", 8, "PANTENES").
dico("P", 8, "PANTENNE").
dico("P", 8, "PANTHEES").
dico("P", 8, "PANTHEON").
dico("P", 8, "PANTHERE").
dico("P", 8, "PANTIERE").
dico("P", 8, "PANTOIRE").
dico("P", 8, "PANTOISE").
dico("P", 8, "PANTOUMS").
dico("P", 8, "PAONNEAU").
dico("P", 8, "PAPABLES").
dico("P", 8, "PAPAINES").
dico("P", 8, "PAPAUTES").
dico("P", 8, "PAPAVERS").
dico("P", 8, "PAPAYERS").
dico("P", 8, "PAPEGAIS").
dico("P", 8, "PAPELARD").
dico("P", 8, "PAPESSES").
dico("P", 8, "PAPETIER").
dico("P", 8, "PAPETTES").
dico("P", 8, "PAPILLES").
dico("P", 8, "PAPILLON").
dico("P", 8, "PAPISMES").
dico("P", 8, "PAPISTES").
dico("P", 8, "PAPIVORE").
dico("P", 8, "PAPOOSES").
dico("P", 8, "PAPOTAGE").
dico("P", 8, "PAPOTAIS").
dico("P", 8, "PAPOTAIT").
dico("P", 8, "PAPOTANT").
dico("P", 8, "PAPOTENT").
dico("P", 8, "PAPOTERA").
dico("P", 8, "PAPOTIEZ").
dico("P", 8, "PAPOTONS").
dico("P", 8, "PAPRIKAS").
dico("P", 8, "PAPULEUX").
dico("P", 8, "PAQUEBOT").
dico("P", 8, "PAQUETAI").
dico("P", 8, "PAQUETAS").
dico("P", 8, "PAQUETAT").
dico("P", 8, "PAQUETEE").
dico("P", 8, "PAQUETER").
dico("P", 8, "PAQUETES").
dico("P", 8, "PAQUETEZ").
dico("P", 8, "PAQUETTE").
dico("P", 8, "PARABASE").
dico("P", 8, "PARABOLE").
dico("P", 8, "PARACLET").
dico("P", 8, "PARADAIS").
dico("P", 8, "PARADAIT").
dico("P", 8, "PARADANT").
dico("P", 8, "PARADENT").
dico("P", 8, "PARADERA").
dico("P", 8, "PARADEUR").
dico("P", 8, "PARADIEZ").
dico("P", 8, "PARADONS").
dico("P", 8, "PARADORS").
dico("P", 8, "PARADOXE").
dico("P", 8, "PARAFAIS").
dico("P", 8, "PARAFAIT").
dico("P", 8, "PARAFANT").
dico("P", 8, "PARAFEES").
dico("P", 8, "PARAFENT").
dico("P", 8, "PARAFERA").
dico("P", 8, "PARAFEUR").
dico("P", 8, "PARAFIEZ").
dico("P", 8, "PARAFONS").
dico("P", 8, "PARAIENT").
dico("P", 8, "PARAISON").
dico("P", 8, "PARAISSE").
dico("P", 8, "PARAITRA").
dico("P", 8, "PARAITRE").
dico("P", 8, "PARALYSA").
dico("P", 8, "PARALYSE").
dico("P", 8, "PARANGON").
dico("P", 8, "PARANOIA").
dico("P", 8, "PARAPETS").
dico("P", 8, "PARAPHAI").
dico("P", 8, "PARAPHAS").
dico("P", 8, "PARAPHAT").
dico("P", 8, "PARAPHEE").
dico("P", 8, "PARAPHER").
dico("P", 8, "PARAPHES").
dico("P", 8, "PARAPHEZ").
dico("P", 8, "PARAPODE").
dico("P", 8, "PARASITA").
dico("P", 8, "PARASITE").
dico("P", 8, "PARASOLS").
dico("P", 8, "PARASSES").
dico("P", 8, "PARATAXE").
dico("P", 8, "PARATRES").
dico("P", 8, "PARAVENT").
dico("P", 8, "PARCAGES").
dico("P", 8, "PARCELLA").
dico("P", 8, "PARCELLE").
dico("P", 8, "PARCHETS").
dico("P", 8, "PARCOURE").
dico("P", 8, "PARCOURS").
dico("P", 8, "PARCOURT").
dico("P", 8, "PARCOURU").
dico("P", 8, "PARDONNA").
dico("P", 8, "PARDONNE").
dico("P", 8, "PAREAGES").
dico("P", 8, "PAREDRES").
dico("P", 8, "PAREILLE").
dico("P", 8, "PARELIES").
dico("P", 8, "PAREMENT").
dico("P", 8, "PARENTAL").
dico("P", 8, "PARENTES").
dico("P", 8, "PARERAIS").
dico("P", 8, "PARERAIT").
dico("P", 8, "PARERENT").
dico("P", 8, "PARERIEZ").
dico("P", 8, "PARERONS").
dico("P", 8, "PARERONT").
dico("P", 8, "PARESIES").
dico("P", 8, "PARESSAI").
dico("P", 8, "PARESSAS").
dico("P", 8, "PARESSAT").
dico("P", 8, "PARESSER").
dico("P", 8, "PARESSES").
dico("P", 8, "PARESSEZ").
dico("P", 8, "PAREUSES").
dico("P", 8, "PARFAIRE").
dico("P", 8, "PARFAITE").
dico("P", 8, "PARFAITS").
dico("P", 8, "PARFASSE").
dico("P", 8, "PARFERAI").
dico("P", 8, "PARFERAS").
dico("P", 8, "PARFEREZ").
dico("P", 8, "PARFILAI").
dico("P", 8, "PARFILAS").
dico("P", 8, "PARFILAT").
dico("P", 8, "PARFILEE").
dico("P", 8, "PARFILER").
dico("P", 8, "PARFILES").
dico("P", 8, "PARFILEZ").
dico("P", 8, "PARFIMES").
dico("P", 8, "PARFISSE").
dico("P", 8, "PARFITES").
dico("P", 8, "PARFONDE").
dico("P", 8, "PARFONDS").
dico("P", 8, "PARFONDU").
dico("P", 8, "PARFUMAI").
dico("P", 8, "PARFUMAS").
dico("P", 8, "PARFUMAT").
dico("P", 8, "PARFUMEE").
dico("P", 8, "PARFUMER").
dico("P", 8, "PARFUMES").
dico("P", 8, "PARFUMEZ").
dico("P", 8, "PARHELIE").
dico("P", 8, "PARIADES").
dico("P", 8, "PARIAGES").
dico("P", 8, "PARIAMES").
dico("P", 8, "PARIASSE").
dico("P", 8, "PARIATES").
dico("P", 8, "PARIERAI").
dico("P", 8, "PARIERAS").
dico("P", 8, "PARIEREZ").
dico("P", 8, "PARIETAL").
dico("P", 8, "PARIEURS").
dico("P", 8, "PARIEUSE").
dico("P", 8, "PARIGOTE").
dico("P", 8, "PARIGOTS").
dico("P", 8, "PARIIONS").
dico("P", 8, "PARISIEN").
dico("P", 8, "PARJURAI").
dico("P", 8, "PARJURAS").
dico("P", 8, "PARJURAT").
dico("P", 8, "PARJUREE").
dico("P", 8, "PARJURER").
dico("P", 8, "PARJURES").
dico("P", 8, "PARJUREZ").
dico("P", 8, "PARKINGS").
dico("P", 8, "PARLAMES").
dico("P", 8, "PARLANTE").
dico("P", 8, "PARLANTS").
dico("P", 8, "PARLASSE").
dico("P", 8, "PARLATES").
dico("P", 8, "PARLERAI").
dico("P", 8, "PARLERAS").
dico("P", 8, "PARLEREZ").
dico("P", 8, "PARLEURS").
dico("P", 8, "PARLEUSE").
dico("P", 8, "PARLIONS").
dico("P", 8, "PARLOIRS").
dico("P", 8, "PARLOTAI").
dico("P", 8, "PARLOTAS").
dico("P", 8, "PARLOTAT").
dico("P", 8, "PARLOTER").
dico("P", 8, "PARLOTES").
dico("P", 8, "PARLOTEZ").
dico("P", 8, "PARLOTTE").
dico("P", 8, "PARLURES").
dico("P", 8, "PARMELIE").
dico("P", 8, "PARMESAN").
dico("P", 8, "PARNASSE").
dico("P", 8, "PARODIAI").
dico("P", 8, "PARODIAS").
dico("P", 8, "PARODIAT").
dico("P", 8, "PARODIEE").
dico("P", 8, "PARODIER").
dico("P", 8, "PARODIES").
dico("P", 8, "PARODIEZ").
dico("P", 8, "PAROISSE").
dico("P", 8, "PAROLIER").
dico("P", 8, "PARONYME").
dico("P", 8, "PAROTIDE").
dico("P", 8, "PAROUSIE").
dico("P", 8, "PARPAING").
dico("P", 8, "PARQUAIS").
dico("P", 8, "PARQUAIT").
dico("P", 8, "PARQUANT").
dico("P", 8, "PARQUEES").
dico("P", 8, "PARQUENT").
dico("P", 8, "PARQUERA").
dico("P", 8, "PARQUETA").
dico("P", 8, "PARQUETE").
dico("P", 8, "PARQUETS").
dico("P", 8, "PARQUEUR").
dico("P", 8, "PARQUIER").
dico("P", 8, "PARQUIEZ").
dico("P", 8, "PARQUONS").
dico("P", 8, "PARRAINA").
dico("P", 8, "PARRAINE").
dico("P", 8, "PARRAINS").
dico("P", 8, "PARSEMAI").
dico("P", 8, "PARSEMAS").
dico("P", 8, "PARSEMAT").
dico("P", 8, "PARSEMEE").
dico("P", 8, "PARSEMER").
dico("P", 8, "PARSEMES").
dico("P", 8, "PARSEMEZ").
dico("P", 8, "PARSISME").
dico("P", 8, "PARTAGEA").
dico("P", 8, "PARTAGEE").
dico("P", 8, "PARTAGER").
dico("P", 8, "PARTAGES").
dico("P", 8, "PARTAGEZ").
dico("P", 8, "PARTANCE").
dico("P", 8, "PARTANTE").
dico("P", 8, "PARTANTS").
dico("P", 8, "PARTERRE").
dico("P", 8, "PARTIALE").
dico("P", 8, "PARTIAUX").
dico("P", 8, "PARTIELS").
dico("P", 8, "PARTIMES").
dico("P", 8, "PARTIONS").
dico("P", 8, "PARTIRAI").
dico("P", 8, "PARTIRAS").
dico("P", 8, "PARTIREZ").
dico("P", 8, "PARTISAN").
dico("P", 8, "PARTISSE").
dico("P", 8, "PARTITAS").
dico("P", 8, "PARTITES").
dico("P", 8, "PARTITIF").
dico("P", 8, "PARTOUSA").
dico("P", 8, "PARTOUSE").
dico("P", 8, "PARTOUZA").
dico("P", 8, "PARTOUZE").
dico("P", 8, "PARULIES").
dico("P", 8, "PARULINE").
dico("P", 8, "PARURENT").
dico("P", 8, "PARURIER").
dico("P", 8, "PARUSSES").
dico("P", 8, "PARUTION").
dico("P", 8, "PARVENEZ").
dico("P", 8, "PARVENIR").
dico("P", 8, "PARVENUE").
dico("P", 8, "PARVENUS").
dico("P", 8, "PARVIENS").
dico("P", 8, "PARVIENT").
dico("P", 8, "PASCALES").
dico("P", 8, "PASCUANE").
dico("P", 8, "PASCUANS").
dico("P", 8, "PASDARAN").
dico("P", 8, "PASHMINA").
dico("P", 8, "PASQUINA").
dico("P", 8, "PASQUINE").
dico("P", 8, "PASQUINS").
dico("P", 8, "PASSABLE").
dico("P", 8, "PASSADES").
dico("P", 8, "PASSAGER").
dico("P", 8, "PASSAGES").
dico("P", 8, "PASSAMES").
dico("P", 8, "PASSANTE").
dico("P", 8, "PASSANTS").
dico("P", 8, "PASSASSE").
dico("P", 8, "PASSATES").
dico("P", 8, "PASSERAI").
dico("P", 8, "PASSERAS").
dico("P", 8, "PASSEREZ").
dico("P", 8, "PASSETTE").
dico("P", 8, "PASSEURS").
dico("P", 8, "PASSEUSE").
dico("P", 8, "PASSIBLE").
dico("P", 8, "PASSINGS").
dico("P", 8, "PASSIONS").
dico("P", 8, "PASSIVAI").
dico("P", 8, "PASSIVAS").
dico("P", 8, "PASSIVAT").
dico("P", 8, "PASSIVEE").
dico("P", 8, "PASSIVER").
dico("P", 8, "PASSIVES").
dico("P", 8, "PASSIVEZ").
dico("P", 8, "PASSOIRE").
dico("P", 8, "PASTAGAS").
dico("P", 8, "PASTELLA").
dico("P", 8, "PASTELLE").
dico("P", 8, "PASTEQUE").
dico("P", 8, "PASTEURS").
dico("P", 8, "PASTICHA").
dico("P", 8, "PASTICHE").
dico("P", 8, "PASTILLA").
dico("P", 8, "PASTILLE").
dico("P", 8, "PASTORAL").
dico("P", 8, "PASTORAT").
dico("P", 8, "PASTRAMI").
dico("P", 8, "PATACHES").
dico("P", 8, "PATACHON").
dico("P", 8, "PATAGIUM").
dico("P", 8, "PATAGONS").
dico("P", 8, "PATAPOUF").
dico("P", 8, "PATAQUES").
dico("P", 8, "PATARAFE").
dico("P", 8, "PATARINS").
dico("P", 8, "PATATRAS").
dico("P", 8, "PATAUDES").
dico("P", 8, "PATAUGAS").
dico("P", 8, "PATAUGEA").
dico("P", 8, "PATAUGER").
dico("P", 8, "PATAUGES").
dico("P", 8, "PATAUGEZ").
dico("P", 8, "PATELINA").
dico("P", 8, "PATELINE").
dico("P", 8, "PATELINS").
dico("P", 8, "PATELLES").
dico("P", 8, "PATENTAI").
dico("P", 8, "PATENTAS").
dico("P", 8, "PATENTAT").
dico("P", 8, "PATENTEE").
dico("P", 8, "PATENTER").
dico("P", 8, "PATENTES").
dico("P", 8, "PATENTEZ").
dico("P", 8, "PATERNEL").
dico("P", 8, "PATERNES").
dico("P", 8, "PATEUSES").
dico("P", 8, "PATIENCE").
dico("P", 8, "PATIENTA").
dico("P", 8, "PATIENTE").
dico("P", 8, "PATIENTS").
dico("P", 8, "PATINAGE").
dico("P", 8, "PATINAIS").
dico("P", 8, "PATINAIT").
dico("P", 8, "PATINANT").
dico("P", 8, "PATINEES").
dico("P", 8, "PATINENT").
dico("P", 8, "PATINERA").
dico("P", 8, "PATINEUR").
dico("P", 8, "PATINIEZ").
dico("P", 8, "PATINONS").
dico("P", 8, "PATIRAIS").
dico("P", 8, "PATIRAIT").
dico("P", 8, "PATIRENT").
dico("P", 8, "PATIRIEZ").
dico("P", 8, "PATIRONS").
dico("P", 8, "PATIRONT").
dico("P", 8, "PATISSAI").
dico("P", 8, "PATISSAS").
dico("P", 8, "PATISSAT").
dico("P", 8, "PATISSEE").
dico("P", 8, "PATISSER").
dico("P", 8, "PATISSES").
dico("P", 8, "PATISSEZ").
dico("P", 8, "PATISSON").
dico("P", 8, "PATOCHES").
dico("P", 8, "PATOISAI").
dico("P", 8, "PATOISAS").
dico("P", 8, "PATOISAT").
dico("P", 8, "PATOISER").
dico("P", 8, "PATOISES").
dico("P", 8, "PATOISEZ").
dico("P", 8, "PATRAQUE").
dico("P", 8, "PATRICES").
dico("P", 8, "PATRIOTE").
dico("P", 8, "PATRONAL").
dico("P", 8, "PATRONAT").
dico("P", 8, "PATRONNA").
dico("P", 8, "PATRONNE").
dico("P", 8, "PATTERNS").
dico("P", 8, "PATTIERE").
dico("P", 8, "PATTIERS").
dico("P", 8, "PATURAGE").
dico("P", 8, "PATURAIS").
dico("P", 8, "PATURAIT").
dico("P", 8, "PATURANT").
dico("P", 8, "PATUREES").
dico("P", 8, "PATURENT").
dico("P", 8, "PATURERA").
dico("P", 8, "PATURIEZ").
dico("P", 8, "PATURINS").
dico("P", 8, "PATURONS").
dico("P", 8, "PAUILLAC").
dico("P", 8, "PAULETTE").
dico("P", 8, "PAULIENS").
dico("P", 8, "PAULISTE").
dico("P", 8, "PAUMAMES").
dico("P", 8, "PAUMASSE").
dico("P", 8, "PAUMATES").
dico("P", 8, "PAUMELLE").
dico("P", 8, "PAUMERAI").
dico("P", 8, "PAUMERAS").
dico("P", 8, "PAUMEREZ").
dico("P", 8, "PAUMIERE").
dico("P", 8, "PAUMIERS").
dico("P", 8, "PAUMIONS").
dico("P", 8, "PAUMOIES").
dico("P", 8, "PAUMOYAI").
dico("P", 8, "PAUMOYAS").
dico("P", 8, "PAUMOYAT").
dico("P", 8, "PAUMOYEE").
dico("P", 8, "PAUMOYER").
dico("P", 8, "PAUMOYES").
dico("P", 8, "PAUMOYEZ").
dico("P", 8, "PAUMURES").
dico("P", 8, "PAUPIERE").
dico("P", 8, "PAUSAMES").
dico("P", 8, "PAUSASSE").
dico("P", 8, "PAUSATES").
dico("P", 8, "PAUSERAI").
dico("P", 8, "PAUSERAS").
dico("P", 8, "PAUSEREZ").
dico("P", 8, "PAUSIONS").
dico("P", 8, "PAUVRETE").
dico("P", 8, "PAUVRETS").
dico("P", 8, "PAVAIENT").
dico("P", 8, "PAVANAIS").
dico("P", 8, "PAVANAIT").
dico("P", 8, "PAVANANT").
dico("P", 8, "PAVANEES").
dico("P", 8, "PAVANENT").
dico("P", 8, "PAVANERA").
dico("P", 8, "PAVANIEZ").
dico("P", 8, "PAVANONS").
dico("P", 8, "PAVASSES").
dico("P", 8, "PAVEMENT").
dico("P", 8, "PAVERAIS").
dico("P", 8, "PAVERAIT").
dico("P", 8, "PAVERENT").
dico("P", 8, "PAVERIEZ").
dico("P", 8, "PAVERONS").
dico("P", 8, "PAVERONT").
dico("P", 8, "PAVESANE").
dico("P", 8, "PAVESANS").
dico("P", 8, "PAVILLON").
dico("P", 8, "PAVOISAI").
dico("P", 8, "PAVOISAS").
dico("P", 8, "PAVOISAT").
dico("P", 8, "PAVOISEE").
dico("P", 8, "PAVOISER").
dico("P", 8, "PAVOISES").
dico("P", 8, "PAVOISEZ").
dico("P", 8, "PAYABLES").
dico("P", 8, "PAYAIENT").
dico("P", 8, "PAYANTES").
dico("P", 8, "PAYASSES").
dico("P", 8, "PAYEMENT").
dico("P", 8, "PAYERAIS").
dico("P", 8, "PAYERAIT").
dico("P", 8, "PAYERENT").
dico("P", 8, "PAYERIEZ").
dico("P", 8, "PAYERONS").
dico("P", 8, "PAYERONT").
dico("P", 8, "PAYEUSES").
dico("P", 8, "PAYSAGEE").
dico("P", 8, "PAYSAGER").
dico("P", 8, "PAYSAGES").
dico("P", 8, "PAYSANNE").
dico("P", 8, "PEAGERES").
dico("P", 8, "PEAGISTE").
dico("P", 8, "PEAUCIER").
dico("P", 8, "PEAUFINA").
dico("P", 8, "PEAUFINE").
dico("P", 8, "PEBRINES").
dico("P", 8, "PEBROQUE").
dico("P", 8, "PECCABLE").
dico("P", 8, "PECCANTE").
dico("P", 8, "PECCANTS").
dico("P", 8, "PECHAMES").
dico("P", 8, "PECHASSE").
dico("P", 8, "PECHATES").
dico("P", 8, "PECHERAI").
dico("P", 8, "PECHERAS").
dico("P", 8, "PECHEREZ").
dico("P", 8, "PECHERIE").
dico("P", 8, "PECHETTE").
dico("P", 8, "PECHEURS").
dico("P", 8, "PECHEUSE").
dico("P", 8, "PECHIONS").
dico("P", 8, "PECLOTAI").
dico("P", 8, "PECLOTAS").
dico("P", 8, "PECLOTAT").
dico("P", 8, "PECLOTER").
dico("P", 8, "PECLOTES").
dico("P", 8, "PECLOTEZ").
dico("P", 8, "PECNOTTE").
dico("P", 8, "PECORINO").
dico("P", 8, "PECTASES").
dico("P", 8, "PECTINEE").
dico("P", 8, "PECTINES").
dico("P", 8, "PECTIQUE").
dico("P", 8, "PECTORAL").
dico("P", 8, "PECTOSES").
dico("P", 8, "PECULATS").
dico("P", 8, "PEDALAGE").
dico("P", 8, "PEDALAIS").
dico("P", 8, "PEDALAIT").
dico("P", 8, "PEDALANT").
dico("P", 8, "PEDALENT").
dico("P", 8, "PEDALERA").
dico("P", 8, "PEDALEUR").
dico("P", 8, "PEDALIER").
dico("P", 8, "PEDALIEZ").
dico("P", 8, "PEDALONS").
dico("P", 8, "PEDANTES").
dico("P", 8, "PEDEGERE").
dico("P", 8, "PEDESTRE").
dico("P", 8, "PEDIATRE").
dico("P", 8, "PEDICULE").
dico("P", 8, "PEDICURE").
dico("P", 8, "PEDIEUSE").
dico("P", 8, "PEDIGREE").
dico("P", 8, "PEDILUVE").
dico("P", 8, "PEDIMANE").
dico("P", 8, "PEDIMENT").
dico("P", 8, "PEDZAMES").
dico("P", 8, "PEDZASSE").
dico("P", 8, "PEDZATES").
dico("P", 8, "PEDZERAI").
dico("P", 8, "PEDZERAS").
dico("P", 8, "PEDZEREZ").
dico("P", 8, "PEDZIONS").
dico("P", 8, "PEELINGS").
dico("P", 8, "PEGOSITE").
dico("P", 8, "PEGUEUSE").
dico("P", 8, "PEIGNAGE").
dico("P", 8, "PEIGNAIS").
dico("P", 8, "PEIGNAIT").
dico("P", 8, "PEIGNANT").
dico("P", 8, "PEIGNEES").
dico("P", 8, "PEIGNENT").
dico("P", 8, "PEIGNERA").
dico("P", 8, "PEIGNEUR").
dico("P", 8, "PEIGNIER").
dico("P", 8, "PEIGNIEZ").
dico("P", 8, "PEIGNOIR").
dico("P", 8, "PEIGNONS").
dico("P", 8, "PEIGNURE").
dico("P", 8, "PEINAMES").
dico("P", 8, "PEINARDE").
dico("P", 8, "PEINARDS").
dico("P", 8, "PEINASSE").
dico("P", 8, "PEINATES").
dico("P", 8, "PEINDRAI").
dico("P", 8, "PEINDRAS").
dico("P", 8, "PEINDREZ").
dico("P", 8, "PEINERAI").
dico("P", 8, "PEINERAS").
dico("P", 8, "PEINEREZ").
dico("P", 8, "PEINIONS").
dico("P", 8, "PEINTRES").
dico("P", 8, "PEINTURA").
dico("P", 8, "PEINTURE").
dico("P", 8, "PEKINEES").
dico("P", 8, "PEKINOIS").
dico("P", 8, "PELAGIEN").
dico("P", 8, "PELAIENT").
dico("P", 8, "PELAMIDE").
dico("P", 8, "PELAMYDE").
dico("P", 8, "PELANTES").
dico("P", 8, "PELARDON").
dico("P", 8, "PELASSES").
dico("P", 8, "PELEENNE").
dico("P", 8, "PELERAIS").
dico("P", 8, "PELERAIT").
dico("P", 8, "PELERENT").
dico("P", 8, "PELERIEZ").
dico("P", 8, "PELERINE").
dico("P", 8, "PELERINS").
dico("P", 8, "PELERONS").
dico("P", 8, "PELERONT").
dico("P", 8, "PELIADES").
dico("P", 8, "PELICANS").
dico("P", 8, "PELISSES").
dico("P", 8, "PELLAGRE").
dico("P", 8, "PELLAMES").
dico("P", 8, "PELLASSE").
dico("P", 8, "PELLATES").
dico("P", 8, "PELLERAI").
dico("P", 8, "PELLERAS").
dico("P", 8, "PELLEREZ").
dico("P", 8, "PELLETAI").
dico("P", 8, "PELLETAS").
dico("P", 8, "PELLETAT").
dico("P", 8, "PELLETEE").
dico("P", 8, "PELLETER").
dico("P", 8, "PELLETES").
dico("P", 8, "PELLETEZ").
dico("P", 8, "PELLETTE").
dico("P", 8, "PELLIONS").
dico("P", 8, "PELLOCHE").
dico("P", 8, "PELOBATE").
dico("P", 8, "PELOCHES").
dico("P", 8, "PELODYTE").
dico("P", 8, "PELOTAGE").
dico("P", 8, "PELOTAIS").
dico("P", 8, "PELOTAIT").
dico("P", 8, "PELOTANT").
dico("P", 8, "PELOTARI").
dico("P", 8, "PELOTEES").
dico("P", 8, "PELOTENT").
dico("P", 8, "PELOTERA").
dico("P", 8, "PELOTEUR").
dico("P", 8, "PELOTIEZ").
dico("P", 8, "PELOTONS").
dico("P", 8, "PELOUSES").
dico("P", 8, "PELTASTE").
dico("P", 8, "PELUCHAI").
dico("P", 8, "PELUCHAS").
dico("P", 8, "PELUCHAT").
dico("P", 8, "PELUCHEE").
dico("P", 8, "PELUCHER").
dico("P", 8, "PELUCHES").
dico("P", 8, "PELUCHEZ").
dico("P", 8, "PELVIENS").
dico("P", 8, "PEMBINAS").
dico("P", 8, "PEMMICAN").
dico("P", 8, "PENALISA").
dico("P", 8, "PENALISE").
dico("P", 8, "PENALITE").
dico("P", 8, "PENALTYS").
dico("P", 8, "PENARDES").
dico("P", 8, "PENAUDES").
dico("P", 8, "PENCHAIS").
dico("P", 8, "PENCHAIT").
dico("P", 8, "PENCHANT").
dico("P", 8, "PENCHEES").
dico("P", 8, "PENCHENT").
dico("P", 8, "PENCHERA").
dico("P", 8, "PENCHIEZ").
dico("P", 8, "PENCHONS").
dico("P", 8, "PENDABLE").
dico("P", 8, "PENDAGES").
dico("P", 8, "PENDANTE").
dico("P", 8, "PENDANTS").
dico("P", 8, "PENDARDE").
dico("P", 8, "PENDARDS").
dico("P", 8, "PENDERIE").
dico("P", 8, "PENDILLA").
dico("P", 8, "PENDILLE").
dico("P", 8, "PENDIMES").
dico("P", 8, "PENDIONS").
dico("P", 8, "PENDISSE").
dico("P", 8, "PENDITES").
dico("P", 8, "PENDJABI").
dico("P", 8, "PENDOIRS").
dico("P", 8, "PENDRAIS").
dico("P", 8, "PENDRAIT").
dico("P", 8, "PENDRIEZ").
dico("P", 8, "PENDRONS").
dico("P", 8, "PENDRONT").
dico("P", 8, "PENDULAI").
dico("P", 8, "PENDULAS").
dico("P", 8, "PENDULAT").
dico("P", 8, "PENDULEE").
dico("P", 8, "PENDULER").
dico("P", 8, "PENDULES").
dico("P", 8, "PENDULEZ").
dico("P", 8, "PENELOPE").
dico("P", 8, "PENETRAI").
dico("P", 8, "PENETRAS").
dico("P", 8, "PENETRAT").
dico("P", 8, "PENETREE").
dico("P", 8, "PENETRER").
dico("P", 8, "PENETRES").
dico("P", 8, "PENETREZ").
dico("P", 8, "PENIBLES").
dico("P", 8, "PENICHES").
dico("P", 8, "PENIENNE").
dico("P", 8, "PENITENT").
dico("P", 8, "PENNAGES").
dico("P", 8, "PENOMBRE").
dico("P", 8, "PENSABLE").
dico("P", 8, "PENSAMES").
dico("P", 8, "PENSANTE").
dico("P", 8, "PENSANTS").
dico("P", 8, "PENSASSE").
dico("P", 8, "PENSATES").
dico("P", 8, "PENSERAI").
dico("P", 8, "PENSERAS").
dico("P", 8, "PENSEREZ").
dico("P", 8, "PENSEURS").
dico("P", 8, "PENSEUSE").
dico("P", 8, "PENSIONS").
dico("P", 8, "PENSIVES").
dico("P", 8, "PENTACLE").
dico("P", 8, "PENTANES").
dico("P", 8, "PENTANOL").
dico("P", 8, "PENTHODE").
dico("P", 8, "PENTODES").
dico("P", 8, "PENTOSES").
dico("P", 8, "PENTRITE").
dico("P", 8, "PENTURES").
dico("P", 8, "PENURIES").
dico("P", 8, "PEPERINS").
dico("P", 8, "PEPETTES").
dico("P", 8, "PEPIAMES").
dico("P", 8, "PEPIASSE").
dico("P", 8, "PEPIATES").
dico("P", 8, "PEPIERAI").
dico("P", 8, "PEPIERAS").
dico("P", 8, "PEPIEREZ").
dico("P", 8, "PEPIIONS").
dico("P", 8, "PEPONIDE").
dico("P", 8, "PEPSINES").
dico("P", 8, "PEPTIDES").
dico("P", 8, "PEPTIQUE").
dico("P", 8, "PEPTONES").
dico("P", 8, "PEQUENOT").
dico("P", 8, "PEQUISTE").
dico("P", 8, "PERACIDE").
dico("P", 8, "PERAMELE").
dico("P", 8, "PERCAGES").
dico("P", 8, "PERCALES").
dico("P", 8, "PERCAMES").
dico("P", 8, "PERCANTE").
dico("P", 8, "PERCANTS").
dico("P", 8, "PERCASSE").
dico("P", 8, "PERCATES").
dico("P", 8, "PERCEPTS").
dico("P", 8, "PERCERAI").
dico("P", 8, "PERCERAS").
dico("P", 8, "PERCEREZ").
dico("P", 8, "PERCETTE").
dico("P", 8, "PERCEURS").
dico("P", 8, "PERCEUSE").
dico("P", 8, "PERCEVEZ").
dico("P", 8, "PERCEVRA").
dico("P", 8, "PERCHAGE").
dico("P", 8, "PERCHAIS").
dico("P", 8, "PERCHAIT").
dico("P", 8, "PERCHANT").
dico("P", 8, "PERCHEES").
dico("P", 8, "PERCHENT").
dico("P", 8, "PERCHERA").
dico("P", 8, "PERCHEUR").
dico("P", 8, "PERCHIEZ").
dico("P", 8, "PERCHMAN").
dico("P", 8, "PERCHOIR").
dico("P", 8, "PERCHONS").
dico("P", 8, "PERCIDES").
dico("P", 8, "PERCIONS").
dico("P", 8, "PERCLUSE").
dico("P", 8, "PERCOIRS").
dico("P", 8, "PERCOIVE").
dico("P", 8, "PERCUMES").
dico("P", 8, "PERCUSSE").
dico("P", 8, "PERCUTAI").
dico("P", 8, "PERCUTAS").
dico("P", 8, "PERCUTAT").
dico("P", 8, "PERCUTEE").
dico("P", 8, "PERCUTER").
dico("P", 8, "PERCUTES").
dico("P", 8, "PERCUTEZ").
dico("P", 8, "PERDABLE").
dico("P", 8, "PERDANTE").
dico("P", 8, "PERDANTS").
dico("P", 8, "PERDIMES").
dico("P", 8, "PERDIONS").
dico("P", 8, "PERDISSE").
dico("P", 8, "PERDITES").
dico("P", 8, "PERDRAIS").
dico("P", 8, "PERDRAIT").
dico("P", 8, "PERDREAU").
dico("P", 8, "PERDRIEZ").
dico("P", 8, "PERDRONS").
dico("P", 8, "PERDRONT").
dico("P", 8, "PERDURAI").
dico("P", 8, "PERDURAS").
dico("P", 8, "PERDURAT").
dico("P", 8, "PERDURER").
dico("P", 8, "PERDURES").
dico("P", 8, "PERDUREZ").
dico("P", 8, "PEREGRIN").
dico("P", 8, "PERENNES").
dico("P", 8, "PERFECTO").
dico("P", 8, "PERFIDES").
dico("P", 8, "PERFIDIE").
dico("P", 8, "PERFOLIE").
dico("P", 8, "PERFORAI").
dico("P", 8, "PERFORAS").
dico("P", 8, "PERFORAT").
dico("P", 8, "PERFOREE").
dico("P", 8, "PERFORER").
dico("P", 8, "PERFORES").
dico("P", 8, "PERFOREZ").
dico("P", 8, "PERFORMA").
dico("P", 8, "PERFORME").
dico("P", 8, "PERFUSAI").
dico("P", 8, "PERFUSAS").
dico("P", 8, "PERFUSAT").
dico("P", 8, "PERFUSEE").
dico("P", 8, "PERFUSER").
dico("P", 8, "PERFUSES").
dico("P", 8, "PERFUSEZ").
dico("P", 8, "PERGOLAS").
dico("P", 8, "PERIBOLE").
dico("P", 8, "PERIDOTS").
dico("P", 8, "PERIGEES").
dico("P", 8, "PERIMAIS").
dico("P", 8, "PERIMAIT").
dico("P", 8, "PERIMANT").
dico("P", 8, "PERIMEES").
dico("P", 8, "PERIMENT").
dico("P", 8, "PERIMERA").
dico("P", 8, "PERIMIEZ").
dico("P", 8, "PERIMONS").
dico("P", 8, "PERINEAL").
dico("P", 8, "PERINEES").
dico("P", 8, "PERIODES").
dico("P", 8, "PERIOSTE").
dico("P", 8, "PERIPATE").
dico("P", 8, "PERIPLES").
dico("P", 8, "PERIRAIS").
dico("P", 8, "PERIRAIT").
dico("P", 8, "PERIRENT").
dico("P", 8, "PERIRIEZ").
dico("P", 8, "PERIRONS").
dico("P", 8, "PERIRONT").
dico("P", 8, "PERISSES").
dico("P", 8, "PERISSEZ").
dico("P", 8, "PERITELS").
dico("P", 8, "PERLAMES").
dico("P", 8, "PERLANTE").
dico("P", 8, "PERLANTS").
dico("P", 8, "PERLASSE").
dico("P", 8, "PERLATES").
dico("P", 8, "PERLECHE").
dico("P", 8, "PERLERAI").
dico("P", 8, "PERLERAS").
dico("P", 8, "PERLEREZ").
dico("P", 8, "PERLIERE").
dico("P", 8, "PERLIERS").
dico("P", 8, "PERLIONS").
dico("P", 8, "PERLITES").
dico("P", 8, "PERLOIRS").
dico("P", 8, "PERLOUSE").
dico("P", 8, "PERLOUZE").
dico("P", 8, "PERLURES").
dico("P", 8, "PERMAGEL").
dico("P", 8, "PERMEASE").
dico("P", 8, "PERMETTE").
dico("P", 8, "PERMIENS").
dico("P", 8, "PERMIMES").
dico("P", 8, "PERMISES").
dico("P", 8, "PERMISSE").
dico("P", 8, "PERMITES").
dico("P", 8, "PERMUTAI").
dico("P", 8, "PERMUTAS").
dico("P", 8, "PERMUTAT").
dico("P", 8, "PERMUTEE").
dico("P", 8, "PERMUTER").
dico("P", 8, "PERMUTES").
dico("P", 8, "PERMUTEZ").
dico("P", 8, "PERONIER").
dico("P", 8, "PERORAIS").
dico("P", 8, "PERORAIT").
dico("P", 8, "PERORANT").
dico("P", 8, "PERORENT").
dico("P", 8, "PERORERA").
dico("P", 8, "PEROREUR").
dico("P", 8, "PERORIEZ").
dico("P", 8, "PERORONS").
dico("P", 8, "PEROXYDA").
dico("P", 8, "PEROXYDE").
dico("P", 8, "PERPETRA").
dico("P", 8, "PERPETRE").
dico("P", 8, "PERPETTE").
dico("P", 8, "PERPETUA").
dico("P", 8, "PERPETUE").
dico("P", 8, "PERPLEXE").
dico("P", 8, "PERRIERE").
dico("P", 8, "PERRUCHE").
dico("P", 8, "PERRUQUE").
dico("P", 8, "PERSANES").
dico("P", 8, "PERSEIDE").
dico("P", 8, "PERSICOT").
dico("P", 8, "PERSIFLA").
dico("P", 8, "PERSIFLE").
dico("P", 8, "PERSILLA").
dico("P", 8, "PERSILLE").
dico("P", 8, "PERSIQUE").
dico("P", 8, "PERSISTA").
dico("P", 8, "PERSISTE").
dico("P", 8, "PERSONEE").
dico("P", 8, "PERSONES").
dico("P", 8, "PERSONNE").
dico("P", 8, "PERSUADA").
dico("P", 8, "PERSUADE").
dico("P", 8, "PERTURBA").
dico("P", 8, "PERTURBE").
dico("P", 8, "PERUGINE").
dico("P", 8, "PERUGINS").
dico("P", 8, "PERUVIEN").
dico("P", 8, "PERVERSE").
dico("P", 8, "PERVERTI").
dico("P", 8, "PERVIBRA").
dico("P", 8, "PERVIBRE").
dico("P", 8, "PESAIENT").
dico("P", 8, "PESANTES").
dico("P", 8, "PESASSES").
dico("P", 8, "PESERAIS").
dico("P", 8, "PESERAIT").
dico("P", 8, "PESERENT").
dico("P", 8, "PESERIEZ").
dico("P", 8, "PESERONS").
dico("P", 8, "PESERONT").
dico("P", 8, "PESETTES").
dico("P", 8, "PESEUSES").
dico("P", 8, "PESSAIRE").
dico("P", 8, "PESSIERE").
dico("P", 8, "PESTAMES").
dico("P", 8, "PESTASSE").
dico("P", 8, "PESTATES").
dico("P", 8, "PESTERAI").
dico("P", 8, "PESTERAS").
dico("P", 8, "PESTEREZ").
dico("P", 8, "PESTEUSE").
dico("P", 8, "PESTIONS").
dico("P", 8, "PETAIENT").
dico("P", 8, "PETANQUE").
dico("P", 8, "PETANTES").
dico("P", 8, "PETARADA").
dico("P", 8, "PETARADE").
dico("P", 8, "PETARDAI").
dico("P", 8, "PETARDAS").
dico("P", 8, "PETARDAT").
dico("P", 8, "PETARDEE").
dico("P", 8, "PETARDER").
dico("P", 8, "PETARDES").
dico("P", 8, "PETARDEZ").
dico("P", 8, "PETASSES").
dico("P", 8, "PETAURES").
dico("P", 8, "PETECHIE").
dico("P", 8, "PETERAIS").
dico("P", 8, "PETERAIT").
dico("P", 8, "PETERENT").
dico("P", 8, "PETERIEZ").
dico("P", 8, "PETERONS").
dico("P", 8, "PETERONT").
dico("P", 8, "PETEUSES").
dico("P", 8, "PETILLAI").
dico("P", 8, "PETILLAS").
dico("P", 8, "PETILLAT").
dico("P", 8, "PETILLER").
dico("P", 8, "PETILLES").
dico("P", 8, "PETILLEZ").
dico("P", 8, "PETIOLEE").
dico("P", 8, "PETIOLES").
dico("P", 8, "PETIOTES").
dico("P", 8, "PETITION").
dico("P", 8, "PETOCHES").
dico("P", 8, "PETOIRES").
dico("P", 8, "PETOMANE").
dico("P", 8, "PETONCLE").
dico("P", 8, "PETOULET").
dico("P", 8, "PETREUSE").
dico("P", 8, "PETRIFIA").
dico("P", 8, "PETRIFIE").
dico("P", 8, "PETRIMES").
dico("P", 8, "PETRIRAI").
dico("P", 8, "PETRIRAS").
dico("P", 8, "PETRIREZ").
dico("P", 8, "PETRISSE").
dico("P", 8, "PETRITES").
dico("P", 8, "PETROLAI").
dico("P", 8, "PETROLAS").
dico("P", 8, "PETROLAT").
dico("P", 8, "PETROLEE").
dico("P", 8, "PETROLER").
dico("P", 8, "PETROLES").
dico("P", 8, "PETROLEZ").
dico("P", 8, "PETULANT").
dico("P", 8, "PETUNAIS").
dico("P", 8, "PETUNAIT").
dico("P", 8, "PETUNANT").
dico("P", 8, "PETUNENT").
dico("P", 8, "PETUNERA").
dico("P", 8, "PETUNIAS").
dico("P", 8, "PETUNIEZ").
dico("P", 8, "PETUNONS").
dico("P", 8, "PETUNSES").
dico("P", 8, "PEUCEDAN").
dico("P", 8, "PEUCHERE").
dico("P", 8, "PEULVENS").
dico("P", 8, "PEUPLADE").
dico("P", 8, "PEUPLAIS").
dico("P", 8, "PEUPLAIT").
dico("P", 8, "PEUPLANT").
dico("P", 8, "PEUPLEES").
dico("P", 8, "PEUPLENT").
dico("P", 8, "PEUPLERA").
dico("P", 8, "PEUPLIER").
dico("P", 8, "PEUPLIEZ").
dico("P", 8, "PEUPLONS").
dico("P", 8, "PEUREUSE").
dico("P", 8, "PEZIZALE").
dico("P", 8, "PFENNIGE").
dico("P", 8, "PFENNIGS").
dico("P", 8, "PHAETONS").
dico("P", 8, "PHALANGE").
dico("P", 8, "PHALENES").
dico("P", 8, "PHALERES").
dico("P", 8, "PHALLINE").
dico("P", 8, "PHANERES").
dico("P", 8, "PHARAONS").
dico("P", 8, "PHARYNGE").
dico("P", 8, "PHASIQUE").
dico("P", 8, "PHASMIDE").
dico("P", 8, "PHATIQUE").
dico("P", 8, "PHENATES").
dico("P", 8, "PHENIQUE").
dico("P", 8, "PHENYLES").
dico("P", 8, "PHILIBEG").
dico("P", 8, "PHILTRES").
dico("P", 8, "PHIMOSIS").
dico("P", 8, "PHLEBITE").
dico("P", 8, "PHLEGMON").
dico("P", 8, "PHLEOLES").
dico("P", 8, "PHLOEMES").
dico("P", 8, "PHOBIQUE").
dico("P", 8, "PHOCEENS").
dico("P", 8, "PHOLADES").
dico("P", 8, "PHOLIOTE").
dico("P", 8, "PHONEMES").
dico("P", 8, "PHONIQUE").
dico("P", 8, "PHORMION").
dico("P", 8, "PHORMIUM").
dico("P", 8, "PHOSGENE").
dico("P", 8, "PHRASAIS").
dico("P", 8, "PHRASAIT").
dico("P", 8, "PHRASANT").
dico("P", 8, "PHRASEES").
dico("P", 8, "PHRASENT").
dico("P", 8, "PHRASERA").
dico("P", 8, "PHRASEUR").
dico("P", 8, "PHRASIEZ").
dico("P", 8, "PHRASONS").
dico("P", 8, "PHRATRIE").
dico("P", 8, "PHRYGANE").
dico("P", 8, "PHRYGIEN").
dico("P", 8, "PHTIRIUS").
dico("P", 8, "PHTISIES").
dico("P", 8, "PHYLLADE").
dico("P", 8, "PHYLLIES").
dico("P", 8, "PHYSALIE").
dico("P", 8, "PHYSALIS").
dico("P", 8, "PHYSIQUE").
dico("P", 8, "PHYTOPTE").
dico("P", 8, "PIAFFAIS").
dico("P", 8, "PIAFFAIT").
dico("P", 8, "PIAFFANT").
dico("P", 8, "PIAFFENT").
dico("P", 8, "PIAFFERA").
dico("P", 8, "PIAFFERS").
dico("P", 8, "PIAFFEUR").
dico("P", 8, "PIAFFIEZ").
dico("P", 8, "PIAFFONS").
dico("P", 8, "PIAILLAI").
dico("P", 8, "PIAILLAS").
dico("P", 8, "PIAILLAT").
dico("P", 8, "PIAILLER").
dico("P", 8, "PIAILLES").
dico("P", 8, "PIAILLEZ").
dico("P", 8, "PIANISTE").
dico("P", 8, "PIANOLAS").
dico("P", 8, "PIANOTAI").
dico("P", 8, "PIANOTAS").
dico("P", 8, "PIANOTAT").
dico("P", 8, "PIANOTEE").
dico("P", 8, "PIANOTER").
dico("P", 8, "PIANOTES").
dico("P", 8, "PIANOTEZ").
dico("P", 8, "PIAPIATA").
dico("P", 8, "PIAPIATE").
dico("P", 8, "PIASSAVA").
dico("P", 8, "PIASTRES").
dico("P", 8, "PIAULAIS").
dico("P", 8, "PIAULAIT").
dico("P", 8, "PIAULANT").
dico("P", 8, "PIAULENT").
dico("P", 8, "PIAULERA").
dico("P", 8, "PIAULIEZ").
dico("P", 8, "PIAULONS").
dico("P", 8, "PIBROCKS").
dico("P", 8, "PICADORS").
dico("P", 8, "PICARDAN").
dico("P", 8, "PICARDES").
dico("P", 8, "PICARELS").
dico("P", 8, "PICCOLOS").
dico("P", 8, "PICODONS").
dico("P", 8, "PICOLAIS").
dico("P", 8, "PICOLAIT").
dico("P", 8, "PICOLANT").
dico("P", 8, "PICOLEES").
dico("P", 8, "PICOLENT").
dico("P", 8, "PICOLERA").
dico("P", 8, "PICOLEUR").
dico("P", 8, "PICOLIEZ").
dico("P", 8, "PICOLONS").
dico("P", 8, "PICORAIS").
dico("P", 8, "PICORAIT").
dico("P", 8, "PICORANT").
dico("P", 8, "PICOREES").
dico("P", 8, "PICORENT").
dico("P", 8, "PICORERA").
dico("P", 8, "PICORIEZ").
dico("P", 8, "PICORONS").
dico("P", 8, "PICOSSAI").
dico("P", 8, "PICOSSAS").
dico("P", 8, "PICOSSAT").
dico("P", 8, "PICOSSEE").
dico("P", 8, "PICOSSER").
dico("P", 8, "PICOSSES").
dico("P", 8, "PICOSSEZ").
dico("P", 8, "PICOTAGE").
dico("P", 8, "PICOTAIS").
dico("P", 8, "PICOTAIT").
dico("P", 8, "PICOTANT").
dico("P", 8, "PICOTEES").
dico("P", 8, "PICOTENT").
dico("P", 8, "PICOTERA").
dico("P", 8, "PICOTIEZ").
dico("P", 8, "PICOTINS").
dico("P", 8, "PICOTONS").
dico("P", 8, "PICOULET").
dico("P", 8, "PICPOULS").
dico("P", 8, "PICRATES").
dico("P", 8, "PICRIDES").
dico("P", 8, "PICRIQUE").
dico("P", 8, "PICTURAL").
dico("P", 8, "PICVERTS").
dico("P", 8, "PIECETTE").
dico("P", 8, "PIEDMONT").
dico("P", 8, "PIEDROIT").
dico("P", 8, "PIEFORTS").
dico("P", 8, "PIEGEAGE").
dico("P", 8, "PIEGEAIS").
dico("P", 8, "PIEGEAIT").
dico("P", 8, "PIEGEANT").
dico("P", 8, "PIEGEONS").
dico("P", 8, "PIEGERAI").
dico("P", 8, "PIEGERAS").
dico("P", 8, "PIEGEREZ").
dico("P", 8, "PIEGEURS").
dico("P", 8, "PIEGEUSE").
dico("P", 8, "PIEGIONS").
dico("P", 8, "PIEMONTS").
dico("P", 8, "PIERCAIS").
dico("P", 8, "PIERCAIT").
dico("P", 8, "PIERCANT").
dico("P", 8, "PIERCEES").
dico("P", 8, "PIERCENT").
dico("P", 8, "PIERCERA").
dico("P", 8, "PIERCIEZ").
dico("P", 8, "PIERCING").
dico("P", 8, "PIERCONS").
dico("P", 8, "PIERIDES").
dico("P", 8, "PIERRAGE").
dico("P", 8, "PIERREES").
dico("P", 8, "PIERREUX").
dico("P", 8, "PIERRIER").
dico("P", 8, "PIERROTS").
dico("P", 8, "PIERRURE").
dico("P", 8, "PIETAMES").
dico("P", 8, "PIETASSE").
dico("P", 8, "PIETATES").
dico("P", 8, "PIETERAI").
dico("P", 8, "PIETERAS").
dico("P", 8, "PIETEREZ").
dico("P", 8, "PIETINAI").
dico("P", 8, "PIETINAS").
dico("P", 8, "PIETINAT").
dico("P", 8, "PIETINEE").
dico("P", 8, "PIETINER").
dico("P", 8, "PIETINES").
dico("P", 8, "PIETINEZ").
dico("P", 8, "PIETIONS").
dico("P", 8, "PIETISME").
dico("P", 8, "PIETISTE").
dico("P", 8, "PIETONNE").
dico("P", 8, "PIETRAIN").
dico("P", 8, "PIEUTAIS").
dico("P", 8, "PIEUTAIT").
dico("P", 8, "PIEUTANT").
dico("P", 8, "PIEUTEES").
dico("P", 8, "PIEUTENT").
dico("P", 8, "PIEUTERA").
dico("P", 8, "PIEUTIEZ").
dico("P", 8, "PIEUTONS").
dico("P", 8, "PIEUVRES").
dico("P", 8, "PIFAIENT").
dico("P", 8, "PIFASSES").
dico("P", 8, "PIFERAIS").
dico("P", 8, "PIFERAIT").
dico("P", 8, "PIFERENT").
dico("P", 8, "PIFERIEZ").
dico("P", 8, "PIFERONS").
dico("P", 8, "PIFERONT").
dico("P", 8, "PIFFAMES").
dico("P", 8, "PIFFASSE").
dico("P", 8, "PIFFATES").
dico("P", 8, "PIFFERAI").
dico("P", 8, "PIFFERAS").
dico("P", 8, "PIFFEREZ").
dico("P", 8, "PIFFIONS").
dico("P", 8, "PIGEAMES").
dico("P", 8, "PIGEASSE").
dico("P", 8, "PIGEATES").
dico("P", 8, "PIGEONNA").
dico("P", 8, "PIGEONNE").
dico("P", 8, "PIGERAIS").
dico("P", 8, "PIGERAIT").
dico("P", 8, "PIGERENT").
dico("P", 8, "PIGERIEZ").
dico("P", 8, "PIGERONS").
dico("P", 8, "PIGERONT").
dico("P", 8, "PIGISTES").
dico("P", 8, "PIGMENTA").
dico("P", 8, "PIGMENTE").
dico("P", 8, "PIGMENTS").
dico("P", 8, "PIGNADAS").
dico("P", 8, "PIGNADES").
dico("P", 8, "PIGNOCHA").
dico("P", 8, "PIGNOCHE").
dico("P", 8, "PIGNOUFE").
dico("P", 8, "PIGNOUFS").
dico("P", 8, "PILAIENT").
dico("P", 8, "PILAIRES").
dico("P", 8, "PILASSES").
dico("P", 8, "PILASTRE").
dico("P", 8, "PILCHARD").
dico("P", 8, "PILERAIS").
dico("P", 8, "PILERAIT").
dico("P", 8, "PILERENT").
dico("P", 8, "PILERIEZ").
dico("P", 8, "PILERONS").
dico("P", 8, "PILERONT").
dico("P", 8, "PILEUSES").
dico("P", 8, "PILIFERE").
dico("P", 8, "PILIPINO").
dico("P", 8, "PILLAGES").
dico("P", 8, "PILLAMES").
dico("P", 8, "PILLARDE").
dico("P", 8, "PILLARDS").
dico("P", 8, "PILLASSE").
dico("P", 8, "PILLATES").
dico("P", 8, "PILLERAI").
dico("P", 8, "PILLERAS").
dico("P", 8, "PILLEREZ").
dico("P", 8, "PILLEURS").
dico("P", 8, "PILLEUSE").
dico("P", 8, "PILLIONS").
dico("P", 8, "PILONNAI").
dico("P", 8, "PILONNAS").
dico("P", 8, "PILONNAT").
dico("P", 8, "PILONNEE").
dico("P", 8, "PILONNER").
dico("P", 8, "PILONNES").
dico("P", 8, "PILONNEZ").
dico("P", 8, "PILOSITE").
dico("P", 8, "PILOTAGE").
dico("P", 8, "PILOTAIS").
dico("P", 8, "PILOTAIT").
dico("P", 8, "PILOTANT").
dico("P", 8, "PILOTEES").
dico("P", 8, "PILOTENT").
dico("P", 8, "PILOTERA").
dico("P", 8, "PILOTIEZ").
dico("P", 8, "PILOTINS").
dico("P", 8, "PILOTONS").
dico("P", 8, "PILULIER").
dico("P", 8, "PIMBECHE").
dico("P", 8, "PIMBINAS").
dico("P", 8, "PIMENTAI").
dico("P", 8, "PIMENTAS").
dico("P", 8, "PIMENTAT").
dico("P", 8, "PIMENTEE").
dico("P", 8, "PIMENTER").
dico("P", 8, "PIMENTES").
dico("P", 8, "PIMENTEZ").
dico("P", 8, "PIMPANTE").
dico("P", 8, "PIMPANTS").
dico("P", 8, "PINACEES").
dico("P", 8, "PINACLES").
dico("P", 8, "PINAILLA").
dico("P", 8, "PINAILLE").
dico("P", 8, "PINASSES").
dico("P", 8, "PINASTRE").
dico("P", 8, "PINCAGES").
dico("P", 8, "PINCAMES").
dico("P", 8, "PINCARDE").
dico("P", 8, "PINCARDS").
dico("P", 8, "PINCASSE").
dico("P", 8, "PINCATES").
dico("P", 8, "PINCEAUX").
dico("P", 8, "PINCERAI").
dico("P", 8, "PINCERAS").
dico("P", 8, "PINCEREZ").
dico("P", 8, "PINCETTE").
dico("P", 8, "PINCEURS").
dico("P", 8, "PINCEUSE").
dico("P", 8, "PINCHARD").
dico("P", 8, "PINCIONS").
dico("P", 8, "PINCURES").
dico("P", 8, "PINEALES").
dico("P", 8, "PINERAIE").
dico("P", 8, "PINGOUIN").
dico("P", 8, "PINIERES").
dico("P", 8, "PINNULES").
dico("P", 8, "PINSCHER").
dico("P", 8, "PINTADES").
dico("P", 8, "PINTAMES").
dico("P", 8, "PINTASSE").
dico("P", 8, "PINTATES").
dico("P", 8, "PINTERAI").
dico("P", 8, "PINTERAS").
dico("P", 8, "PINTEREZ").
dico("P", 8, "PINTIONS").
dico("P", 8, "PINTOCHA").
dico("P", 8, "PINTOCHE").
dico("P", 8, "PIOCHAGE").
dico("P", 8, "PIOCHAIS").
dico("P", 8, "PIOCHAIT").
dico("P", 8, "PIOCHANT").
dico("P", 8, "PIOCHEES").
dico("P", 8, "PIOCHENT").
dico("P", 8, "PIOCHERA").
dico("P", 8, "PIOCHEUR").
dico("P", 8, "PIOCHIEZ").
dico("P", 8, "PIOCHONS").
dico("P", 8, "PIONCAIS").
dico("P", 8, "PIONCAIT").
dico("P", 8, "PIONCANT").
dico("P", 8, "PIONCEES").
dico("P", 8, "PIONCENT").
dico("P", 8, "PIONCERA").
dico("P", 8, "PIONCEUR").
dico("P", 8, "PIONCIEZ").
dico("P", 8, "PIONCONS").
dico("P", 8, "PIONNAIS").
dico("P", 8, "PIONNAIT").
dico("P", 8, "PIONNANT").
dico("P", 8, "PIONNENT").
dico("P", 8, "PIONNERA").
dico("P", 8, "PIONNIER").
dico("P", 8, "PIONNIEZ").
dico("P", 8, "PIONNONS").
dico("P", 8, "PIORNAIS").
dico("P", 8, "PIORNAIT").
dico("P", 8, "PIORNANT").
dico("P", 8, "PIORNENT").
dico("P", 8, "PIORNERA").
dico("P", 8, "PIORNIEZ").
dico("P", 8, "PIORNONS").
dico("P", 8, "PIOUPIOU").
dico("P", 8, "PIPAIENT").
dico("P", 8, "PIPASSES").
dico("P", 8, "PIPELETS").
dico("P", 8, "PIPELINE").
dico("P", 8, "PIPERADE").
dico("P", 8, "PIPERAIS").
dico("P", 8, "PIPERAIT").
dico("P", 8, "PIPERENT").
dico("P", 8, "PIPERIES").
dico("P", 8, "PIPERIEZ").
dico("P", 8, "PIPERINE").
dico("P", 8, "PIPERINS").
dico("P", 8, "PIPERONS").
dico("P", 8, "PIPERONT").
dico("P", 8, "PIPETTES").
dico("P", 8, "PIPEUSES").
dico("P", 8, "PIPIERES").
dico("P", 8, "PIQUAGES").
dico("P", 8, "PIQUAMES").
dico("P", 8, "PIQUANTE").
dico("P", 8, "PIQUANTS").
dico("P", 8, "PIQUASSE").
dico("P", 8, "PIQUATES").
dico("P", 8, "PIQUERAI").
dico("P", 8, "PIQUERAS").
dico("P", 8, "PIQUEREZ").
dico("P", 8, "PIQUERIE").
dico("P", 8, "PIQUETAI").
dico("P", 8, "PIQUETAS").
dico("P", 8, "PIQUETAT").
dico("P", 8, "PIQUETEE").
dico("P", 8, "PIQUETER").
dico("P", 8, "PIQUETES").
dico("P", 8, "PIQUETEZ").
dico("P", 8, "PIQUETTE").
dico("P", 8, "PIQUEURS").
dico("P", 8, "PIQUEUSE").
dico("P", 8, "PIQUIERS").
dico("P", 8, "PIQUIONS").
dico("P", 8, "PIQUOIRS").
dico("P", 8, "PIRANHAS").
dico("P", 8, "PIRATAGE").
dico("P", 8, "PIRATAIS").
dico("P", 8, "PIRATAIT").
dico("P", 8, "PIRATANT").
dico("P", 8, "PIRATEES").
dico("P", 8, "PIRATENT").
dico("P", 8, "PIRATERA").
dico("P", 8, "PIRATIEZ").
dico("P", 8, "PIRATONS").
dico("P", 8, "PIROGUES").
dico("P", 8, "PIROJKIS").
dico("P", 8, "PIROJOKS").
dico("P", 8, "PISCINES").
dico("P", 8, "PISOLITE").
dico("P", 8, "PISSAMES").
dico("P", 8, "PISSASSE").
dico("P", 8, "PISSATES").
dico("P", 8, "PISSERAI").
dico("P", 8, "PISSERAS").
dico("P", 8, "PISSEREZ").
dico("P", 8, "PISSETTE").
dico("P", 8, "PISSEURS").
dico("P", 8, "PISSEUSE").
dico("P", 8, "PISSIONS").
dico("P", 8, "PISSOIRS").
dico("P", 8, "PISSOTAI").
dico("P", 8, "PISSOTAS").
dico("P", 8, "PISSOTAT").
dico("P", 8, "PISSOTER").
dico("P", 8, "PISSOTES").
dico("P", 8, "PISSOTEZ").
dico("P", 8, "PISTACHE").
dico("P", 8, "PISTAGES").
dico("P", 8, "PISTAMES").
dico("P", 8, "PISTARDE").
dico("P", 8, "PISTARDS").
dico("P", 8, "PISTASSE").
dico("P", 8, "PISTATES").
dico("P", 8, "PISTERAI").
dico("P", 8, "PISTERAS").
dico("P", 8, "PISTEREZ").
dico("P", 8, "PISTEURS").
dico("P", 8, "PISTEUSE").
dico("P", 8, "PISTIONS").
dico("P", 8, "PISTOLAI").
dico("P", 8, "PISTOLAS").
dico("P", 8, "PISTOLAT").
dico("P", 8, "PISTOLEE").
dico("P", 8, "PISTOLER").
dico("P", 8, "PISTOLES").
dico("P", 8, "PISTOLET").
dico("P", 8, "PISTOLEZ").
dico("P", 8, "PISTONNA").
dico("P", 8, "PISTONNE").
dico("P", 8, "PITANCES").
dico("P", 8, "PITBULLS").
dico("P", 8, "PITCHOUN").
dico("P", 8, "PITCHPIN").
dico("P", 8, "PITEUSES").
dico("P", 8, "PITONNAI").
dico("P", 8, "PITONNAS").
dico("P", 8, "PITONNAT").
dico("P", 8, "PITONNEE").
dico("P", 8, "PITONNER").
dico("P", 8, "PITONNES").
dico("P", 8, "PITONNEZ").
dico("P", 8, "PITOUNES").
dico("P", 8, "PITRERIE").
dico("P", 8, "PITUITAI").
dico("P", 8, "PITUITAS").
dico("P", 8, "PITUITAT").
dico("P", 8, "PITUITER").
dico("P", 8, "PITUITES").
dico("P", 8, "PITUITEZ").
dico("P", 8, "PIVOINES").
dico("P", 8, "PIVOTAIS").
dico("P", 8, "PIVOTAIT").
dico("P", 8, "PIVOTANT").
dico("P", 8, "PIVOTEES").
dico("P", 8, "PIVOTENT").
dico("P", 8, "PIVOTERA").
dico("P", 8, "PIVOTIEZ").
dico("P", 8, "PIVOTONS").
dico("P", 8, "PIZZERIA").
dico("P", 8, "PLACABLE").
dico("P", 8, "PLACAGES").
dico("P", 8, "PLACAMES").
dico("P", 8, "PLACARDA").
dico("P", 8, "PLACARDE").
dico("P", 8, "PLACARDS").
dico("P", 8, "PLACASSE").
dico("P", 8, "PLACATES").
dico("P", 8, "PLACEAUX").
dico("P", 8, "PLACEBOS").
dico("P", 8, "PLACENTA").
dico("P", 8, "PLACERAI").
dico("P", 8, "PLACERAS").
dico("P", 8, "PLACEREZ").
dico("P", 8, "PLACETTE").
dico("P", 8, "PLACEURS").
dico("P", 8, "PLACEUSE").
dico("P", 8, "PLACIDES").
dico("P", 8, "PLACIERE").
dico("P", 8, "PLACIERS").
dico("P", 8, "PLACIONS").
dico("P", 8, "PLACOTAI").
dico("P", 8, "PLACOTAS").
dico("P", 8, "PLACOTAT").
dico("P", 8, "PLACOTEE").
dico("P", 8, "PLACOTER").
dico("P", 8, "PLACOTES").
dico("P", 8, "PLACOTEZ").
dico("P", 8, "PLACURES").
dico("P", 8, "PLAFONDS").
dico("P", 8, "PLAFONNA").
dico("P", 8, "PLAFONNE").
dico("P", 8, "PLAGALES").
dico("P", 8, "PLAGIAIS").
dico("P", 8, "PLAGIAIT").
dico("P", 8, "PLAGIANT").
dico("P", 8, "PLAGIATS").
dico("P", 8, "PLAGIEES").
dico("P", 8, "PLAGIENT").
dico("P", 8, "PLAGIERA").
dico("P", 8, "PLAGIIEZ").
dico("P", 8, "PLAGIONS").
dico("P", 8, "PLAGISTE").
dico("P", 8, "PLAIDAIS").
dico("P", 8, "PLAIDAIT").
dico("P", 8, "PLAIDANT").
dico("P", 8, "PLAIDEES").
dico("P", 8, "PLAIDENT").
dico("P", 8, "PLAIDERA").
dico("P", 8, "PLAIDEUR").
dico("P", 8, "PLAIDIEZ").
dico("P", 8, "PLAIDONS").
dico("P", 8, "PLAIGNES").
dico("P", 8, "PLAIGNEZ").
dico("P", 8, "PLAIGNIS").
dico("P", 8, "PLAIGNIT").
dico("P", 8, "PLAINDRA").
dico("P", 8, "PLAINDRE").
dico("P", 8, "PLAINTES").
dico("P", 8, "PLAINTIF").
dico("P", 8, "PLAIRAIS").
dico("P", 8, "PLAIRAIT").
dico("P", 8, "PLAIRIEZ").
dico("P", 8, "PLAIRONS").
dico("P", 8, "PLAIRONT").
dico("P", 8, "PLAISAIS").
dico("P", 8, "PLAISAIT").
dico("P", 8, "PLAISANT").
dico("P", 8, "PLAISENT").
dico("P", 8, "PLAISIEZ").
dico("P", 8, "PLAISIRS").
dico("P", 8, "PLAISONS").
dico("P", 8, "PLANAGES").
dico("P", 8, "PLANAIRE").
dico("P", 8, "PLANAMES").
dico("P", 8, "PLANANTE").
dico("P", 8, "PLANANTS").
dico("P", 8, "PLANASSE").
dico("P", 8, "PLANATES").
dico("P", 8, "PLANCHAI").
dico("P", 8, "PLANCHAS").
dico("P", 8, "PLANCHAT").
dico("P", 8, "PLANCHER").
dico("P", 8, "PLANCHES").
dico("P", 8, "PLANCHEZ").
dico("P", 8, "PLANCONS").
dico("P", 8, "PLANCTON").
dico("P", 8, "PLANEITE").
dico("P", 8, "PLANELLE").
dico("P", 8, "PLANERAI").
dico("P", 8, "PLANERAS").
dico("P", 8, "PLANEREZ").
dico("P", 8, "PLANETES").
dico("P", 8, "PLANEURS").
dico("P", 8, "PLANEUSE").
dico("P", 8, "PLANEZES").
dico("P", 8, "PLANIFIA").
dico("P", 8, "PLANIFIE").
dico("P", 8, "PLANIONS").
dico("P", 8, "PLANISME").
dico("P", 8, "PLANISTE").
dico("P", 8, "PLANNING").
dico("P", 8, "PLANOIRS").
dico("P", 8, "PLANORBE").
dico("P", 8, "PLANQUAI").
dico("P", 8, "PLANQUAS").
dico("P", 8, "PLANQUAT").
dico("P", 8, "PLANQUEE").
dico("P", 8, "PLANQUER").
dico("P", 8, "PLANQUES").
dico("P", 8, "PLANQUEZ").
dico("P", 8, "PLANTAGE").
dico("P", 8, "PLANTAIN").
dico("P", 8, "PLANTAIS").
dico("P", 8, "PLANTAIT").
dico("P", 8, "PLANTANT").
dico("P", 8, "PLANTARD").
dico("P", 8, "PLANTEES").
dico("P", 8, "PLANTENT").
dico("P", 8, "PLANTERA").
dico("P", 8, "PLANTEUR").
dico("P", 8, "PLANTIEZ").
dico("P", 8, "PLANTOIR").
dico("P", 8, "PLANTONS").
dico("P", 8, "PLANTULE").
dico("P", 8, "PLAQUAGE").
dico("P", 8, "PLAQUAIS").
dico("P", 8, "PLAQUAIT").
dico("P", 8, "PLAQUANT").
dico("P", 8, "PLAQUEES").
dico("P", 8, "PLAQUENT").
dico("P", 8, "PLAQUERA").
dico("P", 8, "PLAQUEUR").
dico("P", 8, "PLAQUIEZ").
dico("P", 8, "PLAQUONS").
dico("P", 8, "PLASMIDE").
dico("P", 8, "PLASMINE").
dico("P", 8, "PLASMODE").
dico("P", 8, "PLASTICS").
dico("P", 8, "PLASTIES").
dico("P", 8, "PLASTRON").
dico("P", 8, "PLATANES").
dico("P", 8, "PLATEAUX").
dico("P", 8, "PLATERIE").
dico("P", 8, "PLATEURE").
dico("P", 8, "PLATIERE").
dico("P", 8, "PLATIERS").
dico("P", 8, "PLATINAI").
dico("P", 8, "PLATINAS").
dico("P", 8, "PLATINAT").
dico("P", 8, "PLATINEE").
dico("P", 8, "PLATINER").
dico("P", 8, "PLATINES").
dico("P", 8, "PLATINEZ").
dico("P", 8, "PLATODES").
dico("P", 8, "PLATRAGE").
dico("P", 8, "PLATRAIS").
dico("P", 8, "PLATRAIT").
dico("P", 8, "PLATRANT").
dico("P", 8, "PLATREES").
dico("P", 8, "PLATRENT").
dico("P", 8, "PLATRERA").
dico("P", 8, "PLATREUX").
dico("P", 8, "PLATRIER").
dico("P", 8, "PLATRIEZ").
dico("P", 8, "PLATRONS").
dico("P", 8, "PLAYMATE").
dico("P", 8, "PLEBAINS").
dico("P", 8, "PLEBEIEN").
dico("P", 8, "PLECTRES").
dico("P", 8, "PLEIADES").
dico("P", 8, "PLENIERE").
dico("P", 8, "PLENIERS").
dico("P", 8, "PLETHORE").
dico("P", 8, "PLEURAGE").
dico("P", 8, "PLEURAIS").
dico("P", 8, "PLEURAIT").
dico("P", 8, "PLEURALE").
dico("P", 8, "PLEURANT").
dico("P", 8, "PLEURARD").
dico("P", 8, "PLEURAUX").
dico("P", 8, "PLEUREES").
dico("P", 8, "PLEURENT").
dico("P", 8, "PLEURERA").
dico("P", 8, "PLEUREUR").
dico("P", 8, "PLEURIEZ").
dico("P", 8, "PLEURITE").
dico("P", 8, "PLEURONS").
dico("P", 8, "PLEUROTE").
dico("P", 8, "PLEUTRES").
dico("P", 8, "PLEUVAIT").
dico("P", 8, "PLEUVANT").
dico("P", 8, "PLEUVENT").
dico("P", 8, "PLEUVINA").
dico("P", 8, "PLEUVINE").
dico("P", 8, "PLEUVOIR").
dico("P", 8, "PLEUVOTA").
dico("P", 8, "PLEUVOTE").
dico("P", 8, "PLIABLES").
dico("P", 8, "PLIAIENT").
dico("P", 8, "PLIANTES").
dico("P", 8, "PLIASSES").
dico("P", 8, "PLIEMENT").
dico("P", 8, "PLIERAIS").
dico("P", 8, "PLIERAIT").
dico("P", 8, "PLIERENT").
dico("P", 8, "PLIERIEZ").
dico("P", 8, "PLIERONS").
dico("P", 8, "PLIERONT").
dico("P", 8, "PLIEUSES").
dico("P", 8, "PLINTHES").
dico("P", 8, "PLIOCENE").
dico("P", 8, "PLISSAGE").
dico("P", 8, "PLISSAIS").
dico("P", 8, "PLISSAIT").
dico("P", 8, "PLISSANT").
dico("P", 8, "PLISSEES").
dico("P", 8, "PLISSENT").
dico("P", 8, "PLISSERA").
dico("P", 8, "PLISSEUR").
dico("P", 8, "PLISSIEZ").
dico("P", 8, "PLISSONS").
dico("P", 8, "PLISSURE").
dico("P", 8, "PLOCEIDE").
dico("P", 8, "PLOIERAI").
dico("P", 8, "PLOIERAS").
dico("P", 8, "PLOIEREZ").
dico("P", 8, "PLOMBAGE").
dico("P", 8, "PLOMBAIS").
dico("P", 8, "PLOMBAIT").
dico("P", 8, "PLOMBANT").
dico("P", 8, "PLOMBEES").
dico("P", 8, "PLOMBENT").
dico("P", 8, "PLOMBERA").
dico("P", 8, "PLOMBEUR").
dico("P", 8, "PLOMBEUX").
dico("P", 8, "PLOMBIER").
dico("P", 8, "PLOMBIEZ").
dico("P", 8, "PLOMBOIR").
dico("P", 8, "PLOMBONS").
dico("P", 8, "PLOMBURE").
dico("P", 8, "PLOMMEES").
dico("P", 8, "PLONGEAI").
dico("P", 8, "PLONGEAS").
dico("P", 8, "PLONGEAT").
dico("P", 8, "PLONGEES").
dico("P", 8, "PLONGENT").
dico("P", 8, "PLONGEON").
dico("P", 8, "PLONGERA").
dico("P", 8, "PLONGEUR").
dico("P", 8, "PLONGIEZ").
dico("P", 8, "PLOYABLE").
dico("P", 8, "PLOYAGES").
dico("P", 8, "PLOYAMES").
dico("P", 8, "PLOYASSE").
dico("P", 8, "PLOYATES").
dico("P", 8, "PLOYIONS").
dico("P", 8, "PLUCHAIS").
dico("P", 8, "PLUCHAIT").
dico("P", 8, "PLUCHANT").
dico("P", 8, "PLUCHEES").
dico("P", 8, "PLUCHENT").
dico("P", 8, "PLUCHERA").
dico("P", 8, "PLUCHEUX").
dico("P", 8, "PLUCHIEZ").
dico("P", 8, "PLUCHONS").
dico("P", 8, "PLUMAGES").
dico("P", 8, "PLUMAMES").
dico("P", 8, "PLUMARDS").
dico("P", 8, "PLUMASSE").
dico("P", 8, "PLUMATES").
dico("P", 8, "PLUMEAUX").
dico("P", 8, "PLUMERAI").
dico("P", 8, "PLUMERAS").
dico("P", 8, "PLUMEREZ").
dico("P", 8, "PLUMETEE").
dico("P", 8, "PLUMETES").
dico("P", 8, "PLUMETIS").
dico("P", 8, "PLUMETTE").
dico("P", 8, "PLUMEURS").
dico("P", 8, "PLUMEUSE").
dico("P", 8, "PLUMIERS").
dico("P", 8, "PLUMIONS").
dico("P", 8, "PLUMITIF").
dico("P", 8, "PLUMULES").
dico("P", 8, "PLURALES").
dico("P", 8, "PLURIELS").
dico("P", 8, "PLUSSENT").
dico("P", 8, "PLUSSIEZ").
dico("P", 8, "PLUVIALE").
dico("P", 8, "PLUVIANS").
dico("P", 8, "PLUVIAUX").
dico("P", 8, "PLUVIERS").
dico("P", 8, "PLUVIEUX").
dico("P", 8, "PLUVINAT").
dico("P", 8, "PLUVINER").
dico("P", 8, "PLUVIOSE").
dico("P", 8, "POCHADES").
dico("P", 8, "POCHAGES").
dico("P", 8, "POCHAMES").
dico("P", 8, "POCHARDA").
dico("P", 8, "POCHARDE").
dico("P", 8, "POCHARDS").
dico("P", 8, "POCHASSE").
dico("P", 8, "POCHATES").
dico("P", 8, "POCHERAI").
dico("P", 8, "POCHERAS").
dico("P", 8, "POCHEREZ").
dico("P", 8, "POCHETEE").
dico("P", 8, "POCHETTE").
dico("P", 8, "POCHEUSE").
dico("P", 8, "POCHIONS").
dico("P", 8, "POCHOIRS").
dico("P", 8, "POCHOUSE").
dico("P", 8, "PODAGRES").
dico("P", 8, "PODAIRES").
dico("P", 8, "PODESTAT").
dico("P", 8, "PODIATRE").
dico("P", 8, "POECILES").
dico("P", 8, "POELAGES").
dico("P", 8, "POELAMES").
dico("P", 8, "POELASSE").
dico("P", 8, "POELATES").
dico("P", 8, "POELERAI").
dico("P", 8, "POELERAS").
dico("P", 8, "POELEREZ").
dico("P", 8, "POELERIE").
dico("P", 8, "POELIERE").
dico("P", 8, "POELIERS").
dico("P", 8, "POELIONS").
dico("P", 8, "POETESSE").
dico("P", 8, "POETIQUE").
dico("P", 8, "POETISAI").
dico("P", 8, "POETISAS").
dico("P", 8, "POETISAT").
dico("P", 8, "POETISEE").
dico("P", 8, "POETISER").
dico("P", 8, "POETISES").
dico("P", 8, "POETISEZ").
dico("P", 8, "POGROMES").
dico("P", 8, "POIGNAIS").
dico("P", 8, "POIGNAIT").
dico("P", 8, "POIGNANT").
dico("P", 8, "POIGNARD").
dico("P", 8, "POIGNEES").
dico("P", 8, "POIGNENT").
dico("P", 8, "POIGNERA").
dico("P", 8, "POIGNETS").
dico("P", 8, "POIGNIEZ").
dico("P", 8, "POIGNONS").
dico("P", 8, "POILAMES").
dico("P", 8, "POILANTE").
dico("P", 8, "POILANTS").
dico("P", 8, "POILASSE").
dico("P", 8, "POILATES").
dico("P", 8, "POILERAI").
dico("P", 8, "POILERAS").
dico("P", 8, "POILEREZ").
dico("P", 8, "POILIONS").
dico("P", 8, "POINCONS").
dico("P", 8, "POINDRAI").
dico("P", 8, "POINDRAS").
dico("P", 8, "POINDREZ").
dico("P", 8, "POINTAGE").
dico("P", 8, "POINTAIS").
dico("P", 8, "POINTAIT").
dico("P", 8, "POINTANT").
dico("P", 8, "POINTAUX").
dico("P", 8, "POINTEAU").
dico("P", 8, "POINTEES").
dico("P", 8, "POINTENT").
dico("P", 8, "POINTERA").
dico("P", 8, "POINTERS").
dico("P", 8, "POINTEUR").
dico("P", 8, "POINTIEZ").
dico("P", 8, "POINTILS").
dico("P", 8, "POINTOIS").
dico("P", 8, "POINTONS").
dico("P", 8, "POINTUES").
dico("P", 8, "POINTURE").
dico("P", 8, "POIREAUX").
dico("P", 8, "POIRIERS").
dico("P", 8, "POIROTAI").
dico("P", 8, "POIROTAS").
dico("P", 8, "POIROTAT").
dico("P", 8, "POIROTER").
dico("P", 8, "POIROTES").
dico("P", 8, "POIROTEZ").
dico("P", 8, "POISSAIS").
dico("P", 8, "POISSAIT").
dico("P", 8, "POISSANT").
dico("P", 8, "POISSARD").
dico("P", 8, "POISSEES").
dico("P", 8, "POISSENT").
dico("P", 8, "POISSERA").
dico("P", 8, "POISSEUX").
dico("P", 8, "POISSIEZ").
dico("P", 8, "POISSONS").
dico("P", 8, "POITEVIN").
dico("P", 8, "POITRAIL").
dico("P", 8, "POITRINE").
dico("P", 8, "POIVRADE").
dico("P", 8, "POIVRAIS").
dico("P", 8, "POIVRAIT").
dico("P", 8, "POIVRANT").
dico("P", 8, "POIVREES").
dico("P", 8, "POIVRENT").
dico("P", 8, "POIVRERA").
dico("P", 8, "POIVRIER").
dico("P", 8, "POIVRIEZ").
dico("P", 8, "POIVRONS").
dico("P", 8, "POIVROTE").
dico("P", 8, "POIVROTS").
dico("P", 8, "POLACRES").
dico("P", 8, "POLAIRES").
dico("P", 8, "POLAQUES").
dico("P", 8, "POLARDES").
dico("P", 8, "POLARISA").
dico("P", 8, "POLARISE").
dico("P", 8, "POLARITE").
dico("P", 8, "POLAROID").
dico("P", 8, "POLENTAS").
dico("P", 8, "POLICAIS").
dico("P", 8, "POLICAIT").
dico("P", 8, "POLICANT").
dico("P", 8, "POLICEES").
dico("P", 8, "POLICENT").
dico("P", 8, "POLICERA").
dico("P", 8, "POLICIER").
dico("P", 8, "POLICIEZ").
dico("P", 8, "POLICONS").
dico("P", 8, "POLIMENT").
dico("P", 8, "POLIRAIS").
dico("P", 8, "POLIRAIT").
dico("P", 8, "POLIRENT").
dico("P", 8, "POLIRIEZ").
dico("P", 8, "POLIRONS").
dico("P", 8, "POLIRONT").
dico("P", 8, "POLISSES").
dico("P", 8, "POLISSEZ").
dico("P", 8, "POLISSON").
dico("P", 8, "POLISTES").
dico("P", 8, "POLITISA").
dico("P", 8, "POLITISE").
dico("P", 8, "POLLINIE").
dico("P", 8, "POLLUAIS").
dico("P", 8, "POLLUAIT").
dico("P", 8, "POLLUANT").
dico("P", 8, "POLLUEES").
dico("P", 8, "POLLUENT").
dico("P", 8, "POLLUERA").
dico("P", 8, "POLLUEUR").
dico("P", 8, "POLLUIEZ").
dico("P", 8, "POLLUONS").
dico("P", 8, "POLOCHON").
dico("P", 8, "POLOISTE").
dico("P", 8, "POLONAIS").
dico("P", 8, "POLONIUM").
dico("P", 8, "POLTRONS").
dico("P", 8, "POLYEDRE").
dico("P", 8, "POLYGALA").
dico("P", 8, "POLYGALE").
dico("P", 8, "POLYGAME").
dico("P", 8, "POLYGONE").
dico("P", 8, "POLYLOBE").
dico("P", 8, "POLYMERE").
dico("P", 8, "POLYNOME").
dico("P", 8, "POLYPEUX").
dico("P", 8, "POLYPIER").
dico("P", 8, "POLYPNEE").
dico("P", 8, "POLYPODE").
dico("P", 8, "POLYPORE").
dico("P", 8, "POLYSOCS").
dico("P", 8, "POLYSOME").
dico("P", 8, "POLYTRIC").
dico("P", 8, "POLYURIE").
dico("P", 8, "POMERIUM").
dico("P", 8, "POMEROLS").
dico("P", 8, "POMMADAI").
dico("P", 8, "POMMADAS").
dico("P", 8, "POMMADAT").
dico("P", 8, "POMMADEE").
dico("P", 8, "POMMADER").
dico("P", 8, "POMMADES").
dico("P", 8, "POMMADEZ").
dico("P", 8, "POMMAMES").
dico("P", 8, "POMMARDS").
dico("P", 8, "POMMASSE").
dico("P", 8, "POMMATES").
dico("P", 8, "POMMEAUX").
dico("P", 8, "POMMELAI").
dico("P", 8, "POMMELAS").
dico("P", 8, "POMMELAT").
dico("P", 8, "POMMELEE").
dico("P", 8, "POMMELER").
dico("P", 8, "POMMELES").
dico("P", 8, "POMMELEZ").
dico("P", 8, "POMMELLE").
dico("P", 8, "POMMERAI").
dico("P", 8, "POMMERAS").
dico("P", 8, "POMMEREZ").
dico("P", 8, "POMMETEE").
dico("P", 8, "POMMETES").
dico("P", 8, "POMMETTE").
dico("P", 8, "POMMIERS").
dico("P", 8, "POMMIONS").
dico("P", 8, "POMPAGES").
dico("P", 8, "POMPAMES").
dico("P", 8, "POMPASSE").
dico("P", 8, "POMPATES").
dico("P", 8, "POMPEIEN").
dico("P", 8, "POMPERAI").
dico("P", 8, "POMPERAS").
dico("P", 8, "POMPEREZ").
dico("P", 8, "POMPETTE").
dico("P", 8, "POMPEURS").
dico("P", 8, "POMPEUSE").
dico("P", 8, "POMPIERE").
dico("P", 8, "POMPIERS").
dico("P", 8, "POMPILES").
dico("P", 8, "POMPIONS").
dico("P", 8, "POMPISTE").
dico("P", 8, "POMPONNA").
dico("P", 8, "POMPONNE").
dico("P", 8, "PONCAGES").
dico("P", 8, "PONCAMES").
dico("P", 8, "PONCASSE").
dico("P", 8, "PONCATES").
dico("P", 8, "PONCEAUX").
dico("P", 8, "PONCELET").
dico("P", 8, "PONCERAI").
dico("P", 8, "PONCERAS").
dico("P", 8, "PONCEREZ").
dico("P", 8, "PONCEURS").
dico("P", 8, "PONCEUSE").
dico("P", 8, "PONCIONS").
dico("P", 8, "PONCTION").
dico("P", 8, "PONCTUAI").
dico("P", 8, "PONCTUAS").
dico("P", 8, "PONCTUAT").
dico("P", 8, "PONCTUEE").
dico("P", 8, "PONCTUEL").
dico("P", 8, "PONCTUER").
dico("P", 8, "PONCTUES").
dico("P", 8, "PONCTUEZ").
dico("P", 8, "PONDERAI").
dico("P", 8, "PONDERAL").
dico("P", 8, "PONDERAS").
dico("P", 8, "PONDERAT").
dico("P", 8, "PONDEREE").
dico("P", 8, "PONDERER").
dico("P", 8, "PONDERES").
dico("P", 8, "PONDEREZ").
dico("P", 8, "PONDEURS").
dico("P", 8, "PONDEUSE").
dico("P", 8, "PONDIMES").
dico("P", 8, "PONDIONS").
dico("P", 8, "PONDISSE").
dico("P", 8, "PONDITES").
dico("P", 8, "PONDOIRS").
dico("P", 8, "PONDRAIS").
dico("P", 8, "PONDRAIT").
dico("P", 8, "PONDRIEZ").
dico("P", 8, "PONDRONS").
dico("P", 8, "PONDRONT").
dico("P", 8, "PONETTES").
dico("P", 8, "PONGIDES").
dico("P", 8, "PONGISTE").
dico("P", 8, "PONTAGES").
dico("P", 8, "PONTAMES").
dico("P", 8, "PONTASSE").
dico("P", 8, "PONTATES").
dico("P", 8, "PONTERAI").
dico("P", 8, "PONTERAS").
dico("P", 8, "PONTEREZ").
dico("P", 8, "PONTIERE").
dico("P", 8, "PONTIERS").
dico("P", 8, "PONTIFES").
dico("P", 8, "PONTIFIA").
dico("P", 8, "PONTIFIE").
dico("P", 8, "PONTIONS").
dico("P", 8, "POPELINE").
dico("P", 8, "POPINEES").
dico("P", 8, "POPLITEE").
dico("P", 8, "POPLITES").
dico("P", 8, "POPOTINS").
dico("P", 8, "POPULACE").
dico("P", 8, "POPULAGE").
dico("P", 8, "POPULEUM").
dico("P", 8, "POPULEUX").
dico("P", 8, "POQUAMES").
dico("P", 8, "POQUASSE").
dico("P", 8, "POQUATES").
dico("P", 8, "POQUERAI").
dico("P", 8, "POQUERAS").
dico("P", 8, "POQUEREZ").
dico("P", 8, "POQUIONS").
dico("P", 8, "PORACEES").
dico("P", 8, "PORCELET").
dico("P", 8, "PORCHERE").
dico("P", 8, "PORCHERS").
dico("P", 8, "PORCINES").
dico("P", 8, "POREUSES").
dico("P", 8, "POROSITE").
dico("P", 8, "PORPHYRA").
dico("P", 8, "PORPHYRE").
dico("P", 8, "PORRACEE").
dico("P", 8, "PORRACES").
dico("P", 8, "PORREAUX").
dico("P", 8, "PORRIDGE").
dico("P", 8, "PORTABLE").
dico("P", 8, "PORTAGEA").
dico("P", 8, "PORTAGEE").
dico("P", 8, "PORTAGER").
dico("P", 8, "PORTAGES").
dico("P", 8, "PORTAGEZ").
dico("P", 8, "PORTAILS").
dico("P", 8, "PORTALES").
dico("P", 8, "PORTAMES").
dico("P", 8, "PORTANCE").
dico("P", 8, "PORTANTE").
dico("P", 8, "PORTANTS").
dico("P", 8, "PORTASSE").
dico("P", 8, "PORTATES").
dico("P", 8, "PORTATIF").
dico("P", 8, "PORTERAI").
dico("P", 8, "PORTERAS").
dico("P", 8, "PORTEREZ").
dico("P", 8, "PORTERIE").
dico("P", 8, "PORTEURS").
dico("P", 8, "PORTEUSE").
dico("P", 8, "PORTIERE").
dico("P", 8, "PORTIERS").
dico("P", 8, "PORTIONS").
dico("P", 8, "PORTIQUE").
dico("P", 8, "PORTLAND").
dico("P", 8, "PORTRAIT").
dico("P", 8, "PORTULAN").
dico("P", 8, "PORTUNES").
dico("P", 8, "POSAIENT").
dico("P", 8, "POSASSES").
dico("P", 8, "POSEMENT").
dico("P", 8, "POSERAIS").
dico("P", 8, "POSERAIT").
dico("P", 8, "POSERENT").
dico("P", 8, "POSERIEZ").
dico("P", 8, "POSERONS").
dico("P", 8, "POSERONT").
dico("P", 8, "POSEUSES").
dico("P", 8, "POSITIFS").
dico("P", 8, "POSITION").
dico("P", 8, "POSITIVA").
dico("P", 8, "POSITIVE").
dico("P", 8, "POSITONS").
dico("P", 8, "POSITRON").
dico("P", 8, "POSSEDAI").
dico("P", 8, "POSSEDAS").
dico("P", 8, "POSSEDAT").
dico("P", 8, "POSSEDEE").
dico("P", 8, "POSSEDER").
dico("P", 8, "POSSEDES").
dico("P", 8, "POSSEDEZ").
dico("P", 8, "POSSIBLE").
dico("P", 8, "POSTAGES").
dico("P", 8, "POSTALES").
dico("P", 8, "POSTAMES").
dico("P", 8, "POSTASSE").
dico("P", 8, "POSTATES").
dico("P", 8, "POSTCURE").
dico("P", 8, "POSTDATA").
dico("P", 8, "POSTDATE").
dico("P", 8, "POSTERAI").
dico("P", 8, "POSTERAS").
dico("P", 8, "POSTEREZ").
dico("P", 8, "POSTFACA").
dico("P", 8, "POSTFACE").
dico("P", 8, "POSTHITE").
dico("P", 8, "POSTHUME").
dico("P", 8, "POSTICHE").
dico("P", 8, "POSTIERE").
dico("P", 8, "POSTIERS").
dico("P", 8, "POSTIONS").
dico("P", 8, "POSTLUDE").
dico("P", 8, "POSTPOSA").
dico("P", 8, "POSTPOSE").
dico("P", 8, "POSTULAI").
dico("P", 8, "POSTULAS").
dico("P", 8, "POSTULAT").
dico("P", 8, "POSTULEE").
dico("P", 8, "POSTULER").
dico("P", 8, "POSTULES").
dico("P", 8, "POSTULEZ").
dico("P", 8, "POSTURAL").
dico("P", 8, "POSTURES").
dico("P", 8, "POTABLES").
dico("P", 8, "POTACHES").
dico("P", 8, "POTAGERE").
dico("P", 8, "POTAGERS").
dico("P", 8, "POTAMOTS").
dico("P", 8, "POTASSAI").
dico("P", 8, "POTASSAS").
dico("P", 8, "POTASSAT").
dico("P", 8, "POTASSEE").
dico("P", 8, "POTASSER").
dico("P", 8, "POTASSES").
dico("P", 8, "POTASSEZ").
dico("P", 8, "POTELEES").
dico("P", 8, "POTELETS").
dico("P", 8, "POTELLES").
dico("P", 8, "POTENCEE").
dico("P", 8, "POTENCES").
dico("P", 8, "POTENTAT").
dico("P", 8, "POTERIES").
dico("P", 8, "POTERNES").
dico("P", 8, "POTICHES").
dico("P", 8, "POTIERES").
dico("P", 8, "POTINAIS").
dico("P", 8, "POTINAIT").
dico("P", 8, "POTINANT").
dico("P", 8, "POTINENT").
dico("P", 8, "POTINERA").
dico("P", 8, "POTINIER").
dico("P", 8, "POTINIEZ").
dico("P", 8, "POTINONS").
dico("P", 8, "POTIQUET").
dico("P", 8, "POTIRONS").
dico("P", 8, "POTLATCH").
dico("P", 8, "POTOROUS").
dico("P", 8, "POTTOCKS").
dico("P", 8, "POUACRES").
dico("P", 8, "POUBELLE").
dico("P", 8, "POUCAMES").
dico("P", 8, "POUCASSE").
dico("P", 8, "POUCATES").
dico("P", 8, "POUCERAI").
dico("P", 8, "POUCERAS").
dico("P", 8, "POUCEREZ").
dico("P", 8, "POUCEURS").
dico("P", 8, "POUCEUSE").
dico("P", 8, "POUCIERS").
dico("P", 8, "POUCIONS").
dico("P", 8, "POUDINGS").
dico("P", 8, "POUDRAGE").
dico("P", 8, "POUDRAIS").
dico("P", 8, "POUDRAIT").
dico("P", 8, "POUDRANT").
dico("P", 8, "POUDREES").
dico("P", 8, "POUDRENT").
dico("P", 8, "POUDRERA").
dico("P", 8, "POUDREUX").
dico("P", 8, "POUDRIER").
dico("P", 8, "POUDRIEZ").
dico("P", 8, "POUDRINS").
dico("P", 8, "POUDROIE").
dico("P", 8, "POUDRONS").
dico("P", 8, "POUDROYA").
dico("P", 8, "POUDROYE").
dico("P", 8, "POUFFAIS").
dico("P", 8, "POUFFAIT").
dico("P", 8, "POUFFANT").
dico("P", 8, "POUFFENT").
dico("P", 8, "POUFFERA").
dico("P", 8, "POUFFIEZ").
dico("P", 8, "POUFFONS").
dico("P", 8, "POUGNAIS").
dico("P", 8, "POUGNAIT").
dico("P", 8, "POUGNANT").
dico("P", 8, "POUGNENT").
dico("P", 8, "POUGNERA").
dico("P", 8, "POUGNIEZ").
dico("P", 8, "POUGNONS").
dico("P", 8, "POUILLES").
dico("P", 8, "POUILLOT").
dico("P", 8, "POUILLYS").
dico("P", 8, "POULAGAS").
dico("P", 8, "POULAINE").
dico("P", 8, "POULAINS").
dico("P", 8, "POULAMON").
dico("P", 8, "POULARDE").
dico("P", 8, "POULARDS").
dico("P", 8, "POULBOTS").
dico("P", 8, "POULETTE").
dico("P", 8, "POULICHE").
dico("P", 8, "POULINAI").
dico("P", 8, "POULINAS").
dico("P", 8, "POULINAT").
dico("P", 8, "POULINER").
dico("P", 8, "POULINES").
dico("P", 8, "POULINEZ").
dico("P", 8, "POULIOTS").
dico("P", 8, "POULOTTE").
dico("P", 8, "POUPARDE").
dico("P", 8, "POUPARDS").
dico("P", 8, "POUPARTS").
dico("P", 8, "POUPINES").
dico("P", 8, "POUPONNA").
dico("P", 8, "POUPONNE").
dico("P", 8, "POURCEAU").
dico("P", 8, "POURFEND").
dico("P", 8, "POURPIER").
dico("P", 8, "POURPREE").
dico("P", 8, "POURPRES").
dico("P", 8, "POURPRIN").
dico("P", 8, "POURQUOI").
dico("P", 8, "POURRAIS").
dico("P", 8, "POURRAIT").
dico("P", 8, "POURRIES").
dico("P", 8, "POURRIEZ").
dico("P", 8, "POURRIRA").
dico("P", 8, "POURRONS").
dico("P", 8, "POURRONT").
dico("P", 8, "POURSUIS").
dico("P", 8, "POURSUIT").
dico("P", 8, "POURTANT").
dico("P", 8, "POURTOUR").
dico("P", 8, "POURVOIE").
dico("P", 8, "POURVOIR").
dico("P", 8, "POURVOIS").
dico("P", 8, "POURVOIT").
dico("P", 8, "POURVUES").
dico("P", 8, "POUSSAGE").
dico("P", 8, "POUSSAHS").
dico("P", 8, "POUSSAIS").
dico("P", 8, "POUSSAIT").
dico("P", 8, "POUSSANT").
dico("P", 8, "POUSSEES").
dico("P", 8, "POUSSENT").
dico("P", 8, "POUSSERA").
dico("P", 8, "POUSSEUR").
dico("P", 8, "POUSSIER").
dico("P", 8, "POUSSIEZ").
dico("P", 8, "POUSSIFS").
dico("P", 8, "POUSSINE").
dico("P", 8, "POUSSINS").
dico("P", 8, "POUSSIVE").
dico("P", 8, "POUSSOIR").
dico("P", 8, "POUSSONS").
dico("P", 8, "POUTINES").
dico("P", 8, "POUTRAGE").
dico("P", 8, "POUTSAIS").
dico("P", 8, "POUTSAIT").
dico("P", 8, "POUTSANT").
dico("P", 8, "POUTSEES").
dico("P", 8, "POUTSENT").
dico("P", 8, "POUTSERA").
dico("P", 8, "POUTSIEZ").
dico("P", 8, "POUTSONS").
dico("P", 8, "POUTURES").
dico("P", 8, "POUVIONS").
dico("P", 8, "POUVOIRS").
dico("P", 8, "PRACRITS").
dico("P", 8, "PRACTICE").
dico("P", 8, "PRADELLE").
dico("P", 8, "PRAGOISE").
dico("P", 8, "PRAGUOIS").
dico("P", 8, "PRAIENNE").
dico("P", 8, "PRAIRIAL").
dico("P", 8, "PRAIRIES").
dico("P", 8, "PRAKRITS").
dico("P", 8, "PRALINAI").
dico("P", 8, "PRALINAS").
dico("P", 8, "PRALINAT").
dico("P", 8, "PRALINEE").
dico("P", 8, "PRALINER").
dico("P", 8, "PRALINES").
dico("P", 8, "PRALINEZ").
dico("P", 8, "PRANDIAL").
dico("P", 8, "PRATIQUA").
dico("P", 8, "PRATIQUE").
dico("P", 8, "PREALPIN").
dico("P", 8, "PREAMPLI").
dico("P", 8, "PREAVISA").
dico("P", 8, "PREAVISE").
dico("P", 8, "PREBENDE").
dico("P", 8, "PRECAIRE").
dico("P", 8, "PRECATIF").
dico("P", 8, "PRECEDAI").
dico("P", 8, "PRECEDAS").
dico("P", 8, "PRECEDAT").
dico("P", 8, "PRECEDEE").
dico("P", 8, "PRECEDER").
dico("P", 8, "PRECEDES").
dico("P", 8, "PRECEDEZ").
dico("P", 8, "PRECEPTE").
dico("P", 8, "PRECHAIS").
dico("P", 8, "PRECHAIT").
dico("P", 8, "PRECHANT").
dico("P", 8, "PRECHEES").
dico("P", 8, "PRECHENT").
dico("P", 8, "PRECHERA").
dico("P", 8, "PRECHEUR").
dico("P", 8, "PRECHIEZ").
dico("P", 8, "PRECHONS").
dico("P", 8, "PRECIEUX").
dico("P", 8, "PRECIPUT").
dico("P", 8, "PRECISAI").
dico("P", 8, "PRECISAS").
dico("P", 8, "PRECISAT").
dico("P", 8, "PRECISEE").
dico("P", 8, "PRECISER").
dico("P", 8, "PRECISES").
dico("P", 8, "PRECISEZ").
dico("P", 8, "PRECITEE").
dico("P", 8, "PRECITES").
dico("P", 8, "PRECOCES").
dico("P", 8, "PRECONCU").
dico("P", 8, "PRECUIRA").
dico("P", 8, "PRECUIRE").
dico("P", 8, "PRECUISE").
dico("P", 8, "PRECUITE").
dico("P", 8, "PRECUITS").
dico("P", 8, "PREDATEE").
dico("P", 8, "PREDATES").
dico("P", 8, "PREDECES").
dico("P", 8, "PREDELLE").
dico("P", 8, "PREDICAT").
dico("P", 8, "PREDIMES").
dico("P", 8, "PREDIQUA").
dico("P", 8, "PREDIQUE").
dico("P", 8, "PREDIRAI").
dico("P", 8, "PREDIRAS").
dico("P", 8, "PREDIREZ").
dico("P", 8, "PREDISES").
dico("P", 8, "PREDISEZ").
dico("P", 8, "PREDISSE").
dico("P", 8, "PREDITES").
dico("P", 8, "PREEMPTA").
dico("P", 8, "PREEMPTE").
dico("P", 8, "PREFACAI").
dico("P", 8, "PREFACAS").
dico("P", 8, "PREFACAT").
dico("P", 8, "PREFACEE").
dico("P", 8, "PREFACER").
dico("P", 8, "PREFACES").
dico("P", 8, "PREFACEZ").
dico("P", 8, "PREFERAI").
dico("P", 8, "PREFERAS").
dico("P", 8, "PREFERAT").
dico("P", 8, "PREFEREE").
dico("P", 8, "PREFERER").
dico("P", 8, "PREFERES").
dico("P", 8, "PREFEREZ").
dico("P", 8, "PREFETES").
dico("P", 8, "PREFIXAI").
dico("P", 8, "PREFIXAL").
dico("P", 8, "PREFIXAS").
dico("P", 8, "PREFIXAT").
dico("P", 8, "PREFIXEE").
dico("P", 8, "PREFIXER").
dico("P", 8, "PREFIXES").
dico("P", 8, "PREFIXEZ").
dico("P", 8, "PREFORMA").
dico("P", 8, "PREFORME").
dico("P", 8, "PREGNANT").
dico("P", 8, "PREJUGEA").
dico("P", 8, "PREJUGEE").
dico("P", 8, "PREJUGER").
dico("P", 8, "PREJUGES").
dico("P", 8, "PREJUGEZ").
dico("P", 8, "PRELARTS").
dico("P", 8, "PRELASSA").
dico("P", 8, "PRELASSE").
dico("P", 8, "PRELATIN").
dico("P", 8, "PRELAVAI").
dico("P", 8, "PRELAVAS").
dico("P", 8, "PRELAVAT").
dico("P", 8, "PRELAVEE").
dico("P", 8, "PRELAVER").
dico("P", 8, "PRELAVES").
dico("P", 8, "PRELAVEZ").
dico("P", 8, "PRELEVAI").
dico("P", 8, "PRELEVAS").
dico("P", 8, "PRELEVAT").
dico("P", 8, "PRELEVEE").
dico("P", 8, "PRELEVER").
dico("P", 8, "PRELEVES").
dico("P", 8, "PRELEVEZ").
dico("P", 8, "PRELUDAI").
dico("P", 8, "PRELUDAS").
dico("P", 8, "PRELUDAT").
dico("P", 8, "PRELUDER").
dico("P", 8, "PRELUDES").
dico("P", 8, "PRELUDEZ").
dico("P", 8, "PREMICES").
dico("P", 8, "PREMIERE").
dico("P", 8, "PREMIERS").
dico("P", 8, "PREMISSE").
dico("P", 8, "PREMIUMS").
dico("P", 8, "PREMUNIE").
dico("P", 8, "PREMUNIR").
dico("P", 8, "PREMUNIS").
dico("P", 8, "PREMUNIT").
dico("P", 8, "PRENABLE").
dico("P", 8, "PRENANTE").
dico("P", 8, "PRENANTS").
dico("P", 8, "PRENATAL").
dico("P", 8, "PRENDRAI").
dico("P", 8, "PRENDRAS").
dico("P", 8, "PRENDREZ").
dico("P", 8, "PRENEURS").
dico("P", 8, "PRENEUSE").
dico("P", 8, "PRENIONS").
dico("P", 8, "PRENNENT").
dico("P", 8, "PRENOMMA").
dico("P", 8, "PRENOMME").
dico("P", 8, "PRENOTAI").
dico("P", 8, "PRENOTAS").
dico("P", 8, "PRENOTAT").
dico("P", 8, "PRENOTEE").
dico("P", 8, "PRENOTER").
dico("P", 8, "PRENOTES").
dico("P", 8, "PRENOTEZ").
dico("P", 8, "PREORALE").
dico("P", 8, "PREORAUX").
dico("P", 8, "PREPAIES").
dico("P", 8, "PREPARAI").
dico("P", 8, "PREPARAS").
dico("P", 8, "PREPARAT").
dico("P", 8, "PREPAREE").
dico("P", 8, "PREPARER").
dico("P", 8, "PREPARES").
dico("P", 8, "PREPAREZ").
dico("P", 8, "PREPAYAI").
dico("P", 8, "PREPAYAS").
dico("P", 8, "PREPAYAT").
dico("P", 8, "PREPAYEE").
dico("P", 8, "PREPAYER").
dico("P", 8, "PREPAYES").
dico("P", 8, "PREPAYEZ").
dico("P", 8, "PREPOSAI").
dico("P", 8, "PREPOSAS").
dico("P", 8, "PREPOSAT").
dico("P", 8, "PREPOSEE").
dico("P", 8, "PREPOSER").
dico("P", 8, "PREPOSES").
dico("P", 8, "PREPOSEZ").
dico("P", 8, "PREPUCES").
dico("P", 8, "PREREGLA").
dico("P", 8, "PREREGLE").
dico("P", 8, "PREREINE").
dico("P", 8, "PREROMAN").
dico("P", 8, "PRESAGEA").
dico("P", 8, "PRESAGEE").
dico("P", 8, "PRESAGER").
dico("P", 8, "PRESAGES").
dico("P", 8, "PRESAGEZ").
dico("P", 8, "PRESALES").
dico("P", 8, "PRESBYTE").
dico("P", 8, "PRESCRIS").
dico("P", 8, "PRESCRIT").
dico("P", 8, "PRESENCE").
dico("P", 8, "PRESENTA").
dico("P", 8, "PRESENTE").
dico("P", 8, "PRESENTS").
dico("P", 8, "PRESERIE").
dico("P", 8, "PRESERVA").
dico("P", 8, "PRESERVE").
dico("P", 8, "PRESIDAI").
dico("P", 8, "PRESIDAS").
dico("P", 8, "PRESIDAT").
dico("P", 8, "PRESIDEE").
dico("P", 8, "PRESIDER").
dico("P", 8, "PRESIDES").
dico("P", 8, "PRESIDEZ").
dico("P", 8, "PRESSAGE").
dico("P", 8, "PRESSAIS").
dico("P", 8, "PRESSAIT").
dico("P", 8, "PRESSANT").
dico("P", 8, "PRESSEES").
dico("P", 8, "PRESSENS").
dico("P", 8, "PRESSENT").
dico("P", 8, "PRESSERA").
dico("P", 8, "PRESSEUR").
dico("P", 8, "PRESSIER").
dico("P", 8, "PRESSIEZ").
dico("P", 8, "PRESSING").
dico("P", 8, "PRESSION").
dico("P", 8, "PRESSOIR").
dico("P", 8, "PRESSONS").
dico("P", 8, "PRESSURA").
dico("P", 8, "PRESSURE").
dico("P", 8, "PRESTAIS").
dico("P", 8, "PRESTAIT").
dico("P", 8, "PRESTANT").
dico("P", 8, "PRESTEES").
dico("P", 8, "PRESTENT").
dico("P", 8, "PRESTERA").
dico("P", 8, "PRESTIEZ").
dico("P", 8, "PRESTIGE").
dico("P", 8, "PRESTONS").
dico("P", 8, "PRESUMAI").
dico("P", 8, "PRESUMAS").
dico("P", 8, "PRESUMAT").
dico("P", 8, "PRESUMEE").
dico("P", 8, "PRESUMER").
dico("P", 8, "PRESUMES").
dico("P", 8, "PRESUMEZ").
dico("P", 8, "PRESURAI").
dico("P", 8, "PRESURAS").
dico("P", 8, "PRESURAT").
dico("P", 8, "PRESUREE").
dico("P", 8, "PRESURER").
dico("P", 8, "PRESURES").
dico("P", 8, "PRESUREZ").
dico("P", 8, "PRETAMES").
dico("P", 8, "PRETASSE").
dico("P", 8, "PRETATES").
dico("P", 8, "PRETENDE").
dico("P", 8, "PRETENDS").
dico("P", 8, "PRETENDU").
dico("P", 8, "PRETERAI").
dico("P", 8, "PRETERAS").
dico("P", 8, "PRETEREZ").
dico("P", 8, "PRETERIT").
dico("P", 8, "PRETESTS").
dico("P", 8, "PRETEURS").
dico("P", 8, "PRETEUSE").
dico("P", 8, "PRETEXTA").
dico("P", 8, "PRETEXTE").
dico("P", 8, "PRETIONS").
dico("P", 8, "PRETIRAI").
dico("P", 8, "PRETIRAS").
dico("P", 8, "PRETIRAT").
dico("P", 8, "PRETIREE").
dico("P", 8, "PRETIRER").
dico("P", 8, "PRETIRES").
dico("P", 8, "PRETIREZ").
dico("P", 8, "PRETOIRE").
dico("P", 8, "PRETRISE").
dico("P", 8, "PRETURES").
dico("P", 8, "PREVALES").
dico("P", 8, "PREVALEZ").
dico("P", 8, "PREVALUE").
dico("P", 8, "PREVALUS").
dico("P", 8, "PREVALUT").
dico("P", 8, "PREVENEZ").
dico("P", 8, "PREVENIR").
dico("P", 8, "PREVENTE").
dico("P", 8, "PREVENUE").
dico("P", 8, "PREVENUS").
dico("P", 8, "PREVERBE").
dico("P", 8, "PREVIENS").
dico("P", 8, "PREVIENT").
dico("P", 8, "PREVIMES").
dico("P", 8, "PREVISSE").
dico("P", 8, "PREVITES").
dico("P", 8, "PREVOIES").
dico("P", 8, "PREVOIRA").
dico("P", 8, "PREVOTAL").
dico("P", 8, "PREVOTES").
dico("P", 8, "PREVOYEZ").
dico("P", 8, "PRIAIENT").
dico("P", 8, "PRIANTES").
dico("P", 8, "PRIAPEES").
dico("P", 8, "PRIASSES").
dico("P", 8, "PRIERAIS").
dico("P", 8, "PRIERAIT").
dico("P", 8, "PRIERENT").
dico("P", 8, "PRIERIEZ").
dico("P", 8, "PRIERONS").
dico("P", 8, "PRIERONT").
dico("P", 8, "PRIEURAL").
dico("P", 8, "PRIEURES").
dico("P", 8, "PRIMAGES").
dico("P", 8, "PRIMAIRE").
dico("P", 8, "PRIMALES").
dico("P", 8, "PRIMAMES").
dico("P", 8, "PRIMASSE").
dico("P", 8, "PRIMATES").
dico("P", 8, "PRIMATIE").
dico("P", 8, "PRIMAUTE").
dico("P", 8, "PRIMERAI").
dico("P", 8, "PRIMERAS").
dico("P", 8, "PRIMEREZ").
dico("P", 8, "PRIMEURS").
dico("P", 8, "PRIMIDIS").
dico("P", 8, "PRIMIONS").
dico("P", 8, "PRIMITIF").
dico("P", 8, "PRINCEPS").
dico("P", 8, "PRINCIER").
dico("P", 8, "PRINCIPE").
dico("P", 8, "PRIORATS").
dico("P", 8, "PRIORITE").
dico("P", 8, "PRISAMES").
dico("P", 8, "PRISASSE").
dico("P", 8, "PRISATES").
dico("P", 8, "PRISERAI").
dico("P", 8, "PRISERAS").
dico("P", 8, "PRISEREZ").
dico("P", 8, "PRISEURS").
dico("P", 8, "PRISEUSE").
dico("P", 8, "PRISIONS").
dico("P", 8, "PRISSENT").
dico("P", 8, "PRISSIEZ").
dico("P", 8, "PRISUNIC").
dico("P", 8, "PRIVAMES").
dico("P", 8, "PRIVASSE").
dico("P", 8, "PRIVATES").
dico("P", 8, "PRIVATIF").
dico("P", 8, "PRIVAUTE").
dico("P", 8, "PRIVERAI").
dico("P", 8, "PRIVERAS").
dico("P", 8, "PRIVEREZ").
dico("P", 8, "PRIVIONS").
dico("P", 8, "PROACTIF").
dico("P", 8, "PROBABLE").
dico("P", 8, "PROBANTE").
dico("P", 8, "PROBANTS").
dico("P", 8, "PROBITES").
dico("P", 8, "PROBLEME").
dico("P", 8, "PROCAINE").
dico("P", 8, "PROCEDAI").
dico("P", 8, "PROCEDAS").
dico("P", 8, "PROCEDAT").
dico("P", 8, "PROCEDER").
dico("P", 8, "PROCEDES").
dico("P", 8, "PROCEDEZ").
dico("P", 8, "PROCHAIN").
dico("P", 8, "PROCLAMA").
dico("P", 8, "PROCLAME").
dico("P", 8, "PROCLISE").
dico("P", 8, "PROCLIVE").
dico("P", 8, "PROCORDE").
dico("P", 8, "PROCREAI").
dico("P", 8, "PROCREAS").
dico("P", 8, "PROCREAT").
dico("P", 8, "PROCREEE").
dico("P", 8, "PROCREER").
dico("P", 8, "PROCREES").
dico("P", 8, "PROCREEZ").
dico("P", 8, "PROCTITE").
dico("P", 8, "PROCURAI").
dico("P", 8, "PROCURAS").
dico("P", 8, "PROCURAT").
dico("P", 8, "PROCUREE").
dico("P", 8, "PROCURER").
dico("P", 8, "PROCURES").
dico("P", 8, "PROCUREZ").
dico("P", 8, "PRODIGES").
dico("P", 8, "PRODIGUA").
dico("P", 8, "PRODIGUE").
dico("P", 8, "PRODROME").
dico("P", 8, "PRODUIRA").
dico("P", 8, "PRODUIRE").
dico("P", 8, "PRODUISE").
dico("P", 8, "PRODUITE").
dico("P", 8, "PRODUITS").
dico("P", 8, "PROEDRES").
dico("P", 8, "PROFANAI").
dico("P", 8, "PROFANAS").
dico("P", 8, "PROFANAT").
dico("P", 8, "PROFANEE").
dico("P", 8, "PROFANER").
dico("P", 8, "PROFANES").
dico("P", 8, "PROFANEZ").
dico("P", 8, "PROFERAI").
dico("P", 8, "PROFERAS").
dico("P", 8, "PROFERAT").
dico("P", 8, "PROFEREE").
dico("P", 8, "PROFERER").
dico("P", 8, "PROFERES").
dico("P", 8, "PROFEREZ").
dico("P", 8, "PROFESSA").
dico("P", 8, "PROFESSE").
dico("P", 8, "PROFILAI").
dico("P", 8, "PROFILAS").
dico("P", 8, "PROFILAT").
dico("P", 8, "PROFILEE").
dico("P", 8, "PROFILER").
dico("P", 8, "PROFILES").
dico("P", 8, "PROFILEZ").
dico("P", 8, "PROFITAI").
dico("P", 8, "PROFITAS").
dico("P", 8, "PROFITAT").
dico("P", 8, "PROFITER").
dico("P", 8, "PROFITES").
dico("P", 8, "PROFITEZ").
dico("P", 8, "PROFONDE").
dico("P", 8, "PROFONDS").
dico("P", 8, "PROFUSES").
dico("P", 8, "PROHIBAI").
dico("P", 8, "PROHIBAS").
dico("P", 8, "PROHIBAT").
dico("P", 8, "PROHIBEE").
dico("P", 8, "PROHIBER").
dico("P", 8, "PROHIBES").
dico("P", 8, "PROHIBEZ").
dico("P", 8, "PROJETAI").
dico("P", 8, "PROJETAS").
dico("P", 8, "PROJETAT").
dico("P", 8, "PROJETEE").
dico("P", 8, "PROJETER").
dico("P", 8, "PROJETES").
dico("P", 8, "PROJETEZ").
dico("P", 8, "PROJETTE").
dico("P", 8, "PROLEPSE").
dico("P", 8, "PROLINES").
dico("P", 8, "PROLIXES").
dico("P", 8, "PROLOGUE").
dico("P", 8, "PROLONGE").
dico("P", 8, "PROMENAI").
dico("P", 8, "PROMENAS").
dico("P", 8, "PROMENAT").
dico("P", 8, "PROMENEE").
dico("P", 8, "PROMENER").
dico("P", 8, "PROMENES").
dico("P", 8, "PROMENEZ").
dico("P", 8, "PROMESSE").
dico("P", 8, "PROMETTE").
dico("P", 8, "PROMEUVE").
dico("P", 8, "PROMIMES").
dico("P", 8, "PROMISES").
dico("P", 8, "PROMISSE").
dico("P", 8, "PROMITES").
dico("P", 8, "PROMPTES").
dico("P", 8, "PROMUMES").
dico("P", 8, "PROMUSSE").
dico("P", 8, "PROMUTES").
dico("P", 8, "PRONAMES").
dico("P", 8, "PRONASSE").
dico("P", 8, "PRONATES").
dico("P", 8, "PRONERAI").
dico("P", 8, "PRONERAS").
dico("P", 8, "PRONEREZ").
dico("P", 8, "PRONEURS").
dico("P", 8, "PRONEUSE").
dico("P", 8, "PRONIONS").
dico("P", 8, "PRONONCA").
dico("P", 8, "PRONONCE").
dico("P", 8, "PROPAGEA").
dico("P", 8, "PROPAGEE").
dico("P", 8, "PROPAGER").
dico("P", 8, "PROPAGES").
dico("P", 8, "PROPAGEZ").
dico("P", 8, "PROPANES").
dico("P", 8, "PROPANOL").
dico("P", 8, "PROPENES").
dico("P", 8, "PROPFANS").
dico("P", 8, "PROPHASE").
dico("P", 8, "PROPHETE").
dico("P", 8, "PROPICES").
dico("P", 8, "PROPOLIS").
dico("P", 8, "PROPOSAI").
dico("P", 8, "PROPOSAS").
dico("P", 8, "PROPOSAT").
dico("P", 8, "PROPOSEE").
dico("P", 8, "PROPOSER").
dico("P", 8, "PROPOSES").
dico("P", 8, "PROPOSEZ").
dico("P", 8, "PROPRETE").
dico("P", 8, "PROPRETS").
dico("P", 8, "PROPRIOS").
dico("P", 8, "PROPULSA").
dico("P", 8, "PROPULSE").
dico("P", 8, "PROPYLEE").
dico("P", 8, "PROPYLES").
dico("P", 8, "PROROGEA").
dico("P", 8, "PROROGEE").
dico("P", 8, "PROROGER").
dico("P", 8, "PROROGES").
dico("P", 8, "PROROGEZ").
dico("P", 8, "PROSCRIS").
dico("P", 8, "PROSCRIT").
dico("P", 8, "PROSODIE").
dico("P", 8, "PROSOMAS").
dico("P", 8, "PROSOMES").
dico("P", 8, "PROSPECT").
dico("P", 8, "PROSPERA").
dico("P", 8, "PROSPERE").
dico("P", 8, "PROSTATE").
dico("P", 8, "PROSTREE").
dico("P", 8, "PROSTRES").
dico("P", 8, "PROSTYLE").
dico("P", 8, "PROTASES").
dico("P", 8, "PROTEASE").
dico("P", 8, "PROTEGEA").
dico("P", 8, "PROTEGEE").
dico("P", 8, "PROTEGER").
dico("P", 8, "PROTEGES").
dico("P", 8, "PROTEGEZ").
dico("P", 8, "PROTEIDE").
dico("P", 8, "PROTEINE").
dico("P", 8, "PROTELES").
dico("P", 8, "PROTESTA").
dico("P", 8, "PROTESTE").
dico("P", 8, "PROTHESE").
dico("P", 8, "PROTIDES").
dico("P", 8, "PROTIQUE").
dico("P", 8, "PROTISTE").
dico("P", 8, "PROTOMES").
dico("P", 8, "PROTOURE").
dico("P", 8, "PROUESSE").
dico("P", 8, "PROUVAIS").
dico("P", 8, "PROUVAIT").
dico("P", 8, "PROUVANT").
dico("P", 8, "PROUVEES").
dico("P", 8, "PROUVENT").
dico("P", 8, "PROUVERA").
dico("P", 8, "PROUVIEZ").
dico("P", 8, "PROUVONS").
dico("P", 8, "PROVENDE").
dico("P", 8, "PROVENEZ").
dico("P", 8, "PROVENIR").
dico("P", 8, "PROVENUE").
dico("P", 8, "PROVENUS").
dico("P", 8, "PROVERBE").
dico("P", 8, "PROVIENS").
dico("P", 8, "PROVIENT").
dico("P", 8, "PROVIGNA").
dico("P", 8, "PROVIGNE").
dico("P", 8, "PROVINCE").
dico("P", 8, "PROVOQUA").
dico("P", 8, "PROVOQUE").
dico("P", 8, "PROXENES").
dico("P", 8, "PROXIMAL").
dico("P", 8, "PRUDENCE").
dico("P", 8, "PRUDENTE").
dico("P", 8, "PRUDENTS").
dico("P", 8, "PRUDERIE").
dico("P", 8, "PRUNEAUX").
dico("P", 8, "PRUNELEE").
dico("P", 8, "PRUNELLE").
dico("P", 8, "PRUNIERS").
dico("P", 8, "PRURIGOS").
dico("P", 8, "PRUSSIEN").
dico("P", 8, "PRUSSIKS").
dico("P", 8, "PRYTANEE").
dico("P", 8, "PRYTANES").
dico("P", 8, "PSAMMITE").
dico("P", 8, "PSAUTIER").
dico("P", 8, "PSCHENTS").
dico("P", 8, "PSCHITTS").
dico("P", 8, "PSILOPAS").
dico("P", 8, "PSILOTUM").
dico("P", 8, "PSYCHOSE").
dico("P", 8, "PSYLLIUM").
dico("P", 8, "PTOMAINE").
dico("P", 8, "PTYALINE").
dico("P", 8, "PUANTEUR").
dico("P", 8, "PUASSENT").
dico("P", 8, "PUASSIEZ").
dico("P", 8, "PUBALGIE").
dico("P", 8, "PUBERTES").
dico("P", 8, "PUBIENNE").
dico("P", 8, "PUBLIAIS").
dico("P", 8, "PUBLIAIT").
dico("P", 8, "PUBLIANT").
dico("P", 8, "PUBLIEES").
dico("P", 8, "PUBLIENT").
dico("P", 8, "PUBLIERA").
dico("P", 8, "PUBLIIEZ").
dico("P", 8, "PUBLIONS").
dico("P", 8, "PUBLIQUE").
dico("P", 8, "PUCCINIA").
dico("P", 8, "PUCCINIE").
dico("P", 8, "PUCELAGE").
dico("P", 8, "PUCELLES").
dico("P", 8, "PUCERONS").
dico("P", 8, "PUDDINGS").
dico("P", 8, "PUDDLAGE").
dico("P", 8, "PUDDLAIS").
dico("P", 8, "PUDDLAIT").
dico("P", 8, "PUDDLANT").
dico("P", 8, "PUDDLEES").
dico("P", 8, "PUDDLENT").
dico("P", 8, "PUDDLERA").
dico("P", 8, "PUDDLEUR").
dico("P", 8, "PUDDLIEZ").
dico("P", 8, "PUDDLONS").
dico("P", 8, "PUDIBOND").
dico("P", 8, "PUDICITE").
dico("P", 8, "PUDIQUES").
dico("P", 8, "PUERILES").
dico("P", 8, "PUERIONS").
dico("P", 8, "PUGILATS").
dico("P", 8, "PUGNACES").
dico("P", 8, "PUISAGES").
dico("P", 8, "PUISAMES").
dico("P", 8, "PUISARDS").
dico("P", 8, "PUISASSE").
dico("P", 8, "PUISATES").
dico("P", 8, "PUISERAI").
dico("P", 8, "PUISERAS").
dico("P", 8, "PUISEREZ").
dico("P", 8, "PUISETTE").
dico("P", 8, "PUISIONS").
dico("P", 8, "PUISSANT").
dico("P", 8, "PUISSENT").
dico("P", 8, "PUISSIEZ").
dico("P", 8, "PULLMANS").
dico("P", 8, "PULLULAI").
dico("P", 8, "PULLULAS").
dico("P", 8, "PULLULAT").
dico("P", 8, "PULLULER").
dico("P", 8, "PULLULES").
dico("P", 8, "PULLULEZ").
dico("P", 8, "PULMONES").
dico("P", 8, "PULPAIRE").
dico("P", 8, "PULPEUSE").
dico("P", 8, "PULPITES").
dico("P", 8, "PULSAMES").
dico("P", 8, "PULSANTE").
dico("P", 8, "PULSANTS").
dico("P", 8, "PULSASSE").
dico("P", 8, "PULSATES").
dico("P", 8, "PULSATIF").
dico("P", 8, "PULSERAI").
dico("P", 8, "PULSERAS").
dico("P", 8, "PULSEREZ").
dico("P", 8, "PULSIONS").
dico("P", 8, "PULTACEE").
dico("P", 8, "PULTACES").
dico("P", 8, "PULVERIN").
dico("P", 8, "PUNAISAI").
dico("P", 8, "PUNAISAS").
dico("P", 8, "PUNAISAT").
dico("P", 8, "PUNAISEE").
dico("P", 8, "PUNAISER").
dico("P", 8, "PUNAISES").
dico("P", 8, "PUNAISEZ").
dico("P", 8, "PUNCHEUR").
dico("P", 8, "PUNCTURE").
dico("P", 8, "PUNIQUES").
dico("P", 8, "PUNIRAIS").
dico("P", 8, "PUNIRAIT").
dico("P", 8, "PUNIRENT").
dico("P", 8, "PUNIRIEZ").
dico("P", 8, "PUNIRONS").
dico("P", 8, "PUNIRONT").
dico("P", 8, "PUNISSES").
dico("P", 8, "PUNISSEZ").
dico("P", 8, "PUNITIFS").
dico("P", 8, "PUNITION").
dico("P", 8, "PUNITIVE").
dico("P", 8, "PUNKETTE").
dico("P", 8, "PUPAZZOS").
dico("P", 8, "PUPILLES").
dico("P", 8, "PUPIPARE").
dico("P", 8, "PUPITRES").
dico("P", 8, "PUREMENT").
dico("P", 8, "PURGATIF").
dico("P", 8, "PURGEAIS").
dico("P", 8, "PURGEAIT").
dico("P", 8, "PURGEANT").
dico("P", 8, "PURGEOIR").
dico("P", 8, "PURGEONS").
dico("P", 8, "PURGERAI").
dico("P", 8, "PURGERAS").
dico("P", 8, "PURGEREZ").
dico("P", 8, "PURGEURS").
dico("P", 8, "PURGIONS").
dico("P", 8, "PURIFIAI").
dico("P", 8, "PURIFIAS").
dico("P", 8, "PURIFIAT").
dico("P", 8, "PURIFIEE").
dico("P", 8, "PURIFIER").
dico("P", 8, "PURIFIES").
dico("P", 8, "PURIFIEZ").
dico("P", 8, "PURINAIS").
dico("P", 8, "PURINAIT").
dico("P", 8, "PURINANT").
dico("P", 8, "PURINEES").
dico("P", 8, "PURINENT").
dico("P", 8, "PURINERA").
dico("P", 8, "PURINIEZ").
dico("P", 8, "PURINONS").
dico("P", 8, "PURIQUES").
dico("P", 8, "PURISMES").
dico("P", 8, "PURISTES").
dico("P", 8, "PURITAIN").
dico("P", 8, "PUROTINS").
dico("P", 8, "PURPURAS").
dico("P", 8, "PURPURIN").
dico("P", 8, "PURULENT").
dico("P", 8, "PUSSIONS").
dico("P", 8, "PUSTULEE").
dico("P", 8, "PUSTULES").
dico("P", 8, "PUTATIFS").
dico("P", 8, "PUTATIVE").
dico("P", 8, "PUTREFIA").
dico("P", 8, "PUTREFIE").
dico("P", 8, "PUTRIDES").
dico("P", 8, "PUTTAMES").
dico("P", 8, "PUTTASSE").
dico("P", 8, "PUTTATES").
dico("P", 8, "PUTTERAI").
dico("P", 8, "PUTTERAS").
dico("P", 8, "PUTTEREZ").
dico("P", 8, "PUTTINGS").
dico("P", 8, "PUTTIONS").
dico("P", 8, "PYCNIQUE").
dico("P", 8, "PYCNOSES").
dico("P", 8, "PYELITES").
dico("P", 8, "PYGARGUE").
dico("P", 8, "PYGMEENS").
dico("P", 8, "PYOGENES").
dico("P", 8, "PYORRHEE").
dico("P", 8, "PYRALENE").
dico("P", 8, "PYRAMIDA").
dico("P", 8, "PYRAMIDE").
dico("P", 8, "PYRANNES").
dico("P", 8, "PYRENEEN").
dico("P", 8, "PYRETHRE").
dico("P", 8, "PYREXIES").
dico("P", 8, "PYRIDINE").
dico("P", 8, "PYROFLAM").
dico("P", 8, "PYROGENE").
dico("P", 8, "PYROLYSE").
dico("P", 8, "PYROMANE").
dico("P", 8, "PYROXENE").
dico("P", 8, "PYROXYLE").
dico("P", 8, "PYRROLES").
dico("P", 8, "PYTHIENS").
dico("P", 8, "PYTHIQUE").
