dico("Q", 10, "QATARIENNE").
dico("Q", 10, "QUADRANGLE").
dico("Q", 10, "QUADRATURE").
dico("Q", 10, "QUADRETTES").
dico("Q", 10, "QUADRICEPS").
dico("Q", 10, "QUADRIFIDE").
dico("Q", 10, "QUADRILLAI").
dico("Q", 10, "QUADRILLAS").
dico("Q", 10, "QUADRILLAT").
dico("Q", 10, "QUADRILLEE").
dico("Q", 10, "QUADRILLER").
dico("Q", 10, "QUADRILLES").
dico("Q", 10, "QUADRILLEZ").
dico("Q", 10, "QUADRILOBE").
dico("Q", 10, "QUADRIPOLE").
dico("Q", 10, "QUADRIQUES").
dico("Q", 10, "QUADRIREME").
dico("Q", 10, "QUADRIVIUM").
dico("Q", 10, "QUADRUMANE").
dico("Q", 10, "QUADRUPEDE").
dico("Q", 10, "QUADRUPLAI").
dico("Q", 10, "QUADRUPLAS").
dico("Q", 10, "QUADRUPLAT").
dico("Q", 10, "QUADRUPLEE").
dico("Q", 10, "QUADRUPLER").
dico("Q", 10, "QUADRUPLES").
dico("Q", 10, "QUADRUPLET").
dico("Q", 10, "QUADRUPLEX").
dico("Q", 10, "QUADRUPLEZ").
dico("Q", 10, "QUAKERESSE").
dico("Q", 10, "QUAKERISME").
dico("Q", 10, "QUALIFIAIS").
dico("Q", 10, "QUALIFIAIT").
dico("Q", 10, "QUALIFIANT").
dico("Q", 10, "QUALIFIEES").
dico("Q", 10, "QUALIFIENT").
dico("Q", 10, "QUALIFIERA").
dico("Q", 10, "QUALIFIIEZ").
dico("Q", 10, "QUALIFIONS").
dico("Q", 10, "QUALITATIF").
dico("Q", 10, "QUANTIEMES").
dico("Q", 10, "QUANTIFIAI").
dico("Q", 10, "QUANTIFIAS").
dico("Q", 10, "QUANTIFIAT").
dico("Q", 10, "QUANTIFIEE").
dico("Q", 10, "QUANTIFIER").
dico("Q", 10, "QUANTIFIES").
dico("Q", 10, "QUANTIFIEZ").
dico("Q", 10, "QUANTIQUES").
dico("Q", 10, "QUARRABLES").
dico("Q", 10, "QUARTAGEAI").
dico("Q", 10, "QUARTAGEAS").
dico("Q", 10, "QUARTAGEAT").
dico("Q", 10, "QUARTAGEES").
dico("Q", 10, "QUARTAGENT").
dico("Q", 10, "QUARTAGERA").
dico("Q", 10, "QUARTAGIEZ").
dico("Q", 10, "QUARTAIENT").
dico("Q", 10, "QUARTANIER").
dico("Q", 10, "QUARTASSES").
dico("Q", 10, "QUARTATION").
dico("Q", 10, "QUARTENIER").
dico("Q", 10, "QUARTERAIS").
dico("Q", 10, "QUARTERAIT").
dico("Q", 10, "QUARTERENT").
dico("Q", 10, "QUARTERIEZ").
dico("Q", 10, "QUARTERONS").
dico("Q", 10, "QUARTERONT").
dico("Q", 10, "QUARTETTES").
dico("Q", 10, "QUARTILAGE").
dico("Q", 10, "QUARTIQUES").
dico("Q", 10, "QUARTZEUSE").
dico("Q", 10, "QUARTZIQUE").
dico("Q", 10, "QUARTZITES").
dico("Q", 10, "QUASIMODOS").
dico("Q", 10, "QUATERNION").
dico("Q", 10, "QUATRIEMES").
dico("Q", 10, "QUEBECISAI").
dico("Q", 10, "QUEBECISAS").
dico("Q", 10, "QUEBECISAT").
dico("Q", 10, "QUEBECISEE").
dico("Q", 10, "QUEBECISER").
dico("Q", 10, "QUEBECISES").
dico("Q", 10, "QUEBECISEZ").
dico("Q", 10, "QUEBECISME").
dico("Q", 10, "QUEBECOISE").
dico("Q", 10, "QUEBRACHOS").
dico("Q", 10, "QUELCONQUE").
dico("Q", 10, "QUEMANDAIS").
dico("Q", 10, "QUEMANDAIT").
dico("Q", 10, "QUEMANDANT").
dico("Q", 10, "QUEMANDEES").
dico("Q", 10, "QUEMANDENT").
dico("Q", 10, "QUEMANDERA").
dico("Q", 10, "QUEMANDEUR").
dico("Q", 10, "QUEMANDIEZ").
dico("Q", 10, "QUEMANDONS").
dico("Q", 10, "QUENOUILLE").
dico("Q", 10, "QUEQUETTES").
dico("Q", 10, "QUERCINOIS").
dico("Q", 10, "QUERCITRIN").
dico("Q", 10, "QUERCITRON").
dico("Q", 10, "QUERCYNOIS").
dico("Q", 10, "QUERELLAIS").
dico("Q", 10, "QUERELLAIT").
dico("Q", 10, "QUERELLANT").
dico("Q", 10, "QUERELLEES").
dico("Q", 10, "QUERELLENT").
dico("Q", 10, "QUERELLERA").
dico("Q", 10, "QUERELLEUR").
dico("Q", 10, "QUERELLIEZ").
dico("Q", 10, "QUERELLONS").
dico("Q", 10, "QUERULENCE").
dico("Q", 10, "QUERULENTE").
dico("Q", 10, "QUERULENTS").
dico("Q", 10, "QUESTIONNA").
dico("Q", 10, "QUESTIONNE").
dico("Q", 10, "QUETASSENT").
dico("Q", 10, "QUETASSIEZ").
dico("Q", 10, "QUETERIONS").
dico("Q", 10, "QUETSCHIER").
dico("Q", 10, "QUEUTAIENT").
dico("Q", 10, "QUEUTASSES").
dico("Q", 10, "QUEUTERAIS").
dico("Q", 10, "QUEUTERAIT").
dico("Q", 10, "QUEUTERENT").
dico("Q", 10, "QUEUTERIEZ").
dico("Q", 10, "QUEUTERONS").
dico("Q", 10, "QUEUTERONT").
dico("Q", 10, "QUICAGEONS").
dico("Q", 10, "QUIESCENCE").
dico("Q", 10, "QUIESCENTE").
dico("Q", 10, "QUIESCENTS").
dico("Q", 10, "QUIETISMES").
dico("Q", 10, "QUIETISTES").
dico("Q", 10, "QUILLAIENT").
dico("Q", 10, "QUILLASSES").
dico("Q", 10, "QUILLERAIS").
dico("Q", 10, "QUILLERAIT").
dico("Q", 10, "QUILLERENT").
dico("Q", 10, "QUILLERIEZ").
dico("Q", 10, "QUILLERONS").
dico("Q", 10, "QUILLERONT").
dico("Q", 10, "QUILLEUSES").
dico("Q", 10, "QUIMPEROIS").
dico("Q", 10, "QUINCAILLE").
dico("Q", 10, "QUINCONCES").
dico("Q", 10, "QUINIDINES").
dico("Q", 10, "QUINOLEINE").
dico("Q", 10, "QUINOLONES").
dico("Q", 10, "QUINQUINAS").
dico("Q", 10, "QUINTAINES").
dico("Q", 10, "QUINTETTES").
dico("Q", 10, "QUINTEUSES").
dico("Q", 10, "QUINTOLETS").
dico("Q", 10, "QUINTUPLAI").
dico("Q", 10, "QUINTUPLAS").
dico("Q", 10, "QUINTUPLAT").
dico("Q", 10, "QUINTUPLEE").
dico("Q", 10, "QUINTUPLER").
dico("Q", 10, "QUINTUPLES").
dico("Q", 10, "QUINTUPLEZ").
dico("Q", 10, "QUINZAINES").
dico("Q", 10, "QUINZIEMES").
dico("Q", 10, "QUINZISTES").
dico("Q", 10, "QUIPROQUOS").
dico("Q", 10, "QUIQUAJONS").
dico("Q", 10, "QUIRATAIRE").
dico("Q", 10, "QUITENIENS").
dico("Q", 10, "QUITTAIENT").
dico("Q", 10, "QUITTANCAI").
dico("Q", 10, "QUITTANCAS").
dico("Q", 10, "QUITTANCAT").
dico("Q", 10, "QUITTANCEE").
dico("Q", 10, "QUITTANCER").
dico("Q", 10, "QUITTANCES").
dico("Q", 10, "QUITTANCEZ").
dico("Q", 10, "QUITTASSES").
dico("Q", 10, "QUITTERAIS").
dico("Q", 10, "QUITTERAIT").
dico("Q", 10, "QUITTERENT").
dico("Q", 10, "QUITTERIEZ").
dico("Q", 10, "QUITTERONS").
dico("Q", 10, "QUITTERONT").
dico("Q", 10, "QUOTIDIENS").
