dico("Q", 5, "QANUN").
dico("Q", 5, "QIBLA").
dico("Q", 5, "QUADO").
dico("Q", 5, "QUADS").
dico("Q", 5, "QUAIS").
dico("Q", 5, "QUAND").
dico("Q", 5, "QUANT").
dico("Q", 5, "QUARK").
dico("Q", 5, "QUART").
dico("Q", 5, "QUASI").
dico("Q", 5, "QUELS").
dico("Q", 5, "QUETA").
dico("Q", 5, "QUETE").
dico("Q", 5, "QUEUE").
dico("Q", 5, "QUEUX").
dico("Q", 5, "QUICK").
dico("Q", 5, "QUIET").
dico("Q", 5, "QUINE").
dico("Q", 5, "QUINT").
dico("Q", 5, "QUIPO").
dico("Q", 5, "QUIPU").
dico("Q", 5, "QUOTA").
