dico("Q", 6, "QANUNS").
dico("Q", 6, "QASIDA").
dico("Q", 6, "QATARI").
dico("Q", 6, "QIBLAS").
dico("Q", 6, "QUADOS").
dico("Q", 6, "QUADRA").
dico("Q", 6, "QUADRI").
dico("Q", 6, "QUAHOG").
dico("Q", 6, "QUAKER").
dico("Q", 6, "QUALIF").
dico("Q", 6, "QUANTA").
dico("Q", 6, "QUARKS").
dico("Q", 6, "QUARRE").
dico("Q", 6, "QUARTA").
dico("Q", 6, "QUARTE").
dico("Q", 6, "QUARTO").
dico("Q", 6, "QUARTS").
dico("Q", 6, "QUARTZ").
dico("Q", 6, "QUASAR").
dico("Q", 6, "QUASIS").
dico("Q", 6, "QUATER").
dico("Q", 6, "QUATRE").
dico("Q", 6, "QUELEA").
dico("Q", 6, "QUELLE").
dico("Q", 6, "QUERIR").
dico("Q", 6, "QUETAI").
dico("Q", 6, "QUETAS").
dico("Q", 6, "QUETAT").
dico("Q", 6, "QUETEE").
dico("Q", 6, "QUETER").
dico("Q", 6, "QUETES").
dico("Q", 6, "QUETEZ").
dico("Q", 6, "QUETTE").
dico("Q", 6, "QUEUES").
dico("Q", 6, "QUEUTA").
dico("Q", 6, "QUEUTE").
dico("Q", 6, "QUICHE").
dico("Q", 6, "QUICKS").
dico("Q", 6, "QUIDAM").
dico("Q", 6, "QUIETE").
dico("Q", 6, "QUIETS").
dico("Q", 6, "QUILLA").
dico("Q", 6, "QUILLE").
dico("Q", 6, "QUINEE").
dico("Q", 6, "QUINES").
dico("Q", 6, "QUINOA").
dico("Q", 6, "QUINTE").
dico("Q", 6, "QUINTO").
dico("Q", 6, "QUINTS").
dico("Q", 6, "QUINZE").
dico("Q", 6, "QUIPOS").
dico("Q", 6, "QUIPOU").
dico("Q", 6, "QUIPUS").
dico("Q", 6, "QUIRAT").
dico("Q", 6, "QUITTA").
dico("Q", 6, "QUITTE").
dico("Q", 6, "QUITUS").
dico("Q", 6, "QUORUM").
dico("Q", 6, "QUOTAS").
dico("Q", 6, "QWERTY").
