dico("Q", 7, "QARAITE").
dico("Q", 7, "QASIDAS").
dico("Q", 7, "QATARIE").
dico("Q", 7, "QATARIS").
dico("Q", 7, "QUADRAS").
dico("Q", 7, "QUADRIS").
dico("Q", 7, "QUAHOGS").
dico("Q", 7, "QUAKERS").
dico("Q", 7, "QUALIFS").
dico("Q", 7, "QUALITE").
dico("Q", 7, "QUANTON").
dico("Q", 7, "QUANTUM").
dico("Q", 7, "QUARRES").
dico("Q", 7, "QUARTAI").
dico("Q", 7, "QUARTAS").
dico("Q", 7, "QUARTAT").
dico("Q", 7, "QUARTEE").
dico("Q", 7, "QUARTER").
dico("Q", 7, "QUARTES").
dico("Q", 7, "QUARTET").
dico("Q", 7, "QUARTEZ").
dico("Q", 7, "QUASARS").
dico("Q", 7, "QUASSIA").
dico("Q", 7, "QUATUOR").
dico("Q", 7, "QUECHUA").
dico("Q", 7, "QUELEAS").
dico("Q", 7, "QUELLES").
dico("Q", 7, "QUELQUE").
dico("Q", 7, "QUESACO").
dico("Q", 7, "QUETAIS").
dico("Q", 7, "QUETAIT").
dico("Q", 7, "QUETANT").
dico("Q", 7, "QUETEES").
dico("Q", 7, "QUETENT").
dico("Q", 7, "QUETERA").
dico("Q", 7, "QUETEUR").
dico("Q", 7, "QUETEUX").
dico("Q", 7, "QUETIEZ").
dico("Q", 7, "QUETONS").
dico("Q", 7, "QUETTES").
dico("Q", 7, "QUETZAL").
dico("Q", 7, "QUEUSOT").
dico("Q", 7, "QUEUTAI").
dico("Q", 7, "QUEUTAS").
dico("Q", 7, "QUEUTAT").
dico("Q", 7, "QUEUTER").
dico("Q", 7, "QUEUTES").
dico("Q", 7, "QUEUTEZ").
dico("Q", 7, "QUICHES").
dico("Q", 7, "QUICHUA").
dico("Q", 7, "QUIDAMS").
dico("Q", 7, "QUIETES").
dico("Q", 7, "QUIGNON").
dico("Q", 7, "QUILLAI").
dico("Q", 7, "QUILLAS").
dico("Q", 7, "QUILLAT").
dico("Q", 7, "QUILLEE").
dico("Q", 7, "QUILLER").
dico("Q", 7, "QUILLES").
dico("Q", 7, "QUILLEZ").
dico("Q", 7, "QUILLON").
dico("Q", 7, "QUINAUD").
dico("Q", 7, "QUINEES").
dico("Q", 7, "QUININE").
dico("Q", 7, "QUINOAS").
dico("Q", 7, "QUINOLA").
dico("Q", 7, "QUINONE").
dico("Q", 7, "QUINQUA").
dico("Q", 7, "QUINTAL").
dico("Q", 7, "QUINTES").
dico("Q", 7, "QUINTET").
dico("Q", 7, "QUIPOUS").
dico("Q", 7, "QUIRATS").
dico("Q", 7, "QUIRITE").
dico("Q", 7, "QUITTAI").
dico("Q", 7, "QUITTAS").
dico("Q", 7, "QUITTAT").
dico("Q", 7, "QUITTEE").
dico("Q", 7, "QUITTER").
dico("Q", 7, "QUITTES").
dico("Q", 7, "QUITTEZ").
dico("Q", 7, "QUOIQUE").
dico("Q", 7, "QUORUMS").
dico("Q", 7, "QUOTITE").
