dico("Q", 9, "QATARIENS").
dico("Q", 9, "QUADRANTS").
dico("Q", 9, "QUADRETTE").
dico("Q", 9, "QUADRIGES").
dico("Q", 9, "QUADRILLA").
dico("Q", 9, "QUADRILLE").
dico("Q", 9, "QUADRIQUE").
dico("Q", 9, "QUADRUPLA").
dico("Q", 9, "QUADRUPLE").
dico("Q", 9, "QUALIFIAI").
dico("Q", 9, "QUALIFIAS").
dico("Q", 9, "QUALIFIAT").
dico("Q", 9, "QUALIFIEE").
dico("Q", 9, "QUALIFIER").
dico("Q", 9, "QUALIFIES").
dico("Q", 9, "QUALIFIEZ").
dico("Q", 9, "QUANTEURS").
dico("Q", 9, "QUANTIEME").
dico("Q", 9, "QUANTIFIA").
dico("Q", 9, "QUANTIFIE").
dico("Q", 9, "QUANTILES").
dico("Q", 9, "QUANTIQUE").
dico("Q", 9, "QUANTITES").
dico("Q", 9, "QUARRABLE").
dico("Q", 9, "QUARTAGEA").
dico("Q", 9, "QUARTAGEE").
dico("Q", 9, "QUARTAGER").
dico("Q", 9, "QUARTAGES").
dico("Q", 9, "QUARTAGEZ").
dico("Q", 9, "QUARTAMES").
dico("Q", 9, "QUARTASSE").
dico("Q", 9, "QUARTATES").
dico("Q", 9, "QUARTAUTS").
dico("Q", 9, "QUARTERAI").
dico("Q", 9, "QUARTERAS").
dico("Q", 9, "QUARTEREZ").
dico("Q", 9, "QUARTERON").
dico("Q", 9, "QUARTETTE").
dico("Q", 9, "QUARTIDIS").
dico("Q", 9, "QUARTIERS").
dico("Q", 9, "QUARTILES").
dico("Q", 9, "QUARTIONS").
dico("Q", 9, "QUARTIQUE").
dico("Q", 9, "QUARTZEUX").
dico("Q", 9, "QUARTZITE").
dico("Q", 9, "QUASIMENT").
dico("Q", 9, "QUASIMODO").
dico("Q", 9, "QUASSIERS").
dico("Q", 9, "QUASSINES").
dico("Q", 9, "QUATERNES").
dico("Q", 9, "QUATRAINS").
dico("Q", 9, "QUATRIEME").
dico("Q", 9, "QUEBECISA").
dico("Q", 9, "QUEBECISE").
dico("Q", 9, "QUEBECOIS").
dico("Q", 9, "QUEBRACHO").
dico("Q", 9, "QUEMANDAI").
dico("Q", 9, "QUEMANDAS").
dico("Q", 9, "QUEMANDAT").
dico("Q", 9, "QUEMANDEE").
dico("Q", 9, "QUEMANDER").
dico("Q", 9, "QUEMANDES").
dico("Q", 9, "QUEMANDEZ").
dico("Q", 9, "QUENELLES").
dico("Q", 9, "QUENETTES").
dico("Q", 9, "QUENOTTES").
dico("Q", 9, "QUEQUETTE").
dico("Q", 9, "QUERABLES").
dico("Q", 9, "QUERELLAI").
dico("Q", 9, "QUERELLAS").
dico("Q", 9, "QUERELLAT").
dico("Q", 9, "QUERELLEE").
dico("Q", 9, "QUERELLER").
dico("Q", 9, "QUERELLES").
dico("Q", 9, "QUERELLEZ").
dico("Q", 9, "QUERULENT").
dico("Q", 9, "QUESTEURS").
dico("Q", 9, "QUESTIONS").
dico("Q", 9, "QUESTURES").
dico("Q", 9, "QUETAIENT").
dico("Q", 9, "QUETAINES").
dico("Q", 9, "QUETASSES").
dico("Q", 9, "QUETERAIS").
dico("Q", 9, "QUETERAIT").
dico("Q", 9, "QUETERENT").
dico("Q", 9, "QUETERIEZ").
dico("Q", 9, "QUETERONS").
dico("Q", 9, "QUETERONT").
dico("Q", 9, "QUETEUSES").
dico("Q", 9, "QUETSCHES").
dico("Q", 9, "QUETZALES").
dico("Q", 9, "QUEUTAGES").
dico("Q", 9, "QUEUTAMES").
dico("Q", 9, "QUEUTASSE").
dico("Q", 9, "QUEUTATES").
dico("Q", 9, "QUEUTERAI").
dico("Q", 9, "QUEUTERAS").
dico("Q", 9, "QUEUTEREZ").
dico("Q", 9, "QUEUTIONS").
dico("Q", 9, "QUICAGEON").
dico("Q", 9, "QUICONQUE").
dico("Q", 9, "QUIDDITES").
dico("Q", 9, "QUIESCENT").
dico("Q", 9, "QUIETISME").
dico("Q", 9, "QUIETISTE").
dico("Q", 9, "QUIETUDES").
dico("Q", 9, "QUILLAMES").
dico("Q", 9, "QUILLARDS").
dico("Q", 9, "QUILLASSE").
dico("Q", 9, "QUILLATES").
dico("Q", 9, "QUILLERAI").
dico("Q", 9, "QUILLERAS").
dico("Q", 9, "QUILLEREZ").
dico("Q", 9, "QUILLEURS").
dico("Q", 9, "QUILLEUSE").
dico("Q", 9, "QUILLIERS").
dico("Q", 9, "QUILLIONS").
dico("Q", 9, "QUINAIRES").
dico("Q", 9, "QUINAUDES").
dico("Q", 9, "QUINCONCE").
dico("Q", 9, "QUINIDINE").
dico("Q", 9, "QUINOLONE").
dico("Q", 9, "QUINQUETS").
dico("Q", 9, "QUINQUINA").
dico("Q", 9, "QUINQUINS").
dico("Q", 9, "QUINTAINE").
dico("Q", 9, "QUINTETTE").
dico("Q", 9, "QUINTEUSE").
dico("Q", 9, "QUINTIDIS").
dico("Q", 9, "QUINTOLET").
dico("Q", 9, "QUINTUPLA").
dico("Q", 9, "QUINTUPLE").
dico("Q", 9, "QUINZAINE").
dico("Q", 9, "QUINZIEME").
dico("Q", 9, "QUINZISTE").
dico("Q", 9, "QUIPROQUO").
dico("Q", 9, "QUIQUAJON").
dico("Q", 9, "QUISCALES").
dico("Q", 9, "QUITENIEN").
dico("Q", 9, "QUITTAMES").
dico("Q", 9, "QUITTANCA").
dico("Q", 9, "QUITTANCE").
dico("Q", 9, "QUITTASSE").
dico("Q", 9, "QUITTATES").
dico("Q", 9, "QUITTERAI").
dico("Q", 9, "QUITTERAS").
dico("Q", 9, "QUITTEREZ").
dico("Q", 9, "QUITTIONS").
dico("Q", 9, "QUOLIBETS").
dico("Q", 9, "QUOTIDIEN").
dico("Q", 9, "QUOTIENTS").
