dico("R", 6, "RABABS").
dico("R", 6, "RABAIS").
dico("R", 6, "RABANE").
dico("R", 6, "RABANS").
dico("R", 6, "RABATS").
dico("R", 6, "RABBIN").
dico("R", 6, "RABBIS").
dico("R", 6, "RABIOT").
dico("R", 6, "RABLAI").
dico("R", 6, "RABLAS").
dico("R", 6, "RABLAT").
dico("R", 6, "RABLEE").
dico("R", 6, "RABLER").
dico("R", 6, "RABLES").
dico("R", 6, "RABLEZ").
dico("R", 6, "RABOTA").
dico("R", 6, "RABOTE").
dico("R", 6, "RABOTS").
dico("R", 6, "RACAGE").
dico("R", 6, "RACEES").
dico("R", 6, "RACERS").
dico("R", 6, "RACHAT").
dico("R", 6, "RACHIS").
dico("R", 6, "RACIAL").
dico("R", 6, "RACINA").
dico("R", 6, "RACINE").
dico("R", 6, "RACKET").
dico("R", 6, "RACLAI").
dico("R", 6, "RACLAS").
dico("R", 6, "RACLAT").
dico("R", 6, "RACLEE").
dico("R", 6, "RACLER").
dico("R", 6, "RACLES").
dico("R", 6, "RACLEZ").
dico("R", 6, "RACOLA").
dico("R", 6, "RACOLE").
dico("R", 6, "RACOON").
dico("R", 6, "RADAIS").
dico("R", 6, "RADAIT").
dico("R", 6, "RADANT").
dico("R", 6, "RADARS").
dico("R", 6, "RADEAU").
dico("R", 6, "RADEES").
dico("R", 6, "RADENT").
dico("R", 6, "RADERA").
dico("R", 6, "RADIAI").
dico("R", 6, "RADIAL").
dico("R", 6, "RADIAN").
dico("R", 6, "RADIAS").
dico("R", 6, "RADIAT").
dico("R", 6, "RADIEE").
dico("R", 6, "RADIER").
dico("R", 6, "RADIES").
dico("R", 6, "RADIEZ").
dico("R", 6, "RADINA").
dico("R", 6, "RADINE").
dico("R", 6, "RADINS").
dico("R", 6, "RADIOS").
dico("R", 6, "RADIUM").
dico("R", 6, "RADIUS").
dico("R", 6, "RADJAH").
dico("R", 6, "RADJAS").
dico("R", 6, "RADOME").
dico("R", 6, "RADONS").
dico("R", 6, "RADOTA").
dico("R", 6, "RADOTE").
dico("R", 6, "RADOUB").
dico("R", 6, "RADSOC").
dico("R", 6, "RADULA").
dico("R", 6, "RAFALA").
dico("R", 6, "RAFALE").
dico("R", 6, "RAFFLE").
dico("R", 6, "RAFFUT").
dico("R", 6, "RAFIAU").
dico("R", 6, "RAFIOT").
dico("R", 6, "RAFLAI").
dico("R", 6, "RAFLAS").
dico("R", 6, "RAFLAT").
dico("R", 6, "RAFLEE").
dico("R", 6, "RAFLER").
dico("R", 6, "RAFLES").
dico("R", 6, "RAFLEZ").
dico("R", 6, "RAGAGE").
dico("R", 6, "RAGEAI").
dico("R", 6, "RAGEAS").
dico("R", 6, "RAGEAT").
dico("R", 6, "RAGENT").
dico("R", 6, "RAGERA").
dico("R", 6, "RAGEUR").
dico("R", 6, "RAGIEZ").
dico("R", 6, "RAGLAN").
dico("R", 6, "RAGOTE").
dico("R", 6, "RAGOTS").
dico("R", 6, "RAGOUT").
dico("R", 6, "RAGREA").
dico("R", 6, "RAGREE").
dico("R", 6, "RAGUAI").
dico("R", 6, "RAGUAS").
dico("R", 6, "RAGUAT").
dico("R", 6, "RAGUEE").
dico("R", 6, "RAGUER").
dico("R", 6, "RAGUES").
dico("R", 6, "RAGUEZ").
dico("R", 6, "RAIDER").
dico("R", 6, "RAIDES").
dico("R", 6, "RAIDIE").
dico("R", 6, "RAIDIR").
dico("R", 6, "RAIDIS").
dico("R", 6, "RAIDIT").
dico("R", 6, "RAIENT").
dico("R", 6, "RAIERA").
dico("R", 6, "RAILLA").
dico("R", 6, "RAILLE").
dico("R", 6, "RAINAI").
dico("R", 6, "RAINAS").
dico("R", 6, "RAINAT").
dico("R", 6, "RAINEE").
dico("R", 6, "RAINER").
dico("R", 6, "RAINES").
dico("R", 6, "RAINEZ").
dico("R", 6, "RAIRAI").
dico("R", 6, "RAIRAS").
dico("R", 6, "RAIREZ").
dico("R", 6, "RAISIN").
dico("R", 6, "RAISON").
dico("R", 6, "RAJAHS").
dico("R", 6, "RAJOUT").
dico("R", 6, "RALAIS").
dico("R", 6, "RALAIT").
dico("R", 6, "RALANT").
dico("R", 6, "RALENT").
dico("R", 6, "RALERA").
dico("R", 6, "RALEUR").
dico("R", 6, "RALIEZ").
dico("R", 6, "RALLAI").
dico("R", 6, "RALLAS").
dico("R", 6, "RALLAT").
dico("R", 6, "RALLER").
dico("R", 6, "RALLES").
dico("R", 6, "RALLEZ").
dico("R", 6, "RALLIA").
dico("R", 6, "RALLIE").
dico("R", 6, "RALLYE").
dico("R", 6, "RALONS").
dico("R", 6, "RAMAGE").
dico("R", 6, "RAMAIS").
dico("R", 6, "RAMAIT").
dico("R", 6, "RAMANT").
dico("R", 6, "RAMDAM").
dico("R", 6, "RAMEAU").
dico("R", 6, "RAMEES").
dico("R", 6, "RAMENA").
dico("R", 6, "RAMENE").
dico("R", 6, "RAMENT").
dico("R", 6, "RAMERA").
dico("R", 6, "RAMEUR").
dico("R", 6, "RAMEUX").
dico("R", 6, "RAMIER").
dico("R", 6, "RAMIES").
dico("R", 6, "RAMIEZ").
dico("R", 6, "RAMONA").
dico("R", 6, "RAMONE").
dico("R", 6, "RAMONS").
dico("R", 6, "RAMPAI").
dico("R", 6, "RAMPAS").
dico("R", 6, "RAMPAT").
dico("R", 6, "RAMPER").
dico("R", 6, "RAMPES").
dico("R", 6, "RAMPEZ").
dico("R", 6, "RAMPON").
dico("R", 6, "RAMULE").
dico("R", 6, "RAMURE").
dico("R", 6, "RANALE").
dico("R", 6, "RANCES").
dico("R", 6, "RANCHE").
dico("R", 6, "RANCHO").
dico("R", 6, "RANCHS").
dico("R", 6, "RANCIE").
dico("R", 6, "RANCIO").
dico("R", 6, "RANCIR").
dico("R", 6, "RANCIS").
dico("R", 6, "RANCIT").
dico("R", 6, "RANCON").
dico("R", 6, "RANGEA").
dico("R", 6, "RANGEE").
dico("R", 6, "RANGER").
dico("R", 6, "RANGES").
dico("R", 6, "RANGEZ").
dico("R", 6, "RANIDE").
dico("R", 6, "RANIMA").
dico("R", 6, "RANIME").
dico("R", 6, "RAOUTS").
dico("R", 6, "RAPACE").
dico("R", 6, "RAPAGE").
dico("R", 6, "RAPAIS").
dico("R", 6, "RAPAIT").
dico("R", 6, "RAPANT").
dico("R", 6, "RAPEES").
dico("R", 6, "RAPENT").
dico("R", 6, "RAPERA").
dico("R", 6, "RAPEUX").
dico("R", 6, "RAPHES").
dico("R", 6, "RAPHIA").
dico("R", 6, "RAPIAT").
dico("R", 6, "RAPIDE").
dico("R", 6, "RAPIDO").
dico("R", 6, "RAPIEZ").
dico("R", 6, "RAPINA").
dico("R", 6, "RAPINE").
dico("R", 6, "RAPINS").
dico("R", 6, "RAPONS").
dico("R", 6, "RAPPAI").
dico("R", 6, "RAPPAS").
dico("R", 6, "RAPPAT").
dico("R", 6, "RAPPEE").
dico("R", 6, "RAPPEL").
dico("R", 6, "RAPPER").
dico("R", 6, "RAPPES").
dico("R", 6, "RAPPEZ").
dico("R", 6, "RAPTUS").
dico("R", 6, "RAPURE").
dico("R", 6, "RAQUAI").
dico("R", 6, "RAQUAS").
dico("R", 6, "RAQUAT").
dico("R", 6, "RAQUEE").
dico("R", 6, "RAQUER").
dico("R", 6, "RAQUES").
dico("R", 6, "RAQUEZ").
dico("R", 6, "RARETE").
dico("R", 6, "RASADE").
dico("R", 6, "RASAGE").
dico("R", 6, "RASAIS").
dico("R", 6, "RASAIT").
dico("R", 6, "RASANT").
dico("R", 6, "RASEES").
dico("R", 6, "RASENT").
dico("R", 6, "RASERA").
dico("R", 6, "RASEUR").
dico("R", 6, "RASHES").
dico("R", 6, "RASIEZ").
dico("R", 6, "RASKOL").
dico("R", 6, "RASOIR").
dico("R", 6, "RASONS").
dico("R", 6, "RASSIE").
dico("R", 6, "RASSIR").
dico("R", 6, "RASSIS").
dico("R", 6, "RASSIT").
dico("R", 6, "RASTAS").
dico("R", 6, "RASTEL").
dico("R", 6, "RATAGE").
dico("R", 6, "RATAIS").
dico("R", 6, "RATAIT").
dico("R", 6, "RATANT").
dico("R", 6, "RATEAU").
dico("R", 6, "RATEES").
dico("R", 6, "RATELA").
dico("R", 6, "RATELE").
dico("R", 6, "RATELS").
dico("R", 6, "RATENT").
dico("R", 6, "RATERA").
dico("R", 6, "RATIER").
dico("R", 6, "RATIEZ").
dico("R", 6, "RATINA").
dico("R", 6, "RATINE").
dico("R", 6, "RATING").
dico("R", 6, "RATION").
dico("R", 6, "RATIOS").
dico("R", 6, "RATITE").
dico("R", 6, "RATONS").
dico("R", 6, "RATTES").
dico("R", 6, "RATURA").
dico("R", 6, "RATURE").
dico("R", 6, "RAUCHA").
dico("R", 6, "RAUCHE").
dico("R", 6, "RAUQUA").
dico("R", 6, "RAUQUE").
dico("R", 6, "RAVAGE").
dico("R", 6, "RAVALA").
dico("R", 6, "RAVALE").
dico("R", 6, "RAVALS").
dico("R", 6, "RAVERS").
dico("R", 6, "RAVEUR").
dico("R", 6, "RAVIER").
dico("R", 6, "RAVIES").
dico("R", 6, "RAVILI").
dico("R", 6, "RAVINA").
dico("R", 6, "RAVINE").
dico("R", 6, "RAVINS").
dico("R", 6, "RAVIRA").
dico("R", 6, "RAVISA").
dico("R", 6, "RAVISE").
dico("R", 6, "RAVIVA").
dico("R", 6, "RAVIVE").
dico("R", 6, "RAVOIR").
dico("R", 6, "RAYAGE").
dico("R", 6, "RAYAIS").
dico("R", 6, "RAYAIT").
dico("R", 6, "RAYANT").
dico("R", 6, "RAYEES").
dico("R", 6, "RAYENT").
dico("R", 6, "RAYERA").
dico("R", 6, "RAYERE").
dico("R", 6, "RAYIAS").
dico("R", 6, "RAYIEZ").
dico("R", 6, "RAYONS").
dico("R", 6, "RAYURE").
dico("R", 6, "RAZZIA").
dico("R", 6, "RAZZIE").
dico("R", 6, "RBATIE").
dico("R", 6, "RBATIS").
dico("R", 6, "REAGIR").
dico("R", 6, "REAGIS").
dico("R", 6, "REAGIT").
dico("R", 6, "REALES").
dico("R", 6, "REAMES").
dico("R", 6, "REARMA").
dico("R", 6, "REARME").
dico("R", 6, "REASSE").
dico("R", 6, "REATES").
dico("R", 6, "REBABS").
dico("R", 6, "REBATI").
dico("R", 6, "REBATS").
dico("R", 6, "REBECS").
dico("R", 6, "REBIBE").
dico("R", 6, "REBOIS").
dico("R", 6, "REBOIT").
dico("R", 6, "REBOND").
dico("R", 6, "REBORD").
dico("R", 6, "REBOTS").
dico("R", 6, "REBRAS").
dico("R", 6, "REBUES").
dico("R", 6, "REBUSE").
dico("R", 6, "REBUTA").
dico("R", 6, "REBUTE").
dico("R", 6, "REBUTS").
dico("R", 6, "RECALA").
dico("R", 6, "RECALE").
dico("R", 6, "RECASA").
dico("R", 6, "RECASE").
dico("R", 6, "RECAVA").
dico("R", 6, "RECAVE").
dico("R", 6, "RECEDA").
dico("R", 6, "RECEDE").
dico("R", 6, "RECELA").
dico("R", 6, "RECELE").
dico("R", 6, "RECELS").
dico("R", 6, "RECENT").
dico("R", 6, "RECEPA").
dico("R", 6, "RECEPE").
dico("R", 6, "RECHES").
dico("R", 6, "RECIFS").
dico("R", 6, "RECITA").
dico("R", 6, "RECITE").
dico("R", 6, "RECITS").
dico("R", 6, "RECLUS").
dico("R", 6, "RECOIN").
dico("R", 6, "RECOIS").
dico("R", 6, "RECOIT").
dico("R", 6, "RECOLA").
dico("R", 6, "RECOLE").
dico("R", 6, "RECORD").
dico("R", 6, "RECORS").
dico("R", 6, "RECOUD").
dico("R", 6, "RECREA").
dico("R", 6, "RECREE").
dico("R", 6, "RECRES").
dico("R", 6, "RECRIA").
dico("R", 6, "RECRIE").
dico("R", 6, "RECRIS").
dico("R", 6, "RECRIT").
dico("R", 6, "RECRUE").
dico("R", 6, "RECRUS").
dico("R", 6, "RECRUT").
dico("R", 6, "RECTAL").
dico("R", 6, "RECTOS").
dico("R", 6, "RECTUM").
dico("R", 6, "RECUES").
dico("R", 6, "RECUIS").
dico("R", 6, "RECUIT").
dico("R", 6, "RECULA").
dico("R", 6, "RECULE").
dico("R", 6, "RECULS").
dico("R", 6, "RECUPS").
dico("R", 6, "RECURA").
dico("R", 6, "RECURE").
dico("R", 6, "RECUSA").
dico("R", 6, "RECUSE").
dico("R", 6, "REDANS").
dico("R", 6, "REDENT").
dico("R", 6, "REDIES").
dico("R", 6, "REDIGE").
dico("R", 6, "REDIMA").
dico("R", 6, "REDIME").
dico("R", 6, "REDIRA").
dico("R", 6, "REDIRE").
dico("R", 6, "REDISE").
dico("R", 6, "REDITE").
dico("R", 6, "REDITS").
dico("R", 6, "REDOIS").
dico("R", 6, "REDOIT").
dico("R", 6, "REDORA").
dico("R", 6, "REDORE").
dico("R", 6, "REDORS").
dico("R", 6, "REDORT").
dico("R", 6, "REDOUL").
dico("R", 6, "REDOUX").
dico("R", 6, "REDOWA").
dico("R", 6, "REDUES").
dico("R", 6, "REDUIS").
dico("R", 6, "REDUIT").
dico("R", 6, "REDUVE").
dico("R", 6, "REELIS").
dico("R", 6, "REELIT").
dico("R", 6, "REELLE").
dico("R", 6, "REELUE").
dico("R", 6, "REELUS").
dico("R", 6, "REELUT").
dico("R", 6, "REEMET").
dico("R", 6, "REEMIS").
dico("R", 6, "REEMIT").
dico("R", 6, "REERAI").
dico("R", 6, "REERAS").
dico("R", 6, "REEREZ").
dico("R", 6, "REFAIS").
dico("R", 6, "REFAIT").
dico("R", 6, "REFEND").
dico("R", 6, "REFERA").
dico("R", 6, "REFERE").
dico("R", 6, "REFILA").
dico("R", 6, "REFILE").
dico("R", 6, "REFIXA").
dico("R", 6, "REFIXE").
dico("R", 6, "REFLET").
dico("R", 6, "REFLEX").
dico("R", 6, "REFLUA").
dico("R", 6, "REFLUE").
dico("R", 6, "REFLUX").
dico("R", 6, "REFOND").
dico("R", 6, "REFONT").
dico("R", 6, "REFOUS").
dico("R", 6, "REFOUT").
dico("R", 6, "REFUGE").
dico("R", 6, "REFUMA").
dico("R", 6, "REFUME").
dico("R", 6, "REFUSA").
dico("R", 6, "REFUSE").
dico("R", 6, "REFUTA").
dico("R", 6, "REFUTE").
dico("R", 6, "REGAIN").
dico("R", 6, "REGALA").
dico("R", 6, "REGALE").
dico("R", 6, "REGALS").
dico("R", 6, "REGARD").
dico("R", 6, "REGATA").
dico("R", 6, "REGATE").
dico("R", 6, "REGELA").
dico("R", 6, "REGELE").
dico("R", 6, "REGELS").
dico("R", 6, "REGENT").
dico("R", 6, "REGGAE").
dico("R", 6, "REGIES").
dico("R", 6, "REGIME").
dico("R", 6, "REGION").
dico("R", 6, "REGIRA").
dico("R", 6, "REGLAI").
dico("R", 6, "REGLAS").
dico("R", 6, "REGLAT").
dico("R", 6, "REGLEE").
dico("R", 6, "REGLER").
dico("R", 6, "REGLES").
dico("R", 6, "REGLET").
dico("R", 6, "REGLEZ").
dico("R", 6, "REGLOS").
dico("R", 6, "REGNAI").
dico("R", 6, "REGNAS").
dico("R", 6, "REGNAT").
dico("R", 6, "REGNER").
dico("R", 6, "REGNES").
dico("R", 6, "REGNEZ").
dico("R", 6, "REGNIE").
dico("R", 6, "REGRAT").
dico("R", 6, "REGREA").
dico("R", 6, "REGREE").
dico("R", 6, "REGRET").
dico("R", 6, "REGROS").
dico("R", 6, "REGULA").
dico("R", 6, "REGULE").
dico("R", 6, "REGURS").
dico("R", 6, "REHAUT").
dico("R", 6, "REIFIA").
dico("R", 6, "REIFIE").
dico("R", 6, "REINES").
dico("R", 6, "REIONS").
dico("R", 6, "REITRE").
dico("R", 6, "REJETA").
dico("R", 6, "REJETE").
dico("R", 6, "REJETS").
dico("R", 6, "REJOUA").
dico("R", 6, "REJOUE").
dico("R", 6, "REJOUI").
dico("R", 6, "REJUGE").
dico("R", 6, "RELACA").
dico("R", 6, "RELACE").
dico("R", 6, "RELAIE").
dico("R", 6, "RELAIS").
dico("R", 6, "RELAPS").
dico("R", 6, "RELATA").
dico("R", 6, "RELATE").
dico("R", 6, "RELAVA").
dico("R", 6, "RELAVE").
dico("R", 6, "RELAXA").
dico("R", 6, "RELAXE").
dico("R", 6, "RELAYA").
dico("R", 6, "RELAYE").
dico("R", 6, "RELENT").
dico("R", 6, "RELEVA").
dico("R", 6, "RELEVE").
dico("R", 6, "RELIAI").
dico("R", 6, "RELIAS").
dico("R", 6, "RELIAT").
dico("R", 6, "RELIEE").
dico("R", 6, "RELIEF").
dico("R", 6, "RELIER").
dico("R", 6, "RELIES").
dico("R", 6, "RELIEZ").
dico("R", 6, "RELIRA").
dico("R", 6, "RELIRE").
dico("R", 6, "RELISE").
dico("R", 6, "RELISH").
dico("R", 6, "RELOGE").
dico("R", 6, "RELOUA").
dico("R", 6, "RELOUE").
dico("R", 6, "RELUES").
dico("R", 6, "RELUIS").
dico("R", 6, "RELUIT").
dico("R", 6, "REMAKE").
dico("R", 6, "REMEDE").
dico("R", 6, "REMELA").
dico("R", 6, "REMELE").
dico("R", 6, "REMERE").
dico("R", 6, "REMETS").
dico("R", 6, "REMIGE").
dico("R", 6, "REMISA").
dico("R", 6, "REMISE").
dico("R", 6, "REMIXA").
dico("R", 6, "REMIXE").
dico("R", 6, "REMOIS").
dico("R", 6, "REMORA").
dico("R", 6, "REMORD").
dico("R", 6, "REMOUD").
dico("R", 6, "REMOUS").
dico("R", 6, "REMPLI").
dico("R", 6, "REMUAI").
dico("R", 6, "REMUAS").
dico("R", 6, "REMUAT").
dico("R", 6, "REMUEE").
dico("R", 6, "REMUER").
dico("R", 6, "REMUES").
dico("R", 6, "REMUEZ").
dico("R", 6, "RENAIS").
dico("R", 6, "RENAIT").
dico("R", 6, "RENALE").
dico("R", 6, "RENARD").
dico("R", 6, "RENAUX").
dico("R", 6, "RENDES").
dico("R", 6, "RENDEZ").
dico("R", 6, "RENDIS").
dico("R", 6, "RENDIT").
dico("R", 6, "RENDRA").
dico("R", 6, "RENDRE").
dico("R", 6, "RENDUE").
dico("R", 6, "RENDUS").
dico("R", 6, "RENFLA").
dico("R", 6, "RENFLE").
dico("R", 6, "RENIAI").
dico("R", 6, "RENIAS").
dico("R", 6, "RENIAT").
dico("R", 6, "RENIEE").
dico("R", 6, "RENIER").
dico("R", 6, "RENIES").
dico("R", 6, "RENIEZ").
dico("R", 6, "RENINE").
dico("R", 6, "RENNES").
dico("R", 6, "RENOMS").
dico("R", 6, "RENONS").
dico("R", 6, "RENOTA").
dico("R", 6, "RENOTE").
dico("R", 6, "RENOUA").
dico("R", 6, "RENOUE").
dico("R", 6, "RENOVA").
dico("R", 6, "RENOVE").
dico("R", 6, "RENTAI").
dico("R", 6, "RENTAS").
dico("R", 6, "RENTAT").
dico("R", 6, "RENTEE").
dico("R", 6, "RENTER").
dico("R", 6, "RENTES").
dico("R", 6, "RENTEZ").
dico("R", 6, "RENTRA").
dico("R", 6, "RENTRE").
dico("R", 6, "RENVOI").
dico("R", 6, "REPAIE").
dico("R", 6, "REPAIS").
dico("R", 6, "REPAIT").
dico("R", 6, "REPAND").
dico("R", 6, "REPARA").
dico("R", 6, "REPARE").
dico("R", 6, "REPARS").
dico("R", 6, "REPART").
dico("R", 6, "REPARU").
dico("R", 6, "REPAVA").
dico("R", 6, "REPAVE").
dico("R", 6, "REPAYA").
dico("R", 6, "REPAYE").
dico("R", 6, "REPEND").
dico("R", 6, "REPENS").
dico("R", 6, "REPENT").
dico("R", 6, "REPERA").
dico("R", 6, "REPERD").
dico("R", 6, "REPERE").
dico("R", 6, "REPESA").
dico("R", 6, "REPESE").
dico("R", 6, "REPETA").
dico("R", 6, "REPETE").
dico("R", 6, "REPICS").
dico("R", 6, "REPITS").
dico("R", 6, "REPLAT").
dico("R", 6, "REPLET").
dico("R", 6, "REPLIA").
dico("R", 6, "REPLIE").
dico("R", 6, "REPLIS").
dico("R", 6, "REPLUT").
dico("R", 6, "REPOLI").
dico("R", 6, "REPOND").
dico("R", 6, "REPONS").
dico("R", 6, "REPORT").
dico("R", 6, "REPOSA").
dico("R", 6, "REPOSE").
dico("R", 6, "REPRIS").
dico("R", 6, "REPRIT").
dico("R", 6, "REPUES").
dico("R", 6, "REPUTA").
dico("R", 6, "REPUTE").
dico("R", 6, "REQUIN").
dico("R", 6, "REQUIS").
dico("R", 6, "REQUIT").
dico("R", 6, "RESALA").
dico("R", 6, "RESALE").
dico("R", 6, "RESALI").
dico("R", 6, "RESEAU").
dico("R", 6, "RESEDA").
dico("R", 6, "RESEMA").
dico("R", 6, "RESEME").
dico("R", 6, "RESIDA").
dico("R", 6, "RESIDE").
dico("R", 6, "RESIDU").
dico("R", 6, "RESINA").
dico("R", 6, "RESINE").
dico("R", 6, "RESOLU").
dico("R", 6, "RESOUS").
dico("R", 6, "RESOUT").
dico("R", 6, "RESSAC").
dico("R", 6, "RESSAT").
dico("R", 6, "RESSUA").
dico("R", 6, "RESSUE").
dico("R", 6, "RESSUI").
dico("R", 6, "RESTAI").
dico("R", 6, "RESTAS").
dico("R", 6, "RESTAT").
dico("R", 6, "RESTAU").
dico("R", 6, "RESTEE").
dico("R", 6, "RESTER").
dico("R", 6, "RESTES").
dico("R", 6, "RESTEZ").
dico("R", 6, "RESTOS").
dico("R", 6, "RESUMA").
dico("R", 6, "RESUME").
dico("R", 6, "RETAIS").
dico("R", 6, "RETAMA").
dico("R", 6, "RETAME").
dico("R", 6, "RETAPA").
dico("R", 6, "RETAPE").
dico("R", 6, "RETARD").
dico("R", 6, "RETATA").
dico("R", 6, "RETATE").
dico("R", 6, "RETAXA").
dico("R", 6, "RETAXE").
dico("R", 6, "RETEND").
dico("R", 6, "RETENU").
dico("R", 6, "RETIFS").
dico("R", 6, "RETIGE").
dico("R", 6, "RETINE").
dico("R", 6, "RETINS").
dico("R", 6, "RETINT").
dico("R", 6, "RETIRA").
dico("R", 6, "RETIRE").
dico("R", 6, "RETIVE").
dico("R", 6, "RETOND").
dico("R", 6, "RETORD").
dico("R", 6, "RETORS").
dico("R", 6, "RETOUR").
dico("R", 6, "RETROS").
dico("R", 6, "RETUBA").
dico("R", 6, "RETUBE").
dico("R", 6, "REUNIE").
dico("R", 6, "REUNIR").
dico("R", 6, "REUNIS").
dico("R", 6, "REUNIT").
dico("R", 6, "REUSSI").
dico("R", 6, "REVAIS").
dico("R", 6, "REVAIT").
dico("R", 6, "REVALU").
dico("R", 6, "REVANT").
dico("R", 6, "REVAUT").
dico("R", 6, "REVAUX").
dico("R", 6, "REVECU").
dico("R", 6, "REVEES").
dico("R", 6, "REVEIL").
dico("R", 6, "REVELA").
dico("R", 6, "REVELE").
dico("R", 6, "REVEND").
dico("R", 6, "REVENT").
dico("R", 6, "REVENU").
dico("R", 6, "REVERA").
dico("R", 6, "REVERE").
dico("R", 6, "REVERS").
dico("R", 6, "REVETE").
dico("R", 6, "REVETS").
dico("R", 6, "REVETU").
dico("R", 6, "REVEUR").
dico("R", 6, "REVEUT").
dico("R", 6, "REVEUX").
dico("R", 6, "REVIEZ").
dico("R", 6, "REVIFS").
dico("R", 6, "REVINS").
dico("R", 6, "REVINT").
dico("R", 6, "REVIRA").
dico("R", 6, "REVIRE").
dico("R", 6, "REVISA").
dico("R", 6, "REVISE").
dico("R", 6, "REVIVE").
dico("R", 6, "REVOIE").
dico("R", 6, "REVOIR").
dico("R", 6, "REVOIS").
dico("R", 6, "REVOIT").
dico("R", 6, "REVOLA").
dico("R", 6, "REVOLE").
dico("R", 6, "REVOLU").
dico("R", 6, "REVONS").
dico("R", 6, "REVOTA").
dico("R", 6, "REVOTE").
dico("R", 6, "REVUES").
dico("R", 6, "REZZOU").
dico("R", 6, "RHEMES").
dico("R", 6, "RHENAN").
dico("R", 6, "RHESUS").
dico("R", 6, "RHETOS").
dico("R", 6, "RHODIA").
dico("R", 6, "RHODIE").
dico("R", 6, "RHOMBE").
dico("R", 6, "RHOVYL").
dico("R", 6, "RHUMAI").
dico("R", 6, "RHUMAS").
dico("R", 6, "RHUMAT").
dico("R", 6, "RHUMBS").
dico("R", 6, "RHUMEE").
dico("R", 6, "RHUMER").
dico("R", 6, "RHUMES").
dico("R", 6, "RHUMEZ").
dico("R", 6, "RHYTON").
dico("R", 6, "RIANTE").
dico("R", 6, "RIANTS").
dico("R", 6, "RIBATS").
dico("R", 6, "RIBAUD").
dico("R", 6, "RIBLAI").
dico("R", 6, "RIBLAS").
dico("R", 6, "RIBLAT").
dico("R", 6, "RIBLEE").
dico("R", 6, "RIBLER").
dico("R", 6, "RIBLES").
dico("R", 6, "RIBLEZ").
dico("R", 6, "RIBLON").
dico("R", 6, "RIBORD").
dico("R", 6, "RIBOSE").
dico("R", 6, "RIBOTE").
dico("R", 6, "RICAIN").
dico("R", 6, "RICANA").
dico("R", 6, "RICANE").
dico("R", 6, "RICARD").
dico("R", 6, "RICCIE").
dico("R", 6, "RICHES").
dico("R", 6, "RICHIS").
dico("R", 6, "RICINE").
dico("R", 6, "RICINS").
dico("R", 6, "RICTUS").
dico("R", 6, "RIDAGE").
dico("R", 6, "RIDAIS").
dico("R", 6, "RIDAIT").
dico("R", 6, "RIDANT").
dico("R", 6, "RIDEAU").
dico("R", 6, "RIDEES").
dico("R", 6, "RIDENT").
dico("R", 6, "RIDERA").
dico("R", 6, "RIDIEZ").
dico("R", 6, "RIDOIR").
dico("R", 6, "RIDONS").
dico("R", 6, "RIDULE").
dico("R", 6, "RIEURS").
dico("R", 6, "RIEUSE").
dico("R", 6, "RIFAIN").
dico("R", 6, "RIFFES").
dico("R", 6, "RIFFLE").
dico("R", 6, "RIFIFI").
dico("R", 6, "RIFLAI").
dico("R", 6, "RIFLAS").
dico("R", 6, "RIFLAT").
dico("R", 6, "RIFLEE").
dico("R", 6, "RIFLER").
dico("R", 6, "RIFLES").
dico("R", 6, "RIFLEZ").
dico("R", 6, "RIGIDE").
dico("R", 6, "RIGOLA").
dico("R", 6, "RIGOLE").
dico("R", 6, "RIGOLO").
dico("R", 6, "RIIONS").
dico("R", 6, "RIKIKI").
dico("R", 6, "RILSAN").
dico("R", 6, "RIMAIS").
dico("R", 6, "RIMAIT").
dico("R", 6, "RIMANT").
dico("R", 6, "RIMAYE").
dico("R", 6, "RIMEES").
dico("R", 6, "RIMENT").
dico("R", 6, "RIMERA").
dico("R", 6, "RIMEUR").
dico("R", 6, "RIMIEZ").
dico("R", 6, "RIMMEL").
dico("R", 6, "RIMONS").
dico("R", 6, "RINCAI").
dico("R", 6, "RINCAS").
dico("R", 6, "RINCAT").
dico("R", 6, "RINCEE").
dico("R", 6, "RINCER").
dico("R", 6, "RINCES").
dico("R", 6, "RINCEZ").
dico("R", 6, "RIOJAS").
dico("R", 6, "RIOTAI").
dico("R", 6, "RIOTAS").
dico("R", 6, "RIOTAT").
dico("R", 6, "RIOTER").
dico("R", 6, "RIOTES").
dico("R", 6, "RIOTEZ").
dico("R", 6, "RIPAGE").
dico("R", 6, "RIPAIS").
dico("R", 6, "RIPAIT").
dico("R", 6, "RIPANT").
dico("R", 6, "RIPEES").
dico("R", 6, "RIPENT").
dico("R", 6, "RIPERA").
dico("R", 6, "RIPIEZ").
dico("R", 6, "RIPONS").
dico("R", 6, "RIPOUS").
dico("R", 6, "RIPOUX").
dico("R", 6, "RIPPER").
dico("R", 6, "RIRAIS").
dico("R", 6, "RIRAIT").
dico("R", 6, "RIRENT").
dico("R", 6, "RIRIEZ").
dico("R", 6, "RIRONS").
dico("R", 6, "RIRONT").
dico("R", 6, "RISBAN").
dico("R", 6, "RISEES").
dico("R", 6, "RISERS").
dico("R", 6, "RISHIS").
dico("R", 6, "RISQUA").
dico("R", 6, "RISQUE").
dico("R", 6, "RISSES").
dico("R", 6, "RITALE").
dico("R", 6, "RITALS").
dico("R", 6, "RITUEL").
dico("R", 6, "RIVAGE").
dico("R", 6, "RIVAIS").
dico("R", 6, "RIVAIT").
dico("R", 6, "RIVALE").
dico("R", 6, "RIVANT").
dico("R", 6, "RIVAUX").
dico("R", 6, "RIVEES").
dico("R", 6, "RIVENT").
dico("R", 6, "RIVERA").
dico("R", 6, "RIVETA").
dico("R", 6, "RIVETE").
dico("R", 6, "RIVETS").
dico("R", 6, "RIVEUR").
dico("R", 6, "RIVIEZ").
dico("R", 6, "RIVOIR").
dico("R", 6, "RIVONS").
dico("R", 6, "RIVURE").
dico("R", 6, "RIYALS").
dico("R", 6, "ROBAGE").
dico("R", 6, "ROBAIS").
dico("R", 6, "ROBAIT").
dico("R", 6, "ROBANT").
dico("R", 6, "ROBEES").
dico("R", 6, "ROBENT").
dico("R", 6, "ROBERA").
dico("R", 6, "ROBERT").
dico("R", 6, "ROBIEZ").
dico("R", 6, "ROBINE").
dico("R", 6, "ROBINS").
dico("R", 6, "ROBONS").
dico("R", 6, "ROBOTS").
dico("R", 6, "ROBRES").
dico("R", 6, "ROCADE").
dico("R", 6, "ROCHAI").
dico("R", 6, "ROCHAS").
dico("R", 6, "ROCHAT").
dico("R", 6, "ROCHEE").
dico("R", 6, "ROCHER").
dico("R", 6, "ROCHES").
dico("R", 6, "ROCHET").
dico("R", 6, "ROCHEZ").
dico("R", 6, "ROCKER").
dico("R", 6, "ROCKET").
dico("R", 6, "ROCOCO").
dico("R", 6, "ROCOUA").
dico("R", 6, "ROCOUE").
dico("R", 6, "ROCOUS").
dico("R", 6, "RODAGE").
dico("R", 6, "RODAIS").
dico("R", 6, "RODAIT").
dico("R", 6, "RODANT").
dico("R", 6, "RODEES").
dico("R", 6, "RODENT").
dico("R", 6, "RODEOS").
dico("R", 6, "RODERA").
dico("R", 6, "RODEUR").
dico("R", 6, "RODIEZ").
dico("R", 6, "RODOIR").
dico("R", 6, "RODONS").
dico("R", 6, "ROESTI").
dico("R", 6, "ROGNAI").
dico("R", 6, "ROGNAS").
dico("R", 6, "ROGNAT").
dico("R", 6, "ROGNEE").
dico("R", 6, "ROGNER").
dico("R", 6, "ROGNES").
dico("R", 6, "ROGNEZ").
dico("R", 6, "ROGNON").
dico("R", 6, "ROGUEE").
dico("R", 6, "ROGUES").
dico("R", 6, "ROHART").
dico("R", 6, "ROIDES").
dico("R", 6, "ROIDIE").
dico("R", 6, "ROIDIR").
dico("R", 6, "ROIDIS").
dico("R", 6, "ROIDIT").
dico("R", 6, "ROILLA").
dico("R", 6, "ROILLE").
dico("R", 6, "ROLAGE").
dico("R", 6, "ROLLER").
dico("R", 6, "ROLLOT").
dico("R", 6, "ROMAIN").
dico("R", 6, "ROMAND").
dico("R", 6, "ROMANE").
dico("R", 6, "ROMANI").
dico("R", 6, "ROMANO").
dico("R", 6, "ROMANS").
dico("R", 6, "ROMPES").
dico("R", 6, "ROMPEZ").
dico("R", 6, "ROMPIS").
dico("R", 6, "ROMPIT").
dico("R", 6, "ROMPRA").
dico("R", 6, "ROMPRE").
dico("R", 6, "ROMPUE").
dico("R", 6, "ROMPUS").
dico("R", 6, "RONCES").
dico("R", 6, "RONDEL").
dico("R", 6, "RONDES").
dico("R", 6, "RONDIE").
dico("R", 6, "RONDIN").
dico("R", 6, "RONDIR").
dico("R", 6, "RONDIS").
dico("R", 6, "RONDIT").
dico("R", 6, "RONDOS").
dico("R", 6, "RONEOS").
dico("R", 6, "RONFLA").
dico("R", 6, "RONFLE").
dico("R", 6, "RONGEA").
dico("R", 6, "RONGEE").
dico("R", 6, "RONGER").
dico("R", 6, "RONGES").
dico("R", 6, "RONGEZ").
dico("R", 6, "RONIER").
dico("R", 6, "RONINS").
dico("R", 6, "RONRON").
dico("R", 6, "ROOTER").
dico("R", 6, "ROQUAI").
dico("R", 6, "ROQUAS").
dico("R", 6, "ROQUAT").
dico("R", 6, "ROQUER").
dico("R", 6, "ROQUES").
dico("R", 6, "ROQUET").
dico("R", 6, "ROQUEZ").
dico("R", 6, "ROSACE").
dico("R", 6, "ROSAGE").
dico("R", 6, "ROSAIS").
dico("R", 6, "ROSAIT").
dico("R", 6, "ROSANT").
dico("R", 6, "ROSBIF").
dico("R", 6, "ROSEAU").
dico("R", 6, "ROSEES").
dico("R", 6, "ROSENT").
dico("R", 6, "ROSERA").
dico("R", 6, "ROSEUR").
dico("R", 6, "ROSIER").
dico("R", 6, "ROSIES").
dico("R", 6, "ROSIEZ").
dico("R", 6, "ROSIRA").
dico("R", 6, "ROSONS").
dico("R", 6, "ROSSAI").
dico("R", 6, "ROSSAS").
dico("R", 6, "ROSSAT").
dico("R", 6, "ROSSEE").
dico("R", 6, "ROSSER").
dico("R", 6, "ROSSES").
dico("R", 6, "ROSSEZ").
dico("R", 6, "ROSTIS").
dico("R", 6, "ROSTRE").
dico("R", 6, "ROTACE").
dico("R", 6, "ROTAIS").
dico("R", 6, "ROTAIT").
dico("R", 6, "ROTANG").
dico("R", 6, "ROTANT").
dico("R", 6, "ROTARY").
dico("R", 6, "ROTENT").
dico("R", 6, "ROTERA").
dico("R", 6, "ROTEUR").
dico("R", 6, "ROTIES").
dico("R", 6, "ROTIEZ").
dico("R", 6, "ROTINS").
dico("R", 6, "ROTIRA").
dico("R", 6, "ROTONS").
dico("R", 6, "ROTORS").
dico("R", 6, "ROTOTO").
dico("R", 6, "ROTULE").
dico("R", 6, "ROTURE").
dico("R", 6, "ROUAGE").
dico("R", 6, "ROUAIS").
dico("R", 6, "ROUAIT").
dico("R", 6, "ROUANS").
dico("R", 6, "ROUANT").
dico("R", 6, "ROUBLA").
dico("R", 6, "ROUBLE").
dico("R", 6, "ROUCHI").
dico("R", 6, "ROUEES").
dico("R", 6, "ROUENT").
dico("R", 6, "ROUERA").
dico("R", 6, "ROUETS").
dico("R", 6, "ROUGES").
dico("R", 6, "ROUGET").
dico("R", 6, "ROUGHS").
dico("R", 6, "ROUGIE").
dico("R", 6, "ROUGIR").
dico("R", 6, "ROUGIS").
dico("R", 6, "ROUGIT").
dico("R", 6, "ROUIES").
dico("R", 6, "ROUIEZ").
dico("R", 6, "ROUIRA").
dico("R", 6, "ROULAI").
dico("R", 6, "ROULAS").
dico("R", 6, "ROULAT").
dico("R", 6, "ROULEE").
dico("R", 6, "ROULER").
dico("R", 6, "ROULES").
dico("R", 6, "ROULEZ").
dico("R", 6, "ROULIS").
dico("R", 6, "ROUMIE").
dico("R", 6, "ROUMIS").
dico("R", 6, "ROUNDS").
dico("R", 6, "ROUONS").
dico("R", 6, "ROUPIE").
dico("R", 6, "ROUSSE").
dico("R", 6, "ROUSSI").
dico("R", 6, "ROUSTE").
dico("R", 6, "ROUSTI").
dico("R", 6, "ROUTAI").
dico("R", 6, "ROUTAS").
dico("R", 6, "ROUTAT").
dico("R", 6, "ROUTEE").
dico("R", 6, "ROUTER").
dico("R", 6, "ROUTES").
dico("R", 6, "ROUTEZ").
dico("R", 6, "ROUVRE").
dico("R", 6, "ROWING").
dico("R", 6, "ROYALE").
dico("R", 6, "ROYAUX").
dico("R", 6, "RUADES").
dico("R", 6, "RUAMES").
dico("R", 6, "RUASSE").
dico("R", 6, "RUATES").
dico("R", 6, "RUBANA").
dico("R", 6, "RUBANE").
dico("R", 6, "RUBANS").
dico("R", 6, "RUBATO").
dico("R", 6, "RUBINE").
dico("R", 6, "RUCHAI").
dico("R", 6, "RUCHAS").
dico("R", 6, "RUCHAT").
dico("R", 6, "RUCHEE").
dico("R", 6, "RUCHER").
dico("R", 6, "RUCHES").
dico("R", 6, "RUCHEZ").
dico("R", 6, "RUCLON").
dico("R", 6, "RUDOIE").
dico("R", 6, "RUDOYA").
dico("R", 6, "RUDOYE").
dico("R", 6, "RUELLE").
dico("R", 6, "RUERAI").
dico("R", 6, "RUERAS").
dico("R", 6, "RUEREZ").
dico("R", 6, "RUFIAN").
dico("R", 6, "RUGBYS").
dico("R", 6, "RUGIES").
dico("R", 6, "RUGINA").
dico("R", 6, "RUGINE").
dico("R", 6, "RUGIRA").
dico("R", 6, "RUILAI").
dico("R", 6, "RUILAS").
dico("R", 6, "RUILAT").
dico("R", 6, "RUILEE").
dico("R", 6, "RUILER").
dico("R", 6, "RUILES").
dico("R", 6, "RUILEZ").
dico("R", 6, "RUINAI").
dico("R", 6, "RUINAS").
dico("R", 6, "RUINAT").
dico("R", 6, "RUINEE").
dico("R", 6, "RUINER").
dico("R", 6, "RUINES").
dico("R", 6, "RUINEZ").
dico("R", 6, "RUIONS").
dico("R", 6, "RUMBAS").
dico("R", 6, "RUMENS").
dico("R", 6, "RUMEUR").
dico("R", 6, "RUMINA").
dico("R", 6, "RUMINE").
dico("R", 6, "RUPAIS").
dico("R", 6, "RUPAIT").
dico("R", 6, "RUPANT").
dico("R", 6, "RUPEES").
dico("R", 6, "RUPENT").
dico("R", 6, "RUPERA").
dico("R", 6, "RUPIAH").
dico("R", 6, "RUPIEZ").
dico("R", 6, "RUPINA").
dico("R", 6, "RUPINE").
dico("R", 6, "RUPINS").
dico("R", 6, "RUPONS").
dico("R", 6, "RURALE").
dico("R", 6, "RURAUX").
dico("R", 6, "RUSAIS").
dico("R", 6, "RUSAIT").
dico("R", 6, "RUSANT").
dico("R", 6, "RUSEES").
dico("R", 6, "RUSENT").
dico("R", 6, "RUSERA").
dico("R", 6, "RUSHES").
dico("R", 6, "RUSIEZ").
dico("R", 6, "RUSONS").
dico("R", 6, "RUSSES").
dico("R", 6, "RUSTRE").
dico("R", 6, "RUTILA").
dico("R", 6, "RUTILE").
dico("R", 6, "RUTINE").
dico("R", 6, "RYTHMA").
dico("R", 6, "RYTHME").
