dico("R", 7, "RABACHA").
dico("R", 7, "RABACHE").
dico("R", 7, "RABANES").
dico("R", 7, "RABATTE").
dico("R", 7, "RABATTU").
dico("R", 7, "RABBINS").
dico("R", 7, "RABIOTA").
dico("R", 7, "RABIOTE").
dico("R", 7, "RABIOTS").
dico("R", 7, "RABIQUE").
dico("R", 7, "RABLAIS").
dico("R", 7, "RABLAIT").
dico("R", 7, "RABLANT").
dico("R", 7, "RABLEES").
dico("R", 7, "RABLENT").
dico("R", 7, "RABLERA").
dico("R", 7, "RABLIEZ").
dico("R", 7, "RABLONS").
dico("R", 7, "RABLURE").
dico("R", 7, "RABONNI").
dico("R", 7, "RABOTAI").
dico("R", 7, "RABOTAS").
dico("R", 7, "RABOTAT").
dico("R", 7, "RABOTEE").
dico("R", 7, "RABOTER").
dico("R", 7, "RABOTES").
dico("R", 7, "RABOTEZ").
dico("R", 7, "RABOUTA").
dico("R", 7, "RABOUTE").
dico("R", 7, "RABROUA").
dico("R", 7, "RABROUE").
dico("R", 7, "RACAGES").
dico("R", 7, "RACCARD").
dico("R", 7, "RACCORD").
dico("R", 7, "RACCROC").
dico("R", 7, "RACCUSA").
dico("R", 7, "RACCUSE").
dico("R", 7, "RACHATS").
dico("R", 7, "RACHETA").
dico("R", 7, "RACHETE").
dico("R", 7, "RACIALE").
dico("R", 7, "RACIAUX").
dico("R", 7, "RACINAI").
dico("R", 7, "RACINAL").
dico("R", 7, "RACINAS").
dico("R", 7, "RACINAT").
dico("R", 7, "RACINEE").
dico("R", 7, "RACINER").
dico("R", 7, "RACINES").
dico("R", 7, "RACINEZ").
dico("R", 7, "RACISME").
dico("R", 7, "RACISTE").
dico("R", 7, "RACKETS").
dico("R", 7, "RACLAGE").
dico("R", 7, "RACLAIS").
dico("R", 7, "RACLAIT").
dico("R", 7, "RACLANT").
dico("R", 7, "RACLEES").
dico("R", 7, "RACLENT").
dico("R", 7, "RACLERA").
dico("R", 7, "RACLEUR").
dico("R", 7, "RACLIEZ").
dico("R", 7, "RACLOIR").
dico("R", 7, "RACLONS").
dico("R", 7, "RACLURE").
dico("R", 7, "RACOLAI").
dico("R", 7, "RACOLAS").
dico("R", 7, "RACOLAT").
dico("R", 7, "RACOLEE").
dico("R", 7, "RACOLER").
dico("R", 7, "RACOLES").
dico("R", 7, "RACOLEZ").
dico("R", 7, "RACONTA").
dico("R", 7, "RACONTE").
dico("R", 7, "RACOONS").
dico("R", 7, "RACORNI").
dico("R", 7, "RADAMES").
dico("R", 7, "RADASSE").
dico("R", 7, "RADATES").
dico("R", 7, "RADEAUX").
dico("R", 7, "RADERAI").
dico("R", 7, "RADERAS").
dico("R", 7, "RADEREZ").
dico("R", 7, "RADEUSE").
dico("R", 7, "RADIAIS").
dico("R", 7, "RADIAIT").
dico("R", 7, "RADIALE").
dico("R", 7, "RADIANS").
dico("R", 7, "RADIANT").
dico("R", 7, "RADIAUX").
dico("R", 7, "RADICAL").
dico("R", 7, "RADIEES").
dico("R", 7, "RADIENT").
dico("R", 7, "RADIERA").
dico("R", 7, "RADIERS").
dico("R", 7, "RADIEUX").
dico("R", 7, "RADIIEZ").
dico("R", 7, "RADINAI").
dico("R", 7, "RADINAS").
dico("R", 7, "RADINAT").
dico("R", 7, "RADINEE").
dico("R", 7, "RADINER").
dico("R", 7, "RADINES").
dico("R", 7, "RADINEZ").
dico("R", 7, "RADIONS").
dico("R", 7, "RADIUMS").
dico("R", 7, "RADJAHS").
dico("R", 7, "RADOIRE").
dico("R", 7, "RADOMES").
dico("R", 7, "RADOTAI").
dico("R", 7, "RADOTAS").
dico("R", 7, "RADOTAT").
dico("R", 7, "RADOTEE").
dico("R", 7, "RADOTER").
dico("R", 7, "RADOTES").
dico("R", 7, "RADOTEZ").
dico("R", 7, "RADOUBA").
dico("R", 7, "RADOUBE").
dico("R", 7, "RADOUBS").
dico("R", 7, "RADOUCI").
dico("R", 7, "RADSOCS").
dico("R", 7, "RADULAS").
dico("R", 7, "RAFALAI").
dico("R", 7, "RAFALAS").
dico("R", 7, "RAFALAT").
dico("R", 7, "RAFALER").
dico("R", 7, "RAFALES").
dico("R", 7, "RAFALEZ").
dico("R", 7, "RAFFINA").
dico("R", 7, "RAFFINE").
dico("R", 7, "RAFFLES").
dico("R", 7, "RAFFOLA").
dico("R", 7, "RAFFOLE").
dico("R", 7, "RAFFUTA").
dico("R", 7, "RAFFUTE").
dico("R", 7, "RAFFUTS").
dico("R", 7, "RAFIAUX").
dico("R", 7, "RAFIOTS").
dico("R", 7, "RAFLAIS").
dico("R", 7, "RAFLAIT").
dico("R", 7, "RAFLANT").
dico("R", 7, "RAFLEES").
dico("R", 7, "RAFLENT").
dico("R", 7, "RAFLERA").
dico("R", 7, "RAFLIEZ").
dico("R", 7, "RAFLONS").
dico("R", 7, "RAFTEUR").
dico("R", 7, "RAFTING").
dico("R", 7, "RAGAGES").
dico("R", 7, "RAGEAIS").
dico("R", 7, "RAGEAIT").
dico("R", 7, "RAGEANT").
dico("R", 7, "RAGEONS").
dico("R", 7, "RAGERAI").
dico("R", 7, "RAGERAS").
dico("R", 7, "RAGEREZ").
dico("R", 7, "RAGEURS").
dico("R", 7, "RAGEUSE").
dico("R", 7, "RAGIONS").
dico("R", 7, "RAGLANS").
dico("R", 7, "RAGOTES").
dico("R", 7, "RAGOUTS").
dico("R", 7, "RAGRAFA").
dico("R", 7, "RAGRAFE").
dico("R", 7, "RAGREAI").
dico("R", 7, "RAGREAS").
dico("R", 7, "RAGREAT").
dico("R", 7, "RAGREEE").
dico("R", 7, "RAGREER").
dico("R", 7, "RAGREES").
dico("R", 7, "RAGREEZ").
dico("R", 7, "RAGTIME").
dico("R", 7, "RAGUAIS").
dico("R", 7, "RAGUAIT").
dico("R", 7, "RAGUANT").
dico("R", 7, "RAGUEES").
dico("R", 7, "RAGUENT").
dico("R", 7, "RAGUERA").
dico("R", 7, "RAGUIEZ").
dico("R", 7, "RAGUONS").
dico("R", 7, "RAIDERS").
dico("R", 7, "RAIDEUR").
dico("R", 7, "RAIDIES").
dico("R", 7, "RAIDIRA").
dico("R", 7, "RAIERAI").
dico("R", 7, "RAIERAS").
dico("R", 7, "RAIEREZ").
dico("R", 7, "RAIFORT").
dico("R", 7, "RAILLAI").
dico("R", 7, "RAILLAS").
dico("R", 7, "RAILLAT").
dico("R", 7, "RAILLEE").
dico("R", 7, "RAILLER").
dico("R", 7, "RAILLES").
dico("R", 7, "RAILLEZ").
dico("R", 7, "RAINAIS").
dico("R", 7, "RAINAIT").
dico("R", 7, "RAINANT").
dico("R", 7, "RAINEES").
dico("R", 7, "RAINENT").
dico("R", 7, "RAINERA").
dico("R", 7, "RAINIEZ").
dico("R", 7, "RAINONS").
dico("R", 7, "RAINURA").
dico("R", 7, "RAINURE").
dico("R", 7, "RAIRAIS").
dico("R", 7, "RAIRAIT").
dico("R", 7, "RAIRIEZ").
dico("R", 7, "RAIRONS").
dico("R", 7, "RAIRONT").
dico("R", 7, "RAISINE").
dico("R", 7, "RAISINS").
dico("R", 7, "RAISONS").
dico("R", 7, "RAJEUNI").
dico("R", 7, "RAJOUTA").
dico("R", 7, "RAJOUTE").
dico("R", 7, "RAJOUTS").
dico("R", 7, "RAJUSTA").
dico("R", 7, "RAJUSTE").
dico("R", 7, "RALAMES").
dico("R", 7, "RALANTE").
dico("R", 7, "RALANTS").
dico("R", 7, "RALASSE").
dico("R", 7, "RALATES").
dico("R", 7, "RALENTI").
dico("R", 7, "RALERAI").
dico("R", 7, "RALERAS").
dico("R", 7, "RALEREZ").
dico("R", 7, "RALEURS").
dico("R", 7, "RALEUSE").
dico("R", 7, "RALIONS").
dico("R", 7, "RALLAIS").
dico("R", 7, "RALLAIT").
dico("R", 7, "RALLANT").
dico("R", 7, "RALLENT").
dico("R", 7, "RALLERA").
dico("R", 7, "RALLIAI").
dico("R", 7, "RALLIAS").
dico("R", 7, "RALLIAT").
dico("R", 7, "RALLIDE").
dico("R", 7, "RALLIEE").
dico("R", 7, "RALLIER").
dico("R", 7, "RALLIES").
dico("R", 7, "RALLIEZ").
dico("R", 7, "RALLONS").
dico("R", 7, "RALLUMA").
dico("R", 7, "RALLUME").
dico("R", 7, "RALLYES").
dico("R", 7, "RAMADAN").
dico("R", 7, "RAMAGEA").
dico("R", 7, "RAMAGEE").
dico("R", 7, "RAMAGER").
dico("R", 7, "RAMAGES").
dico("R", 7, "RAMAGEZ").
dico("R", 7, "RAMAMES").
dico("R", 7, "RAMASSA").
dico("R", 7, "RAMASSE").
dico("R", 7, "RAMATES").
dico("R", 7, "RAMBOUR").
dico("R", 7, "RAMDAMS").
dico("R", 7, "RAMEAUX").
dico("R", 7, "RAMENAI").
dico("R", 7, "RAMENAS").
dico("R", 7, "RAMENAT").
dico("R", 7, "RAMENDA").
dico("R", 7, "RAMENDE").
dico("R", 7, "RAMENEE").
dico("R", 7, "RAMENER").
dico("R", 7, "RAMENES").
dico("R", 7, "RAMENEZ").
dico("R", 7, "RAMERAI").
dico("R", 7, "RAMERAS").
dico("R", 7, "RAMEREZ").
dico("R", 7, "RAMEROT").
dico("R", 7, "RAMETTE").
dico("R", 7, "RAMEURS").
dico("R", 7, "RAMEUSE").
dico("R", 7, "RAMEUTA").
dico("R", 7, "RAMEUTE").
dico("R", 7, "RAMIERS").
dico("R", 7, "RAMIFIA").
dico("R", 7, "RAMIFIE").
dico("R", 7, "RAMILLE").
dico("R", 7, "RAMIONS").
dico("R", 7, "RAMOLLI").
dico("R", 7, "RAMOLLO").
dico("R", 7, "RAMONAI").
dico("R", 7, "RAMONAS").
dico("R", 7, "RAMONAT").
dico("R", 7, "RAMONEE").
dico("R", 7, "RAMONER").
dico("R", 7, "RAMONES").
dico("R", 7, "RAMONEZ").
dico("R", 7, "RAMPAIS").
dico("R", 7, "RAMPAIT").
dico("R", 7, "RAMPANT").
dico("R", 7, "RAMPEAU").
dico("R", 7, "RAMPENT").
dico("R", 7, "RAMPERA").
dico("R", 7, "RAMPIEZ").
dico("R", 7, "RAMPONS").
dico("R", 7, "RAMULES").
dico("R", 7, "RAMURES").
dico("R", 7, "RANALES").
dico("R", 7, "RANATRE").
dico("R", 7, "RANCARD").
dico("R", 7, "RANCART").
dico("R", 7, "RANCHER").
dico("R", 7, "RANCHES").
dico("R", 7, "RANCHOS").
dico("R", 7, "RANCIES").
dico("R", 7, "RANCIOS").
dico("R", 7, "RANCIRA").
dico("R", 7, "RANCONS").
dico("R", 7, "RANCUNE").
dico("R", 7, "RANGEAI").
dico("R", 7, "RANGEAS").
dico("R", 7, "RANGEAT").
dico("R", 7, "RANGEES").
dico("R", 7, "RANGENT").
dico("R", 7, "RANGERA").
dico("R", 7, "RANGERS").
dico("R", 7, "RANGIEZ").
dico("R", 7, "RANIDES").
dico("R", 7, "RANIMAI").
dico("R", 7, "RANIMAS").
dico("R", 7, "RANIMAT").
dico("R", 7, "RANIMEE").
dico("R", 7, "RANIMER").
dico("R", 7, "RANIMES").
dico("R", 7, "RANIMEZ").
dico("R", 7, "RAPACES").
dico("R", 7, "RAPAGES").
dico("R", 7, "RAPAMES").
dico("R", 7, "RAPASSE").
dico("R", 7, "RAPATES").
dico("R", 7, "RAPERAI").
dico("R", 7, "RAPERAS").
dico("R", 7, "RAPEREZ").
dico("R", 7, "RAPERIE").
dico("R", 7, "RAPEUSE").
dico("R", 7, "RAPHIAS").
dico("R", 7, "RAPHIDE").
dico("R", 7, "RAPIATE").
dico("R", 7, "RAPIATS").
dico("R", 7, "RAPIDES").
dico("R", 7, "RAPIECA").
dico("R", 7, "RAPIECE").
dico("R", 7, "RAPIERE").
dico("R", 7, "RAPINAI").
dico("R", 7, "RAPINAS").
dico("R", 7, "RAPINAT").
dico("R", 7, "RAPINEE").
dico("R", 7, "RAPINER").
dico("R", 7, "RAPINES").
dico("R", 7, "RAPINEZ").
dico("R", 7, "RAPIONS").
dico("R", 7, "RAPLATI").
dico("R", 7, "RAPPAIS").
dico("R", 7, "RAPPAIT").
dico("R", 7, "RAPPANT").
dico("R", 7, "RAPPEES").
dico("R", 7, "RAPPELA").
dico("R", 7, "RAPPELE").
dico("R", 7, "RAPPELS").
dico("R", 7, "RAPPENT").
dico("R", 7, "RAPPERA").
dico("R", 7, "RAPPERS").
dico("R", 7, "RAPPEUR").
dico("R", 7, "RAPPIEZ").
dico("R", 7, "RAPPONS").
dico("R", 7, "RAPPORT").
dico("R", 7, "RAPPRIS").
dico("R", 7, "RAPPRIT").
dico("R", 7, "RAPPUIE").
dico("R", 7, "RAPPUYA").
dico("R", 7, "RAPPUYE").
dico("R", 7, "RAPSODE").
dico("R", 7, "RAPURES").
dico("R", 7, "RAQUAIS").
dico("R", 7, "RAQUAIT").
dico("R", 7, "RAQUANT").
dico("R", 7, "RAQUEES").
dico("R", 7, "RAQUENT").
dico("R", 7, "RAQUERA").
dico("R", 7, "RAQUIEZ").
dico("R", 7, "RAQUONS").
dico("R", 7, "RAREFIA").
dico("R", 7, "RAREFIE").
dico("R", 7, "RARETES").
dico("R", 7, "RASADES").
dico("R", 7, "RASAGES").
dico("R", 7, "RASAMES").
dico("R", 7, "RASANCE").
dico("R", 7, "RASANTE").
dico("R", 7, "RASANTS").
dico("R", 7, "RASASSE").
dico("R", 7, "RASATES").
dico("R", 7, "RASERAI").
dico("R", 7, "RASERAS").
dico("R", 7, "RASEREZ").
dico("R", 7, "RASETTE").
dico("R", 7, "RASEURS").
dico("R", 7, "RASEUSE").
dico("R", 7, "RASIBUS").
dico("R", 7, "RASIONS").
dico("R", 7, "RASKOLS").
dico("R", 7, "RASOIRS").
dico("R", 7, "RASSEYE").
dico("R", 7, "RASSIED").
dico("R", 7, "RASSIES").
dico("R", 7, "RASSIRA").
dico("R", 7, "RASSISE").
dico("R", 7, "RASSOIE").
dico("R", 7, "RASSOIS").
dico("R", 7, "RASSOIT").
dico("R", 7, "RASSURA").
dico("R", 7, "RASSURE").
dico("R", 7, "RASTELS").
dico("R", 7, "RATAFIA").
dico("R", 7, "RATAGES").
dico("R", 7, "RATAMES").
dico("R", 7, "RATASSE").
dico("R", 7, "RATATES").
dico("R", 7, "RATEAUX").
dico("R", 7, "RATELAI").
dico("R", 7, "RATELAS").
dico("R", 7, "RATELAT").
dico("R", 7, "RATELEE").
dico("R", 7, "RATELER").
dico("R", 7, "RATELES").
dico("R", 7, "RATELEZ").
dico("R", 7, "RATELLE").
dico("R", 7, "RATERAI").
dico("R", 7, "RATERAS").
dico("R", 7, "RATEREZ").
dico("R", 7, "RATICHE").
dico("R", 7, "RATIERE").
dico("R", 7, "RATIERS").
dico("R", 7, "RATIFIA").
dico("R", 7, "RATIFIE").
dico("R", 7, "RATINAI").
dico("R", 7, "RATINAS").
dico("R", 7, "RATINAT").
dico("R", 7, "RATINEE").
dico("R", 7, "RATINER").
dico("R", 7, "RATINES").
dico("R", 7, "RATINEZ").
dico("R", 7, "RATINGS").
dico("R", 7, "RATIONS").
dico("R", 7, "RATISSA").
dico("R", 7, "RATISSE").
dico("R", 7, "RATITES").
dico("R", 7, "RATONNA").
dico("R", 7, "RATONNE").
dico("R", 7, "RATURAI").
dico("R", 7, "RATURAS").
dico("R", 7, "RATURAT").
dico("R", 7, "RATUREE").
dico("R", 7, "RATURER").
dico("R", 7, "RATURES").
dico("R", 7, "RATUREZ").
dico("R", 7, "RAUCHAI").
dico("R", 7, "RAUCHAS").
dico("R", 7, "RAUCHAT").
dico("R", 7, "RAUCHEE").
dico("R", 7, "RAUCHER").
dico("R", 7, "RAUCHES").
dico("R", 7, "RAUCHEZ").
dico("R", 7, "RAUCITE").
dico("R", 7, "RAUQUAI").
dico("R", 7, "RAUQUAS").
dico("R", 7, "RAUQUAT").
dico("R", 7, "RAUQUER").
dico("R", 7, "RAUQUES").
dico("R", 7, "RAUQUEZ").
dico("R", 7, "RAVAGEA").
dico("R", 7, "RAVAGEE").
dico("R", 7, "RAVAGER").
dico("R", 7, "RAVAGES").
dico("R", 7, "RAVAGEZ").
dico("R", 7, "RAVALAI").
dico("R", 7, "RAVALAS").
dico("R", 7, "RAVALAT").
dico("R", 7, "RAVALEE").
dico("R", 7, "RAVALER").
dico("R", 7, "RAVALES").
dico("R", 7, "RAVALEZ").
dico("R", 7, "RAVAUDA").
dico("R", 7, "RAVAUDE").
dico("R", 7, "RAVELIN").
dico("R", 7, "RAVEURS").
dico("R", 7, "RAVEUSE").
dico("R", 7, "RAVIERE").
dico("R", 7, "RAVIERS").
dico("R", 7, "RAVILIE").
dico("R", 7, "RAVILIR").
dico("R", 7, "RAVILIS").
dico("R", 7, "RAVILIT").
dico("R", 7, "RAVIMES").
dico("R", 7, "RAVINAI").
dico("R", 7, "RAVINAS").
dico("R", 7, "RAVINAT").
dico("R", 7, "RAVINEE").
dico("R", 7, "RAVINER").
dico("R", 7, "RAVINES").
dico("R", 7, "RAVINEZ").
dico("R", 7, "RAVIOLE").
dico("R", 7, "RAVIOLI").
dico("R", 7, "RAVIRAI").
dico("R", 7, "RAVIRAS").
dico("R", 7, "RAVIREZ").
dico("R", 7, "RAVISAI").
dico("R", 7, "RAVISAS").
dico("R", 7, "RAVISAT").
dico("R", 7, "RAVISEE").
dico("R", 7, "RAVISER").
dico("R", 7, "RAVISES").
dico("R", 7, "RAVISEZ").
dico("R", 7, "RAVISSE").
dico("R", 7, "RAVITES").
dico("R", 7, "RAVIVAI").
dico("R", 7, "RAVIVAS").
dico("R", 7, "RAVIVAT").
dico("R", 7, "RAVIVEE").
dico("R", 7, "RAVIVER").
dico("R", 7, "RAVIVES").
dico("R", 7, "RAVIVEZ").
dico("R", 7, "RAYAGES").
dico("R", 7, "RAYAMES").
dico("R", 7, "RAYASSE").
dico("R", 7, "RAYATES").
dico("R", 7, "RAYERAI").
dico("R", 7, "RAYERAS").
dico("R", 7, "RAYERES").
dico("R", 7, "RAYEREZ").
dico("R", 7, "RAYIONS").
dico("R", 7, "RAYONNA").
dico("R", 7, "RAYONNE").
dico("R", 7, "RAYURES").
dico("R", 7, "RAZZIAI").
dico("R", 7, "RAZZIAS").
dico("R", 7, "RAZZIAT").
dico("R", 7, "RAZZIEE").
dico("R", 7, "RAZZIER").
dico("R", 7, "RAZZIES").
dico("R", 7, "RAZZIEZ").
dico("R", 7, "RBATIES").
dico("R", 7, "REACTIF").
dico("R", 7, "READMET").
dico("R", 7, "READMIS").
dico("R", 7, "READMIT").
dico("R", 7, "REAGINE").
dico("R", 7, "REAGIRA").
dico("R", 7, "REAIENT").
dico("R", 7, "REALESA").
dico("R", 7, "REALESE").
dico("R", 7, "REALGAR").
dico("R", 7, "REALISA").
dico("R", 7, "REALISE").
dico("R", 7, "REALITE").
dico("R", 7, "REANIMA").
dico("R", 7, "REANIME").
dico("R", 7, "REARMAI").
dico("R", 7, "REARMAS").
dico("R", 7, "REARMAT").
dico("R", 7, "REARMEE").
dico("R", 7, "REARMER").
dico("R", 7, "REARMES").
dico("R", 7, "REARMEZ").
dico("R", 7, "REASSES").
dico("R", 7, "REAUMUR").
dico("R", 7, "REBATIE").
dico("R", 7, "REBATIR").
dico("R", 7, "REBATIS").
dico("R", 7, "REBATIT").
dico("R", 7, "REBATTE").
dico("R", 7, "REBATTU").
dico("R", 7, "REBELLA").
dico("R", 7, "REBELLE").
dico("R", 7, "REBIBES").
dico("R", 7, "REBIFFA").
dico("R", 7, "REBIFFE").
dico("R", 7, "REBIQUA").
dico("R", 7, "REBIQUE").
dico("R", 7, "REBOIRA").
dico("R", 7, "REBOIRE").
dico("R", 7, "REBOISA").
dico("R", 7, "REBOISE").
dico("R", 7, "REBOIVE").
dico("R", 7, "REBONDI").
dico("R", 7, "REBONDS").
dico("R", 7, "REBORDA").
dico("R", 7, "REBORDE").
dico("R", 7, "REBORDS").
dico("R", 7, "REBOURS").
dico("R", 7, "REBOUTA").
dico("R", 7, "REBOUTE").
dico("R", 7, "REBRODA").
dico("R", 7, "REBRODE").
dico("R", 7, "REBRULA").
dico("R", 7, "REBRULE").
dico("R", 7, "REBUMES").
dico("R", 7, "REBUSES").
dico("R", 7, "REBUSSE").
dico("R", 7, "REBUTAI").
dico("R", 7, "REBUTAS").
dico("R", 7, "REBUTAT").
dico("R", 7, "REBUTEE").
dico("R", 7, "REBUTER").
dico("R", 7, "REBUTES").
dico("R", 7, "REBUTEZ").
dico("R", 7, "REBUVEZ").
dico("R", 7, "RECADRA").
dico("R", 7, "RECADRE").
dico("R", 7, "RECALAI").
dico("R", 7, "RECALAS").
dico("R", 7, "RECALAT").
dico("R", 7, "RECALEE").
dico("R", 7, "RECALER").
dico("R", 7, "RECALES").
dico("R", 7, "RECALEZ").
dico("R", 7, "RECARDA").
dico("R", 7, "RECARDE").
dico("R", 7, "RECASAI").
dico("R", 7, "RECASAS").
dico("R", 7, "RECASAT").
dico("R", 7, "RECASEE").
dico("R", 7, "RECASER").
dico("R", 7, "RECASES").
dico("R", 7, "RECASEZ").
dico("R", 7, "RECASSA").
dico("R", 7, "RECASSE").
dico("R", 7, "RECAUSA").
dico("R", 7, "RECAUSE").
dico("R", 7, "RECAVAI").
dico("R", 7, "RECAVAS").
dico("R", 7, "RECAVAT").
dico("R", 7, "RECAVEE").
dico("R", 7, "RECAVER").
dico("R", 7, "RECAVES").
dico("R", 7, "RECAVEZ").
dico("R", 7, "RECEDAI").
dico("R", 7, "RECEDAS").
dico("R", 7, "RECEDAT").
dico("R", 7, "RECEDEE").
dico("R", 7, "RECEDER").
dico("R", 7, "RECEDES").
dico("R", 7, "RECEDEZ").
dico("R", 7, "RECELAI").
dico("R", 7, "RECELAS").
dico("R", 7, "RECELAT").
dico("R", 7, "RECELEE").
dico("R", 7, "RECELER").
dico("R", 7, "RECELES").
dico("R", 7, "RECELEZ").
dico("R", 7, "RECENCE").
dico("R", 7, "RECENSA").
dico("R", 7, "RECENSE").
dico("R", 7, "RECENTE").
dico("R", 7, "RECENTS").
dico("R", 7, "RECEPAI").
dico("R", 7, "RECEPAS").
dico("R", 7, "RECEPAT").
dico("R", 7, "RECEPEE").
dico("R", 7, "RECEPER").
dico("R", 7, "RECEPES").
dico("R", 7, "RECEPEZ").
dico("R", 7, "RECETTE").
dico("R", 7, "RECEVEZ").
dico("R", 7, "RECEVRA").
dico("R", 7, "RECHAPA").
dico("R", 7, "RECHAPE").
dico("R", 7, "RECHAUD").
dico("R", 7, "RECHUTA").
dico("R", 7, "RECHUTE").
dico("R", 7, "RECIFAL").
dico("R", 7, "RECITAI").
dico("R", 7, "RECITAL").
dico("R", 7, "RECITAS").
dico("R", 7, "RECITAT").
dico("R", 7, "RECITEE").
dico("R", 7, "RECITER").
dico("R", 7, "RECITES").
dico("R", 7, "RECITEZ").
dico("R", 7, "RECLAMA").
dico("R", 7, "RECLAME").
dico("R", 7, "RECLOUA").
dico("R", 7, "RECLOUE").
dico("R", 7, "RECLUSE").
dico("R", 7, "RECOINS").
dico("R", 7, "RECOIVE").
dico("R", 7, "RECOLAI").
dico("R", 7, "RECOLAS").
dico("R", 7, "RECOLAT").
dico("R", 7, "RECOLEE").
dico("R", 7, "RECOLER").
dico("R", 7, "RECOLES").
dico("R", 7, "RECOLEZ").
dico("R", 7, "RECOLLA").
dico("R", 7, "RECOLLE").
dico("R", 7, "RECOLTA").
dico("R", 7, "RECOLTE").
dico("R", 7, "RECONNU").
dico("R", 7, "RECOPIA").
dico("R", 7, "RECOPIE").
dico("R", 7, "RECORDA").
dico("R", 7, "RECORDE").
dico("R", 7, "RECORDS").
dico("R", 7, "RECOUDS").
dico("R", 7, "RECOUPA").
dico("R", 7, "RECOUPE").
dico("R", 7, "RECOURE").
dico("R", 7, "RECOURS").
dico("R", 7, "RECOURT").
dico("R", 7, "RECOURU").
dico("R", 7, "RECOUSE").
dico("R", 7, "RECOUSU").
dico("R", 7, "RECREAI").
dico("R", 7, "RECREAS").
dico("R", 7, "RECREAT").
dico("R", 7, "RECREEE").
dico("R", 7, "RECREER").
dico("R", 7, "RECREES").
dico("R", 7, "RECREEZ").
dico("R", 7, "RECREPI").
dico("R", 7, "RECRIAI").
dico("R", 7, "RECRIAS").
dico("R", 7, "RECRIAT").
dico("R", 7, "RECRIEE").
dico("R", 7, "RECRIER").
dico("R", 7, "RECRIES").
dico("R", 7, "RECRIEZ").
dico("R", 7, "RECRIRA").
dico("R", 7, "RECRIRE").
dico("R", 7, "RECRITE").
dico("R", 7, "RECRITS").
dico("R", 7, "RECRIVE").
dico("R", 7, "RECROIS").
dico("R", 7, "RECROIT").
dico("R", 7, "RECRUES").
dico("R", 7, "RECRUTA").
dico("R", 7, "RECRUTE").
dico("R", 7, "RECTALE").
dico("R", 7, "RECTAUX").
dico("R", 7, "RECTEUR").
dico("R", 7, "RECTION").
dico("R", 7, "RECTITE").
dico("R", 7, "RECTUMS").
dico("R", 7, "RECUEIL").
dico("R", 7, "RECUIRA").
dico("R", 7, "RECUIRE").
dico("R", 7, "RECUISE").
dico("R", 7, "RECUITE").
dico("R", 7, "RECUITS").
dico("R", 7, "RECULAI").
dico("R", 7, "RECULAS").
dico("R", 7, "RECULAT").
dico("R", 7, "RECULEE").
dico("R", 7, "RECULER").
dico("R", 7, "RECULES").
dico("R", 7, "RECULEZ").
dico("R", 7, "RECULON").
dico("R", 7, "RECUMES").
dico("R", 7, "RECURAI").
dico("R", 7, "RECURAS").
dico("R", 7, "RECURAT").
dico("R", 7, "RECUREE").
dico("R", 7, "RECURER").
dico("R", 7, "RECURES").
dico("R", 7, "RECUREZ").
dico("R", 7, "RECUSAI").
dico("R", 7, "RECUSAS").
dico("R", 7, "RECUSAT").
dico("R", 7, "RECUSEE").
dico("R", 7, "RECUSER").
dico("R", 7, "RECUSES").
dico("R", 7, "RECUSEZ").
dico("R", 7, "RECUSSE").
dico("R", 7, "RECUTES").
dico("R", 7, "RECYCLA").
dico("R", 7, "RECYCLE").
dico("R", 7, "REDEFIS").
dico("R", 7, "REDEFIT").
dico("R", 7, "REDENTE").
dico("R", 7, "REDENTS").
dico("R", 7, "REDEVEZ").
dico("R", 7, "REDEVRA").
dico("R", 7, "REDIGEA").
dico("R", 7, "REDIGEE").
dico("R", 7, "REDIGER").
dico("R", 7, "REDIGES").
dico("R", 7, "REDIGEZ").
dico("R", 7, "REDIMAI").
dico("R", 7, "REDIMAS").
dico("R", 7, "REDIMAT").
dico("R", 7, "REDIMEE").
dico("R", 7, "REDIMER").
dico("R", 7, "REDIMES").
dico("R", 7, "REDIMEZ").
dico("R", 7, "REDIRAI").
dico("R", 7, "REDIRAS").
dico("R", 7, "REDIREZ").
dico("R", 7, "REDISES").
dico("R", 7, "REDISSE").
dico("R", 7, "REDITES").
dico("R", 7, "REDOIVE").
dico("R", 7, "REDONNA").
dico("R", 7, "REDONNE").
dico("R", 7, "REDORAI").
dico("R", 7, "REDORAS").
dico("R", 7, "REDORAT").
dico("R", 7, "REDOREE").
dico("R", 7, "REDORER").
dico("R", 7, "REDORES").
dico("R", 7, "REDOREZ").
dico("R", 7, "REDORME").
dico("R", 7, "REDORMI").
dico("R", 7, "REDOULS").
dico("R", 7, "REDOUTA").
dico("R", 7, "REDOUTE").
dico("R", 7, "REDOWAS").
dico("R", 7, "REDUIRA").
dico("R", 7, "REDUIRE").
dico("R", 7, "REDUISE").
dico("R", 7, "REDUITE").
dico("R", 7, "REDUITS").
dico("R", 7, "REDUMES").
dico("R", 7, "REDUSSE").
dico("R", 7, "REDUTES").
dico("R", 7, "REDUVES").
dico("R", 7, "REECRIS").
dico("R", 7, "REECRIT").
dico("R", 7, "REEDITA").
dico("R", 7, "REEDITE").
dico("R", 7, "REELIRA").
dico("R", 7, "REELIRE").
dico("R", 7, "REELISE").
dico("R", 7, "REELLES").
dico("R", 7, "REELUES").
dico("R", 7, "REEMETS").
dico("R", 7, "REEMISE").
dico("R", 7, "REERAIS").
dico("R", 7, "REERAIT").
dico("R", 7, "REERENT").
dico("R", 7, "REERIEZ").
dico("R", 7, "REERONS").
dico("R", 7, "REERONT").
dico("R", 7, "REFAIRE").
dico("R", 7, "REFAITE").
dico("R", 7, "REFAITS").
dico("R", 7, "REFASSE").
dico("R", 7, "REFENDE").
dico("R", 7, "REFENDS").
dico("R", 7, "REFENDU").
dico("R", 7, "REFERAI").
dico("R", 7, "REFERAS").
dico("R", 7, "REFERAT").
dico("R", 7, "REFEREE").
dico("R", 7, "REFERER").
dico("R", 7, "REFERES").
dico("R", 7, "REFEREZ").
dico("R", 7, "REFERMA").
dico("R", 7, "REFERME").
dico("R", 7, "REFILAI").
dico("R", 7, "REFILAS").
dico("R", 7, "REFILAT").
dico("R", 7, "REFILEE").
dico("R", 7, "REFILER").
dico("R", 7, "REFILES").
dico("R", 7, "REFILEZ").
dico("R", 7, "REFIMES").
dico("R", 7, "REFISSE").
dico("R", 7, "REFITES").
dico("R", 7, "REFIXAI").
dico("R", 7, "REFIXAS").
dico("R", 7, "REFIXAT").
dico("R", 7, "REFIXEE").
dico("R", 7, "REFIXER").
dico("R", 7, "REFIXES").
dico("R", 7, "REFIXEZ").
dico("R", 7, "REFLETA").
dico("R", 7, "REFLETE").
dico("R", 7, "REFLETS").
dico("R", 7, "REFLEXE").
dico("R", 7, "REFLUAI").
dico("R", 7, "REFLUAS").
dico("R", 7, "REFLUAT").
dico("R", 7, "REFLUER").
dico("R", 7, "REFLUES").
dico("R", 7, "REFLUEZ").
dico("R", 7, "REFONDA").
dico("R", 7, "REFONDE").
dico("R", 7, "REFONDS").
dico("R", 7, "REFONDU").
dico("R", 7, "REFONTE").
dico("R", 7, "REFORMA").
dico("R", 7, "REFORME").
dico("R", 7, "REFOULA").
dico("R", 7, "REFOULE").
dico("R", 7, "REFOUTE").
dico("R", 7, "REFOUTU").
dico("R", 7, "REFRAIN").
dico("R", 7, "REFRENA").
dico("R", 7, "REFRENE").
dico("R", 7, "REFUGES").
dico("R", 7, "REFUGIA").
dico("R", 7, "REFUGIE").
dico("R", 7, "REFUMAI").
dico("R", 7, "REFUMAS").
dico("R", 7, "REFUMAT").
dico("R", 7, "REFUMEE").
dico("R", 7, "REFUMER").
dico("R", 7, "REFUMES").
dico("R", 7, "REFUMEZ").
dico("R", 7, "REFUSAI").
dico("R", 7, "REFUSAS").
dico("R", 7, "REFUSAT").
dico("R", 7, "REFUSEE").
dico("R", 7, "REFUSER").
dico("R", 7, "REFUSES").
dico("R", 7, "REFUSEZ").
dico("R", 7, "REFUTAI").
dico("R", 7, "REFUTAS").
dico("R", 7, "REFUTAT").
dico("R", 7, "REFUTEE").
dico("R", 7, "REFUTER").
dico("R", 7, "REFUTES").
dico("R", 7, "REFUTEZ").
dico("R", 7, "REGAGNA").
dico("R", 7, "REGAGNE").
dico("R", 7, "REGAINS").
dico("R", 7, "REGALAI").
dico("R", 7, "REGALAS").
dico("R", 7, "REGALAT").
dico("R", 7, "REGALEC").
dico("R", 7, "REGALEE").
dico("R", 7, "REGALER").
dico("R", 7, "REGALES").
dico("R", 7, "REGALEZ").
dico("R", 7, "REGARDA").
dico("R", 7, "REGARDE").
dico("R", 7, "REGARDS").
dico("R", 7, "REGARNI").
dico("R", 7, "REGATAI").
dico("R", 7, "REGATAS").
dico("R", 7, "REGATAT").
dico("R", 7, "REGATER").
dico("R", 7, "REGATES").
dico("R", 7, "REGATEZ").
dico("R", 7, "REGELAI").
dico("R", 7, "REGELAS").
dico("R", 7, "REGELAT").
dico("R", 7, "REGELEE").
dico("R", 7, "REGELER").
dico("R", 7, "REGELES").
dico("R", 7, "REGELEZ").
dico("R", 7, "REGENCE").
dico("R", 7, "REGENCY").
dico("R", 7, "REGENTA").
dico("R", 7, "REGENTE").
dico("R", 7, "REGENTS").
dico("R", 7, "REGGAES").
dico("R", 7, "REGIMBA").
dico("R", 7, "REGIMBE").
dico("R", 7, "REGIMES").
dico("R", 7, "REGIONS").
dico("R", 7, "REGIRAI").
dico("R", 7, "REGIRAS").
dico("R", 7, "REGIREZ").
dico("R", 7, "REGISSE").
dico("R", 7, "REGITES").
dico("R", 7, "REGLAGE").
dico("R", 7, "REGLAIS").
dico("R", 7, "REGLAIT").
dico("R", 7, "REGLANT").
dico("R", 7, "REGLEES").
dico("R", 7, "REGLENT").
dico("R", 7, "REGLERA").
dico("R", 7, "REGLETS").
dico("R", 7, "REGLEUR").
dico("R", 7, "REGLIEZ").
dico("R", 7, "REGLOIR").
dico("R", 7, "REGLONS").
dico("R", 7, "REGLURE").
dico("R", 7, "REGNAIS").
dico("R", 7, "REGNAIT").
dico("R", 7, "REGNANT").
dico("R", 7, "REGNENT").
dico("R", 7, "REGNERA").
dico("R", 7, "REGNIES").
dico("R", 7, "REGNIEZ").
dico("R", 7, "REGNONS").
dico("R", 7, "REGOMMA").
dico("R", 7, "REGOMME").
dico("R", 7, "REGORGE").
dico("R", 7, "REGRATS").
dico("R", 7, "REGREAI").
dico("R", 7, "REGREAS").
dico("R", 7, "REGREAT").
dico("R", 7, "REGREEE").
dico("R", 7, "REGREER").
dico("R", 7, "REGREES").
dico("R", 7, "REGREEZ").
dico("R", 7, "REGRETS").
dico("R", 7, "REGULAI").
dico("R", 7, "REGULAS").
dico("R", 7, "REGULAT").
dico("R", 7, "REGULEE").
dico("R", 7, "REGULER").
dico("R", 7, "REGULES").
dico("R", 7, "REGULEZ").
dico("R", 7, "REHAUTS").
dico("R", 7, "REIFIAI").
dico("R", 7, "REIFIAS").
dico("R", 7, "REIFIAT").
dico("R", 7, "REIFIEE").
dico("R", 7, "REIFIER").
dico("R", 7, "REIFIES").
dico("R", 7, "REIFIEZ").
dico("R", 7, "REITERA").
dico("R", 7, "REITERE").
dico("R", 7, "REITRES").
dico("R", 7, "REJETAI").
dico("R", 7, "REJETAS").
dico("R", 7, "REJETAT").
dico("R", 7, "REJETEE").
dico("R", 7, "REJETER").
dico("R", 7, "REJETES").
dico("R", 7, "REJETEZ").
dico("R", 7, "REJETON").
dico("R", 7, "REJETTE").
dico("R", 7, "REJOINS").
dico("R", 7, "REJOINT").
dico("R", 7, "REJOUAI").
dico("R", 7, "REJOUAS").
dico("R", 7, "REJOUAT").
dico("R", 7, "REJOUEE").
dico("R", 7, "REJOUER").
dico("R", 7, "REJOUES").
dico("R", 7, "REJOUEZ").
dico("R", 7, "REJOUIE").
dico("R", 7, "REJOUIR").
dico("R", 7, "REJOUIS").
dico("R", 7, "REJOUIT").
dico("R", 7, "REJUGEA").
dico("R", 7, "REJUGEE").
dico("R", 7, "REJUGER").
dico("R", 7, "REJUGES").
dico("R", 7, "REJUGEZ").
dico("R", 7, "RELACAI").
dico("R", 7, "RELACAS").
dico("R", 7, "RELACAT").
dico("R", 7, "RELACEE").
dico("R", 7, "RELACER").
dico("R", 7, "RELACES").
dico("R", 7, "RELACEZ").
dico("R", 7, "RELACHA").
dico("R", 7, "RELACHE").
dico("R", 7, "RELAIES").
dico("R", 7, "RELANCA").
dico("R", 7, "RELANCE").
dico("R", 7, "RELAPSE").
dico("R", 7, "RELARGI").
dico("R", 7, "RELATAI").
dico("R", 7, "RELATAS").
dico("R", 7, "RELATAT").
dico("R", 7, "RELATEE").
dico("R", 7, "RELATER").
dico("R", 7, "RELATES").
dico("R", 7, "RELATEZ").
dico("R", 7, "RELATIF").
dico("R", 7, "RELAVAI").
dico("R", 7, "RELAVAS").
dico("R", 7, "RELAVAT").
dico("R", 7, "RELAVEE").
dico("R", 7, "RELAVER").
dico("R", 7, "RELAVES").
dico("R", 7, "RELAVEZ").
dico("R", 7, "RELAXAI").
dico("R", 7, "RELAXAS").
dico("R", 7, "RELAXAT").
dico("R", 7, "RELAXEE").
dico("R", 7, "RELAXER").
dico("R", 7, "RELAXES").
dico("R", 7, "RELAXEZ").
dico("R", 7, "RELAYAI").
dico("R", 7, "RELAYAS").
dico("R", 7, "RELAYAT").
dico("R", 7, "RELAYEE").
dico("R", 7, "RELAYER").
dico("R", 7, "RELAYES").
dico("R", 7, "RELAYEZ").
dico("R", 7, "RELEGUA").
dico("R", 7, "RELEGUE").
dico("R", 7, "RELENTS").
dico("R", 7, "RELEVAI").
dico("R", 7, "RELEVAS").
dico("R", 7, "RELEVAT").
dico("R", 7, "RELEVEE").
dico("R", 7, "RELEVER").
dico("R", 7, "RELEVES").
dico("R", 7, "RELEVEZ").
dico("R", 7, "RELIAGE").
dico("R", 7, "RELIAIS").
dico("R", 7, "RELIAIT").
dico("R", 7, "RELIANT").
dico("R", 7, "RELIEES").
dico("R", 7, "RELIEFS").
dico("R", 7, "RELIENT").
dico("R", 7, "RELIERA").
dico("R", 7, "RELIEUR").
dico("R", 7, "RELIFTA").
dico("R", 7, "RELIFTE").
dico("R", 7, "RELIIEZ").
dico("R", 7, "RELIONS").
dico("R", 7, "RELIQUE").
dico("R", 7, "RELIRAI").
dico("R", 7, "RELIRAS").
dico("R", 7, "RELIREZ").
dico("R", 7, "RELISES").
dico("R", 7, "RELISEZ").
dico("R", 7, "RELISHS").
dico("R", 7, "RELIURE").
dico("R", 7, "RELOGEA").
dico("R", 7, "RELOGEE").
dico("R", 7, "RELOGER").
dico("R", 7, "RELOGES").
dico("R", 7, "RELOGEZ").
dico("R", 7, "RELOOKA").
dico("R", 7, "RELOOKE").
dico("R", 7, "RELOUAI").
dico("R", 7, "RELOUAS").
dico("R", 7, "RELOUAT").
dico("R", 7, "RELOUEE").
dico("R", 7, "RELOUER").
dico("R", 7, "RELOUES").
dico("R", 7, "RELOUEZ").
dico("R", 7, "RELUIRA").
dico("R", 7, "RELUIRE").
dico("R", 7, "RELUISE").
dico("R", 7, "RELUMES").
dico("R", 7, "RELUQUA").
dico("R", 7, "RELUQUE").
dico("R", 7, "RELUSSE").
dico("R", 7, "RELUTES").
dico("R", 7, "REMACHA").
dico("R", 7, "REMACHE").
dico("R", 7, "REMAKES").
dico("R", 7, "REMANGE").
dico("R", 7, "REMANIA").
dico("R", 7, "REMANIE").
dico("R", 7, "REMARIA").
dico("R", 7, "REMARIE").
dico("R", 7, "REMBLAI").
dico("R", 7, "REMEDES").
dico("R", 7, "REMEDIA").
dico("R", 7, "REMEDIE").
dico("R", 7, "REMELAI").
dico("R", 7, "REMELAS").
dico("R", 7, "REMELAT").
dico("R", 7, "REMELEE").
dico("R", 7, "REMELER").
dico("R", 7, "REMELES").
dico("R", 7, "REMELEZ").
dico("R", 7, "REMERES").
dico("R", 7, "REMETTE").
dico("R", 7, "REMIGES").
dico("R", 7, "REMIMES").
dico("R", 7, "REMISAI").
dico("R", 7, "REMISAS").
dico("R", 7, "REMISAT").
dico("R", 7, "REMISEE").
dico("R", 7, "REMISER").
dico("R", 7, "REMISES").
dico("R", 7, "REMISEZ").
dico("R", 7, "REMISSE").
dico("R", 7, "REMITES").
dico("R", 7, "REMIXAI").
dico("R", 7, "REMIXAS").
dico("R", 7, "REMIXAT").
dico("R", 7, "REMIXEE").
dico("R", 7, "REMIXER").
dico("R", 7, "REMIXES").
dico("R", 7, "REMIXEZ").
dico("R", 7, "REMMENA").
dico("R", 7, "REMMENE").
dico("R", 7, "REMOISE").
dico("R", 7, "REMONTA").
dico("R", 7, "REMONTE").
dico("R", 7, "REMORAS").
dico("R", 7, "REMORDE").
dico("R", 7, "REMORDS").
dico("R", 7, "REMORDU").
dico("R", 7, "REMOUDS").
dico("R", 7, "REMOULA").
dico("R", 7, "REMOULE").
dico("R", 7, "REMOULU").
dico("R", 7, "REMPART").
dico("R", 7, "REMPILA").
dico("R", 7, "REMPILE").
dico("R", 7, "REMPLIA").
dico("R", 7, "REMPLIE").
dico("R", 7, "REMPLIR").
dico("R", 7, "REMPLIS").
dico("R", 7, "REMPLIT").
dico("R", 7, "REMPLOI").
dico("R", 7, "REMPOTA").
dico("R", 7, "REMPOTE").
dico("R", 7, "REMUAGE").
dico("R", 7, "REMUAIS").
dico("R", 7, "REMUAIT").
dico("R", 7, "REMUANT").
dico("R", 7, "REMUEES").
dico("R", 7, "REMUENT").
dico("R", 7, "REMUERA").
dico("R", 7, "REMUEUR").
dico("R", 7, "REMUGLE").
dico("R", 7, "REMUIEZ").
dico("R", 7, "REMUONS").
dico("R", 7, "RENACLA").
dico("R", 7, "RENACLE").
dico("R", 7, "RENALES").
dico("R", 7, "RENARDA").
dico("R", 7, "RENARDE").
dico("R", 7, "RENARDS").
dico("R", 7, "RENAUDA").
dico("R", 7, "RENAUDE").
dico("R", 7, "RENCARD").
dico("R", 7, "RENCART").
dico("R", 7, "RENDAIS").
dico("R", 7, "RENDAIT").
dico("R", 7, "RENDANT").
dico("R", 7, "RENDENT").
dico("R", 7, "RENDIEZ").
dico("R", 7, "RENDONS").
dico("R", 7, "RENDORS").
dico("R", 7, "RENDORT").
dico("R", 7, "RENDRAI").
dico("R", 7, "RENDRAS").
dico("R", 7, "RENDREZ").
dico("R", 7, "RENDUES").
dico("R", 7, "RENEGAT").
dico("R", 7, "RENEIGE").
dico("R", 7, "RENETTA").
dico("R", 7, "RENETTE").
dico("R", 7, "RENFILA").
dico("R", 7, "RENFILE").
dico("R", 7, "RENFLAI").
dico("R", 7, "RENFLAS").
dico("R", 7, "RENFLAT").
dico("R", 7, "RENFLEE").
dico("R", 7, "RENFLER").
dico("R", 7, "RENFLES").
dico("R", 7, "RENFLEZ").
dico("R", 7, "RENFORT").
dico("R", 7, "RENGAGE").
dico("R", 7, "RENIAIS").
dico("R", 7, "RENIAIT").
dico("R", 7, "RENIANT").
dico("R", 7, "RENIEES").
dico("R", 7, "RENIENT").
dico("R", 7, "RENIERA").
dico("R", 7, "RENIFLA").
dico("R", 7, "RENIFLE").
dico("R", 7, "RENIIEZ").
dico("R", 7, "RENINES").
dico("R", 7, "RENIONS").
dico("R", 7, "RENIPPA").
dico("R", 7, "RENIPPE").
dico("R", 7, "RENNAIS").
dico("R", 7, "RENOMMA").
dico("R", 7, "RENOMME").
dico("R", 7, "RENONCA").
dico("R", 7, "RENONCE").
dico("R", 7, "RENOTAI").
dico("R", 7, "RENOTAS").
dico("R", 7, "RENOTAT").
dico("R", 7, "RENOTEE").
dico("R", 7, "RENOTER").
dico("R", 7, "RENOTES").
dico("R", 7, "RENOTEZ").
dico("R", 7, "RENOUAI").
dico("R", 7, "RENOUAS").
dico("R", 7, "RENOUAT").
dico("R", 7, "RENOUEE").
dico("R", 7, "RENOUER").
dico("R", 7, "RENOUES").
dico("R", 7, "RENOUEZ").
dico("R", 7, "RENOVAI").
dico("R", 7, "RENOVAS").
dico("R", 7, "RENOVAT").
dico("R", 7, "RENOVEE").
dico("R", 7, "RENOVER").
dico("R", 7, "RENOVES").
dico("R", 7, "RENOVEZ").
dico("R", 7, "RENTAIS").
dico("R", 7, "RENTAIT").
dico("R", 7, "RENTAMA").
dico("R", 7, "RENTAME").
dico("R", 7, "RENTANT").
dico("R", 7, "RENTEES").
dico("R", 7, "RENTENT").
dico("R", 7, "RENTERA").
dico("R", 7, "RENTIER").
dico("R", 7, "RENTIEZ").
dico("R", 7, "RENTONS").
dico("R", 7, "RENTRAI").
dico("R", 7, "RENTRAS").
dico("R", 7, "RENTRAT").
dico("R", 7, "RENTREE").
dico("R", 7, "RENTRER").
dico("R", 7, "RENTRES").
dico("R", 7, "RENTREZ").
dico("R", 7, "RENVIDA").
dico("R", 7, "RENVIDE").
dico("R", 7, "RENVOIE").
dico("R", 7, "RENVOIS").
dico("R", 7, "RENVOYA").
dico("R", 7, "RENVOYE").
dico("R", 7, "REOPERA").
dico("R", 7, "REOPERE").
dico("R", 7, "REOUVRE").
dico("R", 7, "REPAIES").
dico("R", 7, "REPAIRA").
dico("R", 7, "REPAIRE").
dico("R", 7, "REPANDE").
dico("R", 7, "REPANDS").
dico("R", 7, "REPANDU").
dico("R", 7, "REPARAI").
dico("R", 7, "REPARAS").
dico("R", 7, "REPARAT").
dico("R", 7, "REPAREE").
dico("R", 7, "REPARER").
dico("R", 7, "REPARES").
dico("R", 7, "REPAREZ").
dico("R", 7, "REPARLA").
dico("R", 7, "REPARLE").
dico("R", 7, "REPARTE").
dico("R", 7, "REPARTI").
dico("R", 7, "REPARUE").
dico("R", 7, "REPARUS").
dico("R", 7, "REPARUT").
dico("R", 7, "REPASSA").
dico("R", 7, "REPASSE").
dico("R", 7, "REPAVAI").
dico("R", 7, "REPAVAS").
dico("R", 7, "REPAVAT").
dico("R", 7, "REPAVEE").
dico("R", 7, "REPAVER").
dico("R", 7, "REPAVES").
dico("R", 7, "REPAVEZ").
dico("R", 7, "REPAYAI").
dico("R", 7, "REPAYAS").
dico("R", 7, "REPAYAT").
dico("R", 7, "REPAYEE").
dico("R", 7, "REPAYER").
dico("R", 7, "REPAYES").
dico("R", 7, "REPAYEZ").
dico("R", 7, "REPECHA").
dico("R", 7, "REPECHE").
dico("R", 7, "REPEINS").
dico("R", 7, "REPEINT").
dico("R", 7, "REPENDE").
dico("R", 7, "REPENDS").
dico("R", 7, "REPENDU").
dico("R", 7, "REPENSA").
dico("R", 7, "REPENSE").
dico("R", 7, "REPENTE").
dico("R", 7, "REPENTI").
dico("R", 7, "REPERAI").
dico("R", 7, "REPERAS").
dico("R", 7, "REPERAT").
dico("R", 7, "REPERCA").
dico("R", 7, "REPERCE").
dico("R", 7, "REPERDE").
dico("R", 7, "REPERDS").
dico("R", 7, "REPERDU").
dico("R", 7, "REPEREE").
dico("R", 7, "REPERER").
dico("R", 7, "REPERES").
dico("R", 7, "REPEREZ").
dico("R", 7, "REPESAI").
dico("R", 7, "REPESAS").
dico("R", 7, "REPESAT").
dico("R", 7, "REPESEE").
dico("R", 7, "REPESER").
dico("R", 7, "REPESES").
dico("R", 7, "REPESEZ").
dico("R", 7, "REPETAI").
dico("R", 7, "REPETAS").
dico("R", 7, "REPETAT").
dico("R", 7, "REPETEE").
dico("R", 7, "REPETER").
dico("R", 7, "REPETES").
dico("R", 7, "REPETEZ").
dico("R", 7, "REPETRI").
dico("R", 7, "REPIQUA").
dico("R", 7, "REPIQUE").
dico("R", 7, "REPLACA").
dico("R", 7, "REPLACE").
dico("R", 7, "REPLATS").
dico("R", 7, "REPLETE").
dico("R", 7, "REPLETS").
dico("R", 7, "REPLEUT").
dico("R", 7, "REPLIAI").
dico("R", 7, "REPLIAS").
dico("R", 7, "REPLIAT").
dico("R", 7, "REPLIEE").
dico("R", 7, "REPLIER").
dico("R", 7, "REPLIES").
dico("R", 7, "REPLIEZ").
dico("R", 7, "REPLOIE").
dico("R", 7, "REPLOYA").
dico("R", 7, "REPLOYE").
dico("R", 7, "REPOLIE").
dico("R", 7, "REPOLIR").
dico("R", 7, "REPOLIS").
dico("R", 7, "REPOLIT").
dico("R", 7, "REPONDE").
dico("R", 7, "REPONDS").
dico("R", 7, "REPONDU").
dico("R", 7, "REPONSE").
dico("R", 7, "REPORTA").
dico("R", 7, "REPORTE").
dico("R", 7, "REPORTS").
dico("R", 7, "REPOSAI").
dico("R", 7, "REPOSAS").
dico("R", 7, "REPOSAT").
dico("R", 7, "REPOSEE").
dico("R", 7, "REPOSER").
dico("R", 7, "REPOSES").
dico("R", 7, "REPOSEZ").
dico("R", 7, "REPREND").
dico("R", 7, "REPRIMA").
dico("R", 7, "REPRIME").
dico("R", 7, "REPRINT").
dico("R", 7, "REPRISA").
dico("R", 7, "REPRISE").
dico("R", 7, "REPTILE").
dico("R", 7, "REPUDIA").
dico("R", 7, "REPUDIE").
dico("R", 7, "REPUGNA").
dico("R", 7, "REPUGNE").
dico("R", 7, "REPUMES").
dico("R", 7, "REPUSSE").
dico("R", 7, "REPUTAI").
dico("R", 7, "REPUTAS").
dico("R", 7, "REPUTAT").
dico("R", 7, "REPUTEE").
dico("R", 7, "REPUTER").
dico("R", 7, "REPUTES").
dico("R", 7, "REPUTEZ").
dico("R", 7, "REQUETA").
dico("R", 7, "REQUETE").
dico("R", 7, "REQUIEM").
dico("R", 7, "REQUINS").
dico("R", 7, "REQUISE").
dico("R", 7, "RESALAI").
dico("R", 7, "RESALAS").
dico("R", 7, "RESALAT").
dico("R", 7, "RESALEE").
dico("R", 7, "RESALER").
dico("R", 7, "RESALES").
dico("R", 7, "RESALEZ").
dico("R", 7, "RESALIE").
dico("R", 7, "RESALIR").
dico("R", 7, "RESALIS").
dico("R", 7, "RESALIT").
dico("R", 7, "RESCAPA").
dico("R", 7, "RESCAPE").
dico("R", 7, "RESCRIT").
dico("R", 7, "RESEAUX").
dico("R", 7, "RESEDAS").
dico("R", 7, "RESEMAI").
dico("R", 7, "RESEMAS").
dico("R", 7, "RESEMAT").
dico("R", 7, "RESEMEE").
dico("R", 7, "RESEMER").
dico("R", 7, "RESEMES").
dico("R", 7, "RESEMEZ").
dico("R", 7, "RESEQUA").
dico("R", 7, "RESEQUE").
dico("R", 7, "RESERVA").
dico("R", 7, "RESERVE").
dico("R", 7, "RESIDAI").
dico("R", 7, "RESIDAS").
dico("R", 7, "RESIDAT").
dico("R", 7, "RESIDER").
dico("R", 7, "RESIDES").
dico("R", 7, "RESIDEZ").
dico("R", 7, "RESIDUS").
dico("R", 7, "RESIGNA").
dico("R", 7, "RESIGNE").
dico("R", 7, "RESILIA").
dico("R", 7, "RESILIE").
dico("R", 7, "RESILLE").
dico("R", 7, "RESINAI").
dico("R", 7, "RESINAS").
dico("R", 7, "RESINAT").
dico("R", 7, "RESINEE").
dico("R", 7, "RESINER").
dico("R", 7, "RESINES").
dico("R", 7, "RESINEZ").
dico("R", 7, "RESISTA").
dico("R", 7, "RESISTE").
dico("R", 7, "RESITUA").
dico("R", 7, "RESITUE").
dico("R", 7, "RESOLUE").
dico("R", 7, "RESOLUS").
dico("R", 7, "RESOLUT").
dico("R", 7, "RESOLVE").
dico("R", 7, "RESONNA").
dico("R", 7, "RESONNE").
dico("R", 7, "RESORBA").
dico("R", 7, "RESORBE").
dico("R", 7, "RESOUTE").
dico("R", 7, "RESPECT").
dico("R", 7, "RESPIRA").
dico("R", 7, "RESPIRE").
dico("R", 7, "RESSACS").
dico("R", 7, "RESSAIE").
dico("R", 7, "RESSATS").
dico("R", 7, "RESSAUT").
dico("R", 7, "RESSAYA").
dico("R", 7, "RESSAYE").
dico("R", 7, "RESSEMA").
dico("R", 7, "RESSEME").
dico("R", 7, "RESSENS").
dico("R", 7, "RESSENT").
dico("R", 7, "RESSERS").
dico("R", 7, "RESSERT").
dico("R", 7, "RESSORS").
dico("R", 7, "RESSORT").
dico("R", 7, "RESSUAI").
dico("R", 7, "RESSUAS").
dico("R", 7, "RESSUAT").
dico("R", 7, "RESSUER").
dico("R", 7, "RESSUES").
dico("R", 7, "RESSUEZ").
dico("R", 7, "RESSUIE").
dico("R", 7, "RESSUIS").
dico("R", 7, "RESSUYA").
dico("R", 7, "RESSUYE").
dico("R", 7, "RESTAIS").
dico("R", 7, "RESTAIT").
dico("R", 7, "RESTANT").
dico("R", 7, "RESTAUS").
dico("R", 7, "RESTAUX").
dico("R", 7, "RESTEES").
dico("R", 7, "RESTENT").
dico("R", 7, "RESTERA").
dico("R", 7, "RESTIEZ").
dico("R", 7, "RESTONS").
dico("R", 7, "RESUCEE").
dico("R", 7, "RESULTA").
dico("R", 7, "RESULTE").
dico("R", 7, "RESUMAI").
dico("R", 7, "RESUMAS").
dico("R", 7, "RESUMAT").
dico("R", 7, "RESUMEE").
dico("R", 7, "RESUMER").
dico("R", 7, "RESUMES").
dico("R", 7, "RESUMEZ").
dico("R", 7, "RESURGI").
dico("R", 7, "RETABLE").
dico("R", 7, "RETABLI").
dico("R", 7, "RETAISE").
dico("R", 7, "RETAMAI").
dico("R", 7, "RETAMAS").
dico("R", 7, "RETAMAT").
dico("R", 7, "RETAMEE").
dico("R", 7, "RETAMER").
dico("R", 7, "RETAMES").
dico("R", 7, "RETAMEZ").
dico("R", 7, "RETAPAI").
dico("R", 7, "RETAPAS").
dico("R", 7, "RETAPAT").
dico("R", 7, "RETAPEE").
dico("R", 7, "RETAPER").
dico("R", 7, "RETAPES").
dico("R", 7, "RETAPEZ").
dico("R", 7, "RETARDA").
dico("R", 7, "RETARDE").
dico("R", 7, "RETARDS").
dico("R", 7, "RETATAI").
dico("R", 7, "RETATAS").
dico("R", 7, "RETATAT").
dico("R", 7, "RETATEE").
dico("R", 7, "RETATER").
dico("R", 7, "RETATES").
dico("R", 7, "RETATEZ").
dico("R", 7, "RETAXAI").
dico("R", 7, "RETAXAS").
dico("R", 7, "RETAXAT").
dico("R", 7, "RETAXEE").
dico("R", 7, "RETAXER").
dico("R", 7, "RETAXES").
dico("R", 7, "RETAXEZ").
dico("R", 7, "RETEINS").
dico("R", 7, "RETEINT").
dico("R", 7, "RETENDE").
dico("R", 7, "RETENDS").
dico("R", 7, "RETENDU").
dico("R", 7, "RETENEZ").
dico("R", 7, "RETENIR").
dico("R", 7, "RETENTA").
dico("R", 7, "RETENTE").
dico("R", 7, "RETENTI").
dico("R", 7, "RETENUE").
dico("R", 7, "RETENUS").
dico("R", 7, "RETERCA").
dico("R", 7, "RETERCE").
dico("R", 7, "RETERSA").
dico("R", 7, "RETERSE").
dico("R", 7, "RETIENS").
dico("R", 7, "RETIENT").
dico("R", 7, "RETIGEA").
dico("R", 7, "RETIGER").
dico("R", 7, "RETIGES").
dico("R", 7, "RETIGEZ").
dico("R", 7, "RETINAL").
dico("R", 7, "RETINES").
dico("R", 7, "RETINOL").
dico("R", 7, "RETIQUE").
dico("R", 7, "RETIRAI").
dico("R", 7, "RETIRAS").
dico("R", 7, "RETIRAT").
dico("R", 7, "RETIREE").
dico("R", 7, "RETIRER").
dico("R", 7, "RETIRES").
dico("R", 7, "RETIREZ").
dico("R", 7, "RETISSA").
dico("R", 7, "RETISSE").
dico("R", 7, "RETIVES").
dico("R", 7, "RETOMBA").
dico("R", 7, "RETOMBE").
dico("R", 7, "RETONDE").
dico("R", 7, "RETONDS").
dico("R", 7, "RETONDU").
dico("R", 7, "RETOQUA").
dico("R", 7, "RETOQUE").
dico("R", 7, "RETORDE").
dico("R", 7, "RETORDS").
dico("R", 7, "RETORDU").
dico("R", 7, "RETORSE").
dico("R", 7, "RETOUPA").
dico("R", 7, "RETOUPE").
dico("R", 7, "RETOURS").
dico("R", 7, "RETRACA").
dico("R", 7, "RETRACE").
dico("R", 7, "RETRAIE").
dico("R", 7, "RETRAIS").
dico("R", 7, "RETRAIT").
dico("R", 7, "RETRAYE").
dico("R", 7, "RETRECI").
dico("R", 7, "RETSINA").
dico("R", 7, "RETUBAI").
dico("R", 7, "RETUBAS").
dico("R", 7, "RETUBAT").
dico("R", 7, "RETUBEE").
dico("R", 7, "RETUBER").
dico("R", 7, "RETUBES").
dico("R", 7, "RETUBEZ").
dico("R", 7, "REUNIES").
dico("R", 7, "REUNION").
dico("R", 7, "REUNIRA").
dico("R", 7, "REUSSIE").
dico("R", 7, "REUSSIR").
dico("R", 7, "REUSSIS").
dico("R", 7, "REUSSIT").
dico("R", 7, "REVALEZ").
dico("R", 7, "REVALUE").
dico("R", 7, "REVALUS").
dico("R", 7, "REVALUT").
dico("R", 7, "REVAMES").
dico("R", 7, "REVASSA").
dico("R", 7, "REVASSE").
dico("R", 7, "REVATES").
dico("R", 7, "REVECHE").
dico("R", 7, "REVECUE").
dico("R", 7, "REVECUS").
dico("R", 7, "REVECUT").
dico("R", 7, "REVEILS").
dico("R", 7, "REVELAI").
dico("R", 7, "REVELAS").
dico("R", 7, "REVELAT").
dico("R", 7, "REVELEE").
dico("R", 7, "REVELER").
dico("R", 7, "REVELES").
dico("R", 7, "REVELEZ").
dico("R", 7, "REVENDE").
dico("R", 7, "REVENDS").
dico("R", 7, "REVENDU").
dico("R", 7, "REVENEZ").
dico("R", 7, "REVENIR").
dico("R", 7, "REVENTE").
dico("R", 7, "REVENUE").
dico("R", 7, "REVENUS").
dico("R", 7, "REVERAI").
dico("R", 7, "REVERAS").
dico("R", 7, "REVERAT").
dico("R", 7, "REVERDI").
dico("R", 7, "REVEREE").
dico("R", 7, "REVERER").
dico("R", 7, "REVERES").
dico("R", 7, "REVEREZ").
dico("R", 7, "REVERIE").
dico("R", 7, "REVERNI").
dico("R", 7, "REVERRA").
dico("R", 7, "REVERSA").
dico("R", 7, "REVERSE").
dico("R", 7, "REVERSI").
dico("R", 7, "REVETES").
dico("R", 7, "REVETEZ").
dico("R", 7, "REVETIR").
dico("R", 7, "REVETIS").
dico("R", 7, "REVETIT").
dico("R", 7, "REVETUE").
dico("R", 7, "REVETUS").
dico("R", 7, "REVEURS").
dico("R", 7, "REVEUSE").
dico("R", 7, "REVIENS").
dico("R", 7, "REVIENT").
dico("R", 7, "REVIMES").
dico("R", 7, "REVIONS").
dico("R", 7, "REVIRAI").
dico("R", 7, "REVIRAS").
dico("R", 7, "REVIRAT").
dico("R", 7, "REVIREE").
dico("R", 7, "REVIRER").
dico("R", 7, "REVIRES").
dico("R", 7, "REVIREZ").
dico("R", 7, "REVISAI").
dico("R", 7, "REVISAS").
dico("R", 7, "REVISAT").
dico("R", 7, "REVISEE").
dico("R", 7, "REVISER").
dico("R", 7, "REVISES").
dico("R", 7, "REVISEZ").
dico("R", 7, "REVISSA").
dico("R", 7, "REVISSE").
dico("R", 7, "REVITES").
dico("R", 7, "REVIVAL").
dico("R", 7, "REVIVES").
dico("R", 7, "REVIVEZ").
dico("R", 7, "REVIVRA").
dico("R", 7, "REVIVRE").
dico("R", 7, "REVOICI").
dico("R", 7, "REVOIES").
dico("R", 7, "REVOILA").
dico("R", 7, "REVOLAI").
dico("R", 7, "REVOLAS").
dico("R", 7, "REVOLAT").
dico("R", 7, "REVOLEE").
dico("R", 7, "REVOLER").
dico("R", 7, "REVOLES").
dico("R", 7, "REVOLEZ").
dico("R", 7, "REVOLTA").
dico("R", 7, "REVOLTE").
dico("R", 7, "REVOLUE").
dico("R", 7, "REVOLUS").
dico("R", 7, "REVOQUA").
dico("R", 7, "REVOQUE").
dico("R", 7, "REVOTAI").
dico("R", 7, "REVOTAS").
dico("R", 7, "REVOTAT").
dico("R", 7, "REVOTEE").
dico("R", 7, "REVOTER").
dico("R", 7, "REVOTES").
dico("R", 7, "REVOTEZ").
dico("R", 7, "REVOULU").
dico("R", 7, "REVOYEZ").
dico("R", 7, "REVULSA").
dico("R", 7, "REVULSE").
dico("R", 7, "REWRITA").
dico("R", 7, "REWRITE").
dico("R", 7, "REXISME").
dico("R", 7, "REXISTE").
dico("R", 7, "REZZOUS").
dico("R", 7, "RHENANE").
dico("R", 7, "RHENANS").
dico("R", 7, "RHENIUM").
dico("R", 7, "RHETEUR").
dico("R", 7, "RHETIEN").
dico("R", 7, "RHINITE").
dico("R", 7, "RHIZOME").
dico("R", 7, "RHODIAI").
dico("R", 7, "RHODIAS").
dico("R", 7, "RHODIAT").
dico("R", 7, "RHODIEE").
dico("R", 7, "RHODIEN").
dico("R", 7, "RHODIER").
dico("R", 7, "RHODIES").
dico("R", 7, "RHODIEZ").
dico("R", 7, "RHODITE").
dico("R", 7, "RHODIUM").
dico("R", 7, "RHODOID").
dico("R", 7, "RHOMBES").
dico("R", 7, "RHOVYLS").
dico("R", 7, "RHUMAIS").
dico("R", 7, "RHUMAIT").
dico("R", 7, "RHUMANT").
dico("R", 7, "RHUMATO").
dico("R", 7, "RHUMEES").
dico("R", 7, "RHUMENT").
dico("R", 7, "RHUMERA").
dico("R", 7, "RHUMIEZ").
dico("R", 7, "RHUMONS").
dico("R", 7, "RHYTINE").
dico("R", 7, "RHYTONS").
dico("R", 7, "RIAIENT").
dico("R", 7, "RIANTES").
dico("R", 7, "RIBAUDE").
dico("R", 7, "RIBAUDS").
dico("R", 7, "RIBLAGE").
dico("R", 7, "RIBLAIS").
dico("R", 7, "RIBLAIT").
dico("R", 7, "RIBLANT").
dico("R", 7, "RIBLEES").
dico("R", 7, "RIBLENT").
dico("R", 7, "RIBLERA").
dico("R", 7, "RIBLIEZ").
dico("R", 7, "RIBLONS").
dico("R", 7, "RIBORDS").
dico("R", 7, "RIBOSES").
dico("R", 7, "RIBOTES").
dico("R", 7, "RIBOUIS").
dico("R", 7, "RIBOULA").
dico("R", 7, "RIBOULE").
dico("R", 7, "RICAINE").
dico("R", 7, "RICAINS").
dico("R", 7, "RICANAI").
dico("R", 7, "RICANAS").
dico("R", 7, "RICANAT").
dico("R", 7, "RICANER").
dico("R", 7, "RICANES").
dico("R", 7, "RICANEZ").
dico("R", 7, "RICARDS").
dico("R", 7, "RICCIES").
dico("R", 7, "RICHARD").
dico("R", 7, "RICINEE").
dico("R", 7, "RICINES").
dico("R", 7, "RICOCHA").
dico("R", 7, "RICOCHE").
dico("R", 7, "RICOTTA").
dico("R", 7, "RIDAGES").
dico("R", 7, "RIDAMES").
dico("R", 7, "RIDASSE").
dico("R", 7, "RIDATES").
dico("R", 7, "RIDEAUX").
dico("R", 7, "RIDELLE").
dico("R", 7, "RIDERAI").
dico("R", 7, "RIDERAS").
dico("R", 7, "RIDEREZ").
dico("R", 7, "RIDIONS").
dico("R", 7, "RIDOIRS").
dico("R", 7, "RIDULES").
dico("R", 7, "RIEUSES").
dico("R", 7, "RIFAINE").
dico("R", 7, "RIFAINS").
dico("R", 7, "RIFFLES").
dico("R", 7, "RIFIFIS").
dico("R", 7, "RIFLAIS").
dico("R", 7, "RIFLAIT").
dico("R", 7, "RIFLANT").
dico("R", 7, "RIFLARD").
dico("R", 7, "RIFLEES").
dico("R", 7, "RIFLENT").
dico("R", 7, "RIFLERA").
dico("R", 7, "RIFLIEZ").
dico("R", 7, "RIFLOIR").
dico("R", 7, "RIFLONS").
dico("R", 7, "RIGIDES").
dico("R", 7, "RIGODON").
dico("R", 7, "RIGOLAI").
dico("R", 7, "RIGOLAS").
dico("R", 7, "RIGOLAT").
dico("R", 7, "RIGOLER").
dico("R", 7, "RIGOLES").
dico("R", 7, "RIGOLEZ").
dico("R", 7, "RIGOLOS").
dico("R", 7, "RIGOTTE").
dico("R", 7, "RIGUEUR").
dico("R", 7, "RIKIKIS").
dico("R", 7, "RILLONS").
dico("R", 7, "RILSANS").
dico("R", 7, "RIMAMES").
dico("R", 7, "RIMASSE").
dico("R", 7, "RIMATES").
dico("R", 7, "RIMAYES").
dico("R", 7, "RIMERAI").
dico("R", 7, "RIMERAS").
dico("R", 7, "RIMEREZ").
dico("R", 7, "RIMEURS").
dico("R", 7, "RIMEUSE").
dico("R", 7, "RIMIONS").
dico("R", 7, "RIMMELS").
dico("R", 7, "RINCAGE").
dico("R", 7, "RINCAIS").
dico("R", 7, "RINCAIT").
dico("R", 7, "RINCANT").
dico("R", 7, "RINCEAU").
dico("R", 7, "RINCEES").
dico("R", 7, "RINCENT").
dico("R", 7, "RINCERA").
dico("R", 7, "RINCEUR").
dico("R", 7, "RINCIEZ").
dico("R", 7, "RINCONS").
dico("R", 7, "RINCURE").
dico("R", 7, "RINGARD").
dico("R", 7, "RINGGIT").
dico("R", 7, "RIOTAIS").
dico("R", 7, "RIOTAIT").
dico("R", 7, "RIOTANT").
dico("R", 7, "RIOTENT").
dico("R", 7, "RIOTERA").
dico("R", 7, "RIOTIEZ").
dico("R", 7, "RIOTONS").
dico("R", 7, "RIPAGES").
dico("R", 7, "RIPAMES").
dico("R", 7, "RIPASSE").
dico("R", 7, "RIPATES").
dico("R", 7, "RIPATON").
dico("R", 7, "RIPERAI").
dico("R", 7, "RIPERAS").
dico("R", 7, "RIPEREZ").
dico("R", 7, "RIPIENO").
dico("R", 7, "RIPIONS").
dico("R", 7, "RIPOLIN").
dico("R", 7, "RIPOSTA").
dico("R", 7, "RIPOSTE").
dico("R", 7, "RIPPERS").
dico("R", 7, "RIPPEUR").
dico("R", 7, "RIRIONS").
dico("R", 7, "RISBANS").
dico("R", 7, "RISETTE").
dico("R", 7, "RISIBLE").
dico("R", 7, "RISOTTO").
dico("R", 7, "RISQUAI").
dico("R", 7, "RISQUAS").
dico("R", 7, "RISQUAT").
dico("R", 7, "RISQUEE").
dico("R", 7, "RISQUER").
dico("R", 7, "RISQUES").
dico("R", 7, "RISQUEZ").
dico("R", 7, "RISSENT").
dico("R", 7, "RISSIEZ").
dico("R", 7, "RISSOLA").
dico("R", 7, "RISSOLE").
dico("R", 7, "RITALES").
dico("R", 7, "RITUELS").
dico("R", 7, "RIVAGES").
dico("R", 7, "RIVALES").
dico("R", 7, "RIVAMES").
dico("R", 7, "RIVASSE").
dico("R", 7, "RIVATES").
dico("R", 7, "RIVERAI").
dico("R", 7, "RIVERAS").
dico("R", 7, "RIVEREZ").
dico("R", 7, "RIVETAI").
dico("R", 7, "RIVETAS").
dico("R", 7, "RIVETAT").
dico("R", 7, "RIVETEE").
dico("R", 7, "RIVETER").
dico("R", 7, "RIVETES").
dico("R", 7, "RIVETEZ").
dico("R", 7, "RIVETTE").
dico("R", 7, "RIVEURS").
dico("R", 7, "RIVEUSE").
dico("R", 7, "RIVIERE").
dico("R", 7, "RIVIONS").
dico("R", 7, "RIVOIRS").
dico("R", 7, "RIVURES").
dico("R", 7, "RIXDALE").
dico("R", 7, "RIZERIE").
dico("R", 7, "RIZETTE").
dico("R", 7, "RIZIERE").
dico("R", 7, "ROBAGES").
dico("R", 7, "ROBAMES").
dico("R", 7, "ROBASSE").
dico("R", 7, "ROBATES").
dico("R", 7, "ROBERAI").
dico("R", 7, "ROBERAS").
dico("R", 7, "ROBEREZ").
dico("R", 7, "ROBERTS").
dico("R", 7, "ROBEUSE").
dico("R", 7, "ROBINES").
dico("R", 7, "ROBINET").
dico("R", 7, "ROBIONS").
dico("R", 7, "ROBUSTA").
dico("R", 7, "ROBUSTE").
dico("R", 7, "ROCADES").
dico("R", 7, "ROCELLE").
dico("R", 7, "ROCHAGE").
dico("R", 7, "ROCHAIS").
dico("R", 7, "ROCHAIT").
dico("R", 7, "ROCHANT").
dico("R", 7, "ROCHEES").
dico("R", 7, "ROCHENT").
dico("R", 7, "ROCHERA").
dico("R", 7, "ROCHERS").
dico("R", 7, "ROCHETS").
dico("R", 7, "ROCHEUX").
dico("R", 7, "ROCHIER").
dico("R", 7, "ROCHIEZ").
dico("R", 7, "ROCHONS").
dico("R", 7, "ROCKERS").
dico("R", 7, "ROCKETS").
dico("R", 7, "ROCKEUR").
dico("R", 7, "ROCOCOS").
dico("R", 7, "ROCOUAI").
dico("R", 7, "ROCOUAS").
dico("R", 7, "ROCOUAT").
dico("R", 7, "ROCOUEE").
dico("R", 7, "ROCOUER").
dico("R", 7, "ROCOUES").
dico("R", 7, "ROCOUEZ").
dico("R", 7, "RODAGES").
dico("R", 7, "RODAMES").
dico("R", 7, "RODASSE").
dico("R", 7, "RODATES").
dico("R", 7, "RODERAI").
dico("R", 7, "RODERAS").
dico("R", 7, "RODEREZ").
dico("R", 7, "RODEURS").
dico("R", 7, "RODEUSE").
dico("R", 7, "RODIONS").
dico("R", 7, "RODOIRS").
dico("R", 7, "ROESTIS").
dico("R", 7, "ROGATON").
dico("R", 7, "ROGNAGE").
dico("R", 7, "ROGNAIS").
dico("R", 7, "ROGNAIT").
dico("R", 7, "ROGNANT").
dico("R", 7, "ROGNEES").
dico("R", 7, "ROGNENT").
dico("R", 7, "ROGNERA").
dico("R", 7, "ROGNEUR").
dico("R", 7, "ROGNEUX").
dico("R", 7, "ROGNIEZ").
dico("R", 7, "ROGNOIR").
dico("R", 7, "ROGNONS").
dico("R", 7, "ROGNURE").
dico("R", 7, "ROGOMME").
dico("R", 7, "ROGUEES").
dico("R", 7, "ROHARTS").
dico("R", 7, "ROIDEUR").
dico("R", 7, "ROIDIES").
dico("R", 7, "ROIDIRA").
dico("R", 7, "ROILLAI").
dico("R", 7, "ROILLAS").
dico("R", 7, "ROILLAT").
dico("R", 7, "ROILLEE").
dico("R", 7, "ROILLER").
dico("R", 7, "ROILLES").
dico("R", 7, "ROILLEZ").
dico("R", 7, "ROLAGES").
dico("R", 7, "ROLISTE").
dico("R", 7, "ROLLERS").
dico("R", 7, "ROLLEUR").
dico("R", 7, "ROLLIER").
dico("R", 7, "ROLLOTS").
dico("R", 7, "ROMAINE").
dico("R", 7, "ROMAINS").
dico("R", 7, "ROMANCA").
dico("R", 7, "ROMANCE").
dico("R", 7, "ROMANDE").
dico("R", 7, "ROMANDS").
dico("R", 7, "ROMANEE").
dico("R", 7, "ROMANES").
dico("R", 7, "ROMANIS").
dico("R", 7, "ROMANOS").
dico("R", 7, "ROMARIN").
dico("R", 7, "ROMPAIS").
dico("R", 7, "ROMPAIT").
dico("R", 7, "ROMPANT").
dico("R", 7, "ROMPENT").
dico("R", 7, "ROMPIEZ").
dico("R", 7, "ROMPONS").
dico("R", 7, "ROMPRAI").
dico("R", 7, "ROMPRAS").
dico("R", 7, "ROMPREZ").
dico("R", 7, "ROMPUES").
dico("R", 7, "RONCEUX").
dico("R", 7, "RONCHON").
dico("R", 7, "RONCIER").
dico("R", 7, "RONDADE").
dico("R", 7, "RONDEAU").
dico("R", 7, "RONDELS").
dico("R", 7, "RONDEUR").
dico("R", 7, "RONDIER").
dico("R", 7, "RONDIES").
dico("R", 7, "RONDINS").
dico("R", 7, "RONDIRA").
dico("R", 7, "RONEOTA").
dico("R", 7, "RONEOTE").
dico("R", 7, "RONFLAI").
dico("R", 7, "RONFLAS").
dico("R", 7, "RONFLAT").
dico("R", 7, "RONFLER").
dico("R", 7, "RONFLES").
dico("R", 7, "RONFLEZ").
dico("R", 7, "RONGEAI").
dico("R", 7, "RONGEAS").
dico("R", 7, "RONGEAT").
dico("R", 7, "RONGEES").
dico("R", 7, "RONGENT").
dico("R", 7, "RONGERA").
dico("R", 7, "RONGEUR").
dico("R", 7, "RONGIEZ").
dico("R", 7, "RONIERS").
dico("R", 7, "RONRONS").
dico("R", 7, "RONTGEN").
dico("R", 7, "ROOFING").
dico("R", 7, "ROOKERY").
dico("R", 7, "ROOTERS").
dico("R", 7, "ROQUAIS").
dico("R", 7, "ROQUAIT").
dico("R", 7, "ROQUANT").
dico("R", 7, "ROQUENT").
dico("R", 7, "ROQUERA").
dico("R", 7, "ROQUETS").
dico("R", 7, "ROQUIEZ").
dico("R", 7, "ROQUONS").
dico("R", 7, "RORQUAL").
dico("R", 7, "ROSACEE").
dico("R", 7, "ROSACES").
dico("R", 7, "ROSAGES").
dico("R", 7, "ROSAIRE").
dico("R", 7, "ROSALIE").
dico("R", 7, "ROSAMES").
dico("R", 7, "ROSASSE").
dico("R", 7, "ROSATES").
dico("R", 7, "ROSATRE").
dico("R", 7, "ROSBIFS").
dico("R", 7, "ROSEAUX").
dico("R", 7, "ROSELET").
dico("R", 7, "ROSEOLE").
dico("R", 7, "ROSERAI").
dico("R", 7, "ROSERAS").
dico("R", 7, "ROSEREZ").
dico("R", 7, "ROSETTE").
dico("R", 7, "ROSEURS").
dico("R", 7, "ROSEVAL").
dico("R", 7, "ROSIERE").
dico("R", 7, "ROSIERS").
dico("R", 7, "ROSIMES").
dico("R", 7, "ROSIONS").
dico("R", 7, "ROSIRAI").
dico("R", 7, "ROSIRAS").
dico("R", 7, "ROSIREZ").
dico("R", 7, "ROSISSE").
dico("R", 7, "ROSITES").
dico("R", 7, "ROSSAIS").
dico("R", 7, "ROSSAIT").
dico("R", 7, "ROSSANT").
dico("R", 7, "ROSSARD").
dico("R", 7, "ROSSEES").
dico("R", 7, "ROSSENT").
dico("R", 7, "ROSSERA").
dico("R", 7, "ROSSIEZ").
dico("R", 7, "ROSSONS").
dico("R", 7, "ROSTRAL").
dico("R", 7, "ROSTRES").
dico("R", 7, "ROTACEE").
dico("R", 7, "ROTACES").
dico("R", 7, "ROTAMES").
dico("R", 7, "ROTANGS").
dico("R", 7, "ROTARYS").
dico("R", 7, "ROTASSE").
dico("R", 7, "ROTATES").
dico("R", 7, "ROTATIF").
dico("R", 7, "ROTERAI").
dico("R", 7, "ROTERAS").
dico("R", 7, "ROTEREZ").
dico("R", 7, "ROTEURS").
dico("R", 7, "ROTEUSE").
dico("R", 7, "ROTIMES").
dico("R", 7, "ROTIONS").
dico("R", 7, "ROTIRAI").
dico("R", 7, "ROTIRAS").
dico("R", 7, "ROTIREZ").
dico("R", 7, "ROTISSE").
dico("R", 7, "ROTITES").
dico("R", 7, "ROTONDE").
dico("R", 7, "ROTOTOS").
dico("R", 7, "ROTRING").
dico("R", 7, "ROTULES").
dico("R", 7, "ROTURES").
dico("R", 7, "ROUABLE").
dico("R", 7, "ROUAGES").
dico("R", 7, "ROUAMES").
dico("R", 7, "ROUANNE").
dico("R", 7, "ROUASSE").
dico("R", 7, "ROUATES").
dico("R", 7, "ROUBINE").
dico("R", 7, "ROUBLAI").
dico("R", 7, "ROUBLAS").
dico("R", 7, "ROUBLAT").
dico("R", 7, "ROUBLEE").
dico("R", 7, "ROUBLER").
dico("R", 7, "ROUBLES").
dico("R", 7, "ROUBLEZ").
dico("R", 7, "ROUCHIS").
dico("R", 7, "ROUELLE").
dico("R", 7, "ROUERAI").
dico("R", 7, "ROUERAS").
dico("R", 7, "ROUEREZ").
dico("R", 7, "ROUERIE").
dico("R", 7, "ROUETTE").
dico("R", 7, "ROUGAIL").
dico("R", 7, "ROUGETS").
dico("R", 7, "ROUGEUR").
dico("R", 7, "ROUGIES").
dico("R", 7, "ROUGIRA").
dico("R", 7, "ROUILLA").
dico("R", 7, "ROUILLE").
dico("R", 7, "ROUIMES").
dico("R", 7, "ROUIONS").
dico("R", 7, "ROUIRAI").
dico("R", 7, "ROUIRAS").
dico("R", 7, "ROUIREZ").
dico("R", 7, "ROUISSE").
dico("R", 7, "ROUITES").
dico("R", 7, "ROULADE").
dico("R", 7, "ROULAGE").
dico("R", 7, "ROULAIS").
dico("R", 7, "ROULAIT").
dico("R", 7, "ROULANT").
dico("R", 7, "ROULEAU").
dico("R", 7, "ROULEES").
dico("R", 7, "ROULENT").
dico("R", 7, "ROULERA").
dico("R", 7, "ROULEUR").
dico("R", 7, "ROULIER").
dico("R", 7, "ROULIEZ").
dico("R", 7, "ROULOIR").
dico("R", 7, "ROULONS").
dico("R", 7, "ROULURE").
dico("R", 7, "ROUMAIN").
dico("R", 7, "ROUMIES").
dico("R", 7, "ROUPIES").
dico("R", 7, "ROUQUIN").
dico("R", 7, "ROUSSES").
dico("R", 7, "ROUSSIE").
dico("R", 7, "ROUSSIN").
dico("R", 7, "ROUSSIR").
dico("R", 7, "ROUSSIS").
dico("R", 7, "ROUSSIT").
dico("R", 7, "ROUSTES").
dico("R", 7, "ROUSTIE").
dico("R", 7, "ROUSTIR").
dico("R", 7, "ROUSTIS").
dico("R", 7, "ROUSTIT").
dico("R", 7, "ROUSTON").
dico("R", 7, "ROUTAGE").
dico("R", 7, "ROUTAIS").
dico("R", 7, "ROUTAIT").
dico("R", 7, "ROUTANT").
dico("R", 7, "ROUTARD").
dico("R", 7, "ROUTEES").
dico("R", 7, "ROUTENT").
dico("R", 7, "ROUTERA").
dico("R", 7, "ROUTEUR").
dico("R", 7, "ROUTIER").
dico("R", 7, "ROUTIEZ").
dico("R", 7, "ROUTINE").
dico("R", 7, "ROUTONS").
dico("R", 7, "ROUVERT").
dico("R", 7, "ROUVRES").
dico("R", 7, "ROUVREZ").
dico("R", 7, "ROUVRIR").
dico("R", 7, "ROUVRIS").
dico("R", 7, "ROUVRIT").
dico("R", 7, "ROWINGS").
dico("R", 7, "ROYALES").
dico("R", 7, "ROYAUMA").
dico("R", 7, "ROYAUME").
dico("R", 7, "ROYAUTE").
dico("R", 7, "RUAIENT").
dico("R", 7, "RUASSES").
dico("R", 7, "RUBANAI").
dico("R", 7, "RUBANAS").
dico("R", 7, "RUBANAT").
dico("R", 7, "RUBANEE").
dico("R", 7, "RUBANER").
dico("R", 7, "RUBANES").
dico("R", 7, "RUBANEZ").
dico("R", 7, "RUBATOS").
dico("R", 7, "RUBEFIA").
dico("R", 7, "RUBEFIE").
dico("R", 7, "RUBEOLE").
dico("R", 7, "RUBICAN").
dico("R", 7, "RUBINES").
dico("R", 7, "RUCHAIS").
dico("R", 7, "RUCHAIT").
dico("R", 7, "RUCHANT").
dico("R", 7, "RUCHEES").
dico("R", 7, "RUCHENT").
dico("R", 7, "RUCHERA").
dico("R", 7, "RUCHERS").
dico("R", 7, "RUCHIEZ").
dico("R", 7, "RUCHONS").
dico("R", 7, "RUCLONS").
dico("R", 7, "RUDENTA").
dico("R", 7, "RUDENTE").
dico("R", 7, "RUDERAL").
dico("R", 7, "RUDESSE").
dico("R", 7, "RUDISTE").
dico("R", 7, "RUDOIES").
dico("R", 7, "RUDOYAI").
dico("R", 7, "RUDOYAS").
dico("R", 7, "RUDOYAT").
dico("R", 7, "RUDOYEE").
dico("R", 7, "RUDOYER").
dico("R", 7, "RUDOYES").
dico("R", 7, "RUDOYEZ").
dico("R", 7, "RUELLES").
dico("R", 7, "RUERAIS").
dico("R", 7, "RUERAIT").
dico("R", 7, "RUERENT").
dico("R", 7, "RUERIEZ").
dico("R", 7, "RUERONS").
dico("R", 7, "RUERONT").
dico("R", 7, "RUFFIAN").
dico("R", 7, "RUFIANS").
dico("R", 7, "RUFIYAA").
dico("R", 7, "RUGIMES").
dico("R", 7, "RUGINAI").
dico("R", 7, "RUGINAS").
dico("R", 7, "RUGINAT").
dico("R", 7, "RUGINEE").
dico("R", 7, "RUGINER").
dico("R", 7, "RUGINES").
dico("R", 7, "RUGINEZ").
dico("R", 7, "RUGIRAI").
dico("R", 7, "RUGIRAS").
dico("R", 7, "RUGIREZ").
dico("R", 7, "RUGISSE").
dico("R", 7, "RUGITES").
dico("R", 7, "RUGUEUX").
dico("R", 7, "RUILAIS").
dico("R", 7, "RUILAIT").
dico("R", 7, "RUILANT").
dico("R", 7, "RUILEES").
dico("R", 7, "RUILENT").
dico("R", 7, "RUILERA").
dico("R", 7, "RUILIEZ").
dico("R", 7, "RUILONS").
dico("R", 7, "RUINAIS").
dico("R", 7, "RUINAIT").
dico("R", 7, "RUINANT").
dico("R", 7, "RUINEES").
dico("R", 7, "RUINENT").
dico("R", 7, "RUINERA").
dico("R", 7, "RUINEUX").
dico("R", 7, "RUINIEZ").
dico("R", 7, "RUINONS").
dico("R", 7, "RUINURE").
dico("R", 7, "RUMEURS").
dico("R", 7, "RUMINAI").
dico("R", 7, "RUMINAS").
dico("R", 7, "RUMINAT").
dico("R", 7, "RUMINEE").
dico("R", 7, "RUMINER").
dico("R", 7, "RUMINES").
dico("R", 7, "RUMINEZ").
dico("R", 7, "RUNIQUE").
dico("R", 7, "RUPAMES").
dico("R", 7, "RUPASSE").
dico("R", 7, "RUPATES").
dico("R", 7, "RUPERAI").
dico("R", 7, "RUPERAS").
dico("R", 7, "RUPEREZ").
dico("R", 7, "RUPIAHS").
dico("R", 7, "RUPINAI").
dico("R", 7, "RUPINAS").
dico("R", 7, "RUPINAT").
dico("R", 7, "RUPINEE").
dico("R", 7, "RUPINER").
dico("R", 7, "RUPINES").
dico("R", 7, "RUPINEZ").
dico("R", 7, "RUPIONS").
dico("R", 7, "RUPTEUR").
dico("R", 7, "RUPTURE").
dico("R", 7, "RURALES").
dico("R", 7, "RURBAIN").
dico("R", 7, "RUSAMES").
dico("R", 7, "RUSASSE").
dico("R", 7, "RUSATES").
dico("R", 7, "RUSERAI").
dico("R", 7, "RUSERAS").
dico("R", 7, "RUSEREZ").
dico("R", 7, "RUSIONS").
dico("R", 7, "RUSSISA").
dico("R", 7, "RUSSISE").
dico("R", 7, "RUSSULE").
dico("R", 7, "RUSTAUD").
dico("R", 7, "RUSTINE").
dico("R", 7, "RUSTRES").
dico("R", 7, "RUTACEE").
dico("R", 7, "RUTHENE").
dico("R", 7, "RUTILAI").
dico("R", 7, "RUTILAS").
dico("R", 7, "RUTILAT").
dico("R", 7, "RUTILER").
dico("R", 7, "RUTILES").
dico("R", 7, "RUTILEZ").
dico("R", 7, "RUTINES").
dico("R", 7, "RYTHMAI").
dico("R", 7, "RYTHMAS").
dico("R", 7, "RYTHMAT").
dico("R", 7, "RYTHMEE").
dico("R", 7, "RYTHMER").
dico("R", 7, "RYTHMES").
dico("R", 7, "RYTHMEZ").
