dico("S", 6, "SAANEN").
dico("S", 6, "SABBAT").
dico("S", 6, "SABEEN").
dico("S", 6, "SABINE").
dico("S", 6, "SABINS").
dico("S", 6, "SABIRS").
dico("S", 6, "SABLAI").
dico("S", 6, "SABLAS").
dico("S", 6, "SABLAT").
dico("S", 6, "SABLEE").
dico("S", 6, "SABLER").
dico("S", 6, "SABLES").
dico("S", 6, "SABLEZ").
dico("S", 6, "SABLON").
dico("S", 6, "SABORD").
dico("S", 6, "SABOTA").
dico("S", 6, "SABOTE").
dico("S", 6, "SABOTS").
dico("S", 6, "SABRAI").
dico("S", 6, "SABRAS").
dico("S", 6, "SABRAT").
dico("S", 6, "SABREE").
dico("S", 6, "SABRER").
dico("S", 6, "SABRES").
dico("S", 6, "SABREZ").
dico("S", 6, "SACHEE").
dico("S", 6, "SACHEM").
dico("S", 6, "SACHES").
dico("S", 6, "SACHET").
dico("S", 6, "SACHEZ").
dico("S", 6, "SACOME").
dico("S", 6, "SACQUA").
dico("S", 6, "SACQUE").
dico("S", 6, "SACRAI").
dico("S", 6, "SACRAL").
dico("S", 6, "SACRAS").
dico("S", 6, "SACRAT").
dico("S", 6, "SACREE").
dico("S", 6, "SACRER").
dico("S", 6, "SACRES").
dico("S", 6, "SACRET").
dico("S", 6, "SACREZ").
dico("S", 6, "SACRUM").
dico("S", 6, "SAFARI").
dico("S", 6, "SAFRAN").
dico("S", 6, "SAFRES").
dico("S", 6, "SAGACE").
dico("S", 6, "SAGAIE").
dico("S", 6, "SAGARD").
dico("S", 6, "SAGINA").
dico("S", 6, "SAGINE").
dico("S", 6, "SAGOUS").
dico("S", 6, "SAGUMS").
dico("S", 6, "SAHELS").
dico("S", 6, "SAHIBS").
dico("S", 6, "SAIGAS").
dico("S", 6, "SAIGNA").
dico("S", 6, "SAIGNE").
dico("S", 6, "SAILLE").
dico("S", 6, "SAILLI").
dico("S", 6, "SAINES").
dico("S", 6, "SAINTE").
dico("S", 6, "SAINTS").
dico("S", 6, "SAISIE").
dico("S", 6, "SAISIR").
dico("S", 6, "SAISIS").
dico("S", 6, "SAISIT").
dico("S", 6, "SAISON").
dico("S", 6, "SAITES").
dico("S", 6, "SAJOUS").
dico("S", 6, "SAKIEH").
dico("S", 6, "SAKTIS").
dico("S", 6, "SALACE").
dico("S", 6, "SALADE").
dico("S", 6, "SALAGE").
dico("S", 6, "SALAIS").
dico("S", 6, "SALAIT").
dico("S", 6, "SALAMI").
dico("S", 6, "SALANT").
dico("S", 6, "SALATS").
dico("S", 6, "SALAUD").
dico("S", 6, "SALEES").
dico("S", 6, "SALENT").
dico("S", 6, "SALEPS").
dico("S", 6, "SALERA").
dico("S", 6, "SALERS").
dico("S", 6, "SALETE").
dico("S", 6, "SALEUR").
dico("S", 6, "SALIEN").
dico("S", 6, "SALIES").
dico("S", 6, "SALIEZ").
dico("S", 6, "SALINE").
dico("S", 6, "SALINS").
dico("S", 6, "SALIRA").
dico("S", 6, "SALIVA").
dico("S", 6, "SALIVE").
dico("S", 6, "SALLES").
dico("S", 6, "SALMIS").
dico("S", 6, "SALOIR").
dico("S", 6, "SALOLS").
dico("S", 6, "SALOME").
dico("S", 6, "SALONS").
dico("S", 6, "SALOON").
dico("S", 6, "SALOPA").
dico("S", 6, "SALOPE").
dico("S", 6, "SALOPS").
dico("S", 6, "SALPES").
dico("S", 6, "SALSAS").
dico("S", 6, "SALSES").
dico("S", 6, "SALTOS").
dico("S", 6, "SALUAI").
dico("S", 6, "SALUAS").
dico("S", 6, "SALUAT").
dico("S", 6, "SALUEE").
dico("S", 6, "SALUER").
dico("S", 6, "SALUES").
dico("S", 6, "SALUEZ").
dico("S", 6, "SALURE").
dico("S", 6, "SALUTS").
dico("S", 6, "SALVES").
dico("S", 6, "SAMARA").
dico("S", 6, "SAMARE").
dico("S", 6, "SAMBAS").
dico("S", 6, "SAMBOS").
dico("S", 6, "SAMEDI").
dico("S", 6, "SAMIEN").
dico("S", 6, "SAMITS").
dico("S", 6, "SAMMYS").
dico("S", 6, "SAMOAN").
dico("S", 6, "SAMOLE").
dico("S", 6, "SAMPAN").
dico("S", 6, "SAMPLA").
dico("S", 6, "SAMPLE").
dico("S", 6, "SAMPOT").
dico("S", 6, "SANDIX").
dico("S", 6, "SANDOW").
dico("S", 6, "SANDRE").
dico("S", 6, "SANDYX").
dico("S", 6, "SANGLA").
dico("S", 6, "SANGLE").
dico("S", 6, "SANIES").
dico("S", 6, "SANTAL").
dico("S", 6, "SANTES").
dico("S", 6, "SANTON").
dico("S", 6, "SANVES").
dico("S", 6, "SANZAS").
dico("S", 6, "SAOLAS").
dico("S", 6, "SAOULA").
dico("S", 6, "SAOULE").
dico("S", 6, "SAOULS").
dico("S", 6, "SAPAIS").
dico("S", 6, "SAPAIT").
dico("S", 6, "SAPANT").
dico("S", 6, "SAPEES").
dico("S", 6, "SAPENT").
dico("S", 6, "SAPERA").
dico("S", 6, "SAPEUR").
dico("S", 6, "SAPHIR").
dico("S", 6, "SAPIDE").
dico("S", 6, "SAPIEZ").
dico("S", 6, "SAPINE").
dico("S", 6, "SAPINS").
dico("S", 6, "SAPONE").
dico("S", 6, "SAPONS").
dico("S", 6, "SAPOTE").
dico("S", 6, "SAPPAN").
dico("S", 6, "SAQUAI").
dico("S", 6, "SAQUAS").
dico("S", 6, "SAQUAT").
dico("S", 6, "SAQUEE").
dico("S", 6, "SAQUER").
dico("S", 6, "SAQUES").
dico("S", 6, "SAQUEZ").
dico("S", 6, "SARCLA").
dico("S", 6, "SARCLE").
dico("S", 6, "SARDES").
dico("S", 6, "SARGUE").
dico("S", 6, "SARINS").
dico("S", 6, "SARODE").
dico("S", 6, "SARODS").
dico("S", 6, "SARONG").
dico("S", 6, "SARRAU").
dico("S", 6, "SASSAI").
dico("S", 6, "SASSAS").
dico("S", 6, "SASSAT").
dico("S", 6, "SASSEE").
dico("S", 6, "SASSER").
dico("S", 6, "SASSES").
dico("S", 6, "SASSEZ").
dico("S", 6, "SATANE").
dico("S", 6, "SATINA").
dico("S", 6, "SATINE").
dico("S", 6, "SATINS").
dico("S", 6, "SATIRE").
dico("S", 6, "SATORI").
dico("S", 6, "SATURA").
dico("S", 6, "SATURE").
dico("S", 6, "SATYRE").
dico("S", 6, "SAUCAI").
dico("S", 6, "SAUCAS").
dico("S", 6, "SAUCAT").
dico("S", 6, "SAUCEE").
dico("S", 6, "SAUCER").
dico("S", 6, "SAUCES").
dico("S", 6, "SAUCEZ").
dico("S", 6, "SAUGES").
dico("S", 6, "SAULEE").
dico("S", 6, "SAULES").
dico("S", 6, "SAUMON").
dico("S", 6, "SAUMUR").
dico("S", 6, "SAUNAI").
dico("S", 6, "SAUNAS").
dico("S", 6, "SAUNAT").
dico("S", 6, "SAUNER").
dico("S", 6, "SAUNES").
dico("S", 6, "SAUNEZ").
dico("S", 6, "SAUPES").
dico("S", 6, "SAURAI").
dico("S", 6, "SAURAS").
dico("S", 6, "SAURAT").
dico("S", 6, "SAUREE").
dico("S", 6, "SAUREL").
dico("S", 6, "SAURER").
dico("S", 6, "SAURES").
dico("S", 6, "SAURET").
dico("S", 6, "SAUREZ").
dico("S", 6, "SAURIE").
dico("S", 6, "SAURIN").
dico("S", 6, "SAURIR").
dico("S", 6, "SAURIS").
dico("S", 6, "SAURIT").
dico("S", 6, "SAUTAI").
dico("S", 6, "SAUTAS").
dico("S", 6, "SAUTAT").
dico("S", 6, "SAUTEE").
dico("S", 6, "SAUTER").
dico("S", 6, "SAUTES").
dico("S", 6, "SAUTEZ").
dico("S", 6, "SAUVAI").
dico("S", 6, "SAUVAS").
dico("S", 6, "SAUVAT").
dico("S", 6, "SAUVEE").
dico("S", 6, "SAUVER").
dico("S", 6, "SAUVES").
dico("S", 6, "SAUVEZ").
dico("S", 6, "SAVAIS").
dico("S", 6, "SAVAIT").
dico("S", 6, "SAVANE").
dico("S", 6, "SAVANT").
dico("S", 6, "SAVART").
dico("S", 6, "SAVATE").
dico("S", 6, "SAVENT").
dico("S", 6, "SAVEUR").
dico("S", 6, "SAVIEZ").
dico("S", 6, "SAVOIR").
dico("S", 6, "SAVONS").
dico("S", 6, "SAXONS").
dico("S", 6, "SAYONS").
dico("S", 6, "SBIRES").
dico("S", 6, "SBRINZ").
dico("S", 6, "SCALDE").
dico("S", 6, "SCALPA").
dico("S", 6, "SCALPE").
dico("S", 6, "SCALPS").
dico("S", 6, "SCAMPI").
dico("S", 6, "SCANDA").
dico("S", 6, "SCANDE").
dico("S", 6, "SCANNA").
dico("S", 6, "SCANNE").
dico("S", 6, "SCARES").
dico("S", 6, "SCATOL").
dico("S", 6, "SCEAUX").
dico("S", 6, "SCELLA").
dico("S", 6, "SCELLE").
dico("S", 6, "SCENES").
dico("S", 6, "SCHADA").
dico("S", 6, "SCHADE").
dico("S", 6, "SCHAHS").
dico("S", 6, "SCHAKO").
dico("S", 6, "SCHEIK").
dico("S", 6, "SCHEMA").
dico("S", 6, "SCHEME").
dico("S", 6, "SCHEOL").
dico("S", 6, "SCHIZO").
dico("S", 6, "SCHLEM").
dico("S", 6, "SCHLEU").
dico("S", 6, "SCHUPO").
dico("S", 6, "SCHUSS").
dico("S", 6, "SCHWAS").
dico("S", 6, "SCIAGE").
dico("S", 6, "SCIAIS").
dico("S", 6, "SCIAIT").
dico("S", 6, "SCIANT").
dico("S", 6, "SCIEES").
dico("S", 6, "SCIENE").
dico("S", 6, "SCIENT").
dico("S", 6, "SCIERA").
dico("S", 6, "SCIEUR").
dico("S", 6, "SCIIEZ").
dico("S", 6, "SCILLE").
dico("S", 6, "SCINDA").
dico("S", 6, "SCINDE").
dico("S", 6, "SCIONS").
dico("S", 6, "SCIRPE").
dico("S", 6, "SCIURE").
dico("S", 6, "SCLERE").
dico("S", 6, "SCOLEX").
dico("S", 6, "SCOLIE").
dico("S", 6, "SCONES").
dico("S", 6, "SCONSE").
dico("S", 6, "SCOOPS").
dico("S", 6, "SCOPAS").
dico("S", 6, "SCOPES").
dico("S", 6, "SCOPIE").
dico("S", 6, "SCORAI").
dico("S", 6, "SCORAS").
dico("S", 6, "SCORAT").
dico("S", 6, "SCOREE").
dico("S", 6, "SCORER").
dico("S", 6, "SCORES").
dico("S", 6, "SCOREZ").
dico("S", 6, "SCORIE").
dico("S", 6, "SCOTCH").
dico("S", 6, "SCOTIE").
dico("S", 6, "SCOUTE").
dico("S", 6, "SCOUTS").
dico("S", 6, "SCRIBE").
dico("S", 6, "SCRIPT").
dico("S", 6, "SCRUBS").
dico("S", 6, "SCRUTA").
dico("S", 6, "SCRUTE").
dico("S", 6, "SCULLS").
dico("S", 6, "SCUTUM").
dico("S", 6, "SCYTHE").
dico("S", 6, "SEANCE").
dico("S", 6, "SEANTE").
dico("S", 6, "SEANTS").
dico("S", 6, "SEBACE").
dico("S", 6, "SEBILE").
dico("S", 6, "SEBKAS").
dico("S", 6, "SEBKHA").
dico("S", 6, "SEBKRA").
dico("S", 6, "SEBUMS").
dico("S", 6, "SECAMS").
dico("S", 6, "SECANT").
dico("S", 6, "SECCOS").
dico("S", 6, "SECHAI").
dico("S", 6, "SECHAS").
dico("S", 6, "SECHAT").
dico("S", 6, "SECHEE").
dico("S", 6, "SECHER").
dico("S", 6, "SECHES").
dico("S", 6, "SECHEZ").
dico("S", 6, "SECOND").
dico("S", 6, "SECOUA").
dico("S", 6, "SECOUE").
dico("S", 6, "SECRET").
dico("S", 6, "SECTES").
dico("S", 6, "SEDANS").
dico("S", 6, "SEDONS").
dico("S", 6, "SEDUIS").
dico("S", 6, "SEDUIT").
dico("S", 6, "SEDUMS").
dico("S", 6, "SEGALA").
dico("S", 6, "SEGHIA").
dico("S", 6, "SEGUIA").
dico("S", 6, "SEHTAR").
dico("S", 6, "SEICHE").
dico("S", 6, "SEIDES").
dico("S", 6, "SEIGLE").
dico("S", 6, "SEILLE").
dico("S", 6, "SEIMES").
dico("S", 6, "SEINES").
dico("S", 6, "SEINGS").
dico("S", 6, "SEISME").
dico("S", 6, "SEJOUR").
dico("S", 6, "SELECT").
dico("S", 6, "SELENE").
dico("S", 6, "SELLAI").
dico("S", 6, "SELLAS").
dico("S", 6, "SELLAT").
dico("S", 6, "SELLEE").
dico("S", 6, "SELLER").
dico("S", 6, "SELLES").
dico("S", 6, "SELLEZ").
dico("S", 6, "SELVAS").
dico("S", 6, "SELVES").
dico("S", 6, "SEMAIS").
dico("S", 6, "SEMAIT").
dico("S", 6, "SEMANT").
dico("S", 6, "SEMBLA").
dico("S", 6, "SEMBLE").
dico("S", 6, "SEMEES").
dico("S", 6, "SEMEME").
dico("S", 6, "SEMENT").
dico("S", 6, "SEMERA").
dico("S", 6, "SEMEUR").
dico("S", 6, "SEMIEZ").
dico("S", 6, "SEMITE").
dico("S", 6, "SEMOIR").
dico("S", 6, "SEMONS").
dico("S", 6, "SEMPLE").
dico("S", 6, "SEMTEX").
dico("S", 6, "SENATS").
dico("S", 6, "SENAUS").
dico("S", 6, "SENAUX").
dico("S", 6, "SENEVE").
dico("S", 6, "SENILE").
dico("S", 6, "SENIOR").
dico("S", 6, "SENNES").
dico("S", 6, "SENSAS").
dico("S", 6, "SENSEE").
dico("S", 6, "SENSES").
dico("S", 6, "SENTES").
dico("S", 6, "SENTEZ").
dico("S", 6, "SENTIE").
dico("S", 6, "SENTIR").
dico("S", 6, "SENTIS").
dico("S", 6, "SENTIT").
dico("S", 6, "SEPALE").
dico("S", 6, "SEPARA").
dico("S", 6, "SEPARE").
dico("S", 6, "SEPIAS").
dico("S", 6, "SEPTAL").
dico("S", 6, "SEPTUM").
dico("S", 6, "SEQUIN").
dico("S", 6, "SERACS").
dico("S", 6, "SERAIL").
dico("S", 6, "SERAIS").
dico("S", 6, "SERAIT").
dico("S", 6, "SERANS").
dico("S", 6, "SERBES").
dico("S", 6, "SERDAB").
dico("S", 6, "SEREIN").
dico("S", 6, "SEREUX").
dico("S", 6, "SERGES").
dico("S", 6, "SERIAI").
dico("S", 6, "SERIAL").
dico("S", 6, "SERIAS").
dico("S", 6, "SERIAT").
dico("S", 6, "SERIEE").
dico("S", 6, "SERIEL").
dico("S", 6, "SERIER").
dico("S", 6, "SERIES").
dico("S", 6, "SERIEZ").
dico("S", 6, "SERINA").
dico("S", 6, "SERINE").
dico("S", 6, "SERINS").
dico("S", 6, "SERMON").
dico("S", 6, "SERONS").
dico("S", 6, "SERONT").
dico("S", 6, "SERPES").
dico("S", 6, "SERRAI").
dico("S", 6, "SERRAN").
dico("S", 6, "SERRAS").
dico("S", 6, "SERRAT").
dico("S", 6, "SERREE").
dico("S", 6, "SERRER").
dico("S", 6, "SERRES").
dico("S", 6, "SERREZ").
dico("S", 6, "SERTAO").
dico("S", 6, "SERTES").
dico("S", 6, "SERTIE").
dico("S", 6, "SERTIR").
dico("S", 6, "SERTIS").
dico("S", 6, "SERTIT").
dico("S", 6, "SERUMS").
dico("S", 6, "SERVAL").
dico("S", 6, "SERVES").
dico("S", 6, "SERVEZ").
dico("S", 6, "SERVIE").
dico("S", 6, "SERVIR").
dico("S", 6, "SERVIS").
dico("S", 6, "SERVIT").
dico("S", 6, "SESAME").
dico("S", 6, "SETACE").
dico("S", 6, "SETARS").
dico("S", 6, "SETIER").
dico("S", 6, "SETOIS").
dico("S", 6, "SETONS").
dico("S", 6, "SETTER").
dico("S", 6, "SEUILS").
dico("S", 6, "SEULES").
dico("S", 6, "SEULET").
dico("S", 6, "SEVERE").
dico("S", 6, "SEVIRA").
dico("S", 6, "SEVRAI").
dico("S", 6, "SEVRAS").
dico("S", 6, "SEVRAT").
dico("S", 6, "SEVREE").
dico("S", 6, "SEVRER").
dico("S", 6, "SEVRES").
dico("S", 6, "SEVREZ").
dico("S", 6, "SEXAGE").
dico("S", 6, "SEXTES").
dico("S", 6, "SEXUEE").
dico("S", 6, "SEXUEL").
dico("S", 6, "SEXUES").
dico("S", 6, "SEYAIT").
dico("S", 6, "SEYANT").
dico("S", 6, "SEYVAL").
dico("S", 6, "SHAKER").
dico("S", 6, "SHAKOS").
dico("S", 6, "SHAKTI").
dico("S", 6, "SHAMAS").
dico("S", 6, "SHANAS").
dico("S", 6, "SHEKEL").
dico("S", 6, "SHELFS").
dico("S", 6, "SHEOLS").
dico("S", 6, "SHERIF").
dico("S", 6, "SHERPA").
dico("S", 6, "SHERRY").
dico("S", 6, "SHIFTS").
dico("S", 6, "SHILOM").
dico("S", 6, "SHIMMY").
dico("S", 6, "SHINTO").
dico("S", 6, "SHOGIS").
dico("S", 6, "SHOGUN").
dico("S", 6, "SHOOTA").
dico("S", 6, "SHOOTE").
dico("S", 6, "SHOOTS").
dico("S", 6, "SHORTS").
dico("S", 6, "SHTETL").
dico("S", 6, "SHUDRA").
dico("S", 6, "SHUNTA").
dico("S", 6, "SHUNTE").
dico("S", 6, "SHUNTS").
dico("S", 6, "SIALIS").
dico("S", 6, "SICLAI").
dico("S", 6, "SICLAS").
dico("S", 6, "SICLAT").
dico("S", 6, "SICLEE").
dico("S", 6, "SICLER").
dico("S", 6, "SICLES").
dico("S", 6, "SICLEZ").
dico("S", 6, "SIDEEN").
dico("S", 6, "SIDERA").
dico("S", 6, "SIDERE").
dico("S", 6, "SIECLE").
dico("S", 6, "SIEENT").
dico("S", 6, "SIEGEA").
dico("S", 6, "SIEGER").
dico("S", 6, "SIEGES").
dico("S", 6, "SIEGEZ").
dico("S", 6, "SIENNE").
dico("S", 6, "SIERRA").
dico("S", 6, "SIESTA").
dico("S", 6, "SIESTE").
dico("S", 6, "SIEURS").
dico("S", 6, "SIFFLA").
dico("S", 6, "SIFFLE").
dico("S", 6, "SIGLEE").
dico("S", 6, "SIGLES").
dico("S", 6, "SIGNAI").
dico("S", 6, "SIGNAL").
dico("S", 6, "SIGNAS").
dico("S", 6, "SIGNAT").
dico("S", 6, "SIGNEE").
dico("S", 6, "SIGNER").
dico("S", 6, "SIGNES").
dico("S", 6, "SIGNET").
dico("S", 6, "SIGNEZ").
dico("S", 6, "SIKHES").
dico("S", 6, "SILAIS").
dico("S", 6, "SILAIT").
dico("S", 6, "SILANE").
dico("S", 6, "SILANT").
dico("S", 6, "SILENE").
dico("S", 6, "SILENT").
dico("S", 6, "SILERA").
dico("S", 6, "SILICE").
dico("S", 6, "SILIEZ").
dico("S", 6, "SILLET").
dico("S", 6, "SILLON").
dico("S", 6, "SILONS").
dico("S", 6, "SILPHE").
dico("S", 6, "SILURE").
dico("S", 6, "SILVES").
dico("S", 6, "SIMIEN").
dico("S", 6, "SIMILI").
dico("S", 6, "SIMOUN").
dico("S", 6, "SIMPLE").
dico("S", 6, "SIMULA").
dico("S", 6, "SIMULE").
dico("S", 6, "SINGEA").
dico("S", 6, "SINGEE").
dico("S", 6, "SINGER").
dico("S", 6, "SINGES").
dico("S", 6, "SINGEZ").
dico("S", 6, "SINGLE").
dico("S", 6, "SINISA").
dico("S", 6, "SINISE").
dico("S", 6, "SINITE").
dico("S", 6, "SINOCS").
dico("S", 6, "SINTER").
dico("S", 6, "SINUAI").
dico("S", 6, "SINUAS").
dico("S", 6, "SINUAT").
dico("S", 6, "SINUEE").
dico("S", 6, "SINUER").
dico("S", 6, "SINUES").
dico("S", 6, "SINUEZ").
dico("S", 6, "SIPHON").
dico("S", 6, "SIRDAR").
dico("S", 6, "SIRENE").
dico("S", 6, "SIRLIS").
dico("S", 6, "SIROCO").
dico("S", 6, "SIROPS").
dico("S", 6, "SIROTA").
dico("S", 6, "SIROTE").
dico("S", 6, "SISALS").
dico("S", 6, "SISMAL").
dico("S", 6, "SISTRE").
dico("S", 6, "SITARS").
dico("S", 6, "SITCOM").
dico("S", 6, "SITUAI").
dico("S", 6, "SITUAS").
dico("S", 6, "SITUAT").
dico("S", 6, "SITUEE").
dico("S", 6, "SITUER").
dico("S", 6, "SITUES").
dico("S", 6, "SITUEZ").
dico("S", 6, "SIXAIN").
dico("S", 6, "SIXTES").
dico("S", 6, "SIXTUS").
dico("S", 6, "SIZAIN").
dico("S", 6, "SKATES").
dico("S", 6, "SKEETS").
dico("S", 6, "SKETCH").
dico("S", 6, "SKIAIS").
dico("S", 6, "SKIAIT").
dico("S", 6, "SKIANT").
dico("S", 6, "SKIENT").
dico("S", 6, "SKIERA").
dico("S", 6, "SKIEUR").
dico("S", 6, "SKIFFS").
dico("S", 6, "SKIIEZ").
dico("S", 6, "SKIONS").
dico("S", 6, "SKIPPA").
dico("S", 6, "SKIPPE").
dico("S", 6, "SKUNKS").
dico("S", 6, "SLALOM").
dico("S", 6, "SLANGS").
dico("S", 6, "SLASHS").
dico("S", 6, "SLAVES").
dico("S", 6, "SLAVON").
dico("S", 6, "SLICAI").
dico("S", 6, "SLICAS").
dico("S", 6, "SLICAT").
dico("S", 6, "SLICEE").
dico("S", 6, "SLICER").
dico("S", 6, "SLICES").
dico("S", 6, "SLICEZ").
dico("S", 6, "SLIKKE").
dico("S", 6, "SLOCHE").
dico("S", 6, "SLOGAN").
dico("S", 6, "SLOOPS").
dico("S", 6, "SLUSHS").
dico("S", 6, "SMALAH").
dico("S", 6, "SMALAS").
dico("S", 6, "SMALTS").
dico("S", 6, "SMASHA").
dico("S", 6, "SMASHE").
dico("S", 6, "SMASHS").
dico("S", 6, "SMEGMA").
dico("S", 6, "SMILAX").
dico("S", 6, "SMILEY").
dico("S", 6, "SMILLA").
dico("S", 6, "SMILLE").
dico("S", 6, "SMOCKS").
dico("S", 6, "SMOLTS").
dico("S", 6, "SMURFA").
dico("S", 6, "SMURFE").
dico("S", 6, "SMURFS").
dico("S", 6, "SNACKS").
dico("S", 6, "SNIFAI").
dico("S", 6, "SNIFAS").
dico("S", 6, "SNIFAT").
dico("S", 6, "SNIFEE").
dico("S", 6, "SNIFER").
dico("S", 6, "SNIFES").
dico("S", 6, "SNIFEZ").
dico("S", 6, "SNIFFA").
dico("S", 6, "SNIFFE").
dico("S", 6, "SNIPER").
dico("S", 6, "SNOBAI").
dico("S", 6, "SNOBAS").
dico("S", 6, "SNOBAT").
dico("S", 6, "SNOBEE").
dico("S", 6, "SNOBER").
dico("S", 6, "SNOBES").
dico("S", 6, "SNOBEZ").
dico("S", 6, "SOBRES").
dico("S", 6, "SOCCER").
dico("S", 6, "SOCIAL").
dico("S", 6, "SOCIOS").
dico("S", 6, "SOCKET").
dico("S", 6, "SOCLES").
dico("S", 6, "SOCQUE").
dico("S", 6, "SODABI").
dico("S", 6, "SODEES").
dico("S", 6, "SODIUM").
dico("S", 6, "SODOKU").
dico("S", 6, "SOEURS").
dico("S", 6, "SOIENT").
dico("S", 6, "SOIGNA").
dico("S", 6, "SOIGNE").
dico("S", 6, "SOIREE").
dico("S", 6, "SOLAGE").
dico("S", 6, "SOLDAI").
dico("S", 6, "SOLDAS").
dico("S", 6, "SOLDAT").
dico("S", 6, "SOLDEE").
dico("S", 6, "SOLDER").
dico("S", 6, "SOLDES").
dico("S", 6, "SOLDEZ").
dico("S", 6, "SOLEAS").
dico("S", 6, "SOLEIL").
dico("S", 6, "SOLENS").
dico("S", 6, "SOLFIA").
dico("S", 6, "SOLFIE").
dico("S", 6, "SOLIDE").
dico("S", 6, "SOLINS").
dico("S", 6, "SOLIVE").
dico("S", 6, "SOLUTE").
dico("S", 6, "SOMALI").
dico("S", 6, "SOMANS").
dico("S", 6, "SOMBRA").
dico("S", 6, "SOMBRE").
dico("S", 6, "SOMITE").
dico("S", 6, "SOMMAI").
dico("S", 6, "SOMMAS").
dico("S", 6, "SOMMAT").
dico("S", 6, "SOMMEE").
dico("S", 6, "SOMMER").
dico("S", 6, "SOMMES").
dico("S", 6, "SOMMET").
dico("S", 6, "SOMMEZ").
dico("S", 6, "SOMONI").
dico("S", 6, "SONALS").
dico("S", 6, "SONARS").
dico("S", 6, "SONATE").
dico("S", 6, "SONDAI").
dico("S", 6, "SONDAS").
dico("S", 6, "SONDAT").
dico("S", 6, "SONDEE").
dico("S", 6, "SONDER").
dico("S", 6, "SONDES").
dico("S", 6, "SONDEZ").
dico("S", 6, "SONGEA").
dico("S", 6, "SONGER").
dico("S", 6, "SONGES").
dico("S", 6, "SONGEZ").
dico("S", 6, "SONIES").
dico("S", 6, "SONNAI").
dico("S", 6, "SONNAS").
dico("S", 6, "SONNAT").
dico("S", 6, "SONNEE").
dico("S", 6, "SONNER").
dico("S", 6, "SONNES").
dico("S", 6, "SONNET").
dico("S", 6, "SONNEZ").
dico("S", 6, "SONORE").
dico("S", 6, "SOPORS").
dico("S", 6, "SOQUET").
dico("S", 6, "SORBES").
dico("S", 6, "SORBET").
dico("S", 6, "SORGHO").
dico("S", 6, "SORITE").
dico("S", 6, "SORTES").
dico("S", 6, "SORTEZ").
dico("S", 6, "SORTIE").
dico("S", 6, "SORTIR").
dico("S", 6, "SORTIS").
dico("S", 6, "SORTIT").
dico("S", 6, "SOSIES").
dico("S", 6, "SOTCHS").
dico("S", 6, "SOTIES").
dico("S", 6, "SOTTES").
dico("S", 6, "SOTTIE").
dico("S", 6, "SOUABE").
dico("S", 6, "SOUAGE").
dico("S", 6, "SOUCHE").
dico("S", 6, "SOUCIA").
dico("S", 6, "SOUCIE").
dico("S", 6, "SOUCIS").
dico("S", 6, "SOUDAI").
dico("S", 6, "SOUDAN").
dico("S", 6, "SOUDAS").
dico("S", 6, "SOUDAT").
dico("S", 6, "SOUDEE").
dico("S", 6, "SOUDER").
dico("S", 6, "SOUDES").
dico("S", 6, "SOUDEZ").
dico("S", 6, "SOUFIE").
dico("S", 6, "SOUFIS").
dico("S", 6, "SOUFRA").
dico("S", 6, "SOUFRE").
dico("S", 6, "SOULAI").
dico("S", 6, "SOULAS").
dico("S", 6, "SOULAT").
dico("S", 6, "SOULEE").
dico("S", 6, "SOULER").
dico("S", 6, "SOULES").
dico("S", 6, "SOULEZ").
dico("S", 6, "SOULON").
dico("S", 6, "SOULOT").
dico("S", 6, "SOULTE").
dico("S", 6, "SOUMET").
dico("S", 6, "SOUMIS").
dico("S", 6, "SOUMIT").
dico("S", 6, "SOUNAS").
dico("S", 6, "SOUNNA").
dico("S", 6, "SOUPAI").
dico("S", 6, "SOUPAS").
dico("S", 6, "SOUPAT").
dico("S", 6, "SOUPER").
dico("S", 6, "SOUPES").
dico("S", 6, "SOUPEZ").
dico("S", 6, "SOUPIR").
dico("S", 6, "SOUPLE").
dico("S", 6, "SOUQUA").
dico("S", 6, "SOUQUE").
dico("S", 6, "SOURCE").
dico("S", 6, "SOURDE").
dico("S", 6, "SOURDS").
dico("S", 6, "SOURIE").
dico("S", 6, "SOURIS").
dico("S", 6, "SOURIT").
dico("S", 6, "SOUTES").
dico("S", 6, "SOUTIF").
dico("S", 6, "SOUTRA").
dico("S", 6, "SOVIET").
dico("S", 6, "SOYERE").
dico("S", 6, "SOYERS").
dico("S", 6, "SOYEUX").
dico("S", 6, "SOYONS").
dico("S", 6, "SPAHIS").
dico("S", 6, "SPALAX").
dico("S", 6, "SPARES").
dico("S", 6, "SPARTE").
dico("S", 6, "SPARTS").
dico("S", 6, "SPASME").
dico("S", 6, "SPATHE").
dico("S", 6, "SPATHS").
dico("S", 6, "SPEECH").
dico("S", 6, "SPEEDA").
dico("S", 6, "SPEEDE").
dico("S", 6, "SPEEDS").
dico("S", 6, "SPEISS").
dico("S", 6, "SPELEO").
dico("S", 6, "SPERME").
dico("S", 6, "SPHENE").
dico("S", 6, "SPHERE").
dico("S", 6, "SPHINX").
dico("S", 6, "SPICAS").
dico("S", 6, "SPIDER").
dico("S", 6, "SPINAL").
dico("S", 6, "SPIRAL").
dico("S", 6, "SPIREE").
dico("S", 6, "SPIRES").
dico("S", 6, "SPIROU").
dico("S", 6, "SPLEEN").
dico("S", 6, "SPOLIA").
dico("S", 6, "SPOLIE").
dico("S", 6, "SPORES").
dico("S", 6, "SPORTS").
dico("S", 6, "SPOULE").
dico("S", 6, "SPRATS").
dico("S", 6, "SPRAYS").
dico("S", 6, "SPRINT").
dico("S", 6, "SPRUES").
dico("S", 6, "SPUMES").
dico("S", 6, "SQUALE").
dico("S", 6, "SQUAME").
dico("S", 6, "SQUARE").
dico("S", 6, "SQUASH").
dico("S", 6, "SQUATS").
dico("S", 6, "SQUAWS").
dico("S", 6, "SQUIRE").
dico("S", 6, "STABLE").
dico("S", 6, "STADES").
dico("S", 6, "STADIA").
dico("S", 6, "STAFFA").
dico("S", 6, "STAFFE").
dico("S", 6, "STAFFS").
dico("S", 6, "STAGES").
dico("S", 6, "STAGNA").
dico("S", 6, "STAGNE").
dico("S", 6, "STALAG").
dico("S", 6, "STALLE").
dico("S", 6, "STAMMS").
dico("S", 6, "STANCE").
dico("S", 6, "STANDS").
dico("S", 6, "STARIE").
dico("S", 6, "STASES").
dico("S", 6, "STATIF").
dico("S", 6, "STATOR").
dico("S", 6, "STATUA").
dico("S", 6, "STATUE").
dico("S", 6, "STATUS").
dico("S", 6, "STATUT").
dico("S", 6, "STAWUG").
dico("S", 6, "STAYER").
dico("S", 6, "STEAKS").
dico("S", 6, "STELES").
dico("S", 6, "STEMMS").
dico("S", 6, "STENOS").
dico("S", 6, "STENTS").
dico("S", 6, "STEPPE").
dico("S", 6, "STERAI").
dico("S", 6, "STERAS").
dico("S", 6, "STERAT").
dico("S", 6, "STEREE").
dico("S", 6, "STEREO").
dico("S", 6, "STERER").
dico("S", 6, "STERES").
dico("S", 6, "STEREZ").
dico("S", 6, "STERNE").
dico("S", 6, "STEROL").
dico("S", 6, "STHENE").
dico("S", 6, "STIBIE").
dico("S", 6, "STICKS").
dico("S", 6, "STIGMA").
dico("S", 6, "STILBS").
dico("S", 6, "STIPES").
dico("S", 6, "STIPLE").
dico("S", 6, "STOCKA").
dico("S", 6, "STOCKE").
dico("S", 6, "STOCKS").
dico("S", 6, "STOKER").
dico("S", 6, "STOKES").
dico("S", 6, "STOLON").
dico("S", 6, "STOMIE").
dico("S", 6, "STOPPA").
dico("S", 6, "STOPPE").
dico("S", 6, "STORAX").
dico("S", 6, "STORES").
dico("S", 6, "STOUPA").
dico("S", 6, "STOUTS").
dico("S", 6, "STRASS").
dico("S", 6, "STRATE").
dico("S", 6, "STRESS").
dico("S", 6, "STRIAI").
dico("S", 6, "STRIAS").
dico("S", 6, "STRIAT").
dico("S", 6, "STRICT").
dico("S", 6, "STRIEE").
dico("S", 6, "STRIER").
dico("S", 6, "STRIES").
dico("S", 6, "STRIEZ").
dico("S", 6, "STRIGE").
dico("S", 6, "STRIKE").
dico("S", 6, "STRING").
dico("S", 6, "STRIPS").
dico("S", 6, "STROMA").
dico("S", 6, "STRUME").
dico("S", 6, "STRYGE").
dico("S", 6, "STUDIO").
dico("S", 6, "STUKAS").
dico("S", 6, "STUPAS").
dico("S", 6, "STUPRE").
dico("S", 6, "STUQUA").
dico("S", 6, "STUQUE").
dico("S", 6, "STYLAI").
dico("S", 6, "STYLAS").
dico("S", 6, "STYLAT").
dico("S", 6, "STYLEE").
dico("S", 6, "STYLER").
dico("S", 6, "STYLES").
dico("S", 6, "STYLET").
dico("S", 6, "STYLEZ").
dico("S", 6, "STYLOS").
dico("S", 6, "STYRAX").
dico("S", 6, "SUAGES").
dico("S", 6, "SUAIRE").
dico("S", 6, "SUAMES").
dico("S", 6, "SUANTE").
dico("S", 6, "SUANTS").
dico("S", 6, "SUASSE").
dico("S", 6, "SUATES").
dico("S", 6, "SUAVES").
dico("S", 6, "SUBERS").
dico("S", 6, "SUBIES").
dico("S", 6, "SUBIRA").
dico("S", 6, "SUBITE").
dico("S", 6, "SUBITO").
dico("S", 6, "SUBITS").
dico("S", 6, "SUBLAI").
dico("S", 6, "SUBLAS").
dico("S", 6, "SUBLAT").
dico("S", 6, "SUBLEE").
dico("S", 6, "SUBLER").
dico("S", 6, "SUBLES").
dico("S", 6, "SUBLEZ").
dico("S", 6, "SUBTIL").
dico("S", 6, "SUBULE").
dico("S", 6, "SUCAIS").
dico("S", 6, "SUCAIT").
dico("S", 6, "SUCANT").
dico("S", 6, "SUCCES").
dico("S", 6, "SUCCIN").
dico("S", 6, "SUCEES").
dico("S", 6, "SUCENT").
dico("S", 6, "SUCERA").
dico("S", 6, "SUCEUR").
dico("S", 6, "SUCIEZ").
dico("S", 6, "SUCOIR").
dico("S", 6, "SUCONS").
dico("S", 6, "SUCOTA").
dico("S", 6, "SUCOTE").
dico("S", 6, "SUCRAI").
dico("S", 6, "SUCRAS").
dico("S", 6, "SUCRAT").
dico("S", 6, "SUCREE").
dico("S", 6, "SUCRER").
dico("S", 6, "SUCRES").
dico("S", 6, "SUCREZ").
dico("S", 6, "SUCRIN").
dico("S", 6, "SUDETE").
dico("S", 6, "SUDRAS").
dico("S", 6, "SUEDEE").
dico("S", 6, "SUEDES").
dico("S", 6, "SUERAI").
dico("S", 6, "SUERAS").
dico("S", 6, "SUEREZ").
dico("S", 6, "SUETTE").
dico("S", 6, "SUEURS").
dico("S", 6, "SUFFIS").
dico("S", 6, "SUFFIT").
dico("S", 6, "SUIDES").
dico("S", 6, "SUIFAI").
dico("S", 6, "SUIFAS").
dico("S", 6, "SUIFAT").
dico("S", 6, "SUIFEE").
dico("S", 6, "SUIFER").
dico("S", 6, "SUIFES").
dico("S", 6, "SUIFEZ").
dico("S", 6, "SUIFFA").
dico("S", 6, "SUIFFE").
dico("S", 6, "SUINTA").
dico("S", 6, "SUINTE").
dico("S", 6, "SUINTS").
dico("S", 6, "SUIONS").
dico("S", 6, "SUISSE").
dico("S", 6, "SUITEE").
dico("S", 6, "SUITES").
dico("S", 6, "SUIVES").
dico("S", 6, "SUIVEZ").
dico("S", 6, "SUIVIE").
dico("S", 6, "SUIVIS").
dico("S", 6, "SUIVIT").
dico("S", 6, "SUIVRA").
dico("S", 6, "SUIVRE").
dico("S", 6, "SUJETS").
dico("S", 6, "SULKYS").
dico("S", 6, "SULTAN").
dico("S", 6, "SUMACS").
dico("S", 6, "SUMMUM").
dico("S", 6, "SUNDAE").
dico("S", 6, "SUNNAS").
dico("S", 6, "SUPAIS").
dico("S", 6, "SUPAIT").
dico("S", 6, "SUPANT").
dico("S", 6, "SUPEES").
dico("S", 6, "SUPENT").
dico("S", 6, "SUPERA").
dico("S", 6, "SUPERE").
dico("S", 6, "SUPERS").
dico("S", 6, "SUPIEZ").
dico("S", 6, "SUPINS").
dico("S", 6, "SUPION").
dico("S", 6, "SUPONS").
dico("S", 6, "SUPPOS").
dico("S", 6, "SUPPOT").
dico("S", 6, "SURAHS").
dico("S", 6, "SURALE").
dico("S", 6, "SURATE").
dico("S", 6, "SURAUX").
dico("S", 6, "SURBAU").
dico("S", 6, "SURCOT").
dico("S", 6, "SURDOS").
dico("S", 6, "SUREAU").
dico("S", 6, "SURENT").
dico("S", 6, "SURETE").
dico("S", 6, "SURETS").
dico("S", 6, "SURFAI").
dico("S", 6, "SURFAS").
dico("S", 6, "SURFAT").
dico("S", 6, "SURFER").
dico("S", 6, "SURFES").
dico("S", 6, "SURFEZ").
dico("S", 6, "SURFIL").
dico("S", 6, "SURFIN").
dico("S", 6, "SURFIS").
dico("S", 6, "SURFIT").
dico("S", 6, "SURGES").
dico("S", 6, "SURGIE").
dico("S", 6, "SURGIR").
dico("S", 6, "SURGIS").
dico("S", 6, "SURGIT").
dico("S", 6, "SURIES").
dico("S", 6, "SURIMI").
dico("S", 6, "SURINA").
dico("S", 6, "SURINE").
dico("S", 6, "SURINS").
dico("S", 6, "SURIRA").
dico("S", 6, "SURJET").
dico("S", 6, "SURLIA").
dico("S", 6, "SURLIE").
dico("S", 6, "SURMOI").
dico("S", 6, "SURNOM").
dico("S", 6, "SUROIT").
dico("S", 6, "SURSIS").
dico("S", 6, "SURSIT").
dico("S", 6, "SURVET").
dico("S", 6, "SURVIE").
dico("S", 6, "SURVIS").
dico("S", 6, "SURVIT").
dico("S", 6, "SURVOL").
dico("S", 6, "SUSDIT").
dico("S", 6, "SUSHIS").
dico("S", 6, "SUSSES").
dico("S", 6, "SUTRAS").
dico("S", 6, "SUTURA").
dico("S", 6, "SUTURE").
dico("S", 6, "SVELTE").
dico("S", 6, "SWAPPA").
dico("S", 6, "SWAPPE").
dico("S", 6, "SWAZIE").
dico("S", 6, "SWAZIS").
dico("S", 6, "SWEATS").
dico("S", 6, "SWINGS").
dico("S", 6, "SWITCH").
dico("S", 6, "SYCONE").
dico("S", 6, "SYLPHE").
dico("S", 6, "SYLVES").
dico("S", 6, "SYLVIE").
dico("S", 6, "SYMPAS").
dico("S", 6, "SYNASE").
dico("S", 6, "SYNDIC").
dico("S", 6, "SYNODE").
dico("S", 6, "SYNTHE").
dico("S", 6, "SYRAHS").
dico("S", 6, "SYRIEN").
dico("S", 6, "SYRINX").
dico("S", 6, "SYRPHE").
dico("S", 6, "SYRTES").
