dico("S", 7, "SAANENS").
dico("S", 7, "SABAYON").
dico("S", 7, "SABBATS").
dico("S", 7, "SABEENS").
dico("S", 7, "SABELLE").
dico("S", 7, "SABINES").
dico("S", 7, "SABLAGE").
dico("S", 7, "SABLAIS").
dico("S", 7, "SABLAIT").
dico("S", 7, "SABLANT").
dico("S", 7, "SABLEES").
dico("S", 7, "SABLENT").
dico("S", 7, "SABLERA").
dico("S", 7, "SABLEUR").
dico("S", 7, "SABLEUX").
dico("S", 7, "SABLIER").
dico("S", 7, "SABLIEZ").
dico("S", 7, "SABLONS").
dico("S", 7, "SABORDA").
dico("S", 7, "SABORDE").
dico("S", 7, "SABORDS").
dico("S", 7, "SABOTAI").
dico("S", 7, "SABOTAS").
dico("S", 7, "SABOTAT").
dico("S", 7, "SABOTEE").
dico("S", 7, "SABOTER").
dico("S", 7, "SABOTES").
dico("S", 7, "SABOTEZ").
dico("S", 7, "SABOULA").
dico("S", 7, "SABOULE").
dico("S", 7, "SABRAGE").
dico("S", 7, "SABRAIS").
dico("S", 7, "SABRAIT").
dico("S", 7, "SABRANT").
dico("S", 7, "SABREES").
dico("S", 7, "SABRENT").
dico("S", 7, "SABRERA").
dico("S", 7, "SABREUR").
dico("S", 7, "SABRIEZ").
dico("S", 7, "SABRONS").
dico("S", 7, "SABURRE").
dico("S", 7, "SACCADA").
dico("S", 7, "SACCADE").
dico("S", 7, "SACCAGE").
dico("S", 7, "SACCULE").
dico("S", 7, "SACHANT").
dico("S", 7, "SACHEES").
dico("S", 7, "SACHEMS").
dico("S", 7, "SACHENT").
dico("S", 7, "SACHETS").
dico("S", 7, "SACHIEZ").
dico("S", 7, "SACHONS").
dico("S", 7, "SACOCHE").
dico("S", 7, "SACOMES").
dico("S", 7, "SACQUAI").
dico("S", 7, "SACQUAS").
dico("S", 7, "SACQUAT").
dico("S", 7, "SACQUEE").
dico("S", 7, "SACQUER").
dico("S", 7, "SACQUES").
dico("S", 7, "SACQUEZ").
dico("S", 7, "SACRAIS").
dico("S", 7, "SACRAIT").
dico("S", 7, "SACRALE").
dico("S", 7, "SACRANT").
dico("S", 7, "SACRAUX").
dico("S", 7, "SACREES").
dico("S", 7, "SACRENT").
dico("S", 7, "SACRERA").
dico("S", 7, "SACRETS").
dico("S", 7, "SACRIEZ").
dico("S", 7, "SACRONS").
dico("S", 7, "SACRUMS").
dico("S", 7, "SADIQUE").
dico("S", 7, "SADISME").
dico("S", 7, "SAFARIS").
dico("S", 7, "SAFRANA").
dico("S", 7, "SAFRANE").
dico("S", 7, "SAFRANS").
dico("S", 7, "SAGACES").
dico("S", 7, "SAGAIES").
dico("S", 7, "SAGARDS").
dico("S", 7, "SAGESSE").
dico("S", 7, "SAGETTE").
dico("S", 7, "SAGINAS").
dico("S", 7, "SAGINES").
dico("S", 7, "SAGITTE").
dico("S", 7, "SAGOUIN").
dico("S", 7, "SAIETTA").
dico("S", 7, "SAIETTE").
dico("S", 7, "SAIGNAI").
dico("S", 7, "SAIGNAS").
dico("S", 7, "SAIGNAT").
dico("S", 7, "SAIGNEE").
dico("S", 7, "SAIGNER").
dico("S", 7, "SAIGNES").
dico("S", 7, "SAIGNEZ").
dico("S", 7, "SAILLIE").
dico("S", 7, "SAILLIR").
dico("S", 7, "SAILLIS").
dico("S", 7, "SAILLIT").
dico("S", 7, "SAIMIRI").
dico("S", 7, "SAINTES").
dico("S", 7, "SAISIES").
dico("S", 7, "SAISINE").
dico("S", 7, "SAISIRA").
dico("S", 7, "SAISONS").
dico("S", 7, "SAKIEHS").
dico("S", 7, "SALACES").
dico("S", 7, "SALADES").
dico("S", 7, "SALAGES").
dico("S", 7, "SALAIRE").
dico("S", 7, "SALAMES").
dico("S", 7, "SALAMIS").
dico("S", 7, "SALANTS").
dico("S", 7, "SALARIA").
dico("S", 7, "SALARIE").
dico("S", 7, "SALASSE").
dico("S", 7, "SALATES").
dico("S", 7, "SALAUDE").
dico("S", 7, "SALAUDS").
dico("S", 7, "SALCHOW").
dico("S", 7, "SALERAI").
dico("S", 7, "SALERAS").
dico("S", 7, "SALEREZ").
dico("S", 7, "SALERON").
dico("S", 7, "SALETES").
dico("S", 7, "SALEURS").
dico("S", 7, "SALEUSE").
dico("S", 7, "SALIENS").
dico("S", 7, "SALIERE").
dico("S", 7, "SALIFIA").
dico("S", 7, "SALIFIE").
dico("S", 7, "SALIMES").
dico("S", 7, "SALINES").
dico("S", 7, "SALIONS").
dico("S", 7, "SALIQUE").
dico("S", 7, "SALIRAI").
dico("S", 7, "SALIRAS").
dico("S", 7, "SALIREZ").
dico("S", 7, "SALISSE").
dico("S", 7, "SALITES").
dico("S", 7, "SALIVAI").
dico("S", 7, "SALIVAS").
dico("S", 7, "SALIVAT").
dico("S", 7, "SALIVER").
dico("S", 7, "SALIVES").
dico("S", 7, "SALIVEZ").
dico("S", 7, "SALOIRS").
dico("S", 7, "SALOMES").
dico("S", 7, "SALOONS").
dico("S", 7, "SALOPAI").
dico("S", 7, "SALOPAS").
dico("S", 7, "SALOPAT").
dico("S", 7, "SALOPEE").
dico("S", 7, "SALOPER").
dico("S", 7, "SALOPES").
dico("S", 7, "SALOPEZ").
dico("S", 7, "SALUAIS").
dico("S", 7, "SALUAIT").
dico("S", 7, "SALUANT").
dico("S", 7, "SALUBRE").
dico("S", 7, "SALUEES").
dico("S", 7, "SALUENT").
dico("S", 7, "SALUERA").
dico("S", 7, "SALUIEZ").
dico("S", 7, "SALUONS").
dico("S", 7, "SALURES").
dico("S", 7, "SAMARAS").
dico("S", 7, "SAMARES").
dico("S", 7, "SAMBUCA").
dico("S", 7, "SAMEDIS").
dico("S", 7, "SAMIENS").
dico("S", 7, "SAMMIES").
dico("S", 7, "SAMNITE").
dico("S", 7, "SAMOANE").
dico("S", 7, "SAMOANS").
dico("S", 7, "SAMOLES").
dico("S", 7, "SAMOVAR").
dico("S", 7, "SAMPANG").
dico("S", 7, "SAMPANS").
dico("S", 7, "SAMPLAI").
dico("S", 7, "SAMPLAS").
dico("S", 7, "SAMPLAT").
dico("S", 7, "SAMPLEE").
dico("S", 7, "SAMPLER").
dico("S", 7, "SAMPLES").
dico("S", 7, "SAMPLEZ").
dico("S", 7, "SAMPOTS").
dico("S", 7, "SAMURAI").
dico("S", 7, "SANCTUS").
dico("S", 7, "SANDALE").
dico("S", 7, "SANDJAK").
dico("S", 7, "SANDOWS").
dico("S", 7, "SANDRES").
dico("S", 7, "SANGLAI").
dico("S", 7, "SANGLAS").
dico("S", 7, "SANGLAT").
dico("S", 7, "SANGLEE").
dico("S", 7, "SANGLER").
dico("S", 7, "SANGLES").
dico("S", 7, "SANGLEZ").
dico("S", 7, "SANGLON").
dico("S", 7, "SANGLOT").
dico("S", 7, "SANGRIA").
dico("S", 7, "SANGSUE").
dico("S", 7, "SANGUIN").
dico("S", 7, "SANICLE").
dico("S", 7, "SANIEUX").
dico("S", 7, "SANTALS").
dico("S", 7, "SANTAUX").
dico("S", 7, "SANTIAG").
dico("S", 7, "SANTONE").
dico("S", 7, "SANTONS").
dico("S", 7, "SAOULAI").
dico("S", 7, "SAOULAS").
dico("S", 7, "SAOULAT").
dico("S", 7, "SAOULEE").
dico("S", 7, "SAOULER").
dico("S", 7, "SAOULES").
dico("S", 7, "SAOULEZ").
dico("S", 7, "SAPAJOU").
dico("S", 7, "SAPAMES").
dico("S", 7, "SAPASSE").
dico("S", 7, "SAPATES").
dico("S", 7, "SAPELLI").
dico("S", 7, "SAPEQUE").
dico("S", 7, "SAPERAI").
dico("S", 7, "SAPERAS").
dico("S", 7, "SAPERDE").
dico("S", 7, "SAPEREZ").
dico("S", 7, "SAPEURS").
dico("S", 7, "SAPHENE").
dico("S", 7, "SAPHIRS").
dico("S", 7, "SAPIDES").
dico("S", 7, "SAPINES").
dico("S", 7, "SAPIONS").
dico("S", 7, "SAPONES").
dico("S", 7, "SAPOTES").
dico("S", 7, "SAPPANS").
dico("S", 7, "SAQUAIS").
dico("S", 7, "SAQUAIT").
dico("S", 7, "SAQUANT").
dico("S", 7, "SAQUEES").
dico("S", 7, "SAQUENT").
dico("S", 7, "SAQUERA").
dico("S", 7, "SAQUIEZ").
dico("S", 7, "SAQUONS").
dico("S", 7, "SARCINE").
dico("S", 7, "SARCLAI").
dico("S", 7, "SARCLAS").
dico("S", 7, "SARCLAT").
dico("S", 7, "SARCLEE").
dico("S", 7, "SARCLER").
dico("S", 7, "SARCLES").
dico("S", 7, "SARCLEZ").
dico("S", 7, "SARCOME").
dico("S", 7, "SARDANE").
dico("S", 7, "SARDINE").
dico("S", 7, "SARGUES").
dico("S", 7, "SARIGUE").
dico("S", 7, "SARISSE").
dico("S", 7, "SARMENT").
dico("S", 7, "SARODES").
dico("S", 7, "SARONGS").
dico("S", 7, "SAROUAL").
dico("S", 7, "SAROUEL").
dico("S", 7, "SARRAUS").
dico("S", 7, "SARRETE").
dico("S", 7, "SARROIS").
dico("S", 7, "SASHIMI").
dico("S", 7, "SASSAGE").
dico("S", 7, "SASSAIS").
dico("S", 7, "SASSAIT").
dico("S", 7, "SASSANT").
dico("S", 7, "SASSEES").
dico("S", 7, "SASSENT").
dico("S", 7, "SASSERA").
dico("S", 7, "SASSEUR").
dico("S", 7, "SASSIEZ").
dico("S", 7, "SASSONS").
dico("S", 7, "SATANEE").
dico("S", 7, "SATANES").
dico("S", 7, "SATIETE").
dico("S", 7, "SATINAI").
dico("S", 7, "SATINAS").
dico("S", 7, "SATINAT").
dico("S", 7, "SATINEE").
dico("S", 7, "SATINER").
dico("S", 7, "SATINES").
dico("S", 7, "SATINEZ").
dico("S", 7, "SATIRES").
dico("S", 7, "SATORIS").
dico("S", 7, "SATRAPE").
dico("S", 7, "SATURAI").
dico("S", 7, "SATURAS").
dico("S", 7, "SATURAT").
dico("S", 7, "SATUREE").
dico("S", 7, "SATURER").
dico("S", 7, "SATURES").
dico("S", 7, "SATUREZ").
dico("S", 7, "SATURNE").
dico("S", 7, "SATYRES").
dico("S", 7, "SAUCAIS").
dico("S", 7, "SAUCAIT").
dico("S", 7, "SAUCANT").
dico("S", 7, "SAUCEES").
dico("S", 7, "SAUCENT").
dico("S", 7, "SAUCERA").
dico("S", 7, "SAUCIER").
dico("S", 7, "SAUCIEZ").
dico("S", 7, "SAUCONS").
dico("S", 7, "SAULAIE").
dico("S", 7, "SAULEES").
dico("S", 7, "SAUMONE").
dico("S", 7, "SAUMONS").
dico("S", 7, "SAUMURA").
dico("S", 7, "SAUMURE").
dico("S", 7, "SAUMURS").
dico("S", 7, "SAUNAGE").
dico("S", 7, "SAUNAIS").
dico("S", 7, "SAUNAIT").
dico("S", 7, "SAUNANT").
dico("S", 7, "SAUNENT").
dico("S", 7, "SAUNERA").
dico("S", 7, "SAUNIER").
dico("S", 7, "SAUNIEZ").
dico("S", 7, "SAUNONS").
dico("S", 7, "SAURAGE").
dico("S", 7, "SAURAIS").
dico("S", 7, "SAURAIT").
dico("S", 7, "SAURANT").
dico("S", 7, "SAUREES").
dico("S", 7, "SAURELS").
dico("S", 7, "SAURENT").
dico("S", 7, "SAURERA").
dico("S", 7, "SAURETS").
dico("S", 7, "SAURIEN").
dico("S", 7, "SAURIES").
dico("S", 7, "SAURIEZ").
dico("S", 7, "SAURINS").
dico("S", 7, "SAURIRA").
dico("S", 7, "SAURONS").
dico("S", 7, "SAURONT").
dico("S", 7, "SAUTAGE").
dico("S", 7, "SAUTAIS").
dico("S", 7, "SAUTAIT").
dico("S", 7, "SAUTANT").
dico("S", 7, "SAUTEES").
dico("S", 7, "SAUTENT").
dico("S", 7, "SAUTERA").
dico("S", 7, "SAUTEUR").
dico("S", 7, "SAUTIER").
dico("S", 7, "SAUTIEZ").
dico("S", 7, "SAUTOIR").
dico("S", 7, "SAUTONS").
dico("S", 7, "SAUVAGE").
dico("S", 7, "SAUVAIS").
dico("S", 7, "SAUVAIT").
dico("S", 7, "SAUVANT").
dico("S", 7, "SAUVEES").
dico("S", 7, "SAUVENT").
dico("S", 7, "SAUVERA").
dico("S", 7, "SAUVETE").
dico("S", 7, "SAUVEUR").
dico("S", 7, "SAUVIEZ").
dico("S", 7, "SAUVONS").
dico("S", 7, "SAVANES").
dico("S", 7, "SAVANTE").
dico("S", 7, "SAVANTS").
dico("S", 7, "SAVARIN").
dico("S", 7, "SAVARTS").
dico("S", 7, "SAVATES").
dico("S", 7, "SAVEURS").
dico("S", 7, "SAVIONS").
dico("S", 7, "SAVOIRS").
dico("S", 7, "SAVONNA").
dico("S", 7, "SAVONNE").
dico("S", 7, "SAVOURA").
dico("S", 7, "SAVOURE").
dico("S", 7, "SAXHORN").
dico("S", 7, "SAXONNE").
dico("S", 7, "SAYNETE").
dico("S", 7, "SCALANT").
dico("S", 7, "SCALDES").
dico("S", 7, "SCALENE").
dico("S", 7, "SCALPAI").
dico("S", 7, "SCALPAS").
dico("S", 7, "SCALPAT").
dico("S", 7, "SCALPEE").
dico("S", 7, "SCALPEL").
dico("S", 7, "SCALPER").
dico("S", 7, "SCALPES").
dico("S", 7, "SCALPEZ").
dico("S", 7, "SCAMPIS").
dico("S", 7, "SCANDAI").
dico("S", 7, "SCANDAS").
dico("S", 7, "SCANDAT").
dico("S", 7, "SCANDEE").
dico("S", 7, "SCANDER").
dico("S", 7, "SCANDES").
dico("S", 7, "SCANDEZ").
dico("S", 7, "SCANDIX").
dico("S", 7, "SCANNAI").
dico("S", 7, "SCANNAS").
dico("S", 7, "SCANNAT").
dico("S", 7, "SCANNEE").
dico("S", 7, "SCANNER").
dico("S", 7, "SCANNES").
dico("S", 7, "SCANNEZ").
dico("S", 7, "SCAPULA").
dico("S", 7, "SCAROLE").
dico("S", 7, "SCATOLE").
dico("S", 7, "SCATOLS").
dico("S", 7, "SCELLAI").
dico("S", 7, "SCELLAS").
dico("S", 7, "SCELLAT").
dico("S", 7, "SCELLEE").
dico("S", 7, "SCELLER").
dico("S", 7, "SCELLES").
dico("S", 7, "SCELLEZ").
dico("S", 7, "SCEPTRE").
dico("S", 7, "SCHADAI").
dico("S", 7, "SCHADAS").
dico("S", 7, "SCHADAT").
dico("S", 7, "SCHADER").
dico("S", 7, "SCHADES").
dico("S", 7, "SCHADEZ").
dico("S", 7, "SCHAKOS").
dico("S", 7, "SCHAPPE").
dico("S", 7, "SCHEIDA").
dico("S", 7, "SCHEIDE").
dico("S", 7, "SCHEIKS").
dico("S", 7, "SCHELEM").
dico("S", 7, "SCHEMAS").
dico("S", 7, "SCHEMES").
dico("S", 7, "SCHEOLS").
dico("S", 7, "SCHERZO").
dico("S", 7, "SCHINDA").
dico("S", 7, "SCHINDE").
dico("S", 7, "SCHISME").
dico("S", 7, "SCHISTE").
dico("S", 7, "SCHIZOS").
dico("S", 7, "SCHLAMM").
dico("S", 7, "SCHLASS").
dico("S", 7, "SCHLEMS").
dico("S", 7, "SCHLEUE").
dico("S", 7, "SCHLEUS").
dico("S", 7, "SCHLICH").
dico("S", 7, "SCHNAPS").
dico("S", 7, "SCHNICK").
dico("S", 7, "SCHNOCK").
dico("S", 7, "SCHNOUF").
dico("S", 7, "SCHOFAR").
dico("S", 7, "SCHOLIE").
dico("S", 7, "SCHORRE").
dico("S", 7, "SCHUPOS").
dico("S", 7, "SCIABLE").
dico("S", 7, "SCIAGES").
dico("S", 7, "SCIAMES").
dico("S", 7, "SCIANTE").
dico("S", 7, "SCIANTS").
dico("S", 7, "SCIASSE").
dico("S", 7, "SCIATES").
dico("S", 7, "SCIENCE").
dico("S", 7, "SCIENES").
dico("S", 7, "SCIERAI").
dico("S", 7, "SCIERAS").
dico("S", 7, "SCIEREZ").
dico("S", 7, "SCIERIE").
dico("S", 7, "SCIEURS").
dico("S", 7, "SCIEUSE").
dico("S", 7, "SCIIONS").
dico("S", 7, "SCILLES").
dico("S", 7, "SCINDAI").
dico("S", 7, "SCINDAS").
dico("S", 7, "SCINDAT").
dico("S", 7, "SCINDEE").
dico("S", 7, "SCINDER").
dico("S", 7, "SCINDES").
dico("S", 7, "SCINDEZ").
dico("S", 7, "SCINQUE").
dico("S", 7, "SCIOTTE").
dico("S", 7, "SCIRPES").
dico("S", 7, "SCIURES").
dico("S", 7, "SCLERAL").
dico("S", 7, "SCLERES").
dico("S", 7, "SCOLIES").
dico("S", 7, "SCOLYTE").
dico("S", 7, "SCONSES").
dico("S", 7, "SCOOTER").
dico("S", 7, "SCOPIES").
dico("S", 7, "SCORAIS").
dico("S", 7, "SCORAIT").
dico("S", 7, "SCORANT").
dico("S", 7, "SCORBUT").
dico("S", 7, "SCOREES").
dico("S", 7, "SCORENT").
dico("S", 7, "SCORERA").
dico("S", 7, "SCORIES").
dico("S", 7, "SCORIEZ").
dico("S", 7, "SCORONS").
dico("S", 7, "SCOTCHA").
dico("S", 7, "SCOTCHE").
dico("S", 7, "SCOTCHS").
dico("S", 7, "SCOTIES").
dico("S", 7, "SCOTOME").
dico("S", 7, "SCOURED").
dico("S", 7, "SCOUTES").
dico("S", 7, "SCRAPER").
dico("S", 7, "SCRAPIE").
dico("S", 7, "SCRATCH").
dico("S", 7, "SCRIBAN").
dico("S", 7, "SCRIBES").
dico("S", 7, "SCRIPTE").
dico("S", 7, "SCRIPTS").
dico("S", 7, "SCROTAL").
dico("S", 7, "SCROTUM").
dico("S", 7, "SCRUTAI").
dico("S", 7, "SCRUTAS").
dico("S", 7, "SCRUTAT").
dico("S", 7, "SCRUTEE").
dico("S", 7, "SCRUTER").
dico("S", 7, "SCRUTES").
dico("S", 7, "SCRUTEZ").
dico("S", 7, "SCRUTIN").
dico("S", 7, "SCULPTA").
dico("S", 7, "SCULPTE").
dico("S", 7, "SCUTUMS").
dico("S", 7, "SCYTHES").
dico("S", 7, "SEANCES").
dico("S", 7, "SEANTES").
dico("S", 7, "SEBACEE").
dico("S", 7, "SEBACES").
dico("S", 7, "SEBASTE").
dico("S", 7, "SEBILES").
dico("S", 7, "SEBKHAS").
dico("S", 7, "SEBKRAS").
dico("S", 7, "SECABLE").
dico("S", 7, "SECANTE").
dico("S", 7, "SECANTS").
dico("S", 7, "SECHAGE").
dico("S", 7, "SECHAIS").
dico("S", 7, "SECHAIT").
dico("S", 7, "SECHANT").
dico("S", 7, "SECHEES").
dico("S", 7, "SECHENT").
dico("S", 7, "SECHERA").
dico("S", 7, "SECHEUR").
dico("S", 7, "SECHIEZ").
dico("S", 7, "SECHOIR").
dico("S", 7, "SECHONS").
dico("S", 7, "SECONDA").
dico("S", 7, "SECONDE").
dico("S", 7, "SECONDS").
dico("S", 7, "SECOUAI").
dico("S", 7, "SECOUAS").
dico("S", 7, "SECOUAT").
dico("S", 7, "SECOUEE").
dico("S", 7, "SECOUER").
dico("S", 7, "SECOUES").
dico("S", 7, "SECOUEZ").
dico("S", 7, "SECOURE").
dico("S", 7, "SECOURS").
dico("S", 7, "SECOURT").
dico("S", 7, "SECOURU").
dico("S", 7, "SECRETA").
dico("S", 7, "SECRETE").
dico("S", 7, "SECRETS").
dico("S", 7, "SECTEUR").
dico("S", 7, "SECTION").
dico("S", 7, "SECUNDO").
dico("S", 7, "SECURIT").
dico("S", 7, "SEDATIF").
dico("S", 7, "SEDUIRA").
dico("S", 7, "SEDUIRE").
dico("S", 7, "SEDUISE").
dico("S", 7, "SEDUITE").
dico("S", 7, "SEDUITS").
dico("S", 7, "SEFARDI").
dico("S", 7, "SEGALAS").
dico("S", 7, "SEGHIAS").
dico("S", 7, "SEGMENT").
dico("S", 7, "SEGRAIS").
dico("S", 7, "SEGREGE").
dico("S", 7, "SEGUIAS").
dico("S", 7, "SEHTARS").
dico("S", 7, "SEICHES").
dico("S", 7, "SEIGLES").
dico("S", 7, "SEILLES").
dico("S", 7, "SEILLON").
dico("S", 7, "SEISMAL").
dico("S", 7, "SEISMES").
dico("S", 7, "SEIZAIN").
dico("S", 7, "SEJOURS").
dico("S", 7, "SELECTA").
dico("S", 7, "SELECTE").
dico("S", 7, "SELECTS").
dico("S", 7, "SELENES").
dico("S", 7, "SELENIE").
dico("S", 7, "SELLAGE").
dico("S", 7, "SELLAIS").
dico("S", 7, "SELLAIT").
dico("S", 7, "SELLANT").
dico("S", 7, "SELLEES").
dico("S", 7, "SELLENT").
dico("S", 7, "SELLERA").
dico("S", 7, "SELLIER").
dico("S", 7, "SELLIEZ").
dico("S", 7, "SELLONS").
dico("S", 7, "SEMAINE").
dico("S", 7, "SEMAMES").
dico("S", 7, "SEMASSE").
dico("S", 7, "SEMATES").
dico("S", 7, "SEMBLAI").
dico("S", 7, "SEMBLAS").
dico("S", 7, "SEMBLAT").
dico("S", 7, "SEMBLER").
dico("S", 7, "SEMBLES").
dico("S", 7, "SEMBLEZ").
dico("S", 7, "SEMELLE").
dico("S", 7, "SEMEMES").
dico("S", 7, "SEMENCE").
dico("S", 7, "SEMERAI").
dico("S", 7, "SEMERAS").
dico("S", 7, "SEMEREZ").
dico("S", 7, "SEMEURS").
dico("S", 7, "SEMEUSE").
dico("S", 7, "SEMINAL").
dico("S", 7, "SEMIONS").
dico("S", 7, "SEMIQUE").
dico("S", 7, "SEMITES").
dico("S", 7, "SEMOIRS").
dico("S", 7, "SEMONCA").
dico("S", 7, "SEMONCE").
dico("S", 7, "SEMOULE").
dico("S", 7, "SEMPLES").
dico("S", 7, "SENAIRE").
dico("S", 7, "SENECON").
dico("S", 7, "SENEVES").
dico("S", 7, "SENEVOL").
dico("S", 7, "SENILES").
dico("S", 7, "SENIORS").
dico("S", 7, "SENNEUR").
dico("S", 7, "SENSASS").
dico("S", 7, "SENSEES").
dico("S", 7, "SENSEUR").
dico("S", 7, "SENSUEL").
dico("S", 7, "SENTAIS").
dico("S", 7, "SENTAIT").
dico("S", 7, "SENTANT").
dico("S", 7, "SENTENT").
dico("S", 7, "SENTEUR").
dico("S", 7, "SENTIER").
dico("S", 7, "SENTIES").
dico("S", 7, "SENTIEZ").
dico("S", 7, "SENTINE").
dico("S", 7, "SENTIRA").
dico("S", 7, "SENTONS").
dico("S", 7, "SEPALES").
dico("S", 7, "SEPARAI").
dico("S", 7, "SEPARAS").
dico("S", 7, "SEPARAT").
dico("S", 7, "SEPAREE").
dico("S", 7, "SEPARER").
dico("S", 7, "SEPARES").
dico("S", 7, "SEPAREZ").
dico("S", 7, "SEPIOLE").
dico("S", 7, "SEPPUKU").
dico("S", 7, "SEPTAIN").
dico("S", 7, "SEPTALE").
dico("S", 7, "SEPTAUX").
dico("S", 7, "SEPTIDI").
dico("S", 7, "SEPTIME").
dico("S", 7, "SEPTIMO").
dico("S", 7, "SEPTUMS").
dico("S", 7, "SEPTUOR").
dico("S", 7, "SEQUINS").
dico("S", 7, "SEQUOIA").
dico("S", 7, "SERAILS").
dico("S", 7, "SERANCA").
dico("S", 7, "SERANCE").
dico("S", 7, "SERDABS").
dico("S", 7, "SERDEAU").
dico("S", 7, "SEREINE").
dico("S", 7, "SEREINS").
dico("S", 7, "SEREUSE").
dico("S", 7, "SERFOUI").
dico("S", 7, "SERGENT").
dico("S", 7, "SERIAIS").
dico("S", 7, "SERIAIT").
dico("S", 7, "SERIALS").
dico("S", 7, "SERIANT").
dico("S", 7, "SERIEES").
dico("S", 7, "SERIELS").
dico("S", 7, "SERIENT").
dico("S", 7, "SERIERA").
dico("S", 7, "SERIEUX").
dico("S", 7, "SERIIEZ").
dico("S", 7, "SERINAI").
dico("S", 7, "SERINAS").
dico("S", 7, "SERINAT").
dico("S", 7, "SERINEE").
dico("S", 7, "SERINER").
dico("S", 7, "SERINES").
dico("S", 7, "SERINEZ").
dico("S", 7, "SERINGA").
dico("S", 7, "SERIONS").
dico("S", 7, "SERIQUE").
dico("S", 7, "SERMENT").
dico("S", 7, "SERMONS").
dico("S", 7, "SERPENT").
dico("S", 7, "SERPULE").
dico("S", 7, "SERRAGE").
dico("S", 7, "SERRAIS").
dico("S", 7, "SERRAIT").
dico("S", 7, "SERRANS").
dico("S", 7, "SERRANT").
dico("S", 7, "SERRATE").
dico("S", 7, "SERRATI").
dico("S", 7, "SERREES").
dico("S", 7, "SERRENT").
dico("S", 7, "SERRERA").
dico("S", 7, "SERRIEZ").
dico("S", 7, "SERRONS").
dico("S", 7, "SERRURE").
dico("S", 7, "SERTAOS").
dico("S", 7, "SERTIES").
dico("S", 7, "SERTIRA").
dico("S", 7, "SERVAGE").
dico("S", 7, "SERVAIS").
dico("S", 7, "SERVAIT").
dico("S", 7, "SERVALS").
dico("S", 7, "SERVANT").
dico("S", 7, "SERVENT").
dico("S", 7, "SERVEUR").
dico("S", 7, "SERVICE").
dico("S", 7, "SERVIES").
dico("S", 7, "SERVIEZ").
dico("S", 7, "SERVILE").
dico("S", 7, "SERVIRA").
dico("S", 7, "SERVITE").
dico("S", 7, "SERVONS").
dico("S", 7, "SESAMES").
dico("S", 7, "SESSILE").
dico("S", 7, "SESSION").
dico("S", 7, "SETACEE").
dico("S", 7, "SETACES").
dico("S", 7, "SETEREE").
dico("S", 7, "SETIERS").
dico("S", 7, "SETOISE").
dico("S", 7, "SETTERS").
dico("S", 7, "SEULETS").
dico("S", 7, "SEVERES").
dico("S", 7, "SEVICES").
dico("S", 7, "SEVIMES").
dico("S", 7, "SEVIRAI").
dico("S", 7, "SEVIRAS").
dico("S", 7, "SEVIREZ").
dico("S", 7, "SEVISSE").
dico("S", 7, "SEVITES").
dico("S", 7, "SEVRAGE").
dico("S", 7, "SEVRAIS").
dico("S", 7, "SEVRAIT").
dico("S", 7, "SEVRANT").
dico("S", 7, "SEVREES").
dico("S", 7, "SEVRENT").
dico("S", 7, "SEVRERA").
dico("S", 7, "SEVRIEZ").
dico("S", 7, "SEVRONS").
dico("S", 7, "SEVRUGA").
dico("S", 7, "SEXAGES").
dico("S", 7, "SEXISME").
dico("S", 7, "SEXISTE").
dico("S", 7, "SEXTANT").
dico("S", 7, "SEXTIDI").
dico("S", 7, "SEXTINE").
dico("S", 7, "SEXTUOR").
dico("S", 7, "SEXUEES").
dico("S", 7, "SEXUELS").
dico("S", 7, "SEYANTE").
dico("S", 7, "SEYANTS").
dico("S", 7, "SEYVALS").
dico("S", 7, "SEZIGUE").
dico("S", 7, "SFAXIEN").
dico("S", 7, "SFUMATO").
dico("S", 7, "SHABBAT").
dico("S", 7, "SHABIEN").
dico("S", 7, "SHAHNAI").
dico("S", 7, "SHAKERS").
dico("S", 7, "SHAKTIS").
dico("S", 7, "SHARPEI").
dico("S", 7, "SHARPIE").
dico("S", 7, "SHAVING").
dico("S", 7, "SHEKELS").
dico("S", 7, "SHERIFS").
dico("S", 7, "SHERPAS").
dico("S", 7, "SHERRYS").
dico("S", 7, "SHIATSU").
dico("S", 7, "SHILOMS").
dico("S", 7, "SHIMMYS").
dico("S", 7, "SHINGLE").
dico("S", 7, "SHINTOS").
dico("S", 7, "SHOGOUN").
dico("S", 7, "SHOGUNS").
dico("S", 7, "SHOOTAI").
dico("S", 7, "SHOOTAS").
dico("S", 7, "SHOOTAT").
dico("S", 7, "SHOOTEE").
dico("S", 7, "SHOOTER").
dico("S", 7, "SHOOTES").
dico("S", 7, "SHOOTEZ").
dico("S", 7, "SHOWBIZ").
dico("S", 7, "SHTETLS").
dico("S", 7, "SHUDRAS").
dico("S", 7, "SHUNTAI").
dico("S", 7, "SHUNTAS").
dico("S", 7, "SHUNTAT").
dico("S", 7, "SHUNTEE").
dico("S", 7, "SHUNTER").
dico("S", 7, "SHUNTES").
dico("S", 7, "SHUNTEZ").
dico("S", 7, "SIAMANG").
dico("S", 7, "SIAMOIS").
dico("S", 7, "SIBYLLE").
dico("S", 7, "SICAIRE").
dico("S", 7, "SICCITE").
dico("S", 7, "SICLAIS").
dico("S", 7, "SICLAIT").
dico("S", 7, "SICLANT").
dico("S", 7, "SICLEES").
dico("S", 7, "SICLENT").
dico("S", 7, "SICLERA").
dico("S", 7, "SICLIEZ").
dico("S", 7, "SICLONS").
dico("S", 7, "SIDEENS").
dico("S", 7, "SIDERAI").
dico("S", 7, "SIDERAL").
dico("S", 7, "SIDERAS").
dico("S", 7, "SIDERAT").
dico("S", 7, "SIDEREE").
dico("S", 7, "SIDERER").
dico("S", 7, "SIDERES").
dico("S", 7, "SIDEREZ").
dico("S", 7, "SIECLES").
dico("S", 7, "SIEGEAI").
dico("S", 7, "SIEGEAS").
dico("S", 7, "SIEGEAT").
dico("S", 7, "SIEGENT").
dico("S", 7, "SIEGERA").
dico("S", 7, "SIEGIEZ").
dico("S", 7, "SIEMENS").
dico("S", 7, "SIENNES").
dico("S", 7, "SIERAIT").
dico("S", 7, "SIERONT").
dico("S", 7, "SIERRAS").
dico("S", 7, "SIESTAI").
dico("S", 7, "SIESTAS").
dico("S", 7, "SIESTAT").
dico("S", 7, "SIESTER").
dico("S", 7, "SIESTES").
dico("S", 7, "SIESTEZ").
dico("S", 7, "SIEVERT").
dico("S", 7, "SIFFLAI").
dico("S", 7, "SIFFLAS").
dico("S", 7, "SIFFLAT").
dico("S", 7, "SIFFLEE").
dico("S", 7, "SIFFLER").
dico("S", 7, "SIFFLES").
dico("S", 7, "SIFFLET").
dico("S", 7, "SIFFLEZ").
dico("S", 7, "SIFILET").
dico("S", 7, "SIGILLE").
dico("S", 7, "SIGLEES").
dico("S", 7, "SIGNAIS").
dico("S", 7, "SIGNAIT").
dico("S", 7, "SIGNALA").
dico("S", 7, "SIGNALE").
dico("S", 7, "SIGNANT").
dico("S", 7, "SIGNAUX").
dico("S", 7, "SIGNEES").
dico("S", 7, "SIGNENT").
dico("S", 7, "SIGNERA").
dico("S", 7, "SIGNETS").
dico("S", 7, "SIGNIEZ").
dico("S", 7, "SIGNONS").
dico("S", 7, "SIKHARA").
dico("S", 7, "SILAMES").
dico("S", 7, "SILANES").
dico("S", 7, "SILASSE").
dico("S", 7, "SILATES").
dico("S", 7, "SILENCE").
dico("S", 7, "SILENES").
dico("S", 7, "SILERAI").
dico("S", 7, "SILERAS").
dico("S", 7, "SILEREZ").
dico("S", 7, "SILICES").
dico("S", 7, "SILIONS").
dico("S", 7, "SILIQUE").
dico("S", 7, "SILLAGE").
dico("S", 7, "SILLETS").
dico("S", 7, "SILLONS").
dico("S", 7, "SILPHES").
dico("S", 7, "SILURES").
dico("S", 7, "SIMARRE").
dico("S", 7, "SIMIENS").
dico("S", 7, "SIMILIS").
dico("S", 7, "SIMILOR").
dico("S", 7, "SIMONIE").
dico("S", 7, "SIMOUNS").
dico("S", 7, "SIMPLES").
dico("S", 7, "SIMPLET").
dico("S", 7, "SIMPLEX").
dico("S", 7, "SIMULAI").
dico("S", 7, "SIMULAS").
dico("S", 7, "SIMULAT").
dico("S", 7, "SIMULEE").
dico("S", 7, "SIMULER").
dico("S", 7, "SIMULES").
dico("S", 7, "SIMULEZ").
dico("S", 7, "SIMULIE").
dico("S", 7, "SINAGOT").
dico("S", 7, "SINCERE").
dico("S", 7, "SINGEAI").
dico("S", 7, "SINGEAS").
dico("S", 7, "SINGEAT").
dico("S", 7, "SINGEES").
dico("S", 7, "SINGENT").
dico("S", 7, "SINGERA").
dico("S", 7, "SINGIEZ").
dico("S", 7, "SINGLES").
dico("S", 7, "SINGLET").
dico("S", 7, "SINISAI").
dico("S", 7, "SINISAS").
dico("S", 7, "SINISAT").
dico("S", 7, "SINISEE").
dico("S", 7, "SINISER").
dico("S", 7, "SINISES").
dico("S", 7, "SINISEZ").
dico("S", 7, "SINITES").
dico("S", 7, "SINOPLE").
dico("S", 7, "SINOQUE").
dico("S", 7, "SINTERS").
dico("S", 7, "SINUAIS").
dico("S", 7, "SINUAIT").
dico("S", 7, "SINUANT").
dico("S", 7, "SINUEES").
dico("S", 7, "SINUENT").
dico("S", 7, "SINUERA").
dico("S", 7, "SINUEUX").
dico("S", 7, "SINUIEZ").
dico("S", 7, "SINUONS").
dico("S", 7, "SINUSAL").
dico("S", 7, "SIPHONS").
dico("S", 7, "SIRDARS").
dico("S", 7, "SIRENES").
dico("S", 7, "SIROCCO").
dico("S", 7, "SIROCOS").
dico("S", 7, "SIROTAI").
dico("S", 7, "SIROTAS").
dico("S", 7, "SIROTAT").
dico("S", 7, "SIROTEE").
dico("S", 7, "SIROTER").
dico("S", 7, "SIROTES").
dico("S", 7, "SIROTEZ").
dico("S", 7, "SIRTAKI").
dico("S", 7, "SISMALE").
dico("S", 7, "SISMAUX").
dico("S", 7, "SISSONE").
dico("S", 7, "SISTRES").
dico("S", 7, "SITCOMS").
dico("S", 7, "SITTELE").
dico("S", 7, "SITTIDE").
dico("S", 7, "SITUAIS").
dico("S", 7, "SITUAIT").
dico("S", 7, "SITUANT").
dico("S", 7, "SITUEES").
dico("S", 7, "SITUENT").
dico("S", 7, "SITUERA").
dico("S", 7, "SITUIEZ").
dico("S", 7, "SITUONS").
dico("S", 7, "SIVAITE").
dico("S", 7, "SIXAINS").
dico("S", 7, "SIXIEME").
dico("S", 7, "SIXTIES").
dico("S", 7, "SIZAINE").
dico("S", 7, "SIZAINS").
dico("S", 7, "SIZERIN").
dico("S", 7, "SKATING").
dico("S", 7, "SKETCHS").
dico("S", 7, "SKIABLE").
dico("S", 7, "SKIAMES").
dico("S", 7, "SKIASSE").
dico("S", 7, "SKIATES").
dico("S", 7, "SKIERAI").
dico("S", 7, "SKIERAS").
dico("S", 7, "SKIEREZ").
dico("S", 7, "SKIEURS").
dico("S", 7, "SKIEUSE").
dico("S", 7, "SKIFEUR").
dico("S", 7, "SKIIONS").
dico("S", 7, "SKIPPAI").
dico("S", 7, "SKIPPAS").
dico("S", 7, "SKIPPAT").
dico("S", 7, "SKIPPEE").
dico("S", 7, "SKIPPER").
dico("S", 7, "SKIPPES").
dico("S", 7, "SKIPPEZ").
dico("S", 7, "SKYDOME").
dico("S", 7, "SLALOMA").
dico("S", 7, "SLALOME").
dico("S", 7, "SLALOMS").
dico("S", 7, "SLASHES").
dico("S", 7, "SLAVISA").
dico("S", 7, "SLAVISE").
dico("S", 7, "SLAVONS").
dico("S", 7, "SLICAIS").
dico("S", 7, "SLICAIT").
dico("S", 7, "SLICANT").
dico("S", 7, "SLICEES").
dico("S", 7, "SLICENT").
dico("S", 7, "SLICERA").
dico("S", 7, "SLICIEZ").
dico("S", 7, "SLICONS").
dico("S", 7, "SLIKKES").
dico("S", 7, "SLOCHES").
dico("S", 7, "SLOGANS").
dico("S", 7, "SLOUGHI").
dico("S", 7, "SLOVENE").
dico("S", 7, "SMALAHS").
dico("S", 7, "SMASHAI").
dico("S", 7, "SMASHAS").
dico("S", 7, "SMASHAT").
dico("S", 7, "SMASHEE").
dico("S", 7, "SMASHER").
dico("S", 7, "SMASHES").
dico("S", 7, "SMASHEZ").
dico("S", 7, "SMEGMAS").
dico("S", 7, "SMICARD").
dico("S", 7, "SMILEYS").
dico("S", 7, "SMILLAI").
dico("S", 7, "SMILLAS").
dico("S", 7, "SMILLAT").
dico("S", 7, "SMILLEE").
dico("S", 7, "SMILLER").
dico("S", 7, "SMILLES").
dico("S", 7, "SMILLEZ").
dico("S", 7, "SMOKING").
dico("S", 7, "SMURFAI").
dico("S", 7, "SMURFAS").
dico("S", 7, "SMURFAT").
dico("S", 7, "SMURFER").
dico("S", 7, "SMURFES").
dico("S", 7, "SMURFEZ").
dico("S", 7, "SNIFAIS").
dico("S", 7, "SNIFAIT").
dico("S", 7, "SNIFANT").
dico("S", 7, "SNIFEES").
dico("S", 7, "SNIFENT").
dico("S", 7, "SNIFERA").
dico("S", 7, "SNIFFAI").
dico("S", 7, "SNIFFAS").
dico("S", 7, "SNIFFAT").
dico("S", 7, "SNIFFEE").
dico("S", 7, "SNIFFER").
dico("S", 7, "SNIFFES").
dico("S", 7, "SNIFFEZ").
dico("S", 7, "SNIFIEZ").
dico("S", 7, "SNIFONS").
dico("S", 7, "SNIPERS").
dico("S", 7, "SNOBAIS").
dico("S", 7, "SNOBAIT").
dico("S", 7, "SNOBANT").
dico("S", 7, "SNOBEES").
dico("S", 7, "SNOBENT").
dico("S", 7, "SNOBERA").
dico("S", 7, "SNOBIEZ").
dico("S", 7, "SNOBONS").
dico("S", 7, "SNOOKER").
dico("S", 7, "SNOREAU").
dico("S", 7, "SOCCERS").
dico("S", 7, "SOCIALE").
dico("S", 7, "SOCIALO").
dico("S", 7, "SOCIAUX").
dico("S", 7, "SOCIETE").
dico("S", 7, "SOCKETS").
dico("S", 7, "SOCQUES").
dico("S", 7, "SOCQUET").
dico("S", 7, "SODABIS").
dico("S", 7, "SODIQUE").
dico("S", 7, "SODIUMS").
dico("S", 7, "SODOKUS").
dico("S", 7, "SODOMIE").
dico("S", 7, "SOFFITE").
dico("S", 7, "SOFIOTE").
dico("S", 7, "SOIERIE").
dico("S", 7, "SOIGNAI").
dico("S", 7, "SOIGNAS").
dico("S", 7, "SOIGNAT").
dico("S", 7, "SOIGNEE").
dico("S", 7, "SOIGNER").
dico("S", 7, "SOIGNES").
dico("S", 7, "SOIGNEZ").
dico("S", 7, "SOIREES").
dico("S", 7, "SOLAGES").
dico("S", 7, "SOLAIRE").
dico("S", 7, "SOLDAIS").
dico("S", 7, "SOLDAIT").
dico("S", 7, "SOLDANT").
dico("S", 7, "SOLDATE").
dico("S", 7, "SOLDATS").
dico("S", 7, "SOLDEES").
dico("S", 7, "SOLDENT").
dico("S", 7, "SOLDERA").
dico("S", 7, "SOLDEUR").
dico("S", 7, "SOLDIEZ").
dico("S", 7, "SOLDONS").
dico("S", 7, "SOLEILS").
dico("S", 7, "SOLERET").
dico("S", 7, "SOLETTE").
dico("S", 7, "SOLFEGE").
dico("S", 7, "SOLFIAI").
dico("S", 7, "SOLFIAS").
dico("S", 7, "SOLFIAT").
dico("S", 7, "SOLFIEE").
dico("S", 7, "SOLFIER").
dico("S", 7, "SOLFIES").
dico("S", 7, "SOLFIEZ").
dico("S", 7, "SOLIDES").
dico("S", 7, "SOLISTE").
dico("S", 7, "SOLIVES").
dico("S", 7, "SOLUBLE").
dico("S", 7, "SOLUTES").
dico("S", 7, "SOLVANT").
dico("S", 7, "SOLVATE").
dico("S", 7, "SOMALIE").
dico("S", 7, "SOMALIS").
dico("S", 7, "SOMBRAI").
dico("S", 7, "SOMBRAS").
dico("S", 7, "SOMBRAT").
dico("S", 7, "SOMBRER").
dico("S", 7, "SOMBRES").
dico("S", 7, "SOMBREZ").
dico("S", 7, "SOMITES").
dico("S", 7, "SOMMAIS").
dico("S", 7, "SOMMAIT").
dico("S", 7, "SOMMANT").
dico("S", 7, "SOMMEES").
dico("S", 7, "SOMMEIL").
dico("S", 7, "SOMMENT").
dico("S", 7, "SOMMERA").
dico("S", 7, "SOMMETS").
dico("S", 7, "SOMMIER").
dico("S", 7, "SOMMIEZ").
dico("S", 7, "SOMMITE").
dico("S", 7, "SOMMONS").
dico("S", 7, "SOMNOLA").
dico("S", 7, "SOMNOLE").
dico("S", 7, "SOMONIS").
dico("S", 7, "SONATES").
dico("S", 7, "SONDAGE").
dico("S", 7, "SONDAIS").
dico("S", 7, "SONDAIT").
dico("S", 7, "SONDANT").
dico("S", 7, "SONDEES").
dico("S", 7, "SONDENT").
dico("S", 7, "SONDERA").
dico("S", 7, "SONDEUR").
dico("S", 7, "SONDIEZ").
dico("S", 7, "SONDONS").
dico("S", 7, "SONGEAI").
dico("S", 7, "SONGEAS").
dico("S", 7, "SONGEAT").
dico("S", 7, "SONGENT").
dico("S", 7, "SONGERA").
dico("S", 7, "SONGEUR").
dico("S", 7, "SONGIEZ").
dico("S", 7, "SONIQUE").
dico("S", 7, "SONNAIS").
dico("S", 7, "SONNAIT").
dico("S", 7, "SONNANT").
dico("S", 7, "SONNEES").
dico("S", 7, "SONNENT").
dico("S", 7, "SONNERA").
dico("S", 7, "SONNETS").
dico("S", 7, "SONNEUR").
dico("S", 7, "SONNIEZ").
dico("S", 7, "SONNONS").
dico("S", 7, "SONORES").
dico("S", 7, "SOPHORA").
dico("S", 7, "SOPRANE").
dico("S", 7, "SOPRANI").
dico("S", 7, "SOPRANO").
dico("S", 7, "SOQUETS").
dico("S", 7, "SORBETS").
dico("S", 7, "SORBIER").
dico("S", 7, "SORCIER").
dico("S", 7, "SORDIDE").
dico("S", 7, "SORGHOS").
dico("S", 7, "SORITES").
dico("S", 7, "SORORAL").
dico("S", 7, "SORORAT").
dico("S", 7, "SORTAIS").
dico("S", 7, "SORTAIT").
dico("S", 7, "SORTANT").
dico("S", 7, "SORTENT").
dico("S", 7, "SORTEUR").
dico("S", 7, "SORTIES").
dico("S", 7, "SORTIEZ").
dico("S", 7, "SORTIRA").
dico("S", 7, "SORTONS").
dico("S", 7, "SOTTIES").
dico("S", 7, "SOTTISE").
dico("S", 7, "SOUABES").
dico("S", 7, "SOUAGES").
dico("S", 7, "SOUBISE").
dico("S", 7, "SOUCHES").
dico("S", 7, "SOUCHET").
dico("S", 7, "SOUCIAI").
dico("S", 7, "SOUCIAS").
dico("S", 7, "SOUCIAT").
dico("S", 7, "SOUCIEE").
dico("S", 7, "SOUCIER").
dico("S", 7, "SOUCIES").
dico("S", 7, "SOUCIEZ").
dico("S", 7, "SOUDAGE").
dico("S", 7, "SOUDAIN").
dico("S", 7, "SOUDAIS").
dico("S", 7, "SOUDAIT").
dico("S", 7, "SOUDANS").
dico("S", 7, "SOUDANT").
dico("S", 7, "SOUDARD").
dico("S", 7, "SOUDEES").
dico("S", 7, "SOUDENT").
dico("S", 7, "SOUDERA").
dico("S", 7, "SOUDEUR").
dico("S", 7, "SOUDIER").
dico("S", 7, "SOUDIEZ").
dico("S", 7, "SOUDOIE").
dico("S", 7, "SOUDONS").
dico("S", 7, "SOUDOYA").
dico("S", 7, "SOUDOYE").
dico("S", 7, "SOUDURE").
dico("S", 7, "SOUFFLA").
dico("S", 7, "SOUFFLE").
dico("S", 7, "SOUFFRE").
dico("S", 7, "SOUFIES").
dico("S", 7, "SOUFRAI").
dico("S", 7, "SOUFRAS").
dico("S", 7, "SOUFRAT").
dico("S", 7, "SOUFREE").
dico("S", 7, "SOUFRER").
dico("S", 7, "SOUFRES").
dico("S", 7, "SOUFREZ").
dico("S", 7, "SOUHAIT").
dico("S", 7, "SOUILLA").
dico("S", 7, "SOUILLE").
dico("S", 7, "SOUKHOT").
dico("S", 7, "SOUKKOT").
dico("S", 7, "SOULAGE").
dico("S", 7, "SOULAIS").
dico("S", 7, "SOULAIT").
dico("S", 7, "SOULANE").
dico("S", 7, "SOULANT").
dico("S", 7, "SOULARD").
dico("S", 7, "SOULAUD").
dico("S", 7, "SOULEES").
dico("S", 7, "SOULENT").
dico("S", 7, "SOULERA").
dico("S", 7, "SOULEVA").
dico("S", 7, "SOULEVE").
dico("S", 7, "SOULIER").
dico("S", 7, "SOULIEZ").
dico("S", 7, "SOULONS").
dico("S", 7, "SOULOTE").
dico("S", 7, "SOULOTS").
dico("S", 7, "SOULTES").
dico("S", 7, "SOUMETS").
dico("S", 7, "SOUMISE").
dico("S", 7, "SOUNNAS").
dico("S", 7, "SOUPAIS").
dico("S", 7, "SOUPAIT").
dico("S", 7, "SOUPANE").
dico("S", 7, "SOUPANT").
dico("S", 7, "SOUPAPE").
dico("S", 7, "SOUPCON").
dico("S", 7, "SOUPENT").
dico("S", 7, "SOUPERA").
dico("S", 7, "SOUPERS").
dico("S", 7, "SOUPESA").
dico("S", 7, "SOUPESE").
dico("S", 7, "SOUPEUR").
dico("S", 7, "SOUPIEZ").
dico("S", 7, "SOUPIRA").
dico("S", 7, "SOUPIRE").
dico("S", 7, "SOUPIRS").
dico("S", 7, "SOUPLES").
dico("S", 7, "SOUPONS").
dico("S", 7, "SOUQUAI").
dico("S", 7, "SOUQUAS").
dico("S", 7, "SOUQUAT").
dico("S", 7, "SOUQUEE").
dico("S", 7, "SOUQUER").
dico("S", 7, "SOUQUES").
dico("S", 7, "SOUQUEZ").
dico("S", 7, "SOURATE").
dico("S", 7, "SOURCES").
dico("S", 7, "SOURCIL").
dico("S", 7, "SOURDES").
dico("S", 7, "SOURDRE").
dico("S", 7, "SOURIES").
dico("S", 7, "SOURIEZ").
dico("S", 7, "SOURIRA").
dico("S", 7, "SOURIRE").
dico("S", 7, "SOUSLIK").
dico("S", 7, "SOUTANE").
dico("S", 7, "SOUTENU").
dico("S", 7, "SOUTIEN").
dico("S", 7, "SOUTIER").
dico("S", 7, "SOUTIFS").
dico("S", 7, "SOUTINS").
dico("S", 7, "SOUTINT").
dico("S", 7, "SOUTIRA").
dico("S", 7, "SOUTIRE").
dico("S", 7, "SOUTRAS").
dico("S", 7, "SOUVENT").
dico("S", 7, "SOUVENU").
dico("S", 7, "SOUVINS").
dico("S", 7, "SOUVINT").
dico("S", 7, "SOVIETS").
dico("S", 7, "SOVKHOZ").
dico("S", 7, "SOYERES").
dico("S", 7, "SOYEUSE").
dico("S", 7, "SPADICE").
dico("S", 7, "SPALTER").
dico("S", 7, "SPARIDE").
dico("S", 7, "SPARTES").
dico("S", 7, "SPASMES").
dico("S", 7, "SPATHES").
dico("S", 7, "SPATIAL").
dico("S", 7, "SPATULE").
dico("S", 7, "SPATZLE").
dico("S", 7, "SPEAKER").
dico("S", 7, "SPECIAL").
dico("S", 7, "SPECTRE").
dico("S", 7, "SPECULA").
dico("S", 7, "SPECULE").
dico("S", 7, "SPEECHS").
dico("S", 7, "SPEEDAI").
dico("S", 7, "SPEEDAS").
dico("S", 7, "SPEEDAT").
dico("S", 7, "SPEEDEE").
dico("S", 7, "SPEEDER").
dico("S", 7, "SPEEDES").
dico("S", 7, "SPEEDEZ").
dico("S", 7, "SPELEOS").
dico("S", 7, "SPENCER").
dico("S", 7, "SPERMES").
dico("S", 7, "SPHENES").
dico("S", 7, "SPHERES").
dico("S", 7, "SPHINGE").
dico("S", 7, "SPICULE").
dico("S", 7, "SPIDERS").
dico("S", 7, "SPIEGEL").
dico("S", 7, "SPINALE").
dico("S", 7, "SPINAUX").
dico("S", 7, "SPINULE").
dico("S", 7, "SPIRALE").
dico("S", 7, "SPIRANT").
dico("S", 7, "SPIRAUX").
dico("S", 7, "SPIREES").
dico("S", 7, "SPIRITE").
dico("S", 7, "SPIROUS").
dico("S", 7, "SPITANT").
dico("S", 7, "SPLEENS").
dico("S", 7, "SPOILER").
dico("S", 7, "SPOLIAI").
dico("S", 7, "SPOLIAS").
dico("S", 7, "SPOLIAT").
dico("S", 7, "SPOLIEE").
dico("S", 7, "SPOLIER").
dico("S", 7, "SPOLIES").
dico("S", 7, "SPOLIEZ").
dico("S", 7, "SPONDEE").
dico("S", 7, "SPONSOR").
dico("S", 7, "SPOOLER").
dico("S", 7, "SPORTIF").
dico("S", 7, "SPORULA").
dico("S", 7, "SPORULE").
dico("S", 7, "SPOULES").
dico("S", 7, "SPRINTA").
dico("S", 7, "SPRINTE").
dico("S", 7, "SPRINTS").
dico("S", 7, "SPUMEUX").
dico("S", 7, "SQUALES").
dico("S", 7, "SQUAMEE").
dico("S", 7, "SQUAMES").
dico("S", 7, "SQUARES").
dico("S", 7, "SQUASHS").
dico("S", 7, "SQUATTA").
dico("S", 7, "SQUATTE").
dico("S", 7, "SQUEEZA").
dico("S", 7, "SQUEEZE").
dico("S", 7, "SQUILLE").
dico("S", 7, "SQUIRES").
dico("S", 7, "SQUIRRE").
dico("S", 7, "STABILE").
dico("S", 7, "STABLES").
dico("S", 7, "STADIAS").
dico("S", 7, "STADIER").
dico("S", 7, "STAFFAI").
dico("S", 7, "STAFFAS").
dico("S", 7, "STAFFAT").
dico("S", 7, "STAFFEE").
dico("S", 7, "STAFFER").
dico("S", 7, "STAFFES").
dico("S", 7, "STAFFEZ").
dico("S", 7, "STAGNAI").
dico("S", 7, "STAGNAS").
dico("S", 7, "STAGNAT").
dico("S", 7, "STAGNER").
dico("S", 7, "STAGNES").
dico("S", 7, "STAGNEZ").
dico("S", 7, "STALAGS").
dico("S", 7, "STALLES").
dico("S", 7, "STAMINE").
dico("S", 7, "STANCES").
dico("S", 7, "STARETS").
dico("S", 7, "STARIES").
dico("S", 7, "STARISA").
dico("S", 7, "STARISE").
dico("S", 7, "STARTER").
dico("S", 7, "STATERE").
dico("S", 7, "STATICE").
dico("S", 7, "STATIFS").
dico("S", 7, "STATINE").
dico("S", 7, "STATION").
dico("S", 7, "STATIVE").
dico("S", 7, "STATORS").
dico("S", 7, "STATUAI").
dico("S", 7, "STATUAS").
dico("S", 7, "STATUAT").
dico("S", 7, "STATUEE").
dico("S", 7, "STATUER").
dico("S", 7, "STATUES").
dico("S", 7, "STATUEZ").
dico("S", 7, "STATURE").
dico("S", 7, "STATUTS").
dico("S", 7, "STAWUGS").
dico("S", 7, "STAYERS").
dico("S", 7, "STEAMER").
dico("S", 7, "STEEPLE").
dico("S", 7, "STENCIL").
dico("S", 7, "STENOPE").
dico("S", 7, "STENOSA").
dico("S", 7, "STENOSE").
dico("S", 7, "STENTOR").
dico("S", 7, "STEPPER").
dico("S", 7, "STEPPES").
dico("S", 7, "STERAGE").
dico("S", 7, "STERAIS").
dico("S", 7, "STERAIT").
dico("S", 7, "STERANT").
dico("S", 7, "STEREES").
dico("S", 7, "STERENT").
dico("S", 7, "STEREOS").
dico("S", 7, "STERERA").
dico("S", 7, "STERIDE").
dico("S", 7, "STERIEZ").
dico("S", 7, "STERILE").
dico("S", 7, "STERLET").
dico("S", 7, "STERNAL").
dico("S", 7, "STERNES").
dico("S", 7, "STERNUM").
dico("S", 7, "STEROLS").
dico("S", 7, "STERONS").
dico("S", 7, "STERTOR").
dico("S", 7, "STETSON").
dico("S", 7, "STEWARD").
dico("S", 7, "STHENES").
dico("S", 7, "STHENIE").
dico("S", 7, "STIBIEE").
dico("S", 7, "STIBIES").
dico("S", 7, "STIBINE").
dico("S", 7, "STICKER").
dico("S", 7, "STIGMAS").
dico("S", 7, "STILTON").
dico("S", 7, "STIMULA").
dico("S", 7, "STIMULE").
dico("S", 7, "STIMULI").
dico("S", 7, "STIPITE").
dico("S", 7, "STIPLES").
dico("S", 7, "STIPULA").
dico("S", 7, "STIPULE").
dico("S", 7, "STOCKAI").
dico("S", 7, "STOCKAS").
dico("S", 7, "STOCKAT").
dico("S", 7, "STOCKEE").
dico("S", 7, "STOCKER").
dico("S", 7, "STOCKES").
dico("S", 7, "STOCKEZ").
dico("S", 7, "STOIQUE").
dico("S", 7, "STOKERS").
dico("S", 7, "STOLONS").
dico("S", 7, "STOMATE").
dico("S", 7, "STOMATO").
dico("S", 7, "STOMIES").
dico("S", 7, "STOMISE").
dico("S", 7, "STOMOXE").
dico("S", 7, "STOPPAI").
dico("S", 7, "STOPPAS").
dico("S", 7, "STOPPAT").
dico("S", 7, "STOPPEE").
dico("S", 7, "STOPPER").
dico("S", 7, "STOPPES").
dico("S", 7, "STOPPEZ").
dico("S", 7, "STOUPAS").
dico("S", 7, "STRASSE").
dico("S", 7, "STRATES").
dico("S", 7, "STRATUM").
dico("S", 7, "STRATUS").
dico("S", 7, "STRESSA").
dico("S", 7, "STRESSE").
dico("S", 7, "STRETCH").
dico("S", 7, "STRETTE").
dico("S", 7, "STRIAIS").
dico("S", 7, "STRIAIT").
dico("S", 7, "STRIANT").
dico("S", 7, "STRICTE").
dico("S", 7, "STRICTS").
dico("S", 7, "STRIDOR").
dico("S", 7, "STRIEES").
dico("S", 7, "STRIENT").
dico("S", 7, "STRIERA").
dico("S", 7, "STRIGES").
dico("S", 7, "STRIIEZ").
dico("S", 7, "STRIKES").
dico("S", 7, "STRINGS").
dico("S", 7, "STRIONS").
dico("S", 7, "STRIPPA").
dico("S", 7, "STRIPPE").
dico("S", 7, "STRIURE").
dico("S", 7, "STROMAS").
dico("S", 7, "STROMBE").
dico("S", 7, "STROPHE").
dico("S", 7, "STRUDEL").
dico("S", 7, "STRUMES").
dico("S", 7, "STRYGES").
dico("S", 7, "STUCAGE").
dico("S", 7, "STUDENT").
dico("S", 7, "STUDIOS").
dico("S", 7, "STUPEUR").
dico("S", 7, "STUPIDE").
dico("S", 7, "STUPRES").
dico("S", 7, "STUQUAI").
dico("S", 7, "STUQUAS").
dico("S", 7, "STUQUAT").
dico("S", 7, "STUQUEE").
dico("S", 7, "STUQUER").
dico("S", 7, "STUQUES").
dico("S", 7, "STUQUEZ").
dico("S", 7, "STYLAIS").
dico("S", 7, "STYLAIT").
dico("S", 7, "STYLANT").
dico("S", 7, "STYLEES").
dico("S", 7, "STYLENT").
dico("S", 7, "STYLERA").
dico("S", 7, "STYLETS").
dico("S", 7, "STYLIEZ").
dico("S", 7, "STYLISA").
dico("S", 7, "STYLISE").
dico("S", 7, "STYLITE").
dico("S", 7, "STYLONS").
dico("S", 7, "STYRENE").
dico("S", 7, "SUAIENT").
dico("S", 7, "SUAIRES").
dico("S", 7, "SUANTES").
dico("S", 7, "SUASSES").
dico("S", 7, "SUAVITE").
dico("S", 7, "SUBAIGU").
dico("S", 7, "SUBIMES").
dico("S", 7, "SUBIRAI").
dico("S", 7, "SUBIRAS").
dico("S", 7, "SUBIREZ").
dico("S", 7, "SUBISSE").
dico("S", 7, "SUBITES").
dico("S", 7, "SUBLAIS").
dico("S", 7, "SUBLAIT").
dico("S", 7, "SUBLANT").
dico("S", 7, "SUBLEES").
dico("S", 7, "SUBLENT").
dico("S", 7, "SUBLERA").
dico("S", 7, "SUBLIEZ").
dico("S", 7, "SUBLIMA").
dico("S", 7, "SUBLIME").
dico("S", 7, "SUBLONS").
dico("S", 7, "SUBORNA").
dico("S", 7, "SUBORNE").
dico("S", 7, "SUBROGE").
dico("S", 7, "SUBSIDE").
dico("S", 7, "SUBSUMA").
dico("S", 7, "SUBSUME").
dico("S", 7, "SUBTILE").
dico("S", 7, "SUBTILS").
dico("S", 7, "SUBULEE").
dico("S", 7, "SUBULES").
dico("S", 7, "SUBVENU").
dico("S", 7, "SUBVINS").
dico("S", 7, "SUBVINT").
dico("S", 7, "SUCAMES").
dico("S", 7, "SUCASSE").
dico("S", 7, "SUCATES").
dico("S", 7, "SUCCEDA").
dico("S", 7, "SUCCEDE").
dico("S", 7, "SUCCINS").
dico("S", 7, "SUCCION").
dico("S", 7, "SUCCUBE").
dico("S", 7, "SUCEPIN").
dico("S", 7, "SUCERAI").
dico("S", 7, "SUCERAS").
dico("S", 7, "SUCEREZ").
dico("S", 7, "SUCETTE").
dico("S", 7, "SUCEURS").
dico("S", 7, "SUCEUSE").
dico("S", 7, "SUCIONS").
dico("S", 7, "SUCOIRS").
dico("S", 7, "SUCOTAI").
dico("S", 7, "SUCOTAS").
dico("S", 7, "SUCOTAT").
dico("S", 7, "SUCOTEE").
dico("S", 7, "SUCOTER").
dico("S", 7, "SUCOTES").
dico("S", 7, "SUCOTEZ").
dico("S", 7, "SUCRAGE").
dico("S", 7, "SUCRAIS").
dico("S", 7, "SUCRAIT").
dico("S", 7, "SUCRANT").
dico("S", 7, "SUCRASE").
dico("S", 7, "SUCRATE").
dico("S", 7, "SUCREES").
dico("S", 7, "SUCRENT").
dico("S", 7, "SUCRERA").
dico("S", 7, "SUCRIER").
dico("S", 7, "SUCRIEZ").
dico("S", 7, "SUCRINE").
dico("S", 7, "SUCRINS").
dico("S", 7, "SUCRONS").
dico("S", 7, "SUDETES").
dico("S", 7, "SUDISTE").
dico("S", 7, "SUDORAL").
dico("S", 7, "SUEDEES").
dico("S", 7, "SUEDINE").
dico("S", 7, "SUEDOIS").
dico("S", 7, "SUERAIS").
dico("S", 7, "SUERAIT").
dico("S", 7, "SUERENT").
dico("S", 7, "SUERIEZ").
dico("S", 7, "SUERONS").
dico("S", 7, "SUERONT").
dico("S", 7, "SUETTES").
dico("S", 7, "SUFFETE").
dico("S", 7, "SUFFIRA").
dico("S", 7, "SUFFIRE").
dico("S", 7, "SUFFISE").
dico("S", 7, "SUFFIXA").
dico("S", 7, "SUFFIXE").
dico("S", 7, "SUFISME").
dico("S", 7, "SUGGERA").
dico("S", 7, "SUGGERE").
dico("S", 7, "SUICIDA").
dico("S", 7, "SUICIDE").
dico("S", 7, "SUIFAIS").
dico("S", 7, "SUIFAIT").
dico("S", 7, "SUIFANT").
dico("S", 7, "SUIFEES").
dico("S", 7, "SUIFENT").
dico("S", 7, "SUIFERA").
dico("S", 7, "SUIFFAI").
dico("S", 7, "SUIFFAS").
dico("S", 7, "SUIFFAT").
dico("S", 7, "SUIFFEE").
dico("S", 7, "SUIFFER").
dico("S", 7, "SUIFFES").
dico("S", 7, "SUIFFEZ").
dico("S", 7, "SUIFIEZ").
dico("S", 7, "SUIFONS").
dico("S", 7, "SUINTAI").
dico("S", 7, "SUINTAS").
dico("S", 7, "SUINTAT").
dico("S", 7, "SUINTEE").
dico("S", 7, "SUINTER").
dico("S", 7, "SUINTES").
dico("S", 7, "SUINTEZ").
dico("S", 7, "SUISSES").
dico("S", 7, "SUITEES").
dico("S", 7, "SUIVAIS").
dico("S", 7, "SUIVAIT").
dico("S", 7, "SUIVANT").
dico("S", 7, "SUIVENT").
dico("S", 7, "SUIVEUR").
dico("S", 7, "SUIVIES").
dico("S", 7, "SUIVIEZ").
dico("S", 7, "SUIVONS").
dico("S", 7, "SUIVRAI").
dico("S", 7, "SUIVRAS").
dico("S", 7, "SUIVREZ").
dico("S", 7, "SUJETTE").
dico("S", 7, "SULFATA").
dico("S", 7, "SULFATE").
dico("S", 7, "SULFITA").
dico("S", 7, "SULFITE").
dico("S", 7, "SULFONA").
dico("S", 7, "SULFONE").
dico("S", 7, "SULFURA").
dico("S", 7, "SULFURE").
dico("S", 7, "SULKIES").
dico("S", 7, "SULTANE").
dico("S", 7, "SULTANS").
dico("S", 7, "SUMMUMS").
dico("S", 7, "SUNDAES").
dico("S", 7, "SUNNITE").
dico("S", 7, "SUPAMES").
dico("S", 7, "SUPASSE").
dico("S", 7, "SUPATES").
dico("S", 7, "SUPERAI").
dico("S", 7, "SUPERAS").
dico("S", 7, "SUPERBE").
dico("S", 7, "SUPERES").
dico("S", 7, "SUPEREZ").
dico("S", 7, "SUPIONS").
dico("S", 7, "SUPPLEA").
dico("S", 7, "SUPPLEE").
dico("S", 7, "SUPPLIA").
dico("S", 7, "SUPPLIE").
dico("S", 7, "SUPPORT").
dico("S", 7, "SUPPOSA").
dico("S", 7, "SUPPOSE").
dico("S", 7, "SUPPOTS").
dico("S", 7, "SUPPURA").
dico("S", 7, "SUPPURE").
dico("S", 7, "SUPPUTA").
dico("S", 7, "SUPPUTE").
dico("S", 7, "SUPREMA").
dico("S", 7, "SUPREME").
dico("S", 7, "SURAIGU").
dico("S", 7, "SURALES").
dico("S", 7, "SURANNE").
dico("S", 7, "SURARMA").
dico("S", 7, "SURARME").
dico("S", 7, "SURATES").
dico("S", 7, "SURBAUX").
dico("S", 7, "SURBOUM").
dico("S", 7, "SURBOUT").
dico("S", 7, "SURCOTA").
dico("S", 7, "SURCOTE").
dico("S", 7, "SURCOTS").
dico("S", 7, "SURCOUT").
dico("S", 7, "SURCUIT").
dico("S", 7, "SURDENT").
dico("S", 7, "SURDITE").
dico("S", 7, "SURDORA").
dico("S", 7, "SURDORE").
dico("S", 7, "SURDOSA").
dico("S", 7, "SURDOSE").
dico("S", 7, "SURDOUE").
dico("S", 7, "SUREAUX").
dico("S", 7, "SURELLE").
dico("S", 7, "SURETES").
dico("S", 7, "SURETTE").
dico("S", 7, "SURFACA").
dico("S", 7, "SURFACE").
dico("S", 7, "SURFAIS").
dico("S", 7, "SURFAIT").
dico("S", 7, "SURFAIX").
dico("S", 7, "SURFANT").
dico("S", 7, "SURFENT").
dico("S", 7, "SURFERA").
dico("S", 7, "SURFEUR").
dico("S", 7, "SURFIEZ").
dico("S", 7, "SURFILA").
dico("S", 7, "SURFILE").
dico("S", 7, "SURFILS").
dico("S", 7, "SURFINE").
dico("S", 7, "SURFINS").
dico("S", 7, "SURFONS").
dico("S", 7, "SURFONT").
dico("S", 7, "SURGELA").
dico("S", 7, "SURGELE").
dico("S", 7, "SURGEON").
dico("S", 7, "SURGIES").
dico("S", 7, "SURGIRA").
dico("S", 7, "SURIMES").
dico("S", 7, "SURIMIS").
dico("S", 7, "SURINAI").
dico("S", 7, "SURINAS").
dico("S", 7, "SURINAT").
dico("S", 7, "SURINEE").
dico("S", 7, "SURINER").
dico("S", 7, "SURINES").
dico("S", 7, "SURINEZ").
dico("S", 7, "SURIRAI").
dico("S", 7, "SURIRAS").
dico("S", 7, "SURIREZ").
dico("S", 7, "SURISSE").
dico("S", 7, "SURITES").
dico("S", 7, "SURJALA").
dico("S", 7, "SURJALE").
dico("S", 7, "SURJETA").
dico("S", 7, "SURJETE").
dico("S", 7, "SURJETS").
dico("S", 7, "SURLIAI").
dico("S", 7, "SURLIAS").
dico("S", 7, "SURLIAT").
dico("S", 7, "SURLIEE").
dico("S", 7, "SURLIER").
dico("S", 7, "SURLIES").
dico("S", 7, "SURLIEZ").
dico("S", 7, "SURLOUA").
dico("S", 7, "SURLOUE").
dico("S", 7, "SURMENA").
dico("S", 7, "SURMENE").
dico("S", 7, "SURNAGE").
dico("S", 7, "SURNOMS").
dico("S", 7, "SURNOTA").
dico("S", 7, "SURNOTE").
dico("S", 7, "SUROITS").
dico("S", 7, "SURPAIE").
dico("S", 7, "SURPAYA").
dico("S", 7, "SURPAYE").
dico("S", 7, "SURPLIS").
dico("S", 7, "SURPLUS").
dico("S", 7, "SURPRIS").
dico("S", 7, "SURPRIT").
dico("S", 7, "SURREEL").
dico("S", 7, "SURSAUT").
dico("S", 7, "SURSEMA").
dico("S", 7, "SURSEME").
dico("S", 7, "SURSISE").
dico("S", 7, "SURSOIE").
dico("S", 7, "SURSOIS").
dico("S", 7, "SURSOIT").
dico("S", 7, "SURTAUX").
dico("S", 7, "SURTAXA").
dico("S", 7, "SURTAXE").
dico("S", 7, "SURTOND").
dico("S", 7, "SURTOUT").
dico("S", 7, "SURVECU").
dico("S", 7, "SURVEND").
dico("S", 7, "SURVENU").
dico("S", 7, "SURVETS").
dico("S", 7, "SURVIES").
dico("S", 7, "SURVINS").
dico("S", 7, "SURVINT").
dico("S", 7, "SURVIRA").
dico("S", 7, "SURVIRE").
dico("S", 7, "SURVIVE").
dico("S", 7, "SURVOLA").
dico("S", 7, "SURVOLE").
dico("S", 7, "SURVOLS").
dico("S", 7, "SUSCITA").
dico("S", 7, "SUSCITE").
dico("S", 7, "SUSDITE").
dico("S", 7, "SUSDITS").
dico("S", 7, "SUSPECT").
dico("S", 7, "SUSPEND").
dico("S", 7, "SUSPENS").
dico("S", 7, "SUSSENT").
dico("S", 7, "SUSSIEZ").
dico("S", 7, "SUSURRA").
dico("S", 7, "SUSURRE").
dico("S", 7, "SUSVISE").
dico("S", 7, "SUTURAI").
dico("S", 7, "SUTURAL").
dico("S", 7, "SUTURAS").
dico("S", 7, "SUTURAT").
dico("S", 7, "SUTUREE").
dico("S", 7, "SUTURER").
dico("S", 7, "SUTURES").
dico("S", 7, "SUTUREZ").
dico("S", 7, "SUZETTE").
dico("S", 7, "SVELTES").
dico("S", 7, "SWAHELI").
dico("S", 7, "SWAHILI").
dico("S", 7, "SWAPPAI").
dico("S", 7, "SWAPPAS").
dico("S", 7, "SWAPPAT").
dico("S", 7, "SWAPPEE").
dico("S", 7, "SWAPPER").
dico("S", 7, "SWAPPES").
dico("S", 7, "SWAPPEZ").
dico("S", 7, "SWAZIES").
dico("S", 7, "SWEATER").
dico("S", 7, "SWINGUA").
dico("S", 7, "SWINGUE").
dico("S", 7, "SWITCHA").
dico("S", 7, "SWITCHE").
dico("S", 7, "SWITCHS").
dico("S", 7, "SYCONES").
dico("S", 7, "SYCOSIS").
dico("S", 7, "SYENITE").
dico("S", 7, "SYLLABE").
dico("S", 7, "SYLPHES").
dico("S", 7, "SYLVAIN").
dico("S", 7, "SYLVIES").
dico("S", 7, "SYLVITE").
dico("S", 7, "SYMBOLE").
dico("S", 7, "SYNAPSE").
dico("S", 7, "SYNASES").
dico("S", 7, "SYNCHRO").
dico("S", 7, "SYNCOPA").
dico("S", 7, "SYNCOPE").
dico("S", 7, "SYNDICS").
dico("S", 7, "SYNODAL").
dico("S", 7, "SYNODES").
dico("S", 7, "SYNOPSE").
dico("S", 7, "SYNOVIE").
dico("S", 7, "SYNTAXE").
dico("S", 7, "SYNTHES").
dico("S", 7, "SYNTONE").
dico("S", 7, "SYRIENS").
dico("S", 7, "SYRINGE").
dico("S", 7, "SYRPHES").
dico("S", 7, "SYSTEME").
dico("S", 7, "SYSTOLE").
dico("S", 7, "SYSTYLE").
dico("S", 7, "SYZYGIE").
