dico("S", 8, "SABAYONS").
dico("S", 8, "SABEENNE").
dico("S", 8, "SABEISME").
dico("S", 8, "SABELLES").
dico("S", 8, "SABLAGES").
dico("S", 8, "SABLAMES").
dico("S", 8, "SABLASSE").
dico("S", 8, "SABLATES").
dico("S", 8, "SABLERAI").
dico("S", 8, "SABLERAS").
dico("S", 8, "SABLEREZ").
dico("S", 8, "SABLERIE").
dico("S", 8, "SABLEURS").
dico("S", 8, "SABLEUSE").
dico("S", 8, "SABLIERE").
dico("S", 8, "SABLIERS").
dico("S", 8, "SABLIONS").
dico("S", 8, "SABLONNA").
dico("S", 8, "SABLONNE").
dico("S", 8, "SABORDAI").
dico("S", 8, "SABORDAS").
dico("S", 8, "SABORDAT").
dico("S", 8, "SABORDEE").
dico("S", 8, "SABORDER").
dico("S", 8, "SABORDES").
dico("S", 8, "SABORDEZ").
dico("S", 8, "SABOTAGE").
dico("S", 8, "SABOTAIS").
dico("S", 8, "SABOTAIT").
dico("S", 8, "SABOTANT").
dico("S", 8, "SABOTEES").
dico("S", 8, "SABOTENT").
dico("S", 8, "SABOTERA").
dico("S", 8, "SABOTEUR").
dico("S", 8, "SABOTIER").
dico("S", 8, "SABOTIEZ").
dico("S", 8, "SABOTONS").
dico("S", 8, "SABOULAI").
dico("S", 8, "SABOULAS").
dico("S", 8, "SABOULAT").
dico("S", 8, "SABOULEE").
dico("S", 8, "SABOULER").
dico("S", 8, "SABOULES").
dico("S", 8, "SABOULEZ").
dico("S", 8, "SABRAGES").
dico("S", 8, "SABRAMES").
dico("S", 8, "SABRASSE").
dico("S", 8, "SABRATES").
dico("S", 8, "SABRERAI").
dico("S", 8, "SABRERAS").
dico("S", 8, "SABREREZ").
dico("S", 8, "SABREURS").
dico("S", 8, "SABREUSE").
dico("S", 8, "SABRIONS").
dico("S", 8, "SABURRAL").
dico("S", 8, "SABURRES").
dico("S", 8, "SACCADAI").
dico("S", 8, "SACCADAS").
dico("S", 8, "SACCADAT").
dico("S", 8, "SACCADEE").
dico("S", 8, "SACCADER").
dico("S", 8, "SACCADES").
dico("S", 8, "SACCADEZ").
dico("S", 8, "SACCAGEA").
dico("S", 8, "SACCAGEE").
dico("S", 8, "SACCAGER").
dico("S", 8, "SACCAGES").
dico("S", 8, "SACCAGEZ").
dico("S", 8, "SACCULES").
dico("S", 8, "SACHERIE").
dico("S", 8, "SACHIONS").
dico("S", 8, "SACOCHES").
dico("S", 8, "SACOLEVA").
dico("S", 8, "SACOLEVE").
dico("S", 8, "SACQUAIS").
dico("S", 8, "SACQUAIT").
dico("S", 8, "SACQUANT").
dico("S", 8, "SACQUEES").
dico("S", 8, "SACQUENT").
dico("S", 8, "SACQUERA").
dico("S", 8, "SACQUIEZ").
dico("S", 8, "SACQUONS").
dico("S", 8, "SACRALES").
dico("S", 8, "SACRAMES").
dico("S", 8, "SACRASSE").
dico("S", 8, "SACRATES").
dico("S", 8, "SACRERAI").
dico("S", 8, "SACRERAS").
dico("S", 8, "SACREREZ").
dico("S", 8, "SACRIFIA").
dico("S", 8, "SACRIFIE").
dico("S", 8, "SACRIONS").
dico("S", 8, "SACRISTI").
dico("S", 8, "SADIQUES").
dico("S", 8, "SADISMES").
dico("S", 8, "SADOMASO").
dico("S", 8, "SADUCEEN").
dico("S", 8, "SAFRANAI").
dico("S", 8, "SAFRANAS").
dico("S", 8, "SAFRANAT").
dico("S", 8, "SAFRANEE").
dico("S", 8, "SAFRANER").
dico("S", 8, "SAFRANES").
dico("S", 8, "SAFRANEZ").
dico("S", 8, "SAGACITE").
dico("S", 8, "SAGEMENT").
dico("S", 8, "SAGESSES").
dico("S", 8, "SAGETTES").
dico("S", 8, "SAGITTAL").
dico("S", 8, "SAGITTEE").
dico("S", 8, "SAGITTES").
dico("S", 8, "SAGOUINE").
dico("S", 8, "SAGOUINS").
dico("S", 8, "SAHARIEN").
dico("S", 8, "SAHELIEN").
dico("S", 8, "SAHRAOUI").
dico("S", 8, "SAIETTAI").
dico("S", 8, "SAIETTAS").
dico("S", 8, "SAIETTAT").
dico("S", 8, "SAIETTEE").
dico("S", 8, "SAIETTER").
dico("S", 8, "SAIETTES").
dico("S", 8, "SAIETTEZ").
dico("S", 8, "SAIGNAIS").
dico("S", 8, "SAIGNAIT").
dico("S", 8, "SAIGNANT").
dico("S", 8, "SAIGNEES").
dico("S", 8, "SAIGNENT").
dico("S", 8, "SAIGNERA").
dico("S", 8, "SAIGNEUR").
dico("S", 8, "SAIGNEUX").
dico("S", 8, "SAIGNIEZ").
dico("S", 8, "SAIGNOIR").
dico("S", 8, "SAIGNONS").
dico("S", 8, "SAILLAIT").
dico("S", 8, "SAILLANT").
dico("S", 8, "SAILLENT").
dico("S", 8, "SAILLERA").
dico("S", 8, "SAILLIES").
dico("S", 8, "SAILLIRA").
dico("S", 8, "SAIMIRIS").
dico("S", 8, "SAINBOIS").
dico("S", 8, "SAINDOUX").
dico("S", 8, "SAINFOIN").
dico("S", 8, "SAINTETE").
dico("S", 8, "SAISIMES").
dico("S", 8, "SAISINES").
dico("S", 8, "SAISIRAI").
dico("S", 8, "SAISIRAS").
dico("S", 8, "SAISIREZ").
dico("S", 8, "SAISISSE").
dico("S", 8, "SAISITES").
dico("S", 8, "SAKTISME").
dico("S", 8, "SALACITE").
dico("S", 8, "SALADERO").
dico("S", 8, "SALADIER").
dico("S", 8, "SALAIENT").
dico("S", 8, "SALAIRES").
dico("S", 8, "SALAISON").
dico("S", 8, "SALANQUE").
dico("S", 8, "SALARIAI").
dico("S", 8, "SALARIAL").
dico("S", 8, "SALARIAS").
dico("S", 8, "SALARIAT").
dico("S", 8, "SALARIEE").
dico("S", 8, "SALARIER").
dico("S", 8, "SALARIES").
dico("S", 8, "SALARIEZ").
dico("S", 8, "SALASSES").
dico("S", 8, "SALAUDES").
dico("S", 8, "SALBANDE").
dico("S", 8, "SALCHOWS").
dico("S", 8, "SALEMENT").
dico("S", 8, "SALERAIS").
dico("S", 8, "SALERAIT").
dico("S", 8, "SALERENT").
dico("S", 8, "SALERIEZ").
dico("S", 8, "SALERONS").
dico("S", 8, "SALERONT").
dico("S", 8, "SALESIEN").
dico("S", 8, "SALEUSES").
dico("S", 8, "SALICINE").
dico("S", 8, "SALICOLE").
dico("S", 8, "SALICYLE").
dico("S", 8, "SALIENNE").
dico("S", 8, "SALIERES").
dico("S", 8, "SALIFERE").
dico("S", 8, "SALIFIAI").
dico("S", 8, "SALIFIAS").
dico("S", 8, "SALIFIAT").
dico("S", 8, "SALIFIEE").
dico("S", 8, "SALIFIER").
dico("S", 8, "SALIFIES").
dico("S", 8, "SALIFIEZ").
dico("S", 8, "SALIGAUD").
dico("S", 8, "SALIGNON").
dico("S", 8, "SALINAGE").
dico("S", 8, "SALINIER").
dico("S", 8, "SALINITE").
dico("S", 8, "SALIQUES").
dico("S", 8, "SALIRAIS").
dico("S", 8, "SALIRAIT").
dico("S", 8, "SALIRENT").
dico("S", 8, "SALIRIEZ").
dico("S", 8, "SALIRONS").
dico("S", 8, "SALIRONT").
dico("S", 8, "SALISSES").
dico("S", 8, "SALISSEZ").
dico("S", 8, "SALISSON").
dico("S", 8, "SALIVAIS").
dico("S", 8, "SALIVAIT").
dico("S", 8, "SALIVANT").
dico("S", 8, "SALIVENT").
dico("S", 8, "SALIVERA").
dico("S", 8, "SALIVIEZ").
dico("S", 8, "SALIVONS").
dico("S", 8, "SALONARD").
dico("S", 8, "SALOPAIS").
dico("S", 8, "SALOPAIT").
dico("S", 8, "SALOPANT").
dico("S", 8, "SALOPARD").
dico("S", 8, "SALOPEES").
dico("S", 8, "SALOPENT").
dico("S", 8, "SALOPERA").
dico("S", 8, "SALOPIAU").
dico("S", 8, "SALOPIEZ").
dico("S", 8, "SALOPIOT").
dico("S", 8, "SALOPONS").
dico("S", 8, "SALPETRA").
dico("S", 8, "SALPETRE").
dico("S", 8, "SALPICON").
dico("S", 8, "SALSIFIS").
dico("S", 8, "SALUAMES").
dico("S", 8, "SALUASSE").
dico("S", 8, "SALUATES").
dico("S", 8, "SALUBRES").
dico("S", 8, "SALUERAI").
dico("S", 8, "SALUERAS").
dico("S", 8, "SALUEREZ").
dico("S", 8, "SALUIONS").
dico("S", 8, "SAMARIUM").
dico("S", 8, "SAMBUCAS").
dico("S", 8, "SAMBUQUE").
dico("S", 8, "SAMIENNE").
dico("S", 8, "SAMIZDAT").
dico("S", 8, "SAMNITES").
dico("S", 8, "SAMOANES").
dico("S", 8, "SAMOURAI").
dico("S", 8, "SAMOVARS").
dico("S", 8, "SAMOYEDE").
dico("S", 8, "SAMPANGS").
dico("S", 8, "SAMPLAIS").
dico("S", 8, "SAMPLAIT").
dico("S", 8, "SAMPLANT").
dico("S", 8, "SAMPLEES").
dico("S", 8, "SAMPLENT").
dico("S", 8, "SAMPLERA").
dico("S", 8, "SAMPLERS").
dico("S", 8, "SAMPLIEZ").
dico("S", 8, "SAMPLING").
dico("S", 8, "SAMPLONS").
dico("S", 8, "SAMURAIS").
dico("S", 8, "SANCERRE").
dico("S", 8, "SANCTION").
dico("S", 8, "SANDALES").
dico("S", 8, "SANDJAKS").
dico("S", 8, "SANDWICH").
dico("S", 8, "SANGLAGE").
dico("S", 8, "SANGLAIS").
dico("S", 8, "SANGLAIT").
dico("S", 8, "SANGLANT").
dico("S", 8, "SANGLEES").
dico("S", 8, "SANGLENT").
dico("S", 8, "SANGLERA").
dico("S", 8, "SANGLIER").
dico("S", 8, "SANGLIEZ").
dico("S", 8, "SANGLONS").
dico("S", 8, "SANGLOTA").
dico("S", 8, "SANGLOTE").
dico("S", 8, "SANGLOTS").
dico("S", 8, "SANGRIAS").
dico("S", 8, "SANGSUES").
dico("S", 8, "SANGUINE").
dico("S", 8, "SANGUINS").
dico("S", 8, "SANICLES").
dico("S", 8, "SANICULE").
dico("S", 8, "SANIEUSE").
dico("S", 8, "SANSCRIT").
dico("S", 8, "SANSKRIT").
dico("S", 8, "SANTIAGS").
dico("S", 8, "SANTONES").
dico("S", 8, "SAOUDIEN").
dico("S", 8, "SAOUDITE").
dico("S", 8, "SAOULAIS").
dico("S", 8, "SAOULAIT").
dico("S", 8, "SAOULANT").
dico("S", 8, "SAOULARD").
dico("S", 8, "SAOULEES").
dico("S", 8, "SAOULENT").
dico("S", 8, "SAOULERA").
dico("S", 8, "SAOULIEZ").
dico("S", 8, "SAOULONS").
dico("S", 8, "SAPAIENT").
dico("S", 8, "SAPAJOUS").
dico("S", 8, "SAPASSES").
dico("S", 8, "SAPELLIS").
dico("S", 8, "SAPEMENT").
dico("S", 8, "SAPEQUES").
dico("S", 8, "SAPERAIS").
dico("S", 8, "SAPERAIT").
dico("S", 8, "SAPERDES").
dico("S", 8, "SAPERENT").
dico("S", 8, "SAPERIEZ").
dico("S", 8, "SAPERONS").
dico("S", 8, "SAPERONT").
dico("S", 8, "SAPHENES").
dico("S", 8, "SAPHIQUE").
dico("S", 8, "SAPHISME").
dico("S", 8, "SAPIDITE").
dico("S", 8, "SAPIENCE").
dico("S", 8, "SAPINAGE").
dico("S", 8, "SAPINEAU").
dico("S", 8, "SAPITEUR").
dico("S", 8, "SAPONACE").
dico("S", 8, "SAPONASE").
dico("S", 8, "SAPONINE").
dico("S", 8, "SAPONITE").
dico("S", 8, "SAPOTIER").
dico("S", 8, "SAPRISTI").
dico("S", 8, "SAPROPEL").
dico("S", 8, "SAQUAMES").
dico("S", 8, "SAQUASSE").
dico("S", 8, "SAQUATES").
dico("S", 8, "SAQUERAI").
dico("S", 8, "SAQUERAS").
dico("S", 8, "SAQUEREZ").
dico("S", 8, "SAQUIONS").
dico("S", 8, "SARCASME").
dico("S", 8, "SARCELLE").
dico("S", 8, "SARCINES").
dico("S", 8, "SARCLAGE").
dico("S", 8, "SARCLAIS").
dico("S", 8, "SARCLAIT").
dico("S", 8, "SARCLANT").
dico("S", 8, "SARCLEES").
dico("S", 8, "SARCLENT").
dico("S", 8, "SARCLERA").
dico("S", 8, "SARCLEUR").
dico("S", 8, "SARCLIEZ").
dico("S", 8, "SARCLOIR").
dico("S", 8, "SARCLONS").
dico("S", 8, "SARCLURE").
dico("S", 8, "SARCOIDE").
dico("S", 8, "SARCOMES").
dico("S", 8, "SARCOPTE").
dico("S", 8, "SARDANES").
dico("S", 8, "SARDINES").
dico("S", 8, "SARDOINE").
dico("S", 8, "SARDONYX").
dico("S", 8, "SARGASSE").
dico("S", 8, "SARIGUES").
dico("S", 8, "SARISSES").
dico("S", 8, "SARMENTA").
dico("S", 8, "SARMENTE").
dico("S", 8, "SARMENTS").
dico("S", 8, "SAROUALS").
dico("S", 8, "SAROUELS").
dico("S", 8, "SARRASIN").
dico("S", 8, "SARRETES").
dico("S", 8, "SARRETTE").
dico("S", 8, "SARROISE").
dico("S", 8, "SARTHOIS").
dico("S", 8, "SARTRIEN").
dico("S", 8, "SASHIMIS").
dico("S", 8, "SASSAGES").
dico("S", 8, "SASSAMES").
dico("S", 8, "SASSASSE").
dico("S", 8, "SASSATES").
dico("S", 8, "SASSERAI").
dico("S", 8, "SASSERAS").
dico("S", 8, "SASSEREZ").
dico("S", 8, "SASSEURS").
dico("S", 8, "SASSEUSE").
dico("S", 8, "SASSIONS").
dico("S", 8, "SATANEES").
dico("S", 8, "SATIETES").
dico("S", 8, "SATINAGE").
dico("S", 8, "SATINAIS").
dico("S", 8, "SATINAIT").
dico("S", 8, "SATINANT").
dico("S", 8, "SATINEES").
dico("S", 8, "SATINENT").
dico("S", 8, "SATINERA").
dico("S", 8, "SATINEUR").
dico("S", 8, "SATINIEZ").
dico("S", 8, "SATINONS").
dico("S", 8, "SATIRISA").
dico("S", 8, "SATIRISE").
dico("S", 8, "SATISFIS").
dico("S", 8, "SATISFIT").
dico("S", 8, "SATRAPES").
dico("S", 8, "SATRAPIE").
dico("S", 8, "SATURAIS").
dico("S", 8, "SATURAIT").
dico("S", 8, "SATURANT").
dico("S", 8, "SATUREES").
dico("S", 8, "SATURENT").
dico("S", 8, "SATURERA").
dico("S", 8, "SATURIEZ").
dico("S", 8, "SATURNES").
dico("S", 8, "SATURNIE").
dico("S", 8, "SATURNIN").
dico("S", 8, "SATURONS").
dico("S", 8, "SAUCAMES").
dico("S", 8, "SAUCASSE").
dico("S", 8, "SAUCATES").
dico("S", 8, "SAUCERAI").
dico("S", 8, "SAUCERAS").
dico("S", 8, "SAUCEREZ").
dico("S", 8, "SAUCETTE").
dico("S", 8, "SAUCIERE").
dico("S", 8, "SAUCIERS").
dico("S", 8, "SAUCIONS").
dico("S", 8, "SAUCISSE").
dico("S", 8, "SAUGRENU").
dico("S", 8, "SAULAIES").
dico("S", 8, "SAUMATRE").
dico("S", 8, "SAUMONEE").
dico("S", 8, "SAUMONES").
dico("S", 8, "SAUMURAI").
dico("S", 8, "SAUMURAS").
dico("S", 8, "SAUMURAT").
dico("S", 8, "SAUMUREE").
dico("S", 8, "SAUMURER").
dico("S", 8, "SAUMURES").
dico("S", 8, "SAUMUREZ").
dico("S", 8, "SAUNAGES").
dico("S", 8, "SAUNAMES").
dico("S", 8, "SAUNASSE").
dico("S", 8, "SAUNATES").
dico("S", 8, "SAUNERAI").
dico("S", 8, "SAUNERAS").
dico("S", 8, "SAUNEREZ").
dico("S", 8, "SAUNIERE").
dico("S", 8, "SAUNIERS").
dico("S", 8, "SAUNIONS").
dico("S", 8, "SAURAGES").
dico("S", 8, "SAURAMES").
dico("S", 8, "SAURASSE").
dico("S", 8, "SAURATES").
dico("S", 8, "SAURERAI").
dico("S", 8, "SAURERAS").
dico("S", 8, "SAUREREZ").
dico("S", 8, "SAURIENS").
dico("S", 8, "SAURIMES").
dico("S", 8, "SAURIONS").
dico("S", 8, "SAURIRAI").
dico("S", 8, "SAURIRAS").
dico("S", 8, "SAURIREZ").
dico("S", 8, "SAURISSE").
dico("S", 8, "SAURITES").
dico("S", 8, "SAUSSAIE").
dico("S", 8, "SAUTAGES").
dico("S", 8, "SAUTAMES").
dico("S", 8, "SAUTASSE").
dico("S", 8, "SAUTATES").
dico("S", 8, "SAUTELLE").
dico("S", 8, "SAUTERAI").
dico("S", 8, "SAUTERAS").
dico("S", 8, "SAUTEREZ").
dico("S", 8, "SAUTERIE").
dico("S", 8, "SAUTEURS").
dico("S", 8, "SAUTEUSE").
dico("S", 8, "SAUTIERS").
dico("S", 8, "SAUTILLA").
dico("S", 8, "SAUTILLE").
dico("S", 8, "SAUTIONS").
dico("S", 8, "SAUTOIRS").
dico("S", 8, "SAUVAGES").
dico("S", 8, "SAUVAGIN").
dico("S", 8, "SAUVAMES").
dico("S", 8, "SAUVASSE").
dico("S", 8, "SAUVATES").
dico("S", 8, "SAUVERAI").
dico("S", 8, "SAUVERAS").
dico("S", 8, "SAUVEREZ").
dico("S", 8, "SAUVETES").
dico("S", 8, "SAUVETTE").
dico("S", 8, "SAUVEURS").
dico("S", 8, "SAUVIONS").
dico("S", 8, "SAVAIENT").
dico("S", 8, "SAVANTES").
dico("S", 8, "SAVARINS").
dico("S", 8, "SAVETIER").
dico("S", 8, "SAVONNAI").
dico("S", 8, "SAVONNAS").
dico("S", 8, "SAVONNAT").
dico("S", 8, "SAVONNEE").
dico("S", 8, "SAVONNER").
dico("S", 8, "SAVONNES").
dico("S", 8, "SAVONNEZ").
dico("S", 8, "SAVOURAI").
dico("S", 8, "SAVOURAS").
dico("S", 8, "SAVOURAT").
dico("S", 8, "SAVOUREE").
dico("S", 8, "SAVOURER").
dico("S", 8, "SAVOURES").
dico("S", 8, "SAVOUREZ").
dico("S", 8, "SAVOYARD").
dico("S", 8, "SAXATILE").
dico("S", 8, "SAXHORNS").
dico("S", 8, "SAXICOLE").
dico("S", 8, "SAXONIEN").
dico("S", 8, "SAXONNES").
dico("S", 8, "SAYNETES").
dico("S", 8, "SCABIEUX").
dico("S", 8, "SCABINAL").
dico("S", 8, "SCABREUX").
dico("S", 8, "SCALAIRE").
dico("S", 8, "SCALANTE").
dico("S", 8, "SCALANTS").
dico("S", 8, "SCALDIEN").
dico("S", 8, "SCALENES").
dico("S", 8, "SCALPAIS").
dico("S", 8, "SCALPAIT").
dico("S", 8, "SCALPANT").
dico("S", 8, "SCALPEES").
dico("S", 8, "SCALPELS").
dico("S", 8, "SCALPENT").
dico("S", 8, "SCALPERA").
dico("S", 8, "SCALPIEZ").
dico("S", 8, "SCALPONS").
dico("S", 8, "SCANDAIS").
dico("S", 8, "SCANDAIT").
dico("S", 8, "SCANDALE").
dico("S", 8, "SCANDANT").
dico("S", 8, "SCANDEES").
dico("S", 8, "SCANDENT").
dico("S", 8, "SCANDERA").
dico("S", 8, "SCANDIEZ").
dico("S", 8, "SCANDIUM").
dico("S", 8, "SCANDONS").
dico("S", 8, "SCANNAIS").
dico("S", 8, "SCANNAIT").
dico("S", 8, "SCANNANT").
dico("S", 8, "SCANNEES").
dico("S", 8, "SCANNENT").
dico("S", 8, "SCANNERA").
dico("S", 8, "SCANNERS").
dico("S", 8, "SCANNEUR").
dico("S", 8, "SCANNIEZ").
dico("S", 8, "SCANNONS").
dico("S", 8, "SCANSION").
dico("S", 8, "SCAPHITE").
dico("S", 8, "SCAPULAS").
dico("S", 8, "SCARABEE").
dico("S", 8, "SCARIEUX").
dico("S", 8, "SCARIFIA").
dico("S", 8, "SCARIFIE").
dico("S", 8, "SCAROLES").
dico("S", 8, "SCATOLES").
dico("S", 8, "SCELERAT").
dico("S", 8, "SCELLAGE").
dico("S", 8, "SCELLAIS").
dico("S", 8, "SCELLAIT").
dico("S", 8, "SCELLANT").
dico("S", 8, "SCELLEES").
dico("S", 8, "SCELLENT").
dico("S", 8, "SCELLERA").
dico("S", 8, "SCELLIEZ").
dico("S", 8, "SCELLONS").
dico("S", 8, "SCENARII").
dico("S", 8, "SCENARIO").
dico("S", 8, "SCENIQUE").
dico("S", 8, "SCEPTRES").
dico("S", 8, "SCHADAIS").
dico("S", 8, "SCHADAIT").
dico("S", 8, "SCHADANT").
dico("S", 8, "SCHADENT").
dico("S", 8, "SCHADERA").
dico("S", 8, "SCHADIEZ").
dico("S", 8, "SCHADONS").
dico("S", 8, "SCHAPPES").
dico("S", 8, "SCHAPSKA").
dico("S", 8, "SCHEIDAI").
dico("S", 8, "SCHEIDAS").
dico("S", 8, "SCHEIDAT").
dico("S", 8, "SCHEIDEE").
dico("S", 8, "SCHEIDER").
dico("S", 8, "SCHEIDES").
dico("S", 8, "SCHEIDEZ").
dico("S", 8, "SCHELEMS").
dico("S", 8, "SCHERZOS").
dico("S", 8, "SCHIEDAM").
dico("S", 8, "SCHINDAI").
dico("S", 8, "SCHINDAS").
dico("S", 8, "SCHINDAT").
dico("S", 8, "SCHINDER").
dico("S", 8, "SCHINDES").
dico("S", 8, "SCHINDEZ").
dico("S", 8, "SCHISMES").
dico("S", 8, "SCHISTES").
dico("S", 8, "SCHIZOSE").
dico("S", 8, "SCHLAGUE").
dico("S", 8, "SCHLAMMS").
dico("S", 8, "SCHLEUES").
dico("S", 8, "SCHLICHS").
dico("S", 8, "SCHLITTA").
dico("S", 8, "SCHLITTE").
dico("S", 8, "SCHNICKS").
dico("S", 8, "SCHNOCKS").
dico("S", 8, "SCHNOQUE").
dico("S", 8, "SCHNOUFF").
dico("S", 8, "SCHNOUFS").
dico("S", 8, "SCHOFARS").
dico("S", 8, "SCHOLIES").
dico("S", 8, "SCHOONER").
dico("S", 8, "SCHORRES").
dico("S", 8, "SCHPROUM").
dico("S", 8, "SCIABLES").
dico("S", 8, "SCIAIENT").
dico("S", 8, "SCIANTES").
dico("S", 8, "SCIASSES").
dico("S", 8, "SCIENCES").
dico("S", 8, "SCIENIDE").
dico("S", 8, "SCIERAIS").
dico("S", 8, "SCIERAIT").
dico("S", 8, "SCIERENT").
dico("S", 8, "SCIERIES").
dico("S", 8, "SCIERIEZ").
dico("S", 8, "SCIERONS").
dico("S", 8, "SCIERONT").
dico("S", 8, "SCIEUSES").
dico("S", 8, "SCINCIDE").
dico("S", 8, "SCINDAIS").
dico("S", 8, "SCINDAIT").
dico("S", 8, "SCINDANT").
dico("S", 8, "SCINDEES").
dico("S", 8, "SCINDENT").
dico("S", 8, "SCINDERA").
dico("S", 8, "SCINDIEZ").
dico("S", 8, "SCINDONS").
dico("S", 8, "SCINQUES").
dico("S", 8, "SCIOTTES").
dico("S", 8, "SCISSILE").
dico("S", 8, "SCISSION").
dico("S", 8, "SCISSURE").
dico("S", 8, "SCIURIDE").
dico("S", 8, "SCLERALE").
dico("S", 8, "SCLERAUX").
dico("S", 8, "SCLEREUX").
dico("S", 8, "SCLEROSA").
dico("S", 8, "SCLEROSE").
dico("S", 8, "SCLEROTE").
dico("S", 8, "SCOLAIRE").
dico("S", 8, "SCOLIOSE").
dico("S", 8, "SCOLYTES").
dico("S", 8, "SCOOTERS").
dico("S", 8, "SCORAMES").
dico("S", 8, "SCORASSE").
dico("S", 8, "SCORATES").
dico("S", 8, "SCORBUTS").
dico("S", 8, "SCORERAI").
dico("S", 8, "SCORERAS").
dico("S", 8, "SCOREREZ").
dico("S", 8, "SCORIACE").
dico("S", 8, "SCORIFIA").
dico("S", 8, "SCORIFIE").
dico("S", 8, "SCORIONS").
dico("S", 8, "SCORPENE").
dico("S", 8, "SCORPION").
dico("S", 8, "SCOTCHAI").
dico("S", 8, "SCOTCHAS").
dico("S", 8, "SCOTCHAT").
dico("S", 8, "SCOTCHEE").
dico("S", 8, "SCOTCHER").
dico("S", 8, "SCOTCHES").
dico("S", 8, "SCOTCHEZ").
dico("S", 8, "SCOTISME").
dico("S", 8, "SCOTISTE").
dico("S", 8, "SCOTOMES").
dico("S", 8, "SCOTOPIE").
dico("S", 8, "SCOTTISH").
dico("S", 8, "SCOUREDS").
dico("S", 8, "SCRABBLA").
dico("S", 8, "SCRABBLE").
dico("S", 8, "SCRAPERS").
dico("S", 8, "SCRAPEUR").
dico("S", 8, "SCRAPIES").
dico("S", 8, "SCRATCHA").
dico("S", 8, "SCRATCHE").
dico("S", 8, "SCRATCHS").
dico("S", 8, "SCRIBANS").
dico("S", 8, "SCRIPTES").
dico("S", 8, "SCROFULE").
dico("S", 8, "SCROTALE").
dico("S", 8, "SCROTAUX").
dico("S", 8, "SCROTUMS").
dico("S", 8, "SCRUBBER").
dico("S", 8, "SCRUPULE").
dico("S", 8, "SCRUTAIS").
dico("S", 8, "SCRUTAIT").
dico("S", 8, "SCRUTANT").
dico("S", 8, "SCRUTEES").
dico("S", 8, "SCRUTENT").
dico("S", 8, "SCRUTERA").
dico("S", 8, "SCRUTIEZ").
dico("S", 8, "SCRUTINS").
dico("S", 8, "SCRUTONS").
dico("S", 8, "SCULPTAI").
dico("S", 8, "SCULPTAS").
dico("S", 8, "SCULPTAT").
dico("S", 8, "SCULPTEE").
dico("S", 8, "SCULPTER").
dico("S", 8, "SCULPTES").
dico("S", 8, "SCULPTEZ").
dico("S", 8, "SEBACEES").
dico("S", 8, "SEBASTES").
dico("S", 8, "SECABLES").
dico("S", 8, "SECANTES").
dico("S", 8, "SECATEUR").
dico("S", 8, "SECHAGES").
dico("S", 8, "SECHAMES").
dico("S", 8, "SECHANTE").
dico("S", 8, "SECHANTS").
dico("S", 8, "SECHASSE").
dico("S", 8, "SECHATES").
dico("S", 8, "SECHERAI").
dico("S", 8, "SECHERAS").
dico("S", 8, "SECHEREZ").
dico("S", 8, "SECHERIE").
dico("S", 8, "SECHEURS").
dico("S", 8, "SECHEUSE").
dico("S", 8, "SECHIONS").
dico("S", 8, "SECHOIRS").
dico("S", 8, "SECONDAI").
dico("S", 8, "SECONDAS").
dico("S", 8, "SECONDAT").
dico("S", 8, "SECONDEE").
dico("S", 8, "SECONDER").
dico("S", 8, "SECONDES").
dico("S", 8, "SECONDEZ").
dico("S", 8, "SECOUAGE").
dico("S", 8, "SECOUAIS").
dico("S", 8, "SECOUAIT").
dico("S", 8, "SECOUANT").
dico("S", 8, "SECOUEES").
dico("S", 8, "SECOUENT").
dico("S", 8, "SECOUERA").
dico("S", 8, "SECOUEUR").
dico("S", 8, "SECOUIEZ").
dico("S", 8, "SECOUONS").
dico("S", 8, "SECOURES").
dico("S", 8, "SECOUREZ").
dico("S", 8, "SECOURIR").
dico("S", 8, "SECOURRA").
dico("S", 8, "SECOURUE").
dico("S", 8, "SECOURUS").
dico("S", 8, "SECOURUT").
dico("S", 8, "SECOUSSE").
dico("S", 8, "SECRETAI").
dico("S", 8, "SECRETAS").
dico("S", 8, "SECRETAT").
dico("S", 8, "SECRETEE").
dico("S", 8, "SECRETER").
dico("S", 8, "SECRETES").
dico("S", 8, "SECRETEZ").
dico("S", 8, "SECTAIRE").
dico("S", 8, "SECTEURS").
dico("S", 8, "SECTIONS").
dico("S", 8, "SECULIER").
dico("S", 8, "SECURISA").
dico("S", 8, "SECURISE").
dico("S", 8, "SECURITE").
dico("S", 8, "SECURITS").
dico("S", 8, "SEDATIFS").
dico("S", 8, "SEDATION").
dico("S", 8, "SEDATIVE").
dico("S", 8, "SEDIMENT").
dico("S", 8, "SEDITION").
dico("S", 8, "SEDUIRAI").
dico("S", 8, "SEDUIRAS").
dico("S", 8, "SEDUIREZ").
dico("S", 8, "SEDUISES").
dico("S", 8, "SEDUISEZ").
dico("S", 8, "SEDUISIS").
dico("S", 8, "SEDUISIT").
dico("S", 8, "SEDUITES").
dico("S", 8, "SEDUNOIS").
dico("S", 8, "SEFARADE").
dico("S", 8, "SEFARDIM").
dico("S", 8, "SEFARDIS").
dico("S", 8, "SEGMENTA").
dico("S", 8, "SEGMENTE").
dico("S", 8, "SEGMENTS").
dico("S", 8, "SEGOVIEN").
dico("S", 8, "SEGREGEA").
dico("S", 8, "SEGREGEE").
dico("S", 8, "SEGREGER").
dico("S", 8, "SEGREGES").
dico("S", 8, "SEGREGEZ").
dico("S", 8, "SEGREGUA").
dico("S", 8, "SEGREGUE").
dico("S", 8, "SEIGNEUR").
dico("S", 8, "SEILLONS").
dico("S", 8, "SEISMALE").
dico("S", 8, "SEISMAUX").
dico("S", 8, "SEIZAINS").
dico("S", 8, "SEIZIEME").
dico("S", 8, "SEJOURNA").
dico("S", 8, "SEJOURNE").
dico("S", 8, "SELACIEN").
dico("S", 8, "SELECTAI").
dico("S", 8, "SELECTAS").
dico("S", 8, "SELECTAT").
dico("S", 8, "SELECTEE").
dico("S", 8, "SELECTER").
dico("S", 8, "SELECTES").
dico("S", 8, "SELECTEZ").
dico("S", 8, "SELECTIF").
dico("S", 8, "SELENATE").
dico("S", 8, "SELENIEE").
dico("S", 8, "SELENIEN").
dico("S", 8, "SELENIES").
dico("S", 8, "SELENITE").
dico("S", 8, "SELENIUM").
dico("S", 8, "SELLAGES").
dico("S", 8, "SELLAMES").
dico("S", 8, "SELLASSE").
dico("S", 8, "SELLATES").
dico("S", 8, "SELLERAI").
dico("S", 8, "SELLERAS").
dico("S", 8, "SELLEREZ").
dico("S", 8, "SELLERIE").
dico("S", 8, "SELLETTE").
dico("S", 8, "SELLIERS").
dico("S", 8, "SELLIONS").
dico("S", 8, "SEMAIENT").
dico("S", 8, "SEMAILLE").
dico("S", 8, "SEMAINES").
dico("S", 8, "SEMASSES").
dico("S", 8, "SEMBLAIS").
dico("S", 8, "SEMBLAIT").
dico("S", 8, "SEMBLANT").
dico("S", 8, "SEMBLENT").
dico("S", 8, "SEMBLERA").
dico("S", 8, "SEMBLIEZ").
dico("S", 8, "SEMBLONS").
dico("S", 8, "SEMELAGE").
dico("S", 8, "SEMELLES").
dico("S", 8, "SEMENCES").
dico("S", 8, "SEMERAIS").
dico("S", 8, "SEMERAIT").
dico("S", 8, "SEMERENT").
dico("S", 8, "SEMERIEZ").
dico("S", 8, "SEMERONS").
dico("S", 8, "SEMERONT").
dico("S", 8, "SEMESTRE").
dico("S", 8, "SEMEUSES").
dico("S", 8, "SEMILLON").
dico("S", 8, "SEMINALE").
dico("S", 8, "SEMINAUX").
dico("S", 8, "SEMINOLE").
dico("S", 8, "SEMINOME").
dico("S", 8, "SEMIQUES").
dico("S", 8, "SEMONCAI").
dico("S", 8, "SEMONCAS").
dico("S", 8, "SEMONCAT").
dico("S", 8, "SEMONCEE").
dico("S", 8, "SEMONCER").
dico("S", 8, "SEMONCES").
dico("S", 8, "SEMONCEZ").
dico("S", 8, "SEMOULES").
dico("S", 8, "SENAIRES").
dico("S", 8, "SENATEUR").
dico("S", 8, "SENECHAL").
dico("S", 8, "SENECONS").
dico("S", 8, "SENESTRE").
dico("S", 8, "SENEVOLS").
dico("S", 8, "SENILITE").
dico("S", 8, "SENIORAT").
dico("S", 8, "SENIORIE").
dico("S", 8, "SENNEURS").
dico("S", 8, "SENONAIS").
dico("S", 8, "SENONIEN").
dico("S", 8, "SENORITA").
dico("S", 8, "SENSEURS").
dico("S", 8, "SENSIBLE").
dico("S", 8, "SENSILLE").
dico("S", 8, "SENSITIF").
dico("S", 8, "SENSUELS").
dico("S", 8, "SENTENCE").
dico("S", 8, "SENTEURS").
dico("S", 8, "SENTIERS").
dico("S", 8, "SENTIMES").
dico("S", 8, "SENTINES").
dico("S", 8, "SENTIONS").
dico("S", 8, "SENTIRAI").
dico("S", 8, "SENTIRAS").
dico("S", 8, "SENTIREZ").
dico("S", 8, "SENTISSE").
dico("S", 8, "SENTITES").
dico("S", 8, "SEOULIEN").
dico("S", 8, "SEPARAIS").
dico("S", 8, "SEPARAIT").
dico("S", 8, "SEPARANT").
dico("S", 8, "SEPAREES").
dico("S", 8, "SEPARENT").
dico("S", 8, "SEPARERA").
dico("S", 8, "SEPARIEZ").
dico("S", 8, "SEPARONS").
dico("S", 8, "SEPIOLES").
dico("S", 8, "SEPPUKUS").
dico("S", 8, "SEPTAINS").
dico("S", 8, "SEPTALES").
dico("S", 8, "SEPTANTE").
dico("S", 8, "SEPTIDIS").
dico("S", 8, "SEPTIEME").
dico("S", 8, "SEPTIMES").
dico("S", 8, "SEPTIQUE").
dico("S", 8, "SEPTOLET").
dico("S", 8, "SEPTUORS").
dico("S", 8, "SEPTUPLA").
dico("S", 8, "SEPTUPLE").
dico("S", 8, "SEPULCRE").
dico("S", 8, "SEQUELLE").
dico("S", 8, "SEQUENCA").
dico("S", 8, "SEQUENCE").
dico("S", 8, "SEQUOIAS").
dico("S", 8, "SERAIENT").
dico("S", 8, "SERANCAI").
dico("S", 8, "SERANCAS").
dico("S", 8, "SERANCAT").
dico("S", 8, "SERANCEE").
dico("S", 8, "SERANCER").
dico("S", 8, "SERANCES").
dico("S", 8, "SERANCEZ").
dico("S", 8, "SERAPEUM").
dico("S", 8, "SERAPHIN").
dico("S", 8, "SERDEAUX").
dico("S", 8, "SEREINES").
dico("S", 8, "SERENADE").
dico("S", 8, "SERENITE").
dico("S", 8, "SERESIEN").
dico("S", 8, "SEREUSES").
dico("S", 8, "SERFOUIE").
dico("S", 8, "SERFOUIR").
dico("S", 8, "SERFOUIS").
dico("S", 8, "SERFOUIT").
dico("S", 8, "SERGENTS").
dico("S", 8, "SERGETTE").
dico("S", 8, "SERIAMES").
dico("S", 8, "SERIASSE").
dico("S", 8, "SERIATES").
dico("S", 8, "SERICINE").
dico("S", 8, "SERIELLE").
dico("S", 8, "SERIERAI").
dico("S", 8, "SERIERAS").
dico("S", 8, "SERIEREZ").
dico("S", 8, "SERIEUSE").
dico("S", 8, "SERIIONS").
dico("S", 8, "SERINAIS").
dico("S", 8, "SERINAIT").
dico("S", 8, "SERINANT").
dico("S", 8, "SERINEES").
dico("S", 8, "SERINENT").
dico("S", 8, "SERINERA").
dico("S", 8, "SERINGAS").
dico("S", 8, "SERINGAT").
dico("S", 8, "SERINGUA").
dico("S", 8, "SERINGUE").
dico("S", 8, "SERINIEZ").
dico("S", 8, "SERINONS").
dico("S", 8, "SERIQUES").
dico("S", 8, "SERMENTS").
dico("S", 8, "SERMONNA").
dico("S", 8, "SERMONNE").
dico("S", 8, "SEROSITE").
dico("S", 8, "SEROTINE").
dico("S", 8, "SEROTYPE").
dico("S", 8, "SERPENTA").
dico("S", 8, "SERPENTE").
dico("S", 8, "SERPENTS").
dico("S", 8, "SERPETTE").
dico("S", 8, "SERPOLET").
dico("S", 8, "SERPULES").
dico("S", 8, "SERRAGES").
dico("S", 8, "SERRAMES").
dico("S", 8, "SERRANTE").
dico("S", 8, "SERRANTS").
dico("S", 8, "SERRASSE").
dico("S", 8, "SERRATES").
dico("S", 8, "SERRATUS").
dico("S", 8, "SERRERAI").
dico("S", 8, "SERRERAS").
dico("S", 8, "SERREREZ").
dico("S", 8, "SERRETTE").
dico("S", 8, "SERRIONS").
dico("S", 8, "SERRISTE").
dico("S", 8, "SERRURES").
dico("S", 8, "SERTIMES").
dico("S", 8, "SERTIRAI").
dico("S", 8, "SERTIRAS").
dico("S", 8, "SERTIREZ").
dico("S", 8, "SERTISSE").
dico("S", 8, "SERTITES").
dico("S", 8, "SERVAGES").
dico("S", 8, "SERVANTE").
dico("S", 8, "SERVANTS").
dico("S", 8, "SERVEURS").
dico("S", 8, "SERVEUSE").
dico("S", 8, "SERVICES").
dico("S", 8, "SERVILES").
dico("S", 8, "SERVIMES").
dico("S", 8, "SERVIONS").
dico("S", 8, "SERVIRAI").
dico("S", 8, "SERVIRAS").
dico("S", 8, "SERVIREZ").
dico("S", 8, "SERVISSE").
dico("S", 8, "SERVITES").
dico("S", 8, "SESBANIA").
dico("S", 8, "SESBANIE").
dico("S", 8, "SESSILES").
dico("S", 8, "SESSIONS").
dico("S", 8, "SESTERCE").
dico("S", 8, "SETACEES").
dico("S", 8, "SETEREES").
dico("S", 8, "SETOISES").
dico("S", 8, "SEULETTE").
dico("S", 8, "SEVERITE").
dico("S", 8, "SEVILLAN").
dico("S", 8, "SEVIRAIS").
dico("S", 8, "SEVIRAIT").
dico("S", 8, "SEVIRENT").
dico("S", 8, "SEVIRIEZ").
dico("S", 8, "SEVIRONS").
dico("S", 8, "SEVIRONT").
dico("S", 8, "SEVISSES").
dico("S", 8, "SEVISSEZ").
dico("S", 8, "SEVRAGES").
dico("S", 8, "SEVRAMES").
dico("S", 8, "SEVRASSE").
dico("S", 8, "SEVRATES").
dico("S", 8, "SEVRERAI").
dico("S", 8, "SEVRERAS").
dico("S", 8, "SEVREREZ").
dico("S", 8, "SEVRIONS").
dico("S", 8, "SEVRUGAS").
dico("S", 8, "SEXENNAL").
dico("S", 8, "SEXISMES").
dico("S", 8, "SEXISTES").
dico("S", 8, "SEXTANTS").
dico("S", 8, "SEXTIDIS").
dico("S", 8, "SEXTINES").
dico("S", 8, "SEXTOLET").
dico("S", 8, "SEXTUORS").
dico("S", 8, "SEXTUPLA").
dico("S", 8, "SEXTUPLE").
dico("S", 8, "SEXUELLE").
dico("S", 8, "SEYAIENT").
dico("S", 8, "SEYANTES").
dico("S", 8, "SFAXIENS").
dico("S", 8, "SFUMATOS").
dico("S", 8, "SHABBATS").
dico("S", 8, "SHABIENS").
dico("S", 8, "SHABOUOT").
dico("S", 8, "SHAHNAIS").
dico("S", 8, "SHAMISEN").
dico("S", 8, "SHANTUNG").
dico("S", 8, "SHARPEIS").
dico("S", 8, "SHARPIES").
dico("S", 8, "SHAVINGS").
dico("S", 8, "SHERRIES").
dico("S", 8, "SHETLAND").
dico("S", 8, "SHIATSUS").
dico("S", 8, "SHIGELLE").
dico("S", 8, "SHIKHARA").
dico("S", 8, "SHILLING").
dico("S", 8, "SHINGLES").
dico("S", 8, "SHIRTING").
dico("S", 8, "SHIVAITE").
dico("S", 8, "SHOCKING").
dico("S", 8, "SHOGOUNS").
dico("S", 8, "SHOGUNAL").
dico("S", 8, "SHOGUNAT").
dico("S", 8, "SHOOTAIS").
dico("S", 8, "SHOOTAIT").
dico("S", 8, "SHOOTANT").
dico("S", 8, "SHOOTEES").
dico("S", 8, "SHOOTENT").
dico("S", 8, "SHOOTERA").
dico("S", 8, "SHOOTIEZ").
dico("S", 8, "SHOOTONS").
dico("S", 8, "SHOPPING").
dico("S", 8, "SHOWROOM").
dico("S", 8, "SHRAPNEL").
dico("S", 8, "SHUNTAGE").
dico("S", 8, "SHUNTAIS").
dico("S", 8, "SHUNTAIT").
dico("S", 8, "SHUNTANT").
dico("S", 8, "SHUNTEES").
dico("S", 8, "SHUNTENT").
dico("S", 8, "SHUNTERA").
dico("S", 8, "SHUNTIEZ").
dico("S", 8, "SHUNTONS").
dico("S", 8, "SIALIQUE").
dico("S", 8, "SIAMANGS").
dico("S", 8, "SIAMOISE").
dico("S", 8, "SIBERIEN").
dico("S", 8, "SIBILANT").
dico("S", 8, "SIBYLLES").
dico("S", 8, "SIBYLLIN").
dico("S", 8, "SICAIRES").
dico("S", 8, "SICCATIF").
dico("S", 8, "SICCITES").
dico("S", 8, "SICILIEN").
dico("S", 8, "SICLAMES").
dico("S", 8, "SICLASSE").
dico("S", 8, "SICLATES").
dico("S", 8, "SICLERAI").
dico("S", 8, "SICLERAS").
dico("S", 8, "SICLEREZ").
dico("S", 8, "SICLIONS").
dico("S", 8, "SIDAIQUE").
dico("S", 8, "SIDEENNE").
dico("S", 8, "SIDERAIS").
dico("S", 8, "SIDERAIT").
dico("S", 8, "SIDERALE").
dico("S", 8, "SIDERANT").
dico("S", 8, "SIDERAUX").
dico("S", 8, "SIDEREES").
dico("S", 8, "SIDERENT").
dico("S", 8, "SIDERERA").
dico("S", 8, "SIDERIEZ").
dico("S", 8, "SIDERITE").
dico("S", 8, "SIDERONS").
dico("S", 8, "SIDEROSE").
dico("S", 8, "SIEGEAIS").
dico("S", 8, "SIEGEAIT").
dico("S", 8, "SIEGEANT").
dico("S", 8, "SIEGEONS").
dico("S", 8, "SIEGERAI").
dico("S", 8, "SIEGERAS").
dico("S", 8, "SIEGEREZ").
dico("S", 8, "SIEGIONS").
dico("S", 8, "SIENNOIS").
dico("S", 8, "SIESTAIS").
dico("S", 8, "SIESTAIT").
dico("S", 8, "SIESTANT").
dico("S", 8, "SIESTENT").
dico("S", 8, "SIESTERA").
dico("S", 8, "SIESTIEZ").
dico("S", 8, "SIESTONS").
dico("S", 8, "SIEVERTS").
dico("S", 8, "SIFFLAGE").
dico("S", 8, "SIFFLAIS").
dico("S", 8, "SIFFLAIT").
dico("S", 8, "SIFFLANT").
dico("S", 8, "SIFFLEES").
dico("S", 8, "SIFFLENT").
dico("S", 8, "SIFFLERA").
dico("S", 8, "SIFFLETS").
dico("S", 8, "SIFFLEUR").
dico("S", 8, "SIFFLEUX").
dico("S", 8, "SIFFLIEZ").
dico("S", 8, "SIFFLONS").
dico("S", 8, "SIFFLOTA").
dico("S", 8, "SIFFLOTE").
dico("S", 8, "SIFILETS").
dico("S", 8, "SIGILLEE").
dico("S", 8, "SIGILLES").
dico("S", 8, "SIGISBEE").
dico("S", 8, "SIGMOIDE").
dico("S", 8, "SIGNALAI").
dico("S", 8, "SIGNALAS").
dico("S", 8, "SIGNALAT").
dico("S", 8, "SIGNALEE").
dico("S", 8, "SIGNALER").
dico("S", 8, "SIGNALES").
dico("S", 8, "SIGNALEZ").
dico("S", 8, "SIGNAMES").
dico("S", 8, "SIGNASSE").
dico("S", 8, "SIGNATES").
dico("S", 8, "SIGNERAI").
dico("S", 8, "SIGNERAS").
dico("S", 8, "SIGNEREZ").
dico("S", 8, "SIGNIFIA").
dico("S", 8, "SIGNIFIE").
dico("S", 8, "SIGNIONS").
dico("S", 8, "SIKHARAS").
dico("S", 8, "SIKHISME").
dico("S", 8, "SILAIENT").
dico("S", 8, "SILASSES").
dico("S", 8, "SILENCES").
dico("S", 8, "SILERAIS").
dico("S", 8, "SILERAIT").
dico("S", 8, "SILERENT").
dico("S", 8, "SILERIEZ").
dico("S", 8, "SILERONS").
dico("S", 8, "SILERONT").
dico("S", 8, "SILESIEN").
dico("S", 8, "SILICATE").
dico("S", 8, "SILICEUX").
dico("S", 8, "SILICIUM").
dico("S", 8, "SILICONA").
dico("S", 8, "SILICONE").
dico("S", 8, "SILICOSE").
dico("S", 8, "SILICULE").
dico("S", 8, "SILIONNE").
dico("S", 8, "SILIQUES").
dico("S", 8, "SILLAGES").
dico("S", 8, "SILLONNA").
dico("S", 8, "SILLONNE").
dico("S", 8, "SILOTAGE").
dico("S", 8, "SILPHIDE").
dico("S", 8, "SILURIDE").
dico("S", 8, "SILURIEN").
dico("S", 8, "SILVANER").
dico("S", 8, "SIMAGREE").
dico("S", 8, "SIMARRES").
dico("S", 8, "SIMARUBA").
dico("S", 8, "SIMBLEAU").
dico("S", 8, "SIMIENNE").
dico("S", 8, "SIMILISA").
dico("S", 8, "SIMILISE").
dico("S", 8, "SIMILORS").
dico("S", 8, "SIMONIES").
dico("S", 8, "SIMPLETS").
dico("S", 8, "SIMPLEXE").
dico("S", 8, "SIMULAIS").
dico("S", 8, "SIMULAIT").
dico("S", 8, "SIMULANT").
dico("S", 8, "SIMULEES").
dico("S", 8, "SIMULENT").
dico("S", 8, "SIMULERA").
dico("S", 8, "SIMULIES").
dico("S", 8, "SIMULIEZ").
dico("S", 8, "SIMULONS").
dico("S", 8, "SINAGOTS").
dico("S", 8, "SINAPISA").
dico("S", 8, "SINAPISE").
dico("S", 8, "SINCERES").
dico("S", 8, "SINCIPUT").
dico("S", 8, "SINECURE").
dico("S", 8, "SINGEAIS").
dico("S", 8, "SINGEAIT").
dico("S", 8, "SINGEANT").
dico("S", 8, "SINGEONS").
dico("S", 8, "SINGERAI").
dico("S", 8, "SINGERAS").
dico("S", 8, "SINGEREZ").
dico("S", 8, "SINGERIE").
dico("S", 8, "SINGIONS").
dico("S", 8, "SINGLETS").
dico("S", 8, "SINISAIS").
dico("S", 8, "SINISAIT").
dico("S", 8, "SINISANT").
dico("S", 8, "SINISEES").
dico("S", 8, "SINISENT").
dico("S", 8, "SINISERA").
dico("S", 8, "SINISIEZ").
dico("S", 8, "SINISONS").
dico("S", 8, "SINISTRE").
dico("S", 8, "SINOPLES").
dico("S", 8, "SINOQUES").
dico("S", 8, "SINUAMES").
dico("S", 8, "SINUASSE").
dico("S", 8, "SINUATES").
dico("S", 8, "SINUERAI").
dico("S", 8, "SINUERAS").
dico("S", 8, "SINUEREZ").
dico("S", 8, "SINUEUSE").
dico("S", 8, "SINUIONS").
dico("S", 8, "SINUSALE").
dico("S", 8, "SINUSAUX").
dico("S", 8, "SINUSIEN").
dico("S", 8, "SINUSITE").
dico("S", 8, "SIONISME").
dico("S", 8, "SIONISTE").
dico("S", 8, "SIPHOIDE").
dico("S", 8, "SIPHONNA").
dico("S", 8, "SIPHONNE").
dico("S", 8, "SIRENIEN").
dico("S", 8, "SIROCCOS").
dico("S", 8, "SIROTAIS").
dico("S", 8, "SIROTAIT").
dico("S", 8, "SIROTANT").
dico("S", 8, "SIROTEES").
dico("S", 8, "SIROTENT").
dico("S", 8, "SIROTERA").
dico("S", 8, "SIROTEUR").
dico("S", 8, "SIROTIEZ").
dico("S", 8, "SIROTONS").
dico("S", 8, "SIRTAKIS").
dico("S", 8, "SIRUPEUX").
dico("S", 8, "SIRVENTE").
dico("S", 8, "SISMALES").
dico("S", 8, "SISMIQUE").
dico("S", 8, "SISSONES").
dico("S", 8, "SISSONNE").
dico("S", 8, "SISYMBRE").
dico("S", 8, "SITTELES").
dico("S", 8, "SITTELLE").
dico("S", 8, "SITTIDES").
dico("S", 8, "SITUAMES").
dico("S", 8, "SITUASSE").
dico("S", 8, "SITUATES").
dico("S", 8, "SITUERAI").
dico("S", 8, "SITUERAS").
dico("S", 8, "SITUEREZ").
dico("S", 8, "SITUIONS").
dico("S", 8, "SIVAISME").
dico("S", 8, "SIVAITES").
dico("S", 8, "SIXIEMES").
dico("S", 8, "SIZAINES").
dico("S", 8, "SIZERINS").
dico("S", 8, "SKATINGS").
dico("S", 8, "SKELETON").
dico("S", 8, "SKETCHES").
dico("S", 8, "SKIABLES").
dico("S", 8, "SKIAIENT").
dico("S", 8, "SKIASSES").
dico("S", 8, "SKIERAIS").
dico("S", 8, "SKIERAIT").
dico("S", 8, "SKIERENT").
dico("S", 8, "SKIERIEZ").
dico("S", 8, "SKIERONS").
dico("S", 8, "SKIERONT").
dico("S", 8, "SKIEUSES").
dico("S", 8, "SKIFEURS").
dico("S", 8, "SKIFEUSE").
dico("S", 8, "SKIFFEUR").
dico("S", 8, "SKINHEAD").
dico("S", 8, "SKIPPAIS").
dico("S", 8, "SKIPPAIT").
dico("S", 8, "SKIPPANT").
dico("S", 8, "SKIPPEES").
dico("S", 8, "SKIPPENT").
dico("S", 8, "SKIPPERA").
dico("S", 8, "SKIPPERS").
dico("S", 8, "SKIPPIEZ").
dico("S", 8, "SKIPPONS").
dico("S", 8, "SKOPIOTE").
dico("S", 8, "SKYDOMES").
dico("S", 8, "SLALOMAI").
dico("S", 8, "SLALOMAS").
dico("S", 8, "SLALOMAT").
dico("S", 8, "SLALOMER").
dico("S", 8, "SLALOMES").
dico("S", 8, "SLALOMEZ").
dico("S", 8, "SLAVISAI").
dico("S", 8, "SLAVISAS").
dico("S", 8, "SLAVISAT").
dico("S", 8, "SLAVISEE").
dico("S", 8, "SLAVISER").
dico("S", 8, "SLAVISES").
dico("S", 8, "SLAVISEZ").
dico("S", 8, "SLAVISME").
dico("S", 8, "SLAVISTE").
dico("S", 8, "SLAVONNE").
dico("S", 8, "SLEEPING").
dico("S", 8, "SLICAMES").
dico("S", 8, "SLICASSE").
dico("S", 8, "SLICATES").
dico("S", 8, "SLICERAI").
dico("S", 8, "SLICERAS").
dico("S", 8, "SLICEREZ").
dico("S", 8, "SLICIONS").
dico("S", 8, "SLOUGHIS").
dico("S", 8, "SLOVAQUE").
dico("S", 8, "SLOVENES").
dico("S", 8, "SMALTINE").
dico("S", 8, "SMALTITE").
dico("S", 8, "SMASHAIS").
dico("S", 8, "SMASHAIT").
dico("S", 8, "SMASHANT").
dico("S", 8, "SMASHEES").
dico("S", 8, "SMASHENT").
dico("S", 8, "SMASHERA").
dico("S", 8, "SMASHEUR").
dico("S", 8, "SMASHIEZ").
dico("S", 8, "SMASHONS").
dico("S", 8, "SMICARDE").
dico("S", 8, "SMICARDS").
dico("S", 8, "SMILLAGE").
dico("S", 8, "SMILLAIS").
dico("S", 8, "SMILLAIT").
dico("S", 8, "SMILLANT").
dico("S", 8, "SMILLEES").
dico("S", 8, "SMILLENT").
dico("S", 8, "SMILLERA").
dico("S", 8, "SMILLIEZ").
dico("S", 8, "SMILLONS").
dico("S", 8, "SMOKINGS").
dico("S", 8, "SMURFAIS").
dico("S", 8, "SMURFAIT").
dico("S", 8, "SMURFANT").
dico("S", 8, "SMURFENT").
dico("S", 8, "SMURFERA").
dico("S", 8, "SMURFEUR").
dico("S", 8, "SMURFIEZ").
dico("S", 8, "SMURFONS").
dico("S", 8, "SNIFAMES").
dico("S", 8, "SNIFASSE").
dico("S", 8, "SNIFATES").
dico("S", 8, "SNIFERAI").
dico("S", 8, "SNIFERAS").
dico("S", 8, "SNIFEREZ").
dico("S", 8, "SNIFFAIS").
dico("S", 8, "SNIFFAIT").
dico("S", 8, "SNIFFANT").
dico("S", 8, "SNIFFEES").
dico("S", 8, "SNIFFENT").
dico("S", 8, "SNIFFERA").
dico("S", 8, "SNIFFIEZ").
dico("S", 8, "SNIFFONS").
dico("S", 8, "SNIFIONS").
dico("S", 8, "SNOBAMES").
dico("S", 8, "SNOBASSE").
dico("S", 8, "SNOBATES").
dico("S", 8, "SNOBERAI").
dico("S", 8, "SNOBERAS").
dico("S", 8, "SNOBEREZ").
dico("S", 8, "SNOBIONS").
dico("S", 8, "SNOBISME").
dico("S", 8, "SNOOKERS").
dico("S", 8, "SNOREAUX").
dico("S", 8, "SOBRIETE").
dico("S", 8, "SOCIABLE").
dico("S", 8, "SOCIALES").
dico("S", 8, "SOCIALOS").
dico("S", 8, "SOCIETAL").
dico("S", 8, "SOCIETES").
dico("S", 8, "SOCINIEN").
dico("S", 8, "SOCQUETS").
dico("S", 8, "SODIQUES").
dico("S", 8, "SODOMIES").
dico("S", 8, "SODOMISA").
dico("S", 8, "SODOMISE").
dico("S", 8, "SODOMITE").
dico("S", 8, "SOFFITES").
dico("S", 8, "SOFIOTES").
dico("S", 8, "SOFTBALL").
dico("S", 8, "SOFTWARE").
dico("S", 8, "SOIERIES").
dico("S", 8, "SOIFFARD").
dico("S", 8, "SOIGNAIS").
dico("S", 8, "SOIGNAIT").
dico("S", 8, "SOIGNANT").
dico("S", 8, "SOIGNEES").
dico("S", 8, "SOIGNENT").
dico("S", 8, "SOIGNERA").
dico("S", 8, "SOIGNEUR").
dico("S", 8, "SOIGNEUX").
dico("S", 8, "SOIGNIEZ").
dico("S", 8, "SOIGNONS").
dico("S", 8, "SOIXANTE").
dico("S", 8, "SOLAIRES").
dico("S", 8, "SOLARISA").
dico("S", 8, "SOLARISE").
dico("S", 8, "SOLARIUM").
dico("S", 8, "SOLDAMES").
dico("S", 8, "SOLDASSE").
dico("S", 8, "SOLDATES").
dico("S", 8, "SOLDERAI").
dico("S", 8, "SOLDERAS").
dico("S", 8, "SOLDEREZ").
dico("S", 8, "SOLDERIE").
dico("S", 8, "SOLDEURS").
dico("S", 8, "SOLDEUSE").
dico("S", 8, "SOLDIONS").
dico("S", 8, "SOLEAIRE").
dico("S", 8, "SOLEARES").
dico("S", 8, "SOLENNEL").
dico("S", 8, "SOLERETS").
dico("S", 8, "SOLETTES").
dico("S", 8, "SOLFEGES").
dico("S", 8, "SOLFIAIS").
dico("S", 8, "SOLFIAIT").
dico("S", 8, "SOLFIANT").
dico("S", 8, "SOLFIEES").
dico("S", 8, "SOLFIENT").
dico("S", 8, "SOLFIERA").
dico("S", 8, "SOLFIIEZ").
dico("S", 8, "SOLFIONS").
dico("S", 8, "SOLIDAGE").
dico("S", 8, "SOLIDAGO").
dico("S", 8, "SOLIDITE").
dico("S", 8, "SOLIFUGE").
dico("S", 8, "SOLIPEDE").
dico("S", 8, "SOLISTES").
dico("S", 8, "SOLITUDE").
dico("S", 8, "SOLIVEAU").
dico("S", 8, "SOLOGNOT").
dico("S", 8, "SOLSTICE").
dico("S", 8, "SOLUBLES").
dico("S", 8, "SOLUTION").
dico("S", 8, "SOLVABLE").
dico("S", 8, "SOLVANTS").
dico("S", 8, "SOLVATES").
dico("S", 8, "SOMALIEN").
dico("S", 8, "SOMALIES").
dico("S", 8, "SOMATION").
dico("S", 8, "SOMATISA").
dico("S", 8, "SOMATISE").
dico("S", 8, "SOMBRAIS").
dico("S", 8, "SOMBRAIT").
dico("S", 8, "SOMBRANT").
dico("S", 8, "SOMBRENT").
dico("S", 8, "SOMBRERA").
dico("S", 8, "SOMBRERO").
dico("S", 8, "SOMBRIEZ").
dico("S", 8, "SOMBRONS").
dico("S", 8, "SOMMABLE").
dico("S", 8, "SOMMAIRE").
dico("S", 8, "SOMMAMES").
dico("S", 8, "SOMMASSE").
dico("S", 8, "SOMMATES").
dico("S", 8, "SOMMEILS").
dico("S", 8, "SOMMERAI").
dico("S", 8, "SOMMERAS").
dico("S", 8, "SOMMEREZ").
dico("S", 8, "SOMMIERS").
dico("S", 8, "SOMMIONS").
dico("S", 8, "SOMMITAL").
dico("S", 8, "SOMMITES").
dico("S", 8, "SOMNOLAI").
dico("S", 8, "SOMNOLAS").
dico("S", 8, "SOMNOLAT").
dico("S", 8, "SOMNOLER").
dico("S", 8, "SOMNOLES").
dico("S", 8, "SOMNOLEZ").
dico("S", 8, "SONATINE").
dico("S", 8, "SONDAGES").
dico("S", 8, "SONDAMES").
dico("S", 8, "SONDASSE").
dico("S", 8, "SONDATES").
dico("S", 8, "SONDERAI").
dico("S", 8, "SONDERAS").
dico("S", 8, "SONDEREZ").
dico("S", 8, "SONDEURS").
dico("S", 8, "SONDEUSE").
dico("S", 8, "SONDIONS").
dico("S", 8, "SONEGIEN").
dico("S", 8, "SONGEAIS").
dico("S", 8, "SONGEAIT").
dico("S", 8, "SONGEANT").
dico("S", 8, "SONGEONS").
dico("S", 8, "SONGERAI").
dico("S", 8, "SONGERAS").
dico("S", 8, "SONGEREZ").
dico("S", 8, "SONGERIE").
dico("S", 8, "SONGEURS").
dico("S", 8, "SONGEUSE").
dico("S", 8, "SONGIONS").
dico("S", 8, "SONIQUES").
dico("S", 8, "SONNAMES").
dico("S", 8, "SONNANTE").
dico("S", 8, "SONNANTS").
dico("S", 8, "SONNASSE").
dico("S", 8, "SONNATES").
dico("S", 8, "SONNERAI").
dico("S", 8, "SONNERAS").
dico("S", 8, "SONNEREZ").
dico("S", 8, "SONNERIE").
dico("S", 8, "SONNETTE").
dico("S", 8, "SONNEURS").
dico("S", 8, "SONNEUSE").
dico("S", 8, "SONNIONS").
dico("S", 8, "SONORISA").
dico("S", 8, "SONORISE").
dico("S", 8, "SONORITE").
dico("S", 8, "SONOTONE").
dico("S", 8, "SOPHISME").
dico("S", 8, "SOPHISTE").
dico("S", 8, "SOPHORAS").
dico("S", 8, "SOPOREUX").
dico("S", 8, "SOPRANES").
dico("S", 8, "SOPRANOS").
dico("S", 8, "SORBIERS").
dico("S", 8, "SORBITOL").
dico("S", 8, "SORCIERE").
dico("S", 8, "SORCIERS").
dico("S", 8, "SORDIDES").
dico("S", 8, "SORNETTE").
dico("S", 8, "SORORALE").
dico("S", 8, "SORORATS").
dico("S", 8, "SORORAUX").
dico("S", 8, "SORORITE").
dico("S", 8, "SORPTION").
dico("S", 8, "SORTABLE").
dico("S", 8, "SORTANTE").
dico("S", 8, "SORTANTS").
dico("S", 8, "SORTEURS").
dico("S", 8, "SORTEUSE").
dico("S", 8, "SORTIMES").
dico("S", 8, "SORTIONS").
dico("S", 8, "SORTIRAI").
dico("S", 8, "SORTIRAS").
dico("S", 8, "SORTIREZ").
dico("S", 8, "SORTISSE").
dico("S", 8, "SORTITES").
dico("S", 8, "SOTTISES").
dico("S", 8, "SOUAHELI").
dico("S", 8, "SOUBISES").
dico("S", 8, "SOUCHETS").
dico("S", 8, "SOUCHONG").
dico("S", 8, "SOUCIAIS").
dico("S", 8, "SOUCIAIT").
dico("S", 8, "SOUCIANT").
dico("S", 8, "SOUCIEES").
dico("S", 8, "SOUCIENT").
dico("S", 8, "SOUCIERA").
dico("S", 8, "SOUCIEUX").
dico("S", 8, "SOUCIIEZ").
dico("S", 8, "SOUCIONS").
dico("S", 8, "SOUCOUPE").
dico("S", 8, "SOUDABLE").
dico("S", 8, "SOUDAGES").
dico("S", 8, "SOUDAINE").
dico("S", 8, "SOUDAINS").
dico("S", 8, "SOUDAMES").
dico("S", 8, "SOUDANTE").
dico("S", 8, "SOUDANTS").
dico("S", 8, "SOUDARDS").
dico("S", 8, "SOUDASSE").
dico("S", 8, "SOUDATES").
dico("S", 8, "SOUDERAI").
dico("S", 8, "SOUDERAS").
dico("S", 8, "SOUDEREZ").
dico("S", 8, "SOUDEURS").
dico("S", 8, "SOUDEUSE").
dico("S", 8, "SOUDIERE").
dico("S", 8, "SOUDIERS").
dico("S", 8, "SOUDIONS").
dico("S", 8, "SOUDOIES").
dico("S", 8, "SOUDOYAI").
dico("S", 8, "SOUDOYAS").
dico("S", 8, "SOUDOYAT").
dico("S", 8, "SOUDOYEE").
dico("S", 8, "SOUDOYER").
dico("S", 8, "SOUDOYES").
dico("S", 8, "SOUDOYEZ").
dico("S", 8, "SOUDURES").
dico("S", 8, "SOUFFERT").
dico("S", 8, "SOUFFLAI").
dico("S", 8, "SOUFFLAS").
dico("S", 8, "SOUFFLAT").
dico("S", 8, "SOUFFLEE").
dico("S", 8, "SOUFFLER").
dico("S", 8, "SOUFFLES").
dico("S", 8, "SOUFFLET").
dico("S", 8, "SOUFFLEZ").
dico("S", 8, "SOUFFRES").
dico("S", 8, "SOUFFREZ").
dico("S", 8, "SOUFFRIR").
dico("S", 8, "SOUFFRIS").
dico("S", 8, "SOUFFRIT").
dico("S", 8, "SOUFISME").
dico("S", 8, "SOUFRAGE").
dico("S", 8, "SOUFRAIS").
dico("S", 8, "SOUFRAIT").
dico("S", 8, "SOUFRANT").
dico("S", 8, "SOUFREES").
dico("S", 8, "SOUFRENT").
dico("S", 8, "SOUFRERA").
dico("S", 8, "SOUFREUR").
dico("S", 8, "SOUFRIEZ").
dico("S", 8, "SOUFROIR").
dico("S", 8, "SOUFRONS").
dico("S", 8, "SOUHAITA").
dico("S", 8, "SOUHAITE").
dico("S", 8, "SOUHAITS").
dico("S", 8, "SOUILLAI").
dico("S", 8, "SOUILLAS").
dico("S", 8, "SOUILLAT").
dico("S", 8, "SOUILLEE").
dico("S", 8, "SOUILLER").
dico("S", 8, "SOUILLES").
dico("S", 8, "SOUILLEZ").
dico("S", 8, "SOUILLON").
dico("S", 8, "SOUKHOTS").
dico("S", 8, "SOUKKOTS").
dico("S", 8, "SOULAGEA").
dico("S", 8, "SOULAGEE").
dico("S", 8, "SOULAGER").
dico("S", 8, "SOULAGES").
dico("S", 8, "SOULAGEZ").
dico("S", 8, "SOULAMES").
dico("S", 8, "SOULANES").
dico("S", 8, "SOULANTE").
dico("S", 8, "SOULANTS").
dico("S", 8, "SOULARDE").
dico("S", 8, "SOULARDS").
dico("S", 8, "SOULASSE").
dico("S", 8, "SOULATES").
dico("S", 8, "SOULAUDE").
dico("S", 8, "SOULAUDS").
dico("S", 8, "SOULERAI").
dico("S", 8, "SOULERAS").
dico("S", 8, "SOULEREZ").
dico("S", 8, "SOULERIE").
dico("S", 8, "SOULEVAI").
dico("S", 8, "SOULEVAS").
dico("S", 8, "SOULEVAT").
dico("S", 8, "SOULEVEE").
dico("S", 8, "SOULEVER").
dico("S", 8, "SOULEVES").
dico("S", 8, "SOULEVEZ").
dico("S", 8, "SOULIERS").
dico("S", 8, "SOULIGNA").
dico("S", 8, "SOULIGNE").
dico("S", 8, "SOULIONS").
dico("S", 8, "SOULONNE").
dico("S", 8, "SOULOTES").
dico("S", 8, "SOUMETTE").
dico("S", 8, "SOUMIMES").
dico("S", 8, "SOUMISES").
dico("S", 8, "SOUMISSE").
dico("S", 8, "SOUMITES").
dico("S", 8, "SOUPAMES").
dico("S", 8, "SOUPANES").
dico("S", 8, "SOUPAPES").
dico("S", 8, "SOUPASSE").
dico("S", 8, "SOUPATES").
dico("S", 8, "SOUPCONS").
dico("S", 8, "SOUPENTE").
dico("S", 8, "SOUPERAI").
dico("S", 8, "SOUPERAS").
dico("S", 8, "SOUPEREZ").
dico("S", 8, "SOUPESAI").
dico("S", 8, "SOUPESAS").
dico("S", 8, "SOUPESAT").
dico("S", 8, "SOUPESEE").
dico("S", 8, "SOUPESER").
dico("S", 8, "SOUPESES").
dico("S", 8, "SOUPESEZ").
dico("S", 8, "SOUPEURS").
dico("S", 8, "SOUPEUSE").
dico("S", 8, "SOUPIERE").
dico("S", 8, "SOUPIONS").
dico("S", 8, "SOUPIRAI").
dico("S", 8, "SOUPIRAS").
dico("S", 8, "SOUPIRAT").
dico("S", 8, "SOUPIREE").
dico("S", 8, "SOUPIRER").
dico("S", 8, "SOUPIRES").
dico("S", 8, "SOUPIREZ").
dico("S", 8, "SOUQUAIS").
dico("S", 8, "SOUQUAIT").
dico("S", 8, "SOUQUANT").
dico("S", 8, "SOUQUEES").
dico("S", 8, "SOUQUENT").
dico("S", 8, "SOUQUERA").
dico("S", 8, "SOUQUIEZ").
dico("S", 8, "SOUQUONS").
dico("S", 8, "SOURATES").
dico("S", 8, "SOURCEUR").
dico("S", 8, "SOURCIER").
dico("S", 8, "SOURCILS").
dico("S", 8, "SOURDAIT").
dico("S", 8, "SOURDENT").
dico("S", 8, "SOURDINE").
dico("S", 8, "SOURIAIS").
dico("S", 8, "SOURIAIT").
dico("S", 8, "SOURIANT").
dico("S", 8, "SOURIENT").
dico("S", 8, "SOURIIEZ").
dico("S", 8, "SOURIMES").
dico("S", 8, "SOURIONS").
dico("S", 8, "SOURIRAI").
dico("S", 8, "SOURIRAS").
dico("S", 8, "SOURIRES").
dico("S", 8, "SOURIREZ").
dico("S", 8, "SOURISSE").
dico("S", 8, "SOURITES").
dico("S", 8, "SOURNOIS").
dico("S", 8, "SOUSCRIS").
dico("S", 8, "SOUSCRIT").
dico("S", 8, "SOUSLIKS").
dico("S", 8, "SOUTACHA").
dico("S", 8, "SOUTACHE").
dico("S", 8, "SOUTANES").
dico("S", 8, "SOUTASSE").
dico("S", 8, "SOUTENEZ").
dico("S", 8, "SOUTENIR").
dico("S", 8, "SOUTENUE").
dico("S", 8, "SOUTENUS").
dico("S", 8, "SOUTIENS").
dico("S", 8, "SOUTIENT").
dico("S", 8, "SOUTIERS").
dico("S", 8, "SOUTIRAI").
dico("S", 8, "SOUTIRAS").
dico("S", 8, "SOUTIRAT").
dico("S", 8, "SOUTIREE").
dico("S", 8, "SOUTIRER").
dico("S", 8, "SOUTIRES").
dico("S", 8, "SOUTIREZ").
dico("S", 8, "SOUTRAGE").
dico("S", 8, "SOUVENEZ").
dico("S", 8, "SOUVENIR").
dico("S", 8, "SOUVENUE").
dico("S", 8, "SOUVENUS").
dico("S", 8, "SOUVIENS").
dico("S", 8, "SOUVIENT").
dico("S", 8, "SOUVLAKI").
dico("S", 8, "SOVKHOZE").
dico("S", 8, "SOYEUSES").
dico("S", 8, "SPACIEUX").
dico("S", 8, "SPADICES").
dico("S", 8, "SPAETZLI").
dico("S", 8, "SPALTERS").
dico("S", 8, "SPARDECK").
dico("S", 8, "SPARIDES").
dico("S", 8, "SPARKLET").
dico("S", 8, "SPATIALE").
dico("S", 8, "SPATIAUX").
dico("S", 8, "SPATULEE").
dico("S", 8, "SPATULES").
dico("S", 8, "SPEAKERS").
dico("S", 8, "SPECIALE").
dico("S", 8, "SPECIAUX").
dico("S", 8, "SPECIEUX").
dico("S", 8, "SPECIFIA").
dico("S", 8, "SPECIFIE").
dico("S", 8, "SPECIMEN").
dico("S", 8, "SPECTRAL").
dico("S", 8, "SPECTRES").
dico("S", 8, "SPECULAI").
dico("S", 8, "SPECULAS").
dico("S", 8, "SPECULAT").
dico("S", 8, "SPECULER").
dico("S", 8, "SPECULES").
dico("S", 8, "SPECULEZ").
dico("S", 8, "SPECULOS").
dico("S", 8, "SPECULUM").
dico("S", 8, "SPEECHES").
dico("S", 8, "SPEEDAIS").
dico("S", 8, "SPEEDAIT").
dico("S", 8, "SPEEDANT").
dico("S", 8, "SPEEDEES").
dico("S", 8, "SPEEDENT").
dico("S", 8, "SPEEDERA").
dico("S", 8, "SPEEDIEZ").
dico("S", 8, "SPEEDONS").
dico("S", 8, "SPEEDWAY").
dico("S", 8, "SPENCERS").
dico("S", 8, "SPERGULE").
dico("S", 8, "SPERMINE").
dico("S", 8, "SPETSNAZ").
dico("S", 8, "SPHACELE").
dico("S", 8, "SPHAIGNE").
dico("S", 8, "SPHERULE").
dico("S", 8, "SPHINGES").
dico("S", 8, "SPHYRENE").
dico("S", 8, "SPICULES").
dico("S", 8, "SPIEGELS").
dico("S", 8, "SPINALES").
dico("S", 8, "SPINELLE").
dico("S", 8, "SPINULES").
dico("S", 8, "SPIRACLE").
dico("S", 8, "SPIRALEE").
dico("S", 8, "SPIRALES").
dico("S", 8, "SPIRANTE").
dico("S", 8, "SPIRANTS").
dico("S", 8, "SPIRIFER").
dico("S", 8, "SPIRILLE").
dico("S", 8, "SPIRITES").
dico("S", 8, "SPIRORBE").
dico("S", 8, "SPITANTE").
dico("S", 8, "SPITANTS").
dico("S", 8, "SPITTANT").
dico("S", 8, "SPLENITE").
dico("S", 8, "SPLENIUS").
dico("S", 8, "SPOILERS").
dico("S", 8, "SPOLIAIS").
dico("S", 8, "SPOLIAIT").
dico("S", 8, "SPOLIANT").
dico("S", 8, "SPOLIEES").
dico("S", 8, "SPOLIENT").
dico("S", 8, "SPOLIERA").
dico("S", 8, "SPOLIIEZ").
dico("S", 8, "SPOLIONS").
dico("S", 8, "SPONDEES").
dico("S", 8, "SPONDIAS").
dico("S", 8, "SPONDYLE").
dico("S", 8, "SPONSORS").
dico("S", 8, "SPONTANE").
dico("S", 8, "SPOOLERS").
dico("S", 8, "SPORANGE").
dico("S", 8, "SPORIDIE").
dico("S", 8, "SPORTIFS").
dico("S", 8, "SPORTIVE").
dico("S", 8, "SPORTULE").
dico("S", 8, "SPORULAI").
dico("S", 8, "SPORULAS").
dico("S", 8, "SPORULAT").
dico("S", 8, "SPORULER").
dico("S", 8, "SPORULES").
dico("S", 8, "SPORULEZ").
dico("S", 8, "SPOUTNIK").
dico("S", 8, "SPRINGER").
dico("S", 8, "SPRINTAI").
dico("S", 8, "SPRINTAS").
dico("S", 8, "SPRINTAT").
dico("S", 8, "SPRINTER").
dico("S", 8, "SPRINTES").
dico("S", 8, "SPRINTEZ").
dico("S", 8, "SPUMANTE").
dico("S", 8, "SPUMEUSE").
dico("S", 8, "SQUALIDE").
dico("S", 8, "SQUAMATE").
dico("S", 8, "SQUAMEES").
dico("S", 8, "SQUAMEUX").
dico("S", 8, "SQUAMULE").
dico("S", 8, "SQUATINA").
dico("S", 8, "SQUATINE").
dico("S", 8, "SQUATTAI").
dico("S", 8, "SQUATTAS").
dico("S", 8, "SQUATTAT").
dico("S", 8, "SQUATTEE").
dico("S", 8, "SQUATTER").
dico("S", 8, "SQUATTES").
dico("S", 8, "SQUATTEZ").
dico("S", 8, "SQUEEZAI").
dico("S", 8, "SQUEEZAS").
dico("S", 8, "SQUEEZAT").
dico("S", 8, "SQUEEZEE").
dico("S", 8, "SQUEEZER").
dico("S", 8, "SQUEEZES").
dico("S", 8, "SQUEEZEZ").
dico("S", 8, "SQUILLES").
dico("S", 8, "SQUIRRES").
dico("S", 8, "SQUIRRHE").
dico("S", 8, "STABILES").
dico("S", 8, "STACCATI").
dico("S", 8, "STACCATO").
dico("S", 8, "STADIERE").
dico("S", 8, "STADIERS").
dico("S", 8, "STAFFAIS").
dico("S", 8, "STAFFAIT").
dico("S", 8, "STAFFANT").
dico("S", 8, "STAFFEES").
dico("S", 8, "STAFFENT").
dico("S", 8, "STAFFERA").
dico("S", 8, "STAFFEUR").
dico("S", 8, "STAFFIEZ").
dico("S", 8, "STAFFONS").
dico("S", 8, "STAGNAIS").
dico("S", 8, "STAGNAIT").
dico("S", 8, "STAGNANT").
dico("S", 8, "STAGNENT").
dico("S", 8, "STAGNERA").
dico("S", 8, "STAGNIEZ").
dico("S", 8, "STAGNONS").
dico("S", 8, "STAKNING").
dico("S", 8, "STAMINAL").
dico("S", 8, "STAMINEE").
dico("S", 8, "STAMINES").
dico("S", 8, "STANDARD").
dico("S", 8, "STANDING").
dico("S", 8, "STANNEUX").
dico("S", 8, "STARIETS").
dico("S", 8, "STARIFIA").
dico("S", 8, "STARIFIE").
dico("S", 8, "STARISAI").
dico("S", 8, "STARISAS").
dico("S", 8, "STARISAT").
dico("S", 8, "STARISEE").
dico("S", 8, "STARISER").
dico("S", 8, "STARISES").
dico("S", 8, "STARISEZ").
dico("S", 8, "STARKING").
dico("S", 8, "STAROSTE").
dico("S", 8, "STARTERS").
dico("S", 8, "STATERES").
dico("S", 8, "STATICES").
dico("S", 8, "STATINES").
dico("S", 8, "STATIONS").
dico("S", 8, "STATIQUE").
dico("S", 8, "STATISME").
dico("S", 8, "STATIVES").
dico("S", 8, "STATUAIS").
dico("S", 8, "STATUAIT").
dico("S", 8, "STATUANT").
dico("S", 8, "STATUEES").
dico("S", 8, "STATUENT").
dico("S", 8, "STATUERA").
dico("S", 8, "STATUFIA").
dico("S", 8, "STATUFIE").
dico("S", 8, "STATUIEZ").
dico("S", 8, "STATUONS").
dico("S", 8, "STATURES").
dico("S", 8, "STEAMERS").
dico("S", 8, "STEARATE").
dico("S", 8, "STEARINE").
dico("S", 8, "STEARYLE").
dico("S", 8, "STEATITE").
dico("S", 8, "STEATOME").
dico("S", 8, "STEATOSE").
dico("S", 8, "STEENBOK").
dico("S", 8, "STEEPLES").
dico("S", 8, "STEGOMYA").
dico("S", 8, "STELLAGE").
dico("S", 8, "STELLITE").
dico("S", 8, "STEMMATE").
dico("S", 8, "STENCILS").
dico("S", 8, "STENOPES").
dico("S", 8, "STENOSAI").
dico("S", 8, "STENOSAS").
dico("S", 8, "STENOSAT").
dico("S", 8, "STENOSEE").
dico("S", 8, "STENOSER").
dico("S", 8, "STENOSES").
dico("S", 8, "STENOSEZ").
dico("S", 8, "STENTORS").
dico("S", 8, "STEPPAGE").
dico("S", 8, "STEPPERS").
dico("S", 8, "STEPPEUR").
dico("S", 8, "STERAGES").
dico("S", 8, "STERAMES").
dico("S", 8, "STERASSE").
dico("S", 8, "STERATES").
dico("S", 8, "STERERAI").
dico("S", 8, "STERERAS").
dico("S", 8, "STEREREZ").
dico("S", 8, "STERFPUT").
dico("S", 8, "STERIDES").
dico("S", 8, "STERILES").
dico("S", 8, "STERILET").
dico("S", 8, "STERIONS").
dico("S", 8, "STERIQUE").
dico("S", 8, "STERLETS").
dico("S", 8, "STERLING").
dico("S", 8, "STERNALE").
dico("S", 8, "STERNAUX").
dico("S", 8, "STERNITE").
dico("S", 8, "STERNUMS").
dico("S", 8, "STEROIDE").
dico("S", 8, "STERTORS").
dico("S", 8, "STETSONS").
dico("S", 8, "STEWARDS").
dico("S", 8, "STHENIES").
dico("S", 8, "STIBIEES").
dico("S", 8, "STIBINES").
dico("S", 8, "STICKERS").
dico("S", 8, "STIGMATE").
dico("S", 8, "STILTONS").
dico("S", 8, "STIMULAI").
dico("S", 8, "STIMULAS").
dico("S", 8, "STIMULAT").
dico("S", 8, "STIMULEE").
dico("S", 8, "STIMULER").
dico("S", 8, "STIMULES").
dico("S", 8, "STIMULEZ").
dico("S", 8, "STIMULUS").
dico("S", 8, "STIPITEE").
dico("S", 8, "STIPITES").
dico("S", 8, "STIPULAI").
dico("S", 8, "STIPULAS").
dico("S", 8, "STIPULAT").
dico("S", 8, "STIPULEE").
dico("S", 8, "STIPULER").
dico("S", 8, "STIPULES").
dico("S", 8, "STIPULEZ").
dico("S", 8, "STOCKAGE").
dico("S", 8, "STOCKAIS").
dico("S", 8, "STOCKAIT").
dico("S", 8, "STOCKANT").
dico("S", 8, "STOCKEES").
dico("S", 8, "STOCKENT").
dico("S", 8, "STOCKERA").
dico("S", 8, "STOCKIEZ").
dico("S", 8, "STOCKONS").
dico("S", 8, "STOICIEN").
dico("S", 8, "STOIQUES").
dico("S", 8, "STOMACAL").
dico("S", 8, "STOMATES").
dico("S", 8, "STOMATOS").
dico("S", 8, "STOMISEE").
dico("S", 8, "STOMISES").
dico("S", 8, "STOMOXES").
dico("S", 8, "STOPPAGE").
dico("S", 8, "STOPPAIS").
dico("S", 8, "STOPPAIT").
dico("S", 8, "STOPPANT").
dico("S", 8, "STOPPEES").
dico("S", 8, "STOPPENT").
dico("S", 8, "STOPPERA").
dico("S", 8, "STOPPEUR").
dico("S", 8, "STOPPIEZ").
dico("S", 8, "STOPPONS").
dico("S", 8, "STORISTE").
dico("S", 8, "STOTINKA").
dico("S", 8, "STOTINKI").
dico("S", 8, "STRADIOT").
dico("S", 8, "STRASSES").
dico("S", 8, "STRATEGE").
dico("S", 8, "STRESSAI").
dico("S", 8, "STRESSAS").
dico("S", 8, "STRESSAT").
dico("S", 8, "STRESSEE").
dico("S", 8, "STRESSER").
dico("S", 8, "STRESSES").
dico("S", 8, "STRESSEZ").
dico("S", 8, "STRETCHS").
dico("S", 8, "STRETTES").
dico("S", 8, "STRIAMES").
dico("S", 8, "STRIASSE").
dico("S", 8, "STRIATES").
dico("S", 8, "STRICTES").
dico("S", 8, "STRIDENT").
dico("S", 8, "STRIDORS").
dico("S", 8, "STRIDULA").
dico("S", 8, "STRIDULE").
dico("S", 8, "STRIERAI").
dico("S", 8, "STRIERAS").
dico("S", 8, "STRIEREZ").
dico("S", 8, "STRIGIDE").
dico("S", 8, "STRIGILE").
dico("S", 8, "STRIIONS").
dico("S", 8, "STRIPAGE").
dico("S", 8, "STRIPPAI").
dico("S", 8, "STRIPPAS").
dico("S", 8, "STRIPPAT").
dico("S", 8, "STRIPPEE").
dico("S", 8, "STRIPPER").
dico("S", 8, "STRIPPES").
dico("S", 8, "STRIPPEZ").
dico("S", 8, "STRIURES").
dico("S", 8, "STROBILE").
dico("S", 8, "STROMBES").
dico("S", 8, "STRONGLE").
dico("S", 8, "STROPHES").
dico("S", 8, "STRUDELS").
dico("S", 8, "STUCAGES").
dico("S", 8, "STUDENTS").
dico("S", 8, "STUDETTE").
dico("S", 8, "STUDIEUX").
dico("S", 8, "STUPEFIA").
dico("S", 8, "STUPEFIE").
dico("S", 8, "STUPEURS").
dico("S", 8, "STUPIDES").
dico("S", 8, "STUQUAIS").
dico("S", 8, "STUQUAIT").
dico("S", 8, "STUQUANT").
dico("S", 8, "STUQUEES").
dico("S", 8, "STUQUENT").
dico("S", 8, "STUQUERA").
dico("S", 8, "STUQUIEZ").
dico("S", 8, "STUQUONS").
dico("S", 8, "STURNIDE").
dico("S", 8, "STYLAMES").
dico("S", 8, "STYLASSE").
dico("S", 8, "STYLATES").
dico("S", 8, "STYLERAI").
dico("S", 8, "STYLERAS").
dico("S", 8, "STYLEREZ").
dico("S", 8, "STYLIONS").
dico("S", 8, "STYLIQUE").
dico("S", 8, "STYLISAI").
dico("S", 8, "STYLISAS").
dico("S", 8, "STYLISAT").
dico("S", 8, "STYLISEE").
dico("S", 8, "STYLISER").
dico("S", 8, "STYLISES").
dico("S", 8, "STYLISEZ").
dico("S", 8, "STYLISME").
dico("S", 8, "STYLISTE").
dico("S", 8, "STYLITES").
dico("S", 8, "STYLOIDE").
dico("S", 8, "STYRENES").
dico("S", 8, "SUASSENT").
dico("S", 8, "SUASSIEZ").
dico("S", 8, "SUAVITES").
dico("S", 8, "SUBAIGUE").
dico("S", 8, "SUBAIGUS").
dico("S", 8, "SUBALPIN").
dico("S", 8, "SUBARIDE").
dico("S", 8, "SUBEREUX").
dico("S", 8, "SUBERINE").
dico("S", 8, "SUBIRAIS").
dico("S", 8, "SUBIRAIT").
dico("S", 8, "SUBIRENT").
dico("S", 8, "SUBIRIEZ").
dico("S", 8, "SUBIRONS").
dico("S", 8, "SUBIRONT").
dico("S", 8, "SUBISSES").
dico("S", 8, "SUBISSEZ").
dico("S", 8, "SUBJUGUA").
dico("S", 8, "SUBJUGUE").
dico("S", 8, "SUBLAMES").
dico("S", 8, "SUBLASSE").
dico("S", 8, "SUBLATES").
dico("S", 8, "SUBLERAI").
dico("S", 8, "SUBLERAS").
dico("S", 8, "SUBLEREZ").
dico("S", 8, "SUBLIMAI").
dico("S", 8, "SUBLIMAS").
dico("S", 8, "SUBLIMAT").
dico("S", 8, "SUBLIMEE").
dico("S", 8, "SUBLIMER").
dico("S", 8, "SUBLIMES").
dico("S", 8, "SUBLIMEZ").
dico("S", 8, "SUBLIONS").
dico("S", 8, "SUBMERGE").
dico("S", 8, "SUBODORA").
dico("S", 8, "SUBODORE").
dico("S", 8, "SUBORNAI").
dico("S", 8, "SUBORNAS").
dico("S", 8, "SUBORNAT").
dico("S", 8, "SUBORNEE").
dico("S", 8, "SUBORNER").
dico("S", 8, "SUBORNES").
dico("S", 8, "SUBORNEZ").
dico("S", 8, "SUBPOENA").
dico("S", 8, "SUBROGEA").
dico("S", 8, "SUBROGEE").
dico("S", 8, "SUBROGER").
dico("S", 8, "SUBROGES").
dico("S", 8, "SUBROGEZ").
dico("S", 8, "SUBSIDES").
dico("S", 8, "SUBSIDIA").
dico("S", 8, "SUBSIDIE").
dico("S", 8, "SUBSISTA").
dico("S", 8, "SUBSISTE").
dico("S", 8, "SUBSTRAT").
dico("S", 8, "SUBSUMAI").
dico("S", 8, "SUBSUMAS").
dico("S", 8, "SUBSUMAT").
dico("S", 8, "SUBSUMEE").
dico("S", 8, "SUBSUMER").
dico("S", 8, "SUBSUMES").
dico("S", 8, "SUBSUMEZ").
dico("S", 8, "SUBTILES").
dico("S", 8, "SUBULEES").
dico("S", 8, "SUBVENEZ").
dico("S", 8, "SUBVENIR").
dico("S", 8, "SUBVERTI").
dico("S", 8, "SUBVIENS").
dico("S", 8, "SUBVIENT").
dico("S", 8, "SUCAIENT").
dico("S", 8, "SUCASSES").
dico("S", 8, "SUCCEDAI").
dico("S", 8, "SUCCEDAS").
dico("S", 8, "SUCCEDAT").
dico("S", 8, "SUCCEDER").
dico("S", 8, "SUCCEDES").
dico("S", 8, "SUCCEDEZ").
dico("S", 8, "SUCCINCT").
dico("S", 8, "SUCCIONS").
dico("S", 8, "SUCCOMBA").
dico("S", 8, "SUCCOMBE").
dico("S", 8, "SUCCUBES").
dico("S", 8, "SUCEMENT").
dico("S", 8, "SUCEPINS").
dico("S", 8, "SUCERAIS").
dico("S", 8, "SUCERAIT").
dico("S", 8, "SUCERENT").
dico("S", 8, "SUCERIEZ").
dico("S", 8, "SUCERONS").
dico("S", 8, "SUCERONT").
dico("S", 8, "SUCETTES").
dico("S", 8, "SUCEUSES").
dico("S", 8, "SUCOTAIS").
dico("S", 8, "SUCOTAIT").
dico("S", 8, "SUCOTANT").
dico("S", 8, "SUCOTEES").
dico("S", 8, "SUCOTENT").
dico("S", 8, "SUCOTERA").
dico("S", 8, "SUCOTIEZ").
dico("S", 8, "SUCOTONS").
dico("S", 8, "SUCRAGES").
dico("S", 8, "SUCRAMES").
dico("S", 8, "SUCRANTE").
dico("S", 8, "SUCRANTS").
dico("S", 8, "SUCRASES").
dico("S", 8, "SUCRASSE").
dico("S", 8, "SUCRATES").
dico("S", 8, "SUCRERAI").
dico("S", 8, "SUCRERAS").
dico("S", 8, "SUCREREZ").
dico("S", 8, "SUCRERIE").
dico("S", 8, "SUCRETTE").
dico("S", 8, "SUCRIERE").
dico("S", 8, "SUCRIERS").
dico("S", 8, "SUCRINES").
dico("S", 8, "SUCRIONS").
dico("S", 8, "SUDATION").
dico("S", 8, "SUDISTES").
dico("S", 8, "SUDORALE").
dico("S", 8, "SUDORAUX").
dico("S", 8, "SUEDINES").
dico("S", 8, "SUEDOISE").
dico("S", 8, "SUERIONS").
dico("S", 8, "SUFFETES").
dico("S", 8, "SUFFIMES").
dico("S", 8, "SUFFIRAI").
dico("S", 8, "SUFFIRAS").
dico("S", 8, "SUFFIREZ").
dico("S", 8, "SUFFISES").
dico("S", 8, "SUFFISEZ").
dico("S", 8, "SUFFISSE").
dico("S", 8, "SUFFITES").
dico("S", 8, "SUFFIXAI").
dico("S", 8, "SUFFIXAL").
dico("S", 8, "SUFFIXAS").
dico("S", 8, "SUFFIXAT").
dico("S", 8, "SUFFIXEE").
dico("S", 8, "SUFFIXER").
dico("S", 8, "SUFFIXES").
dico("S", 8, "SUFFIXEZ").
dico("S", 8, "SUFFOQUA").
dico("S", 8, "SUFFOQUE").
dico("S", 8, "SUFFRAGE").
dico("S", 8, "SUFISMES").
dico("S", 8, "SUGGERAI").
dico("S", 8, "SUGGERAS").
dico("S", 8, "SUGGERAT").
dico("S", 8, "SUGGEREE").
dico("S", 8, "SUGGERER").
dico("S", 8, "SUGGERES").
dico("S", 8, "SUGGEREZ").
dico("S", 8, "SUICIDAI").
dico("S", 8, "SUICIDAS").
dico("S", 8, "SUICIDAT").
dico("S", 8, "SUICIDEE").
dico("S", 8, "SUICIDER").
dico("S", 8, "SUICIDES").
dico("S", 8, "SUICIDEZ").
dico("S", 8, "SUIFAMES").
dico("S", 8, "SUIFASSE").
dico("S", 8, "SUIFATES").
dico("S", 8, "SUIFERAI").
dico("S", 8, "SUIFERAS").
dico("S", 8, "SUIFEREZ").
dico("S", 8, "SUIFFAIS").
dico("S", 8, "SUIFFAIT").
dico("S", 8, "SUIFFANT").
dico("S", 8, "SUIFFEES").
dico("S", 8, "SUIFFENT").
dico("S", 8, "SUIFFERA").
dico("S", 8, "SUIFFEUX").
dico("S", 8, "SUIFFIEZ").
dico("S", 8, "SUIFFONS").
dico("S", 8, "SUIFIONS").
dico("S", 8, "SUIFORME").
dico("S", 8, "SUINTAIS").
dico("S", 8, "SUINTAIT").
dico("S", 8, "SUINTANT").
dico("S", 8, "SUINTEES").
dico("S", 8, "SUINTENT").
dico("S", 8, "SUINTERA").
dico("S", 8, "SUINTIEZ").
dico("S", 8, "SUINTINE").
dico("S", 8, "SUINTONS").
dico("S", 8, "SUIVANTE").
dico("S", 8, "SUIVANTS").
dico("S", 8, "SUIVEURS").
dico("S", 8, "SUIVEUSE").
dico("S", 8, "SUIVIMES").
dico("S", 8, "SUIVIONS").
dico("S", 8, "SUIVISME").
dico("S", 8, "SUIVISSE").
dico("S", 8, "SUIVISTE").
dico("S", 8, "SUIVITES").
dico("S", 8, "SUIVRAIS").
dico("S", 8, "SUIVRAIT").
dico("S", 8, "SUIVRIEZ").
dico("S", 8, "SUIVRONS").
dico("S", 8, "SUIVRONT").
dico("S", 8, "SUJETION").
dico("S", 8, "SUJETTES").
dico("S", 8, "SUKIYAKI").
dico("S", 8, "SULFATAI").
dico("S", 8, "SULFATAS").
dico("S", 8, "SULFATAT").
dico("S", 8, "SULFATEE").
dico("S", 8, "SULFATER").
dico("S", 8, "SULFATES").
dico("S", 8, "SULFATEZ").
dico("S", 8, "SULFITAI").
dico("S", 8, "SULFITAS").
dico("S", 8, "SULFITAT").
dico("S", 8, "SULFITEE").
dico("S", 8, "SULFITER").
dico("S", 8, "SULFITES").
dico("S", 8, "SULFITEZ").
dico("S", 8, "SULFONAI").
dico("S", 8, "SULFONAS").
dico("S", 8, "SULFONAT").
dico("S", 8, "SULFONEE").
dico("S", 8, "SULFONER").
dico("S", 8, "SULFONES").
dico("S", 8, "SULFONEZ").
dico("S", 8, "SULFOSEL").
dico("S", 8, "SULFURAI").
dico("S", 8, "SULFURAS").
dico("S", 8, "SULFURAT").
dico("S", 8, "SULFUREE").
dico("S", 8, "SULFURER").
dico("S", 8, "SULFURES").
dico("S", 8, "SULFUREZ").
dico("S", 8, "SULTANAT").
dico("S", 8, "SULTANES").
dico("S", 8, "SUMERIEN").
dico("S", 8, "SUMOTORI").
dico("S", 8, "SUNLIGHT").
dico("S", 8, "SUNNISME").
dico("S", 8, "SUNNITES").
dico("S", 8, "SUPAIENT").
dico("S", 8, "SUPASSES").
dico("S", 8, "SUPERAIS").
dico("S", 8, "SUPERAIT").
dico("S", 8, "SUPERBES").
dico("S", 8, "SUPERENT").
dico("S", 8, "SUPERFIN").
dico("S", 8, "SUPERFLU").
dico("S", 8, "SUPERIEZ").
dico("S", 8, "SUPERMAN").
dico("S", 8, "SUPERMEN").
dico("S", 8, "SUPERONS").
dico("S", 8, "SUPERONT").
dico("S", 8, "SUPPLEAI").
dico("S", 8, "SUPPLEAS").
dico("S", 8, "SUPPLEAT").
dico("S", 8, "SUPPLEEE").
dico("S", 8, "SUPPLEER").
dico("S", 8, "SUPPLEES").
dico("S", 8, "SUPPLEEZ").
dico("S", 8, "SUPPLIAI").
dico("S", 8, "SUPPLIAS").
dico("S", 8, "SUPPLIAT").
dico("S", 8, "SUPPLICE").
dico("S", 8, "SUPPLIEE").
dico("S", 8, "SUPPLIER").
dico("S", 8, "SUPPLIES").
dico("S", 8, "SUPPLIEZ").
dico("S", 8, "SUPPORTA").
dico("S", 8, "SUPPORTE").
dico("S", 8, "SUPPORTS").
dico("S", 8, "SUPPOSAI").
dico("S", 8, "SUPPOSAS").
dico("S", 8, "SUPPOSAT").
dico("S", 8, "SUPPOSEE").
dico("S", 8, "SUPPOSER").
dico("S", 8, "SUPPOSES").
dico("S", 8, "SUPPOSEZ").
dico("S", 8, "SUPPRIMA").
dico("S", 8, "SUPPRIME").
dico("S", 8, "SUPPURAI").
dico("S", 8, "SUPPURAS").
dico("S", 8, "SUPPURAT").
dico("S", 8, "SUPPUREE").
dico("S", 8, "SUPPURER").
dico("S", 8, "SUPPURES").
dico("S", 8, "SUPPUREZ").
dico("S", 8, "SUPPUTAI").
dico("S", 8, "SUPPUTAS").
dico("S", 8, "SUPPUTAT").
dico("S", 8, "SUPPUTEE").
dico("S", 8, "SUPPUTER").
dico("S", 8, "SUPPUTES").
dico("S", 8, "SUPPUTEZ").
dico("S", 8, "SUPREMES").
dico("S", 8, "SUPREMUM").
dico("S", 8, "SURACTIF").
dico("S", 8, "SURAIGUE").
dico("S", 8, "SURAIGUS").
dico("S", 8, "SURANNEE").
dico("S", 8, "SURANNES").
dico("S", 8, "SURARMAI").
dico("S", 8, "SURARMAS").
dico("S", 8, "SURARMAT").
dico("S", 8, "SURARMEE").
dico("S", 8, "SURARMER").
dico("S", 8, "SURARMES").
dico("S", 8, "SURARMEZ").
dico("S", 8, "SURBOOKE").
dico("S", 8, "SURBOUMS").
dico("S", 8, "SURBOUTS").
dico("S", 8, "SURCHOIX").
dico("S", 8, "SURCOTAI").
dico("S", 8, "SURCOTAS").
dico("S", 8, "SURCOTAT").
dico("S", 8, "SURCOTEE").
dico("S", 8, "SURCOTER").
dico("S", 8, "SURCOTES").
dico("S", 8, "SURCOTEZ").
dico("S", 8, "SURCOUPA").
dico("S", 8, "SURCOUPE").
dico("S", 8, "SURCOUTS").
dico("S", 8, "SURCROIT").
dico("S", 8, "SURCUITS").
dico("S", 8, "SURDENTS").
dico("S", 8, "SURDITES").
dico("S", 8, "SURDORAI").
dico("S", 8, "SURDORAS").
dico("S", 8, "SURDORAT").
dico("S", 8, "SURDOREE").
dico("S", 8, "SURDORER").
dico("S", 8, "SURDORES").
dico("S", 8, "SURDOREZ").
dico("S", 8, "SURDOSAI").
dico("S", 8, "SURDOSAS").
dico("S", 8, "SURDOSAT").
dico("S", 8, "SURDOSEE").
dico("S", 8, "SURDOSER").
dico("S", 8, "SURDOSES").
dico("S", 8, "SURDOSEZ").
dico("S", 8, "SURDOUEE").
dico("S", 8, "SURDOUES").
dico("S", 8, "SURELEVA").
dico("S", 8, "SURELEVE").
dico("S", 8, "SURELLES").
dico("S", 8, "SUREMENT").
dico("S", 8, "SURETTES").
dico("S", 8, "SURFACAI").
dico("S", 8, "SURFACAS").
dico("S", 8, "SURFACAT").
dico("S", 8, "SURFACEE").
dico("S", 8, "SURFACER").
dico("S", 8, "SURFACES").
dico("S", 8, "SURFACEZ").
dico("S", 8, "SURFAIRE").
dico("S", 8, "SURFAITE").
dico("S", 8, "SURFAITS").
dico("S", 8, "SURFAMES").
dico("S", 8, "SURFASSE").
dico("S", 8, "SURFATES").
dico("S", 8, "SURFERAI").
dico("S", 8, "SURFERAS").
dico("S", 8, "SURFEREZ").
dico("S", 8, "SURFEURS").
dico("S", 8, "SURFEUSE").
dico("S", 8, "SURFILAI").
dico("S", 8, "SURFILAS").
dico("S", 8, "SURFILAT").
dico("S", 8, "SURFILEE").
dico("S", 8, "SURFILER").
dico("S", 8, "SURFILES").
dico("S", 8, "SURFILEZ").
dico("S", 8, "SURFIMES").
dico("S", 8, "SURFINES").
dico("S", 8, "SURFIONS").
dico("S", 8, "SURFISSE").
dico("S", 8, "SURFITES").
dico("S", 8, "SURFONDU").
dico("S", 8, "SURGELAI").
dico("S", 8, "SURGELAS").
dico("S", 8, "SURGELAT").
dico("S", 8, "SURGELEE").
dico("S", 8, "SURGELER").
dico("S", 8, "SURGELES").
dico("S", 8, "SURGELEZ").
dico("S", 8, "SURGEONS").
dico("S", 8, "SURGIMES").
dico("S", 8, "SURGIRAI").
dico("S", 8, "SURGIRAS").
dico("S", 8, "SURGIREZ").
dico("S", 8, "SURGISSE").
dico("S", 8, "SURGITES").
dico("S", 8, "SURHOMME").
dico("S", 8, "SURICATE").
dico("S", 8, "SURIKATE").
dico("S", 8, "SURINAIS").
dico("S", 8, "SURINAIT").
dico("S", 8, "SURINANT").
dico("S", 8, "SURINEES").
dico("S", 8, "SURINENT").
dico("S", 8, "SURINERA").
dico("S", 8, "SURINIEZ").
dico("S", 8, "SURINONS").
dico("S", 8, "SURIRAIS").
dico("S", 8, "SURIRAIT").
dico("S", 8, "SURIRENT").
dico("S", 8, "SURIRIEZ").
dico("S", 8, "SURIRONS").
dico("S", 8, "SURIRONT").
dico("S", 8, "SURISSES").
dico("S", 8, "SURISSEZ").
dico("S", 8, "SURJALAI").
dico("S", 8, "SURJALAS").
dico("S", 8, "SURJALAT").
dico("S", 8, "SURJALEE").
dico("S", 8, "SURJALER").
dico("S", 8, "SURJALES").
dico("S", 8, "SURJALEZ").
dico("S", 8, "SURJETAI").
dico("S", 8, "SURJETAS").
dico("S", 8, "SURJETAT").
dico("S", 8, "SURJETEE").
dico("S", 8, "SURJETER").
dico("S", 8, "SURJETES").
dico("S", 8, "SURJETEZ").
dico("S", 8, "SURJETTE").
dico("S", 8, "SURLIAIS").
dico("S", 8, "SURLIAIT").
dico("S", 8, "SURLIANT").
dico("S", 8, "SURLIEES").
dico("S", 8, "SURLIENT").
dico("S", 8, "SURLIERA").
dico("S", 8, "SURLIGNA").
dico("S", 8, "SURLIGNE").
dico("S", 8, "SURLIIEZ").
dico("S", 8, "SURLIONS").
dico("S", 8, "SURLIURE").
dico("S", 8, "SURLONGE").
dico("S", 8, "SURLOUAI").
dico("S", 8, "SURLOUAS").
dico("S", 8, "SURLOUAT").
dico("S", 8, "SURLOUEE").
dico("S", 8, "SURLOUER").
dico("S", 8, "SURLOUES").
dico("S", 8, "SURLOUEZ").
dico("S", 8, "SURLOYER").
dico("S", 8, "SURMENAI").
dico("S", 8, "SURMENAS").
dico("S", 8, "SURMENAT").
dico("S", 8, "SURMENEE").
dico("S", 8, "SURMENER").
dico("S", 8, "SURMENES").
dico("S", 8, "SURMENEZ").
dico("S", 8, "SURMONTA").
dico("S", 8, "SURMONTE").
dico("S", 8, "SURMOULA").
dico("S", 8, "SURMOULE").
dico("S", 8, "SURMULET").
dico("S", 8, "SURMULOT").
dico("S", 8, "SURNAGEA").
dico("S", 8, "SURNAGER").
dico("S", 8, "SURNAGES").
dico("S", 8, "SURNAGEZ").
dico("S", 8, "SURNOMMA").
dico("S", 8, "SURNOMME").
dico("S", 8, "SURNOTAI").
dico("S", 8, "SURNOTAS").
dico("S", 8, "SURNOTAT").
dico("S", 8, "SURNOTEE").
dico("S", 8, "SURNOTER").
dico("S", 8, "SURNOTES").
dico("S", 8, "SURNOTEZ").
dico("S", 8, "SUROFFRE").
dico("S", 8, "SUROXYDA").
dico("S", 8, "SUROXYDE").
dico("S", 8, "SURPAIES").
dico("S", 8, "SURPASSA").
dico("S", 8, "SURPASSE").
dico("S", 8, "SURPATTE").
dico("S", 8, "SURPAYAI").
dico("S", 8, "SURPAYAS").
dico("S", 8, "SURPAYAT").
dico("S", 8, "SURPAYEE").
dico("S", 8, "SURPAYER").
dico("S", 8, "SURPAYES").
dico("S", 8, "SURPAYEZ").
dico("S", 8, "SURPECHE").
dico("S", 8, "SURPIQUA").
dico("S", 8, "SURPIQUE").
dico("S", 8, "SURPLACE").
dico("S", 8, "SURPLOMB").
dico("S", 8, "SURPOIDS").
dico("S", 8, "SURPREND").
dico("S", 8, "SURPRIME").
dico("S", 8, "SURPRISE").
dico("S", 8, "SURREELS").
dico("S", 8, "SURRENAL").
dico("S", 8, "SURSAUTA").
dico("S", 8, "SURSAUTE").
dico("S", 8, "SURSAUTS").
dico("S", 8, "SURSEMAI").
dico("S", 8, "SURSEMAS").
dico("S", 8, "SURSEMAT").
dico("S", 8, "SURSEMEE").
dico("S", 8, "SURSEMER").
dico("S", 8, "SURSEMES").
dico("S", 8, "SURSEMEZ").
dico("S", 8, "SURSEOIR").
dico("S", 8, "SURSIMES").
dico("S", 8, "SURSISES").
dico("S", 8, "SURSISSE").
dico("S", 8, "SURSITES").
dico("S", 8, "SURSOIES").
dico("S", 8, "SURSOYEZ").
dico("S", 8, "SURSTOCK").
dico("S", 8, "SURTAXAI").
dico("S", 8, "SURTAXAS").
dico("S", 8, "SURTAXAT").
dico("S", 8, "SURTAXEE").
dico("S", 8, "SURTAXER").
dico("S", 8, "SURTAXES").
dico("S", 8, "SURTAXEZ").
dico("S", 8, "SURTEMPS").
dico("S", 8, "SURTITRA").
dico("S", 8, "SURTITRE").
dico("S", 8, "SURTOILE").
dico("S", 8, "SURTONDE").
dico("S", 8, "SURTONDS").
dico("S", 8, "SURTONDU").
dico("S", 8, "SURTONTE").
dico("S", 8, "SURTOUTS").
dico("S", 8, "SURVECUS").
dico("S", 8, "SURVECUT").
dico("S", 8, "SURVENDE").
dico("S", 8, "SURVENDS").
dico("S", 8, "SURVENDU").
dico("S", 8, "SURVENEZ").
dico("S", 8, "SURVENIR").
dico("S", 8, "SURVENTA").
dico("S", 8, "SURVENTE").
dico("S", 8, "SURVENUE").
dico("S", 8, "SURVENUS").
dico("S", 8, "SURVESTE").
dico("S", 8, "SURVIENS").
dico("S", 8, "SURVIENT").
dico("S", 8, "SURVIRAI").
dico("S", 8, "SURVIRAS").
dico("S", 8, "SURVIRAT").
dico("S", 8, "SURVIRER").
dico("S", 8, "SURVIRES").
dico("S", 8, "SURVIREZ").
dico("S", 8, "SURVIVES").
dico("S", 8, "SURVIVEZ").
dico("S", 8, "SURVIVRA").
dico("S", 8, "SURVIVRE").
dico("S", 8, "SURVOLAI").
dico("S", 8, "SURVOLAS").
dico("S", 8, "SURVOLAT").
dico("S", 8, "SURVOLEE").
dico("S", 8, "SURVOLER").
dico("S", 8, "SURVOLES").
dico("S", 8, "SURVOLEZ").
dico("S", 8, "SURVOLTA").
dico("S", 8, "SURVOLTE").
dico("S", 8, "SUSCITAI").
dico("S", 8, "SUSCITAS").
dico("S", 8, "SUSCITAT").
dico("S", 8, "SUSCITEE").
dico("S", 8, "SUSCITER").
dico("S", 8, "SUSCITES").
dico("S", 8, "SUSCITEZ").
dico("S", 8, "SUSDITES").
dico("S", 8, "SUSNOMME").
dico("S", 8, "SUSPECTA").
dico("S", 8, "SUSPECTE").
dico("S", 8, "SUSPECTS").
dico("S", 8, "SUSPENDE").
dico("S", 8, "SUSPENDS").
dico("S", 8, "SUSPENDU").
dico("S", 8, "SUSPENSE").
dico("S", 8, "SUSPENTE").
dico("S", 8, "SUSSIONS").
dico("S", 8, "SUSTENTA").
dico("S", 8, "SUSTENTE").
dico("S", 8, "SUSURRAI").
dico("S", 8, "SUSURRAS").
dico("S", 8, "SUSURRAT").
dico("S", 8, "SUSURREE").
dico("S", 8, "SUSURRER").
dico("S", 8, "SUSURRES").
dico("S", 8, "SUSURREZ").
dico("S", 8, "SUSVISEE").
dico("S", 8, "SUSVISES").
dico("S", 8, "SUTURAIS").
dico("S", 8, "SUTURAIT").
dico("S", 8, "SUTURALE").
dico("S", 8, "SUTURANT").
dico("S", 8, "SUTURAUX").
dico("S", 8, "SUTUREES").
dico("S", 8, "SUTURENT").
dico("S", 8, "SUTURERA").
dico("S", 8, "SUTURIEZ").
dico("S", 8, "SUTURONS").
dico("S", 8, "SUZERAIN").
dico("S", 8, "SUZETTES").
dico("S", 8, "SVASTIKA").
dico("S", 8, "SWAHELIE").
dico("S", 8, "SWAHELIS").
dico("S", 8, "SWAHILIE").
dico("S", 8, "SWAHILIS").
dico("S", 8, "SWAPPAIS").
dico("S", 8, "SWAPPAIT").
dico("S", 8, "SWAPPANT").
dico("S", 8, "SWAPPEES").
dico("S", 8, "SWAPPENT").
dico("S", 8, "SWAPPERA").
dico("S", 8, "SWAPPIEZ").
dico("S", 8, "SWAPPONS").
dico("S", 8, "SWASTIKA").
dico("S", 8, "SWEATERS").
dico("S", 8, "SWINGUAI").
dico("S", 8, "SWINGUAS").
dico("S", 8, "SWINGUAT").
dico("S", 8, "SWINGUER").
dico("S", 8, "SWINGUES").
dico("S", 8, "SWINGUEZ").
dico("S", 8, "SWITCHAI").
dico("S", 8, "SWITCHAS").
dico("S", 8, "SWITCHAT").
dico("S", 8, "SWITCHEE").
dico("S", 8, "SWITCHER").
dico("S", 8, "SWITCHES").
dico("S", 8, "SWITCHEZ").
dico("S", 8, "SYBARITE").
dico("S", 8, "SYCOMORE").
dico("S", 8, "SYENITES").
dico("S", 8, "SYLLABES").
dico("S", 8, "SYLLABUS").
dico("S", 8, "SYLLEPSE").
dico("S", 8, "SYLPHIDE").
dico("S", 8, "SYLVAINE").
dico("S", 8, "SYLVAINS").
dico("S", 8, "SYLVANER").
dico("S", 8, "SYLVIIDE").
dico("S", 8, "SYLVITES").
dico("S", 8, "SYMBIOSE").
dico("S", 8, "SYMBIOTE").
dico("S", 8, "SYMBOLES").
dico("S", 8, "SYMETRIE").
dico("S", 8, "SYMPHYSE").
dico("S", 8, "SYMPTOME").
dico("S", 8, "SYNAPSES").
dico("S", 8, "SYNCHROS").
dico("S", 8, "SYNCOPAI").
dico("S", 8, "SYNCOPAL").
dico("S", 8, "SYNCOPAS").
dico("S", 8, "SYNCOPAT").
dico("S", 8, "SYNCOPEE").
dico("S", 8, "SYNCOPER").
dico("S", 8, "SYNCOPES").
dico("S", 8, "SYNCOPEZ").
dico("S", 8, "SYNDERME").
dico("S", 8, "SYNDICAL").
dico("S", 8, "SYNDICAT").
dico("S", 8, "SYNDIQUA").
dico("S", 8, "SYNDIQUE").
dico("S", 8, "SYNDROME").
dico("S", 8, "SYNECHIE").
dico("S", 8, "SYNERESE").
dico("S", 8, "SYNERGIE").
dico("S", 8, "SYNODALE").
dico("S", 8, "SYNODAUX").
dico("S", 8, "SYNONYME").
dico("S", 8, "SYNOPSES").
dico("S", 8, "SYNOPSIE").
dico("S", 8, "SYNOPSIS").
dico("S", 8, "SYNOVIAL").
dico("S", 8, "SYNOVIES").
dico("S", 8, "SYNOVITE").
dico("S", 8, "SYNTAGME").
dico("S", 8, "SYNTAXES").
dico("S", 8, "SYNTHESE").
dico("S", 8, "SYNTONES").
dico("S", 8, "SYNTONIE").
dico("S", 8, "SYPHILIS").
dico("S", 8, "SYRIAQUE").
dico("S", 8, "SYRIENNE").
dico("S", 8, "SYRINGES").
dico("S", 8, "SYRPHIDE").
dico("S", 8, "SYSTEMES").
dico("S", 8, "SYSTOLES").
dico("S", 8, "SYSTYLES").
dico("S", 8, "SYZYGIES").
dico("S", 8, "SZLACHTA").
