dico("S", 9, "SABEENNES").
dico("S", 9, "SABEISMES").
dico("S", 9, "SABLAIENT").
dico("S", 9, "SABLASSES").
dico("S", 9, "SABLERAIS").
dico("S", 9, "SABLERAIT").
dico("S", 9, "SABLERENT").
dico("S", 9, "SABLERIES").
dico("S", 9, "SABLERIEZ").
dico("S", 9, "SABLERONS").
dico("S", 9, "SABLERONT").
dico("S", 9, "SABLEUSES").
dico("S", 9, "SABLIERES").
dico("S", 9, "SABLONNAI").
dico("S", 9, "SABLONNAS").
dico("S", 9, "SABLONNAT").
dico("S", 9, "SABLONNEE").
dico("S", 9, "SABLONNER").
dico("S", 9, "SABLONNES").
dico("S", 9, "SABLONNEZ").
dico("S", 9, "SABORDAGE").
dico("S", 9, "SABORDAIS").
dico("S", 9, "SABORDAIT").
dico("S", 9, "SABORDANT").
dico("S", 9, "SABORDEES").
dico("S", 9, "SABORDENT").
dico("S", 9, "SABORDERA").
dico("S", 9, "SABORDIEZ").
dico("S", 9, "SABORDONS").
dico("S", 9, "SABOTAGES").
dico("S", 9, "SABOTAMES").
dico("S", 9, "SABOTASSE").
dico("S", 9, "SABOTATES").
dico("S", 9, "SABOTERAI").
dico("S", 9, "SABOTERAS").
dico("S", 9, "SABOTEREZ").
dico("S", 9, "SABOTERIE").
dico("S", 9, "SABOTEURS").
dico("S", 9, "SABOTEUSE").
dico("S", 9, "SABOTIERE").
dico("S", 9, "SABOTIERS").
dico("S", 9, "SABOTIONS").
dico("S", 9, "SABOULAIS").
dico("S", 9, "SABOULAIT").
dico("S", 9, "SABOULANT").
dico("S", 9, "SABOULEES").
dico("S", 9, "SABOULENT").
dico("S", 9, "SABOULERA").
dico("S", 9, "SABOULIEZ").
dico("S", 9, "SABOULONS").
dico("S", 9, "SABRAIENT").
dico("S", 9, "SABRASSES").
dico("S", 9, "SABRERAIS").
dico("S", 9, "SABRERAIT").
dico("S", 9, "SABRERENT").
dico("S", 9, "SABRERIEZ").
dico("S", 9, "SABRERONS").
dico("S", 9, "SABRERONT").
dico("S", 9, "SABREUSES").
dico("S", 9, "SABURRALE").
dico("S", 9, "SABURRAUX").
dico("S", 9, "SACCADAIS").
dico("S", 9, "SACCADAIT").
dico("S", 9, "SACCADANT").
dico("S", 9, "SACCADEES").
dico("S", 9, "SACCADENT").
dico("S", 9, "SACCADERA").
dico("S", 9, "SACCADIEZ").
dico("S", 9, "SACCADONS").
dico("S", 9, "SACCAGEAI").
dico("S", 9, "SACCAGEAS").
dico("S", 9, "SACCAGEAT").
dico("S", 9, "SACCAGEES").
dico("S", 9, "SACCAGENT").
dico("S", 9, "SACCAGERA").
dico("S", 9, "SACCAGEUR").
dico("S", 9, "SACCAGIEZ").
dico("S", 9, "SACCHARIN").
dico("S", 9, "SACCULINE").
dico("S", 9, "SACERDOCE").
dico("S", 9, "SACHERIES").
dico("S", 9, "SACOLEVAS").
dico("S", 9, "SACOLEVES").
dico("S", 9, "SACQUAMES").
dico("S", 9, "SACQUASSE").
dico("S", 9, "SACQUATES").
dico("S", 9, "SACQUERAI").
dico("S", 9, "SACQUERAS").
dico("S", 9, "SACQUEREZ").
dico("S", 9, "SACQUIONS").
dico("S", 9, "SACRAIENT").
dico("S", 9, "SACRALISA").
dico("S", 9, "SACRALISE").
dico("S", 9, "SACRASSES").
dico("S", 9, "SACREBLEU").
dico("S", 9, "SACREDIEU").
dico("S", 9, "SACREMENT").
dico("S", 9, "SACRERAIS").
dico("S", 9, "SACRERAIT").
dico("S", 9, "SACRERENT").
dico("S", 9, "SACRERIEZ").
dico("S", 9, "SACRERONS").
dico("S", 9, "SACRERONT").
dico("S", 9, "SACRIFIAI").
dico("S", 9, "SACRIFIAS").
dico("S", 9, "SACRIFIAT").
dico("S", 9, "SACRIFICE").
dico("S", 9, "SACRIFIEE").
dico("S", 9, "SACRIFIER").
dico("S", 9, "SACRIFIES").
dico("S", 9, "SACRIFIEZ").
dico("S", 9, "SACRILEGE").
dico("S", 9, "SACRIPANT").
dico("S", 9, "SACRISTIE").
dico("S", 9, "SADDUCEEN").
dico("S", 9, "SADOMASOS").
dico("S", 9, "SADUCEENS").
dico("S", 9, "SAFRANAIS").
dico("S", 9, "SAFRANAIT").
dico("S", 9, "SAFRANANT").
dico("S", 9, "SAFRANEES").
dico("S", 9, "SAFRANENT").
dico("S", 9, "SAFRANERA").
dico("S", 9, "SAFRANIEZ").
dico("S", 9, "SAFRANINE").
dico("S", 9, "SAFRANONS").
dico("S", 9, "SAGACITES").
dico("S", 9, "SAGITTALE").
dico("S", 9, "SAGITTAUX").
dico("S", 9, "SAGITTEES").
dico("S", 9, "SAGOUINES").
dico("S", 9, "SAGOUTIER").
dico("S", 9, "SAGUENEEN").
dico("S", 9, "SAHARIENS").
dico("S", 9, "SAHELIENS").
dico("S", 9, "SAHRAOUIE").
dico("S", 9, "SAHRAOUIS").
dico("S", 9, "SAIETTAIS").
dico("S", 9, "SAIETTAIT").
dico("S", 9, "SAIETTANT").
dico("S", 9, "SAIETTEES").
dico("S", 9, "SAIETTENT").
dico("S", 9, "SAIETTERA").
dico("S", 9, "SAIETTIEZ").
dico("S", 9, "SAIETTONS").
dico("S", 9, "SAIGNAMES").
dico("S", 9, "SAIGNANTE").
dico("S", 9, "SAIGNANTS").
dico("S", 9, "SAIGNASSE").
dico("S", 9, "SAIGNATES").
dico("S", 9, "SAIGNERAI").
dico("S", 9, "SAIGNERAS").
dico("S", 9, "SAIGNEREZ").
dico("S", 9, "SAIGNEURS").
dico("S", 9, "SAIGNEUSE").
dico("S", 9, "SAIGNIONS").
dico("S", 9, "SAIGNOIRS").
dico("S", 9, "SAILLANTE").
dico("S", 9, "SAILLANTS").
dico("S", 9, "SAILLISSE").
dico("S", 9, "SAINEMENT").
dico("S", 9, "SAINFOINS").
dico("S", 9, "SAINTETES").
dico("S", 9, "SAISIRAIS").
dico("S", 9, "SAISIRAIT").
dico("S", 9, "SAISIRENT").
dico("S", 9, "SAISIRIEZ").
dico("S", 9, "SAISIRONS").
dico("S", 9, "SAISIRONT").
dico("S", 9, "SAISISSES").
dico("S", 9, "SAISISSEZ").
dico("S", 9, "SAKTISMES").
dico("S", 9, "SALACITES").
dico("S", 9, "SALADEROS").
dico("S", 9, "SALADIERE").
dico("S", 9, "SALADIERS").
dico("S", 9, "SALAISONS").
dico("S", 9, "SALAMALEC").
dico("S", 9, "SALANGANE").
dico("S", 9, "SALANQUES").
dico("S", 9, "SALARIAIS").
dico("S", 9, "SALARIAIT").
dico("S", 9, "SALARIALE").
dico("S", 9, "SALARIANT").
dico("S", 9, "SALARIATS").
dico("S", 9, "SALARIAUX").
dico("S", 9, "SALARIEES").
dico("S", 9, "SALARIENT").
dico("S", 9, "SALARIERA").
dico("S", 9, "SALARIIEZ").
dico("S", 9, "SALARIONS").
dico("S", 9, "SALASSENT").
dico("S", 9, "SALASSIEZ").
dico("S", 9, "SALBANDES").
dico("S", 9, "SALERIONS").
dico("S", 9, "SALESIENS").
dico("S", 9, "SALICACEE").
dico("S", 9, "SALICAIRE").
dico("S", 9, "SALICINEE").
dico("S", 9, "SALICINES").
dico("S", 9, "SALICOLES").
dico("S", 9, "SALICOQUE").
dico("S", 9, "SALICORNE").
dico("S", 9, "SALICYLEE").
dico("S", 9, "SALICYLES").
dico("S", 9, "SALIENNES").
dico("S", 9, "SALIFERES").
dico("S", 9, "SALIFIAIS").
dico("S", 9, "SALIFIAIT").
dico("S", 9, "SALIFIANT").
dico("S", 9, "SALIFIEES").
dico("S", 9, "SALIFIENT").
dico("S", 9, "SALIFIERA").
dico("S", 9, "SALIFIIEZ").
dico("S", 9, "SALIFIONS").
dico("S", 9, "SALIGAUDE").
dico("S", 9, "SALIGAUDS").
dico("S", 9, "SALIGNONS").
dico("S", 9, "SALINAGES").
dico("S", 9, "SALINIERE").
dico("S", 9, "SALINIERS").
dico("S", 9, "SALINITES").
dico("S", 9, "SALIRIONS").
dico("S", 9, "SALISSAIS").
dico("S", 9, "SALISSAIT").
dico("S", 9, "SALISSANT").
dico("S", 9, "SALISSENT").
dico("S", 9, "SALISSIEZ").
dico("S", 9, "SALISSONS").
dico("S", 9, "SALISSURE").
dico("S", 9, "SALIVAIRE").
dico("S", 9, "SALIVAMES").
dico("S", 9, "SALIVANTE").
dico("S", 9, "SALIVANTS").
dico("S", 9, "SALIVASSE").
dico("S", 9, "SALIVATES").
dico("S", 9, "SALIVERAI").
dico("S", 9, "SALIVERAS").
dico("S", 9, "SALIVEREZ").
dico("S", 9, "SALIVIONS").
dico("S", 9, "SALMONIDE").
dico("S", 9, "SALONARDE").
dico("S", 9, "SALONARDS").
dico("S", 9, "SALONNARD").
dico("S", 9, "SALONNIER").
dico("S", 9, "SALOPAMES").
dico("S", 9, "SALOPARDE").
dico("S", 9, "SALOPARDS").
dico("S", 9, "SALOPASSE").
dico("S", 9, "SALOPATES").
dico("S", 9, "SALOPERAI").
dico("S", 9, "SALOPERAS").
dico("S", 9, "SALOPEREZ").
dico("S", 9, "SALOPERIE").
dico("S", 9, "SALOPETTE").
dico("S", 9, "SALOPIAUD").
dico("S", 9, "SALOPIAUX").
dico("S", 9, "SALOPIONS").
dico("S", 9, "SALOPIOTS").
dico("S", 9, "SALPETRAI").
dico("S", 9, "SALPETRAS").
dico("S", 9, "SALPETRAT").
dico("S", 9, "SALPETREE").
dico("S", 9, "SALPETRER").
dico("S", 9, "SALPETRES").
dico("S", 9, "SALPETREZ").
dico("S", 9, "SALPICONS").
dico("S", 9, "SALTATION").
dico("S", 9, "SALUAIENT").
dico("S", 9, "SALUASSES").
dico("S", 9, "SALUBRITE").
dico("S", 9, "SALUERAIS").
dico("S", 9, "SALUERAIT").
dico("S", 9, "SALUERENT").
dico("S", 9, "SALUERIEZ").
dico("S", 9, "SALUERONS").
dico("S", 9, "SALUERONT").
dico("S", 9, "SALUTAIRE").
dico("S", 9, "SALUTISTE").
dico("S", 9, "SALVAGNIN").
dico("S", 9, "SALVATEUR").
dico("S", 9, "SAMARIUMS").
dico("S", 9, "SAMBOISTE").
dico("S", 9, "SAMBUQUES").
dico("S", 9, "SAMIENNES").
dico("S", 9, "SAMIZDATS").
dico("S", 9, "SAMOURAIS").
dico("S", 9, "SAMOYEDES").
dico("S", 9, "SAMPLAMES").
dico("S", 9, "SAMPLASSE").
dico("S", 9, "SAMPLATES").
dico("S", 9, "SAMPLERAI").
dico("S", 9, "SAMPLERAS").
dico("S", 9, "SAMPLEREZ").
dico("S", 9, "SAMPLINGS").
dico("S", 9, "SAMPLIONS").
dico("S", 9, "SANCERRES").
dico("S", 9, "SANCTIFIA").
dico("S", 9, "SANCTIFIE").
dico("S", 9, "SANCTIONS").
dico("S", 9, "SANDALIER").
dico("S", 9, "SANDWICHA").
dico("S", 9, "SANDWICHE").
dico("S", 9, "SANDWICHS").
dico("S", 9, "SANGLAGES").
dico("S", 9, "SANGLAMES").
dico("S", 9, "SANGLANTE").
dico("S", 9, "SANGLANTS").
dico("S", 9, "SANGLASSE").
dico("S", 9, "SANGLATES").
dico("S", 9, "SANGLERAI").
dico("S", 9, "SANGLERAS").
dico("S", 9, "SANGLEREZ").
dico("S", 9, "SANGLIERS").
dico("S", 9, "SANGLIONS").
dico("S", 9, "SANGLOTAI").
dico("S", 9, "SANGLOTAS").
dico("S", 9, "SANGLOTAT").
dico("S", 9, "SANGLOTER").
dico("S", 9, "SANGLOTES").
dico("S", 9, "SANGLOTEZ").
dico("S", 9, "SANGUINES").
dico("S", 9, "SANHEDRIN").
dico("S", 9, "SANICULES").
dico("S", 9, "SANIEUSES").
dico("S", 9, "SANISETTE").
dico("S", 9, "SANITAIRE").
dico("S", 9, "SANSCRITE").
dico("S", 9, "SANSCRITS").
dico("S", 9, "SANSKRITE").
dico("S", 9, "SANSKRITS").
dico("S", 9, "SANSONNET").
dico("S", 9, "SANTALINE").
dico("S", 9, "SANTOLINE").
dico("S", 9, "SANTOMEEN").
dico("S", 9, "SANTONINE").
dico("S", 9, "SAOUDIENS").
dico("S", 9, "SAOUDITES").
dico("S", 9, "SAOULAMES").
dico("S", 9, "SAOULANTE").
dico("S", 9, "SAOULANTS").
dico("S", 9, "SAOULARDE").
dico("S", 9, "SAOULARDS").
dico("S", 9, "SAOULASSE").
dico("S", 9, "SAOULATES").
dico("S", 9, "SAOULERAI").
dico("S", 9, "SAOULERAS").
dico("S", 9, "SAOULEREZ").
dico("S", 9, "SAOULERIE").
dico("S", 9, "SAOULIONS").
dico("S", 9, "SAPASSENT").
dico("S", 9, "SAPASSIEZ").
dico("S", 9, "SAPEMENTS").
dico("S", 9, "SAPERIONS").
dico("S", 9, "SAPHIQUES").
dico("S", 9, "SAPHISMES").
dico("S", 9, "SAPIDITES").
dico("S", 9, "SAPIENCES").
dico("S", 9, "SAPINAGES").
dico("S", 9, "SAPINEAUX").
dico("S", 9, "SAPINETTE").
dico("S", 9, "SAPINIERE").
dico("S", 9, "SAPITEURS").
dico("S", 9, "SAPONACEE").
dico("S", 9, "SAPONACES").
dico("S", 9, "SAPONAIRE").
dico("S", 9, "SAPONASES").
dico("S", 9, "SAPONIFIA").
dico("S", 9, "SAPONIFIE").
dico("S", 9, "SAPONINES").
dico("S", 9, "SAPONITES").
dico("S", 9, "SAPOTACEE").
dico("S", 9, "SAPOTIERS").
dico("S", 9, "SAPOTILLE").
dico("S", 9, "SAPROPELE").
dico("S", 9, "SAPROPELS").
dico("S", 9, "SAQUAIENT").
dico("S", 9, "SAQUASSES").
dico("S", 9, "SAQUEBUTE").
dico("S", 9, "SAQUERAIS").
dico("S", 9, "SAQUERAIT").
dico("S", 9, "SAQUERENT").
dico("S", 9, "SAQUERIEZ").
dico("S", 9, "SAQUERONS").
dico("S", 9, "SAQUERONT").
dico("S", 9, "SARABANDE").
dico("S", 9, "SARBACANE").
dico("S", 9, "SARCASMES").
dico("S", 9, "SARCELLES").
dico("S", 9, "SARCLAGES").
dico("S", 9, "SARCLAMES").
dico("S", 9, "SARCLASSE").
dico("S", 9, "SARCLATES").
dico("S", 9, "SARCLERAI").
dico("S", 9, "SARCLERAS").
dico("S", 9, "SARCLEREZ").
dico("S", 9, "SARCLETTE").
dico("S", 9, "SARCLEURS").
dico("S", 9, "SARCLEUSE").
dico("S", 9, "SARCLIONS").
dico("S", 9, "SARCLOIRS").
dico("S", 9, "SARCLURES").
dico("S", 9, "SARCOIDES").
dico("S", 9, "SARCOMERE").
dico("S", 9, "SARCOPTES").
dico("S", 9, "SARDINIER").
dico("S", 9, "SARDOINES").
dico("S", 9, "SARGASSES").
dico("S", 9, "SARMENTAI").
dico("S", 9, "SARMENTAS").
dico("S", 9, "SARMENTAT").
dico("S", 9, "SARMENTEE").
dico("S", 9, "SARMENTER").
dico("S", 9, "SARMENTES").
dico("S", 9, "SARMENTEZ").
dico("S", 9, "SARODISTE").
dico("S", 9, "SARRASINE").
dico("S", 9, "SARRASINS").
dico("S", 9, "SARRETTES").
dico("S", 9, "SARRIETTE").
dico("S", 9, "SARROISES").
dico("S", 9, "SARTHOISE").
dico("S", 9, "SARTRIENS").
dico("S", 9, "SASSAFRAS").
dico("S", 9, "SASSAIENT").
dico("S", 9, "SASSANIDE").
dico("S", 9, "SASSASSES").
dico("S", 9, "SASSEMENT").
dico("S", 9, "SASSENAGE").
dico("S", 9, "SASSERAIS").
dico("S", 9, "SASSERAIT").
dico("S", 9, "SASSERENT").
dico("S", 9, "SASSERIEZ").
dico("S", 9, "SASSERONS").
dico("S", 9, "SASSERONT").
dico("S", 9, "SASSEUSES").
dico("S", 9, "SATANIQUE").
dico("S", 9, "SATANISME").
dico("S", 9, "SATANISTE").
dico("S", 9, "SATELLISA").
dico("S", 9, "SATELLISE").
dico("S", 9, "SATELLITE").
dico("S", 9, "SATIATION").
dico("S", 9, "SATINAGES").
dico("S", 9, "SATINAMES").
dico("S", 9, "SATINASSE").
dico("S", 9, "SATINATES").
dico("S", 9, "SATINERAI").
dico("S", 9, "SATINERAS").
dico("S", 9, "SATINEREZ").
dico("S", 9, "SATINETTE").
dico("S", 9, "SATINEURS").
dico("S", 9, "SATINEUSE").
dico("S", 9, "SATINIONS").
dico("S", 9, "SATIRIQUE").
dico("S", 9, "SATIRISAI").
dico("S", 9, "SATIRISAS").
dico("S", 9, "SATIRISAT").
dico("S", 9, "SATIRISEE").
dico("S", 9, "SATIRISER").
dico("S", 9, "SATIRISES").
dico("S", 9, "SATIRISEZ").
dico("S", 9, "SATIRISTE").
dico("S", 9, "SATISFAIS").
dico("S", 9, "SATISFAIT").
dico("S", 9, "SATISFERA").
dico("S", 9, "SATISFONT").
dico("S", 9, "SATRAPIES").
dico("S", 9, "SATURABLE").
dico("S", 9, "SATURAMES").
dico("S", 9, "SATURANTE").
dico("S", 9, "SATURANTS").
dico("S", 9, "SATURASSE").
dico("S", 9, "SATURATES").
dico("S", 9, "SATURERAI").
dico("S", 9, "SATURERAS").
dico("S", 9, "SATUREREZ").
dico("S", 9, "SATURIONS").
dico("S", 9, "SATURNIEN").
dico("S", 9, "SATURNIES").
dico("S", 9, "SATURNINE").
dico("S", 9, "SATURNINS").
dico("S", 9, "SATYRIQUE").
dico("S", 9, "SATYRISME").
dico("S", 9, "SAUCAIENT").
dico("S", 9, "SAUCASSES").
dico("S", 9, "SAUCERAIS").
dico("S", 9, "SAUCERAIT").
dico("S", 9, "SAUCERENT").
dico("S", 9, "SAUCERIEZ").
dico("S", 9, "SAUCERONS").
dico("S", 9, "SAUCERONT").
dico("S", 9, "SAUCETTES").
dico("S", 9, "SAUCIERES").
dico("S", 9, "SAUCISSES").
dico("S", 9, "SAUCISSON").
dico("S", 9, "SAUGRENUE").
dico("S", 9, "SAUGRENUS").
dico("S", 9, "SAUMATRES").
dico("S", 9, "SAUMONEAU").
dico("S", 9, "SAUMONEES").
dico("S", 9, "SAUMONEUX").
dico("S", 9, "SAUMURAGE").
dico("S", 9, "SAUMURAIS").
dico("S", 9, "SAUMURAIT").
dico("S", 9, "SAUMURANT").
dico("S", 9, "SAUMUREES").
dico("S", 9, "SAUMURENT").
dico("S", 9, "SAUMURERA").
dico("S", 9, "SAUMURIEZ").
dico("S", 9, "SAUMURONS").
dico("S", 9, "SAUNAIENT").
dico("S", 9, "SAUNAISON").
dico("S", 9, "SAUNASSES").
dico("S", 9, "SAUNERAIS").
dico("S", 9, "SAUNERAIT").
dico("S", 9, "SAUNERENT").
dico("S", 9, "SAUNERIEZ").
dico("S", 9, "SAUNERONS").
dico("S", 9, "SAUNERONT").
dico("S", 9, "SAUNIERES").
dico("S", 9, "SAUPIQUET").
dico("S", 9, "SAUPOUDRA").
dico("S", 9, "SAUPOUDRE").
dico("S", 9, "SAURAIENT").
dico("S", 9, "SAURASSES").
dico("S", 9, "SAURERAIS").
dico("S", 9, "SAURERAIT").
dico("S", 9, "SAURERENT").
dico("S", 9, "SAURERIEZ").
dico("S", 9, "SAURERONS").
dico("S", 9, "SAURERONT").
dico("S", 9, "SAURIRAIS").
dico("S", 9, "SAURIRAIT").
dico("S", 9, "SAURIRENT").
dico("S", 9, "SAURIRIEZ").
dico("S", 9, "SAURIRONS").
dico("S", 9, "SAURIRONT").
dico("S", 9, "SAURISSES").
dico("S", 9, "SAURISSEZ").
dico("S", 9, "SAUSSAIES").
dico("S", 9, "SAUTAIENT").
dico("S", 9, "SAUTASSES").
dico("S", 9, "SAUTELLES").
dico("S", 9, "SAUTERAIS").
dico("S", 9, "SAUTERAIT").
dico("S", 9, "SAUTEREAU").
dico("S", 9, "SAUTERENT").
dico("S", 9, "SAUTERIES").
dico("S", 9, "SAUTERIEZ").
dico("S", 9, "SAUTERNES").
dico("S", 9, "SAUTERONS").
dico("S", 9, "SAUTERONT").
dico("S", 9, "SAUTEUSES").
dico("S", 9, "SAUTILLAI").
dico("S", 9, "SAUTILLAS").
dico("S", 9, "SAUTILLAT").
dico("S", 9, "SAUTILLER").
dico("S", 9, "SAUTILLES").
dico("S", 9, "SAUTILLEZ").
dico("S", 9, "SAUVAGEON").
dico("S", 9, "SAUVAGINE").
dico("S", 9, "SAUVAGINS").
dico("S", 9, "SAUVAIENT").
dico("S", 9, "SAUVASSES").
dico("S", 9, "SAUVERAIS").
dico("S", 9, "SAUVERAIT").
dico("S", 9, "SAUVERENT").
dico("S", 9, "SAUVERIEZ").
dico("S", 9, "SAUVERONS").
dico("S", 9, "SAUVERONT").
dico("S", 9, "SAUVETAGE").
dico("S", 9, "SAUVETEUR").
dico("S", 9, "SAUVIGNON").
dico("S", 9, "SAVAMMENT").
dico("S", 9, "SAVETIERE").
dico("S", 9, "SAVETIERS").
dico("S", 9, "SAVOISIEN").
dico("S", 9, "SAVONNAGE").
dico("S", 9, "SAVONNAIS").
dico("S", 9, "SAVONNAIT").
dico("S", 9, "SAVONNANT").
dico("S", 9, "SAVONNEES").
dico("S", 9, "SAVONNENT").
dico("S", 9, "SAVONNERA").
dico("S", 9, "SAVONNEUR").
dico("S", 9, "SAVONNEUX").
dico("S", 9, "SAVONNIER").
dico("S", 9, "SAVONNIEZ").
dico("S", 9, "SAVONNONS").
dico("S", 9, "SAVOURAIS").
dico("S", 9, "SAVOURAIT").
dico("S", 9, "SAVOURANT").
dico("S", 9, "SAVOUREES").
dico("S", 9, "SAVOURENT").
dico("S", 9, "SAVOURERA").
dico("S", 9, "SAVOUREUX").
dico("S", 9, "SAVOURIEZ").
dico("S", 9, "SAVOURONS").
dico("S", 9, "SAVOYARDE").
dico("S", 9, "SAVOYARDS").
dico("S", 9, "SAXATILES").
dico("S", 9, "SAXICOLES").
dico("S", 9, "SAXIFRAGE").
dico("S", 9, "SAXONIENS").
dico("S", 9, "SAXOPHONE").
dico("S", 9, "SCABIEUSE").
dico("S", 9, "SCABINALE").
dico("S", 9, "SCABINAUX").
dico("S", 9, "SCABREUSE").
dico("S", 9, "SCALAIRES").
dico("S", 9, "SCALANTES").
dico("S", 9, "SCALDIENS").
dico("S", 9, "SCALDIQUE").
dico("S", 9, "SCALPAMES").
dico("S", 9, "SCALPASSE").
dico("S", 9, "SCALPATES").
dico("S", 9, "SCALPERAI").
dico("S", 9, "SCALPERAS").
dico("S", 9, "SCALPEREZ").
dico("S", 9, "SCALPIONS").
dico("S", 9, "SCANDALES").
dico("S", 9, "SCANDAMES").
dico("S", 9, "SCANDASSE").
dico("S", 9, "SCANDATES").
dico("S", 9, "SCANDERAI").
dico("S", 9, "SCANDERAS").
dico("S", 9, "SCANDEREZ").
dico("S", 9, "SCANDIONS").
dico("S", 9, "SCANDIUMS").
dico("S", 9, "SCANNAMES").
dico("S", 9, "SCANNASSE").
dico("S", 9, "SCANNATES").
dico("S", 9, "SCANNERAI").
dico("S", 9, "SCANNERAS").
dico("S", 9, "SCANNEREZ").
dico("S", 9, "SCANNEURS").
dico("S", 9, "SCANNIONS").
dico("S", 9, "SCANSIONS").
dico("S", 9, "SCAPHITES").
dico("S", 9, "SCAPHOIDE").
dico("S", 9, "SCARABEES").
dico("S", 9, "SCARIEUSE").
dico("S", 9, "SCARIFIAI").
dico("S", 9, "SCARIFIAS").
dico("S", 9, "SCARIFIAT").
dico("S", 9, "SCARIFIEE").
dico("S", 9, "SCARIFIER").
dico("S", 9, "SCARIFIES").
dico("S", 9, "SCARIFIEZ").
dico("S", 9, "SCELERATE").
dico("S", 9, "SCELERATS").
dico("S", 9, "SCELLAGES").
dico("S", 9, "SCELLAMES").
dico("S", 9, "SCELLASSE").
dico("S", 9, "SCELLATES").
dico("S", 9, "SCELLERAI").
dico("S", 9, "SCELLERAS").
dico("S", 9, "SCELLEREZ").
dico("S", 9, "SCELLIONS").
dico("S", 9, "SCENARIOS").
dico("S", 9, "SCENARISA").
dico("S", 9, "SCENARISE").
dico("S", 9, "SCENIQUES").
dico("S", 9, "SCEPTIQUE").
dico("S", 9, "SCHADAMES").
dico("S", 9, "SCHADASSE").
dico("S", 9, "SCHADATES").
dico("S", 9, "SCHADERAI").
dico("S", 9, "SCHADERAS").
dico("S", 9, "SCHADEREZ").
dico("S", 9, "SCHADIONS").
dico("S", 9, "SCHAPSKAS").
dico("S", 9, "SCHEIDAGE").
dico("S", 9, "SCHEIDAIS").
dico("S", 9, "SCHEIDAIT").
dico("S", 9, "SCHEIDANT").
dico("S", 9, "SCHEIDEES").
dico("S", 9, "SCHEIDENT").
dico("S", 9, "SCHEIDERA").
dico("S", 9, "SCHEIDEUR").
dico("S", 9, "SCHEIDIEZ").
dico("S", 9, "SCHEIDONS").
dico("S", 9, "SCHELLING").
dico("S", 9, "SCHIEDAMS").
dico("S", 9, "SCHILLING").
dico("S", 9, "SCHINDAIS").
dico("S", 9, "SCHINDAIT").
dico("S", 9, "SCHINDANT").
dico("S", 9, "SCHINDENT").
dico("S", 9, "SCHINDERA").
dico("S", 9, "SCHINDIEZ").
dico("S", 9, "SCHINDONS").
dico("S", 9, "SCHISTEUX").
dico("S", 9, "SCHIZOIDE").
dico("S", 9, "SCHIZOSES").
dico("S", 9, "SCHLAGUES").
dico("S", 9, "SCHLINGUA").
dico("S", 9, "SCHLINGUE").
dico("S", 9, "SCHLITTAI").
dico("S", 9, "SCHLITTAS").
dico("S", 9, "SCHLITTAT").
dico("S", 9, "SCHLITTEE").
dico("S", 9, "SCHLITTER").
dico("S", 9, "SCHLITTES").
dico("S", 9, "SCHLITTEZ").
dico("S", 9, "SCHNAUZER").
dico("S", 9, "SCHNOQUES").
dico("S", 9, "SCHNORKEL").
dico("S", 9, "SCHNOUFFS").
dico("S", 9, "SCHOONERS").
dico("S", 9, "SCHPROUMS").
dico("S", 9, "SCHWYZOIS").
dico("S", 9, "SCIASSENT").
dico("S", 9, "SCIASSIEZ").
dico("S", 9, "SCIATIQUE").
dico("S", 9, "SCIEMMENT").
dico("S", 9, "SCIENIDES").
dico("S", 9, "SCIERIONS").
dico("S", 9, "SCINCIDES").
dico("S", 9, "SCINCOIDE").
dico("S", 9, "SCINDAMES").
dico("S", 9, "SCINDASSE").
dico("S", 9, "SCINDATES").
dico("S", 9, "SCINDERAI").
dico("S", 9, "SCINDERAS").
dico("S", 9, "SCINDEREZ").
dico("S", 9, "SCINDIONS").
dico("S", 9, "SCINTILLA").
dico("S", 9, "SCINTILLE").
dico("S", 9, "SCISSILES").
dico("S", 9, "SCISSIONS").
dico("S", 9, "SCISSURES").
dico("S", 9, "SCIURIDES").
dico("S", 9, "SCLERALES").
dico("S", 9, "SCLEREUSE").
dico("S", 9, "SCLEROSAI").
dico("S", 9, "SCLEROSAS").
dico("S", 9, "SCLEROSAT").
dico("S", 9, "SCLEROSEE").
dico("S", 9, "SCLEROSER").
dico("S", 9, "SCLEROSES").
dico("S", 9, "SCLEROSEZ").
dico("S", 9, "SCLEROTES").
dico("S", 9, "SCOLAIRES").
dico("S", 9, "SCOLARISA").
dico("S", 9, "SCOLARISE").
dico("S", 9, "SCOLARITE").
dico("S", 9, "SCOLIASTE").
dico("S", 9, "SCOLIOSES").
dico("S", 9, "SCOMBRIDE").
dico("S", 9, "SCOPITONE").
dico("S", 9, "SCORAIENT").
dico("S", 9, "SCORASSES").
dico("S", 9, "SCORERAIS").
dico("S", 9, "SCORERAIT").
dico("S", 9, "SCORERENT").
dico("S", 9, "SCORERIEZ").
dico("S", 9, "SCORERONS").
dico("S", 9, "SCORERONT").
dico("S", 9, "SCORIACEE").
dico("S", 9, "SCORIACES").
dico("S", 9, "SCORIFIAI").
dico("S", 9, "SCORIFIAS").
dico("S", 9, "SCORIFIAT").
dico("S", 9, "SCORIFIEE").
dico("S", 9, "SCORIFIER").
dico("S", 9, "SCORIFIES").
dico("S", 9, "SCORIFIEZ").
dico("S", 9, "SCORPENES").
dico("S", 9, "SCORPIONS").
dico("S", 9, "SCOTCHAIS").
dico("S", 9, "SCOTCHAIT").
dico("S", 9, "SCOTCHANT").
dico("S", 9, "SCOTCHEES").
dico("S", 9, "SCOTCHENT").
dico("S", 9, "SCOTCHERA").
dico("S", 9, "SCOTCHIEZ").
dico("S", 9, "SCOTCHONS").
dico("S", 9, "SCOTISMES").
dico("S", 9, "SCOTISTES").
dico("S", 9, "SCOTOMISA").
dico("S", 9, "SCOTOMISE").
dico("S", 9, "SCOTOPIES").
dico("S", 9, "SCOTTISHS").
dico("S", 9, "SCOUBIDOU").
dico("S", 9, "SCOUMOUNE").
dico("S", 9, "SCOUTISME").
dico("S", 9, "SCRABBLAI").
dico("S", 9, "SCRABBLAS").
dico("S", 9, "SCRABBLAT").
dico("S", 9, "SCRABBLER").
dico("S", 9, "SCRABBLES").
dico("S", 9, "SCRABBLEZ").
dico("S", 9, "SCRAPEURS").
dico("S", 9, "SCRATCHAI").
dico("S", 9, "SCRATCHAS").
dico("S", 9, "SCRATCHAT").
dico("S", 9, "SCRATCHEE").
dico("S", 9, "SCRATCHER").
dico("S", 9, "SCRATCHES").
dico("S", 9, "SCRATCHEZ").
dico("S", 9, "SCRIBANNE").
dico("S", 9, "SCRIPTEUR").
dico("S", 9, "SCROFULES").
dico("S", 9, "SCROTALES").
dico("S", 9, "SCRUBBERS").
dico("S", 9, "SCRUPULES").
dico("S", 9, "SCRUTAMES").
dico("S", 9, "SCRUTASSE").
dico("S", 9, "SCRUTATES").
dico("S", 9, "SCRUTERAI").
dico("S", 9, "SCRUTERAS").
dico("S", 9, "SCRUTEREZ").
dico("S", 9, "SCRUTIONS").
dico("S", 9, "SCULPTAGE").
dico("S", 9, "SCULPTAIS").
dico("S", 9, "SCULPTAIT").
dico("S", 9, "SCULPTANT").
dico("S", 9, "SCULPTEES").
dico("S", 9, "SCULPTENT").
dico("S", 9, "SCULPTERA").
dico("S", 9, "SCULPTEUR").
dico("S", 9, "SCULPTIEZ").
dico("S", 9, "SCULPTONS").
dico("S", 9, "SCULPTURE").
dico("S", 9, "SCYTHIQUE").
dico("S", 9, "SEBORRHEE").
dico("S", 9, "SECATEURS").
dico("S", 9, "SECESSION").
dico("S", 9, "SECHAIENT").
dico("S", 9, "SECHANTES").
dico("S", 9, "SECHASSES").
dico("S", 9, "SECHEMENT").
dico("S", 9, "SECHERAIS").
dico("S", 9, "SECHERAIT").
dico("S", 9, "SECHERENT").
dico("S", 9, "SECHERIES").
dico("S", 9, "SECHERIEZ").
dico("S", 9, "SECHERONS").
dico("S", 9, "SECHERONT").
dico("S", 9, "SECHEUSES").
dico("S", 9, "SECONDAIS").
dico("S", 9, "SECONDAIT").
dico("S", 9, "SECONDANT").
dico("S", 9, "SECONDEES").
dico("S", 9, "SECONDENT").
dico("S", 9, "SECONDERA").
dico("S", 9, "SECONDIEZ").
dico("S", 9, "SECONDONS").
dico("S", 9, "SECOUAGES").
dico("S", 9, "SECOUAMES").
dico("S", 9, "SECOUASSE").
dico("S", 9, "SECOUATES").
dico("S", 9, "SECOUERAI").
dico("S", 9, "SECOUERAS").
dico("S", 9, "SECOUEREZ").
dico("S", 9, "SECOUEURS").
dico("S", 9, "SECOUEUSE").
dico("S", 9, "SECOUIONS").
dico("S", 9, "SECOURAIS").
dico("S", 9, "SECOURAIT").
dico("S", 9, "SECOURANT").
dico("S", 9, "SECOURENT").
dico("S", 9, "SECOUREUR").
dico("S", 9, "SECOURIEZ").
dico("S", 9, "SECOURONS").
dico("S", 9, "SECOURRAI").
dico("S", 9, "SECOURRAS").
dico("S", 9, "SECOURREZ").
dico("S", 9, "SECOURUES").
dico("S", 9, "SECOUSSES").
dico("S", 9, "SECRETAGE").
dico("S", 9, "SECRETAIS").
dico("S", 9, "SECRETAIT").
dico("S", 9, "SECRETANT").
dico("S", 9, "SECRETEES").
dico("S", 9, "SECRETENT").
dico("S", 9, "SECRETERA").
dico("S", 9, "SECRETEUR").
dico("S", 9, "SECRETIEZ").
dico("S", 9, "SECRETINE").
dico("S", 9, "SECRETION").
dico("S", 9, "SECRETONS").
dico("S", 9, "SECTAIRES").
dico("S", 9, "SECTATEUR").
dico("S", 9, "SECTIONNA").
dico("S", 9, "SECTIONNE").
dico("S", 9, "SECTORIEL").
dico("S", 9, "SECTORISA").
dico("S", 9, "SECTORISE").
dico("S", 9, "SECULAIRE").
dico("S", 9, "SECULIERE").
dico("S", 9, "SECULIERS").
dico("S", 9, "SECURISAI").
dico("S", 9, "SECURISAS").
dico("S", 9, "SECURISAT").
dico("S", 9, "SECURISEE").
dico("S", 9, "SECURISER").
dico("S", 9, "SECURISES").
dico("S", 9, "SECURISEZ").
dico("S", 9, "SECURITES").
dico("S", 9, "SEDATIONS").
dico("S", 9, "SEDATIVES").
dico("S", 9, "SEDIMENTA").
dico("S", 9, "SEDIMENTE").
dico("S", 9, "SEDIMENTS").
dico("S", 9, "SEDITIEUX").
dico("S", 9, "SEDITIONS").
dico("S", 9, "SEDUCTEUR").
dico("S", 9, "SEDUCTION").
dico("S", 9, "SEDUIRAIS").
dico("S", 9, "SEDUIRAIT").
dico("S", 9, "SEDUIRIEZ").
dico("S", 9, "SEDUIRONS").
dico("S", 9, "SEDUIRONT").
dico("S", 9, "SEDUISAIS").
dico("S", 9, "SEDUISAIT").
dico("S", 9, "SEDUISANT").
dico("S", 9, "SEDUISENT").
dico("S", 9, "SEDUISIEZ").
dico("S", 9, "SEDUISONS").
dico("S", 9, "SEDUNOISE").
dico("S", 9, "SEFARADES").
dico("S", 9, "SEGMENTAI").
dico("S", 9, "SEGMENTAL").
dico("S", 9, "SEGMENTAS").
dico("S", 9, "SEGMENTAT").
dico("S", 9, "SEGMENTEE").
dico("S", 9, "SEGMENTER").
dico("S", 9, "SEGMENTES").
dico("S", 9, "SEGMENTEZ").
dico("S", 9, "SEGOVIENS").
dico("S", 9, "SEGRAIRIE").
dico("S", 9, "SEGREGEAI").
dico("S", 9, "SEGREGEAS").
dico("S", 9, "SEGREGEAT").
dico("S", 9, "SEGREGEES").
dico("S", 9, "SEGREGENT").
dico("S", 9, "SEGREGERA").
dico("S", 9, "SEGREGIEZ").
dico("S", 9, "SEGREGUAI").
dico("S", 9, "SEGREGUAS").
dico("S", 9, "SEGREGUAT").
dico("S", 9, "SEGREGUEE").
dico("S", 9, "SEGREGUER").
dico("S", 9, "SEGREGUES").
dico("S", 9, "SEGREGUEZ").
dico("S", 9, "SEIGNEURS").
dico("S", 9, "SEISMALES").
dico("S", 9, "SEISMIQUE").
dico("S", 9, "SEIZIEMES").
dico("S", 9, "SEJOURNAI").
dico("S", 9, "SEJOURNAS").
dico("S", 9, "SEJOURNAT").
dico("S", 9, "SEJOURNER").
dico("S", 9, "SEJOURNES").
dico("S", 9, "SEJOURNEZ").
dico("S", 9, "SELACIENS").
dico("S", 9, "SELECTAIS").
dico("S", 9, "SELECTAIT").
dico("S", 9, "SELECTANT").
dico("S", 9, "SELECTEES").
dico("S", 9, "SELECTENT").
dico("S", 9, "SELECTERA").
dico("S", 9, "SELECTEUR").
dico("S", 9, "SELECTIEZ").
dico("S", 9, "SELECTIFS").
dico("S", 9, "SELECTION").
dico("S", 9, "SELECTIVE").
dico("S", 9, "SELECTONS").
dico("S", 9, "SELENATES").
dico("S", 9, "SELENIATE").
dico("S", 9, "SELENIEES").
dico("S", 9, "SELENIENS").
dico("S", 9, "SELENIEUX").
dico("S", 9, "SELENIQUE").
dico("S", 9, "SELENITES").
dico("S", 9, "SELENIUMS").
dico("S", 9, "SELENIURE").
dico("S", 9, "SELLAIENT").
dico("S", 9, "SELLASSES").
dico("S", 9, "SELLERAIS").
dico("S", 9, "SELLERAIT").
dico("S", 9, "SELLERENT").
dico("S", 9, "SELLERIES").
dico("S", 9, "SELLERIEZ").
dico("S", 9, "SELLERONS").
dico("S", 9, "SELLERONT").
dico("S", 9, "SELLETTES").
dico("S", 9, "SEMAILLES").
dico("S", 9, "SEMAINIER").
dico("S", 9, "SEMANTEME").
dico("S", 9, "SEMAPHORE").
dico("S", 9, "SEMASSENT").
dico("S", 9, "SEMASSIEZ").
dico("S", 9, "SEMBLABLE").
dico("S", 9, "SEMBLAMES").
dico("S", 9, "SEMBLANTS").
dico("S", 9, "SEMBLASSE").
dico("S", 9, "SEMBLATES").
dico("S", 9, "SEMBLERAI").
dico("S", 9, "SEMBLERAS").
dico("S", 9, "SEMBLEREZ").
dico("S", 9, "SEMBLIONS").
dico("S", 9, "SEMELAGES").
dico("S", 9, "SEMENCIER").
dico("S", 9, "SEMERIONS").
dico("S", 9, "SEMESTRES").
dico("S", 9, "SEMILLANT").
dico("S", 9, "SEMILLONS").
dico("S", 9, "SEMINAIRE").
dico("S", 9, "SEMINALES").
dico("S", 9, "SEMINOLES").
dico("S", 9, "SEMINOMES").
dico("S", 9, "SEMITIQUE").
dico("S", 9, "SEMITISME").
dico("S", 9, "SEMONCAIS").
dico("S", 9, "SEMONCAIT").
dico("S", 9, "SEMONCANT").
dico("S", 9, "SEMONCEES").
dico("S", 9, "SEMONCENT").
dico("S", 9, "SEMONCERA").
dico("S", 9, "SEMONCIEZ").
dico("S", 9, "SEMONCONS").
dico("S", 9, "SEMOULIER").
dico("S", 9, "SENATEURS").
dico("S", 9, "SENATRICE").
dico("S", 9, "SENECHAUX").
dico("S", 9, "SENELLIER").
dico("S", 9, "SENESCENT").
dico("S", 9, "SENESTREE").
dico("S", 9, "SENESTRES").
dico("S", 9, "SENILISME").
dico("S", 9, "SENILITES").
dico("S", 9, "SENIORATS").
dico("S", 9, "SENIORIES").
dico("S", 9, "SENIORITE").
dico("S", 9, "SENOLOGIE").
dico("S", 9, "SENOLOGUE").
dico("S", 9, "SENONAISE").
dico("S", 9, "SENONIENS").
dico("S", 9, "SENORITAS").
dico("S", 9, "SENSATION").
dico("S", 9, "SENSEMENT").
dico("S", 9, "SENSIBLES").
dico("S", 9, "SENSILLES").
dico("S", 9, "SENSITIFS").
dico("S", 9, "SENSITIVE").
dico("S", 9, "SENSORIEL").
dico("S", 9, "SENSUELLE").
dico("S", 9, "SENTAIENT").
dico("S", 9, "SENTENCES").
dico("S", 9, "SENTIMENT").
dico("S", 9, "SENTIRAIS").
dico("S", 9, "SENTIRAIT").
dico("S", 9, "SENTIRENT").
dico("S", 9, "SENTIRIEZ").
dico("S", 9, "SENTIRONS").
dico("S", 9, "SENTIRONT").
dico("S", 9, "SENTISSES").
dico("S", 9, "SEOULIENS").
dico("S", 9, "SEPALOIDE").
dico("S", 9, "SEPARABLE").
dico("S", 9, "SEPARAMES").
dico("S", 9, "SEPARASSE").
dico("S", 9, "SEPARATES").
dico("S", 9, "SEPARATIF").
dico("S", 9, "SEPARERAI").
dico("S", 9, "SEPARERAS").
dico("S", 9, "SEPAREREZ").
dico("S", 9, "SEPARIONS").
dico("S", 9, "SEPHARADE").
dico("S", 9, "SEPIOLITE").
dico("S", 9, "SEPTEMBRE").
dico("S", 9, "SEPTEMVIR").
dico("S", 9, "SEPTENNAL").
dico("S", 9, "SEPTENNAT").
dico("S", 9, "SEPTICITE").
dico("S", 9, "SEPTIEMES").
dico("S", 9, "SEPTILIEN").
dico("S", 9, "SEPTIQUES").
dico("S", 9, "SEPTOLETS").
dico("S", 9, "SEPTUPLAI").
dico("S", 9, "SEPTUPLAS").
dico("S", 9, "SEPTUPLAT").
dico("S", 9, "SEPTUPLEE").
dico("S", 9, "SEPTUPLER").
dico("S", 9, "SEPTUPLES").
dico("S", 9, "SEPTUPLEZ").
dico("S", 9, "SEPULCRAL").
dico("S", 9, "SEPULCRES").
dico("S", 9, "SEPULTURE").
dico("S", 9, "SEQUELLES").
dico("S", 9, "SEQUENCAI").
dico("S", 9, "SEQUENCAS").
dico("S", 9, "SEQUENCAT").
dico("S", 9, "SEQUENCEE").
dico("S", 9, "SEQUENCER").
dico("S", 9, "SEQUENCES").
dico("S", 9, "SEQUENCEZ").
dico("S", 9, "SEQUESTRA").
dico("S", 9, "SEQUESTRE").
dico("S", 9, "SERANCAGE").
dico("S", 9, "SERANCAIS").
dico("S", 9, "SERANCAIT").
dico("S", 9, "SERANCANT").
dico("S", 9, "SERANCEES").
dico("S", 9, "SERANCENT").
dico("S", 9, "SERANCERA").
dico("S", 9, "SERANCEUR").
dico("S", 9, "SERANCIEZ").
dico("S", 9, "SERANCOIR").
dico("S", 9, "SERANCONS").
dico("S", 9, "SERAPEUMS").
dico("S", 9, "SERAPHINE").
dico("S", 9, "SERAPHINS").
dico("S", 9, "SERENADES").
dico("S", 9, "SERENITES").
dico("S", 9, "SERESIENS").
dico("S", 9, "SERFOUAGE").
dico("S", 9, "SERFOUIES").
dico("S", 9, "SERFOUIRA").
dico("S", 9, "SERGETTES").
dico("S", 9, "SERIAIENT").
dico("S", 9, "SERIALITE").
dico("S", 9, "SERIASSES").
dico("S", 9, "SERIATION").
dico("S", 9, "SERICINES").
dico("S", 9, "SERIELLES").
dico("S", 9, "SERIERAIS").
dico("S", 9, "SERIERAIT").
dico("S", 9, "SERIERENT").
dico("S", 9, "SERIERIEZ").
dico("S", 9, "SERIERONS").
dico("S", 9, "SERIERONT").
dico("S", 9, "SERIEUSES").
dico("S", 9, "SERINAMES").
dico("S", 9, "SERINASSE").
dico("S", 9, "SERINATES").
dico("S", 9, "SERINERAI").
dico("S", 9, "SERINERAS").
dico("S", 9, "SERINEREZ").
dico("S", 9, "SERINETTE").
dico("S", 9, "SERINGAGE").
dico("S", 9, "SERINGATS").
dico("S", 9, "SERINGUAI").
dico("S", 9, "SERINGUAS").
dico("S", 9, "SERINGUAT").
dico("S", 9, "SERINGUEE").
dico("S", 9, "SERINGUER").
dico("S", 9, "SERINGUES").
dico("S", 9, "SERINGUEZ").
dico("S", 9, "SERINIONS").
dico("S", 9, "SERLIENNE").
dico("S", 9, "SERMONNAI").
dico("S", 9, "SERMONNAS").
dico("S", 9, "SERMONNAT").
dico("S", 9, "SERMONNEE").
dico("S", 9, "SERMONNER").
dico("S", 9, "SERMONNES").
dico("S", 9, "SERMONNEZ").
dico("S", 9, "SEROLOGIE").
dico("S", 9, "SEROSITES").
dico("S", 9, "SEROTINES").
dico("S", 9, "SEROTYPES").
dico("S", 9, "SERPENTAI").
dico("S", 9, "SERPENTAS").
dico("S", 9, "SERPENTAT").
dico("S", 9, "SERPENTER").
dico("S", 9, "SERPENTES").
dico("S", 9, "SERPENTEZ").
dico("S", 9, "SERPENTIN").
dico("S", 9, "SERPETTES").
dico("S", 9, "SERPOLETS").
dico("S", 9, "SERRAIENT").
dico("S", 9, "SERRANIDE").
dico("S", 9, "SERRANTES").
dico("S", 9, "SERRASSES").
dico("S", 9, "SERRATULE").
dico("S", 9, "SERREMENT").
dico("S", 9, "SERRERAIS").
dico("S", 9, "SERRERAIT").
dico("S", 9, "SERRERENT").
dico("S", 9, "SERRERIEZ").
dico("S", 9, "SERRERONS").
dico("S", 9, "SERRERONT").
dico("S", 9, "SERRETTES").
dico("S", 9, "SERRISTES").
dico("S", 9, "SERRURIER").
dico("S", 9, "SERTIRAIS").
dico("S", 9, "SERTIRAIT").
dico("S", 9, "SERTIRENT").
dico("S", 9, "SERTIRIEZ").
dico("S", 9, "SERTIRONS").
dico("S", 9, "SERTIRONT").
dico("S", 9, "SERTISSES").
dico("S", 9, "SERTISSEZ").
dico("S", 9, "SERVAIENT").
dico("S", 9, "SERVANTES").
dico("S", 9, "SERVEUSES").
dico("S", 9, "SERVIABLE").
dico("S", 9, "SERVIETTE").
dico("S", 9, "SERVILITE").
dico("S", 9, "SERVIRAIS").
dico("S", 9, "SERVIRAIT").
dico("S", 9, "SERVIRENT").
dico("S", 9, "SERVIRIEZ").
dico("S", 9, "SERVIRONS").
dico("S", 9, "SERVIRONT").
dico("S", 9, "SERVISSES").
dico("S", 9, "SERVITEUR").
dico("S", 9, "SERVITUDE").
dico("S", 9, "SESAMOIDE").
dico("S", 9, "SESBANIAS").
dico("S", 9, "SESBANIES").
dico("S", 9, "SESTERCES").
dico("S", 9, "SEUILLAGE").
dico("S", 9, "SEULEMENT").
dico("S", 9, "SEULETTES").
dico("S", 9, "SEVERITES").
dico("S", 9, "SEVILLANE").
dico("S", 9, "SEVILLANS").
dico("S", 9, "SEVIRIONS").
dico("S", 9, "SEVISSAIS").
dico("S", 9, "SEVISSAIT").
dico("S", 9, "SEVISSANT").
dico("S", 9, "SEVISSENT").
dico("S", 9, "SEVISSIEZ").
dico("S", 9, "SEVISSONS").
dico("S", 9, "SEVRAIENT").
dico("S", 9, "SEVRASSES").
dico("S", 9, "SEVRERAIS").
dico("S", 9, "SEVRERAIT").
dico("S", 9, "SEVRERENT").
dico("S", 9, "SEVRERIEZ").
dico("S", 9, "SEVRERONS").
dico("S", 9, "SEVRERONT").
dico("S", 9, "SEVRIENNE").
dico("S", 9, "SEXENNALE").
dico("S", 9, "SEXENNAUX").
dico("S", 9, "SEXOLOGIE").
dico("S", 9, "SEXOLOGUE").
dico("S", 9, "SEXONOMIE").
dico("S", 9, "SEXTOLETS").
dico("S", 9, "SEXTUPLAI").
dico("S", 9, "SEXTUPLAS").
dico("S", 9, "SEXTUPLAT").
dico("S", 9, "SEXTUPLEE").
dico("S", 9, "SEXTUPLER").
dico("S", 9, "SEXTUPLES").
dico("S", 9, "SEXTUPLEZ").
dico("S", 9, "SEXUALISA").
dico("S", 9, "SEXUALISE").
dico("S", 9, "SEXUALITE").
dico("S", 9, "SEXUELLES").
dico("S", 9, "SFAXIENNE").
dico("S", 9, "SFORZANDO").
dico("S", 9, "SGRAFFITE").
dico("S", 9, "SHABIENNE").
dico("S", 9, "SHABOUOTS").
dico("S", 9, "SHAKTISME").
dico("S", 9, "SHAMISENS").
dico("S", 9, "SHAMPOING").
dico("S", 9, "SHANTOUNG").
dico("S", 9, "SHANTUNGS").
dico("S", 9, "SHETLANDS").
dico("S", 9, "SHIGELLES").
dico("S", 9, "SHIKHARAS").
dico("S", 9, "SHILLINGS").
dico("S", 9, "SHIRTINGS").
dico("S", 9, "SHIVAISME").
dico("S", 9, "SHIVAITES").
dico("S", 9, "SHOGOUNAL").
dico("S", 9, "SHOGOUNAT").
dico("S", 9, "SHOGUNALE").
dico("S", 9, "SHOGUNATS").
dico("S", 9, "SHOGUNAUX").
dico("S", 9, "SHOOTAMES").
dico("S", 9, "SHOOTASSE").
dico("S", 9, "SHOOTATES").
dico("S", 9, "SHOOTERAI").
dico("S", 9, "SHOOTERAS").
dico("S", 9, "SHOOTEREZ").
dico("S", 9, "SHOOTIONS").
dico("S", 9, "SHOPPINGS").
dico("S", 9, "SHORTHORN").
dico("S", 9, "SHOWROOMS").
dico("S", 9, "SHRAPNELL").
dico("S", 9, "SHRAPNELS").
dico("S", 9, "SHUNTAGES").
dico("S", 9, "SHUNTAMES").
dico("S", 9, "SHUNTASSE").
dico("S", 9, "SHUNTATES").
dico("S", 9, "SHUNTERAI").
dico("S", 9, "SHUNTERAS").
dico("S", 9, "SHUNTEREZ").
dico("S", 9, "SHUNTIONS").
dico("S", 9, "SIALIQUES").
dico("S", 9, "SIAMOISES").
dico("S", 9, "SIBERIENS").
dico("S", 9, "SIBILANCE").
dico("S", 9, "SIBILANTE").
dico("S", 9, "SIBILANTS").
dico("S", 9, "SIBYLLINE").
dico("S", 9, "SIBYLLINS").
dico("S", 9, "SICCATIFS").
dico("S", 9, "SICCATIVE").
dico("S", 9, "SICILIENS").
dico("S", 9, "SICLAIENT").
dico("S", 9, "SICLASSES").
dico("S", 9, "SICLERAIS").
dico("S", 9, "SICLERAIT").
dico("S", 9, "SICLERENT").
dico("S", 9, "SICLERIEZ").
dico("S", 9, "SICLERONS").
dico("S", 9, "SICLERONT").
dico("S", 9, "SIDAIQUES").
dico("S", 9, "SIDATIQUE").
dico("S", 9, "SIDEENNES").
dico("S", 9, "SIDERALES").
dico("S", 9, "SIDERAMES").
dico("S", 9, "SIDERANTE").
dico("S", 9, "SIDERANTS").
dico("S", 9, "SIDERASSE").
dico("S", 9, "SIDERATES").
dico("S", 9, "SIDERERAI").
dico("S", 9, "SIDERERAS").
dico("S", 9, "SIDEREREZ").
dico("S", 9, "SIDERIONS").
dico("S", 9, "SIDERITES").
dico("S", 9, "SIDEROSES").
dico("S", 9, "SIDOLOGUE").
dico("S", 9, "SIEGEAMES").
dico("S", 9, "SIEGEASSE").
dico("S", 9, "SIEGEATES").
dico("S", 9, "SIEGERAIS").
dico("S", 9, "SIEGERAIT").
dico("S", 9, "SIEGERENT").
dico("S", 9, "SIEGERIEZ").
dico("S", 9, "SIEGERONS").
dico("S", 9, "SIEGERONT").
dico("S", 9, "SIENNOISE").
dico("S", 9, "SIERAIENT").
dico("S", 9, "SIESTAMES").
dico("S", 9, "SIESTASSE").
dico("S", 9, "SIESTATES").
dico("S", 9, "SIESTERAI").
dico("S", 9, "SIESTERAS").
dico("S", 9, "SIESTEREZ").
dico("S", 9, "SIESTIONS").
dico("S", 9, "SIFFLAGES").
dico("S", 9, "SIFFLAMES").
dico("S", 9, "SIFFLANTE").
dico("S", 9, "SIFFLANTS").
dico("S", 9, "SIFFLASSE").
dico("S", 9, "SIFFLATES").
dico("S", 9, "SIFFLERAI").
dico("S", 9, "SIFFLERAS").
dico("S", 9, "SIFFLEREZ").
dico("S", 9, "SIFFLEURS").
dico("S", 9, "SIFFLEUSE").
dico("S", 9, "SIFFLIONS").
dico("S", 9, "SIFFLOTAI").
dico("S", 9, "SIFFLOTAS").
dico("S", 9, "SIFFLOTAT").
dico("S", 9, "SIFFLOTEE").
dico("S", 9, "SIFFLOTER").
dico("S", 9, "SIFFLOTES").
dico("S", 9, "SIFFLOTEZ").
dico("S", 9, "SIGILLEES").
dico("S", 9, "SIGISBEES").
dico("S", 9, "SIGLAISON").
dico("S", 9, "SIGMOIDES").
dico("S", 9, "SIGNAIENT").
dico("S", 9, "SIGNALAIS").
dico("S", 9, "SIGNALAIT").
dico("S", 9, "SIGNALANT").
dico("S", 9, "SIGNALEES").
dico("S", 9, "SIGNALENT").
dico("S", 9, "SIGNALERA").
dico("S", 9, "SIGNALEUR").
dico("S", 9, "SIGNALIEZ").
dico("S", 9, "SIGNALISA").
dico("S", 9, "SIGNALISE").
dico("S", 9, "SIGNALONS").
dico("S", 9, "SIGNASSES").
dico("S", 9, "SIGNATURE").
dico("S", 9, "SIGNERAIS").
dico("S", 9, "SIGNERAIT").
dico("S", 9, "SIGNERENT").
dico("S", 9, "SIGNERIEZ").
dico("S", 9, "SIGNERONS").
dico("S", 9, "SIGNERONT").
dico("S", 9, "SIGNIFIAI").
dico("S", 9, "SIGNIFIAS").
dico("S", 9, "SIGNIFIAT").
dico("S", 9, "SIGNIFIEE").
dico("S", 9, "SIGNIFIER").
dico("S", 9, "SIGNIFIES").
dico("S", 9, "SIGNIFIEZ").
dico("S", 9, "SIGNOFILE").
dico("S", 9, "SIKHISMES").
dico("S", 9, "SILASSENT").
dico("S", 9, "SILASSIEZ").
dico("S", 9, "SILENCEUR").
dico("S", 9, "SILERIONS").
dico("S", 9, "SILESIENS").
dico("S", 9, "SILICAGEL").
dico("S", 9, "SILICATEE").
dico("S", 9, "SILICATES").
dico("S", 9, "SILICEUSE").
dico("S", 9, "SILICIQUE").
dico("S", 9, "SILICIUMS").
dico("S", 9, "SILICIURE").
dico("S", 9, "SILICONAI").
dico("S", 9, "SILICONAS").
dico("S", 9, "SILICONAT").
dico("S", 9, "SILICONEE").
dico("S", 9, "SILICONER").
dico("S", 9, "SILICONES").
dico("S", 9, "SILICONEZ").
dico("S", 9, "SILICOSEE").
dico("S", 9, "SILICOSES").
dico("S", 9, "SILICULES").
dico("S", 9, "SILIONNES").
dico("S", 9, "SILLONNAI").
dico("S", 9, "SILLONNAS").
dico("S", 9, "SILLONNAT").
dico("S", 9, "SILLONNEE").
dico("S", 9, "SILLONNER").
dico("S", 9, "SILLONNES").
dico("S", 9, "SILLONNEZ").
dico("S", 9, "SILOTAGES").
dico("S", 9, "SILPHIDES").
dico("S", 9, "SILURIDES").
dico("S", 9, "SILURIENS").
dico("S", 9, "SILVANERS").
dico("S", 9, "SIMAGREES").
dico("S", 9, "SIMARUBAS").
dico("S", 9, "SIMBLEAUX").
dico("S", 9, "SIMIENNES").
dico("S", 9, "SIMIESQUE").
dico("S", 9, "SIMILAIRE").
dico("S", 9, "SIMILISAI").
dico("S", 9, "SIMILISAS").
dico("S", 9, "SIMILISAT").
dico("S", 9, "SIMILISEE").
dico("S", 9, "SIMILISER").
dico("S", 9, "SIMILISES").
dico("S", 9, "SIMILISEZ").
dico("S", 9, "SIMILISTE").
dico("S", 9, "SIMPLETTE").
dico("S", 9, "SIMPLEXES").
dico("S", 9, "SIMPLIFIA").
dico("S", 9, "SIMPLIFIE").
dico("S", 9, "SIMPLISME").
dico("S", 9, "SIMPLISTE").
dico("S", 9, "SIMULACRE").
dico("S", 9, "SIMULAMES").
dico("S", 9, "SIMULASSE").
dico("S", 9, "SIMULATES").
dico("S", 9, "SIMULERAI").
dico("S", 9, "SIMULERAS").
dico("S", 9, "SIMULEREZ").
dico("S", 9, "SIMULIONS").
dico("S", 9, "SIMULTANE").
dico("S", 9, "SINAPISAI").
dico("S", 9, "SINAPISAS").
dico("S", 9, "SINAPISAT").
dico("S", 9, "SINAPISEE").
dico("S", 9, "SINAPISER").
dico("S", 9, "SINAPISES").
dico("S", 9, "SINAPISEZ").
dico("S", 9, "SINAPISME").
dico("S", 9, "SINCERITE").
dico("S", 9, "SINCIPUTS").
dico("S", 9, "SINECURES").
dico("S", 9, "SINGEAMES").
dico("S", 9, "SINGEASSE").
dico("S", 9, "SINGEATES").
dico("S", 9, "SINGERAIS").
dico("S", 9, "SINGERAIT").
dico("S", 9, "SINGERENT").
dico("S", 9, "SINGERIES").
dico("S", 9, "SINGERIEZ").
dico("S", 9, "SINGERONS").
dico("S", 9, "SINGERONT").
dico("S", 9, "SINGLETON").
dico("S", 9, "SINGSPIEL").
dico("S", 9, "SINGULIER").
dico("S", 9, "SINISAMES").
dico("S", 9, "SINISANTE").
dico("S", 9, "SINISANTS").
dico("S", 9, "SINISASSE").
dico("S", 9, "SINISATES").
dico("S", 9, "SINISERAI").
dico("S", 9, "SINISERAS").
dico("S", 9, "SINISEREZ").
dico("S", 9, "SINISIONS").
dico("S", 9, "SINISTREE").
dico("S", 9, "SINISTRES").
dico("S", 9, "SINOLOGIE").
dico("S", 9, "SINOLOGUE").
dico("S", 9, "SINOPHILE").
dico("S", 9, "SINOPHOBE").
dico("S", 9, "SINTERISA").
dico("S", 9, "SINTERISE").
dico("S", 9, "SINUAIENT").
dico("S", 9, "SINUASSES").
dico("S", 9, "SINUERAIS").
dico("S", 9, "SINUERAIT").
dico("S", 9, "SINUERENT").
dico("S", 9, "SINUERIEZ").
dico("S", 9, "SINUERONS").
dico("S", 9, "SINUERONT").
dico("S", 9, "SINUEUSES").
dico("S", 9, "SINUOSITE").
dico("S", 9, "SINUSALES").
dico("S", 9, "SINUSIENS").
dico("S", 9, "SINUSITES").
dico("S", 9, "SINUSOIDE").
dico("S", 9, "SIONISMES").
dico("S", 9, "SIONISTES").
dico("S", 9, "SIPHOIDES").
dico("S", 9, "SIPHONNAI").
dico("S", 9, "SIPHONNAS").
dico("S", 9, "SIPHONNAT").
dico("S", 9, "SIPHONNEE").
dico("S", 9, "SIPHONNER").
dico("S", 9, "SIPHONNES").
dico("S", 9, "SIPHONNEZ").
dico("S", 9, "SIRENIENS").
dico("S", 9, "SIROPERIE").
dico("S", 9, "SIROTAMES").
dico("S", 9, "SIROTASSE").
dico("S", 9, "SIROTATES").
dico("S", 9, "SIROTERAI").
dico("S", 9, "SIROTERAS").
dico("S", 9, "SIROTEREZ").
dico("S", 9, "SIROTEURS").
dico("S", 9, "SIROTEUSE").
dico("S", 9, "SIROTIONS").
dico("S", 9, "SIRUPEUSE").
dico("S", 9, "SIRVENTES").
dico("S", 9, "SISMICITE").
dico("S", 9, "SISMIQUES").
dico("S", 9, "SISSONNES").
dico("S", 9, "SISYMBRES").
dico("S", 9, "SITARISTE").
dico("S", 9, "SITOLOGIE").
dico("S", 9, "SITOLOGUE").
dico("S", 9, "SITTELLES").
dico("S", 9, "SITUAIENT").
dico("S", 9, "SITUASSES").
dico("S", 9, "SITUATION").
dico("S", 9, "SITUERAIS").
dico("S", 9, "SITUERAIT").
dico("S", 9, "SITUERENT").
dico("S", 9, "SITUERIEZ").
dico("S", 9, "SITUERONS").
dico("S", 9, "SITUERONT").
dico("S", 9, "SIVAISMES").
dico("S", 9, "SKELETONS").
dico("S", 9, "SKIASSENT").
dico("S", 9, "SKIASSIEZ").
dico("S", 9, "SKIERIONS").
dico("S", 9, "SKIFEUSES").
dico("S", 9, "SKIFFEURS").
dico("S", 9, "SKIFFEUSE").
dico("S", 9, "SKINHEADS").
dico("S", 9, "SKIPPAMES").
dico("S", 9, "SKIPPASSE").
dico("S", 9, "SKIPPATES").
dico("S", 9, "SKIPPERAI").
dico("S", 9, "SKIPPERAS").
dico("S", 9, "SKIPPEREZ").
dico("S", 9, "SKIPPIONS").
dico("S", 9, "SKOPIOTES").
dico("S", 9, "SLALOMAIS").
dico("S", 9, "SLALOMAIT").
dico("S", 9, "SLALOMANT").
dico("S", 9, "SLALOMENT").
dico("S", 9, "SLALOMERA").
dico("S", 9, "SLALOMEUR").
dico("S", 9, "SLALOMIEZ").
dico("S", 9, "SLALOMONS").
dico("S", 9, "SLAVISAIS").
dico("S", 9, "SLAVISAIT").
dico("S", 9, "SLAVISANT").
dico("S", 9, "SLAVISEES").
dico("S", 9, "SLAVISENT").
dico("S", 9, "SLAVISERA").
dico("S", 9, "SLAVISIEZ").
dico("S", 9, "SLAVISMES").
dico("S", 9, "SLAVISONS").
dico("S", 9, "SLAVISTES").
dico("S", 9, "SLAVONNES").
dico("S", 9, "SLEEPINGS").
dico("S", 9, "SLICAIENT").
dico("S", 9, "SLICASSES").
dico("S", 9, "SLICERAIS").
dico("S", 9, "SLICERAIT").
dico("S", 9, "SLICERENT").
dico("S", 9, "SLICERIEZ").
dico("S", 9, "SLICERONS").
dico("S", 9, "SLICERONT").
dico("S", 9, "SLOVAQUES").
dico("S", 9, "SMALTINES").
dico("S", 9, "SMALTITES").
dico("S", 9, "SMARAGDIN").
dico("S", 9, "SMASHAMES").
dico("S", 9, "SMASHASSE").
dico("S", 9, "SMASHATES").
dico("S", 9, "SMASHERAI").
dico("S", 9, "SMASHERAS").
dico("S", 9, "SMASHEREZ").
dico("S", 9, "SMASHEURS").
dico("S", 9, "SMASHEUSE").
dico("S", 9, "SMASHIONS").
dico("S", 9, "SMECTIQUE").
dico("S", 9, "SMICARDES").
dico("S", 9, "SMILLAGES").
dico("S", 9, "SMILLAMES").
dico("S", 9, "SMILLASSE").
dico("S", 9, "SMILLATES").
dico("S", 9, "SMILLERAI").
dico("S", 9, "SMILLERAS").
dico("S", 9, "SMILLEREZ").
dico("S", 9, "SMILLIONS").
dico("S", 9, "SMORZANDO").
dico("S", 9, "SMURFAMES").
dico("S", 9, "SMURFASSE").
dico("S", 9, "SMURFATES").
dico("S", 9, "SMURFERAI").
dico("S", 9, "SMURFERAS").
dico("S", 9, "SMURFEREZ").
dico("S", 9, "SMURFEURS").
dico("S", 9, "SMURFEUSE").
dico("S", 9, "SMURFIONS").
dico("S", 9, "SNIFAIENT").
dico("S", 9, "SNIFASSES").
dico("S", 9, "SNIFERAIS").
dico("S", 9, "SNIFERAIT").
dico("S", 9, "SNIFERENT").
dico("S", 9, "SNIFERIEZ").
dico("S", 9, "SNIFERONS").
dico("S", 9, "SNIFERONT").
dico("S", 9, "SNIFFAMES").
dico("S", 9, "SNIFFASSE").
dico("S", 9, "SNIFFATES").
dico("S", 9, "SNIFFERAI").
dico("S", 9, "SNIFFERAS").
dico("S", 9, "SNIFFEREZ").
dico("S", 9, "SNIFFIONS").
dico("S", 9, "SNOBAIENT").
dico("S", 9, "SNOBASSES").
dico("S", 9, "SNOBERAIS").
dico("S", 9, "SNOBERAIT").
dico("S", 9, "SNOBERENT").
dico("S", 9, "SNOBERIEZ").
dico("S", 9, "SNOBERONS").
dico("S", 9, "SNOBERONT").
dico("S", 9, "SNOBINARD").
dico("S", 9, "SNOBISMES").
dico("S", 9, "SNOWBOARD").
dico("S", 9, "SOBREMENT").
dico("S", 9, "SOBRIETES").
dico("S", 9, "SOBRIQUET").
dico("S", 9, "SOCHALIEN").
dico("S", 9, "SOCIABLES").
dico("S", 9, "SOCIALISA").
dico("S", 9, "SOCIALISE").
dico("S", 9, "SOCIALITE").
dico("S", 9, "SOCIATRIE").
dico("S", 9, "SOCIETALE").
dico("S", 9, "SOCIETAUX").
dico("S", 9, "SOCINIENS").
dico("S", 9, "SOCQUETTE").
dico("S", 9, "SODOMISAI").
dico("S", 9, "SODOMISAS").
dico("S", 9, "SODOMISAT").
dico("S", 9, "SODOMISEE").
dico("S", 9, "SODOMISER").
dico("S", 9, "SODOMISES").
dico("S", 9, "SODOMISEZ").
dico("S", 9, "SODOMITES").
dico("S", 9, "SOEURETTE").
dico("S", 9, "SOFTBALLS").
dico("S", 9, "SOFTWARES").
dico("S", 9, "SOIFFARDE").
dico("S", 9, "SOIFFARDS").
dico("S", 9, "SOIGNABLE").
dico("S", 9, "SOIGNAMES").
dico("S", 9, "SOIGNANTE").
dico("S", 9, "SOIGNANTS").
dico("S", 9, "SOIGNASSE").
dico("S", 9, "SOIGNATES").
dico("S", 9, "SOIGNERAI").
dico("S", 9, "SOIGNERAS").
dico("S", 9, "SOIGNEREZ").
dico("S", 9, "SOIGNEURS").
dico("S", 9, "SOIGNEUSE").
dico("S", 9, "SOIGNIONS").
dico("S", 9, "SOLANACEE").
dico("S", 9, "SOLARISAI").
dico("S", 9, "SOLARISAS").
dico("S", 9, "SOLARISAT").
dico("S", 9, "SOLARISEE").
dico("S", 9, "SOLARISER").
dico("S", 9, "SOLARISES").
dico("S", 9, "SOLARISEZ").
dico("S", 9, "SOLARIUMS").
dico("S", 9, "SOLDAIENT").
dico("S", 9, "SOLDASSES").
dico("S", 9, "SOLDERAIS").
dico("S", 9, "SOLDERAIT").
dico("S", 9, "SOLDERENT").
dico("S", 9, "SOLDERIES").
dico("S", 9, "SOLDERIEZ").
dico("S", 9, "SOLDERONS").
dico("S", 9, "SOLDERONT").
dico("S", 9, "SOLDEUSES").
dico("S", 9, "SOLEAIRES").
dico("S", 9, "SOLECISME").
dico("S", 9, "SOLENNELS").
dico("S", 9, "SOLENNISA").
dico("S", 9, "SOLENNISE").
dico("S", 9, "SOLENNITE").
dico("S", 9, "SOLENOIDE").
dico("S", 9, "SOLEUROIS").
dico("S", 9, "SOLFATARE").
dico("S", 9, "SOLFIAMES").
dico("S", 9, "SOLFIASSE").
dico("S", 9, "SOLFIATES").
dico("S", 9, "SOLFIERAI").
dico("S", 9, "SOLFIERAS").
dico("S", 9, "SOLFIEREZ").
dico("S", 9, "SOLFIIONS").
dico("S", 9, "SOLICITOR").
dico("S", 9, "SOLIDAGES").
dico("S", 9, "SOLIDAGOS").
dico("S", 9, "SOLIDAIRE").
dico("S", 9, "SOLIDIFIA").
dico("S", 9, "SOLIDIFIE").
dico("S", 9, "SOLIDITES").
dico("S", 9, "SOLIFLORE").
dico("S", 9, "SOLIFUGES").
dico("S", 9, "SOLILOQUA").
dico("S", 9, "SOLILOQUE").
dico("S", 9, "SOLIPEDES").
dico("S", 9, "SOLITAIRE").
dico("S", 9, "SOLITUDES").
dico("S", 9, "SOLIVEAUX").
dico("S", 9, "SOLLICITA").
dico("S", 9, "SOLLICITE").
dico("S", 9, "SOLOGNOTE").
dico("S", 9, "SOLOGNOTS").
dico("S", 9, "SOLSTICES").
dico("S", 9, "SOLUTIONS").
dico("S", 9, "SOLUTREEN").
dico("S", 9, "SOLVABLES").
dico("S", 9, "SOMALIENS").
dico("S", 9, "SOMATIONS").
dico("S", 9, "SOMATIQUE").
dico("S", 9, "SOMATISAI").
dico("S", 9, "SOMATISAS").
dico("S", 9, "SOMATISAT").
dico("S", 9, "SOMATISEE").
dico("S", 9, "SOMATISER").
dico("S", 9, "SOMATISES").
dico("S", 9, "SOMATISEZ").
dico("S", 9, "SOMBRAMES").
dico("S", 9, "SOMBRASSE").
dico("S", 9, "SOMBRATES").
dico("S", 9, "SOMBRERAI").
dico("S", 9, "SOMBRERAS").
dico("S", 9, "SOMBREREZ").
dico("S", 9, "SOMBREROS").
dico("S", 9, "SOMBRIONS").
dico("S", 9, "SOMMABLES").
dico("S", 9, "SOMMAIENT").
dico("S", 9, "SOMMAIRES").
dico("S", 9, "SOMMASSES").
dico("S", 9, "SOMMATION").
dico("S", 9, "SOMMEILLA").
dico("S", 9, "SOMMEILLE").
dico("S", 9, "SOMMELIER").
dico("S", 9, "SOMMERAIS").
dico("S", 9, "SOMMERAIT").
dico("S", 9, "SOMMERENT").
dico("S", 9, "SOMMERIEZ").
dico("S", 9, "SOMMERONS").
dico("S", 9, "SOMMERONT").
dico("S", 9, "SOMMITALE").
dico("S", 9, "SOMMITAUX").
dico("S", 9, "SOMNIFERE").
dico("S", 9, "SOMNOLAIS").
dico("S", 9, "SOMNOLAIT").
dico("S", 9, "SOMNOLANT").
dico("S", 9, "SOMNOLENT").
dico("S", 9, "SOMNOLERA").
dico("S", 9, "SOMNOLIEZ").
dico("S", 9, "SOMNOLONS").
dico("S", 9, "SOMPTUEUX").
dico("S", 9, "SONATINES").
dico("S", 9, "SONDAIENT").
dico("S", 9, "SONDASSES").
dico("S", 9, "SONDERAIS").
dico("S", 9, "SONDERAIT").
dico("S", 9, "SONDERENT").
dico("S", 9, "SONDERIEZ").
dico("S", 9, "SONDERONS").
dico("S", 9, "SONDERONT").
dico("S", 9, "SONDEUSES").
dico("S", 9, "SONEGIENS").
dico("S", 9, "SONGEAMES").
dico("S", 9, "SONGEASSE").
dico("S", 9, "SONGEATES").
dico("S", 9, "SONGERAIS").
dico("S", 9, "SONGERAIT").
dico("S", 9, "SONGERENT").
dico("S", 9, "SONGERIES").
dico("S", 9, "SONGERIEZ").
dico("S", 9, "SONGERONS").
dico("S", 9, "SONGERONT").
dico("S", 9, "SONGEUSES").
dico("S", 9, "SONNAIENT").
dico("S", 9, "SONNAILLA").
dico("S", 9, "SONNAILLE").
dico("S", 9, "SONNANTES").
dico("S", 9, "SONNASSES").
dico("S", 9, "SONNERAIS").
dico("S", 9, "SONNERAIT").
dico("S", 9, "SONNERENT").
dico("S", 9, "SONNERIES").
dico("S", 9, "SONNERIEZ").
dico("S", 9, "SONNERONS").
dico("S", 9, "SONNERONT").
dico("S", 9, "SONNETTES").
dico("S", 9, "SONNEUSES").
dico("S", 9, "SONOMETRE").
dico("S", 9, "SONORISAI").
dico("S", 9, "SONORISAS").
dico("S", 9, "SONORISAT").
dico("S", 9, "SONORISEE").
dico("S", 9, "SONORISER").
dico("S", 9, "SONORISES").
dico("S", 9, "SONORISEZ").
dico("S", 9, "SONORITES").
dico("S", 9, "SONOTONES").
dico("S", 9, "SOPHISMES").
dico("S", 9, "SOPHISTES").
dico("S", 9, "SOPOREUSE").
dico("S", 9, "SORBITOLS").
dico("S", 9, "SORCIERES").
dico("S", 9, "SORDIDITE").
dico("S", 9, "SORNETTES").
dico("S", 9, "SORORALES").
dico("S", 9, "SORORITES").
dico("S", 9, "SORPTIONS").
dico("S", 9, "SORTABLES").
dico("S", 9, "SORTAIENT").
dico("S", 9, "SORTANTES").
dico("S", 9, "SORTEUSES").
dico("S", 9, "SORTILEGE").
dico("S", 9, "SORTIRAIS").
dico("S", 9, "SORTIRAIT").
dico("S", 9, "SORTIRENT").
dico("S", 9, "SORTIRIEZ").
dico("S", 9, "SORTIRONS").
dico("S", 9, "SORTIRONT").
dico("S", 9, "SORTISSES").
dico("S", 9, "SOSTENUTO").
dico("S", 9, "SOTTEMENT").
dico("S", 9, "SOTTISIER").
dico("S", 9, "SOUAHELIE").
dico("S", 9, "SOUAHELIS").
dico("S", 9, "SOUBRETTE").
dico("S", 9, "SOUCHETTE").
dico("S", 9, "SOUCHONGS").
dico("S", 9, "SOUCIAMES").
dico("S", 9, "SOUCIASSE").
dico("S", 9, "SOUCIATES").
dico("S", 9, "SOUCIERAI").
dico("S", 9, "SOUCIERAS").
dico("S", 9, "SOUCIEREZ").
dico("S", 9, "SOUCIEUSE").
dico("S", 9, "SOUCIIONS").
dico("S", 9, "SOUCOUPES").
dico("S", 9, "SOUDABLES").
dico("S", 9, "SOUDAIENT").
dico("S", 9, "SOUDAINES").
dico("S", 9, "SOUDANAIS").
dico("S", 9, "SOUDANIEN").
dico("S", 9, "SOUDANTES").
dico("S", 9, "SOUDASSES").
dico("S", 9, "SOUDERAIS").
dico("S", 9, "SOUDERAIT").
dico("S", 9, "SOUDERENT").
dico("S", 9, "SOUDERIEZ").
dico("S", 9, "SOUDERONS").
dico("S", 9, "SOUDERONT").
dico("S", 9, "SOUDEUSES").
dico("S", 9, "SOUDIERES").
dico("S", 9, "SOUDOIENT").
dico("S", 9, "SOUDOIERA").
dico("S", 9, "SOUDOYAIS").
dico("S", 9, "SOUDOYAIT").
dico("S", 9, "SOUDOYANT").
dico("S", 9, "SOUDOYEES").
dico("S", 9, "SOUDOYIEZ").
dico("S", 9, "SOUDOYONS").
dico("S", 9, "SOUFFERTE").
dico("S", 9, "SOUFFERTS").
dico("S", 9, "SOUFFLAGE").
dico("S", 9, "SOUFFLAIS").
dico("S", 9, "SOUFFLAIT").
dico("S", 9, "SOUFFLANT").
dico("S", 9, "SOUFFLARD").
dico("S", 9, "SOUFFLEES").
dico("S", 9, "SOUFFLENT").
dico("S", 9, "SOUFFLERA").
dico("S", 9, "SOUFFLETA").
dico("S", 9, "SOUFFLETE").
dico("S", 9, "SOUFFLETS").
dico("S", 9, "SOUFFLEUR").
dico("S", 9, "SOUFFLIEZ").
dico("S", 9, "SOUFFLONS").
dico("S", 9, "SOUFFLURE").
dico("S", 9, "SOUFFRAIS").
dico("S", 9, "SOUFFRAIT").
dico("S", 9, "SOUFFRANT").
dico("S", 9, "SOUFFRENT").
dico("S", 9, "SOUFFRIEZ").
dico("S", 9, "SOUFFRIRA").
dico("S", 9, "SOUFFRONS").
dico("S", 9, "SOUFISMES").
dico("S", 9, "SOUFRAGES").
dico("S", 9, "SOUFRAMES").
dico("S", 9, "SOUFRASSE").
dico("S", 9, "SOUFRATES").
dico("S", 9, "SOUFRERAI").
dico("S", 9, "SOUFRERAS").
dico("S", 9, "SOUFREREZ").
dico("S", 9, "SOUFREURS").
dico("S", 9, "SOUFREUSE").
dico("S", 9, "SOUFRIERE").
dico("S", 9, "SOUFRIONS").
dico("S", 9, "SOUFROIRS").
dico("S", 9, "SOUHAITAI").
dico("S", 9, "SOUHAITAS").
dico("S", 9, "SOUHAITAT").
dico("S", 9, "SOUHAITEE").
dico("S", 9, "SOUHAITER").
dico("S", 9, "SOUHAITES").
dico("S", 9, "SOUHAITEZ").
dico("S", 9, "SOUILLAIS").
dico("S", 9, "SOUILLAIT").
dico("S", 9, "SOUILLANT").
dico("S", 9, "SOUILLARD").
dico("S", 9, "SOUILLEES").
dico("S", 9, "SOUILLENT").
dico("S", 9, "SOUILLERA").
dico("S", 9, "SOUILLIEZ").
dico("S", 9, "SOUILLONS").
dico("S", 9, "SOUILLURE").
dico("S", 9, "SOUIMANGA").
dico("S", 9, "SOULAGEAI").
dico("S", 9, "SOULAGEAS").
dico("S", 9, "SOULAGEAT").
dico("S", 9, "SOULAGEES").
dico("S", 9, "SOULAGENT").
dico("S", 9, "SOULAGERA").
dico("S", 9, "SOULAGIEZ").
dico("S", 9, "SOULAIENT").
dico("S", 9, "SOULANTES").
dico("S", 9, "SOULARDES").
dico("S", 9, "SOULASSES").
dico("S", 9, "SOULAUDES").
dico("S", 9, "SOULERAIS").
dico("S", 9, "SOULERAIT").
dico("S", 9, "SOULERENT").
dico("S", 9, "SOULERIES").
dico("S", 9, "SOULERIEZ").
dico("S", 9, "SOULERONS").
dico("S", 9, "SOULERONT").
dico("S", 9, "SOULEVAIS").
dico("S", 9, "SOULEVAIT").
dico("S", 9, "SOULEVANT").
dico("S", 9, "SOULEVEES").
dico("S", 9, "SOULEVENT").
dico("S", 9, "SOULEVERA").
dico("S", 9, "SOULEVIEZ").
dico("S", 9, "SOULEVONS").
dico("S", 9, "SOULIGNAI").
dico("S", 9, "SOULIGNAS").
dico("S", 9, "SOULIGNAT").
dico("S", 9, "SOULIGNEE").
dico("S", 9, "SOULIGNER").
dico("S", 9, "SOULIGNES").
dico("S", 9, "SOULIGNEZ").
dico("S", 9, "SOULONNES").
dico("S", 9, "SOUMETTES").
dico("S", 9, "SOUMETTEZ").
dico("S", 9, "SOUMETTRA").
dico("S", 9, "SOUMETTRE").
dico("S", 9, "SOUMIRENT").
dico("S", 9, "SOUMISSES").
dico("S", 9, "SOUPAIENT").
dico("S", 9, "SOUPASSES").
dico("S", 9, "SOUPCONNA").
dico("S", 9, "SOUPCONNE").
dico("S", 9, "SOUPENTES").
dico("S", 9, "SOUPERAIS").
dico("S", 9, "SOUPERAIT").
dico("S", 9, "SOUPERENT").
dico("S", 9, "SOUPERIEZ").
dico("S", 9, "SOUPERONS").
dico("S", 9, "SOUPERONT").
dico("S", 9, "SOUPESAIS").
dico("S", 9, "SOUPESAIT").
dico("S", 9, "SOUPESANT").
dico("S", 9, "SOUPESEES").
dico("S", 9, "SOUPESENT").
dico("S", 9, "SOUPESERA").
dico("S", 9, "SOUPESIEZ").
dico("S", 9, "SOUPESONS").
dico("S", 9, "SOUPEUSES").
dico("S", 9, "SOUPIERES").
dico("S", 9, "SOUPIRAIL").
dico("S", 9, "SOUPIRAIS").
dico("S", 9, "SOUPIRAIT").
dico("S", 9, "SOUPIRANT").
dico("S", 9, "SOUPIRAUX").
dico("S", 9, "SOUPIREES").
dico("S", 9, "SOUPIRENT").
dico("S", 9, "SOUPIRERA").
dico("S", 9, "SOUPIRIEZ").
dico("S", 9, "SOUPIRONS").
dico("S", 9, "SOUPLESSE").
dico("S", 9, "SOUQUAMES").
dico("S", 9, "SOUQUASSE").
dico("S", 9, "SOUQUATES").
dico("S", 9, "SOUQUERAI").
dico("S", 9, "SOUQUERAS").
dico("S", 9, "SOUQUEREZ").
dico("S", 9, "SOUQUIONS").
dico("S", 9, "SOURCEURS").
dico("S", 9, "SOURCEUSE").
dico("S", 9, "SOURCIERE").
dico("S", 9, "SOURCIERS").
dico("S", 9, "SOURCILLA").
dico("S", 9, "SOURCILLE").
dico("S", 9, "SOURDINES").
dico("S", 9, "SOURIANTE").
dico("S", 9, "SOURIANTS").
dico("S", 9, "SOURICEAU").
dico("S", 9, "SOURICIER").
dico("S", 9, "SOURIIONS").
dico("S", 9, "SOURIRAIS").
dico("S", 9, "SOURIRAIT").
dico("S", 9, "SOURIRENT").
dico("S", 9, "SOURIRIEZ").
dico("S", 9, "SOURIRONS").
dico("S", 9, "SOURIRONT").
dico("S", 9, "SOURISSES").
dico("S", 9, "SOURNOISE").
dico("S", 9, "SOUSCRIRA").
dico("S", 9, "SOUSCRIRE").
dico("S", 9, "SOUSCRITE").
dico("S", 9, "SOUSCRITS").
dico("S", 9, "SOUSCRIVE").
dico("S", 9, "SOUSSIGNE").
dico("S", 9, "SOUSTRAIE").
dico("S", 9, "SOUSTRAIS").
dico("S", 9, "SOUSTRAIT").
dico("S", 9, "SOUTACHAI").
dico("S", 9, "SOUTACHAS").
dico("S", 9, "SOUTACHAT").
dico("S", 9, "SOUTACHEE").
dico("S", 9, "SOUTACHER").
dico("S", 9, "SOUTACHES").
dico("S", 9, "SOUTACHEZ").
dico("S", 9, "SOUTASSES").
dico("S", 9, "SOUTENAIS").
dico("S", 9, "SOUTENAIT").
dico("S", 9, "SOUTENANT").
dico("S", 9, "SOUTENEUR").
dico("S", 9, "SOUTENIEZ").
dico("S", 9, "SOUTENONS").
dico("S", 9, "SOUTENUES").
dico("S", 9, "SOUTIENNE").
dico("S", 9, "SOUTINMES").
dico("S", 9, "SOUTINSSE").
dico("S", 9, "SOUTINTES").
dico("S", 9, "SOUTIRAGE").
dico("S", 9, "SOUTIRAIS").
dico("S", 9, "SOUTIRAIT").
dico("S", 9, "SOUTIRANT").
dico("S", 9, "SOUTIREES").
dico("S", 9, "SOUTIRENT").
dico("S", 9, "SOUTIRERA").
dico("S", 9, "SOUTIRIEZ").
dico("S", 9, "SOUTIRONS").
dico("S", 9, "SOUTRAGES").
dico("S", 9, "SOUVENAIS").
dico("S", 9, "SOUVENAIT").
dico("S", 9, "SOUVENANT").
dico("S", 9, "SOUVENIEZ").
dico("S", 9, "SOUVENIRS").
dico("S", 9, "SOUVENONS").
dico("S", 9, "SOUVENUES").
dico("S", 9, "SOUVERAIN").
dico("S", 9, "SOUVIENNE").
dico("S", 9, "SOUVINMES").
dico("S", 9, "SOUVINSSE").
dico("S", 9, "SOUVINTES").
dico("S", 9, "SOUVLAKIS").
dico("S", 9, "SOVIETISA").
dico("S", 9, "SOVIETISE").
dico("S", 9, "SOVKHOZES").
dico("S", 9, "SPACIEUSE").
dico("S", 9, "SPADASSIN").
dico("S", 9, "SPAETZLIS").
dico("S", 9, "SPAGHETTI").
dico("S", 9, "SPARADRAP").
dico("S", 9, "SPARDECKS").
dico("S", 9, "SPARGOUTE").
dico("S", 9, "SPARKLETS").
dico("S", 9, "SPARTEINE").
dico("S", 9, "SPARTERIE").
dico("S", 9, "SPARTIATE").
dico("S", 9, "SPATANGUE").
dico("S", 9, "SPATHIQUE").
dico("S", 9, "SPATIALES").
dico("S", 9, "SPATIONEF").
dico("S", 9, "SPATULEES").
dico("S", 9, "SPEAKEASY").
dico("S", 9, "SPECIALES").
dico("S", 9, "SPECIEUSE").
dico("S", 9, "SPECIFIAI").
dico("S", 9, "SPECIFIAS").
dico("S", 9, "SPECIFIAT").
dico("S", 9, "SPECIFIEE").
dico("S", 9, "SPECIFIER").
dico("S", 9, "SPECIFIES").
dico("S", 9, "SPECIFIEZ").
dico("S", 9, "SPECIMENS").
dico("S", 9, "SPECTACLE").
dico("S", 9, "SPECTRALE").
dico("S", 9, "SPECTRAUX").
dico("S", 9, "SPECULAIS").
dico("S", 9, "SPECULAIT").
dico("S", 9, "SPECULANT").
dico("S", 9, "SPECULAUS").
dico("S", 9, "SPECULENT").
dico("S", 9, "SPECULERA").
dico("S", 9, "SPECULIEZ").
dico("S", 9, "SPECULONS").
dico("S", 9, "SPECULOOS").
dico("S", 9, "SPECULUMS").
dico("S", 9, "SPEEDAMES").
dico("S", 9, "SPEEDASSE").
dico("S", 9, "SPEEDATES").
dico("S", 9, "SPEEDERAI").
dico("S", 9, "SPEEDERAS").
dico("S", 9, "SPEEDEREZ").
dico("S", 9, "SPEEDIONS").
dico("S", 9, "SPEEDWAYS").
dico("S", 9, "SPERGULES").
dico("S", 9, "SPERMATIE").
dico("S", 9, "SPERMINES").
dico("S", 9, "SPHACELES").
dico("S", 9, "SPHAGNALE").
dico("S", 9, "SPHAIGNES").
dico("S", 9, "SPHENODON").
dico("S", 9, "SPHENOIDE").
dico("S", 9, "SPHERIQUE").
dico("S", 9, "SPHEROIDE").
dico("S", 9, "SPHERULES").
dico("S", 9, "SPHINCTER").
dico("S", 9, "SPHINGIDE").
dico("S", 9, "SPHYRENES").
dico("S", 9, "SPICILEGE").
dico("S", 9, "SPINACKER").
dico("S", 9, "SPINALIEN").
dico("S", 9, "SPINELLES").
dico("S", 9, "SPINNAKER").
dico("S", 9, "SPIRACLES").
dico("S", 9, "SPIRALEES").
dico("S", 9, "SPIRANTES").
dico("S", 9, "SPIRIFERS").
dico("S", 9, "SPIRILLES").
dico("S", 9, "SPIRITAIN").
dico("S", 9, "SPIRITUAL").
dico("S", 9, "SPIRITUEL").
dico("S", 9, "SPIROGYRE").
dico("S", 9, "SPIROIDAL").
dico("S", 9, "SPIRORBES").
dico("S", 9, "SPIRULINE").
dico("S", 9, "SPITANTES").
dico("S", 9, "SPITTANTE").
dico("S", 9, "SPITTANTS").
dico("S", 9, "SPLENDEUR").
dico("S", 9, "SPLENDIDE").
dico("S", 9, "SPLENIQUE").
dico("S", 9, "SPLENITES").
dico("S", 9, "SPOLIAMES").
dico("S", 9, "SPOLIASSE").
dico("S", 9, "SPOLIATES").
dico("S", 9, "SPOLIERAI").
dico("S", 9, "SPOLIERAS").
dico("S", 9, "SPOLIEREZ").
dico("S", 9, "SPOLIIONS").
dico("S", 9, "SPONDYLES").
dico("S", 9, "SPONGIEUX").
dico("S", 9, "SPONGILLE").
dico("S", 9, "SPONSORAT").
dico("S", 9, "SPONTANEE").
dico("S", 9, "SPONTANES").
dico("S", 9, "SPORANGES").
dico("S", 9, "SPORIDIES").
dico("S", 9, "SPORIFERE").
dico("S", 9, "SPOROGONE").
dico("S", 9, "SPORTIVES").
dico("S", 9, "SPORTSMAN").
dico("S", 9, "SPORTSMEN").
dico("S", 9, "SPORTULES").
dico("S", 9, "SPORTWEAR").
dico("S", 9, "SPORULAIS").
dico("S", 9, "SPORULAIT").
dico("S", 9, "SPORULANT").
dico("S", 9, "SPORULENT").
dico("S", 9, "SPORULERA").
dico("S", 9, "SPORULIEZ").
dico("S", 9, "SPORULONS").
dico("S", 9, "SPOUTNIKS").
dico("S", 9, "SPRINGBOK").
dico("S", 9, "SPRINGERS").
dico("S", 9, "SPRINKLER").
dico("S", 9, "SPRINTAIS").
dico("S", 9, "SPRINTAIT").
dico("S", 9, "SPRINTANT").
dico("S", 9, "SPRINTENT").
dico("S", 9, "SPRINTERA").
dico("S", 9, "SPRINTERS").
dico("S", 9, "SPRINTEUR").
dico("S", 9, "SPRINTIEZ").
dico("S", 9, "SPRINTONS").
dico("S", 9, "SPUMANTES").
dico("S", 9, "SPUMEUSES").
dico("S", 9, "SPUMOSITE").
dico("S", 9, "SQUALIDES").
dico("S", 9, "SQUAMATES").
dico("S", 9, "SQUAMEUSE").
dico("S", 9, "SQUAMULES").
dico("S", 9, "SQUATINAS").
dico("S", 9, "SQUATINES").
dico("S", 9, "SQUATTAIS").
dico("S", 9, "SQUATTAIT").
dico("S", 9, "SQUATTANT").
dico("S", 9, "SQUATTEES").
dico("S", 9, "SQUATTENT").
dico("S", 9, "SQUATTERA").
dico("S", 9, "SQUATTERS").
dico("S", 9, "SQUATTEUR").
dico("S", 9, "SQUATTIEZ").
dico("S", 9, "SQUATTONS").
dico("S", 9, "SQUEEZAIS").
dico("S", 9, "SQUEEZAIT").
dico("S", 9, "SQUEEZANT").
dico("S", 9, "SQUEEZEES").
dico("S", 9, "SQUEEZENT").
dico("S", 9, "SQUEEZERA").
dico("S", 9, "SQUEEZIEZ").
dico("S", 9, "SQUEEZONS").
dico("S", 9, "SQUELETTE").
dico("S", 9, "SQUIRREUX").
dico("S", 9, "SQUIRRHES").
dico("S", 9, "STABILISA").
dico("S", 9, "STABILISE").
dico("S", 9, "STABILITE").
dico("S", 9, "STACCATOS").
dico("S", 9, "STADIERES").
dico("S", 9, "STAFFAMES").
dico("S", 9, "STAFFASSE").
dico("S", 9, "STAFFATES").
dico("S", 9, "STAFFERAI").
dico("S", 9, "STAFFERAS").
dico("S", 9, "STAFFEREZ").
dico("S", 9, "STAFFEURS").
dico("S", 9, "STAFFEUSE").
dico("S", 9, "STAFFIONS").
dico("S", 9, "STAGIAIRE").
dico("S", 9, "STAGNAMES").
dico("S", 9, "STAGNANTE").
dico("S", 9, "STAGNANTS").
dico("S", 9, "STAGNASSE").
dico("S", 9, "STAGNATES").
dico("S", 9, "STAGNERAI").
dico("S", 9, "STAGNERAS").
dico("S", 9, "STAGNEREZ").
dico("S", 9, "STAGNIONS").
dico("S", 9, "STAKNINGS").
dico("S", 9, "STALINIEN").
dico("S", 9, "STAMINALE").
dico("S", 9, "STAMINAUX").
dico("S", 9, "STAMINEES").
dico("S", 9, "STANDARDS").
dico("S", 9, "STANDINGS").
dico("S", 9, "STANNEUSE").
dico("S", 9, "STANNIQUE").
dico("S", 9, "STAPHYLIN").
dico("S", 9, "STARIFIAI").
dico("S", 9, "STARIFIAS").
dico("S", 9, "STARIFIAT").
dico("S", 9, "STARIFIEE").
dico("S", 9, "STARIFIER").
dico("S", 9, "STARIFIES").
dico("S", 9, "STARIFIEZ").
dico("S", 9, "STARISAIS").
dico("S", 9, "STARISAIT").
dico("S", 9, "STARISANT").
dico("S", 9, "STARISEES").
dico("S", 9, "STARISENT").
dico("S", 9, "STARISERA").
dico("S", 9, "STARISIEZ").
dico("S", 9, "STARISONS").
dico("S", 9, "STARKINGS").
dico("S", 9, "STARLETTE").
dico("S", 9, "STAROSTES").
dico("S", 9, "STATIONNA").
dico("S", 9, "STATIONNE").
dico("S", 9, "STATIQUES").
dico("S", 9, "STATISMES").
dico("S", 9, "STATUAIRE").
dico("S", 9, "STATUAMES").
dico("S", 9, "STATUASSE").
dico("S", 9, "STATUATES").
dico("S", 9, "STATUERAI").
dico("S", 9, "STATUERAS").
dico("S", 9, "STATUEREZ").
dico("S", 9, "STATUETTE").
dico("S", 9, "STATUFIAI").
dico("S", 9, "STATUFIAS").
dico("S", 9, "STATUFIAT").
dico("S", 9, "STATUFIEE").
dico("S", 9, "STATUFIER").
dico("S", 9, "STATUFIES").
dico("S", 9, "STATUFIEZ").
dico("S", 9, "STATUIONS").
dico("S", 9, "STEARATES").
dico("S", 9, "STEARINES").
dico("S", 9, "STEARIQUE").
dico("S", 9, "STEARYLES").
dico("S", 9, "STEATITES").
dico("S", 9, "STEATOMES").
dico("S", 9, "STEATOSES").
dico("S", 9, "STEENBOKS").
dico("S", 9, "STEGOMYAS").
dico("S", 9, "STEGOMYIA").
dico("S", 9, "STEGOMYIE").
dico("S", 9, "STEINBOCK").
dico("S", 9, "STELLAGES").
dico("S", 9, "STELLAIRE").
dico("S", 9, "STELLITES").
dico("S", 9, "STEMMATES").
dico("S", 9, "STENOSAGE").
dico("S", 9, "STENOSAIS").
dico("S", 9, "STENOSAIT").
dico("S", 9, "STENOSANT").
dico("S", 9, "STENOSEES").
dico("S", 9, "STENOSENT").
dico("S", 9, "STENOSERA").
dico("S", 9, "STENOSIEZ").
dico("S", 9, "STENOSONS").
dico("S", 9, "STENOTYPA").
dico("S", 9, "STENOTYPE").
dico("S", 9, "STEPPAGES").
dico("S", 9, "STEPPEURS").
dico("S", 9, "STEPPIQUE").
dico("S", 9, "STERADIAN").
dico("S", 9, "STERAIENT").
dico("S", 9, "STERASSES").
dico("S", 9, "STERCORAL").
dico("S", 9, "STEREODUC").
dico("S", 9, "STERERAIS").
dico("S", 9, "STERERAIT").
dico("S", 9, "STERERENT").
dico("S", 9, "STERERIEZ").
dico("S", 9, "STERERONS").
dico("S", 9, "STERERONT").
dico("S", 9, "STERFPUTS").
dico("S", 9, "STERILETS").
dico("S", 9, "STERILISA").
dico("S", 9, "STERILISE").
dico("S", 9, "STERILITE").
dico("S", 9, "STERIQUES").
dico("S", 9, "STERLINGS").
dico("S", 9, "STERNALES").
dico("S", 9, "STERNITES").
dico("S", 9, "STEROIDES").
dico("S", 9, "STHENIQUE").
dico("S", 9, "STIGMATES").
dico("S", 9, "STIMUGENE").
dico("S", 9, "STIMULAIS").
dico("S", 9, "STIMULAIT").
dico("S", 9, "STIMULANT").
dico("S", 9, "STIMULEES").
dico("S", 9, "STIMULENT").
dico("S", 9, "STIMULERA").
dico("S", 9, "STIMULIEZ").
dico("S", 9, "STIMULINE").
dico("S", 9, "STIMULONS").
dico("S", 9, "STIPENDIA").
dico("S", 9, "STIPENDIE").
dico("S", 9, "STIPITEES").
dico("S", 9, "STIPULAIS").
dico("S", 9, "STIPULAIT").
dico("S", 9, "STIPULANT").
dico("S", 9, "STIPULEES").
dico("S", 9, "STIPULENT").
dico("S", 9, "STIPULERA").
dico("S", 9, "STIPULIEZ").
dico("S", 9, "STIPULONS").
dico("S", 9, "STOCKAGES").
dico("S", 9, "STOCKAMES").
dico("S", 9, "STOCKASSE").
dico("S", 9, "STOCKATES").
dico("S", 9, "STOCKERAI").
dico("S", 9, "STOCKERAS").
dico("S", 9, "STOCKEREZ").
dico("S", 9, "STOCKIONS").
dico("S", 9, "STOCKISTE").
dico("S", 9, "STOICIENS").
dico("S", 9, "STOICISME").
dico("S", 9, "STOLONIAL").
dico("S", 9, "STOMACALE").
dico("S", 9, "STOMACAUX").
dico("S", 9, "STOMATITE").
dico("S", 9, "STOMISEES").
dico("S", 9, "STOPPAGES").
dico("S", 9, "STOPPAMES").
dico("S", 9, "STOPPASSE").
dico("S", 9, "STOPPATES").
dico("S", 9, "STOPPERAI").
dico("S", 9, "STOPPERAS").
dico("S", 9, "STOPPEREZ").
dico("S", 9, "STOPPEURS").
dico("S", 9, "STOPPEUSE").
dico("S", 9, "STOPPIONS").
dico("S", 9, "STORISTES").
dico("S", 9, "STOTINKAS").
dico("S", 9, "STRABIQUE").
dico("S", 9, "STRABISME").
dico("S", 9, "STRADIOTE").
dico("S", 9, "STRADIOTS").
dico("S", 9, "STRAMOINE").
dico("S", 9, "STRANGULA").
dico("S", 9, "STRANGULE").
dico("S", 9, "STRAPPING").
dico("S", 9, "STRATEGES").
dico("S", 9, "STRATEGIE").
dico("S", 9, "STRATIFIA").
dico("S", 9, "STRATIFIE").
dico("S", 9, "STRATIOME").
dico("S", 9, "STRESSAIS").
dico("S", 9, "STRESSAIT").
dico("S", 9, "STRESSANT").
dico("S", 9, "STRESSEES").
dico("S", 9, "STRESSENT").
dico("S", 9, "STRESSERA").
dico("S", 9, "STRESSIEZ").
dico("S", 9, "STRESSONS").
dico("S", 9, "STRIAIENT").
dico("S", 9, "STRIASSES").
dico("S", 9, "STRIATION").
dico("S", 9, "STRICTION").
dico("S", 9, "STRIDENCE").
dico("S", 9, "STRIDENTE").
dico("S", 9, "STRIDENTS").
dico("S", 9, "STRIDULAI").
dico("S", 9, "STRIDULAS").
dico("S", 9, "STRIDULAT").
dico("S", 9, "STRIDULEE").
dico("S", 9, "STRIDULER").
dico("S", 9, "STRIDULES").
dico("S", 9, "STRIDULEZ").
dico("S", 9, "STRIERAIS").
dico("S", 9, "STRIERAIT").
dico("S", 9, "STRIERENT").
dico("S", 9, "STRIERIEZ").
dico("S", 9, "STRIERONS").
dico("S", 9, "STRIERONT").
dico("S", 9, "STRIGIDES").
dico("S", 9, "STRIGILES").
dico("S", 9, "STRIPAGES").
dico("S", 9, "STRIPPAIS").
dico("S", 9, "STRIPPAIT").
dico("S", 9, "STRIPPANT").
dico("S", 9, "STRIPPEES").
dico("S", 9, "STRIPPENT").
dico("S", 9, "STRIPPERA").
dico("S", 9, "STRIPPERS").
dico("S", 9, "STRIPPIEZ").
dico("S", 9, "STRIPPING").
dico("S", 9, "STRIPPONS").
dico("S", 9, "STROBILES").
dico("S", 9, "STRONGLES").
dico("S", 9, "STRONGYLE").
dico("S", 9, "STRONTIUM").
dico("S", 9, "STRUCTURA").
dico("S", 9, "STRUCTURE").
dico("S", 9, "STRYCHNEE").
dico("S", 9, "STRYCHNOS").
dico("S", 9, "STUCATEUR").
dico("S", 9, "STUDETTES").
dico("S", 9, "STUDIEUSE").
dico("S", 9, "STUPEFAIT").
dico("S", 9, "STUPEFIAI").
dico("S", 9, "STUPEFIAS").
dico("S", 9, "STUPEFIAT").
dico("S", 9, "STUPEFIEE").
dico("S", 9, "STUPEFIER").
dico("S", 9, "STUPEFIES").
dico("S", 9, "STUPEFIEZ").
dico("S", 9, "STUPIDITE").
dico("S", 9, "STUPOREUX").
dico("S", 9, "STUQUAMES").
dico("S", 9, "STUQUASSE").
dico("S", 9, "STUQUATES").
dico("S", 9, "STUQUERAI").
dico("S", 9, "STUQUERAS").
dico("S", 9, "STUQUEREZ").
dico("S", 9, "STUQUIONS").
dico("S", 9, "STURNIDES").
dico("S", 9, "STYLAIENT").
dico("S", 9, "STYLASSES").
dico("S", 9, "STYLERAIS").
dico("S", 9, "STYLERAIT").
dico("S", 9, "STYLERENT").
dico("S", 9, "STYLERIEZ").
dico("S", 9, "STYLERONS").
dico("S", 9, "STYLERONT").
dico("S", 9, "STYLICIEN").
dico("S", 9, "STYLIQUES").
dico("S", 9, "STYLISAIS").
dico("S", 9, "STYLISAIT").
dico("S", 9, "STYLISANT").
dico("S", 9, "STYLISEES").
dico("S", 9, "STYLISENT").
dico("S", 9, "STYLISERA").
dico("S", 9, "STYLISIEZ").
dico("S", 9, "STYLISMES").
dico("S", 9, "STYLISONS").
dico("S", 9, "STYLISTES").
dico("S", 9, "STYLOBATE").
dico("S", 9, "STYLOIDES").
dico("S", 9, "STYLOMINE").
dico("S", 9, "STYPTIQUE").
dico("S", 9, "STYROLENE").
dico("S", 9, "SUASSIONS").
dico("S", 9, "SUAVEMENT").
dico("S", 9, "SUBADULTE").
dico("S", 9, "SUBAERIEN").
dico("S", 9, "SUBAIGUES").
dico("S", 9, "SUBALPINE").
dico("S", 9, "SUBALPINS").
dico("S", 9, "SUBARIDES").
dico("S", 9, "SUBDIVISA").
dico("S", 9, "SUBDIVISE").
dico("S", 9, "SUBEREUSE").
dico("S", 9, "SUBERINES").
dico("S", 9, "SUBIRIONS").
dico("S", 9, "SUBISSAIS").
dico("S", 9, "SUBISSAIT").
dico("S", 9, "SUBISSANT").
dico("S", 9, "SUBISSENT").
dico("S", 9, "SUBISSIEZ").
dico("S", 9, "SUBISSONS").
dico("S", 9, "SUBJACENT").
dico("S", 9, "SUBJECTIF").
dico("S", 9, "SUBJUGUAI").
dico("S", 9, "SUBJUGUAS").
dico("S", 9, "SUBJUGUAT").
dico("S", 9, "SUBJUGUEE").
dico("S", 9, "SUBJUGUER").
dico("S", 9, "SUBJUGUES").
dico("S", 9, "SUBJUGUEZ").
dico("S", 9, "SUBLAIENT").
dico("S", 9, "SUBLASSES").
dico("S", 9, "SUBLERAIS").
dico("S", 9, "SUBLERAIT").
dico("S", 9, "SUBLERENT").
dico("S", 9, "SUBLERIEZ").
dico("S", 9, "SUBLERONS").
dico("S", 9, "SUBLERONT").
dico("S", 9, "SUBLIMAIS").
dico("S", 9, "SUBLIMAIT").
dico("S", 9, "SUBLIMANT").
dico("S", 9, "SUBLIMEES").
dico("S", 9, "SUBLIMENT").
dico("S", 9, "SUBLIMERA").
dico("S", 9, "SUBLIMIEZ").
dico("S", 9, "SUBLIMITE").
dico("S", 9, "SUBLIMONS").
dico("S", 9, "SUBMERGEA").
dico("S", 9, "SUBMERGEE").
dico("S", 9, "SUBMERGER").
dico("S", 9, "SUBMERGES").
dico("S", 9, "SUBMERGEZ").
dico("S", 9, "SUBODORAI").
dico("S", 9, "SUBODORAS").
dico("S", 9, "SUBODORAT").
dico("S", 9, "SUBODOREE").
dico("S", 9, "SUBODORER").
dico("S", 9, "SUBODORES").
dico("S", 9, "SUBODOREZ").
dico("S", 9, "SUBORNAIS").
dico("S", 9, "SUBORNAIT").
dico("S", 9, "SUBORNANT").
dico("S", 9, "SUBORNEES").
dico("S", 9, "SUBORNENT").
dico("S", 9, "SUBORNERA").
dico("S", 9, "SUBORNEUR").
dico("S", 9, "SUBORNIEZ").
dico("S", 9, "SUBORNONS").
dico("S", 9, "SUBPOENAS").
dico("S", 9, "SUBROGEAI").
dico("S", 9, "SUBROGEAS").
dico("S", 9, "SUBROGEAT").
dico("S", 9, "SUBROGEES").
dico("S", 9, "SUBROGENT").
dico("S", 9, "SUBROGERA").
dico("S", 9, "SUBROGIEZ").
dico("S", 9, "SUBSIDIAI").
dico("S", 9, "SUBSIDIAS").
dico("S", 9, "SUBSIDIAT").
dico("S", 9, "SUBSIDIEE").
dico("S", 9, "SUBSIDIER").
dico("S", 9, "SUBSIDIES").
dico("S", 9, "SUBSIDIEZ").
dico("S", 9, "SUBSISTAI").
dico("S", 9, "SUBSISTAS").
dico("S", 9, "SUBSISTAT").
dico("S", 9, "SUBSISTER").
dico("S", 9, "SUBSISTES").
dico("S", 9, "SUBSISTEZ").
dico("S", 9, "SUBSTANCE").
dico("S", 9, "SUBSTITUA").
dico("S", 9, "SUBSTITUE").
dico("S", 9, "SUBSTITUT").
dico("S", 9, "SUBSTRATS").
dico("S", 9, "SUBSUMAIS").
dico("S", 9, "SUBSUMAIT").
dico("S", 9, "SUBSUMANT").
dico("S", 9, "SUBSUMEES").
dico("S", 9, "SUBSUMENT").
dico("S", 9, "SUBSUMERA").
dico("S", 9, "SUBSUMIEZ").
dico("S", 9, "SUBSUMONS").
dico("S", 9, "SUBTILISA").
dico("S", 9, "SUBTILISE").
dico("S", 9, "SUBTILITE").
dico("S", 9, "SUBURBAIN").
dico("S", 9, "SUBVENAIS").
dico("S", 9, "SUBVENAIT").
dico("S", 9, "SUBVENANT").
dico("S", 9, "SUBVENIEZ").
dico("S", 9, "SUBVENONS").
dico("S", 9, "SUBVERSIF").
dico("S", 9, "SUBVERTIE").
dico("S", 9, "SUBVERTIR").
dico("S", 9, "SUBVERTIS").
dico("S", 9, "SUBVERTIT").
dico("S", 9, "SUBVIENNE").
dico("S", 9, "SUBVINMES").
dico("S", 9, "SUBVINSSE").
dico("S", 9, "SUBVINTES").
dico("S", 9, "SUCASSENT").
dico("S", 9, "SUCASSIEZ").
dico("S", 9, "SUCCEDAIS").
dico("S", 9, "SUCCEDAIT").
dico("S", 9, "SUCCEDANE").
dico("S", 9, "SUCCEDANT").
dico("S", 9, "SUCCEDENT").
dico("S", 9, "SUCCEDERA").
dico("S", 9, "SUCCEDIEZ").
dico("S", 9, "SUCCEDONS").
dico("S", 9, "SUCCESSIF").
dico("S", 9, "SUCCINCTE").
dico("S", 9, "SUCCINCTS").
dico("S", 9, "SUCCOMBAI").
dico("S", 9, "SUCCOMBAS").
dico("S", 9, "SUCCOMBAT").
dico("S", 9, "SUCCOMBER").
dico("S", 9, "SUCCOMBES").
dico("S", 9, "SUCCOMBEZ").
dico("S", 9, "SUCCULENT").
dico("S", 9, "SUCEMENTS").
dico("S", 9, "SUCERIONS").
dico("S", 9, "SUCOTAMES").
dico("S", 9, "SUCOTASSE").
dico("S", 9, "SUCOTATES").
dico("S", 9, "SUCOTERAI").
dico("S", 9, "SUCOTERAS").
dico("S", 9, "SUCOTEREZ").
dico("S", 9, "SUCOTIONS").
dico("S", 9, "SUCRAIENT").
dico("S", 9, "SUCRANTES").
dico("S", 9, "SUCRASSES").
dico("S", 9, "SUCRERAIS").
dico("S", 9, "SUCRERAIT").
dico("S", 9, "SUCRERENT").
dico("S", 9, "SUCRERIES").
dico("S", 9, "SUCRERIEZ").
dico("S", 9, "SUCRERONS").
dico("S", 9, "SUCRERONT").
dico("S", 9, "SUCRETTES").
dico("S", 9, "SUCRIERES").
dico("S", 9, "SUDATIONS").
dico("S", 9, "SUDATOIRE").
dico("S", 9, "SUDORALES").
dico("S", 9, "SUEDOISES").
dico("S", 9, "SUERAIENT").
dico("S", 9, "SUFFIRAIS").
dico("S", 9, "SUFFIRAIT").
dico("S", 9, "SUFFIRENT").
dico("S", 9, "SUFFIRIEZ").
dico("S", 9, "SUFFIRONS").
dico("S", 9, "SUFFIRONT").
dico("S", 9, "SUFFISAIS").
dico("S", 9, "SUFFISAIT").
dico("S", 9, "SUFFISANT").
dico("S", 9, "SUFFISENT").
dico("S", 9, "SUFFISIEZ").
dico("S", 9, "SUFFISONS").
dico("S", 9, "SUFFISSES").
dico("S", 9, "SUFFIXAIS").
dico("S", 9, "SUFFIXAIT").
dico("S", 9, "SUFFIXALE").
dico("S", 9, "SUFFIXANT").
dico("S", 9, "SUFFIXAUX").
dico("S", 9, "SUFFIXEES").
dico("S", 9, "SUFFIXENT").
dico("S", 9, "SUFFIXERA").
dico("S", 9, "SUFFIXIEZ").
dico("S", 9, "SUFFIXONS").
dico("S", 9, "SUFFOCANT").
dico("S", 9, "SUFFOQUAI").
dico("S", 9, "SUFFOQUAS").
dico("S", 9, "SUFFOQUAT").
dico("S", 9, "SUFFOQUEE").
dico("S", 9, "SUFFOQUER").
dico("S", 9, "SUFFOQUES").
dico("S", 9, "SUFFOQUEZ").
dico("S", 9, "SUFFRAGES").
dico("S", 9, "SUFFUSION").
dico("S", 9, "SUGGERAIS").
dico("S", 9, "SUGGERAIT").
dico("S", 9, "SUGGERANT").
dico("S", 9, "SUGGEREES").
dico("S", 9, "SUGGERENT").
dico("S", 9, "SUGGERERA").
dico("S", 9, "SUGGERIEZ").
dico("S", 9, "SUGGERONS").
dico("S", 9, "SUGGESTIF").
dico("S", 9, "SUICIDAIS").
dico("S", 9, "SUICIDAIT").
dico("S", 9, "SUICIDANT").
dico("S", 9, "SUICIDEES").
dico("S", 9, "SUICIDENT").
dico("S", 9, "SUICIDERA").
dico("S", 9, "SUICIDIEZ").
dico("S", 9, "SUICIDONS").
dico("S", 9, "SUIFAIENT").
dico("S", 9, "SUIFASSES").
dico("S", 9, "SUIFERAIS").
dico("S", 9, "SUIFERAIT").
dico("S", 9, "SUIFERENT").
dico("S", 9, "SUIFERIEZ").
dico("S", 9, "SUIFERONS").
dico("S", 9, "SUIFERONT").
dico("S", 9, "SUIFFAMES").
dico("S", 9, "SUIFFASSE").
dico("S", 9, "SUIFFATES").
dico("S", 9, "SUIFFERAI").
dico("S", 9, "SUIFFERAS").
dico("S", 9, "SUIFFEREZ").
dico("S", 9, "SUIFFEUSE").
dico("S", 9, "SUIFFIONS").
dico("S", 9, "SUIFORMES").
dico("S", 9, "SUINTAMES").
dico("S", 9, "SUINTANTE").
dico("S", 9, "SUINTANTS").
dico("S", 9, "SUINTASSE").
dico("S", 9, "SUINTATES").
dico("S", 9, "SUINTERAI").
dico("S", 9, "SUINTERAS").
dico("S", 9, "SUINTEREZ").
dico("S", 9, "SUINTINES").
dico("S", 9, "SUINTIONS").
dico("S", 9, "SUIVAIENT").
dico("S", 9, "SUIVANTES").
dico("S", 9, "SUIVEUSES").
dico("S", 9, "SUIVIRENT").
dico("S", 9, "SUIVISMES").
dico("S", 9, "SUIVISSES").
dico("S", 9, "SUIVISTES").
dico("S", 9, "SUIVRIONS").
dico("S", 9, "SUJETIONS").
dico("S", 9, "SUKIYAKIS").
dico("S", 9, "SULCATURE").
dico("S", 9, "SULFACIDE").
dico("S", 9, "SULFAMIDE").
dico("S", 9, "SULFATAGE").
dico("S", 9, "SULFATAIS").
dico("S", 9, "SULFATAIT").
dico("S", 9, "SULFATANT").
dico("S", 9, "SULFATEES").
dico("S", 9, "SULFATENT").
dico("S", 9, "SULFATERA").
dico("S", 9, "SULFATEUR").
dico("S", 9, "SULFATIEZ").
dico("S", 9, "SULFATONS").
dico("S", 9, "SULFITAGE").
dico("S", 9, "SULFITAIS").
dico("S", 9, "SULFITAIT").
dico("S", 9, "SULFITANT").
dico("S", 9, "SULFITEES").
dico("S", 9, "SULFITENT").
dico("S", 9, "SULFITERA").
dico("S", 9, "SULFITIEZ").
dico("S", 9, "SULFITONS").
dico("S", 9, "SULFONAIS").
dico("S", 9, "SULFONAIT").
dico("S", 9, "SULFONANT").
dico("S", 9, "SULFONEES").
dico("S", 9, "SULFONENT").
dico("S", 9, "SULFONERA").
dico("S", 9, "SULFONIEZ").
dico("S", 9, "SULFONONS").
dico("S", 9, "SULFOSELS").
dico("S", 9, "SULFOXYDE").
dico("S", 9, "SULFURAGE").
dico("S", 9, "SULFURAIS").
dico("S", 9, "SULFURAIT").
dico("S", 9, "SULFURANT").
dico("S", 9, "SULFUREES").
dico("S", 9, "SULFURENT").
dico("S", 9, "SULFURERA").
dico("S", 9, "SULFUREUX").
dico("S", 9, "SULFURIEZ").
dico("S", 9, "SULFURISE").
dico("S", 9, "SULFURONS").
dico("S", 9, "SULPICIEN").
dico("S", 9, "SULPIRIDE").
dico("S", 9, "SULTANATS").
dico("S", 9, "SULVINITE").
dico("S", 9, "SUMERIENS").
dico("S", 9, "SUMOTORIS").
dico("S", 9, "SUNLIGHTS").
dico("S", 9, "SUNNISMES").
dico("S", 9, "SUPASSENT").
dico("S", 9, "SUPASSIEZ").
dico("S", 9, "SUPERAMAS").
dico("S", 9, "SUPERETTE").
dico("S", 9, "SUPERFINE").
dico("S", 9, "SUPERFINS").
dico("S", 9, "SUPERFLIC").
dico("S", 9, "SUPERFLUE").
dico("S", 9, "SUPERFLUS").
dico("S", 9, "SUPERIEUR").
dico("S", 9, "SUPERIONS").
dico("S", 9, "SUPERMALE").
dico("S", 9, "SUPERMANS").
dico("S", 9, "SUPERNOVA").
dico("S", 9, "SUPERPOSA").
dico("S", 9, "SUPERPOSE").
dico("S", 9, "SUPERSTAR").
dico("S", 9, "SUPERVISA").
dico("S", 9, "SUPERVISE").
dico("S", 9, "SUPPLANTA").
dico("S", 9, "SUPPLANTE").
dico("S", 9, "SUPPLEAIS").
dico("S", 9, "SUPPLEAIT").
dico("S", 9, "SUPPLEANT").
dico("S", 9, "SUPPLEEES").
dico("S", 9, "SUPPLEENT").
dico("S", 9, "SUPPLEERA").
dico("S", 9, "SUPPLEIEZ").
dico("S", 9, "SUPPLEONS").
dico("S", 9, "SUPPLETIF").
dico("S", 9, "SUPPLIAIS").
dico("S", 9, "SUPPLIAIT").
dico("S", 9, "SUPPLIANT").
dico("S", 9, "SUPPLICES").
dico("S", 9, "SUPPLICIA").
dico("S", 9, "SUPPLICIE").
dico("S", 9, "SUPPLIEES").
dico("S", 9, "SUPPLIENT").
dico("S", 9, "SUPPLIERA").
dico("S", 9, "SUPPLIIEZ").
dico("S", 9, "SUPPLIONS").
dico("S", 9, "SUPPLIQUE").
dico("S", 9, "SUPPORTAI").
dico("S", 9, "SUPPORTAS").
dico("S", 9, "SUPPORTAT").
dico("S", 9, "SUPPORTEE").
dico("S", 9, "SUPPORTER").
dico("S", 9, "SUPPORTES").
dico("S", 9, "SUPPORTEZ").
dico("S", 9, "SUPPOSAIS").
dico("S", 9, "SUPPOSAIT").
dico("S", 9, "SUPPOSANT").
dico("S", 9, "SUPPOSEES").
dico("S", 9, "SUPPOSENT").
dico("S", 9, "SUPPOSERA").
dico("S", 9, "SUPPOSIEZ").
dico("S", 9, "SUPPOSONS").
dico("S", 9, "SUPPRIMAI").
dico("S", 9, "SUPPRIMAS").
dico("S", 9, "SUPPRIMAT").
dico("S", 9, "SUPPRIMEE").
dico("S", 9, "SUPPRIMER").
dico("S", 9, "SUPPRIMES").
dico("S", 9, "SUPPRIMEZ").
dico("S", 9, "SUPPURAIS").
dico("S", 9, "SUPPURAIT").
dico("S", 9, "SUPPURANT").
dico("S", 9, "SUPPUREES").
dico("S", 9, "SUPPURENT").
dico("S", 9, "SUPPURERA").
dico("S", 9, "SUPPURIEZ").
dico("S", 9, "SUPPURONS").
dico("S", 9, "SUPPUTAIS").
dico("S", 9, "SUPPUTAIT").
dico("S", 9, "SUPPUTANT").
dico("S", 9, "SUPPUTEES").
dico("S", 9, "SUPPUTENT").
dico("S", 9, "SUPPUTERA").
dico("S", 9, "SUPPUTIEZ").
dico("S", 9, "SUPPUTONS").
dico("S", 9, "SUPREMUMS").
dico("S", 9, "SURABONDA").
dico("S", 9, "SURABONDE").
dico("S", 9, "SURACTIFS").
dico("S", 9, "SURACTIVA").
dico("S", 9, "SURACTIVE").
dico("S", 9, "SURAIGUES").
dico("S", 9, "SURAJOUTA").
dico("S", 9, "SURAJOUTE").
dico("S", 9, "SURANNEES").
dico("S", 9, "SURARMAIS").
dico("S", 9, "SURARMAIT").
dico("S", 9, "SURARMANT").
dico("S", 9, "SURARMEES").
dico("S", 9, "SURARMENT").
dico("S", 9, "SURARMERA").
dico("S", 9, "SURARMIEZ").
dico("S", 9, "SURARMONS").
dico("S", 9, "SURBAISSA").
dico("S", 9, "SURBAISSE").
dico("S", 9, "SURBOOKEE").
dico("S", 9, "SURBOOKES").
dico("S", 9, "SURCHARGE").
dico("S", 9, "SURCLASSA").
dico("S", 9, "SURCLASSE").
dico("S", 9, "SURCONTRA").
dico("S", 9, "SURCONTRE").
dico("S", 9, "SURCOSTAL").
dico("S", 9, "SURCOTAIS").
dico("S", 9, "SURCOTAIT").
dico("S", 9, "SURCOTANT").
dico("S", 9, "SURCOTEES").
dico("S", 9, "SURCOTENT").
dico("S", 9, "SURCOTERA").
dico("S", 9, "SURCOTIEZ").
dico("S", 9, "SURCOTONS").
dico("S", 9, "SURCOUPAI").
dico("S", 9, "SURCOUPAS").
dico("S", 9, "SURCOUPAT").
dico("S", 9, "SURCOUPEE").
dico("S", 9, "SURCOUPER").
dico("S", 9, "SURCOUPES").
dico("S", 9, "SURCOUPEZ").
dico("S", 9, "SURCROITS").
dico("S", 9, "SURDORAIS").
dico("S", 9, "SURDORAIT").
dico("S", 9, "SURDORANT").
dico("S", 9, "SURDOREES").
dico("S", 9, "SURDORENT").
dico("S", 9, "SURDORERA").
dico("S", 9, "SURDORIEZ").
dico("S", 9, "SURDORONS").
dico("S", 9, "SURDOSAGE").
dico("S", 9, "SURDOSAIS").
dico("S", 9, "SURDOSAIT").
dico("S", 9, "SURDOSANT").
dico("S", 9, "SURDOSEES").
dico("S", 9, "SURDOSENT").
dico("S", 9, "SURDOSERA").
dico("S", 9, "SURDOSIEZ").
dico("S", 9, "SURDOSONS").
dico("S", 9, "SURDOUEES").
dico("S", 9, "SURELEVAI").
dico("S", 9, "SURELEVAS").
dico("S", 9, "SURELEVAT").
dico("S", 9, "SURELEVEE").
dico("S", 9, "SURELEVER").
dico("S", 9, "SURELEVES").
dico("S", 9, "SURELEVEZ").
dico("S", 9, "SUREMPLOI").
dico("S", 9, "SUREQUIPA").
dico("S", 9, "SUREQUIPE").
dico("S", 9, "SURESTIMA").
dico("S", 9, "SURESTIME").
dico("S", 9, "SUREVALUA").
dico("S", 9, "SUREVALUE").
dico("S", 9, "SUREXCITA").
dico("S", 9, "SUREXCITE").
dico("S", 9, "SUREXPOSA").
dico("S", 9, "SUREXPOSE").
dico("S", 9, "SURFACAGE").
dico("S", 9, "SURFACAIS").
dico("S", 9, "SURFACAIT").
dico("S", 9, "SURFACANT").
dico("S", 9, "SURFACEES").
dico("S", 9, "SURFACENT").
dico("S", 9, "SURFACERA").
dico("S", 9, "SURFACIEZ").
dico("S", 9, "SURFACONS").
dico("S", 9, "SURFAIENT").
dico("S", 9, "SURFAITES").
dico("S", 9, "SURFASSES").
dico("S", 9, "SURFERAIS").
dico("S", 9, "SURFERAIT").
dico("S", 9, "SURFERENT").
dico("S", 9, "SURFERIEZ").
dico("S", 9, "SURFERONS").
dico("S", 9, "SURFERONT").
dico("S", 9, "SURFEUSES").
dico("S", 9, "SURFILAGE").
dico("S", 9, "SURFILAIS").
dico("S", 9, "SURFILAIT").
dico("S", 9, "SURFILANT").
dico("S", 9, "SURFILEES").
dico("S", 9, "SURFILENT").
dico("S", 9, "SURFILERA").
dico("S", 9, "SURFILIEZ").
dico("S", 9, "SURFILONS").
dico("S", 9, "SURFIRENT").
dico("S", 9, "SURFISSES").
dico("S", 9, "SURFONDUE").
dico("S", 9, "SURFONDUS").
dico("S", 9, "SURFUSION").
dico("S", 9, "SURGELAIS").
dico("S", 9, "SURGELAIT").
dico("S", 9, "SURGELANT").
dico("S", 9, "SURGELEES").
dico("S", 9, "SURGELENT").
dico("S", 9, "SURGELERA").
dico("S", 9, "SURGELIEZ").
dico("S", 9, "SURGELONS").
dico("S", 9, "SURGEONNA").
dico("S", 9, "SURGEONNE").
dico("S", 9, "SURGIRAIS").
dico("S", 9, "SURGIRAIT").
dico("S", 9, "SURGIRENT").
dico("S", 9, "SURGIRIEZ").
dico("S", 9, "SURGIRONS").
dico("S", 9, "SURGIRONT").
dico("S", 9, "SURGISSES").
dico("S", 9, "SURGISSEZ").
dico("S", 9, "SURHAUSSA").
dico("S", 9, "SURHAUSSE").
dico("S", 9, "SURHOMMES").
dico("S", 9, "SURHUMAIN").
dico("S", 9, "SURICATES").
dico("S", 9, "SURIKATES").
dico("S", 9, "SURIMPOSA").
dico("S", 9, "SURIMPOSE").
dico("S", 9, "SURINAMES").
dico("S", 9, "SURINASSE").
dico("S", 9, "SURINATES").
dico("S", 9, "SURINERAI").
dico("S", 9, "SURINERAS").
dico("S", 9, "SURINEREZ").
dico("S", 9, "SURINIONS").
dico("S", 9, "SURIRIONS").
dico("S", 9, "SURISSAIS").
dico("S", 9, "SURISSAIT").
dico("S", 9, "SURISSANT").
dico("S", 9, "SURISSENT").
dico("S", 9, "SURISSIEZ").
dico("S", 9, "SURISSONS").
dico("S", 9, "SURJALAIS").
dico("S", 9, "SURJALAIT").
dico("S", 9, "SURJALANT").
dico("S", 9, "SURJALEES").
dico("S", 9, "SURJALENT").
dico("S", 9, "SURJALERA").
dico("S", 9, "SURJALIEZ").
dico("S", 9, "SURJALONS").
dico("S", 9, "SURJECTIF").
dico("S", 9, "SURJETAIS").
dico("S", 9, "SURJETAIT").
dico("S", 9, "SURJETANT").
dico("S", 9, "SURJETEES").
dico("S", 9, "SURJETIEZ").
dico("S", 9, "SURJETONS").
dico("S", 9, "SURJETTES").
dico("S", 9, "SURLIAMES").
dico("S", 9, "SURLIASSE").
dico("S", 9, "SURLIATES").
dico("S", 9, "SURLIERAI").
dico("S", 9, "SURLIERAS").
dico("S", 9, "SURLIEREZ").
dico("S", 9, "SURLIGNAI").
dico("S", 9, "SURLIGNAS").
dico("S", 9, "SURLIGNAT").
dico("S", 9, "SURLIGNEE").
dico("S", 9, "SURLIGNER").
dico("S", 9, "SURLIGNES").
dico("S", 9, "SURLIGNEZ").
dico("S", 9, "SURLIIONS").
dico("S", 9, "SURLIURES").
dico("S", 9, "SURLONGES").
dico("S", 9, "SURLOUAIS").
dico("S", 9, "SURLOUAIT").
dico("S", 9, "SURLOUANT").
dico("S", 9, "SURLOUEES").
dico("S", 9, "SURLOUENT").
dico("S", 9, "SURLOUERA").
dico("S", 9, "SURLOUIEZ").
dico("S", 9, "SURLOUONS").
dico("S", 9, "SURLOYERS").
dico("S", 9, "SURMENAGE").
dico("S", 9, "SURMENAIS").
dico("S", 9, "SURMENAIT").
dico("S", 9, "SURMENANT").
dico("S", 9, "SURMENEES").
dico("S", 9, "SURMENENT").
dico("S", 9, "SURMENERA").
dico("S", 9, "SURMENIEZ").
dico("S", 9, "SURMENONS").
dico("S", 9, "SURMONTAI").
dico("S", 9, "SURMONTAS").
dico("S", 9, "SURMONTAT").
dico("S", 9, "SURMONTEE").
dico("S", 9, "SURMONTER").
dico("S", 9, "SURMONTES").
dico("S", 9, "SURMONTEZ").
dico("S", 9, "SURMOULAI").
dico("S", 9, "SURMOULAS").
dico("S", 9, "SURMOULAT").
dico("S", 9, "SURMOULEE").
dico("S", 9, "SURMOULER").
dico("S", 9, "SURMOULES").
dico("S", 9, "SURMOULEZ").
dico("S", 9, "SURMULETS").
dico("S", 9, "SURMULOTS").
dico("S", 9, "SURNAGEAI").
dico("S", 9, "SURNAGEAS").
dico("S", 9, "SURNAGEAT").
dico("S", 9, "SURNAGENT").
dico("S", 9, "SURNAGERA").
dico("S", 9, "SURNAGIEZ").
dico("S", 9, "SURNOMBRE").
dico("S", 9, "SURNOMMAI").
dico("S", 9, "SURNOMMAS").
dico("S", 9, "SURNOMMAT").
dico("S", 9, "SURNOMMEE").
dico("S", 9, "SURNOMMER").
dico("S", 9, "SURNOMMES").
dico("S", 9, "SURNOMMEZ").
dico("S", 9, "SURNOTAIS").
dico("S", 9, "SURNOTAIT").
dico("S", 9, "SURNOTANT").
dico("S", 9, "SURNOTEES").
dico("S", 9, "SURNOTENT").
dico("S", 9, "SURNOTERA").
dico("S", 9, "SURNOTIEZ").
dico("S", 9, "SURNOTONS").
dico("S", 9, "SUROFFRES").
dico("S", 9, "SUROXYDAI").
dico("S", 9, "SUROXYDAS").
dico("S", 9, "SUROXYDAT").
dico("S", 9, "SUROXYDEE").
dico("S", 9, "SUROXYDER").
dico("S", 9, "SUROXYDES").
dico("S", 9, "SUROXYDEZ").
dico("S", 9, "SURPAIENT").
dico("S", 9, "SURPAIERA").
dico("S", 9, "SURPASSAI").
dico("S", 9, "SURPASSAS").
dico("S", 9, "SURPASSAT").
dico("S", 9, "SURPASSEE").
dico("S", 9, "SURPASSER").
dico("S", 9, "SURPASSES").
dico("S", 9, "SURPASSEZ").
dico("S", 9, "SURPATTES").
dico("S", 9, "SURPAYAIS").
dico("S", 9, "SURPAYAIT").
dico("S", 9, "SURPAYANT").
dico("S", 9, "SURPAYEES").
dico("S", 9, "SURPAYENT").
dico("S", 9, "SURPAYERA").
dico("S", 9, "SURPAYIEZ").
dico("S", 9, "SURPAYONS").
dico("S", 9, "SURPECHES").
dico("S", 9, "SURPEUPLE").
dico("S", 9, "SURPIQUAI").
dico("S", 9, "SURPIQUAS").
dico("S", 9, "SURPIQUAT").
dico("S", 9, "SURPIQUEE").
dico("S", 9, "SURPIQUER").
dico("S", 9, "SURPIQUES").
dico("S", 9, "SURPIQUEZ").
dico("S", 9, "SURPIQURE").
dico("S", 9, "SURPLACES").
dico("S", 9, "SURPLOMBA").
dico("S", 9, "SURPLOMBE").
dico("S", 9, "SURPLOMBS").
dico("S", 9, "SURPRENDS").
dico("S", 9, "SURPRENEZ").
dico("S", 9, "SURPRENNE").
dico("S", 9, "SURPRIMES").
dico("S", 9, "SURPRISES").
dico("S", 9, "SURPRISSE").
dico("S", 9, "SURPRITES").
dico("S", 9, "SURREELLE").
dico("S", 9, "SURREGIME").
dico("S", 9, "SURREMISE").
dico("S", 9, "SURRENALE").
dico("S", 9, "SURRENAUX").
dico("S", 9, "SURSATURA").
dico("S", 9, "SURSATURE").
dico("S", 9, "SURSAUTAI").
dico("S", 9, "SURSAUTAS").
dico("S", 9, "SURSAUTAT").
dico("S", 9, "SURSAUTER").
dico("S", 9, "SURSAUTES").
dico("S", 9, "SURSAUTEZ").
dico("S", 9, "SURSEANCE").
dico("S", 9, "SURSEMAIS").
dico("S", 9, "SURSEMAIT").
dico("S", 9, "SURSEMANT").
dico("S", 9, "SURSEMEES").
dico("S", 9, "SURSEMENT").
dico("S", 9, "SURSEMERA").
dico("S", 9, "SURSEMIEZ").
dico("S", 9, "SURSEMONS").
dico("S", 9, "SURSEOIRA").
dico("S", 9, "SURSIRENT").
dico("S", 9, "SURSISSES").
dico("S", 9, "SURSOIENT").
dico("S", 9, "SURSOLIDE").
dico("S", 9, "SURSOYAIS").
dico("S", 9, "SURSOYAIT").
dico("S", 9, "SURSOYANT").
dico("S", 9, "SURSOYIEZ").
dico("S", 9, "SURSOYONS").
dico("S", 9, "SURSTOCKA").
dico("S", 9, "SURSTOCKE").
dico("S", 9, "SURSTOCKS").
dico("S", 9, "SURTAXAIS").
dico("S", 9, "SURTAXAIT").
dico("S", 9, "SURTAXANT").
dico("S", 9, "SURTAXEES").
dico("S", 9, "SURTAXENT").
dico("S", 9, "SURTAXERA").
dico("S", 9, "SURTAXIEZ").
dico("S", 9, "SURTAXONS").
dico("S", 9, "SURTITRAI").
dico("S", 9, "SURTITRAS").
dico("S", 9, "SURTITRAT").
dico("S", 9, "SURTITREE").
dico("S", 9, "SURTITRER").
dico("S", 9, "SURTITRES").
dico("S", 9, "SURTITREZ").
dico("S", 9, "SURTOILEE").
dico("S", 9, "SURTOILES").
dico("S", 9, "SURTONDES").
dico("S", 9, "SURTONDEZ").
dico("S", 9, "SURTONDIS").
dico("S", 9, "SURTONDIT").
dico("S", 9, "SURTONDRA").
dico("S", 9, "SURTONDRE").
dico("S", 9, "SURTONDUE").
dico("S", 9, "SURTONDUS").
dico("S", 9, "SURTONTES").
dico("S", 9, "SURVALEUR").
dico("S", 9, "SURVEILLA").
dico("S", 9, "SURVEILLE").
dico("S", 9, "SURVENAIS").
dico("S", 9, "SURVENAIT").
dico("S", 9, "SURVENANT").
dico("S", 9, "SURVENDES").
dico("S", 9, "SURVENDEZ").
dico("S", 9, "SURVENDIS").
dico("S", 9, "SURVENDIT").
dico("S", 9, "SURVENDRA").
dico("S", 9, "SURVENDRE").
dico("S", 9, "SURVENDUE").
dico("S", 9, "SURVENDUS").
dico("S", 9, "SURVENIEZ").
dico("S", 9, "SURVENONS").
dico("S", 9, "SURVENTAT").
dico("S", 9, "SURVENTER").
dico("S", 9, "SURVENTES").
dico("S", 9, "SURVENUES").
dico("S", 9, "SURVESTES").
dico("S", 9, "SURVIENNE").
dico("S", 9, "SURVINMES").
dico("S", 9, "SURVINSSE").
dico("S", 9, "SURVINTES").
dico("S", 9, "SURVIRAGE").
dico("S", 9, "SURVIRAIS").
dico("S", 9, "SURVIRAIT").
dico("S", 9, "SURVIRANT").
dico("S", 9, "SURVIRENT").
dico("S", 9, "SURVIRERA").
dico("S", 9, "SURVIREUR").
dico("S", 9, "SURVIRIEZ").
dico("S", 9, "SURVIRONS").
dico("S", 9, "SURVIVAIS").
dico("S", 9, "SURVIVAIT").
dico("S", 9, "SURVIVANT").
dico("S", 9, "SURVIVENT").
dico("S", 9, "SURVIVIEZ").
dico("S", 9, "SURVIVONS").
dico("S", 9, "SURVIVRAI").
dico("S", 9, "SURVIVRAS").
dico("S", 9, "SURVIVREZ").
dico("S", 9, "SURVOLAIS").
dico("S", 9, "SURVOLAIT").
dico("S", 9, "SURVOLANT").
dico("S", 9, "SURVOLEES").
dico("S", 9, "SURVOLENT").
dico("S", 9, "SURVOLERA").
dico("S", 9, "SURVOLIEZ").
dico("S", 9, "SURVOLONS").
dico("S", 9, "SURVOLTAI").
dico("S", 9, "SURVOLTAS").
dico("S", 9, "SURVOLTAT").
dico("S", 9, "SURVOLTEE").
dico("S", 9, "SURVOLTER").
dico("S", 9, "SURVOLTES").
dico("S", 9, "SURVOLTEZ").
dico("S", 9, "SUSCITAIS").
dico("S", 9, "SUSCITAIT").
dico("S", 9, "SUSCITANT").
dico("S", 9, "SUSCITEES").
dico("S", 9, "SUSCITENT").
dico("S", 9, "SUSCITERA").
dico("S", 9, "SUSCITIEZ").
dico("S", 9, "SUSCITONS").
dico("S", 9, "SUSNOMMEE").
dico("S", 9, "SUSNOMMES").
dico("S", 9, "SUSPECTAI").
dico("S", 9, "SUSPECTAS").
dico("S", 9, "SUSPECTAT").
dico("S", 9, "SUSPECTEE").
dico("S", 9, "SUSPECTER").
dico("S", 9, "SUSPECTES").
dico("S", 9, "SUSPECTEZ").
dico("S", 9, "SUSPENDES").
dico("S", 9, "SUSPENDEZ").
dico("S", 9, "SUSPENDIS").
dico("S", 9, "SUSPENDIT").
dico("S", 9, "SUSPENDRA").
dico("S", 9, "SUSPENDRE").
dico("S", 9, "SUSPENDUE").
dico("S", 9, "SUSPENDUS").
dico("S", 9, "SUSPENSES").
dico("S", 9, "SUSPENSIF").
dico("S", 9, "SUSPENTES").
dico("S", 9, "SUSPICION").
dico("S", 9, "SUSTENTAI").
dico("S", 9, "SUSTENTAS").
dico("S", 9, "SUSTENTAT").
dico("S", 9, "SUSTENTEE").
dico("S", 9, "SUSTENTER").
dico("S", 9, "SUSTENTES").
dico("S", 9, "SUSTENTEZ").
dico("S", 9, "SUSURRAIS").
dico("S", 9, "SUSURRAIT").
dico("S", 9, "SUSURRANT").
dico("S", 9, "SUSURREES").
dico("S", 9, "SUSURRENT").
dico("S", 9, "SUSURRERA").
dico("S", 9, "SUSURRIEZ").
dico("S", 9, "SUSURRONS").
dico("S", 9, "SUSVISEES").
dico("S", 9, "SUTURALES").
dico("S", 9, "SUTURAMES").
dico("S", 9, "SUTURASSE").
dico("S", 9, "SUTURATES").
dico("S", 9, "SUTURERAI").
dico("S", 9, "SUTURERAS").
dico("S", 9, "SUTUREREZ").
dico("S", 9, "SUTURIONS").
dico("S", 9, "SUZERAINE").
dico("S", 9, "SUZERAINS").
dico("S", 9, "SVASTIKAS").
dico("S", 9, "SVELTESSE").
dico("S", 9, "SWAHELIES").
dico("S", 9, "SWAHILIES").
dico("S", 9, "SWAPPAMES").
dico("S", 9, "SWAPPASSE").
dico("S", 9, "SWAPPATES").
dico("S", 9, "SWAPPERAI").
dico("S", 9, "SWAPPERAS").
dico("S", 9, "SWAPPEREZ").
dico("S", 9, "SWAPPIONS").
dico("S", 9, "SWASTIKAS").
dico("S", 9, "SWINGUAIS").
dico("S", 9, "SWINGUAIT").
dico("S", 9, "SWINGUANT").
dico("S", 9, "SWINGUENT").
dico("S", 9, "SWINGUERA").
dico("S", 9, "SWINGUIEZ").
dico("S", 9, "SWINGUONS").
dico("S", 9, "SWITCHAIS").
dico("S", 9, "SWITCHAIT").
dico("S", 9, "SWITCHANT").
dico("S", 9, "SWITCHEES").
dico("S", 9, "SWITCHENT").
dico("S", 9, "SWITCHERA").
dico("S", 9, "SWITCHIEZ").
dico("S", 9, "SWITCHONS").
dico("S", 9, "SYBARITES").
dico("S", 9, "SYCOMORES").
dico("S", 9, "SYLLEPSES").
dico("S", 9, "SYLPHIDES").
dico("S", 9, "SYLVAINES").
dico("S", 9, "SYLVANERS").
dico("S", 9, "SYLVESTRE").
dico("S", 9, "SYLVICOLE").
dico("S", 9, "SYLVIIDES").
dico("S", 9, "SYLVINITE").
dico("S", 9, "SYMBIONTE").
dico("S", 9, "SYMBIOSES").
dico("S", 9, "SYMBIOTES").
dico("S", 9, "SYMBOLISA").
dico("S", 9, "SYMBOLISE").
dico("S", 9, "SYMETRIES").
dico("S", 9, "SYMETRISA").
dico("S", 9, "SYMETRISE").
dico("S", 9, "SYMPATHIE").
dico("S", 9, "SYMPHONIE").
dico("S", 9, "SYMPHYSES").
dico("S", 9, "SYMPOSION").
dico("S", 9, "SYMPOSIUM").
dico("S", 9, "SYMPTOMES").
dico("S", 9, "SYNAGOGUE").
dico("S", 9, "SYNALEPHE").
dico("S", 9, "SYNAPTASE").
dico("S", 9, "SYNARCHIE").
dico("S", 9, "SYNCHRONE").
dico("S", 9, "SYNCITIUM").
dico("S", 9, "SYNCLINAL").
dico("S", 9, "SYNCOPAIS").
dico("S", 9, "SYNCOPAIT").
dico("S", 9, "SYNCOPALE").
dico("S", 9, "SYNCOPANT").
dico("S", 9, "SYNCOPAUX").
dico("S", 9, "SYNCOPEES").
dico("S", 9, "SYNCOPENT").
dico("S", 9, "SYNCOPERA").
dico("S", 9, "SYNCOPIEZ").
dico("S", 9, "SYNCOPONS").
dico("S", 9, "SYNCYTIAL").
dico("S", 9, "SYNCYTIUM").
dico("S", 9, "SYNDERMES").
dico("S", 9, "SYNDICALE").
dico("S", 9, "SYNDICATS").
dico("S", 9, "SYNDICAUX").
dico("S", 9, "SYNDIQUAI").
dico("S", 9, "SYNDIQUAS").
dico("S", 9, "SYNDIQUAT").
dico("S", 9, "SYNDIQUEE").
dico("S", 9, "SYNDIQUER").
dico("S", 9, "SYNDIQUES").
dico("S", 9, "SYNDIQUEZ").
dico("S", 9, "SYNDROMES").
dico("S", 9, "SYNECHIES").
dico("S", 9, "SYNERESES").
dico("S", 9, "SYNERGIDE").
dico("S", 9, "SYNERGIES").
dico("S", 9, "SYNGNATHE").
dico("S", 9, "SYNODALES").
dico("S", 9, "SYNODIQUE").
dico("S", 9, "SYNONYMES").
dico("S", 9, "SYNONYMIE").
dico("S", 9, "SYNOPSIES").
dico("S", 9, "SYNOSTOSE").
dico("S", 9, "SYNOVIALE").
dico("S", 9, "SYNOVIAUX").
dico("S", 9, "SYNOVITES").
dico("S", 9, "SYNTAGMES").
dico("S", 9, "SYNTHESES").
dico("S", 9, "SYNTONIES").
dico("S", 9, "SYNTONISA").
dico("S", 9, "SYNTONISE").
dico("S", 9, "SYPHILIDE").
dico("S", 9, "SYRIAQUES").
dico("S", 9, "SYRIENNES").
dico("S", 9, "SYRPHIDES").
dico("S", 9, "SYRRHAPTE").
dico("S", 9, "SZLACHTAS").
