dico("T", 10, "TABAGIQUES").
dico("T", 10, "TABAGISMES").
dico("T", 10, "TABASSAGES").
dico("T", 10, "TABASSAMES").
dico("T", 10, "TABASSASSE").
dico("T", 10, "TABASSATES").
dico("T", 10, "TABASSERAI").
dico("T", 10, "TABASSERAS").
dico("T", 10, "TABASSEREZ").
dico("T", 10, "TABASSIONS").
dico("T", 10, "TABATIERES").
dico("T", 10, "TABELLAIRE").
dico("T", 10, "TABELLIONS").
dico("T", 10, "TABERNACLE").
dico("T", 10, "TABETIQUES").
dico("T", 10, "TABLASSENT").
dico("T", 10, "TABLASSIEZ").
dico("T", 10, "TABLATURES").
dico("T", 10, "TABLEAUTIN").
dico("T", 10, "TABLERIONS").
dico("T", 10, "TABLETIERE").
dico("T", 10, "TABLETIERS").
dico("T", 10, "TABOUAIENT").
dico("T", 10, "TABOUASSES").
dico("T", 10, "TABOUERAIS").
dico("T", 10, "TABOUERAIT").
dico("T", 10, "TABOUERENT").
dico("T", 10, "TABOUERIEZ").
dico("T", 10, "TABOUERONS").
dico("T", 10, "TABOUERONT").
dico("T", 10, "TABOUISAIS").
dico("T", 10, "TABOUISAIT").
dico("T", 10, "TABOUISANT").
dico("T", 10, "TABOUISEES").
dico("T", 10, "TABOUISENT").
dico("T", 10, "TABOUISERA").
dico("T", 10, "TABOUISIEZ").
dico("T", 10, "TABOUISONS").
dico("T", 10, "TABULAIENT").
dico("T", 10, "TABULAIRES").
dico("T", 10, "TABULASSES").
dico("T", 10, "TABULATEUR").
dico("T", 10, "TABULATION").
dico("T", 10, "TABULERAIS").
dico("T", 10, "TABULERAIT").
dico("T", 10, "TABULERENT").
dico("T", 10, "TABULERIEZ").
dico("T", 10, "TABULERONS").
dico("T", 10, "TABULERONT").
dico("T", 10, "TACHASSENT").
dico("T", 10, "TACHASSIEZ").
dico("T", 10, "TACHERIONS").
dico("T", 10, "TACHETAMES").
dico("T", 10, "TACHETASSE").
dico("T", 10, "TACHETATES").
dico("T", 10, "TACHETIONS").
dico("T", 10, "TACHETTENT").
dico("T", 10, "TACHETTERA").
dico("T", 10, "TACHETURES").
dico("T", 10, "TACHYMETRE").
dico("T", 10, "TACITEMENT").
dico("T", 10, "TACITURNES").
dico("T", 10, "TACLASSENT").
dico("T", 10, "TACLASSIEZ").
dico("T", 10, "TACLERIONS").
dico("T", 10, "TACTICIENS").
dico("T", 10, "TACTICITES").
dico("T", 10, "TAEKWONDOS").
dico("T", 10, "TAGGASSENT").
dico("T", 10, "TAGGASSIEZ").
dico("T", 10, "TAGGERIONS").
dico("T", 10, "TAGUASSENT").
dico("T", 10, "TAGUASSIEZ").
dico("T", 10, "TAGUERIONS").
dico("T", 10, "TAHITIENNE").
dico("T", 10, "TAILLABLES").
dico("T", 10, "TAILLADAIS").
dico("T", 10, "TAILLADAIT").
dico("T", 10, "TAILLADANT").
dico("T", 10, "TAILLADEES").
dico("T", 10, "TAILLADENT").
dico("T", 10, "TAILLADERA").
dico("T", 10, "TAILLADIEZ").
dico("T", 10, "TAILLADONS").
dico("T", 10, "TAILLAIENT").
dico("T", 10, "TAILLASSES").
dico("T", 10, "TAILLAULES").
dico("T", 10, "TAILLERAIS").
dico("T", 10, "TAILLERAIT").
dico("T", 10, "TAILLERENT").
dico("T", 10, "TAILLERIES").
dico("T", 10, "TAILLERIEZ").
dico("T", 10, "TAILLERONS").
dico("T", 10, "TAILLERONT").
dico("T", 10, "TAILLEUSES").
dico("T", 10, "TAIWANAISE").
dico("T", 10, "TALASSIONS").
dico("T", 10, "TALENTUEUX").
dico("T", 10, "TALERAIENT").
dico("T", 10, "TALLASSENT").
dico("T", 10, "TALLASSIEZ").
dico("T", 10, "TALLERIONS").
dico("T", 10, "TALMUDIQUE").
dico("T", 10, "TALMUDISTE").
dico("T", 10, "TALOCHAGES").
dico("T", 10, "TALOCHAMES").
dico("T", 10, "TALOCHASSE").
dico("T", 10, "TALOCHATES").
dico("T", 10, "TALOCHERAI").
dico("T", 10, "TALOCHERAS").
dico("T", 10, "TALOCHEREZ").
dico("T", 10, "TALOCHIONS").
dico("T", 10, "TALONNADES").
dico("T", 10, "TALONNAGES").
dico("T", 10, "TALONNAMES").
dico("T", 10, "TALONNASSE").
dico("T", 10, "TALONNATES").
dico("T", 10, "TALONNERAI").
dico("T", 10, "TALONNERAS").
dico("T", 10, "TALONNEREZ").
dico("T", 10, "TALONNETTE").
dico("T", 10, "TALONNEURS").
dico("T", 10, "TALONNIERE").
dico("T", 10, "TALONNIONS").
dico("T", 10, "TALQUAIENT").
dico("T", 10, "TALQUASSES").
dico("T", 10, "TALQUERAIS").
dico("T", 10, "TALQUERAIT").
dico("T", 10, "TALQUERENT").
dico("T", 10, "TALQUERIEZ").
dico("T", 10, "TALQUERONS").
dico("T", 10, "TALQUERONT").
dico("T", 10, "TALQUEUSES").
dico("T", 10, "TALUTAIENT").
dico("T", 10, "TALUTASSES").
dico("T", 10, "TALUTERAIS").
dico("T", 10, "TALUTERAIT").
dico("T", 10, "TALUTERENT").
dico("T", 10, "TALUTERIEZ").
dico("T", 10, "TALUTERONS").
dico("T", 10, "TALUTERONT").
dico("T", 10, "TAMARINIER").
dico("T", 10, "TAMAZIGHTS").
dico("T", 10, "TAMBOUILLE").
dico("T", 10, "TAMBOURINA").
dico("T", 10, "TAMBOURINE").
dico("T", 10, "TAMBOURINS").
dico("T", 10, "TAMISAIENT").
dico("T", 10, "TAMISASSES").
dico("T", 10, "TAMISERAIS").
dico("T", 10, "TAMISERAIT").
dico("T", 10, "TAMISERENT").
dico("T", 10, "TAMISERIES").
dico("T", 10, "TAMISERIEZ").
dico("T", 10, "TAMISERONS").
dico("T", 10, "TAMISERONT").
dico("T", 10, "TAMISEUSES").
dico("T", 10, "TAMISIERES").
dico("T", 10, "TAMPONNADE").
dico("T", 10, "TAMPONNAGE").
dico("T", 10, "TAMPONNAIS").
dico("T", 10, "TAMPONNAIT").
dico("T", 10, "TAMPONNANT").
dico("T", 10, "TAMPONNEES").
dico("T", 10, "TAMPONNENT").
dico("T", 10, "TAMPONNERA").
dico("T", 10, "TAMPONNEUR").
dico("T", 10, "TAMPONNIER").
dico("T", 10, "TAMPONNIEZ").
dico("T", 10, "TAMPONNOIR").
dico("T", 10, "TAMPONNONS").
dico("T", 10, "TANCASSENT").
dico("T", 10, "TANCASSIEZ").
dico("T", 10, "TANCERIONS").
dico("T", 10, "TANDEMISTE").
dico("T", 10, "TANGENTIEL").
dico("T", 10, "TANGERINES").
dico("T", 10, "TANGUAIENT").
dico("T", 10, "TANGUASSES").
dico("T", 10, "TANGUERAIS").
dico("T", 10, "TANGUERAIT").
dico("T", 10, "TANGUERENT").
dico("T", 10, "TANGUERIEZ").
dico("T", 10, "TANGUERONS").
dico("T", 10, "TANGUERONT").
dico("T", 10, "TANGUIERES").
dico("T", 10, "TANISAIENT").
dico("T", 10, "TANISASSES").
dico("T", 10, "TANISERAIS").
dico("T", 10, "TANISERAIT").
dico("T", 10, "TANISERENT").
dico("T", 10, "TANISERIEZ").
dico("T", 10, "TANISERONS").
dico("T", 10, "TANISERONT").
dico("T", 10, "TANNASSENT").
dico("T", 10, "TANNASSIEZ").
dico("T", 10, "TANNERIONS").
dico("T", 10, "TANNISAGES").
dico("T", 10, "TANNISAMES").
dico("T", 10, "TANNISASSE").
dico("T", 10, "TANNISATES").
dico("T", 10, "TANNISERAI").
dico("T", 10, "TANNISERAS").
dico("T", 10, "TANNISEREZ").
dico("T", 10, "TANNISIONS").
dico("T", 10, "TANTRIQUES").
dico("T", 10, "TANTRISMES").
dico("T", 10, "TANZANIENS").
dico("T", 10, "TAPAGEAMES").
dico("T", 10, "TAPAGEASSE").
dico("T", 10, "TAPAGEATES").
dico("T", 10, "TAPAGERAIS").
dico("T", 10, "TAPAGERAIT").
dico("T", 10, "TAPAGERENT").
dico("T", 10, "TAPAGERIEZ").
dico("T", 10, "TAPAGERONS").
dico("T", 10, "TAPAGERONT").
dico("T", 10, "TAPAGEUSES").
dico("T", 10, "TAPASSIONS").
dico("T", 10, "TAPERAIENT").
dico("T", 10, "TAPINAIENT").
dico("T", 10, "TAPINASSES").
dico("T", 10, "TAPINERAIS").
dico("T", 10, "TAPINERAIT").
dico("T", 10, "TAPINERENT").
dico("T", 10, "TAPINERIEZ").
dico("T", 10, "TAPINERONS").
dico("T", 10, "TAPINERONT").
dico("T", 10, "TAPINEUSES").
dico("T", 10, "TAPIRAIENT").
dico("T", 10, "TAPISSAGES").
dico("T", 10, "TAPISSAMES").
dico("T", 10, "TAPISSASSE").
dico("T", 10, "TAPISSATES").
dico("T", 10, "TAPISSERAI").
dico("T", 10, "TAPISSERAS").
dico("T", 10, "TAPISSEREZ").
dico("T", 10, "TAPISSERIE").
dico("T", 10, "TAPISSEURS").
dico("T", 10, "TAPISSEUSE").
dico("T", 10, "TAPISSIERE").
dico("T", 10, "TAPISSIERS").
dico("T", 10, "TAPISSIONS").
dico("T", 10, "TAPOCHAMES").
dico("T", 10, "TAPOCHASSE").
dico("T", 10, "TAPOCHATES").
dico("T", 10, "TAPOCHERAI").
dico("T", 10, "TAPOCHERAS").
dico("T", 10, "TAPOCHEREZ").
dico("T", 10, "TAPOCHIONS").
dico("T", 10, "TAPONNAGES").
dico("T", 10, "TAPONNAMES").
dico("T", 10, "TAPONNASSE").
dico("T", 10, "TAPONNATES").
dico("T", 10, "TAPONNERAI").
dico("T", 10, "TAPONNERAS").
dico("T", 10, "TAPONNEREZ").
dico("T", 10, "TAPONNEURS").
dico("T", 10, "TAPONNEUSE").
dico("T", 10, "TAPONNIONS").
dico("T", 10, "TAPOTAIENT").
dico("T", 10, "TAPOTASSES").
dico("T", 10, "TAPOTEMENT").
dico("T", 10, "TAPOTERAIS").
dico("T", 10, "TAPOTERAIT").
dico("T", 10, "TAPOTERENT").
dico("T", 10, "TAPOTERIEZ").
dico("T", 10, "TAPOTERONS").
dico("T", 10, "TAPOTERONT").
dico("T", 10, "TAPUSCRITS").
dico("T", 10, "TAQUASSENT").
dico("T", 10, "TAQUASSIEZ").
dico("T", 10, "TAQUERIONS").
dico("T", 10, "TAQUINAMES").
dico("T", 10, "TAQUINASSE").
dico("T", 10, "TAQUINATES").
dico("T", 10, "TAQUINERAI").
dico("T", 10, "TAQUINERAS").
dico("T", 10, "TAQUINEREZ").
dico("T", 10, "TAQUINERIE").
dico("T", 10, "TAQUINIONS").
dico("T", 10, "TARABISCOT").
dico("T", 10, "TARABUSTAI").
dico("T", 10, "TARABUSTAS").
dico("T", 10, "TARABUSTAT").
dico("T", 10, "TARABUSTEE").
dico("T", 10, "TARABUSTER").
dico("T", 10, "TARABUSTES").
dico("T", 10, "TARABUSTEZ").
dico("T", 10, "TARASSIONS").
dico("T", 10, "TARAUDAGES").
dico("T", 10, "TARAUDAMES").
dico("T", 10, "TARAUDANTE").
dico("T", 10, "TARAUDANTS").
dico("T", 10, "TARAUDASSE").
dico("T", 10, "TARAUDATES").
dico("T", 10, "TARAUDERAI").
dico("T", 10, "TARAUDERAS").
dico("T", 10, "TARAUDEREZ").
dico("T", 10, "TARAUDEURS").
dico("T", 10, "TARAUDEUSE").
dico("T", 10, "TARAUDIONS").
dico("T", 10, "TARAVELLES").
dico("T", 10, "TARBOUCHES").
dico("T", 10, "TARDASSENT").
dico("T", 10, "TARDASSIEZ").
dico("T", 10, "TARDERIONS").
dico("T", 10, "TARDIGRADE").
dico("T", 10, "TARDILLONS").
dico("T", 10, "TARDIVETES").
dico("T", 10, "TARENTAISE").
dico("T", 10, "TARENTELLE").
dico("T", 10, "TARENTINES").
dico("T", 10, "TARENTULES").
dico("T", 10, "TARERAIENT").
dico("T", 10, "TARGUAIENT").
dico("T", 10, "TARGUASSES").
dico("T", 10, "TARGUERAIS").
dico("T", 10, "TARGUERAIT").
dico("T", 10, "TARGUERENT").
dico("T", 10, "TARGUERIEZ").
dico("T", 10, "TARGUERONS").
dico("T", 10, "TARGUERONT").
dico("T", 10, "TARICHEUTE").
dico("T", 10, "TARIFAIENT").
dico("T", 10, "TARIFAIRES").
dico("T", 10, "TARIFASSES").
dico("T", 10, "TARIFERAIS").
dico("T", 10, "TARIFERAIT").
dico("T", 10, "TARIFERENT").
dico("T", 10, "TARIFERIEZ").
dico("T", 10, "TARIFERONS").
dico("T", 10, "TARIFERONT").
dico("T", 10, "TARIFIAMES").
dico("T", 10, "TARIFIASSE").
dico("T", 10, "TARIFIATES").
dico("T", 10, "TARIFIERAI").
dico("T", 10, "TARIFIERAS").
dico("T", 10, "TARIFIEREZ").
dico("T", 10, "TARIFIIONS").
dico("T", 10, "TARIRAIENT").
dico("T", 10, "TARISSABLE").
dico("T", 10, "TARISSIONS").
dico("T", 10, "TARLATANES").
dico("T", 10, "TARMACADAM").
dico("T", 10, "TAROTEUSES").
dico("T", 10, "TARSIENNES").
dico("T", 10, "TARTELETTE").
dico("T", 10, "TARTEMPION").
dico("T", 10, "TARTIGNOLE").
dico("T", 10, "TARTINAMES").
dico("T", 10, "TARTINASSE").
dico("T", 10, "TARTINATES").
dico("T", 10, "TARTINERAI").
dico("T", 10, "TARTINERAS").
dico("T", 10, "TARTINEREZ").
dico("T", 10, "TARTINIONS").
dico("T", 10, "TARTIRIONS").
dico("T", 10, "TARTISSAIS").
dico("T", 10, "TARTISSAIT").
dico("T", 10, "TARTISSANT").
dico("T", 10, "TARTISSENT").
dico("T", 10, "TARTISSIEZ").
dico("T", 10, "TARTISSONS").
dico("T", 10, "TARTREUSES").
dico("T", 10, "TARTRIQUES").
dico("T", 10, "TARTUFERIE").
dico("T", 10, "TASMANIENS").
dico("T", 10, "TASSASSENT").
dico("T", 10, "TASSASSIEZ").
dico("T", 10, "TASSEMENTS").
dico("T", 10, "TASSERIONS").
dico("T", 10, "TATASSIONS").
dico("T", 10, "TATERAIENT").
dico("T", 10, "TATILLONNA").
dico("T", 10, "TATILLONNE").
dico("T", 10, "TATONNAMES").
dico("T", 10, "TATONNANTE").
dico("T", 10, "TATONNANTS").
dico("T", 10, "TATONNASSE").
dico("T", 10, "TATONNATES").
dico("T", 10, "TATONNERAI").
dico("T", 10, "TATONNERAS").
dico("T", 10, "TATONNEREZ").
dico("T", 10, "TATONNIONS").
dico("T", 10, "TATOUAIENT").
dico("T", 10, "TATOUASSES").
dico("T", 10, "TATOUERAIS").
dico("T", 10, "TATOUERAIT").
dico("T", 10, "TATOUERENT").
dico("T", 10, "TATOUERIEZ").
dico("T", 10, "TATOUERONS").
dico("T", 10, "TATOUERONT").
dico("T", 10, "TATOUEUSES").
dico("T", 10, "TATOUILLES").
dico("T", 10, "TAUDASSENT").
dico("T", 10, "TAUDASSIEZ").
dico("T", 10, "TAUDERIONS").
dico("T", 10, "TAUPASSENT").
dico("T", 10, "TAUPASSIEZ").
dico("T", 10, "TAUPERIONS").
dico("T", 10, "TAUPINIERE").
dico("T", 10, "TAURILLONS").
dico("T", 10, "TAUROBOLES").
dico("T", 10, "TAUTOLOGIE").
dico("T", 10, "TAUTOLOGUE").
dico("T", 10, "TAUTOMERES").
dico("T", 10, "TAUTOMERIE").
dico("T", 10, "TAVAIOLLES").
dico("T", 10, "TAVELAIENT").
dico("T", 10, "TAVELASSES").
dico("T", 10, "TAVELERENT").
dico("T", 10, "TAVELLERAI").
dico("T", 10, "TAVELLERAS").
dico("T", 10, "TAVELLEREZ").
dico("T", 10, "TAVERNIERE").
dico("T", 10, "TAVERNIERS").
dico("T", 10, "TAXASSIONS").
dico("T", 10, "TAXATRICES").
dico("T", 10, "TAXAUDIERS").
dico("T", 10, "TAXERAIENT").
dico("T", 10, "TAXIARQUES").
dico("T", 10, "TAXIDERMIE").
dico("T", 10, "TAXIMETRES").
dico("T", 10, "TAXINOMIES").
dico("T", 10, "TAXIPHONES").
dico("T", 10, "TAXONOMIES").
dico("T", 10, "TAYLORISAI").
dico("T", 10, "TAYLORISAS").
dico("T", 10, "TAYLORISAT").
dico("T", 10, "TAYLORISEE").
dico("T", 10, "TAYLORISER").
dico("T", 10, "TAYLORISES").
dico("T", 10, "TAYLORISEZ").
dico("T", 10, "TAYLORISME").
dico("T", 10, "TCHADIENNE").
dico("T", 10, "TCHARCHAFS").
dico("T", 10, "TCHATCHAIS").
dico("T", 10, "TCHATCHAIT").
dico("T", 10, "TCHATCHANT").
dico("T", 10, "TCHATCHEES").
dico("T", 10, "TCHATCHENT").
dico("T", 10, "TCHATCHERA").
dico("T", 10, "TCHATCHEUR").
dico("T", 10, "TCHATCHIEZ").
dico("T", 10, "TCHATCHONS").
dico("T", 10, "TCHERKESSE").
dico("T", 10, "TCHERNOZEM").
dico("T", 10, "TCHETCHENE").
dico("T", 10, "TECHNETIUM").
dico("T", 10, "TECHNICIEN").
dico("T", 10, "TECHNICISA").
dico("T", 10, "TECHNICISE").
dico("T", 10, "TECHNICITE").
dico("T", 10, "TECHNIQUES").
dico("T", 10, "TECHNISAIS").
dico("T", 10, "TECHNISAIT").
dico("T", 10, "TECHNISANT").
dico("T", 10, "TECHNISEES").
dico("T", 10, "TECHNISENT").
dico("T", 10, "TECHNISERA").
dico("T", 10, "TECHNISIEZ").
dico("T", 10, "TECHNISONS").
dico("T", 10, "TECHNOPOLE").
dico("T", 10, "TECTONIQUE").
dico("T", 10, "TEFLONISEE").
dico("T", 10, "TEFLONISES").
dico("T", 10, "TEGENAIRES").
dico("T", 10, "TEGEVISTES").
dico("T", 10, "TEHERANAIS").
dico("T", 10, "TEIGNAIENT").
dico("T", 10, "TEIGNEUSES").
dico("T", 10, "TEIGNIRENT").
dico("T", 10, "TEIGNISSES").
dico("T", 10, "TEILLAIENT").
dico("T", 10, "TEILLASSES").
dico("T", 10, "TEILLERAIS").
dico("T", 10, "TEILLERAIT").
dico("T", 10, "TEILLERENT").
dico("T", 10, "TEILLERIEZ").
dico("T", 10, "TEILLERONS").
dico("T", 10, "TEILLERONT").
dico("T", 10, "TEILLEUSES").
dico("T", 10, "TEINDRIONS").
dico("T", 10, "TEINTAIENT").
dico("T", 10, "TEINTANTES").
dico("T", 10, "TEINTASSES").
dico("T", 10, "TEINTERAIS").
dico("T", 10, "TEINTERAIT").
dico("T", 10, "TEINTERENT").
dico("T", 10, "TEINTERIEZ").
dico("T", 10, "TEINTERONS").
dico("T", 10, "TEINTERONT").
dico("T", 10, "TEINTURIER").
dico("T", 10, "TELEACHATS").
dico("T", 10, "TELEACTEUR").
dico("T", 10, "TELEALARME").
dico("T", 10, "TELEBENNES").
dico("T", 10, "TELECABINE").
dico("T", 10, "TELECARTES").
dico("T", 10, "TELECHARGE").
dico("T", 10, "TELECINEMA").
dico("T", 10, "TELECOPIAI").
dico("T", 10, "TELECOPIAS").
dico("T", 10, "TELECOPIAT").
dico("T", 10, "TELECOPIEE").
dico("T", 10, "TELECOPIER").
dico("T", 10, "TELECOPIES").
dico("T", 10, "TELECOPIEZ").
dico("T", 10, "TELEFERAGE").
dico("T", 10, "TELEGENIES").
dico("T", 10, "TELEGRAMME").
dico("T", 10, "TELEGRAPHE").
dico("T", 10, "TELEGUIDAI").
dico("T", 10, "TELEGUIDAS").
dico("T", 10, "TELEGUIDAT").
dico("T", 10, "TELEGUIDEE").
dico("T", 10, "TELEGUIDER").
dico("T", 10, "TELEGUIDES").
dico("T", 10, "TELEGUIDEZ").
dico("T", 10, "TELEMATISA").
dico("T", 10, "TELEMATISE").
dico("T", 10, "TELEMESURE").
dico("T", 10, "TELEMETRAI").
dico("T", 10, "TELEMETRAS").
dico("T", 10, "TELEMETRAT").
dico("T", 10, "TELEMETREE").
dico("T", 10, "TELEMETRER").
dico("T", 10, "TELEMETRES").
dico("T", 10, "TELEMETREZ").
dico("T", 10, "TELEMETRIE").
dico("T", 10, "TELENOMIES").
dico("T", 10, "TELEOLOGIE").
dico("T", 10, "TELEONOMIE").
dico("T", 10, "TELEOSAURE").
dico("T", 10, "TELEOSTEEN").
dico("T", 10, "TELEPATHES").
dico("T", 10, "TELEPATHIE").
dico("T", 10, "TELEPEAGES").
dico("T", 10, "TELEPHAGES").
dico("T", 10, "TELEPHONAI").
dico("T", 10, "TELEPHONAS").
dico("T", 10, "TELEPHONAT").
dico("T", 10, "TELEPHONEE").
dico("T", 10, "TELEPHONER").
dico("T", 10, "TELEPHONES").
dico("T", 10, "TELEPHONEZ").
dico("T", 10, "TELEPHONIE").
dico("T", 10, "TELERADARS").
dico("T", 10, "TELERADIOS").
dico("T", 10, "TELEROMANS").
dico("T", 10, "TELESCAPHE").
dico("T", 10, "TELESCOPAI").
dico("T", 10, "TELESCOPAS").
dico("T", 10, "TELESCOPAT").
dico("T", 10, "TELESCOPEE").
dico("T", 10, "TELESCOPER").
dico("T", 10, "TELESCOPES").
dico("T", 10, "TELESCOPEZ").
dico("T", 10, "TELESIEGES").
dico("T", 10, "TELESUITES").
dico("T", 10, "TELETEXTES").
dico("T", 10, "TELETHEQUE").
dico("T", 10, "TELETOXIES").
dico("T", 10, "TELEVENTES").
dico("T", 10, "TELEVERITE").
dico("T", 10, "TELEVISAIS").
dico("T", 10, "TELEVISAIT").
dico("T", 10, "TELEVISANT").
dico("T", 10, "TELEVISEES").
dico("T", 10, "TELEVISENT").
dico("T", 10, "TELEVISERA").
dico("T", 10, "TELEVISEUR").
dico("T", 10, "TELEVISIEZ").
dico("T", 10, "TELEVISION").
dico("T", 10, "TELEVISONS").
dico("T", 10, "TELEVISUEL").
dico("T", 10, "TELEXAIENT").
dico("T", 10, "TELEXASSES").
dico("T", 10, "TELEXERAIS").
dico("T", 10, "TELEXERAIT").
dico("T", 10, "TELEXERENT").
dico("T", 10, "TELEXERIEZ").
dico("T", 10, "TELEXERONS").
dico("T", 10, "TELEXERONT").
dico("T", 10, "TELEXISTES").
dico("T", 10, "TELLURATES").
dico("T", 10, "TELLUREUSE").
dico("T", 10, "TELLURIENS").
dico("T", 10, "TELLURIQUE").
dico("T", 10, "TELLURISME").
dico("T", 10, "TELLURURES").
dico("T", 10, "TELOPHASES").
dico("T", 10, "TEMERAIRES").
dico("T", 10, "TEMOIGNAGE").
dico("T", 10, "TEMOIGNAIS").
dico("T", 10, "TEMOIGNAIT").
dico("T", 10, "TEMOIGNANT").
dico("T", 10, "TEMOIGNEES").
dico("T", 10, "TEMOIGNENT").
dico("T", 10, "TEMOIGNERA").
dico("T", 10, "TEMOIGNIEZ").
dico("T", 10, "TEMOIGNONS").
dico("T", 10, "TEMPERAMES").
dico("T", 10, "TEMPERANCE").
dico("T", 10, "TEMPERANTE").
dico("T", 10, "TEMPERANTS").
dico("T", 10, "TEMPERASSE").
dico("T", 10, "TEMPERATES").
dico("T", 10, "TEMPERERAI").
dico("T", 10, "TEMPERERAS").
dico("T", 10, "TEMPEREREZ").
dico("T", 10, "TEMPERIONS").
dico("T", 10, "TEMPETAMES").
dico("T", 10, "TEMPETASSE").
dico("T", 10, "TEMPETATES").
dico("T", 10, "TEMPETERAI").
dico("T", 10, "TEMPETERAS").
dico("T", 10, "TEMPETEREZ").
dico("T", 10, "TEMPETIONS").
dico("T", 10, "TEMPETUEUX").
dico("T", 10, "TEMPORAIRE").
dico("T", 10, "TEMPORALES").
dico("T", 10, "TEMPORELLE").
dico("T", 10, "TEMPORISAI").
dico("T", 10, "TEMPORISAS").
dico("T", 10, "TEMPORISAT").
dico("T", 10, "TEMPORISER").
dico("T", 10, "TEMPORISES").
dico("T", 10, "TEMPORISEZ").
dico("T", 10, "TENACEMENT").
dico("T", 10, "TENAILLAIS").
dico("T", 10, "TENAILLAIT").
dico("T", 10, "TENAILLANT").
dico("T", 10, "TENAILLEES").
dico("T", 10, "TENAILLENT").
dico("T", 10, "TENAILLERA").
dico("T", 10, "TENAILLIEZ").
dico("T", 10, "TENAILLONS").
dico("T", 10, "TENANCIERE").
dico("T", 10, "TENANCIERS").
dico("T", 10, "TENDANCIEL").
dico("T", 10, "TENDINEUSE").
dico("T", 10, "TENDINITES").
dico("T", 10, "TENDISSENT").
dico("T", 10, "TENDISSIEZ").
dico("T", 10, "TENDRAIENT").
dico("T", 10, "TENDREMENT").
dico("T", 10, "TENDRESSES").
dico("T", 10, "TENEBREUSE").
dico("T", 10, "TENEBRIONS").
dico("T", 10, "TENNISMANS").
dico("T", 10, "TENONNAGES").
dico("T", 10, "TENONNAMES").
dico("T", 10, "TENONNASSE").
dico("T", 10, "TENONNATES").
dico("T", 10, "TENONNERAI").
dico("T", 10, "TENONNERAS").
dico("T", 10, "TENONNEREZ").
dico("T", 10, "TENONNEUSE").
dico("T", 10, "TENONNIONS").
dico("T", 10, "TENORISAIS").
dico("T", 10, "TENORISAIT").
dico("T", 10, "TENORISANT").
dico("T", 10, "TENORISEES").
dico("T", 10, "TENORISENT").
dico("T", 10, "TENORISERA").
dico("T", 10, "TENORISIEZ").
dico("T", 10, "TENORISONS").
dico("T", 10, "TENOTOMIES").
dico("T", 10, "TENSORIELS").
dico("T", 10, "TENTACULES").
dico("T", 10, "TENTASSENT").
dico("T", 10, "TENTASSIEZ").
dico("T", 10, "TENTATEURS").
dico("T", 10, "TENTATIONS").
dico("T", 10, "TENTATIVES").
dico("T", 10, "TENTATRICE").
dico("T", 10, "TENTERIONS").
dico("T", 10, "TENTHREDES").
dico("T", 10, "TEPHROSIAS").
dico("T", 10, "TEPHROSIES").
dico("T", 10, "TEPIDARIUM").
dico("T", 10, "TERATOGENE").
dico("T", 10, "TERCASSENT").
dico("T", 10, "TERCASSIEZ").
dico("T", 10, "TERCERIONS").
dico("T", 10, "TEREBELLES").
dico("T", 10, "TEREBELLUM").
dico("T", 10, "TEREBINTHE").
dico("T", 10, "TEREBIQUES").
dico("T", 10, "TEREBRANTE").
dico("T", 10, "TEREBRANTS").
dico("T", 10, "TERGIVERSA").
dico("T", 10, "TERGIVERSE").
dico("T", 10, "TERMINALES").
dico("T", 10, "TERMINAMES").
dico("T", 10, "TERMINASSE").
dico("T", 10, "TERMINATES").
dico("T", 10, "TERMINERAI").
dico("T", 10, "TERMINERAS").
dico("T", 10, "TERMINEREZ").
dico("T", 10, "TERMINIONS").
dico("T", 10, "TERMINISME").
dico("T", 10, "TERMITIERE").
dico("T", 10, "TERNIRIONS").
dico("T", 10, "TERNISSAIS").
dico("T", 10, "TERNISSAIT").
dico("T", 10, "TERNISSANT").
dico("T", 10, "TERNISSENT").
dico("T", 10, "TERNISSIEZ").
dico("T", 10, "TERNISSONS").
dico("T", 10, "TERNISSURE").
dico("T", 10, "TERPENIQUE").
dico("T", 10, "TERPENOIDE").
dico("T", 10, "TERPINEOLS").
dico("T", 10, "TERRAMARES").
dico("T", 10, "TERRAPLANE").
dico("T", 10, "TERRAQUEES").
dico("T", 10, "TERRARIUMS").
dico("T", 10, "TERRASSAIS").
dico("T", 10, "TERRASSAIT").
dico("T", 10, "TERRASSANT").
dico("T", 10, "TERRASSEES").
dico("T", 10, "TERRASSENT").
dico("T", 10, "TERRASSERA").
dico("T", 10, "TERRASSIER").
dico("T", 10, "TERRASSIEZ").
dico("T", 10, "TERRASSONS").
dico("T", 10, "TERREAUTAI").
dico("T", 10, "TERREAUTAS").
dico("T", 10, "TERREAUTAT").
dico("T", 10, "TERREAUTEE").
dico("T", 10, "TERREAUTER").
dico("T", 10, "TERREAUTES").
dico("T", 10, "TERREAUTEZ").
dico("T", 10, "TERREFORTS").
dico("T", 10, "TERRERIONS").
dico("T", 10, "TERRESTRES").
dico("T", 10, "TERRICOLES").
dico("T", 10, "TERRIENNES").
dico("T", 10, "TERRIFIAIS").
dico("T", 10, "TERRIFIAIT").
dico("T", 10, "TERRIFIANT").
dico("T", 10, "TERRIFIEES").
dico("T", 10, "TERRIFIENT").
dico("T", 10, "TERRIFIERA").
dico("T", 10, "TERRIFIIEZ").
dico("T", 10, "TERRIFIONS").
dico("T", 10, "TERRIGENES").
dico("T", 10, "TERRIRIONS").
dico("T", 10, "TERRISSAIS").
dico("T", 10, "TERRISSAIT").
dico("T", 10, "TERRISSANT").
dico("T", 10, "TERRISSENT").
dico("T", 10, "TERRISSIEZ").
dico("T", 10, "TERRISSONS").
dico("T", 10, "TERRITOIRE").
dico("T", 10, "TERRORISAI").
dico("T", 10, "TERRORISAS").
dico("T", 10, "TERRORISAT").
dico("T", 10, "TERRORISEE").
dico("T", 10, "TERRORISER").
dico("T", 10, "TERRORISES").
dico("T", 10, "TERRORISEZ").
dico("T", 10, "TERRORISME").
dico("T", 10, "TERRORISTE").
dico("T", 10, "TERSASSENT").
dico("T", 10, "TERSASSIEZ").
dico("T", 10, "TERSERIONS").
dico("T", 10, "TERTIAIRES").
dico("T", 10, "TERVUERENS").
dico("T", 10, "TESSINOISE").
dico("T", 10, "TESSITURES").
dico("T", 10, "TESTACELLE").
dico("T", 10, "TESTAMENTS").
dico("T", 10, "TESTASSENT").
dico("T", 10, "TESTASSIEZ").
dico("T", 10, "TESTATEURS").
dico("T", 10, "TESTATRICE").
dico("T", 10, "TESTERIONS").
dico("T", 10, "TESTICULES").
dico("T", 10, "TESTOLOGIE").
dico("T", 10, "TETANIQUES").
dico("T", 10, "TETANISAIS").
dico("T", 10, "TETANISAIT").
dico("T", 10, "TETANISANT").
dico("T", 10, "TETANISEES").
dico("T", 10, "TETANISENT").
dico("T", 10, "TETANISERA").
dico("T", 10, "TETANISIEZ").
dico("T", 10, "TETANISMES").
dico("T", 10, "TETANISONS").
dico("T", 10, "TETASSIONS").
dico("T", 10, "TETERAIENT").
dico("T", 10, "TETERELLES").
dico("T", 10, "TETONNIERE").
dico("T", 10, "TETRACORDE").
dico("T", 10, "TETRAEDRES").
dico("T", 10, "TETRAGONES").
dico("T", 10, "TETRALINES").
dico("T", 10, "TETRALOGIE").
dico("T", 10, "TETRAMERES").
dico("T", 10, "TETRAMETRE").
dico("T", 10, "TETRAPODES").
dico("T", 10, "TETRAPTERE").
dico("T", 10, "TETRARCHAT").
dico("T", 10, "TETRARCHIE").
dico("T", 10, "TETRARQUES").
dico("T", 10, "TETRASTYLE").
dico("T", 10, "TEUTONIQUE").
dico("T", 10, "TEUTONISME").
dico("T", 10, "TEXTUELLES").
dico("T", 10, "TEXTURAMES").
dico("T", 10, "TEXTURANTS").
dico("T", 10, "TEXTURASSE").
dico("T", 10, "TEXTURATES").
dico("T", 10, "TEXTURERAI").
dico("T", 10, "TEXTURERAS").
dico("T", 10, "TEXTUREREZ").
dico("T", 10, "TEXTURIONS").
dico("T", 10, "TEXTURISAI").
dico("T", 10, "TEXTURISAS").
dico("T", 10, "TEXTURISAT").
dico("T", 10, "TEXTURISEE").
dico("T", 10, "TEXTURISER").
dico("T", 10, "TEXTURISES").
dico("T", 10, "TEXTURISEZ").
dico("T", 10, "THALAMIQUE").
dico("T", 10, "THANATOSES").
dico("T", 10, "THEATRALES").
dico("T", 10, "THEATREUSE").
dico("T", 10, "THEBAIQUES").
dico("T", 10, "THEBAISMES").
dico("T", 10, "THEMATIQUE").
dico("T", 10, "THEMATISME").
dico("T", 10, "THEOCRATIE").
dico("T", 10, "THEODICEES").
dico("T", 10, "THEODOLITE").
dico("T", 10, "THEOGONIES").
dico("T", 10, "THEOLOGALE").
dico("T", 10, "THEOLOGAUX").
dico("T", 10, "THEOLOGIEN").
dico("T", 10, "THEOLOGIES").
dico("T", 10, "THEOPHORES").
dico("T", 10, "THEORICIEN").
dico("T", 10, "THEORIQUES").
dico("T", 10, "THEORISAIS").
dico("T", 10, "THEORISAIT").
dico("T", 10, "THEORISANT").
dico("T", 10, "THEORISEES").
dico("T", 10, "THEORISENT").
dico("T", 10, "THEORISERA").
dico("T", 10, "THEORISIEZ").
dico("T", 10, "THEORISONS").
dico("T", 10, "THEOSOPHES").
dico("T", 10, "THEOSOPHIE").
dico("T", 10, "THERAPEUTE").
dico("T", 10, "THERAVADAS").
dico("T", 10, "THERIAQUES").
dico("T", 10, "THERIDIONS").
dico("T", 10, "THERIDIUMS").
dico("T", 10, "THERMALITE").
dico("T", 10, "THERMICIEN").
dico("T", 10, "THERMICITE").
dico("T", 10, "THERMIDORS").
dico("T", 10, "THERMIQUES").
dico("T", 10, "THERMISTOR").
dico("T", 10, "THERMOGENE").
dico("T", 10, "THERMOLYSE").
dico("T", 10, "THERMOPILE").
dico("T", 10, "THERMOSTAT").
dico("T", 10, "THEROPODES").
dico("T", 10, "THEROPSIDE").
dico("T", 10, "THESAURISA").
dico("T", 10, "THESAURISE").
dico("T", 10, "THESSALIEN").
dico("T", 10, "THEURGIQUE").
dico("T", 10, "THIOACIDES").
dico("T", 10, "THIOALCOOL").
dico("T", 10, "THIONIQUES").
dico("T", 10, "THIOPENTAL").
dico("T", 10, "THIOPHENES").
dico("T", 10, "THIXOTROPE").
dico("T", 10, "THORACIQUE").
dico("T", 10, "THORIANITE").
dico("T", 10, "THREONINES").
dico("T", 10, "THROMBINES").
dico("T", 10, "THROMBOSES").
dico("T", 10, "THURGOVIEN").
dico("T", 10, "THYLACINES").
dico("T", 10, "THYMOCYTES").
dico("T", 10, "THYRATRONS").
dico("T", 10, "THYRISTORS").
dico("T", 10, "THYROIDIEN").
dico("T", 10, "THYROIDITE").
dico("T", 10, "THYROXINES").
dico("T", 10, "THYSANOURE").
dico("T", 10, "TIBETAINES").
dico("T", 10, "TICHODROME").
dico("T", 10, "TICTAQUAIS").
dico("T", 10, "TICTAQUAIT").
dico("T", 10, "TICTAQUANT").
dico("T", 10, "TICTAQUENT").
dico("T", 10, "TICTAQUERA").
dico("T", 10, "TICTAQUIEZ").
dico("T", 10, "TICTAQUONS").
dico("T", 10, "TIEDIRIONS").
dico("T", 10, "TIEDISSAIS").
dico("T", 10, "TIEDISSAIT").
dico("T", 10, "TIEDISSANT").
dico("T", 10, "TIEDISSENT").
dico("T", 10, "TIEDISSIEZ").
dico("T", 10, "TIEDISSONS").
dico("T", 10, "TIENDRIONS").
dico("T", 10, "TIERCAIENT").
dico("T", 10, "TIERCASSES").
dico("T", 10, "TIERCEISTE").
dico("T", 10, "TIERCELETS").
dico("T", 10, "TIERCEMENT").
dico("T", 10, "TIERCERAIS").
dico("T", 10, "TIERCERAIT").
dico("T", 10, "TIERCERENT").
dico("T", 10, "TIERCERIEZ").
dico("T", 10, "TIERCERONS").
dico("T", 10, "TIERCERONT").
dico("T", 10, "TIGEASSENT").
dico("T", 10, "TIGEASSIEZ").
dico("T", 10, "TIGERAIENT").
dico("T", 10, "TIGRASSENT").
dico("T", 10, "TIGRASSIEZ").
dico("T", 10, "TIGRERIONS").
dico("T", 10, "TILLANDSIA").
dico("T", 10, "TILLANDSIE").
dico("T", 10, "TILLASSENT").
dico("T", 10, "TILLASSIEZ").
dico("T", 10, "TILLERIONS").
dico("T", 10, "TILTASSENT").
dico("T", 10, "TILTASSIEZ").
dico("T", 10, "TILTERIONS").
dico("T", 10, "TIMBALIERS").
dico("T", 10, "TIMBRAIENT").
dico("T", 10, "TIMBRASSES").
dico("T", 10, "TIMBRERAIS").
dico("T", 10, "TIMBRERAIT").
dico("T", 10, "TIMBRERENT").
dico("T", 10, "TIMBRERIEZ").
dico("T", 10, "TIMBRERONS").
dico("T", 10, "TIMBRERONT").
dico("T", 10, "TIMBREUSES").
dico("T", 10, "TIMIDEMENT").
dico("T", 10, "TIMONERIES").
dico("T", 10, "TIMORAISES").
dico("T", 10, "TINCTORIAL").
dico("T", 10, "TINTAMARRE").
dico("T", 10, "TINTASSENT").
dico("T", 10, "TINTASSIEZ").
dico("T", 10, "TINTEMENTS").
dico("T", 10, "TINTERIONS").
dico("T", 10, "TIPASSIONS").
dico("T", 10, "TIPERAIENT").
dico("T", 10, "TIPPASSENT").
dico("T", 10, "TIPPASSIEZ").
dico("T", 10, "TIPPERIONS").
dico("T", 10, "TIQUASSENT").
dico("T", 10, "TIQUASSIEZ").
dico("T", 10, "TIQUERIONS").
dico("T", 10, "TIQUETURES").
dico("T", 10, "TIRAILLAIS").
dico("T", 10, "TIRAILLAIT").
dico("T", 10, "TIRAILLANT").
dico("T", 10, "TIRAILLEES").
dico("T", 10, "TIRAILLENT").
dico("T", 10, "TIRAILLERA").
dico("T", 10, "TIRAILLEUR").
dico("T", 10, "TIRAILLIEZ").
dico("T", 10, "TIRAILLONS").
dico("T", 10, "TIRANAISES").
dico("T", 10, "TIRASSIONS").
dico("T", 10, "TIRERAIENT").
dico("T", 10, "TIRETAINES").
dico("T", 10, "TISANERIES").
dico("T", 10, "TISANIERES").
dico("T", 10, "TISONNAMES").
dico("T", 10, "TISONNASSE").
dico("T", 10, "TISONNATES").
dico("T", 10, "TISONNERAI").
dico("T", 10, "TISONNERAS").
dico("T", 10, "TISONNEREZ").
dico("T", 10, "TISONNIERS").
dico("T", 10, "TISONNIONS").
dico("T", 10, "TISSASSENT").
dico("T", 10, "TISSASSIEZ").
dico("T", 10, "TISSERANDE").
dico("T", 10, "TISSERANDS").
dico("T", 10, "TISSERIONS").
dico("T", 10, "TISSULAIRE").
dico("T", 10, "TITANESQUE").
dico("T", 10, "TITANIQUES").
dico("T", 10, "TITILLAMES").
dico("T", 10, "TITILLASSE").
dico("T", 10, "TITILLATES").
dico("T", 10, "TITILLERAI").
dico("T", 10, "TITILLERAS").
dico("T", 10, "TITILLEREZ").
dico("T", 10, "TITILLIONS").
dico("T", 10, "TITRASSENT").
dico("T", 10, "TITRASSIEZ").
dico("T", 10, "TITRERIONS").
dico("T", 10, "TITRISAMES").
dico("T", 10, "TITRISASSE").
dico("T", 10, "TITRISATES").
dico("T", 10, "TITRISERAI").
dico("T", 10, "TITRISERAS").
dico("T", 10, "TITRISEREZ").
dico("T", 10, "TITRISIONS").
dico("T", 10, "TITUBAIENT").
dico("T", 10, "TITUBANTES").
dico("T", 10, "TITUBASSES").
dico("T", 10, "TITUBATION").
dico("T", 10, "TITUBERAIS").
dico("T", 10, "TITUBERAIT").
dico("T", 10, "TITUBERENT").
dico("T", 10, "TITUBERIEZ").
dico("T", 10, "TITUBERONS").
dico("T", 10, "TITUBERONT").
dico("T", 10, "TITULAIRES").
dico("T", 10, "TITULARISA").
dico("T", 10, "TITULARISE").
dico("T", 10, "TITULATURE").
dico("T", 10, "TOARCIENNE").
dico("T", 10, "TOASTAIENT").
dico("T", 10, "TOASTASSES").
dico("T", 10, "TOASTERAIS").
dico("T", 10, "TOASTERAIT").
dico("T", 10, "TOASTERENT").
dico("T", 10, "TOASTERIEZ").
dico("T", 10, "TOASTERONS").
dico("T", 10, "TOASTERONT").
dico("T", 10, "TOCOPHEROL").
dico("T", 10, "TOGOLAISES").
dico("T", 10, "TOILASSENT").
dico("T", 10, "TOILASSIEZ").
dico("T", 10, "TOILERIONS").
dico("T", 10, "TOILETTAGE").
dico("T", 10, "TOILETTAIS").
dico("T", 10, "TOILETTAIT").
dico("T", 10, "TOILETTANT").
dico("T", 10, "TOILETTEES").
dico("T", 10, "TOILETTENT").
dico("T", 10, "TOILETTERA").
dico("T", 10, "TOILETTEUR").
dico("T", 10, "TOILETTIEZ").
dico("T", 10, "TOILETTONS").
dico("T", 10, "TOISASSENT").
dico("T", 10, "TOISASSIEZ").
dico("T", 10, "TOISERIONS").
dico("T", 10, "TOKHARIENS").
dico("T", 10, "TOLASSIONS").
dico("T", 10, "TOLERABLES").
dico("T", 10, "TOLERAIENT").
dico("T", 10, "TOLERANCES").
dico("T", 10, "TOLERANTES").
dico("T", 10, "TOLERASSES").
dico("T", 10, "TOLERERAIS").
dico("T", 10, "TOLERERAIT").
dico("T", 10, "TOLERERENT").
dico("T", 10, "TOLERERIEZ").
dico("T", 10, "TOLERERONS").
dico("T", 10, "TOLERERONT").
dico("T", 10, "TOLETIERES").
dico("T", 10, "TOLUIDINES").
dico("T", 10, "TOMASSIONS").
dico("T", 10, "TOMBASSENT").
dico("T", 10, "TOMBASSIEZ").
dico("T", 10, "TOMBEREAUX").
dico("T", 10, "TOMBERIONS").
dico("T", 10, "TOMENTEUSE").
dico("T", 10, "TOMERAIENT").
dico("T", 10, "TONDAISONS").
dico("T", 10, "TONDISSENT").
dico("T", 10, "TONDISSIEZ").
dico("T", 10, "TONDRAIENT").
dico("T", 10, "TONETIQUES").
dico("T", 10, "TONGRIENNE").
dico("T", 10, "TONGUIENNE").
dico("T", 10, "TONIFIAMES").
dico("T", 10, "TONIFIANTE").
dico("T", 10, "TONIFIANTS").
dico("T", 10, "TONIFIASSE").
dico("T", 10, "TONIFIATES").
dico("T", 10, "TONIFIERAI").
dico("T", 10, "TONIFIERAS").
dico("T", 10, "TONIFIEREZ").
dico("T", 10, "TONIFIIONS").
dico("T", 10, "TONITRUAIS").
dico("T", 10, "TONITRUAIT").
dico("T", 10, "TONITRUANT").
dico("T", 10, "TONITRUENT").
dico("T", 10, "TONITRUERA").
dico("T", 10, "TONITRUIEZ").
dico("T", 10, "TONITRUONS").
dico("T", 10, "TONKINOISE").
dico("T", 10, "TONNASSENT").
dico("T", 10, "TONNASSIEZ").
dico("T", 10, "TONNELAGES").
dico("T", 10, "TONNELIERS").
dico("T", 10, "TONNERIONS").
dico("T", 10, "TONOLOGIES").
dico("T", 10, "TONOMETRIE").
dico("T", 10, "TONSURAMES").
dico("T", 10, "TONSURASSE").
dico("T", 10, "TONSURATES").
dico("T", 10, "TONSURERAI").
dico("T", 10, "TONSURERAS").
dico("T", 10, "TONSUREREZ").
dico("T", 10, "TONSURIONS").
dico("T", 10, "TONTINAMES").
dico("T", 10, "TONTINASSE").
dico("T", 10, "TONTINATES").
dico("T", 10, "TONTINERAI").
dico("T", 10, "TONTINERAS").
dico("T", 10, "TONTINEREZ").
dico("T", 10, "TONTINIONS").
dico("T", 10, "TOPASSIONS").
dico("T", 10, "TOPERAIENT").
dico("T", 10, "TOPOGRAPHE").
dico("T", 10, "TOPOGUIDES").
dico("T", 10, "TOPOLOGIES").
dico("T", 10, "TOPOMETRIE").
dico("T", 10, "TOPONYMIES").
dico("T", 10, "TOQUASSENT").
dico("T", 10, "TOQUASSIEZ").
dico("T", 10, "TOQUERIONS").
dico("T", 10, "TORAILLAIS").
dico("T", 10, "TORAILLAIT").
dico("T", 10, "TORAILLANT").
dico("T", 10, "TORAILLENT").
dico("T", 10, "TORAILLERA").
dico("T", 10, "TORAILLIEZ").
dico("T", 10, "TORAILLONS").
dico("T", 10, "TORCHAIENT").
dico("T", 10, "TORCHASSES").
dico("T", 10, "TORCHERAIS").
dico("T", 10, "TORCHERAIT").
dico("T", 10, "TORCHERENT").
dico("T", 10, "TORCHERIEZ").
dico("T", 10, "TORCHERONS").
dico("T", 10, "TORCHERONT").
dico("T", 10, "TORCHONNAI").
dico("T", 10, "TORCHONNAS").
dico("T", 10, "TORCHONNAT").
dico("T", 10, "TORCHONNEE").
dico("T", 10, "TORCHONNER").
dico("T", 10, "TORCHONNES").
dico("T", 10, "TORCHONNEZ").
dico("T", 10, "TORDISSENT").
dico("T", 10, "TORDISSIEZ").
dico("T", 10, "TORDRAIENT").
dico("T", 10, "TOREASSENT").
dico("T", 10, "TOREASSIEZ").
dico("T", 10, "TOREERIONS").
dico("T", 10, "TOREUTIQUE").
dico("T", 10, "TOROIDALES").
dico("T", 10, "TORONNAMES").
dico("T", 10, "TORONNASSE").
dico("T", 10, "TORONNATES").
dico("T", 10, "TORONNERAI").
dico("T", 10, "TORONNERAS").
dico("T", 10, "TORONNEREZ").
dico("T", 10, "TORONNEUSE").
dico("T", 10, "TORONNIONS").
dico("T", 10, "TORONTOISE").
dico("T", 10, "TORPILLAGE").
dico("T", 10, "TORPILLAIS").
dico("T", 10, "TORPILLAIT").
dico("T", 10, "TORPILLANT").
dico("T", 10, "TORPILLEES").
dico("T", 10, "TORPILLENT").
dico("T", 10, "TORPILLERA").
dico("T", 10, "TORPILLEUR").
dico("T", 10, "TORPILLIEZ").
dico("T", 10, "TORPILLONS").
dico("T", 10, "TORRAILLAI").
dico("T", 10, "TORRAILLAS").
dico("T", 10, "TORRAILLAT").
dico("T", 10, "TORRAILLER").
dico("T", 10, "TORRAILLES").
dico("T", 10, "TORRAILLEZ").
dico("T", 10, "TORREFIAIS").
dico("T", 10, "TORREFIAIT").
dico("T", 10, "TORREFIANT").
dico("T", 10, "TORREFIEES").
dico("T", 10, "TORREFIENT").
dico("T", 10, "TORREFIERA").
dico("T", 10, "TORREFIIEZ").
dico("T", 10, "TORREFIONS").
dico("T", 10, "TORRENTIEL").
dico("T", 10, "TORSADAMES").
dico("T", 10, "TORSADASSE").
dico("T", 10, "TORSADATES").
dico("T", 10, "TORSADERAI").
dico("T", 10, "TORSADERAS").
dico("T", 10, "TORSADEREZ").
dico("T", 10, "TORSADIONS").
dico("T", 10, "TORTELLINI").
dico("T", 10, "TORTICOLIS").
dico("T", 10, "TORTILLAGE").
dico("T", 10, "TORTILLAIS").
dico("T", 10, "TORTILLAIT").
dico("T", 10, "TORTILLANT").
dico("T", 10, "TORTILLARD").
dico("T", 10, "TORTILLEES").
dico("T", 10, "TORTILLENT").
dico("T", 10, "TORTILLERA").
dico("T", 10, "TORTILLERE").
dico("T", 10, "TORTILLIEZ").
dico("T", 10, "TORTILLONS").
dico("T", 10, "TORTORAMES").
dico("T", 10, "TORTORASSE").
dico("T", 10, "TORTORATES").
dico("T", 10, "TORTORERAI").
dico("T", 10, "TORTORERAS").
dico("T", 10, "TORTOREREZ").
dico("T", 10, "TORTORIONS").
dico("T", 10, "TORTRICIDE").
dico("T", 10, "TORTUEUSES").
dico("T", 10, "TORTUOSITE").
dico("T", 10, "TORTURAMES").
dico("T", 10, "TORTURANTE").
dico("T", 10, "TORTURANTS").
dico("T", 10, "TORTURASSE").
dico("T", 10, "TORTURATES").
dico("T", 10, "TORTURERAI").
dico("T", 10, "TORTURERAS").
dico("T", 10, "TORTUREREZ").
dico("T", 10, "TORTURIONS").
dico("T", 10, "TOSSASSENT").
dico("T", 10, "TOSSASSIEZ").
dico("T", 10, "TOSSERIONS").
dico("T", 10, "TOTALEMENT").
dico("T", 10, "TOTALISAIS").
dico("T", 10, "TOTALISAIT").
dico("T", 10, "TOTALISANT").
dico("T", 10, "TOTALISEES").
dico("T", 10, "TOTALISENT").
dico("T", 10, "TOTALISERA").
dico("T", 10, "TOTALISEUR").
dico("T", 10, "TOTALISIEZ").
dico("T", 10, "TOTALISONS").
dico("T", 10, "TOTEMIQUES").
dico("T", 10, "TOTEMISMES").
dico("T", 10, "TOTIPOTENT").
dico("T", 10, "TOUAREGUES").
dico("T", 10, "TOUASSIONS").
dico("T", 10, "TOUCHABLES").
dico("T", 10, "TOUCHAIENT").
dico("T", 10, "TOUCHANTES").
dico("T", 10, "TOUCHASSES").
dico("T", 10, "TOUCHERAIS").
dico("T", 10, "TOUCHERAIT").
dico("T", 10, "TOUCHERENT").
dico("T", 10, "TOUCHERIEZ").
dico("T", 10, "TOUCHERONS").
dico("T", 10, "TOUCHERONT").
dico("T", 10, "TOUCHETTES").
dico("T", 10, "TOUCHEUSES").
dico("T", 10, "TOUCOULEUR").
dico("T", 10, "TOUERAIENT").
dico("T", 10, "TOUILLAGES").
dico("T", 10, "TOUILLAMES").
dico("T", 10, "TOUILLASSE").
dico("T", 10, "TOUILLATES").
dico("T", 10, "TOUILLERAI").
dico("T", 10, "TOUILLERAS").
dico("T", 10, "TOUILLEREZ").
dico("T", 10, "TOUILLEURS").
dico("T", 10, "TOUILLEUSE").
dico("T", 10, "TOUILLIONS").
dico("T", 10, "TOULONNAIS").
dico("T", 10, "TOULOUSAIN").
dico("T", 10, "TOUNGOUSES").
dico("T", 10, "TOUNGOUZES").
dico("T", 10, "TOUPILLAGE").
dico("T", 10, "TOUPILLAIS").
dico("T", 10, "TOUPILLAIT").
dico("T", 10, "TOUPILLANT").
dico("T", 10, "TOUPILLEES").
dico("T", 10, "TOUPILLENT").
dico("T", 10, "TOUPILLERA").
dico("T", 10, "TOUPILLEUR").
dico("T", 10, "TOUPILLIEZ").
dico("T", 10, "TOUPILLONS").
dico("T", 10, "TOUPINAMES").
dico("T", 10, "TOUPINASSE").
dico("T", 10, "TOUPINATES").
dico("T", 10, "TOUPINERAI").
dico("T", 10, "TOUPINERAS").
dico("T", 10, "TOUPINEREZ").
dico("T", 10, "TOUPINIONS").
dico("T", 10, "TOURAILLES").
dico("T", 10, "TOURAILLON").
dico("T", 10, "TOURANGEAU").
dico("T", 10, "TOURANIENS").
dico("T", 10, "TOURBAIENT").
dico("T", 10, "TOURBASSES").
dico("T", 10, "TOURBERAIS").
dico("T", 10, "TOURBERAIT").
dico("T", 10, "TOURBERENT").
dico("T", 10, "TOURBERIEZ").
dico("T", 10, "TOURBERONS").
dico("T", 10, "TOURBERONT").
dico("T", 10, "TOURBEUSES").
dico("T", 10, "TOURBIERES").
dico("T", 10, "TOURBILLON").
dico("T", 10, "TOURDILLES").
dico("T", 10, "TOURILLONS").
dico("T", 10, "TOURLOUROU").
dico("T", 10, "TOURMALINE").
dico("T", 10, "TOURMENTAI").
dico("T", 10, "TOURMENTAS").
dico("T", 10, "TOURMENTAT").
dico("T", 10, "TOURMENTEE").
dico("T", 10, "TOURMENTER").
dico("T", 10, "TOURMENTES").
dico("T", 10, "TOURMENTEZ").
dico("T", 10, "TOURMENTIN").
dico("T", 10, "TOURNAIENT").
dico("T", 10, "TOURNAILLA").
dico("T", 10, "TOURNAILLE").
dico("T", 10, "TOURNANTES").
dico("T", 10, "TOURNASSES").
dico("T", 10, "TOURNEMAIN").
dico("T", 10, "TOURNERAIS").
dico("T", 10, "TOURNERAIT").
dico("T", 10, "TOURNERENT").
dico("T", 10, "TOURNERIES").
dico("T", 10, "TOURNERIEZ").
dico("T", 10, "TOURNERONS").
dico("T", 10, "TOURNERONT").
dico("T", 10, "TOURNESOLS").
dico("T", 10, "TOURNETTES").
dico("T", 10, "TOURNEUSES").
dico("T", 10, "TOURNICOTA").
dico("T", 10, "TOURNICOTE").
dico("T", 10, "TOURNIOLES").
dico("T", 10, "TOURNIQUAI").
dico("T", 10, "TOURNIQUAS").
dico("T", 10, "TOURNIQUAT").
dico("T", 10, "TOURNIQUER").
dico("T", 10, "TOURNIQUES").
dico("T", 10, "TOURNIQUET").
dico("T", 10, "TOURNIQUEZ").
dico("T", 10, "TOURNISSES").
dico("T", 10, "TOURNOIENT").
dico("T", 10, "TOURNOIERA").
dico("T", 10, "TOURNOYAIS").
dico("T", 10, "TOURNOYAIT").
dico("T", 10, "TOURNOYANT").
dico("T", 10, "TOURNOYIEZ").
dico("T", 10, "TOURNOYONS").
dico("T", 10, "TOURTEREAU").
dico("T", 10, "TOURTIERES").
dico("T", 10, "TOUSSAIENT").
dico("T", 10, "TOUSSAILLA").
dico("T", 10, "TOUSSAILLE").
dico("T", 10, "TOUSSAINTS").
dico("T", 10, "TOUSSASSES").
dico("T", 10, "TOUSSERAIS").
dico("T", 10, "TOUSSERAIT").
dico("T", 10, "TOUSSERENT").
dico("T", 10, "TOUSSERIES").
dico("T", 10, "TOUSSERIEZ").
dico("T", 10, "TOUSSERONS").
dico("T", 10, "TOUSSERONT").
dico("T", 10, "TOUSSEUSES").
dico("T", 10, "TOUSSOTAIS").
dico("T", 10, "TOUSSOTAIT").
dico("T", 10, "TOUSSOTANT").
dico("T", 10, "TOUSSOTENT").
dico("T", 10, "TOUSSOTERA").
dico("T", 10, "TOUSSOTIEZ").
dico("T", 10, "TOUSSOTONS").
dico("T", 10, "TOXEMIQUES").
dico("T", 10, "TOXICOMANE").
dico("T", 10, "TOXIDERMIE").
dico("T", 10, "TOXOCAROSE").
dico("T", 10, "TOXOPLASME").
dico("T", 10, "TRABOULAIS").
dico("T", 10, "TRABOULAIT").
dico("T", 10, "TRABOULANT").
dico("T", 10, "TRABOULENT").
dico("T", 10, "TRABOULERA").
dico("T", 10, "TRABOULIEZ").
dico("T", 10, "TRABOULONS").
dico("T", 10, "TRACASSAIS").
dico("T", 10, "TRACASSAIT").
dico("T", 10, "TRACASSANT").
dico("T", 10, "TRACASSEES").
dico("T", 10, "TRACASSENT").
dico("T", 10, "TRACASSERA").
dico("T", 10, "TRACASSIER").
dico("T", 10, "TRACASSIEZ").
dico("T", 10, "TRACASSINS").
dico("T", 10, "TRACASSONS").
dico("T", 10, "TRACEMENTS").
dico("T", 10, "TRACERIONS").
dico("T", 10, "TRACHEALES").
dico("T", 10, "TRACHEENNE").
dico("T", 10, "TRACHEIDES").
dico("T", 10, "TRACHEITES").
dico("T", 10, "TRACTABLES").
dico("T", 10, "TRACTAIENT").
dico("T", 10, "TRACTASSES").
dico("T", 10, "TRACTATION").
dico("T", 10, "TRACTERAIS").
dico("T", 10, "TRACTERAIT").
dico("T", 10, "TRACTERENT").
dico("T", 10, "TRACTERIEZ").
dico("T", 10, "TRACTERONS").
dico("T", 10, "TRACTERONT").
dico("T", 10, "TRACTRICES").
dico("T", 10, "TRADITEURS").
dico("T", 10, "TRADITIONS").
dico("T", 10, "TRADUCTEUR").
dico("T", 10, "TRADUCTION").
dico("T", 10, "TRADUIRAIS").
dico("T", 10, "TRADUIRAIT").
dico("T", 10, "TRADUIRIEZ").
dico("T", 10, "TRADUIRONS").
dico("T", 10, "TRADUIRONT").
dico("T", 10, "TRADUISAIS").
dico("T", 10, "TRADUISAIT").
dico("T", 10, "TRADUISANT").
dico("T", 10, "TRADUISENT").
dico("T", 10, "TRADUISIEZ").
dico("T", 10, "TRADUISONS").
dico("T", 10, "TRAFALGARS").
dico("T", 10, "TRAFICOTAI").
dico("T", 10, "TRAFICOTAS").
dico("T", 10, "TRAFICOTAT").
dico("T", 10, "TRAFICOTEE").
dico("T", 10, "TRAFICOTER").
dico("T", 10, "TRAFICOTES").
dico("T", 10, "TRAFICOTEZ").
dico("T", 10, "TRAFIQUAIS").
dico("T", 10, "TRAFIQUAIT").
dico("T", 10, "TRAFIQUANT").
dico("T", 10, "TRAFIQUEES").
dico("T", 10, "TRAFIQUENT").
dico("T", 10, "TRAFIQUERA").
dico("T", 10, "TRAFIQUEUR").
dico("T", 10, "TRAFIQUIEZ").
dico("T", 10, "TRAFIQUONS").
dico("T", 10, "TRAGEDIENS").
dico("T", 10, "TRAHIRIONS").
dico("T", 10, "TRAHISSAIS").
dico("T", 10, "TRAHISSAIT").
dico("T", 10, "TRAHISSANT").
dico("T", 10, "TRAHISSENT").
dico("T", 10, "TRAHISSIEZ").
dico("T", 10, "TRAHISSONS").
dico("T", 10, "TRAINAIENT").
dico("T", 10, "TRAINAILLA").
dico("T", 10, "TRAINAILLE").
dico("T", 10, "TRAINANTES").
dico("T", 10, "TRAINARDES").
dico("T", 10, "TRAINASSAI").
dico("T", 10, "TRAINASSAS").
dico("T", 10, "TRAINASSAT").
dico("T", 10, "TRAINASSEE").
dico("T", 10, "TRAINASSER").
dico("T", 10, "TRAINASSES").
dico("T", 10, "TRAINASSEZ").
dico("T", 10, "TRAINEMENT").
dico("T", 10, "TRAINERAIS").
dico("T", 10, "TRAINERAIT").
dico("T", 10, "TRAINERENT").
dico("T", 10, "TRAINERIES").
dico("T", 10, "TRAINERIEZ").
dico("T", 10, "TRAINERONS").
dico("T", 10, "TRAINERONT").
dico("T", 10, "TRAINEUSES").
dico("T", 10, "TRAINGLOTS").
dico("T", 10, "TRAINTRAIN").
dico("T", 10, "TRAIRAIENT").
dico("T", 10, "TRAITABLES").
dico("T", 10, "TRAITAIENT").
dico("T", 10, "TRAITANTES").
dico("T", 10, "TRAITASSES").
dico("T", 10, "TRAITEMENT").
dico("T", 10, "TRAITERAIS").
dico("T", 10, "TRAITERAIT").
dico("T", 10, "TRAITERENT").
dico("T", 10, "TRAITERIEZ").
dico("T", 10, "TRAITERONS").
dico("T", 10, "TRAITERONT").
dico("T", 10, "TRAITRESSE").
dico("T", 10, "TRAITRISES").
dico("T", 10, "TRALUIRAIS").
dico("T", 10, "TRALUIRAIT").
dico("T", 10, "TRALUIRENT").
dico("T", 10, "TRALUIRIEZ").
dico("T", 10, "TRALUIRONS").
dico("T", 10, "TRALUIRONT").
dico("T", 10, "TRALUISAIS").
dico("T", 10, "TRALUISAIT").
dico("T", 10, "TRALUISANT").
dico("T", 10, "TRALUISENT").
dico("T", 10, "TRALUISIEZ").
dico("T", 10, "TRALUISONS").
dico("T", 10, "TRAMASSENT").
dico("T", 10, "TRAMASSIEZ").
dico("T", 10, "TRAMERIONS").
dico("T", 10, "TRAMONTANE").
dico("T", 10, "TRAMPOLINE").
dico("T", 10, "TRANCHAGES").
dico("T", 10, "TRANCHAMES").
dico("T", 10, "TRANCHANTE").
dico("T", 10, "TRANCHANTS").
dico("T", 10, "TRANCHASSE").
dico("T", 10, "TRANCHATES").
dico("T", 10, "TRANCHEFIL").
dico("T", 10, "TRANCHERAI").
dico("T", 10, "TRANCHERAS").
dico("T", 10, "TRANCHEREZ").
dico("T", 10, "TRANCHEURS").
dico("T", 10, "TRANCHEUSE").
dico("T", 10, "TRANCHIONS").
dico("T", 10, "TRANCHOIRS").
dico("T", 10, "TRANQUILLE").
dico("T", 10, "TRANSALPIN").
dico("T", 10, "TRANSANDIN").
dico("T", 10, "TRANSBORDA").
dico("T", 10, "TRANSBORDE").
dico("T", 10, "TRANSCENDA").
dico("T", 10, "TRANSCENDE").
dico("T", 10, "TRANSCODAI").
dico("T", 10, "TRANSCODAS").
dico("T", 10, "TRANSCODAT").
dico("T", 10, "TRANSCODEE").
dico("T", 10, "TRANSCODER").
dico("T", 10, "TRANSCODES").
dico("T", 10, "TRANSCODEZ").
dico("T", 10, "TRANSCRIRA").
dico("T", 10, "TRANSCRIRE").
dico("T", 10, "TRANSCRITE").
dico("T", 10, "TRANSCRITS").
dico("T", 10, "TRANSCRIVE").
dico("T", 10, "TRANSFERAI").
dico("T", 10, "TRANSFERAS").
dico("T", 10, "TRANSFERAT").
dico("T", 10, "TRANSFEREE").
dico("T", 10, "TRANSFERER").
dico("T", 10, "TRANSFERES").
dico("T", 10, "TRANSFEREZ").
dico("T", 10, "TRANSFERTS").
dico("T", 10, "TRANSFILAI").
dico("T", 10, "TRANSFILAS").
dico("T", 10, "TRANSFILAT").
dico("T", 10, "TRANSFILEE").
dico("T", 10, "TRANSFILER").
dico("T", 10, "TRANSFILES").
dico("T", 10, "TRANSFILEZ").
dico("T", 10, "TRANSFINIE").
dico("T", 10, "TRANSFINIS").
dico("T", 10, "TRANSFORMA").
dico("T", 10, "TRANSFORME").
dico("T", 10, "TRANSFUGES").
dico("T", 10, "TRANSFUSAI").
dico("T", 10, "TRANSFUSAS").
dico("T", 10, "TRANSFUSAT").
dico("T", 10, "TRANSFUSEE").
dico("T", 10, "TRANSFUSER").
dico("T", 10, "TRANSFUSES").
dico("T", 10, "TRANSFUSEZ").
dico("T", 10, "TRANSGENES").
dico("T", 10, "TRANSHUMAI").
dico("T", 10, "TRANSHUMAS").
dico("T", 10, "TRANSHUMAT").
dico("T", 10, "TRANSHUMEE").
dico("T", 10, "TRANSHUMER").
dico("T", 10, "TRANSHUMES").
dico("T", 10, "TRANSHUMEZ").
dico("T", 10, "TRANSIGEAI").
dico("T", 10, "TRANSIGEAS").
dico("T", 10, "TRANSIGEAT").
dico("T", 10, "TRANSIGENT").
dico("T", 10, "TRANSIGERA").
dico("T", 10, "TRANSIGIEZ").
dico("T", 10, "TRANSIRAIS").
dico("T", 10, "TRANSIRAIT").
dico("T", 10, "TRANSIRENT").
dico("T", 10, "TRANSIRIEZ").
dico("T", 10, "TRANSIRONS").
dico("T", 10, "TRANSIRONT").
dico("T", 10, "TRANSISSES").
dico("T", 10, "TRANSISSEZ").
dico("T", 10, "TRANSISTOR").
dico("T", 10, "TRANSITAIS").
dico("T", 10, "TRANSITAIT").
dico("T", 10, "TRANSITANT").
dico("T", 10, "TRANSITEES").
dico("T", 10, "TRANSITENT").
dico("T", 10, "TRANSITERA").
dico("T", 10, "TRANSITIEZ").
dico("T", 10, "TRANSITIFS").
dico("T", 10, "TRANSITION").
dico("T", 10, "TRANSITIVE").
dico("T", 10, "TRANSITONS").
dico("T", 10, "TRANSJURAN").
dico("T", 10, "TRANSLATAI").
dico("T", 10, "TRANSLATAS").
dico("T", 10, "TRANSLATAT").
dico("T", 10, "TRANSLATEE").
dico("T", 10, "TRANSLATER").
dico("T", 10, "TRANSLATES").
dico("T", 10, "TRANSLATEZ").
dico("T", 10, "TRANSLATIF").
dico("T", 10, "TRANSMETTE").
dico("T", 10, "TRANSMIGRA").
dico("T", 10, "TRANSMIGRE").
dico("T", 10, "TRANSMIMES").
dico("T", 10, "TRANSMISES").
dico("T", 10, "TRANSMISSE").
dico("T", 10, "TRANSMITES").
dico("T", 10, "TRANSMUAIS").
dico("T", 10, "TRANSMUAIT").
dico("T", 10, "TRANSMUANT").
dico("T", 10, "TRANSMUEES").
dico("T", 10, "TRANSMUENT").
dico("T", 10, "TRANSMUERA").
dico("T", 10, "TRANSMUIEZ").
dico("T", 10, "TRANSMUONS").
dico("T", 10, "TRANSMUTAI").
dico("T", 10, "TRANSMUTAS").
dico("T", 10, "TRANSMUTAT").
dico("T", 10, "TRANSMUTEE").
dico("T", 10, "TRANSMUTER").
dico("T", 10, "TRANSMUTES").
dico("T", 10, "TRANSMUTEZ").
dico("T", 10, "TRANSPARUS").
dico("T", 10, "TRANSPARUT").
dico("T", 10, "TRANSPERCA").
dico("T", 10, "TRANSPERCE").
dico("T", 10, "TRANSPIRAI").
dico("T", 10, "TRANSPIRAS").
dico("T", 10, "TRANSPIRAT").
dico("T", 10, "TRANSPIREE").
dico("T", 10, "TRANSPIRER").
dico("T", 10, "TRANSPIRES").
dico("T", 10, "TRANSPIREZ").
dico("T", 10, "TRANSPLANT").
dico("T", 10, "TRANSPORTA").
dico("T", 10, "TRANSPORTE").
dico("T", 10, "TRANSPORTS").
dico("T", 10, "TRANSPOSAI").
dico("T", 10, "TRANSPOSAS").
dico("T", 10, "TRANSPOSAT").
dico("T", 10, "TRANSPOSEE").
dico("T", 10, "TRANSPOSER").
dico("T", 10, "TRANSPOSES").
dico("T", 10, "TRANSPOSEZ").
dico("T", 10, "TRANSPOSON").
dico("T", 10, "TRANSSUDAI").
dico("T", 10, "TRANSSUDAS").
dico("T", 10, "TRANSSUDAT").
dico("T", 10, "TRANSSUDEE").
dico("T", 10, "TRANSSUDER").
dico("T", 10, "TRANSSUDES").
dico("T", 10, "TRANSSUDEZ").
dico("T", 10, "TRANSVASAI").
dico("T", 10, "TRANSVASAS").
dico("T", 10, "TRANSVASAT").
dico("T", 10, "TRANSVASEE").
dico("T", 10, "TRANSVASER").
dico("T", 10, "TRANSVASES").
dico("T", 10, "TRANSVASEZ").
dico("T", 10, "TRANSVERSE").
dico("T", 10, "TRANSVIDAI").
dico("T", 10, "TRANSVIDAS").
dico("T", 10, "TRANSVIDAT").
dico("T", 10, "TRANSVIDEE").
dico("T", 10, "TRANSVIDER").
dico("T", 10, "TRANSVIDES").
dico("T", 10, "TRANSVIDEZ").
dico("T", 10, "TRAPEZISTE").
dico("T", 10, "TRAPEZOIDE").
dico("T", 10, "TRAPILLONS").
dico("T", 10, "TRAPPAIENT").
dico("T", 10, "TRAPPASSES").
dico("T", 10, "TRAPPERAIS").
dico("T", 10, "TRAPPERAIT").
dico("T", 10, "TRAPPERENT").
dico("T", 10, "TRAPPERIEZ").
dico("T", 10, "TRAPPERONS").
dico("T", 10, "TRAPPERONT").
dico("T", 10, "TRAPPILLON").
dico("T", 10, "TRAPPISTES").
dico("T", 10, "TRAQUAIENT").
dico("T", 10, "TRAQUASSES").
dico("T", 10, "TRAQUELETS").
dico("T", 10, "TRAQUENARD").
dico("T", 10, "TRAQUERAIS").
dico("T", 10, "TRAQUERAIT").
dico("T", 10, "TRAQUERENT").
dico("T", 10, "TRAQUERIEZ").
dico("T", 10, "TRAQUERONS").
dico("T", 10, "TRAQUERONT").
dico("T", 10, "TRAQUEUSES").
dico("T", 10, "TRATTORIAS").
dico("T", 10, "TRAUMATISA").
dico("T", 10, "TRAUMATISE").
dico("T", 10, "TRAVAILLAI").
dico("T", 10, "TRAVAILLAS").
dico("T", 10, "TRAVAILLAT").
dico("T", 10, "TRAVAILLEE").
dico("T", 10, "TRAVAILLER").
dico("T", 10, "TRAVAILLES").
dico("T", 10, "TRAVAILLEZ").
dico("T", 10, "TRAVELAGES").
dico("T", 10, "TRAVELINGS").
dico("T", 10, "TRAVELLERS").
dico("T", 10, "TRAVELLING").
dico("T", 10, "TRAVERSAIS").
dico("T", 10, "TRAVERSAIT").
dico("T", 10, "TRAVERSANT").
dico("T", 10, "TRAVERSEES").
dico("T", 10, "TRAVERSENT").
dico("T", 10, "TRAVERSERA").
dico("T", 10, "TRAVERSIER").
dico("T", 10, "TRAVERSIEZ").
dico("T", 10, "TRAVERSINE").
dico("T", 10, "TRAVERSINS").
dico("T", 10, "TRAVERSONS").
dico("T", 10, "TRAVERTINS").
dico("T", 10, "TRAVESTIES").
dico("T", 10, "TRAVESTIRA").
dico("T", 10, "TREBUCHAIS").
dico("T", 10, "TREBUCHAIT").
dico("T", 10, "TREBUCHANT").
dico("T", 10, "TREBUCHEES").
dico("T", 10, "TREBUCHENT").
dico("T", 10, "TREBUCHERA").
dico("T", 10, "TREBUCHETS").
dico("T", 10, "TREBUCHIEZ").
dico("T", 10, "TREBUCHONS").
dico("T", 10, "TREFILAGES").
dico("T", 10, "TREFILAMES").
dico("T", 10, "TREFILASSE").
dico("T", 10, "TREFILATES").
dico("T", 10, "TREFILERAI").
dico("T", 10, "TREFILERAS").
dico("T", 10, "TREFILEREZ").
dico("T", 10, "TREFILERIE").
dico("T", 10, "TREFILEURS").
dico("T", 10, "TREFILEUSE").
dico("T", 10, "TREFILIONS").
dico("T", 10, "TREFLERIES").
dico("T", 10, "TREFLIERES").
dico("T", 10, "TREFONCIER").
dico("T", 10, "TREGOROISE").
dico("T", 10, "TREGORROIS").
dico("T", 10, "TREHALOSES").
dico("T", 10, "TREILLAGEA").
dico("T", 10, "TREILLAGEE").
dico("T", 10, "TREILLAGER").
dico("T", 10, "TREILLAGES").
dico("T", 10, "TREILLAGEZ").
dico("T", 10, "TREILLISSA").
dico("T", 10, "TREILLISSE").
dico("T", 10, "TREIZIEMES").
dico("T", 10, "TREIZISTES").
dico("T", 10, "TREKKEUSES").
dico("T", 10, "TRELINGAGE").
dico("T", 10, "TREMATAGES").
dico("T", 10, "TREMATAMES").
dico("T", 10, "TREMATASSE").
dico("T", 10, "TREMATATES").
dico("T", 10, "TREMATERAI").
dico("T", 10, "TREMATERAS").
dico("T", 10, "TREMATEREZ").
dico("T", 10, "TREMATIONS").
dico("T", 10, "TREMATODES").
dico("T", 10, "TREMBLAIES").
dico("T", 10, "TREMBLAMES").
dico("T", 10, "TREMBLANTE").
dico("T", 10, "TREMBLANTS").
dico("T", 10, "TREMBLASSE").
dico("T", 10, "TREMBLATES").
dico("T", 10, "TREMBLERAI").
dico("T", 10, "TREMBLERAS").
dico("T", 10, "TREMBLEREZ").
dico("T", 10, "TREMBLEURS").
dico("T", 10, "TREMBLEUSE").
dico("T", 10, "TREMBLIONS").
dico("T", 10, "TREMBLOTAI").
dico("T", 10, "TREMBLOTAS").
dico("T", 10, "TREMBLOTAT").
dico("T", 10, "TREMBLOTER").
dico("T", 10, "TREMBLOTES").
dico("T", 10, "TREMBLOTEZ").
dico("T", 10, "TREMOLITES").
dico("T", 10, "TREMOUSSAI").
dico("T", 10, "TREMOUSSAS").
dico("T", 10, "TREMOUSSAT").
dico("T", 10, "TREMOUSSEE").
dico("T", 10, "TREMOUSSER").
dico("T", 10, "TREMOUSSES").
dico("T", 10, "TREMOUSSEZ").
dico("T", 10, "TREMPAIENT").
dico("T", 10, "TREMPASSES").
dico("T", 10, "TREMPERAIS").
dico("T", 10, "TREMPERAIT").
dico("T", 10, "TREMPERENT").
dico("T", 10, "TREMPERIEZ").
dico("T", 10, "TREMPERONS").
dico("T", 10, "TREMPERONT").
dico("T", 10, "TREMPETTES").
dico("T", 10, "TREMULAMES").
dico("T", 10, "TREMULANTE").
dico("T", 10, "TREMULANTS").
dico("T", 10, "TREMULASSE").
dico("T", 10, "TREMULATES").
dico("T", 10, "TREMULERAI").
dico("T", 10, "TREMULERAS").
dico("T", 10, "TREMULEREZ").
dico("T", 10, "TREMULIONS").
dico("T", 10, "TRENTAINES").
dico("T", 10, "TRENTIEMES").
dico("T", 10, "TREPANAMES").
dico("T", 10, "TREPANASSE").
dico("T", 10, "TREPANATES").
dico("T", 10, "TREPANERAI").
dico("T", 10, "TREPANERAS").
dico("T", 10, "TREPANEREZ").
dico("T", 10, "TREPANIONS").
dico("T", 10, "TREPASSAIS").
dico("T", 10, "TREPASSAIT").
dico("T", 10, "TREPASSANT").
dico("T", 10, "TREPASSEES").
dico("T", 10, "TREPASSENT").
dico("T", 10, "TREPASSERA").
dico("T", 10, "TREPASSIEZ").
dico("T", 10, "TREPASSONS").
dico("T", 10, "TREPHOCYTE").
dico("T", 10, "TREPIDAMES").
dico("T", 10, "TREPIDANTE").
dico("T", 10, "TREPIDANTS").
dico("T", 10, "TREPIDASSE").
dico("T", 10, "TREPIDATES").
dico("T", 10, "TREPIDERAI").
dico("T", 10, "TREPIDERAS").
dico("T", 10, "TREPIDEREZ").
dico("T", 10, "TREPIDIONS").
dico("T", 10, "TREPIGNAIS").
dico("T", 10, "TREPIGNAIT").
dico("T", 10, "TREPIGNANT").
dico("T", 10, "TREPIGNEES").
dico("T", 10, "TREPIGNENT").
dico("T", 10, "TREPIGNERA").
dico("T", 10, "TREPIGNIEZ").
dico("T", 10, "TREPIGNONS").
dico("T", 10, "TREPOINTES").
dico("T", 10, "TREPONEMES").
dico("T", 10, "TRESAILLES").
dico("T", 10, "TRESCHEURS").
dico("T", 10, "TRESORERIE").
dico("T", 10, "TRESORIERE").
dico("T", 10, "TRESORIERS").
dico("T", 10, "TRESSAIENT").
dico("T", 10, "TRESSAILLE").
dico("T", 10, "TRESSAILLI").
dico("T", 10, "TRESSASSES").
dico("T", 10, "TRESSAUTAI").
dico("T", 10, "TRESSAUTAS").
dico("T", 10, "TRESSAUTAT").
dico("T", 10, "TRESSAUTER").
dico("T", 10, "TRESSAUTES").
dico("T", 10, "TRESSAUTEZ").
dico("T", 10, "TRESSERAIS").
dico("T", 10, "TRESSERAIT").
dico("T", 10, "TRESSERENT").
dico("T", 10, "TRESSERIEZ").
dico("T", 10, "TRESSERONS").
dico("T", 10, "TRESSERONT").
dico("T", 10, "TRESSEUSES").
dico("T", 10, "TREUILLAGE").
dico("T", 10, "TREUILLAIS").
dico("T", 10, "TREUILLAIT").
dico("T", 10, "TREUILLANT").
dico("T", 10, "TREUILLEES").
dico("T", 10, "TREUILLENT").
dico("T", 10, "TREUILLERA").
dico("T", 10, "TREUILLIEZ").
dico("T", 10, "TREUILLONS").
dico("T", 10, "TREVIRAMES").
dico("T", 10, "TREVIRASSE").
dico("T", 10, "TREVIRATES").
dico("T", 10, "TREVIRERAI").
dico("T", 10, "TREVIRERAS").
dico("T", 10, "TREVIREREZ").
dico("T", 10, "TREVIRIONS").
dico("T", 10, "TREVISANES").
dico("T", 10, "TRIADIQUES").
dico("T", 10, "TRIALCOOLS").
dico("T", 10, "TRIALISTES").
dico("T", 10, "TRIANDINES").
dico("T", 10, "TRIANDRIES").
dico("T", 10, "TRIANGULAI").
dico("T", 10, "TRIANGULAS").
dico("T", 10, "TRIANGULAT").
dico("T", 10, "TRIANGULEE").
dico("T", 10, "TRIANGULER").
dico("T", 10, "TRIANGULES").
dico("T", 10, "TRIANGULEZ").
dico("T", 10, "TRIASIQUES").
dico("T", 10, "TRIASSIONS").
dico("T", 10, "TRIATHLETE").
dico("T", 10, "TRIATHLONS").
dico("T", 10, "TRIBADISME").
dico("T", 10, "TRIBALISME").
dico("T", 10, "TRIBALLAIS").
dico("T", 10, "TRIBALLAIT").
dico("T", 10, "TRIBALLANT").
dico("T", 10, "TRIBALLEES").
dico("T", 10, "TRIBALLENT").
dico("T", 10, "TRIBALLERA").
dico("T", 10, "TRIBALLIEZ").
dico("T", 10, "TRIBALLONS").
dico("T", 10, "TRIBASIQUE").
dico("T", 10, "TRIBOLOGIE").
dico("T", 10, "TRIBOMETRE").
dico("T", 10, "TRIBORDAIS").
dico("T", 10, "TRIBOULETS").
dico("T", 10, "TRIBRAQUES").
dico("T", 10, "TRIBUTAIRE").
dico("T", 10, "TRICENNALE").
dico("T", 10, "TRICENNAUX").
dico("T", 10, "TRICEPHALE").
dico("T", 10, "TRICHAIENT").
dico("T", 10, "TRICHASSES").
dico("T", 10, "TRICHERAIS").
dico("T", 10, "TRICHERAIT").
dico("T", 10, "TRICHERENT").
dico("T", 10, "TRICHERIES").
dico("T", 10, "TRICHERIEZ").
dico("T", 10, "TRICHERONS").
dico("T", 10, "TRICHERONT").
dico("T", 10, "TRICHEUSES").
dico("T", 10, "TRICHIASIS").
dico("T", 10, "TRICHINEES").
dico("T", 10, "TRICHINEUX").
dico("T", 10, "TRICHINOSE").
dico("T", 10, "TRICHOLOME").
dico("T", 10, "TRICHROMES").
dico("T", 10, "TRICHROMIE").
dico("T", 10, "TRICKSTERS").
dico("T", 10, "TRICLINIUM").
dico("T", 10, "TRICOLORES").
dico("T", 10, "TRICOTAGES").
dico("T", 10, "TRICOTAMES").
dico("T", 10, "TRICOTASSE").
dico("T", 10, "TRICOTATES").
dico("T", 10, "TRICOTERAI").
dico("T", 10, "TRICOTERAS").
dico("T", 10, "TRICOTEREZ").
dico("T", 10, "TRICOTEURS").
dico("T", 10, "TRICOTEUSE").
dico("T", 10, "TRICOTIONS").
dico("T", 10, "TRICOURANT").
dico("T", 10, "TRICUSPIDE").
dico("T", 10, "TRIDACTYLE").
dico("T", 10, "TRIDENTEES").
dico("T", 10, "TRIENNALES").
dico("T", 10, "TRIERAIENT").
dico("T", 10, "TRIERARQUE").
dico("T", 10, "TRIESTINES").
dico("T", 10, "TRIFLUVIEN").
dico("T", 10, "TRIFOLIEES").
dico("T", 10, "TRIFOLIOLE").
dico("T", 10, "TRIFOLIUMS").
dico("T", 10, "TRIFORIUMS").
dico("T", 10, "TRIFOUILLA").
dico("T", 10, "TRIFOUILLE").
dico("T", 10, "TRIGEMINEE").
dico("T", 10, "TRIGEMINES").
dico("T", 10, "TRIGLYPHES").
dico("T", 10, "TRIGONELLE").
dico("T", 10, "TRIGRAMMES").
dico("T", 10, "TRIJUMEAUX").
dico("T", 10, "TRILATERAL").
dico("T", 10, "TRILINGUES").
dico("T", 10, "TRILITERES").
dico("T", 10, "TRILITTERE").
dico("T", 10, "TRILLAIENT").
dico("T", 10, "TRILLASSES").
dico("T", 10, "TRILLERAIS").
dico("T", 10, "TRILLERAIT").
dico("T", 10, "TRILLERENT").
dico("T", 10, "TRILLERIEZ").
dico("T", 10, "TRILLERONS").
dico("T", 10, "TRILLERONT").
dico("T", 10, "TRILOBITES").
dico("T", 10, "TRILOGIQUE").
dico("T", 10, "TRIMARDAIS").
dico("T", 10, "TRIMARDAIT").
dico("T", 10, "TRIMARDANT").
dico("T", 10, "TRIMARDENT").
dico("T", 10, "TRIMARDERA").
dico("T", 10, "TRIMARDEUR").
dico("T", 10, "TRIMARDIEZ").
dico("T", 10, "TRIMARDONS").
dico("T", 10, "TRIMASSENT").
dico("T", 10, "TRIMASSIEZ").
dico("T", 10, "TRIMBALAGE").
dico("T", 10, "TRIMBALAIS").
dico("T", 10, "TRIMBALAIT").
dico("T", 10, "TRIMBALANT").
dico("T", 10, "TRIMBALEES").
dico("T", 10, "TRIMBALENT").
dico("T", 10, "TRIMBALERA").
dico("T", 10, "TRIMBALIEZ").
dico("T", 10, "TRIMBALLAI").
dico("T", 10, "TRIMBALLAS").
dico("T", 10, "TRIMBALLAT").
dico("T", 10, "TRIMBALLEE").
dico("T", 10, "TRIMBALLER").
dico("T", 10, "TRIMBALLES").
dico("T", 10, "TRIMBALLEZ").
dico("T", 10, "TRIMBALONS").
dico("T", 10, "TRIMERIONS").
dico("T", 10, "TRIMESTRES").
dico("T", 10, "TRIMOTEURS").
dico("T", 10, "TRINERVEES").
dico("T", 10, "TRINGLAMES").
dico("T", 10, "TRINGLASSE").
dico("T", 10, "TRINGLATES").
dico("T", 10, "TRINGLERAI").
dico("T", 10, "TRINGLERAS").
dico("T", 10, "TRINGLEREZ").
dico("T", 10, "TRINGLIONS").
dico("T", 10, "TRINITAIRE").
dico("T", 10, "TRINITRATE").
dico("T", 10, "TRINITRINE").
dico("T", 10, "TRINQUAMES").
dico("T", 10, "TRINQUARTS").
dico("T", 10, "TRINQUASSE").
dico("T", 10, "TRINQUATES").
dico("T", 10, "TRINQUERAI").
dico("T", 10, "TRINQUERAS").
dico("T", 10, "TRINQUEREZ").
dico("T", 10, "TRINQUETTE").
dico("T", 10, "TRINQUEURS").
dico("T", 10, "TRINQUEUSE").
dico("T", 10, "TRINQUIONS").
dico("T", 10, "TRIOLISMES").
dico("T", 10, "TRIOMPHAIS").
dico("T", 10, "TRIOMPHAIT").
dico("T", 10, "TRIOMPHALE").
dico("T", 10, "TRIOMPHANT").
dico("T", 10, "TRIOMPHAUX").
dico("T", 10, "TRIOMPHENT").
dico("T", 10, "TRIOMPHERA").
dico("T", 10, "TRIOMPHIEZ").
dico("T", 10, "TRIOMPHONS").
dico("T", 10, "TRIPAILLES").
dico("T", 10, "TRIPARTIES").
dico("T", 10, "TRIPARTITE").
dico("T", 10, "TRIPHASEES").
dico("T", 10, "TRIPLAIENT").
dico("T", 10, "TRIPLASSES").
dico("T", 10, "TRIPLEMENT").
dico("T", 10, "TRIPLERAIS").
dico("T", 10, "TRIPLERAIT").
dico("T", 10, "TRIPLERENT").
dico("T", 10, "TRIPLERIEZ").
dico("T", 10, "TRIPLERONS").
dico("T", 10, "TRIPLERONT").
dico("T", 10, "TRIPLETTES").
dico("T", 10, "TRIPLICATA").
dico("T", 10, "TRIPLOIDES").
dico("T", 10, "TRIPLOIDIE").
dico("T", 10, "TRIPORTEUR").
dico("T", 10, "TRIPOTAGES").
dico("T", 10, "TRIPOTAMES").
dico("T", 10, "TRIPOTASSE").
dico("T", 10, "TRIPOTATES").
dico("T", 10, "TRIPOTERAI").
dico("T", 10, "TRIPOTERAS").
dico("T", 10, "TRIPOTEREZ").
dico("T", 10, "TRIPOTEURS").
dico("T", 10, "TRIPOTEUSE").
dico("T", 10, "TRIPOTIONS").
dico("T", 10, "TRIPTYQUES").
dico("T", 10, "TRIQUAIENT").
dico("T", 10, "TRIQUARDES").
dico("T", 10, "TRIQUASSES").
dico("T", 10, "TRIQUERAIS").
dico("T", 10, "TRIQUERAIT").
dico("T", 10, "TRIQUERENT").
dico("T", 10, "TRIQUERIEZ").
dico("T", 10, "TRIQUERONS").
dico("T", 10, "TRIQUERONT").
dico("T", 10, "TRIQUETRES").
dico("T", 10, "TRISAIEULE").
dico("T", 10, "TRISAIEULS").
dico("T", 10, "TRISANNUEL").
dico("T", 10, "TRISECTEUR").
dico("T", 10, "TRISECTION").
dico("T", 10, "TRISMIQUES").
dico("T", 10, "TRISOMIQUE").
dico("T", 10, "TRISSAIENT").
dico("T", 10, "TRISSASSES").
dico("T", 10, "TRISSERAIS").
dico("T", 10, "TRISSERAIT").
dico("T", 10, "TRISSERENT").
dico("T", 10, "TRISSERIEZ").
dico("T", 10, "TRISSERONS").
dico("T", 10, "TRISSERONT").
dico("T", 10, "TRISTEMENT").
dico("T", 10, "TRISTESSES").
dico("T", 10, "TRISTOUNET").
dico("T", 10, "TRISYLLABE").
dico("T", 10, "TRITICALES").
dico("T", 10, "TRITURABLE").
dico("T", 10, "TRITURAMES").
dico("T", 10, "TRITURASSE").
dico("T", 10, "TRITURATES").
dico("T", 10, "TRITURERAI").
dico("T", 10, "TRITURERAS").
dico("T", 10, "TRITUREREZ").
dico("T", 10, "TRITURIONS").
dico("T", 10, "TRIUMVIRAL").
dico("T", 10, "TRIUMVIRAT").
dico("T", 10, "TRIVALENCE").
dico("T", 10, "TRIVALENTE").
dico("T", 10, "TRIVALENTS").
dico("T", 10, "TRIVIALITE").
dico("T", 10, "TROCHAIQUE").
dico("T", 10, "TROCHANTER").
dico("T", 10, "TROCHILIDE").
dico("T", 10, "TROCHISQUE").
dico("T", 10, "TROCHITERS").
dico("T", 10, "TROCHLEENS").
dico("T", 10, "TROGLOBIES").
dico("T", 10, "TROGLODYTE").
dico("T", 10, "TROGONIDES").
dico("T", 10, "TROISIEMES").
dico("T", 10, "TROLLEYBUS").
dico("T", 10, "TROMBIDION").
dico("T", 10, "TROMPAIENT").
dico("T", 10, "TROMPASSES").
dico("T", 10, "TROMPERAIS").
dico("T", 10, "TROMPERAIT").
dico("T", 10, "TROMPERENT").
dico("T", 10, "TROMPERIES").
dico("T", 10, "TROMPERIEZ").
dico("T", 10, "TROMPERONS").
dico("T", 10, "TROMPERONT").
dico("T", 10, "TROMPETAIS").
dico("T", 10, "TROMPETAIT").
dico("T", 10, "TROMPETANT").
dico("T", 10, "TROMPETEES").
dico("T", 10, "TROMPETEUR").
dico("T", 10, "TROMPETIEZ").
dico("T", 10, "TROMPETONS").
dico("T", 10, "TROMPETTES").
dico("T", 10, "TROMPEUSES").
dico("T", 10, "TROMPILLON").
dico("T", 10, "TRONASSENT").
dico("T", 10, "TRONASSIEZ").
dico("T", 10, "TRONCATION").
dico("T", 10, "TRONCATURE").
dico("T", 10, "TRONCONNAI").
dico("T", 10, "TRONCONNAS").
dico("T", 10, "TRONCONNAT").
dico("T", 10, "TRONCONNEE").
dico("T", 10, "TRONCONNER").
dico("T", 10, "TRONCONNES").
dico("T", 10, "TRONCONNEZ").
dico("T", 10, "TRONERIONS").
dico("T", 10, "TRONQUAMES").
dico("T", 10, "TRONQUASSE").
dico("T", 10, "TRONQUATES").
dico("T", 10, "TRONQUERAI").
dico("T", 10, "TRONQUERAS").
dico("T", 10, "TRONQUEREZ").
dico("T", 10, "TRONQUIONS").
dico("T", 10, "TROPEZIENS").
dico("T", 10, "TROPHIQUES").
dico("T", 10, "TROPICALES").
dico("T", 10, "TROPOPAUSE").
dico("T", 10, "TROQUAIENT").
dico("T", 10, "TROQUASSES").
dico("T", 10, "TROQUERAIS").
dico("T", 10, "TROQUERAIT").
dico("T", 10, "TROQUERENT").
dico("T", 10, "TROQUERIEZ").
dico("T", 10, "TROQUERONS").
dico("T", 10, "TROQUERONT").
dico("T", 10, "TROQUEUSES").
dico("T", 10, "TROTSKISME").
dico("T", 10, "TROTSKISTE").
dico("T", 10, "TROTSKYSME").
dico("T", 10, "TROTSKYSTE").
dico("T", 10, "TROTTAIENT").
dico("T", 10, "TROTTASSES").
dico("T", 10, "TROTTERAIS").
dico("T", 10, "TROTTERAIT").
dico("T", 10, "TROTTERENT").
dico("T", 10, "TROTTERIEZ").
dico("T", 10, "TROTTERONS").
dico("T", 10, "TROTTERONT").
dico("T", 10, "TROTTEUSES").
dico("T", 10, "TROTTINAIS").
dico("T", 10, "TROTTINAIT").
dico("T", 10, "TROTTINANT").
dico("T", 10, "TROTTINENT").
dico("T", 10, "TROTTINERA").
dico("T", 10, "TROTTINIEZ").
dico("T", 10, "TROTTINONS").
dico("T", 10, "TROUASSENT").
dico("T", 10, "TROUASSIEZ").
dico("T", 10, "TROUBADOUR").
dico("T", 10, "TROUBLAMES").
dico("T", 10, "TROUBLANTE").
dico("T", 10, "TROUBLANTS").
dico("T", 10, "TROUBLASSE").
dico("T", 10, "TROUBLATES").
dico("T", 10, "TROUBLEAUX").
dico("T", 10, "TROUBLERAI").
dico("T", 10, "TROUBLERAS").
dico("T", 10, "TROUBLEREZ").
dico("T", 10, "TROUBLIONS").
dico("T", 10, "TROUERIONS").
dico("T", 10, "TROUFIGNON").
dico("T", 10, "TROUILLAIS").
dico("T", 10, "TROUILLAIT").
dico("T", 10, "TROUILLANT").
dico("T", 10, "TROUILLARD").
dico("T", 10, "TROUILLENT").
dico("T", 10, "TROUILLERA").
dico("T", 10, "TROUILLIEZ").
dico("T", 10, "TROUILLONS").
dico("T", 10, "TROUPIALES").
dico("T", 10, "TROUSSAGES").
dico("T", 10, "TROUSSAMES").
dico("T", 10, "TROUSSASSE").
dico("T", 10, "TROUSSATES").
dico("T", 10, "TROUSSEAUX").
dico("T", 10, "TROUSSERAI").
dico("T", 10, "TROUSSERAS").
dico("T", 10, "TROUSSEREZ").
dico("T", 10, "TROUSSEURS").
dico("T", 10, "TROUSSIONS").
dico("T", 10, "TROUVABLES").
dico("T", 10, "TROUVAIENT").
dico("T", 10, "TROUVAILLE").
dico("T", 10, "TROUVASSES").
dico("T", 10, "TROUVERAIS").
dico("T", 10, "TROUVERAIT").
dico("T", 10, "TROUVERENT").
dico("T", 10, "TROUVERIEZ").
dico("T", 10, "TROUVERONS").
dico("T", 10, "TROUVERONT").
dico("T", 10, "TROUVEUSES").
dico("T", 10, "TRUANDAMES").
dico("T", 10, "TRUANDASSE").
dico("T", 10, "TRUANDATES").
dico("T", 10, "TRUANDERAI").
dico("T", 10, "TRUANDERAS").
dico("T", 10, "TRUANDEREZ").
dico("T", 10, "TRUANDERIE").
dico("T", 10, "TRUANDIONS").
dico("T", 10, "TRUCHEMENT").
dico("T", 10, "TRUCIDAMES").
dico("T", 10, "TRUCIDASSE").
dico("T", 10, "TRUCIDATES").
dico("T", 10, "TRUCIDERAI").
dico("T", 10, "TRUCIDERAS").
dico("T", 10, "TRUCIDEREZ").
dico("T", 10, "TRUCIDIONS").
dico("T", 10, "TRUCMUCHES").
dico("T", 10, "TRUCULENCE").
dico("T", 10, "TRUCULENTE").
dico("T", 10, "TRUCULENTS").
dico("T", 10, "TRUFFAIENT").
dico("T", 10, "TRUFFASSES").
dico("T", 10, "TRUFFERAIS").
dico("T", 10, "TRUFFERAIT").
dico("T", 10, "TRUFFERENT").
dico("T", 10, "TRUFFERIEZ").
dico("T", 10, "TRUFFERONS").
dico("T", 10, "TRUFFERONT").
dico("T", 10, "TRUFFIERES").
dico("T", 10, "TRUITELLES").
dico("T", 10, "TRUQUAIENT").
dico("T", 10, "TRUQUASSES").
dico("T", 10, "TRUQUERAIS").
dico("T", 10, "TRUQUERAIT").
dico("T", 10, "TRUQUERENT").
dico("T", 10, "TRUQUERIEZ").
dico("T", 10, "TRUQUERONS").
dico("T", 10, "TRUQUERONT").
dico("T", 10, "TRUQUEUSES").
dico("T", 10, "TRUQUISTES").
dico("T", 10, "TRUSQUINAI").
dico("T", 10, "TRUSQUINAS").
dico("T", 10, "TRUSQUINAT").
dico("T", 10, "TRUSQUINEE").
dico("T", 10, "TRUSQUINER").
dico("T", 10, "TRUSQUINES").
dico("T", 10, "TRUSQUINEZ").
dico("T", 10, "TRUSTAIENT").
dico("T", 10, "TRUSTASSES").
dico("T", 10, "TRUSTERAIS").
dico("T", 10, "TRUSTERAIT").
dico("T", 10, "TRUSTERENT").
dico("T", 10, "TRUSTERIEZ").
dico("T", 10, "TRUSTERONS").
dico("T", 10, "TRUSTERONT").
dico("T", 10, "TRYPTAMINE").
dico("T", 10, "TSAREVITCH").
dico("T", 10, "TUBASSIONS").
dico("T", 10, "TUBERACEES").
dico("T", 10, "TUBERAIENT").
dico("T", 10, "TUBERCULES").
dico("T", 10, "TUBEREUSES").
dico("T", 10, "TUBERISEES").
dico("T", 10, "TUBEROSITE").
dico("T", 10, "TUBULAIRES").
dico("T", 10, "TUBULEUSES").
dico("T", 10, "TUILASSENT").
dico("T", 10, "TUILASSIEZ").
dico("T", 10, "TUILERIONS").
dico("T", 10, "TULAREMIES").
dico("T", 10, "TUMEFIAMES").
dico("T", 10, "TUMEFIASSE").
dico("T", 10, "TUMEFIATES").
dico("T", 10, "TUMEFIERAI").
dico("T", 10, "TUMEFIERAS").
dico("T", 10, "TUMEFIEREZ").
dico("T", 10, "TUMEFIIONS").
dico("T", 10, "TUMESCENCE").
dico("T", 10, "TUMESCENTE").
dico("T", 10, "TUMESCENTS").
dico("T", 10, "TUMORIGENE").
dico("T", 10, "TUMULAIRES").
dico("T", 10, "TUMULTUEUX").
dico("T", 10, "TUNGSTATES").
dico("T", 10, "TUNGSTENES").
dico("T", 10, "TUNGSTIQUE").
dico("T", 10, "TUNICELLES").
dico("T", 10, "TUNISIENNE").
dico("T", 10, "TUNISOISES").
dico("T", 10, "TUNNELIERS").
dico("T", 10, "TUPINAMBIS").
dico("T", 10, "TUPPERWARE").
dico("T", 10, "TURBIDITES").
dico("T", 10, "TURBINAGES").
dico("T", 10, "TURBINAMES").
dico("T", 10, "TURBINASSE").
dico("T", 10, "TURBINATES").
dico("T", 10, "TURBINELLE").
dico("T", 10, "TURBINERAI").
dico("T", 10, "TURBINERAS").
dico("T", 10, "TURBINEREZ").
dico("T", 10, "TURBINIONS").
dico("T", 10, "TURBOPOMPE").
dico("T", 10, "TURBOTIERE").
dico("T", 10, "TURBOTRAIN").
dico("T", 10, "TURBULENCE").
dico("T", 10, "TURBULENTE").
dico("T", 10, "TURBULENTS").
dico("T", 10, "TURBULETTE").
dico("T", 10, "TURCOPHONE").
dico("T", 10, "TURGESCENT").
dico("T", 10, "TURINOISES").
dico("T", 10, "TURLUPINAI").
dico("T", 10, "TURLUPINAS").
dico("T", 10, "TURLUPINAT").
dico("T", 10, "TURLUPINEE").
dico("T", 10, "TURLUPINER").
dico("T", 10, "TURLUPINES").
dico("T", 10, "TURLUPINEZ").
dico("T", 10, "TURLURETTE").
dico("T", 10, "TURLUTAINE").
dico("T", 10, "TURLUTAMES").
dico("T", 10, "TURLUTASSE").
dico("T", 10, "TURLUTATES").
dico("T", 10, "TURLUTERAI").
dico("T", 10, "TURLUTERAS").
dico("T", 10, "TURLUTEREZ").
dico("T", 10, "TURLUTIONS").
dico("T", 10, "TURONIENNE").
dico("T", 10, "TURPITUDES").
dico("T", 10, "TURQUERIES").
dico("T", 10, "TURQUETTES").
dico("T", 10, "TURQUOISES").
dico("T", 10, "TURRICULEE").
dico("T", 10, "TURRICULES").
dico("T", 10, "TURRITELLE").
dico("T", 10, "TUSSILAGES").
dico("T", 10, "TUTELAIRES").
dico("T", 10, "TUTEURAGES").
dico("T", 10, "TUTEURAMES").
dico("T", 10, "TUTEURASSE").
dico("T", 10, "TUTEURATES").
dico("T", 10, "TUTEURERAI").
dico("T", 10, "TUTEURERAS").
dico("T", 10, "TUTEUREREZ").
dico("T", 10, "TUTEURIONS").
dico("T", 10, "TUTOIEMENT").
dico("T", 10, "TUTOIERAIS").
dico("T", 10, "TUTOIERAIT").
dico("T", 10, "TUTOIERIEZ").
dico("T", 10, "TUTOIERONS").
dico("T", 10, "TUTOIERONT").
dico("T", 10, "TUTOYAIENT").
dico("T", 10, "TUTOYASSES").
dico("T", 10, "TUTOYERENT").
dico("T", 10, "TUTOYEUSES").
dico("T", 10, "TUVALUANES").
dico("T", 10, "TUYAUTAGES").
dico("T", 10, "TUYAUTAMES").
dico("T", 10, "TUYAUTASSE").
dico("T", 10, "TUYAUTATES").
dico("T", 10, "TUYAUTERAI").
dico("T", 10, "TUYAUTERAS").
dico("T", 10, "TUYAUTEREZ").
dico("T", 10, "TUYAUTERIE").
dico("T", 10, "TUYAUTEURS").
dico("T", 10, "TUYAUTEUSE").
dico("T", 10, "TUYAUTIONS").
dico("T", 10, "TWISTAIENT").
dico("T", 10, "TWISTASSES").
dico("T", 10, "TWISTERAIS").
dico("T", 10, "TWISTERAIT").
dico("T", 10, "TWISTERENT").
dico("T", 10, "TWISTERIEZ").
dico("T", 10, "TWISTERONS").
dico("T", 10, "TWISTERONT").
dico("T", 10, "TWISTEUSES").
dico("T", 10, "TYMPANALES").
dico("T", 10, "TYMPANIQUE").
dico("T", 10, "TYMPANISAI").
dico("T", 10, "TYMPANISAS").
dico("T", 10, "TYMPANISAT").
dico("T", 10, "TYMPANISEE").
dico("T", 10, "TYMPANISER").
dico("T", 10, "TYMPANISES").
dico("T", 10, "TYMPANISEZ").
dico("T", 10, "TYMPANISME").
dico("T", 10, "TYPASSIONS").
dico("T", 10, "TYPERAIENT").
dico("T", 10, "TYPOGRAPHE").
dico("T", 10, "TYPOLOGIES").
dico("T", 10, "TYPOMETRES").
dico("T", 10, "TYPTOLOGIE").
dico("T", 10, "TYRANNEAUX").
dico("T", 10, "TYRANNIQUE").
dico("T", 10, "TYRANNISAI").
dico("T", 10, "TYRANNISAS").
dico("T", 10, "TYRANNISAT").
dico("T", 10, "TYRANNISEE").
dico("T", 10, "TYRANNISER").
dico("T", 10, "TYRANNISES").
dico("T", 10, "TYRANNISEZ").
dico("T", 10, "TYROLIENNE").
dico("T", 10, "TYROSINASE").
dico("T", 10, "TZAREVITCH").
