dico("T", 5, "TAALS").
dico("T", 5, "TABAC").
dico("T", 5, "TABAR").
dico("T", 5, "TABES").
dico("T", 5, "TABLA").
dico("T", 5, "TABLE").
dico("T", 5, "TABOR").
dico("T", 5, "TABOU").
dico("T", 5, "TABUN").
dico("T", 5, "TACCA").
dico("T", 5, "TACET").
dico("T", 5, "TACHA").
dico("T", 5, "TACHE").
dico("T", 5, "TACLA").
dico("T", 5, "TACLE").
dico("T", 5, "TACON").
dico("T", 5, "TACOS").
dico("T", 5, "TACOT").
dico("T", 5, "TACTS").
dico("T", 5, "TAELS").
dico("T", 5, "TAFFE").
dico("T", 5, "TAFIA").
dico("T", 5, "TAGAL").
dico("T", 5, "TAGGA").
dico("T", 5, "TAGGE").
dico("T", 5, "TAGME").
dico("T", 5, "TAGUA").
dico("T", 5, "TAGUE").
dico("T", 5, "TAIES").
dico("T", 5, "TAIGA").
dico("T", 5, "TAIJI").
dico("T", 5, "TAINS").
dico("T", 5, "TAIRA").
dico("T", 5, "TAIRE").
dico("T", 5, "TAISE").
dico("T", 5, "TAKAS").
dico("T", 5, "TALAI").
dico("T", 5, "TALAS").
dico("T", 5, "TALAT").
dico("T", 5, "TALCS").
dico("T", 5, "TALED").
dico("T", 5, "TALEE").
dico("T", 5, "TALER").
dico("T", 5, "TALES").
dico("T", 5, "TALET").
dico("T", 5, "TALEZ").
dico("T", 5, "TALLA").
dico("T", 5, "TALLE").
dico("T", 5, "TALON").
dico("T", 5, "TALUS").
dico("T", 5, "TAMIA").
dico("T", 5, "TAMIL").
dico("T", 5, "TAMIS").
dico("T", 5, "TANCA").
dico("T", 5, "TANCE").
dico("T", 5, "TANGO").
dico("T", 5, "TANIN").
dico("T", 5, "TANKA").
dico("T", 5, "TANKS").
dico("T", 5, "TANNA").
dico("T", 5, "TANNE").
dico("T", 5, "TANTE").
dico("T", 5, "TAONS").
dico("T", 5, "TAPAI").
dico("T", 5, "TAPAS").
dico("T", 5, "TAPAT").
dico("T", 5, "TAPEE").
dico("T", 5, "TAPER").
dico("T", 5, "TAPES").
dico("T", 5, "TAPEZ").
dico("T", 5, "TAPIE").
dico("T", 5, "TAPIN").
dico("T", 5, "TAPIR").
dico("T", 5, "TAPIS").
dico("T", 5, "TAPIT").
dico("T", 5, "TAPON").
dico("T", 5, "TAQUA").
dico("T", 5, "TAQUE").
dico("T", 5, "TARAF").
dico("T", 5, "TARAI").
dico("T", 5, "TARAS").
dico("T", 5, "TARAT").
dico("T", 5, "TARDA").
dico("T", 5, "TARDE").
dico("T", 5, "TAREE").
dico("T", 5, "TARER").
dico("T", 5, "TARES").
dico("T", 5, "TARET").
dico("T", 5, "TAREZ").
dico("T", 5, "TARGE").
dico("T", 5, "TARIE").
dico("T", 5, "TARIF").
dico("T", 5, "TARIN").
dico("T", 5, "TARIR").
dico("T", 5, "TARIS").
dico("T", 5, "TARIT").
dico("T", 5, "TAROS").
dico("T", 5, "TAROT").
dico("T", 5, "TARSE").
dico("T", 5, "TARTE").
dico("T", 5, "TARTI").
dico("T", 5, "TASSA").
dico("T", 5, "TASSE").
dico("T", 5, "TATAI").
dico("T", 5, "TATAR").
dico("T", 5, "TATAS").
dico("T", 5, "TATAT").
dico("T", 5, "TATEE").
dico("T", 5, "TATER").
dico("T", 5, "TATES").
dico("T", 5, "TATEZ").
dico("T", 5, "TATIE").
dico("T", 5, "TATIN").
dico("T", 5, "TATIS").
dico("T", 5, "TATOU").
dico("T", 5, "TAUDA").
dico("T", 5, "TAUDE").
dico("T", 5, "TAUDS").
dico("T", 5, "TAULE").
dico("T", 5, "TAUON").
dico("T", 5, "TAUPA").
dico("T", 5, "TAUPE").
dico("T", 5, "TAURE").
dico("T", 5, "TAVEL").
dico("T", 5, "TAXAI").
dico("T", 5, "TAXAS").
dico("T", 5, "TAXAT").
dico("T", 5, "TAXEE").
dico("T", 5, "TAXER").
dico("T", 5, "TAXES").
dico("T", 5, "TAXEZ").
dico("T", 5, "TAXIE").
dico("T", 5, "TAXIS").
dico("T", 5, "TAXOL").
dico("T", 5, "TAXON").
dico("T", 5, "TAXUM").
dico("T", 5, "TAXUS").
dico("T", 5, "TCHAN").
dico("T", 5, "TCHAO").
dico("T", 5, "TCHIN").
dico("T", 5, "TEAMS").
dico("T", 5, "TECKS").
dico("T", 5, "TEFAL").
dico("T", 5, "TEINS").
dico("T", 5, "TEINT").
dico("T", 5, "TEJUS").
dico("T", 5, "TELES").
dico("T", 5, "TELEX").
dico("T", 5, "TELLE").
dico("T", 5, "TELLS").
dico("T", 5, "TEMPE").
dico("T", 5, "TEMPI").
dico("T", 5, "TEMPO").
dico("T", 5, "TEMPS").
dico("T", 5, "TENDE").
dico("T", 5, "TENDS").
dico("T", 5, "TENDU").
dico("T", 5, "TENEZ").
dico("T", 5, "TENGE").
dico("T", 5, "TENIA").
dico("T", 5, "TENIR").
dico("T", 5, "TENON").
dico("T", 5, "TENOR").
dico("T", 5, "TENTA").
dico("T", 5, "TENTE").
dico("T", 5, "TENUE").
dico("T", 5, "TENUS").
dico("T", 5, "TEPUI").
dico("T", 5, "TERCA").
dico("T", 5, "TERCE").
dico("T", 5, "TERME").
dico("T", 5, "TERNE").
dico("T", 5, "TERNI").
dico("T", 5, "TERRA").
dico("T", 5, "TERRE").
dico("T", 5, "TERRI").
dico("T", 5, "TERSA").
dico("T", 5, "TERSE").
dico("T", 5, "TESLA").
dico("T", 5, "TESTA").
dico("T", 5, "TESTE").
dico("T", 5, "TESTS").
dico("T", 5, "TETAI").
dico("T", 5, "TETAS").
dico("T", 5, "TETAT").
dico("T", 5, "TETEE").
dico("T", 5, "TETER").
dico("T", 5, "TETES").
dico("T", 5, "TETEZ").
dico("T", 5, "TETIN").
dico("T", 5, "TETON").
dico("T", 5, "TETRA").
dico("T", 5, "TETTE").
dico("T", 5, "TETUE").
dico("T", 5, "TETUS").
dico("T", 5, "TEUFS").
dico("T", 5, "TEXAN").
dico("T", 5, "TEXTE").
dico("T", 5, "TEXTO").
dico("T", 5, "TEZIG").
dico("T", 5, "THAIE").
dico("T", 5, "THAIS").
dico("T", 5, "THANE").
dico("T", 5, "THEME").
dico("T", 5, "THESE").
dico("T", 5, "THETA").
dico("T", 5, "THETE").
dico("T", 5, "THIOL").
dico("T", 5, "THONS").
dico("T", 5, "THORA").
dico("T", 5, "THUGS").
dico("T", 5, "THUNE").
dico("T", 5, "THUYA").
dico("T", 5, "THYMS").
dico("T", 5, "TIANS").
dico("T", 5, "TIARE").
dico("T", 5, "TIBIA").
dico("T", 5, "TICAL").
dico("T", 5, "TIEDE").
dico("T", 5, "TIEDI").
dico("T", 5, "TIENS").
dico("T", 5, "TIENT").
dico("T", 5, "TIERS").
dico("T", 5, "TIFFE").
dico("T", 5, "TIGEA").
dico("T", 5, "TIGER").
dico("T", 5, "TIGES").
dico("T", 5, "TIGEZ").
dico("T", 5, "TIGRA").
dico("T", 5, "TIGRE").
dico("T", 5, "TIKIS").
dico("T", 5, "TILDE").
dico("T", 5, "TILLA").
dico("T", 5, "TILLE").
dico("T", 5, "TILTA").
dico("T", 5, "TILTE").
dico("T", 5, "TILTS").
dico("T", 5, "TIMON").
dico("T", 5, "TINES").
dico("T", 5, "TINTA").
dico("T", 5, "TINTE").
dico("T", 5, "TIPAI").
dico("T", 5, "TIPAS").
dico("T", 5, "TIPAT").
dico("T", 5, "TIPEE").
dico("T", 5, "TIPER").
dico("T", 5, "TIPES").
dico("T", 5, "TIPEZ").
dico("T", 5, "TIPIS").
dico("T", 5, "TIPPA").
dico("T", 5, "TIPPE").
dico("T", 5, "TIQUA").
dico("T", 5, "TIQUE").
dico("T", 5, "TIRAI").
dico("T", 5, "TIRAS").
dico("T", 5, "TIRAT").
dico("T", 5, "TIREE").
dico("T", 5, "TIRER").
dico("T", 5, "TIRES").
dico("T", 5, "TIRET").
dico("T", 5, "TIREZ").
dico("T", 5, "TISON").
dico("T", 5, "TISSA").
dico("T", 5, "TISSE").
dico("T", 5, "TISSU").
dico("T", 5, "TITAN").
dico("T", 5, "TITIS").
dico("T", 5, "TITRA").
dico("T", 5, "TITRE").
dico("T", 5, "TITUS").
dico("T", 5, "TJALE").
dico("T", 5, "TMESE").
dico("T", 5, "TOAST").
dico("T", 5, "TOBYS").
dico("T", 5, "TOFUS").
dico("T", 5, "TOGES").
dico("T", 5, "TOILA").
dico("T", 5, "TOILE").
dico("T", 5, "TOISA").
dico("T", 5, "TOISE").
dico("T", 5, "TOITS").
dico("T", 5, "TOKAI").
dico("T", 5, "TOKAJ").
dico("T", 5, "TOKAY").
dico("T", 5, "TOLAI").
dico("T", 5, "TOLAR").
dico("T", 5, "TOLAS").
dico("T", 5, "TOLAT").
dico("T", 5, "TOLEE").
dico("T", 5, "TOLER").
dico("T", 5, "TOLES").
dico("T", 5, "TOLET").
dico("T", 5, "TOLEZ").
dico("T", 5, "TOLLE").
dico("T", 5, "TOLUS").
dico("T", 5, "TOMAI").
dico("T", 5, "TOMAN").
dico("T", 5, "TOMAS").
dico("T", 5, "TOMAT").
dico("T", 5, "TOMBA").
dico("T", 5, "TOMBE").
dico("T", 5, "TOMEE").
dico("T", 5, "TOMER").
dico("T", 5, "TOMES").
dico("T", 5, "TOMEZ").
dico("T", 5, "TOMME").
dico("T", 5, "TOMMY").
dico("T", 5, "TONAL").
dico("T", 5, "TONCA").
dico("T", 5, "TONDE").
dico("T", 5, "TONDS").
dico("T", 5, "TONDU").
dico("T", 5, "TONER").
dico("T", 5, "TONGS").
dico("T", 5, "TONIC").
dico("T", 5, "TONIE").
dico("T", 5, "TONKA").
dico("T", 5, "TONNA").
dico("T", 5, "TONNE").
dico("T", 5, "TONTE").
dico("T", 5, "TONUS").
dico("T", 5, "TOPAI").
dico("T", 5, "TOPAS").
dico("T", 5, "TOPAT").
dico("T", 5, "TOPER").
dico("T", 5, "TOPES").
dico("T", 5, "TOPEZ").
dico("T", 5, "TOPOS").
dico("T", 5, "TOQUA").
dico("T", 5, "TOQUE").
dico("T", 5, "TORAH").
dico("T", 5, "TORDE").
dico("T", 5, "TORDS").
dico("T", 5, "TORDU").
dico("T", 5, "TOREA").
dico("T", 5, "TOREE").
dico("T", 5, "TORES").
dico("T", 5, "TORII").
dico("T", 5, "TORIL").
dico("T", 5, "TORON").
dico("T", 5, "TORRS").
dico("T", 5, "TORSE").
dico("T", 5, "TORTE").
dico("T", 5, "TORTS").
dico("T", 5, "TORTU").
dico("T", 5, "TORVE").
dico("T", 5, "TORYS").
dico("T", 5, "TOSSA").
dico("T", 5, "TOSSE").
dico("T", 5, "TOTAL").
dico("T", 5, "TOTEM").
dico("T", 5, "TOTON").
dico("T", 5, "TOTOS").
dico("T", 5, "TOUAI").
dico("T", 5, "TOUAS").
dico("T", 5, "TOUAT").
dico("T", 5, "TOUEE").
dico("T", 5, "TOUER").
dico("T", 5, "TOUES").
dico("T", 5, "TOUEZ").
dico("T", 5, "TOURD").
dico("T", 5, "TOURS").
dico("T", 5, "TOUTE").
dico("T", 5, "TOUTS").
dico("T", 5, "TRABE").
dico("T", 5, "TRACA").
dico("T", 5, "TRACE").
dico("T", 5, "TRACS").
dico("T", 5, "TRACT").
dico("T", 5, "TRAHI").
dico("T", 5, "TRAIE").
dico("T", 5, "TRAIL").
dico("T", 5, "TRAIN").
dico("T", 5, "TRAIS").
dico("T", 5, "TRAIT").
dico("T", 5, "TRAMA").
dico("T", 5, "TRAME").
dico("T", 5, "TRAMP").
dico("T", 5, "TRAMS").
dico("T", 5, "TRANS").
dico("T", 5, "TRAPU").
dico("T", 5, "TRASH").
dico("T", 5, "TREKS").
dico("T", 5, "TREMA").
dico("T", 5, "TREND").
dico("T", 5, "TREVE").
dico("T", 5, "TRIAI").
dico("T", 5, "TRIAL").
dico("T", 5, "TRIAS").
dico("T", 5, "TRIAT").
dico("T", 5, "TRIBU").
dico("T", 5, "TRICK").
dico("T", 5, "TRICS").
dico("T", 5, "TRIDI").
dico("T", 5, "TRIEE").
dico("T", 5, "TRIER").
dico("T", 5, "TRIES").
dico("T", 5, "TRIEZ").
dico("T", 5, "TRIGO").
dico("T", 5, "TRIMA").
dico("T", 5, "TRIME").
dico("T", 5, "TRINE").
dico("T", 5, "TRINS").
dico("T", 5, "TRIOL").
dico("T", 5, "TRIOS").
dico("T", 5, "TRIPE").
dico("T", 5, "TRIPS").
dico("T", 5, "TROCS").
dico("T", 5, "TROIS").
dico("T", 5, "TROLL").
dico("T", 5, "TRONA").
dico("T", 5, "TRONC").
dico("T", 5, "TRONE").
dico("T", 5, "TROPE").
dico("T", 5, "TROTS").
dico("T", 5, "TROUA").
dico("T", 5, "TROUE").
dico("T", 5, "TROUS").
dico("T", 5, "TRUCK").
dico("T", 5, "TRUCS").
dico("T", 5, "TRUIE").
dico("T", 5, "TRUST").
dico("T", 5, "TSARS").
dico("T", 5, "TSUBA").
dico("T", 5, "TUAGE").
dico("T", 5, "TUAIS").
dico("T", 5, "TUAIT").
dico("T", 5, "TUANT").
dico("T", 5, "TUBAI").
dico("T", 5, "TUBAS").
dico("T", 5, "TUBAT").
dico("T", 5, "TUBEE").
dico("T", 5, "TUBER").
dico("T", 5, "TUBES").
dico("T", 5, "TUBEZ").
dico("T", 5, "TUEES").
dico("T", 5, "TUENT").
dico("T", 5, "TUERA").
dico("T", 5, "TUEUR").
dico("T", 5, "TUIEZ").
dico("T", 5, "TUILA").
dico("T", 5, "TUILE").
dico("T", 5, "TULLE").
dico("T", 5, "TUMES").
dico("T", 5, "TUNER").
dico("T", 5, "TUNES").
dico("T", 5, "TUONS").
dico("T", 5, "TUPIS").
dico("T", 5, "TUQUE").
dico("T", 5, "TURBE").
dico("T", 5, "TURBO").
dico("T", 5, "TURCO").
dico("T", 5, "TURCS").
dico("T", 5, "TURFS").
dico("T", 5, "TURNE").
dico("T", 5, "TUSSE").
dico("T", 5, "TUTES").
dico("T", 5, "TUTIE").
dico("T", 5, "TUTSI").
dico("T", 5, "TUTTI").
dico("T", 5, "TUTUS").
dico("T", 5, "TUYAU").
dico("T", 5, "TWEED").
dico("T", 5, "TWEEN").
dico("T", 5, "TWILL").
dico("T", 5, "TWIST").
dico("T", 5, "TYPAI").
dico("T", 5, "TYPAS").
dico("T", 5, "TYPAT").
dico("T", 5, "TYPEE").
dico("T", 5, "TYPER").
dico("T", 5, "TYPES").
dico("T", 5, "TYPEZ").
dico("T", 5, "TYPHA").
dico("T", 5, "TYPON").
dico("T", 5, "TYPOS").
dico("T", 5, "TYRAN").
dico("T", 5, "TZARS").
