dico("T", 7, "TABAGIE").
dico("T", 7, "TABARDS").
dico("T", 7, "TABASCO").
dico("T", 7, "TABASKI").
dico("T", 7, "TABASSA").
dico("T", 7, "TABASSE").
dico("T", 7, "TABELLE").
dico("T", 7, "TABLAIS").
dico("T", 7, "TABLAIT").
dico("T", 7, "TABLANT").
dico("T", 7, "TABLARD").
dico("T", 7, "TABLARS").
dico("T", 7, "TABLEAU").
dico("T", 7, "TABLEES").
dico("T", 7, "TABLENT").
dico("T", 7, "TABLERA").
dico("T", 7, "TABLEUR").
dico("T", 7, "TABLIER").
dico("T", 7, "TABLIEZ").
dico("T", 7, "TABLOID").
dico("T", 7, "TABLONS").
dico("T", 7, "TABOUAI").
dico("T", 7, "TABOUAS").
dico("T", 7, "TABOUAT").
dico("T", 7, "TABOUEE").
dico("T", 7, "TABOUER").
dico("T", 7, "TABOUES").
dico("T", 7, "TABOUEZ").
dico("T", 7, "TABOULE").
dico("T", 7, "TABULAI").
dico("T", 7, "TABULAS").
dico("T", 7, "TABULAT").
dico("T", 7, "TABULEE").
dico("T", 7, "TABULER").
dico("T", 7, "TABULES").
dico("T", 7, "TABULEZ").
dico("T", 7, "TACAUDS").
dico("T", 7, "TACHAIS").
dico("T", 7, "TACHAIT").
dico("T", 7, "TACHANT").
dico("T", 7, "TACHEES").
dico("T", 7, "TACHENT").
dico("T", 7, "TACHERA").
dico("T", 7, "TACHETA").
dico("T", 7, "TACHETE").
dico("T", 7, "TACHIEZ").
dico("T", 7, "TACHINA").
dico("T", 7, "TACHINE").
dico("T", 7, "TACHONS").
dico("T", 7, "TACHYON").
dico("T", 7, "TACITES").
dico("T", 7, "TACLAIS").
dico("T", 7, "TACLAIT").
dico("T", 7, "TACLANT").
dico("T", 7, "TACLEES").
dico("T", 7, "TACLENT").
dico("T", 7, "TACLERA").
dico("T", 7, "TACLIEZ").
dico("T", 7, "TACLONS").
dico("T", 7, "TACTILE").
dico("T", 7, "TADJIKE").
dico("T", 7, "TADJIKS").
dico("T", 7, "TADORNE").
dico("T", 7, "TAENIAS").
dico("T", 7, "TAGALOG").
dico("T", 7, "TAGETES").
dico("T", 7, "TAGETTE").
dico("T", 7, "TAGGAIS").
dico("T", 7, "TAGGAIT").
dico("T", 7, "TAGGANT").
dico("T", 7, "TAGGEES").
dico("T", 7, "TAGGENT").
dico("T", 7, "TAGGERA").
dico("T", 7, "TAGGERS").
dico("T", 7, "TAGGIEZ").
dico("T", 7, "TAGGONS").
dico("T", 7, "TAGINES").
dico("T", 7, "TAGUAIS").
dico("T", 7, "TAGUAIT").
dico("T", 7, "TAGUANT").
dico("T", 7, "TAGUEES").
dico("T", 7, "TAGUENT").
dico("T", 7, "TAGUERA").
dico("T", 7, "TAGUEUR").
dico("T", 7, "TAGUIEZ").
dico("T", 7, "TAGUONS").
dico("T", 7, "TAILLAI").
dico("T", 7, "TAILLAS").
dico("T", 7, "TAILLAT").
dico("T", 7, "TAILLEE").
dico("T", 7, "TAILLER").
dico("T", 7, "TAILLES").
dico("T", 7, "TAILLEZ").
dico("T", 7, "TAILLIS").
dico("T", 7, "TAIRAIS").
dico("T", 7, "TAIRAIT").
dico("T", 7, "TAIRIEZ").
dico("T", 7, "TAIRONS").
dico("T", 7, "TAIRONT").
dico("T", 7, "TAISAIS").
dico("T", 7, "TAISAIT").
dico("T", 7, "TAISANT").
dico("T", 7, "TAISENT").
dico("T", 7, "TAISEUX").
dico("T", 7, "TAISIEZ").
dico("T", 7, "TAISONS").
dico("T", 7, "TAJINES").
dico("T", 7, "TALAIRE").
dico("T", 7, "TALAMES").
dico("T", 7, "TALASSE").
dico("T", 7, "TALATES").
dico("T", 7, "TALENTS").
dico("T", 7, "TALERAI").
dico("T", 7, "TALERAS").
dico("T", 7, "TALEREZ").
dico("T", 7, "TALETHS").
dico("T", 7, "TALIBAN").
dico("T", 7, "TALIBES").
dico("T", 7, "TALIONS").
dico("T", 7, "TALIPOT").
dico("T", 7, "TALITHS").
dico("T", 7, "TALITRE").
dico("T", 7, "TALLAGE").
dico("T", 7, "TALLAIS").
dico("T", 7, "TALLAIT").
dico("T", 7, "TALLANT").
dico("T", 7, "TALLENT").
dico("T", 7, "TALLERA").
dico("T", 7, "TALLETH").
dico("T", 7, "TALLIEZ").
dico("T", 7, "TALLITH").
dico("T", 7, "TALLONS").
dico("T", 7, "TALMUDS").
dico("T", 7, "TALOCHA").
dico("T", 7, "TALOCHE").
dico("T", 7, "TALONNA").
dico("T", 7, "TALONNE").
dico("T", 7, "TALPACK").
dico("T", 7, "TALQUAI").
dico("T", 7, "TALQUAS").
dico("T", 7, "TALQUAT").
dico("T", 7, "TALQUEE").
dico("T", 7, "TALQUER").
dico("T", 7, "TALQUES").
dico("T", 7, "TALQUEZ").
dico("T", 7, "TALURES").
dico("T", 7, "TALUTAI").
dico("T", 7, "TALUTAS").
dico("T", 7, "TALUTAT").
dico("T", 7, "TALUTEE").
dico("T", 7, "TALUTER").
dico("T", 7, "TALUTES").
dico("T", 7, "TALUTEZ").
dico("T", 7, "TALWEGS").
dico("T", 7, "TAMARIN").
dico("T", 7, "TAMARIS").
dico("T", 7, "TAMARIX").
dico("T", 7, "TAMBOUR").
dico("T", 7, "TAMIERS").
dico("T", 7, "TAMILES").
dico("T", 7, "TAMISAI").
dico("T", 7, "TAMISAS").
dico("T", 7, "TAMISAT").
dico("T", 7, "TAMISEE").
dico("T", 7, "TAMISER").
dico("T", 7, "TAMISES").
dico("T", 7, "TAMISEZ").
dico("T", 7, "TAMOULE").
dico("T", 7, "TAMOULS").
dico("T", 7, "TAMOURE").
dico("T", 7, "TAMPICO").
dico("T", 7, "TAMPONS").
dico("T", 7, "TANAGRA").
dico("T", 7, "TANCAIS").
dico("T", 7, "TANCAIT").
dico("T", 7, "TANCANT").
dico("T", 7, "TANCEES").
dico("T", 7, "TANCENT").
dico("T", 7, "TANCERA").
dico("T", 7, "TANCHES").
dico("T", 7, "TANCIEZ").
dico("T", 7, "TANCONS").
dico("T", 7, "TANDEMS").
dico("T", 7, "TANDOOR").
dico("T", 7, "TANGAGE").
dico("T", 7, "TANGARA").
dico("T", 7, "TANGENT").
dico("T", 7, "TANGONS").
dico("T", 7, "TANGUAI").
dico("T", 7, "TANGUAS").
dico("T", 7, "TANGUAT").
dico("T", 7, "TANGUER").
dico("T", 7, "TANGUES").
dico("T", 7, "TANGUEZ").
dico("T", 7, "TANIERE").
dico("T", 7, "TANIQUE").
dico("T", 7, "TANISAI").
dico("T", 7, "TANISAS").
dico("T", 7, "TANISAT").
dico("T", 7, "TANISEE").
dico("T", 7, "TANISER").
dico("T", 7, "TANISES").
dico("T", 7, "TANISEZ").
dico("T", 7, "TANKERS").
dico("T", 7, "TANNAGE").
dico("T", 7, "TANNAIS").
dico("T", 7, "TANNAIT").
dico("T", 7, "TANNANT").
dico("T", 7, "TANNEES").
dico("T", 7, "TANNENT").
dico("T", 7, "TANNERA").
dico("T", 7, "TANNEUR").
dico("T", 7, "TANNIEZ").
dico("T", 7, "TANNINS").
dico("T", 7, "TANNISA").
dico("T", 7, "TANNISE").
dico("T", 7, "TANNONS").
dico("T", 7, "TANRECS").
dico("T", 7, "TANSADS").
dico("T", 7, "TANTALE").
dico("T", 7, "TANTINE").
dico("T", 7, "TANTRAS").
dico("T", 7, "TAOISME").
dico("T", 7, "TAOISTE").
dico("T", 7, "TAPAGEA").
dico("T", 7, "TAPAGER").
dico("T", 7, "TAPAGES").
dico("T", 7, "TAPAGEZ").
dico("T", 7, "TAPAMES").
dico("T", 7, "TAPANTE").
dico("T", 7, "TAPANTS").
dico("T", 7, "TAPASSE").
dico("T", 7, "TAPATES").
dico("T", 7, "TAPECUL").
dico("T", 7, "TAPERAI").
dico("T", 7, "TAPERAS").
dico("T", 7, "TAPEREZ").
dico("T", 7, "TAPETTE").
dico("T", 7, "TAPEURS").
dico("T", 7, "TAPEUSE").
dico("T", 7, "TAPIMES").
dico("T", 7, "TAPINAI").
dico("T", 7, "TAPINAS").
dico("T", 7, "TAPINAT").
dico("T", 7, "TAPINER").
dico("T", 7, "TAPINES").
dico("T", 7, "TAPINEZ").
dico("T", 7, "TAPIOCA").
dico("T", 7, "TAPIONS").
dico("T", 7, "TAPIRAI").
dico("T", 7, "TAPIRAS").
dico("T", 7, "TAPIREZ").
dico("T", 7, "TAPISSA").
dico("T", 7, "TAPISSE").
dico("T", 7, "TAPITES").
dico("T", 7, "TAPOCHA").
dico("T", 7, "TAPOCHE").
dico("T", 7, "TAPONNA").
dico("T", 7, "TAPONNE").
dico("T", 7, "TAPOTAI").
dico("T", 7, "TAPOTAS").
dico("T", 7, "TAPOTAT").
dico("T", 7, "TAPOTEE").
dico("T", 7, "TAPOTER").
dico("T", 7, "TAPOTES").
dico("T", 7, "TAPOTEZ").
dico("T", 7, "TAPURES").
dico("T", 7, "TAQUAGE").
dico("T", 7, "TAQUAIS").
dico("T", 7, "TAQUAIT").
dico("T", 7, "TAQUANT").
dico("T", 7, "TAQUEES").
dico("T", 7, "TAQUENT").
dico("T", 7, "TAQUERA").
dico("T", 7, "TAQUETS").
dico("T", 7, "TAQUIEZ").
dico("T", 7, "TAQUINA").
dico("T", 7, "TAQUINE").
dico("T", 7, "TAQUINS").
dico("T", 7, "TAQUOIR").
dico("T", 7, "TAQUONS").
dico("T", 7, "TARAGES").
dico("T", 7, "TARAMAS").
dico("T", 7, "TARAMES").
dico("T", 7, "TARARES").
dico("T", 7, "TARASSE").
dico("T", 7, "TARATES").
dico("T", 7, "TARAUDA").
dico("T", 7, "TARAUDE").
dico("T", 7, "TARAUDS").
dico("T", 7, "TARBAIS").
dico("T", 7, "TARDAIS").
dico("T", 7, "TARDAIT").
dico("T", 7, "TARDANT").
dico("T", 7, "TARDENT").
dico("T", 7, "TARDERA").
dico("T", 7, "TARDIEZ").
dico("T", 7, "TARDIFS").
dico("T", 7, "TARDIVE").
dico("T", 7, "TARDONS").
dico("T", 7, "TARENTE").
dico("T", 7, "TARERAI").
dico("T", 7, "TARERAS").
dico("T", 7, "TAREREZ").
dico("T", 7, "TARGUAI").
dico("T", 7, "TARGUAS").
dico("T", 7, "TARGUAT").
dico("T", 7, "TARGUEE").
dico("T", 7, "TARGUER").
dico("T", 7, "TARGUES").
dico("T", 7, "TARGUEZ").
dico("T", 7, "TARGUIE").
dico("T", 7, "TARGUIS").
dico("T", 7, "TARGUMS").
dico("T", 7, "TARIERE").
dico("T", 7, "TARIFAI").
dico("T", 7, "TARIFAS").
dico("T", 7, "TARIFAT").
dico("T", 7, "TARIFEE").
dico("T", 7, "TARIFER").
dico("T", 7, "TARIFES").
dico("T", 7, "TARIFEZ").
dico("T", 7, "TARIFIA").
dico("T", 7, "TARIFIE").
dico("T", 7, "TARIMES").
dico("T", 7, "TARIONS").
dico("T", 7, "TARIRAI").
dico("T", 7, "TARIRAS").
dico("T", 7, "TARIREZ").
dico("T", 7, "TARISSE").
dico("T", 7, "TARITES").
dico("T", 7, "TARMACS").
dico("T", 7, "TARNAIS").
dico("T", 7, "TAROTEE").
dico("T", 7, "TAROTES").
dico("T", 7, "TARPANS").
dico("T", 7, "TARPONS").
dico("T", 7, "TARSIEN").
dico("T", 7, "TARSIER").
dico("T", 7, "TARTANE").
dico("T", 7, "TARTANS").
dico("T", 7, "TARTARE").
dico("T", 7, "TARTINA").
dico("T", 7, "TARTINE").
dico("T", 7, "TARTIRA").
dico("T", 7, "TARTREE").
dico("T", 7, "TARTRES").
dico("T", 7, "TARTUFE").
dico("T", 7, "TARZANS").
dico("T", 7, "TASSAGE").
dico("T", 7, "TASSAIS").
dico("T", 7, "TASSAIT").
dico("T", 7, "TASSANT").
dico("T", 7, "TASSEAU").
dico("T", 7, "TASSEES").
dico("T", 7, "TASSENT").
dico("T", 7, "TASSERA").
dico("T", 7, "TASSIEZ").
dico("T", 7, "TASSILI").
dico("T", 7, "TASSONS").
dico("T", 7, "TATAMES").
dico("T", 7, "TATAMIS").
dico("T", 7, "TATANES").
dico("T", 7, "TATARES").
dico("T", 7, "TATASSE").
dico("T", 7, "TATATES").
dico("T", 7, "TATERAI").
dico("T", 7, "TATERAS").
dico("T", 7, "TATEREZ").
dico("T", 7, "TATEURS").
dico("T", 7, "TATEUSE").
dico("T", 7, "TATIONS").
dico("T", 7, "TATONNA").
dico("T", 7, "TATONNE").
dico("T", 7, "TATOUAI").
dico("T", 7, "TATOUAS").
dico("T", 7, "TATOUAT").
dico("T", 7, "TATOUEE").
dico("T", 7, "TATOUER").
dico("T", 7, "TATOUES").
dico("T", 7, "TATOUEZ").
dico("T", 7, "TAUDAIS").
dico("T", 7, "TAUDAIT").
dico("T", 7, "TAUDANT").
dico("T", 7, "TAUDEES").
dico("T", 7, "TAUDENT").
dico("T", 7, "TAUDERA").
dico("T", 7, "TAUDIEZ").
dico("T", 7, "TAUDONS").
dico("T", 7, "TAULARD").
dico("T", 7, "TAULIER").
dico("T", 7, "TAUPAIS").
dico("T", 7, "TAUPAIT").
dico("T", 7, "TAUPANT").
dico("T", 7, "TAUPEES").
dico("T", 7, "TAUPENT").
dico("T", 7, "TAUPERA").
dico("T", 7, "TAUPIER").
dico("T", 7, "TAUPIEZ").
dico("T", 7, "TAUPINS").
dico("T", 7, "TAUPONS").
dico("T", 7, "TAUREAU").
dico("T", 7, "TAURINE").
dico("T", 7, "TAURINS").
dico("T", 7, "TAUZINS").
dico("T", 7, "TAVELAI").
dico("T", 7, "TAVELAS").
dico("T", 7, "TAVELAT").
dico("T", 7, "TAVELEE").
dico("T", 7, "TAVELER").
dico("T", 7, "TAVELES").
dico("T", 7, "TAVELEZ").
dico("T", 7, "TAVELLE").
dico("T", 7, "TAVERNE").
dico("T", 7, "TAXABLE").
dico("T", 7, "TAXACEE").
dico("T", 7, "TAXAGES").
dico("T", 7, "TAXAMES").
dico("T", 7, "TAXASSE").
dico("T", 7, "TAXATES").
dico("T", 7, "TAXATIF").
dico("T", 7, "TAXERAI").
dico("T", 7, "TAXERAS").
dico("T", 7, "TAXEREZ").
dico("T", 7, "TAXIMAN").
dico("T", 7, "TAXIMEN").
dico("T", 7, "TAXINEE").
dico("T", 7, "TAXIONS").
dico("T", 7, "TAXIWAY").
dico("T", 7, "TCHADOR").
dico("T", 7, "TCHADRI").
dico("T", 7, "TCHEQUE").
dico("T", 7, "TEASERS").
dico("T", 7, "TEASING").
dico("T", 7, "TECHNOS").
dico("T", 7, "TECKELS").
dico("T", 7, "TECTITE").
dico("T", 7, "TEFLONS").
dico("T", 7, "TEIGNES").
dico("T", 7, "TEIGNEZ").
dico("T", 7, "TEIGNIS").
dico("T", 7, "TEIGNIT").
dico("T", 7, "TEILLAI").
dico("T", 7, "TEILLAS").
dico("T", 7, "TEILLAT").
dico("T", 7, "TEILLEE").
dico("T", 7, "TEILLER").
dico("T", 7, "TEILLES").
dico("T", 7, "TEILLEZ").
dico("T", 7, "TEINDRA").
dico("T", 7, "TEINDRE").
dico("T", 7, "TEINTAI").
dico("T", 7, "TEINTAS").
dico("T", 7, "TEINTAT").
dico("T", 7, "TEINTEE").
dico("T", 7, "TEINTER").
dico("T", 7, "TEINTES").
dico("T", 7, "TEINTEZ").
dico("T", 7, "TELAMON").
dico("T", 7, "TELEFAX").
dico("T", 7, "TELEGAS").
dico("T", 7, "TELEGUE").
dico("T", 7, "TELESKI").
dico("T", 7, "TELETEL").
dico("T", 7, "TELETEX").
dico("T", 7, "TELEXAI").
dico("T", 7, "TELEXAS").
dico("T", 7, "TELEXAT").
dico("T", 7, "TELEXEE").
dico("T", 7, "TELEXER").
dico("T", 7, "TELEXES").
dico("T", 7, "TELEXEZ").
dico("T", 7, "TELLINE").
dico("T", 7, "TELLURE").
dico("T", 7, "TELOCHE").
dico("T", 7, "TELSONS").
dico("T", 7, "TELUGUS").
dico("T", 7, "TEMENOS").
dico("T", 7, "TEMOINS").
dico("T", 7, "TEMPERA").
dico("T", 7, "TEMPERE").
dico("T", 7, "TEMPETA").
dico("T", 7, "TEMPETE").
dico("T", 7, "TEMPLES").
dico("T", 7, "TEMPURA").
dico("T", 7, "TENABLE").
dico("T", 7, "TENACES").
dico("T", 7, "TENANTE").
dico("T", 7, "TENANTS").
dico("T", 7, "TENDAIS").
dico("T", 7, "TENDAIT").
dico("T", 7, "TENDANT").
dico("T", 7, "TENDENT").
dico("T", 7, "TENDERS").
dico("T", 7, "TENDEUR").
dico("T", 7, "TENDIEZ").
dico("T", 7, "TENDOIR").
dico("T", 7, "TENDONS").
dico("T", 7, "TENDRAI").
dico("T", 7, "TENDRAS").
dico("T", 7, "TENDRES").
dico("T", 7, "TENDREZ").
dico("T", 7, "TENDRON").
dico("T", 7, "TENDUES").
dico("T", 7, "TENESME").
dico("T", 7, "TENEURS").
dico("T", 7, "TENEUSE").
dico("T", 7, "TENIONS").
dico("T", 7, "TENONNA").
dico("T", 7, "TENONNE").
dico("T", 7, "TENRECS").
dico("T", 7, "TENSEUR").
dico("T", 7, "TENSION").
dico("T", 7, "TENSONS").
dico("T", 7, "TENTAIS").
dico("T", 7, "TENTAIT").
dico("T", 7, "TENTANT").
dico("T", 7, "TENTEES").
dico("T", 7, "TENTENT").
dico("T", 7, "TENTERA").
dico("T", 7, "TENTIEZ").
dico("T", 7, "TENTONS").
dico("T", 7, "TENTURE").
dico("T", 7, "TENUITE").
dico("T", 7, "TENURES").
dico("T", 7, "TEOCALI").
dico("T", 7, "TEORBES").
dico("T", 7, "TEPALES").
dico("T", 7, "TEQUILA").
dico("T", 7, "TERBIUM").
dico("T", 7, "TERCAIS").
dico("T", 7, "TERCAIT").
dico("T", 7, "TERCANT").
dico("T", 7, "TERCEES").
dico("T", 7, "TERCENT").
dico("T", 7, "TERCERA").
dico("T", 7, "TERCETS").
dico("T", 7, "TERCIEZ").
dico("T", 7, "TERCONS").
dico("T", 7, "TERFEZE").
dico("T", 7, "TERGALE").
dico("T", 7, "TERGALS").
dico("T", 7, "TERGAUX").
dico("T", 7, "TERGITE").
dico("T", 7, "TERMINA").
dico("T", 7, "TERMINE").
dico("T", 7, "TERMITE").
dico("T", 7, "TERNIES").
dico("T", 7, "TERNIRA").
dico("T", 7, "TERPENE").
dico("T", 7, "TERPINE").
dico("T", 7, "TERRAGE").
dico("T", 7, "TERRAIN").
dico("T", 7, "TERRAIS").
dico("T", 7, "TERRAIT").
dico("T", 7, "TERRANT").
dico("T", 7, "TERREAU").
dico("T", 7, "TERREES").
dico("T", 7, "TERRENT").
dico("T", 7, "TERRERA").
dico("T", 7, "TERREUR").
dico("T", 7, "TERREUX").
dico("T", 7, "TERRIEN").
dico("T", 7, "TERRIER").
dico("T", 7, "TERRIEZ").
dico("T", 7, "TERRILS").
dico("T", 7, "TERRINE").
dico("T", 7, "TERRIRA").
dico("T", 7, "TERROIR").
dico("T", 7, "TERRONS").
dico("T", 7, "TERSAIS").
dico("T", 7, "TERSAIT").
dico("T", 7, "TERSANT").
dico("T", 7, "TERSEES").
dico("T", 7, "TERSENT").
dico("T", 7, "TERSERA").
dico("T", 7, "TERSIEZ").
dico("T", 7, "TERSONS").
dico("T", 7, "TERTRES").
dico("T", 7, "TESSERE").
dico("T", 7, "TESSONS").
dico("T", 7, "TESTACE").
dico("T", 7, "TESTAGE").
dico("T", 7, "TESTAIS").
dico("T", 7, "TESTAIT").
dico("T", 7, "TESTANT").
dico("T", 7, "TESTEES").
dico("T", 7, "TESTENT").
dico("T", 7, "TESTERA").
dico("T", 7, "TESTEUR").
dico("T", 7, "TESTIEZ").
dico("T", 7, "TESTONS").
dico("T", 7, "TETAMES").
dico("T", 7, "TETANIE").
dico("T", 7, "TETANOS").
dico("T", 7, "TETARDS").
dico("T", 7, "TETASSE").
dico("T", 7, "TETATES").
dico("T", 7, "TETEAUX").
dico("T", 7, "TETERAI").
dico("T", 7, "TETERAS").
dico("T", 7, "TETEREZ").
dico("T", 7, "TETIERE").
dico("T", 7, "TETINES").
dico("T", 7, "TETIONS").
dico("T", 7, "TETRADE").
dico("T", 7, "TETRODE").
dico("T", 7, "TEUTONS").
dico("T", 7, "TEXANES").
dico("T", 7, "TEXTILE").
dico("T", 7, "TEXTUEL").
dico("T", 7, "TEXTURA").
dico("T", 7, "TEXTURE").
dico("T", 7, "TEZIGUE").
dico("T", 7, "THALERS").
dico("T", 7, "THALLES").
dico("T", 7, "THALWEG").
dico("T", 7, "THEATIN").
dico("T", 7, "THEATRE").
dico("T", 7, "THEBAIN").
dico("T", 7, "THEIERE").
dico("T", 7, "THEIERS").
dico("T", 7, "THEINES").
dico("T", 7, "THEISME").
dico("T", 7, "THEISTE").
dico("T", 7, "THENARS").
dico("T", 7, "THEORBE").
dico("T", 7, "THEORIE").
dico("T", 7, "THEQUES").
dico("T", 7, "THERIEN").
dico("T", 7, "THERMAL").
dico("T", 7, "THERMES").
dico("T", 7, "THERMIE").
dico("T", 7, "THERMOS").
dico("T", 7, "THESARD").
dico("T", 7, "THLASPI").
dico("T", 7, "THOMISE").
dico("T", 7, "THONIER").
dico("T", 7, "THONINE").
dico("T", 7, "THORINE").
dico("T", 7, "THORITE").
dico("T", 7, "THORIUM").
dico("T", 7, "THORONS").
dico("T", 7, "THRACES").
dico("T", 7, "THRENES").
dico("T", 7, "THULIUM").
dico("T", 7, "THURNES").
dico("T", 7, "THYADES").
dico("T", 7, "THYIADE").
dico("T", 7, "THYMIES").
dico("T", 7, "THYMINE").
dico("T", 7, "THYMOLS").
dico("T", 7, "THYRSES").
dico("T", 7, "TIAFFES").
dico("T", 7, "TIBIALE").
dico("T", 7, "TIBIAUX").
dico("T", 7, "TICKETS").
dico("T", 7, "TICSONS").
dico("T", 7, "TICTACS").
dico("T", 7, "TIEDEUR").
dico("T", 7, "TIEDIES").
dico("T", 7, "TIEDIRA").
dico("T", 7, "TIENDRA").
dico("T", 7, "TIENNES").
dico("T", 7, "TIENTOS").
dico("T", 7, "TIERCAI").
dico("T", 7, "TIERCAS").
dico("T", 7, "TIERCAT").
dico("T", 7, "TIERCEE").
dico("T", 7, "TIERCER").
dico("T", 7, "TIERCES").
dico("T", 7, "TIERCEZ").
dico("T", 7, "TIFOSIS").
dico("T", 7, "TIFOSOS").
dico("T", 7, "TIGEAIS").
dico("T", 7, "TIGEAIT").
dico("T", 7, "TIGEANT").
dico("T", 7, "TIGELLE").
dico("T", 7, "TIGEONS").
dico("T", 7, "TIGERAI").
dico("T", 7, "TIGERAS").
dico("T", 7, "TIGEREZ").
dico("T", 7, "TIGETTE").
dico("T", 7, "TIGIONS").
dico("T", 7, "TIGLONS").
dico("T", 7, "TIGRAIS").
dico("T", 7, "TIGRAIT").
dico("T", 7, "TIGRANT").
dico("T", 7, "TIGREES").
dico("T", 7, "TIGRENT").
dico("T", 7, "TIGRERA").
dico("T", 7, "TIGRIEZ").
dico("T", 7, "TIGRONS").
dico("T", 7, "TIGRURE").
dico("T", 7, "TILAPIA").
dico("T", 7, "TILBURY").
dico("T", 7, "TILDEES").
dico("T", 7, "TILLACS").
dico("T", 7, "TILLAGE").
dico("T", 7, "TILLAIS").
dico("T", 7, "TILLAIT").
dico("T", 7, "TILLANT").
dico("T", 7, "TILLEES").
dico("T", 7, "TILLENT").
dico("T", 7, "TILLERA").
dico("T", 7, "TILLEUL").
dico("T", 7, "TILLEUR").
dico("T", 7, "TILLIEZ").
dico("T", 7, "TILLONS").
dico("T", 7, "TILSITS").
dico("T", 7, "TILTAIS").
dico("T", 7, "TILTAIT").
dico("T", 7, "TILTANT").
dico("T", 7, "TILTENT").
dico("T", 7, "TILTERA").
dico("T", 7, "TILTIEZ").
dico("T", 7, "TILTONS").
dico("T", 7, "TIMBALE").
dico("T", 7, "TIMBRAI").
dico("T", 7, "TIMBRAS").
dico("T", 7, "TIMBRAT").
dico("T", 7, "TIMBREE").
dico("T", 7, "TIMBRER").
dico("T", 7, "TIMBRES").
dico("T", 7, "TIMBREZ").
dico("T", 7, "TIMIDES").
dico("T", 7, "TIMINGS").
dico("T", 7, "TIMOREE").
dico("T", 7, "TIMORES").
dico("T", 7, "TINAMOU").
dico("T", 7, "TINCALS").
dico("T", 7, "TINEIDE").
dico("T", 7, "TINETTE").
dico("T", 7, "TINRENT").
dico("T", 7, "TINSSES").
dico("T", 7, "TINTAIS").
dico("T", 7, "TINTAIT").
dico("T", 7, "TINTANT").
dico("T", 7, "TINTEES").
dico("T", 7, "TINTENT").
dico("T", 7, "TINTERA").
dico("T", 7, "TINTIEZ").
dico("T", 7, "TINTONS").
dico("T", 7, "TIPAMES").
dico("T", 7, "TIPASSE").
dico("T", 7, "TIPATES").
dico("T", 7, "TIPERAI").
dico("T", 7, "TIPERAS").
dico("T", 7, "TIPEREZ").
dico("T", 7, "TIPIONS").
dico("T", 7, "TIPPAIS").
dico("T", 7, "TIPPAIT").
dico("T", 7, "TIPPANT").
dico("T", 7, "TIPPEES").
dico("T", 7, "TIPPENT").
dico("T", 7, "TIPPERA").
dico("T", 7, "TIPPIEZ").
dico("T", 7, "TIPPONS").
dico("T", 7, "TIPULES").
dico("T", 7, "TIQUAIS").
dico("T", 7, "TIQUAIT").
dico("T", 7, "TIQUANT").
dico("T", 7, "TIQUENT").
dico("T", 7, "TIQUERA").
dico("T", 7, "TIQUETE").
dico("T", 7, "TIQUEUR").
dico("T", 7, "TIQUIEZ").
dico("T", 7, "TIQUONS").
dico("T", 7, "TIRADES").
dico("T", 7, "TIRAGES").
dico("T", 7, "TIRAMES").
dico("T", 7, "TIRANTS").
dico("T", 7, "TIRASSE").
dico("T", 7, "TIRATES").
dico("T", 7, "TIRERAI").
dico("T", 7, "TIRERAS").
dico("T", 7, "TIREREZ").
dico("T", 7, "TIRETTE").
dico("T", 7, "TIREURS").
dico("T", 7, "TIREUSE").
dico("T", 7, "TIRIONS").
dico("T", 7, "TIROIRS").
dico("T", 7, "TISANES").
dico("T", 7, "TISONNA").
dico("T", 7, "TISONNE").
dico("T", 7, "TISSAGE").
dico("T", 7, "TISSAIS").
dico("T", 7, "TISSAIT").
dico("T", 7, "TISSANT").
dico("T", 7, "TISSEES").
dico("T", 7, "TISSENT").
dico("T", 7, "TISSERA").
dico("T", 7, "TISSEUR").
dico("T", 7, "TISSIEZ").
dico("T", 7, "TISSONS").
dico("T", 7, "TISSUES").
dico("T", 7, "TISSURE").
dico("T", 7, "TITANEE").
dico("T", 7, "TITANES").
dico("T", 7, "TITILLA").
dico("T", 7, "TITILLE").
dico("T", 7, "TITISME").
dico("T", 7, "TITISTE").
dico("T", 7, "TITRAGE").
dico("T", 7, "TITRAIS").
dico("T", 7, "TITRAIT").
dico("T", 7, "TITRANT").
dico("T", 7, "TITREES").
dico("T", 7, "TITRENT").
dico("T", 7, "TITRERA").
dico("T", 7, "TITREUR").
dico("T", 7, "TITRIEZ").
dico("T", 7, "TITRISA").
dico("T", 7, "TITRISE").
dico("T", 7, "TITRONS").
dico("T", 7, "TITUBAI").
dico("T", 7, "TITUBAS").
dico("T", 7, "TITUBAT").
dico("T", 7, "TITUBER").
dico("T", 7, "TITUBES").
dico("T", 7, "TITUBEZ").
dico("T", 7, "TOASTAI").
dico("T", 7, "TOASTAS").
dico("T", 7, "TOASTAT").
dico("T", 7, "TOASTEE").
dico("T", 7, "TOASTER").
dico("T", 7, "TOASTES").
dico("T", 7, "TOASTEZ").
dico("T", 7, "TOCADES").
dico("T", 7, "TOCANTE").
dico("T", 7, "TOCARDE").
dico("T", 7, "TOCARDS").
dico("T", 7, "TOCCATA").
dico("T", 7, "TOCCATE").
dico("T", 7, "TOCSINS").
dico("T", 7, "TOCSONS").
dico("T", 7, "TOFFEES").
dico("T", 7, "TOILAGE").
dico("T", 7, "TOILAIS").
dico("T", 7, "TOILAIT").
dico("T", 7, "TOILANT").
dico("T", 7, "TOILEES").
dico("T", 7, "TOILENT").
dico("T", 7, "TOILERA").
dico("T", 7, "TOILIER").
dico("T", 7, "TOILIEZ").
dico("T", 7, "TOILONS").
dico("T", 7, "TOISAIS").
dico("T", 7, "TOISAIT").
dico("T", 7, "TOISANT").
dico("T", 7, "TOISEES").
dico("T", 7, "TOISENT").
dico("T", 7, "TOISERA").
dico("T", 7, "TOISIEZ").
dico("T", 7, "TOISONS").
dico("T", 7, "TOITURE").
dico("T", 7, "TOKAMAK").
dico("T", 7, "TOKOMAK").
dico("T", 7, "TOKYOTE").
dico("T", 7, "TOLAMES").
dico("T", 7, "TOLARDE").
dico("T", 7, "TOLARDS").
dico("T", 7, "TOLARJI").
dico("T", 7, "TOLASSE").
dico("T", 7, "TOLATES").
dico("T", 7, "TOLERAI").
dico("T", 7, "TOLERAS").
dico("T", 7, "TOLERAT").
dico("T", 7, "TOLEREE").
dico("T", 7, "TOLERER").
dico("T", 7, "TOLERES").
dico("T", 7, "TOLEREZ").
dico("T", 7, "TOLERIE").
dico("T", 7, "TOLIERE").
dico("T", 7, "TOLIERS").
dico("T", 7, "TOLIONS").
dico("T", 7, "TOLITES").
dico("T", 7, "TOLUENE").
dico("T", 7, "TOLUOLS").
dico("T", 7, "TOMAMES").
dico("T", 7, "TOMASSE").
dico("T", 7, "TOMATES").
dico("T", 7, "TOMBACS").
dico("T", 7, "TOMBAIS").
dico("T", 7, "TOMBAIT").
dico("T", 7, "TOMBALE").
dico("T", 7, "TOMBALS").
dico("T", 7, "TOMBANT").
dico("T", 7, "TOMBAUX").
dico("T", 7, "TOMBEAU").
dico("T", 7, "TOMBEES").
dico("T", 7, "TOMBENT").
dico("T", 7, "TOMBERA").
dico("T", 7, "TOMBERS").
dico("T", 7, "TOMBEUR").
dico("T", 7, "TOMBIEZ").
dico("T", 7, "TOMBOLA").
dico("T", 7, "TOMBOLO").
dico("T", 7, "TOMBONS").
dico("T", 7, "TOMERAI").
dico("T", 7, "TOMERAS").
dico("T", 7, "TOMEREZ").
dico("T", 7, "TOMETTE").
dico("T", 7, "TOMIENS").
dico("T", 7, "TOMIONS").
dico("T", 7, "TOMMIES").
dico("T", 7, "TONALES").
dico("T", 7, "TONDAGE").
dico("T", 7, "TONDAIS").
dico("T", 7, "TONDAIT").
dico("T", 7, "TONDANT").
dico("T", 7, "TONDENT").
dico("T", 7, "TONDEUR").
dico("T", 7, "TONDIEZ").
dico("T", 7, "TONDONS").
dico("T", 7, "TONDRAI").
dico("T", 7, "TONDRAS").
dico("T", 7, "TONDREZ").
dico("T", 7, "TONDUES").
dico("T", 7, "TONIFIA").
dico("T", 7, "TONIFIE").
dico("T", 7, "TONIQUE").
dico("T", 7, "TONLIEU").
dico("T", 7, "TONNAGE").
dico("T", 7, "TONNAIS").
dico("T", 7, "TONNAIT").
dico("T", 7, "TONNANT").
dico("T", 7, "TONNEAU").
dico("T", 7, "TONNENT").
dico("T", 7, "TONNERA").
dico("T", 7, "TONNIEZ").
dico("T", 7, "TONNONS").
dico("T", 7, "TONSURA").
dico("T", 7, "TONSURE").
dico("T", 7, "TONTINA").
dico("T", 7, "TONTINE").
dico("T", 7, "TONTONS").
dico("T", 7, "TONTURE").
dico("T", 7, "TOPAMES").
dico("T", 7, "TOPASSE").
dico("T", 7, "TOPATES").
dico("T", 7, "TOPAZES").
dico("T", 7, "TOPERAI").
dico("T", 7, "TOPERAS").
dico("T", 7, "TOPEREZ").
dico("T", 7, "TOPETTE").
dico("T", 7, "TOPHACE").
dico("T", 7, "TOPIONS").
dico("T", 7, "TOPIQUE").
dico("T", 7, "TOPLESS").
dico("T", 7, "TOQUADE").
dico("T", 7, "TOQUAIS").
dico("T", 7, "TOQUAIT").
dico("T", 7, "TOQUANT").
dico("T", 7, "TOQUARD").
dico("T", 7, "TOQUEES").
dico("T", 7, "TOQUENT").
dico("T", 7, "TOQUERA").
dico("T", 7, "TOQUETS").
dico("T", 7, "TOQUIEZ").
dico("T", 7, "TOQUONS").
dico("T", 7, "TORANAS").
dico("T", 7, "TORBALL").
dico("T", 7, "TORCHAI").
dico("T", 7, "TORCHAS").
dico("T", 7, "TORCHAT").
dico("T", 7, "TORCHEE").
dico("T", 7, "TORCHER").
dico("T", 7, "TORCHES").
dico("T", 7, "TORCHEZ").
dico("T", 7, "TORCHIS").
dico("T", 7, "TORCHON").
dico("T", 7, "TORCOLS").
dico("T", 7, "TORCOUS").
dico("T", 7, "TORDAGE").
dico("T", 7, "TORDAIS").
dico("T", 7, "TORDAIT").
dico("T", 7, "TORDANT").
dico("T", 7, "TORDENT").
dico("T", 7, "TORDEUR").
dico("T", 7, "TORDIEZ").
dico("T", 7, "TORDOIR").
dico("T", 7, "TORDONS").
dico("T", 7, "TORDRAI").
dico("T", 7, "TORDRAS").
dico("T", 7, "TORDREZ").
dico("T", 7, "TORDUES").
dico("T", 7, "TOREAIS").
dico("T", 7, "TOREAIT").
dico("T", 7, "TOREANT").
dico("T", 7, "TOREEES").
dico("T", 7, "TOREENT").
dico("T", 7, "TOREERA").
dico("T", 7, "TOREIEZ").
dico("T", 7, "TOREONS").
dico("T", 7, "TORERAS").
dico("T", 7, "TOREROS").
dico("T", 7, "TORIQUE").
dico("T", 7, "TORNADE").
dico("T", 7, "TORONNA").
dico("T", 7, "TORONNE").
dico("T", 7, "TORPEDO").
dico("T", 7, "TORPEUR").
dico("T", 7, "TORPIDE").
dico("T", 7, "TORQUES").
dico("T", 7, "TORREES").
dico("T", 7, "TORRENT").
dico("T", 7, "TORRIDE").
dico("T", 7, "TORSADA").
dico("T", 7, "TORSADE").
dico("T", 7, "TORSEUR").
dico("T", 7, "TORSION").
dico("T", 7, "TORTILS").
dico("T", 7, "TORTORA").
dico("T", 7, "TORTORE").
dico("T", 7, "TORTUES").
dico("T", 7, "TORTURA").
dico("T", 7, "TORTURE").
dico("T", 7, "TORYSME").
dico("T", 7, "TOSCANE").
dico("T", 7, "TOSCANS").
dico("T", 7, "TOSSAIS").
dico("T", 7, "TOSSAIT").
dico("T", 7, "TOSSANT").
dico("T", 7, "TOSSENT").
dico("T", 7, "TOSSERA").
dico("T", 7, "TOSSIEZ").
dico("T", 7, "TOSSONS").
dico("T", 7, "TOTALES").
dico("T", 7, "TOUAGES").
dico("T", 7, "TOUAMES").
dico("T", 7, "TOUAREG").
dico("T", 7, "TOUASSE").
dico("T", 7, "TOUATES").
dico("T", 7, "TOUBABS").
dico("T", 7, "TOUBIBS").
dico("T", 7, "TOUCANS").
dico("T", 7, "TOUCHAI").
dico("T", 7, "TOUCHAS").
dico("T", 7, "TOUCHAT").
dico("T", 7, "TOUCHAU").
dico("T", 7, "TOUCHEE").
dico("T", 7, "TOUCHER").
dico("T", 7, "TOUCHES").
dico("T", 7, "TOUCHEZ").
dico("T", 7, "TOUERAI").
dico("T", 7, "TOUERAS").
dico("T", 7, "TOUEREZ").
dico("T", 7, "TOUEURS").
dico("T", 7, "TOUEUSE").
dico("T", 7, "TOUFFES").
dico("T", 7, "TOUFFUE").
dico("T", 7, "TOUFFUS").
dico("T", 7, "TOUILLA").
dico("T", 7, "TOUILLE").
dico("T", 7, "TOUIONS").
dico("T", 7, "TOULADI").
dico("T", 7, "TOUNDRA").
dico("T", 7, "TOUPAYE").
dico("T", 7, "TOUPETS").
dico("T", 7, "TOUPIES").
dico("T", 7, "TOUPINA").
dico("T", 7, "TOUPINE").
dico("T", 7, "TOUPINS").
dico("T", 7, "TOUQUES").
dico("T", 7, "TOURBAI").
dico("T", 7, "TOURBAS").
dico("T", 7, "TOURBAT").
dico("T", 7, "TOURBER").
dico("T", 7, "TOURBES").
dico("T", 7, "TOURBEZ").
dico("T", 7, "TOURDES").
dico("T", 7, "TOURETS").
dico("T", 7, "TOURIER").
dico("T", 7, "TOURIES").
dico("T", 7, "TOURINS").
dico("T", 7, "TOURNAI").
dico("T", 7, "TOURNAS").
dico("T", 7, "TOURNAT").
dico("T", 7, "TOURNEE").
dico("T", 7, "TOURNER").
dico("T", 7, "TOURNES").
dico("T", 7, "TOURNEZ").
dico("T", 7, "TOURNIS").
dico("T", 7, "TOURNOI").
dico("T", 7, "TOURNUS").
dico("T", 7, "TOURONS").
dico("T", 7, "TOURTES").
dico("T", 7, "TOUSSAI").
dico("T", 7, "TOUSSAS").
dico("T", 7, "TOUSSAT").
dico("T", 7, "TOUSSER").
dico("T", 7, "TOUSSES").
dico("T", 7, "TOUSSEZ").
dico("T", 7, "TOUTIME").
dico("T", 7, "TOUTOUS").
dico("T", 7, "TOXEMIE").
dico("T", 7, "TOXICOS").
dico("T", 7, "TOXINES").
dico("T", 7, "TOXIQUE").
dico("T", 7, "TRABANS").
dico("T", 7, "TRABEES").
dico("T", 7, "TRACAGE").
dico("T", 7, "TRACAIS").
dico("T", 7, "TRACAIT").
dico("T", 7, "TRACANT").
dico("T", 7, "TRACEES").
dico("T", 7, "TRACENT").
dico("T", 7, "TRACERA").
dico("T", 7, "TRACEUR").
dico("T", 7, "TRACHEE").
dico("T", 7, "TRACIEZ").
dico("T", 7, "TRACLET").
dico("T", 7, "TRACOIR").
dico("T", 7, "TRACONS").
dico("T", 7, "TRACTAI").
dico("T", 7, "TRACTAS").
dico("T", 7, "TRACTAT").
dico("T", 7, "TRACTEE").
dico("T", 7, "TRACTER").
dico("T", 7, "TRACTES").
dico("T", 7, "TRACTEZ").
dico("T", 7, "TRACTIF").
dico("T", 7, "TRACTUS").
dico("T", 7, "TRADERS").
dico("T", 7, "TRADEUR").
dico("T", 7, "TRADING").
dico("T", 7, "TRADUIS").
dico("T", 7, "TRADUIT").
dico("T", 7, "TRAFICS").
dico("T", 7, "TRAHIES").
dico("T", 7, "TRAHIRA").
dico("T", 7, "TRAIENT").
dico("T", 7, "TRAILLE").
dico("T", 7, "TRAINAI").
dico("T", 7, "TRAINAS").
dico("T", 7, "TRAINAT").
dico("T", 7, "TRAINEE").
dico("T", 7, "TRAINER").
dico("T", 7, "TRAINES").
dico("T", 7, "TRAINEZ").
dico("T", 7, "TRAIRAI").
dico("T", 7, "TRAIRAS").
dico("T", 7, "TRAIREZ").
dico("T", 7, "TRAITAI").
dico("T", 7, "TRAITAS").
dico("T", 7, "TRAITAT").
dico("T", 7, "TRAITEE").
dico("T", 7, "TRAITER").
dico("T", 7, "TRAITES").
dico("T", 7, "TRAITEZ").
dico("T", 7, "TRAITRE").
dico("T", 7, "TRAJETS").
dico("T", 7, "TRALALA").
dico("T", 7, "TRALEES").
dico("T", 7, "TRALUIS").
dico("T", 7, "TRALUIT").
dico("T", 7, "TRAMAGE").
dico("T", 7, "TRAMAIL").
dico("T", 7, "TRAMAIS").
dico("T", 7, "TRAMAIT").
dico("T", 7, "TRAMANT").
dico("T", 7, "TRAMEES").
dico("T", 7, "TRAMENT").
dico("T", 7, "TRAMERA").
dico("T", 7, "TRAMEUR").
dico("T", 7, "TRAMIEZ").
dico("T", 7, "TRAMONS").
dico("T", 7, "TRAMWAY").
dico("T", 7, "TRANCHA").
dico("T", 7, "TRANCHE").
dico("T", 7, "TRANSAT").
dico("T", 7, "TRANSES").
dico("T", 7, "TRANSFO").
dico("T", 7, "TRANSIE").
dico("T", 7, "TRANSIR").
dico("T", 7, "TRANSIS").
dico("T", 7, "TRANSIT").
dico("T", 7, "TRAPEZE").
dico("T", 7, "TRAPPAI").
dico("T", 7, "TRAPPAS").
dico("T", 7, "TRAPPAT").
dico("T", 7, "TRAPPEE").
dico("T", 7, "TRAPPER").
dico("T", 7, "TRAPPES").
dico("T", 7, "TRAPPEZ").
dico("T", 7, "TRAPUES").
dico("T", 7, "TRAQUAI").
dico("T", 7, "TRAQUAS").
dico("T", 7, "TRAQUAT").
dico("T", 7, "TRAQUEE").
dico("T", 7, "TRAQUER").
dico("T", 7, "TRAQUES").
dico("T", 7, "TRAQUET").
dico("T", 7, "TRAQUEZ").
dico("T", 7, "TRAUMAS").
dico("T", 7, "TRAVAIL").
dico("T", 7, "TRAVAUX").
dico("T", 7, "TRAVEES").
dico("T", 7, "TRAVELO").
dico("T", 7, "TRAVERS").
dico("T", 7, "TRAYAIS").
dico("T", 7, "TRAYAIT").
dico("T", 7, "TRAYANT").
dico("T", 7, "TRAYEUR").
dico("T", 7, "TRAYIEZ").
dico("T", 7, "TRAYONS").
dico("T", 7, "TREFILA").
dico("T", 7, "TREFILE").
dico("T", 7, "TREFLEE").
dico("T", 7, "TREFLES").
dico("T", 7, "TREILLE").
dico("T", 7, "TREMAIL").
dico("T", 7, "TREMATA").
dico("T", 7, "TREMATE").
dico("T", 7, "TREMBLA").
dico("T", 7, "TREMBLE").
dico("T", 7, "TREMIES").
dico("T", 7, "TREMOLO").
dico("T", 7, "TREMPAI").
dico("T", 7, "TREMPAS").
dico("T", 7, "TREMPAT").
dico("T", 7, "TREMPEE").
dico("T", 7, "TREMPER").
dico("T", 7, "TREMPES").
dico("T", 7, "TREMPEZ").
dico("T", 7, "TREMULA").
dico("T", 7, "TREMULE").
dico("T", 7, "TRENAIL").
dico("T", 7, "TRENCHS").
dico("T", 7, "TREPANA").
dico("T", 7, "TREPANE").
dico("T", 7, "TREPANG").
dico("T", 7, "TREPANS").
dico("T", 7, "TREPIDA").
dico("T", 7, "TREPIDE").
dico("T", 7, "TREPIED").
dico("T", 7, "TRESORS").
dico("T", 7, "TRESSAI").
dico("T", 7, "TRESSAS").
dico("T", 7, "TRESSAT").
dico("T", 7, "TRESSEE").
dico("T", 7, "TRESSER").
dico("T", 7, "TRESSES").
dico("T", 7, "TRESSEZ").
dico("T", 7, "TRETEAU").
dico("T", 7, "TREUILS").
dico("T", 7, "TREVIRA").
dico("T", 7, "TREVIRE").
dico("T", 7, "TREVISE").
dico("T", 7, "TRIADES").
dico("T", 7, "TRIAGES").
dico("T", 7, "TRIAIRE").
dico("T", 7, "TRIALLE").
dico("T", 7, "TRIAMES").
dico("T", 7, "TRIASSE").
dico("T", 7, "TRIATES").
dico("T", 7, "TRIBADE").
dico("T", 7, "TRIBALE").
dico("T", 7, "TRIBALS").
dico("T", 7, "TRIBART").
dico("T", 7, "TRIBAUX").
dico("T", 7, "TRIBORD").
dico("T", 7, "TRIBUNE").
dico("T", 7, "TRIBUNS").
dico("T", 7, "TRIBUTE").
dico("T", 7, "TRIBUTS").
dico("T", 7, "TRICARD").
dico("T", 7, "TRICEPS").
dico("T", 7, "TRICHAI").
dico("T", 7, "TRICHAS").
dico("T", 7, "TRICHAT").
dico("T", 7, "TRICHEE").
dico("T", 7, "TRICHER").
dico("T", 7, "TRICHES").
dico("T", 7, "TRICHEZ").
dico("T", 7, "TRICHLO").
dico("T", 7, "TRICONE").
dico("T", 7, "TRICOTA").
dico("T", 7, "TRICOTE").
dico("T", 7, "TRICOTS").
dico("T", 7, "TRIDENT").
dico("T", 7, "TRIEDRE").
dico("T", 7, "TRIERAI").
dico("T", 7, "TRIERAS").
dico("T", 7, "TRIERES").
dico("T", 7, "TRIEREZ").
dico("T", 7, "TRIEURS").
dico("T", 7, "TRIEUSE").
dico("T", 7, "TRIFIDE").
dico("T", 7, "TRIGLES").
dico("T", 7, "TRIGONE").
dico("T", 7, "TRIIONS").
dico("T", 7, "TRILLAI").
dico("T", 7, "TRILLAS").
dico("T", 7, "TRILLAT").
dico("T", 7, "TRILLEE").
dico("T", 7, "TRILLER").
dico("T", 7, "TRILLES").
dico("T", 7, "TRILLEZ").
dico("T", 7, "TRILOBE").
dico("T", 7, "TRIMAIS").
dico("T", 7, "TRIMAIT").
dico("T", 7, "TRIMANT").
dico("T", 7, "TRIMARD").
dico("T", 7, "TRIMENT").
dico("T", 7, "TRIMERA").
dico("T", 7, "TRIMERE").
dico("T", 7, "TRIMEUR").
dico("T", 7, "TRIMIEZ").
dico("T", 7, "TRIMMER").
dico("T", 7, "TRIMONS").
dico("T", 7, "TRINGLA").
dico("T", 7, "TRINGLE").
dico("T", 7, "TRINITE").
dico("T", 7, "TRINOME").
dico("T", 7, "TRINQUA").
dico("T", 7, "TRINQUE").
dico("T", 7, "TRIODES").
dico("T", 7, "TRIOLET").
dico("T", 7, "TRIONYX").
dico("T", 7, "TRIPALE").
dico("T", 7, "TRIPANG").
dico("T", 7, "TRIPANT").
dico("T", 7, "TRIPIER").
dico("T", 7, "TRIPLAI").
dico("T", 7, "TRIPLAN").
dico("T", 7, "TRIPLAS").
dico("T", 7, "TRIPLAT").
dico("T", 7, "TRIPLEE").
dico("T", 7, "TRIPLER").
dico("T", 7, "TRIPLES").
dico("T", 7, "TRIPLET").
dico("T", 7, "TRIPLEX").
dico("T", 7, "TRIPLEZ").
dico("T", 7, "TRIPODE").
dico("T", 7, "TRIPOLI").
dico("T", 7, "TRIPOTA").
dico("T", 7, "TRIPOTE").
dico("T", 7, "TRIPOTS").
dico("T", 7, "TRIPOUS").
dico("T", 7, "TRIPOUX").
dico("T", 7, "TRIQUAI").
dico("T", 7, "TRIQUAS").
dico("T", 7, "TRIQUAT").
dico("T", 7, "TRIQUEE").
dico("T", 7, "TRIQUER").
dico("T", 7, "TRIQUES").
dico("T", 7, "TRIQUET").
dico("T", 7, "TRIQUEZ").
dico("T", 7, "TRIREME").
dico("T", 7, "TRISMES").
dico("T", 7, "TRISMUS").
dico("T", 7, "TRISOCS").
dico("T", 7, "TRISSAI").
dico("T", 7, "TRISSAS").
dico("T", 7, "TRISSAT").
dico("T", 7, "TRISSEE").
dico("T", 7, "TRISSER").
dico("T", 7, "TRISSES").
dico("T", 7, "TRISSEZ").
dico("T", 7, "TRISTES").
dico("T", 7, "TRITIUM").
dico("T", 7, "TRITONS").
dico("T", 7, "TRITURA").
dico("T", 7, "TRITURE").
dico("T", 7, "TRIVIAL").
dico("T", 7, "TRIVIUM").
dico("T", 7, "TROCART").
dico("T", 7, "TROCHEE").
dico("T", 7, "TROCHES").
dico("T", 7, "TROCHET").
dico("T", 7, "TROCHIN").
dico("T", 7, "TROENES").
dico("T", 7, "TROGNES").
dico("T", 7, "TROGNON").
dico("T", 7, "TROIKAS").
dico("T", 7, "TROLLES").
dico("T", 7, "TROLLEY").
dico("T", 7, "TROMBES").
dico("T", 7, "TROMMEL").
dico("T", 7, "TROMPAI").
dico("T", 7, "TROMPAS").
dico("T", 7, "TROMPAT").
dico("T", 7, "TROMPEE").
dico("T", 7, "TROMPER").
dico("T", 7, "TROMPES").
dico("T", 7, "TROMPEZ").
dico("T", 7, "TRONAIS").
dico("T", 7, "TRONAIT").
dico("T", 7, "TRONANT").
dico("T", 7, "TRONCES").
dico("T", 7, "TRONCHE").
dico("T", 7, "TRONCON").
dico("T", 7, "TRONENT").
dico("T", 7, "TRONERA").
dico("T", 7, "TRONIEZ").
dico("T", 7, "TRONONS").
dico("T", 7, "TRONQUA").
dico("T", 7, "TRONQUE").
dico("T", 7, "TROPHEE").
dico("T", 7, "TROQUAI").
dico("T", 7, "TROQUAS").
dico("T", 7, "TROQUAT").
dico("T", 7, "TROQUEE").
dico("T", 7, "TROQUER").
dico("T", 7, "TROQUES").
dico("T", 7, "TROQUET").
dico("T", 7, "TROQUEZ").
dico("T", 7, "TROTTAI").
dico("T", 7, "TROTTAS").
dico("T", 7, "TROTTAT").
dico("T", 7, "TROTTEE").
dico("T", 7, "TROTTER").
dico("T", 7, "TROTTES").
dico("T", 7, "TROTTEZ").
dico("T", 7, "TROTTIN").
dico("T", 7, "TROUAIS").
dico("T", 7, "TROUAIT").
dico("T", 7, "TROUANT").
dico("T", 7, "TROUBLA").
dico("T", 7, "TROUBLE").
dico("T", 7, "TROUEES").
dico("T", 7, "TROUENT").
dico("T", 7, "TROUERA").
dico("T", 7, "TROUETS").
dico("T", 7, "TROUIEZ").
dico("T", 7, "TROUONS").
dico("T", 7, "TROUPES").
dico("T", 7, "TROUSSA").
dico("T", 7, "TROUSSE").
dico("T", 7, "TROUVAI").
dico("T", 7, "TROUVAS").
dico("T", 7, "TROUVAT").
dico("T", 7, "TROUVEE").
dico("T", 7, "TROUVER").
dico("T", 7, "TROUVES").
dico("T", 7, "TROUVEZ").
dico("T", 7, "TROYENS").
dico("T", 7, "TRUANDA").
dico("T", 7, "TRUANDE").
dico("T", 7, "TRUANDS").
dico("T", 7, "TRUBLES").
dico("T", 7, "TRUCAGE").
dico("T", 7, "TRUCIDA").
dico("T", 7, "TRUCIDE").
dico("T", 7, "TRUELLE").
dico("T", 7, "TRUFFAI").
dico("T", 7, "TRUFFAS").
dico("T", 7, "TRUFFAT").
dico("T", 7, "TRUFFEE").
dico("T", 7, "TRUFFER").
dico("T", 7, "TRUFFES").
dico("T", 7, "TRUFFEZ").
dico("T", 7, "TRUISME").
dico("T", 7, "TRUITEE").
dico("T", 7, "TRUITES").
dico("T", 7, "TRULLOS").
dico("T", 7, "TRUMEAU").
dico("T", 7, "TRUQUAI").
dico("T", 7, "TRUQUAS").
dico("T", 7, "TRUQUAT").
dico("T", 7, "TRUQUEE").
dico("T", 7, "TRUQUER").
dico("T", 7, "TRUQUES").
dico("T", 7, "TRUQUEZ").
dico("T", 7, "TRUSTAI").
dico("T", 7, "TRUSTAS").
dico("T", 7, "TRUSTAT").
dico("T", 7, "TRUSTEE").
dico("T", 7, "TRUSTER").
dico("T", 7, "TRUSTES").
dico("T", 7, "TRUSTEZ").
dico("T", 7, "TRUSTIS").
dico("T", 7, "TSARINE").
dico("T", 7, "TSIGANE").
dico("T", 7, "TSUNAMI").
dico("T", 7, "TUABLES").
dico("T", 7, "TUAIENT").
dico("T", 7, "TUANTES").
dico("T", 7, "TUASSES").
dico("T", 7, "TUBAGES").
dico("T", 7, "TUBAIRE").
dico("T", 7, "TUBAMES").
dico("T", 7, "TUBARDE").
dico("T", 7, "TUBARDS").
dico("T", 7, "TUBASSE").
dico("T", 7, "TUBATES").
dico("T", 7, "TUBERAI").
dico("T", 7, "TUBERAS").
dico("T", 7, "TUBEREZ").
dico("T", 7, "TUBIFEX").
dico("T", 7, "TUBINGS").
dico("T", 7, "TUBIONS").
dico("T", 7, "TUBISTE").
dico("T", 7, "TUBULEE").
dico("T", 7, "TUBULES").
dico("T", 7, "TUCARDE").
dico("T", 7, "TUCARDS").
dico("T", 7, "TUCISTE").
dico("T", 7, "TUERAIS").
dico("T", 7, "TUERAIT").
dico("T", 7, "TUERENT").
dico("T", 7, "TUERIES").
dico("T", 7, "TUERIEZ").
dico("T", 7, "TUERONS").
dico("T", 7, "TUERONT").
dico("T", 7, "TUEUSES").
dico("T", 7, "TUFEAUX").
dico("T", 7, "TUFFEAU").
dico("T", 7, "TUFIERE").
dico("T", 7, "TUFIERS").
dico("T", 7, "TUGRIKS").
dico("T", 7, "TUILAIS").
dico("T", 7, "TUILAIT").
dico("T", 7, "TUILANT").
dico("T", 7, "TUILEAU").
dico("T", 7, "TUILEES").
dico("T", 7, "TUILENT").
dico("T", 7, "TUILERA").
dico("T", 7, "TUILIER").
dico("T", 7, "TUILIEZ").
dico("T", 7, "TUILONS").
dico("T", 7, "TULIPES").
dico("T", 7, "TULLIER").
dico("T", 7, "TULLOIS").
dico("T", 7, "TUMEFIA").
dico("T", 7, "TUMEFIE").
dico("T", 7, "TUMEURS").
dico("T", 7, "TUMORAL").
dico("T", 7, "TUMULTE").
dico("T", 7, "TUMULUS").
dico("T", 7, "TUNAGES").
dico("T", 7, "TUNGARS").
dico("T", 7, "TUNIQUE").
dico("T", 7, "TUNNELS").
dico("T", 7, "TUPAIAS").
dico("T", 7, "TUPAJAS").
dico("T", 7, "TURBANS").
dico("T", 7, "TURBEHS").
dico("T", 7, "TURBIDE").
dico("T", 7, "TURBINA").
dico("T", 7, "TURBINE").
dico("T", 7, "TURBINS").
dico("T", 7, "TURBITH").
dico("T", 7, "TURBOTS").
dico("T", 7, "TURDIDE").
dico("T", 7, "TURGIDE").
dico("T", 7, "TURIONS").
dico("T", 7, "TURISTA").
dico("T", 7, "TURLUTA").
dico("T", 7, "TURLUTE").
dico("T", 7, "TURNEPS").
dico("T", 7, "TURPIDE").
dico("T", 7, "TURQUES").
dico("T", 7, "TURQUIN").
dico("T", 7, "TURSANS").
dico("T", 7, "TUSSAHS").
dico("T", 7, "TUSSAUS").
dico("T", 7, "TUSSAUX").
dico("T", 7, "TUSSENT").
dico("T", 7, "TUSSIEZ").
dico("T", 7, "TUSSORE").
dico("T", 7, "TUSSORS").
dico("T", 7, "TUTELLE").
dico("T", 7, "TUTEURA").
dico("T", 7, "TUTEURE").
dico("T", 7, "TUTEURS").
dico("T", 7, "TUTHIES").
dico("T", 7, "TUTOIES").
dico("T", 7, "TUTORAT").
dico("T", 7, "TUTOYAI").
dico("T", 7, "TUTOYAS").
dico("T", 7, "TUTOYAT").
dico("T", 7, "TUTOYEE").
dico("T", 7, "TUTOYER").
dico("T", 7, "TUTOYES").
dico("T", 7, "TUTOYEZ").
dico("T", 7, "TUTRICE").
dico("T", 7, "TUTSIES").
dico("T", 7, "TUYAUTA").
dico("T", 7, "TUYAUTE").
dico("T", 7, "TUYERES").
dico("T", 7, "TWEETER").
dico("T", 7, "TWISTAI").
dico("T", 7, "TWISTAS").
dico("T", 7, "TWISTAT").
dico("T", 7, "TWISTEE").
dico("T", 7, "TWISTER").
dico("T", 7, "TWISTES").
dico("T", 7, "TWISTEZ").
dico("T", 7, "TYMPANS").
dico("T", 7, "TYPAGES").
dico("T", 7, "TYPAMES").
dico("T", 7, "TYPASSE").
dico("T", 7, "TYPATES").
dico("T", 7, "TYPERAI").
dico("T", 7, "TYPERAS").
dico("T", 7, "TYPEREZ").
dico("T", 7, "TYPESSE").
dico("T", 7, "TYPHONS").
dico("T", 7, "TYPHOSE").
dico("T", 7, "TYPIONS").
dico("T", 7, "TYPIQUE").
dico("T", 7, "TYPOTES").
dico("T", 7, "TYRIENS").
dico("T", 7, "TZARINE").
dico("T", 7, "TZIGANE").
