dico("T", 9, "TABAGIQUE").
dico("T", 9, "TABAGISME").
dico("T", 9, "TABASSAGE").
dico("T", 9, "TABASSAIS").
dico("T", 9, "TABASSAIT").
dico("T", 9, "TABASSANT").
dico("T", 9, "TABASSEES").
dico("T", 9, "TABASSENT").
dico("T", 9, "TABASSERA").
dico("T", 9, "TABASSIEZ").
dico("T", 9, "TABASSONS").
dico("T", 9, "TABATIERE").
dico("T", 9, "TABELLION").
dico("T", 9, "TABETIQUE").
dico("T", 9, "TABLAIENT").
dico("T", 9, "TABLASSES").
dico("T", 9, "TABLATURE").
dico("T", 9, "TABLERAIS").
dico("T", 9, "TABLERAIT").
dico("T", 9, "TABLERENT").
dico("T", 9, "TABLERIEZ").
dico("T", 9, "TABLERONS").
dico("T", 9, "TABLERONT").
dico("T", 9, "TABLETIER").
dico("T", 9, "TABLETTES").
dico("T", 9, "TABLOIDES").
dico("T", 9, "TABORITES").
dico("T", 9, "TABOUAMES").
dico("T", 9, "TABOUASSE").
dico("T", 9, "TABOUATES").
dico("T", 9, "TABOUERAI").
dico("T", 9, "TABOUERAS").
dico("T", 9, "TABOUEREZ").
dico("T", 9, "TABOUIONS").
dico("T", 9, "TABOUISAI").
dico("T", 9, "TABOUISAS").
dico("T", 9, "TABOUISAT").
dico("T", 9, "TABOUISEE").
dico("T", 9, "TABOUISER").
dico("T", 9, "TABOUISES").
dico("T", 9, "TABOUISEZ").
dico("T", 9, "TABOURETS").
dico("T", 9, "TABULAIRE").
dico("T", 9, "TABULAMES").
dico("T", 9, "TABULASSE").
dico("T", 9, "TABULATES").
dico("T", 9, "TABULERAI").
dico("T", 9, "TABULERAS").
dico("T", 9, "TABULEREZ").
dico("T", 9, "TABULIONS").
dico("T", 9, "TACHAIENT").
dico("T", 9, "TACHASSES").
dico("T", 9, "TACHERAIS").
dico("T", 9, "TACHERAIT").
dico("T", 9, "TACHERENT").
dico("T", 9, "TACHERIEZ").
dico("T", 9, "TACHERONS").
dico("T", 9, "TACHERONT").
dico("T", 9, "TACHETAIS").
dico("T", 9, "TACHETAIT").
dico("T", 9, "TACHETANT").
dico("T", 9, "TACHETEES").
dico("T", 9, "TACHETIEZ").
dico("T", 9, "TACHETONS").
dico("T", 9, "TACHETTES").
dico("T", 9, "TACHETURE").
dico("T", 9, "TACHISMES").
dico("T", 9, "TACHISTES").
dico("T", 9, "TACITURNE").
dico("T", 9, "TACLAIENT").
dico("T", 9, "TACLASSES").
dico("T", 9, "TACLERAIS").
dico("T", 9, "TACLERAIT").
dico("T", 9, "TACLERENT").
dico("T", 9, "TACLERIEZ").
dico("T", 9, "TACLERONS").
dico("T", 9, "TACLERONT").
dico("T", 9, "TACTICIEN").
dico("T", 9, "TACTICITE").
dico("T", 9, "TACTIQUES").
dico("T", 9, "TACTISMES").
dico("T", 9, "TAEKWONDO").
dico("T", 9, "TAGGAIENT").
dico("T", 9, "TAGGASSES").
dico("T", 9, "TAGGERAIS").
dico("T", 9, "TAGGERAIT").
dico("T", 9, "TAGGERENT").
dico("T", 9, "TAGGERIEZ").
dico("T", 9, "TAGGERONS").
dico("T", 9, "TAGGERONT").
dico("T", 9, "TAGUAIENT").
dico("T", 9, "TAGUASSES").
dico("T", 9, "TAGUERAIS").
dico("T", 9, "TAGUERAIT").
dico("T", 9, "TAGUERENT").
dico("T", 9, "TAGUERIEZ").
dico("T", 9, "TAGUERONS").
dico("T", 9, "TAGUERONT").
dico("T", 9, "TAGUEUSES").
dico("T", 9, "TAHITIENS").
dico("T", 9, "TAILLABLE").
dico("T", 9, "TAILLADAI").
dico("T", 9, "TAILLADAS").
dico("T", 9, "TAILLADAT").
dico("T", 9, "TAILLADEE").
dico("T", 9, "TAILLADER").
dico("T", 9, "TAILLADES").
dico("T", 9, "TAILLADEZ").
dico("T", 9, "TAILLAGES").
dico("T", 9, "TAILLAMES").
dico("T", 9, "TAILLANTS").
dico("T", 9, "TAILLASSE").
dico("T", 9, "TAILLATES").
dico("T", 9, "TAILLAULE").
dico("T", 9, "TAILLERAI").
dico("T", 9, "TAILLERAS").
dico("T", 9, "TAILLEREZ").
dico("T", 9, "TAILLERIE").
dico("T", 9, "TAILLEURS").
dico("T", 9, "TAILLEUSE").
dico("T", 9, "TAILLIONS").
dico("T", 9, "TAILLOIRS").
dico("T", 9, "TAILLOLES").
dico("T", 9, "TAIRAIENT").
dico("T", 9, "TAISAIENT").
dico("T", 9, "TAISEUSES").
dico("T", 9, "TAIWANAIS").
dico("T", 9, "TALAPOINS").
dico("T", 9, "TALASSENT").
dico("T", 9, "TALASSIEZ").
dico("T", 9, "TALEGGIOS").
dico("T", 9, "TALERIONS").
dico("T", 9, "TALIBANES").
dico("T", 9, "TALISMANS").
dico("T", 9, "TALLAIENT").
dico("T", 9, "TALLASSES").
dico("T", 9, "TALLERAIS").
dico("T", 9, "TALLERAIT").
dico("T", 9, "TALLERENT").
dico("T", 9, "TALLERIEZ").
dico("T", 9, "TALLERONS").
dico("T", 9, "TALLERONT").
dico("T", 9, "TALLIPOTS").
dico("T", 9, "TALMOUSES").
dico("T", 9, "TALOCHAGE").
dico("T", 9, "TALOCHAIS").
dico("T", 9, "TALOCHAIT").
dico("T", 9, "TALOCHANT").
dico("T", 9, "TALOCHEES").
dico("T", 9, "TALOCHENT").
dico("T", 9, "TALOCHERA").
dico("T", 9, "TALOCHIEZ").
dico("T", 9, "TALOCHONS").
dico("T", 9, "TALONNADE").
dico("T", 9, "TALONNAGE").
dico("T", 9, "TALONNAIS").
dico("T", 9, "TALONNAIT").
dico("T", 9, "TALONNANT").
dico("T", 9, "TALONNEES").
dico("T", 9, "TALONNENT").
dico("T", 9, "TALONNERA").
dico("T", 9, "TALONNEUR").
dico("T", 9, "TALONNIEZ").
dico("T", 9, "TALONNONS").
dico("T", 9, "TALQUAGES").
dico("T", 9, "TALQUAMES").
dico("T", 9, "TALQUASSE").
dico("T", 9, "TALQUATES").
dico("T", 9, "TALQUERAI").
dico("T", 9, "TALQUERAS").
dico("T", 9, "TALQUEREZ").
dico("T", 9, "TALQUEUSE").
dico("T", 9, "TALQUIONS").
dico("T", 9, "TALUTAGES").
dico("T", 9, "TALUTAMES").
dico("T", 9, "TALUTASSE").
dico("T", 9, "TALUTATES").
dico("T", 9, "TALUTERAI").
dico("T", 9, "TALUTERAS").
dico("T", 9, "TALUTEREZ").
dico("T", 9, "TALUTIONS").
dico("T", 9, "TAMANDUAS").
dico("T", 9, "TAMANOIRS").
dico("T", 9, "TAMAZIGHT").
dico("T", 9, "TAMAZIRTS").
dico("T", 9, "TAMBOURIN").
dico("T", 9, "TAMBOUYES").
dico("T", 9, "TAMISAGES").
dico("T", 9, "TAMISAMES").
dico("T", 9, "TAMISASSE").
dico("T", 9, "TAMISATES").
dico("T", 9, "TAMISERAI").
dico("T", 9, "TAMISERAS").
dico("T", 9, "TAMISEREZ").
dico("T", 9, "TAMISERIE").
dico("T", 9, "TAMISEURS").
dico("T", 9, "TAMISEUSE").
dico("T", 9, "TAMISIERE").
dico("T", 9, "TAMISIERS").
dico("T", 9, "TAMISIONS").
dico("T", 9, "TAMPONNAI").
dico("T", 9, "TAMPONNAS").
dico("T", 9, "TAMPONNAT").
dico("T", 9, "TAMPONNEE").
dico("T", 9, "TAMPONNER").
dico("T", 9, "TAMPONNES").
dico("T", 9, "TAMPONNEZ").
dico("T", 9, "TANAISIES").
dico("T", 9, "TANCAIENT").
dico("T", 9, "TANCASSES").
dico("T", 9, "TANCERAIS").
dico("T", 9, "TANCERAIT").
dico("T", 9, "TANCERENT").
dico("T", 9, "TANCERIEZ").
dico("T", 9, "TANCERONS").
dico("T", 9, "TANCERONT").
dico("T", 9, "TANDOORIS").
dico("T", 9, "TANGENCES").
dico("T", 9, "TANGENTES").
dico("T", 9, "TANGERINE").
dico("T", 9, "TANGIBLES").
dico("T", 9, "TANGUAMES").
dico("T", 9, "TANGUASSE").
dico("T", 9, "TANGUATES").
dico("T", 9, "TANGUERAI").
dico("T", 9, "TANGUERAS").
dico("T", 9, "TANGUEREZ").
dico("T", 9, "TANGUIERE").
dico("T", 9, "TANGUIONS").
dico("T", 9, "TANISAGES").
dico("T", 9, "TANISAMES").
dico("T", 9, "TANISASSE").
dico("T", 9, "TANISATES").
dico("T", 9, "TANISERAI").
dico("T", 9, "TANISERAS").
dico("T", 9, "TANISEREZ").
dico("T", 9, "TANISIONS").
dico("T", 9, "TANKISTES").
dico("T", 9, "TANNAIENT").
dico("T", 9, "TANNANTES").
dico("T", 9, "TANNASSES").
dico("T", 9, "TANNERAIS").
dico("T", 9, "TANNERAIT").
dico("T", 9, "TANNERENT").
dico("T", 9, "TANNERIES").
dico("T", 9, "TANNERIEZ").
dico("T", 9, "TANNERONS").
dico("T", 9, "TANNERONT").
dico("T", 9, "TANNEUSES").
dico("T", 9, "TANNIQUES").
dico("T", 9, "TANNISAGE").
dico("T", 9, "TANNISAIS").
dico("T", 9, "TANNISAIT").
dico("T", 9, "TANNISANT").
dico("T", 9, "TANNISEES").
dico("T", 9, "TANNISENT").
dico("T", 9, "TANNISERA").
dico("T", 9, "TANNISIEZ").
dico("T", 9, "TANNISONS").
dico("T", 9, "TANTIEMES").
dico("T", 9, "TANTOUSES").
dico("T", 9, "TANTOUZES").
dico("T", 9, "TANTRIQUE").
dico("T", 9, "TANTRISME").
dico("T", 9, "TANZANIEN").
dico("T", 9, "TAPAGEAIS").
dico("T", 9, "TAPAGEAIT").
dico("T", 9, "TAPAGEANT").
dico("T", 9, "TAPAGEONS").
dico("T", 9, "TAPAGERAI").
dico("T", 9, "TAPAGERAS").
dico("T", 9, "TAPAGEREZ").
dico("T", 9, "TAPAGEURS").
dico("T", 9, "TAPAGEUSE").
dico("T", 9, "TAPAGIONS").
dico("T", 9, "TAPASSENT").
dico("T", 9, "TAPASSIEZ").
dico("T", 9, "TAPEMENTS").
dico("T", 9, "TAPENADES").
dico("T", 9, "TAPERIONS").
dico("T", 9, "TAPINAMES").
dico("T", 9, "TAPINASSE").
dico("T", 9, "TAPINATES").
dico("T", 9, "TAPINERAI").
dico("T", 9, "TAPINERAS").
dico("T", 9, "TAPINEREZ").
dico("T", 9, "TAPINEUSE").
dico("T", 9, "TAPINIONS").
dico("T", 9, "TAPIRIONS").
dico("T", 9, "TAPISSAGE").
dico("T", 9, "TAPISSAIS").
dico("T", 9, "TAPISSAIT").
dico("T", 9, "TAPISSANT").
dico("T", 9, "TAPISSEES").
dico("T", 9, "TAPISSENT").
dico("T", 9, "TAPISSERA").
dico("T", 9, "TAPISSEUR").
dico("T", 9, "TAPISSIER").
dico("T", 9, "TAPISSIEZ").
dico("T", 9, "TAPISSONS").
dico("T", 9, "TAPOCHAIS").
dico("T", 9, "TAPOCHAIT").
dico("T", 9, "TAPOCHANT").
dico("T", 9, "TAPOCHEES").
dico("T", 9, "TAPOCHENT").
dico("T", 9, "TAPOCHERA").
dico("T", 9, "TAPOCHIEZ").
dico("T", 9, "TAPOCHONS").
dico("T", 9, "TAPONNAGE").
dico("T", 9, "TAPONNAIS").
dico("T", 9, "TAPONNAIT").
dico("T", 9, "TAPONNANT").
dico("T", 9, "TAPONNEES").
dico("T", 9, "TAPONNENT").
dico("T", 9, "TAPONNERA").
dico("T", 9, "TAPONNEUR").
dico("T", 9, "TAPONNIEZ").
dico("T", 9, "TAPONNONS").
dico("T", 9, "TAPOTAGES").
dico("T", 9, "TAPOTAMES").
dico("T", 9, "TAPOTASSE").
dico("T", 9, "TAPOTATES").
dico("T", 9, "TAPOTERAI").
dico("T", 9, "TAPOTERAS").
dico("T", 9, "TAPOTEREZ").
dico("T", 9, "TAPOTIONS").
dico("T", 9, "TAPUSCRIT").
dico("T", 9, "TAQUAIENT").
dico("T", 9, "TAQUASSES").
dico("T", 9, "TAQUERAIS").
dico("T", 9, "TAQUERAIT").
dico("T", 9, "TAQUERENT").
dico("T", 9, "TAQUERIEZ").
dico("T", 9, "TAQUERONS").
dico("T", 9, "TAQUERONT").
dico("T", 9, "TAQUINAIS").
dico("T", 9, "TAQUINAIT").
dico("T", 9, "TAQUINANT").
dico("T", 9, "TAQUINEES").
dico("T", 9, "TAQUINENT").
dico("T", 9, "TAQUINERA").
dico("T", 9, "TAQUINIEZ").
dico("T", 9, "TAQUINONS").
dico("T", 9, "TARABUSTA").
dico("T", 9, "TARABUSTE").
dico("T", 9, "TARANTASS").
dico("T", 9, "TARARAGES").
dico("T", 9, "TARASQUES").
dico("T", 9, "TARASSENT").
dico("T", 9, "TARASSIEZ").
dico("T", 9, "TARAUDAGE").
dico("T", 9, "TARAUDAIS").
dico("T", 9, "TARAUDAIT").
dico("T", 9, "TARAUDANT").
dico("T", 9, "TARAUDEES").
dico("T", 9, "TARAUDENT").
dico("T", 9, "TARAUDERA").
dico("T", 9, "TARAUDEUR").
dico("T", 9, "TARAUDIEZ").
dico("T", 9, "TARAUDONS").
dico("T", 9, "TARAVELLE").
dico("T", 9, "TARBAISES").
dico("T", 9, "TARBOUCHE").
dico("T", 9, "TARBOUCHS").
dico("T", 9, "TARDAIENT").
dico("T", 9, "TARDASSES").
dico("T", 9, "TARDERAIS").
dico("T", 9, "TARDERAIT").
dico("T", 9, "TARDERENT").
dico("T", 9, "TARDERIEZ").
dico("T", 9, "TARDERONS").
dico("T", 9, "TARDERONT").
dico("T", 9, "TARDILLON").
dico("T", 9, "TARDIVETE").
dico("T", 9, "TARENTAIS").
dico("T", 9, "TARENTINE").
dico("T", 9, "TARENTINS").
dico("T", 9, "TARENTULE").
dico("T", 9, "TARERIONS").
dico("T", 9, "TARGETTES").
dico("T", 9, "TARGUAMES").
dico("T", 9, "TARGUASSE").
dico("T", 9, "TARGUATES").
dico("T", 9, "TARGUERAI").
dico("T", 9, "TARGUERAS").
dico("T", 9, "TARGUEREZ").
dico("T", 9, "TARGUIONS").
dico("T", 9, "TARIFAIRE").
dico("T", 9, "TARIFAMES").
dico("T", 9, "TARIFASSE").
dico("T", 9, "TARIFATES").
dico("T", 9, "TARIFERAI").
dico("T", 9, "TARIFERAS").
dico("T", 9, "TARIFEREZ").
dico("T", 9, "TARIFIAIS").
dico("T", 9, "TARIFIAIT").
dico("T", 9, "TARIFIANT").
dico("T", 9, "TARIFIEES").
dico("T", 9, "TARIFIENT").
dico("T", 9, "TARIFIERA").
dico("T", 9, "TARIFIIEZ").
dico("T", 9, "TARIFIONS").
dico("T", 9, "TARIRIONS").
dico("T", 9, "TARISSAIS").
dico("T", 9, "TARISSAIT").
dico("T", 9, "TARISSANT").
dico("T", 9, "TARISSENT").
dico("T", 9, "TARISSIEZ").
dico("T", 9, "TARISSONS").
dico("T", 9, "TARLATANE").
dico("T", 9, "TARNAISES").
dico("T", 9, "TAROTEURS").
dico("T", 9, "TAROTEUSE").
dico("T", 9, "TARSIENNE").
dico("T", 9, "TARTARINS").
dico("T", 9, "TARTINAIS").
dico("T", 9, "TARTINAIT").
dico("T", 9, "TARTINANT").
dico("T", 9, "TARTINEES").
dico("T", 9, "TARTINENT").
dico("T", 9, "TARTINERA").
dico("T", 9, "TARTINIEZ").
dico("T", 9, "TARTINONS").
dico("T", 9, "TARTIRAIS").
dico("T", 9, "TARTIRAIT").
dico("T", 9, "TARTIRENT").
dico("T", 9, "TARTIRIEZ").
dico("T", 9, "TARTIRONS").
dico("T", 9, "TARTIRONT").
dico("T", 9, "TARTISSES").
dico("T", 9, "TARTISSEZ").
dico("T", 9, "TARTRAGES").
dico("T", 9, "TARTRATES").
dico("T", 9, "TARTREUSE").
dico("T", 9, "TARTRIQUE").
dico("T", 9, "TARTUFFES").
dico("T", 9, "TASMANIEN").
dico("T", 9, "TASSAIENT").
dico("T", 9, "TASSASSES").
dico("T", 9, "TASSEMENT").
dico("T", 9, "TASSERAIS").
dico("T", 9, "TASSERAIT").
dico("T", 9, "TASSERENT").
dico("T", 9, "TASSERIEZ").
dico("T", 9, "TASSERONS").
dico("T", 9, "TASSERONT").
dico("T", 9, "TASSETTES").
dico("T", 9, "TATASSENT").
dico("T", 9, "TATASSIEZ").
dico("T", 9, "TATERIONS").
dico("T", 9, "TATILLONS").
dico("T", 9, "TATONNAIS").
dico("T", 9, "TATONNAIT").
dico("T", 9, "TATONNANT").
dico("T", 9, "TATONNENT").
dico("T", 9, "TATONNERA").
dico("T", 9, "TATONNIEZ").
dico("T", 9, "TATONNONS").
dico("T", 9, "TATOUAGES").
dico("T", 9, "TATOUAMES").
dico("T", 9, "TATOUASSE").
dico("T", 9, "TATOUATES").
dico("T", 9, "TATOUERAI").
dico("T", 9, "TATOUERAS").
dico("T", 9, "TATOUEREZ").
dico("T", 9, "TATOUEURS").
dico("T", 9, "TATOUEUSE").
dico("T", 9, "TATOUILLE").
dico("T", 9, "TATOUIONS").
dico("T", 9, "TAUDAIENT").
dico("T", 9, "TAUDASSES").
dico("T", 9, "TAUDERAIS").
dico("T", 9, "TAUDERAIT").
dico("T", 9, "TAUDERENT").
dico("T", 9, "TAUDERIEZ").
dico("T", 9, "TAUDERONS").
dico("T", 9, "TAUDERONT").
dico("T", 9, "TAULARDES").
dico("T", 9, "TAULIERES").
dico("T", 9, "TAUPAIENT").
dico("T", 9, "TAUPASSES").
dico("T", 9, "TAUPERAIS").
dico("T", 9, "TAUPERAIT").
dico("T", 9, "TAUPERENT").
dico("T", 9, "TAUPERIEZ").
dico("T", 9, "TAUPERONS").
dico("T", 9, "TAUPERONT").
dico("T", 9, "TAUPIERES").
dico("T", 9, "TAUPINEES").
dico("T", 9, "TAURILLON").
dico("T", 9, "TAUROBOLE").
dico("T", 9, "TAUTOMERE").
dico("T", 9, "TAVAIOLLE").
dico("T", 9, "TAVELAGES").
dico("T", 9, "TAVELAMES").
dico("T", 9, "TAVELASSE").
dico("T", 9, "TAVELATES").
dico("T", 9, "TAVELIONS").
dico("T", 9, "TAVELLENT").
dico("T", 9, "TAVELLERA").
dico("T", 9, "TAVELURES").
dico("T", 9, "TAVERNIER").
dico("T", 9, "TAVILLONS").
dico("T", 9, "TAXASSENT").
dico("T", 9, "TAXASSIEZ").
dico("T", 9, "TAXATEURS").
dico("T", 9, "TAXATIONS").
dico("T", 9, "TAXATIVES").
dico("T", 9, "TAXATRICE").
dico("T", 9, "TAXAUDIER").
dico("T", 9, "TAXERIONS").
dico("T", 9, "TAXIARQUE").
dico("T", 9, "TAXIMETRE").
dico("T", 9, "TAXINOMIE").
dico("T", 9, "TAXIPHONE").
dico("T", 9, "TAXODIERS").
dico("T", 9, "TAXODIUMS").
dico("T", 9, "TAXONOMIE").
dico("T", 9, "TAYLORISA").
dico("T", 9, "TAYLORISE").
dico("T", 9, "TCHADIENS").
dico("T", 9, "TCHAPALOS").
dico("T", 9, "TCHARCHAF").
dico("T", 9, "TCHATCHAI").
dico("T", 9, "TCHATCHAS").
dico("T", 9, "TCHATCHAT").
dico("T", 9, "TCHATCHEE").
dico("T", 9, "TCHATCHER").
dico("T", 9, "TCHATCHES").
dico("T", 9, "TCHATCHEZ").
dico("T", 9, "TCHETNIKS").
dico("T", 9, "TCHITOLAS").
dico("T", 9, "TECHNEMES").
dico("T", 9, "TECHNIQUE").
dico("T", 9, "TECHNISAI").
dico("T", 9, "TECHNISAS").
dico("T", 9, "TECHNISAT").
dico("T", 9, "TECHNISEE").
dico("T", 9, "TECHNISER").
dico("T", 9, "TECHNISES").
dico("T", 9, "TECHNISEZ").
dico("T", 9, "TECTRICES").
dico("T", 9, "TEENAGERS").
dico("T", 9, "TEFLONISE").
dico("T", 9, "TEGENAIRE").
dico("T", 9, "TEGEVISTE").
dico("T", 9, "TEGUMENTS").
dico("T", 9, "TEIGNEUSE").
dico("T", 9, "TEIGNIMES").
dico("T", 9, "TEIGNIONS").
dico("T", 9, "TEIGNISSE").
dico("T", 9, "TEIGNITES").
dico("T", 9, "TEILLAGES").
dico("T", 9, "TEILLAMES").
dico("T", 9, "TEILLASSE").
dico("T", 9, "TEILLATES").
dico("T", 9, "TEILLERAI").
dico("T", 9, "TEILLERAS").
dico("T", 9, "TEILLEREZ").
dico("T", 9, "TEILLEURS").
dico("T", 9, "TEILLEUSE").
dico("T", 9, "TEILLIONS").
dico("T", 9, "TEINDRAIS").
dico("T", 9, "TEINDRAIT").
dico("T", 9, "TEINDRIEZ").
dico("T", 9, "TEINDRONS").
dico("T", 9, "TEINDRONT").
dico("T", 9, "TEINTAMES").
dico("T", 9, "TEINTANTE").
dico("T", 9, "TEINTANTS").
dico("T", 9, "TEINTASSE").
dico("T", 9, "TEINTATES").
dico("T", 9, "TEINTERAI").
dico("T", 9, "TEINTERAS").
dico("T", 9, "TEINTEREZ").
dico("T", 9, "TEINTIONS").
dico("T", 9, "TEINTURES").
dico("T", 9, "TELEACHAT").
dico("T", 9, "TELEASTES").
dico("T", 9, "TELEBENNE").
dico("T", 9, "TELECARTE").
dico("T", 9, "TELECOPIA").
dico("T", 9, "TELECOPIE").
dico("T", 9, "TELECRANS").
dico("T", 9, "TELEFILMS").
dico("T", 9, "TELEGENIE").
dico("T", 9, "TELEGUIDA").
dico("T", 9, "TELEGUIDE").
dico("T", 9, "TELEMARKS").
dico("T", 9, "TELEMETRA").
dico("T", 9, "TELEMETRE").
dico("T", 9, "TELENOMIE").
dico("T", 9, "TELEPATHE").
dico("T", 9, "TELEPEAGE").
dico("T", 9, "TELEPHAGE").
dico("T", 9, "TELEPHONA").
dico("T", 9, "TELEPHONE").
dico("T", 9, "TELEPORTS").
dico("T", 9, "TELERADAR").
dico("T", 9, "TELERADIO").
dico("T", 9, "TELEROMAN").
dico("T", 9, "TELESCOPA").
dico("T", 9, "TELESCOPE").
dico("T", 9, "TELESIEGE").
dico("T", 9, "TELESUITE").
dico("T", 9, "TELETEXTE").
dico("T", 9, "TELETHONS").
dico("T", 9, "TELETOXIE").
dico("T", 9, "TELETYPES").
dico("T", 9, "TELEVENTE").
dico("T", 9, "TELEVISAI").
dico("T", 9, "TELEVISAS").
dico("T", 9, "TELEVISAT").
dico("T", 9, "TELEVISEE").
dico("T", 9, "TELEVISER").
dico("T", 9, "TELEVISES").
dico("T", 9, "TELEVISEZ").
dico("T", 9, "TELEXAMES").
dico("T", 9, "TELEXASSE").
dico("T", 9, "TELEXATES").
dico("T", 9, "TELEXERAI").
dico("T", 9, "TELEXERAS").
dico("T", 9, "TELEXEREZ").
dico("T", 9, "TELEXIONS").
dico("T", 9, "TELEXISTE").
dico("T", 9, "TELLEMENT").
dico("T", 9, "TELLIERES").
dico("T", 9, "TELLURATE").
dico("T", 9, "TELLUREUX").
dico("T", 9, "TELLURIEN").
dico("T", 9, "TELLURURE").
dico("T", 9, "TELOMERES").
dico("T", 9, "TELOPHASE").
dico("T", 9, "TELOUGOUS").
dico("T", 9, "TEMERAIRE").
dico("T", 9, "TEMERITES").
dico("T", 9, "TEMOIGNAI").
dico("T", 9, "TEMOIGNAS").
dico("T", 9, "TEMOIGNAT").
dico("T", 9, "TEMOIGNEE").
dico("T", 9, "TEMOIGNER").
dico("T", 9, "TEMOIGNES").
dico("T", 9, "TEMOIGNEZ").
dico("T", 9, "TEMPERAIS").
dico("T", 9, "TEMPERAIT").
dico("T", 9, "TEMPERANT").
dico("T", 9, "TEMPEREES").
dico("T", 9, "TEMPERENT").
dico("T", 9, "TEMPERERA").
dico("T", 9, "TEMPERIEZ").
dico("T", 9, "TEMPERONS").
dico("T", 9, "TEMPETAIS").
dico("T", 9, "TEMPETAIT").
dico("T", 9, "TEMPETANT").
dico("T", 9, "TEMPETENT").
dico("T", 9, "TEMPETERA").
dico("T", 9, "TEMPETIEZ").
dico("T", 9, "TEMPETONS").
dico("T", 9, "TEMPLIERS").
dico("T", 9, "TEMPORALE").
dico("T", 9, "TEMPORAUX").
dico("T", 9, "TEMPORELS").
dico("T", 9, "TEMPORISA").
dico("T", 9, "TEMPORISE").
dico("T", 9, "TENACITES").
dico("T", 9, "TENAILLAI").
dico("T", 9, "TENAILLAS").
dico("T", 9, "TENAILLAT").
dico("T", 9, "TENAILLEE").
dico("T", 9, "TENAILLER").
dico("T", 9, "TENAILLES").
dico("T", 9, "TENAILLEZ").
dico("T", 9, "TENANCIER").
dico("T", 9, "TENDAIENT").
dico("T", 9, "TENDANCES").
dico("T", 9, "TENDANTES").
dico("T", 9, "TENDELLES").
dico("T", 9, "TENDERIES").
dico("T", 9, "TENDEUSES").
dico("T", 9, "TENDINEUX").
dico("T", 9, "TENDINITE").
dico("T", 9, "TENDIRENT").
dico("T", 9, "TENDISSES").
dico("T", 9, "TENDRESSE").
dico("T", 9, "TENDRETES").
dico("T", 9, "TENDRIONS").
dico("T", 9, "TENEBREUX").
dico("T", 9, "TENEBRION").
dico("T", 9, "TENEMENTS").
dico("T", 9, "TENICIDES").
dico("T", 9, "TENIFUGES").
dico("T", 9, "TENNISMAN").
dico("T", 9, "TENNISMEN").
dico("T", 9, "TENONNAGE").
dico("T", 9, "TENONNAIS").
dico("T", 9, "TENONNAIT").
dico("T", 9, "TENONNANT").
dico("T", 9, "TENONNEES").
dico("T", 9, "TENONNENT").
dico("T", 9, "TENONNERA").
dico("T", 9, "TENONNIEZ").
dico("T", 9, "TENONNONS").
dico("T", 9, "TENORINOS").
dico("T", 9, "TENORISAI").
dico("T", 9, "TENORISAS").
dico("T", 9, "TENORISAT").
dico("T", 9, "TENORISEE").
dico("T", 9, "TENORISER").
dico("T", 9, "TENORISES").
dico("T", 9, "TENORISEZ").
dico("T", 9, "TENORITES").
dico("T", 9, "TENOTOMIE").
dico("T", 9, "TENSORIEL").
dico("T", 9, "TENTACULE").
dico("T", 9, "TENTAIENT").
dico("T", 9, "TENTANTES").
dico("T", 9, "TENTASSES").
dico("T", 9, "TENTATEUR").
dico("T", 9, "TENTATION").
dico("T", 9, "TENTATIVE").
dico("T", 9, "TENTERAIS").
dico("T", 9, "TENTERAIT").
dico("T", 9, "TENTERENT").
dico("T", 9, "TENTERIEZ").
dico("T", 9, "TENTERONS").
dico("T", 9, "TENTERONT").
dico("T", 9, "TENTHREDE").
dico("T", 9, "TEOCALLIS").
dico("T", 9, "TEPHILLIM").
dico("T", 9, "TEPHILLIN").
dico("T", 9, "TEPHRITES").
dico("T", 9, "TEPHROSIA").
dico("T", 9, "TEPHROSIE").
dico("T", 9, "TERAGONES").
dico("T", 9, "TERASPICS").
dico("T", 9, "TERATOMES").
dico("T", 9, "TERAWATTS").
dico("T", 9, "TERCAIENT").
dico("T", 9, "TERCASSES").
dico("T", 9, "TERCERAIS").
dico("T", 9, "TERCERAIT").
dico("T", 9, "TERCERENT").
dico("T", 9, "TERCERIEZ").
dico("T", 9, "TERCERONS").
dico("T", 9, "TERCERONT").
dico("T", 9, "TEREBELLE").
dico("T", 9, "TEREBIQUE").
dico("T", 9, "TEREBRANT").
dico("T", 9, "TERFESSES").
dico("T", 9, "TERLENKAS").
dico("T", 9, "TERMINAIS").
dico("T", 9, "TERMINAIT").
dico("T", 9, "TERMINALE").
dico("T", 9, "TERMINANT").
dico("T", 9, "TERMINAUX").
dico("T", 9, "TERMINEES").
dico("T", 9, "TERMINENT").
dico("T", 9, "TERMINERA").
dico("T", 9, "TERMINIEZ").
dico("T", 9, "TERMINONS").
dico("T", 9, "TERNAIRES").
dico("T", 9, "TERNIRAIS").
dico("T", 9, "TERNIRAIT").
dico("T", 9, "TERNIRENT").
dico("T", 9, "TERNIRIEZ").
dico("T", 9, "TERNIRONS").
dico("T", 9, "TERNIRONT").
dico("T", 9, "TERNISSES").
dico("T", 9, "TERNISSEZ").
dico("T", 9, "TERPINEOL").
dico("T", 9, "TERPINOLS").
dico("T", 9, "TERRAIENT").
dico("T", 9, "TERRAMARE").
dico("T", 9, "TERRAQUEE").
dico("T", 9, "TERRAQUES").
dico("T", 9, "TERRARIUM").
dico("T", 9, "TERRASSAI").
dico("T", 9, "TERRASSAS").
dico("T", 9, "TERRASSAT").
dico("T", 9, "TERRASSEE").
dico("T", 9, "TERRASSER").
dico("T", 9, "TERRASSES").
dico("T", 9, "TERRASSEZ").
dico("T", 9, "TERRAZZOS").
dico("T", 9, "TERREAUTA").
dico("T", 9, "TERREAUTE").
dico("T", 9, "TERREFORT").
dico("T", 9, "TERRERAIS").
dico("T", 9, "TERRERAIT").
dico("T", 9, "TERRERENT").
dico("T", 9, "TERRERIEZ").
dico("T", 9, "TERRERONS").
dico("T", 9, "TERRERONT").
dico("T", 9, "TERRESTRE").
dico("T", 9, "TERREUSES").
dico("T", 9, "TERRIBLES").
dico("T", 9, "TERRICOLE").
dico("T", 9, "TERRIENNE").
dico("T", 9, "TERRIERES").
dico("T", 9, "TERRIFIAI").
dico("T", 9, "TERRIFIAS").
dico("T", 9, "TERRIFIAT").
dico("T", 9, "TERRIFIEE").
dico("T", 9, "TERRIFIER").
dico("T", 9, "TERRIFIES").
dico("T", 9, "TERRIFIEZ").
dico("T", 9, "TERRIGENE").
dico("T", 9, "TERRINEES").
dico("T", 9, "TERRIRAIS").
dico("T", 9, "TERRIRAIT").
dico("T", 9, "TERRIRENT").
dico("T", 9, "TERRIRIEZ").
dico("T", 9, "TERRIRONS").
dico("T", 9, "TERRIRONT").
dico("T", 9, "TERRISSES").
dico("T", 9, "TERRISSEZ").
dico("T", 9, "TERRORISA").
dico("T", 9, "TERRORISE").
dico("T", 9, "TERSAIENT").
dico("T", 9, "TERSASSES").
dico("T", 9, "TERSERAIS").
dico("T", 9, "TERSERAIT").
dico("T", 9, "TERSERENT").
dico("T", 9, "TERSERIEZ").
dico("T", 9, "TERSERONS").
dico("T", 9, "TERSERONT").
dico("T", 9, "TERTIAIRE").
dico("T", 9, "TERVUEREN").
dico("T", 9, "TERYLENES").
dico("T", 9, "TERZETTOS").
dico("T", 9, "TESSELLES").
dico("T", 9, "TESSINOIS").
dico("T", 9, "TESSITURE").
dico("T", 9, "TESTABLES").
dico("T", 9, "TESTACEES").
dico("T", 9, "TESTAIENT").
dico("T", 9, "TESTAMENT").
dico("T", 9, "TESTASSES").
dico("T", 9, "TESTATEUR").
dico("T", 9, "TESTERAIS").
dico("T", 9, "TESTERAIT").
dico("T", 9, "TESTERENT").
dico("T", 9, "TESTERIEZ").
dico("T", 9, "TESTERONS").
dico("T", 9, "TESTERONT").
dico("T", 9, "TESTEUSES").
dico("T", 9, "TESTICULE").
dico("T", 9, "TETANIQUE").
dico("T", 9, "TETANISAI").
dico("T", 9, "TETANISAS").
dico("T", 9, "TETANISAT").
dico("T", 9, "TETANISEE").
dico("T", 9, "TETANISER").
dico("T", 9, "TETANISES").
dico("T", 9, "TETANISEZ").
dico("T", 9, "TETANISME").
dico("T", 9, "TETASSENT").
dico("T", 9, "TETASSIEZ").
dico("T", 9, "TETERELLE").
dico("T", 9, "TETERIONS").
dico("T", 9, "TETRAEDRE").
dico("T", 9, "TETRAGONE").
dico("T", 9, "TETRALINE").
dico("T", 9, "TETRAMERE").
dico("T", 9, "TETRAPODE").
dico("T", 9, "TETRARQUE").
dico("T", 9, "TETRODONS").
dico("T", 9, "TEUTONNES").
dico("T", 9, "TEXTUELLE").
dico("T", 9, "TEXTURAIS").
dico("T", 9, "TEXTURAIT").
dico("T", 9, "TEXTURANT").
dico("T", 9, "TEXTUREES").
dico("T", 9, "TEXTURENT").
dico("T", 9, "TEXTURERA").
dico("T", 9, "TEXTURIEZ").
dico("T", 9, "TEXTURISA").
dico("T", 9, "TEXTURISE").
dico("T", 9, "TEXTURONS").
dico("T", 9, "THALASSOS").
dico("T", 9, "THALLIUMS").
dico("T", 9, "THANATOSE").
dico("T", 9, "THEATRALE").
dico("T", 9, "THEATRAUX").
dico("T", 9, "THEATREUX").
dico("T", 9, "THEBAIDES").
dico("T", 9, "THEBAINES").
dico("T", 9, "THEBAIQUE").
dico("T", 9, "THEBAISME").
dico("T", 9, "THEODICEE").
dico("T", 9, "THEOGONIE").
dico("T", 9, "THEOLOGAL").
dico("T", 9, "THEOLOGIE").
dico("T", 9, "THEOPHORE").
dico("T", 9, "THEOREMES").
dico("T", 9, "THEORIQUE").
dico("T", 9, "THEORISAI").
dico("T", 9, "THEORISAS").
dico("T", 9, "THEORISAT").
dico("T", 9, "THEORISEE").
dico("T", 9, "THEORISER").
dico("T", 9, "THEORISES").
dico("T", 9, "THEORISEZ").
dico("T", 9, "THEOSOPHE").
dico("T", 9, "THERAPIES").
dico("T", 9, "THERAVADA").
dico("T", 9, "THERIAQUE").
dico("T", 9, "THERIDION").
dico("T", 9, "THERIDIUM").
dico("T", 9, "THERMALES").
dico("T", 9, "THERMIDOR").
dico("T", 9, "THERMIQUE").
dico("T", 9, "THERMITES").
dico("T", 9, "THEROPODE").
dico("T", 9, "THESARDES").
dico("T", 9, "THESAURUS").
dico("T", 9, "THETIQUES").
dico("T", 9, "THEURGIES").
dico("T", 9, "THIAMINES").
dico("T", 9, "THIAZINES").
dico("T", 9, "THIAZOLES").
dico("T", 9, "THIBAUDES").
dico("T", 9, "THIOACIDE").
dico("T", 9, "THIOFENES").
dico("T", 9, "THIONATES").
dico("T", 9, "THIONINES").
dico("T", 9, "THIONIQUE").
dico("T", 9, "THIOPHENE").
dico("T", 9, "THOMISMES").
dico("T", 9, "THOMISTES").
dico("T", 9, "THONAIRES").
dico("T", 9, "THREONINE").
dico("T", 9, "THRIDACES").
dico("T", 9, "THRILLERS").
dico("T", 9, "THROMBINE").
dico("T", 9, "THROMBOSE").
dico("T", 9, "THYLACINE").
dico("T", 9, "THYMIQUES").
dico("T", 9, "THYMOCYTE").
dico("T", 9, "THYRATRON").
dico("T", 9, "THYRISTOR").
dico("T", 9, "THYROIDES").
dico("T", 9, "THYROXINE").
dico("T", 9, "TIBETAINE").
dico("T", 9, "TIBETAINS").
dico("T", 9, "TICTAQUAI").
dico("T", 9, "TICTAQUAS").
dico("T", 9, "TICTAQUAT").
dico("T", 9, "TICTAQUER").
dico("T", 9, "TICTAQUES").
dico("T", 9, "TICTAQUEZ").
dico("T", 9, "TIEDASSES").
dico("T", 9, "TIEDEMENT").
dico("T", 9, "TIEDIRAIS").
dico("T", 9, "TIEDIRAIT").
dico("T", 9, "TIEDIRENT").
dico("T", 9, "TIEDIRIEZ").
dico("T", 9, "TIEDIRONS").
dico("T", 9, "TIEDIRONT").
dico("T", 9, "TIEDISSES").
dico("T", 9, "TIEDISSEZ").
dico("T", 9, "TIENDRAIS").
dico("T", 9, "TIENDRAIT").
dico("T", 9, "TIENDRIEZ").
dico("T", 9, "TIENDRONS").
dico("T", 9, "TIENDRONT").
dico("T", 9, "TIERCAGES").
dico("T", 9, "TIERCAMES").
dico("T", 9, "TIERCASSE").
dico("T", 9, "TIERCATES").
dico("T", 9, "TIERCELET").
dico("T", 9, "TIERCERAI").
dico("T", 9, "TIERCERAS").
dico("T", 9, "TIERCEREZ").
dico("T", 9, "TIERCERON").
dico("T", 9, "TIERCIONS").
dico("T", 9, "TIGEAIENT").
dico("T", 9, "TIGEASSES").
dico("T", 9, "TIGERIONS").
dico("T", 9, "TIGNASSES").
dico("T", 9, "TIGRAIENT").
dico("T", 9, "TIGRASSES").
dico("T", 9, "TIGRERAIS").
dico("T", 9, "TIGRERAIT").
dico("T", 9, "TIGRERENT").
dico("T", 9, "TIGRERIEZ").
dico("T", 9, "TIGRERONS").
dico("T", 9, "TIGRERONT").
dico("T", 9, "TIGRESSES").
dico("T", 9, "TIGRIDIAS").
dico("T", 9, "TIGRIDIES").
dico("T", 9, "TILIACEES").
dico("T", 9, "TILLAIENT").
dico("T", 9, "TILLASSES").
dico("T", 9, "TILLERAIS").
dico("T", 9, "TILLERAIT").
dico("T", 9, "TILLERENT").
dico("T", 9, "TILLERIEZ").
dico("T", 9, "TILLERONS").
dico("T", 9, "TILLERONT").
dico("T", 9, "TILLEUSES").
dico("T", 9, "TILTAIENT").
dico("T", 9, "TILTASSES").
dico("T", 9, "TILTERAIS").
dico("T", 9, "TILTERAIT").
dico("T", 9, "TILTERENT").
dico("T", 9, "TILTERIEZ").
dico("T", 9, "TILTERONS").
dico("T", 9, "TILTERONT").
dico("T", 9, "TIMBALIER").
dico("T", 9, "TIMBRAGES").
dico("T", 9, "TIMBRAMES").
dico("T", 9, "TIMBRASSE").
dico("T", 9, "TIMBRATES").
dico("T", 9, "TIMBRERAI").
dico("T", 9, "TIMBRERAS").
dico("T", 9, "TIMBREREZ").
dico("T", 9, "TIMBREURS").
dico("T", 9, "TIMBREUSE").
dico("T", 9, "TIMBRIONS").
dico("T", 9, "TIMIDITES").
dico("T", 9, "TIMONERIE").
dico("T", 9, "TIMONIERS").
dico("T", 9, "TIMORAISE").
dico("T", 9, "TINSSIONS").
dico("T", 9, "TINTAIENT").
dico("T", 9, "TINTASSES").
dico("T", 9, "TINTEMENT").
dico("T", 9, "TINTERAIS").
dico("T", 9, "TINTERAIT").
dico("T", 9, "TINTERENT").
dico("T", 9, "TINTERIEZ").
dico("T", 9, "TINTERONS").
dico("T", 9, "TINTERONT").
dico("T", 9, "TINTOUINS").
dico("T", 9, "TIPASSENT").
dico("T", 9, "TIPASSIEZ").
dico("T", 9, "TIPERIONS").
dico("T", 9, "TIPPAIENT").
dico("T", 9, "TIPPASSES").
dico("T", 9, "TIPPERAIS").
dico("T", 9, "TIPPERAIT").
dico("T", 9, "TIPPERENT").
dico("T", 9, "TIPPERIEZ").
dico("T", 9, "TIPPERONS").
dico("T", 9, "TIPPERONT").
dico("T", 9, "TIQUAIENT").
dico("T", 9, "TIQUASSES").
dico("T", 9, "TIQUERAIS").
dico("T", 9, "TIQUERAIT").
dico("T", 9, "TIQUERENT").
dico("T", 9, "TIQUERIEZ").
dico("T", 9, "TIQUERONS").
dico("T", 9, "TIQUERONT").
dico("T", 9, "TIQUETEES").
dico("T", 9, "TIQUETURE").
dico("T", 9, "TIQUEUSES").
dico("T", 9, "TIRAILLAI").
dico("T", 9, "TIRAILLAS").
dico("T", 9, "TIRAILLAT").
dico("T", 9, "TIRAILLEE").
dico("T", 9, "TIRAILLER").
dico("T", 9, "TIRAILLES").
dico("T", 9, "TIRAILLEZ").
dico("T", 9, "TIRAMISUS").
dico("T", 9, "TIRANAISE").
dico("T", 9, "TIRASSENT").
dico("T", 9, "TIRASSIEZ").
dico("T", 9, "TIREFONDS").
dico("T", 9, "TIRELIRES").
dico("T", 9, "TIRERIONS").
dico("T", 9, "TIRETAINE").
dico("T", 9, "TISANERIE").
dico("T", 9, "TISANIERE").
dico("T", 9, "TISONNAIS").
dico("T", 9, "TISONNAIT").
dico("T", 9, "TISONNANT").
dico("T", 9, "TISONNEES").
dico("T", 9, "TISONNENT").
dico("T", 9, "TISONNERA").
dico("T", 9, "TISONNIER").
dico("T", 9, "TISONNIEZ").
dico("T", 9, "TISONNONS").
dico("T", 9, "TISSAIENT").
dico("T", 9, "TISSASSES").
dico("T", 9, "TISSERAIS").
dico("T", 9, "TISSERAIT").
dico("T", 9, "TISSERAND").
dico("T", 9, "TISSERENT").
dico("T", 9, "TISSERIEZ").
dico("T", 9, "TISSERINS").
dico("T", 9, "TISSERONS").
dico("T", 9, "TISSERONT").
dico("T", 9, "TISSEUSES").
dico("T", 9, "TITANIQUE").
dico("T", 9, "TITILLAIS").
dico("T", 9, "TITILLAIT").
dico("T", 9, "TITILLANT").
dico("T", 9, "TITILLEES").
dico("T", 9, "TITILLENT").
dico("T", 9, "TITILLERA").
dico("T", 9, "TITILLIEZ").
dico("T", 9, "TITILLONS").
dico("T", 9, "TITRAIENT").
dico("T", 9, "TITRASSES").
dico("T", 9, "TITRERAIS").
dico("T", 9, "TITRERAIT").
dico("T", 9, "TITRERENT").
dico("T", 9, "TITRERIEZ").
dico("T", 9, "TITRERONS").
dico("T", 9, "TITRERONT").
dico("T", 9, "TITREUSES").
dico("T", 9, "TITRISAIS").
dico("T", 9, "TITRISAIT").
dico("T", 9, "TITRISANT").
dico("T", 9, "TITRISEES").
dico("T", 9, "TITRISENT").
dico("T", 9, "TITRISERA").
dico("T", 9, "TITRISIEZ").
dico("T", 9, "TITRISONS").
dico("T", 9, "TITUBAMES").
dico("T", 9, "TITUBANTE").
dico("T", 9, "TITUBANTS").
dico("T", 9, "TITUBASSE").
dico("T", 9, "TITUBATES").
dico("T", 9, "TITUBERAI").
dico("T", 9, "TITUBERAS").
dico("T", 9, "TITUBEREZ").
dico("T", 9, "TITUBIONS").
dico("T", 9, "TITULAIRE").
dico("T", 9, "TOARCIENS").
dico("T", 9, "TOASTAMES").
dico("T", 9, "TOASTASSE").
dico("T", 9, "TOASTATES").
dico("T", 9, "TOASTERAI").
dico("T", 9, "TOASTERAS").
dico("T", 9, "TOASTEREZ").
dico("T", 9, "TOASTEURS").
dico("T", 9, "TOASTIONS").
dico("T", 9, "TOBOGGANS").
dico("T", 9, "TOCSONNES").
dico("T", 9, "TOGOLAISE").
dico("T", 9, "TOILAIENT").
dico("T", 9, "TOILASSES").
dico("T", 9, "TOILERAIS").
dico("T", 9, "TOILERAIT").
dico("T", 9, "TOILERENT").
dico("T", 9, "TOILERIES").
dico("T", 9, "TOILERIEZ").
dico("T", 9, "TOILERONS").
dico("T", 9, "TOILERONT").
dico("T", 9, "TOILETTAI").
dico("T", 9, "TOILETTAS").
dico("T", 9, "TOILETTAT").
dico("T", 9, "TOILETTEE").
dico("T", 9, "TOILETTER").
dico("T", 9, "TOILETTES").
dico("T", 9, "TOILETTEZ").
dico("T", 9, "TOILEUSES").
dico("T", 9, "TOILIERES").
dico("T", 9, "TOISAIENT").
dico("T", 9, "TOISASSES").
dico("T", 9, "TOISERAIS").
dico("T", 9, "TOISERAIT").
dico("T", 9, "TOISERENT").
dico("T", 9, "TOISERIEZ").
dico("T", 9, "TOISERONS").
dico("T", 9, "TOISERONT").
dico("T", 9, "TOKHARIEN").
dico("T", 9, "TOKYOITES").
dico("T", 9, "TOLASSENT").
dico("T", 9, "TOLASSIEZ").
dico("T", 9, "TOLERABLE").
dico("T", 9, "TOLERAMES").
dico("T", 9, "TOLERANCE").
dico("T", 9, "TOLERANTE").
dico("T", 9, "TOLERANTS").
dico("T", 9, "TOLERASSE").
dico("T", 9, "TOLERATES").
dico("T", 9, "TOLERERAI").
dico("T", 9, "TOLERERAS").
dico("T", 9, "TOLEREREZ").
dico("T", 9, "TOLERIONS").
dico("T", 9, "TOLETIERE").
dico("T", 9, "TOLTEQUES").
dico("T", 9, "TOLUIDINE").
dico("T", 9, "TOMAHAWKS").
dico("T", 9, "TOMAISONS").
dico("T", 9, "TOMASSENT").
dico("T", 9, "TOMASSIEZ").
dico("T", 9, "TOMBAIENT").
dico("T", 9, "TOMBANTES").
dico("T", 9, "TOMBASSES").
dico("T", 9, "TOMBELLES").
dico("T", 9, "TOMBERAIS").
dico("T", 9, "TOMBERAIT").
dico("T", 9, "TOMBEREAU").
dico("T", 9, "TOMBERENT").
dico("T", 9, "TOMBERIEZ").
dico("T", 9, "TOMBERONS").
dico("T", 9, "TOMBERONT").
dico("T", 9, "TOMBEUSES").
dico("T", 9, "TOMENTEUX").
dico("T", 9, "TOMERIONS").
dico("T", 9, "TOMIENNES").
dico("T", 9, "TOMMETTES").
dico("T", 9, "TONALITES").
dico("T", 9, "TONDAIENT").
dico("T", 9, "TONDAISON").
dico("T", 9, "TONDEUSES").
dico("T", 9, "TONDIRENT").
dico("T", 9, "TONDISSES").
dico("T", 9, "TONDRIONS").
dico("T", 9, "TONETIQUE").
dico("T", 9, "TONGRIENS").
dico("T", 9, "TONGUIENS").
dico("T", 9, "TONICITES").
dico("T", 9, "TONIFIAIS").
dico("T", 9, "TONIFIAIT").
dico("T", 9, "TONIFIANT").
dico("T", 9, "TONIFIEES").
dico("T", 9, "TONIFIENT").
dico("T", 9, "TONIFIERA").
dico("T", 9, "TONIFIIEZ").
dico("T", 9, "TONIFIONS").
dico("T", 9, "TONITRUAI").
dico("T", 9, "TONITRUAS").
dico("T", 9, "TONITRUAT").
dico("T", 9, "TONITRUER").
dico("T", 9, "TONITRUES").
dico("T", 9, "TONITRUEZ").
dico("T", 9, "TONKINOIS").
dico("T", 9, "TONNAIENT").
dico("T", 9, "TONNANTES").
dico("T", 9, "TONNASSES").
dico("T", 9, "TONNELAGE").
dico("T", 9, "TONNELETS").
dico("T", 9, "TONNELIER").
dico("T", 9, "TONNELLES").
dico("T", 9, "TONNERAIS").
dico("T", 9, "TONNERAIT").
dico("T", 9, "TONNERENT").
dico("T", 9, "TONNERIEZ").
dico("T", 9, "TONNERONS").
dico("T", 9, "TONNERONT").
dico("T", 9, "TONNERRES").
dico("T", 9, "TONOLOGIE").
dico("T", 9, "TONSURAIS").
dico("T", 9, "TONSURAIT").
dico("T", 9, "TONSURANT").
dico("T", 9, "TONSUREES").
dico("T", 9, "TONSURENT").
dico("T", 9, "TONSURERA").
dico("T", 9, "TONSURIEZ").
dico("T", 9, "TONSURONS").
dico("T", 9, "TONTINAIS").
dico("T", 9, "TONTINAIT").
dico("T", 9, "TONTINANT").
dico("T", 9, "TONTINEES").
dico("T", 9, "TONTINENT").
dico("T", 9, "TONTINERA").
dico("T", 9, "TONTINIEZ").
dico("T", 9, "TONTINONS").
dico("T", 9, "TONTISSES").
dico("T", 9, "TOPASSENT").
dico("T", 9, "TOPASSIEZ").
dico("T", 9, "TOPERIONS").
dico("T", 9, "TOPHACEES").
dico("T", 9, "TOPIAIRES").
dico("T", 9, "TOPOGUIDE").
dico("T", 9, "TOPOLOGIE").
dico("T", 9, "TOPONYMES").
dico("T", 9, "TOPONYMIE").
dico("T", 9, "TOQUAIENT").
dico("T", 9, "TOQUANTES").
dico("T", 9, "TOQUARDES").
dico("T", 9, "TOQUASSES").
dico("T", 9, "TOQUERAIS").
dico("T", 9, "TOQUERAIT").
dico("T", 9, "TOQUERENT").
dico("T", 9, "TOQUERIEZ").
dico("T", 9, "TOQUERONS").
dico("T", 9, "TOQUERONT").
dico("T", 9, "TORAILLAI").
dico("T", 9, "TORAILLAS").
dico("T", 9, "TORAILLAT").
dico("T", 9, "TORAILLER").
dico("T", 9, "TORAILLES").
dico("T", 9, "TORAILLEZ").
dico("T", 9, "TORCHAMES").
dico("T", 9, "TORCHASSE").
dico("T", 9, "TORCHATES").
dico("T", 9, "TORCHERAI").
dico("T", 9, "TORCHERAS").
dico("T", 9, "TORCHERES").
dico("T", 9, "TORCHEREZ").
dico("T", 9, "TORCHIONS").
dico("T", 9, "TORCHONNA").
dico("T", 9, "TORCHONNE").
dico("T", 9, "TORDAIENT").
dico("T", 9, "TORDANTES").
dico("T", 9, "TORDEUSES").
dico("T", 9, "TORDIRENT").
dico("T", 9, "TORDISSES").
dico("T", 9, "TORDRIONS").
dico("T", 9, "TOREADORS").
dico("T", 9, "TOREAIENT").
dico("T", 9, "TOREASSES").
dico("T", 9, "TOREERAIS").
dico("T", 9, "TOREERAIT").
dico("T", 9, "TOREERENT").
dico("T", 9, "TOREERIEZ").
dico("T", 9, "TOREERONS").
dico("T", 9, "TOREERONT").
dico("T", 9, "TORGNOLES").
dico("T", 9, "TOROIDALE").
dico("T", 9, "TOROIDAUX").
dico("T", 9, "TORONNAIS").
dico("T", 9, "TORONNAIT").
dico("T", 9, "TORONNANT").
dico("T", 9, "TORONNEES").
dico("T", 9, "TORONNENT").
dico("T", 9, "TORONNERA").
dico("T", 9, "TORONNIEZ").
dico("T", 9, "TORONNONS").
dico("T", 9, "TORONTOIS").
dico("T", 9, "TORPILLAI").
dico("T", 9, "TORPILLAS").
dico("T", 9, "TORPILLAT").
dico("T", 9, "TORPILLEE").
dico("T", 9, "TORPILLER").
dico("T", 9, "TORPILLES").
dico("T", 9, "TORPILLEZ").
dico("T", 9, "TORRAILLA").
dico("T", 9, "TORRAILLE").
dico("T", 9, "TORREFIAI").
dico("T", 9, "TORREFIAS").
dico("T", 9, "TORREFIAT").
dico("T", 9, "TORREFIEE").
dico("T", 9, "TORREFIER").
dico("T", 9, "TORREFIES").
dico("T", 9, "TORREFIEZ").
dico("T", 9, "TORSADAIS").
dico("T", 9, "TORSADAIT").
dico("T", 9, "TORSADANT").
dico("T", 9, "TORSADEES").
dico("T", 9, "TORSADENT").
dico("T", 9, "TORSADERA").
dico("T", 9, "TORSADIEZ").
dico("T", 9, "TORSADONS").
dico("T", 9, "TORTILLAI").
dico("T", 9, "TORTILLAS").
dico("T", 9, "TORTILLAT").
dico("T", 9, "TORTILLEE").
dico("T", 9, "TORTILLER").
dico("T", 9, "TORTILLES").
dico("T", 9, "TORTILLEZ").
dico("T", 9, "TORTILLON").
dico("T", 9, "TORTORAIS").
dico("T", 9, "TORTORAIT").
dico("T", 9, "TORTORANT").
dico("T", 9, "TORTOREES").
dico("T", 9, "TORTORENT").
dico("T", 9, "TORTORERA").
dico("T", 9, "TORTORIEZ").
dico("T", 9, "TORTORONS").
dico("T", 9, "TORTUEUSE").
dico("T", 9, "TORTURAIS").
dico("T", 9, "TORTURAIT").
dico("T", 9, "TORTURANT").
dico("T", 9, "TORTUREES").
dico("T", 9, "TORTURENT").
dico("T", 9, "TORTURERA").
dico("T", 9, "TORTURIEZ").
dico("T", 9, "TORTURONS").
dico("T", 9, "TOSSAIENT").
dico("T", 9, "TOSSASSES").
dico("T", 9, "TOSSERAIS").
dico("T", 9, "TOSSERAIT").
dico("T", 9, "TOSSERENT").
dico("T", 9, "TOSSERIEZ").
dico("T", 9, "TOSSERONS").
dico("T", 9, "TOSSERONT").
dico("T", 9, "TOTALISAI").
dico("T", 9, "TOTALISAS").
dico("T", 9, "TOTALISAT").
dico("T", 9, "TOTALISEE").
dico("T", 9, "TOTALISER").
dico("T", 9, "TOTALISES").
dico("T", 9, "TOTALISEZ").
dico("T", 9, "TOTALITES").
dico("T", 9, "TOTEMIQUE").
dico("T", 9, "TOTEMISME").
dico("T", 9, "TOUAILLES").
dico("T", 9, "TOUAREGUE").
dico("T", 9, "TOUASSENT").
dico("T", 9, "TOUASSIEZ").
dico("T", 9, "TOUCHABLE").
dico("T", 9, "TOUCHAMES").
dico("T", 9, "TOUCHANTE").
dico("T", 9, "TOUCHANTS").
dico("T", 9, "TOUCHASSE").
dico("T", 9, "TOUCHATES").
dico("T", 9, "TOUCHAUDS").
dico("T", 9, "TOUCHEAUX").
dico("T", 9, "TOUCHERAI").
dico("T", 9, "TOUCHERAS").
dico("T", 9, "TOUCHEREZ").
dico("T", 9, "TOUCHETTE").
dico("T", 9, "TOUCHEURS").
dico("T", 9, "TOUCHEUSE").
dico("T", 9, "TOUCHIONS").
dico("T", 9, "TOUERIONS").
dico("T", 9, "TOUFFEURS").
dico("T", 9, "TOUILLAGE").
dico("T", 9, "TOUILLAIS").
dico("T", 9, "TOUILLAIT").
dico("T", 9, "TOUILLANT").
dico("T", 9, "TOUILLEES").
dico("T", 9, "TOUILLENT").
dico("T", 9, "TOUILLERA").
dico("T", 9, "TOUILLEUR").
dico("T", 9, "TOUILLIEZ").
dico("T", 9, "TOUILLONS").
dico("T", 9, "TOULOUPES").
dico("T", 9, "TOUNGOUSE").
dico("T", 9, "TOUNGOUZE").
dico("T", 9, "TOUPILLAI").
dico("T", 9, "TOUPILLAS").
dico("T", 9, "TOUPILLAT").
dico("T", 9, "TOUPILLEE").
dico("T", 9, "TOUPILLER").
dico("T", 9, "TOUPILLES").
dico("T", 9, "TOUPILLEZ").
dico("T", 9, "TOUPILLON").
dico("T", 9, "TOUPINAIS").
dico("T", 9, "TOUPINAIT").
dico("T", 9, "TOUPINANT").
dico("T", 9, "TOUPINENT").
dico("T", 9, "TOUPINERA").
dico("T", 9, "TOUPINIEZ").
dico("T", 9, "TOUPINONS").
dico("T", 9, "TOURAILLE").
dico("T", 9, "TOURAINES").
dico("T", 9, "TOURANIEN").
dico("T", 9, "TOURBAMES").
dico("T", 9, "TOURBASSE").
dico("T", 9, "TOURBATES").
dico("T", 9, "TOURBERAI").
dico("T", 9, "TOURBERAS").
dico("T", 9, "TOURBEREZ").
dico("T", 9, "TOURBEUSE").
dico("T", 9, "TOURBIERE").
dico("T", 9, "TOURBIERS").
dico("T", 9, "TOURBIONS").
dico("T", 9, "TOURDILLE").
dico("T", 9, "TOURELLES").
dico("T", 9, "TOURIERES").
dico("T", 9, "TOURILLON").
dico("T", 9, "TOURISMES").
dico("T", 9, "TOURISTES").
dico("T", 9, "TOURMENTA").
dico("T", 9, "TOURMENTE").
dico("T", 9, "TOURMENTS").
dico("T", 9, "TOURNAGES").
dico("T", 9, "TOURNAMES").
dico("T", 9, "TOURNANTE").
dico("T", 9, "TOURNANTS").
dico("T", 9, "TOURNASSE").
dico("T", 9, "TOURNATES").
dico("T", 9, "TOURNEDOS").
dico("T", 9, "TOURNERAI").
dico("T", 9, "TOURNERAS").
dico("T", 9, "TOURNEREZ").
dico("T", 9, "TOURNERIE").
dico("T", 9, "TOURNESOL").
dico("T", 9, "TOURNETTE").
dico("T", 9, "TOURNEURS").
dico("T", 9, "TOURNEUSE").
dico("T", 9, "TOURNEVIS").
dico("T", 9, "TOURNIOLE").
dico("T", 9, "TOURNIONS").
dico("T", 9, "TOURNIQUA").
dico("T", 9, "TOURNIQUE").
dico("T", 9, "TOURNISSE").
dico("T", 9, "TOURNOIES").
dico("T", 9, "TOURNOYAI").
dico("T", 9, "TOURNOYAS").
dico("T", 9, "TOURNOYAT").
dico("T", 9, "TOURNOYER").
dico("T", 9, "TOURNOYEZ").
dico("T", 9, "TOURNURES").
dico("T", 9, "TOURTEAUX").
dico("T", 9, "TOURTIERE").
dico("T", 9, "TOUSELLES").
dico("T", 9, "TOUSSAINT").
dico("T", 9, "TOUSSAMES").
dico("T", 9, "TOUSSASSE").
dico("T", 9, "TOUSSATES").
dico("T", 9, "TOUSSERAI").
dico("T", 9, "TOUSSERAS").
dico("T", 9, "TOUSSEREZ").
dico("T", 9, "TOUSSERIE").
dico("T", 9, "TOUSSEURS").
dico("T", 9, "TOUSSEUSE").
dico("T", 9, "TOUSSIONS").
dico("T", 9, "TOUSSOTAI").
dico("T", 9, "TOUSSOTAS").
dico("T", 9, "TOUSSOTAT").
dico("T", 9, "TOUSSOTER").
dico("T", 9, "TOUSSOTES").
dico("T", 9, "TOUSSOTEZ").
dico("T", 9, "TOUTEFOIS").
dico("T", 9, "TOWNSHIPS").
dico("T", 9, "TOXEMIQUE").
dico("T", 9, "TOXICITES").
dico("T", 9, "TOXICOSES").
dico("T", 9, "TRABENDOS").
dico("T", 9, "TRABOULAI").
dico("T", 9, "TRABOULAS").
dico("T", 9, "TRABOULAT").
dico("T", 9, "TRABOULER").
dico("T", 9, "TRABOULES").
dico("T", 9, "TRABOULEZ").
dico("T", 9, "TRACAIENT").
dico("T", 9, "TRACANTES").
dico("T", 9, "TRACASSAI").
dico("T", 9, "TRACASSAS").
dico("T", 9, "TRACASSAT").
dico("T", 9, "TRACASSEE").
dico("T", 9, "TRACASSER").
dico("T", 9, "TRACASSES").
dico("T", 9, "TRACASSEZ").
dico("T", 9, "TRACASSIN").
dico("T", 9, "TRACELETS").
dico("T", 9, "TRACEMENT").
dico("T", 9, "TRACERAIS").
dico("T", 9, "TRACERAIT").
dico("T", 9, "TRACERENT").
dico("T", 9, "TRACERETS").
dico("T", 9, "TRACERIEZ").
dico("T", 9, "TRACERONS").
dico("T", 9, "TRACERONT").
dico("T", 9, "TRACEUSES").
dico("T", 9, "TRACHEALE").
dico("T", 9, "TRACHEAUX").
dico("T", 9, "TRACHEENS").
dico("T", 9, "TRACHEIDE").
dico("T", 9, "TRACHEITE").
dico("T", 9, "TRACHOMES").
dico("T", 9, "TRACHYTES").
dico("T", 9, "TRACTABLE").
dico("T", 9, "TRACTAGES").
dico("T", 9, "TRACTAMES").
dico("T", 9, "TRACTASSE").
dico("T", 9, "TRACTATES").
dico("T", 9, "TRACTERAI").
dico("T", 9, "TRACTERAS").
dico("T", 9, "TRACTEREZ").
dico("T", 9, "TRACTEURS").
dico("T", 9, "TRACTIONS").
dico("T", 9, "TRACTIVES").
dico("T", 9, "TRACTRICE").
dico("T", 9, "TRADITEUR").
dico("T", 9, "TRADITION").
dico("T", 9, "TRADUIRAI").
dico("T", 9, "TRADUIRAS").
dico("T", 9, "TRADUIREZ").
dico("T", 9, "TRADUISES").
dico("T", 9, "TRADUISEZ").
dico("T", 9, "TRADUISIS").
dico("T", 9, "TRADUISIT").
dico("T", 9, "TRADUITES").
dico("T", 9, "TRAFALGAR").
dico("T", 9, "TRAFICOTA").
dico("T", 9, "TRAFICOTE").
dico("T", 9, "TRAFIQUAI").
dico("T", 9, "TRAFIQUAS").
dico("T", 9, "TRAFIQUAT").
dico("T", 9, "TRAFIQUEE").
dico("T", 9, "TRAFIQUER").
dico("T", 9, "TRAFIQUES").
dico("T", 9, "TRAFIQUEZ").
dico("T", 9, "TRAGEDIEN").
dico("T", 9, "TRAGEDIES").
dico("T", 9, "TRAGIQUES").
dico("T", 9, "TRAHIRAIS").
dico("T", 9, "TRAHIRAIT").
dico("T", 9, "TRAHIRENT").
dico("T", 9, "TRAHIRIEZ").
dico("T", 9, "TRAHIRONS").
dico("T", 9, "TRAHIRONT").
dico("T", 9, "TRAHISONS").
dico("T", 9, "TRAHISSES").
dico("T", 9, "TRAHISSEZ").
dico("T", 9, "TRAINAGES").
dico("T", 9, "TRAINAMES").
dico("T", 9, "TRAINANTE").
dico("T", 9, "TRAINANTS").
dico("T", 9, "TRAINARDE").
dico("T", 9, "TRAINARDS").
dico("T", 9, "TRAINASSA").
dico("T", 9, "TRAINASSE").
dico("T", 9, "TRAINATES").
dico("T", 9, "TRAINEAUX").
dico("T", 9, "TRAINERAI").
dico("T", 9, "TRAINERAS").
dico("T", 9, "TRAINEREZ").
dico("T", 9, "TRAINERIE").
dico("T", 9, "TRAINEURS").
dico("T", 9, "TRAINEUSE").
dico("T", 9, "TRAINGLOT").
dico("T", 9, "TRAININGS").
dico("T", 9, "TRAINIONS").
dico("T", 9, "TRAIRIONS").
dico("T", 9, "TRAITABLE").
dico("T", 9, "TRAITAMES").
dico("T", 9, "TRAITANTE").
dico("T", 9, "TRAITANTS").
dico("T", 9, "TRAITASSE").
dico("T", 9, "TRAITATES").
dico("T", 9, "TRAITERAI").
dico("T", 9, "TRAITERAS").
dico("T", 9, "TRAITEREZ").
dico("T", 9, "TRAITEURS").
dico("T", 9, "TRAITIONS").
dico("T", 9, "TRAITRISE").
dico("T", 9, "TRALUIMES").
dico("T", 9, "TRALUIRAI").
dico("T", 9, "TRALUIRAS").
dico("T", 9, "TRALUIREZ").
dico("T", 9, "TRALUISES").
dico("T", 9, "TRALUISEZ").
dico("T", 9, "TRALUISIS").
dico("T", 9, "TRALUISIT").
dico("T", 9, "TRALUITES").
dico("T", 9, "TRAMAIENT").
dico("T", 9, "TRAMASSES").
dico("T", 9, "TRAMELOTS").
dico("T", 9, "TRAMERAIS").
dico("T", 9, "TRAMERAIT").
dico("T", 9, "TRAMERENT").
dico("T", 9, "TRAMERIEZ").
dico("T", 9, "TRAMERONS").
dico("T", 9, "TRAMERONT").
dico("T", 9, "TRAMEUSES").
dico("T", 9, "TRAMINERS").
dico("T", 9, "TRAMINOTS").
dico("T", 9, "TRAMPINGS").
dico("T", 9, "TRANCHAGE").
dico("T", 9, "TRANCHAIS").
dico("T", 9, "TRANCHAIT").
dico("T", 9, "TRANCHANT").
dico("T", 9, "TRANCHEES").
dico("T", 9, "TRANCHENT").
dico("T", 9, "TRANCHERA").
dico("T", 9, "TRANCHETS").
dico("T", 9, "TRANCHEUR").
dico("T", 9, "TRANCHIEZ").
dico("T", 9, "TRANCHOIR").
dico("T", 9, "TRANCHONS").
dico("T", 9, "TRANSCODA").
dico("T", 9, "TRANSCODE").
dico("T", 9, "TRANSCRIS").
dico("T", 9, "TRANSCRIT").
dico("T", 9, "TRANSEPTS").
dico("T", 9, "TRANSFERA").
dico("T", 9, "TRANSFERE").
dico("T", 9, "TRANSFERT").
dico("T", 9, "TRANSFILA").
dico("T", 9, "TRANSFILE").
dico("T", 9, "TRANSFINI").
dico("T", 9, "TRANSFUGE").
dico("T", 9, "TRANSFUSA").
dico("T", 9, "TRANSFUSE").
dico("T", 9, "TRANSGENE").
dico("T", 9, "TRANSHUMA").
dico("T", 9, "TRANSHUME").
dico("T", 9, "TRANSIGEA").
dico("T", 9, "TRANSIGER").
dico("T", 9, "TRANSIGES").
dico("T", 9, "TRANSIGEZ").
dico("T", 9, "TRANSIMES").
dico("T", 9, "TRANSIRAI").
dico("T", 9, "TRANSIRAS").
dico("T", 9, "TRANSIREZ").
dico("T", 9, "TRANSISSE").
dico("T", 9, "TRANSITAI").
dico("T", 9, "TRANSITAS").
dico("T", 9, "TRANSITAT").
dico("T", 9, "TRANSITEE").
dico("T", 9, "TRANSITER").
dico("T", 9, "TRANSITES").
dico("T", 9, "TRANSITEZ").
dico("T", 9, "TRANSITIF").
dico("T", 9, "TRANSLATA").
dico("T", 9, "TRANSLATE").
dico("T", 9, "TRANSMETS").
dico("T", 9, "TRANSMISE").
dico("T", 9, "TRANSMUAI").
dico("T", 9, "TRANSMUAS").
dico("T", 9, "TRANSMUAT").
dico("T", 9, "TRANSMUEE").
dico("T", 9, "TRANSMUER").
dico("T", 9, "TRANSMUES").
dico("T", 9, "TRANSMUEZ").
dico("T", 9, "TRANSMUTA").
dico("T", 9, "TRANSMUTE").
dico("T", 9, "TRANSPARU").
dico("T", 9, "TRANSPIRA").
dico("T", 9, "TRANSPIRE").
dico("T", 9, "TRANSPORT").
dico("T", 9, "TRANSPOSA").
dico("T", 9, "TRANSPOSE").
dico("T", 9, "TRANSSUDA").
dico("T", 9, "TRANSSUDE").
dico("T", 9, "TRANSVASA").
dico("T", 9, "TRANSVASE").
dico("T", 9, "TRANSVIDA").
dico("T", 9, "TRANSVIDE").
dico("T", 9, "TRANTRANS").
dico("T", 9, "TRAPILLON").
dico("T", 9, "TRAPPAMES").
dico("T", 9, "TRAPPASSE").
dico("T", 9, "TRAPPATES").
dico("T", 9, "TRAPPERAI").
dico("T", 9, "TRAPPERAS").
dico("T", 9, "TRAPPEREZ").
dico("T", 9, "TRAPPEURS").
dico("T", 9, "TRAPPIONS").
dico("T", 9, "TRAPPISTE").
dico("T", 9, "TRAQUAMES").
dico("T", 9, "TRAQUASSE").
dico("T", 9, "TRAQUATES").
dico("T", 9, "TRAQUELET").
dico("T", 9, "TRAQUERAI").
dico("T", 9, "TRAQUERAS").
dico("T", 9, "TRAQUEREZ").
dico("T", 9, "TRAQUEURS").
dico("T", 9, "TRAQUEUSE").
dico("T", 9, "TRAQUIONS").
dico("T", 9, "TRATTORIA").
dico("T", 9, "TRAVAILLA").
dico("T", 9, "TRAVAILLE").
dico("T", 9, "TRAVELAGE").
dico("T", 9, "TRAVELING").
dico("T", 9, "TRAVELLER").
dico("T", 9, "TRAVERSAI").
dico("T", 9, "TRAVERSAS").
dico("T", 9, "TRAVERSAT").
dico("T", 9, "TRAVERSEE").
dico("T", 9, "TRAVERSER").
dico("T", 9, "TRAVERSES").
dico("T", 9, "TRAVERSEZ").
dico("T", 9, "TRAVERSIN").
dico("T", 9, "TRAVERTIN").
dico("T", 9, "TRAVESTIE").
dico("T", 9, "TRAVESTIR").
dico("T", 9, "TRAVESTIS").
dico("T", 9, "TRAVESTIT").
dico("T", 9, "TRAYAIENT").
dico("T", 9, "TRAYEUSES").
dico("T", 9, "TREBUCHAI").
dico("T", 9, "TREBUCHAS").
dico("T", 9, "TREBUCHAT").
dico("T", 9, "TREBUCHEE").
dico("T", 9, "TREBUCHER").
dico("T", 9, "TREBUCHES").
dico("T", 9, "TREBUCHET").
dico("T", 9, "TREBUCHEZ").
dico("T", 9, "TRECHEURS").
dico("T", 9, "TREFILAGE").
dico("T", 9, "TREFILAIS").
dico("T", 9, "TREFILAIT").
dico("T", 9, "TREFILANT").
dico("T", 9, "TREFILEES").
dico("T", 9, "TREFILENT").
dico("T", 9, "TREFILERA").
dico("T", 9, "TREFILEUR").
dico("T", 9, "TREFILIEZ").
dico("T", 9, "TREFILONS").
dico("T", 9, "TREFLERIE").
dico("T", 9, "TREFLIERE").
dico("T", 9, "TREGOROIS").
dico("T", 9, "TREHALOSE").
dico("T", 9, "TREILLAGE").
dico("T", 9, "TREIZIEME").
dico("T", 9, "TREIZISTE").
dico("T", 9, "TREKKEURS").
dico("T", 9, "TREKKEUSE").
dico("T", 9, "TREKKINGS").
dico("T", 9, "TREMATAGE").
dico("T", 9, "TREMATAIS").
dico("T", 9, "TREMATAIT").
dico("T", 9, "TREMATANT").
dico("T", 9, "TREMATEES").
dico("T", 9, "TREMATENT").
dico("T", 9, "TREMATERA").
dico("T", 9, "TREMATIEZ").
dico("T", 9, "TREMATODE").
dico("T", 9, "TREMATONS").
dico("T", 9, "TREMBLAIE").
dico("T", 9, "TREMBLAIS").
dico("T", 9, "TREMBLAIT").
dico("T", 9, "TREMBLANT").
dico("T", 9, "TREMBLEES").
dico("T", 9, "TREMBLENT").
dico("T", 9, "TREMBLERA").
dico("T", 9, "TREMBLEUR").
dico("T", 9, "TREMBLIEZ").
dico("T", 9, "TREMBLONS").
dico("T", 9, "TREMBLOTA").
dico("T", 9, "TREMBLOTE").
dico("T", 9, "TREMELLES").
dico("T", 9, "TREMIERES").
dico("T", 9, "TREMOLITE").
dico("T", 9, "TREMOUSSA").
dico("T", 9, "TREMOUSSE").
dico("T", 9, "TREMPAGES").
dico("T", 9, "TREMPAMES").
dico("T", 9, "TREMPASSE").
dico("T", 9, "TREMPATES").
dico("T", 9, "TREMPERAI").
dico("T", 9, "TREMPERAS").
dico("T", 9, "TREMPEREZ").
dico("T", 9, "TREMPETTE").
dico("T", 9, "TREMPEURS").
dico("T", 9, "TREMPIONS").
dico("T", 9, "TREMPLINS").
dico("T", 9, "TREMULAIS").
dico("T", 9, "TREMULAIT").
dico("T", 9, "TREMULANT").
dico("T", 9, "TREMULEES").
dico("T", 9, "TREMULENT").
dico("T", 9, "TREMULERA").
dico("T", 9, "TREMULIEZ").
dico("T", 9, "TREMULONS").
dico("T", 9, "TRENTAINE").
dico("T", 9, "TRENTAINS").
dico("T", 9, "TRENTIEME").
dico("T", 9, "TREPANAIS").
dico("T", 9, "TREPANAIT").
dico("T", 9, "TREPANANT").
dico("T", 9, "TREPANEES").
dico("T", 9, "TREPANENT").
dico("T", 9, "TREPANERA").
dico("T", 9, "TREPANIEZ").
dico("T", 9, "TREPANONS").
dico("T", 9, "TREPASSAI").
dico("T", 9, "TREPASSAS").
dico("T", 9, "TREPASSAT").
dico("T", 9, "TREPASSEE").
dico("T", 9, "TREPASSER").
dico("T", 9, "TREPASSES").
dico("T", 9, "TREPASSEZ").
dico("T", 9, "TREPHONES").
dico("T", 9, "TREPIDAIS").
dico("T", 9, "TREPIDAIT").
dico("T", 9, "TREPIDANT").
dico("T", 9, "TREPIDENT").
dico("T", 9, "TREPIDERA").
dico("T", 9, "TREPIDIEZ").
dico("T", 9, "TREPIDONS").
dico("T", 9, "TREPIGNAI").
dico("T", 9, "TREPIGNAS").
dico("T", 9, "TREPIGNAT").
dico("T", 9, "TREPIGNEE").
dico("T", 9, "TREPIGNER").
dico("T", 9, "TREPIGNES").
dico("T", 9, "TREPIGNEZ").
dico("T", 9, "TREPOINTE").
dico("T", 9, "TREPONEME").
dico("T", 9, "TRESAILLE").
dico("T", 9, "TRESCHEUR").
dico("T", 9, "TRESORIER").
dico("T", 9, "TRESSAGES").
dico("T", 9, "TRESSAMES").
dico("T", 9, "TRESSASSE").
dico("T", 9, "TRESSATES").
dico("T", 9, "TRESSAUTA").
dico("T", 9, "TRESSAUTE").
dico("T", 9, "TRESSERAI").
dico("T", 9, "TRESSERAS").
dico("T", 9, "TRESSEREZ").
dico("T", 9, "TRESSEURS").
dico("T", 9, "TRESSEUSE").
dico("T", 9, "TRESSIONS").
dico("T", 9, "TREUILLAI").
dico("T", 9, "TREUILLAS").
dico("T", 9, "TREUILLAT").
dico("T", 9, "TREUILLEE").
dico("T", 9, "TREUILLER").
dico("T", 9, "TREUILLES").
dico("T", 9, "TREUILLEZ").
dico("T", 9, "TREVIRAIS").
dico("T", 9, "TREVIRAIT").
dico("T", 9, "TREVIRANT").
dico("T", 9, "TREVIREES").
dico("T", 9, "TREVIRENT").
dico("T", 9, "TREVIRERA").
dico("T", 9, "TREVIRIEZ").
dico("T", 9, "TREVIRONS").
dico("T", 9, "TREVISANE").
dico("T", 9, "TREVISANS").
dico("T", 9, "TRIACIDES").
dico("T", 9, "TRIADIQUE").
dico("T", 9, "TRIALCOOL").
dico("T", 9, "TRIALISTE").
dico("T", 9, "TRIANDINE").
dico("T", 9, "TRIANDRIE").
dico("T", 9, "TRIANGLES").
dico("T", 9, "TRIANGULA").
dico("T", 9, "TRIANGULE").
dico("T", 9, "TRIASIQUE").
dico("T", 9, "TRIASSENT").
dico("T", 9, "TRIASSIEZ").
dico("T", 9, "TRIATHLON").
dico("T", 9, "TRIBALLAI").
dico("T", 9, "TRIBALLAS").
dico("T", 9, "TRIBALLAT").
dico("T", 9, "TRIBALLEE").
dico("T", 9, "TRIBALLER").
dico("T", 9, "TRIBALLES").
dico("T", 9, "TRIBALLEZ").
dico("T", 9, "TRIBOULET").
dico("T", 9, "TRIBRAQUE").
dico("T", 9, "TRIBUNATS").
dico("T", 9, "TRIBUNAUX").
dico("T", 9, "TRICARDES").
dico("T", 9, "TRICENNAL").
dico("T", 9, "TRICHAMES").
dico("T", 9, "TRICHASSE").
dico("T", 9, "TRICHATES").
dico("T", 9, "TRICHERAI").
dico("T", 9, "TRICHERAS").
dico("T", 9, "TRICHEREZ").
dico("T", 9, "TRICHERIE").
dico("T", 9, "TRICHEURS").
dico("T", 9, "TRICHEUSE").
dico("T", 9, "TRICHINEE").
dico("T", 9, "TRICHINES").
dico("T", 9, "TRICHIONS").
dico("T", 9, "TRICHITES").
dico("T", 9, "TRICHOMAS").
dico("T", 9, "TRICHOMES").
dico("T", 9, "TRICHROME").
dico("T", 9, "TRICKSTER").
dico("T", 9, "TRICOISES").
dico("T", 9, "TRICOLORE").
dico("T", 9, "TRICORNES").
dico("T", 9, "TRICOTAGE").
dico("T", 9, "TRICOTAIS").
dico("T", 9, "TRICOTAIT").
dico("T", 9, "TRICOTANT").
dico("T", 9, "TRICOTEES").
dico("T", 9, "TRICOTENT").
dico("T", 9, "TRICOTERA").
dico("T", 9, "TRICOTETS").
dico("T", 9, "TRICOTEUR").
dico("T", 9, "TRICOTIEZ").
dico("T", 9, "TRICOTONS").
dico("T", 9, "TRICOUNIS").
dico("T", 9, "TRICTRACS").
dico("T", 9, "TRICYCLES").
dico("T", 9, "TRIDACNES").
dico("T", 9, "TRIDENTEE").
dico("T", 9, "TRIDENTES").
dico("T", 9, "TRIENNALE").
dico("T", 9, "TRIENNATS").
dico("T", 9, "TRIENNAUX").
dico("T", 9, "TRIERIONS").
dico("T", 9, "TRIESTERS").
dico("T", 9, "TRIESTINE").
dico("T", 9, "TRIESTINS").
dico("T", 9, "TRIFOLIEE").
dico("T", 9, "TRIFOLIES").
dico("T", 9, "TRIFOLIUM").
dico("T", 9, "TRIFORIUM").
dico("T", 9, "TRIGEMINE").
dico("T", 9, "TRIGLYPHE").
dico("T", 9, "TRIGRAMME").
dico("T", 9, "TRIJUMEAU").
dico("T", 9, "TRILINGUE").
dico("T", 9, "TRILITERE").
dico("T", 9, "TRILLAMES").
dico("T", 9, "TRILLASSE").
dico("T", 9, "TRILLATES").
dico("T", 9, "TRILLERAI").
dico("T", 9, "TRILLERAS").
dico("T", 9, "TRILLEREZ").
dico("T", 9, "TRILLIONS").
dico("T", 9, "TRILOBEES").
dico("T", 9, "TRILOBITE").
dico("T", 9, "TRILOGIES").
dico("T", 9, "TRIMAIENT").
dico("T", 9, "TRIMARANS").
dico("T", 9, "TRIMARDAI").
dico("T", 9, "TRIMARDAS").
dico("T", 9, "TRIMARDAT").
dico("T", 9, "TRIMARDER").
dico("T", 9, "TRIMARDES").
dico("T", 9, "TRIMARDEZ").
dico("T", 9, "TRIMASSES").
dico("T", 9, "TRIMBALAI").
dico("T", 9, "TRIMBALAS").
dico("T", 9, "TRIMBALAT").
dico("T", 9, "TRIMBALEE").
dico("T", 9, "TRIMBALER").
dico("T", 9, "TRIMBALES").
dico("T", 9, "TRIMBALEZ").
dico("T", 9, "TRIMBALLA").
dico("T", 9, "TRIMBALLE").
dico("T", 9, "TRIMERAIS").
dico("T", 9, "TRIMERAIT").
dico("T", 9, "TRIMERENT").
dico("T", 9, "TRIMERIEZ").
dico("T", 9, "TRIMERONS").
dico("T", 9, "TRIMERONT").
dico("T", 9, "TRIMESTRE").
dico("T", 9, "TRIMETAUX").
dico("T", 9, "TRIMETRES").
dico("T", 9, "TRIMEUSES").
dico("T", 9, "TRIMOTEUR").
dico("T", 9, "TRINERVEE").
dico("T", 9, "TRINERVES").
dico("T", 9, "TRINGLAIS").
dico("T", 9, "TRINGLAIT").
dico("T", 9, "TRINGLANT").
dico("T", 9, "TRINGLEES").
dico("T", 9, "TRINGLENT").
dico("T", 9, "TRINGLERA").
dico("T", 9, "TRINGLIEZ").
dico("T", 9, "TRINGLONS").
dico("T", 9, "TRINGLOTS").
dico("T", 9, "TRINQUAIS").
dico("T", 9, "TRINQUAIT").
dico("T", 9, "TRINQUANT").
dico("T", 9, "TRINQUART").
dico("T", 9, "TRINQUENT").
dico("T", 9, "TRINQUERA").
dico("T", 9, "TRINQUETS").
dico("T", 9, "TRINQUEUR").
dico("T", 9, "TRINQUIEZ").
dico("T", 9, "TRINQUONS").
dico("T", 9, "TRIOLISME").
dico("T", 9, "TRIOMPHAI").
dico("T", 9, "TRIOMPHAL").
dico("T", 9, "TRIOMPHAS").
dico("T", 9, "TRIOMPHAT").
dico("T", 9, "TRIOMPHER").
dico("T", 9, "TRIOMPHES").
dico("T", 9, "TRIOMPHEZ").
dico("T", 9, "TRIPAILLE").
dico("T", 9, "TRIPANTES").
dico("T", 9, "TRIPARTIE").
dico("T", 9, "TRIPARTIS").
dico("T", 9, "TRIPERIES").
dico("T", 9, "TRIPETTES").
dico("T", 9, "TRIPHASEE").
dico("T", 9, "TRIPHASES").
dico("T", 9, "TRIPIERES").
dico("T", 9, "TRIPLACES").
dico("T", 9, "TRIPLAMES").
dico("T", 9, "TRIPLASSE").
dico("T", 9, "TRIPLATES").
dico("T", 9, "TRIPLERAI").
dico("T", 9, "TRIPLERAS").
dico("T", 9, "TRIPLEREZ").
dico("T", 9, "TRIPLETTE").
dico("T", 9, "TRIPLIONS").
dico("T", 9, "TRIPLOIDE").
dico("T", 9, "TRIPLURES").
dico("T", 9, "TRIPODIES").
dico("T", 9, "TRIPOTAGE").
dico("T", 9, "TRIPOTAIS").
dico("T", 9, "TRIPOTAIT").
dico("T", 9, "TRIPOTANT").
dico("T", 9, "TRIPOTEES").
dico("T", 9, "TRIPOTENT").
dico("T", 9, "TRIPOTERA").
dico("T", 9, "TRIPOTEUR").
dico("T", 9, "TRIPOTIEZ").
dico("T", 9, "TRIPOTONS").
dico("T", 9, "TRIPTYQUE").
dico("T", 9, "TRIQUAMES").
dico("T", 9, "TRIQUARDE").
dico("T", 9, "TRIQUARDS").
dico("T", 9, "TRIQUASSE").
dico("T", 9, "TRIQUATES").
dico("T", 9, "TRIQUERAI").
dico("T", 9, "TRIQUERAS").
dico("T", 9, "TRIQUEREZ").
dico("T", 9, "TRIQUETRE").
dico("T", 9, "TRIQUIONS").
dico("T", 9, "TRIREGNES").
dico("T", 9, "TRISAIEUL").
dico("T", 9, "TRISCELES").
dico("T", 9, "TRISKELES").
dico("T", 9, "TRISMIQUE").
dico("T", 9, "TRISOMIES").
dico("T", 9, "TRISSAMES").
dico("T", 9, "TRISSASSE").
dico("T", 9, "TRISSATES").
dico("T", 9, "TRISSERAI").
dico("T", 9, "TRISSERAS").
dico("T", 9, "TRISSEREZ").
dico("T", 9, "TRISSIONS").
dico("T", 9, "TRISTESSE").
dico("T", 9, "TRITICALE").
dico("T", 9, "TRITURAIS").
dico("T", 9, "TRITURAIT").
dico("T", 9, "TRITURANT").
dico("T", 9, "TRITUREES").
dico("T", 9, "TRITURENT").
dico("T", 9, "TRITURERA").
dico("T", 9, "TRITURIEZ").
dico("T", 9, "TRITURONS").
dico("T", 9, "TRIUMVIRS").
dico("T", 9, "TRIVALENT").
dico("T", 9, "TRIVALVES").
dico("T", 9, "TRIVIALES").
dico("T", 9, "TROCHILES").
dico("T", 9, "TROCHITER").
dico("T", 9, "TROCHLEEN").
dico("T", 9, "TROCHLEES").
dico("T", 9, "TROCHURES").
dico("T", 9, "TROGLOBIE").
dico("T", 9, "TROGONIDE").
dico("T", 9, "TROISIEME").
dico("T", 9, "TROMBINES").
dico("T", 9, "TROMBLONS").
dico("T", 9, "TROMBONES").
dico("T", 9, "TROMPAMES").
dico("T", 9, "TROMPASSE").
dico("T", 9, "TROMPATES").
dico("T", 9, "TROMPERAI").
dico("T", 9, "TROMPERAS").
dico("T", 9, "TROMPEREZ").
dico("T", 9, "TROMPERIE").
dico("T", 9, "TROMPETAI").
dico("T", 9, "TROMPETAS").
dico("T", 9, "TROMPETAT").
dico("T", 9, "TROMPETEE").
dico("T", 9, "TROMPETER").
dico("T", 9, "TROMPETES").
dico("T", 9, "TROMPETEZ").
dico("T", 9, "TROMPETTE").
dico("T", 9, "TROMPEURS").
dico("T", 9, "TROMPEUSE").
dico("T", 9, "TROMPIONS").
dico("T", 9, "TRONAIENT").
dico("T", 9, "TRONASSES").
dico("T", 9, "TRONCHETS").
dico("T", 9, "TRONCONNA").
dico("T", 9, "TRONCONNE").
dico("T", 9, "TRONERAIS").
dico("T", 9, "TRONERAIT").
dico("T", 9, "TRONERENT").
dico("T", 9, "TRONERIEZ").
dico("T", 9, "TRONERONS").
dico("T", 9, "TRONERONT").
dico("T", 9, "TRONQUAIS").
dico("T", 9, "TRONQUAIT").
dico("T", 9, "TRONQUANT").
dico("T", 9, "TRONQUEES").
dico("T", 9, "TRONQUENT").
dico("T", 9, "TRONQUERA").
dico("T", 9, "TRONQUIEZ").
dico("T", 9, "TRONQUONS").
dico("T", 9, "TROPEZIEN").
dico("T", 9, "TROPHIQUE").
dico("T", 9, "TROPICALE").
dico("T", 9, "TROPICAUX").
dico("T", 9, "TROPIQUES").
dico("T", 9, "TROPISMES").
dico("T", 9, "TROQUAMES").
dico("T", 9, "TROQUASSE").
dico("T", 9, "TROQUATES").
dico("T", 9, "TROQUERAI").
dico("T", 9, "TROQUERAS").
dico("T", 9, "TROQUEREZ").
dico("T", 9, "TROQUEURS").
dico("T", 9, "TROQUEUSE").
dico("T", 9, "TROQUIONS").
dico("T", 9, "TROTTAMES").
dico("T", 9, "TROTTASSE").
dico("T", 9, "TROTTATES").
dico("T", 9, "TROTTERAI").
dico("T", 9, "TROTTERAS").
dico("T", 9, "TROTTEREZ").
dico("T", 9, "TROTTEURS").
dico("T", 9, "TROTTEUSE").
dico("T", 9, "TROTTINAI").
dico("T", 9, "TROTTINAS").
dico("T", 9, "TROTTINAT").
dico("T", 9, "TROTTINER").
dico("T", 9, "TROTTINES").
dico("T", 9, "TROTTINEZ").
dico("T", 9, "TROTTINGS").
dico("T", 9, "TROTTIONS").
dico("T", 9, "TROTTOIRS").
dico("T", 9, "TROUAIENT").
dico("T", 9, "TROUASSES").
dico("T", 9, "TROUBADES").
dico("T", 9, "TROUBLAIS").
dico("T", 9, "TROUBLAIT").
dico("T", 9, "TROUBLANT").
dico("T", 9, "TROUBLEAU").
dico("T", 9, "TROUBLEES").
dico("T", 9, "TROUBLENT").
dico("T", 9, "TROUBLERA").
dico("T", 9, "TROUBLIEZ").
dico("T", 9, "TROUBLONS").
dico("T", 9, "TROUERAIS").
dico("T", 9, "TROUERAIT").
dico("T", 9, "TROUERENT").
dico("T", 9, "TROUERIEZ").
dico("T", 9, "TROUERONS").
dico("T", 9, "TROUERONT").
dico("T", 9, "TROUFIONS").
dico("T", 9, "TROUILLAI").
dico("T", 9, "TROUILLAS").
dico("T", 9, "TROUILLAT").
dico("T", 9, "TROUILLER").
dico("T", 9, "TROUILLES").
dico("T", 9, "TROUILLEZ").
dico("T", 9, "TROUPEAUX").
dico("T", 9, "TROUPIALE").
dico("T", 9, "TROUPIERS").
dico("T", 9, "TROUSSAGE").
dico("T", 9, "TROUSSAIS").
dico("T", 9, "TROUSSAIT").
dico("T", 9, "TROUSSANT").
dico("T", 9, "TROUSSEAU").
dico("T", 9, "TROUSSEES").
dico("T", 9, "TROUSSENT").
dico("T", 9, "TROUSSERA").
dico("T", 9, "TROUSSEUR").
dico("T", 9, "TROUSSIEZ").
dico("T", 9, "TROUSSONS").
dico("T", 9, "TROUVABLE").
dico("T", 9, "TROUVAMES").
dico("T", 9, "TROUVASSE").
dico("T", 9, "TROUVATES").
dico("T", 9, "TROUVERAI").
dico("T", 9, "TROUVERAS").
dico("T", 9, "TROUVERES").
dico("T", 9, "TROUVEREZ").
dico("T", 9, "TROUVEURS").
dico("T", 9, "TROUVEUSE").
dico("T", 9, "TROUVIONS").
dico("T", 9, "TROYENNES").
dico("T", 9, "TRUANDAIS").
dico("T", 9, "TRUANDAIT").
dico("T", 9, "TRUANDANT").
dico("T", 9, "TRUANDEES").
dico("T", 9, "TRUANDENT").
dico("T", 9, "TRUANDERA").
dico("T", 9, "TRUANDIEZ").
dico("T", 9, "TRUANDONS").
dico("T", 9, "TRUBLIONS").
dico("T", 9, "TRUCIDAIS").
dico("T", 9, "TRUCIDAIT").
dico("T", 9, "TRUCIDANT").
dico("T", 9, "TRUCIDEES").
dico("T", 9, "TRUCIDENT").
dico("T", 9, "TRUCIDERA").
dico("T", 9, "TRUCIDIEZ").
dico("T", 9, "TRUCIDONS").
dico("T", 9, "TRUCMUCHE").
dico("T", 9, "TRUCULENT").
dico("T", 9, "TRUDGEONS").
dico("T", 9, "TRUELLEES").
dico("T", 9, "TRUFFADES").
dico("T", 9, "TRUFFAMES").
dico("T", 9, "TRUFFASSE").
dico("T", 9, "TRUFFATES").
dico("T", 9, "TRUFFERAI").
dico("T", 9, "TRUFFERAS").
dico("T", 9, "TRUFFEREZ").
dico("T", 9, "TRUFFIERE").
dico("T", 9, "TRUFFIERS").
dico("T", 9, "TRUFFIONS").
dico("T", 9, "TRUITELLE").
dico("T", 9, "TRUQUAGES").
dico("T", 9, "TRUQUAMES").
dico("T", 9, "TRUQUASSE").
dico("T", 9, "TRUQUATES").
dico("T", 9, "TRUQUERAI").
dico("T", 9, "TRUQUERAS").
dico("T", 9, "TRUQUEREZ").
dico("T", 9, "TRUQUEURS").
dico("T", 9, "TRUQUEUSE").
dico("T", 9, "TRUQUIONS").
dico("T", 9, "TRUQUISTE").
dico("T", 9, "TRUSQUINA").
dico("T", 9, "TRUSQUINE").
dico("T", 9, "TRUSQUINS").
dico("T", 9, "TRUSTAMES").
dico("T", 9, "TRUSTASSE").
dico("T", 9, "TRUSTATES").
dico("T", 9, "TRUSTERAI").
dico("T", 9, "TRUSTERAS").
dico("T", 9, "TRUSTEREZ").
dico("T", 9, "TRUSTEURS").
dico("T", 9, "TRUSTIONS").
dico("T", 9, "TRYPSINES").
dico("T", 9, "TSARISMES").
dico("T", 9, "TSARISTES").
dico("T", 9, "TUASSIONS").
dico("T", 9, "TUBASSENT").
dico("T", 9, "TUBASSIEZ").
dico("T", 9, "TUBERACEE").
dico("T", 9, "TUBERACES").
dico("T", 9, "TUBERALES").
dico("T", 9, "TUBERCULE").
dico("T", 9, "TUBEREUSE").
dico("T", 9, "TUBERIONS").
dico("T", 9, "TUBERISEE").
dico("T", 9, "TUBERISES").
dico("T", 9, "TUBICOLES").
dico("T", 9, "TUBIPORES").
dico("T", 9, "TUBITELES").
dico("T", 9, "TUBULAIRE").
dico("T", 9, "TUBULEUSE").
dico("T", 9, "TUBULINES").
dico("T", 9, "TUBULURES").
dico("T", 9, "TUDESQUES").
dico("T", 9, "TUERAIENT").
dico("T", 9, "TUILAIENT").
dico("T", 9, "TUILASSES").
dico("T", 9, "TUILERAIS").
dico("T", 9, "TUILERAIT").
dico("T", 9, "TUILERENT").
dico("T", 9, "TUILERIES").
dico("T", 9, "TUILERIEZ").
dico("T", 9, "TUILERONS").
dico("T", 9, "TUILERONT").
dico("T", 9, "TUILETTES").
dico("T", 9, "TUILIERES").
dico("T", 9, "TULAREMIE").
dico("T", 9, "TULIPIERS").
dico("T", 9, "TULLERIES").
dico("T", 9, "TULLIERES").
dico("T", 9, "TULLISTES").
dico("T", 9, "TULLOISES").
dico("T", 9, "TUMBLINGS").
dico("T", 9, "TUMEFIAIS").
dico("T", 9, "TUMEFIAIT").
dico("T", 9, "TUMEFIANT").
dico("T", 9, "TUMEFIEES").
dico("T", 9, "TUMEFIENT").
dico("T", 9, "TUMEFIERA").
dico("T", 9, "TUMEFIIEZ").
dico("T", 9, "TUMEFIONS").
dico("T", 9, "TUMESCENT").
dico("T", 9, "TUMORALES").
dico("T", 9, "TUMULAIRE").
dico("T", 9, "TUNGSTATE").
dico("T", 9, "TUNGSTENE").
dico("T", 9, "TUNICELLE").
dico("T", 9, "TUNICIERS").
dico("T", 9, "TUNIQUEES").
dico("T", 9, "TUNISIENS").
dico("T", 9, "TUNISOISE").
dico("T", 9, "TUNNELIER").
dico("T", 9, "TURBIDITE").
dico("T", 9, "TURBINAGE").
dico("T", 9, "TURBINAIS").
dico("T", 9, "TURBINAIT").
dico("T", 9, "TURBINANT").
dico("T", 9, "TURBINEES").
dico("T", 9, "TURBINENT").
dico("T", 9, "TURBINERA").
dico("T", 9, "TURBINIEZ").
dico("T", 9, "TURBINONS").
dico("T", 9, "TURBOTINS").
dico("T", 9, "TURBULENT").
dico("T", 9, "TURCIQUES").
dico("T", 9, "TURELURES").
dico("T", 9, "TURFISTES").
dico("T", 9, "TURINOISE").
dico("T", 9, "TURKMENES").
dico("T", 9, "TURLUPINA").
dico("T", 9, "TURLUPINE").
dico("T", 9, "TURLUPINS").
dico("T", 9, "TURLUTAIS").
dico("T", 9, "TURLUTAIT").
dico("T", 9, "TURLUTANT").
dico("T", 9, "TURLUTEES").
dico("T", 9, "TURLUTENT").
dico("T", 9, "TURLUTERA").
dico("T", 9, "TURLUTIEZ").
dico("T", 9, "TURLUTONS").
dico("T", 9, "TURLUTTES").
dico("T", 9, "TURLUTUTU").
dico("T", 9, "TURNOVERS").
dico("T", 9, "TURONIENS").
dico("T", 9, "TURPITUDE").
dico("T", 9, "TURQUERIE").
dico("T", 9, "TURQUETTE").
dico("T", 9, "TURQUOISE").
dico("T", 9, "TURRICULE").
dico("T", 9, "TUSSILAGE").
dico("T", 9, "TUTELAIRE").
dico("T", 9, "TUTEURAGE").
dico("T", 9, "TUTEURAIS").
dico("T", 9, "TUTEURAIT").
dico("T", 9, "TUTEURANT").
dico("T", 9, "TUTEUREES").
dico("T", 9, "TUTEURENT").
dico("T", 9, "TUTEURERA").
dico("T", 9, "TUTEURIEZ").
dico("T", 9, "TUTEURONS").
dico("T", 9, "TUTOIERAI").
dico("T", 9, "TUTOIERAS").
dico("T", 9, "TUTOIEREZ").
dico("T", 9, "TUTOYAMES").
dico("T", 9, "TUTOYASSE").
dico("T", 9, "TUTOYATES").
dico("T", 9, "TUTOYEURS").
dico("T", 9, "TUTOYEUSE").
dico("T", 9, "TUTOYIONS").
dico("T", 9, "TUVALUANE").
dico("T", 9, "TUVALUANS").
dico("T", 9, "TUYAUTAGE").
dico("T", 9, "TUYAUTAIS").
dico("T", 9, "TUYAUTAIT").
dico("T", 9, "TUYAUTANT").
dico("T", 9, "TUYAUTEES").
dico("T", 9, "TUYAUTENT").
dico("T", 9, "TUYAUTERA").
dico("T", 9, "TUYAUTEUR").
dico("T", 9, "TUYAUTIEZ").
dico("T", 9, "TUYAUTONS").
dico("T", 9, "TWIRLINGS").
dico("T", 9, "TWISTAMES").
dico("T", 9, "TWISTASSE").
dico("T", 9, "TWISTATES").
dico("T", 9, "TWISTERAI").
dico("T", 9, "TWISTERAS").
dico("T", 9, "TWISTEREZ").
dico("T", 9, "TWISTEURS").
dico("T", 9, "TWISTEUSE").
dico("T", 9, "TWISTIONS").
dico("T", 9, "TYLENCHUS").
dico("T", 9, "TYMPANALE").
dico("T", 9, "TYMPANAUX").
dico("T", 9, "TYMPANISA").
dico("T", 9, "TYMPANISE").
dico("T", 9, "TYMPANONS").
dico("T", 9, "TYPASSENT").
dico("T", 9, "TYPASSIEZ").
dico("T", 9, "TYPERIONS").
dico("T", 9, "TYPHACEES").
dico("T", 9, "TYPHIQUES").
dico("T", 9, "TYPHLITES").
dico("T", 9, "TYPHOIDES").
dico("T", 9, "TYPICITES").
dico("T", 9, "TYPOLOGIE").
dico("T", 9, "TYPOMETRE").
dico("T", 9, "TYRAMINES").
dico("T", 9, "TYRANNEAU").
dico("T", 9, "TYRANNIES").
dico("T", 9, "TYRANNISA").
dico("T", 9, "TYRANNISE").
dico("T", 9, "TYRIENNES").
dico("T", 9, "TYROLIENS").
dico("T", 9, "TYROSINES").
dico("T", 9, "TZARISMES").
dico("T", 9, "TZARISTES").
