dico("U", 10, "UBIQUISTES").
dico("U", 10, "UFOLOGIQUE").
dico("U", 10, "UKRAINIENS").
dico("U", 10, "ULCERAIENT").
dico("U", 10, "ULCERASSES").
dico("U", 10, "ULCERATIFS").
dico("U", 10, "ULCERATION").
dico("U", 10, "ULCERATIVE").
dico("U", 10, "ULCERERAIS").
dico("U", 10, "ULCERERAIT").
dico("U", 10, "ULCERERENT").
dico("U", 10, "ULCERERIEZ").
dico("U", 10, "ULCERERONS").
dico("U", 10, "ULCERERONT").
dico("U", 10, "ULCEREUSES").
dico("U", 10, "ULCEROIDES").
dico("U", 10, "ULIGINAIRE").
dico("U", 10, "ULIGINEUSE").
dico("U", 10, "ULTERIEURE").
dico("U", 10, "ULTERIEURS").
dico("U", 10, "ULTIMATUMS").
dico("U", 10, "ULTRACHICS").
dico("U", 10, "ULTRACOURT").
dico("U", 10, "ULTRADIENS").
dico("U", 10, "ULTRALEGER").
dico("U", 10, "ULTRAMARIN").
dico("U", 10, "ULTRAPLATE").
dico("U", 10, "ULTRAPLATS").
dico("U", 10, "ULTRAVIDES").
dico("U", 10, "ULTRAVIRUS").
dico("U", 10, "ULULASSENT").
dico("U", 10, "ULULASSIEZ").
dico("U", 10, "ULULATIONS").
dico("U", 10, "ULULEMENTS").
dico("U", 10, "ULULERIONS").
dico("U", 10, "UNANIMISME").
dico("U", 10, "UNANIMISTE").
dico("U", 10, "UNANIMITES").
dico("U", 10, "UNCIFORMES").
dico("U", 10, "UNGUIFERES").
dico("U", 10, "UNICOLORES").
dico("U", 10, "UNIEMEMENT").
dico("U", 10, "UNIFIAIENT").
dico("U", 10, "UNIFIASSES").
dico("U", 10, "UNIFIERAIS").
dico("U", 10, "UNIFIERAIT").
dico("U", 10, "UNIFIERENT").
dico("U", 10, "UNIFIERIEZ").
dico("U", 10, "UNIFIERONS").
dico("U", 10, "UNIFIERONT").
dico("U", 10, "UNIFILAIRE").
dico("U", 10, "UNIFOLIEES").
dico("U", 10, "UNIFORMISA").
dico("U", 10, "UNIFORMISE").
dico("U", 10, "UNIFORMITE").
dico("U", 10, "UNILATERAL").
dico("U", 10, "UNILINGUES").
dico("U", 10, "UNIMODALES").
dico("U", 10, "UNINOMINAL").
dico("U", 10, "UNIONISMES").
dico("U", 10, "UNIONISTES").
dico("U", 10, "UNIOVULEES").
dico("U", 10, "UNIPOLAIRE").
dico("U", 10, "UNIQUEMENT").
dico("U", 10, "UNISEXUEES").
dico("U", 10, "UNISEXUELS").
dico("U", 10, "UNISSAIENT").
dico("U", 10, "UNITARIENS").
dico("U", 10, "UNITARISME").
dico("U", 10, "UNIVALENCE").
dico("U", 10, "UNIVALENTE").
dico("U", 10, "UNIVALENTS").
dico("U", 10, "UNIVERSAUX").
dico("U", 10, "UNIVERSELS").
dico("U", 10, "UNIVERSITE").
dico("U", 10, "UNIVOCITES").
dico("U", 10, "UPERISAMES").
dico("U", 10, "UPERISASSE").
dico("U", 10, "UPERISATES").
dico("U", 10, "UPERISERAI").
dico("U", 10, "UPERISERAS").
dico("U", 10, "UPERISEREZ").
dico("U", 10, "UPERISIONS").
dico("U", 10, "UPWELLINGS").
dico("U", 10, "URANIFERES").
dico("U", 10, "URANINITES").
dico("U", 10, "URANOSCOPE").
dico("U", 10, "URBANISAIS").
dico("U", 10, "URBANISAIT").
dico("U", 10, "URBANISANT").
dico("U", 10, "URBANISEES").
dico("U", 10, "URBANISENT").
dico("U", 10, "URBANISERA").
dico("U", 10, "URBANISIEZ").
dico("U", 10, "URBANISMES").
dico("U", 10, "URBANISONS").
dico("U", 10, "URBANISTES").
dico("U", 10, "UREDINALES").
dico("U", 10, "UREDOSPORE").
dico("U", 10, "UREOGENESE").
dico("U", 10, "URETERALES").
dico("U", 10, "URETERITES").
dico("U", 10, "URETHANNES").
dico("U", 10, "URGEASSENT").
dico("U", 10, "URGENTISTE").
dico("U", 10, "URGERAIENT").
dico("U", 10, "URGONIENNE").
dico("U", 10, "URINASSENT").
dico("U", 10, "URINASSIEZ").
dico("U", 10, "URINERIONS").
dico("U", 10, "URINIFERES").
dico("U", 10, "UROBILINES").
dico("U", 10, "UROCHROMES").
dico("U", 10, "UROGENITAL").
dico("U", 10, "UROGRAPHIE").
dico("U", 10, "UROKINASES").
dico("U", 10, "UROLAGNIES").
dico("U", 10, "UROPYGIALE").
dico("U", 10, "UROPYGIAUX").
dico("U", 10, "UROPYGIENS").
dico("U", 10, "UROTELIQUE").
dico("U", 10, "URTICACEES").
dico("U", 10, "URTICAIRES").
dico("U", 10, "URTICANTES").
dico("U", 10, "URTICATION").
dico("U", 10, "URUGUAYENS").
dico("U", 10, "USINASSENT").
dico("U", 10, "USINASSIEZ").
dico("U", 10, "USINERIONS").
dico("U", 10, "USTENSILES").
dico("U", 10, "USUCAPIONS").
dico("U", 10, "USURPAIENT").
dico("U", 10, "USURPASSES").
dico("U", 10, "USURPATEUR").
dico("U", 10, "USURPATION").
dico("U", 10, "USURPERAIS").
dico("U", 10, "USURPERAIT").
dico("U", 10, "USURPERENT").
dico("U", 10, "USURPERIEZ").
dico("U", 10, "USURPERONS").
dico("U", 10, "USURPERONT").
dico("U", 10, "UTILISABLE").
dico("U", 10, "UTILISAMES").
dico("U", 10, "UTILISASSE").
dico("U", 10, "UTILISATES").
dico("U", 10, "UTILISERAI").
dico("U", 10, "UTILISERAS").
dico("U", 10, "UTILISEREZ").
dico("U", 10, "UTILISIONS").
dico("U", 10, "UTILITAIRE").
dico("U", 10, "UTRAQUISTE").
dico("U", 10, "UTRICULEUX").
dico("U", 10, "UXORILOCAL").
