dico("U", 7, "UBERALE").
dico("U", 7, "UKULELE").
dico("U", 7, "ULCERAI").
dico("U", 7, "ULCERAS").
dico("U", 7, "ULCERAT").
dico("U", 7, "ULCEREE").
dico("U", 7, "ULCERER").
dico("U", 7, "ULCERES").
dico("U", 7, "ULCEREZ").
dico("U", 7, "ULLUCOS").
dico("U", 7, "ULLUCUS").
dico("U", 7, "ULLUQUE").
dico("U", 7, "ULMACEE").
dico("U", 7, "ULMAIRE").
dico("U", 7, "ULMISTE").
dico("U", 7, "ULNAIRE").
dico("U", 7, "ULSTERS").
dico("U", 7, "ULTIMES").
dico("U", 7, "ULULAIS").
dico("U", 7, "ULULAIT").
dico("U", 7, "ULULANT").
dico("U", 7, "ULULENT").
dico("U", 7, "ULULERA").
dico("U", 7, "ULULIEZ").
dico("U", 7, "ULULONS").
dico("U", 7, "UMBANDA").
dico("U", 7, "UMLAUTS").
dico("U", 7, "UNANIME").
dico("U", 7, "UNCINEE").
dico("U", 7, "UNCINES").
dico("U", 7, "UNGUEAL").
dico("U", 7, "UNIATES").
dico("U", 7, "UNIAXES").
dico("U", 7, "UNICITE").
dico("U", 7, "UNIEMES").
dico("U", 7, "UNIFIAI").
dico("U", 7, "UNIFIAS").
dico("U", 7, "UNIFIAT").
dico("U", 7, "UNIFIEE").
dico("U", 7, "UNIFIER").
dico("U", 7, "UNIFIES").
dico("U", 7, "UNIFIEZ").
dico("U", 7, "UNILOBE").
dico("U", 7, "UNIMENT").
dico("U", 7, "UNIPARE").
dico("U", 7, "UNIPRIX").
dico("U", 7, "UNIQUES").
dico("U", 7, "UNIRAIS").
dico("U", 7, "UNIRAIT").
dico("U", 7, "UNIRAME").
dico("U", 7, "UNIRENT").
dico("U", 7, "UNIRIEZ").
dico("U", 7, "UNIRONS").
dico("U", 7, "UNIRONT").
dico("U", 7, "UNISEXE").
dico("U", 7, "UNISSES").
dico("U", 7, "UNISSEZ").
dico("U", 7, "UNISSON").
dico("U", 7, "UNITIFS").
dico("U", 7, "UNITIVE").
dico("U", 7, "UNIVERS").
dico("U", 7, "UPERISA").
dico("U", 7, "UPERISE").
dico("U", 7, "UPSILON").
dico("U", 7, "URACILE").
dico("U", 7, "URAETES").
dico("U", 7, "URANAIS").
dico("U", 7, "URANATE").
dico("U", 7, "URANEUX").
dico("U", 7, "URANIDE").
dico("U", 7, "URANIES").
dico("U", 7, "URANITE").
dico("U", 7, "URANIUM").
dico("U", 7, "URANYLE").
dico("U", 7, "URBAINE").
dico("U", 7, "URBAINS").
dico("U", 7, "URCEOLE").
dico("U", 7, "UREIDES").
dico("U", 7, "UREIQUE").
dico("U", 7, "UREMIES").
dico("U", 7, "URETERE").
dico("U", 7, "URETRAL").
dico("U", 7, "URETRES").
dico("U", 7, "URGEAIT").
dico("U", 7, "URGEANT").
dico("U", 7, "URGENCE").
dico("U", 7, "URGENTE").
dico("U", 7, "URGENTS").
dico("U", 7, "URINAIS").
dico("U", 7, "URINAIT").
dico("U", 7, "URINANT").
dico("U", 7, "URINAUX").
dico("U", 7, "URINEES").
dico("U", 7, "URINENT").
dico("U", 7, "URINERA").
dico("U", 7, "URINEUX").
dico("U", 7, "URINIEZ").
dico("U", 7, "URINOIR").
dico("U", 7, "URINONS").
dico("U", 7, "URIQUES").
dico("U", 7, "URODELE").
dico("U", 7, "UROPODE").
dico("U", 7, "UROPYGE").
dico("U", 7, "URSIDES").
dico("U", 7, "USABLES").
dico("U", 7, "USAGEES").
dico("U", 7, "USAGERE").
dico("U", 7, "USAGERS").
dico("U", 7, "USAIENT").
dico("U", 7, "USANCES").
dico("U", 7, "USANTES").
dico("U", 7, "USASSES").
dico("U", 7, "USERAIS").
dico("U", 7, "USERAIT").
dico("U", 7, "USERENT").
dico("U", 7, "USERIEZ").
dico("U", 7, "USERONS").
dico("U", 7, "USERONT").
dico("U", 7, "USINAGE").
dico("U", 7, "USINAIS").
dico("U", 7, "USINAIT").
dico("U", 7, "USINANT").
dico("U", 7, "USINEES").
dico("U", 7, "USINENT").
dico("U", 7, "USINERA").
dico("U", 7, "USINIER").
dico("U", 7, "USINIEZ").
dico("U", 7, "USINONS").
dico("U", 7, "USITEES").
dico("U", 7, "USUELLE").
dico("U", 7, "USURIER").
dico("U", 7, "USURPAI").
dico("U", 7, "USURPAS").
dico("U", 7, "USURPAT").
dico("U", 7, "USURPEE").
dico("U", 7, "USURPER").
dico("U", 7, "USURPES").
dico("U", 7, "USURPEZ").
dico("U", 7, "UTERINE").
dico("U", 7, "UTERINS").
dico("U", 7, "UTILISA").
dico("U", 7, "UTILISE").
dico("U", 7, "UTILITE").
dico("U", 7, "UTOPIES").
dico("U", 7, "UVEITES").
dico("U", 7, "UZBEKES").
