dico("U", 8, "UBERALES").
dico("U", 8, "UBIQUITE").
dico("U", 8, "UBUESQUE").
dico("U", 8, "UFOLOGIE").
dico("U", 8, "UFOLOGUE").
dico("U", 8, "UKULELES").
dico("U", 8, "ULCERAIS").
dico("U", 8, "ULCERAIT").
dico("U", 8, "ULCERANT").
dico("U", 8, "ULCEREES").
dico("U", 8, "ULCERENT").
dico("U", 8, "ULCERERA").
dico("U", 8, "ULCEREUX").
dico("U", 8, "ULCERIEZ").
dico("U", 8, "ULCERONS").
dico("U", 8, "ULLUQUES").
dico("U", 8, "ULMACEES").
dico("U", 8, "ULMAIRES").
dico("U", 8, "ULMISTES").
dico("U", 8, "ULNAIRES").
dico("U", 8, "ULTRASON").
dico("U", 8, "ULULAMES").
dico("U", 8, "ULULASSE").
dico("U", 8, "ULULATES").
dico("U", 8, "ULULERAI").
dico("U", 8, "ULULERAS").
dico("U", 8, "ULULEREZ").
dico("U", 8, "ULULIONS").
dico("U", 8, "UMBANDAS").
dico("U", 8, "UNANIMES").
dico("U", 8, "UNCINEES").
dico("U", 8, "UNETELLE").
dico("U", 8, "UNGUEALE").
dico("U", 8, "UNGUEAUX").
dico("U", 8, "UNICAULE").
dico("U", 8, "UNICITES").
dico("U", 8, "UNICORNE").
dico("U", 8, "UNIFIAIS").
dico("U", 8, "UNIFIAIT").
dico("U", 8, "UNIFIANT").
dico("U", 8, "UNIFIEES").
dico("U", 8, "UNIFIENT").
dico("U", 8, "UNIFIERA").
dico("U", 8, "UNIFIIEZ").
dico("U", 8, "UNIFIONS").
dico("U", 8, "UNIFLORE").
dico("U", 8, "UNIFOLIE").
dico("U", 8, "UNIFORME").
dico("U", 8, "UNILOBEE").
dico("U", 8, "UNILOBES").
dico("U", 8, "UNIMODAL").
dico("U", 8, "UNIOVULE").
dico("U", 8, "UNIPARES").
dico("U", 8, "UNIRAMEE").
dico("U", 8, "UNIRAMES").
dico("U", 8, "UNIRIONS").
dico("U", 8, "UNISEXES").
dico("U", 8, "UNISEXUE").
dico("U", 8, "UNISSAIS").
dico("U", 8, "UNISSAIT").
dico("U", 8, "UNISSANT").
dico("U", 8, "UNISSENT").
dico("U", 8, "UNISSIEZ").
dico("U", 8, "UNISSONS").
dico("U", 8, "UNITAIRE").
dico("U", 8, "UNITIVES").
dico("U", 8, "UNIVALVE").
dico("U", 8, "UNIVOQUE").
dico("U", 8, "UPERISAI").
dico("U", 8, "UPERISAS").
dico("U", 8, "UPERISAT").
dico("U", 8, "UPERISEE").
dico("U", 8, "UPERISER").
dico("U", 8, "UPERISES").
dico("U", 8, "UPERISEZ").
dico("U", 8, "UPPERCUT").
dico("U", 8, "URACILES").
dico("U", 8, "URANAISE").
dico("U", 8, "URANATES").
dico("U", 8, "URANEUSE").
dico("U", 8, "URANIDES").
dico("U", 8, "URANIQUE").
dico("U", 8, "URANISME").
dico("U", 8, "URANISTE").
dico("U", 8, "URANITES").
dico("U", 8, "URANIUMS").
dico("U", 8, "URANYLES").
dico("U", 8, "URBAINES").
dico("U", 8, "URBANISA").
dico("U", 8, "URBANISE").
dico("U", 8, "URBANITE").
dico("U", 8, "URCEOLEE").
dico("U", 8, "URCEOLES").
dico("U", 8, "UREDINEE").
dico("U", 8, "UREIQUES").
dico("U", 8, "UREMIQUE").
dico("U", 8, "URETERAL").
dico("U", 8, "URETERES").
dico("U", 8, "URETHANE").
dico("U", 8, "URETRALE").
dico("U", 8, "URETRAUX").
dico("U", 8, "URETRITE").
dico("U", 8, "URGENCES").
dico("U", 8, "URGENTES").
dico("U", 8, "URGERAIT").
dico("U", 8, "URGERENT").
dico("U", 8, "URGERONT").
dico("U", 8, "URGONIEN").
dico("U", 8, "URICEMIE").
dico("U", 8, "URINAIRE").
dico("U", 8, "URINAMES").
dico("U", 8, "URINASSE").
dico("U", 8, "URINATES").
dico("U", 8, "URINERAI").
dico("U", 8, "URINERAS").
dico("U", 8, "URINEREZ").
dico("U", 8, "URINEUSE").
dico("U", 8, "URINIONS").
dico("U", 8, "URINOIRS").
dico("U", 8, "UROCORDE").
dico("U", 8, "URODELES").
dico("U", 8, "UROLOGIE").
dico("U", 8, "UROLOGUE").
dico("U", 8, "UROMETRE").
dico("U", 8, "URONIQUE").
dico("U", 8, "UROPODES").
dico("U", 8, "UROPYGES").
dico("U", 8, "URSULINE").
dico("U", 8, "URTICALE").
dico("U", 8, "URTICANT").
dico("U", 8, "USAGERES").
dico("U", 8, "USASSENT").
dico("U", 8, "USASSIEZ").
dico("U", 8, "USERIONS").
dico("U", 8, "USINAGES").
dico("U", 8, "USINAMES").
dico("U", 8, "USINASSE").
dico("U", 8, "USINATES").
dico("U", 8, "USINERAI").
dico("U", 8, "USINERAS").
dico("U", 8, "USINEREZ").
dico("U", 8, "USINIERE").
dico("U", 8, "USINIERS").
dico("U", 8, "USINIONS").
dico("U", 8, "USUELLES").
dico("U", 8, "USUFRUIT").
dico("U", 8, "USURAIRE").
dico("U", 8, "USURIERE").
dico("U", 8, "USURIERS").
dico("U", 8, "USURPAIS").
dico("U", 8, "USURPAIT").
dico("U", 8, "USURPANT").
dico("U", 8, "USURPEES").
dico("U", 8, "USURPENT").
dico("U", 8, "USURPERA").
dico("U", 8, "USURPIEZ").
dico("U", 8, "USURPONS").
dico("U", 8, "UTERINES").
dico("U", 8, "UTILISAI").
dico("U", 8, "UTILISAS").
dico("U", 8, "UTILISAT").
dico("U", 8, "UTILISEE").
dico("U", 8, "UTILISER").
dico("U", 8, "UTILISES").
dico("U", 8, "UTILISEZ").
dico("U", 8, "UTILITES").
dico("U", 8, "UTOPIQUE").
dico("U", 8, "UTOPISME").
dico("U", 8, "UTOPISTE").
dico("U", 8, "UTRICULE").
dico("U", 8, "UVULAIRE").
