dico("U", 9, "UBIQUISTE").
dico("U", 9, "UBIQUITES").
dico("U", 9, "UBUESQUES").
dico("U", 9, "UFOLOGIES").
dico("U", 9, "UFOLOGUES").
dico("U", 9, "UKRAINIEN").
dico("U", 9, "ULCERAMES").
dico("U", 9, "ULCERASSE").
dico("U", 9, "ULCERATES").
dico("U", 9, "ULCERATIF").
dico("U", 9, "ULCERERAI").
dico("U", 9, "ULCERERAS").
dico("U", 9, "ULCEREREZ").
dico("U", 9, "ULCEREUSE").
dico("U", 9, "ULCERIONS").
dico("U", 9, "ULCEROIDE").
dico("U", 9, "ULIGINEUX").
dico("U", 9, "ULTERIEUR").
dico("U", 9, "ULTIMATUM").
dico("U", 9, "ULTRACHIC").
dico("U", 9, "ULTRADIEN").
dico("U", 9, "ULTRAPLAT").
dico("U", 9, "ULTRASONS").
dico("U", 9, "ULTRAVIDE").
dico("U", 9, "ULULAIENT").
dico("U", 9, "ULULASSES").
dico("U", 9, "ULULATION").
dico("U", 9, "ULULEMENT").
dico("U", 9, "ULULERAIS").
dico("U", 9, "ULULERAIT").
dico("U", 9, "ULULERENT").
dico("U", 9, "ULULERIEZ").
dico("U", 9, "ULULERONS").
dico("U", 9, "ULULERONT").
dico("U", 9, "UNANIMITE").
dico("U", 9, "UNCIFORME").
dico("U", 9, "UNGUEALES").
dico("U", 9, "UNGUIFERE").
dico("U", 9, "UNICAULES").
dico("U", 9, "UNICOLORE").
dico("U", 9, "UNICORNES").
dico("U", 9, "UNIFIAMES").
dico("U", 9, "UNIFIASSE").
dico("U", 9, "UNIFIATES").
dico("U", 9, "UNIFIERAI").
dico("U", 9, "UNIFIERAS").
dico("U", 9, "UNIFIEREZ").
dico("U", 9, "UNIFIIONS").
dico("U", 9, "UNIFLORES").
dico("U", 9, "UNIFOLIEE").
dico("U", 9, "UNIFOLIES").
dico("U", 9, "UNIFORMES").
dico("U", 9, "UNILINGUE").
dico("U", 9, "UNILOBEES").
dico("U", 9, "UNIMODALE").
dico("U", 9, "UNIMODAUX").
dico("U", 9, "UNIONISME").
dico("U", 9, "UNIONISTE").
dico("U", 9, "UNIOVULEE").
dico("U", 9, "UNIOVULES").
dico("U", 9, "UNIRAIENT").
dico("U", 9, "UNIRAMEES").
dico("U", 9, "UNISEXUEE").
dico("U", 9, "UNISEXUEL").
dico("U", 9, "UNISEXUES").
dico("U", 9, "UNISSIONS").
dico("U", 9, "UNITAIRES").
dico("U", 9, "UNITARIEN").
dico("U", 9, "UNIVALENT").
dico("U", 9, "UNIVALVES").
dico("U", 9, "UNIVERSEL").
dico("U", 9, "UNIVOCITE").
dico("U", 9, "UNIVOQUES").
dico("U", 9, "UPERISAIS").
dico("U", 9, "UPERISAIT").
dico("U", 9, "UPERISANT").
dico("U", 9, "UPERISEES").
dico("U", 9, "UPERISENT").
dico("U", 9, "UPERISERA").
dico("U", 9, "UPERISIEZ").
dico("U", 9, "UPERISONS").
dico("U", 9, "UPPERCUTS").
dico("U", 9, "UPWELLING").
dico("U", 9, "URANAISES").
dico("U", 9, "URANEUSES").
dico("U", 9, "URANIFERE").
dico("U", 9, "URANINITE").
dico("U", 9, "URANIQUES").
dico("U", 9, "URANISMES").
dico("U", 9, "URANISTES").
dico("U", 9, "URBANISAI").
dico("U", 9, "URBANISAS").
dico("U", 9, "URBANISAT").
dico("U", 9, "URBANISEE").
dico("U", 9, "URBANISER").
dico("U", 9, "URBANISES").
dico("U", 9, "URBANISEZ").
dico("U", 9, "URBANISME").
dico("U", 9, "URBANISTE").
dico("U", 9, "URBANITES").
dico("U", 9, "URCEOLEES").
dico("U", 9, "UREDINALE").
dico("U", 9, "UREDINEES").
dico("U", 9, "UREMIQUES").
dico("U", 9, "URETERALE").
dico("U", 9, "URETERAUX").
dico("U", 9, "URETERITE").
dico("U", 9, "URETHANES").
dico("U", 9, "URETHANNE").
dico("U", 9, "URETRALES").
dico("U", 9, "URETRITES").
dico("U", 9, "URGEAIENT").
dico("U", 9, "URGEMMENT").
dico("U", 9, "URGONIENS").
dico("U", 9, "URICEMIES").
dico("U", 9, "URINAIENT").
dico("U", 9, "URINAIRES").
dico("U", 9, "URINASSES").
dico("U", 9, "URINERAIS").
dico("U", 9, "URINERAIT").
dico("U", 9, "URINERENT").
dico("U", 9, "URINERIEZ").
dico("U", 9, "URINERONS").
dico("U", 9, "URINERONT").
dico("U", 9, "URINEUSES").
dico("U", 9, "URINIFERE").
dico("U", 9, "UROBILINE").
dico("U", 9, "UROCHROME").
dico("U", 9, "UROCORDES").
dico("U", 9, "UROKINASE").
dico("U", 9, "UROLAGNIE").
dico("U", 9, "UROLOGIES").
dico("U", 9, "UROLOGUES").
dico("U", 9, "UROMETRES").
dico("U", 9, "URONIQUES").
dico("U", 9, "UROPYGIAL").
dico("U", 9, "UROPYGIEN").
dico("U", 9, "URSULINES").
dico("U", 9, "URTICACEE").
dico("U", 9, "URTICAIRE").
dico("U", 9, "URTICALES").
dico("U", 9, "URTICANTE").
dico("U", 9, "URTICANTS").
dico("U", 9, "URUGUAYEN").
dico("U", 9, "USASSIONS").
dico("U", 9, "USERAIENT").
dico("U", 9, "USINAIENT").
dico("U", 9, "USINASSES").
dico("U", 9, "USINERAIS").
dico("U", 9, "USINERAIT").
dico("U", 9, "USINERENT").
dico("U", 9, "USINERIEZ").
dico("U", 9, "USINERONS").
dico("U", 9, "USINERONT").
dico("U", 9, "USINIERES").
dico("U", 9, "USTENSILE").
dico("U", 9, "USUCAPION").
dico("U", 9, "USUFRUITS").
dico("U", 9, "USURAIRES").
dico("U", 9, "USURIERES").
dico("U", 9, "USURPAMES").
dico("U", 9, "USURPASSE").
dico("U", 9, "USURPATES").
dico("U", 9, "USURPERAI").
dico("U", 9, "USURPERAS").
dico("U", 9, "USURPEREZ").
dico("U", 9, "USURPIONS").
dico("U", 9, "UTILEMENT").
dico("U", 9, "UTILISAIS").
dico("U", 9, "UTILISAIT").
dico("U", 9, "UTILISANT").
dico("U", 9, "UTILISEES").
dico("U", 9, "UTILISENT").
dico("U", 9, "UTILISERA").
dico("U", 9, "UTILISIEZ").
dico("U", 9, "UTILISONS").
dico("U", 9, "UTOPIQUES").
dico("U", 9, "UTOPISMES").
dico("U", 9, "UTOPISTES").
dico("U", 9, "UTRICULES").
dico("U", 9, "UVULAIRES").
