dico("V", 10, "VACANCIERE").
dico("V", 10, "VACANCIERS").
dico("V", 10, "VACATAIRES").
dico("V", 10, "VACCINABLE").
dico("V", 10, "VACCINALES").
dico("V", 10, "VACCINAMES").
dico("V", 10, "VACCINASSE").
dico("V", 10, "VACCINATES").
dico("V", 10, "VACCINELLE").
dico("V", 10, "VACCINERAI").
dico("V", 10, "VACCINERAS").
dico("V", 10, "VACCINEREZ").
dico("V", 10, "VACCINIDES").
dico("V", 10, "VACCINIERS").
dico("V", 10, "VACCINIONS").
dico("V", 10, "VACCINOIDE").
dico("V", 10, "VACHASSENT").
dico("V", 10, "VACHASSIEZ").
dico("V", 10, "VACHERIONS").
dico("V", 10, "VACILLAMES").
dico("V", 10, "VACILLANTE").
dico("V", 10, "VACILLANTS").
dico("V", 10, "VACILLASSE").
dico("V", 10, "VACILLATES").
dico("V", 10, "VACILLERAI").
dico("V", 10, "VACILLERAS").
dico("V", 10, "VACILLEREZ").
dico("V", 10, "VACILLIONS").
dico("V", 10, "VACUOLAIRE").
dico("V", 10, "VACUOLISAI").
dico("V", 10, "VACUOLISAS").
dico("V", 10, "VACUOLISAT").
dico("V", 10, "VACUOLISEE").
dico("V", 10, "VACUOLISER").
dico("V", 10, "VACUOLISES").
dico("V", 10, "VACUOLISEZ").
dico("V", 10, "VACUOMETRE").
dico("V", 10, "VADROUILLA").
dico("V", 10, "VADROUILLE").
dico("V", 10, "VAGABONDAI").
dico("V", 10, "VAGABONDAS").
dico("V", 10, "VAGABONDAT").
dico("V", 10, "VAGABONDER").
dico("V", 10, "VAGABONDES").
dico("V", 10, "VAGABONDEZ").
dico("V", 10, "VAGINISMES").
dico("V", 10, "VAGIRAIENT").
dico("V", 10, "VAGISSANTE").
dico("V", 10, "VAGISSANTS").
dico("V", 10, "VAGISSIONS").
dico("V", 10, "VAGOTOMIES").
dico("V", 10, "VAGOTONIES").
dico("V", 10, "VAGUASSENT").
dico("V", 10, "VAGUASSIEZ").
dico("V", 10, "VAGUELETTE").
dico("V", 10, "VAGUERIONS").
dico("V", 10, "VAILLANCES").
dico("V", 10, "VAILLANTES").
dico("V", 10, "VAILLANTIE").
dico("V", 10, "VAINCRIONS").
dico("V", 10, "VAINQUEURS").
dico("V", 10, "VAINQUIMES").
dico("V", 10, "VAINQUIONS").
dico("V", 10, "VAINQUISSE").
dico("V", 10, "VAINQUITES").
dico("V", 10, "VAISSELIER").
dico("V", 10, "VAISSELLES").
dico("V", 10, "VALAISANNE").
dico("V", 10, "VALDEISMES").
dico("V", 10, "VALDINGUAI").
dico("V", 10, "VALDINGUAS").
dico("V", 10, "VALDINGUAT").
dico("V", 10, "VALDINGUER").
dico("V", 10, "VALDINGUES").
dico("V", 10, "VALDINGUEZ").
dico("V", 10, "VALDOISIEN").
dico("V", 10, "VALDOTAINE").
dico("V", 10, "VALDOTAINS").
dico("V", 10, "VALENTINES").
dico("V", 10, "VALERIANES").
dico("V", 10, "VALERIQUES").
dico("V", 10, "VALETAILLE").
dico("V", 10, "VALEUREUSE").
dico("V", 10, "VALIDAIENT").
dico("V", 10, "VALIDASSES").
dico("V", 10, "VALIDATION").
dico("V", 10, "VALIDEMENT").
dico("V", 10, "VALIDERAIS").
dico("V", 10, "VALIDERAIT").
dico("V", 10, "VALIDERENT").
dico("V", 10, "VALIDERIEZ").
dico("V", 10, "VALIDERONS").
dico("V", 10, "VALIDERONT").
dico("V", 10, "VALIDEUSES").
dico("V", 10, "VALLONNAIS").
dico("V", 10, "VALLONNAIT").
dico("V", 10, "VALLONNANT").
dico("V", 10, "VALLONNEES").
dico("V", 10, "VALLONNENT").
dico("V", 10, "VALLONNERA").
dico("V", 10, "VALLONNEUX").
dico("V", 10, "VALLONNIEZ").
dico("V", 10, "VALLONNONS").
dico("V", 10, "VALORISAIS").
dico("V", 10, "VALORISAIT").
dico("V", 10, "VALORISANT").
dico("V", 10, "VALORISEES").
dico("V", 10, "VALORISENT").
dico("V", 10, "VALORISERA").
dico("V", 10, "VALORISIEZ").
dico("V", 10, "VALORISONS").
dico("V", 10, "VALSASSENT").
dico("V", 10, "VALSASSIEZ").
dico("V", 10, "VALSERIONS").
dico("V", 10, "VALUSSIONS").
dico("V", 10, "VALVULAIRE").
dico("V", 10, "VAMPASSENT").
dico("V", 10, "VAMPASSIEZ").
dico("V", 10, "VAMPERIONS").
dico("V", 10, "VAMPIRIQUE").
dico("V", 10, "VAMPIRISAI").
dico("V", 10, "VAMPIRISAS").
dico("V", 10, "VAMPIRISAT").
dico("V", 10, "VAMPIRISEE").
dico("V", 10, "VAMPIRISER").
dico("V", 10, "VAMPIRISES").
dico("V", 10, "VAMPIRISEZ").
dico("V", 10, "VAMPIRISME").
dico("V", 10, "VANADINITE").
dico("V", 10, "VANADIQUES").
dico("V", 10, "VANDALISAI").
dico("V", 10, "VANDALISAS").
dico("V", 10, "VANDALISAT").
dico("V", 10, "VANDALISEE").
dico("V", 10, "VANDALISER").
dico("V", 10, "VANDALISES").
dico("V", 10, "VANDALISEZ").
dico("V", 10, "VANDALISME").
dico("V", 10, "VANILLIERS").
dico("V", 10, "VANILLINEE").
dico("V", 10, "VANILLINES").
dico("V", 10, "VANILLISME").
dico("V", 10, "VANITEUSES").
dico("V", 10, "VANNASSENT").
dico("V", 10, "VANNASSIEZ").
dico("V", 10, "VANNERIONS").
dico("V", 10, "VANNETAISE").
dico("V", 10, "VANTARDISE").
dico("V", 10, "VANTASSENT").
dico("V", 10, "VANTASSIEZ").
dico("V", 10, "VANTERIONS").
dico("V", 10, "VANUATUANE").
dico("V", 10, "VANUATUANS").
dico("V", 10, "VAPORETTOS").
dico("V", 10, "VAPOREUSES").
dico("V", 10, "VAPORISAGE").
dico("V", 10, "VAPORISAIS").
dico("V", 10, "VAPORISAIT").
dico("V", 10, "VAPORISANT").
dico("V", 10, "VAPORISEES").
dico("V", 10, "VAPORISENT").
dico("V", 10, "VAPORISERA").
dico("V", 10, "VAPORISIEZ").
dico("V", 10, "VAPORISONS").
dico("V", 10, "VAQUASSENT").
dico("V", 10, "VAQUASSIEZ").
dico("V", 10, "VAQUERIONS").
dico("V", 10, "VARAPPAMES").
dico("V", 10, "VARAPPASSE").
dico("V", 10, "VARAPPATES").
dico("V", 10, "VARAPPERAI").
dico("V", 10, "VARAPPERAS").
dico("V", 10, "VARAPPEREZ").
dico("V", 10, "VARAPPEURS").
dico("V", 10, "VARAPPEUSE").
dico("V", 10, "VARAPPIONS").
dico("V", 10, "VARIASSENT").
dico("V", 10, "VARIASSIEZ").
dico("V", 10, "VARIATEURS").
dico("V", 10, "VARIATIONS").
dico("V", 10, "VARICELLES").
dico("V", 10, "VARICOCELE").
dico("V", 10, "VARIERIONS").
dico("V", 10, "VARIETALES").
dico("V", 10, "VARIOLEUSE").
dico("V", 10, "VARIOLIQUE").
dico("V", 10, "VARIOMETRE").
dico("V", 10, "VARIQUEUSE").
dico("V", 10, "VARISTANCE").
dico("V", 10, "VARLOPAGES").
dico("V", 10, "VARLOPAMES").
dico("V", 10, "VARLOPASSE").
dico("V", 10, "VARLOPATES").
dico("V", 10, "VARLOPERAI").
dico("V", 10, "VARLOPERAS").
dico("V", 10, "VARLOPEREZ").
dico("V", 10, "VARLOPIONS").
dico("V", 10, "VARSOVIENS").
dico("V", 10, "VASCULAIRE").
dico("V", 10, "VASECTOMIE").
dico("V", 10, "VASELINAIS").
dico("V", 10, "VASELINAIT").
dico("V", 10, "VASELINANT").
dico("V", 10, "VASELINEES").
dico("V", 10, "VASELINENT").
dico("V", 10, "VASELINERA").
dico("V", 10, "VASELINIEZ").
dico("V", 10, "VASELINONS").
dico("V", 10, "VASOMOTEUR").
dico("V", 10, "VASOTOMIES").
dico("V", 10, "VASOUILLAI").
dico("V", 10, "VASOUILLAS").
dico("V", 10, "VASOUILLAT").
dico("V", 10, "VASOUILLER").
dico("V", 10, "VASOUILLES").
dico("V", 10, "VASOUILLEZ").
dico("V", 10, "VASSALIQUE").
dico("V", 10, "VASSALISAI").
dico("V", 10, "VASSALISAS").
dico("V", 10, "VASSALISAT").
dico("V", 10, "VASSALISEE").
dico("V", 10, "VASSALISER").
dico("V", 10, "VASSALISES").
dico("V", 10, "VASSALISEZ").
dico("V", 10, "VASSALITES").
dico("V", 10, "VASSELAGES").
dico("V", 10, "VASSIVEAUX").
dico("V", 10, "VASTITUDES").
dico("V", 10, "VATICINAIS").
dico("V", 10, "VATICINAIT").
dico("V", 10, "VATICINANT").
dico("V", 10, "VATICINENT").
dico("V", 10, "VATICINERA").
dico("V", 10, "VATICINIEZ").
dico("V", 10, "VATICINONS").
dico("V", 10, "VAUCHERIES").
dico("V", 10, "VAUCLUSIEN").
dico("V", 10, "VAUDEVILLE").
dico("V", 10, "VAUDEVIRES").
dico("V", 10, "VAUDRAIENT").
dico("V", 10, "VAURIENNES").
dico("V", 10, "VAUTRAIENT").
dico("V", 10, "VAUTRASSES").
dico("V", 10, "VAUTRERAIS").
dico("V", 10, "VAUTRERAIT").
dico("V", 10, "VAUTRERENT").
dico("V", 10, "VAUTRERIEZ").
dico("V", 10, "VAUTRERONS").
dico("V", 10, "VAUTRERONT").
dico("V", 10, "VAVASSEURS").
dico("V", 10, "VECTORIELS").
dico("V", 10, "VECUSSIONS").
dico("V", 10, "VEDETTISAI").
dico("V", 10, "VEDETTISAS").
dico("V", 10, "VEDETTISAT").
dico("V", 10, "VEDETTISEE").
dico("V", 10, "VEDETTISER").
dico("V", 10, "VEDETTISES").
dico("V", 10, "VEDETTISEZ").
dico("V", 10, "VEGETAIENT").
dico("V", 10, "VEGETALIEN").
dico("V", 10, "VEGETALISA").
dico("V", 10, "VEGETALISE").
dico("V", 10, "VEGETARIEN").
dico("V", 10, "VEGETASSES").
dico("V", 10, "VEGETATIFS").
dico("V", 10, "VEGETATION").
dico("V", 10, "VEGETATIVE").
dico("V", 10, "VEGETERAIS").
dico("V", 10, "VEGETERAIT").
dico("V", 10, "VEGETERENT").
dico("V", 10, "VEGETERIEZ").
dico("V", 10, "VEGETERONS").
dico("V", 10, "VEGETERONT").
dico("V", 10, "VEHEMENCES").
dico("V", 10, "VEHEMENTES").
dico("V", 10, "VEHICULAIS").
dico("V", 10, "VEHICULAIT").
dico("V", 10, "VEHICULANT").
dico("V", 10, "VEHICULEES").
dico("V", 10, "VEHICULENT").
dico("V", 10, "VEHICULERA").
dico("V", 10, "VEHICULEUR").
dico("V", 10, "VEHICULIEZ").
dico("V", 10, "VEHICULONS").
dico("V", 10, "VEILLAIENT").
dico("V", 10, "VEILLASSES").
dico("V", 10, "VEILLERAIS").
dico("V", 10, "VEILLERAIT").
dico("V", 10, "VEILLERENT").
dico("V", 10, "VEILLERIEZ").
dico("V", 10, "VEILLERONS").
dico("V", 10, "VEILLERONT").
dico("V", 10, "VEILLEUSES").
dico("V", 10, "VEINASSENT").
dico("V", 10, "VEINASSIEZ").
dico("V", 10, "VEINERIONS").
dico("V", 10, "VEINOSITES").
dico("V", 10, "VELASSIONS").
dico("V", 10, "VELERAIENT").
dico("V", 10, "VELOCEMENT").
dico("V", 10, "VELOCIPEDE").
dico("V", 10, "VELOCISTES").
dico("V", 10, "VELODROMES").
dico("V", 10, "VELOMOTEUR").
dico("V", 10, "VELOPOUSSE").
dico("V", 10, "VELOUTAMES").
dico("V", 10, "VELOUTASSE").
dico("V", 10, "VELOUTATES").
dico("V", 10, "VELOUTERAI").
dico("V", 10, "VELOUTERAS").
dico("V", 10, "VELOUTEREZ").
dico("V", 10, "VELOUTEUSE").
dico("V", 10, "VELOUTIERS").
dico("V", 10, "VELOUTINES").
dico("V", 10, "VELOUTIONS").
dico("V", 10, "VENAISSINE").
dico("V", 10, "VENAISSINS").
dico("V", 10, "VENALEMENT").
dico("V", 10, "VENDANGEAI").
dico("V", 10, "VENDANGEAS").
dico("V", 10, "VENDANGEAT").
dico("V", 10, "VENDANGEES").
dico("V", 10, "VENDANGENT").
dico("V", 10, "VENDANGEON").
dico("V", 10, "VENDANGERA").
dico("V", 10, "VENDANGEUR").
dico("V", 10, "VENDANGIEZ").
dico("V", 10, "VENDEENNES").
dico("V", 10, "VENDERESSE").
dico("V", 10, "VENDISSENT").
dico("V", 10, "VENDISSIEZ").
dico("V", 10, "VENDRAIENT").
dico("V", 10, "VENENEUSES").
dico("V", 10, "VENENOSITE").
dico("V", 10, "VENERABLES").
dico("V", 10, "VENERAIENT").
dico("V", 10, "VENERASSES").
dico("V", 10, "VENERATION").
dico("V", 10, "VENERERAIS").
dico("V", 10, "VENERERAIT").
dico("V", 10, "VENERERENT").
dico("V", 10, "VENERERIEZ").
dico("V", 10, "VENERERONS").
dico("V", 10, "VENERERONT").
dico("V", 10, "VENERIENNE").
dico("V", 10, "VENGEAIENT").
dico("V", 10, "VENGEANCES").
dico("V", 10, "VENGEASSES").
dico("V", 10, "VENGERESSE").
dico("V", 10, "VENGERIONS").
dico("V", 10, "VENIMEUSES").
dico("V", 10, "VENIMOSITE").
dico("V", 10, "VENITIENNE").
dico("V", 10, "VENTAILLES").
dico("V", 10, "VENTILAMES").
dico("V", 10, "VENTILASSE").
dico("V", 10, "VENTILATES").
dico("V", 10, "VENTILERAI").
dico("V", 10, "VENTILERAS").
dico("V", 10, "VENTILEREZ").
dico("V", 10, "VENTILEUSE").
dico("V", 10, "VENTILIONS").
dico("V", 10, "VENTREBLEU").
dico("V", 10, "VENTRECHES").
dico("V", 10, "VENTRICULE").
dico("V", 10, "VENTRIERES").
dico("V", 10, "VENUSIENNE").
dico("V", 10, "VEPECISTES").
dico("V", 10, "VERATRINES").
dico("V", 10, "VERBALISAI").
dico("V", 10, "VERBALISAS").
dico("V", 10, "VERBALISAT").
dico("V", 10, "VERBALISEE").
dico("V", 10, "VERBALISER").
dico("V", 10, "VERBALISES").
dico("V", 10, "VERBALISEZ").
dico("V", 10, "VERBALISME").
dico("V", 10, "VERBENACEE").
dico("V", 10, "VERBOMANIE").
dico("V", 10, "VERBOQUETS").
dico("V", 10, "VERBOSITES").
dico("V", 10, "VERDELETTE").
dico("V", 10, "VERDIRIONS").
dico("V", 10, "VERDISSAGE").
dico("V", 10, "VERDISSAIS").
dico("V", 10, "VERDISSAIT").
dico("V", 10, "VERDISSANT").
dico("V", 10, "VERDISSENT").
dico("V", 10, "VERDISSIEZ").
dico("V", 10, "VERDISSONS").
dico("V", 10, "VERDOIERAI").
dico("V", 10, "VERDOIERAS").
dico("V", 10, "VERDOIEREZ").
dico("V", 10, "VERDOYAMES").
dico("V", 10, "VERDOYANTE").
dico("V", 10, "VERDOYANTS").
dico("V", 10, "VERDOYASSE").
dico("V", 10, "VERDOYATES").
dico("V", 10, "VERDOYIONS").
dico("V", 10, "VERDUNISAI").
dico("V", 10, "VERDUNISAS").
dico("V", 10, "VERDUNISAT").
dico("V", 10, "VERDUNISEE").
dico("V", 10, "VERDUNISER").
dico("V", 10, "VERDUNISES").
dico("V", 10, "VERDUNISEZ").
dico("V", 10, "VERDURIERE").
dico("V", 10, "VERDURIERS").
dico("V", 10, "VERETILLES").
dico("V", 10, "VERGEOISES").
dico("V", 10, "VERGERETTE").
dico("V", 10, "VERGETIERS").
dico("V", 10, "VERGETURES").
dico("V", 10, "VERGLACAIT").
dico("V", 10, "VERGLACANT").
dico("V", 10, "VERGLACEES").
dico("V", 10, "VERGLACERA").
dico("V", 10, "VERGOBRETS").
dico("V", 10, "VERIDICITE").
dico("V", 10, "VERIDIQUES").
dico("V", 10, "VERIFIABLE").
dico("V", 10, "VERIFIAMES").
dico("V", 10, "VERIFIASSE").
dico("V", 10, "VERIFIATES").
dico("V", 10, "VERIFIERAI").
dico("V", 10, "VERIFIERAS").
dico("V", 10, "VERIFIEREZ").
dico("V", 10, "VERIFIEURS").
dico("V", 10, "VERIFIEUSE").
dico("V", 10, "VERIFIIONS").
dico("V", 10, "VERITABLES").
dico("V", 10, "VERJUTAMES").
dico("V", 10, "VERJUTASSE").
dico("V", 10, "VERJUTATES").
dico("V", 10, "VERJUTERAI").
dico("V", 10, "VERJUTERAS").
dico("V", 10, "VERJUTEREZ").
dico("V", 10, "VERJUTIONS").
dico("V", 10, "VERMEILLES").
dico("V", 10, "VERMICELLE").
dico("V", 10, "VERMICIDES").
dico("V", 10, "VERMICULEE").
dico("V", 10, "VERMICULES").
dico("V", 10, "VERMIDIENS").
dico("V", 10, "VERMIFORME").
dico("V", 10, "VERMIFUGEA").
dico("V", 10, "VERMIFUGEE").
dico("V", 10, "VERMIFUGER").
dico("V", 10, "VERMIFUGES").
dico("V", 10, "VERMIFUGEZ").
dico("V", 10, "VERMILLAIS").
dico("V", 10, "VERMILLAIT").
dico("V", 10, "VERMILLANT").
dico("V", 10, "VERMILLENT").
dico("V", 10, "VERMILLERA").
dico("V", 10, "VERMILLIEZ").
dico("V", 10, "VERMILLONS").
dico("V", 10, "VERMINEUSE").
dico("V", 10, "VERMINOSES").
dico("V", 10, "VERMISSEAU").
dico("V", 10, "VERMIVORES").
dico("V", 10, "VERMOULAIS").
dico("V", 10, "VERMOULAIT").
dico("V", 10, "VERMOULANT").
dico("V", 10, "VERMOULEES").
dico("V", 10, "VERMOULENT").
dico("V", 10, "VERMOULERA").
dico("V", 10, "VERMOULIEZ").
dico("V", 10, "VERMOULONS").
dico("V", 10, "VERMOULUES").
dico("V", 10, "VERMOULURE").
dico("V", 10, "VERNATIONS").
dico("V", 10, "VERNIRIONS").
dico("V", 10, "VERNISSAGE").
dico("V", 10, "VERNISSAIS").
dico("V", 10, "VERNISSAIT").
dico("V", 10, "VERNISSANT").
dico("V", 10, "VERNISSEES").
dico("V", 10, "VERNISSENT").
dico("V", 10, "VERNISSERA").
dico("V", 10, "VERNISSEUR").
dico("V", 10, "VERNISSIEZ").
dico("V", 10, "VERNISSONS").
dico("V", 10, "VEROLAIENT").
dico("V", 10, "VEROLASSES").
dico("V", 10, "VEROLERAIS").
dico("V", 10, "VEROLERAIT").
dico("V", 10, "VEROLERENT").
dico("V", 10, "VEROLERIEZ").
dico("V", 10, "VEROLERONS").
dico("V", 10, "VEROLERONT").
dico("V", 10, "VEROLEUSES").
dico("V", 10, "VERONAISES").
dico("V", 10, "VERONIQUES").
dico("V", 10, "VERROTERIE").
dico("V", 10, "VERROUILLA").
dico("V", 10, "VERROUILLE").
dico("V", 10, "VERRUCAIRE").
dico("V", 10, "VERRUQUEUX").
dico("V", 10, "VERSASSENT").
dico("V", 10, "VERSASSIEZ").
dico("V", 10, "VERSATILES").
dico("V", 10, "VERSEMENTS").
dico("V", 10, "VERSERIONS").
dico("V", 10, "VERSIFIAIS").
dico("V", 10, "VERSIFIAIT").
dico("V", 10, "VERSIFIANT").
dico("V", 10, "VERSIFIEES").
dico("V", 10, "VERSIFIENT").
dico("V", 10, "VERSIFIERA").
dico("V", 10, "VERSIFIIEZ").
dico("V", 10, "VERSIFIONS").
dico("V", 10, "VERTEBRALE").
dico("V", 10, "VERTEBRAUX").
dico("V", 10, "VERTEBREES").
dico("V", 10, "VERTICALES").
dico("V", 10, "VERTICILLE").
dico("V", 10, "VERTICITES").
dico("V", 10, "VERTUEUSES").
dico("V", 10, "VERTUGADIN").
dico("V", 10, "VERVIETOIS").
dico("V", 10, "VESANIQUES").
dico("V", 10, "VESICANTES").
dico("V", 10, "VESICATION").
dico("V", 10, "VESICULEES").
dico("V", 10, "VESICULEUX").
dico("V", 10, "VESPERALES").
dico("V", 10, "VESSASSENT").
dico("V", 10, "VESSASSIEZ").
dico("V", 10, "VESSERIONS").
dico("V", 10, "VESTIAIRES").
dico("V", 10, "VESTIBULES").
dico("V", 10, "VESTIGIALE").
dico("V", 10, "VESTIGIAUX").
dico("V", 10, "VESULIENNE").
dico("V", 10, "VETECISTES").
dico("V", 10, "VETERANCES").
dico("V", 10, "VETETISTES").
dico("V", 10, "VETILLAMES").
dico("V", 10, "VETILLARDE").
dico("V", 10, "VETILLARDS").
dico("V", 10, "VETILLASSE").
dico("V", 10, "VETILLATES").
dico("V", 10, "VETILLERAI").
dico("V", 10, "VETILLERAS").
dico("V", 10, "VETILLEREZ").
dico("V", 10, "VETILLEUSE").
dico("V", 10, "VETILLIONS").
dico("V", 10, "VETIRAIENT").
dico("V", 10, "VETISSIONS").
dico("V", 10, "VEUGLAIRES").
dico("V", 10, "VEXASSIONS").
dico("V", 10, "VEXATOIRES").
dico("V", 10, "VEXATRICES").
dico("V", 10, "VEXERAIENT").
dico("V", 10, "VEXILLAIRE").
dico("V", 10, "VIABILISAI").
dico("V", 10, "VIABILISAS").
dico("V", 10, "VIABILISAT").
dico("V", 10, "VIABILISEE").
dico("V", 10, "VIABILISER").
dico("V", 10, "VIABILISES").
dico("V", 10, "VIABILISEZ").
dico("V", 10, "VIABILITES").
dico("V", 10, "VIANDAIENT").
dico("V", 10, "VIANDASSES").
dico("V", 10, "VIANDERAIS").
dico("V", 10, "VIANDERAIT").
dico("V", 10, "VIANDERENT").
dico("V", 10, "VIANDERIEZ").
dico("V", 10, "VIANDERONS").
dico("V", 10, "VIANDERONT").
dico("V", 10, "VIANDEUSES").
dico("V", 10, "VIBRAPHONE").
dico("V", 10, "VIBRASSENT").
dico("V", 10, "VIBRASSIEZ").
dico("V", 10, "VIBRATEURS").
dico("V", 10, "VIBRATILES").
dico("V", 10, "VIBRATIONS").
dico("V", 10, "VIBRATOIRE").
dico("V", 10, "VIBRERIONS").
dico("V", 10, "VIBRIONNAI").
dico("V", 10, "VIBRIONNAS").
dico("V", 10, "VIBRIONNAT").
dico("V", 10, "VIBRIONNER").
dico("V", 10, "VIBRIONNES").
dico("V", 10, "VIBRIONNEZ").
dico("V", 10, "VICARIALES").
dico("V", 10, "VICARIANCE").
dico("V", 10, "VICARIANTE").
dico("V", 10, "VICARIANTS").
dico("V", 10, "VICELARDES").
dico("V", 10, "VICENNALES").
dico("V", 10, "VICENTINES").
dico("V", 10, "VICESIMALE").
dico("V", 10, "VICESIMAUX").
dico("V", 10, "VICHYSSOIS").
dico("V", 10, "VICIASSENT").
dico("V", 10, "VICIASSIEZ").
dico("V", 10, "VICIATEURS").
dico("V", 10, "VICIATIONS").
dico("V", 10, "VICIATRICE").
dico("V", 10, "VICIERIONS").
dico("V", 10, "VICINALITE").
dico("V", 10, "VICOMTALES").
dico("V", 10, "VICOMTESSE").
dico("V", 10, "VICTIMAIRE").
dico("V", 10, "VICTIMISAI").
dico("V", 10, "VICTIMISAS").
dico("V", 10, "VICTIMISAT").
dico("V", 10, "VICTIMISEE").
dico("V", 10, "VICTIMISER").
dico("V", 10, "VICTIMISES").
dico("V", 10, "VICTIMISEZ").
dico("V", 10, "VICTORIENS").
dico("V", 10, "VICTORIEUX").
dico("V", 10, "VICTUAILLE").
dico("V", 10, "VIDANGEAIS").
dico("V", 10, "VIDANGEAIT").
dico("V", 10, "VIDANGEANT").
dico("V", 10, "VIDANGEONS").
dico("V", 10, "VIDANGERAI").
dico("V", 10, "VIDANGERAS").
dico("V", 10, "VIDANGEREZ").
dico("V", 10, "VIDANGEURS").
dico("V", 10, "VIDANGEUSE").
dico("V", 10, "VIDANGIONS").
dico("V", 10, "VIDASSIONS").
dico("V", 10, "VIDEOCABLE").
dico("V", 10, "VIDEOCLIPS").
dico("V", 10, "VIDEOCLUBS").
dico("V", 10, "VIDEOPHONE").
dico("V", 10, "VIDERAIENT").
dico("V", 10, "VIDIMAIENT").
dico("V", 10, "VIDIMASSES").
dico("V", 10, "VIDIMERAIS").
dico("V", 10, "VIDIMERAIT").
dico("V", 10, "VIDIMERENT").
dico("V", 10, "VIDIMERIEZ").
dico("V", 10, "VIDIMERONS").
dico("V", 10, "VIDIMERONT").
dico("V", 10, "VIDRECOMES").
dico("V", 10, "VIEILLARDE").
dico("V", 10, "VIEILLARDS").
dico("V", 10, "VIEILLERIE").
dico("V", 10, "VIEILLESSE").
dico("V", 10, "VIEILLIMES").
dico("V", 10, "VIEILLIRAI").
dico("V", 10, "VIEILLIRAS").
dico("V", 10, "VIEILLIREZ").
dico("V", 10, "VIEILLISSE").
dico("V", 10, "VIEILLITES").
dico("V", 10, "VIEILLOTTE").
dico("V", 10, "VIELLAIENT").
dico("V", 10, "VIELLASSES").
dico("V", 10, "VIELLERAIS").
dico("V", 10, "VIELLERAIT").
dico("V", 10, "VIELLERENT").
dico("V", 10, "VIELLERIEZ").
dico("V", 10, "VIELLERONS").
dico("V", 10, "VIELLERONT").
dico("V", 10, "VIELLEUSES").
dico("V", 10, "VIENDRIONS").
dico("V", 10, "VIENNOISES").
dico("V", 10, "VIETNAMIEN").
dico("V", 10, "VIGILANCES").
dico("V", 10, "VIGILANTES").
dico("V", 10, "VIGNERONNE").
dico("V", 10, "VIGNETAGES").
dico("V", 10, "VIGNETAMES").
dico("V", 10, "VIGNETASSE").
dico("V", 10, "VIGNETATES").
dico("V", 10, "VIGNETIONS").
dico("V", 10, "VIGNETTAGE").
dico("V", 10, "VIGNETTENT").
dico("V", 10, "VIGNETTERA").
dico("V", 10, "VIGNETURES").
dico("V", 10, "VIGOUREUSE").
dico("V", 10, "VILIPENDAI").
dico("V", 10, "VILIPENDAS").
dico("V", 10, "VILIPENDAT").
dico("V", 10, "VILIPENDEE").
dico("V", 10, "VILIPENDER").
dico("V", 10, "VILIPENDES").
dico("V", 10, "VILIPENDEZ").
dico("V", 10, "VILLAGEOIS").
dico("V", 10, "VILLANELLE").
dico("V", 10, "VILLOSITES").
dico("V", 10, "VINAIGRAIS").
dico("V", 10, "VINAIGRAIT").
dico("V", 10, "VINAIGRANT").
dico("V", 10, "VINAIGREES").
dico("V", 10, "VINAIGRENT").
dico("V", 10, "VINAIGRERA").
dico("V", 10, "VINAIGRIER").
dico("V", 10, "VINAIGRIEZ").
dico("V", 10, "VINAIGRONS").
dico("V", 10, "VINASSIONS").
dico("V", 10, "VINCAMINES").
dico("V", 10, "VINDICATIF").
dico("V", 10, "VINERAIENT").
dico("V", 10, "VINGTAINES").
dico("V", 10, "VINGTIEMES").
dico("V", 10, "VINIFIAMES").
dico("V", 10, "VINIFIASSE").
dico("V", 10, "VINIFIATES").
dico("V", 10, "VINIFIERAI").
dico("V", 10, "VINIFIERAS").
dico("V", 10, "VINIFIEREZ").
dico("V", 10, "VINIFIIONS").
dico("V", 10, "VINYLIQUES").
dico("V", 10, "VIOLACAMES").
dico("V", 10, "VIOLACASSE").
dico("V", 10, "VIOLACATES").
dico("V", 10, "VIOLACERAI").
dico("V", 10, "VIOLACERAS").
dico("V", 10, "VIOLACEREZ").
dico("V", 10, "VIOLACIONS").
dico("V", 10, "VIOLASSENT").
dico("V", 10, "VIOLASSIEZ").
dico("V", 10, "VIOLATEURS").
dico("V", 10, "VIOLATIONS").
dico("V", 10, "VIOLATRICE").
dico("V", 10, "VIOLEMMENT").
dico("V", 10, "VIOLENTAIS").
dico("V", 10, "VIOLENTAIT").
dico("V", 10, "VIOLENTANT").
dico("V", 10, "VIOLENTEES").
dico("V", 10, "VIOLENTENT").
dico("V", 10, "VIOLENTERA").
dico("V", 10, "VIOLENTIEZ").
dico("V", 10, "VIOLENTONS").
dico("V", 10, "VIOLERIONS").
dico("V", 10, "VIOLETAMES").
dico("V", 10, "VIOLETASSE").
dico("V", 10, "VIOLETATES").
dico("V", 10, "VIOLETIONS").
dico("V", 10, "VIOLETTENT").
dico("V", 10, "VIOLETTERA").
dico("V", 10, "VIOLONAMES").
dico("V", 10, "VIOLONASSE").
dico("V", 10, "VIOLONATES").
dico("V", 10, "VIOLONERAI").
dico("V", 10, "VIOLONERAS").
dico("V", 10, "VIOLONEREZ").
dico("V", 10, "VIOLONIONS").
dico("V", 10, "VIOLONISTE").
dico("V", 10, "VIRAILLAIS").
dico("V", 10, "VIRAILLAIT").
dico("V", 10, "VIRAILLANT").
dico("V", 10, "VIRAILLENT").
dico("V", 10, "VIRAILLERA").
dico("V", 10, "VIRAILLEUR").
dico("V", 10, "VIRAILLIEZ").
dico("V", 10, "VIRAILLONS").
dico("V", 10, "VIRASSIONS").
dico("V", 10, "VIRERAIENT").
dico("V", 10, "VIRESCENCE").
dico("V", 10, "VIREVOLTAI").
dico("V", 10, "VIREVOLTAS").
dico("V", 10, "VIREVOLTAT").
dico("V", 10, "VIREVOLTER").
dico("V", 10, "VIREVOLTES").
dico("V", 10, "VIREVOLTEZ").
dico("V", 10, "VIRGINALES").
dico("V", 10, "VIRGINITES").
dico("V", 10, "VIRGULAMES").
dico("V", 10, "VIRGULASSE").
dico("V", 10, "VIRGULATES").
dico("V", 10, "VIRGULERAI").
dico("V", 10, "VIRGULERAS").
dico("V", 10, "VIRGULEREZ").
dico("V", 10, "VIRGULIONS").
dico("V", 10, "VIRILEMENT").
dico("V", 10, "VIRILISAIS").
dico("V", 10, "VIRILISAIT").
dico("V", 10, "VIRILISANT").
dico("V", 10, "VIRILISEES").
dico("V", 10, "VIRILISENT").
dico("V", 10, "VIRILISERA").
dico("V", 10, "VIRILISIEZ").
dico("V", 10, "VIRILISMES").
dico("V", 10, "VIRILISONS").
dico("V", 10, "VIRILOCALE").
dico("V", 10, "VIRILOCAUX").
dico("V", 10, "VIROLAIENT").
dico("V", 10, "VIROLASSES").
dico("V", 10, "VIROLERAIS").
dico("V", 10, "VIROLERAIT").
dico("V", 10, "VIROLERENT").
dico("V", 10, "VIROLERIEZ").
dico("V", 10, "VIROLERONS").
dico("V", 10, "VIROLERONT").
dico("V", 10, "VIROLIERES").
dico("V", 10, "VIROLOGIES").
dico("V", 10, "VIROLOGUES").
dico("V", 10, "VIRTUALITE").
dico("V", 10, "VIRTUELLES").
dico("V", 10, "VIRTUOSITE").
dico("V", 10, "VIRULENCES").
dico("V", 10, "VIRULENTES").
dico("V", 10, "VIRULICIDE").
dico("V", 10, "VISAGISMES").
dico("V", 10, "VISAGISTES").
dico("V", 10, "VISASSIONS").
dico("V", 10, "VISCERALES").
dico("V", 10, "VISCOSITES").
dico("V", 10, "VISERAIENT").
dico("V", 10, "VISIBILITE").
dico("V", 10, "VISIGOTHES").
dico("V", 10, "VISIONIQUE").
dico("V", 10, "VISIONNAGE").
dico("V", 10, "VISIONNAIS").
dico("V", 10, "VISIONNAIT").
dico("V", 10, "VISIONNANT").
dico("V", 10, "VISIONNEES").
dico("V", 10, "VISIONNENT").
dico("V", 10, "VISIONNERA").
dico("V", 10, "VISIONNIEZ").
dico("V", 10, "VISIONNONS").
dico("V", 10, "VISIOPHONE").
dico("V", 10, "VISITAIENT").
dico("V", 10, "VISITASSES").
dico("V", 10, "VISITATEUR").
dico("V", 10, "VISITATION").
dico("V", 10, "VISITERAIS").
dico("V", 10, "VISITERAIT").
dico("V", 10, "VISITERENT").
dico("V", 10, "VISITERIEZ").
dico("V", 10, "VISITERONS").
dico("V", 10, "VISITERONT").
dico("V", 10, "VISITEUSES").
dico("V", 10, "VISNUISMES").
dico("V", 10, "VISONNIERE").
dico("V", 10, "VISQUEUSES").
dico("V", 10, "VISSASSENT").
dico("V", 10, "VISSASSIEZ").
dico("V", 10, "VISSERIONS").
dico("V", 10, "VISUALISAI").
dico("V", 10, "VISUALISAS").
dico("V", 10, "VISUALISAT").
dico("V", 10, "VISUALISEE").
dico("V", 10, "VISUALISER").
dico("V", 10, "VISUALISES").
dico("V", 10, "VISUALISEZ").
dico("V", 10, "VITALISMES").
dico("V", 10, "VITALISTES").
dico("V", 10, "VITAMINAIS").
dico("V", 10, "VITAMINAIT").
dico("V", 10, "VITAMINANT").
dico("V", 10, "VITAMINEES").
dico("V", 10, "VITAMINENT").
dico("V", 10, "VITAMINERA").
dico("V", 10, "VITAMINIEZ").
dico("V", 10, "VITAMINONS").
dico("V", 10, "VITELLINES").
dico("V", 10, "VITELOTTES").
dico("V", 10, "VITRASSENT").
dico("V", 10, "VITRASSIEZ").
dico("V", 10, "VITRERIONS").
dico("V", 10, "VITRIFIAIS").
dico("V", 10, "VITRIFIAIT").
dico("V", 10, "VITRIFIANT").
dico("V", 10, "VITRIFIEES").
dico("V", 10, "VITRIFIENT").
dico("V", 10, "VITRIFIERA").
dico("V", 10, "VITRIFIIEZ").
dico("V", 10, "VITRIFIONS").
dico("V", 10, "VITRIOLAGE").
dico("V", 10, "VITRIOLAIS").
dico("V", 10, "VITRIOLAIT").
dico("V", 10, "VITRIOLANT").
dico("V", 10, "VITRIOLEES").
dico("V", 10, "VITRIOLENT").
dico("V", 10, "VITRIOLERA").
dico("V", 10, "VITRIOLEUR").
dico("V", 10, "VITRIOLIEZ").
dico("V", 10, "VITRIOLONS").
dico("V", 10, "VITULAIRES").
dico("V", 10, "VITUPERAIS").
dico("V", 10, "VITUPERAIT").
dico("V", 10, "VITUPERANT").
dico("V", 10, "VITUPEREES").
dico("V", 10, "VITUPERENT").
dico("V", 10, "VITUPERERA").
dico("V", 10, "VITUPERIEZ").
dico("V", 10, "VITUPERONS").
dico("V", 10, "VIVANDIERE").
dico("V", 10, "VIVANDIERS").
dico("V", 10, "VIVARAISES").
dico("V", 10, "VIVERRIDES").
dico("V", 10, "VIVIFIAMES").
dico("V", 10, "VIVIFIANTE").
dico("V", 10, "VIVIFIANTS").
dico("V", 10, "VIVIFIASSE").
dico("V", 10, "VIVIFIATES").
dico("V", 10, "VIVIFIERAI").
dico("V", 10, "VIVIFIERAS").
dico("V", 10, "VIVIFIEREZ").
dico("V", 10, "VIVIFIIONS").
dico("V", 10, "VIVIPARITE").
dico("V", 10, "VIVOTAIENT").
dico("V", 10, "VIVOTASSES").
dico("V", 10, "VIVOTERAIS").
dico("V", 10, "VIVOTERAIT").
dico("V", 10, "VIVOTERENT").
dico("V", 10, "VIVOTERIEZ").
dico("V", 10, "VIVOTERONS").
dico("V", 10, "VIVOTERONT").
dico("V", 10, "VOBULATEUR").
dico("V", 10, "VOCALEMENT").
dico("V", 10, "VOCALIQUES").
dico("V", 10, "VOCALISAIS").
dico("V", 10, "VOCALISAIT").
dico("V", 10, "VOCALISANT").
dico("V", 10, "VOCALISEES").
dico("V", 10, "VOCALISENT").
dico("V", 10, "VOCALISERA").
dico("V", 10, "VOCALISIEZ").
dico("V", 10, "VOCALISMES").
dico("V", 10, "VOCALISONS").
dico("V", 10, "VOCALISTES").
dico("V", 10, "VOCIFERAIS").
dico("V", 10, "VOCIFERAIT").
dico("V", 10, "VOCIFERANT").
dico("V", 10, "VOCIFEREES").
dico("V", 10, "VOCIFERENT").
dico("V", 10, "VOCIFERERA").
dico("V", 10, "VOCIFERIEZ").
dico("V", 10, "VOCIFERONS").
dico("V", 10, "VOGUASSENT").
dico("V", 10, "VOGUASSIEZ").
dico("V", 10, "VOGUERIONS").
dico("V", 10, "VOIEVODATS").
dico("V", 10, "VOIEVODIES").
dico("V", 10, "VOILASSENT").
dico("V", 10, "VOILASSIEZ").
dico("V", 10, "VOILEMENTS").
dico("V", 10, "VOILERIONS").
dico("V", 10, "VOISEMENTS").
dico("V", 10, "VOISINAGES").
dico("V", 10, "VOISINAMES").
dico("V", 10, "VOISINASSE").
dico("V", 10, "VOISINATES").
dico("V", 10, "VOISINERAI").
dico("V", 10, "VOISINERAS").
dico("V", 10, "VOISINEREZ").
dico("V", 10, "VOISINIONS").
dico("V", 10, "VOITURAGES").
dico("V", 10, "VOITURAMES").
dico("V", 10, "VOITURASSE").
dico("V", 10, "VOITURATES").
dico("V", 10, "VOITURERAI").
dico("V", 10, "VOITURERAS").
dico("V", 10, "VOITUREREZ").
dico("V", 10, "VOITURETTE").
dico("V", 10, "VOITURIERE").
dico("V", 10, "VOITURIERS").
dico("V", 10, "VOITURIONS").
dico("V", 10, "VOLAILLERE").
dico("V", 10, "VOLAILLERS").
dico("V", 10, "VOLAILLEUR").
dico("V", 10, "VOLASSIONS").
dico("V", 10, "VOLATILISA").
dico("V", 10, "VOLATILISE").
dico("V", 10, "VOLATILITE").
dico("V", 10, "VOLCANIQUE").
dico("V", 10, "VOLCANISAI").
dico("V", 10, "VOLCANISAS").
dico("V", 10, "VOLCANISAT").
dico("V", 10, "VOLCANISEE").
dico("V", 10, "VOLCANISER").
dico("V", 10, "VOLCANISES").
dico("V", 10, "VOLCANISEZ").
dico("V", 10, "VOLCANISME").
dico("V", 10, "VOLERAIENT").
dico("V", 10, "VOLETAIENT").
dico("V", 10, "VOLETANTES").
dico("V", 10, "VOLETASSES").
dico("V", 10, "VOLETERENT").
dico("V", 10, "VOLETTERAI").
dico("V", 10, "VOLETTERAS").
dico("V", 10, "VOLETTEREZ").
dico("V", 10, "VOLIGEAGES").
dico("V", 10, "VOLIGEAMES").
dico("V", 10, "VOLIGEASSE").
dico("V", 10, "VOLIGEATES").
dico("V", 10, "VOLIGERAIS").
dico("V", 10, "VOLIGERAIT").
dico("V", 10, "VOLIGERENT").
dico("V", 10, "VOLIGERIEZ").
dico("V", 10, "VOLIGERONS").
dico("V", 10, "VOLIGERONT").
dico("V", 10, "VOLLEYAMES").
dico("V", 10, "VOLLEYASSE").
dico("V", 10, "VOLLEYATES").
dico("V", 10, "VOLLEYERAI").
dico("V", 10, "VOLLEYERAS").
dico("V", 10, "VOLLEYEREZ").
dico("V", 10, "VOLLEYEURS").
dico("V", 10, "VOLLEYEUSE").
dico("V", 10, "VOLLEYIONS").
dico("V", 10, "VOLONTAIRE").
dico("V", 10, "VOLONTIERS").
dico("V", 10, "VOLTAIQUES").
dico("V", 10, "VOLTAIRIEN").
dico("V", 10, "VOLTAMETRE").
dico("V", 10, "VOLTAMPERE").
dico("V", 10, "VOLTASSENT").
dico("V", 10, "VOLTASSIEZ").
dico("V", 10, "VOLTERIONS").
dico("V", 10, "VOLTIGEAIS").
dico("V", 10, "VOLTIGEAIT").
dico("V", 10, "VOLTIGEANT").
dico("V", 10, "VOLTIGEONS").
dico("V", 10, "VOLTIGERAI").
dico("V", 10, "VOLTIGERAS").
dico("V", 10, "VOLTIGEREZ").
dico("V", 10, "VOLTIGEURS").
dico("V", 10, "VOLTIGEUSE").
dico("V", 10, "VOLTIGIONS").
dico("V", 10, "VOLTMETRES").
dico("V", 10, "VOLUBILITE").
dico("V", 10, "VOLUCELLES").
dico("V", 10, "VOLUMETRES").
dico("V", 10, "VOLUMETRIE").
dico("V", 10, "VOLUMINEUX").
dico("V", 10, "VOLUMIQUES").
dico("V", 10, "VOLUPTUEUX").
dico("V", 10, "VOLVATIONS").
dico("V", 10, "VOLVOCALES").
dico("V", 10, "VOMERIENNE").
dico("V", 10, "VOMIQUIERS").
dico("V", 10, "VOMIRAIENT").
dico("V", 10, "VOMISSIONS").
dico("V", 10, "VOMISSURES").
dico("V", 10, "VOMITOIRES").
dico("V", 10, "VORACEMENT").
dico("V", 10, "VORTICELLE").
dico("V", 10, "VOSGIENNES").
dico("V", 10, "VOTASSIONS").
dico("V", 10, "VOTERAIENT").
dico("V", 10, "VOUASSIONS").
dico("V", 10, "VOUDRAIENT").
dico("V", 10, "VOUERAIENT").
dico("V", 10, "VOULUSSENT").
dico("V", 10, "VOULUSSIEZ").
dico("V", 10, "VOUSOIERAI").
dico("V", 10, "VOUSOIERAS").
dico("V", 10, "VOUSOIEREZ").
dico("V", 10, "VOUSOYAMES").
dico("V", 10, "VOUSOYASSE").
dico("V", 10, "VOUSOYATES").
dico("V", 10, "VOUSOYIONS").
dico("V", 10, "VOUSSOIENT").
dico("V", 10, "VOUSSOIERA").
dico("V", 10, "VOUSSOYAIS").
dico("V", 10, "VOUSSOYAIT").
dico("V", 10, "VOUSSOYANT").
dico("V", 10, "VOUSSOYEES").
dico("V", 10, "VOUSSOYIEZ").
dico("V", 10, "VOUSSOYONS").
dico("V", 10, "VOUTASSENT").
dico("V", 10, "VOUTASSIEZ").
dico("V", 10, "VOUTEMENTS").
dico("V", 10, "VOUTERIONS").
dico("V", 10, "VOUVOIERAI").
dico("V", 10, "VOUVOIERAS").
dico("V", 10, "VOUVOIEREZ").
dico("V", 10, "VOUVOYAMES").
dico("V", 10, "VOUVOYASSE").
dico("V", 10, "VOUVOYATES").
dico("V", 10, "VOUVOYIONS").
dico("V", 10, "VOYAGEAGES").
dico("V", 10, "VOYAGEAMES").
dico("V", 10, "VOYAGEASSE").
dico("V", 10, "VOYAGEATES").
dico("V", 10, "VOYAGEMENT").
dico("V", 10, "VOYAGERAIS").
dico("V", 10, "VOYAGERAIT").
dico("V", 10, "VOYAGERENT").
dico("V", 10, "VOYAGERIEZ").
dico("V", 10, "VOYAGERONS").
dico("V", 10, "VOYAGERONT").
dico("V", 10, "VOYAGEUSES").
dico("V", 10, "VOYAGISTES").
dico("V", 10, "VOYEURISME").
dico("V", 10, "VOYEURISTE").
dico("V", 10, "VRILLAIENT").
dico("V", 10, "VRILLASSES").
dico("V", 10, "VRILLERAIS").
dico("V", 10, "VRILLERAIT").
dico("V", 10, "VRILLERENT").
dico("V", 10, "VRILLERIEZ").
dico("V", 10, "VRILLERONS").
dico("V", 10, "VRILLERONT").
dico("V", 10, "VRILLETTES").
dico("V", 10, "VROMBIRAIS").
dico("V", 10, "VROMBIRAIT").
dico("V", 10, "VROMBIRENT").
dico("V", 10, "VROMBIRIEZ").
dico("V", 10, "VROMBIRONS").
dico("V", 10, "VROMBIRONT").
dico("V", 10, "VROMBISSES").
dico("V", 10, "VROMBISSEZ").
dico("V", 10, "VULCANALES").
dico("V", 10, "VULCANIENS").
dico("V", 10, "VULCANISAI").
dico("V", 10, "VULCANISAS").
dico("V", 10, "VULCANISAT").
dico("V", 10, "VULCANISEE").
dico("V", 10, "VULCANISER").
dico("V", 10, "VULCANISES").
dico("V", 10, "VULCANISEZ").
dico("V", 10, "VULGARISAI").
dico("V", 10, "VULGARISAS").
dico("V", 10, "VULGARISAT").
dico("V", 10, "VULGARISEE").
dico("V", 10, "VULGARISER").
dico("V", 10, "VULGARISES").
dico("V", 10, "VULGARISEZ").
dico("V", 10, "VULGARISME").
dico("V", 10, "VULGARITES").
dico("V", 10, "VULNERABLE").
dico("V", 10, "VULNERAIRE").
dico("V", 10, "VULNERANTE").
dico("V", 10, "VULNERANTS").
dico("V", 10, "VULTUEUSES").
dico("V", 10, "VULTUOSITE").
