dico("V", 5, "VACHA").
dico("V", 5, "VACHE").
dico("V", 5, "VAGAL").
dico("V", 5, "VAGIN").
dico("V", 5, "VAGIR").
dico("V", 5, "VAGIS").
dico("V", 5, "VAGIT").
dico("V", 5, "VAGUA").
dico("V", 5, "VAGUE").
dico("V", 5, "VAINC").
dico("V", 5, "VAINE").
dico("V", 5, "VAINS").
dico("V", 5, "VAIRE").
dico("V", 5, "VAIRS").
dico("V", 5, "VALET").
dico("V", 5, "VALEZ").
dico("V", 5, "VALGA").
dico("V", 5, "VALSA").
dico("V", 5, "VALSE").
dico("V", 5, "VALUE").
dico("V", 5, "VALUS").
dico("V", 5, "VALUT").
dico("V", 5, "VALVE").
dico("V", 5, "VAMPA").
dico("V", 5, "VAMPE").
dico("V", 5, "VAMPS").
dico("V", 5, "VANDA").
dico("V", 5, "VANNA").
dico("V", 5, "VANNE").
dico("V", 5, "VANTA").
dico("V", 5, "VANTE").
dico("V", 5, "VAPES").
dico("V", 5, "VAQUA").
dico("V", 5, "VAQUE").
dico("V", 5, "VARAN").
dico("V", 5, "VARIA").
dico("V", 5, "VARIE").
dico("V", 5, "VARON").
dico("V", 5, "VARUS").
dico("V", 5, "VARVE").
dico("V", 5, "VASES").
dico("V", 5, "VASTE").
dico("V", 5, "VATUS").
dico("V", 5, "VEAUX").
dico("V", 5, "VECES").
dico("V", 5, "VECUE").
dico("V", 5, "VECUS").
dico("V", 5, "VECUT").
dico("V", 5, "VEDAS").
dico("V", 5, "VEINA").
dico("V", 5, "VEINE").
dico("V", 5, "VELAI").
dico("V", 5, "VELAR").
dico("V", 5, "VELAS").
dico("V", 5, "VELAT").
dico("V", 5, "VELDS").
dico("V", 5, "VELDT").
dico("V", 5, "VELER").
dico("V", 5, "VELES").
dico("V", 5, "VELET").
dico("V", 5, "VELEZ").
dico("V", 5, "VELIE").
dico("V", 5, "VELIN").
dico("V", 5, "VELOS").
dico("V", 5, "VELOT").
dico("V", 5, "VELTE").
dico("V", 5, "VELUE").
dico("V", 5, "VELUM").
dico("V", 5, "VELUS").
dico("V", 5, "VELUX").
dico("V", 5, "VENAL").
dico("V", 5, "VENDE").
dico("V", 5, "VENDS").
dico("V", 5, "VENDU").
dico("V", 5, "VENET").
dico("V", 5, "VENEZ").
dico("V", 5, "VENGE").
dico("V", 5, "VENIN").
dico("V", 5, "VENIR").
dico("V", 5, "VENTA").
dico("V", 5, "VENTE").
dico("V", 5, "VENTS").
dico("V", 5, "VENUE").
dico("V", 5, "VENUS").
dico("V", 5, "VERBE").
dico("V", 5, "VERDI").
dico("V", 5, "VERGE").
dico("V", 5, "VERIF").
dico("V", 5, "VERIN").
dico("V", 5, "VERNE").
dico("V", 5, "VERNI").
dico("V", 5, "VERRA").
dico("V", 5, "VERRE").
dico("V", 5, "VERSA").
dico("V", 5, "VERSE").
dico("V", 5, "VERSO").
dico("V", 5, "VERTE").
dico("V", 5, "VERTS").
dico("V", 5, "VERTU").
dico("V", 5, "VERVE").
dico("V", 5, "VESCE").
dico("V", 5, "VESOU").
dico("V", 5, "VESPA").
dico("V", 5, "VESSA").
dico("V", 5, "VESSE").
dico("V", 5, "VESTE").
dico("V", 5, "VETES").
dico("V", 5, "VETEZ").
dico("V", 5, "VETIR").
dico("V", 5, "VETIS").
dico("V", 5, "VETIT").
dico("V", 5, "VETOS").
dico("V", 5, "VETUE").
dico("V", 5, "VETUS").
dico("V", 5, "VEUFS").
dico("V", 5, "VEULE").
dico("V", 5, "VEUVE").
dico("V", 5, "VEXAI").
dico("V", 5, "VEXAS").
dico("V", 5, "VEXAT").
dico("V", 5, "VEXEE").
dico("V", 5, "VEXER").
dico("V", 5, "VEXES").
dico("V", 5, "VEXEZ").
dico("V", 5, "VIBOR").
dico("V", 5, "VIBRA").
dico("V", 5, "VIBRE").
dico("V", 5, "VICES").
dico("V", 5, "VICHY").
dico("V", 5, "VICIA").
dico("V", 5, "VICIE").
dico("V", 5, "VIDAI").
dico("V", 5, "VIDAS").
dico("V", 5, "VIDAT").
dico("V", 5, "VIDEE").
dico("V", 5, "VIDEO").
dico("V", 5, "VIDER").
dico("V", 5, "VIDES").
dico("V", 5, "VIDEZ").
dico("V", 5, "VIEIL").
dico("V", 5, "VIELE").
dico("V", 5, "VIENS").
dico("V", 5, "VIENT").
dico("V", 5, "VIETS").
dico("V", 5, "VIEUX").
dico("V", 5, "VIGIE").
dico("V", 5, "VIGIL").
dico("V", 5, "VIGNE").
dico("V", 5, "VILES").
dico("V", 5, "VILLA").
dico("V", 5, "VILLE").
dico("V", 5, "VIMES").
dico("V", 5, "VINAI").
dico("V", 5, "VINAS").
dico("V", 5, "VINAT").
dico("V", 5, "VINEE").
dico("V", 5, "VINER").
dico("V", 5, "VINES").
dico("V", 5, "VINEZ").
dico("V", 5, "VINGT").
dico("V", 5, "VINYL").
dico("V", 5, "VIOCS").
dico("V", 5, "VIOLA").
dico("V", 5, "VIOLE").
dico("V", 5, "VIOLS").
dico("V", 5, "VIRAI").
dico("V", 5, "VIRAL").
dico("V", 5, "VIRAS").
dico("V", 5, "VIRAT").
dico("V", 5, "VIREE").
dico("V", 5, "VIRER").
dico("V", 5, "VIRES").
dico("V", 5, "VIREZ").
dico("V", 5, "VIRIL").
dico("V", 5, "VIRUS").
dico("V", 5, "VISAI").
dico("V", 5, "VISAS").
dico("V", 5, "VISAT").
dico("V", 5, "VISEE").
dico("V", 5, "VISER").
dico("V", 5, "VISES").
dico("V", 5, "VISEZ").
dico("V", 5, "VISON").
dico("V", 5, "VISOU").
dico("V", 5, "VISSA").
dico("V", 5, "VISSE").
dico("V", 5, "VISTA").
dico("V", 5, "VITAL").
dico("V", 5, "VITES").
dico("V", 5, "VITRA").
dico("V", 5, "VITRE").
dico("V", 5, "VIVAT").
dico("V", 5, "VIVES").
dico("V", 5, "VIVEZ").
dico("V", 5, "VIVRA").
dico("V", 5, "VIVRE").
dico("V", 5, "VIZIR").
dico("V", 5, "VOCAL").
dico("V", 5, "VODKA").
dico("V", 5, "VOEUX").
dico("V", 5, "VOGUA").
dico("V", 5, "VOGUE").
dico("V", 5, "VOICI").
dico("V", 5, "VOIES").
dico("V", 5, "VOILA").
dico("V", 5, "VOILE").
dico("V", 5, "VOIRE").
dico("V", 5, "VOISE").
dico("V", 5, "VOLAI").
dico("V", 5, "VOLAS").
dico("V", 5, "VOLAT").
dico("V", 5, "VOLEE").
dico("V", 5, "VOLER").
dico("V", 5, "VOLES").
dico("V", 5, "VOLET").
dico("V", 5, "VOLEZ").
dico("V", 5, "VOLIS").
dico("V", 5, "VOLTA").
dico("V", 5, "VOLTE").
dico("V", 5, "VOLTS").
dico("V", 5, "VOLVE").
dico("V", 5, "VOMER").
dico("V", 5, "VOMIE").
dico("V", 5, "VOMIR").
dico("V", 5, "VOMIS").
dico("V", 5, "VOMIT").
dico("V", 5, "VOTAI").
dico("V", 5, "VOTAS").
dico("V", 5, "VOTAT").
dico("V", 5, "VOTEE").
dico("V", 5, "VOTER").
dico("V", 5, "VOTES").
dico("V", 5, "VOTEZ").
dico("V", 5, "VOTIF").
dico("V", 5, "VOTRE").
dico("V", 5, "VOUAI").
dico("V", 5, "VOUAS").
dico("V", 5, "VOUAT").
dico("V", 5, "VOUEE").
dico("V", 5, "VOUER").
dico("V", 5, "VOUES").
dico("V", 5, "VOUEZ").
dico("V", 5, "VOUGE").
dico("V", 5, "VOULU").
dico("V", 5, "VOUTA").
dico("V", 5, "VOUTE").
dico("V", 5, "VOYER").
dico("V", 5, "VOYEZ").
dico("V", 5, "VOYOU").
dico("V", 5, "VRACS").
dico("V", 5, "VRAIE").
dico("V", 5, "VRAIS").
dico("V", 5, "VROOM").
dico("V", 5, "VROUM").
dico("V", 5, "VULGO").
dico("V", 5, "VULVE").
