dico("V", 6, "VACANT").
dico("V", 6, "VACCIN").
dico("V", 6, "VACHAI").
dico("V", 6, "VACHAS").
dico("V", 6, "VACHAT").
dico("V", 6, "VACHEE").
dico("V", 6, "VACHER").
dico("V", 6, "VACHES").
dico("V", 6, "VACHEZ").
dico("V", 6, "VACIEU").
dico("V", 6, "VACIVE").
dico("V", 6, "VACUUM").
dico("V", 6, "VAGALE").
dico("V", 6, "VAGAUX").
dico("V", 6, "VAGILE").
dico("V", 6, "VAGINE").
dico("V", 6, "VAGINS").
dico("V", 6, "VAGIRA").
dico("V", 6, "VAGUAI").
dico("V", 6, "VAGUAS").
dico("V", 6, "VAGUAT").
dico("V", 6, "VAGUER").
dico("V", 6, "VAGUES").
dico("V", 6, "VAGUEZ").
dico("V", 6, "VAHINE").
dico("V", 6, "VAICYA").
dico("V", 6, "VAIGRE").
dico("V", 6, "VAILLE").
dico("V", 6, "VAINCS").
dico("V", 6, "VAINCU").
dico("V", 6, "VAINES").
dico("V", 6, "VAIREE").
dico("V", 6, "VAIRES").
dico("V", 6, "VAIRON").
dico("V", 6, "VAISYA").
dico("V", 6, "VALAIS").
dico("V", 6, "VALAIT").
dico("V", 6, "VALANT").
dico("V", 6, "VALENT").
dico("V", 6, "VALETS").
dico("V", 6, "VALEUR").
dico("V", 6, "VALGUS").
dico("V", 6, "VALIDA").
dico("V", 6, "VALIDE").
dico("V", 6, "VALIEZ").
dico("V", 6, "VALINE").
dico("V", 6, "VALISE").
dico("V", 6, "VALIUM").
dico("V", 6, "VALLEE").
dico("V", 6, "VALLON").
dico("V", 6, "VALOIR").
dico("V", 6, "VALONS").
dico("V", 6, "VALSAI").
dico("V", 6, "VALSAS").
dico("V", 6, "VALSAT").
dico("V", 6, "VALSEE").
dico("V", 6, "VALSER").
dico("V", 6, "VALSES").
dico("V", 6, "VALSEZ").
dico("V", 6, "VALUES").
dico("V", 6, "VALVEE").
dico("V", 6, "VALVES").
dico("V", 6, "VAMPAI").
dico("V", 6, "VAMPAS").
dico("V", 6, "VAMPAT").
dico("V", 6, "VAMPEE").
dico("V", 6, "VAMPER").
dico("V", 6, "VAMPES").
dico("V", 6, "VAMPEZ").
dico("V", 6, "VANDAS").
dico("V", 6, "VANISE").
dico("V", 6, "VANITE").
dico("V", 6, "VANNAI").
dico("V", 6, "VANNAS").
dico("V", 6, "VANNAT").
dico("V", 6, "VANNEE").
dico("V", 6, "VANNER").
dico("V", 6, "VANNES").
dico("V", 6, "VANNET").
dico("V", 6, "VANNEZ").
dico("V", 6, "VANTAI").
dico("V", 6, "VANTAS").
dico("V", 6, "VANTAT").
dico("V", 6, "VANTEE").
dico("V", 6, "VANTER").
dico("V", 6, "VANTES").
dico("V", 6, "VANTEZ").
dico("V", 6, "VAPEUR").
dico("V", 6, "VAQUAI").
dico("V", 6, "VAQUAS").
dico("V", 6, "VAQUAT").
dico("V", 6, "VAQUER").
dico("V", 6, "VAQUES").
dico("V", 6, "VAQUEZ").
dico("V", 6, "VARANS").
dico("V", 6, "VARECH").
dico("V", 6, "VARIAI").
dico("V", 6, "VARIAS").
dico("V", 6, "VARIAT").
dico("V", 6, "VARICE").
dico("V", 6, "VARIEE").
dico("V", 6, "VARIER").
dico("V", 6, "VARIES").
dico("V", 6, "VARIEZ").
dico("V", 6, "VARLET").
dico("V", 6, "VAROIS").
dico("V", 6, "VARONS").
dico("V", 6, "VARROA").
dico("V", 6, "VARRON").
dico("V", 6, "VARVES").
dico("V", 6, "VASARD").
dico("V", 6, "VASEUX").
dico("V", 6, "VASQUE").
dico("V", 6, "VASSAL").
dico("V", 6, "VASTES").
dico("V", 6, "VAUDOU").
dico("V", 6, "VAUDRA").
dico("V", 6, "VAUTRA").
dico("V", 6, "VAUTRE").
dico("V", 6, "VECUES").
dico("V", 6, "VEDIKA").
dico("V", 6, "VEGETA").
dico("V", 6, "VEGETE").
dico("V", 6, "VEILLA").
dico("V", 6, "VEILLE").
dico("V", 6, "VEINAI").
dico("V", 6, "VEINAS").
dico("V", 6, "VEINAT").
dico("V", 6, "VEINEE").
dico("V", 6, "VEINER").
dico("V", 6, "VEINES").
dico("V", 6, "VEINEZ").
dico("V", 6, "VELAGE").
dico("V", 6, "VELAIS").
dico("V", 6, "VELAIT").
dico("V", 6, "VELANI").
dico("V", 6, "VELANT").
dico("V", 6, "VELARS").
dico("V", 6, "VELCHE").
dico("V", 6, "VELCRO").
dico("V", 6, "VELDTS").
dico("V", 6, "VELENT").
dico("V", 6, "VELERA").
dico("V", 6, "VELETS").
dico("V", 6, "VELIES").
dico("V", 6, "VELIEZ").
dico("V", 6, "VELINS").
dico("V", 6, "VELITE").
dico("V", 6, "VELOCE").
dico("V", 6, "VELONS").
dico("V", 6, "VELOTS").
dico("V", 6, "VELTES").
dico("V", 6, "VELUES").
dico("V", 6, "VELUMS").
dico("V", 6, "VELVET").
dico("V", 6, "VENAIS").
dico("V", 6, "VENAIT").
dico("V", 6, "VENALE").
dico("V", 6, "VENANT").
dico("V", 6, "VENAUX").
dico("V", 6, "VENDES").
dico("V", 6, "VENDEZ").
dico("V", 6, "VENDIS").
dico("V", 6, "VENDIT").
dico("V", 6, "VENDRA").
dico("V", 6, "VENDRE").
dico("V", 6, "VENDUE").
dico("V", 6, "VENDUS").
dico("V", 6, "VENERA").
dico("V", 6, "VENERE").
dico("V", 6, "VENETS").
dico("V", 6, "VENEUR").
dico("V", 6, "VENGEA").
dico("V", 6, "VENGEE").
dico("V", 6, "VENGER").
dico("V", 6, "VENGES").
dico("V", 6, "VENGEZ").
dico("V", 6, "VENIAT").
dico("V", 6, "VENIEL").
dico("V", 6, "VENIEZ").
dico("V", 6, "VENINS").
dico("V", 6, "VENONS").
dico("V", 6, "VENTAT").
dico("V", 6, "VENTEE").
dico("V", 6, "VENTER").
dico("V", 6, "VENTES").
dico("V", 6, "VENTIS").
dico("V", 6, "VENTRE").
dico("V", 6, "VENTRU").
dico("V", 6, "VENUES").
dico("V", 6, "VEPREE").
dico("V", 6, "VEPRES").
dico("V", 6, "VERACE").
dico("V", 6, "VERBAL").
dico("V", 6, "VERBES").
dico("V", 6, "VERDET").
dico("V", 6, "VERDIE").
dico("V", 6, "VERDIN").
dico("V", 6, "VERDIR").
dico("V", 6, "VERDIS").
dico("V", 6, "VERDIT").
dico("V", 6, "VEREUX").
dico("V", 6, "VERGEE").
dico("V", 6, "VERGER").
dico("V", 6, "VERGES").
dico("V", 6, "VERGNE").
dico("V", 6, "VERGUE").
dico("V", 6, "VERIFS").
dico("V", 6, "VERINE").
dico("V", 6, "VERINS").
dico("V", 6, "VERITE").
dico("V", 6, "VERJUS").
dico("V", 6, "VERLAN").
dico("V", 6, "VERMEE").
dico("V", 6, "VERMET").
dico("V", 6, "VERMIS").
dico("V", 6, "VERNAL").
dico("V", 6, "VERNES").
dico("V", 6, "VERNIE").
dico("V", 6, "VERNIR").
dico("V", 6, "VERNIS").
dico("V", 6, "VERNIT").
dico("V", 6, "VEROLA").
dico("V", 6, "VEROLE").
dico("V", 6, "VERRAI").
dico("V", 6, "VERRAS").
dico("V", 6, "VERRAT").
dico("V", 6, "VERREE").
dico("V", 6, "VERRES").
dico("V", 6, "VERREZ").
dico("V", 6, "VERROU").
dico("V", 6, "VERRUE").
dico("V", 6, "VERSAI").
dico("V", 6, "VERSAS").
dico("V", 6, "VERSAT").
dico("V", 6, "VERSEE").
dico("V", 6, "VERSER").
dico("V", 6, "VERSES").
dico("V", 6, "VERSET").
dico("V", 6, "VERSEZ").
dico("V", 6, "VERSOS").
dico("V", 6, "VERSTE").
dico("V", 6, "VERSUS").
dico("V", 6, "VERTES").
dico("V", 6, "VERTEX").
dico("V", 6, "VERTUS").
dico("V", 6, "VERVES").
dico("V", 6, "VERVET").
dico("V", 6, "VESCES").
dico("V", 6, "VESOUS").
dico("V", 6, "VESPAS").
dico("V", 6, "VESSAI").
dico("V", 6, "VESSAS").
dico("V", 6, "VESSAT").
dico("V", 6, "VESSER").
dico("V", 6, "VESSES").
dico("V", 6, "VESSEZ").
dico("V", 6, "VESSIE").
dico("V", 6, "VESTES").
dico("V", 6, "VESTON").
dico("V", 6, "VETAGE").
dico("V", 6, "VETAIS").
dico("V", 6, "VETAIT").
dico("V", 6, "VETANT").
dico("V", 6, "VETENT").
dico("V", 6, "VETIEZ").
dico("V", 6, "VETIRA").
dico("V", 6, "VETONS").
dico("V", 6, "VETUES").
dico("V", 6, "VETURE").
dico("V", 6, "VEULES").
dico("V", 6, "VEUVES").
dico("V", 6, "VEXAIS").
dico("V", 6, "VEXAIT").
dico("V", 6, "VEXANT").
dico("V", 6, "VEXEES").
dico("V", 6, "VEXENT").
dico("V", 6, "VEXERA").
dico("V", 6, "VEXIEZ").
dico("V", 6, "VEXONS").
dico("V", 6, "VIABLE").
dico("V", 6, "VIADUC").
dico("V", 6, "VIAGER").
dico("V", 6, "VIANDA").
dico("V", 6, "VIANDE").
dico("V", 6, "VIBICE").
dico("V", 6, "VIBORD").
dico("V", 6, "VIBORS").
dico("V", 6, "VIBRAI").
dico("V", 6, "VIBRAS").
dico("V", 6, "VIBRAT").
dico("V", 6, "VIBREE").
dico("V", 6, "VIBRER").
dico("V", 6, "VIBRES").
dico("V", 6, "VIBREZ").
dico("V", 6, "VIBURE").
dico("V", 6, "VICHYS").
dico("V", 6, "VICIAI").
dico("V", 6, "VICIAS").
dico("V", 6, "VICIAT").
dico("V", 6, "VICIEE").
dico("V", 6, "VICIER").
dico("V", 6, "VICIES").
dico("V", 6, "VICIEZ").
dico("V", 6, "VIDAGE").
dico("V", 6, "VIDAIS").
dico("V", 6, "VIDAIT").
dico("V", 6, "VIDAME").
dico("V", 6, "VIDANT").
dico("V", 6, "VIDEAU").
dico("V", 6, "VIDEES").
dico("V", 6, "VIDENT").
dico("V", 6, "VIDEOS").
dico("V", 6, "VIDERA").
dico("V", 6, "VIDEUR").
dico("V", 6, "VIDIEZ").
dico("V", 6, "VIDIMA").
dico("V", 6, "VIDIME").
dico("V", 6, "VIDOIR").
dico("V", 6, "VIDONS").
dico("V", 6, "VIDURE").
dico("V", 6, "VIELES").
dico("V", 6, "VIELLA").
dico("V", 6, "VIELLE").
dico("V", 6, "VIENNE").
dico("V", 6, "VIERGE").
dico("V", 6, "VIGIES").
dico("V", 6, "VIGILE").
dico("V", 6, "VIGILS").
dico("V", 6, "VIGNES").
dico("V", 6, "VIGNOT").
dico("V", 6, "VIHARA").
dico("V", 6, "VIKING").
dico("V", 6, "VILAIN").
dico("V", 6, "VILLAS").
dico("V", 6, "VILLES").
dico("V", 6, "VIMANA").
dico("V", 6, "VINAGE").
dico("V", 6, "VINAIS").
dico("V", 6, "VINAIT").
dico("V", 6, "VINANT").
dico("V", 6, "VINDAS").
dico("V", 6, "VINEES").
dico("V", 6, "VINENT").
dico("V", 6, "VINERA").
dico("V", 6, "VINEUX").
dico("V", 6, "VINGTS").
dico("V", 6, "VINIEZ").
dico("V", 6, "VINMES").
dico("V", 6, "VINONS").
dico("V", 6, "VINSSE").
dico("V", 6, "VINTES").
dico("V", 6, "VINYLE").
dico("V", 6, "VINYLS").
dico("V", 6, "VIOLAI").
dico("V", 6, "VIOLAS").
dico("V", 6, "VIOLAT").
dico("V", 6, "VIOLEE").
dico("V", 6, "VIOLER").
dico("V", 6, "VIOLES").
dico("V", 6, "VIOLET").
dico("V", 6, "VIOLEZ").
dico("V", 6, "VIOLON").
dico("V", 6, "VIOQUE").
dico("V", 6, "VIORNE").
dico("V", 6, "VIPERE").
dico("V", 6, "VIRAGE").
dico("V", 6, "VIRAGO").
dico("V", 6, "VIRAIS").
dico("V", 6, "VIRAIT").
dico("V", 6, "VIRALE").
dico("V", 6, "VIRANT").
dico("V", 6, "VIRAUX").
dico("V", 6, "VIREES").
dico("V", 6, "VIRENT").
dico("V", 6, "VIRERA").
dico("V", 6, "VIREUR").
dico("V", 6, "VIREUX").
dico("V", 6, "VIRIEZ").
dico("V", 6, "VIRILE").
dico("V", 6, "VIRILS").
dico("V", 6, "VIRION").
dico("V", 6, "VIROLA").
dico("V", 6, "VIROLE").
dico("V", 6, "VIRONS").
dico("V", 6, "VIROSE").
dico("V", 6, "VIRURE").
dico("V", 6, "VISAGE").
dico("V", 6, "VISAIS").
dico("V", 6, "VISAIT").
dico("V", 6, "VISANT").
dico("V", 6, "VISEES").
dico("V", 6, "VISENT").
dico("V", 6, "VISERA").
dico("V", 6, "VISEUR").
dico("V", 6, "VISIEZ").
dico("V", 6, "VISION").
dico("V", 6, "VISITA").
dico("V", 6, "VISITE").
dico("V", 6, "VISONS").
dico("V", 6, "VISSAI").
dico("V", 6, "VISSAS").
dico("V", 6, "VISSAT").
dico("V", 6, "VISSEE").
dico("V", 6, "VISSER").
dico("V", 6, "VISSES").
dico("V", 6, "VISSEZ").
dico("V", 6, "VISTAS").
dico("V", 6, "VISUEL").
dico("V", 6, "VITALE").
dico("V", 6, "VITAUX").
dico("V", 6, "VITRAI").
dico("V", 6, "VITRAS").
dico("V", 6, "VITRAT").
dico("V", 6, "VITREE").
dico("V", 6, "VITRER").
dico("V", 6, "VITRES").
dico("V", 6, "VITREZ").
dico("V", 6, "VIVACE").
dico("V", 6, "VIVAIS").
dico("V", 6, "VIVAIT").
dico("V", 6, "VIVANT").
dico("V", 6, "VIVATS").
dico("V", 6, "VIVENT").
dico("V", 6, "VIVEUR").
dico("V", 6, "VIVIDE").
dico("V", 6, "VIVIER").
dico("V", 6, "VIVIEZ").
dico("V", 6, "VIVOIR").
dico("V", 6, "VIVONS").
dico("V", 6, "VIVOTA").
dico("V", 6, "VIVOTE").
dico("V", 6, "VIVRAI").
dico("V", 6, "VIVRAS").
dico("V", 6, "VIVREE").
dico("V", 6, "VIVRES").
dico("V", 6, "VIVREZ").
dico("V", 6, "VIZIRS").
dico("V", 6, "VOCALE").
dico("V", 6, "VOCAUX").
dico("V", 6, "VOCERI").
dico("V", 6, "VOCERO").
dico("V", 6, "VODKAS").
dico("V", 6, "VOGOUL").
dico("V", 6, "VOGUAI").
dico("V", 6, "VOGUAS").
dico("V", 6, "VOGUAT").
dico("V", 6, "VOGUER").
dico("V", 6, "VOGUES").
dico("V", 6, "VOGUEZ").
dico("V", 6, "VOIENT").
dico("V", 6, "VOILAI").
dico("V", 6, "VOILAS").
dico("V", 6, "VOILAT").
dico("V", 6, "VOILEE").
dico("V", 6, "VOILER").
dico("V", 6, "VOILES").
dico("V", 6, "VOILEZ").
dico("V", 6, "VOIRIE").
dico("V", 6, "VOISEE").
dico("V", 6, "VOISES").
dico("V", 6, "VOISIN").
dico("V", 6, "VOLAGE").
dico("V", 6, "VOLAIS").
dico("V", 6, "VOLAIT").
dico("V", 6, "VOLANT").
dico("V", 6, "VOLCAN").
dico("V", 6, "VOLEES").
dico("V", 6, "VOLENT").
dico("V", 6, "VOLERA").
dico("V", 6, "VOLETA").
dico("V", 6, "VOLETE").
dico("V", 6, "VOLETS").
dico("V", 6, "VOLEUR").
dico("V", 6, "VOLIEZ").
dico("V", 6, "VOLIGE").
dico("V", 6, "VOLLEY").
dico("V", 6, "VOLNAY").
dico("V", 6, "VOLONS").
dico("V", 6, "VOLTAI").
dico("V", 6, "VOLTAS").
dico("V", 6, "VOLTAT").
dico("V", 6, "VOLTER").
dico("V", 6, "VOLTES").
dico("V", 6, "VOLTEZ").
dico("V", 6, "VOLUME").
dico("V", 6, "VOLUTE").
dico("V", 6, "VOLVES").
dico("V", 6, "VOLVOX").
dico("V", 6, "VOMERS").
dico("V", 6, "VOMIES").
dico("V", 6, "VOMIRA").
dico("V", 6, "VOMITO").
dico("V", 6, "VORACE").
dico("V", 6, "VORTEX").
dico("V", 6, "VOTAIS").
dico("V", 6, "VOTAIT").
dico("V", 6, "VOTANT").
dico("V", 6, "VOTEES").
dico("V", 6, "VOTENT").
dico("V", 6, "VOTERA").
dico("V", 6, "VOTIEZ").
dico("V", 6, "VOTIFS").
dico("V", 6, "VOTIVE").
dico("V", 6, "VOTONS").
dico("V", 6, "VOTRES").
dico("V", 6, "VOUAIS").
dico("V", 6, "VOUAIT").
dico("V", 6, "VOUANT").
dico("V", 6, "VOUDRA").
dico("V", 6, "VOUEES").
dico("V", 6, "VOUENT").
dico("V", 6, "VOUERA").
dico("V", 6, "VOUGES").
dico("V", 6, "VOUIEZ").
dico("V", 6, "VOULEZ").
dico("V", 6, "VOULUE").
dico("V", 6, "VOULUS").
dico("V", 6, "VOULUT").
dico("V", 6, "VOUONS").
dico("V", 6, "VOUTAI").
dico("V", 6, "VOUTAS").
dico("V", 6, "VOUTAT").
dico("V", 6, "VOUTEE").
dico("V", 6, "VOUTER").
dico("V", 6, "VOUTES").
dico("V", 6, "VOUTEZ").
dico("V", 6, "VOYAGE").
dico("V", 6, "VOYAIS").
dico("V", 6, "VOYAIT").
dico("V", 6, "VOYANT").
dico("V", 6, "VOYERS").
dico("V", 6, "VOYEUR").
dico("V", 6, "VOYIEZ").
dico("V", 6, "VOYONS").
dico("V", 6, "VOYOUS").
dico("V", 6, "VRAIES").
dico("V", 6, "VRILLA").
dico("V", 6, "VRILLE").
dico("V", 6, "VROMBI").
dico("V", 6, "VULPIN").
dico("V", 6, "VULVES").
