dico("V", 7, "VACANCE").
dico("V", 7, "VACANTE").
dico("V", 7, "VACANTS").
dico("V", 7, "VACARME").
dico("V", 7, "VACCINA").
dico("V", 7, "VACCINE").
dico("V", 7, "VACCINS").
dico("V", 7, "VACHAIS").
dico("V", 7, "VACHAIT").
dico("V", 7, "VACHANT").
dico("V", 7, "VACHARD").
dico("V", 7, "VACHEES").
dico("V", 7, "VACHENT").
dico("V", 7, "VACHERA").
dico("V", 7, "VACHERE").
dico("V", 7, "VACHERS").
dico("V", 7, "VACHIEZ").
dico("V", 7, "VACHONS").
dico("V", 7, "VACIEUX").
dico("V", 7, "VACILLA").
dico("V", 7, "VACILLE").
dico("V", 7, "VACIVES").
dico("V", 7, "VACUITE").
dico("V", 7, "VACUOLE").
dico("V", 7, "VACUOME").
dico("V", 7, "VACUUMS").
dico("V", 7, "VAGALES").
dico("V", 7, "VAGILES").
dico("V", 7, "VAGIMES").
dico("V", 7, "VAGINAL").
dico("V", 7, "VAGINEE").
dico("V", 7, "VAGINES").
dico("V", 7, "VAGIRAI").
dico("V", 7, "VAGIRAS").
dico("V", 7, "VAGIREZ").
dico("V", 7, "VAGISSE").
dico("V", 7, "VAGITES").
dico("V", 7, "VAGUAIS").
dico("V", 7, "VAGUAIT").
dico("V", 7, "VAGUANT").
dico("V", 7, "VAGUENT").
dico("V", 7, "VAGUERA").
dico("V", 7, "VAGUIEZ").
dico("V", 7, "VAGUONS").
dico("V", 7, "VAHINES").
dico("V", 7, "VAICYAS").
dico("V", 7, "VAIGRES").
dico("V", 7, "VAILLES").
dico("V", 7, "VAINCRA").
dico("V", 7, "VAINCRE").
dico("V", 7, "VAINCUE").
dico("V", 7, "VAINCUS").
dico("V", 7, "VAINQUE").
dico("V", 7, "VAIREES").
dico("V", 7, "VAIRONS").
dico("V", 7, "VAISHYA").
dico("V", 7, "VAISYAS").
dico("V", 7, "VALABLE").
dico("V", 7, "VALAQUE").
dico("V", 7, "VALENCE").
dico("V", 7, "VALEURS").
dico("V", 7, "VALIDAI").
dico("V", 7, "VALIDAS").
dico("V", 7, "VALIDAT").
dico("V", 7, "VALIDEE").
dico("V", 7, "VALIDER").
dico("V", 7, "VALIDES").
dico("V", 7, "VALIDEZ").
dico("V", 7, "VALINES").
dico("V", 7, "VALIONS").
dico("V", 7, "VALISES").
dico("V", 7, "VALIUMS").
dico("V", 7, "VALLEES").
dico("V", 7, "VALLONS").
dico("V", 7, "VALOCHE").
dico("V", 7, "VALSAIS").
dico("V", 7, "VALSAIT").
dico("V", 7, "VALSANT").
dico("V", 7, "VALSEES").
dico("V", 7, "VALSENT").
dico("V", 7, "VALSERA").
dico("V", 7, "VALSEUR").
dico("V", 7, "VALSIEZ").
dico("V", 7, "VALSONS").
dico("V", 7, "VALUMES").
dico("V", 7, "VALUSSE").
dico("V", 7, "VALUTES").
dico("V", 7, "VALVEES").
dico("V", 7, "VALVULE").
dico("V", 7, "VAMPAIS").
dico("V", 7, "VAMPAIT").
dico("V", 7, "VAMPANT").
dico("V", 7, "VAMPEES").
dico("V", 7, "VAMPENT").
dico("V", 7, "VAMPERA").
dico("V", 7, "VAMPIEZ").
dico("V", 7, "VAMPIRE").
dico("V", 7, "VAMPONS").
dico("V", 7, "VANDALE").
dico("V", 7, "VANESSE").
dico("V", 7, "VANILLE").
dico("V", 7, "VANISEE").
dico("V", 7, "VANISES").
dico("V", 7, "VANITES").
dico("V", 7, "VANNAGE").
dico("V", 7, "VANNAIS").
dico("V", 7, "VANNAIT").
dico("V", 7, "VANNANT").
dico("V", 7, "VANNEAU").
dico("V", 7, "VANNEES").
dico("V", 7, "VANNENT").
dico("V", 7, "VANNERA").
dico("V", 7, "VANNETS").
dico("V", 7, "VANNEUR").
dico("V", 7, "VANNIER").
dico("V", 7, "VANNIEZ").
dico("V", 7, "VANNONS").
dico("V", 7, "VANNURE").
dico("V", 7, "VANTAIL").
dico("V", 7, "VANTAIS").
dico("V", 7, "VANTAIT").
dico("V", 7, "VANTANT").
dico("V", 7, "VANTARD").
dico("V", 7, "VANTAUX").
dico("V", 7, "VANTEES").
dico("V", 7, "VANTENT").
dico("V", 7, "VANTERA").
dico("V", 7, "VANTIEZ").
dico("V", 7, "VANTONS").
dico("V", 7, "VAPEURS").
dico("V", 7, "VAQUAIS").
dico("V", 7, "VAQUAIT").
dico("V", 7, "VAQUANT").
dico("V", 7, "VAQUENT").
dico("V", 7, "VAQUERA").
dico("V", 7, "VAQUERO").
dico("V", 7, "VAQUIEZ").
dico("V", 7, "VAQUONS").
dico("V", 7, "VARAPPA").
dico("V", 7, "VARAPPE").
dico("V", 7, "VARECHS").
dico("V", 7, "VARENNE").
dico("V", 7, "VAREUSE").
dico("V", 7, "VARIAIS").
dico("V", 7, "VARIAIT").
dico("V", 7, "VARIANT").
dico("V", 7, "VARICES").
dico("V", 7, "VARIEES").
dico("V", 7, "VARIENT").
dico("V", 7, "VARIERA").
dico("V", 7, "VARIETE").
dico("V", 7, "VARIIEZ").
dico("V", 7, "VARIOLE").
dico("V", 7, "VARIONS").
dico("V", 7, "VARLETS").
dico("V", 7, "VARLOPA").
dico("V", 7, "VARLOPE").
dico("V", 7, "VAROISE").
dico("V", 7, "VARROAS").
dico("V", 7, "VARRONS").
dico("V", 7, "VASARDE").
dico("V", 7, "VASARDS").
dico("V", 7, "VASEUSE").
dico("V", 7, "VASIERE").
dico("V", 7, "VASQUES").
dico("V", 7, "VASSALE").
dico("V", 7, "VASSAUX").
dico("V", 7, "VAUDOIS").
dico("V", 7, "VAUDOUE").
dico("V", 7, "VAUDOUS").
dico("V", 7, "VAUDRAI").
dico("V", 7, "VAUDRAS").
dico("V", 7, "VAUDREZ").
dico("V", 7, "VAURIEN").
dico("V", 7, "VAUTOUR").
dico("V", 7, "VAUTRAI").
dico("V", 7, "VAUTRAS").
dico("V", 7, "VAUTRAT").
dico("V", 7, "VAUTREE").
dico("V", 7, "VAUTRER").
dico("V", 7, "VAUTRES").
dico("V", 7, "VAUTREZ").
dico("V", 7, "VAUVERT").
dico("V", 7, "VECTEUR").
dico("V", 7, "VECUMES").
dico("V", 7, "VECUSSE").
dico("V", 7, "VECUTES").
dico("V", 7, "VEDANTA").
dico("V", 7, "VEDETTE").
dico("V", 7, "VEDIKAS").
dico("V", 7, "VEDIQUE").
dico("V", 7, "VEDISME").
dico("V", 7, "VEGETAI").
dico("V", 7, "VEGETAL").
dico("V", 7, "VEGETAS").
dico("V", 7, "VEGETAT").
dico("V", 7, "VEGETER").
dico("V", 7, "VEGETES").
dico("V", 7, "VEGETEZ").
dico("V", 7, "VEILLAI").
dico("V", 7, "VEILLAS").
dico("V", 7, "VEILLAT").
dico("V", 7, "VEILLEE").
dico("V", 7, "VEILLER").
dico("V", 7, "VEILLES").
dico("V", 7, "VEILLEZ").
dico("V", 7, "VEINAIS").
dico("V", 7, "VEINAIT").
dico("V", 7, "VEINANT").
dico("V", 7, "VEINARD").
dico("V", 7, "VEINEES").
dico("V", 7, "VEINENT").
dico("V", 7, "VEINERA").
dico("V", 7, "VEINEUX").
dico("V", 7, "VEINIEZ").
dico("V", 7, "VEINONS").
dico("V", 7, "VEINULE").
dico("V", 7, "VEINURE").
dico("V", 7, "VELAGES").
dico("V", 7, "VELAIRE").
dico("V", 7, "VELAMES").
dico("V", 7, "VELANIS").
dico("V", 7, "VELASSE").
dico("V", 7, "VELATES").
dico("V", 7, "VELCHES").
dico("V", 7, "VELCROS").
dico("V", 7, "VELERAI").
dico("V", 7, "VELERAS").
dico("V", 7, "VELEREZ").
dico("V", 7, "VELEUSE").
dico("V", 7, "VELIONS").
dico("V", 7, "VELIQUE").
dico("V", 7, "VELITES").
dico("V", 7, "VELLAVE").
dico("V", 7, "VELOCES").
dico("V", 7, "VELOSKI").
dico("V", 7, "VELOURS").
dico("V", 7, "VELOUTA").
dico("V", 7, "VELOUTE").
dico("V", 7, "VELTAGE").
dico("V", 7, "VELVETS").
dico("V", 7, "VELVOTE").
dico("V", 7, "VENALES").
dico("V", 7, "VENANTE").
dico("V", 7, "VENANTS").
dico("V", 7, "VENDAIS").
dico("V", 7, "VENDAIT").
dico("V", 7, "VENDANT").
dico("V", 7, "VENDEEN").
dico("V", 7, "VENDENT").
dico("V", 7, "VENDEUR").
dico("V", 7, "VENDIEZ").
dico("V", 7, "VENDONS").
dico("V", 7, "VENDRAI").
dico("V", 7, "VENDRAS").
dico("V", 7, "VENDREZ").
dico("V", 7, "VENDUES").
dico("V", 7, "VENELLE").
dico("V", 7, "VENERAI").
dico("V", 7, "VENERAS").
dico("V", 7, "VENERAT").
dico("V", 7, "VENEREE").
dico("V", 7, "VENERER").
dico("V", 7, "VENERES").
dico("V", 7, "VENEREZ").
dico("V", 7, "VENERIE").
dico("V", 7, "VENETTE").
dico("V", 7, "VENEURS").
dico("V", 7, "VENGEAI").
dico("V", 7, "VENGEAS").
dico("V", 7, "VENGEAT").
dico("V", 7, "VENGEES").
dico("V", 7, "VENGENT").
dico("V", 7, "VENGERA").
dico("V", 7, "VENGEUR").
dico("V", 7, "VENGIEZ").
dico("V", 7, "VENIELS").
dico("V", 7, "VENIONS").
dico("V", 7, "VENTAGE").
dico("V", 7, "VENTAIL").
dico("V", 7, "VENTAIT").
dico("V", 7, "VENTAUX").
dico("V", 7, "VENTEAU").
dico("V", 7, "VENTEES").
dico("V", 7, "VENTERA").
dico("V", 7, "VENTEUX").
dico("V", 7, "VENTILA").
dico("V", 7, "VENTILE").
dico("V", 7, "VENTOSE").
dico("V", 7, "VENTRAL").
dico("V", 7, "VENTREE").
dico("V", 7, "VENTRES").
dico("V", 7, "VENTRUE").
dico("V", 7, "VENTRUS").
dico("V", 7, "VENTURI").
dico("V", 7, "VENUSTE").
dico("V", 7, "VEPREES").
dico("V", 7, "VERACES").
dico("V", 7, "VERANDA").
dico("V", 7, "VERATRE").
dico("V", 7, "VERBALE").
dico("V", 7, "VERBAUX").
dico("V", 7, "VERBEUX").
dico("V", 7, "VERDAGE").
dico("V", 7, "VERDETS").
dico("V", 7, "VERDEUR").
dico("V", 7, "VERDICT").
dico("V", 7, "VERDIER").
dico("V", 7, "VERDIES").
dico("V", 7, "VERDINS").
dico("V", 7, "VERDIRA").
dico("V", 7, "VERDOIE").
dico("V", 7, "VERDOYA").
dico("V", 7, "VERDOYE").
dico("V", 7, "VERDURE").
dico("V", 7, "VEREUSE").
dico("V", 7, "VERGEES").
dico("V", 7, "VERGERS").
dico("V", 7, "VERGETE").
dico("V", 7, "VERGLAS").
dico("V", 7, "VERGNES").
dico("V", 7, "VERGUES").
dico("V", 7, "VERIFIA").
dico("V", 7, "VERIFIE").
dico("V", 7, "VERINES").
dico("V", 7, "VERISME").
dico("V", 7, "VERISTE").
dico("V", 7, "VERITES").
dico("V", 7, "VERJUTA").
dico("V", 7, "VERJUTE").
dico("V", 7, "VERLANS").
dico("V", 7, "VERMEES").
dico("V", 7, "VERMEIL").
dico("V", 7, "VERMETS").
dico("V", 7, "VERMINE").
dico("V", 7, "VERMOUT").
dico("V", 7, "VERNALE").
dico("V", 7, "VERNAUX").
dico("V", 7, "VERNIER").
dico("V", 7, "VERNIES").
dico("V", 7, "VERNIRA").
dico("V", 7, "VEROLAI").
dico("V", 7, "VEROLAS").
dico("V", 7, "VEROLAT").
dico("V", 7, "VEROLEE").
dico("V", 7, "VEROLER").
dico("V", 7, "VEROLES").
dico("V", 7, "VEROLEZ").
dico("V", 7, "VERONAL").
dico("V", 7, "VERRAIS").
dico("V", 7, "VERRAIT").
dico("V", 7, "VERRATS").
dico("V", 7, "VERREES").
dico("V", 7, "VERRIER").
dico("V", 7, "VERRIEZ").
dico("V", 7, "VERRINE").
dico("V", 7, "VERRONS").
dico("V", 7, "VERRONT").
dico("V", 7, "VERROUS").
dico("V", 7, "VERRUES").
dico("V", 7, "VERSAGE").
dico("V", 7, "VERSAIS").
dico("V", 7, "VERSAIT").
dico("V", 7, "VERSANT").
dico("V", 7, "VERSEAU").
dico("V", 7, "VERSEES").
dico("V", 7, "VERSENT").
dico("V", 7, "VERSERA").
dico("V", 7, "VERSETS").
dico("V", 7, "VERSEUR").
dico("V", 7, "VERSIEZ").
dico("V", 7, "VERSION").
dico("V", 7, "VERSOIR").
dico("V", 7, "VERSONS").
dico("V", 7, "VERSTES").
dico("V", 7, "VERTIGE").
dico("V", 7, "VERTIGO").
dico("V", 7, "VERVETS").
dico("V", 7, "VERVEUX").
dico("V", 7, "VESANIE").
dico("V", 7, "VESICAL").
dico("V", 7, "VESPIDE").
dico("V", 7, "VESPREE").
dico("V", 7, "VESSAIS").
dico("V", 7, "VESSAIT").
dico("V", 7, "VESSANT").
dico("V", 7, "VESSENT").
dico("V", 7, "VESSERA").
dico("V", 7, "VESSIES").
dico("V", 7, "VESSIEZ").
dico("V", 7, "VESSONS").
dico("V", 7, "VESTALE").
dico("V", 7, "VESTIGE").
dico("V", 7, "VESTONS").
dico("V", 7, "VETAGES").
dico("V", 7, "VETERAN").
dico("V", 7, "VETILLA").
dico("V", 7, "VETILLE").
dico("V", 7, "VETIMES").
dico("V", 7, "VETIONS").
dico("V", 7, "VETIRAI").
dico("V", 7, "VETIRAS").
dico("V", 7, "VETIREZ").
dico("V", 7, "VETISSE").
dico("V", 7, "VETITES").
dico("V", 7, "VETIVER").
dico("V", 7, "VETURES").
dico("V", 7, "VETUSTE").
dico("V", 7, "VEUILLE").
dico("V", 7, "VEULENT").
dico("V", 7, "VEUVAGE").
dico("V", 7, "VEXAMES").
dico("V", 7, "VEXANTE").
dico("V", 7, "VEXANTS").
dico("V", 7, "VEXASSE").
dico("V", 7, "VEXATES").
dico("V", 7, "VEXERAI").
dico("V", 7, "VEXERAS").
dico("V", 7, "VEXEREZ").
dico("V", 7, "VEXILLE").
dico("V", 7, "VEXIONS").
dico("V", 7, "VIABLES").
dico("V", 7, "VIADUCS").
dico("V", 7, "VIAGERE").
dico("V", 7, "VIAGERS").
dico("V", 7, "VIANDAI").
dico("V", 7, "VIANDAS").
dico("V", 7, "VIANDAT").
dico("V", 7, "VIANDEE").
dico("V", 7, "VIANDER").
dico("V", 7, "VIANDES").
dico("V", 7, "VIANDEZ").
dico("V", 7, "VIBICES").
dico("V", 7, "VIBORDS").
dico("V", 7, "VIBRAGE").
dico("V", 7, "VIBRAIS").
dico("V", 7, "VIBRAIT").
dico("V", 7, "VIBRANT").
dico("V", 7, "VIBRATO").
dico("V", 7, "VIBREES").
dico("V", 7, "VIBRENT").
dico("V", 7, "VIBRERA").
dico("V", 7, "VIBREUR").
dico("V", 7, "VIBRIEZ").
dico("V", 7, "VIBRION").
dico("V", 7, "VIBRONS").
dico("V", 7, "VICAIRE").
dico("V", 7, "VICIAIS").
dico("V", 7, "VICIAIT").
dico("V", 7, "VICIANT").
dico("V", 7, "VICIEES").
dico("V", 7, "VICIENT").
dico("V", 7, "VICIERA").
dico("V", 7, "VICIEUX").
dico("V", 7, "VICIIEZ").
dico("V", 7, "VICINAL").
dico("V", 7, "VICIONS").
dico("V", 7, "VICOMTE").
dico("V", 7, "VICTIME").
dico("V", 7, "VIDAGES").
dico("V", 7, "VIDAMES").
dico("V", 7, "VIDAMIE").
dico("V", 7, "VIDANGE").
dico("V", 7, "VIDASSE").
dico("V", 7, "VIDATES").
dico("V", 7, "VIDEAUX").
dico("V", 7, "VIDELLE").
dico("V", 7, "VIDERAI").
dico("V", 7, "VIDERAS").
dico("V", 7, "VIDEREZ").
dico("V", 7, "VIDEURS").
dico("V", 7, "VIDEUSE").
dico("V", 7, "VIDICON").
dico("V", 7, "VIDIMAI").
dico("V", 7, "VIDIMAS").
dico("V", 7, "VIDIMAT").
dico("V", 7, "VIDIMEE").
dico("V", 7, "VIDIMER").
dico("V", 7, "VIDIMES").
dico("V", 7, "VIDIMEZ").
dico("V", 7, "VIDIMUS").
dico("V", 7, "VIDIONS").
dico("V", 7, "VIDOIRS").
dico("V", 7, "VIDUITE").
dico("V", 7, "VIDURES").
dico("V", 7, "VIEILLE").
dico("V", 7, "VIEILLI").
dico("V", 7, "VIELLAI").
dico("V", 7, "VIELLAS").
dico("V", 7, "VIELLAT").
dico("V", 7, "VIELLER").
dico("V", 7, "VIELLES").
dico("V", 7, "VIELLEZ").
dico("V", 7, "VIENDRA").
dico("V", 7, "VIENNES").
dico("V", 7, "VIERGES").
dico("V", 7, "VIGILES").
dico("V", 7, "VIGNEAU").
dico("V", 7, "VIGNETA").
dico("V", 7, "VIGNETE").
dico("V", 7, "VIGNOTS").
dico("V", 7, "VIGOGNE").
dico("V", 7, "VIGUEUR").
dico("V", 7, "VIGUIER").
dico("V", 7, "VIHARAS").
dico("V", 7, "VIKINGS").
dico("V", 7, "VILAINE").
dico("V", 7, "VILAINS").
dico("V", 7, "VILAYET").
dico("V", 7, "VILENIE").
dico("V", 7, "VILLAGE").
dico("V", 7, "VILLEUX").
dico("V", 7, "VIMANAS").
dico("V", 7, "VINAGES").
dico("V", 7, "VINAIRE").
dico("V", 7, "VINAMES").
dico("V", 7, "VINASSE").
dico("V", 7, "VINATES").
dico("V", 7, "VINERAI").
dico("V", 7, "VINERAS").
dico("V", 7, "VINEREZ").
dico("V", 7, "VINEUSE").
dico("V", 7, "VINIFIA").
dico("V", 7, "VINIFIE").
dico("V", 7, "VINIONS").
dico("V", 7, "VINIQUE").
dico("V", 7, "VINRENT").
dico("V", 7, "VINSSES").
dico("V", 7, "VINTAGE").
dico("V", 7, "VINYLES").
dico("V", 7, "VIOLACA").
dico("V", 7, "VIOLACE").
dico("V", 7, "VIOLAIS").
dico("V", 7, "VIOLAIT").
dico("V", 7, "VIOLANT").
dico("V", 7, "VIOLATS").
dico("V", 7, "VIOLEES").
dico("V", 7, "VIOLENT").
dico("V", 7, "VIOLERA").
dico("V", 7, "VIOLETA").
dico("V", 7, "VIOLETE").
dico("V", 7, "VIOLETS").
dico("V", 7, "VIOLEUR").
dico("V", 7, "VIOLIER").
dico("V", 7, "VIOLIEZ").
dico("V", 7, "VIOLINE").
dico("V", 7, "VIOLONA").
dico("V", 7, "VIOLONE").
dico("V", 7, "VIOLONS").
dico("V", 7, "VIOQUES").
dico("V", 7, "VIORNES").
dico("V", 7, "VIPERES").
dico("V", 7, "VIPERIN").
dico("V", 7, "VIRAGES").
dico("V", 7, "VIRAGOS").
dico("V", 7, "VIRALES").
dico("V", 7, "VIRAMES").
dico("V", 7, "VIRASSE").
dico("V", 7, "VIRATES").
dico("V", 7, "VIRELAI").
dico("V", 7, "VIREMIE").
dico("V", 7, "VIRERAI").
dico("V", 7, "VIRERAS").
dico("V", 7, "VIREREZ").
dico("V", 7, "VIRETON").
dico("V", 7, "VIREURS").
dico("V", 7, "VIREUSE").
dico("V", 7, "VIRGULA").
dico("V", 7, "VIRGULE").
dico("V", 7, "VIRILES").
dico("V", 7, "VIRIONS").
dico("V", 7, "VIROIDE").
dico("V", 7, "VIROLAI").
dico("V", 7, "VIROLAS").
dico("V", 7, "VIROLAT").
dico("V", 7, "VIROLEE").
dico("V", 7, "VIROLER").
dico("V", 7, "VIROLES").
dico("V", 7, "VIROLET").
dico("V", 7, "VIROLEZ").
dico("V", 7, "VIROSES").
dico("V", 7, "VIRTUEL").
dico("V", 7, "VIRURES").
dico("V", 7, "VISAGES").
dico("V", 7, "VISAMES").
dico("V", 7, "VISASSE").
dico("V", 7, "VISATES").
dico("V", 7, "VISCERE").
dico("V", 7, "VISCOSE").
dico("V", 7, "VISERAI").
dico("V", 7, "VISERAS").
dico("V", 7, "VISEREZ").
dico("V", 7, "VISEURS").
dico("V", 7, "VISIBLE").
dico("V", 7, "VISIERE").
dico("V", 7, "VISIONS").
dico("V", 7, "VISITAI").
dico("V", 7, "VISITAS").
dico("V", 7, "VISITAT").
dico("V", 7, "VISITEE").
dico("V", 7, "VISITER").
dico("V", 7, "VISITES").
dico("V", 7, "VISITEZ").
dico("V", 7, "VISNAGE").
dico("V", 7, "VISSAGE").
dico("V", 7, "VISSAIS").
dico("V", 7, "VISSAIT").
dico("V", 7, "VISSANT").
dico("V", 7, "VISSEES").
dico("V", 7, "VISSENT").
dico("V", 7, "VISSERA").
dico("V", 7, "VISSIEZ").
dico("V", 7, "VISSONS").
dico("V", 7, "VISUELS").
dico("V", 7, "VITACEE").
dico("V", 7, "VITALES").
dico("V", 7, "VITESSE").
dico("V", 7, "VITRAGE").
dico("V", 7, "VITRAIL").
dico("V", 7, "VITRAIN").
dico("V", 7, "VITRAIS").
dico("V", 7, "VITRAIT").
dico("V", 7, "VITRANT").
dico("V", 7, "VITRAUX").
dico("V", 7, "VITREES").
dico("V", 7, "VITRENT").
dico("V", 7, "VITRERA").
dico("V", 7, "VITREUX").
dico("V", 7, "VITRIER").
dico("V", 7, "VITRIEZ").
dico("V", 7, "VITRINE").
dico("V", 7, "VITRIOL").
dico("V", 7, "VITRONS").
dico("V", 7, "VIVABLE").
dico("V", 7, "VIVACES").
dico("V", 7, "VIVANTE").
dico("V", 7, "VIVANTS").
dico("V", 7, "VIVEURS").
dico("V", 7, "VIVEUSE").
dico("V", 7, "VIVIDES").
dico("V", 7, "VIVIERS").
dico("V", 7, "VIVIFIA").
dico("V", 7, "VIVIFIE").
dico("V", 7, "VIVIONS").
dico("V", 7, "VIVOIRS").
dico("V", 7, "VIVOTAI").
dico("V", 7, "VIVOTAS").
dico("V", 7, "VIVOTAT").
dico("V", 7, "VIVOTER").
dico("V", 7, "VIVOTES").
dico("V", 7, "VIVOTEZ").
dico("V", 7, "VIVRAIS").
dico("V", 7, "VIVRAIT").
dico("V", 7, "VIVREES").
dico("V", 7, "VIVRIER").
dico("V", 7, "VIVRIEZ").
dico("V", 7, "VIVRONS").
dico("V", 7, "VIVRONT").
dico("V", 7, "VIZIRAT").
dico("V", 7, "VOCABLE").
dico("V", 7, "VOCALES").
dico("V", 7, "VOCATIF").
dico("V", 7, "VOCEROS").
dico("V", 7, "VOGOULE").
dico("V", 7, "VOGOULS").
dico("V", 7, "VOGUAIS").
dico("V", 7, "VOGUAIT").
dico("V", 7, "VOGUANT").
dico("V", 7, "VOGUENT").
dico("V", 7, "VOGUERA").
dico("V", 7, "VOGUIEZ").
dico("V", 7, "VOGUONS").
dico("V", 7, "VOILAGE").
dico("V", 7, "VOILAIS").
dico("V", 7, "VOILAIT").
dico("V", 7, "VOILANT").
dico("V", 7, "VOILEES").
dico("V", 7, "VOILENT").
dico("V", 7, "VOILERA").
dico("V", 7, "VOILIER").
dico("V", 7, "VOILIEZ").
dico("V", 7, "VOILONS").
dico("V", 7, "VOILURE").
dico("V", 7, "VOIRIES").
dico("V", 7, "VOISEES").
dico("V", 7, "VOISINA").
dico("V", 7, "VOISINE").
dico("V", 7, "VOISINS").
dico("V", 7, "VOITURA").
dico("V", 7, "VOITURE").
dico("V", 7, "VOIVODE").
dico("V", 7, "VOLABLE").
dico("V", 7, "VOLAGES").
dico("V", 7, "VOLAMES").
dico("V", 7, "VOLANTE").
dico("V", 7, "VOLANTS").
dico("V", 7, "VOLAPUK").
dico("V", 7, "VOLASSE").
dico("V", 7, "VOLATES").
dico("V", 7, "VOLATIL").
dico("V", 7, "VOLCANS").
dico("V", 7, "VOLEMIE").
dico("V", 7, "VOLERAI").
dico("V", 7, "VOLERAS").
dico("V", 7, "VOLEREZ").
dico("V", 7, "VOLERIE").
dico("V", 7, "VOLETAI").
dico("V", 7, "VOLETAS").
dico("V", 7, "VOLETAT").
dico("V", 7, "VOLETER").
dico("V", 7, "VOLETEZ").
dico("V", 7, "VOLETTE").
dico("V", 7, "VOLEURS").
dico("V", 7, "VOLEUSE").
dico("V", 7, "VOLIERE").
dico("V", 7, "VOLIGEA").
dico("V", 7, "VOLIGEE").
dico("V", 7, "VOLIGER").
dico("V", 7, "VOLIGES").
dico("V", 7, "VOLIGEZ").
dico("V", 7, "VOLIONS").
dico("V", 7, "VOLITIF").
dico("V", 7, "VOLLEYA").
dico("V", 7, "VOLLEYE").
dico("V", 7, "VOLLEYS").
dico("V", 7, "VOLNAYS").
dico("V", 7, "VOLONTE").
dico("V", 7, "VOLTAGE").
dico("V", 7, "VOLTAIS").
dico("V", 7, "VOLTAIT").
dico("V", 7, "VOLTANT").
dico("V", 7, "VOLTENT").
dico("V", 7, "VOLTERA").
dico("V", 7, "VOLTIEZ").
dico("V", 7, "VOLTIGE").
dico("V", 7, "VOLTONS").
dico("V", 7, "VOLUMES").
dico("V", 7, "VOLUPTE").
dico("V", 7, "VOLUTES").
dico("V", 7, "VOLVOCE").
dico("V", 7, "VOMIMES").
dico("V", 7, "VOMIQUE").
dico("V", 7, "VOMIRAI").
dico("V", 7, "VOMIRAS").
dico("V", 7, "VOMIREZ").
dico("V", 7, "VOMISSE").
dico("V", 7, "VOMITES").
dico("V", 7, "VOMITIF").
dico("V", 7, "VOMITOS").
dico("V", 7, "VORACES").
dico("V", 7, "VOSGIEN").
dico("V", 7, "VOTAMES").
dico("V", 7, "VOTANTE").
dico("V", 7, "VOTANTS").
dico("V", 7, "VOTASSE").
dico("V", 7, "VOTATES").
dico("V", 7, "VOTERAI").
dico("V", 7, "VOTERAS").
dico("V", 7, "VOTEREZ").
dico("V", 7, "VOTIONS").
dico("V", 7, "VOTIVES").
dico("V", 7, "VOUAMES").
dico("V", 7, "VOUASSE").
dico("V", 7, "VOUATES").
dico("V", 7, "VOUCHER").
dico("V", 7, "VOUDRAI").
dico("V", 7, "VOUDRAS").
dico("V", 7, "VOUDREZ").
dico("V", 7, "VOUERAI").
dico("V", 7, "VOUERAS").
dico("V", 7, "VOUEREZ").
dico("V", 7, "VOUGEOT").
dico("V", 7, "VOUIONS").
dico("V", 7, "VOUIVRE").
dico("V", 7, "VOULAIS").
dico("V", 7, "VOULAIT").
dico("V", 7, "VOULANT").
dico("V", 7, "VOULIEZ").
dico("V", 7, "VOULOIR").
dico("V", 7, "VOULONS").
dico("V", 7, "VOULUES").
dico("V", 7, "VOUSOIE").
dico("V", 7, "VOUSOYA").
dico("V", 7, "VOUSOYE").
dico("V", 7, "VOUTAIN").
dico("V", 7, "VOUTAIS").
dico("V", 7, "VOUTAIT").
dico("V", 7, "VOUTANT").
dico("V", 7, "VOUTEES").
dico("V", 7, "VOUTENT").
dico("V", 7, "VOUTERA").
dico("V", 7, "VOUTIEZ").
dico("V", 7, "VOUTONS").
dico("V", 7, "VOUVOIE").
dico("V", 7, "VOUVOYA").
dico("V", 7, "VOUVOYE").
dico("V", 7, "VOUVRAY").
dico("V", 7, "VOYAGEA").
dico("V", 7, "VOYAGER").
dico("V", 7, "VOYAGES").
dico("V", 7, "VOYAGEZ").
dico("V", 7, "VOYANCE").
dico("V", 7, "VOYANTE").
dico("V", 7, "VOYANTS").
dico("V", 7, "VOYELLE").
dico("V", 7, "VOYEURS").
dico("V", 7, "VOYEUSE").
dico("V", 7, "VOYIONS").
dico("V", 7, "VOYOUTE").
dico("V", 7, "VRENELI").
dico("V", 7, "VRILLAI").
dico("V", 7, "VRILLAS").
dico("V", 7, "VRILLAT").
dico("V", 7, "VRILLEE").
dico("V", 7, "VRILLER").
dico("V", 7, "VRILLES").
dico("V", 7, "VRILLEZ").
dico("V", 7, "VROMBIR").
dico("V", 7, "VROMBIS").
dico("V", 7, "VROMBIT").
dico("V", 7, "VULCAIN").
dico("V", 7, "VULGATE").
dico("V", 7, "VULPINE").
dico("V", 7, "VULPINS").
dico("V", 7, "VULVITE").
dico("V", 7, "VUMETRE").
