dico("V", 8, "VACANCES").
dico("V", 8, "VACANTES").
dico("V", 8, "VACARMES").
dico("V", 8, "VACATION").
dico("V", 8, "VACCAIRE").
dico("V", 8, "VACCINAI").
dico("V", 8, "VACCINAL").
dico("V", 8, "VACCINAS").
dico("V", 8, "VACCINAT").
dico("V", 8, "VACCINEE").
dico("V", 8, "VACCINER").
dico("V", 8, "VACCINES").
dico("V", 8, "VACCINEZ").
dico("V", 8, "VACHAMES").
dico("V", 8, "VACHARDE").
dico("V", 8, "VACHARDS").
dico("V", 8, "VACHASSE").
dico("V", 8, "VACHATES").
dico("V", 8, "VACHERAI").
dico("V", 8, "VACHERAS").
dico("V", 8, "VACHERES").
dico("V", 8, "VACHEREZ").
dico("V", 8, "VACHERIE").
dico("V", 8, "VACHERIN").
dico("V", 8, "VACHETTE").
dico("V", 8, "VACHIONS").
dico("V", 8, "VACILLAI").
dico("V", 8, "VACILLAS").
dico("V", 8, "VACILLAT").
dico("V", 8, "VACILLER").
dico("V", 8, "VACILLES").
dico("V", 8, "VACILLEZ").
dico("V", 8, "VACUITES").
dico("V", 8, "VACUOLES").
dico("V", 8, "VACUOMES").
dico("V", 8, "VAGABOND").
dico("V", 8, "VAGINALE").
dico("V", 8, "VAGINAUX").
dico("V", 8, "VAGINEES").
dico("V", 8, "VAGINITE").
dico("V", 8, "VAGIRAIS").
dico("V", 8, "VAGIRAIT").
dico("V", 8, "VAGIRENT").
dico("V", 8, "VAGIRIEZ").
dico("V", 8, "VAGIRONS").
dico("V", 8, "VAGIRONT").
dico("V", 8, "VAGISSES").
dico("V", 8, "VAGISSEZ").
dico("V", 8, "VAGUAMES").
dico("V", 8, "VAGUASSE").
dico("V", 8, "VAGUATES").
dico("V", 8, "VAGUERAI").
dico("V", 8, "VAGUERAS").
dico("V", 8, "VAGUEREZ").
dico("V", 8, "VAGUIONS").
dico("V", 8, "VAIGRAGE").
dico("V", 8, "VAILLANT").
dico("V", 8, "VAILLENT").
dico("V", 8, "VAINCRAI").
dico("V", 8, "VAINCRAS").
dico("V", 8, "VAINCREZ").
dico("V", 8, "VAINCUES").
dico("V", 8, "VAINQUES").
dico("V", 8, "VAINQUEZ").
dico("V", 8, "VAINQUIS").
dico("V", 8, "VAINQUIT").
dico("V", 8, "VAISHYAS").
dico("V", 8, "VAISSEAU").
dico("V", 8, "VALABLES").
dico("V", 8, "VALAIENT").
dico("V", 8, "VALAISAN").
dico("V", 8, "VALAQUES").
dico("V", 8, "VALDISME").
dico("V", 8, "VALENCAY").
dico("V", 8, "VALENCES").
dico("V", 8, "VALENCIA").
dico("V", 8, "VALENTIN").
dico("V", 8, "VALIDAIS").
dico("V", 8, "VALIDAIT").
dico("V", 8, "VALIDANT").
dico("V", 8, "VALIDEES").
dico("V", 8, "VALIDENT").
dico("V", 8, "VALIDERA").
dico("V", 8, "VALIDIEZ").
dico("V", 8, "VALIDITE").
dico("V", 8, "VALIDONS").
dico("V", 8, "VALKYRIE").
dico("V", 8, "VALLEUSE").
dico("V", 8, "VALLONNA").
dico("V", 8, "VALLONNE").
dico("V", 8, "VALOCHES").
dico("V", 8, "VALORISA").
dico("V", 8, "VALORISE").
dico("V", 8, "VALSAMES").
dico("V", 8, "VALSASSE").
dico("V", 8, "VALSATES").
dico("V", 8, "VALSERAI").
dico("V", 8, "VALSERAS").
dico("V", 8, "VALSEREZ").
dico("V", 8, "VALSEURS").
dico("V", 8, "VALSEUSE").
dico("V", 8, "VALSIONS").
dico("V", 8, "VALURENT").
dico("V", 8, "VALUSSES").
dico("V", 8, "VALVAIRE").
dico("V", 8, "VALVULES").
dico("V", 8, "VAMPAMES").
dico("V", 8, "VAMPASSE").
dico("V", 8, "VAMPATES").
dico("V", 8, "VAMPERAI").
dico("V", 8, "VAMPERAS").
dico("V", 8, "VAMPEREZ").
dico("V", 8, "VAMPIONS").
dico("V", 8, "VAMPIRES").
dico("V", 8, "VANADIUM").
dico("V", 8, "VANDALES").
dico("V", 8, "VANDOISE").
dico("V", 8, "VANESSES").
dico("V", 8, "VANGERON").
dico("V", 8, "VANILLEE").
dico("V", 8, "VANILLES").
dico("V", 8, "VANILLON").
dico("V", 8, "VANISAGE").
dico("V", 8, "VANISEES").
dico("V", 8, "VANITEUX").
dico("V", 8, "VANNAGES").
dico("V", 8, "VANNAMES").
dico("V", 8, "VANNASSE").
dico("V", 8, "VANNATES").
dico("V", 8, "VANNEAUX").
dico("V", 8, "VANNELLE").
dico("V", 8, "VANNERAI").
dico("V", 8, "VANNERAS").
dico("V", 8, "VANNEREZ").
dico("V", 8, "VANNERIE").
dico("V", 8, "VANNETTE").
dico("V", 8, "VANNEURS").
dico("V", 8, "VANNEUSE").
dico("V", 8, "VANNIERE").
dico("V", 8, "VANNIERS").
dico("V", 8, "VANNIONS").
dico("V", 8, "VANNURES").
dico("V", 8, "VANTAMES").
dico("V", 8, "VANTARDE").
dico("V", 8, "VANTARDS").
dico("V", 8, "VANTASSE").
dico("V", 8, "VANTATES").
dico("V", 8, "VANTELLE").
dico("V", 8, "VANTERAI").
dico("V", 8, "VANTERAS").
dico("V", 8, "VANTEREZ").
dico("V", 8, "VANTERIE").
dico("V", 8, "VANTIONS").
dico("V", 8, "VAPOREUX").
dico("V", 8, "VAPORISA").
dico("V", 8, "VAPORISE").
dico("V", 8, "VAQUAMES").
dico("V", 8, "VAQUASSE").
dico("V", 8, "VAQUATES").
dico("V", 8, "VAQUERAI").
dico("V", 8, "VAQUERAS").
dico("V", 8, "VAQUEREZ").
dico("V", 8, "VAQUEROS").
dico("V", 8, "VAQUIONS").
dico("V", 8, "VARAIGNE").
dico("V", 8, "VARANGUE").
dico("V", 8, "VARAPPAI").
dico("V", 8, "VARAPPAS").
dico("V", 8, "VARAPPAT").
dico("V", 8, "VARAPPER").
dico("V", 8, "VARAPPES").
dico("V", 8, "VARAPPEZ").
dico("V", 8, "VARENNES").
dico("V", 8, "VAREUSES").
dico("V", 8, "VARHEURE").
dico("V", 8, "VARIABLE").
dico("V", 8, "VARIAMES").
dico("V", 8, "VARIANCE").
dico("V", 8, "VARIANTE").
dico("V", 8, "VARIANTS").
dico("V", 8, "VARIASSE").
dico("V", 8, "VARIATES").
dico("V", 8, "VARIERAI").
dico("V", 8, "VARIERAS").
dico("V", 8, "VARIEREZ").
dico("V", 8, "VARIETAL").
dico("V", 8, "VARIETES").
dico("V", 8, "VARIIONS").
dico("V", 8, "VARIOLEE").
dico("V", 8, "VARIOLES").
dico("V", 8, "VARIORUM").
dico("V", 8, "VARLOPAI").
dico("V", 8, "VARLOPAS").
dico("V", 8, "VARLOPAT").
dico("V", 8, "VARLOPEE").
dico("V", 8, "VARLOPER").
dico("V", 8, "VARLOPES").
dico("V", 8, "VARLOPEZ").
dico("V", 8, "VARMETRE").
dico("V", 8, "VAROISES").
dico("V", 8, "VASARDES").
dico("V", 8, "VASELINA").
dico("V", 8, "VASELINE").
dico("V", 8, "VASEUSES").
dico("V", 8, "VASIERES").
dico("V", 8, "VASISTAS").
dico("V", 8, "VASSALES").
dico("V", 8, "VATICANE").
dico("V", 8, "VATICINA").
dico("V", 8, "VATICINE").
dico("V", 8, "VAUDAIRE").
dico("V", 8, "VAUDOISE").
dico("V", 8, "VAUDOUES").
dico("V", 8, "VAUDRAIS").
dico("V", 8, "VAUDRAIT").
dico("V", 8, "VAUDRIEZ").
dico("V", 8, "VAUDRONS").
dico("V", 8, "VAUDRONT").
dico("V", 8, "VAURIENS").
dico("V", 8, "VAUTOURS").
dico("V", 8, "VAUTRAIS").
dico("V", 8, "VAUTRAIT").
dico("V", 8, "VAUTRANT").
dico("V", 8, "VAUTREES").
dico("V", 8, "VAUTRENT").
dico("V", 8, "VAUTRERA").
dico("V", 8, "VAUTRIEZ").
dico("V", 8, "VAUTRONS").
dico("V", 8, "VAVASSAL").
dico("V", 8, "VECTEURS").
dico("V", 8, "VECTRICE").
dico("V", 8, "VECURENT").
dico("V", 8, "VECUSSES").
dico("V", 8, "VEDANTAS").
dico("V", 8, "VEDETTES").
dico("V", 8, "VEDIQUES").
dico("V", 8, "VEDISMES").
dico("V", 8, "VEGETAIS").
dico("V", 8, "VEGETAIT").
dico("V", 8, "VEGETALE").
dico("V", 8, "VEGETANT").
dico("V", 8, "VEGETAUX").
dico("V", 8, "VEGETENT").
dico("V", 8, "VEGETERA").
dico("V", 8, "VEGETIEZ").
dico("V", 8, "VEGETONS").
dico("V", 8, "VEHEMENT").
dico("V", 8, "VEHICULA").
dico("V", 8, "VEHICULE").
dico("V", 8, "VEHMIQUE").
dico("V", 8, "VEILLAIS").
dico("V", 8, "VEILLAIT").
dico("V", 8, "VEILLANT").
dico("V", 8, "VEILLEES").
dico("V", 8, "VEILLENT").
dico("V", 8, "VEILLERA").
dico("V", 8, "VEILLEUR").
dico("V", 8, "VEILLIEZ").
dico("V", 8, "VEILLONS").
dico("V", 8, "VEINAMES").
dico("V", 8, "VEINARDE").
dico("V", 8, "VEINARDS").
dico("V", 8, "VEINASSE").
dico("V", 8, "VEINATES").
dico("V", 8, "VEINERAI").
dico("V", 8, "VEINERAS").
dico("V", 8, "VEINEREZ").
dico("V", 8, "VEINETTE").
dico("V", 8, "VEINEUSE").
dico("V", 8, "VEINIONS").
dico("V", 8, "VEINULES").
dico("V", 8, "VEINURES").
dico("V", 8, "VELAIENT").
dico("V", 8, "VELAIRES").
dico("V", 8, "VELARIUM").
dico("V", 8, "VELASSES").
dico("V", 8, "VELEMENT").
dico("V", 8, "VELERAIS").
dico("V", 8, "VELERAIT").
dico("V", 8, "VELERENT").
dico("V", 8, "VELERIEZ").
dico("V", 8, "VELERONS").
dico("V", 8, "VELERONT").
dico("V", 8, "VELEUSES").
dico("V", 8, "VELIQUES").
dico("V", 8, "VELIVOLE").
dico("V", 8, "VELLAVES").
dico("V", 8, "VELLEITE").
dico("V", 8, "VELOCITE").
dico("V", 8, "VELOSKIS").
dico("V", 8, "VELOUTAI").
dico("V", 8, "VELOUTAS").
dico("V", 8, "VELOUTAT").
dico("V", 8, "VELOUTEE").
dico("V", 8, "VELOUTER").
dico("V", 8, "VELOUTES").
dico("V", 8, "VELOUTEZ").
dico("V", 8, "VELTAGES").
dico("V", 8, "VELVOTES").
dico("V", 8, "VENAIENT").
dico("V", 8, "VENAISON").
dico("V", 8, "VENALITE").
dico("V", 8, "VENANTES").
dico("V", 8, "VENDABLE").
dico("V", 8, "VENDANGE").
dico("V", 8, "VENDEENS").
dico("V", 8, "VENDETTA").
dico("V", 8, "VENDEURS").
dico("V", 8, "VENDEUSE").
dico("V", 8, "VENDIMES").
dico("V", 8, "VENDIONS").
dico("V", 8, "VENDISSE").
dico("V", 8, "VENDITES").
dico("V", 8, "VENDRAIS").
dico("V", 8, "VENDRAIT").
dico("V", 8, "VENDREDI").
dico("V", 8, "VENDRIEZ").
dico("V", 8, "VENDRONS").
dico("V", 8, "VENDRONT").
dico("V", 8, "VENELLES").
dico("V", 8, "VENENEUX").
dico("V", 8, "VENERAIS").
dico("V", 8, "VENERAIT").
dico("V", 8, "VENERANT").
dico("V", 8, "VENEREES").
dico("V", 8, "VENERENT").
dico("V", 8, "VENERERA").
dico("V", 8, "VENERIEN").
dico("V", 8, "VENERIES").
dico("V", 8, "VENERIEZ").
dico("V", 8, "VENERONS").
dico("V", 8, "VENETTES").
dico("V", 8, "VENGEAIS").
dico("V", 8, "VENGEAIT").
dico("V", 8, "VENGEANT").
dico("V", 8, "VENGEONS").
dico("V", 8, "VENGERAI").
dico("V", 8, "VENGERAS").
dico("V", 8, "VENGEREZ").
dico("V", 8, "VENGERON").
dico("V", 8, "VENGEURS").
dico("V", 8, "VENGIONS").
dico("V", 8, "VENIELLE").
dico("V", 8, "VENIMEUX").
dico("V", 8, "VENITIEN").
dico("V", 8, "VENTAGES").
dico("V", 8, "VENTEAUX").
dico("V", 8, "VENTEUSE").
dico("V", 8, "VENTILAI").
dico("V", 8, "VENTILAS").
dico("V", 8, "VENTILAT").
dico("V", 8, "VENTILEE").
dico("V", 8, "VENTILER").
dico("V", 8, "VENTILES").
dico("V", 8, "VENTILEZ").
dico("V", 8, "VENTOSES").
dico("V", 8, "VENTOUSE").
dico("V", 8, "VENTRALE").
dico("V", 8, "VENTRAUX").
dico("V", 8, "VENTREES").
dico("V", 8, "VENTRUES").
dico("V", 8, "VENTURIS").
dico("V", 8, "VENUSIEN").
dico("V", 8, "VENUSTES").
dico("V", 8, "VERACITE").
dico("V", 8, "VERAISON").
dico("V", 8, "VERANDAS").
dico("V", 8, "VERATRES").
dico("V", 8, "VERBALES").
dico("V", 8, "VERBATIM").
dico("V", 8, "VERBEUSE").
dico("V", 8, "VERBIAGE").
dico("V", 8, "VERDAGES").
dico("V", 8, "VERDATRE").
dico("V", 8, "VERDELET").
dico("V", 8, "VERDEURS").
dico("V", 8, "VERDICTS").
dico("V", 8, "VERDIERS").
dico("V", 8, "VERDIMES").
dico("V", 8, "VERDIRAI").
dico("V", 8, "VERDIRAS").
dico("V", 8, "VERDIREZ").
dico("V", 8, "VERDISSE").
dico("V", 8, "VERDITES").
dico("V", 8, "VERDOIES").
dico("V", 8, "VERDOYAI").
dico("V", 8, "VERDOYAS").
dico("V", 8, "VERDOYAT").
dico("V", 8, "VERDOYER").
dico("V", 8, "VERDOYEZ").
dico("V", 8, "VERDURES").
dico("V", 8, "VEREUSES").
dico("V", 8, "VERGENCE").
dico("V", 8, "VERGETEE").
dico("V", 8, "VERGETES").
dico("V", 8, "VERGETTE").
dico("V", 8, "VERGEURE").
dico("V", 8, "VERGLACA").
dico("V", 8, "VERGLACE").
dico("V", 8, "VERGOGNE").
dico("V", 8, "VERIFIAI").
dico("V", 8, "VERIFIAS").
dico("V", 8, "VERIFIAT").
dico("V", 8, "VERIFIEE").
dico("V", 8, "VERIFIER").
dico("V", 8, "VERIFIES").
dico("V", 8, "VERIFIEZ").
dico("V", 8, "VERISMES").
dico("V", 8, "VERISTES").
dico("V", 8, "VERJUTAI").
dico("V", 8, "VERJUTAS").
dico("V", 8, "VERJUTAT").
dico("V", 8, "VERJUTEE").
dico("V", 8, "VERJUTER").
dico("V", 8, "VERJUTES").
dico("V", 8, "VERJUTEZ").
dico("V", 8, "VERMEILS").
dico("V", 8, "VERMILLA").
dico("V", 8, "VERMILLE").
dico("V", 8, "VERMINES").
dico("V", 8, "VERMOULA").
dico("V", 8, "VERMOULE").
dico("V", 8, "VERMOULU").
dico("V", 8, "VERMOUTH").
dico("V", 8, "VERMOUTS").
dico("V", 8, "VERNALES").
dico("V", 8, "VERNIERS").
dico("V", 8, "VERNIMES").
dico("V", 8, "VERNIRAI").
dico("V", 8, "VERNIRAS").
dico("V", 8, "VERNIREZ").
dico("V", 8, "VERNISSA").
dico("V", 8, "VERNISSE").
dico("V", 8, "VERNITES").
dico("V", 8, "VEROLAIS").
dico("V", 8, "VEROLAIT").
dico("V", 8, "VEROLANT").
dico("V", 8, "VEROLEES").
dico("V", 8, "VEROLENT").
dico("V", 8, "VEROLERA").
dico("V", 8, "VEROLEUX").
dico("V", 8, "VEROLIEZ").
dico("V", 8, "VEROLONS").
dico("V", 8, "VERONAIS").
dico("V", 8, "VERONALS").
dico("V", 8, "VERRANNE").
dico("V", 8, "VERRERIE").
dico("V", 8, "VERRIERE").
dico("V", 8, "VERRIERS").
dico("V", 8, "VERRINES").
dico("V", 8, "VERRIONS").
dico("V", 8, "VERSAGES").
dico("V", 8, "VERSAMES").
dico("V", 8, "VERSANTE").
dico("V", 8, "VERSANTS").
dico("V", 8, "VERSASSE").
dico("V", 8, "VERSATES").
dico("V", 8, "VERSEAUX").
dico("V", 8, "VERSERAI").
dico("V", 8, "VERSERAS").
dico("V", 8, "VERSEREZ").
dico("V", 8, "VERSEURS").
dico("V", 8, "VERSEUSE").
dico("V", 8, "VERSIFIA").
dico("V", 8, "VERSIFIE").
dico("V", 8, "VERSIONS").
dico("V", 8, "VERSOIRS").
dico("V", 8, "VERTEBRE").
dico("V", 8, "VERTICAL").
dico("V", 8, "VERTIGES").
dico("V", 8, "VERTIGOS").
dico("V", 8, "VERTISOL").
dico("V", 8, "VERTUEUX").
dico("V", 8, "VERVEINE").
dico("V", 8, "VERVELLE").
dico("V", 8, "VERVEUSE").
dico("V", 8, "VESANIES").
dico("V", 8, "VESICALE").
dico("V", 8, "VESICANT").
dico("V", 8, "VESICAUX").
dico("V", 8, "VESICULE").
dico("V", 8, "VESPERAL").
dico("V", 8, "VESPETRO").
dico("V", 8, "VESPIDES").
dico("V", 8, "VESPREES").
dico("V", 8, "VESSAMES").
dico("V", 8, "VESSASSE").
dico("V", 8, "VESSATES").
dico("V", 8, "VESSERAI").
dico("V", 8, "VESSERAS").
dico("V", 8, "VESSEREZ").
dico("V", 8, "VESSIGON").
dico("V", 8, "VESSIONS").
dico("V", 8, "VESTALES").
dico("V", 8, "VESTIGES").
dico("V", 8, "VESULIEN").
dico("V", 8, "VETAIENT").
dico("V", 8, "VETEMENT").
dico("V", 8, "VETERANS").
dico("V", 8, "VETILLAI").
dico("V", 8, "VETILLAS").
dico("V", 8, "VETILLAT").
dico("V", 8, "VETILLER").
dico("V", 8, "VETILLES").
dico("V", 8, "VETILLEZ").
dico("V", 8, "VETIRAIS").
dico("V", 8, "VETIRAIT").
dico("V", 8, "VETIRENT").
dico("V", 8, "VETIRIEZ").
dico("V", 8, "VETIRONS").
dico("V", 8, "VETIRONT").
dico("V", 8, "VETISSES").
dico("V", 8, "VETIVERS").
dico("V", 8, "VETUSTES").
dico("V", 8, "VEUILLES").
dico("V", 8, "VEUILLEZ").
dico("V", 8, "VEULERIE").
dico("V", 8, "VEUVAGES").
dico("V", 8, "VEXAIENT").
dico("V", 8, "VEXANTES").
dico("V", 8, "VEXASSES").
dico("V", 8, "VEXATEUR").
dico("V", 8, "VEXATION").
dico("V", 8, "VEXERAIS").
dico("V", 8, "VEXERAIT").
dico("V", 8, "VEXERENT").
dico("V", 8, "VEXERIEZ").
dico("V", 8, "VEXERONS").
dico("V", 8, "VEXERONT").
dico("V", 8, "VEXILLES").
dico("V", 8, "VEXILLUM").
dico("V", 8, "VIAGERES").
dico("V", 8, "VIANDAIS").
dico("V", 8, "VIANDAIT").
dico("V", 8, "VIANDANT").
dico("V", 8, "VIANDEES").
dico("V", 8, "VIANDENT").
dico("V", 8, "VIANDERA").
dico("V", 8, "VIANDEUX").
dico("V", 8, "VIANDIEZ").
dico("V", 8, "VIANDONS").
dico("V", 8, "VIATIQUE").
dico("V", 8, "VIBRAGES").
dico("V", 8, "VIBRAMES").
dico("V", 8, "VIBRANTE").
dico("V", 8, "VIBRANTS").
dico("V", 8, "VIBRASSE").
dico("V", 8, "VIBRATES").
dico("V", 8, "VIBRATOS").
dico("V", 8, "VIBRERAI").
dico("V", 8, "VIBRERAS").
dico("V", 8, "VIBREREZ").
dico("V", 8, "VIBREURS").
dico("V", 8, "VIBRIONS").
dico("V", 8, "VIBRISSE").
dico("V", 8, "VICAIRES").
dico("V", 8, "VICARIAL").
dico("V", 8, "VICARIAT").
dico("V", 8, "VICELARD").
dico("V", 8, "VICENNAL").
dico("V", 8, "VICENTIN").
dico("V", 8, "VICHYSME").
dico("V", 8, "VICHYSTE").
dico("V", 8, "VICIABLE").
dico("V", 8, "VICIAMES").
dico("V", 8, "VICIASSE").
dico("V", 8, "VICIATES").
dico("V", 8, "VICIERAI").
dico("V", 8, "VICIERAS").
dico("V", 8, "VICIEREZ").
dico("V", 8, "VICIEUSE").
dico("V", 8, "VICIIONS").
dico("V", 8, "VICINALE").
dico("V", 8, "VICINAUX").
dico("V", 8, "VICOMTAL").
dico("V", 8, "VICOMTES").
dico("V", 8, "VICTIMES").
dico("V", 8, "VICTOIRE").
dico("V", 8, "VICTORIA").
dico("V", 8, "VIDAIENT").
dico("V", 8, "VIDAMIES").
dico("V", 8, "VIDANGEA").
dico("V", 8, "VIDANGEE").
dico("V", 8, "VIDANGER").
dico("V", 8, "VIDANGES").
dico("V", 8, "VIDANGEZ").
dico("V", 8, "VIDASSES").
dico("V", 8, "VIDEASTE").
dico("V", 8, "VIDELLES").
dico("V", 8, "VIDEOTEX").
dico("V", 8, "VIDERAIS").
dico("V", 8, "VIDERAIT").
dico("V", 8, "VIDERENT").
dico("V", 8, "VIDERIEZ").
dico("V", 8, "VIDERONS").
dico("V", 8, "VIDERONT").
dico("V", 8, "VIDEUSES").
dico("V", 8, "VIDICONS").
dico("V", 8, "VIDIMAIS").
dico("V", 8, "VIDIMAIT").
dico("V", 8, "VIDIMANT").
dico("V", 8, "VIDIMEES").
dico("V", 8, "VIDIMENT").
dico("V", 8, "VIDIMERA").
dico("V", 8, "VIDIMIEZ").
dico("V", 8, "VIDIMONS").
dico("V", 8, "VIDUITES").
dico("V", 8, "VIEILLES").
dico("V", 8, "VIEILLIE").
dico("V", 8, "VIEILLIR").
dico("V", 8, "VIEILLIS").
dico("V", 8, "VIEILLIT").
dico("V", 8, "VIEILLOT").
dico("V", 8, "VIELLAIS").
dico("V", 8, "VIELLAIT").
dico("V", 8, "VIELLANT").
dico("V", 8, "VIELLENT").
dico("V", 8, "VIELLERA").
dico("V", 8, "VIELLEUR").
dico("V", 8, "VIELLEUX").
dico("V", 8, "VIELLIEZ").
dico("V", 8, "VIELLONS").
dico("V", 8, "VIENDRAI").
dico("V", 8, "VIENDRAS").
dico("V", 8, "VIENDREZ").
dico("V", 8, "VIENNENT").
dico("V", 8, "VIENNOIS").
dico("V", 8, "VIGILANT").
dico("V", 8, "VIGNEAUX").
dico("V", 8, "VIGNERON").
dico("V", 8, "VIGNETAI").
dico("V", 8, "VIGNETAS").
dico("V", 8, "VIGNETAT").
dico("V", 8, "VIGNETEE").
dico("V", 8, "VIGNETER").
dico("V", 8, "VIGNETES").
dico("V", 8, "VIGNETEZ").
dico("V", 8, "VIGNETTE").
dico("V", 8, "VIGNOBLE").
dico("V", 8, "VIGOGNES").
dico("V", 8, "VIGOUSSE").
dico("V", 8, "VIGUERIE").
dico("V", 8, "VIGUEURS").
dico("V", 8, "VIGUIERS").
dico("V", 8, "VILAINES").
dico("V", 8, "VILAYETS").
dico("V", 8, "VILEMENT").
dico("V", 8, "VILENIES").
dico("V", 8, "VILLAGES").
dico("V", 8, "VILLEUSE").
dico("V", 8, "VINAIENT").
dico("V", 8, "VINAIGRA").
dico("V", 8, "VINAIGRE").
dico("V", 8, "VINAIRES").
dico("V", 8, "VINASSES").
dico("V", 8, "VINDICTE").
dico("V", 8, "VINERAIS").
dico("V", 8, "VINERAIT").
dico("V", 8, "VINERENT").
dico("V", 8, "VINERIEZ").
dico("V", 8, "VINERONS").
dico("V", 8, "VINERONT").
dico("V", 8, "VINEUSES").
dico("V", 8, "VINICOLE").
dico("V", 8, "VINIFERE").
dico("V", 8, "VINIFIAI").
dico("V", 8, "VINIFIAS").
dico("V", 8, "VINIFIAT").
dico("V", 8, "VINIFIEE").
dico("V", 8, "VINIFIER").
dico("V", 8, "VINIFIES").
dico("V", 8, "VINIFIEZ").
dico("V", 8, "VINIQUES").
dico("V", 8, "VINOSITE").
dico("V", 8, "VINSSENT").
dico("V", 8, "VINSSIEZ").
dico("V", 8, "VINTAGES").
dico("V", 8, "VINYLITE").
dico("V", 8, "VIOLACAI").
dico("V", 8, "VIOLACAS").
dico("V", 8, "VIOLACAT").
dico("V", 8, "VIOLACEE").
dico("V", 8, "VIOLACER").
dico("V", 8, "VIOLACES").
dico("V", 8, "VIOLACEZ").
dico("V", 8, "VIOLAMES").
dico("V", 8, "VIOLASSE").
dico("V", 8, "VIOLATES").
dico("V", 8, "VIOLATRE").
dico("V", 8, "VIOLENCE").
dico("V", 8, "VIOLENTA").
dico("V", 8, "VIOLENTE").
dico("V", 8, "VIOLENTS").
dico("V", 8, "VIOLERAI").
dico("V", 8, "VIOLERAS").
dico("V", 8, "VIOLEREZ").
dico("V", 8, "VIOLETAI").
dico("V", 8, "VIOLETAS").
dico("V", 8, "VIOLETAT").
dico("V", 8, "VIOLETEE").
dico("V", 8, "VIOLETER").
dico("V", 8, "VIOLETES").
dico("V", 8, "VIOLETEZ").
dico("V", 8, "VIOLETTE").
dico("V", 8, "VIOLEURS").
dico("V", 8, "VIOLEUSE").
dico("V", 8, "VIOLIERS").
dico("V", 8, "VIOLINES").
dico("V", 8, "VIOLIONS").
dico("V", 8, "VIOLISTE").
dico("V", 8, "VIOLONAI").
dico("V", 8, "VIOLONAS").
dico("V", 8, "VIOLONAT").
dico("V", 8, "VIOLONEE").
dico("V", 8, "VIOLONER").
dico("V", 8, "VIOLONES").
dico("V", 8, "VIOLONEZ").
dico("V", 8, "VIPEREAU").
dico("V", 8, "VIPERIAU").
dico("V", 8, "VIPERIDE").
dico("V", 8, "VIPERINE").
dico("V", 8, "VIPERINS").
dico("V", 8, "VIRAIENT").
dico("V", 8, "VIRAILLA").
dico("V", 8, "VIRAILLE").
dico("V", 8, "VIRASSES").
dico("V", 8, "VIRELAIS").
dico("V", 8, "VIREMENT").
dico("V", 8, "VIREMIES").
dico("V", 8, "VIRERAIS").
dico("V", 8, "VIRERAIT").
dico("V", 8, "VIRERENT").
dico("V", 8, "VIRERIEZ").
dico("V", 8, "VIRERONS").
dico("V", 8, "VIRERONT").
dico("V", 8, "VIRETONS").
dico("V", 8, "VIREUSES").
dico("V", 8, "VIRGINAL").
dico("V", 8, "VIRGINIE").
dico("V", 8, "VIRGULAI").
dico("V", 8, "VIRGULAS").
dico("V", 8, "VIRGULAT").
dico("V", 8, "VIRGULEE").
dico("V", 8, "VIRGULER").
dico("V", 8, "VIRGULES").
dico("V", 8, "VIRGULEZ").
dico("V", 8, "VIRILISA").
dico("V", 8, "VIRILISE").
dico("V", 8, "VIRILITE").
dico("V", 8, "VIROCIDE").
dico("V", 8, "VIROIDES").
dico("V", 8, "VIROLAGE").
dico("V", 8, "VIROLAIS").
dico("V", 8, "VIROLAIT").
dico("V", 8, "VIROLANT").
dico("V", 8, "VIROLEES").
dico("V", 8, "VIROLENT").
dico("V", 8, "VIROLERA").
dico("V", 8, "VIROLETS").
dico("V", 8, "VIROLIER").
dico("V", 8, "VIROLIEZ").
dico("V", 8, "VIROLONS").
dico("V", 8, "VIRTUELS").
dico("V", 8, "VIRTUOSE").
dico("V", 8, "VIRUCIDE").
dico("V", 8, "VIRULENT").
dico("V", 8, "VISAIENT").
dico("V", 8, "VISASSES").
dico("V", 8, "VISCACHE").
dico("V", 8, "VISCERAL").
dico("V", 8, "VISCERES").
dico("V", 8, "VISCOSES").
dico("V", 8, "VISERAIS").
dico("V", 8, "VISERAIT").
dico("V", 8, "VISERENT").
dico("V", 8, "VISERIEZ").
dico("V", 8, "VISERONS").
dico("V", 8, "VISERONT").
dico("V", 8, "VISIBLES").
dico("V", 8, "VISIERES").
dico("V", 8, "VISIGOTH").
dico("V", 8, "VISIONNA").
dico("V", 8, "VISIONNE").
dico("V", 8, "VISITAIS").
dico("V", 8, "VISITAIT").
dico("V", 8, "VISITANT").
dico("V", 8, "VISITEES").
dico("V", 8, "VISITENT").
dico("V", 8, "VISITERA").
dico("V", 8, "VISITEUR").
dico("V", 8, "VISITIEZ").
dico("V", 8, "VISITONS").
dico("V", 8, "VISNAGES").
dico("V", 8, "VISNUITE").
dico("V", 8, "VISQUEUX").
dico("V", 8, "VISSAGES").
dico("V", 8, "VISSAMES").
dico("V", 8, "VISSASSE").
dico("V", 8, "VISSATES").
dico("V", 8, "VISSERAI").
dico("V", 8, "VISSERAS").
dico("V", 8, "VISSEREZ").
dico("V", 8, "VISSERIE").
dico("V", 8, "VISSEUSE").
dico("V", 8, "VISSIONS").
dico("V", 8, "VISUELLE").
dico("V", 8, "VITACEES").
dico("V", 8, "VITALITE").
dico("V", 8, "VITAMINA").
dico("V", 8, "VITAMINE").
dico("V", 8, "VITELLIN").
dico("V", 8, "VITELLUS").
dico("V", 8, "VITESSES").
dico("V", 8, "VITICOLE").
dico("V", 8, "VITILIGO").
dico("V", 8, "VITOULET").
dico("V", 8, "VITRAGES").
dico("V", 8, "VITRAINS").
dico("V", 8, "VITRAMES").
dico("V", 8, "VITRASSE").
dico("V", 8, "VITRATES").
dico("V", 8, "VITRERAI").
dico("V", 8, "VITRERAS").
dico("V", 8, "VITREREZ").
dico("V", 8, "VITRERIE").
dico("V", 8, "VITREUSE").
dico("V", 8, "VITRIERE").
dico("V", 8, "VITRIERS").
dico("V", 8, "VITRIFIA").
dico("V", 8, "VITRIFIE").
dico("V", 8, "VITRINES").
dico("V", 8, "VITRIOLA").
dico("V", 8, "VITRIOLE").
dico("V", 8, "VITRIOLS").
dico("V", 8, "VITRIONS").
dico("V", 8, "VITUPERA").
dico("V", 8, "VITUPERE").
dico("V", 8, "VIVABLES").
dico("V", 8, "VIVACITE").
dico("V", 8, "VIVAIENT").
dico("V", 8, "VIVANTES").
dico("V", 8, "VIVARAIS").
dico("V", 8, "VIVARIUM").
dico("V", 8, "VIVEMENT").
dico("V", 8, "VIVEUSES").
dico("V", 8, "VIVIDITE").
dico("V", 8, "VIVIFIAI").
dico("V", 8, "VIVIFIAS").
dico("V", 8, "VIVIFIAT").
dico("V", 8, "VIVIFIEE").
dico("V", 8, "VIVIFIER").
dico("V", 8, "VIVIFIES").
dico("V", 8, "VIVIFIEZ").
dico("V", 8, "VIVIPARE").
dico("V", 8, "VIVOTAIS").
dico("V", 8, "VIVOTAIT").
dico("V", 8, "VIVOTANT").
dico("V", 8, "VIVOTENT").
dico("V", 8, "VIVOTERA").
dico("V", 8, "VIVOTIEZ").
dico("V", 8, "VIVOTONS").
dico("V", 8, "VIVRIERE").
dico("V", 8, "VIVRIERS").
dico("V", 8, "VIVRIONS").
dico("V", 8, "VIZIRATS").
dico("V", 8, "VOCABLES").
dico("V", 8, "VOCALISA").
dico("V", 8, "VOCALISE").
dico("V", 8, "VOCATIFS").
dico("V", 8, "VOCATION").
dico("V", 8, "VOCIFERA").
dico("V", 8, "VOCIFERE").
dico("V", 8, "VOCODEUR").
dico("V", 8, "VOGELPIK").
dico("V", 8, "VOGOULES").
dico("V", 8, "VOGUAMES").
dico("V", 8, "VOGUASSE").
dico("V", 8, "VOGUATES").
dico("V", 8, "VOGUERAI").
dico("V", 8, "VOGUERAS").
dico("V", 8, "VOGUEREZ").
dico("V", 8, "VOGUIONS").
dico("V", 8, "VOIEVODE").
dico("V", 8, "VOILAGES").
dico("V", 8, "VOILAMES").
dico("V", 8, "VOILASSE").
dico("V", 8, "VOILATES").
dico("V", 8, "VOILERAI").
dico("V", 8, "VOILERAS").
dico("V", 8, "VOILEREZ").
dico("V", 8, "VOILERIE").
dico("V", 8, "VOILETTE").
dico("V", 8, "VOILIERS").
dico("V", 8, "VOILIONS").
dico("V", 8, "VOILURES").
dico("V", 8, "VOISINAI").
dico("V", 8, "VOISINAS").
dico("V", 8, "VOISINAT").
dico("V", 8, "VOISINER").
dico("V", 8, "VOISINES").
dico("V", 8, "VOISINEZ").
dico("V", 8, "VOITURAI").
dico("V", 8, "VOITURAS").
dico("V", 8, "VOITURAT").
dico("V", 8, "VOITUREE").
dico("V", 8, "VOITURER").
dico("V", 8, "VOITURES").
dico("V", 8, "VOITUREZ").
dico("V", 8, "VOITURIN").
dico("V", 8, "VOIVODAT").
dico("V", 8, "VOIVODES").
dico("V", 8, "VOIVODIE").
dico("V", 8, "VOLABLES").
dico("V", 8, "VOLAIENT").
dico("V", 8, "VOLAILLE").
dico("V", 8, "VOLANTES").
dico("V", 8, "VOLAPUKS").
dico("V", 8, "VOLASSES").
dico("V", 8, "VOLATILE").
dico("V", 8, "VOLATILS").
dico("V", 8, "VOLEMIES").
dico("V", 8, "VOLERAIS").
dico("V", 8, "VOLERAIT").
dico("V", 8, "VOLERENT").
dico("V", 8, "VOLERIES").
dico("V", 8, "VOLERIEZ").
dico("V", 8, "VOLERONS").
dico("V", 8, "VOLERONT").
dico("V", 8, "VOLETAIS").
dico("V", 8, "VOLETAIT").
dico("V", 8, "VOLETANT").
dico("V", 8, "VOLETIEZ").
dico("V", 8, "VOLETONS").
dico("V", 8, "VOLETTES").
dico("V", 8, "VOLEUSES").
dico("V", 8, "VOLIERES").
dico("V", 8, "VOLIGEAI").
dico("V", 8, "VOLIGEAS").
dico("V", 8, "VOLIGEAT").
dico("V", 8, "VOLIGEES").
dico("V", 8, "VOLIGENT").
dico("V", 8, "VOLIGERA").
dico("V", 8, "VOLIGIEZ").
dico("V", 8, "VOLITIFS").
dico("V", 8, "VOLITION").
dico("V", 8, "VOLITIVE").
dico("V", 8, "VOLLEYAI").
dico("V", 8, "VOLLEYAS").
dico("V", 8, "VOLLEYAT").
dico("V", 8, "VOLLEYEE").
dico("V", 8, "VOLLEYER").
dico("V", 8, "VOLLEYES").
dico("V", 8, "VOLLEYEZ").
dico("V", 8, "VOLONTES").
dico("V", 8, "VOLTAGES").
dico("V", 8, "VOLTAIRE").
dico("V", 8, "VOLTAMES").
dico("V", 8, "VOLTASSE").
dico("V", 8, "VOLTATES").
dico("V", 8, "VOLTERAI").
dico("V", 8, "VOLTERAS").
dico("V", 8, "VOLTEREZ").
dico("V", 8, "VOLTIGEA").
dico("V", 8, "VOLTIGER").
dico("V", 8, "VOLTIGES").
dico("V", 8, "VOLTIGEZ").
dico("V", 8, "VOLTIONS").
dico("V", 8, "VOLUBILE").
dico("V", 8, "VOLUPTES").
dico("V", 8, "VOLVAIRE").
dico("V", 8, "VOLVOCES").
dico("V", 8, "VOLVULUS").
dico("V", 8, "VOMERIEN").
dico("V", 8, "VOMIQUES").
dico("V", 8, "VOMIRAIS").
dico("V", 8, "VOMIRAIT").
dico("V", 8, "VOMIRENT").
dico("V", 8, "VOMIRIEZ").
dico("V", 8, "VOMIRONS").
dico("V", 8, "VOMIRONT").
dico("V", 8, "VOMISSES").
dico("V", 8, "VOMISSEZ").
dico("V", 8, "VOMITIFS").
dico("V", 8, "VOMITIVE").
dico("V", 8, "VORACITE").
dico("V", 8, "VOSGIENS").
dico("V", 8, "VOTAIENT").
dico("V", 8, "VOTANTES").
dico("V", 8, "VOTASSES").
dico("V", 8, "VOTATION").
dico("V", 8, "VOTERAIS").
dico("V", 8, "VOTERAIT").
dico("V", 8, "VOTERENT").
dico("V", 8, "VOTERIEZ").
dico("V", 8, "VOTERONS").
dico("V", 8, "VOTERONT").
dico("V", 8, "VOUAIENT").
dico("V", 8, "VOUASSES").
dico("V", 8, "VOUCHERS").
dico("V", 8, "VOUDRAIS").
dico("V", 8, "VOUDRAIT").
dico("V", 8, "VOUDRIEZ").
dico("V", 8, "VOUDRONS").
dico("V", 8, "VOUDRONT").
dico("V", 8, "VOUERAIS").
dico("V", 8, "VOUERAIT").
dico("V", 8, "VOUERENT").
dico("V", 8, "VOUERIEZ").
dico("V", 8, "VOUERONS").
dico("V", 8, "VOUERONT").
dico("V", 8, "VOUGEOTS").
dico("V", 8, "VOUIVRES").
dico("V", 8, "VOULIONS").
dico("V", 8, "VOULUMES").
dico("V", 8, "VOULUSSE").
dico("V", 8, "VOULUTES").
dico("V", 8, "VOUSOIES").
dico("V", 8, "VOUSOYAI").
dico("V", 8, "VOUSOYAS").
dico("V", 8, "VOUSOYAT").
dico("V", 8, "VOUSOYEE").
dico("V", 8, "VOUSOYER").
dico("V", 8, "VOUSOYES").
dico("V", 8, "VOUSOYEZ").
dico("V", 8, "VOUSSEAU").
dico("V", 8, "VOUSSOIE").
dico("V", 8, "VOUSSOIR").
dico("V", 8, "VOUSSOYA").
dico("V", 8, "VOUSSOYE").
dico("V", 8, "VOUSSURE").
dico("V", 8, "VOUTAINS").
dico("V", 8, "VOUTAMES").
dico("V", 8, "VOUTASSE").
dico("V", 8, "VOUTATES").
dico("V", 8, "VOUTERAI").
dico("V", 8, "VOUTERAS").
dico("V", 8, "VOUTEREZ").
dico("V", 8, "VOUTIONS").
dico("V", 8, "VOUVOIES").
dico("V", 8, "VOUVOYAI").
dico("V", 8, "VOUVOYAS").
dico("V", 8, "VOUVOYAT").
dico("V", 8, "VOUVOYEE").
dico("V", 8, "VOUVOYER").
dico("V", 8, "VOUVOYES").
dico("V", 8, "VOUVOYEZ").
dico("V", 8, "VOUVRAYS").
dico("V", 8, "VOYAGEAI").
dico("V", 8, "VOYAGEAS").
dico("V", 8, "VOYAGEAT").
dico("V", 8, "VOYAGENT").
dico("V", 8, "VOYAGERA").
dico("V", 8, "VOYAGEUR").
dico("V", 8, "VOYAGIEZ").
dico("V", 8, "VOYAIENT").
dico("V", 8, "VOYANCES").
dico("V", 8, "VOYANTES").
dico("V", 8, "VOYELLES").
dico("V", 8, "VOYEUSES").
dico("V", 8, "VOYOUTES").
dico("V", 8, "VRAIMENT").
dico("V", 8, "VRAQUIER").
dico("V", 8, "VRENELIS").
dico("V", 8, "VRILLAGE").
dico("V", 8, "VRILLAIS").
dico("V", 8, "VRILLAIT").
dico("V", 8, "VRILLANT").
dico("V", 8, "VRILLEES").
dico("V", 8, "VRILLENT").
dico("V", 8, "VRILLERA").
dico("V", 8, "VRILLIEZ").
dico("V", 8, "VRILLONS").
dico("V", 8, "VROMBIRA").
dico("V", 8, "VULCAINS").
dico("V", 8, "VULGAIRE").
dico("V", 8, "VULGATES").
dico("V", 8, "VULPINES").
dico("V", 8, "VULTUEUX").
dico("V", 8, "VULVAIRE").
dico("V", 8, "VULVITES").
dico("V", 8, "VUMETRES").
