dico("W", 10, "WAGNERIENS").
dico("W", 10, "WAGNERISME").
dico("W", 10, "WAGONNIERS").
dico("W", 10, "WAHHABISME").
dico("W", 10, "WAHHABITES").
dico("W", 10, "WALLINGANT").
dico("W", 10, "WALLISIENS").
dico("W", 10, "WALLONISME").
dico("W", 10, "WARRANTAGE").
dico("W", 10, "WARRANTAIS").
dico("W", 10, "WARRANTAIT").
dico("W", 10, "WARRANTANT").
dico("W", 10, "WARRANTEES").
dico("W", 10, "WARRANTENT").
dico("W", 10, "WARRANTERA").
dico("W", 10, "WARRANTIEZ").
dico("W", 10, "WARRANTONS").
dico("W", 10, "WASSINGUES").
dico("W", 10, "WATERGANGS").
dico("W", 10, "WATERINGUE").
dico("W", 10, "WATERPROOF").
dico("W", 10, "WATERZOEIS").
dico("W", 10, "WATERZOOIS").
dico("W", 10, "WATTHEURES").
dico("W", 10, "WATTMETRES").
dico("W", 10, "WAVRIENNES").
dico("W", 10, "WEBCAMERAS").
dico("W", 10, "WEBMESTRES").
dico("W", 10, "WESLEYENNE").
dico("W", 10, "WINCHESTER").
dico("W", 10, "WINDSURFER").
dico("W", 10, "WISIGOTHES").
dico("W", 10, "WOMBATIDES").
dico("W", 10, "WURMIENNES").
dico("W", 10, "WYANDOTTES").
