dico("W", 6, "WADING").
dico("W", 6, "WAGAGE").
dico("W", 6, "WAGONS").
dico("W", 6, "WALLON").
dico("W", 6, "WAPITI").
dico("W", 6, "WATERS").
dico("W", 6, "WATTEE").
dico("W", 6, "WATTES").
dico("W", 6, "WEBCAM").
dico("W", 6, "WEBERS").
dico("W", 6, "WELCHE").
dico("W", 6, "WELTER").
dico("W", 6, "WENGES").
dico("W", 6, "WENZES").
dico("W", 6, "WESTIE").
dico("W", 6, "WHARFS").
dico("W", 6, "WHISKY").
dico("W", 6, "WHISTS").
dico("W", 6, "WIDIAS").
dico("W", 6, "WIGWAM").
dico("W", 6, "WILAYA").
dico("W", 6, "WINCHS").
dico("W", 6, "WOLOFS").
dico("W", 6, "WOMBAT").
dico("W", 6, "WOOFER").
