dico("W", 8, "WAGONNEE").
dico("W", 8, "WAGONNET").
dico("W", 8, "WALKMANS").
dico("W", 8, "WALKYRIE").
dico("W", 8, "WALLABYS").
dico("W", 8, "WALLACES").
dico("W", 8, "WALLONNE").
dico("W", 8, "WARGAMES").
dico("W", 8, "WARNINGS").
dico("W", 8, "WARRANTA").
dico("W", 8, "WARRANTE").
dico("W", 8, "WARRANTS").
dico("W", 8, "WATERZOI").
dico("W", 8, "WATTMANS").
dico("W", 8, "WAVRIENS").
dico("W", 8, "WEHNELTS").
dico("W", 8, "WELSCHES").
dico("W", 8, "WERGELDS").
dico("W", 8, "WESLEYEN").
dico("W", 8, "WESTERNS").
dico("W", 8, "WHIPCORD").
dico("W", 8, "WHIPPETS").
dico("W", 8, "WHISKEYS").
dico("W", 8, "WHISKIES").
dico("W", 8, "WIENERLI").
dico("W", 8, "WILLAYAS").
dico("W", 8, "WILLIAMS").
dico("W", 8, "WINDSURF").
dico("W", 8, "WINSTUBS").
dico("W", 8, "WISHBONE").
dico("W", 8, "WISIGOTH").
dico("W", 8, "WITLOOFS").
dico("W", 8, "WOLFRAMS").
dico("W", 8, "WORMIENS").
dico("W", 8, "WURMIENS").
