dico("W", 9, "WAGNERIEN").
dico("W", 9, "WAGONNEES").
dico("W", 9, "WAGONNETS").
dico("W", 9, "WAGONNIER").
dico("W", 9, "WAHHABITE").
dico("W", 9, "WALKYRIES").
dico("W", 9, "WALLABIES").
dico("W", 9, "WALLISIEN").
dico("W", 9, "WALLONNES").
dico("W", 9, "WARRANTAI").
dico("W", 9, "WARRANTAS").
dico("W", 9, "WARRANTAT").
dico("W", 9, "WARRANTEE").
dico("W", 9, "WARRANTER").
dico("W", 9, "WARRANTES").
dico("W", 9, "WARRANTEZ").
dico("W", 9, "WASSINGUE").
dico("W", 9, "WATERGANG").
dico("W", 9, "WATERZOEI").
dico("W", 9, "WATERZOIS").
dico("W", 9, "WATERZOOI").
dico("W", 9, "WATTHEURE").
dico("W", 9, "WATTMETRE").
dico("W", 9, "WAVRIENNE").
dico("W", 9, "WEBCAMERA").
dico("W", 9, "WEBMESTRE").
dico("W", 9, "WESLEYENS").
dico("W", 9, "WHIPCORDS").
dico("W", 9, "WIENERLIS").
dico("W", 9, "WINDSURFS").
dico("W", 9, "WISHBONES").
dico("W", 9, "WISIGOTHE").
dico("W", 9, "WISIGOTHS").
dico("W", 9, "WOMBATIDE").
dico("W", 9, "WURMIENNE").
dico("W", 9, "WYANDOTTE").
