dico("X", 8, "XANTHIES").
dico("X", 8, "XANTHINE").
dico("X", 8, "XANTHOME").
dico("X", 8, "XENOLITE").
dico("X", 8, "XIMENIAS").
dico("X", 8, "XIMENIES").
dico("X", 8, "XIPHOIDE").
dico("X", 8, "XYLIDINE").
dico("X", 8, "XYLOCOPE").
