dico("Y", 10, "YACHTSMANS").
dico("Y", 10, "YACHTWOMAN").
dico("Y", 10, "YACHTWOMEN").
dico("Y", 10, "YAOUNDEENS").
dico("Y", 10, "YAOURTIERE").
dico("Y", 10, "YASSASSENT").
dico("Y", 10, "YASSASSIEZ").
dico("Y", 10, "YASSERIONS").
dico("Y", 10, "YODLASSENT").
dico("Y", 10, "YODLASSIEZ").
dico("Y", 10, "YODLERIONS").
dico("Y", 10, "YOHIMBEHES").
dico("Y", 10, "YOHIMBINES").
dico("Y", 10, "YORKSHIRES").
dico("Y", 10, "YOUGOSLAVE").
dico("Y", 10, "YOUTSAIENT").
dico("Y", 10, "YOUTSASSES").
dico("Y", 10, "YOUTSERAIS").
dico("Y", 10, "YOUTSERAIT").
dico("Y", 10, "YOUTSERENT").
dico("Y", 10, "YOUTSERIEZ").
dico("Y", 10, "YOUTSERONS").
dico("Y", 10, "YOUTSERONT").
dico("Y", 10, "YOYOTAIENT").
dico("Y", 10, "YOYOTASSES").
dico("Y", 10, "YOYOTERAIS").
dico("Y", 10, "YOYOTERAIT").
dico("Y", 10, "YOYOTERENT").
dico("Y", 10, "YOYOTERIEZ").
dico("Y", 10, "YOYOTERONS").
dico("Y", 10, "YOYOTERONT").
dico("Y", 10, "YOYOTTAMES").
dico("Y", 10, "YOYOTTASSE").
dico("Y", 10, "YOYOTTATES").
dico("Y", 10, "YOYOTTERAI").
dico("Y", 10, "YOYOTTERAS").
dico("Y", 10, "YOYOTTEREZ").
dico("Y", 10, "YOYOTTIONS").
dico("Y", 10, "YPONOMEUTE").
dico("Y", 10, "YPRESIENNE").
dico("Y", 10, "YTTERBINES").
dico("Y", 10, "YTTERBIUMS").
dico("Y", 10, "YTTRIALITE").
dico("Y", 10, "YTTRIFERES").
dico("Y", 10, "YUKONNAISE").
dico("Y", 10, "YVELINOISE").
