dico("Y", 5, "YACHT").
dico("Y", 5, "YACKS").
dico("Y", 5, "YAKAS").
dico("Y", 5, "YANGS").
dico("Y", 5, "YAPOK").
dico("Y", 5, "YARDS").
dico("Y", 5, "YASSA").
dico("Y", 5, "YASSE").
dico("Y", 5, "YAWLS").
dico("Y", 5, "YEBLE").
dico("Y", 5, "YETIS").
dico("Y", 5, "YEUSE").
dico("Y", 5, "YEYES").
dico("Y", 5, "YODLA").
dico("Y", 5, "YODLE").
dico("Y", 5, "YOGAS").
dico("Y", 5, "YOGIS").
dico("Y", 5, "YOLES").
dico("Y", 5, "YOUPI").
dico("Y", 5, "YUANS").
dico("Y", 5, "YUCCA").
dico("Y", 5, "YUKOS").
