dico("Y", 7, "YAKUSAS").
dico("Y", 7, "YAKUZAS").
dico("Y", 7, "YANKEES").
dico("Y", 7, "YAOURTS").
dico("Y", 7, "YAPOCKS").
dico("Y", 7, "YASSAIS").
dico("Y", 7, "YASSAIT").
dico("Y", 7, "YASSANT").
dico("Y", 7, "YASSENT").
dico("Y", 7, "YASSERA").
dico("Y", 7, "YASSEUR").
dico("Y", 7, "YASSIEZ").
dico("Y", 7, "YASSONS").
dico("Y", 7, "YATAGAN").
dico("Y", 7, "YEOMANS").
dico("Y", 7, "YESHIVA").
dico("Y", 7, "YIDDISH").
dico("Y", 7, "YODLAIS").
dico("Y", 7, "YODLAIT").
dico("Y", 7, "YODLANT").
dico("Y", 7, "YODLENT").
dico("Y", 7, "YODLERA").
dico("Y", 7, "YODLIEZ").
dico("Y", 7, "YODLONS").
dico("Y", 7, "YOGOURT").
dico("Y", 7, "YONNAIS").
dico("Y", 7, "YORUBAS").
dico("Y", 7, "YOUPALA").
dico("Y", 7, "YOUPPIE").
dico("Y", 7, "YOURTES").
dico("Y", 7, "YOUTSAI").
dico("Y", 7, "YOUTSAS").
dico("Y", 7, "YOUTSAT").
dico("Y", 7, "YOUTSER").
dico("Y", 7, "YOUTSES").
dico("Y", 7, "YOUTSEZ").
dico("Y", 7, "YOUYOUS").
dico("Y", 7, "YOYOTAI").
dico("Y", 7, "YOYOTAS").
dico("Y", 7, "YOYOTAT").
dico("Y", 7, "YOYOTER").
dico("Y", 7, "YOYOTES").
dico("Y", 7, "YOYOTEZ").
dico("Y", 7, "YOYOTTA").
dico("Y", 7, "YOYOTTE").
dico("Y", 7, "YPERITE").
dico("Y", 7, "YPREAUX").
dico("Y", 7, "YSOPETS").
dico("Y", 7, "YTTRIAS").
dico("Y", 7, "YTTRIUM").
dico("Y", 7, "YUPPIES").
