dico("Y", 8, "YACHTING").
dico("Y", 8, "YACHTMAN").
dico("Y", 8, "YACHTMEN").
dico("Y", 8, "YAKITORI").
dico("Y", 8, "YASSAMES").
dico("Y", 8, "YASSASSE").
dico("Y", 8, "YASSATES").
dico("Y", 8, "YASSERAI").
dico("Y", 8, "YASSERAS").
dico("Y", 8, "YASSEREZ").
dico("Y", 8, "YASSEURS").
dico("Y", 8, "YASSEUSE").
dico("Y", 8, "YASSIONS").
dico("Y", 8, "YATAGANS").
dico("Y", 8, "YEARLING").
dico("Y", 8, "YEMENITE").
dico("Y", 8, "YEOMANRY").
dico("Y", 8, "YERSINIA").
dico("Y", 8, "YESHIVAS").
dico("Y", 8, "YESHIVOT").
dico("Y", 8, "YIDDISHS").
dico("Y", 8, "YODLAMES").
dico("Y", 8, "YODLASSE").
dico("Y", 8, "YODLATES").
dico("Y", 8, "YODLERAI").
dico("Y", 8, "YODLERAS").
dico("Y", 8, "YODLEREZ").
dico("Y", 8, "YODLIONS").
dico("Y", 8, "YOGHOURT").
dico("Y", 8, "YOGOURTS").
dico("Y", 8, "YONNAISE").
dico("Y", 8, "YOUPALAS").
dico("Y", 8, "YOUTSAIS").
dico("Y", 8, "YOUTSAIT").
dico("Y", 8, "YOUTSANT").
dico("Y", 8, "YOUTSENT").
dico("Y", 8, "YOUTSERA").
dico("Y", 8, "YOUTSIEZ").
dico("Y", 8, "YOUTSONS").
dico("Y", 8, "YOYOTAIS").
dico("Y", 8, "YOYOTAIT").
dico("Y", 8, "YOYOTANT").
dico("Y", 8, "YOYOTENT").
dico("Y", 8, "YOYOTERA").
dico("Y", 8, "YOYOTIEZ").
dico("Y", 8, "YOYOTONS").
dico("Y", 8, "YOYOTTAI").
dico("Y", 8, "YOYOTTAS").
dico("Y", 8, "YOYOTTAT").
dico("Y", 8, "YOYOTTER").
dico("Y", 8, "YOYOTTES").
dico("Y", 8, "YOYOTTEZ").
dico("Y", 8, "YPERITES").
dico("Y", 8, "YPRESIEN").
dico("Y", 8, "YTTRIQUE").
dico("Y", 8, "YTTRIUMS").
