dico("Z", 5, "ZABRE").
dico("Z", 5, "ZAINS").
dico("Z", 5, "ZAIRE").
dico("Z", 5, "ZAKAT").
dico("Z", 5, "ZAMAK").
dico("Z", 5, "ZAMIA").
dico("Z", 5, "ZANIS").
dico("Z", 5, "ZANNI").
dico("Z", 5, "ZANZI").
dico("Z", 5, "ZAPPA").
dico("Z", 5, "ZAPPE").
dico("Z", 5, "ZARBI").
dico("Z", 5, "ZARBS").
dico("Z", 5, "ZAZOU").
dico("Z", 5, "ZEBRA").
dico("Z", 5, "ZEBRE").
dico("Z", 5, "ZEBUS").
dico("Z", 5, "ZEINE").
dico("Z", 5, "ZELEE").
dico("Z", 5, "ZELES").
dico("Z", 5, "ZENDE").
dico("Z", 5, "ZENDS").
dico("Z", 5, "ZEROS").
dico("Z", 5, "ZESTA").
dico("Z", 5, "ZESTE").
dico("Z", 5, "ZIGUE").
dico("Z", 5, "ZINCS").
dico("Z", 5, "ZIPPA").
dico("Z", 5, "ZIPPE").
dico("Z", 5, "ZIZIS").
dico("Z", 5, "ZLOTY").
dico("Z", 5, "ZOIDE").
dico("Z", 5, "ZOILE").
dico("Z", 5, "ZOMBI").
dico("Z", 5, "ZONAI").
dico("Z", 5, "ZONAL").
dico("Z", 5, "ZONAS").
dico("Z", 5, "ZONAT").
dico("Z", 5, "ZONEE").
dico("Z", 5, "ZONER").
dico("Z", 5, "ZONES").
dico("Z", 5, "ZONEZ").
dico("Z", 5, "ZOOMA").
dico("Z", 5, "ZOOME").
dico("Z", 5, "ZOOMS").
dico("Z", 5, "ZOUKA").
dico("Z", 5, "ZOUKE").
dico("Z", 5, "ZOUKS").
dico("Z", 5, "ZOZOS").
